### ISSUE TITLE
SerialPort does not work on Windows

### ISSUE THREAD

**Issue by sensestage** [supercollider/supercollider#1008]
refactoring is needed anyways [1], and reimplementation using boost [2] will allow for portable code and finally make a version on Windows working

[1] https://github.com/supercollider/supercollider/issues/862
[2] http://www.boost.org/doc/libs/1_40_0/doc/html/boost_asio/overview/serial_ports.html

**Comment by scztt** [comment]
@timblechmann what's the status on this?

**Comment by timblechmann** [comment]
i'm not using serial devices, so i only provided the basic infrastructure. someone with interest in serial devices will need to check the FIXMEs and test the code.

**Comment by sensestage** [comment]
Hiho,

when things quiet down a bit with current projects, I could look into
this. But that would not be before mid april.

sincerely,
Marije

**Comment by brianlheim** [comment]
I've begun work on preparing @timblechmann 's branch for a PR. I'm familiar with using serial port interfaces in software but not so clear on how it works in detail, so I'm going slowly and carefully. I'm using `socat` for quick testing (and similar utilities exist on Windows) but if anyone has better ideas on how to test (i.e., using mocks), I'm all ears.

**Comment by LFSaw** [comment]
if closing this, make sure to remove the remark in `README_WINDOWS.md`
