### ISSUE TITLE
Duplicate Document class when both IDE and scel are installed

### ISSUE THREAD

**Issue by mortuosplango** [supercollider/supercollider#1014]
As 5033eb36f77428a5734ff00df04a2ec1af8367b6 moves the Document class into the scel directory, it's not possible to use both in parallel anymore it seems.

**Comment by jamshark70** [comment]
Pinging this issue. editors/scel/README.md confidently states:

```
SuperCollider files are put in

`$prefix/share/SuperCollider/Extensions/scel`
```

But, we've known for over three years, as Marije pointed out, that it should be `$prefix/share/SuperCollider/Extensions/scide_scel`.

This has tripped up a user who posted on Facebook about being unable to use ScIDE after installing scel.

**Comment by brianlheim** [comment]
@jamshark70 Thanks for pinging -- could you open a PR? If it's just a matter of changing that line I can do it myself.

**Comment by jamshark70** [comment]
I don't know if it's only that. I can confirm that copying the class files under scide_scel avoids the duplicate class when running from ScIDE. My old scel configuration is far out of repair, so I'm not able to test right now whether anything else is needed (although the user on Facebook says that this was the only thing wrong).

**Comment by widp** [comment]
This issue was moved to supercollider/scel#3
