### ISSUE TITLE
plugins - Env with \hold seems to be broken

### ISSUE THREAD

**Issue by miguel-negrao** [supercollider/supercollider#1027]
{ WhiteNoise.ar * Env([0,1],[3], \hold).ar * 0.01 }.play

Warning the above will cause loud burst of noise. With this one we get randomly either a burst of white noise or a silence. The expected behaviour for me would be 3 seconds of silence followed by the white noise.

    { WhiteNoise.ar * Env([0,1,1],[3,3], \hold).ar * 0.01 }.play

This on the other hand works the first time it's run after booting the server, and then running it again will just ouput the white noise without any silence...

**Comment by sonoro1234** [comment]
Now is it ok?

**Comment by vivid-synth** [comment]
This seems to be fixed on my machine (and is very similar to https://github.com/supercollider/supercollider/issues/1124)
