### ISSUE TITLE
SCIDE needs to escape quotes in strings submitted to "openHelpFor"

### ISSUE THREAD

**Issue by jamshark70** [supercollider/supercollider#1036]
I accidentally had a block of code selected when I hit ctrl-D to open the help browser (first time in the session). The browser window opened and said "Sending request..." but it never got as far as scanning the help files because:

```
ERROR: syntax error, unexpected NAME, expecting ')'
  in file 'selected text'
  line 1 char 43:

  HelpBrowser.openHelpFor("w = Window("window name", Rect(600, 200, 300, 120));
z = EZSlider(w,
    bounds: Rect(5, 5, 290, 20),
    label: "freq",
    controlSpec: [110, 880, \exp],  // short form OK
    action: { |view| ~sound.set(\freq, view.value) },
    i
                                       ^^^^^^
-----------------------------------
ERROR: Command line parse failed
```

SCIDE plugs in the entire string without escaping the quote marks in it.

User impact is: If SCDoc hasn't been initialized, the help browser is useless without at least recompiling the class library. In my case, I did recompile, but the help browser was still non-functional. I had to quit SCIDE and relaunch.

**Comment by brianlheim** [comment]
This allows for a fun injection attack. Select the whole thing and Cmd-D:
```supercollider
" ++ "open /".unixCmd ++ "
```
