### ISSUE TITLE
SCIDE: allow setting line-height (feature request)

### ISSUE THREAD

**Issue by bagong** [supercollider/supercollider#1050]
In some cases it would be nice to have an option to set line height. Users might have different taste preferences as to how narrow or generous they want code to display. There could also be more technical requirements: somebody (I ;)) might want to use custom fonts that contain glyphs outside of the default line height. These are currently invisible in the editor.

**Comment by brianlheim** [comment]
Closing for now, but added [here](https://github.com/supercollider/supercollider/projects/3).
