### ISSUE TITLE
keyDown in QtGUI doesn't pass char as indicated for non-printing chars

### ISSUE THREAD

**Issue by muellmusik** [supercollider/supercollider#1081]
The help says: "In Qt GUI only printable characters are passed. If a key is not associated with any printable character, nil will be passed instead."

This is not the case. Key's such as shift and alt are passed a char with ascii 0, not nil.

```~slid = Slider().front;
~slid.keyDownAction = {|view, char, mod, unicode| char.asCompileString.postln; char.class.postln; unicode.postln }```

This should be fixed or the doc changed (not sure which).

**Comment by scztt** [comment]
It's easiest to fix this in View:keyDownEvent by simply doing:
`if (char.ascii == 0) { char = nil };`

**Comment by jamshark70** [comment]
Necrobump, but having just been doing some programming with TextView and key actions, I can say that in practice, this change is a very very annoying PITA. I think I argued such on the mailing list, but I was voted down.

I still disagree very strongly with this.
