### ISSUE TITLE
Pspawn relies on event pseudo methods, which is risky

### ISSUE THREAD

**Issue by telephon** [supercollider/supercollider#1084]
This is a risky implementation:

```
case
                { event.method == \wait } {
                    event.spawner.wait(event.delta)
                }
```

If some extension implements e.g. `Object:method`, Pspawn will break.

To fix this, we can use a direct lookup `event[\method]` but in order to make it fully backward compatible, it would have to be:

```
method = event[\method];
method !? { method = method.functionPerformList(\value, event) }
```

I am not sure if the second line is necessary, this depends on usage.

**Comment by snappizz** [comment]
fixed #4036
