### ISSUE TITLE
Incorrect window position with multiple displays and negative x value

### ISSUE THREAD

**Issue by acarabott** [supercollider/supercollider#1090]
This is with a second display set up to the left of the primary display

    w = Window("wrong", Rect(-800, 500, 200, 400)).front; 
    // appears at Rect(320, 500, 200, 400);
    w.bounds.postln; // Rect(-800, 500, 200, 400);
    w.bounds = Rect(-800, 500, 200, 400); // moves to correct position

Humorously you can also do `w.bounds = w.bounds;` and get the correct position

OS X 10.9.2
SC 3.6.6

**Comment by scztt** [comment]
Retest after qt5 merge.

**Comment by acarabott** [comment]
Fixed, nice.
