### ISSUE TITLE
No implementation of "Preferences" in Cocoa application

### ISSUE THREAD

**Issue by ledhed2222** [supercollider/supercollider#1098]
(Enhancement request) I find it hard to believe this hasn't been requested before, but I can't find an open issue for this. If this is indeed a dup, shame me and close me :(

It would be nice to implement a simple "Preferences" in the OS X client. In that view, users could define default .scd fonts and other startup file stuff. Mainly I want my default to be larger without editing the startup file. I'm lazy!

**Comment by crucialfelix** [comment]
I vote to close this
