### ISSUE TITLE
MIDI device UID is off-by-one for incoming messages in Windows

### ISSUE THREAD

**Issue by jamshark70** [supercollider/supercollider#1106]
MIDIClient.init;
    -->
    MIDI Sources:
    	MIDIEndPoint("MK-361C USB MIDI keyboard", "MK-361C USB MIDI keyboard")
    
    MIDIClient.sources.do(_.dump);
    -->
    Instance of MIDIEndPoint {    (0x511efb0, gc=10, fmt=00, flg=00, set=03)
      instance variables [3]
        device : "MK-361C USB MIDI keyboard"
        name : "MK-361C USB MIDI keyboard"
        uid : Integer 0
    }
    
    MIDIFunc.trace(true);

Then play a note on the keyboard.

    MIDI Message Received:
    	type: noteOn
    	src: 1
    	chan: 0
    	num: 61
    	val: 127

`uid` in the MIDIEndPoint is 0, but the incoming message reports `src` as 1. I've seen this on another machine, with multiple MIDI devices, and `src` is always 1 greater than the correct number.

Something in SC_PortMidi.cpp, I guess, but I don't have time to look now.

**Comment by llloret** [comment]
I think this working ok now, at least on my setup, with my branch `llloret:midi_fix_win`, which is on PR #2009.

**Comment by llloret** [comment]
This should be working on 3.7.2.

**Comment by bagong** [comment]
Thanks!
