### ISSUE TITLE
Help Browser: Add convenience keys for maneuvring Help Browser

### ISSUE THREAD

**Issue by dvzrv** [supercollider/supercollider#1112]
It would be most awesome to also be able to scroll and move around in Help Browser using additional keys like:

j - down
k - up
/ - search/find
ctrl + k - jump to quick search
alt + cursor left - back one page (if there's one)
alt + cursor right - forward one page (if there's one)

I don't see these keys collide with any other settings.
Can it be done? If so, how?
Let me know, if I can be of any help!

**Comment by brianlheim** [comment]
down - space
up - shift+space
search/find - cmd+F
forward/back as given here: https://doc.qt.io/archives/qt-4.8/qkeysequence.html
jump to quick search - I'm not sure what this means, but the current search capabilities seem to be OK.

Closing this as fixed.
