### ISSUE TITLE
Cursor jumps to the wrong split after dismissing the Find panel

### ISSUE THREAD

**Issue by jamshark70** [supercollider/supercollider#1115]
Steps to reproduce:
1. Open some document.
2. Split the code window.
3. Put the cursor in the right-hand or lower split (depending on whether you did "split to right" or "split to bottom").
4. Ctrl-F and search for anything.
5. Then hit Esc.

At this point, at least in my build, the cursor jumps into the left/top split. Also, the search highlighting in the other split does not disappear.

The issue does not happen if the cursor is in the left/top split when you do Find. So it seems that the logic to close tool panels assumes that the cursor was in split index 0.

I am on:

commit b629767edd16fca0c1d62567f35ce6b62ce4dd4c
Author: Julian Rohrhuber jrhb@users.sourceforge.net
Date:   Tue May 20 17:55:04 2014 +0200
Revert "Merge branch 'bounded-control'. This fixes #1037."

**Comment by brianlheim** [comment]
Can someone else test? This is no longer an issue for me (macOS 10.11, 3.9)

**Comment by telephon** [comment]
I can't reproduce it anymore either.

**Comment by brianlheim** [comment]
@jamshark70 Feel free to reopen if you can find reproducing conditions.

**Comment by vivid-synth** [comment]
The best kind of bug!
