### ISSUE TITLE
(unnecessary?) warning "The HID scheme 'nil' is not installed"

### ISSUE THREAD

**Issue by telephon** [supercollider/supercollider#1120]
On startup, sclang tries to load the GeneralHID spec: 
`GeneralHID.fromID( this.platform.defaultHIDScheme );`
It is not clear whether this is really necessary; in any case, it posts a warning:

```
WARNING: GeneralHID.fromID : The HID scheme 'nil' is not installed
The current scheme is still 'nil'!
RESULT = 0
```

Should the call just be removed and happen on demand?

**Comment by sensestage** [comment]
fully fixed in pull request #1573
