### ISSUE TITLE
Env hold shape fails erratically

### ISSUE THREAD

**Issue by telephon** [supercollider/supercollider#1124]
````
{ WhiteNoise.ar * EnvGen.ar(Env([0,1],[3], \hold)) * 0.01 }.play
````

>on the first time It's run after booting the server it will output 3 seconds of silence followed by the white noise, after that, every time I run it again it will just output the white noise without any silence...

Same here.

**Comment by sonoro1234** [comment]
Should be closed hold should be step and output always1

**Comment by sonoro1234** [comment]
Ohh, I was in 3.6, I have seen hold in 3.7 but it works ok now.

**Comment by vivid-synth** [comment]
This seems to be fixed (always outputs 3 seconds of silence then whitenoise)
