### ISSUE TITLE
Buffer allocMsg doesn't work

### ISSUE THREAD

**Issue by mondaugen** [supercollider/supercollider#1125]
Apologies if this has already been reported, I took a look and found only this thread (maybe that problem is related): https://github.com/supercollider/supercollider/pull/772

For me, even evaluating with "long" pauses between each command (according to the above issue this is not currently possible any other way) this code:

s.boot;
b = Buffer.new(s, 44100);
b.query;
s.sendBundle(nil,b.allocMsg);
b.query;

posts this result:

localhost
Buffer(0, 0, 0, 0, nil)
bufnum      : 0
numFrames   : 0
numChannels : 0
sampleRate  : 0

Buffer(0, 0, 0, 0, nil)
bufnum      : 0
numFrames   : 0
numChannels : 0
sampleRate  : 0

numFrames should indeed be 44100 in the final query call, no?

This code was run on SuperCollider 3.7alpha0 built from the git repo. I had the same problem on the 3.6.5 release.

**Comment by telephon** [comment]
This seems to be working as documented, feel free to reopen if necessary.
