### ISSUE TITLE
alt+tab window doesn't respond to keyboard events once open.

### ISSUE THREAD

**Issue by scztt** [supercollider/supercollider#1137]
This is probably the same problem as several other dialog / dialog-ish windows (i.e. Look up implementation) have had in qt5.

**Comment by bagong** [comment]
I think you fixed this yourself. Anyways it seems to work properly now...

**Comment by brianlheim** [comment]
Fixed for me too. @scztt can you recreate now?

**Comment by brianlheim** [comment]
Closing, this is probably another out-of-date Qt5 thing. Please reopen if you can recreate @scztt.
