### ISSUE TITLE
Qt5 branch in Ubuntu exhibits some seriously weird behavior

### ISSUE THREAD

**Issue by jamshark70** [supercollider/supercollider#1138]
For tracking purposes, I'd like to report some strange behavior that I saw with the qt52 branch in Ubuntu 12.04 using the Unity 2D shell.

1. Installed Qt5 from ppa:ubuntu-sdk-team/ppa.
2. Built SC (qt52 branch).
3. Ran scide.

Weird sh!! that happened:

- My IDE configuration file specifies that the help browser should be detached, and not opened at startup. Instead, the qt52 branch opened a window for the help browser but failed to load an HTML document into it. The window was inactive -- nothing was ever painted into it -- and the close/minimize buttons didn't do anything. The window was just stuck there until I hit ctrl-d to load the main help page; after that, it behaved normally. So that's two bugs: 1/ Don't open a help browser window if sc_ide_conf.yaml says it should be closed and 2/ make sure it can always respond to window-manager commands, even if something goes wrong while loading content.

- While testing different combinations of attached/detached help browser, and open or closed at startup, at some point the Unity 2D menu bar disappeared and I couldn't open any application menus. Also the Unity launcher and dash stopped appearing and stopped responding to hotkeys. The only thing I could do was to log out using Ctrl-Alt-Del. After a reboot, the menubar, launcher and dash were usable, but there was one lasting side effect: the launcher's auto-hide feature stopped working (and it still isn't working). The launcher is always visible, despite auto-hide being enabled.

For the latter, I can imagine a couple of possibilities:

- Installing qt5 messed around with one of the window manager libraries, which broke auto-hide, and I didn't see the effect of that until after the reboot.

- Or, scide or sclang did something that messed up metacity (Unity 2D's graphics engine). It's quite disturbing to contemplate the implications of user-level code that can corrupt part of the operating system.

I'm willing to run other tests later on, but first, I'd like to get more information from the Ubuntu community to be sure that I can work my way back to a fully functioning system before I risk running sc/qt5 again. (It's cost me pretty much all of today's work time to get my system back to where I can use it and run SC -- that's not to blame anybody, just explaining why I'd rather not try the qt52 branch again, not too casually anyway.)

**Comment by bagong** [comment]
Any reason to keep this open, James? The situation has quite changed. 14.04 is the new lt-support release of Ubuntu, ships with Qt5.21 and I don't observe what you describe any more, even on Unity. Okay to close?

**Comment by jamshark70** [comment]
Rebuilt with current master, no more problems. Closing.
