### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [supercollider/supercollider#1153]
I would like to point out that identifiers like "[`_SC_StandAloneInfo_`](https://github.com/supercollider/supercollider/blob/a22cb3ff1609c0b00482af44e068751aec44d6ad/common/SC_StandAloneInfo_Darwin.h#L3)" and "[`_SCDOCPRIM_H_`](https://github.com/supercollider/supercollider/blob/a22cb3ff1609c0b00482af44e068751aec44d6ad/SCDoc/SCDocPrim.h#L1)" [do not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL32-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL32-CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29) to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by vivid-synth** [comment]
It looks like that link is dead; I think the new version is: https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier

**Comment by geoffroymontel** [comment]
I can't find either `_SC_StandAloneInfo_` nor `_SCDOCPRIM_H_` in the code base.

```bash
geoffroy ~/dev/supercollider (develop) $ find . -type f -exec grep _SC_StandAloneInfo_ {} \;
geoffroy ~/dev/supercollider (develop) $ find . -type f -exec grep _SCDOCPRIM_H_ {} \;
geoffroy ~/dev/supercollider (develop) $ 
```

I think we can close this issue !

**Comment by brianlheim** [comment]
yes! i have actually been searching for this one for a long time. most of them are gone now that we use pragma once everywhere. there may still be some places where we use reserved identifiers. i would double check to make sure.

**Comment by snappizz** [comment]
#3781 seems to have resolved this -- reopen if you find any more!
