### ISSUE TITLE
UGen Development: Misleading error message when omitting entry point

### ISSUE THREAD

**Issue by carlocapocasa** [supercollider/supercollider#1157]
Reproduction:
1. Place the contents of the [C++-side Definition of Unit Generators](http://doc.sccode.org/Guides/WritingUGens.html#C++-side%20Definition%20of%20Unit%20Generators) in `sc3-plugins/source/MySawUGens/MySaw.cpp`
2. Comment out the following portion
   //PluginLoad(PlayST)
   //{
   //    ft = inTable;
   //    DefineSimpleUnit(PlayST);
   //}
3. Add `MySawUGens` to `Source/CMakeLists.txt`, and build:
   
   mkdir build
   cd build
   cmake ..
   make MySawUGens
   cp source/MySawUgens.so /usr/lib/SuperCollider/plugins
4. Start the server
   
   s.boot;

Expected behavior: An error message reports that MySawUGens.so does not contain an entry point (preferred) or that MySawUGens.so is not a valid UGen library

Actual behavior: The following error is reported:

```
*** ERROR: API Version Mismatch: /usr/lib/SuperCollider/plugins/MySawUGens.so
```

**Comment by snappizz** [comment]
#3138 fixed this.
