### ISSUE TITLE
DiskIn channel limitation

### ISSUE THREAD

**Issue by ericlyon** [supercollider/supercollider#1162]
Recent tests indicate that DiskIn cannot read a sound file with more than two channels. Please see this posting for more details: 

http://new-supercollider-mailing-lists-forums-use-these.2681727.n2.nabble.com/DiskIn-channel-limitations-td7612705.html

**Comment by scztt** [comment]
Sounds from the email thread like the repro on this was intermittent. This is a pretty severe bug, so it would be nice to smoke this out before 3.7.

**Comment by bagong** [comment]
I think it's fixed in 3.7. The fix (by Tim) wasn't backported correctly to 3.6. See:
http://new-supercollider-mailing-lists-forums-use-these.2681727.n2.nabble.com/SuperCollider-3-6-6-td7612740.html#a7612766

**Comment by scztt** [comment]
Sweet! Closing!
