### ISSUE TITLE
keyToDegree is not inverse of degreeToKey

### ISSUE THREAD

**Issue by triss** [supercollider/supercollider#1163]
The SimpleNumber docs state that keyToDegree is the inverse of degreeToKey.

If you execute the following you can see that it isn't:
`(0..12).keyToDegree(Scale.major).degreeToKey(Scale.major)`
keyToDegree talks about sharps and flats in terms of being + or - 0.5

degreeToKey talks about sharps and flats as being + or - 0.1

**Comment by brianlheim** [comment]
API changes like this are not in the current dev path, and from the discussion at #1164 this is going to be fairly controversial when we do get to it. Closing, but saved [here](https://github.com/supercollider/supercollider/projects/6).
