### ISSUE TITLE
Keyboard-shortcuts that contain right or left arrow are not persistent across sc restart

### ISSUE THREAD

**Issue by bagong** [supercollider/supercollider#1170]
Maybe Mac-specific:
I you define a key-combo in shortcut-preferences that contains arrows (left, right...), SC/Qt generates a funny symbol to represent it in the shortcut list. This is stored in sc-ide.yaml. On restarting SC this funny symbol is not retranslated correctly and the key-combo does not work any more. Manually editing the sc-ide.yaml (replace funny symbol by "right" etc works around this locally)

**Comment by scztt** [comment]
@bagong - this seems fixed in recent builds. can you retest?

**Comment by bagong** [comment]
> On 14 Mar 2015, at 22:56, scztt <notifications@github.com> wrote:
> 
> @bagong <https://github.com/bagong> - this seems fixed in recent builds. can you retest?
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/supercollider/supercollider/issues/1170#issuecomment-80752682>.
> 
I’ve also noticed that this isn’t the case anymore. I had forgotten that I had a pending bug-report.
.r.
