### ISSUE TITLE
drawAtPoint primitive fails if Font not installed

### ISSUE THREAD

**Issue by jleben** [supercollider/supercollider#119]
[Issue migrated from SourceForge | ID: 2963417 | Submitted by 'nobody']
[http://sourceforge.net/support/tracker.php?aid=2963417]

osx 10.5.8
a minor annoyance.  expected behaviour: post warning and fall back on default/current font.
or better - SCFont class could warn if font not installed.

(
w = Window.new.front;
w.drawHook = {
"abc".drawAtPoint(
100@100,
Font("XXXX", 9), //primitive breaks here if font not installed
Color.blue(0.3, 0.5)
)
};
)

ERROR: Primitive '_String_DrawAtPoint' failed.
Failed.
RECEIVER:
Instance of String {    (0D0A1190, gc=80, fmt=07, flg=10, set=01)
  indexed slots [3]
      0 : a
      1 : b
      2 : c
}
CALL STACK:
MethodError:reportError   0CF27B10
arg this = <instance of PrimitiveFailedError>
Nil:handleError   0CF28050
arg this = nil
arg error = <instance of PrimitiveFailedError>
Thread:handleError   0CF27CF0
arg this = <instance of Thread>
arg error = <instance of PrimitiveFailedError>
Object:throw   0CF264B0
arg this = <instance of PrimitiveFailedError>
Object:primitiveFailed   0CF26770
arg this = "abc"
SCWindow:callDrawHook   0CF2A550
arg this = <instance of SCWindow>

**Comment by scztt** [comment]
No failure in Qt. Closing.
