### ISSUE TITLE
scvim extension installed to systemAppSupportDir on OSX

### ISSUE THREAD

**Issue by bagong** [supercollider/supercollider#1199]
scvim-extension tries to install to `/Library/Application Support/SuperCollider/Extensions/scvim`
- that is non standard, everything else I am aware of goes to the `userAppSupportDir`
- it requires admin-privileges
- somehow this path is set in a non-standard way, as I bumped into the problem when trying to build a standalone with a different bundle-name. If constructed correctly, above path should use the bundle-name rather than "SuperCollider"

**Comment by scztt** [comment]
Is there any need to install this in a system-wide place? Especially considering this will be non-functional on a manage system, where the user doesn't have admin access.....

**Comment by timblechmann** [comment]
imho scvim (and scel) should be disabled by default, as they are not exactly well maintained.

**Comment by vivid-synth** [comment]
(can we add the "os: Mac OS X" label to this?)

**Comment by bagong** [comment]
I think this was fixed...
