### ISSUE TITLE
MIDI sysex is not implemented for Windows (SC_PortMIDI.cpp)

### ISSUE THREAD

**Issue by sensestage** [supercollider/supercollider#1200]
line 180 and onwards - sysex is commented out, I am not sure why.
In any case, should be fixed to make it working.

**Comment by scztt** [comment]
Who builds on windows and knows a little MIDI? .... [crickets]

**Comment by llloret** [comment]
What do people expect from sysex in SC? Is it just to send system data to external gear, or also to send days to SC itself?

**Comment by cougarten** [comment]
I guess most people want to push stuff on to devices, like loading samples, settings or operating modi.
For more advanced stuff people might also want it to read out settings, that can than be modified and send back.

I simply need a device to go in to debug mode to get raw sensor data of a midi-keyboard via CC messages.

**Comment by llloret** [comment]
@bagong, or someone else, do you have a way to test SysEx out? I think I have something that might be working, but I am not sure if the gear I have will do something visible when getting SysEx.

**Comment by llloret** [comment]
Well, perhaps I can use the microKontrol for that, I will check.

**Comment by bagong** [comment]
I am really stupid in this, but if you send me sample code, I can run it and try. I just built an hour ago, can rebuild if you just committed a minute ago. I have two midi keyboards and a soundbank-player (not sure how to call them), a Roland Mobile Studio Canvas SD 50, if that's of any use...

**Comment by cougarten** [comment]
microKontrol sysex docs: http://c3.zzounds.com/media/microKONTROL_MIDI-b94472c24a3cc0141735bc3aa3d5c4ab.pdf

**Comment by llloret** [comment]
@bagong, I have just committed. I will try to test it tonight at home if I have time. I think it is probably better for you to work on the other stuff that we have going, and let the people that really use the SysEx do some testing when we cut a test version. It's up to you, of course.

I will try to do some basic SysEx testing with the doc that @cougarten sent, at least to not publish something that does not work at all.

Is that ok?

@cougarten, thanks for the doc.

**Comment by bagong** [comment]
Great!

**Comment by llloret** [comment]
@bagong, I have tested the SysEx out on my side with the microKontrol keyboard, and it seems to be working ok. I was able to change the configured scene using SysEx. This is already in the PR.

**Comment by bagong** [comment]
Great news!

**Comment by llloret** [comment]
Hi, @bagong, I have just committed an initial implementation of SysEx input as well. I have done some very basic testing with my loopback device and it seems ok.

With that, as you suggest, we can start having people test it.

Just make everyone aware that it has gone through very basic testing, very very basic ;).

**Comment by llloret** [comment]
I had not pushed the change for the SysEx input, sorry. I have done it just now.

**Comment by bagong** [comment]
No worries. I am still hoping for a good idea on that shutdown from IDE, so haven't built again yet...

**Comment by llloret** [comment]
This should be working on 3.7.2

**Comment by bagong** [comment]
Thanks!
