### ISSUE TITLE
FFT: double cpu on 3.7a0 vs 3.6.6

### ISSUE THREAD

**Issue by redFrik** [supercollider/supercollider#1202]
as discussed in this thread... https://www.listarc.bham.ac.uk/lists/sc-dev/msg52888.html
there are extras (BufFrames and PV_Copy) introduced by PV_ChainUGen:addCopiesIfNeeded and that can make fft perform much worse under sc3.7a0.

reference: https://github.com/supercollider/supercollider/commit/15ff964d669c41addfd4affb41eca083b3144c9b

**Comment by vivid-synth** [comment]
Agh! bham list archives seem to have renumbered their messages -- that message is no longer active. In fact, the most recent message has a number that's 2,000 lower than 52888.

Here's the original message:
http://new-supercollider-mailing-lists-forums-use-these.2681727.n2.nabble.com/double-cpu-on-3-7a0-vs-3-6-6-fft-td7613892.html

And here's where it should appear, but **seems not to!** (Oct 9th, 2014) : https://www.listarc.bham.ac.uk/lists/sc-users-2014/mail11.html

**Comment by brianlheim** [comment]
We're well past 3.7.0a. This should be reevaluated and a new issue logged with more info if it still applies.
