### ISSUE TITLE
help-installation broken - possibly under Linux only

### ISSUE THREAD

**Issue by nuss** [supercollider/supercollider#1218]
I'm on Linux. Commit f31909c6a31c7770bcf0c56ffee6b25bf740812f seems to have broken the installation of help-files belonging to the default class-lib (classes from extensions don't seem to be affected). In particular, since that commit was a merge, I guess it happened in b6b3dc77680245244c0010c51da08a8cfc3f46cd 

When executing
`$ ls /usr/local/share/SuperCollider/HelpSource/Classes`
I get 0 files. Hence, all classes within the default class-lib appear as 'undocumented'.

**Comment by scztt** [comment]
@nuss - can you confirm this is fixed after qt5 merge?

**Comment by bagong** [comment]
I have two additional little changes related to this PR which I am currently trying with a Windows build. For some reason my mod (NOT APPLE) doesn't work on Windows. If that get's committed it might be good to try on Linux. I've tested it for OS X already.

**Comment by bagong** [comment]
Confirmed.
