### ISSUE TITLE
SuperCollider as a VST/AU plugin host

### ISSUE THREAD

**Issue by LFSaw** [supercollider/supercollider#1251]
How difficult would it be to implement VST / AU host functionality into supercollider?
E.g. something like VST buses (you send audio there, it gets processed by plugins, and you can grab it in the next cycle...)
or VST UGens (having (multichannel) audio input, an array of strings identifying the plugins and their order, and a (multichannel) output)
Maybe a plugin interface a la LADSPA-UGens for SuperCollider?

See also the discussion on FB:

<div id="fb-root"></div> <script>(function(d, s, id) { var js, fjs = d.getElementsByTagName(s)[0]; if (d.getElementById(id)) return; js = d.createElement(s); js.id = id; js.src = "//connect.facebook.net/en_GB/all.js#xfbml=1"; fjs.parentNode.insertBefore(js, fjs); }(document, 'script', 'facebook-jssdk'));</script>
<div class="fb-post" data-href="https://www.facebook.com/groups/supercollider/permalink/10152756729929533/" data-width="466"><div class="fb-xfbml-parse-ignore"><a href="https://www.facebook.com/groups/supercollider/permalink/10152756729929533/">Post</a> by <a href="https://www.facebook.com/LFSaw">Till Bovermann</a>.</div></div>

**Comment by snappizz** [comment]
This isn't going to happen any time soon, sorry.

**Comment by vivid-synth** [comment]
(Note to the reader: the GPL VST compatibility issue Tim referenced has recently gone away. Still a large project, though!)

**Comment by scztt** [comment]
If there's some commitment from SC devs to work on VST support, it might be worth seeing if @sinosoidal can lend some time and consultation to help get things rolling. His (slick as hell) synth is QT based (looks like statically compiled qt 5.8?) and runs as a VST.

**Comment by jarmitage** [comment]
FWIW I would love to see this happen

**Comment by sinosoidal** [comment]
@scztt, I don't have much time but this is an interesting project. I have never tried supercollider and how it works. From my basic knowledge supercollider runs as a separated process. Is it possible to run an instance of supercollider as code?

**Comment by miguel-negrao** [comment]
Olá Nuno :-),

You can compile the audio server component as a static or dynamic library (libscsynth) which you can then link from other code.

**Comment by LFSaw** [comment]
Hello Nuno,

just chiming in here to provide an outline on what I think is the minimal feature set:

I think it'd be cool to have a very basic system for an scsynth in which it acts from the supercollider side as an scsynth process (i.e. with its common OSC interface) and is a VST filter object for the VST host (2 in 2 out) We would need to be able to set (and save within the VST host settings) parameters such as OSC in and out port.


If we get this functionality _reliably_ working such that it can be compiled from sources by anyone with the needed libraries (supercollider git sources + dependancies, JUCE, VST), this woul dbe a _big_ step forward (essentially sidestepping unreliable and cumbersome audio-rerouting via jackosx/soundflower/RME loopback device).


2c
	Till

**Comment by sinosoidal** [comment]
if you guys help me shortcutting the essential, as linking with scsynth and how to make something work, might consider contributing to this integration. I think it would be awesome.

**Comment by LFSaw** [comment]
Hey there! Thanks @sinosoidal to chime in!
Unfortunately, I am not the right person to ask for C/C++ integration... I am able to write/adapt UGens but I don;t know how the actual linking process works.

@g-roma made a SuperColliderAU back in the days, AFAIK incorporating `libscsynth` (the core of the synthesis engine) into an AudioUnit.

I found this link that explains the way it works rather nicely.
http://www.mojolama.com/building-audio-units-supercolliderau-big-picture

Unfortunately, development of this stalled soon after its release for I don't know what reason...

**Comment by LFSaw** [comment]
Also, it might be worth looking into JUCE... 
@telephon mentioned @passivist 's tutorial on JUCE development on the sc-dev mailing list the other day:
https://github.com/passivist/GRNLR/wiki

**Comment by jarmitage** [comment]
If you're exploring JUCE as a potential workflow for this, it's worth noting that they have some pretty good tutorials and demo apps over at https://juce.com/tutorials e.g. https://juce.com/doc/tutorial_create_projucer_basic_plugin

**Comment by dyfer** [comment]
If anyone comes across this discussion: an external plugin for hosting VSTs was developed outside of the core SC: https://git.iem.at/pd/vstplugin/
