### ISSUE TITLE
UserView with drawFunc loops infinitely when resized by code 

### ISSUE THREAD

**Issue by adcxyz** [supercollider/supercollider#1274]
make a window
w = Window("test UserView resize by code").front;

// resizing it by hand is fine
w.bounds_(Rect(10, 500, rrand(200, 300), rrand(200, 300)));

// repeated resize is also fine
Tdef(\test, { loop { 
	w.bounds_(Rect(10, 500, rrand(200, 300), rrand(200, 300)));
	0.2.wait;
} }).play(AppClock);

// add an elastic user view, still fine
u = UserView(w, w.bounds.moveTo(0,0).insetBy(4, 4)).resize_(5);
u.background = Color.grey(0.8);

// add simplest drawFunc, and it goes spinning forever, blocking sclang.
u.drawFunc = { "boom".postln };

**Comment by telephon** [comment]
yes, can reproduce here. Maybe check with the qt5 branch?

**Comment by scztt** [comment]
Definitely cannot repro after qt5 merge - adcxyz, can you retest and close if you're not still seeing this? If you're not building, you can use: http://supercollider.s3.amazonaws.com/builds/supercollider/supercollider/osx/master-latest.html

**Comment by adcxyz** [comment]
just tested here, MBPro 2009, OSX 10.10.1:

works, no spinning beachball anymore - yay!

thanks, adc
