### ISSUE TITLE
TRand, TExpRand, TIRand are broken for audio-rate inputs

### ISSUE THREAD

**Issue by Sciss** [supercollider/supercollider#1278]
This is SC 3.6.5, not tested with SC 3.7 yet:

```
// kr -- ok
x = play {
  var p = Impulse.kr(1);
  var lo = \lo.kr(0);
  var hi = \hi.kr(1);
  var t = TRand.kr(lo, hi, p);
  t.poll(p, "rand");
  0
}

// ar -- moves towards hi and sticks to hi value
x = play {
  var p = Impulse.ar(1);
  var lo = \lo.ar(0);
  var hi = \hi.ar(1);
  var t = TRand.ar(lo, hi, p);
  t.poll(p, "rand");
  0
}
```

**Comment by Sciss** [comment]
Issue doesn't seem to be fixed. Original mcve still shows `TRand` sticking to higher values - scsynth 3.10.2 (Built from branch 'build-3.10.2' [834c036d3]).

According to [this forum thread](https://scsynth.org/t/tirand-not-in-range/), `TIRand` still affected as well.

**Comment by jamshark70** [comment]
For an audio rate UGen and audio rate trigger, do we expect lo and hi to be able to change at audio rate as well, or only at kr? The above proposed solution would support only the latter, but the forum user expected the former.

**Comment by telephon** [comment]
The plot looks ok:
```supercollider

(
{
  var p = Impulse.ar(4000);
  var lo = \lo.ar(0);
  var hi = \hi.ar(10);
  var t = TIRand.ar(lo, hi, p);
 t
}.plot(0.01)
)
```

<img width="512" alt="Screenshot 2021-02-05 at 14 54 47" src="https://user-images.githubusercontent.com/1810559/107042495-21019400-67c2-11eb-8834-54b1a8ee8479.png">

**Comment by Sciss** [comment]
that plot is way too short and uses a way too high frequency to show the problem. if you record longer (plot(1)) you'll see the bias. if you decrease the frequency below ControlRate, you see the bug

```supercollider
(
{
  var p = Impulse.ar(400);
  var lo = \lo.ar(0);
  var hi = \hi.ar(10);
  var t = TIRand.ar(lo, hi, p);
 t
}.plot(0.5)
)
```

![Screenshot from 2021-02-05 15-07-45](https://user-images.githubusercontent.com/131300/107043949-f1ec2200-67c3-11eb-8964-98629b36dcda.png)

**Comment by telephon** [comment]
I took a look, I am unsure, perhaps it is this?

https://github.com/telephon/supercollider/tree/topic/fix-aa-methods-of-triggered-rand

I currently can't build, because of these annoying code signing issues, so I can't test.
