### ISSUE TITLE
MultiSliderView.action_ not triggered by value changes via keyboard

### ISSUE THREAD

**Issue by eleses** [supercollider/supercollider#1285]
The documentation for MultiSliderView.action says "The action object evaluated whenever the user changes the value of a slider." I interpret that as changed by any user interaction, including keyboard action if is enabled, e.g. by setting step_. Unfortunately, only mouse clicks seem to trigger action_, even though the value[s] get changed just fine by up/down arrows with the keyboard. I experienced this with the Qt implementation. You can use the 2nd example from the help file to test this issue by adding one line, i.e. 

```
(
var size;
size = 350 / 6;
w = Window.new;
w.view.decorator = FlowLayout(w.view.bounds);
m = MultiSliderView(w, Rect(0, 0, 350, 100));   
m.value_(Array.fill(size, {0.01}));
m.isFilled_(true); // width in pixels of each stick
m.indexThumbSize_(2.0); // spacing on the value axis
m.gap_(4);
m.action_({|msv| msv.value.postln}); // added to test action
w.front;
)
```

Speaking of which, the comments in that example don't correspond to the lines after which they are added (off by one.)

A workaround can be made in user code as:

```
m.keyDownAction_({ arg msv, char, mod, uni, keycode, key;
	msv.defaultKeyDownAction(char, mod, uni, keycode, key);
	key.switch (
      QKey.up, { msv.doAction },
      QKey.down, { msv.doAction }
	)
});
```

**Comment by telephon** [comment]
>Unfortunately, only mouse clicks seem to trigger action_, even though the value[s] get changed just fine by up/down arrows with the keyboard.

This doesn't apply anymore in QT5, as key down actions do not change the values of the view. 
According to the documentation, ````defaultKeyDownAction```` should indeed work, but this is a new issue.
