### ISSUE TITLE
_String_Format primitive eats backslashes

### ISSUE THREAD

**Issue by jamshark70** [supercollider/supercollider#1291]
"abc %".format("def");
    --> abc def
    
    "a\\bc %".format("def");
    --> abc def

Further (even worse):

    "a\\\\bc %".format("def");
    --> abc def

But:

    "a\\bc " ++ "def"
    --> a\bc def

So, to get backslashes into formatted strings, you have to insert them by %. Doesn't make sense to me. It makes it that much harder to build regexps dynamically.

    "a%bc %".format($\\, "def");

**Comment by sofakid** [comment]
this may break a lot of regexes..
