### ISSUE TITLE
Disable tokenizing and auto-indent for schelp documents

### ISSUE THREAD

**Issue by jamshark70** [supercollider/supercollider#1292]
Here's a concrete case where you definitely don't want auto-indent while working on a help file.

    Here is some text. (Now, a parenthetical remark that's also including an apostrophe.)
    
    	And now, the next line gets indented. !!!???

The tokenizer considers the closing paren to belong to the symbol that started with the apostrophe. The opening paren is never closed, and this causes auto-indentation to force a tab at the beginning of all subsequent lines.

I suppose we could just mention in the SCDoc help files that it isn't properly supported to edit help files within the IDE (and you'd better use an external editor -- I'm going to have to pop over to emacs to write these helpfiles because the present situation is just too irritating), but... it would be a little embarrassing to have to admit that, right?

**Comment by timblechmann** [comment]
auto-indenting help-file violates the original design principles of the IDE: do it correctly or don't do it. 
imho, it should be disabled completely.

**Comment by miguel-negrao** [comment]
This is my fault, I proposed a pr some time ago without giving it much thought. Now I have to agree with Tim, better to do it right, so I have a pr for reverting the commit:

https://github.com/supercollider/supercollider/pull/1293

I compiled it here and seems to work fine.
