### ISSUE TITLE
drag and drop files to expand paths broken

### ISSUE THREAD

**Issue by telephon** [supercollider/supercollider#1295]
On OS X 10.10 (Yosemite) drag and drop files to expand paths broken. Instead, it returns an id like: ````"/.file/id=6571367.3523212/"````

**Comment by telephon** [comment]
Known issue, seems to be a QT bug.

**Comment by telephon** [comment]
Fixed in QT5

**Comment by telephon** [comment]
Just now, it happens again, on a build done with xcode.

**Comment by telephon** [comment]
Should be fixed in QT  5.4.1: https://bugreports.qt.io/browse/QTBUG-40449

**Comment by telephon** [comment]
OK, confirmed. Update QT.

**Comment by adcxyz** [comment]
just tested again on my pretty recent build, works fine.
