### ISSUE TITLE
GeneralHID documentation misleading

### ISSUE THREAD

**Issue by telephon** [supercollider/supercollider#1303]
The GeneralHID documentation says:

````
method::startEventLoop
Start the eventloop with a update rate (or rather update time in seconds).

note::
this is only really needed on MacOSX, but for crossplatform code you should include it in your code.
::
````

But the method isn't found on OS X.

**Comment by telephon** [comment]
Should the documentation be taken out or is the implementation incomplete?

**Comment by sensestage** [comment]
As the HID implementation is now replaced, GeneralHID is just a wrapper
for the remaining LID implementation (some devices are accessible by
LID, internal ones, but not by the new HID).
I started on removing the GeneralHID implementation in a private branch,
to move the necessary methods to LID, in case there are any that are in
GeneralHID, but were not available in LID directly.

Then more urgent projects came up again, and I was not able to finish it
any further...

But for this method - it can be removed.

**Comment by telephon** [comment]
There is still that branch around: https://github.com/supercollider/supercollider/compare/removing-general-hid

Is that taken out too much? It would be nice if we could somehow get HID clean and working for the next release - I don't have much stuff to test it with though.

**Comment by sensestage** [comment]
Hiho,

do we have a deadline for 3.7 now? (sorry, have been out of the loop for
a bit).

I started working on a branch that ports all useful functionality to
LID, so GeneralHID can be removed.

It would be nice to have that in, and GeneralHID removed.

When removing GeneralHID we should also remove the help files and
references to it in helpfiles (so its own helpfiles and the LID helpfile
has a reference).

It is unlikely that I can finish the work on porting stuff back to LID
this week.

sincerely,
Marije

**Comment by scztt** [comment]
Since this hasn't budged much and 3.7 is underway-ish, I would say: leave any big code churn (i.e. removing old GeneralHID things) until 3.8. If documentation can be amended to remove things that no longer exist, or are in a deprecated state, lets do that - it's also fine to leave the docs but simply mark them as deprecated, if there's some chance they might be of use (and as long as it won't confuse anybody).

**Comment by sensestage** [comment]
full removal is in pull request #1573
