### ISSUE TITLE
scsynth ought to print the version number when passed the --version flag

### ISSUE THREAD

**Issue by lpil** [supercollider/supercollider#1310]
Hello!

I believe that this would be a simple yet useful feature to have.

Cheers,
Louis

**Comment by Sciss** [comment]
With the client/server split, this could also allow a client (I'm thinking of course of ScalaCollider, Overtone, hsc3 etc.) to determine whether specific features are available, as there is indeed quite a few changes with the UGens across versions (mostly UGens are added, but also there are cases where UGens were removed in favour of pseudo-UGen code in the class library).

**Comment by blacksound** [comment]
`-v` is already used for verbosity, but `-V` is available.
Python also uses `-V` for version print.

Adding a PR with a simple solution.

**Comment by crucialfelix** [comment]
I've now noticed that -V is very common for version in lots of other common tools.

**Comment by crucialfelix** [comment]
Its -v now

**Comment by lpil** [comment]
Thank you!
