### ISSUE TITLE
Poll ignores initial trigger

### ISSUE THREAD

**Issue by jamshark70** [supercollider/supercollider#1312]
Here, Poll does not print anything.

    a = {
    	var trig = Impulse.kr(0);
    	Poll.kr(trig, trig);
    	FreeSelf.kr(trig <= 0);
    	Silent.ar(1)
    }.play;

But it does if you do this.

    a = {
    	var trig = Impulse.kr(0);
    	Poll.kr(DelayN.kr(trig, 0.01, ControlDur.ir), trig);
    	FreeSelf.kr(trig <= 0);
    	Silent.ar(1)
    }.play;

I think the problem is TriggerUGens.cpp, line 885, which initializes `unit->m_trig` to the trigger input's initial value. Here, the initial value is 1. As a result, when checking the trigger later, `lasttrig` and `trig` are both > 0, so nothing happens.

IMO `unit->m_trig` should be initialized to 0.

User impact: It's a PITA to test server calculations by polling in the first control block.

**Comment by telephon** [comment]
This works here (current master on os x):

````

(
a = {
    var trig = Impulse.kr(0);
	Poll.kr(trig, trig, "hello");
    FreeSelf.kr(trig <= 0);
    Silent.ar(1)
}.play;
)
````

posts:
````hello: 1````

**Comment by jamshark70** [comment]
Can close this... more tales from my old, messed-up local branch.
