### ISSUE TITLE
blocksize and latency in scsynth and supernova

### ISSUE THREAD

**Issue by sonoro1234** [supercollider/supercollider#1314]
Hello,

Currently scsynth and supernova portaudio behaves this way (may be also 
other audio drivers)

Both scsynth and supernova get the blocksize from -z option

But for latency:

scsynth uses -Z value if given or defaults to defaultLowOutputLatency (the 
lowest posible on portaudio)
supernova dont care about -Z and always uses defaultHighOutputLatency (the 
highest posible on portaudio)

the reason for using defaultHighOutputLatency is that is less error prone 
(which is a good reason)
the reason for using defaultLowOutputLatency is for having a responsive 
hardware in order to live-play music (another good reason)

I could change supernova behaviour to let it use -Z value but perhaps also 
add two negative values (ex: -1 and -2) one for defaultLowOutputLatency and 
the other for defaultHighOutputLatency.

Similar changes shoud be done in other drivers (which I dont know at all)

Any thoughts?
victor

**Comment by timblechmann** [comment]
unfortunately defaulting to "defaultLowOutputLatency" is a good way to achieve audio dropouts (especially on windows, but iirc also on with coreaudio). the default setting should avoid dropouts, but i'm happy to review a patch which exposes the -Z parameter for portaudio.

**Comment by sonoro1234** [comment]
Just created a pull request!!
I wish everything is ok
