### ISSUE TITLE
DiskIOUGens zoombies

### ISSUE THREAD

**Issue by sonoro1234** [supercollider/supercollider#1331]
It is an old issue:

On scsynth (or supernova) quit , DiskIOUGens gets blocked so progran has to be killed to terminate.
This happens in win32 and compiling with mingw-w64 32bit version

**Comment by timblechmann** [comment]
the code was written at a time, when resource cleanup was not yet invented

**Comment by sonoro1234** [comment]
Can this be fixed now?

**Comment by sonoro1234** [comment]
can be fixed with 
https://github.com/supercollider/supercollider/pull/1318 already merged and
https://github.com/supercollider/supercollider/pull/1445

**Comment by sonoro1234** [comment]
#1445 is not merged yet

**Comment by sonoro1234** [comment]
https://github.com/supercollider/supercollider/pull/1467 would fix now

**Comment by sonoro1234** [comment]
the work now has two possible PR

https://github.com/supercollider/supercollider/pull/1467
or
https://github.com/supercollider/supercollider/pull/1472


both of them solve program hangs and crash on win32, linux and macosx
the first one does plugin unload on scsynth and leave prepared for supernova
the second one reverts all the unloading plugins stuff

only one should be choosen and the opinion of everybody is important

**Comment by scztt** [comment]
@sonoro1234 - Can you retest in a build after #1456 was merged, and then close?

**Comment by sonoro1234** [comment]
#1456 is an issue about quiting scide , I cant compile that
This issue is about scserver and supernova alone. It is already tested and problem is solved
