### ISSUE TITLE
Make a homebrew formula (OS X) for supercollider

### ISSUE THREAD

**Issue by crucialfelix** [supercollider/supercollider#1335]
I've got this partly working. Will complete it after qt5 is merged to master.

It allows

```
brew install supercollider --HEAD
```

which builds from source

and for released versions (3.6.x) I think it will just download the tarball

**Comment by seansay** [comment]
:congratulations:

**Comment by crucialfelix** [comment]
note: it has to be after the 3.7 release as they will not allow non-stable releases.

**Comment by crucialfelix** [comment]
Its possible for us to just create a tap:  http://octavore.com/posts/2016/02/15/distributing-go-apps-os-x

The homebrew maintainer fussed pretty hard that it was a desktop app even though the formula was not installing the IDE at all.

**Comment by crucialfelix** [comment]
This is still one of my personal priorities. Would love to revisit this.  

Ideally we would make sclang only and scsynth only build targets first.

**Comment by bagong** [comment]
As you know the current build system is not well suited for the effort. And using bundles isn't well received by homebrew ;) As I see it work on this is in the waiting cue until the "path" reform is well established. That's not only relevant for the technicalities of file-system access, but also for questions like how sclang or scsynth find their affiliates, which in turn is important for the portability of executables (currently sclang and the servers build/install expecting to be part of the supercollider bundle)

**Comment by JordanHendersonMusic** [comment]
Closing because it seems to be there (haven't actually ran the command as I'm not on mac, but it is listed on the website).

`brew install --cask supercollider` 

https://formulae.brew.sh/cask/supercollider#default
