### ISSUE TITLE
help: News in 3.7

### ISSUE THREAD

**Issue by telephon** [supercollider/supercollider#1347]
Currently there is a "News in 3.6" file, linked from the main help browser. We should add a file for 3.7, any maybe link to a generated list of changes.

If we plan to make smaller more frequent releases, we could maybe just add a file "News".

**Comment by danstowell** [comment]
imho it's nice to have "News in 3.6" etc so people can refer back and catch up on news. If it was just called "News" then either the new would obliterate the old, or the file would become an unwieldy long changelog (as as `Changelog`!)

**Comment by telephon** [comment]
agreed ...

**Comment by crucialfelix** [comment]
Also this time we should list methods and classes that are new/deprecated/will-be-deprecated/removed

Breaking API changes are one of the most important things people want to know about

**Comment by telephon** [comment]
fixed by 7cf438efd3c3315990d15caa3e6f2f7268e14072
