### ISSUE TITLE
open config file …

### ISSUE THREAD

**Issue by telephon** [supercollider/supercollider#1358]
… would be a useful option in the preferences. Sometimes it's easier to just edit the file directly!

**Comment by bagong** [comment]
+1 - maybe a menu item like 'open startup file'. Especially on linux that should be useful. The file is in a hidden folder that no mere mortal will ever find (on Ubuntu user-support files are in .local/share/Super...., whereas the config-files are in .config/SuperCollider...). Virtually unfindable and not accessible from a file-picker dialogue.

**Comment by jamshark70** [comment]
I would go with Julian's original idea of a button in Preferences. Since the IDE in 3.7 supports multiple language config files, the place to open a config file would be the place that exposes them for selection.

Unless... maybe Julian is talking about language config files while Rainer is talking about the IDE config? Who knows... imprecise comments at this late stage of 3.7 preparation are awfully helpful *wink*

**Comment by scztt** [comment]
There's a distinction here -
- to be able to SELECT AND USE any sclang config file from the IDE
- to be able to OPEN AND EDIT your current sclang config from the IDE

I think this is for the latter. The first seems quite necessary, and the second very useful.

**Comment by jamshark70** [comment]
It's clear to me that the enhancement is to be able to open and edit. My comment is about where in the interface this should go. It would not make sense to put the open/edit command in the file menu, while the config file chooser is in the preferences panel.

Oh, oops... Preferences is a modal dialog... that creates a workflow problem: open preferences, click the button to open the config file, then close preferences to edit. The file menu workflow is not necessarily better: open preferences, choose the config file, close preferences, then use the file menu command. Both ugly. Maybe that's a reason why nobody added this before.

**Comment by scztt** [comment]
Adding an action to the file menu seems acceptable for the time being. You can already edit every available parameter of the sclang config from in the preferences dialog, so if it's just a matter of convenience, that already solves it.

Moving forward, I'm not sure the sclang config should really be in the Preferences at all. Its misleading - if you deleted an sclang file, it's certainly not stored by the IDE and those settings would be lost. It would be nice, in the future, if there was separate IDE functionality (a docket?) to list sclang configs, edit them, launch an sclang process with them, and quickly assemble a new one by picking quarks / extensions or cloning from an existing.

**Comment by telephon** [comment]
>Adding an action to the file menu seems acceptable for the time being. 

yes.

I meant the IDE preferences, but the current language config file would also be useful.

Perhaps on the long run, a customizable menu would allow us to experiment with such things better and then take those which are really useful. 

I suppose that it would anyhow be better if the IDE would call sclang functions instead of sending code to the interpreter, but that is another issue to discuss.

**Comment by bagong** [comment]
Yea, pretty deep, actually. Should be thought together with the new Quarks system. I think Felix is moving in our direction from the other side. He integrates non-quark include paths in the Quark list (and the system is clever enough not to delete them when we order: remove all Quarks)
