### ISSUE TITLE
Add supernova by default to SuperCollider in 3.7 on all platforms

### ISSUE THREAD

**Issue by bagong** [supercollider/supercollider#1359]
If Tim agrees it seems the right thing to do

**Comment by jamshark70** [comment]
"Add" meaning...? I can think of a few possible meanings, but you haven't given enough information to distinguish them.

- Add it as an executable in precompiled downloads (OK).

- Enable its compilation by default in cmake (OK with me, if it isn't already the case).

- Set it as the default server executable in Server.sc -- here, I wouldn't agree because of the different way that supernova handles timing.

**Comment by bagong** [comment]
Well, a discussion is a nice way to decide upon that, isn't it. I agree with all you say.

**Comment by miguel-negrao** [comment]
> Set it as the default server executable in Server.sc -- here, I wouldn't agree because of the different way that supernova handles timing.

I think it would be useful to document this issue in the wiki, and also why do we have supernova and scsynth, and what are the trade-offs of using one or the other.  Would this be accurate ?

scsynth:

- not multicore aware.
- tested for many years.
- older code base.
- has similar performance in osx, windows, and linux.
- follows the system clock.

supernova

- can use all the cores of the computer.
- less well tested.
- modern coding practices.
- performance:
  - Excellent performance in a tuned linux system.
  - Performance in osx is problematic (at least it was when I tried to have a look at it with Tim).
  - Reports of good performance in windows (by victor).
- follows the audio card clock. This might cause it to drift from sclang over large periods of time, e.g., in installations.

**Comment by crucialfelix** [comment]
ParGroup help file needs to explain that its talking about supernova

Client-side representation of a parallel group node on the server

Parallel Groups are server-side node containers that work similar to
Groups, but without ordering constraints for the contained nodes. This
means that on parallel architectures the elements of a Parallel Group can
be executed concurrently.



This makes 0 sense unless you already know what it means. It implies that
its running on the normal scsynth.

There is only one mention of supernova in the docs:

*supernova
Switches server program to use supernova. Check ParGroup how to make use of
multicore hardware with the supernova server.

If we went into a feature freeze as of last Friday or when we released
alpha0 then I think there is too much work to add documentation for
supernova.
I'm not 100% against it, but I think we need all of us swarming around
fixing things and not adding more things (that might introduce new
breakages).

There are lots of bugs. Right now when I open the help files I'm getting a
flash of content and then it goes blank grey.
In SCIDE the help browser opens up on start but its blank.

Both SCIDE and sclang use the same icon and the applications are named the
same. That's really confusing.

**Comment by miguel-negrao** [comment]
> There is only one mention of supernova in the docs:

There should probably be a help 'reference' file for supernova, explaining how the parallelism works, and how to deal with resources such as reading/writing to buses in nested trees of ParGroups and Groups. I could create this reference this weekend if it would help.

**Comment by bagong** [comment]
Felix, adding ;) supernova is a matter of 10 minutes plus the time Miguel needs to write the reference.
A few people have been compiling with supernova over the past by default, and I have never heard of a build problem concerning the supernova binary and plugins in the last months. It can be used as a drop in replacement of scsynth if you want. There is a tiny problem with finding plugins atm.
It'll make the binary download a big bigger, that's all. The other day I read people enquiring about supernova on the sonic-pi list, it's actually a bit embarrassing that it's not provided by the distribution (except on Linux, of course). After all it's a major achievement from one of the members of this community.

The main question in my view is if @timblechmann feels comfortable with it.

**Comment by gusano** [comment]
:+1: to @jamshark70 suggestions and :+1: to @miguel-negrao help file addition

**Comment by timblechmann** [comment]
no objection from my side and i'll happily review supernova-related patches/fixes

**Comment by bagong** [comment]
Do you have time to fix the plugins-not-found problem on OS X?

**Comment by timblechmann** [comment]
i won't spend any time on this, as i'm not running sc on osx.

**Comment by bagong** [comment]
Ah, okay, am I right to conclude you'll support it on Linux only, then?

**Comment by timblechmann** [comment]
"support" as in "actively fix bugs and ensure functionality"? this only applies to those computers that i have a personal interest in running sc on.

**Comment by bagong** [comment]
Okay, fair enough...
I'd suggest waiting then if somebody get's around to doing something about the current situation on OS X. It's discussed a bit here: https://github.com/supercollider/supercollider/issues/1281

**Comment by miguel-negrao** [comment]
> Do you have time to fix the plugins-not-found problem on OS X?

Even if that's fixed there are problems with threading in osx. I'm not sure that it's worth spending effort on this until someone with good c++ and osx threading knowledge commits to picking up supernova development on OSX.

**Comment by bagong** [comment]
Yea, it's a pity though...

**Comment by vivid-synth** [comment]
Can we close this? Supernova is now on all platforms, no? I've created separate issues for OS X and Windows performance:

https://github.com/supercollider/supercollider/issues/2258
https://github.com/supercollider/supercollider/issues/2257

**Comment by vivid-synth** [comment]
Or is it not included on all platforms?
