### ISSUE TITLE
Quarks sclang <-> IDE: Opening help from stacked Quarks-windows doesn't bring help window to the front

### ISSUE THREAD

**Issue by bagong** [supercollider/supercollider#1361]
- Detach the help-docklet and hide it behind the editor-window. 
- Open the Quarks.gui, 
- select a Quark and click e.g. 'classes', 
- select a class and click 'help'. 

This will trigger a help-query, but if the help-window will remain in the background. It is pretty tricky to bring it to the front, with the keyboard I think impossible ;)

**Comment by crucialfelix** [comment]
its the responsibility of the help system to bring the window to the front if needed, no ?

```supercollider
			^HelpBrowser.openHelpFor(p);
```

I'm getting a bunch of issues with the help windows

**Comment by crucialfelix** [comment]
Put another way: Programmatically opening a help file does not cause the IDE to front itself in the OS.

The help methods would have to check if IDE was present, and if so to call a method that fronts it.

If you are not using the IDE then the help window opens as an sclang window anyway

**Comment by vivid-synth** [comment]
(can we add the "env: QT IDE" label to this?)
