### ISSUE TITLE
OSX/IDE: default key for "trigger autocomplete" cmd-space conflicts with spotlight

### ISSUE THREAD

**Issue by bagong** [supercollider/supercollider#1365]
cmd-space for spotlight is a high priority system-wide key on OS X. It can't really be used by any application. Currently autocomplete cannot be triggered manually on OS X with the default setting.

**Comment by telephon** [comment]
in bash, autocomplete is ````tab````, so alt-tab would be a good choice,  but obviously tab is a little much used for window switching etc. Eclipse seems to use ````Ctrl + Space````.

**Comment by bagong** [comment]
I privately use alt-space, and alt-shift-space for arguments-display. Nice for the hand, and I don't think it conflicts with anything on OS X. Ctrl-(shift)-space seems to be free too.

**Comment by timblechmann** [comment]
as mentioned in the commit: @telephon @bagong, please check that the modifier won't interfere with shortcuts on other platforms.
alt-based shortcuts in application-code call for trouble and should usually be avoided

**Comment by telephon** [comment]
Just a note: I can't do this, so I have to trust the awareness of others. Thanks for commenting it.
