### ISSUE TITLE
LanguageConfig.current problems

### ISSUE THREAD

**Issue by crucialfelix** [supercollider/supercollider#1369]
1: If there was no config file when booting up, then LanguageConfig.current returns ""

Which breaks Quarks because it is now saving to a config file of ""

If it instead returns nil (which would be the correct answer), then when Quarks calls LanguageConfig.store(nil); that will correctly create a default sclang_config.yaml and all will function as advertised.

fix: LanguageConfig.current should return nil

2:  If a config file is created or selected using Preferences, then LanguageConfig.current still returns the old value. Even recompiling does not get the new value.  

The value has been saved to sc_ide_conf.yaml

But only restarting SuperCollider IDE will load the new value.

fix: should parse the value directly from the yaml file

**Comment by crucialfelix** [comment]
switching the config is messy. There is a confusion because config values are being read out of memory, but the settings are changing files on disk.

**Comment by crucialfelix** [comment]
Solution if somebody is having problems right now with 3.7-alpha-0 and not being able to install Quarks:

1. go to the app preferences. create or select a config file

2. restart SuperCollider

**Comment by scztt** [comment]
When this gets resolved, it seems like a couple ppl should validate the full quarks workflow (i.e. install SC, checkout and install Quarks, recompile, uninstall - whatever you'd do if you've never used quarks before) on mac/linux, as well as a scenario when you're coming from 3.6.x with already-installed quarks... make sure there aren't any other lingering hiccups. And if that looks solid, this should definitely trigger an alpha1 build. All that's required for that is (a) adding a tag and pushing it to github (travis will build and post the release binary), (b) updating the release wiki page with build link + notes.

**Comment by crucialfelix** [comment]
yes, more than just me testing it !

I'll be even more thorough myself next time.
nobody thought about the config file problem before because it
auto-generates when you pass it nil

**Comment by crucialfelix** [comment]
i'll do this tomorrow, didn't get a chance today.
