### ISSUE TITLE
Server Gui volume bug (gitreports.com)

### ISSUE THREAD

**Issue by scztt** [supercollider/supercollider#1370]
Submitter: patrick
Email: p.dupuis@live.com
Fedora 21 Linux - 3.19.1-201.fc21.x86_64
Supercollider 3.7alpha 
commit 4bcab22

When I create a server window with s.makeGui, the volume slider in the server window is initially set to 0 db regardless of the IDE status bar volume setting. It would be nice if the server window took into account the status bar volume when it is created. 

The two volumes begin to match when either of them is changed after the server window's creation.

**Comment by muellmusik** [comment]
This is not a problem with the IDE, but with the Server GUI window. This causes the same problem:

```
s.volume = -6
s.makeWindow
```
