### ISSUE TITLE
make it easier to test pull requests

### ISSUE THREAD

**Issue by telephon** [supercollider/supercollider#1373]
It is (fairly) complicated to test pull requests. This has the effect that most don't get tested.

Here is a possible solution: http://www.splitbrain.org/blog/2011-06/19-automate_github_pull_requests

Would that make sense for this repository?

**Comment by telephon** [comment]
I  just saw, it is a script that works locally. It is now here: https://github.com/splitbrain/git-pull-request
Need to try it out.

**Comment by gusano** [comment]
> It is (fairly) complicated to test pull requests

Do it a couple of times, then it gets really easy :cocktail:

**Comment by bagong** [comment]
My entry for the github sc-repo in .git/config looks like this:
```
[remote "scgithub"]
	url = https://github.com/supercollider/supercollider.git
	fetch = +refs/heads/*:refs/remotes/scgithub/*
	fetch = +refs/pull/*/head:refs/remotes/scgithub/pr/*
```
The second 'fetch' line pulls all the pr's in automatically. I can locally merge any pr like any other branch:

`git merge scgithub/pr/1372`

I find this more flexible than having each pr be turned into its own branch.

**Comment by telephon** [comment]
This is much better.

**Comment by danstowell** [comment]
nice - maybe document that on the developer webpage or sth?

**Comment by bagong** [comment]
Done. I added it to the cheat sheet (at the end):
https://github.com/supercollider/supercollider.github.io/blob/master/development/git-cheat-sheet.md
Let me know if it needs modifications, I thought a pull request was administrative overhead.

**Comment by crucialfelix** [comment]
Install hub.github.io git extensions

$ git checkout https://github.com/supercollider/supercollider/pull/134

**Comment by bagong** [comment]
http://hub.github.com

**Comment by crucialfelix** [comment]
Meeting adjourned.
