### ISSUE TITLE
no menu bar in i3 window manager in ubuntu < 15.04

### ISSUE THREAD

**Issue by miguel-negrao** [supercollider/supercollider#1374]
Compiled from master today in ubuntu 14.04 with qt5. I use the i3 window manager. SuperCollider doesn't show any menubar, so it's impossible to use. This bug report suggests this is an issue with qt5 and i3, xmonad, gnome3 and kde: https://bugs.launchpad.net/ubuntu/+source/appmenu-qt5/+bug/1307619. The suggested temporary solution there is to uninstall appmenu-qt5 which works but makes supercollider look horrible, it's using a very ugly theme.

```
sudo apt-get remove appmenu-qt5
```

![captura de ecra de 2015-03-26 12 24 26](https://cloud.githubusercontent.com/assets/382777/6846076/109de720-d3b3-11e4-85aa-83911752fd18.png)

```
 sudo apt-get install appmenu-qt5
```

![captura de ecra de 2015-03-26 12 23 51](https://cloud.githubusercontent.com/assets/382777/6846075/109cc89a-d3b3-11e4-91ac-487f73c4cabb.png)

**Comment by bagong** [comment]
Do you think it be fixed in the IDE?

Global menu for SC works fine with Unity, btw ;). Looks like Unity is a lot maturer now than in the past, and Ubuntu holds on to it.

**Comment by miguel-negrao** [comment]
The bug report https://code.soundsoftware.ac.uk/issues/1039 suggests setting  menuBar()->setNativeMenuBar(false) . Not sure how that would look in Unity though. It also suggests that this is because the Qt5 libraries in ubuntu have been changed to work with unity, installing original qt5 libraries might fix this issue then...

**Comment by bagong** [comment]
Sounds more like an distribution issue to me

**Comment by miguel-negrao** [comment]
Yes, I think it happens only on ubuntu + gnome3|i3|kde|xmonad. Very few people probably...

**Comment by bagong** [comment]
Furthermore the more "default-like" sc behaves the more likely it is that it will be fixed in the distribution. Should we maybe remove the tag bug from this issue? (that's also a way to bring them down :) )

**Comment by miguel-negrao** [comment]
It seems ubuntu 15.04 uses local menus, so who knows, it might fix this issue...

**Comment by danstowell** [comment]
I had this problem too - no menu bar in Xubuntu 14.04. I'm using openbox.

I can confirm that uninstalling appmenu-qt5 fixed it for me.

**Comment by miguel-negrao** [comment]
can confirm this issue doesn't happen in debian jessie+ i3
