### ISSUE TITLE
quarks (new) - canceling git checkout

### ISSUE THREAD

**Issue by miguel-negrao** [supercollider/supercollider#1376]
Doing a git checkout via the quarks seems to block the lang ? At least the quarks window seems to freeze.

 I was just now in a place where git's port was blocked and so the git processes didn't do anything and the quarks window froze. It would be nice to get some visual update that the checkout has started (post to the post window ?) and get a cancel button to kill the git process, otherwise in cases like these they must me killed by hand.

**Comment by crucialfelix** [comment]
showing that it is in progress is on my to do list. I didn't think about cancelling it.
