### ISSUE TITLE
quarks (new) - installing local quark does not install it's dependencies it only links.

### ISSUE THREAD

**Issue by miguel-negrao** [supercollider/supercollider#1378]
```
	*install { |name, refspec|
		var path;
		if(Quarks.isPath(name).not, {
			this.installQuark(Quark(name, refspec));
		}, {
			// local path / ~/ ./
			path = this.asAbsolutePath(name);
			if(File.exists(path).not, {
				("Path does not exist" + path).warn;
			});
			this.link(path);
		});
	}
```

Shouldn't the behaviour be the same if the quark is local or not ? Perhaps *installQuark could be modified to also install local quarks, by not doing a checkout on those, but still running the rest of the code, like getting the dependencies.

**Comment by crucialfelix** [comment]
This was fixed in 4581a35136a6c55041e327f0c5f59808b61a7071
