### ISSUE TITLE
Use reader/writer thread for all disk IO (DiskIn / DiskOut ugens, others if applicable)

### ISSUE THREAD

**Issue by scztt** [supercollider/supercollider#1381]
If disk writes are slow or delayed, DiskOut can easily corrupt a recording. A separate IO thread should be used, with reads (DiskIn) and write (DiskOut) requests queued and performed asynchronously. Possibly the supernova implementation can be borrowed or adapted.

**Comment by muellmusik** [comment]
I'm not sure I understand. There is a separate IO thread, or? PR #1382 deals with the issue discussed in the thread that this arose from.

**Comment by scztt** [comment]
You're right - I reviewed your change and the disk io ugens as they are and I don't know if there's more improvement to be had, barring specific performance bugs.
