### ISSUE TITLE
Remove cURL dependency in Quarks

### ISSUE THREAD

**Issue by sensestage** [supercollider/supercollider#1389]
On a system where curl is not installed, Quarks.gui -> [Refresh Quarks Directory], or Quarks.fetchDirectory, just fails without warning, leaving the user in the dark about the failed command and a reason why the window stays empty.

**Comment by crucialfelix** [comment]
agreed, but curl dependency is being removed anyway. so it won't be needed.

I'm going to just change this ticket to say "remove curl dependency"
