### ISSUE TITLE
Blank help window

### ISSUE THREAD

**Issue by acarabott** [supercollider/supercollider#1395]
**Bug description:**
Contents of help window not showing when using an external editor.

This is under OS X 10.9.5, using either Atom or Sublime Text. Has been reported by @crucialfelix to occur with IDE too.

**Steps to reproduce:**
`HelpBrowser.goHome`;

or

`Array.openHelpFile;`
Then click on any other link.

![screen shot 2015-03-31 at 22 56 31](https://cloud.githubusercontent.com/assets/66132/6930246/5385b618-d7f9-11e4-9f00-802ce6bfe3d5.png)

**Comment by vividsnow** [comment]
same with simple sclang shell:
```sh
*** Welcome to SuperCollider 3.7alpha0. *** For help type ctrl-c ctrl-h (Emacs) or :SChelp (vim) or ctrl-U (sced/gedit).
sc3> Help.gui
-> Help
sc3> SCDoc: Indexing help-files...
SCDoc: Indexed 2297 documents in 2.81 seconds

--> displays blank window
```

**Comment by davidgranstrom** [comment]
It seems that WebView closes itself whenever it needs to refresh its scrollbars. Steps to reproduce:
```
w = WebView();
w.url = "www.google.com";
w.front;
```
The first time it will close immediately. Next time you bring it to front it will stay open, but if you hover over the scrollbar to the right and then move the cursor outside of the window, it will close again. I believe that this might be related to this issue.. 

OS X 10.9.5 - SuperCollider build from 430d1b6 (master)

**Comment by scztt** [comment]
@acarabott - Can you retest? Should be fixed in this build or later: http://supercollider.s3.amazonaws.com/builds/supercollider/supercollider/osx/SC-678888ad52404cd36600947307a84d4457df9b3b.zip

**Comment by acarabott** [comment]
@scztt - fixed :)
