### ISSUE TITLE
quarks (new) - suggestion - directory.txt use https instead of git protocol.

### ISSUE THREAD

**Issue by miguel-negrao** [supercollider/supercollider#1397]
Using the [git protocol](http://git-scm.com/book/es/v2/Git-on-the-Server-The-Protocols) (git://) will try to open port 9418. 

    tcp        0      1 143.117.230.148:52195   192.30.252.130:9418     SYN_ENVI    1000       44131       12311/git 

On many netwoks, specially university networks in the uk, that port is blocked. I for instance cannot use the quarks from the university wireless. That causes the git process to just hang.  Wouldn't it be better to use https instead ? Htttps is almost never blocked (thank god for online banking !).

**Comment by crucialfelix** [comment]
I was wondering about that too.

If we change it we will probably break a few installs, but its best to
change it now.

**Comment by scztt** [comment]
I just learned that the workaround for this is to run:
`git config --global url."https://".insteadOf git://`
...which redirects all git:// urls to https:// urls.
For 3.7, we should add this to the documentation and possible to an error message if it appears our git connection is failing.

**Comment by gusano** [comment]
@scztt I don't think changing users global git config is a good idea
@crucialfelix why would using `https://` instead of `git://` break a few installs?

**Comment by crucialfelix** [comment]
I don't think we break any installs at all if we just change it. but it might reinstall them because the url doesn't match. it would put them in the same location.

I'll just find and replace them all and change quarks docs.
