### ISSUE TITLE
icon representation of sclang and scserver: and still jumping

### ISSUE THREAD

**Issue by telephon** [supercollider/supercollider#1399]
That on OSX, sclang and scserver currently have the same icon as scide is a known issue, I think. But also the icon of scserver keeps jumping in the dock for a very long time. It seems to stop only out of final exhaustion.

**Comment by scztt** [comment]
Sounds like folks think it's acceptable to not show scserver in the dock, which would fix. Does that sound appropriate?

**Comment by crucialfelix** [comment]
I agree: scserver has no gui and cannot be fronted so it should not be in
the dock.

similar background processes like databases do not show icons either.

**Comment by telephon** [comment]
+1

**Comment by bagong** [comment]
+1

**Comment by telephon** [comment]
sc-server doesn't show up anymore now.
