### ISSUE TITLE
quarks (new) - quarks always go into default lang config file.

### ISSUE THREAD

**Issue by miguel-negrao** [supercollider/supercollider#1400]
if  non default language config file is selected in the ide the quarks paths still get added to the default language file anyway.

Is this the expected behaviour ? It was confusing for me, I took me a while to understand why the quarks were not getting added to my current lang conf file.

**Comment by bagong** [comment]
The lang-config file used by the IDE is stored in the ide-config file, and for an IDE-independent Quarks system you don't really want to look there. Step by step the complications of the multi-configuration option reveal themselves :)

**Comment by crucialfelix** [comment]
What version are you on ?

Julian fixed it so that Quarks does check which setting was used to start
the language, and that is the config file that it writes to.

Regardless of who you start the language and whether the IDE is there or
not, it should modify the currently active config file.

**Comment by miguel-negrao** [comment]
> ulian fixed it so that Quarks does check which setting was used to start the language, and that is the config file that it writes to.

You're right, this has been fixed already. Sorry, I'm still on the commit before the Qt5 merge due to the disappearing menu on i3, have to remember to check HEAD before adding issues...
