### ISSUE TITLE
Document-switching (alt/ctrl-tab) while having a detached docklet open: focus moves from editor to docklet

### ISSUE THREAD

**Issue by bagong** [supercollider/supercollider#1402]
OSX 10.10/QT5
alt-tab document switching appears as if broken if you have a docklet open (help, post or document) in a detached state (this does not happen with docklets in docked or attached state). In this case with each alt-tab the focus moves from the editor to the docklet and does not return. Thus you cannot type in the switched-to editor window and - as is to be expected - can't document-switch again. This bug (as it seems to me) might actually give the impression that alt-tab switching was intended to allow to switch from the editor to another "window"

Anybody else sees this? Especially on non-OSX platforms?

**Comment by scztt** [comment]
gah, now that you point it out, this is annoying. I tried explicitly setting the focus after the document switches (box->setFocus() on multi_editor.cpp:989) but it doesn't do the trick. Something else more tricky must be happening....

**Comment by bagong** [comment]
Something changed. The docklet isn't shown anymore and the document switches as expected. But the focus doesn't move to the new (switched to) document (at that point it is not visible where the focus is).

Maybe useful as to what is going on: 
- open a docklet and put it to the background
- switch to another document and do *not* move the focus to the new document manually
- switch to another application with cmd-tab
- return to supercollider with cmd-tab

You will se the docklet in the foreground, and it has the focus.

**Comment by bagong** [comment]
Seems to have fixed itself... But I tried on a rather untypical system with Qt 5.8... if somebody else finds it's gone maybe just close...

**Comment by brianlheim** [comment]
Fixed with Qt 5.5 as well.
