### ISSUE TITLE
Textcolors in editor: pipette as color picker doesn't work

### ISSUE THREAD

**Issue by bagong** [supercollider/supercollider#1404]
OSX 10.10/Qt5.4.1
1. Open Preferences/Editor/Font&Colors
2. Activate the color-picker for one of the editable colors, e.g. Text-background, by clicking the rectangular color box after 'background'
3. In the appearing color picker click the pipette in the lower left corner. The cursor should turn into a magnifying glas that allows you to select a color from the environment.
   -> the magnifying glass doesn't appear, no possibility to clone a color is available
4. close the color picker
5. close the preferences dialog
6. the cursor appears as magnifying glas in the sc-editor until you click or press escape

**Comment by scztt** [comment]
Bummer. This seems to be a qt5+yosemite problem - I can repro in Qt Creator, and not in Text Edit. [This thread](https://forum.xojo.com/16488-selectcolor-issue-on-yosemite/0) seems to suggest that it could be a Yosemite bug related to the color picker being (non-)modal, which we have no control over....

Workaround, btw, is to click the pipette and then drag from the color swatch next to it, which will enable the magnifying glass picker.

**Comment by bagong** [comment]
The behaviour is different now, you get the pipette, but on close the mouse disappears... I think this is so far in the Qt/OS domain, that we shouldn't burden our issue tracker with it.
