### ISSUE TITLE
binop ?

### ISSUE THREAD

**Issue by simdax** [supercollider/supercollider#1409]
hello

Hello, I'm sceptic.
 Why does that bunch of code work 
```Supercollider
( p = Pbind( \step, Prand([0,1,2,3], inf),`
\degree, Pseries(step:Pkey(\step)).fold(0,4),

 \dur, Pclutch( Pseq([1, 2], inf),
 Pkey(\step)> 2.trace

 )).play; )
```

 and not this one ??? 
```Supercollider
( p = Pbind( \step, Prand([0,1,2,3], inf),
 \degree, Pseries(step:Pkey(\step)).fold(0,4),

 \dur, Pclutch( Pseq([1, 2], inf), 

//HERE
Pkey(\step) == 2).trace, 

 )).play; ) 
```

Is'nt "==" a binop ??? 
same problem with "!=". The result is random.

**Comment by jamshark70** [comment]
This should not be a bug report. It should be a question on the mailing list.

If everybody logs bug reports for usage questions, then the bug tracker becomes less useful for developers.

== and != are special cases -- they can't be made into "lazy" operations as > and < can. For these, you have to write the lazy operator explicitly: `Pbinop('==', Pkey(\step), 2)`.

Yes, this is a pain. But the need for == to be always "eager" goes deep into the class library. I tried once to improve it, but it caused hundreds of little errors. I had to give up.

**Comment by simdax** [comment]
OK, thank you.
I apologize, but now I have an answer, because the mailing list seems to be very little responsive for that kind of question.
