### ISSUE TITLE
findRegexp does not compile escaped character sequences correctly

### ISSUE THREAD

**Issue by crucialfelix** [supercollider/supercollider#1411]
`-` must be escaped in a regex character set: `\-`

But I think the regex compiler is not being passed the escape sequence. 
It should have parsed docs-syntax-fixes and instead it halted at docs:

```
"(HEAD, tag: docs-syntax-fixes)".findRegexp("tag: ([a-zA-Z0-9\.\-_]+)")
-> [ [ 7, tag: docs ], [ 12, docs ] ]
```

```
"(HEAD, tag: docs-syntax-fixes)".findRegexp("tag: ([^ ]+)")
-> [ [ 7, tag: docs-syntax-fixes) ], [ 12, docs-syntax-fixes) ] ]
```

**Comment by sofakid** [comment]
You need to double the backslashes.

**Comment by crucialfelix** [comment]
ah ha. that would be a bug in itself. escape should not have to be escaped in order to be used as escapes.

**Comment by jamshark70** [comment]
Not a bug. \ serves as an escape character in the regexp language. \ is also an escape character in SC string literals. If you are writing a SC string literal whose value should include a backslash character (serving as a regexp escape), then yes, you need two backslashes.

**Comment by crucialfelix** [comment]
ok, agreed.

I guess that's why python uses the special r string:  r"exp\."

the r before the string marks it as a special type so its compiled with the
\ still in there
