### ISSUE TITLE
MIDIFunc.noteOn does not work with floats when Arrays of numbers are passed

### ISSUE THREAD

**Issue by muellmusik** [supercollider/supercollider#1426]
See discussion under Issue #325 and under #1425. The commit added for that only fixes the single message number case. If floats are allowed there, they should also be allowed for Arrays of message numbers.

**Comment by scztt** [comment]
@muellmusik - Should be fixed by #1432 merge?

**Comment by crucialfelix** [comment]
yes, its fixed by that pr that was merged
