### ISSUE TITLE
Feature: IDE preference to disable displaying help pages in the autocomplete popup

### ISSUE THREAD

**Issue by jamshark70** [supercollider/supercollider#1435]
Just to make sure this doesn't get lost. Not everybody will like the new feature (I'm not especially crazy about it), but I haven't found where to turn it off.

**Comment by jamshark70** [comment]
Since the topic came up of triaging issues: My reason for logging this for 3.7 is that, IMO, the help-in-autocomplete feature is not finished until there's a preference. I think there are two ways to go:

1. Add the preference for 3.7
2. Postpone help-in-autocomplete altogether until 3.8 (i.e., remove it from 3.7).

**Comment by bagong** [comment]
I a menu item under View. I also expected it under preferences, but the higher flexibility also has it's advantages...

**Comment by jamshark70** [comment]
OK... If it's not under Preferences, where at least two users expected it, then it needs documentation. But this issue can be closed anyway.
