### ISSUE TITLE
sclang crashes on 0.exit

### ISSUE THREAD

**Issue by jamshark70** [supercollider/supercollider#1438]
There are a couple of other "crash on exit" issues (#1422, #939). I am not sure if this issue is related to them, but I think this deserves its own issue because:

- It's the most fundamental crash-on-exit case: `0.exit` from within command-line sclang causes the crash.

- Thus, it also affects any editor (e.g. IDE) that tells the interpreter to exit this way.

- This issue doesn't involve any interaction with other components (unlike #1422, which might be about the server, and #939, which might be about the IDE).

Once this is fixed, it's worth rechecking #939 and #1422.

```
$ gdb sclang
... blah blah
(gdb) run
... blah blah
sc3> 0.exit
main: waiting for input thread to join...
main: quitting...
[Thread 0x7fff837f4700 (LWP 28513) exited]
LID: event loop stopped
[Thread 0x7fff83ff5700 (LWP 28512) exited]
[Thread 0x7fff847f6700 (LWP 28496) exited]
[Thread 0x7fff84ff7700 (LWP 28495) exited]
[Thread 0x7fff857f8700 (LWP 28494) exited]
empty
[Thread 0x7fff85ff9700 (LWP 28493) exited]
cleaning up OSC
[Thread 0x7fffe8231700 (LWP 28482) exited]
terminate called without an active exception

Program received signal SIGABRT, Aborted.
0x00007ffff112b0d5 in raise () from /lib/x86_64-linux-gnu/libc.so.6

(gdb) where
0  0x00007ffff112b0d5 in raise () from /lib/x86_64-linux-gnu/libc.so.6
1  0x00007ffff112e83b in abort () from /lib/x86_64-linux-gnu/libc.so.6
2  0x00007ffff1a2716d in __gnu_cxx::__verbose_terminate_handler() ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
3  0x00007ffff1a251d6 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
4  0x00007ffff1a25221 in std::terminate() ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
5  0x000000000045e78e in std::thread::~thread (this=<optimized out>, 
    __in_chrg=<optimized out>) at /usr/include/c++/4.7/thread:141
6  0x00007ffff11305b1 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
7  0x00007ffff1130635 in exit () from /lib/x86_64-linux-gnu/libc.so.6
8  0x00007ffff1116774 in __libc_start_main ()
   from /lib/x86_64-linux-gnu/libc.so.6
9  0x000000000044fb11 in _start ()
```

**Comment by timblechmann** [comment]
a std::thread is destroyed without, violating the requirements. compare http://en.cppreference.com/w/cpp/thread/thread/~thread

**Comment by crucialfelix** [comment]
Does not crash on OS X 3.7.0-dev

Can you checkout linux 3.7 branch and confirm ?

**Comment by bagong** [comment]
On Windows situation is still unchanged. I think that's something for 3.8...

**Comment by danstowell** [comment]
Still same situation on linux 3.7 branch I'm afraid. Very similar output as HJH originally quoted above

**Comment by bagong** [comment]
Fixed for linux in master, fix for Windows is pending merge for 3.7 (after a general 3.7.2 alpha testphase). Does it still exist on OSX?

**Comment by telephon** [comment]
`0.exit`on OSX on master returns in the ide:

`Interpreter has quit. [Exit code: 0]`

nothing else. So this looks fixed.

**Comment by bagong** [comment]
For me too. I'll close until it resurfaces ;)
