### ISSUE TITLE
Font.defaultMonoFace/.defaultSansFace/.defaultSerifFace return the same value

### ISSUE THREAD

**Issue by bagong** [supercollider/supercollider#1447]
Qt5.4/OSX 10.10, it's Lucida Sans for me

**Comment by scztt** [comment]
@bagong - can you test to see if there's a reasonable result on windows? And, can someone test Linux as well?

**Comment by scztt** [comment]
Btw, there are newer / more reasonable API's for this in qt5, but this matches old behavior and involves the least change for 3.7.

**Comment by bagong** [comment]
I checked it on Windows both msys2/MinGW (msys2 Qt5.4.1) and VS64 build (vanilla Qt5.4.2). I also checked on Linux: UbuntuStudio 15.04 using their Qt5.4.1. All works great! Return values:

Windows (Qt5.4.1 and 5.4.2)
Courier New
Arial
Times New Roman

Ubuntustudio (Qt5.4.1)
DejaVu Sans Mono
DejaVu Sans
DejaVu Serif
