### ISSUE TITLE
Error on interpreter startup

### ISSUE THREAD

**Issue by ceremona** [supercollider/supercollider#1448]
Bug description:  On starting the new SC 3.7 prerelease build on OSX 10.8 I get:
SCDoc: Indexing help-files...
ERROR: Message 'isPathSeparator' not understood.
RECEIVER:
   nil
ARGS:

PROTECTED CALL STACK:
	Meta_MethodError:new	0x114eae9c0
		arg this = DoesNotUnderstandError
		arg what = nil
		arg receiver = nil
	Meta_DoesNotUnderstandError:new	0x114eb0980
		arg this = DoesNotUnderstandError
		arg receiver = nil
		arg selector = isPathSeparator
		arg args = [  ]
	Object:doesNotUnderstand	0x114a06440
		arg this = nil
		arg selector = isPathSeparator
		arg args = nil
	PathName:entries	0x115a16040
		arg this = PathName()
		var path = 
	PathName:folders	0x115a18000
		arg this = PathName()
	a FunctionDef	0x114da5840
		sourceCode = "<an open Function>"
		arg dir = PathName()
	ArrayedCollection:do	0x115abc540
		arg this = [ /Users/cere/Library/Application Support/SuperCollider/Extensions, /Library/Application Support/SuperCollider/Extensions,  ]
		arg function = a Function
		var i = 2
	Meta_SCDoc:helpSourceDirs	0x114da5300
		arg this = SCDoc
		var find = a Function
		var rootPaths = [ /Users/cere/Library/Application Support/SuperCollider/Extensions, /Library/Application Support/SuperCollider/Extensions,  ]
	Meta_SCDoc:indexAllDocuments	0x114da0900
		arg this = SCDoc
		arg clearCache = false
		var now = 1.248405106
		var key = nil
		var doc = nil
		var nonHelpFiles = nil
		var undocClasses = IdentitySet[ GrayNoise, TapN, StartUp, Error, TdefGui, AbstractPlayControl, SymbolArray, Plambda, Ppar, JITGui, CurveWarp, Int8Array, SinGrainIBF, SoftClipAmp, UHJ2B, ScaleInfo, Pen, BLBufRd, TouchResponder, PV_Cutoff, BusScopeSynth, OteyPiano, Switch1, Poll, DelayC, Function, Prout, QPen, FuncFilterPattern, BendResponder, AbstractIn, Rest, TabFileReader, CleanupStream, FoaDominateX, Pseg, Ref, DragView, FeatureSave, Pevent, SCViewHolder, BufGrain, PowerOfTwoBlock, CheapVerb, RMShelf, FFTSubbandPower, HDR, ...etc...
		var additions = Dictionary[  ]
	Meta_SCDoc:documents	0x114da5180
		arg this = SCDoc
	Meta_SCDoc:prepareHelpForURL	0x114da90c0
		arg this = SCDoc
		arg url = file:///Users/cere/Library/Application Support/SuperCollider/Help/Help.html
		var path = /Users/cere/Library/Application Support/SuperCollider/Help/Help.html
		var targetBasePath = /Users/cere/Library/Application Support/SuperCollider/Help
		var pathIsCaseInsensitive = false
		var subtarget = Help
		var src = nil
		var c = nil
		var cmd = nil
		var doc = nil
		var destExist = true
		var destMtime = 1430775913
		var verpath = /Users/cere/Library/Application Support/SuperCollider/Help/version
	a FunctionDef	0x114d01e40
		sourceCode = "<an open Function>"
	Function:prTry	0x11510ce80
		arg this = a Function
		var result = nil
		var thread = a Routine
		var next = nil
		var wasInProtectedFunc = true
	
CALL STACK:
	DoesNotUnderstandError:reportError   0x116c6d848
		arg this = <instance of DoesNotUnderstandError>
	< closed FunctionDef >   0x116beca58
		arg error = <instance of DoesNotUnderstandError>
	Integer:forBy   0x1163cef38
		arg this = 0
		arg endval = 0
		arg stepval = 2
		arg function = <instance of Function>
		var i = 0
		var j = 0
	SequenceableCollection:pairsDo   0x116e06968
		arg this = [*2]
		arg function = <instance of Function>
	Scheduler:seconds_   0x116e07818
		arg this = <instance of Scheduler>
		arg newSeconds = 1.252734415
	Meta_AppClock:tick   0x1176e20b8
		arg this = <instance of Meta_AppClock>
		var saveClock = <instance of Meta_SystemClock>
	Process:tick   0x1176ef698
		arg this = <instance of Main>
^^ The preceding error dump is for ERROR: Message 'isPathSeparator' not understood.
RECEIVER: nil

Steps to reproduce:
1.  Download sc 3.7 prerelease build
2.  Start SC app from within the built folder
3.

Actual result:

Expected result:

**Comment by crucialfelix** [comment]
The problem is that you have a blank line added to your include paths

this is an array of 3 items, the last one is ""

    arg this = [ /Users/cere/Library/Application Support/SuperCollider/Extensions, /Library/Application Support/SuperCollider/Extensions, ]

Look at LanguageConfig.includePaths

To fix it open the preferences and remove the bad entry.

The system shouldn't break though, so there is a bug here to fix.

**Comment by ceremona** [comment]
Hrm.  Can you tell me which file to look at?  Based on what you are saying this would come from the sclang_conf.yaml file: 
includePaths:
    - ""
excludePaths:
    []
postInlineWarnings: false

When I vi into this file, I don't see a blank line.

**Comment by crucialfelix** [comment]
your first line in includePaths is ""

its an empty string

the error is happening because its trying to get the first character of ""
(to see if its a path separator)
and that returns nil

// index out of bounds returns nil
""[0]

**Comment by bagong** [comment]
An autogenerated empty sclang_config.yaml looks like this:
```
includePaths:
    []
excludePaths:
    []
postInlineWarnings: false
```

**Comment by telephon** [comment]
Can you check if this fixes it for you? Otherwise, feel free to reopen.

**Comment by ceremona** [comment]
Yes, I cleared out the delimeters in the .yaml file and that seemed to fix things.  Thanks!
