### ISSUE TITLE
Server not shut down on IDE-close

### ISSUE THREAD

**Issue by bagong** [supercollider/supercollider#1449]
SC3.7/Qt5.4/Win8.1

**Comment by bagong** [comment]
Might be a duplicate of #1456, so Windows & (Arch?) Linux

**Comment by bagong** [comment]
So this is not the same issue #1456. with PR #1467 things work as expected on linux, but the zombies remain in Windows. It is likely also not related "cannot close server in terminal with ctrl-c", because supernova can be closed with ctrl-c, but it also remains as zombie in IDE close.

**Comment by bagong** [comment]
This is currently the most annoying problem. Trying to get a bit closer: it seems the server should be shut down by sclang when it closes. I can't find where that happens yet. But obviously sclang does not close properly when this is triggered from scide:
In ScProcess::stopLanguage (sc_process.cpp) "0.exit" is evaluated. If I do the same in the IDE, sclang shutdown get's stuck at posting "main: waiting for input thread to join...".
which in turn seems to be posted by mInputService.stop() in SC_TerminalClient.cpp.
On OS X it continues properly to "main: quitting" posted by mInputThread.join() in the same function.
On Windows it seems sclang is then killed() to allow for a scide shutdown, without caring that sclang didn't close cleanly.
mInputService leads into boost-land (in SC_TerminalClent.h). @timblechmann, I remember you were filing on this when working on the Windows version last November. Do you understand what is going wrong, could you explain, so that somebody else could pick up where you left?

**Comment by timblechmann** [comment]
not sure what happens here ... killing processes is definitely a bug, which should not happen in the default code paths. maybe it was "necessary" because sc is not properly cleaning up after itself?

**Comment by bagong** [comment]
Could you point me to the code where the server is shutdown during close of sclang? Could there be a relation with the fact that a server running in the terminal in Windows cannot be shutdown by hitting ctrl-c (this used to work as well in 3.6.6)?

**Comment by bagong** [comment]
So what seems to happen is that 0.exit fails and after waiting 200ms sclang is killed (kill()). So the failure to close the server might be a side-effect of the failure to close sclang? As currently sclang is killed anyways, would it be possible to add something that kills the server, just as a workaround? I tried adding something like evaluateCode("Server.killAll", true); before kill(), but it had no effect...

**Comment by bagong** [comment]
Okay, I have more or less verified that the server will quit if sclang closes properly, or at lease more properly than at the moment. See #1578

**Comment by bagong** [comment]
So I'd say the actual bug is that sclang cannot close properly. Maybe this issue should be closed...

**Comment by llloret** [comment]
I think this is fixed on 3.7.2.
