### ISSUE TITLE
IDE Help popup -> crash

### ISSUE THREAD

**Issue by thormagnusson** [supercollider/supercollider#1452]
Bug description: Dragging code from the help popup (the examples) onto the current document crashes the IDE. 

I was trying to copy the example code from the popup so I didn't need to find it in the help document.

Steps to reproduce:
1. Type "Butt(on)" into a new document.
2. Try to copy some text from there and paste into the document (well, it won't work)
3. Select some code and drag it into the document.

Actual result: IDE crashes

Expected result: Code is both pasted (on copy-paste) or inserted (on dragging).

**Comment by telephon** [comment]
Fixed.
