### ISSUE TITLE
Readline/Command line mode not working on Windows

### ISSUE THREAD

**Issue by bagong** [supercollider/supercollider#1455]
The situation is somewhat different in the MinGW and VS build:
- in the MinGW build you get a proper prompt and your input is echoed, but nothing happens. None of the control keys does anything too
- in the VS Studio build sclang crashes when started in cmd-line mode. It happens at a very late stage of the startup process. You still get the full list of sclang boot messages, but before the prompt displays it crashes.

**Comment by bagong** [comment]
I have inspected this with more detail now. I have to say first, the situation is quite different from the one described above. If you use readline 5.0.1 as provided by GnuWin32 rather than a readline vs6 from MinGW. With the earlier it *almost* works in the MinGW-32 build (in the 32-bit VS build you get a link error).

In order to get input, you have to keep your finger on a key for something like half a second. Then the keypress is registered (if you wait too long, the key repeats), if you press a key briefly/naturally, it will usually register after the second keystroke. Things like enter, ctrl-x and ctrl-t work (if you wait on the key). On ctrl-t you notice most clearly that there is a wait time, before the key registers.

ctrl-d (quit) works, but crashes sclang

Exiting sclang (ctrl-D)
sc3> main: waiting for input thread to join...
main: quitting...
empty
cleaning up OSC
terminate called without an active exception

And then the system pops in and tells that this was not a nice ending.

There is a readline-Windows related "fixme" in SC_TerminalClient::readlineInit()

    // FIXME: Implement the code below on Windows
    // #ifndef _WIN32
    // Set our handler for SIGINT that will clear the line instead of terminating.
    // NOTE: We prevent readline from setting its own signal handlers,
    // to not override ours.
    rl_catch_signals = 0;
    struct sigaction sact;
    memset( &sact, 0, sizeof(struct sigaction) );
    sact.sa_handler = &sc_rl_signalhandler;
    sigaction( SIGINT, &sact, 0 );
    // #endif

If you try to compile the code commented out in Windows, you get following errors:

    C:\Users\Rainer\Projects\sc\supercollider\lang\LangSource\SC_TerminalClient.cpp:507: error: aggregate 'SC_TerminalClient::readlineInit()::sigaction sact' has incomplete type and cannot be defined
      struct sigaction sact;
    C:\Users\Rainer\Projects\sc\supercollider\lang\LangSource\SC_TerminalClient.cpp:508: error: invalid application of 'sizeof' to incomplete type 'SC_TerminalClient::readlineInit()::sigaction'
      memset( &sact, 0, sizeof(struct sigaction) );
    C:\Users\Rainer\Projects\sc\supercollider\lang\LangSource\SC_TerminalClient.cpp:510: error: invalid use of incomplete type 'struct SC_TerminalClient::readlineInit()::sigaction'
      sigaction( SIGINT, &sact, 0 );
    C:\Users\Rainer\Projects\sc\supercollider\lang\LangSource\SC_TerminalClient.cpp:507: error: forward declaration of 'struct SC_TerminalClient::readlineInit()::sigaction'
      struct sigaction sact;

On mac history works, on Windows it doesn't, but I don't know if it ever did

If you step through the code from readlineInit onwards, you see that most is boost-asio related. There is no crash though, if you use readline GnuWin32 5.0.1. In the MinGW build other versions link, but create an error on sclang startup. In the VS build (32-bit as well) all versions create a link error.

I think the priority here is to solve that key press problem, which will let the interface appear unusable to most (and makes it unusable in a practical sense). The crash in the end (ctrl-d or 0.exit) seems to happen quite late (now?), scsynth is usually shut down.

**Comment by bagong** [comment]
see #2171. Since the Windows MinGW build is up again (for the time being :) ) and MSYS2 is a build environment that provides readline 32- and 64-bit in an ongoing manner, fixing readline for Windows still would be a useful task if no consensus on linenoise can be reached.

**Comment by vivid-synth** [comment]
Can I close this as a dupe of #2171 ?

**Comment by bagong** [comment]
Yea, I'll write something soon in the other thread.
