### ISSUE TITLE
Bracket matching misbehavior in scel

### ISSUE THREAD

**Issue by jleben** [supercollider/supercollider#146]
[Issue migrated from SourceForge | ID: 3170289 | Submitted by 'jamshark70']
[http://sourceforge.net/support/tracker.php?aid=3170289]

Here's an interesting test case for paren/bracket matching in scel.

Emacs shows that the outer array brackets [] are unmatched, but the code compiles properly. You won't be able to run the file because you won't have all the resources it requires, but this isn't an execution issue -- it's all about compilation. If any brackets really were unmatched, this would print a syntax error:

thisProcess.interpreter.compileFile("~/path/to/01-feet-sequence.scd".standardizePath);

But it doesn't -- it returns "a Function" as it should.

So the syntax is fine, but Emacs processes the bracket matching incorrectly.

**Comment by vivid-synth** [comment]
Can't repro
