### ISSUE TITLE
OSX Spaces/fullscreen: sclang stays on root space - so when focus switches to sclang, screen is switched

### ISSUE THREAD

**Issue by bagong** [supercollider/supercollider#1464]
I have read something like this somewhere before, but I couldn't find it, sorry, if this is a duplicate: if the editor is in a secondary space or in fullscreen (which on OS X let's it automatically move to another space/screen), an action that moves the focus to sclang will trigger switching back to the initial space/screen. Two examples: while in fullscreen mode a) create a Window and bring it to front, or b) simply restart the interpreter. If you close the IDE in fullscreen mode and restart it, you will be first moved to the IDE-space/screen, and then back to the primary screen, because the focus on OS X always moves to sclang at the end of startup.

OSX10.10, Qt5.4.1

**Comment by vivid-synth** [comment]
(can we add the "os: Mac OS X" label to this?)
