### ISSUE TITLE
General issue for auto-indent misbehavior in scel

### ISSUE THREAD

**Issue by jleben** [supercollider/supercollider#147]
[Issue migrated from SourceForge | ID: 3177143 | Submitted by 'jamshark70']
[http://sourceforge.net/support/tracker.php?aid=3177143]

Here are a few -- add more to this bug as you find them. Sorry if this is a dupe - sf's search is broken now.

(1..3).do { |i|
\chuckIf.eval(Fact(("drum" ++ i).asSymbol), BP, ("drum" ++ i).asSymbol, nil,
(source: \drum1).putAll(Library.at(\rvbs)))
};

[
Routine {  // any capitalized keyword followed by {} breaks indentation
... do something
},
Routine {.....}  // should be indented but ain't
]

**Comment by snappizz** [comment]
Both of these examples seem to be fine now. Please open new issues for each specific problem.

**Comment by defaultxr** [comment]
@snappizz I'm still able to reproduce these problems with the current git version of scel. Using C-M-\ doesn't indent all of the lines properly in either example. Are you using a different version of scel than what's included in editors/scel/el?

**Comment by snappizz** [comment]
duehehhh I missed the "in scel" part.

**Comment by widp** [comment]
This issue was moved to supercollider/scel#1
