### ISSUE TITLE
How to complete unload plugins PR?

### ISSUE THREAD

**Issue by sonoro1234** [supercollider/supercollider#1473]
commit https://github.com/supercollider/supercollider/commit/87e26cd75c6c7d4cfba40985cb38b113a38a0821
was merged before work was completed, so it introduced problems on scsynth quit. Now it must be solved someway

the work now has two possible PR

https://github.com/supercollider/supercollider/pull/1467
or
https://github.com/supercollider/supercollider/pull/1472

both of them solve program hangs and crash on win32, linux and macosx

the first one does plugin unload on scsynth and leave prepared for supernova
the second one reverts all the unloading plugins stuff and only does a minimal DiskIO_UGens modification

only one should be choosen and the opinion of everybody is important

Best
victor

**Comment by telephon** [comment]
I'd like to contribute to the decision, but I can't judge the implications of the code – what is the main difference between the two?

**Comment by sonoro1234** [comment]
Both of them solve program hangs and crash on win32, linux and macosx

The first one does plugin unload (calls unload on the plugin) on scsynth and leave it prepared for supernova (until novaserver destructor dont crash on macosx and linux)
The second one reverts all the unloading plugins stuff and only does a minimal DiskIO_UGens modification to avoid hang on exit

**Comment by telephon** [comment]
Ah ok, the question is whether to solve the problem generally (1) or just for the one case (2). Are there any implications of (2) that need to be taken into account (e.g. a special way you have to write the plugins?)

**Comment by sonoro1234** [comment]
In case 1 you can declare an unload function (if you need it to deinitialize your pluging) or dont declare unload and behaviour is as ever has been.
Case 2 is just a DiskIOUGens modification that solves the hang and nothing else

**Comment by telephon** [comment]
So it seems that (1) is the better solution, @timblechmann what do you think?

**Comment by timblechmann** [comment]
(2) is keeps the leaks

**Comment by telephon** [comment]
OK, I'll merge (2), yes?

**Comment by timblechmann** [comment]
please merge (1).

**Comment by sonoro1234** [comment]
yes, merge (1) please.

**Comment by telephon** [comment]
OK :)

**Comment by telephon** [comment]
Done here: de18ba2d96108e1fc0a05ce46b4a931422e66458
