### ISSUE TITLE
Windows: New Quarks system: installed Quarks not recognized

### ISSUE THREAD

**Issue by bagong** [supercollider/supercollider#1475]
First of all: we can install Quarks on Windows now, how cool! An Quark clicked for installation is properly added to langConfig and can be used.

1. on reopening the GUI though the Quark is not recognized as installed
2. the "recompile class library" never get's active
3. the vertical scroll-bar cannot be accessed, so scrolling through the whole list of Quarks is only possible by down- and up-arrowing in the list.

Testing is still very cumbersome as the interpreter is very unstable, but maybe these points are usefull.

**Comment by crucialfelix** [comment]
1. What is the exact path that was added to the langConfig ?  What is the actual path where the downloaded quark is ?

2. It would only become active when you make a change.  According to your description you just compiled and then opened Quarks.gui  "recompile class library" would not be active

3. That's something with Qt I guess.

**Comment by bagong** [comment]
langConfig:

    - C:\Users\Rainer\AppData\Local\SuperCollider\downloaded-quarks\MathLib
    - C:\Users\Rainer\AppData\Local\SuperCollider\downloaded-quarks\json

1. The actual paths are the same, as I told you, the Quarks are used in SC after the install
2. the recompile button does *not* get active after the installation of a Quark.

**Comment by crucialfelix** [comment]
fix is merged to master. please check if it parses the paths correctly now

**Comment by bagong** [comment]
Yea, end of next week...

**Comment by crucialfelix** [comment]
beep beep. can you check to confirm that its parsing the windows paths now ? thx

**Comment by crucialfelix** [comment]
I'm assuming that this works. reopen or file a new bug if this is not the case.
