### ISSUE TITLE
ide is running but invisible after sleep on Linux

### ISSUE THREAD

**Issue by sensestage** [supercollider/supercollider#1477]
I have now encountered a couple of times that when I put my computer to sleep, afterwards the IDE is not visible anymore, but still seems to be active - when files get changed, I do get the reload documents dialog.

This is with a recent build from master from earlier this week, on Linux, running Xubuntu.

Has anyone else encountered this issue?

**Comment by sensestage** [comment]
It is quite reproducible with these steps

* start scide
* put computer to sleep (e.g. by laptop lid close)
* wake computer up
* scide window has disappeared, as well as the docklet in the top bar
* scide process and sclang process are still running ( ```$ ps-A | grep sc```)

**Comment by danstowell** [comment]
Doesn't happen here, sorry. Just pulled & built (git 21c661b). Xubuntu 14.04, Qt 5.2.1

**Comment by sensestage** [comment]
I'll test again with new pull and clean build.

**Comment by sensestage** [comment]
same issue still:

cmake output:

```
-- SuperCollider Version: 3.7alpha0
-- Building from branch master, commit hash is 162bd65
-- Build type defaulting to "RelWithDebInfo"
-- Compiling with Qt GUI
-- building boost libraries manually
-- using bundled libyaml-cpp
hidapi cmakelists
===linux hidraw cmakelists===
-- libudev stable: 1
-- Found UDev: /usr/lib/x86_64-linux-gnu/libudev.so
--    include: /usr/include
===hidapi_parser cmakelists===
-- using fftw3f
-- Found jack: /usr/lib/x86_64-linux-gnu/libjack.so
-- Audio API: jack
libsclang qt libs:Qt5::CoreQt5::GuiQt5::WidgetsQt5::NetworkQt5::WebKitQt5::WebKitWidgetsQt5::PrintSupportQt5::OpenGLQt5::SensorsQt5::QuickQt5::QmlQt5::SqlQt5::Positioning/usr/lib/x86_64-linux-gnu/libm.so/usr/lib/x86_64-linux-gnu/libX11.so
core: /usr/lib/x86_64-linux-gnu/libQt5Core.so.5.2.1
-- Compiling with ALSA midi support
-- Building the Qt IDE
-- Configuring done
-- Generating done
-- Build files have been written to: /home/nescivi/git/sc3/supercollider/build
```

**Comment by sensestage** [comment]
Running in KDevelop:

I get an output:
```
QXcbConnection: XCB error: 3 (BadWindow), sequence: 652, resource id: 0, major code: 15 (QueryTree), minor code: 0
```

**Comment by sensestage** [comment]
This may be a similar bug:
https://bugreports.qt.io/browse/QTBUG-38326

**Comment by sensestage** [comment]
Or this one:
https://bugreports.qt.io/browse/QTBUG-42985

**Comment by sensestage** [comment]
The last Qt bug report seems to be the relevant one - this also means that it won't be fixed until Qt 5.5.0 is out.

**Comment by vivid-synth** [comment]
@sensestage do you still see this bug?

**Comment by sensestage** [comment]
I did still see it a little while ago on Xubuntu 14.04; I will test again shortly (building right now).

But will soon move to Xubuntu 16.04; and test there again.

**Comment by sensestage** [comment]
Issue is still there with Xubuntu 14.04.

**Comment by sensestage** [comment]
I've migrated my system to Xubuntu 16.04, which has Qt5 - 5.5.1.
The problem does not occur there - which makes sense, as it was supposed to be fixed with Qt5.5.0
