### ISSUE TITLE
sc3-plugins make error

### ISSUE THREAD

**Issue by davidhedlund** [supercollider/supercollider#1480]
https://github.com/supercollider/supercollider/wiki/Installing-SuperCollider-on-Ubuntu-systems says
Finally, building the plugins
From within sc3-plugins/build, run the following:
make

I running Trisquel GNU/Linux 7 which is based on Ubuntu 14.04 LTS (Trusty Tahr) but I get this error when I run make in sc3-plugins/build.

[  0%] Building CXX object source/CMakeFiles/AY_UGen.dir/AYUGens/AY_UGen.cpp.o
cc1plus: error: unrecognized command line option ‘-std=c++11’
make[2]: *** [source/CMakeFiles/AY_UGen.dir/AYUGens/AY_UGen.cpp.o] Error 1
make[1]: *** [source/CMakeFiles/AY_UGen.dir/all] Error 2
make: *** [all] Error 2

Do you know how to make it work @supercollider?

**Comment by bagong** [comment]
Two things might help:
- get latest sc3-plugins version (git pull, or git clone --recursive https://github.com/supercollider/sc3-plugins.git)
- add -DCPP11=ON to your cmake command (cmake -DCPP11=ON ..)

**Comment by davidhedlund** [comment]
@bagong Should your suggestions be added to https://github.com/supercollider/supercollider/wiki/Installing-SuperCollider-on-Ubuntu-systems ?

**Comment by gusano** [comment]
Why don't we enable `cpp11` by default?

**Comment by bagong** [comment]
it is enabled with the latest merge

**Comment by davidhedlund** [comment]
@bagong 

git clone https://github.com/supercollider/sc3-plugins.git
cd sc3-plugins/
git submodule init && git submodule update
mkdir build
cd build
cmake -DSC_PATH=/usr/include/SuperCollider -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release ..
make
Scanning dependencies of target AY_UGen
[  0%] Building CXX object source/CMakeFiles/AY_UGen.dir/AYUGens/AY_UGen.cpp.o
cc1plus: error: unrecognized command line option ‘-std=c++11’
make[2]: *** [source/CMakeFiles/AY_UGen.dir/AYUGens/AY_UGen.cpp.o] Error 1
make[1]: *** [source/CMakeFiles/AY_UGen.dir/all] Error 2
make: *** [all] Error 2

cmake -DSC_PATH=/usr/include/SuperCollider -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release -DCPP11=ON ..
make
[  0%] Building CXX object source/CMakeFiles/AY_UGen.dir/AYUGens/AY_UGen.cpp.o
cc1plus: error: unrecognized command line option ‘-std=c++11’
make[2]: *** [source/CMakeFiles/AY_UGen.dir/AYUGens/AY_UGen.cpp.o] Error 1
make[1]: *** [source/CMakeFiles/AY_UGen.dir/all] Error 2
make: *** [all] Error 2



git clone --recursive https://github.com/supercollider/sc3-plugins.git
cd sc3-plugins/
git submodule init && git submodule update
mkdir build
cd build
cmake -DSC_PATH=/usr/include/SuperCollider -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release ..
make
Scanning dependencies of target AY_UGen
[  0%] Building CXX object source/CMakeFiles/AY_UGen.dir/AYUGens/AY_UGen.cpp.o
cc1plus: error: unrecognized command line option ‘-std=c++11’
make[2]: *** [source/CMakeFiles/AY_UGen.dir/AYUGens/AY_UGen.cpp.o] Error 1
make[1]: *** [source/CMakeFiles/AY_UGen.dir/all] Error 2
make: *** [all] Error 2

cmake -DSC_PATH=/usr/include/SuperCollider -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release -DCPP11=ON ..
make
[  0%] Building CXX object source/CMakeFiles/AY_UGen.dir/AYUGens/AY_UGen.cpp.o
cc1plus: error: unrecognized command line option ‘-std=c++11’
make[2]: *** [source/CMakeFiles/AY_UGen.dir/AYUGens/AY_UGen.cpp.o] Error 1
make[1]: *** [source/CMakeFiles/AY_UGen.dir/all] Error 2
make: *** [all] Error 2

**Comment by bagong** [comment]
Hmm, sorry, man. I cannot analyze that further. The next question would be why your compiler doesn't accept c++11 as option. Maybe trisquel is still on gcc4.6 or has modifications that don't allow for c++11?

**Comment by davidhedlund** [comment]
@bagong Yes.

gcc -v # says
gcc version 4.6.3 (Ubuntu/Linaro 4.6.3-1ubuntu5)


Which version of GCC do I need?

**Comment by bagong** [comment]
In theory 4.7 should work, but 4.8 upwards is you safest bet...

**Comment by gusano** [comment]
> Which version of GCC do I need?

@davidhedlund You need gcc-4.7

**Comment by davidhedlund** [comment]
@bagong 

Please add that to https://github.com/supercollider/supercollider/wiki/Installing-SuperCollider-on-Ubuntu-systems Can you do that?

**Comment by bagong** [comment]
It's in the supercollider README_LINUX, but not in the sc3-plugins one...

**Comment by davidhedlund** [comment]
@bagong Thank you for all your support. Have a nice weekend.

**Comment by bagong** [comment]
You're welcome. You too ;)
