### ISSUE TITLE
recording display doesn't update on stop

### ISSUE THREAD

**Issue by telephon** [supercollider/supercollider#1484]
When a recording is started from sclang [1], the IDE menu doesn't get updated (`recording` isn't toggled).

Also, when started from the IDE-menu, and then stopped with `cmd-.`, it remains toggled (on).

This may be a problem in `void ScServer::onRunningStateChanged`.

[1] with `s.record("~/test.aiff".standardizePath);`

**Comment by telephon** [comment]
A quick test seems to show that the method ````void ScServer::onRunningStateChanged```` is never called.

**Comment by scztt** [comment]
There's actually no notification sent for recording status changes - the recording UI only works when it's triggered via the ide. Would be good to fix, but this is probably an enhancement for 3.8.

**Comment by scztt** [comment]
The fix would involve an additional server selector in ScServer::onScLangReponse, update messages in Server:record, Server:pauseRecording, Server:stopRecording (i.e. this.changed(\recording, \started), etc), and monitoring those events in the ScIDE SimpleController defined in ScIDE:*defaultServer

**Comment by telephon** [comment]
At least on cmd-. the toggle should be off, I suppose. Woudl that be hard?

**Comment by telephon** [comment]
Eventually it would be much better to have a uniform API that allows us to create menu functions in the IDE through the ScIDE class in sclang without much complications.

**Comment by scztt** [comment]
I'm disinclined to hack in a fix for the cmd+. case, because it'll still behave wonky in most cases (cmd+period from sclang, for example). You're right re uniform API too - I have some ideas how to do this, that would overlap with implementing custom menu's in sclang as well. I'd like to get that stuff done in 3.8.

**Comment by telephon** [comment]
this issue is fixed in #1547

**Comment by snappizz** [comment]
fixed in #1547
