### ISSUE TITLE
MIDIIn.connectAll connects to wrong ports on Linux

### ISSUE THREAD

**Issue by sensestage** [supercollider/supercollider#1487]
If the other ports on Linux are higher in the list, then SC connects to itself instead of the external program.
Proper behaviour would be to skip the own ports and connect to the next one.

**Comment by sensestage** [comment]
Proposed fix:
```
/*

MIDIClient.init;

MIDIClient.externalSources;
MIDIClient.externalDestinations;

MIDIIn.connectAll;
*/

+ MIDIClient {

	*externalSources{
		^MIDIClient.sources.select({ |src,i|
			src.device != "SuperCollider"
		})
	}

	*externalDestinations{
		^MIDIClient.destinations.select({ |src,i|
			src.device != "SuperCollider"
		})
	}

}

+ MIDIIn{

	*connectAll {
		if(MIDIClient.initialized.not,{ MIDIClient.init });
		MIDIClient.externalSources.do({ |src,i|
			MIDIIn.connect(i,src);
		});
	}
}
```

**Comment by sensestage** [comment]
just to elaborate a bit on the issue:

if I have MIDI devices in Alsa (devices other than SC with each one port)
14: Midi Through
129: SuperCollider
130: KMidiMon

then SC will create 4 input ports (2 more for system timer and sequencer, not shown in QJackCtl), and 2 output ports.
Before the fix, SC would connect its input port 3 to MidiThrough, and port 4 to SC's first output port.
With the fix, SuperCollider's own port are filtered out before creating the connections.

**Comment by scztt** [comment]
What does this do in cases where there are multiple copies of SuperCollider running?

**Comment by sensestage** [comment]
That would be something to test...

**Comment by sensestage** [comment]
Just did a test (with just the MidiThrough port otherwise open)

first copy of SC connects to the MidiThrough port,
second copy also just connects to the MidiThrough port - so if the two instances need to connect, a connection has to be made explicitly.

**Comment by sensestage** [comment]
A solution for that would require storing some more info about the MIDIEndpoint from the primitives. In ALSA the different clients get numbered (the two instances above are 128:SuperCollider and 130:SuperCollider), and with that we would be able to distinguish them.

**Comment by sensestage** [comment]
Or do the reverse engineering of the uid as it is done in the primitive:

```
static inline int SC_AlsaMakeUID(int clientID, int portID)
{
	return (clientID << 16) | (portID & 0xFFFF);
}

static inline void SC_AlsaParseUID(int uid, int& clientID, int& portID)
{
	clientID = uid >> 16;
	portID = uid & 0xFFFF;
}
```

**Comment by sensestage** [comment]
It seemed, I did need an additional primitive to do this properly, otherwise there was no way of finding the clientID of the instance of SuperCollider.
I've made a pull request: https://github.com/supercollider/supercollider/pull/1517

**Comment by sensestage** [comment]
pull request is merged!
