### ISSUE TITLE
WebView closes after displaying scrollbar

### ISSUE THREAD

**Issue by davidgranstrom** [supercollider/supercollider#1489]
WebView closes itself whenever it needs to display/redraw its scrollbar. Steps to reproduce:
```
w = WebView();
w.url = "www.google.com";
w.front;
```
The first time it will close immediately. Next time you bring it to front it will stay open, but if you hover over the right side of the window to reveal the scrollbar and then move away the cursor it will close.

OS X 10.9.5 - SuperCollider 3.7alpha0 (debug build) from 4bc71bf

**Comment by davidgranstrom** [comment]
This might be relevant for #1395

**Comment by scztt** [comment]
@davidgranstrom -Thanks for the catch. This bug is very very weird - at actually could be related to #1395 too. Investigating.

**Comment by scztt** [comment]
@davidgranstrom - You are a rock star.... the hint about scrollbars was what helped me nail this down. This is caused by a deep qt bug that's been around for years. Thanks,

**Comment by davidgranstrom** [comment]
Great to hear that it worked out!
