### ISSUE TITLE
MIDIdef.mtcQuarterFrame

### ISSUE THREAD

**Issue by smillan** [supercollider/supercollider#1496]
ERROR: Message 'mtcQF' not understood.
RECEIVER:
class MIDIIn (0x11713bfc0) {
  instance variables [19]
    name : Symbol 'MIDIIn'
    nextclass : instance of Meta_MIDIKeyboardWindow (0x11654d200, size=19, set=5)
    superclass : Symbol 'Object'
    subclasses : nil
    methods : nil
    instVarNames : instance of SymbolArray (0x11713c140, size=1, set=2)
    classVarNames : instance of SymbolArray (0x11713c2c0, size=20, set=4)
    iprototype : instance of Array (0x11713c200, size=1, set=2)
    cprototype : instance of Array (0x11713c440, size=20, set=5)
    constNames : nil
    constValues : nil
    instanceFormat : Integer 0
    instanceFlags : Integer 0
    classIndex : Integer 552
    classFlags : Integer 0
    maxSubclassIndex : Integer 552
    filenameSymbol : Symbol '/Applications/SuperCollider 3.7/SuperCollider.app/Contents/Resources/SCClassLibrary/Common/Control/MIDIOut.sc'
    charPos : Integer 2776
    classVarIndex : Integer 263
}
ARGS:
CALL STACK:
	DoesNotUnderstandError:reportError   0x11b481f28
		arg this = <instance of DoesNotUnderstandError>
	Nil:handleError   0x11b4839f8
		arg this = nil
		arg error = <instance of DoesNotUnderstandError>
	Thread:handleError   0x11b500388
		arg this = <instance of Thread>
		arg error = <instance of DoesNotUnderstandError>
	Object:throw   0x118e23cb8
		arg this = <instance of DoesNotUnderstandError>
	Object:doesNotUnderstand   0x10eab0a38
		arg this = <instance of Meta_MIDIIn>
		arg selector = 'mtcQF'
		arg args = [*0]
	MIDISysDataDispatcher:register   0x11b485368
		arg this = <instance of MIDISysDataDispatcher>
		var hook = 'mtcQF'
	AbstractWrappingDispatcher:add   0x119032dd8
		arg this = <instance of MIDISysDataDispatcher>
		arg funcProxy = <instance of MIDIdef>
		var func = nil
		var keys = [*16]
	AbstractResponderFunc:enable   0x118e1ac48
		arg this = <instance of MIDIdef>
	MIDIFunc:init   0x118d9f1c8
		arg this = <instance of MIDIdef>
		arg argfunc = nil
		arg argmsgNum = nil
		arg argchan = nil
		arg argType = 'mtcQF'
		arg argsrcID = nil
		arg argtempl = nil
		arg argdisp = <instance of MIDISysDataDispatcher>
	Meta_MIDIdef:new   0x11b8225e8
		arg this = <instance of Meta_MIDIdef>
		arg key = <instance of Function>
		arg func = nil
		arg msgNum = nil
		arg chan = nil
		arg msgType = 'mtcQF'
		arg srcID = nil
		arg argTemplate = nil
		arg dispatcher = nil
		var res = nil
	< closed FunctionDef >  (no arguments or variables)
	Interpreter:interpretPrintCmdLine   0x11b92b238
		arg this = <instance of Interpreter>
		var res = nil
		var func = <instance of Function>
		var code = "a = MIDIdef.mtcQuarterFrame(..."
		var doc = nil
		var ideClass = <instance of Meta_ScIDE>
	Process:interpretPrintCmdLine   0x118e8f9f8
		arg this = <instance of Main>
^^ The preceding error dump is for ERROR: Message 'mtcQF' not understood.
RECEIVER: MIDIIn

**Comment by muellmusik** [comment]
Fixed by 5bd67e9.
