### ISSUE TITLE
chebyFill bug

### ISSUE THREAD

**Issue by porres** [supercollider/supercollider#1500]
Hi, I was raising this up in the list

chebyFill is giving DC/Unipolar functions for even harmonics, where it shouldn't!!! Check it out.

Signal.chebyFill(256+1, [0,1]).plot; // even harmonics (with DC, so not ok)
Signal.chebyFill(256+1, [0,0,1]).plot // odd harmonics (no DC, so ok)

Seems to me like an easy bug to be fixed.

Thanks

**Comment by totalgee** [comment]
I've made a proposed fix (#1504) for the above problem (well, a new argument to Signal.chebyFill.  I also fixed some other bugs around Chebyshev polynomials I found.  Under my proposed addition, you would use a new zeroOffset argument to get the unshifted Chebyshev:

    Signal.chebyFill(256+1, [0,1], normalize: false, zeroOffset: false).plot;

**Comment by porres** [comment]
I was just thinking about the same wokaround, but I was thinking about calling it "dcOffset", and it could be "true" if you didn't want it to do what it does!

**Comment by totalgee** [comment]
Regarding your other comment in the pull request, I proposed changing it such that if normalize is on but zeroOffset is off, then it will just apply "regular" normalization (not the `normalizeTransfer` version it currently does).  I think that makes sense, based on what you're saying.  Then you have full flexibility to easily do any combination of things (shift without and without normalizing, unshifted Cheby with and without normalization).

**Comment by porres** [comment]
I guess unshifted Cheby with normalization should be the default

**Comment by olafklingt** [comment]
I agree with porres. I naively complained about the behavior of chebyFill a few years ago and got the answer like "that's how it is". As I was not able to describe it as a bug I stopped working with it. As not many people complained it seems that not many people use this functionality of sc.

**Comment by totalgee** [comment]
I've added a new PR #1520 that changes the default, as well as various further documentation improvements.

**Comment by telephon** [comment]
This is fixed, I suppose, but please add a unit test if you can, here: https://github.com/supercollider-quarks/CommonTests

**Comment by porres** [comment]
howdy, nice to hear it's fixed, I'd love to try it out, how do I do it? cheers

**Comment by telephon** [comment]
>howdy, nice to hear it's fixed, I'd love to try it out, how do I do it?

easiest (if you don't want to build one yourself) is wait a week or so for the next alpha version.

**Comment by porres** [comment]
yeah, don't feel like building myself :) - it's been 2 weeks, but I'll keep waiting ;) should be out anytime, right?

cheers

**Comment by telephon** [comment]
Hm, sorry, I think that got lost over the summer breaks. 
You can always get the latest build from travis:

https://travis-ci.org/supercollider

**Comment by snappizz** [comment]
The bug is fixed and the unit test is implemented, so can this be closed?

**Comment by brianlheim** [comment]
Doesn't look like the unit tests have ever been verified, could we keep this open until that's done? If I'm wrong then yes close.

**Comment by totalgee** [comment]
Some basic unit tests were added a couple of years ago in 827592e, so I think you can close this.  Thanks for following up!
