### ISSUE TITLE
WebView auto-closes when used without explicit parent

### ISSUE THREAD

**Issue by LFSaw** [supercollider/supercollider#1505]
when evaluating 

``` WebView().front.url_("http://lfsaw.de"); ```

the WebView closes, once the page is loaded completely.
What am I doing wrong?

**Comment by nuss** [comment]
... I guess it's not you doing something wrong. Rather you've hit a bug. Your example works without any problem on my machine (Ubuntu Studio 14.04, Qt 5.21, SC compiled from latest commit to master).

**Comment by LFSaw** [comment]
hmm... ok, so this happened on a week-old build, seems to be fixed now... could be closed already by 480ea91 it is closed on my machine with the current master 25a296f .
