### ISSUE TITLE
Issues with maximized (fullscreen) Qt windows on OS X

### ISSUE THREAD

**Issue by totalgee** [supercollider/supercollider#1506]
I am running the latest version (3.7 aka master) on OS X 10.10.3. When I open any Qt window, such as:

    Signal.sineFill(512, [1]).plot

or

    Window.new.front

and then maximize it by clicking the green button, the window goes fullscreen.  That's fine, except it seems to present a couple of ugly side effects:

1. When I close the maximized window (pressing Cmd-w), I am left with a black screen.  Pressing Escape or anything else won't get rid of it, I have to Cmd-Tab to switch back to the IDE.  I don't mind pressing Cmd-Tab (also had to do that in v3.6), but it's a nuisance that the window doesn't disappear to reveal what's underneath.  The sudden black screen is kind of disconcerting.

2. If I maximize a couple of windows, I am unable to switch between them using Cmd-\` (Cmd-backtick).  In v3.6, I could have several plot windows maximized, then quickly switch between them to compare them, using Cmd-\`.  Also, if I have several windows maximized, when I close one (using Cmd-w), I still get the black screen.  It would be nice to reveal the "next" one that's maximized.

This is probably to do with the special "fullscreen" functionality of OS X, but personally I preferred the old way.  Maybe there's a new workflow (or System preference) that allows quick switching that I just need to get used to -- but on first use compared to v3.6, it seems awkward/inefficient.  Also, it's a lot slower to go to fullscreen (you have to watch that zoom-up and cross-fade animation), compared to just maximizing a window without sending it to fullscreen mode.  It might be nice to be able to do both.

I guess a workaround for now would be to "maximize" using `availableBounds`):

    (
    Signal.sineFill(512, [1]).plot(bounds: Window.availableBounds);
    Signal.sineFill(512, [0, 1]).plot(bounds: Window.availableBounds); 
    )

Then I can do Cmd-\` to quickly switch between these "maximized but not fullscreen" windows.

**Comment by totalgee** [comment]
I see that if you Alt-click on the window's maximize button, it gives the old behaviour (maximized but not fullscreen).  So maybe part 2 of this issue is just a documentation thing...?

But regarding part 1 -- if the window is fullscreen (which is the default when clicking the maximize button), it's still a bug that the screen remains in fullscreen (showing black) after you close it with Cmd-w.  If you close it by moving the mouse to the top of the screen and clicking the red 'x' button (when it appears), it does return from fullscreen mode correctly.

**Comment by telephon** [comment]
On OS X 10.10.3: It seems that ````pressing Cmd-w```` has this behavior, but not the window title line, when you minimize again.

But also here, I am unable to switch between different fullscreen windows.

**Comment by telephon** [comment]
Maybe related: http://doc.qt.io/QtForDeviceCreation/qtee-known-issues.html

**Comment by bagong** [comment]
I can move between fullscreen windows/spaces by pressing ctrl-left/right-arrow (default on OS X). You can also select the window/space by doing a 4-finger swipe upwards and clicking the thumbnail of the space. The black window remains for me too with the SuperCollider=here=sclang process "owning" the space. If you close a space occupied by e.g. Safari with cmd-w, you will be flipped back to the root space and the "old" space will disappear.

**Comment by bagong** [comment]
The black spaces disappear if you reboot sclang... Ideally sclang-cmd-w would recognize that it is in fullscreen mode and close the window the same way red-x does. Scide-cmd-w closes a document, right? Confusing ;)

**Comment by scztt** [comment]
If anyone wants to tackle this, I can point you in the right direction - the fix is just to un-fullscreen fullscreened views before closing them.

**Comment by miczac** [comment]
workaround? https://github.com/supercollider/supercollider/pull/1816

**Comment by miczac** [comment]
@crucialfelix this could be closed then as well?

**Comment by miczac** [comment]
@totalgee, I also ran into the same problem, back then. 
(I had to have the post window in foreground, above the fullscreen window. This isn't possible anymore since 10.8 came out)
Alas it's the new behaviour of fullscreens on Spaces OS X comes with. Discussed that back then, @scztt proposed [this workaround](http://new-supercollider-mailing-lists-forums-use-these.2681727.n2.nabble.com/Fullscreen-w-Qt5-on-OS-X-td7616945.html#a7617003), which is in principle what you do.

**Comment by crucialfelix** [comment]
I think so. It solves the first issue. The second is OS X behavior.

What do you think @totalgee ?  Good enough ?

**Comment by miczac** [comment]
*ping* ;)

**Comment by totalgee** [comment]
Sorry for the delay!  Yes, I guess that’s good enough.

**Comment by wassgha** [comment]
So no better fix yet? I still have the issue of the black window (that I can close by using the "minimize button" shown below). 
![screen shot 2017-04-27 at 3 14 43 pm](https://cloud.githubusercontent.com/assets/591655/25500398/ede9ef04-2b5c-11e7-9f30-6a3c67b98f97.png)

However, another issue I am having (which I assume is derived from the same problem) is that when the "close" button is clicked on the fullscreen window, the mouse release event is only triggered after the closing ("sliding") animation is done which triggers buttons on the main (non-fullscreen) window. Is there a fix for that or a way to release the mouse button as soon as the close button is clicked? Thank you in advance
