### ISSUE TITLE
(regression) Document keyDownActions: discrepancy between global and instance

### ISSUE THREAD

**Issue by jamshark70** [supercollider/supercollider#1512]
```
(
Document.current.keyDownAction = { |doc, char, mods|
	mods.debug("instance keyDownAction");
};

Document.globalKeyDownAction = { |doc, char, mods|
	mods.debug("global keyDownAction");
};
)

// when done:
Document.current.keyDownAction = nil;
Document.globalKeyDownAction = nil;
```

SHIFT:
global keyDownAction: 131072
instance keyDownAction: 33554432

CTRL:
global keyDownAction: 262144
instance keyDownAction: 67108864

ALT:
global keyDownAction: 524288
instance keyDownAction: 134217728

I am 100% certain that ctrl used to come into the globalKeyDownAction as 67108864 before, but it's changed since my last pull (today). I'm now on alpha1 plus a few post-alpha1 commits.

I don't have an opinion which is correct -- but these used to be consistent, and now they aren't. That's a regression that must be fixed before release.

**Comment by telephon** [comment]
It should conform to the following:

````
isCaps { ^this.bitAnd(65536) == 65536}
	isShift { ^this.bitAnd(131072) == 131072 }
	isCtrl { ^this.bitAnd(262144) == 262144 }
	isAlt { ^this.bitAnd(524288) == 524288 }
	isCmd { ^this.bitAnd(1048576) == 1048576 }
	isNumPad { ^this.bitAnd(2097152) == 2097152 }
	isHelp { ^this.bitAnd(4194304) == 4194304 }
	isFun { ^this.bitAnd(8388608) == 8388608 }
````

**Comment by scztt** [comment]
Are these correct for View?

**Comment by jamshark70** [comment]
```
v = TextView(nil, Rect(800, 100, 400, 300)).front;

v.keyDownAction = { |view, char, modifiers|
	modifiers.debug("mods");
};
```

In Linux, shift, ctrl and alt are all correct with the above test code. On this machine, I can't get cmd, numpad, help or a function *modifier*, nor does caps-lock trigger a modifier. So I don't know about them. But in Linux at least, 1513 has fixed the issue.

**Comment by telephon** [comment]
On OS X, this fixes the issue for ````TextView````.

Here is the test, in case it is useful:

````
v = TextView(nil, Rect(800, 100, 400, 300)).front;

v.keyDownAction = { |view, char, modifiers|
	case
	{ modifiers.isAlt } { \alt }
	{ modifiers.isCtrl } { \ctrl }
	{ modifiers.isCmd } { \cmd }
	{ modifiers.isShift } { \shift }
	{ modifiers.isFun } { \fun }
	.postln
};

````
