### ISSUE TITLE
help: TempoClock set beats example is incorrect

### ISSUE THREAD

**Issue by telephon** [supercollider/supercollider#1518]
The helpfile says: "When changing code::beats::, you are only changing the clocks's notion of time, and not the current Thread's link::Classes/Thread#-beats#logical time::, which will stay the
same while the Thread is running. Hence, if this clock is the current Thread's
link::Classes/Thread#-clock#associated clock::, and you ask the clock for time in beats
just after changing it, you will see no effect. Nevertheless, the effect will be visible
immediately on a different Thread."

````
(
c = TempoClock.new;
fork {
	loop {
		c.beats.postln;
		1.wait;
	}
};
)

c.beats = 100;
````

This example shows that the beat is caught up immediately.

````
0
1
2
3
-> a TempoClock
100.914109879
101.914109879
102.914109879
103.914109879
````

**Comment by muellmusik** [comment]
The help file is poorly worded in my opinion, but isn't it describing the following?
```
(
t = TempoClock.new;

t.sched(3, {
	t.beats = 100;
	t.beats.postln; // still 3
	nil
});
)
```
The problem is the phrase 'while the thread is running'. It should probably say until the thread yields or something like that.
