### ISSUE TITLE
supercollider does not build on ppc64lel archb

### ISSUE THREAD

**Issue by leitao** [supercollider/supercollider#1519]
Currently, supercollider does not build on ppc64le architecture.

When trying to build it, it fails with:

```
         ^
```

/«PKGBUILDDIR»/include/plugin_interface/SC_Constants.h:49:14: warning: 'truncDouble' defined but not used [-Wunused-variable]
 const double truncDouble = 3. \* std::pow(2.0,51);
              ^
make[3]: **\* [server/plugins/CMakeFiles/BinaryOpUGens.dir/BinaryOpUGens.cpp.o] Error 1
server/plugins/CMakeFiles/BinaryOpUGens.dir/build.make:57: recipe for target 'server/plugins/CMakeFiles/BinaryOpUGens.dir/BinaryOpUGens.cpp.o' failed
make[3]: Leaving directory '/«PKGBUILDDIR»/obj-powerpc64le-linux-gnu'
make[2]: **\* [server/plugins/CMakeFiles/BinaryOpUGens.dir/all] Error 2
make[1]: **\* [all] Error 2
make: **\* [debian/stamp-makefile-build] Error 2
dpkg-buildpackage: error: debian/rules build-arch gave error exit status 2
CMakeFiles/Makefile2:1220: recipe for target 'server/plugins/CMakeFiles/BinaryOpUGens.dir/all' failed
make[2]: Leaving directory '/«PKGBUILDDIR»/obj-powerpc64le-linux-gnu'
Makefile:150: recipe for target 'all' failed
make[1]: Leaving directory '/«PKGBUILDDIR»/obj-powerpc64le-linux-gnu'

As shown in:

https://buildd.debian.org/status/fetch.php?pkg=supercollider&arch=ppc64el&ver=1%3A3.6.6~repack-2-1&stamp=1412444851

**Comment by danstowell** [comment]
Hi - thanks for the report. The informative information is actually slightly higher up:

	/«PKGBUILDDIR»/external_libraries/nova-simd/vec_altivec.hpp: In function 'nova::vec<float> nova::fast_reciprocal(const nova::vec<float>&)':
	/«PKGBUILDDIR»/external_libraries/nova-simd/vec_altivec.hpp:287:43: error: invalid parameter combination for AltiVec intrinsic
		 vector float estimate = vec_re(arg);

All you need to know is that the error is in the **nova-simd** library, probably because nova-simd doesn't (yet?) support your arch. This library improves speed but luckily it is optional.

Could you please try the build again but setting the cmake argument `-DNOVA_SIMD=OFF`?

**Comment by vivid-synth** [comment]
@leitao if you're still interested in this, could you try building with the above changes?

**Comment by leitao** [comment]
Hello @vivid-synth,

In fact I was able to build it using -mno-altivec -mno-vsx

Thank you,
Breno

**Comment by danstowell** [comment]
Aha. That's the same as is done in the debian packaging: https://anonscm.debian.org/cgit/pkg-multimedia/supercollider.git/tree/debian/rules
