### ISSUE TITLE
Seems like interpreter (or servers) are not tracking osc messages to server correctly

### ISSUE THREAD

**Issue by ceremona** [supercollider/supercollider#1524]
Using 10.8 OSX

Seeing lots of cases where interpreter will error out on something but stacktrace will show listings of functions that I am not even executing (coming from another file entirely, etc).  Seems like osc messages are not being properly tracked/inventoried somehow from the interpreter to the server.  I don't know the internals of SC, but I am seeing lots of bugs that seem indicative of this kind of problem.

Build: Built from branch 'HEAD' [b305a24] , though the about SC reads that this is build alpha 0 (though I know it's alpha 1).

Sorry for the vague bug report, but I thought it might be helpful.

**Comment by ceremona** [comment]
Haven't figured how to to reproduce the issue yet.  :(

**Comment by jamshark70** [comment]
Strongly suggested to post a few example stack traces. Of course there's no guarantee that a few call stacks will reveal the cause, but there's some chance. With the available information, though, the probability of narrowing down the issue is exactly 0.

**Comment by ceremona** [comment]
Thanks.  Ok. I'll submit another bug that I think is related and reproducable.
