### ISSUE TITLE
evaluating code in the help browser evaluates code in the document window instead

### ISSUE THREAD

**Issue by telephon** [supercollider/supercollider#1532]
… that says it all. 

Reproducer: open any helpfile and evaluate code there. Instead of running the selected line, it is the current line in the currently open document.

**Comment by bagong** [comment]
Yea, there is an issue for this already somewhere. Using shift-enter evaluates the code in the help-document, if I remember correctly.

**Comment by gusano** [comment]
Duplicate of #1385. Closing.
