### ISSUE TITLE
MethodOverride.printAll fails on OSX 10.8

### ISSUE THREAD

**Issue by ceremona** [supercollider/supercollider#1538]
Running 

MethodOverride.printAll;

Gives the following error:

Window
------
Execution warning: Class 'LocalQuarks' not found
ERROR: Message 'globalPath' not understood.
RECEIVER:
   nil
ARGS:
CALL STACK:
	DoesNotUnderstandError:reportError   0x112b396e8
		arg this = <instance of DoesNotUnderstandError>
	Nil:handleError   0x110097e18
		arg this = nil
		arg error = <instance of DoesNotUnderstandError>
	Thread:handleError   0x1128c6ce8
		arg this = <instance of Thread>
		arg error = <instance of DoesNotUnderstandError>
	Object:throw   0x11282bb38
		arg this = <instance of DoesNotUnderstandError>
	Object:doesNotUnderstand   0x112834a38
		arg this = nil
		arg selector = 'globalPath'
		arg args = [*0]
	Meta_MethodOverride:simplifyPath   0x1139aa3b8
		arg this = <instance of Meta_MethodOverride>
		arg path = "/Users/cere/Library/Applicat..."
		var extDir = "/Users/cere/Library/Applicat..."
		var sysExtDir = "/Library/Application Support..."
		var quarkDir = nil
	< FunctionDef in Method Meta_MethodOverride:printAll >   0x112838f38
		arg x = <instance of MethodOverride>
		var activePath = "/Users/cere/Library/Applicat..."
		var overriddenPath = "/Users/cere/tmp/SuperCollide..."
	ArrayedCollection:do   0x1128f5948
		arg this = [*3]
		arg function = <instance of Function>
		var i = 0
	< FunctionDef in Method Meta_MethodOverride:printAll >   0x11024e7f8
		arg class = <instance of Meta_Window>
	< FunctionDef in Method Set:do >   0x1128c59a8
		arg item = <instance of Meta_Window>
	ArrayedCollection:do   0x1128f22f8
		arg this = [*40]
		arg function = <instance of Function>
		var i = 17
	Set:do   0x1123991c8
		arg this = <instance of Set>
		arg function = <instance of Function>
		var i = 0
	Meta_MethodOverride:printAll   0x112f56e68
		arg this = <instance of Meta_MethodOverride>
		arg simplifyPaths = true
		var all = [*20]
		var classes = <instance of Set>
	Interpreter:interpretPrintCmdLine   0x112fd87f8
		arg this = <instance of Interpreter>
		var res = nil
		var func = <instance of Function>
		var code = "MethodOverride.printAll"
		var doc = nil
		var ideClass = <instance of Meta_ScIDE>
	Process:interpretPrintCmdLine   0x113fcc8e8
		arg this = <instance of Main>
^^ The preceding error dump is for ERROR: Message 'globalPath' not understood.
RECEIVER: nil

**Comment by ceremona** [comment]
Also remove the suggestion to use this function after recompiling class library warning:
Info: 20 methods are currently overwritten by extensions. To see which, execute:
MethodOverride.printAll

Which class/method should I use to find out more information if not MethodOverride?

**Comment by nuss** [comment]
Not MethodOverride.printAll has been removed but a call to broken method within the method. You should be able to use MethodOverride.printAll again without a problem after updating SC at least to this commit: 4b7636ff71f9d08589d83d93b8013574c5b40b7e

**Comment by ceremona** [comment]
Thanks!
