### ISSUE TITLE
concatenating large strings causes memory corruption

### ISSUE THREAD

**Issue by crucialfelix** [supercollider/supercollider#1543]
```
x = "";
2831.do {
    x = x ++ "c60feffaa30ed2e058452272c1cd7ae829e4d3fa";
};

// postln and it dies
x
```

this is 113,240 characters

sclang(37700,0x7fff7383b300) malloc: *** error for object 0x113aa1338: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
sclang exited

**Comment by telephon** [comment]
Array seems not to be affected:
````
x = [];
2831.do {
	x = x ++ "c60feffaa30ed2e058452272c1cd7ae829e4d3fa".as(Array);
};

// postln and it lives on
x
````

So it seems to be in ````_ArrayCat````.

**Comment by telephon** [comment]
````
int prArrayCat(struct VMGlobals *g, int numArgsPushed)
{
	PyrSlot *a, *b;
	PyrObject *obj, *aobj, *bobj;
	int elemsize, size;
	int numbytes, format;

	a = g->sp - 1;
	b = g->sp;

	if (NotObj(b) || slotRawObject(a)->classptr != slotRawObject(b)->classptr) return errWrongType;
	aobj = slotRawObject(a);
	bobj = slotRawObject(b);
	size = aobj->size + bobj->size;
	format = aobj->obj_format;
	assert(aobj->obj_format == bobj->obj_format);
	elemsize = gFormatElemSize[format];
	numbytes = (size * elemsize);

	obj = g->gc->New(numbytes, 0, format, true);
	obj->classptr = aobj->classptr;
	obj->size = size;
	memcpy(obj->slots, aobj->slots, aobj->size * elemsize);
	memcpy((char*)obj->slots + aobj->size * elemsize,
		bobj->slots, bobj->size * elemsize);
	SetObject(a, obj);

	return errNone;
}
````

**Comment by telephon** [comment]
A workaround would be to replace ````prCat```` by ````prArrayAddAll````. 

this doesn't cause memory corruption:

````
x = "";
2831.do {
	x = x.addAll("c60feffaa30ed2e058452272c1cd7ae829e4d3fa");
};
x
````

**Comment by telephon** [comment]
just for referencem ````prArrayAdd```` is the following:

````
int prArrayAddAll(struct VMGlobals *g, int numArgsPushed)
{
	PyrSlot *a, *b;
	PyrObject *obj, *aobj;
	int elemsize, newindexedsize, newsizebytes, asize, bsize;
	int format;

	a = g->sp - 1;
	b = g->sp;

	if (NotObj(b) || slotRawObject(a)->classptr != slotRawObject(b)->classptr) return errWrongType;
	aobj = slotRawObject(a);

	format = aobj->obj_format;
	elemsize = gFormatElemSize[format];
	asize = aobj->size;
	bsize = slotRawObject(b)->size;
	newindexedsize = asize + bsize;
	newsizebytes = newindexedsize * elemsize;

	if (newindexedsize > MAXINDEXSIZE(aobj) || aobj->IsImmutable()) {
		obj = g->gc->New(newsizebytes, 0, format, true);
		obj->classptr = aobj->classptr;
		memcpy(obj->slots, aobj->slots, asize * elemsize);
		SetObject(a, obj);
	} else {
		obj = aobj;
		if (format == obj_slot && !g->gc->ObjIsGrey(obj))
			g->gc->ToGrey(obj);
	}
	obj->size = newindexedsize;
	memcpy((char*)obj->slots + asize * elemsize, slotRawObject(b)->slots, bsize * elemsize);
	return errNone;
}
````

**Comment by scztt** [comment]
Well, the concat case should be almost identical to the addAll case (only
on a newly allocated object in the former case) so it would be useful to
compare the two? I was a little suspicious of the fact that string concats
are done by a somewhat inappropriate cast to a PyrObject (which is probably
strictly correct because they've got the same memory structure, but still
sorta smells). I didn't look closely at the GC barrier in prArrayCat, but
that's a likely candidate, especially because large strings may be
allocated in a special way.

-S

**Comment by bagong** [comment]
When does this occur? I cannot reproduce it with latest master on OS X, even not with 28310.do

**Comment by telephon** [comment]
Ah, you are right, gone here too.

**Comment by crucialfelix** [comment]
well damn, its not doing for me either now. so the memory must already have been corrupted and this was just triggering it.

next suspect:
```
// this was where the concat was happening
unixCmdGetStdOut {
...
		while({line.notNil}, {lines = lines ++ line ++ "\n"; line = pipe.getLine; });
...

// UnixFILE.sc

	getLine { arg maxSize=1024;
		var string;
		string = String.newClear(maxSize);
		^this.prGetLine(string);
	}
	prGetLine { arg argString;
		// returns a string up to lesser of next newline
		// or length-1 of the argument string
		_FileReadLine;
		^this.primitiveFailed;
	}

```

therefore Pipe will only pull lines up to 1024 characters.  That makes it kind of unusable actually.

prGetLine promises to limit it to that, but maybe something is incorrect in that method.

**Comment by telephon** [comment]
````
int prFileReadLine(struct VMGlobals *g, int numArgsPushed)
{
	PyrSlot *a, *b; // receiver(a File), string
	PyrFile *pfile;
	FILE *file;

	a = g->sp - 1;
	b = g->sp;

	pfile = (PyrFile*)slotRawObject(a);
	file = (FILE*)slotRawPtr(&pfile->fileptr);
	if (file == NULL) return errFailed;

	char* result = fgets(slotRawString(b)->s, MAXINDEXSIZE(slotRawObject(b)) - 1, file);
	if (!result) {
		SetNil(a);
	} else {
		slotRawString(b)->size = strlen(slotRawString(b)->s);
		if (slotRawString(b)->s[slotRawString(b)->size-1] == '\n') slotRawString(b)->size--;
		slotCopy(a,b);
	}
	return errNone;
}
````

Have you tried ````file.getLine(2048)```` ?

**Comment by crucialfelix** [comment]
When I get a chance I'll set up a test file or process with really long
lines and see if I can break sc by piping it in.

**Comment by scztt** [comment]
I don't think we should close this? Without a change to prArrayCat or any other primitives, this is almost surely still lurking - we've just lost the repro for it.

**Comment by timblechmann** [comment]
btw, the real bug could be in *any* primitive. it just manifests itself much later. one cannot test this, only analyse the primitives line by line.

we had this a few years back with the regexp primitives and it took jonatan and me a long time (more weeks than days) to figure this out and some of the long-time users heavily complained to me, how many bad things i had done to supercollider.

---

fwiw, the lack of a robust API to the GC was my main concern against language plugins.

**Comment by crucialfelix** [comment]
its not concatenating the arrays that was the problem. we confirmed that.

it is probably something in Pipe. so that's a separate bug.

**Comment by timblechmann** [comment]
it might be related to Pipe or it might be a wrong trace as well.
