### ISSUE TITLE
message length limits still correct?

### ISSUE THREAD

**Issue by telephon** [supercollider/supercollider#1553]
As the maximum udp message sizes seem to have changed is the following still correct? Or maybe they could be dropped? Certainly for `tcp` it would not be necessary, I suppose.

```
sendClumpedBundles { arg time ... args;
        if(args.bundleSize > 65535) {// udp max size.
                args.clumpBundles.do { |item|
                    if(time.notNil) { time = time + 1e-9 }; // make it a nanosecond later
                    this.sendBundle(time, *item)
                };
            } {
                this.sendBundle(time, *args)
        }
    }

    sync { arg condition, bundles, latency; // array of bundles that cause async action
        var resp, id;
        if (condition.isNil) { condition = Condition.new };
        if(bundles.isNil) {
            id = this.makeSyncResponder(condition);
            this.sendBundle(latency, ["/sync", id]);
            condition.wait;
        } {
            // not sure what the exact size is, but its about 20000
            // this relates to what _NetAddr_SendBundle can send
            if(bundles.bundleSize > 20000/*65515*/) { // 65515 = 65535 - 16 - 4 (sync msg size)
                bundles.clumpBundles.do { |item|
                    id = this.makeSyncResponder(condition);
                    this.sendBundle(latency, *(item ++ [["/sync", id]]));
                    if(latency.notNil) { latency = latency + 1e-9 };
                    condition.wait;
                }
            } {
                id = this.makeSyncResponder(condition);
                this.sendBundle(latency, *(bundles ++ [["/sync", id]]));
                condition.wait;
            }
        };
        // maybe needed: a timeout
    }
```

**Comment by timblechmann** [comment]
IP v6 datagrams would allow bigger sizes. Though to be honest: tcp is much more appropriate to transfer larger chunks of data. Or a shared memory interface ...

**Comment by telephon** [comment]
>tcp is much more appropriate to transfer larger chunks of data. Or a shared memory interface ...

For this, multiple connections would have to be made in parallel, and in advance, just in case, no? So one would need to open a TCP/smi connection in the background, just in case a packet happens to be too large for UDP. Or am I wrong in the assumption that UDP is appropriate for the usual small chuncks, because simple and fast?

**Comment by crucialfelix** [comment]
I would say that if you often want to send larger data, then just switch to using only TCP. No need for the complexity of having two protocols open.

I know I've pointed at this before, but its worth re-reading: http://stackoverflow.com/questions/47903/udp-vs-tcp-how-much-faster-is-it

TCP does have a 40 byte header which is quite large if you are just sending live controller information. But local networks are very fast. 

More than anything though I would think unix domain sockets would be very useful. `/var/run/supercollider/scsynth`

**Comment by timblechmann** [comment]
if high performance is a critical issue (what is performance? latency or throughput?), a shared memory interface is the way to go.

though, i'd strongly suggest to do some profiling to see if this is actually a real-world bottleneck.

**Comment by jamshark70** [comment]
Re: throughput, I recall a comment by James McCartney once, when a user asked how to make it safe to send tens of thousands of control messages per second to the server. Paraphrasing, it was something like, "If your control mechanism needs as much bandwidth as the resulting audio signal, you might want to rethink the control mechanism." That's tangentially related, but it suggests that, by the time you reach the point where network traffic becomes a bottleneck, that may be a sign of a poor design decision within that use case.

**Comment by muellmusik** [comment]
Of course important to test, but if we're talking about the server, my guess is that as usual hardware buffer size will be the determining factor for latency. Under normal circumstances this should dwarf network latency. This is important to keep in mind.

Throughput would normally not be a problem either I'd guess. With BEER we've managed a fully meshed audio network with 5 people over wifi.

I think large synthdefs are probably the more common issue. TCP or smi (at least locally) as a default might actually make sense for these reasons.

But of course testing would be needed.

**Comment by telephon** [comment]
Would granular synthesis be a good test case? There you may not really want a check whether each message has arrived.

**Comment by timblechmann** [comment]
well, it will always be a trade-off ... but to discuss the trade-off it is useless to speculate without having some numbers.

fwiw, doing granular synthesis on distributed computers without clock synchronisation (both of the osc bundle dispatcher but also without wordclock) won't produce accurate results, anyway

**Comment by telephon** [comment]
if you have clock synchronization, you do get accurate results with UDP, and if you don't need that high accuracy, that is also ok. UDP may still be more efficient (but I haven't measured this).

**Comment by telephon** [comment]
Independent of the issue whether TCP would be a good replacement, the question is still open: are the current values for message sizes correct?
