### ISSUE TITLE
PSinGrain not installed?

### ISSUE THREAD

**Issue by ceremona** [supercollider/supercollider#1556]
I get:
> Synth('temp__36' : 1003)
exception in GraphDef_Recv: UGen 'PSinGrain' not installed.
*** ERROR: SynthDef temp__36 not found
FAILURE IN SERVER /s_new SynthDef not found

{PSinGrain.ar(440)}.play

**Comment by jamshark70** [comment]
Please ask questions like this on the mailing list. This is a bug tracker, not a site for general support questions.

**Comment by ceremona** [comment]
This is not a question.  There is no stack trace but this function appears to be a part of the standard functions yet doesn't seem to work.

**Comment by jamshark70** [comment]
Sorry for my haste... typically "UGen not installed" is an environment-specific problem. But you're right, this is a bug. OscUGens.cpp omits the required `DefineSimpleUnit` call for PSinGrain.

It appears PSinGrain dates back to JMc's initial check-in, missing the `DefineSimpleUnit` even at that time. Homer nods.

It's an easy fix... I'll check it in soon.

**Comment by ceremona** [comment]
Regardless, I'm not sure how you expect to encourage new people to submit bug reports, without some tolerance for occasional "environmental problems" and misunderstandings.  SC is confusing enough as it is.

**Comment by danstowell** [comment]
@ceremona it's OK, he was just trying to point you towards the correct place. Your report was brief and it _looks_ very similar to a common setup error, you see.
