### ISSUE TITLE
ServerOptions.inDevices not working on Linux Platform + Windows 8

### ISSUE THREAD

**Issue by dsiah** [supercollider/supercollider#1557]
The error received (using ubuntu) :

```

CALL STACK:
    MethodError:reportError   0x1ec2008
        arg this = <instance of PrimitiveFailedError>
    Nil:handleError   0x1d85798
        arg this = nil
        arg error = <instance of PrimitiveFailedError>
    Thread:handleError   0x1f98378
        arg this = <instance of Thread>
        arg error = <instance of PrimitiveFailedError>
    Object:throw   0x1d9bd38
        arg this = <instance of PrimitiveFailedError>
    Function:protect   0x1c89578
        arg this = <instance of Function>
        arg handler = <instance of Function>
        var result = <instance of PrimitiveFailedError>
    Interpreter:executeFile   0x3740eb8
        arg this = <instance of Interpreter>
        arg pathName = "simplePitchTrack.scd"
        arg args = [*0]
        var result = nil
        var saveExecutingPath = nil
    Process:interpretCmdLine   0x1c8c438
        arg this = <instance of Main>
^^ The preceding error dump is for ERROR: Primitive 'none' failed.
Failed.
RECEIVER: nil

```

Weirdly enough this ServerOptions.inDevices line works perfectly fine on OSX and there is no warning in the documentation that says that this property is platform specific.

Is there a different way to get a listing of the input devices on these platforms?

**Comment by gusano** [comment]
AFAIK this primitive is OSX only and yes, it should be documented.

On linux, sc uses jack devices, so you should set this via jack itself instead.

**Comment by dsiah** [comment]
how hard would it be to add this primitive to windows and linux?

**Comment by jamshark70** [comment]
It would be good to have in Windows. It wouldn't be useful in Linux, because device selection takes place in JACK. The server in Linux has no power to override JACK's configuration.

**Comment by scztt** [comment]
:+1: to adding a matching primitive for windows.

**Comment by LFSaw** [comment]
I saw this working on a windows machine:

```
s.options.device = "Focusrite USB 2.0 Audio Driver";
s.boot;
```

can we close this then?

**Comment by jamshark70** [comment]
> can we close this then?

No, your example uses the `device` method not the `devices` method. The two are totally different.

**Comment by LFSaw** [comment]
Just one letter makes so much difference...

---
http://tai-studio.org
