### ISSUE TITLE
equality between floats on sclang is unsound

### ISSUE THREAD

**Issue by telephon** [supercollider/supercollider#1558]
This example Daniel Mayer just posted on the list:
````
0.1 + 0.1 + 0.1 == 0.3
--> false
````
in the source: ````doSpecialBinaryArithMsg````

The origin seems to be:
````
case opEQ  :		SetBool(a, slotRawFloat(a) == slotRawFloat(b)); break;
case opNE  :		SetBool(a, slotRawFloat(a) != slotRawFloat(b)); break;
````

According to some sources (http://stackoverflow.com/questions/17333/most-effective-way-for-float-and-double-comparison), this should be more like:

````
bool AreSame(double a, double b)
{
    return fabs(a - b) < EPSILON;
}
````
where EPSILON is a suitably small step.

**Comment by danstowell** [comment]
This is not a bug, it's a standard quirk of IEEE floating-point. Quick example: Python also says False for the example given. I'd vote to close this.

We've discussed it plenty in the past, eg when implementing the unit tests (trying to work out what sort of tolerance we could permit on float equality). See UnitTest:assertFloatEquals()

**Comment by crucialfelix** [comment]
I don't think that supercollider should try to pretend that it doesn't use
floating point math.

All languages that I know of have separate methods for comparing floating
points


why you shouldn't use a fixed epsilon:

http://www.cygnus-software.com/papers/comparingfloats/comparingfloats.htm


this has a good implementation with the relative technique:

https://www.npmjs.com/package/almost-equal

**Comment by telephon** [comment]
Ok, good!

**Comment by telephon** [comment]
We could introduce ```?== ```` and ````?!=```` as operators, for "almost equal"

**Comment by LFSaw** [comment]
> But this makes it hard to specify absolute and relative tolerance.

via adverbs?

```
a ?==.0.001 b
```

hmm, hard to read...

**Comment by crucialfelix** [comment]
nobody will remember new operators. unless you are using them 100 times a day.

better to just use a method .almostEqual or .nearlyEqual or um ...

.equalWithPrecision

https://github.com/supercollider/supercollider/blob/25a296ff544f04850be2ce0f93282131d3c7d6d9/SCClassLibrary/Common/Math/SimpleNumber.sc#L122

**Comment by LFSaw** [comment]
:+1:

**Comment by telephon** [comment]
>why you shouldn't use a fixed epsilon: http://www.cygnus-software.com/papers/comparingfloats/comparingfloats.htm

So should I change ````equalWithPrecision````  to:

````
equalWithPrecision { arg that, precision=0.0001, relativePrecision=0;
		^absdif(this, that) < max(precision, relativePrecision * min(abs(this), abs(that)))
	}
````

**Comment by crucialfelix** [comment]
maybe,

but only do the math if relativePrecision != 0
