### ISSUE TITLE
Multichannel for long files recording is broken

### ISSUE THREAD

**Issue by gogobd** [supercollider/supercollider#1561]
I am having trouble generating long 4 channel files longer that 2 hours with SC 3.7a1. I was able to reproduce the problem with this code on TWO machines now, both OSX Yosemite using this code:

    (
        // Initialize 8 channels, only 4 will be used later:
        Server.default.quit;
        Server.default.options.device = nil;
        Server.default.options.numOutputBusChannels = 8;
        Server.default.options.sampleRate = 48000;
        Server.default.options.memSize = 1024 * 32;
        s = Server.default.boot;
    )

    (
      // This does not work as expected:

        var duration = 2.00 * 3600.0;   // 2 hours
    //    var duration = 10;   // 10 seconds

        s.recChannels = 4;
    //    s.recChannels = 2;
        s.recHeaderFormat = "WAV";
      
        x = {SinOsc.ar([440,441,880,881], 0, 0.05)};

        r = Routine.new({
            thisProcess.platform.recordingsDir.postln;
            s.prepareForRecord(thisProcess.platform.recordingsDir +/+ 'Test_out.' ++ s.recHeaderFormat);
            s.sync;
            "START: " ++ Date.getDate.postln;
          "DURATION: " ++ (duration / 3600.0) ++ "h".postln;
            s.record;
            t = x.play;
            wait(duration);
            t.free;
            s.stopRecording;
            "STOP: " ++ Date.getDate.postln;
        });

        r.run;
    )

While this code is executing I was using "watch" and "ffmpeg" to introspect the written file. Just a few seconds before x.stopRecording; the file looks good:

    ffmpeg version 2.6.1 Copyright (c) 2000-2015 the FFmpeg developers
      built with Apple LLVM version 6.0 (clang-600.0.57) (based on LLVM 3.5svn)
      configuration: --prefix=/usr/local/Cellar/ffmpeg/2.6.1 --enable-shared --enable-pthreads --enable-gpl --enable-version3 --enable-hardcoded-tables --enable-avresample --cc=clang --host-cflags=
     --host-ldflags= --enable-libx264 --enable-libmp3lame --enable-libvo-aacenc --enable-libxvid --enable-vda
      libavutil      54. 20.100 / 54. 20.100
      libavcodec     56. 26.100 / 56. 26.100
      libavformat    56. 25.101 / 56. 25.101
      libavdevice    56.  4.100 / 56.  4.100
      libavfilter     5. 11.102 /  5. 11.102
      libavresample   2.  1.  0 /  2.  1.  0
      libswscale      3.  1.101 /  3.  1.101
      libswresample   1.  1.100 /  1.  1.100
      libpostproc    53.  3.100 / 53.  3.100
    [wav @ 0x7fd64080d400] Estimating duration from bitrate, this may be inaccurate
    Guessed Channel Layout for  Input Stream #0.0 : 4.0
    Input #0, wav, from '/Users/georg/Music/SuperCollider Recordings/Test_out.WAV':
      Duration: 01:59:36.87, bitrate: 6144 kb/s
        Stream #0:0: Audio: pcm_f32le ([3][0][0][0] / 0x0003), 48000 Hz, 4 channels, flt, 6144 kb/s
    At least one output file must be specified

But unfortunately, as soon as the recording is being ended the file gets corrupted:

    ffmpeg version 2.6.1 Copyright (c) 2000-2015 the FFmpeg developers
      built with Apple LLVM version 6.0 (clang-600.0.57) (based on LLVM 3.5svn)
      configuration: --prefix=/usr/local/Cellar/ffmpeg/2.6.1 --enable-shared --enable-pthreads --enable-gpl --enable-version3 --enable-hardcoded-tables --enable-avresample --cc=clang --host-cflags=
     --host-ldflags= --enable-libx264 --enable-libmp3lame --enable-libvo-aacenc --enable-libxvid --enable-vda
      libavutil      54. 20.100 / 54. 20.100
      libavcodec     56. 26.100 / 56. 26.100
      libavformat    56. 25.101 / 56. 25.101
      libavdevice    56.  4.100 / 56.  4.100
      libavfilter     5. 11.102 /  5. 11.102
      libavresample   2.  1.  0 /  2.  1.  0
      libswscale      3.  1.101 /  3.  1.101
      libswresample   1.  1.100 /  1.  1.100
      libpostproc    53.  3.100 / 53.  3.100
    Guessed Channel Layout for  Input Stream #0.0 : 4.0
    Input #0, wav, from '/Users/georg/Music/SuperCollider Recordings/Test_out.WAV':
      Duration: 00:26:47.24, bitrate: 27522 kb/s
        Stream #0:0: Audio: pcm_f32le ([3][0][0][0] / 0x0003), 48000 Hz, 4 channels, flt, 6144 kb/s
    At least one output file must be specified

On the other machine the corrupted file looks like this:

    ffmpeg version 2.6.2 Copyright (c) 2000-2015 the FFmpeg developers
      built with Apple LLVM version 6.1.0 (clang-602.0.49) (based on LLVM 3.6.0svn)
      configuration: --prefix=/opt/local --enable-swscale --enable-avfilter --enable-avresample --enable-libmp3lam
    e --enable-libvorbis --enable-libopus --enable-libtheora --enable-libschroedinger --enable-libopenjpeg --enabl
    e-libmodplug --enable-libvpx --enable-libspeex --enable-libass --enable-libbluray --enable-lzma --enable-gnutl
    s --enable-fontconfig --enable-libfreetype --enable-libfribidi --disable-indev=jack --disable-outdev=xv --mand
    ir=/opt/local/share/man --enable-shared --enable-pthreads --cc=/usr/bin/clang --enable-vda --arch=x86_64 --ena
    ble-yasm --enable-gpl --enable-postproc --enable-libx264 --enable-libxvid
      libavutil      54. 20.100 / 54. 20.100
      libavcodec     56. 26.100 / 56. 26.100
      libavformat    56. 25.101 / 56. 25.101
      libavdevice    56.  4.100 / 56.  4.100
      libavfilter     5. 11.102 /  5. 11.102
      libavresample   2.  1.  0 /  2.  1.  0
      libswscale      3.  1.101 /  3.  1.101
      libswresample   1.  1.100 /  1.  1.100
      libpostproc    53.  3.100 / 53.  3.100
    Guessed Channel Layout for  Input Stream #0.0 : 4.0
    Input #0, wav, from '/Users/bernhard/Music/SuperCollider Recordings/Test_out.WAV':
      Duration: 00:26:47.59, bitrate: 27517 kb/s
        Stream #0:0: Audio: pcm_f32le ([3][0][0][0] / 0x0003), 48000 Hz, 4 channels, flt, 6144 kb/s
    At least one output file must be specified

Shorter recordings seem to be fine, stereo seems to work, too. I hope that someone is able to pin down the problem. I was already compiling SC from git-sources and swapped out libsndfile to a (brew-installed) libsndfile-1.0.25 - but that did NOT fix the problem for me. :-(

**Comment by jamshark70** [comment]
IIUC, the WAV file format simply cannot hold enough samples for the length of file that you want. You'll have to use a more modern file format.

There is nothing SC can do about this.

**Comment by miguel-negrao** [comment]
maybe try with CAF file format ?

On 25-06-2015 10:52, Georg Gogo. BERNHARD wrote:
> I am having trouble generating long 4 channel files longer that 2 hours
> with SC 3.7a1. I was able to reproduce the problem with this code on TWO
> machines now, both OSX Yosemite using this code:
> 
> |(
>     // Initialize 8 channels, only 4 will be used later:
>     Server.default.quit;
>     Server.default.options.device = nil;
>     Server.default.options.numOutputBusChannels = 8;
>     Server.default.options.sampleRate = 48000;
>     Server.default.options.memSize = 1024 * 32;
>     s = Server.default.boot;
> )
> 
> (
>   // This does not work as expected:
> 
>     var duration = 2.00 * 3600.0;   // 2 hours
> //    var duration = 10;   // 10 seconds
> 
>     s.recChannels = 4;
> //    s.recChannels = 2;
>     s.recHeaderFormat = "WAV";
> 
>     x = {SinOsc.ar([440,441,880,881], 0, 0.05)};
> 
>     r = Routine.new({
>         thisProcess.platform.recordingsDir.postln;
>         s.prepareForRecord(thisProcess.platform.recordingsDir +/+ 'Test_out.' ++ s.recHeaderFormat);
>         s.sync;
>         "START: " ++ Date.getDate.postln;
>       "DURATION: " ++ (duration / 3600.0) ++ "h".postln;
>         s.record;
>         t = x.play;
>         wait(duration);
>         t.free;
>         s.stopRecording;
>         "STOP: " ++ Date.getDate.postln;
>     });
> 
>     r.run;
> )
> |
> 
> While this code is executing I was using "watch" and "ffmpeg" to
> introspect the written file. Just a few seconds before x.stopRecording;
> the file looks good:
> 
> |ffmpeg version 2.6.1 Copyright (c) 2000-2015 the FFmpeg developers
>   built with Apple LLVM version 6.0 (clang-600.0.57) (based on LLVM 3.5svn)
>   configuration: --prefix=/usr/local/Cellar/ffmpeg/2.6.1 --enable-shared --enable-pthreads --enable-gpl --enable-version3 --enable-hardcoded-tables --enable-avresample --cc=clang --host-cflags=
>  --host-ldflags= --enable-libx264 --enable-libmp3lame --enable-libvo-aacenc --enable-libxvid --enable-vda
>   libavutil      54. 20.100 / 54. 20.100
>   libavcodec     56. 26.100 / 56. 26.100
>   libavformat    56. 25.101 / 56. 25.101
>   libavdevice    56.  4.100 / 56.  4.100
>   libavfilter     5. 11.102 /  5. 11.102
>   libavresample   2.  1.  0 /  2.  1.  0
>   libswscale      3.  1.101 /  3.  1.101
>   libswresample   1.  1.100 /  1.  1.100
>   libpostproc    53.  3.100 / 53.  3.100
> [wav @ 0x7fd64080d400] Estimating duration from bitrate, this may be inaccurate
> Guessed Channel Layout for  Input Stream #0.0 : 4.0
> Input #0, wav, from '/Users/georg/Music/SuperCollider Recordings/Test_out.WAV':
>   Duration: 01:59:36.87, bitrate: 6144 kb/s
>     Stream #0:0: Audio: pcm_f32le ([3][0][0][0] / 0x0003), 48000 Hz, 4 channels, flt, 6144 kb/s
> At least one output file must be specified
> |
> 
> But unfortunately, as soon as the recording is being ended the file gets
> corrupted:
> 
> |ffmpeg version 2.6.1 Copyright (c) 2000-2015 the FFmpeg developers
>   built with Apple LLVM version 6.0 (clang-600.0.57) (based on LLVM 3.5svn)
>   configuration: --prefix=/usr/local/Cellar/ffmpeg/2.6.1 --enable-shared --enable-pthreads --enable-gpl --enable-version3 --enable-hardcoded-tables --enable-avresample --cc=clang --host-cflags=
>  --host-ldflags= --enable-libx264 --enable-libmp3lame --enable-libvo-aacenc --enable-libxvid --enable-vda
>   libavutil      54. 20.100 / 54. 20.100
>   libavcodec     56. 26.100 / 56. 26.100
>   libavformat    56. 25.101 / 56. 25.101
>   libavdevice    56.  4.100 / 56.  4.100
>   libavfilter     5. 11.102 /  5. 11.102
>   libavresample   2.  1.  0 /  2.  1.  0
>   libswscale      3.  1.101 /  3.  1.101
>   libswresample   1.  1.100 /  1.  1.100
>   libpostproc    53.  3.100 / 53.  3.100
> Guessed Channel Layout for  Input Stream #0.0 : 4.0
> Input #0, wav, from '/Users/georg/Music/SuperCollider Recordings/Test_out.WAV':
>   Duration: 00:26:47.24, bitrate: 27522 kb/s
>     Stream #0:0: Audio: pcm_f32le ([3][0][0][0] / 0x0003), 48000 Hz, 4 channels, flt, 6144 kb/s
> At least one output file must be specified
> |
> 
> On the other machine the corrupted file looks like this:
> 
> |ffmpeg version 2.6.2 Copyright (c) 2000-2015 the FFmpeg developers
>   built with Apple LLVM version 6.1.0 (clang-602.0.49) (based on LLVM 3.6.0svn)
>   configuration: --prefix=/opt/local --enable-swscale --enable-avfilter --enable-avresample --enable-libmp3lam
> e --enable-libvorbis --enable-libopus --enable-libtheora --enable-libschroedinger --enable-libopenjpeg --enabl
> e-libmodplug --enable-libvpx --enable-libspeex --enable-libass --enable-libbluray --enable-lzma --enable-gnutl
> s --enable-fontconfig --enable-libfreetype --enable-libfribidi --disable-indev=jack --disable-outdev=xv --mand
> ir=/opt/local/share/man --enable-shared --enable-pthreads --cc=/usr/bin/clang --enable-vda --arch=x86_64 --ena
> ble-yasm --enable-gpl --enable-postproc --enable-libx264 --enable-libxvid
>   libavutil      54. 20.100 / 54. 20.100
>   libavcodec     56. 26.100 / 56. 26.100
>   libavformat    56. 25.101 / 56. 25.101
>   libavdevice    56.  4.100 / 56.  4.100
>   libavfilter     5. 11.102 /  5. 11.102
>   libavresample   2.  1.  0 /  2.  1.  0
>   libswscale      3.  1.101 /  3.  1.101
>   libswresample   1.  1.100 /  1.  1.100
>   libpostproc    53.  3.100 / 53.  3.100
> Guessed Channel Layout for  Input Stream #0.0 : 4.0
> Input #0, wav, from '/Users/bernhard/Music/SuperCollider Recordings/Test_out.WAV':
>   Duration: 00:26:47.59, bitrate: 27517 kb/s
>     Stream #0:0: Audio: pcm_f32le ([3][0][0][0] / 0x0003), 48000 Hz, 4 channels, flt, 6144 kb/s
> At least one output file must be specified
> |
> 
> Shorter recordings seem to be fine, stereo seems to work, too. I hope
> that someone is able to pin down the problem. I was already compiling SC
> from git-sources and swapped out libsndfile to a (brew-installed)
> libsndfile-1.0.25 - but that did NOT fix the problem for me. :-(
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/supercollider/supercollider/issues/1561>.
> 


-- 
Miguel Negrão
http://www.friendlyvirus.org/miguelnegrao

**Comment by gogobd** [comment]
Thanks to both of you, @jamshark70 for pointing out that limitation and @miguel-negrao for suggesting a better file format! I'll try my luck with .caf files now, thank you.

**Comment by gogobd** [comment]
Now I'm using .caf and all problems are gone! Thanks every 01!

**Comment by bagong** [comment]
Haha, yea, confirmed. Here too.
