### ISSUE TITLE
Writing to 4 outputs simultaneously corrupts at least one of the output files in 3.7alpha1

### ISSUE THREAD

**Issue by gogobd** [supercollider/supercollider#1565]
I've been struggling with 4ch recordings, so I decided to try to write output into 4 mono tracks instead. This code **works perfectly well on 3.6.6** but on 3.7alpha1 the first output file that's closed has a different file size and different audio length than the other files.

Here's the code that reproduces the problem:

```
(

var out_b0, out_b1, out_b2, out_b3;
var d0, d1, d2, d3;
var output;
var headerFmt = "WAV";
var sampleFmt = "int24";
var sf;
var in_b;
var path;

// This will record one channel to disk
SynthDef("DiskOut1ch", {arg channelnum, bufnum;
        DiskOut.ar(bufnum, In.ar(channelnum, 1));
}).send(s);

// path = Platform.resourceDir +/+ "sounds/a11wlk01.wav";
// path = Platform.resourceDir +/+ "sounds/a11wlk01-44_1.aiff";
path = Platform.resourceDir +/+ "sounds/SinedPink.aiff";

sf = SoundFile.new(path);
sf.openRead;
// sf.inspect;
sf.close;
sf.headerFormat.postln;
sf.sampleFormat.postln;
sf.numChannels.postln;
sf.sampleRate.postln;

// allocate disk i/o buffers
out_b0= Buffer.alloc(s, 262144, 1);
out_b1= Buffer.alloc(s, 262144, 1);
out_b2= Buffer.alloc(s, 262144, 1);
out_b3= Buffer.alloc(s, 262144, 1);

// allocate an output file for each channel and leave it open
out_b0.write(path ++ ".diskouttest_0.wav", headerFmt, sampleFmt, 0, 0, true);
out_b1.write(path ++ ".diskouttest_1.wav", headerFmt, sampleFmt, 0, 0, true);
out_b2.write(path ++ ".diskouttest_2.wav", headerFmt, sampleFmt, 0, 0, true);
out_b3.write(path ++ ".diskouttest_3.wav", headerFmt, sampleFmt, 0, 0, true);

// the output
in_b = Buffer.cueSoundFile(s, path, 0, sf.numChannels);
f = {DiskIn.ar(in_b.numChannels, in_b.bufnum)} ;
t = Task.new({

    ("START:" ++ Date.getDate.asString).postln;
//    ("DURATION: " ++ (sf.duration).asSMPTE.format("hh:mm:ss")).postln;
    ("DURATION: " ++ (sf.duration)).postln;

    // create the diskout nodes; making sure it comes after the source
    d0 = Synth.tail(nil, "DiskOut1ch", ["channelnum", 0, "bufnum", out_b0.bufnum]);
    d1 = Synth.tail(nil, "DiskOut1ch", ["channelnum", 1, "bufnum", out_b1.bufnum]);
    d2 = Synth.tail(nil, "DiskOut1ch", ["channelnum", 2, "bufnum", out_b2.bufnum]);
    d3 = Synth.tail(nil, "DiskOut1ch", ["channelnum", 3, "bufnum", out_b3.bufnum]);

    wait(2);

    f.play;

    wait(sf.duration+5);

    f.stop;

    d3.free;
    d2.free;
    d1.free;
    d0.free;

    out_b3.close;
    out_b2.close;
    out_b1.close;
    out_b0.close;

    out_b3.free;
    out_b2.free;
    out_b1.free;
    out_b0.free;

    ("STOP:" ++ Date.getDate.asString).postln;
});

t.play;

)
```

**Comment by scztt** [comment]
@gogobd - Can you test the same thing before #1382 was merged? This build should do it:
http://supercollider.s3.amazonaws.com/builds/supercollider/supercollider/osx/SC-db05db8f4e4c08253676301353138c13b86acd04.zip

**Comment by muellmusik** [comment]
Providing #1382 is indeed the source, I am not convinced this is a bug, at least if the only issue is different file lengths.

The code above mixes synchronous and asynchronous commands, and does not create or stop synths as bundles. Under those circumstances there is no guarantee that synths will stop at the same time, or of when buffers will be closed.

(As an aside, the ```f.stop``` above is called on the Function, and does not free the DiskIn synth; it just does nothing. Does Object really need stop, actually?)

**Comment by scztt** [comment]
@muellmusik - I had the same thought re. bundling... here's a test case that bundles the commands and leaves all of the scheduling to the server, so there should be no possibility for jitter. The result of this SHOULD be four files of exactly 12 seconds, with a 10s test tone and 1s of padding on either side. However, I consistently see that whichever synth is free'd first (i.e. d0.free) has the correct length, and the length of every subsequent file is shorter. My worry is that ... this suggests to me that freeing the first synth may be causing some kind of state change that's affecting subsequent disk writes or synth frees, a worrisome prospect.

```
(

var out_b0, out_b1, out_b2, out_b3;
var bus;
var d0, d1, d2, d3;
var output;
var headerFmt = "WAV";
var sampleFmt = "int24";
var sf;
var in_b;
var path;

// This will record one channel to disk
SynthDef("DiskOut1ch", {arg channelnum, bufnum;
        DiskOut.ar(bufnum, In.ar(channelnum, 1));
}).add;

SynthDef("testTone", {
	arg out = 0;
	var sig = SinOsc.ar(Line.kr(20, 20000, 10, doneAction:2));
	Out.ar(out, sig);
}).add;

path = "~/Desktop/SinedPink.aiff".standardizePath;

// allocate disk i/o buffers
out_b0= Buffer.alloc(s, 262144, 1);
out_b1= Buffer.alloc(s, 262144, 1);
out_b2= Buffer.alloc(s, 262144, 1);
out_b3= Buffer.alloc(s, 262144, 1);

// allocate an output file for each channel and leave it open
out_b0.write(path ++ ".diskouttest_0.wav", headerFmt, sampleFmt, 0, 0, true);
out_b1.write(path ++ ".diskouttest_1.wav", headerFmt, sampleFmt, 0, 0, true);
out_b2.write(path ++ ".diskouttest_2.wav", headerFmt, sampleFmt, 0, 0, true);
out_b3.write(path ++ ".diskouttest_3.wav", headerFmt, sampleFmt, 0, 0, true);

bus = Bus.audio(s, 1);

fork {
    ("START:" ++ Date.getDate.asString).postln;
    ("DURATION: " ++ (10)).postln;

    // create the diskout nodes; making sure it comes after the source
	// 00:01 - recording starts
	s.makeBundle(1, {
		d0 = Synth.tail(nil, "DiskOut1ch", ["channelnum", bus.index, "bufnum", out_b0.bufnum]);
		d1 = Synth.tail(nil, "DiskOut1ch", ["channelnum", bus.index, "bufnum", out_b1.bufnum]);
		d2 = Synth.tail(nil, "DiskOut1ch", ["channelnum", bus.index, "bufnum", out_b2.bufnum]);
		d3 = Synth.tail(nil, "DiskOut1ch", ["channelnum", bus.index, "bufnum", out_b3.bufnum]);		
	});

	// 00:02 - test tone starts
	s.makeBundle(2, {
		Synth.head(nil, "testTone", args:[\out, bus.index]);
	});

	// 00:12 - test tone ends

	// 00:13 - recording ends
	s.makeBundle(13, {
		d0.free;
		d1.free;
		d2.free;
		d3.free;
		
		out_b3.close;
		out_b2.close;
		out_b1.close;
		out_b0.close;
		
		out_b3.free;
		out_b2.free;
		out_b1.free;
		out_b0.free;
	});
	
	13.wait;
	("DONE:" ++ Date.getDate.asString).postln;
};

)
```

**Comment by scztt** [comment]
A few more findings:
- If you either don't free the synths, or pause them instead of freeing, all of the files are the shorter (incorrect) length.
- If you put the diskout ugens in a group and free via deepFree, the problem persists.
- If you schedule the buffer .close and .free's slightly later than the synth .free's, then the file lengths are correct (in fact, the .close has to be in the same bundle as the synth frees to exhibit the bug).

**Comment by scztt** [comment]
Ah, looks like maybe `sf_close(buf->sndfile);` in `BufCloseCmd::Stage2` needs to be queued on the disk writer thread (and the same in BufFreeCmd). I feel like there was a discussion about that exact thing w/r/t the original bug?

The change is simple, but I think it's a little too high-risk for 3.7?

**Comment by muellmusik** [comment]
So is the guess that the close is happening on the async thread *before* the DiskOut Dtors have all run?

**Comment by muellmusik** [comment]
If the change is simple, I'd say test and include. Otherwise we're releasing with one bug replacing another.

But are you sure that a) #1382 causes this, and b) that they will be cued before the write message in the Dtor?

**Comment by scztt** [comment]
I don't think #1382 causes it per se - I think #1382 just fixes it in some-but-not-all cases. In 3.6, NONE of the buffers had the right length - in 3.7 after #1382 - ONLY in cases where you're recording to multiple files - the first file has the right length, but the rest may exhibit the old bug. In all common single file recording scenarios, the length should be correct.

**Comment by dyfer** [comment]
I believe that this is not an issue anymore in 3.13. Feel free to reopen in case this bug still persists.
