### ISSUE TITLE
remove stale/closed/merged branches from github repo

### ISSUE THREAD

**Issue by LFSaw** [supercollider/supercollider#1577]
looking at the list of (stale) branches in the github repository
      https://github.com/supercollider/supercollider/branches/stale

I wondered if we should do a cleanup of the repository...

**Comment by LFSaw** [comment]
Here's a list of all (currently) stale branches. 
For now, I removed only the ones that are merged or closed (indicated by a checked box).
Next, I will remove all that are older than 1 year. 

+ [ ] jmccartney Updated 8 years ago by Ryan Brown
+ [ ] linux-dev Updated 8 years ago by Ryan Brown
+ [ ] sc64 Updated 8 years ago by Ryan Brown
+ [ ] summer2004-1 Updated 8 years ago by Ryan Brown
+ [ ] universal Updated 8 years ago by Ryan Brown
+ [ ] users Updated 8 years ago by Ryan Brown
+ [ ] nova-simd Updated 6 years ago by Tim Blechmann
+ [ ] reorganize-source-tree Updated 5 years ago by timblechmann
+ [ ] supernova Updated 5 years ago by timblechmann
+ [ ] 10_4_fix Updated 5 years ago by danstowell
+ [ ] scdoc Updated 4 years ago by lijon
+ [ ] Version-3.4-Win32 Updated 4 years ago by cfrb
+ [ ] quarks/enhancements Updated 4 years ago by jleben
+ [ ] topic/scelfork Updated 4 years ago by timblechmann
+ [x] subprocess Updated 4 years ago by lijon
+ [ ] topic/recurringnodes Updated 4 years ago by James Harkins
+ [ ] sced3_3.4 Updated 4 years ago by danstowell
+ [ ] osx104master Updated 3 years ago by danstowell
+ [ ] topic/win-3.5-rc1 Updated 3 years ago by jleben
+ [ ] topic/win-3.5-rc2 Updated 3 years ago by jleben
+ [ ] topic/OSX_HID_Fix Updated 3 years ago by joshpar
+ [ ] topic/supernova_osx Updated 3 years ago by timblechmann
+ [ ] topic/supernova_llvm Updated 3 years ago by timblechmann
+ [ ] topic/supernova_threadlocal_wires Updated 3 years ago by timblechmann
+ [ ] 3.4 Updated 3 years ago by joshpar
+ [ ] topic/sclang_nested_bundle Updated 3 years ago by timblechmann
+ [ ] topic/intrusive_muladds Updated 3 years ago by timblechmann
+ [ ] topic/ide-style Updated 3 years ago by jleben
+ [ ] topic/c++11 Updated 2 years ago by timblechmann
+ [ ] topic/yamlcpp-0.5 Updated 2 years ago by timblechmann
+ [ ] topic/qimage Updated 2 years ago by jleben
+ [ ] 3.5 Updated 2 years ago by jleben
+ [ ] topic/qt5 Updated 2 years ago by timblechmann
+ [ ] topic/bundle_pa Updated 2 years ago by timblechmann
+ [x] ide-editor-improvements Updated 2 years ago by muellmusik
+ [ ] sced3python3 Updated 2 years ago by danstowell
+ [x] AddEditableToWebView Updated 2 years ago by muellmusik
+ [x] ide-editor-improvements-improvements Updated 2 years ago by muellmusik
+ [x] fixOpenDocument Updated 2 years ago by muellmusik
+ [x] matchLangIP Updated 2 years ago by muellmusik
+ [x] serverMultiClient Updated 2 years ago by muellmusik
+ [x] Better-recvOSCMessage-timing Updated a year ago by muellmusik
+ [x] fix-corruption Updated a year ago by muellmusik
+ [ ] hid Updated a year ago by adcxyz
+ [x] fix-ctrl-w Updated a year ago by muellmusik
+ [ ] removing-general-hid Updated a year ago by Julian Rohrhuber
+ [ ] topic/ide-themes Updated a year ago by scztt
+ [ ] Rework-Splits Updated a year ago by LucaDanieli
+ [x] netbsd Updated 10 months ago by danstowell
+ [ ] travis-test Updated 9 months ago by scztt
+ [x] fix-TCP Updated 8 months ago by muellmusik
+ [x] More-Document Updated 8 months ago by muellmusik
+ [ ] 3.6 Updated 5 months ago by James Harkins
+ [x] qt52 Updated 4 months ago by scztt
+ [ ] topic/sclang-app Updated 4 months ago by scztt
+ [ ] topic/ui-refresh Updated 3 months ago by scztt
+ [x] topic/fix-doc-modified-warnings Updated 3 months ago by scztt

**Comment by LFSaw** [comment]
Here's a list of all (currently) active branches.
I will remove all closed or merged branches older than a month.

+ [ ] topic/scwin3.7 Updated 10 hours ago by bagong
+ [ ] topic/null-characters Updated 2 days ago by telephon
+ [ ] topic/refactor-server-status Updated 4 days ago by telephon
+ [ ] fix_SCScope_on_internal Updated 11 days ago by adcxyz
+ [ ] valueActionIfChanged Updated 12 days ago by adcxyz
+ [ ] topic/unresponsive-server Updated 15 days ago by telephon
+ [ ] topic/fix-display-help-widget Updated 22 days ago by scztt
+ [ ] topic/fix-scrollbar-hiding-osx Updated 23 days ago by scztt
+ [ ] topic/fix-default-fonts Updated 24 days ago by scztt
+ [ ] topic/fix-alpha1-vers-num Updated a month ago by scztt
+ [ ] topic/fix-incorrect-modifiers Updated a month ago by scztt
+ [ ] topic/fix-completion-help-crash Updated a month ago by scztt
+ [ ] topic/fix-unprintable-keydown-events Updated a month ago by scztt
+ [ ] topic/fix-visible-origin-on-new-view Updated a month ago by scztt
+ [ ] topic-phasor-generalisation Updated a month ago by telephon
+ [ ] topic/protect-quarks-data-value Updated 2 months ago by scztt
+ [ ] topic/fix-prevent-setproperty-in-drawFunc-crash Updated 2 months ago by scztt
+ [ ] topic/fix-envgen-untriggered-done-action Updated 2 months ago by scztt
+ [ ] topic/fix-dependency-versions-and-case-problems Updated 3 months ago by scztt
+ [ ] topic/fix-quarks-load-non-local Updated 3 months ago by scztt 
+ [ ] topic/fix-parse-quark-url-refspec Updated 3 months ago by scztt
+ [ ] topic/fix-focus-after-toolbox Updated 3 months ago by scztt
+ [ ] topic/fix-format-eats-backslashes Updated 3 months ago by scztt
+ [ ] topic/recent-files-for-session-switch Updated 3 months ago by scztt
+ [ ] fix-DiskOut Updated 3 months ago by muellmusik

**Comment by muellmusik** [comment]
Please do not remove Rework-Splits #1155. This involves some highly desired features (e.g. separate windows in the IDE), and was only held up due to one demand that the changes be reimplemented as an option.

Unfortunately it has since diverged substantially from master (it's pre-Qt5), and I don't have enough time at the moment to commit to taking this forward. Similarly, the internship which paid Luca for his work on this finished last Autumn, and he has research work to undertake.

But the branch should definitely be retained as a base for updating or as a resource for anyone wishing to take this on (please dive in if you're interested!). It was a lot of work, especially by Luca, but also by me and some nice contributions from @scztt. As it seems at least some of the features are very likely to find their way into the IDE eventually, it would be silly to make people start over.

**Comment by crucialfelix** [comment]
please leave jmccartney, its the historical record of the first dump

**Comment by danstowell** [comment]
@crucialfelix might be worth adding a tag on jmccartney? just to help point at it

**Comment by crucialfelix** [comment]
its basically just the first commit I think, but we made an SVN branch out
of it to keep it for whatever reason (like if JMC quit apple and came back
and hated everything we did)

**Comment by telephon** [comment]
• topic-phasor-generalisation

is unmerged and has potentially useful features. Not important now, but better keep it.

**Comment by LFSaw** [comment]
btw., removing branches on github will not force remove them in local repositories. so there is a good chance that all those branches will be floating around somewhere, maybe even here: https://github.com/supercollider/supercollider/network

**Comment by telephon** [comment]
ok, good to know.

**Comment by LFSaw** [comment]
@scztt, how about the https://github.com/supercollider/supercollider/tree/topic/fix-parse-quark-url-refspec branch?

**Comment by snappizz** [comment]
Is there some way to determine whether a branch has been merged into master?

**Comment by brianlheim** [comment]
@snappizz 
```
git branch -r --merged master | grep upstream
```
will work from local terminal (grep pipe is optional for showing only the merged branches for SC).

**Comment by brianlheim** [comment]
Bump - I deleted all branches that seemed like obvious candidates, we're down to 32 now.
@scztt , @telephon , @timblechmann , you have some stale branches open that aren't mentioned above, could you take a look [here](https://github.com/supercollider/supercollider/branches) and let us know if any of them can be deleted?

Thanks.

**Comment by brianlheim** [comment]
We're at 27 branches now, and I think most of the remaining stale branches have valuable commits worth keeping around. Does anyone have objections to closing this?

**Comment by bagong** [comment]
Only a closed issue is a good issue ;)
