### ISSUE TITLE
server crashes with unallocated buffer setn

### ISSUE THREAD

**Issue by dnniejth** [supercollider/supercollider#1586]
Here it is:
b = Buffer.alloc(s, 1024); b.setn(0,Env.new(-3**(1..9)/(-3**9)++0, (1..7), [-4]).asSignal(512).asWavetable);

**Comment by jamshark70** [comment]
Not reproducible in Linux, current master: No crash.

Which OS, and SC version, are you using? Because the issue doesn't occur in all environments.

Also, please use markdown code tags (backticks). Github interprets the exponentiation operators as boldface above. The corrected example is:

```
b = Buffer.alloc(s, 1024); b.setn(0,Env.new(-3 ** (1..9)/(-3 ** 9)++0, (1..7), [-4]).asSignal(512).asWavetable);
```

**Comment by jamshark70** [comment]
Oh wait -- it is reproducible using supernova.

I can't reproduce it using scsynth.

@dnniejth Can you please confirm all the components you're using? SC version, OS (and version), and scsynth or supernova?

**Comment by jamshark70** [comment]
In supernova, b_set is also affected:

```
Server.program = "exec supernova";
s.boot;
s.sendMsg(\b_set, 0, 0, 0);   // crash
```

**Comment by dnniejth** [comment]
SuperCollider is 3.6.6 on OSX 10.9.5,

**Comment by dnniejth** [comment]
SuperCollider 3.7 crashes even more reliantly on OSX 10.9.5

**Comment by jamshark70** [comment]
I have also tested scsynth in Windows (3.7 alpha 1, 32-bit mingw build) and it doesn't crash. So, your scsynth issue here is Mac-specific. I'll mark the issue for OSX, then.

Can a developer on Mac confirm the crash?

(The supernova crash is likely a separate issue. I'll open another bug report for it later.)

**Comment by telephon** [comment]
Yes, I can confirm it on OS X 10.10

**Comment by scztt** [comment]
Huh, I can't repro with scsynth, and wouldn't expect to - meth_b_setn has:
```	
SndBuf* buf = World_GetBuf(inWorld, bufindex);
if (!buf) return kSCErr_Failed;
```
and...
``` if (end < 0 || start >= numSamples) continue; ```

...which should protect both the unallocated buffer case, and the too-many-samples case. At first glance, supernova's setn has neither protection, which would explain the crash. I think supernovas get_buffer throws in case of an unallocated synth, so it's possible the crash is happening in exception handling code elsewhere.

**Comment by scztt** [comment]
@dnniejth - Can you post the crash stack you're seeing on mac?

**Comment by vivid-synth** [comment]
@telephon (or @dnniejth ) can you still repro? Otherwise I think we should close.

Side note: @jamshark70 did you get a chance to file your separate supernova issue?

**Comment by telephon** [comment]
I can't reproduce it now.

**Comment by dyfer** [comment]
This doesn't seem to be a problem anymore. Feel free to reopen in case it still occurs.
