### ISSUE TITLE
Shortcuts to for booting / quitting interpreter

### ISSUE THREAD

**Issue by tonekk** [supercollider/supercollider#1617]
The interpreter crashes quite often.
Would be great to have shortcuts here:
<img width="319" alt="screen shot 2015-07-23 at 21 02 46" src="https://cloud.githubusercontent.com/assets/3327396/8859540/361c4b8a-317e-11e5-8288-8992e459d52a.png">

Would also submit a PR, but I'm quite out of business with QT ;)

**Comment by scztt** [comment]
You can set shortcuts for those in Preferences->Shortcuts.

If you're seeing interpreter crashes, can you post an issue / issues describing how you got the crash, along with a crash stack if possible? (It's easy to get them after the fact on mac via Console.app -> User Diagnostic Reports (look for .crash files)).

**Comment by telephon** [comment]
Interpreter crashes should be rare – probably something else is wrong!

**Comment by LFSaw** [comment]
As @scztt points out:

> You can set shortcuts for those in Preferences->Shortcuts.

I assume this to be closed then.
