### ISSUE TITLE
Feature Request: Platform.applicationDir (was ".load changed")

### ISSUE THREAD

**Issue by thormagnusson** [supercollider/supercollider#1621]
On OSX <3.6, the String:load would look up a file next to the SuperCollider.app, as in:
"test.scd".load
Now, the cwd is: /
This is probably a changed behaviour in File:getcwd which should? return the application location.

If not, we need a method in Platform called
Platform.applicationDir
as we don't have this functionality in SuperCollider now, as far as I can see.
For backwards compatibility it's probably better to change the current behaviour of File:getcwd.

**Comment by timblechmann** [comment]
`File:getcwd` should return the cwd, nothing else. also, what's your proposal on the semantics for `applicationDir` on linux and osx?

**Comment by thormagnusson** [comment]
That's a changed behaviour. But it's ok with me. I just need to know where I find the app on all platforms without spending hours on it (so I can instruct users to place their files there). My proposal on the OSX would be something like this

Platform:

applicationDir {
	^Platform.resourceDir++"/../../../";
}

If indeed that works (at least this works:  ("open"+Platform.resourceDir++"/../../../").unixCmd )

But I can see that all these methods (platformDir, resourceDir, userConfigDir) are primitives in Platform, so could there be a primitive method that would return this location on all platforms?

**Comment by danstowell** [comment]
See this [related stackoverflow question](http://stackoverflow.com/questions/4521151/mac-app-default-working-directory) which implies maybe it's a change in osx, not a change with us...? Also [this related question with a bit of code](http://stackoverflow.com/questions/516200/relative-paths-not-working-in-xcode-c).

However it could perhaps be "caused" by us and our change of build systems over the years. I seem to remember that years ago when I was looking at app bundling, it was possible to specify what cwd the Mac .app bundle would use, but I don't have any evidence for that.

A cwd of '/' may well be "true" on Mac but it's useless, so it would seem reasonable to me that launching the Mac app might deliberately set the cwd to something useful, if that were possible?

**Comment by muellmusik** [comment]
Well, I would certainly expect that when you launch SC from a shell it would inherit the cwd from the shell. As to what it should be when you launch from the finder, I don't know...

I can confirm that the cwd is different when launching from Xcode. I get: ```/code/git_SC/SuperCollider/buildQt5-2/editors/sc-ide/Debug```

**Comment by danstowell** [comment]
@muellmusik indeed I'm referring to the clicking-on-the-app case, though I don't know that it's possible to detect that as a specific case

**Comment by scztt** [comment]
I think adding a Platform:applicationDir is the right choice. 

@thormagnusson - can you either add a new issue and mark it as enhancement, or just retitle this one as a feature request?

**Comment by timblechmann** [comment]
btw, there is no equivalent of an 'application directory' on linux.

**Comment by thormagnusson** [comment]
Related to this feature request, I suggest that Platform.userAppSupportDir will use a directory which is visible to users. I'm thinking here of novices, non-programmers who use packaged software written in SuperCollider. On both OSX and Linux this directory is hidden. Who knows where it is on Windows.

**Comment by gusano** [comment]
> I suggest that Platform.userAppSupportDir will use a directory which is visible to users

I have to disagree on that one.
Even for novices using linux/osx, it's really not that hard to learn how to navigate in an hidden folder inside your $HOME directory. You just need to know which one it is.

**Comment by jamshark70** [comment]
The reason why the folder is hidden in Linux is because of the [Filesystem Hierarchy Standard](https://en.m.wikipedia.org/wiki/Filesystem_Hierarchy_Standard). Specifically -- http://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch03s08.html#homeReferences --

> 3.8.2. Requirements
> 
> User specific configuration files for applications are stored in the user's home directory in a file that starts with the '.' character (a "dot file"). If an application needs to create more than one dot file then they should be placed in a subdirectory with a name starting with a '.' character, (a "dot directory"). In this case the configuration files should not start with the '.' character.8
> 
> 8 It is recommended that, apart from autosave and lock files, programs should refrain from creating non dot files or directories in a home directory without user consent.

We had discussed the pros and cons of adhering to, or violating, the standard. I think it's reasonable to follow the standard.

"novices, non-programmers who use packaged software written in SuperCollider" -- I don't think we want them rooting around SC configuration files without any knowledge of what the files are for. I'd rather the app make a symlink to specific directories that the user will need to access. (On my Linux system, I have a symlink to the user app support directory under ~/share/SC.)

**Comment by scztt** [comment]
@thormagnusson - What's are your uses cases for needed to actually browse / play around in userAppSupportDir?

**Comment by timblechmann** [comment]
> The reason why the folder is hidden in Linux is because of the
> Filesystem Hierarchy Standard
> <https://en.m.wikipedia.org/wiki/Filesystem_Hierarchy_Standard>.
> Specifically --
> http://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch03s08.html#homeReferences
> --
> 
>     3.8.2. Requirements
> 
>     User specific configuration files for applications are stored in the
>     user's home directory in a file that starts with the '.' character
>     (a "dot file"). If an application needs to create more than one dot
>     file then they should be placed in a subdirectory with a name
>     starting with a '.' character, (a "dot directory"). In this case the
>     configuration files should not start with the '.' character.8
> 
>     8 It is recommended that, apart from autosave and lock files,
>     programs should refrain from creating non dot files or directories
>     in a home directory without user consent.
> 
> We had discussed the pros and cons of adhering to, or violating, the
> standard. I think it's reasonable to follow the standard.
> 
> "novices, non-programmers who use packaged software written in
> SuperCollider" -- I don't think we want them rooting around SC
> configuration files without any knowledge of what the files are for. I'd
> rather the app make a symlink to specific directories that the user will
> need to access. (On my Linux system, I have a symlink to the user app
> support directory under ~/share/SC.)

btw, the folder can be opened from the file menu of the IDE

**Comment by thormagnusson** [comment]
@scztt "What's are your uses cases for needed to actually browse / play around in userAppSupportDir?" 

I've tried to discuss this a little on sc-dev, but in short I'm making software for kids, usable for workshops. They need to place samples somewhere, and find SuperCollider's recordings somewhere. Out of many places, I thought it would be best to have a folder next to the .app/.exe called "projects" where they put different samples related the project they're working on.

I don't want to waste time in a workshop (or written tutorials) talking about hidden folders or trying to explain in a help file: "you put your recorded sound samples into a folder that Apple has decided to hide (and it's hidden on Linux too), but you can go into the terminal and ..." - for 12 year olds; this is a killer. 

So I need to be able to tell users where to put stuff and ideally not in hidden folders (where samples are placed in ~/.Library/Application Support/SuperCollider/blah, and recordings are found in ~/Music/SuperCollider Recordings). That's all good, the problem is that I can't be sure where the user has placed their executables (Desktop? Applications?) and it would be nice if SuperCollider would be able to know its location, as it did earlier. 

I see a solution, but it's a time consuming solution where I write platform specific code. So for me it would be handy to have a method like: applicationDir. 

BTW. I'm not using the IDE, but will start sclang from another process.

**Comment by jamshark70** [comment]
> I don't want to waste time in a workshop (or written tutorials) talking about hidden folders or trying to explain in a help file: "you put your recorded sound samples into a folder that Apple has decided to hide (and it's hidden on Linux too), but you can go into the terminal and ..." - for 12 year olds; this is a killer.

Or you could say, "You click this button, and the folder pops up in a file browser" -- where the button's action is `theDirectoryPath.openOS` -- or, on first launch, your app prompts the user to create a location (Dialog.savePanel) and writes this location into a text file under the userAppSupportDir.

There are tons of user friendly ways to handle this without changing SC's behavior for everybody.

**Comment by thormagnusson** [comment]
Ok. I'll do that. But quite the contrary to changing the "behaviour for everybody", I first asked whether we could continue the old Cocoa behaviour (for backwards compatibility) and if that isn't possible, I was wondering whether we could introduce a new method called Platform:applicationDir (this would be a new method, not changing any behaviour), which would make things possible that were possible pre-SCIDE (such as "file.scd".load relative to the application path, or [1,2,3].writeArchive("myArchive.blah") without having to pass full paths)

**Comment by jamshark70** [comment]
E.g.,

```
(
var file, path, samplePath, cond = Condition.new;
var win;

{
	path = Platform.userAppSupportDir +/+ "sampleDir.txt";
	if(File.exists(path)) {
		file = File(path, "r");
		protect {
			samplePath = file.getLine;
		} { file.close };
	} {
		win = Window("Choose location",
			Rect.aboutPoint(Window.screenBounds.center, 200, 75),
			resizable: false, border: false
		)
		.layout_(VLayout(
			StaticText().string_("Do you want to...?").align_(\center),
			HLayout(
				Button()
				.states_([["Choose an existing folder"]])
				.action_({
					win.close;
					FileDialog({ |p|
						samplePath = p;
						cond.unhang;
					}, nil, fileMode: 2, acceptMode: 0, stripResult: true);
				}),
				Button()
				.states_([["Create a new folder"]])
				.action_({
					win.close;
					Dialog.savePanel({ |p|
						samplePath = p;
						cond.unhang;
					});
				})
			)
		))
		.front;
		cond.hang;
		if(File.exists(samplePath.postcs).not) {
			// File.makeDir(samplePath);
			samplePath.debug("making dir");
		};
		// file = File(path, "w");
		// protect {
		// 	file << path << "\n";
		// } { file.close };
	};
	// ... continue ...
}.fork(AppClock);
)
```

**Comment by scztt** [comment]
@thormagnusson - I empathize... in that environment, anything more than one-two step instructions that never fail basically means you'll need 10+ minutes of walking around the room debugging problems. I'd tentatively suggest that you use the path of the .scd file(s) with code, not the application, to deal with soundfiles. It's a good pattern in general - I use a similar structure with most of my projects - is flexible if projects are relocated / reconfigured, and makes loading multiple files easy:
```~mysound = Buffer.read(s, thisProcess.nowExecutingPath +/+ "mysound.wav");```

```~files = (PathName(thisProcess.nowExecutingPath).pathOnly +/+ "sounds/*.wav").pathMatch```

**Comment by scztt** [comment]
Regarding application path - we obviously should expose it, but using it as a default seems like a problem, since OS's often don't allow write access to the locations where applications are stored - it's a bad pattern. I'd much prefer seeing us move to a pattern where you can (a) set a global "default path" (for things like loading samples, writing archives, etc), and (b) start to build functionality around setting it automatically when you e.g. load a "project folder" or some similar concept.

**Comment by thormagnusson** [comment]
Thanks James for the helpful code. From experience with this age group, it's still a bit problematic approach. But I think it's closer and I'm getting there. 

I just discovered that you can start sclang from the terminal like: ./sclang -d ../../ 
and you get the "applicationDir" as the default cwd (so now you can do "file.scd".load) 
Indeed you can cd into the SuperCollider.app folder and start up the language like:
./SuperCollider.app/Contents/MacOS/sclang
and you will be able to run "test.scd".load on a test.scd file located next to the application. - the IDE might use that call to the language on "booting interpreter" if people wanted to support old behaviour.

@scztt Good point on Application dir not having a write access. So I'm thinking I will default do ~/Documents. That seems like a better place for my users to keep files. Processing and Arduino does this by default. And if I'm not mistaken, OSX, Linux and Windows all have a ~/Documents folder, no?

**Comment by muellmusik** [comment]
> the IDE might use that call to the language on "booting interpreter" if people wanted to support old behaviour.

It could be a preference, I suppose.

**Comment by telephon** [comment]
@scztt @thormagnusson 
You don't even need ````mysound = Buffer.read(s, thisProcess.nowExecutingPath +/+ "mysound.wav");````

But this is enough:

````mysound = Buffer.read(s, "mysound.wav".resolveRelative);````

I always put everything in a folder and then ````loadRelative```` it.

**Comment by telephon** [comment]
Does that help?

**Comment by bagong** [comment]
Maybe interesting in this context #1978 

The standardised Documents folder on Linux, Windows and OSX is Platform.userHomeDir +/+ "Documents" (~ does not work on Windows). *Many* applications store their projects folders there (so many that I have stopped using it for my personal files ;) )
