### ISSUE TITLE
Qt TextView arrow keys should be of a Char type, not Nil

### ISSUE THREAD

**Issue by thormagnusson** [supercollider/supercollider#1625]
There is a different behaviour between Cocoa and Qt TextView in that arrow buttons return nil in Qt. This is not the case in Document, so I think this is a Qt TextView bug. Test code:

TextView.new(Window.new("test", Rect(200, 500, 500, 400)).front, Rect(0, 0, 500, 400))
    .keyDownAction_({arg doc, key, mod, unicode, keycode;
        [doc, key, mod, unicode, keycode].postln;
        key.class.postln;
        key.isAlpha.postln; // arrows return false on Cocoa but error in Qt
    })

Document.current.keyDownAction_({arg doc, key, mod, unicode, keycode;
        [doc, key, mod, unicode, keycode].postln;
        key.class.postln;
            key.isAlpha.postln; // works with Document (as opposed to TextView)
    })

**Comment by jamshark70** [comment]
See #1554. Apparently we are supposed to accept the inconvenience of testing `char.notNil` because nil is correct in principle (and supposedly the principle offsets the general pain-in-the-ass-ness of it). I have hardly enough negative things to say about this decision, but haven't swayed anyone yet.

**Comment by thormagnusson** [comment]
Thanks for referencing #1554, I see. But whatever decision is taken, it does not make sense to represent arrows as "Char" in Document and "Nil" in TextView. I suggest moving the behaviour of TextView in line with Document and older Cocoa SC.

**Comment by telephon** [comment]
> Apparently we are supposed to accept the inconvenience of testing char.notNil because nil is correct in principle.

I read the outcome of the discussion differently.

**Comment by brianlheim** [comment]
Should be fixed via #1632.
