### ISSUE TITLE
CocoaBridge seems dead, but examples and doc are still there

### ISSUE THREAD

**Issue by muellmusik** [supercollider/supercollider#1629]
Seems like the Cocoa bridge is dead. I don't know if this is by choice or just nobody wants to do the work to get it going again. If it's not going to be working, would make sense to remove the doc and the examples folder for 3.7

**Comment by LFSaw** [comment]
@scztt , what's your opinion on this? I'd say, stale it... (unless someone wants to put work to it)

**Comment by crucialfelix** [comment]
examples were removed in 3.7

PyrPrimitives still has initCocoaBridgePrimitives

supercollider/HelpSource/Classes/SCNSObject.schelp still exists

supercollider/SCClassLibrary/Common/osx/objC/plusAsNSReturn.sc refers to SCNSObject which is long gone
