### ISSUE TITLE
Closing fullscreen window will not end fullscreen mode

### ISSUE THREAD

**Issue by thormagnusson** [supercollider/supercollider#1633]
I've got some old code that works like this:

w = Window.new("test", Rect(100, 100, 800, 600), resizable: false).front;
w.fullScreen
w.close // and all closes

In Qt, the window closes and you're stuck with a black screen which you can't get rid of. The window is gone and you can't run the .endFullScreen on it.

So an additional command is required:

w = Window.new("test", Rect(100, 100, 800, 600), resizable: false).front;
w.fullScreen
w.endFullScreen // Qt requires this
w.close

I'm suggesting that this is not good and that .endFullScreen should be called on .close by default.

**Comment by scztt** [comment]
This is a duplicate of #1506
