### ISSUE TITLE
Under fedora, supercollider needs libatomic

### ISSUE THREAD

**Issue by ycollet** [supercollider/supercollider#1635]
I compiled supercollider from master branch on fedora 22 64 bits.
Supercollider needs to be linked against libatomic.
The workaround I found was to set CMAKE_EXE_LINKER_FLAGS=-latomic

**Comment by timblechmann** [comment]
boost.atomic requires libatomic on gcc-5.

**Comment by K0F** [comment]
It seems just supernova requires this lib, AFAIK this should be case for all gcc 5+ (confirming on gcc 5.2.1, debian 64 bit)

**Comment by timblechmann** [comment]
probably #1528 and #1649 would have to be merged

**Comment by susnux** [comment]
I had the same problem, but also I had to add pthread to get it build on openSUSE Tumbleweed.
Patches I created therefore:
pthread:
https://gist.github.com/susnux/e804074174ed2b086963
libatomic:
https://gist.github.com/susnux/32e293fb01586bbbdab8

**Comment by patrickdupuis** [comment]
I've recently built SC on Fedora 23 (gcc 5.1.1). Everything worked fine after I installed the Libatomic package. Maybe this needs to be mentioned in the Linux Readme? 

I think this issue can be closed.

**Comment by vivid-synth** [comment]
Should we close this?
