### ISSUE TITLE
Qt GUI: TextView's enterInterpretsSelection treats line wrapping like a hard line break

### ISSUE THREAD

**Issue by jamshark70** [supercollider/supercollider#1637]
```
(
t = TextView(nil, Rect(800, 200, 500, 400))
.font_(Font.monospace(24))
.string_("if(10.rand.even) { \"it was an even number\".postln } { \"it was an odd number\".postln };")
.select(2, 0)
.front;
)

t.currentLine;
```

Here, `t.currentLine` retrieves the entire line, stopping only at newline characters. But, if you ctrl-return, SC will try to evaluate a single *visual* line of code -- stopping where the long line wraps at the right margin. So you get a parse error.

The reason is in QcTextEdit.cpp (https://github.com/supercollider/supercollider/blob/master/QtCollider/widgets/QcTextEdit.cpp, lines 182-185):

```
    if ( !c.hasSelection() ) {
      c.movePosition( QTextCursor::StartOfLine );
      c.movePosition( QTextCursor::EndOfLine, QTextCursor::KeepAnchor );
    }
```

`StartOfLine` and `EndOfLine` must be going by visible, not textual, line breaks.

By contrast, `currentLine` returns `textCursor().block().text()` (line 105).

Shouldn't both use the same method to access the text? In particular, the enterInterpretsSelection behavior seems useless (and it's messing me up in my TextView-based live-coding interface...).

I propose: https://github.com/jamshark70/supercollider-rename/commit/fe6bc709d496f51bd2133ebb2f4bd69ce270d8f9.

**Comment by telephon** [comment]
>I propose: jamshark70@fe6bc70.

looks much better.
