### ISSUE TITLE
DetectSilence won't free if it never encounters nonzero value

### ISSUE THREAD

**Issue by telephon** [supercollider/supercollider#1639]
DetectSilence won't free if it never encounters nonzero value.

This can cause hanging notes e.g. when a filter should be freed after its input has become silent, but its sound input is zero from the beginning for some reason.

````
// this runs forever
SynthDef(\test, { DetectSilence.ar(DC.ar(0.0).poll, doneAction:2) }).add;
Synth(\test)

// this ends
SynthDef(\test, { DetectSilence.ar(Line.ar(1, 0, 0.2).poll, doneAction:2) }).add;
Synth(\test)
````

I'm not sure if this is by design though.

**Comment by timblechmann** [comment]
you might want to check the archive (iirc there was a discussion on this a few years back) ... it was done by design (you don't want DetectSilence to free a synth before the envelope has started)

**Comment by telephon** [comment]
OK, this makes sense, actually it is hidden in plain sight in the helpfile: "If the input signal starts with silence at the beginning of the synth's duration, then DetectSilence will wait indefinitely until the first sound before starting to monitor for silence."

**Comment by telephon** [comment]
Made clearer in 7da53a0c50fb93425ced939e9fc65141d72d6902
