### ISSUE TITLE
MIDI / HID init on OSX can crash interpreter when server is on

### ISSUE THREAD

**Issue by adcxyz** [supercollider/supercollider#1640]
```
// reproducer: 
// reboot interpreter, make sure server is off, then do:
s.boot;  
// wait till server is on, then do these in one line:
MIDIIn.connectAll; HID.findAvailable; 
// -> interpreter dies!

// Console says this:
24/08/15 17:07:20,824 MIDIServer[5912]: 17:07:20.823 ERROR:     0: 
24/08/15 17:07:20,905 MIDIServer[5912]: Bluetooth MIDI driver is starting ...
24/08/15 17:07:20,906 MIDIServer[5912]: Bluetooth MIDI driver finished starting.

so the crash seems to happen in the midi init primitive.

// the inits work fine when order is reversed : 
s.boot;
HID.findAvailable; MIDIIn.connectAll;  // works

// ... and also work when inside a fork
Server.killAll;
s.boot;
fork { 
    MIDIIn.connectAll; 
    123.postln; 
    HID.findAvailable; // dies
};
```

**Comment by LFSaw** [comment]
I can reproduce this on my recent build ( 96e17c2 ) on OSX.

**Comment by adcxyz** [comment]
tested with current master, still a problem: 
after The Line From Hell, the interpreter goes silent, no posting, no code evaluated, 
but does not report crashing.

**Comment by telephon** [comment]
can still reproduce this on macos.

**Comment by adcxyz** [comment]
can still reproduce this on macos.

**Comment by brianlheim** [comment]
PSA - it is much much more helpful to post an actual core dump when you are reproducing a crash, rather than just saying "it crashes over here". We should all get in the habit of doing this, because it takes practically 0 effort and can be very helpful for anyone who wants to investigate further. Crash logs on macOS are kept in ~/Library/Logs/DiagnosticReports. You can post the whole thing or just the backtrace for the crashing thread.

**Comment by gurk** [comment]
Another reproducer:

`AppClock.sched(0, {1}); HID.findAvailable;  // sclang hang`

hidapi calling the main run loop appears to be the cause, hence AppClock.sched().

Traced problem to this change in the hidapi library: https://github.com/signal11/hidapi/pull/31

The change introduces a call to the main run loop from hid_enumerate. This seems like an application level fix introduced into the library :/

Reverting the change in hidapi resolves the issue, don't know if there's a way to circumvent the issue without modifying hidapi itself.

[sample of sclang process during hang](https://github.com/supercollider/supercollider/files/3101569/sclang_hang_dump.txt)

**Comment by sensestage** [comment]
We have our own fork of the hidapi library anyways, so should be no
problem to make a change for that in our one.

It would be good though to leave a comment in that discussion that the
suggested change there does cause issues for applications who manage the
run loops themselves.
