### ISSUE TITLE
Triggering EnvGen with Impulse.ar crashes the server

### ISSUE THREAD

**Issue by michaeldzjap** [supercollider/supercollider#1642]
This seems to crash the server using the latest SC 3.7alpha1 build on osx 10.10.5
```
{ SinOsc.ar(440,0,EnvGen.ar(Env([0,1,0],[0,0.5],-3), Impulse.ar(1))) }.play
```

**Comment by jamshark70** [comment]
Confirmed, an audio rate trigger is definitely broken.

The latest commit as of this writing (730070ad4a29b319dc05bdd3ec26d493eda3ee21) changes the way envelope triggers behave. So, as a test, I rolled back to the immediately preceding commit, and the problem went away.

So 730070ad4a29b319dc05bdd3ec26d493eda3ee21 is the cause of this issue.

**Comment by telephon** [comment]
This was rolled back, so this works again.
