### ISSUE TITLE
d_removed

### ISSUE THREAD

**Issue by sonoro1234** [supercollider/supercollider#1648]
Hello,

I am implementing tcp comunication in my lua client.
The only error I get is receiving a malformed d_removed osc message.
This message is sent from GraphDef_Remove in SC_GraphDef.cpp:563
One explanation could be that this function were called from a different 
thread than the thread that calls SendDone for example.
My knowledge about scsynth threads is not so great so I am asking what you 
think about it

Best
victor

**Comment by sonoro1234** [comment]
PD: /status.reply is always in this malformed messages also

**Comment by telephon** [comment]
Seems to work now here, but I'm not sure. Can you check again?
````
SynthDef("xxx", { Silent.ar }).add;

s.sendMsg("/d_free", "xxx");
````
Then:
````
OSC Message Received:
	time: 3741.487259762
	address: a NetAddr(127.0.0.1, 57110)
	recvPort: 57120
	msg: [ /d_removed, xxx ]
````

**Comment by sonoro1234** [comment]
Fails erratically with TCP connection.
Get mixed message of /status.reply and /d_removed

**Comment by telephon** [comment]
Ah ok, so this is *only* with TCP.

**Comment by sonoro1234** [comment]
Yes but TCP is crucial for not loosing packets when there is a heavy traffic.
I have confirmed my hypothesis of wrong thread handling by inserting this code

```
std::thread::id this_id = std::this_thread::get_id();
std::cout << "thread " << this_id << " Sending from d_removed or whatever...\n";
```
in the relevant places.
d_removed is sent from a different thread that the other messages

**Comment by sonoro1234** [comment]
I could solve the threads issue with SendReplyCmd.
I need my previous PR #1659 being merged before making a new PR
(If not all my commits go to the same opened PR) :-(
