### ISSUE TITLE
OSCFunc with special recvPort can't be freed

### ISSUE THREAD

**Issue by redFrik** [supercollider/supercollider#1654]
if i set the recvPort to something other than 57120 i can't free osc responders.
```
o= OSCFunc({|msg| msg.postln}, \ttest, recvPort: 9123)
n= NetAddr("127.0.0.1", 9123);
n.sendMsg(\ttest, 1, 2, 3)
o.free
n.sendMsg(\ttest, 1, 2, 3) //it is still responding!
CmdPeriod.run
n.sendMsg(\ttest, 1, 2, 3) //still responding
```
OSCdef have the same problem.
latest sc3.7a0

**Comment by muellmusik** [comment]
Can't reproduce this @redFrik with latest master. Try that.

**Comment by adcxyz** [comment]
works in my current master as well, seems fixed.

**Comment by telephon** [comment]
But good to know that it is around in that version.
