### ISSUE TITLE
Windows File.existsCaseSensitive does not work for directories

### ISSUE THREAD

**Issue by jamshark70** [supercollider/supercollider#1668]
```
File.existsCaseSensitive(Platform.userAppSupportDir);
-> false
```

Digging in:

```
	*existsCaseSensitive { arg pathName;
		^if(systemIsCaseSensitive) {
			this.exists(pathName)
		} {
			(pathName.dirname+/+"*").pathMatch.detect{|x|x.compare(pathName)==0}.notNil
		}
	}
```

pathMatch returns *directory* paths with a trailing separator:

```
(Platform.userAppSupportDir.dirname+/+"*").pathMatch
-> [ a bunch of paths ... , C:\Users\hjh\AppData\Local\SuperCollider\ ]
```

... and the `compare` test does not account for this.

I can't do a PR right now but it should be an easy fix.

User impact: Completely breaks Quarks in Windows.

**Comment by telephon** [comment]
(are you running the windows branch (more or less) successfully)?

**Comment by jamshark70** [comment]
I don't have a Windows build environment, so I'm not exactly "running the Windows branch." I installed the most recently available 3.7 alpha package, and replaced the out-of-date Quarks code from the installer with the most recent from the repository.

Where you're supposed to be able to download ZIPs of the quark repositories that you want, and the new quarks system should recognize them and allow you to install them, this didn't happen. It took quite a bit of debugging to find the two problems:

- The current issue (existsCaseSensitive doesn't work for directories in Windows).
- Path-related regular expressions for Windows are wrong in the Quarks class.

Yesterday, I had a bit of time with the Windows machine in my school office (where I did the testing) and checked the diffs. Those two things are the only things I had to change to make Quarks *installation* work in Windows.

There's one other thing that we need, if we want SC/win to invoke msysgit to download quark repositories automatically. Currently the program name "git" is hardcoded, but in Windows, we need to invoke git through msysgit's cmd.exe. I have to doublecheck the exact command, but I did get SC to call git successfully in Windows.

**Comment by telephon** [comment]
Ah ok, yes this is a way to at least have one more or less operable windows version. There is  https://github.com/supercollider/supercollider/tree/topic/scwin3.7-fix-conflicts

But the discussion of the original branch suggests that someone would have to be able to maintain and care for it.

**Comment by crucialfelix** [comment]
the bug would also happen on linux or a mac if your file system is case sensitive.
