### ISSUE TITLE
NodeProxy fails to detect containing audiorate (irregularly)

### ISSUE THREAD

**Issue by K0F** [supercollider/supercollider#1672]
From time to time (quite often now) ProxySpace fails to detect NodeProxy's audio rate and treat it as it is a control rate generator.. this is resulting quite nasty sound of course.

Clearing a NodeProxy ```~a.clear;``` and defining i.e. ```~a.ar(2);``` first, sometimes helps but not always. I couldn't find the pattern of this behavior, but it can be really annoying when it got stuck.

Anyone experienced this lately?

Thanks

**Comment by telephon** [comment]
What version of supercollider you are using?

**Comment by K0F** [comment]
My version is very recent master: ```9498b6792252db44ed372b8eda803be8c79d3999```, the code can be as basic as this (it is hard to reproduce due to irregular behavior, though):

```
s.boot();
p=ProxySpace.push(s);

~a.ar(2);
~a={SinOsc.ar(440!2)};
~a.play();
```

**Comment by telephon** [comment]
I haven't been able to reproduce it. If you run across it again, can you try and find out the following?

````
~a.bus.dump
~a.monitor.ins
~a.monitor.outs
```

**Comment by K0F** [comment]
I am not sure if it makes sense, but I use primary VIm as an interface to SC.. irrationally speaking it could play some role as I didn't noticed similar behavior in SCide (???).

```
~a.bus.dump
```
outs OK as expected:
```
-> [ an OutputProxy, an OutputProxy ]
-> a Function
Instance of Bus {    (0x7042468, gc=50, fmt=00, flg=00, set=03)
  instance variables [5]
    rate : Symbol 'audio'
    index : Integer 4
    numChannels : Integer 2
    server : instance of Server (0x25a6698, size=50, set=6)
    mapSymbol : nil
}
-> Bus(audio, 4, 2, localhost)
```
Other twos do not...
```
~a.monitor.ins
~a.monitor.outs
```
both returns:
```
ERROR: Message 'ins' not understood.
ERROR: Message 'outs' not understood.
```

Thanks for help, I will try anything to track this one down.. I am confused as it is not regular thing, it may refer to length of definition and some pre-processing in Vim maybe.. dunno.

**Comment by telephon** [comment]
>````ERROR: Message 'ins' not understood.````

This means that ````play```` didn't work somehow, the proxy should have a monitor then. Are you sure it played?

**Comment by K0F** [comment]
You're right, it outs ```[ 4, 5 ]``` for ins and ```[ 0, 1 ]``` for outs when played. I will try to do the the same when the error appears again..

**Comment by K0F** [comment]
Ok, I cought the error.. ```~a.bus.dump``` returns following:
```
Instance of Bus {    (0x3c99cc8, gc=A8, fmt=00, flg=00, set=03)
	instance variables [5] rate : Symbol 'control' index : Integer 61 numChannels : Integer 1
	server : instance of Server (0x18f63f8, size =50, set=6)
	mapSymbol : nil
}
-> Bus(control, 61, 1, localhost)
```

```~a.dump``` returns:
```
NodeProxy.control(localhost, 1): wrapped channels from 2 to 1 channels
NodeProxy.control(localhost, 1): adopted proxy input to control rate
WARNING: Can't monitor a control rate bus.

-> NodeProxy.control(localhost, 1)
Instance of NodeProxy { 
   (0x141def8, gc=90, fmt=00, flg=00, set=04)
  instance variables [16]
    server : instance of Server (0x18f63f8, size =50, set=6)
    bus : instance of Bus (0x3c99cc8, size=5, set=3)
    monitor : instance of Monitor (0x115fb18, size=8, set=3)
    parentGroup : nil
    busArg : "c61"
    busLoaded : true
    reshaping : nil
    group : instance of Group (0x3c5e978, size=5, set=3)
    objects : instance of Order (0x3ba5b48, size=2, set=2)
    nodeMap : instance of ProxyNodeMap (0x3ff7f88, size=9, set=4)
    children : instance of Array (0x3aa5088, size=1, set=2)
    loaded : false
    awake : true
    paused : false
    clock : instance of 
TempoBusClock (0x3eb3f08, size=8, set=3)
    quant : Integer 2
}
-> NodeProxy.control(localhost, 1)
```

```~a.monitor.ins``` then: ```nil```
```~a.monitor.outs``` same: ```nil```


It happened after several definitions were already ran and playing.

Any idea what it could cause?

Thanks

**Comment by telephon** [comment]
For some reason, the proxy changed its bus after it had been initialized. Indeed, ````NodeProxy```` can change its bus when it is set to be ````reshaping = \elastic```` (but also then it shouldn't change as it is in your case).

But this is a clue at least.

As a next question: what does ````p.reshaping```` return? If it is not ````\elastic````, you could, just to give it a try, set it: ````p.reshaping = \elastic````. You may want to check the helpfile for ````NodeProxy```` for this.

But in any case your example shows a bug somewhere.

**Comment by K0F** [comment]
Ok, ```p.reshaping``` returns ```nil``` by default. I can try to redefine it in start-up file and let's see if this thing appears again.. Thanks Julian

**Comment by telephon** [comment]
in the end we'll trace that bug down!

**Comment by telephon** [comment]
Here is my attempt at reproducing it, so far I can't (there are occasional other unrelated failures to find the SynthDef, but we can ignore that for this issue):

````
(
s.boot();
NodeProxy.defaultReshaping = nil;
p=ProxySpace.push(s);

fork {
	1000.do {
		~a={ SinOsc.ar(440 ! 2) };
		wait(rrand(0.4, 0.03).postln);
		if(~a.rate != \audio) { "found one --------------- ".postln; ~a.dump; ~a.throw }
	}
	
}
)

````

**Comment by K0F** [comment]
Interesting, the suggested test is passing OK. But when I put some more mess in the fork, I can reproduce this quite regularly in my case by [code](https://raw.githubusercontent.com/k-o-l-e-k-t-i-v/supercollider/master/kof/bug_hunt.scd) 

^^I know it makes no sense to repeat some definitions over but it is quite close to how I often use SC.

I will try to strip it down line by line to find what could be the cause..

**Comment by telephon** [comment]
What can indeed happen is that your first (initializing) output of your node proxy is an array that is larger than the available number of busses. I would have expected an error message from ```Bus.audio(...)```, but it might be that this never happens.

But your inner number of UGens does not require external busses (it requires so called "wires", and if you have more than allocated by default, the server will give you an error and you can then increase ```s.options.numWireBufs = 128; s.reboot```, e.g.).

**Comment by telephon** [comment]
But maybe you can catch the bug in the actual code when it happens, then we'll know more.

**Comment by telephon** [comment]
I think this was closed through the warning when the allocator had an overrun. Feel free to reopen, if it occurs again.

**Comment by K0F** [comment]
It have not occurred for a long time here.. I'm not sure what it was causing, it almost felt like a little discrepancy between using ```~some.ar``` and just ```~some``` inside other node-proxy definitions.

I failed to reproduce it by any means, occurrence seemed completely random to me.. frustrating stuff, I am glad it is gone somehow, anyways thanks for helping out!
