### ISSUE TITLE
Windows mingw build 3.7: FFT crashes server

### ISSUE THREAD

**Issue by jamshark70** [supercollider/supercollider#1695]
Using SuperCollider-201506251338-3.7alpha1_Release-x86-MinGW-bcf4596.exe:

```
s.boot;

a = {
	var sig = PinkNoise.ar,
	fft = FFT(LocalBuf(1024, 1), sig);
	sig
}.play;

-> RESULT = -1073741819  (server crashed)
```

Well, that could be a LocalBuf problem, so let's eliminate that variable.

```
s.boot;

b = Buffer.alloc(s, 1024, 1);

a = {
	var sig = PinkNoise.ar,
	fft = FFT(b, sig);
	sig
}.play;

-> RESULT = -1073741819  (server crashed)
```

Nope... it's just FFT.

Would be very nice to fix for 3.7.

**Comment by sonoro1234** [comment]
Not getting this error with my lua client on scsynth 3.7alpha1
Could mean bad synthdef compilation from sclang?
quick test: Define it as a synthdef and save to file in 3.7alpha1 and previous version working and compare *.scsyndef files.

**Comment by jamshark70** [comment]
It could also be a 32- vs 64-bit issue. I am (unfortunately) limited for the time being to a 32-bit Windows version. It's entirely possible that the 64-bit build (done with Visual Studio rather than mingw) is fine.

**Comment by sonoro1234** [comment]
But I am on 32 bit also.

**Comment by bagong** [comment]
@jamshark70 , I just saw this and tested on a current build (3.7.0). No crash here... So whatever it was, maybe assume as fixed and close?

**Comment by jamshark70** [comment]
I guess so... I can reopen it if I see the problem when I finally have some time to test it. Unfortunately this week has suddenly taken an unwelcome turn. It might be awhile.

**Comment by bagong** [comment]
Okay. Good luck!
