### ISSUE TITLE
Question about ZIN

### ISSUE THREAD

**Issue by sonoro1234** [supercollider/supercollider#1696]
Hello,

Why is ZIN(0) used for a control rate trigger, shouldn't it be ZIN0(0)?

void SendTrig_next(SendTrig *unit, int inNumSamples)
{
 float *trig = ZIN(0);
 float prevtrig = unit->m_prevtrig;

 LOOP1(inNumSamples,
  float curtrig = ZXP(trig);
  if (curtrig > 0.f && prevtrig <= 0.f) {
   SendTrigger(&unit->mParent->mNode, (int)ZIN0(1), ZIN0(2));
  }
  prevtrig = curtrig;
 );
 unit->m_prevtrig = prevtrig;
}

Best
victor

**Comment by telephon** [comment]
```ZIN(0)``` is an audio rate trigger: it is used in the loop: ```float curtrig = ZXP(trig);```

**Comment by sonoro1234** [comment]
but in example a control rate is used:
SendTrig.kr(Dust.kr(1.0),0,0.9);

**Comment by telephon** [comment]
Yes, in that case ```inNumSamples``` equals ```1```.

**Comment by telephon** [comment]
… and a kr signal is represented by a value at index 0

**Comment by sonoro1234** [comment]
Thanks.
I understand now.
