### ISSUE TITLE
TwoWayIdentityDictionary.asCompileString misses to include key 

### ISSUE THREAD

**Issue by miczac** [supercollider/supercollider#1699]
as [dicussed here] (http://new-supercollider-mailing-lists-forums-use-these.2681727.n2.nabble.com/ZArchive-amp-TwoWayIdentityDictionary-td7621088.html):
d = TwoWayIdentityDictionary.new;
d.put(\k1, "blah");
d.asCompileString

// posts this:
TwoWayIdentityDictionary[ "blah" ]

d = IdentityDictionary.new;
d.put(\k1, "blah");
d.asCompileString
// is ok:
IdentityDictionary[ ('k1' -> "blah") ]

**Comment by crucialfelix** [comment]
just adding a bit more: its because it is a direct subclass of Collection and uses that storeArgsOn method. it should print the Associations, not the values.

**Comment by telephon** [comment]
In some ways, the ```TwoWayIdentityDictionary``` is not optimal for general use, because it lacks many of the methods that make subclasses of ```Dictionary``` useful and compatible. IIRC, ihis class was originally  added by JMcC as a superclass for ObjectTable needed to implement SC3d5. So it might need some love.
