### ISSUE TITLE
Shortcuts not working on Ubuntu Unity

### ISSUE THREAD

**Issue by smrg-lm** [supercollider/supercollider#1703]
From some time now, some of the shorcuts are not working, e.g. Ctrl-N, Ctrl+O, Ctrl+S, Ctrl+Shift+W
Ctrl+., and others.

I'm in Ubuntu 14.04 and built with Qt 5.2.1 from Ubuntu repositories (following the readme).

I instaled the system few times and this is quite consisten.

Note: the shortcuts seem to work if I compile with Qt from Digia, but that seems to be not the right solution (unless it is a bug in the qt package)

**Comment by theseanco** [comment]
Also having this problem

**Comment by danstowell** [comment]
Interesting - I don't have this problem, and I'm on Ubuntu Studio 14.04 and Qt 5.2.1, so a very similar system. An important possible difference might be which window manager is in use (since I'm using Ubuntu Studio, which does not use Ubuntu's "unity" wm).

**Comment by theseanco** [comment]
@danstowell - I dropped into i3wm and didn't have this problem. I also didn't have the problem with tooltip fonts.

**Comment by jamshark70** [comment]
FWIW, related to Dan's comment, I quit using Unity more than a year ago. After its configuration got borked, with no apparent way to repair it, I concluded that Unity is a buggy POS that, basically, no one should use, ever.

I've been on gnome 3 since well before this issue was opened and haven't seen a problem like this.

**Comment by theseanco** [comment]
@jamshark70 Thanks for the tip. Will switch now.

**Comment by danstowell** [comment]
Unity is relatively immature - I'm sure they'd be grateful if someone could send these bug reports upstream to them. They might even fix them!

**Comment by paullucas** [comment]
I am also having this issue. Even if I change the key combination, the shortcut for stop never works.

**Comment by felixetienne** [comment]
I am also having this issue on Ubuntu 16.04 (beta, with Unity).

**Comment by theseanco** [comment]
@paullucas @felixetienne - This is definitely a Unity issue. The tooltip font issue also comes with unity but can be resolved by changing the font colour in unity's settings. I've since used KDE and Gnome to work with 3.7.0-b1 and both have been fine

**Comment by felixetienne** [comment]
Thanks. I also use Gnome3 and all work fine with 3.7.0

**Comment by tedthetrumpet** [comment]
Had same problem with Unity, now fine with Gnome 3 on Ubuntu 16.04, SC 3.7.2

**Comment by felixetienne** [comment]
The problem also exists with the new version 3.8.0 and Untuntu 16.04.1.
The workaround is to delete appendix-qt5. It works well, but can eventually produce some other problems.

https://bugs.launchpad.net/ubuntu/+source/appmenu-qt5/+bug/1313248

**Comment by zetteeh** [comment]
with 3.9dev and ubuntu 16.04 the problem seems to still be existent.

**Comment by smrg-lm** [comment]
Would you like to try something funny? Close all documents so the editor gets empty, try open with ctrl-n it won't open nothing, open a document with File -> New and shortcuts should be working again. Now, when closing scide without creating a new session nor saving a file, editor's space will start empty, create or open a session (maybe save a file if session is empty) close scide and the problem is solved. Unity on Ubuntu 16.04. Maybe the document catch the shortcuts without  propagating properly afterwards for some reason, I see a lot of tickets for shortcut problems.

**Comment by smrg-lm** [comment]
I mean, the default document or the way it is initialized.

**Comment by smrg-lm** [comment]
As this is going to be the memory of a bad dream it would be closed.
