### ISSUE TITLE
Typo / wrong cmake function name in CMakeLists.txt

### ISSUE THREAD

**Issue by susnux** [supercollider/supercollider#1705]
When building on openSUSE Tumbleweed I noticed there is a wrong function name.
In lang/CMakeLists.txt is in line 231 a type:

    target_include_directoriesf

instead of

    target_include_directories

Patch I used to fix it for me:
https://gist.github.com/susnux/a3506fdca3ca3ce525d7

**Comment by danstowell** [comment]
Many thanks!
