### ISSUE TITLE
WritingUGens Help

### ISSUE THREAD

**Issue by pabloriera** [supercollider/supercollider#1716]
The MySaw.cpp code in http://doc.sccode.org/Guides/WritingUGens.html has some problems.
It has extra function implementations, I think. I was able to use it though by erasing that extra stuff.

**Comment by sensestage** [comment]
Can you be more specific than "some problems"?
What stuff did you erase, what files did you end up with?

**Comment by pabloriera** [comment]
Sorry, I think I made a mistake and thought the error was on the online code, but it was on a file a thought it was a copy of the original code. I will close this issue. Thanks
