### ISSUE TITLE
Supernova: Master Test Suite has failures

### ISSUE THREAD

**Issue by sonoro1234** [supercollider/supercollider#1717]
Hello,
there are two errors in supernova test suite.
I dont know if they are relevant:
probably only @timblechmann knows
1-
C:\SupercolliderRepos\buildscfork\testsuite\supernova>server_test
Running 3 test cases...
unknown location(0): fatal error in "server_test_1": std::exception: boost::interprocess::bad_alloc
unknown location(0): fatal error in "server_test_2": std::exception: boost::interprocess::bad_alloc
unknown location(0): fatal error in "server_test_3": std::exception: boost::interprocess::bad_alloc

**\* 3 failures detected in test suite "Master Test Suite"
2-
C:\SupercolliderRepos\buildscfork\testsuite\supernova>server_node_graph_test
Running 19 test cases...
C:/SupercolliderRepos/scfork/supercollider/testsuite/supernova/server_node_graph_test.cpp(27): fatal error in "simple_synth_t
est_1": critical check n.group_count() == 1u failed [0 != 1]
C:/SupercolliderRepos/scfork/supercollider/testsuite/supernova/server_node_graph_test.cpp(144): fatal error in "free_all_test
": critical check n.group_count() == 2u failed [1 != 2]
C:/SupercolliderRepos/scfork/supercollider/testsuite/supernova/server_node_graph_test.cpp(186): fatal error in "free_deep_tes
t": critical check n.group_count() == 2u failed [1 != 2]

**\* 3 failures detected in test suite "Master Test Suite"

Best
victor

**Comment by vivid-synth** [comment]
Ah! I created a duplicate issue for this on Linux when I found it: https://github.com/supercollider/supercollider/issues/2193

**Comment by vivid-synth** [comment]
Note at least one of these tests passed in the past:

server_node_graph_test_run succeeds on ce15240

(more info in #2193 )

**Comment by snappizz** [comment]
is this fixed?

**Comment by snappizz** [comment]
never mind, i guess it isn't :(

i bring this up because debian packaging automatically called `make test` and refused to finish because the tests failed. i can work around it though

**Comment by brianlheim** [comment]
ahhh yeah sorry! i would like to get the tests working, they can possibly be disabled for now if need be

**Comment by sonoro1234** [comment]
I wonder if it is related to https://github.com/supercollider/supercollider/issues/3461
