### ISSUE TITLE
supernova performance survey

### ISSUE THREAD

**Issue by sonoro1234** [supercollider/supercollider#1718]
Hi,

I have not seen anything about supernova performance on different systems
and would like to make a simple survey comparing the performance of scsynth
and supernova.
Could anyone having tried that, report cpu times for the same script, os
used (linux, macosx, win), 32bits or 64bits and number of cores?

For example I have the following results:

windows vista 32bits 2-cores: very similar performance (slightly better supernova?)
windows 7 64bits 8-cores: scsynth 43% supernova 54%

Best
victor

**Comment by telephon** [comment]
Maybe post a script that you used for checking?

**Comment by sonoro1234** [comment]
PparGroup example suffices

**Comment by timblechmann** [comment]
the performance of supernova heavily relies on the use cases ... it's easy to construct examples where synchronisation overhead will be huge. fwiw, please consult the section about scalability of my master thesis, as it discusses some of those aspects in detail ...

also: don't rely on "cpu percent", as you have no idea what the percentage tells you: "percentage of what?" ... in general it would be *much* more productive not to do blind brute-force tests, but to analyse (read: fire up a profiler)

**Comment by jamshark70** [comment]
FWIW, I'm currently unable to compile supernova.

```
[ 25%] Building CXX object server/supernova/CMakeFiles/libsupernova.dir/sc/sc_synth_definition.cpp.o
In file included from /home/dlm/share/sc-hjh.git/server/supernova/sc/sc_synth_definition.hpp:26:0,
                 from /home/dlm/share/sc-hjh.git/server/supernova/sc/sc_synth.hpp:29,
                 from /home/dlm/share/sc-hjh.git/server/supernova/sc/sc_synth_definition.cpp:24:
/home/dlm/share/sc-hjh.git/server/supernova/./server/synth_definition.hpp:187:13: error: looser throw specifier for ‘virtual nova::synth_definition::~synth_definition()’
In file included from /home/dlm/share/sc-hjh.git/server/supernova/./utilities/named_hash_entry.hpp:26:0,
                 from /home/dlm/share/sc-hjh.git/server/supernova/sc/sc_synthdef.hpp:30,
                 from /home/dlm/share/sc-hjh.git/server/supernova/sc/sc_synth_definition.hpp:24,
                 from /home/dlm/share/sc-hjh.git/server/supernova/sc/sc_synth.hpp:29,
                 from /home/dlm/share/sc-hjh.git/server/supernova/sc/sc_synth_definition.cpp:24:
/home/dlm/share/sc-hjh.git/server/supernova/./utilities/utils.hpp:142:13: error:   overriding ‘nova::intrusive_refcountable<deleter>::~intrusive_refcountable() noexcept (true) [with deleter = nova::checked_deleter]’
```
