### ISSUE TITLE
Plot assumes that the domain spec is always ascending

### ISSUE THREAD

**Issue by jamshark70** [supercollider/supercollider#1719]
```
(
a = Array.series(512, 0, (-20 / 511)).dbamp;
p = a.plot;
p.domainSpecs = [[0, -20].asSpec];
p.refresh;
)
```

This graph is supposed to show decibels on the x axis and amplitude on y. Decibels should decrease from 0 dBFS down to -20 dB. Plot, however, can't cope with this. The domain grid disappears completely.

The only way to get it to display is to invert the domain, making it 0 .. 20. But you shouldn't have to do that.

I'll assign this to myself for now and try to look at it later. If I can't figure out the thicket of Plot code, then I'll reassign.

**Comment by muellmusik** [comment]
@jamshark70 are you still pursuing this?

**Comment by jamshark70** [comment]
Sorry, I can't handle a thicket of code right now (unless it's my own).

I'll close it.
