### ISSUE TITLE
"ERROR: Message 'bufferAllocator' not understood" When trying to load audio into a Buffer

### ISSUE THREAD

**Issue by deusofnull** [supercollider/supercollider#1720]
Hello everyone,

I am having trouble loading audio into a buffer.  Seems like a pretty simple objective but with very strange results.  

When I execute this line:
`~b0 = Buffer.read(s, "/home/deusofnull/Documents/JOCK/Recordings/clipped_audio/tinks/lamp_tink_med3.aiff");`

I get this error:

RECEIVER: an EventStreamPlayer
ERROR: Message 'bufferAllocator' not understood.
RECEIVER:
Instance of EventStreamPlayer {    (0x35abda8, gc=04, fmt=00, flg=00, set=04)
  instance variables [11]
    stream : nil
    originalStream : instance of Routine (0x1dbe5a8, size=27, set=5)
    clock : instance of TempoClock (0x2fd28a8, size=7, set=3)
    nextBeat : nil
    streamHasEnded : false
    isWaiting : false
    era : Integer 12
    event : instance of Event (0x3522388, size=5, set=3)
    muteCount : Integer 0
    cleanup : instance of EventStreamCleanup (0x4561c88, size=1, set=2)
    routine : instance of Routine (0x7f62fc0a0978, size=27, set=5)
}
ARGS:
PATH: /home/deusofnull/Codes/SuperCollider/11-14-15 Eli- Buffers.scd
CALL STACK:
	DoesNotUnderstandError:reportError   0x466af08
		arg this = <instance of DoesNotUnderstandError>
	Nil:handleError   0x4a059c8
		arg this = nil
		arg error = <instance of DoesNotUnderstandError>
	Thread:handleError   0x376bec8
		arg this = <instance of Thread>
		arg error = <instance of DoesNotUnderstandError>
	Object:throw   0x311b558
		arg this = <instance of DoesNotUnderstandError>
	Object:doesNotUnderstand   0x471b618
		arg this = <instance of EventStreamPlayer>
		arg selector = 'bufferAllocator'
		arg args = [*0]
	Meta_Buffer:read   0x3384c28
		arg this = <instance of Meta_Buffer>
		arg server = <instance of EventStreamPlayer>
		arg path = "/home/deusofnull/Documents/J..."
		arg startFrame = 0
		arg numFrames = -1
		arg action = nil
		arg bufnum = nil
	< closed FunctionDef >  (no arguments or variables)
	Interpreter:interpretPrintCmdLine   0x7f62a8004458
		arg this = <instance of Interpreter>
		var res = nil
		var func = <instance of Function>
		var code = "~b0 = Buffer.read(s, "/home/..."
		var doc = nil
		var ideClass = <instance of Meta_ScIDE>
	Process:interpretPrintCmdLine   0x4a4f1c8
		arg this = <instance of Main>
^^ The preceding error dump is for ERROR: Message 'bufferAllocator' not understood.
RECEIVER: an EventStreamPlayer

---

Can anyone help me understand why 'bufferAllocator' is not understood?  I am running on ubuntu trusty.  

Thanks!

**Comment by jamshark70** [comment]
This is not a bug. Please don't use the bug tracker for such questions.

You've replaced 's' with some object that is not a Server. After doing that, you can't use 's' as the server for buffer loading. Simple as that.
