### ISSUE TITLE
Quarks.update calls wrong git method

### ISSUE THREAD

**Issue by crucialfelix** [supercollider/supercollider#1734]
calls:

   Git.update(this.quarkNameAsLocalPath(name))

should call:

    Git(this.quarkNameAsLocalPath(name)).pull;

also Object should not just implement every damn method that anybody thinks up for their own system and then have a blank implementation. it leads to bugs like this. but that's the smalltalk legacy

**Comment by jamshark70** [comment]
You would be referring to something that James McCartney thought up for the dependants mechanism...

**Comment by telephon** [comment]
the smalltalk legacy is good, but easy to get wrong as well. Obviously it can be problematic to override inherited methods with a completely different semantics! But who can tell what "semantics" is, if not the programmer?

The dependants mechanism was never very good, imo, but the implementation simple enough to be quickly added at that time. But it is easy to cause memory leaks.
