### ISSUE TITLE
Quarks: update fail when missing tag or no new version number

### ISSUE THREAD

**Issue by redFrik** [supercollider/supercollider#1735]
trying to install LATEST version of the Conductor quark.
Quarks.gui -> check for updates -> select Conductor -> select LATEST -> click install...

Removing path: /Users/asdf/Library/Application Support/SuperCollider/downloaded-quarks/Conductor
Installing Conductor
WARNING: Tag not found: Quark: Conductor[1] 953ea218642ed1235c257c3036c596c78942f64 
 Possible tags: [  ]
Adding path: /Users/asdf/Library/Application Support/SuperCollider/downloaded-quarks/Conductor
Conductor installed

but no. the old version is still there.

**Comment by telephon** [comment]
Yes, I can confirm this behavior, the latest changes are not there.:

```
set { arg ... args; // pairs of keys or indices and value
		nodeMap.set(*args);
		if(this.isPlaying) { 
			server.sendBundle(server.latency, [15, group.nodeID] ++ args); 
		};
		this.changed(\set, args);
	}
```
