### ISSUE TITLE
RTAlloc worries (proposal)

### ISSUE THREAD

**Issue by sonoro1234** [supercollider/supercollider#1742]
This code in World_New
```
World *world = 0;

	try {
		static bool gLibInitted = false;
		if (!gLibInitted) {
			InterfaceTable_Init();
			initialize_library(inOptions->mUGensPluginPath);
			initializeScheduler();
			gLibInitted = true;
		}

		world = (World*)zalloc(1, sizeof(World));
```
shows that when calling load in Plugins world is still not existent. That prevents RTAlloc to be used to allocate static variables in the module (for example overriding global new to use RTAlloc).
RTAlloc must wait the first call to any Ctor in the module to get unit->mWorld.

This seems to me a limitation quite strong. My proposal would be to get anything in world working before calling to initialize_library and give it to the Plugin_load function (directly or via InterfaceTable.mWorld) to let RTAlloc being used from the beggining.

What do all of you think about it?

Best
victor

**Comment by joshpar** [comment]
I don't think plugin load should have access to the RTAlloc pool though. At
Load time, you aren't under the same time pressure- should you just alloc any memory your plugin needs in the usual sense in this case and leave RTAlloc for Ctors?

/*
Josh Parmenter
www.realizedsound.net/josh
*/

**Comment by sonoro1234** [comment]
My need comes from overloading global new and delete operators for binding to Stk which uses new in alot of time-critical places.
The problem I found doing that is that there are static variables at Stk.cpp:68
```
std::vector<Stk *> Stk :: alertList_;
std::ostringstream Stk :: oStream_;
```
and when scsynth quits I get 
```
Program received signal SIGSEGV, Segmentation fault.
0x672586b1 in World_Free (inWorld=0x1c2cbc0, inPtr=0x27a22a0)
    at C:\SupercolliderRepos\scfork\supercollider\server\scsynth\SC_World.cpp:807
807             inWorld->hw->mAllocPool->Free(inPtr);
(gdb) thread apply all bt

Thread 1 (Thread 3284.0xb38):
#0  0x672586b1 in World_Free (inWorld=0x1c2cbc0, inPtr=0x27a22a0)
    at C:\SupercolliderRepos\scfork\supercollider\server\scsynth\SC_World.cpp:807
#1  0x6d581bab in operator delete (ptr=0x27a22a0) at C:\SupercolliderRepos\Mios\StkInst\StkInst.cpp:42
#2  0x6d5f8ee4 in deallocate (this=0x6d6fd234 <stk::Stk::alertList_>, __p=<optimized out>)
    at c:/mingw32-4.8.2-posix-dwarf/i686-w64-mingw32/include/c++/ext/new_allocator.h:110
#3  _M_deallocate (this=0x6d6fd234 <stk::Stk::alertList_>, __n=<optimized out>, __p=<optimized out>)
    at c:/mingw32-4.8.2-posix-dwarf/i686-w64-mingw32/include/c++/bits/stl_vector.h:174
#4  ~_Vector_base (this=0x6d6fd234 <stk::Stk::alertList_>, __in_chrg=<optimized out>)
    at c:/mingw32-4.8.2-posix-dwarf/i686-w64-mingw32/include/c++/bits/stl_vector.h:160
#5  ~vector (this=0x6d6fd234 <stk::Stk::alertList_>, __in_chrg=<optimized out>)
    at c:/mingw32-4.8.2-posix-dwarf/i686-w64-mingw32/include/c++/bits/stl_vector.h:416
#6  __tcf_2 () at C:\SupercolliderRepos\Mios\StkInst\stk\src\Stk.cpp:68
#7  0x6d5811a4 in _CRT_INIT@12 () from C:\SupercolliderRepos\Mios\ugens\StkInst.scx
#8  0x6d58139d in __DllMainCRTStartup () from C:\SupercolliderRepos\Mios\ugens\StkInst.scx
#9  0x6d581443 in DllMainCRTStartup@12 () from C:\SupercolliderRepos\Mios\ugens\StkInst.scx
#10 0x77871288 in ntdll!RtlQueryInformationActivationContext () from C:\Windows\system32\ntdll.dll
#11 0x6d580000 in ?? ()
#12 0x7786b16c in ntdll!RtlExitUserProcess () from C:\Windows\system32\ntdll.dll
#13 0x7786b0ee in ntdll!RtlExitUserProcess () from C:\Windows\system32\ntdll.dll
#14 0x761744d1 in KERNEL32!ExitProcess () from C:\Windows\system32\kernel32.dll
#15 0x00000000 in ?? ()
```
when overloaded delete tries to free them without being allocated by overloaded new.
Now I am just thinking that when Plugin_load is called they would be already allocated?!! ,so the problem is more complicated.

**Comment by sonoro1234** [comment]
I could solve the issue (in my local repo) with Plugin_unload: When it is called I clear all Stk memory so that overloaded delete does his work before world´s RTFree is unusable.
