### ISSUE TITLE
bitNot not implemented (but fails to operate silently)

### ISSUE THREAD

**Issue by telephon** [supercollider/supercollider#1749]
The method `bitNot` should work both in sclang and sc-server, like e.g. `bitAnd`.

```
{
    var t = PulseCount.ar(Impulse.ar(8000));
    (t & t.bitNot) % 2
}.plot(2)
```

while `x bitAnd: x.bitNot`  should 0.

**Comment by vivid-synth** [comment]
Can this be merged?

**Comment by telephon** [comment]
I think yes.

**Comment by vivid-synth** [comment]
@telephon can you make a pull request for this?

**Comment by telephon** [comment]
@vivid-synth there is a pull request, just a bit further up...

**Comment by vivid-synth** [comment]
@telephon I might be looking in the wrong place, but I see commits but not a pull request. I also don't see those commits in the git log on master, so can this be merged?

**Comment by vivid-synth** [comment]
Bump

**Comment by telephon** [comment]
here you are: https://github.com/supercollider/supercollider/issues/1749

**Comment by vivid-synth** [comment]
Thanks! Bytebeat musicians will be excited

**Comment by telephon** [comment]
here is the PR, just in case: https://github.com/supercollider/supercollider/pull/2381

**Comment by vivid-synth** [comment]
PR merged
