### ISSUE TITLE
build: LFUGens.cpp requires nova_simd code even if NOVA_SIMD=off

### ISSUE THREAD

**Issue by danstowell** [supercollider/supercollider#1751]
Trying to build master (at latest commit 380b8f6) on a low-resource device. I set `NOVA_SIMD=off` and I've not included the nova-simd files (not much disk space). Build fails with:

```
[ 21%] Building CXX object server/plugins/CMakeFiles/LFUGens.dir/LFUGens.cpp.o
In file included from /boot/uboot/supercollider-master-stripped/server/plugins/LFUGens.cpp:23:0:
/boot/uboot/supercollider-master-stripped/server/plugins/SIMD_Unit.hpp:26:27: fatal error: simd_memory.hpp: No such file or directory
compilation terminated.
make[2]: *** [server/plugins/CMakeFiles/LFUGens.dir/LFUGens.cpp.o] Error 1
make[1]: *** [server/plugins/CMakeFiles/LFUGens.dir/all] Error 2
make: *** [all] Error 2
```

It seems that it's not truly possible to deactivate NOVA_SIMD at the moment.
@timblechmann I'd be grateful for suggestions: is there a way I can provide a fallback option in this case?

**Comment by timblechmann** [comment]
if you're on a low-resource device, SIMD instructions may actually be quite useful, no?

no "easy fallback" atm, though ... you might have to rewrite those parts which use SIMD_Unit ...

**Comment by danstowell** [comment]
Thanks. Yes that's fine, the "low-resource" thing was just explaining how I got to the point of trying a minimal build without the extra source files.

So as it stands NOVA_SIMD=off isn't a very meaningful option. I guess it's still useful for debugging, since it often gives us two implementations whose output we can compare!
