### ISSUE TITLE
virtual room plugins (christmas present)

### ISSUE THREAD

**Issue by sonoro1234** [supercollider/supercollider#1764]
Hi,

Just published a RIR generator of virtual room (image method of Allen an Berkley) plus late reverb modeling by feedback delay networks in:

https://github.com/sonoro1234/DWGReverb

Only source so must be compiled. Script in Lua should be translated (two plugin definitions and a Synthdef) (I someone translates please fork and commit sc file)

I am quite satisfied with sound quality an efficiency.

Take a look and post your comments.

happy holidays for everyone
victor

**Comment by crucialfelix** [comment]
Sounds great. But is this a supercollider issue ?

**Comment by sonoro1234** [comment]
Yes, this are plugins for supercollider.

**Comment by crucialfelix** [comment]
Are you proposing adding them to the sc plugins ? There is a separate
repository for those.
The main app ships with just the core UGens, and the community contributed
ones are in the sc plugins repo.

https://github.com/supercollider/sc3-plugins

**Comment by sonoro1234** [comment]
lets move it to sc3plugins issues
