### ISSUE TITLE
Bad values (nan) from underflow with pow() on Server

### ISSUE THREAD

**Issue by totalgee** [supercollider/supercollider#1766]
When evaluating the `pow()` function on the Server, it is possible to get `nan` values, when the result is very small (just below `FLT_MIN`, aka ~1.175e-38).  I think it should return 0 in these cases, and not return `nan`, because that causes audible glitches, e.g. when filtering the resulting signal.

```
// Here is a case showing the problem -- note the output from CheckBadValues UGen:
{ var sig = Line.ar(3e-6, 4e-6, 0.1), sig2 = sig.pow(7); [sig, sig2, CheckBadValues.ar(sig2)] }.plot(0.1)
// --> CheckBadValues: NaN found in Synth 1004, ID 0 (previous 571 values were normal)
// --> CheckBadValues: denormal found in Synth 1004, ID 0 (previous 1436 values were NaN)
// --> CheckBadValues: normal found in Synth 1004, ID 0 (previous 1586 values were denormal)

// Similar problem, computed using different base and exponent:
{ var sig = Line.ar(0.9e-7, 1.4e-7, 0.1), sig2 = sig.pow(5.5); [sig, sig2, CheckBadValues.ar(sig2)] }.plot(0.1)

// A final example, showing that it is symptomatic of sig.pow(2) but not sig.squared:
{ var sig = Line.ar(0.4e-19, 1.4e-19, 0.1), sig2 = sig.pow(2); [sig, sig.squared, CheckBadValues.ar(sig.squared), sig2, CheckBadValues.ar(sig2)] }.plot(0.1)
```

I was having this problem on 3.6.6 (OS X), but it's also been reproduced on SC 3.7alpha0 (Linux) by Tom.  See the relevant [sc-users thread](http://new-supercollider-mailing-lists-forums-use-these.2681727.n2.nabble.com/Bad-Values-nan-from-underflow-when-using-pow-on-Server-td7622097.html).

**Comment by jamshark70** [comment]
Can you recompile with NOVA_SIMD=OFF and see if it still happens? In Linux:

```
$ cd path/to/sc_source
$ cd my_build_folder
$ cmake .. -DNOVA_SIMD=OFF
$ make
... wait...
$ sudo make install
```

This is to check if it's a general problem with the C `pow()` function, or just with the vector optimizations.

**Comment by jamshark70** [comment]
I am trying now. It takes a little hack into the sources because LinXFade2_Ctor is missing the `#ifdef`s for NOVA_SIMD, so compilation breaks when it's off. That was easy enough to fix. I'll put in a PR for that later.

**Comment by jamshark70** [comment]
My result: It's NOVA_SIMD's problem.

```
{ DC.ar(3.2e-06).pow(7).poll(0); Silent.ar(1); }.play
```

With NOVA_SIMD=ON:

```
-> Synth('temp__0' : 1000)
UGen(BinaryOpUGen): -nan
```

With NOVA_SIMD=OFF:

```
-> Synth('temp__0' : 1000)
UGen(BinaryOpUGen): 0
```

I don't know how to fix it, but at least we know that the non-`_nova` functions are OK.

**Comment by totalgee** [comment]
Thanks for digging. I don't know where to look yet, but if there's
somewhere we are registering for exceptions on all floating point errors
(possibly via boost?), we could try to change it to be all flags except for
underflow...? Though I think underflow is just a "range" error, which would
also include overflow. Will see if I can see where this is handled.

N.B. This may help, from the pow() docs:

If a *range error* occurs:
- And math_errhandling <http://www.cplusplus.com/math_errhandling> has
MATH_ERRNO <http://www.cplusplus.com/MATH_ERRNO> set: the global variable
errno <http://www.cplusplus.com/errno> is set to ERANGE
<http://www.cplusplus.com/ERANGE>.

- And math_errhandling <http://www.cplusplus.com/math_errhandling> has
MATH_ERREXCEPT <http://www.cplusplus.com/MATH_ERREXCEPT> set: either
FE_OVERFLOW <http://www.cplusplus.com/FE_OVERFLOW> or FE_UNDERFLOW
<http://www.cplusplus.com/FE_UNDERFLOW> is raised.

I assume we're set up to get math exceptions in SC (i.e. not using errno).
Maybe we get a range_error exception, which we could ignore when it is for
FE_UNDERFLOW?

**Comment by totalgee** [comment]
We probably just need to use:

feenableexcept(FE_DIVBYZERO|FE_OVERFLOW|FE_INVALID);

rather than FE_ALL_EXCEPT

Because "underflow" and "inexact" are benign. I can try this out later...

Glen.

**Comment by totalgee** [comment]
Hmm, not as obvious as I'd hoped.  (-; I don't see the float exception stuff setup anywhere (except by Boost's BOOST_FPU_EXCEPTION_GUARD macro).

And I don't see us changing Boost's default underflow handling (which is to ignore):

```
#define BOOST_MATH_UNDERFLOW_ERROR_POLICY ignore_error
```

Maybe someone who's familiar with the NOVA_SIMD code could take a look, since the problem seems to be specific to there?  I note that vec_pow() is implemented using log() and exp() (in detail/vec_math.hpp), but I don't see anything specific to float exception or error handling in the SIMD code...

**Comment by sonoro1234** [comment]
@totalgee  I see that tim just updated simd module. Perhaps solves the problem?

**Comment by totalgee** [comment]
I don't think Tim's latest (FMA) changes would affect this.  I just tried compiling with it, but the problem's still there in 3.7 master.

@timblechmann  Any idea why we might be getting this `nan` result for underflow results, with vec_pow (i.e. only happens when compiling with NOVA_SIMD)?

**Comment by timblechmann** [comment]
no. someone would need to have a closer look at it ... this someone is probably me ... but it may take me a bit

**Comment by jamshark70** [comment]
A reasonable workaround in the meantime would be to change the binary op UGen Ctor to use the non-simd functions for pow() only. The simd functions could be reenabled once the problem is fixed properly.

**Comment by totalgee** [comment]
> A reasonable workaround [...] use the non-simd functions for pow() only.

Well, also for exp().  You can repro the same `nan` problem as follows, with `exp`:

```
{ DC.ar(-88.5).exp.poll(0); Silent.ar(1); }.play
```
However, note that calculating `DC.ar(-89).exp` or `DC.ar(-88).exp` on the Server both (correctly) return 0.

**Comment by totalgee** [comment]
Another wacky result (this one completely bonkers!)...

```
{ DC.ar(-88.72284).exp.poll(0); Silent.ar(1); }.play
```
It returns -3.40282e+38, a huge **negative** number (???), whereas the true answer should be around 2.94e-39 (a tiny positive number).

```
{ DC.ar(-88.72283).exp.poll(0); Silent.ar(1); }.play // returns nan
{ DC.ar(-88.72284).exp.poll(0); Silent.ar(1); }.play // returns -3.40282e+38
{ DC.ar(-88.72285).exp.poll(0); Silent.ar(1); }.play // returns 0, which is the best answer
```

**Comment by telephon** [comment]
>A reasonable workaround in the meantime would be to change the binary op UGen Ctor to use the non-simd functions for pow() only. The simd functions could be reenabled once the problem is fixed properly.

This may be good as a first bugfix for 3.7.1, but I can imagine that Tim will find a solution eventually.

**Comment by totalgee** [comment]
I tried @timblechmann's latest fix (changing the value of `minlogf` in nova-simd), and it seems to fix all the issues I've mentioned above (they all return 0 now). Thanks, Tim!
