### ISSUE TITLE
How to reverse full screen mode?

### ISSUE THREAD

**Issue by afischli** [supercollider/supercollider#1782]
I have tried out what would happen if I activate full screen mode (Mac, OS X 10.9.5 Mavericks) using latest SC 3.7. Now I can't get out of it, whatever I do. ESC does not exit that mode and the state is remembered between sessions. I discarded preference files, all to no avail. I can't regain control anymore and the menu bar seems lost for good.

Can anyone help? Thanks.

**Comment by afischli** [comment]
I could resolve the issue by discarding the entire folder in '~/Library/Application Support/SuperCollider'. However, I think we have a bug here, since there should other methods work to restore the menu bar, which do not require such a drastic measure. In my case, only because I have invested nothing into SC yet, this was easy. But everyone could click anytime the green button of the main window and then lose control over the application.

**Comment by crucialfelix** [comment]
You can move your mouse up to the top of the screen, the OS menu bar will appear.

Then you can again see the top left round full-screen toggle icon and you can click it to get out.

There is also a menu item Full Screen (shift-command F) that you can access.

Also you can just do shift-command-F to get out.

This is Mac OS X doing this, not supercollider.

Its the exact same on Chrome - I just did it now here.

**Comment by afischli** [comment]
Thanks, I wasn't aware of the mouse technique. Sorry for the tempest in the tea pot. But ESC should have worked too. That's the technique I normally use. So perhaps SC is swallowing the ESC event? Anyway thanks for the help.

**Comment by crucialfelix** [comment]
Esc doesn't work in chrome or atom either.

**Comment by afischli** [comment]
Chrome is nothing to measure against. I checked several sources for programmer's on this issue. Apple states (https://developer.apple.com/library/mac/documentation/UserExperience/Conceptual/OSXHIGuidelines/FullScreen.html#//apple_ref/doc/uid/20000957-CH61-SW1) that the mouse techniques should work both for the menu bar (moving to the top of the screen) and the dock. Both are ok for SC. In addition Apple reserves the shortcut Cmd-Ctrl-F for the toggling of full screen, not Cmd-Shift-F as SC does (https://developer.apple.com/library/mac/releasenotes/AppKit/RN-AppKitOlderNotes/). I was not aware of alls this and was simply used to  ESC, which works also to exit full screen in all Apple applications I tested (e.g. Safari, Calendar, Contacts, Messages a.o.). Since Apple is not very strict on shortcuts it does not surprise me that this ESC is nowhere recommended.

To wrap up I would say that SC should offer ESC to exit full screen, since using Cmd-Ctrl-F is not possible as cross-platform shortcut, i.e. on non Mac systems. That would offer at least a keyboard based exit that a user is likely to try, since Cmd-Ctrl-F can't be made available for cross-platform reasons.

**Comment by afischli** [comment]
Actually, one of the better articles on this issue is this one: http://www.tekrevue.com/tip/leave-full-screen-os-x/. On the ESC functionality it states: "While the Escape key is easier to remember and use, it doesn’t always work with all apps.". I think this summarizes it quite nicely. For SC my wrap up as given in the previous comment remains of course unchanged. SC should offer ESC, since Cmd-Ctrl-F is not possible.

**Comment by crucialfelix** [comment]
People build interfaces in supercollider, and we need to have all key commands open for setting up however we want it. These are performance tools.

We decided to exclude CMD from those, so all operating system type commands (windows, save, undo etc.) always use CMD. And user-defined key commands do not.

Anyway, I don't use the IDE at all; so I'm going to exit this conversation now. I'm just informing you of why things are as they are. I'm not anybody that will argue or change anything.

**Comment by afischli** [comment]
Thanks Chris, this is already helpful, yet you leave me a bit confused nevertheless.

I do not understand why you suddenly talk about CMD, since I was discussing CMD-CTRL-F vs. CMD-SHIFT-F and the use of ESC. If I understand you correctly, then actually one could argue that SC’s use of CMD-SHIFT-F is actually simply wrong and should be changed to the Mac standard CMD-CTRL-F, since CMD is anyway only used for what you call "operating system type commands (windows, save, undo etc.)” including full screen exit and is anyway only available on Mac systems. Or do you mean that CTRL must not be used for such  "operating system type commands”?

Then I do not understand what you mean by user-defined key commands. But I am happy to learn that they exist and that CMD should not be used for them, e.g. when I build an interface in SC. But for sure what we were discussing are shortcuts for full screen exit and they are NOT user-defined, aren’t they? Thus it is no problem to use CMD in that. And I suggested that SC also offers ESC, an idea on which you have not responded really.

Regards,
Andreas
