### ISSUE TITLE
No native FLAC support for scsynth on OS X

### ISSUE THREAD

**Issue by samaaron** [supercollider/supercollider#1783]
It appears that loading `*.flac` files into audio buffers works great on Linux and Windows but not on OS X. 

Is there any chance that FLAC support could be bundled with scsynth for OS X too??

**Comment by hzulla** [comment]
(It would help Sonic Pi, which is using scsynth, as we can greatly reduce the size of a bundled sample pack for the installer.)

**Comment by timblechmann** [comment]
libsndfile from homebrew is built with flac support ... someone will just have to build it and adapt the entry points from scsynth into libflac

**Comment by danstowell** [comment]
It basically depends on how libsndfile is built on the OSX machine that makes the executable - if you compile libsndfile but libflac is not available, libsndfile happily leaves it out. The pieces are probably almost all in place: if as tim says the standard homebrew build of libsndfile supports flac, and our travis script uses homebrew to install dependencies for building sc, there's probably just a little tweaking of the build to do?

https://github.com/supercollider/supercollider/blob/master/.travis.yml

**Comment by hzulla** [comment]
It would be great if that could be done.

**Comment by timblechmann** [comment]
if would be great if someone, who is interested in the feature can submit a pull request :)

**Comment by hzulla** [comment]
(I'm not using OS X, so I cannot volunteer. Sorry.)

**Comment by timblechmann** [comment]
i'm not using sc on osx, but i'd be willing to review the code

**Comment by samaaron** [comment]
Looks like this is the cause:

https://github.com/supercollider/supercollider/blob/master/README_OS_X.md#on-libsndfile

Perhaps it's just a matter of building a new libsndfile that's got both 32bit and 64bit support?

**Comment by timblechmann** [comment]
is anyone seriously using osx / 32bit these days? tbo, i seriously doubt that

**Comment by telephon** [comment]
IIRC, OS X 10.6 was the last 32bit one. As we don't support 10.6 anymore, there seems to be little reason why to keep supporting 32bit builds. But maybe someone knows a possible reason?

**Comment by danstowell** [comment]
Sounds good to me to drop the 32 bit. It seems it would simplify the libsndfile side of things a lot, since there'd be no need for a UB?

**Comment by telephon** [comment]
Are there other 32bit systems?  Like Raspberry-Pi or similar embedded systems?

**Comment by danstowell** [comment]
Yes - but usually they're running linux and they get libsndfile from the package manager, not from our Mac UB...

**Comment by hzulla** [comment]
Afaik, this 32 bit issue is a Mac-only thing. There should be flac support in SuperCollider on 32 bit Linux, but I cannot test that here and can report back on Monday after testing a 32 bit Linux install.

**Comment by danstowell** [comment]
It's a Mac only thing. Don't worry about linux. This is just about the Mac binary.

**Comment by telephon** [comment]
Ok, then we should drop it.

**Comment by lpil** [comment]
:+1:

**Comment by hzulla** [comment]
Sorry, I don't have a Mac at hand, but after a hard look at the OS X instructions and the travis file, isn't it just a matter of...

- removing the ["On libsnfile"](https://github.com/supercollider/supercollider/blob/master/README_OS_X.md#on-libsndfile) section
- removing the [precompiled library](https://github.com/supercollider/supercollider/tree/master/platform/mac/lib) from the git repo
- adding "libsndfile" in the ["Quick steps"](https://github.com/supercollider/supercollider/blob/master/README_OS_X.md#quick-steps) section to read `brew install git cmake readline libsndfile qt5`

...and be done with it?

**Comment by samaaron** [comment]
Yep, totally works. Just needed to teach `cmake` about the external `libsndfile` :-)

**Comment by lpil** [comment]
Awesome.

**Comment by hzulla** [comment]
Celebrating.

http://freesound.org/people/orangefreesounds/sounds/260820/

**Comment by telephon** [comment]
can this issue be closed then :) ?

**Comment by crucialfelix** [comment]
we are waiting on this PR to be decided/merged: https://github.com/supercollider/supercollider/pull/1870

**Comment by bagong** [comment]
There is a pull request that meets this. Open question are:

- what adjustments to the "entry points" need to be made (maybe none? flac and vorbis are already there)
- for deployment make sure, homebrew built libsndfile runs on every machine...

**Comment by bagong** [comment]
To elaborate on that second point: I haven't found simple documentation on the question yet, but it seems homebrew supplies libraries that to some degree are optimized for the OSX version and the system architecture of the host system. As long as you build for yourself, that's good. But if you build for a release, it's a different story. It's planned to use the Travis build for release, right? One has to make sure libsndfile is built in a way that works on all OSs and architectures targeted by the release.
Using `--build-bottle` with `brew install libsndfile` causes libsndfile to be compiled locally. But I'm not sure what other flags to set, to make the build is as generic as possible. Otoh that question doesn't really need to be addressed in the pull request, I think, but in the Travis build (if it's going to be used for the release)

**Comment by bagong** [comment]
Btw, a similar question could be asked for readline, but I am actually not really sure if readline is really used in the build, even if you specify the library locations for it. I seem to have observed some time ago that in the actual build OSX provided libedit is used anyways (and FFTW cannot be used at all any more in OSX), but I am not fully sure that that's still the case.

**Comment by crucialfelix** [comment]
You can now install libsnd with homebrew and build with FLAC and ogg support. (otherwise it uses the older bundled version) (as of #1870)

We should probably get travis to also install it, then the official release will have FLAC support too.

**Comment by samaaron** [comment]
That's great to hear. Will your travis auto-release mechanism build binaries that will work back as far as OS X 10.7?

I've got local builds of scsynth 3.6.6 working with FLAC-capable libsndfile (which I've tested on both OS X 10.7 and 10.11). However, I can't seem to get scsynth 3.7 to compile back on OS X 10.7.

**Comment by bagong** [comment]
Trying this this very moment! SCsynth won't compile on 3.7, but you can build with 3.9 and set the deployment target to 10.7. Just checking if it actually works.

**Comment by miczac** [comment]
@samaaron  - I compiled 3.7+ & current master on 10.10 w/ Xcode 7.2 w/ deployment target 10.7.

**Comment by bagong** [comment]
@miczac, we want it from travis! The build is done, but I can download it. This link should in theory work, but it gives a AccessDenied error... Anybody knows how to download builds from individual commits, or a PR?
    http://supercollider.s3.amazonaws.com/builds/supercollider/supercollider/osx/SC-789f2fcbb80f65b7d4f53449407e24fbd940f91b.zip

**Comment by bagong** [comment]
I think I have to sleep now. If it is not possible to download builds from individual commits, we could merge that PR and try to download the 3.7-latest, and then revert again if it's not okay. But that's not tidy either... I'll be back tomorrow morning.
The nice thing is that as a byproduct we detected that CMAKE_OSX_DEPLOYMENT_TARGET=10.9 mistake. Would have been pretty unfortunate if 3.7.1 had been released like that ;)

**Comment by bagong** [comment]
this hash doesn't work either
dc0a449da2f3528c8cb05a76386cd4c5a27a1292

**Comment by miczac** [comment]
sorry, I misread it.

**Comment by bagong** [comment]
@miczac, no worries, sorry for being a bit short-worded, it was late at night ;)
@samaaron, I think it's okay now. But I am not sure if it's portable to sonic pi, I think you have a different folder-structure in the Mac bundle? So you might have to build yourself anyways. The core thing is to send the sc-plugins through fixup_bundle too, as the DiskIO_UGens need fixup as well. Using a 10.9 build system and building with support down to 10.7 hasn't ever surfaced a problem for SC users, I guess it's safe. 10.6 is a different story because you might want universal binaries (if I remember correctly).

**Comment by samaaron** [comment]
@bagong  Sonic Pi just needs the `scsynth` binary and a folder of compiled ugens. If `libsndfile` is external, then it would need that and all its deps too :-)

**Comment by bagong** [comment]
@samaaron, yes. The problem I suspect is that scsynth and DiskIO_UGens need to know where the libsndfile and friends are located in the bundle. They do so now in the SC bundle, but that info might not port properly into the sonic pi bundle. Please correct me if I am wrong, I am still not fully at the bottom of what fixup bundle actually does.

**Comment by crucialfelix** [comment]
Let's make a separate build target for just getting scsynth and the plugins:

https://github.com/supercollider/supercollider/issues/1938
