### ISSUE TITLE
Denormals in Linux

### ISSUE THREAD

**Issue by backseatviolist** [supercollider/supercollider#1785]
Run the following (using JPverb from sc3-plugins) and leave it running for a while:

    (
    { JPverb.ar(Saw.ar(100) * EnvGen.kr(Env.perc(0.01, 1), Impulse.kr(0))) * 0.1 }.play;
    { SinOsc.ar(440) * EnvGen.kr(Env.perc(0.01, 1), Impulse.kr(1)) * 0.1!2 }.play;
    )

Weird, glitchy audio happens after about one minute, and at that point the CPU usage spikes to 15% and JACK reports numerous xruns.

This reeks of a denormal problem, and it arises because JPverb has no built-in protection from denormals (unlike many other SC ugens, which use zapgremlins). But here's why I'm reporting this here -- denormals should not be occurring anyway since sc_SetDenormalFlags disables them on CPU architectures supporting SSE or SSE2. I am on 32-bit Linux and my processor definitely supports SSE2, as most modern ones do.

By the way, I'm using the 3.7 branch (the current master doesn't compile for me).

**Comment by telephon** [comment]
>By the way, I'm using the 3.7 branch (the current master doesn't compile for me).

maybe file an issue if you think it might not just be you. Have you tried to make a clean build?

**Comment by backseatviolist** [comment]
The master is broken in [at least one other way](https://github.com/supercollider/supercollider/pull/1758#issuecomment-162440147), so I assume that it's not intended for testing.

**Comment by telephon** [comment]
>The master is broken in at least one other way, so I assume that it's not intended for testing.

Hm, I don't understand. The issue you link has been closed. Of course the master is intended for testing. If it doesn't compile, we need to find out why.
