### ISSUE TITLE
MulAddUGens broken

### ISSUE THREAD

**Issue by sonoro1234** [supercollider/supercollider#1793]
Some atk samples were not working (cracky noise) with a recent compilation. In order to search for the problem I replaced the some new dll with the old ones until the problem dissapeared, the releveant module was MulAddUGens with only one commit from @timblechmann in the recent history.
I will try to find the bug until someone (perhaps Tim) can find it.

**Comment by sonoro1234** [comment]
MulAddUGens last comit only affects to registering the plugin, so dont seem the cause.
May be the changes in nova-simd are more relevant (but they are too much for me) they are only related to provide support for fma3. My compiler is gcc 4.8.2.

**Comment by timblechmann** [comment]
reproducer or minimal test case?

**Comment by sonoro1234** [comment]
Should be silence but it is not in recent compilation:
```
SynthDef("aaa",{},function() 
	local sig = Sum4(SinOsc.ar(200),SinOsc.ar(200,0,-1),SinOsc.ar(100),SinOsc.ar(100,0,-1))
	-- local sig = SinOsc.ar(200) + SinOsc.ar(200,0,-1) + SinOsc.ar(100) + SinOsc.ar(100,0,-1)
	Out.ar(0,sig:dup())
end):play()
```

**Comment by timblechmann** [comment]
```
ERROR: syntax error, unexpected NAME, expecting BEGINCLOSEDFUNC or '{'
  in file 'selected text'
  line 2 char 9:

      local sig = Sum4(SinOsc.ar(200),SinOsc.ar(200,0,-1),SinOsc.ar(100),SinOsc.ar(100,0,-1))
      ^^^^^
      -- local sig = SinOsc.ar(200) + SinOsc.ar(200,0,-1) + SinOsc.ar(100) + SinOsc.ar(100,0,-1)
-----------------------------------
ERROR: Command line parse failed
-> nil

```

@sonoro1234 i know this is lua, but i cannot just paste it into my scide and run it.

**Comment by sonoro1234** [comment]
```
{ Sum4(SinOsc.ar(200),SinOsc.ar(200,0,-1),SinOsc.ar(100),SinOsc.ar(100,0,-1))}.play
```

**Comment by danstowell** [comment]
Oh yes, for me (on latest master 051b909) that plays a tone (when it should be silent). If I try this on 3.7 it is correctly silent.

**Comment by timblechmann** [comment]
thanks a lot ... much easier to find with a clean reproducer ...
