### ISSUE TITLE
write down an agreed git-workflow for SuperCollider development

### ISSUE THREAD

**Issue by LFSaw** [supercollider/supercollider#1796]
I think to prevent issues such as the ones described at #1794, it is important to have an agreed git-workflow for SuperCollider development.

The [git-cheat-sheet](http://supercollider.github.io/development/git-cheat-sheet.html#a-common-git-workflow-for-development-work-on-supercollider) might be a starting point, however, it seems to be outdated and quite hidden. 
Furthermore, as @timblechmann pointed out the intention of the document must be clear:

> there are plenty of git tutorials out there, i'm not sure if it is a good idea to write yet another one. 

That mentioned, though there are plenty of git tutorials, there are also certainly more than a bunch of ways on how a git-based contribution process might/should work (depending on the developer community and personal opinions on what is the way to go).
Therefore, I suggest to _outline_ (in very brief words) how the SC community prefers to receive contributions, possibly (and hopefully) with lots of links to the aforementioned tutorials on git usage. 

I am happy to contribute by formatting and rephrasing but will certainly need advice (which in turn will make me learn how to do things). Anyone wants to help out?

**Comment by LFSaw** [comment]
starting point:

## initial (once)

0a. Have a github account
0b. fork supercollider

## feature development / bug-fixing

1. align your repository to the latest HEAD on master (link to external howto)
3. create branch with reasonable name (naming scheme)
4. work work work inside branch
5. test test test inside branch
6. commit locally
7. commit to remote (personal) fork (link to external howto)
8. create PR (link to external howto)
9. wait for travis
10. fix emerging issues (raised from both, travis and other devs)
	+ where? in my forked repository? how to reflect possible contributions from other dev's?
10. wait for approval, negative: goto 9. else 
11. merge happens (via someone else)

**Comment by timblechmann** [comment]
possible starting point:
https://help.github.com/categories/collaborating-on-projects-using-pull-requests/

**Comment by LFSaw** [comment]
@jamshark70 very helpful comments

> 1. align your repository to the latest HEAD on master (how to do that?)

First you need to add a remote reference pointing to the main SC repository: `git remote add upstream whatever_the_URL_is_too_lazy_to_look_it_up_now`. Then, when you need to sync:

```
git fetch upstream
git checkout master
git merge upstream/master
```

Note that I didn't figure this out on my own. Github's help pages on forking are very well done.

> 8. create PR (how?)

Github website. Visit the main SC repository and it will tell you that you recently pushed a branch, and ask if you want to make a PR.

> + where? in my forked repository? how to reflect possible contributions from other dev's?

Yes, updates have to go into the branch that is the source of the PR. If you pushed the branch into your fork, then updates have to go there too. You'd have to give other devs write access, or use patch files from `git format-patch`.

(Sorry to go further off topic. I wrote the above before gusano's message came in.)

**Comment by LFSaw** [comment]
@timblechmann very helpful comment:

>      1. align your repository to the latest HEAD on master (how to do that?)

"github align your repository to the latest HEAD on master"
first google hit:
https://stackoverflow.com/questions/7244321/how-to-update-a-github-forked-repository


>      1. create PR (how?)

"github how to create pull request"
first google hit:
https://help.github.com/articles/creating-a-pull-request/

**Comment by gusano** [comment]
Thanks for the new issue @LFSaw.
I also wrote a [Pull Request suggested workflow](http://supercollider.github.io/contributing/index.html) a while ago on http://supercollider.github.io

**Comment by LFSaw** [comment]
thanks for the info, @gusano, I added it to the description in the first comment of this issue. Please edit along to your liking.

**Comment by snappizz** [comment]
Let's revive this. I think it's best to use the GitHub wiki for this, since it's really convenient to edit.

**Comment by telephon** [comment]
Good! I tried the steps, and got stuck after:

```
git checkout master # switch to master branch
git pull upstream master # download the latest and the greatest

```

The following:
`git push origin master # update your fork on GitHub`

will point to the intricate documentation of fast forwarding:

```
$ git push origin master
To git@github.com:telephon/supercollider.git
 ! [rejected]        master -> master (non-fast-forward)
error: failed to push some refs to 'git@github.com:telephon/supercollider.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
```

**Comment by telephon** [comment]
This is one reason why I never use my own master but only `supercollider/master` for making new branches.

**Comment by jamshark70** [comment]
I make it a point, before making a branch for a PR, to:

```
git fetch upstream
git merge upstream/master
```

and only then `git checkout -b ...`.

I never commit directly into master.

I never merge a local branch directly into master.

It's always: up-to-date master --> local topic branch --> remote topic branch (in my fork at github) --> pull request --> upstream master --> fetch and merge into local master, rinse and repeat.

Following this procedure strictly has generally kept me out of trouble.

**Comment by brianlheim** [comment]
@telephon  I think you might want to `git pull origin master` before anything else.

**Comment by telephon** [comment]
@brianlheim thank you - but this causes me a lot of conflicts with submodules that were added, but which can't be removed (e.g. portaudio in this case). I'll be able to fix it probably, but we may have to find a way to direct contributors around them?

**Comment by telephon** [comment]
@jamshark70 isn't it safer to just use `supercollider/master` instead`?

**Comment by snappizz** [comment]
check it: https://github.com/supercollider/supercollider/wiki/git-workflow

I jotted down some of the release management stuff

**Comment by jamshark70** [comment]
> isn't it safer to just use supercollider/master instead?

@telephon I am following github's instructions from their own help pages to keep my fork in sync with supercollider/master.

About the submodules, what errors? When I switch branches, `git status` shows me some differences in submodule references, but I handle that by explicitly `git add`-ing only the specific files I want to commit. Unless I'm misunderstanding the issue you're seeing.

**Comment by telephon** [comment]
@jamshark70 it is more difficult here. When I try to update my master (which is very old, because I haven't used it for a long time), I get submodule errors I can't get rid of by means of git. It have to delete the files and then check them out again, then I can switch branches again. But it can be quite complicated.

**Comment by jamshark70** [comment]
Hm, indeed, I've had repositories get broken for whatever reason, and when that happens, normal procedures stop working. I think, though, that your repository is in an abnormal state, and we shouldn't try to write procedures that will handle unpredictable abnormal states... because, if the instructions are ok with your abnormal repository, they won't be ok with someone else's.

The thing to do is to fix your repository, or start over with a new clone. I've "rebooted" with a fresh clone more than once. `git format-patch` and `git am` are useful in that case to transfer commits "clean" (without the hidden metadata that are making your clone act weird).

**Comment by telephon** [comment]
Hm, these are good hints, thank you James. A new clone would get rid of all the branches in my own local repository though, wouldn't it. Many of them are stale, but I'd rather not lose them. I could just keep them in a copy of course.

**Comment by jamshark70** [comment]
Yes, that's what I've done. Worst case, I've been able to transfer comments from broken branches using patch files. A GUI tool like qgit can select multiple commits, save patches for them in a directory, and then you can `git am` them on top of a good branch in a different repository -- then you get only the changes in the commits without any problematic metadata. It isn't exactly convenient (especially if it requires some manual merges), but I've used this approach to rescue some work before.

`git` does seem to be a bit fiddly. It's a beautiful object model and it's very powerful, but it's so easy to get into trouble.

**Comment by telephon** [comment]
Ironically, one of the simple things that is missing is an `undo` tree that is consistent. In git, you simply can't just try things and then undo them, as it is common when you learn how to do things.

The documentation [here](https://git-scm.com/book/en/v2/Git-Basics-Undoing-Things) says: 

> At any stage, you may want to undo something. Here, we’ll review a few basic tools for undoing changes that you’ve made. Be careful, because you can’t always undo some of these undos. This is one of the few areas in Git where you may lose some work if you do it wrong.

**Comment by gusano** [comment]
> In git, you simply can't just try things and then undo them

@telephon Yes you can if you try things on new branches, even if that's a bit tedious

**Comment by telephon** [comment]
yes, still - you can't go fore and back within the chain of the modifications in a branch. You'd have to branch for each step you do, but that gets very confusing, especially in the final log.

There seems a formal tree operation layer missing. Any modification of a tree could be bidirectional in principle.

**Comment by LFSaw** [comment]
cool, people got interested :D

is the info at 
https://github.com/supercollider/supercollider/wiki/git-workflow
the one we're currently preferring / what came out of this thread?

Then, I'd update the info in the first comment accordingly.

**Comment by LFSaw** [comment]
Is there anything to be added to the description up in the first comment?
    Any reasonable name/title for a wiki page?

**Comment by LFSaw** [comment]
@snappizz Thanks for your infos!
I added a link to it to http://supercollider.github.io/contributing/index.html

**Comment by brianlheim** [comment]
This has been resolved; we are now using git-flow.

Documented in https://github.com/supercollider/supercollider/wiki/git-workflow-and-guidelines, and will be added to the forthcoming DEVELOPING.md
