### ISSUE TITLE
sclang compilation error in Linux

### ISSUE THREAD

**Issue by backseatviolist** [supercollider/supercollider#1797]
As before, I'm running Ubuntu Studio 14.04.3 LTS with gcc 4.8.4-2ubuntu1~14.04 and boost 1.55. Latest master fails with the following error:

    /home/nathan/src/supercollider/lang/LangSource/PyrObject.cpp: In function ‘size_t fillClassRow(const PyrClass*, PyrMethod**, boost::executors::basic_thread_pool&)’:
    /home/nathan/src/supercollider/lang/LangSource/PyrObject.cpp:1388:62: error: no matching function for call to ‘irange(long unsigned int, size_t&)’
         for( int subClassIndex : boost::irange(0UL, numSubclasses) )
                                                                  ^
    /home/nathan/src/supercollider/lang/LangSource/PyrObject.cpp:1388:62: note: candidates are:
    In file included from /home/nathan/src/supercollider/lang/LangSource/PyrObject.cpp:43:0:
    /home/nathan/src/supercollider/external_libraries/boost/boost/range/irange.hpp:208:5: note: template<class Integer> boost::integer_range<Integer> boost::irange(Integer, Integer)
         irange(Integer first, Integer last)
         ^
    /home/nathan/src/supercollider/external_libraries/boost/boost/range/irange.hpp:208:5: note:   template argument deduction/substitution failed:
    /home/nathan/src/supercollider/lang/LangSource/PyrObject.cpp:1388:62: note:   deduced conflicting types for parameter ‘Integer’ (‘long unsigned int’ and ‘unsigned int’)
         for( int subClassIndex : boost::irange(0UL, numSubclasses) )
                                                                  ^
    In file included from /home/nathan/src/supercollider/lang/LangSource/PyrObject.cpp:43:0:
    /home/nathan/src/supercollider/external_libraries/boost/boost/range/irange.hpp:216:9: note: template<class Integer, class StepSize> boost::strided_integer_range<Integer> boost::irange(Integer, Integer, StepSize)
             irange(Integer first, Integer last, StepSize step_size)
             ^
    /home/nathan/src/supercollider/external_libraries/boost/boost/range/irange.hpp:216:9: note:   template argument deduction/substitution failed:
    /home/nathan/src/supercollider/lang/LangSource/PyrObject.cpp:1388:62: note:   deduced conflicting types for parameter ‘Integer’ (‘long unsigned int’ and ‘unsigned int’)
         for( int subClassIndex : boost::irange(0UL, numSubclasses) )
                                                                  ^
    /home/nathan/src/supercollider/lang/LangSource/PyrObject.cpp:1394:62: error: no matching function for call to ‘irange(long unsigned int, size_t&)’
         for( int subClassIndex : boost::irange(1UL, numSubclasses) ) {
                                                                  ^
    /home/nathan/src/supercollider/lang/LangSource/PyrObject.cpp:1394:62: note: candidates are:
    In file included from /home/nathan/src/supercollider/lang/LangSource/PyrObject.cpp:43:0:
    /home/nathan/src/supercollider/external_libraries/boost/boost/range/irange.hpp:208:5: note: template<class Integer> boost::integer_range<Integer> boost::irange(Integer, Integer)
         irange(Integer first, Integer last)
         ^
    /home/nathan/src/supercollider/external_libraries/boost/boost/range/irange.hpp:208:5: note:   template argument deduction/substitution failed:
    /home/nathan/src/supercollider/lang/LangSource/PyrObject.cpp:1394:62: note:   deduced conflicting types for parameter ‘Integer’ (‘long unsigned int’ and ‘unsigned int’)
         for( int subClassIndex : boost::irange(1UL, numSubclasses) ) {
                                                                  ^
    In file included from /home/nathan/src/supercollider/lang/LangSource/PyrObject.cpp:43:0:
    /home/nathan/src/supercollider/external_libraries/boost/boost/range/irange.hpp:216:9: note: template<class Integer, class StepSize> boost::strided_integer_range<Integer> boost::irange(Integer, Integer, StepSize)
             irange(Integer first, Integer last, StepSize step_size)
             ^
    /home/nathan/src/supercollider/external_libraries/boost/boost/range/irange.hpp:216:9: note:   template argument deduction/substitution failed:
    /home/nathan/src/supercollider/lang/LangSource/PyrObject.cpp:1394:62: note:   deduced conflicting types for parameter ‘Integer’ (‘long unsigned int’ and ‘unsigned int’)
         for( int subClassIndex : boost::irange(1UL, numSubclasses) ) {
                                                                  ^
    make[2]: *** [lang/CMakeFiles/libsclang.dir/LangSource/PyrObject.cpp.o] Error 1
    make[1]: *** [lang/CMakeFiles/libsclang.dir/all] Error 2
    make: *** [all] Error 2

Is my Boost version too old, maybe?

**Comment by redFrik** [comment]
here’s a hack that fixes that irange error (on 32bit system, gcc 4.8.4).

in your supercollider source directory...
`sed -i 's/UL, numSubclasses/UL, (long unsigned int)numSubclasses/g' lang/LangSource/PyrObject.cpp`

see this thread… http://new-supercollider-mailing-lists-forums-use-these.2681727.n2.nabble.com/supercollider-supercollider-fb44f1-sclang-remove-unused-header-tt7622182.html

**Comment by danstowell** [comment]
Thanks @redFrik, did anyone commit that, or make a PR? Is it a hack or is it the correct fix?

**Comment by redFrik** [comment]
it's a nasty workaround-only hack that shouldn't be committed.  sorry i don't know how to fix it properly.

**Comment by crucialfelix** [comment]
bug ? what needs to be done to resolve this ?

**Comment by backseatviolist** [comment]
I don't understand what exactly is causing this problem.

**Comment by danstowell** [comment]
Chris, FYI Tim diagnosed the issue in that other thread (linked above). I'm not sure why @redFrik says the fix is hacky, but getting the numerical types to match up should presumably fix it. However I'd vote for fixing it by doing the opposite cast from the one he chose, i.e. replace "0UL" and "1UL" with "(size_t)0" and "(size_t)1" since size_t is more semantic. Anyway that's moot since the iteration variable is a plain old "int"! So that should go to size_t too? I haven't looked at the code itself, so just pontificating at this point

**Comment by redFrik** [comment]
er, by hacky i mainly meant the way i did it... search&replace directly in the cpp file.  but also partly because i changed a thing i really have no clue about.  anyway, if it's fixed in the source code and reviewed then i'm not against it.
