### ISSUE TITLE
HelpBrowser find-box does not work correctly

### ISSUE THREAD

**Issue by jleben** [supercollider/supercollider#180]
[Issue migrated from SourceForge | ID: 3310710 | Submitted by 'lijon']
[http://sourceforge.net/support/tracker.php?aid=3310710]

with Qt gui:
cmd-f opens the Edit->Find menu item instead. ctrl-f doesn't do anything

with Cocoa gui:
cmd-f opens both Edit->Find and the helpbrowser find-box, but the find-box does not work and it doesn't close on Escape key.

**Comment by scztt** [comment]
This is fixed. Closing.
