### ISSUE TITLE
cmake: if on ARM, automatically disable SSE and SSE2 flags

### ISSUE THREAD

**Issue by danstowell** [supercollider/supercollider#1802]
In the main SuperCollider project, there are SSE and SSE2 cmake options for the user, that can be turned off. The user must turn them off when on ARM. It would be neat if the project automatically deactivated those flags on ARM.

cf discussion here:
https://github.com/danstowell/sc3-plugins/commit/e8358821b70a5569903dc34c251f74277994f11a#commitcomment-15505958

**Comment by redFrik** [comment]
+1
