### ISSUE TITLE
Crash at Buffer.plot

### ISSUE THREAD

**Issue by jleben** [supercollider/supercollider#181]
[Issue migrated from SourceForge | ID: 3311205 | Submitted by 'jleben']
[http://sourceforge.net/support/tracker.php?aid=3311205]

sclang crashes when plot is called twice in a row on a large enough Buffer. The example code below reproduces the crash.
The crash happens unrelated to whether in- or out-of-process server is used, both with Qt and Swing GUI, so I guess it's not GUI dependent.
The attached gdb backtrace shows that it might be a GC corruption.

Example code:

s.boot;
b = Buffer.alloc( s, s.sampleRate \* 3, 3 );
b.plot;
// close the window
b.plot; // again
// crash!

**Comment by scztt** [comment]
Moving this to future. It's worth investigation, and we should have unit tests around large memory allocation. However, I was able to do this successfully with VERY large blocks of data - large enough that it took minutes to actually perform the plot - so it's safe to say that this is an edge case at the moment.

**Comment by telephon** [comment]
seems ok now.
