### ISSUE TITLE
UserView Qt doesn't support Retina/HiDPI display

### ISSUE THREAD

**Issue by woutersnoei** [supercollider/supercollider#1810]
Ever since the introduction of Qt in SC the (at the time not so common) retina display has been unsupported by UserViews. In the old Cocoa UserViews show up nicely in full resolution, but in Qt-based 3.5, SC3.6 and SC3.7 anything displayed in a UserView looks jagged and low-res on a retina or HiDPI display. The code below should produce two lines of text indistinguishable from each other, and they do in SC3.5.3 Cocoa (left in image), but not in 3.7.0 beta1 on a Macbook Pro 15' Retina. 

`w = Window("3.7.0").front;`
`u = UserView(w, Rect(10,10,120, 20) )`
`.drawFunc_({ Pen.stringInRect( "the lazy fox etc.", Rect(0,0,120,20) ) });`
`t = StaticText(w, Rect(10,35,120,20) )`
`.string_( "the lazy fox etc." );`

<img width="306" alt="userview_retina" src="https://cloud.githubusercontent.com/assets/472356/12448107/26fa864c-bf74-11e5-9d60-e70d69e96524.png">
(on non-retina display; click to view the image in full size)

**Comment by telephon** [comment]
This is a really serious limitation to those who do a lot of graphics. For someone who knows QT, it may be easy to solve.

**Comment by gusano** [comment]
@telephon @woutersnoei I submit a PR but I have no mac with retina display so you guys would have to give it a try.

**Comment by telephon** [comment]
Thank you!

**Comment by crucialfelix** [comment]
sadly pr #2019 didn't work

see http://blog.qt.io/blog/2013/04/25/retina-display-support-for-mac-os-ios-and-x11/

I just tried adding those keys to the plist

```
	<key>NSHighResolutionCapable</key>
	<string>True</string>
```

but it's still chunky.

![plists-changed](https://cloud.githubusercontent.com/assets/218738/15012005/71aef7b2-11f5-11e6-8bcc-32043332c8cd.png)

**Comment by adcxyz** [comment]
In Qt 5.6 there seems to be a way to set it:

QApplication::setAttribute(Qt::AA_EnableHighDpiScaling);

but AFAIK we cant switch 5.6 yet because it replaces Qt5WebKit with WebEngine.

**Comment by telephon** [comment]
I don't know how much refactoring the port to WebEngine will mean – it is probably a good idea to do it, because Qt5WebKit is not developed further. For reference, here is a guide:

http://doc.qt.io/qt-5/qtwebenginewidgets-qtwebkitportingguide.html

The most complicated (and worthwhile) thing is in the new async logic, as it seems.

**Comment by telephon** [comment]
The other good thing is that it seems to be rather straightforward to include rich text (saved as a html-subset).

>"The rich text support in Qt is designed to provide a fast, portable and efficient way to add reasonable online help facilities to applications, and to provide a basis for rich text editors. If you find the HTML support insufficient for your needs you may consider the use of Qt WebKit, which provides a full-featured web browser widget."

**Comment by telephon** [comment]
But for the current issue, maybe there is a QT 5.5. solution here?:

http://blog.qt.io/blog/2013/04/25/retina-display-support-for-mac-os-ios-and-x11/

The examples look as if it had already been solved then.

**Comment by telephon** [comment]
Fixed now, in https://github.com/supercollider/supercollider/commit/7201aa7016f2de87b2827cf6bcc2b0f1f952b7a0
