### ISSUE TITLE
The Font help file has a syntax error

### ISSUE THREAD

**Issue by vanhuman** [supercollider/supercollider#1811]
Then calling Apple-D on Font this is the error: 

ERROR: In /Applications/SuperCollider 3.7.0 beta1/SuperCollider 3.7.0 beta1.app/Contents/Resources/HelpSource/Classes/Font.schelp:
  At line 97: syntax error, unexpected ::, expecting end of file

Tested on OSX 10.9.4

**Comment by snappizz** [comment]
#1813 has fixed this. Can somebody close?
