### ISSUE TITLE
compilation error on slackware linux 

### ISSUE THREAD

**Issue by DavideMaggio** [supercollider/supercollider#1814]
I've just updated my local repository and it doesn't compile anymore on my slackware linux box:

------------------------------------------------------------------------------------------------------------
 [  0%] Built target tlsf
[  1%] Built target yaml
[  1%] Built target hidapi_parser
[  1%] Built target BinaryOpUGens
[  1%] Built target hidapi
[  1%] Built target BinaryOpUGens_supernova
[  1%] [  1%] [  1%] [  2%] Built target ChaosUGens_supernova
Built target ChaosUGens
Built target DelayUGens
Built target DelayUGens_supernova
[  2%] Built target DemandUGens
[  3%] [  3%] Built target DynNoiseUGens
Built target DemandUGens_supernova
[  3%] Built target DynNoiseUGens_supernova
[  3%] Built target DiskIO_UGens_supernova
[  3%] Built target DiskIO_UGens
[  4%] [  4%] Built target FFT_UGens
Built target FFT_UGens_supernova
[  4%] [  4%] [  4%] [  5%] Built target GendynUGens_supernova
Built target GrainUGens
Built target FilterUGens
Built target FilterUGens_supernova
[  5%] Built target GendynUGens
[  5%] Built target LFUGens
[  5%] Built target GrainUGens_supernova
[  6%] [  6%] Built target IOUGens
Built target IOUGens_supernova
[  6%] Built target LFUGens_supernova
[  7%] Built target ML_UGens_supernova
[  7%] Built target MulAddUGens_supernova
[  8%] Built target MulAddUGens
[ 10%] Built target ML_UGens
[ 11%] [ 11%] [ 11%] [ 11%] Built target OscUGens
Built target OscUGens_supernova
Built target NoiseUGens
Built target NoiseUGens_supernova
[ 11%] Built target PV_ThirdParty
[ 12%] Built target PhysicalModelingUGens
[ 12%] [ 12%] Built target PhysicalModelingUGens_supernova
[ 12%] Built target PanUGens
Built target PanUGens_supernova
[ 12%] Built target ReverbUGens
[ 13%] [ 13%] Built target PV_ThirdParty_supernova
Built target ReverbUGens_supernova
[ 13%] Built target TestUGens
[ 13%] Built target TestUGens_supernova
[ 13%] Built target TriggerUGens
[ 14%] [ 14%] Built target TriggerUGens_supernova
Built target UIUGens
[ 14%] Built target UIUGens_supernova
[ 14%] [ 14%] Built target UnaryOpUGens_supernova
Built target UnaryOpUGens
[ 15%] [ 15%] Built target UnpackFFTUGens
Built target UnpackFFTUGens_supernova
[ 15%] Built target boost_system
[ 15%] Built target oscpack
[ 16%] Built target boost_filesystem
[ 17%] Built target boost_test
[ 17%] Built target boost_thread
[ 19%] Built target boost_program_options
[ 24%] Built target libscsynth
[ 24%] Built target scsynth
[ 27%] Built target libsupernova
[ 28%] Built target buffer_manager_test
Scanning dependencies of target callback_interpreter_system
Scanning dependencies of target memory-pool_test
[ 28%] Building CXX object server/supernova/CMakeFiles/supernova.dir/server/main.cpp.o
[ 28%] [ 28%] Building CXX object testsuite/supernova/CMakeFiles/callback_interpreter_system.dir/callback_interpreter_system.cpp.o
Building CXX object testsuite/supernova/CMakeFiles/memory-pool_test.dir/memory-pool_test.cpp.o
In file included from /home/mag/07___CODE/REPOS/supercollider/supercollider/server/supernova/./server/memory_pool.hpp:22:0,
                 from /home/mag/07___CODE/REPOS/supercollider/supercollider/testsuite/supernova/memory-pool_test.cpp:6:
/home/mag/07___CODE/REPOS/supercollider/supercollider/server/supernova/./server/../utilities/simple_pool.hpp:24:18: fatal error: tlsf.h: No such file or directory
 #include "tlsf.h"
                  ^
compilation terminated.
make[2]: *** [testsuite/supernova/CMakeFiles/memory-pool_test.dir/memory-pool_test.cpp.o] Error 1
make[1]: *** [testsuite/supernova/CMakeFiles/memory-pool_test.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 58%] Built target SuperCollider
In file included from /home/mag/07___CODE/REPOS/supercollider/supercollider/server/supernova/server/memory_pool.hpp:22:0,
                 from /home/mag/07___CODE/REPOS/supercollider/supercollider/server/supernova/server/server.hpp:25,
                 from /home/mag/07___CODE/REPOS/supercollider/supercollider/server/supernova/server/main.cpp:28:
/home/mag/07___CODE/REPOS/supercollider/supercollider/server/supernova/server/../utilities/simple_pool.hpp:24:18: fatal error: tlsf.h: No such file or directory
 #include "tlsf.h"
                  ^
compilation terminated.
make[2]: *** [server/supernova/CMakeFiles/supernova.dir/server/main.cpp.o] Error 1
make[1]: *** [server/supernova/CMakeFiles/supernova.dir/all] Error 2
[ 97%] Built target libsclang
Linking CXX executable callback_interpreter_system
[ 97%] Built target callback_interpreter_system
make: *** [all] Error 2
------------------------------------------------------------------------------------------------------------

It has always worked before (my kernel is 3.10.17).

any suggestion?

thanks.

**Comment by danstowell** [comment]
Hi - could you please do `git submodule init && git submodule update` and let us know if the issue remains?

**Comment by DavideMaggio** [comment]
...something changed but I got same error with tlsf.h:


--------------------------------------------------------------------------------------------------------
[......]

[ 59%] Built target SuperCollider
In file included from /home/mag/07___CODE/REPOS/supercollider/SuperCollider/server/supernova/./server/memory_pool.hpp:22:0,
                 from /home/mag/07___CODE/REPOS/supercollider/SuperCollider/testsuite/supernova/memory-pool_test.cpp:6:
/home/mag/07___CODE/REPOS/supercollider/SuperCollider/server/supernova/./server/../utilities/simple_pool.hpp:24:18: fatal error: tlsf.h: No such file or directory
 #include "tlsf.h"
                  ^
compilation terminated.
make[2]: *** [testsuite/supernova/CMakeFiles/memory-pool_test.dir/memory-pool_test.cpp.o] Error 1
make[1]: *** [testsuite/supernova/CMakeFiles/memory-pool_test.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
Scanning dependencies of target server_synth_factory_test
Scanning dependencies of target server_scheduler_test
In file included from /home/mag/07___CODE/REPOS/supercollider/SuperCollider/server/supernova/./server/memory_pool.hpp:22:0,
                 from /home/mag/07___CODE/REPOS/supercollider/SuperCollider/server/supernova/./server/node_types.hpp:26,
                 from /home/mag/07___CODE/REPOS/supercollider/SuperCollider/server/supernova/./server/synth.hpp:27,
                 from /home/mag/07___CODE/REPOS/supercollider/SuperCollider/server/supernova/./server/dsp_thread_queue_node.hpp:27,
                 from /home/mag/07___CODE/REPOS/supercollider/SuperCollider/server/supernova/./server/node_graph.hpp:25,
                 from /home/mag/07___CODE/REPOS/supercollider/SuperCollider/testsuite/supernova/server_node_graph_test.cpp:3:
/home/mag/07___CODE/REPOS/supercollider/SuperCollider/server/supernova/./server/../utilities/simple_pool.hpp:24:18: fatal error: tlsf.h: No such file or directory
 #include "tlsf.h"
                  ^
compilation terminated.
make[2]: *** [testsuite/supernova/CMakeFiles/server_node_graph_test.dir/server_node_graph_test.cpp.o] Error 1
make[1]: *** [testsuite/supernova/CMakeFiles/server_node_graph_test.dir/all] Error 2
In file included from /home/mag/07___CODE/REPOS/supercollider/SuperCollider/server/supernova/./server/memory_pool.hpp:22:0,
                 from /home/mag/07___CODE/REPOS/supercollider/SuperCollider/testsuite/supernova/server_dsp_thread_test.cpp:6:
/home/mag/07___CODE/REPOS/supercollider/SuperCollider/server/supernova/./server/../utilities/simple_pool.hpp:24:18: fatal error: tlsf.h: No such file or directory
 #include "tlsf.h"
                  ^
compilation terminated.
make[2]: *** [testsuite/supernova/CMakeFiles/server_dsp_thread_test.dir/server_dsp_thread_test.cpp.o] Error 1
make[1]: *** [testsuite/supernova/CMakeFiles/server_dsp_thread_test.dir/all] Error 2
[ 59%] Building CXX object testsuite/supernova/CMakeFiles/server_synth_factory_test.dir/server_synth_factory_test.cpp.o
[ 73%] [ 99%] Built target libsclang
Building CXX object testsuite/supernova/CMakeFiles/server_scheduler_test.dir/server_scheduler_test.cpp.o
In file included from /home/mag/07___CODE/REPOS/supercollider/SuperCollider/server/supernova/server/memory_pool.hpp:22:0,
                 from /home/mag/07___CODE/REPOS/supercollider/SuperCollider/server/supernova/server/server.hpp:25,
                 from /home/mag/07___CODE/REPOS/supercollider/SuperCollider/server/supernova/server/main.cpp:28:
/home/mag/07___CODE/REPOS/supercollider/SuperCollider/server/supernova/server/../utilities/simple_pool.hpp:24:18: fatal error: tlsf.h: No such file or directory
 #include "tlsf.h"
                  ^
compilation terminated.
make[2]: *** [server/supernova/CMakeFiles/supernova.dir/server/main.cpp.o] Error 1
make[1]: *** [server/supernova/CMakeFiles/supernova.dir/all] Error 2
In file included from /home/mag/07___CODE/REPOS/supercollider/SuperCollider/server/supernova/./server/memory_pool.hpp:22:0,
                 from /home/mag/07___CODE/REPOS/supercollider/SuperCollider/server/supernova/./server/node_types.hpp:26,
                 from /home/mag/07___CODE/REPOS/supercollider/SuperCollider/server/supernova/./server/synth.hpp:27,
                 from /home/mag/07___CODE/REPOS/supercollider/SuperCollider/server/supernova/./server/synth_factory.hpp:25,
                 from /home/mag/07___CODE/REPOS/supercollider/SuperCollider/testsuite/supernova/server_synth_factory_test.cpp:3:
/home/mag/07___CODE/REPOS/supercollider/SuperCollider/server/supernova/./server/../utilities/simple_pool.hpp:24:18: fatal error: tlsf.h: No such file or directory
 #include "tlsf.h"
                  ^
compilation terminated.
make[2]: *** [testsuite/supernova/CMakeFiles/server_synth_factory_test.dir/server_synth_factory_test.cpp.o] Error 1
make[1]: *** [testsuite/supernova/CMakeFiles/server_synth_factory_test.dir/all] Error 2
In file included from /home/mag/07___CODE/REPOS/supercollider/SuperCollider/server/supernova/./server/memory_pool.hpp:22:0,
                 from /home/mag/07___CODE/REPOS/supercollider/SuperCollider/server/supernova/./server/group.hpp:22,
                 from /home/mag/07___CODE/REPOS/supercollider/SuperCollider/server/supernova/./server/server_scheduler.hpp:25,
                 from /home/mag/07___CODE/REPOS/supercollider/SuperCollider/testsuite/supernova/server_scheduler_test.cpp:6:
/home/mag/07___CODE/REPOS/supercollider/SuperCollider/server/supernova/./server/../utilities/simple_pool.hpp:24:18: fatal error: tlsf.h: No such file or directory
 #include "tlsf.h"
                  ^
compilation terminated.
make[2]: *** [testsuite/supernova/CMakeFiles/server_scheduler_test.dir/server_scheduler_test.cpp.o] Error 1
make[1]: *** [testsuite/supernova/CMakeFiles/server_scheduler_test.dir/all] Error 2
make: *** [all] Error 2

--------------------------------------------------------------------------------------------

**Comment by danstowell** [comment]
OK thanks. It might be that the tlsf include directory needs adding in cmake, but I can't reproduce the error so I can't track it down. Perhaps @timblechmann knows.

**Comment by timblechmann** [comment]
double-checked the logic, it looks good: the include path is coming in via a usage requirement of tlsf. maybe an ancient version of cmake? i'd strongly suggest to increase the minimum required cmake version.

**Comment by DavideMaggio** [comment]
I upgraded my cmake from version 2.8.12 to 3.4.2 and it worked :)

thank you.
