### ISSUE TITLE
SC_SndBuf.h (in master) can't compile on ARM because uses _mm_pause 

### ISSUE THREAD

**Issue by danstowell** [supercollider/supercollider#1819]
commit cd6a72203ad causes me a build fail on ARM - the failing code looks like this:

```
#ifdef __SSE2__
	static inline void pause() { _mm_pause(); }
#else
	static inline void pause() { _mm_pause(); }
#endif
```
(From https://github.com/supercollider/supercollider/blob/master/include/plugin_interface/SC_SndBuf.h#L47)

Paging @timblechmann: it seems obvious that you probably intended to add a non-SSE2 alternative to _mm_pause() but didn't get round to it. It's beyond me to know any suggestions for this I'm afraid!

**Comment by timblechmann** [comment]
ah, yes ... this fallback code is bullshit ... it should just be an empty function, something like:
```
#ifdef __SSE2__
    static inline void pause() { _mm_pause(); }
#else
    static inline void pause() { }
#endif
```

**Comment by danstowell** [comment]
Thanks, that sounds easy - PR on the way
