### ISSUE TITLE
Building master with gcc 4.7 fails due to 'is_trivially_destructible' in SC_PlugIn.hpp

### ISSUE THREAD

**Issue by danstowell** [supercollider/supercollider#1820]
gcc 4.7 build fails due to 'is_trivially_destructible' in SC_PlugIn.hpp (added in 5712dccb1). That call is [not implemented by gcc 4.7](https://gcc.gnu.org/onlinedocs/gcc-4.7.2/libstdc++/manual/manual/status.html) but [is implemented by gcc 4.8+](https://gcc.gnu.org/onlinedocs/gcc-4.8.0/libstdc++/manual/manual/status.html).

So two possible solutions: (a) increase the GCC minimum version to 4.8; (b) change the header file. I guess (a) is the better thing to do (ubuntu 14.04 LTS and Debian Jessie already satisfies it by default, for example) but others may have other opinions.

**Comment by danstowell** [comment]
(For example, this BeagleBone is preinstalled with Debian Wheezy and doesn't have gcc 4.8 in the standard package repo, so that's a bit hobbling)

**Comment by timblechmann** [comment]
we have 2016, `std::is_trivially_destructible` is c++11 (11 as in 2011). c++11 is implemented with all modern compilers, which are widely used: gcc, clang, msvc.

my recommendation: if you want to use a spend your time on workarounds for old toolchains, work around it. though imho it is probably a waste of time, especially in the long term. if people want to use an old system, older supercollider versions might be sufficient.

**Comment by danstowell** [comment]
(fwiw I agree, especially as 3.7 is ready and it works fine with gcc 4.7. I'll simply do this if no-one objects.)

**Comment by jamshark70** [comment]
README_LINUX says:

```
 * gcc >= 4.6
   http://www.gnu.org/software/gcc
```

I have gcc 4.7.3 and I am getting this error message.

So which gcc version should I upgrade to?

**Comment by LFSaw** [comment]
on my machine (yosemite):

```shell
@ gcc -v
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 7.0.2 (clang-700.1.81)
Target: x86_64-apple-darwin14.5.0
Thread model: posix
```
```
@ which gcc
/usr/bin/gcc
```
compile and running of latest git tag 3.7 ( ccde47cbc645e78fbc569474c010888fb3289f97 ) works successfully. Cannot tell, thought, which gcc version this is equivalent to.

**Comment by danstowell** [comment]
@LFSaw thanks. ....... but please note, this thread is about the **master** branch. Tim has some "modern" code in the master branch which is NOT in the 3.7 branch. So the question is specifically about the bleeding-edge branch, whether we're all happy to ditch gcc 4.7 support going forwards.

**Comment by LFSaw** [comment]
It seems I read your comment wrong... 
checked out master and did a fresh compile which, with the above configuration, works fine. So no objections from my side... yosemite is the previous OSX version and it seems that it comes nowadays with a sufficiently recent compiler version. So a certain backwards compatibility for OSX is given. IMHO that's enough,

**Comment by danstowell** [comment]
Great, thanks for testing.

**Comment by danstowell** [comment]
Oh I just discovered that gcc 4.7 lacks another piece of C++11 which is now used by the source code. `std::map.emplace`. Right I'll merge #1839 soon, this is clear enough.

**Comment by LFSaw** [comment]
how's the situation on BeagleBone? I guess, @redFrik could know something about it...

**Comment by danstowell** [comment]
@LFSaw I'm currently testing on beaglebone. debian wheezy (standard choice?) only makes gcc4.7 available, which means it's not easy to build master, though building 3.7 is doable. debian jessie provides gcc48 fine.

I'll try adding gcc4.8 to my beaglebone and check that it works. should do.

thoughts from @redFrik would be welcome, since I don't really know what OS he uses with his

**Comment by redFrik** [comment]
yes, the last sc master i ever managed to build with gcc 4.7 (under debian wheezy) was c7600cc1c9 from 27mar2014.  see https://github.com/supercollider/supercollider/issues/1091

also don’t forget cmake minimum requirements.  iirc last time i tried the cmake version that sc master wanted wasn’t available under wheezy.  had to install that from debian testing and not sure if it'd work with gcc4.7 then.

debian wheezy is still the recommended and ’stable’ system for beaglebone black.

current master will compile with gcc4.8 under debian wheezy, but sclang freezes mysteriously at startup.
_f

> 30 jan 2016 kl. 16:46 skrev danstowell <notifications@github.com>:
> 
> @LFSaw I'm currently testing on beaglebone. debian wheezy (standard choice?) only makes gcc4.7 available, which means it's not easy to build master, though building 3.7 is doable. debian jessie provides gcc48 fine.
> 
> I'll try adding gcc4.8 to my beaglebone and check that it works. should do.
> 
> thoughts from @redFrik would be welcome, since I don't really know what OS he uses with his
> 
> —
> Reply to this email directly or view it on GitHub.
> 


  #|
     fredrikolofsson.com     musicalfieldsforever.com
  |#

**Comment by danstowell** [comment]
@redFrik yes the cmake requirement is just as you remember, it's a bit annoying.

gcc47 is not going to get fixed re the bug you found in 2014, so it's looking even more conclusive!

Massive shame about the sclang freeze that you mention. When I've finished compiling I'll see if I have similar symptoms.

**Comment by miczac** [comment]
On 30.Jan 2016, at 16:46 , danstowell <notifications@github.com> wrote:

> I'll try adding gcc4.8 to my beaglebone and check that it works. should do.

that should be fine indeed. 4.9.2 reveals some peculiar behaviour of sclang which I�m trying 
to track down - having a hard time doing so, ATM. ;)
