### ISSUE TITLE
scsynth: verbosity -1 & -2 not recognised - scsynth won't start

### ISSUE THREAD

**Issue by miczac** [supercollider/supercollider#1825]
from sc-users:
"Using SC 3.7 beta1, if I set verbosity to -1, or -2, I get errors. 
However, it works ok with verbosity set to 0.
This is not a problem with SC 3.6.6

Example code:
```
(
s.quit;
s.options.verbosity = -1;
s.boot;
)

ERROR:  server failed to start
```
I'm on OSX 10.11.1"
https://www.listarc.bham.ac.uk/lists/sc-users/msg48477.html

**Comment by sonoro1234** [comment]
look #1322

**Comment by sonoro1234** [comment]
it was not done in sclang also.
Thanks

**Comment by miczac** [comment]
sorry, got confused - what's your point?

**Comment by sonoro1234** [comment]
Just saying that we should have already done that when we changed it on scsynth and supernova.

**Comment by miczac** [comment]
Ah ... ;) 
Anyway - this could be closed, @crucialfelix, @danstowell ?

**Comment by crucialfelix** [comment]
fyi: when you do a PR or a commit you can say "Fixes #1825" somewhere in the commit message and it will automatically close the issue when it is merged.

**Comment by miczac** [comment]
@crucialfelix, like https://github.com/supercollider/supercollider/pull/1826#issue-128675862 ?

**Comment by crucialfelix** [comment]
well gee, you did do that. Maybe it has to be in the first line, or even at the start of the line.

**Comment by miczac** [comment]
Don't know if this answers that:
"If the commit is in a non-default branch, the issue will remain open and the issue will be referenced with a tooltip."
https://help.github.com/articles/closing-issues-via-commit-messages/
No word about the location of the key words.

**Comment by crucialfelix** [comment]
That makes sense. It would only be regarded as closed when its been merged
into master.

On Wed, Jan 27, 2016 at 2:40 AM Michael Zacherl <notifications@github.com>
wrote:

> Don't know if this answers that:
> "If the commit is in a non-default branch, the issue will remain open and
> the issue will be referenced with a tooltip."
> https://help.github.com/articles/closing-issues-via-commit-messages/
> No word about the location of the key words.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/supercollider/supercollider/issues/1825#issuecomment-175333997>
> .
>
-- 
https://twitter.com/crucialfelix
https://medium.com/@crucialfelix
http://www.mattermind.com/
