### ISSUE TITLE
There should be an AbstractObject class

### ISSUE THREAD

**Issue by olafklingt** [supercollider/supercollider#1831]
The math methods of the Symbol class to introduce the problem that programming mistakes are not caught in the right moment. 

James pointed out that this has a historical reason. A rest event could be specified by a symbol in one of the pitch keys, such as:

`Pbind(\degree, Pseq([0, 1, \r, 2, \r, 3, 4, \r], inf), \dur, 0.25)`

Currently you can make an event into a rest by setting the \isRest key to true (and, in event patterns like Pbind, by yielding a Rest(value) object or the Rest class itself). Before \isRest, years ago, \degree, \note, and \midinote are all converted to \freq by math operations. If symbols don't support math operators, then \r as above for a rest will choke with a "does not understand" error.

I propose that they should be deprecated and removed.

**Comment by telephon** [comment]
Note that the reason for this is a design decision. It has happened at a certain point in history, which doesn't automatically make it a bad one. 

The example @jamshark70 gave is not the only one: e.g. it happens also in ```Env```, where you can multiply curve arguments even when some of the curves are symbols. This is an indication that a change may have consequences for a lot of code. 

The underlying idea is that a symbol is an identity element with regards to math operations. There is always a trade off between generality and certainty.

Do you have an example that made you think this should not be as it is?

**Comment by olafklingt** [comment]
Only when you made a programming mistake and you have a symbol where a number should be and it is harder to trace the error. 

I have to say that it is true that the current behavior helped me before in the use case of multiplying arrays for Env.

**Comment by telephon** [comment]
Maybe this is a documentation problem more than anything else? The specific case of the `Rest` class is one that needs to be sorted out separately, I believe.

**Comment by olafklingt** [comment]
I think you convinced me that the broad approach as it is implemented has it's reasons.

just as a proposal the case when you want to multiply a array of symbols is not that common. 
as such it would be an option to implement a Identity class which implements the math functions and holds an object (in our case a symbol) 
so that we would write instead of:
[\freq,440]*2

[Identity(\freq),440]*2

this would be clear but yes more verbose.

(I do not follow the mailing list in the moment)

**Comment by telephon** [comment]
Yes, I agree that it would be good to have classes like that. Also a neutral element would be good, as well as a fully unspecified object (ProtoObject), whose interface can be safely extended. But that's for the future...

**Comment by olafklingt** [comment]
It would be interesting when you could specify the three classes you suggest to understand how they relate to this question or to understand as part of which bigger project you understand the point under discussion.

**Comment by telephon** [comment]
@olafklingt I can do this, even if it is a bit of a diversion (which I started).

Sometimes one needs to pass around "disguised" objects in the system, which behave like all the others used in that specific context, but have a different function. In our issue here, the symbols are disguised as numbers or math entities, in order to just stay the same (the symbol functions as a neutral (or identity) element: https://en.wikipedia.org/wiki/Identity_element). There are other cases where one needs to pass around some state wrapped in such an element (like the `Rest` objects).

Normally, we implement these neutral elements to be used in a specific context. But it would be good to have a superclass (e.g. `Neutral`) which is customizeable. It could derive from a very stupid object that knows less than `Object`, and you could specify what happens when `doesnNotUnderstand` is called.

Ok, this is about it, I hope this clarifies.

**Comment by telephon** [comment]
I've just renamed the issue, because the original motivation changed.

**Comment by telephon** [comment]
A good example implementation for an `AbstractObject` would be ruby's BasicObject: http://ruby-doc.org/core-2.4.0/BasicObject.html

**Comment by brianlheim** [comment]
I think this issue should exist (the one named by the title), but perhaps as a new ticket because it's confusing to read the history in this thread, and not much has actually been discussed.

**Comment by snappizz** [comment]
i don't really understand it either, but i'm pretty certain the new Operand class is a satisfactory resolution for this issue. closing.

**Comment by brianlheim** [comment]
The concept is clear to me, I was just saying it wouldn't be that hard to port the conversation to a new thread without the baggage of the earlier comments and change of topic. The idea of AbstractObject is different from Operand because it would have a more minimal interface than Object.

**Comment by brianlheim** [comment]
@telephon What do you think? Would you be ok with opening a new ticket for `AbstractObject`? Or reopening this? (Or something else?)

**Comment by telephon** [comment]
I'll open a new ticket, so we can continue the conversation there. Thanks !
