### ISSUE TITLE
sclang in master freezes on arm (due to PR #1677 / commit d0f475d)

### ISSUE THREAD

**Issue by danstowell** [supercollider/supercollider#1842]
Initially [mentioned](https://github.com/supercollider/supercollider/issues/1820#issuecomment-177218955) by @redFrik, who said "current master will compile with gcc4.8 under debian wheezy [on beaglebone], but sclang freezes mysteriously at startup".

I experience the same problem. I've spent the whole day doing `git bisect` (compiling takes a while on these little devices!) and it eventually finds the problem inside commit d0f475d, part of PR #1677 by @timblechmann.

When running sclang it gets as far as outputting all this:

<pre>
init_OSC
empty
compiling class library...
initPassOne started
	NumPrimitives = 590
initPassOne done
	compiling dir: '/usr/local/share/SuperCollider/SCClassLibrary'
	compiling dir: '/usr/local/share/SuperCollider/Extensions'
	pass 1 done
ERROR: Class extension for nonexistent class 'Document'
     In file:'/deprecated/3.7/deprecated-3.7.sc'
</pre>

...and then just sits there. It's not burning CPU or memory, just not ever moving on.

commit d0f475d describes itself as "avoid one indirection" and it's a little tricky to read through. I'm not familiar with this part of the code. I haven't got gdb yet on this device, and not sure how I'd diagnose this anyway.

We could reverse this single commit (in master)? I'd be grateful for thoughts. Tim may have insight into what's happening in that commit that's tripping us up here.

System details:
* Linux arm 3.8.13xenomai-bone41 #2 Wed Mar 26 11:41:31 GMT 2014 armv7l GNU/Linux
* gcc-4.8 (Debian 4.8.4-1) 4.8.4
* cmake version 3.0.2

**Comment by danstowell** [comment]
AHA I think I found a bug: https://github.com/supercollider/supercollider/commit/d0f475daae323509742a414826117d2850f9ccee?diff=unified#commitcomment-15786864

**Comment by timblechmann** [comment]
d0f475d should not really generate any stalls, it would only limit the number of threads used to generate the method table ...

**Comment by timblechmann** [comment]
... unless `std::thread::hardware_concurrency` isn't implemented ...

**Comment by danstowell** [comment]
OK @redFrik this freeze issue should now be fixed in master.

Fixed by #1844, cf #1843.

**Comment by redFrik** [comment]
Dan, you’re my big hero!
it now works to compile and start sc master on a beaglebone with debian jessie.  (gcc-4.8 - i also tried gcc-4.9 but it still gives the atIdentityHash error).
many thanks for your detective work.
_f

> 31 jan 2016 kl. 21:15 skrev danstowell <notifications@github.com>:
> 
> OK @redFrik this freeze issue should now be fixed in master.
> 
> Fixed by #1844, cf #1843.
> 
> —
> Reply to this email directly or view it on GitHub.
> 


  #|
     fredrikolofsson.com     musicalfieldsforever.com
  |#
