### ISSUE TITLE
IDE: leftmost Application Menu Entry has lost information

### ISSUE THREAD

**Issue by telephon** [supercollider/supercollider#1848]
I can't find the moment this changed, it might be an XCode setting.

This is how it was and should be:

<img width="598" alt="screen shot 2016-02-01 at 13 17 45" src="https://cloud.githubusercontent.com/assets/1810559/12734261/b9518340-c93f-11e5-80a9-8a6b471d2cc5.png">

And this is what XCode builds with the default settings:

<img width="531" alt="screen shot 2016-02-01 at 13 17 16" src="https://cloud.githubusercontent.com/assets/1810559/12734272/cbefaf90-c93f-11e5-9df5-ce37441994fa.png">

**Comment by brianlheim** [comment]
Ping. Could we get more information on this please?

**Comment by telephon** [comment]
It's gone. Thanks for pinging.

**Comment by brianlheim** [comment]
Great! Thanks for checking :)
