### ISSUE TITLE
uninitialized variable in compileAssignVar

### ISSUE THREAD

**Issue by jleben** [supercollider/supercollider#186]
[Issue migrated from SourceForge | ID: 3323874 | Submitted by 'timblech']
[http://sourceforge.net/support/tracker.php?aid=3323874]

a codepath in compileAssignVar uses an uninitialized variable. it should be either initialized correctly or the codepath should be removed

**Comment by scztt** [comment]
This is protected by an assert, one that we haven't hit in practice so far, so it's pragmatically safe at this point. It should be removed when someone can inspect the code and figure out what the code path in question is *supposed* to be doing, and ensure we can safely remove it...

**Comment by brianlheim** [comment]
Closing -- the assert is there, so we can create an issue if we ever hit it, but there are tons of "FIXMEs/TODOs" in Pyr code and this one isn't particularly special.

**Comment by snappizz** [comment]
Alright. You won't mind if I keep assigning you to old sclang issues, right?

**Comment by brianlheim** [comment]
Please go ahead! I wouldn't have looked at this otherwise.
