### ISSUE TITLE
scel: Directory change of sclang/scsynth in 3.7-beta1 causing error

### ISSUE THREAD

**Issue by dotinspace** [supercollider/supercollider#1860]
* OS X 10.11.3
* SC 3.7-beta1
* emacs 24.5 (installed with homebrew)

When trying to run `emacs -sclang` I get the following error:
```supercollider
/Applications/SuperCollider/SuperCollider.app/Contents/Resources/sclang: No such file or directory
*** SCLang exited abnormally with code 127 ***
```
Obviously, the folder should be `/Applications/SuperCollider/SuperCollider.app/Contents/MacOS` and not `/Applications/SuperCollider/SuperCollider.app/Contents/Resources` for 3.7, but trying to change that setting has no effect at all, and scel still tries to run from the Resources directory.

**Comment by miguel-negrao** [comment]
Grepping scel directory there aren't any hardcoded paths pointing to something ending in Resources. The readme says:

> Customization
> 
> To fine-tune the installation from within emacs' graphical customization interface, type:
> 
> M-x sclang-customize
> 
> In particular, you will have to customize `sclang-runtime-directory'.

So I think you just have to set sclang-runtime-directory correctly.

**Comment by dotinspace** [comment]
Nope. Not working. Settings changed through `sclang-customize` are not persistent. It resets to `.../Resources/sclang`. I can run sclang fine after I set program path and runtime directory manually, but would have to do that every time I start emacs. It is of course highly likely that I am doing something wrong. So, I suppose closing it makes sense. More people would have this problem if it was not just me doing something wrong in the setup. Thanks.

**Comment by jamshark70** [comment]
I haven't used the emacs interface in some time, but as I recall, I always used the M-x customize-group interface for these settings. It would persist them in ~/.emacs.

Maybe check ~/.emacs for stray assignments to the relevant variables? If there are any, it could step on the customize interface's toes.

**Comment by dotinspace** [comment]
Thanks for the tip, but `~/.emacs.d/init.el` has no conflicting assignments, unfortunately, so customise interface's toes are unscathed. I'll try one more time from scratch and see how it goes.
