### ISSUE TITLE
no .poll for Signal with mul:0

### ISSUE THREAD

**Issue by miczac** [supercollider/supercollider#1861]
while SinOsc apparently delivers a dc-value of 4 in this
```
{m = SinOsc.kr(0.5, 0, 0, 4); LFPulse.ar([100, 200], 0, 0.5, [-20.dbamp, -20.dbamp * m])}.play //scope that!
```
.poll shows no effect with its signal:
```
{m = SinOsc.kr(0.5, 0, 0, 4); m.poll}.play  // simply does nothing
```
whereas DC can be monitored:
```
{m = DC.kr(0); m.poll}.play
```
Why is that?

**Comment by telephon** [comment]
I think that this is a bug or lack of generality from oversight.

`{ 77.poll } // should post 77`

this is something we should add. Numbers should behave like UGens in such cases.

**Comment by telephon** [comment]
... but it is also a symptom of another issue, which @jamshark70 mentioned:

>Definitely a bug. "anyUGen.muladd(0, something)" should optimize to DC.rate(something).

We need to discuss that, too.
