### ISSUE TITLE
ScopeView broken in SuperCollider 3.7.0-beta1?

### ISSUE THREAD

**Issue by gogobd** [supercollider/supercollider#1862]
Hello!

I was playing around with an example from a book (it is called "Mapping and Visualization with SuperCollider", published 2013 by Packt Publishing Ltd.). The example shows how to put two different scopeViews into a Window. I have pasted the source code here: http://pastebin.com/Zg19hQsg

The weird thing is that it *does* work with my older "SuperCollider 3.6.6" (downloaded), but unfortunately it does not display anything in the ScopeViews when I start the same code in "SuperCollider 3.7.0-beta1 Built from branch 'HEAD' [9899190]" that I also downloaded. I'm on OSX and I have tried on raspbian, too.

Can somebody see an obvious problem with that code on SC 3.7.0-beta1? I hope that is easy to fix!

**Comment by telephon** [comment]
yes it is easy.


just remove this line: `Server.default = Server.internal;  // make internal the default server`

**Comment by gogobd** [comment]
Unfortunately that did not fix it. I've also tried setting server tinlocal, but I don't get anything displayed.

**Comment by telephon** [comment]
ok, I didn't test it on 3.7, only on master. Maybe someone else can reproduce it here?

**Comment by miczac** [comment]
On 13.Feb 2016, at 14:23 , Julian Rohrhuber <notifications@github.com> wrote:

> ok, I didn't test it on 3.7, only on master. Maybe someone else can reproduce it here?

I did and got blank coloured windows with no signal shown.
FWIW, the only way to display something properly (*) is via the ide-menu �show scope�.
Anything like .scope won�t work (here).

(*) given this �fill area� view is switched off

**Comment by gogobd** [comment]
I wanted to use custom scopes, the one from the ide menu wirks okay; seems like something has changed and now it doesn't work any more

**Comment by gusano** [comment]
@gogobd you missed a couple of things:

- assign a server to ScopeView(s)
- start the ScopeView(s)
- use ScopeOut2 (and not ScopeOut)

here's your example with the mentioned changes, working on linux (sc-3.7.0-beta1)
https://gist.github.com/gusano/e961e0ce67b09fea80e9

**Comment by gogobd** [comment]
@gusano Thank you very much for your help! That's the problem with books, they become obsolete while new major releases are on the way. Thank you thank you thank you, scopes work perfectly!
