### ISSUE TITLE
Windows dependencies: can we provide a public/official download of library binaries?

### ISSUE THREAD

**Issue by bagong** [supercollider/supercollider#1866]
The ease of use of the Windows build system I am trying to put together to some extent depends on how easily people can assemble the smaller dependencies (libsndfile, fftw, readline and portaudio) and organize them in the expected folder tree.
Rather than making individual downloads of libsndfile and fftw, researching ways to get readline for Windows, and building portaudio, it would be a *lot* faster if people could download a prearranged set of files that they only need to extract into a folder. I used to offer such a zip privately to people who wanted to build. I have now a clear idea of which files to use and how to arrange them in a folder tree, so I'd be ready to upload such a zip.

If people use a defined set of binaries it will also be easier to determine whether it's a problem with the dependency or with SC.

Can we do that, and does Github allow for it? All libraries are free as in libre...

What do you think?

**Comment by bagong** [comment]
I see this option as part of "Releases":

> You can also attach binary assets (such as compiled executables, minified scripts, documentation) to a release. Once published, the release details and assets are available to anyone that can view the repository.

https://github.com/blog/1547-release-your-software

Something independent would be nicer. And anyways, is SC going to be released on Github, or will it stay on Sourceforge?

**Comment by timblechmann** [comment]
portaudio might be free, but dependencies like asiosdk aren't

**Comment by bagong** [comment]
You are right with ASIO sdk, and the directx SDK is a similar case if one were to make it part of a download (which I have been doing privately). Question here is, if we couldn't just ignore it until somebody comes and complains, which is extremely unlikely as it's hard to think of anybody who could be put at an disadvantage by the move... I've had informal talks with two or three people on that question, and they tend to that opinion...
As to asio-sdk: from my understanding that means we'd have to take down sc3.6Win as well, as it is compiled into it.

**Comment by bagong** [comment]
Just to make clear: I am not asking to provide the ASIOSDK or DirectX SDK for public download on github. Nor is any of those two part of the submodule portaudio I suggest for SC. In order to use them anybody would still have to download the SDKs herself.

But: the portaudio *library* I suggest to offer for download was compiled using those two SDKs, as was the portaudio library contained in scwin3.6 (that one doesn't use dx, but from a legal point of view the ASIO SDK is more problematic, I think)

**Comment by bagong** [comment]
Another consideration: should there ever be something comparable to travis-ci for Windows, we would need publicly accessible libraries anyways.

**Comment by bagong** [comment]
Since portaudio is part of the SC build now, I think it's less urgent.
