### ISSUE TITLE
FloatArray prevents rounding

### ISSUE THREAD

**Issue by carlocapocasa** [supercollider/supercollider#1873]
0.02 Is a floating point number. However, if it is inside a FloatArray, that number will never be reached precisely, which can cause rounding errors.

a=FloatArray[0.1];

expected:
=> FloatArray[ 0.1 ]

actual:
=> FloatArray[ 0.10000000149012 ]

a[0] = a[0].round(0.01);

expected:
=> FloatArray[ 0.1 ]

actual:
=> FloatArray[ 0.10000000149012 ]

This works:

a[0].round(0.01);
=> 0.1

a[0].round(0.01).class;
=> Float

**Comment by redFrik** [comment]
nothing strange.  it has been discussed many times on the sc-users mailing list for example in the 'Strange modulo behavior' thread.
or use `a=DoubleArray[0.1];`

**Comment by telephon** [comment]
Why not use an `Array` directly?

**Comment by carlocapocasa** [comment]
To avoid making a copy of a FloatArray from a SoundFile.

**Comment by carlocapocasa** [comment]
@jamshark70 's explanation in #1874 clears it up.
