### ISSUE TITLE
copyRange vs. bracket ranges

### ISSUE THREAD

**Issue by snappizz** [supercollider/supercollider#1876]
The docs for SequenceableCollection state that "`x.copyRange(a,b)` can also be written `x[a..b]`", but I just found a discrepancy between them:

    (
    var a = [1, 2, 3, 4];
    a.copyRange(2, 1).postln; // returns [ ]
    a[2..1].postln; // returns [ 3, 2 ]
    )

Either the docs should change or the behavior should change. I think the behavior should change, because I recently got bitten by the fact that `a[0..-1]` doesn't return an empty array in `b = a.size.collect { |i| a[0..i-1].sum }` (an attempt to compute the cumulative sum of `a`). copyRange behaves closer to the slice operator from other languages like Python.

I understand why this happens -- `a[2..1]` becomes `a[[2,1]]` becomes `[a[2],a[1]]`. But it's very confusing and prone to bugs the way it is now.

**Comment by jamshark70** [comment]
The documentation is wrong. `x[a..b]` compiles to copySeries, not copyRange.

```
{ x[0..1] }.def.dumpByteCodes;
->
BYTECODES: (9)
  0   01 19    PushInstVarX 'x'
  2   63       PushSpecialValue 0
  3   6E       PushSpecialValue nil
  4   64       PushSpecialValue 1
  5   B0       TailCallReturnFromFunction
  6   A4 00    SendMsg 'copySeries'
  8   F2       BlockReturn
```
