### ISSUE TITLE
Errors when closing scope window

### ISSUE THREAD

**Issue by patrickdupuis** [supercollider/supercollider#1878]
I'm on linux running 3.7.0-beta1 [3ed7345].
When I close the scope window, I get this error:

```
ERROR: Non Boolean in test.
RECEIVER:
   nil
CALL STACK:
	MethodError:reportError   0x1826d88
		arg this = <instance of MustBeBooleanError>
	Nil:handleError   0x361a3e8
		arg this = nil
		arg error = <instance of MustBeBooleanError>
	Thread:handleError   0x345c7b8
		arg this = <instance of Thread>
		arg error = <instance of MustBeBooleanError>
	Object:throw   0x168c208
		arg this = <instance of MustBeBooleanError>
	Object:mustBeBoolean   0x164a078
		arg this = nil
	View:close   0x36d3028
		arg this = <instance of TopView>
	Window:close   0x3662e08
		arg this = <instance of Window>
	Function:defer   0x36c9ab8
		arg this = <instance of Function>
		arg delta = nil
	Stethoscope:quit   0x31a3ce8
		arg this = <instance of Stethoscope>
		var win = <instance of Window>
	< FunctionDef in Method Collection:collectInPlace >   0x36a33e8
		arg item = <instance of Function>
		arg i = 0
	ArrayedCollection:do   0x36ca878
		arg this = [*2]
		arg function = <instance of Function>
		var i = 0
	Collection:collectInPlace   0x36cb168
		arg this = [*2]
		arg function = <instance of Function>
	FunctionList:value   0x36c9958
		arg this = <instance of FunctionList>
		arg args = [*1]
		var res = nil
	QObject:doFunction   0x36a6568
		arg this = <instance of TopView>
		arg f = <instance of FunctionList>
		arg args = [*0]
^^ The preceding error dump is for ERROR: Non Boolean in test.
RECEIVER: nil 

When I try and open the scope again, I get this error:

ERROR: Message 'front' not understood.
RECEIVER:
   nil
ARGS:
CALL STACK:
	DoesNotUnderstandError:reportError   0x348e998
		arg this = <instance of DoesNotUnderstandError>
	Nil:handleError   0x3617058
		arg this = nil
		arg error = <instance of DoesNotUnderstandError>
	Thread:handleError   0x16097e8
		arg this = <instance of Thread>
		arg error = <instance of DoesNotUnderstandError>
	Object:throw   0x361ad88
		arg this = <instance of DoesNotUnderstandError>
	Object:doesNotUnderstand   0x361e5e8
		arg this = nil
		arg selector = 'front'
		arg args = [*0]
	Server:scope   0x42288d8
		arg this = <instance of Server>
		arg numChannels = 2
		arg index = 0
		arg bufsize = 4096
		arg zoom = 1
		arg rate = 'audio'
	Process:interpretCmdLine   0x3266138
		arg this = <instance of Main>
^^ The preceding error dump is for ERROR: Message 'front' not understood.
RECEIVER: nil
```

Is this happening to anyone else?
Cheers,
Patrick

**Comment by patrickdupuis** [comment]
Sorry - my message isn't too clear.
There are two error messages here:
1. when I close the scope window -> Non Boolean in test.
2. when I try and reopen the scope window -> Message 'front' not understood.
I have to reboot the interpreter in order to be able to open the scope window again.

**Comment by snappizz** [comment]
On Linux. Can reproduce both errors. The first error can be triggered by running either `Stethoscope(s)` or `{SinOsc.ar(440)}.scope` and clicking X, and the second error only happens when trying to run `{ ... }.scope` (`Stethoscope(s)` works fine).

**Comment by patrickdupuis** [comment]
Thanks Nathan! Hopefully this will be fixed for 3.7.0.

Date: Tue, 23 Feb 2016 13:17:47 -0800

**Comment by jamshark70** [comment]
The first error is more general than just Stethoscope. It's thrown whenever you try to `close` a window programmatically that has already been closed.

```
w = Window("test", Rect(800, 200, 500, 400)).front;
w.onClose = { { w.onClose = nil; w.close }.defer };
```

Close this window with X, and you'll get the same error dump.

The error occurs in QView.sc, line 329:

```
if( this.getProperty( \fullScreen ) ) { this.invokeMethod( \showNormal, synchronous:false ) };
```

If the window is already closed, `getProperty` returns nil. So, one possible fix is `if( this.getProperty( \fullScreen ) ? false)`.

BUT... this line has been removed in master. So, unless there's a good reason to keep the line, I'd say, update 3.7 to match master.

Fixing this one problem resolves both errors.

To be really picky, Stethoscope should check whether the window still exists before trying to close it -- Stethoscope.sc line 251:

```
if(window.notNil) { win = window; window = nil; { win.close }.defer; };
```

--> `window.notNil and: { w.isClosed.not }`

**Comment by patrickdupuis** [comment]
Should this issue be added to the 3.7.0 milestone?

**Comment by telephon** [comment]
yes, thanks.

**Comment by patrickdupuis** [comment]
Now that we have a 3.7.1 milestone, perhaps we could move this issue there? :)

**Comment by crucialfelix** [comment]
so somebody needs to locate the commit that is in master and cherry pick it into a PR for 3.7 branch

**Comment by patrickdupuis** [comment]
@jamshark70 is incorrect;  QView.sc line 329 is the same in 3.7 and in master. 
Changing the line to `if( this.getProperty( \fullScreen ) ? false)` fixed it for me.

I'm going to try and create a pull request.

**Comment by jamshark70** [comment]
I might have been looking at my local repository when checking master, and it might have been behind github. Anyway, the fix is valid.

Oh, and... "unless there's a good reason to keep the line"... "QView.sc: removes residue OS X Space after closing a fullscreen window" is a good reason.

**Comment by telephon** [comment]
see #1903
