### ISSUE TITLE
OSCFunc / OSCdef bug

### ISSUE THREAD

**Issue by antonhornquist** [supercollider/supercollider#1884]
Whilst trying to learn about OSCFuncs I execute code in section Examples of the OSCFunc help file and find the behavior of the two example OSCFunc's and the example OSCdef incoherent. Possibly this is a bug.

I'm runnin SuperCollider 3.6.6 on Windows.

The code executed is:
```
n = NetAddr("127.0.0.1", NetAddr.langPort); // local machine

OSCFunc.newMatching({|msg, time, addr, recvPort| \matching.postln}, '/chat', n); // path matching
OSCFunc({|msg, time, addr, recvPort| \oneShot.postln}, '/chat', n).oneShot; // once only
OSCdef(\test, {|msg, time, addr, recvPort| \unmatching.postln}, '/chat', n); // def style

m = NetAddr("127.0.0.1", NetAddr.langPort); // loopback

m.sendMsg("/chat", "Hello App 1");
m.sendMsg("/chat", "Hello App 1"); // oneshot gone
```

The first m.sendMsg invocation causes this output in the Post window:

```
a NetAddr(127.0.0.1, 57120)
matching
oneShot
```

The second m.sendMsg invocation causes this output:

```
a NetAddr(127.0.0.1, 57120)
matching
unmatching
```

I expected the first output to be this:
```
a NetAddr(127.0.0.1, 57120)
matching
oneShot
unmatching
```

It appears like the OSCFunc oneShot is preventing the OSCdef to apply and produce its output. Isn't this a bug? If this is by design, why does the OSCFunc oneShot short circuit the OSCdef output? 

Screenshot of the session
![sc](https://cloud.githubusercontent.com/assets/32165/13507749/5e73299e-e184-11e5-9cb6-9755f5c9c9d0.PNG)

**Comment by jamshark70** [comment]
That's an important bug, so I had a look. It doesn't occur in the forthcoming 3.7 release.

Unfortunately there have been some problems getting the Windows build of 3.7 ready. I'm not sure of the current status.

You might be able to steal some files from the 3.7 class library (which you can grab from github) and drop them into 3.6 -- probably SCClassLibrary/Core/AbstractFunction.sc and SCClassLibrary/Control/ResponseDefs.sc. I can't test this on SC 3.6 at the moment, but those are the relevant files that changed in 3.7.

**Comment by antonhornquist** [comment]
Thanks for your swift reply. I got hold of 3.7-alpha1 for Windows just now and tried it out. True, the bug does not occur anymore.

A merge of
Core\AbstractFunction.sc
Core\Nil.sc

and partial merge of
Collections\Collection.sc

....from 3.7-alpha1 SCClassLibrary to 3.6.6 did the trick.

I'm looking forward to the 3.7 release.

I close this issue.
