### ISSUE TITLE
SC App not posting anything on korean and japanese OS X

### ISSUE THREAD

**Issue by jleben** [supercollider/supercollider#189]
[Issue migrated from SourceForge | ID: 3335090 | Submitted by 'nobody']
[http://sourceforge.net/support/tracker.php?aid=3335090]

This bug seems to happen in some OS X computers with the OS language on korean or japanese (maybe other asian languages affected)
SuperCollider.app posts the library compile messages on startup, afterwards nothing else.
The executed code works, GUI works, scsynth works, but nothing is being posted.
The problem is fixed when changing the whole OS language to a european language (tested with english and german) but this shouldn't be the "fix".

**Comment by scztt** [comment]
Retest?

**Comment by vivid-synth** [comment]
Can any macOS users retest this?

**Comment by brianlheim** [comment]
Not sure how to test this. I changed my primary OS lang to Japanese, restarted, rebuilt SC, and it's still in English.

**Comment by vivid-synth** [comment]
I don't think we have any multi-language support at the moment (do we?). This bug appears to be nothing being posted at all. If you see messages being posted I think we should close.

**Comment by brianlheim** [comment]
Ah okay. Messages were definitely being posted with lang set to Japanese. I can test again with Korean if you want but I think it's safe to close.

**Comment by vivid-synth** [comment]
Nice work, us!
