### ISSUE TITLE
improve supercollider-specific git workflow documentation

### ISSUE THREAD

**Issue by telephon** [supercollider/supercollider#1913]
It would help old and new user-developers if there were just one really simple workflow for contributing to the collective repository.

There have been some detailed discussions on that, so in order not to lose what has been said, I try to link them here (feel free to add links right here).
- #1781
- #1796
- #1911 
- #1918

We could use this issue here to find the simplest workflow description.

**Comment by telephon** [comment]
[OT] the year #1913 was an interesting one. https://www.overdrive.com/media/168227/1913

**Comment by miczac** [comment]
http://longair.net/blog/2009/04/16/git-fetch-and-merge/

**Comment by brianlheim** [comment]
This has been resolved; we are now using git-flow.

Documented in https://github.com/supercollider/supercollider/wiki/git-workflow-and-guidelines, and will be added to the forthcoming DEVELOPING.md
