### ISSUE TITLE
/notify clientID can be 'too many users' instead of an int

### ISSUE THREAD

**Issue by telephon** [supercollider/supercollider#1914]
With duplicate servers, server startup fails with:
`WARNING: Server localhost couldn't set client id to: 'too many users'`

which is kind of OK, but points to a problem, `['/done', '/notify', clientID]` seem to put in `'too many users'` as third argument.

**Comment by crucialfelix** [comment]
scala and other typed languages will not like that.
nor will supercolliderjs

On Sun, Mar 20, 2016 at 2:53 PM Julian Rohrhuber <notifications@github.com>
wrote:

> With duplicate servers, server startup fails with:
> WARNING: Server localhost couldn't set client id to: 'too many users'
>
> which is kind of OK, but points to a problem, ['/done', '/notify',
> clientID] seems to put 'too many users' as third argument.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/supercollider/supercollider/issues/1914>
>
-- 
https://twitter.com/crucialfelix
https://medium.com/@crucialfelix
http://www.mattermind.com/

**Comment by telephon** [comment]
also the rather untyped types kind of don't like that type of thing.

**Comment by crucialfelix** [comment]
typisch

**Comment by vivid-synth** [comment]
This should be fine in Vivid (and I would guess Scala) but maybe it's the wrong message anyway?

**Comment by telephon** [comment]
For some reason I suddenly can't reproduce it, will check back if I see it again.

**Comment by telephon** [comment]
I have the (unwarranted) suspicion that the error is not in the server (not sending the wrong message) but in sclang, `Main::recvOSCmessage` somehow dropping the `/fail` osc command.

**Comment by crucialfelix** [comment]
The lang bug is 2328 
That is an obvious bug that needs fixing for 3.8

**Comment by telephon** [comment]
… but indeed the incoming message is `[ '/fail', '/notify', 'too many users
', 0 ]`. Would actually be good to check with a different OSC application.

**Comment by jamshark70** [comment]
I think Felix is right. One should not respond to a failure message by changing objects' state, as if the command had succeeded.

Not to mention that the failure OSCFunc sets the clientID to `msg[2]`, which is the error string, instead of `msg[3]` (the number). So at best, it's a typo, but I'm not sure why clientID is being set at all if the server is saying it couldn't provide one.

**Comment by telephon** [comment]
… yes, I see now. It happens when sclang tries to get notified by the server, but because sclang had crashed, the server still has the old sclang notification registered so sends a failed message (ok, a wrong one, too).

Two issues here:
1. the message itself is wrong (this is probably in scserver)
2. what to do when sclang encounters a running server that matches the address it tries to start one from?

Maybe solving (2) properly we have the chance of a graceful recovery even, that is, correctly configured ID-allocators. But as a first step, the best might be to send a free all whatever resources to that server (even reboot it?). Alternatively tell the user to please reboot it.

**Comment by crucialfelix** [comment]
The fix for #2328 is really simple. just don't set the client id in the failure handler: https://github.com/supercollider/supercollider/blob/master/SCClassLibrary/Common/Control/ServerStatus.sc#L58
