### ISSUE TITLE
Custom styling for scide help viewer

### ISSUE THREAD

**Issue by snappizz** [supercollider/supercollider#1919]
As a follow-up to #1917, custom CSS in the scide help viewer would be very nice. It's especially important for dark editor themes, which can clash horribly with the black-on-white help viewer.

I'm envisioning an option in sc_ide_conf.yaml that allows the user to specify the path to a custom CSS file that will be inserted after the default CSS. (And some custom JavaScript while we're at it.)

**Comment by bagong** [comment]
Currently scdoc offers an option for custom css by adding a file "custom.css" to the userAppSupportDir/Help folder. It used not to work well though, probably because of that internal css. Yea, ideally the css would switch with the theme switch (the document docklet also doesn't know the theme, but that's a different issue, and not many people use it).

The help-browser can also be used without the IDE. That should probably be kept in mind if working in this field.

**Comment by snappizz** [comment]
Wasn't aware of custom.css, good to know. So the problem at hand is really about how to make help customization more accessible to users. The user should be able to pick from several preset styles that affect both viewer and editor.

**Comment by bagong** [comment]
That would be great!

**Comment by bagong** [comment]
Or javascript in scdoc would try to translate the IDE settings. But that is likely pretty tricky ;)

**Comment by rygen** [comment]
@snappizz My pull request is probably a little incomplete, but those changes allowed me to almost fully style the scide help viewer to match a dark theme :)

Getting the help viewer to automatically match the colors set in the IDE (as of 3.7) or in sc_ide_conf.yaml would be perfect though, no dirty hacks needed :)

**Comment by bagong** [comment]
@rygen  I think they are two things that can be nicely separated. And changing the help-browser styles with custom.css is not a dirty hack, it has been anticipated ;). Maybe it's not documented, but once you start thinking about the css of the doc browser, you'll look at the help docs source and see custom.css is there, waiting to be used. And the development environments you get with the big modern browsers almost make it fun to adjust it to your liking...

**Comment by rygen** [comment]
@bagong But at the moment custom.css is still being inserted before the internal css, isn't it?
By "dirty hacks" I was referring to ones like my approach (#1917) :)

**Comment by bagong** [comment]
If I remember correctly, internal css is always prioritized over external one, and should be used as sparingly as possible. I haven't looked at your pull request yet, but it sounds like the right thing to do. Back then when I played with the help-browsers css I noticed it didn't work as you'd expect when using custom.css, but I didn't take the time to try and analyze it. Now I'd say internal css is likely the reason for the problems you get when using custom.css. So moving that to the main css sounds rather like *removing a hack* than creating one, provided everything works as expected now. I hope you're not disappointed ;) I am saying all this with the reservation that I haven't looked at your changes yet, sorry...

**Comment by snappizz** [comment]
@bagong [custom.css is documented](http://doc.sccode.org/Classes/SCDocHTMLRenderer.html#CSS%20styling). But it's so well-hidden, it might as well be an ancient secret of our ancestors lost to the sands of time.

**Comment by bagong** [comment]
Hahaha, yes. Or the person who did it was a fan of rtfs ("read the f*ng source") ;)

**Comment by snappizz** [comment]
Is there a way to access the scide configuration file from sclang?

**Comment by bagong** [comment]
http://doc.sccode.org/Classes/LanguageConfig.html

**Comment by bagong** [comment]
Ah, sorry, I retract... Not sure actually ;)

**Comment by snappizz** [comment]
I got it, it's `(Platform.userConfigDir +/+ "sc_ide_conf.yaml").parseYAMLFile"` (with graceful fallbacks for non-scide users, of course).

**Comment by vivid-synth** [comment]
(can we add the "QT IDE" label to this?)

**Comment by snappizz** [comment]
a resolution to this is on the horizon with recent IDE redesigns, but i'm no longer a fan of leaving issues open for vague design goals.

**Comment by capital-G** [comment]
@nhthn I am really annoyed by mixing a general dark UI with light doc files.
From my UX taste the help files should be switch according to the selected QtGUI theme or at least provide an easy way to also switch the UI of the docs.

One way to archive this could be by creating a CSS theme for each Qt theme which could then be copy/pasted to `SCDoc.helpTargetDir` as `theme.css` which would be loaded additionally like a `custom.css`.

Although this is a solution that would work I don't think that its a good solution:

* We assume that QtIDE knows where `SCDoc.helpTargetDir` is located which I am unsure if this is a thing w/o hardcoding something
* Copying config files feels like a code smell to me as we can not guarantee the copying works and we do not overwrite something
* Hitting *Apply* in Settings would not reload the Help files so there would be no intermediate feedback on the user how the theme looks

Any ideas how this could be implemented nicely?
