### ISSUE TITLE
scvim as submodules repo

### ISSUE THREAD

**Issue by blacksound** [supercollider/supercollider#1921]
I am a scvim user. I think scvim maintenance and development would be better if it was a separate repo where scvim users and devs could collaborate better.

I would really like to see more collaboration on scvim.
I suspect that we are not so many people using scvim, so it would be nice to gather those who use it and not let it "drown" in the larger dev flow.

Any opinions on this?

In order to do this I propose these steps:
- Make the repository 'supercollider/scvim', copying the code from 'supercollider/editors/scvim'
- Remove the 'editors/scvim' folder from the supercollider repo, and replace it with a git submodule, linking the new 'supercollider/scvim' repo.

This could also be done for 'scel' and 'sced', but I don't know anything about these editors, so I won't make a case for doing the same thing for them.

Pros:
- Better dev workflow for scvim users/devs. Can make changes without having to affect the main supercollider build. Update submodule in main supercollider repo when things are stable.
- More direct communication to scvim devs for fixing bugs, etc.

+Eirik

**Comment by bagong** [comment]
A practical question, not specific to a potential SCVim submodule: how do changes to a submodule propagate to the main SC repo? Do they automatically update in SC or is a separate commit in the SC repo required?

**Comment by blacksound** [comment]
It doesn't update automatically to the supercollider repo when making changes in the scvim repo.
IMO that is an advantage, isolating and focussing dev effort for scvim.
When everything is working fine you make a commit in the supercollider repo, updating which commit the scvim submodule references.

**Comment by bagong** [comment]
Yes, I can see the nice side of it. And if you wanted to make changes to the submodule from within SC the SC repo, would that also be possible?

**Comment by bagong** [comment]
Please don't get me wrong. I am not opposed to this. I have been thinking about this in the context of other submodules, so I more or less abuse your suggestion to talk about this on more general terms. I think it is pretty difficult to change a submodule on the SC side. Once the SM is established you have to submit a PR to the submodule repo, and then another one to the SC repo, if I am not mistaken.  So on one side a submodule encapsulates an area of SC development and allows to assign separate access rights to it. On the other hand it complicates the workflow and changes control rights. As long as the relations between parent and child repo are constructive, this can be nice, but if that changes, or if the submodule repo is not maintained any more, things have to be changed again. It's not a big change, but worth a thought...

**Comment by blacksound** [comment]
AFAIK you can't make change _from_ the SuperCollider repo.
I don't really know why you would want to do that though? In what case would that would be necessary?

What you can do is to fork the scvim repo and experiment with it. Then new features could be merged to the supercollider/scvim repo later.

+Eirik Blekesaune

**Comment by bagong** [comment]
Oh, a submodule in the SC repo... Yes, then half of what I was considering isn't relevant...

**Comment by blacksound** [comment]
Hi Rainer,
I do get the feeling that the thing you want to discuss is a broader topic, not fitting the scope of this particular issue. Although it is an interstimg topic indeed, I'm merely a git novice so this issue would not be the best forum for discussing git in general.
Please correct me if I'm wrong here, but if you agree I propose that we move that discussion to the sc-dev list, or make another issue. I think that would serve both issues best.
This issue is only about moving scvim into a sumodule for making development better.
+Eirik Blekesaune

**Comment by bagong** [comment]
Sure. Sorry for interfering.

**Comment by crucialfelix** [comment]
vim and emacs both have several very good package management systems.
vundle, pathogen
elpa, marmalade

I don't think publishing is difficult

IMO its much better to install from those and not to include it with
supercollider at all.

if you don't want to take ownership of it then it could be moved to the
supercollider org.

On Thu, Mar 24, 2016 at 2:22 PM Rainer Schütz <notifications@github.com>
wrote:

> Sure. Sorry for interfering.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/supercollider/supercollider/issues/1921#issuecomment-200830566>
>
-- 
https://twitter.com/crucialfelix
https://medium.com/@crucialfelix
http://www.mattermind.com/

**Comment by miguel-negrao** [comment]
> And if you wanted to make changes to the submodule from within the SC repo, would that also be possible?

> What you can do is to fork the scvim repo and experiment with it. Then new features could be merged to the supercollider/scvim repo later.

The way submodules are described above lead me to believe that you might not be understanding completely how submodules work. A submodule is just a git repo which is checked out inside the working tree of another git repo. The parent git repo only keeps track of what is the address/location of the (submodule) repo and at which commit it should point to. Therefore it doesn't make much sense to ask if you can make changes from "within" the sc repo. All changes to the submodule are made in the corresponding git repo, the sc repo then chooses to which commit it wants to point at. I hope this clarifies somewhat. Also, when dealing with git repos "control rights" are not very relevant, if for some reason we loose control of the scvim submodule, we just fork it and point to the new fork, issue solved. That's the beauty of the distributed approach.

**Comment by danstowell** [comment]
I don't see a big difference between the current state and the submodule approach, but yeah why not.

@bagong is right that you have to make a change in the submodule, then update the main repo to point to the updated submodule; so maybe that's 2 PRs rather than one, but that's kinda the same as committing in an experimental branch and then PR'ing to master.

If it was a submodule, people could file/discuss issues specifically with that, and also they could subscribe just to that repo etc. Not a massive change, but yeah why not

**Comment by miguel-negrao** [comment]
> @bagong is right that you have to make a change in the submodule, then update the main repo to point to the updated submodule; so maybe that's 2 PRs rather than one, but that's kinda the same as committing in an experimental branch and then PR'ing to master.

If every commit to the submodule is supposed to appear in the parent repo immediately then I don't think there is much point in having a submodule, it would indeed be more work. If on the other hand the parent repo will only updated the commit pointed to every so often, then it makes more sense, imho.

**Comment by bagong** [comment]
@miguel-negrao , I am likely a bit oversensitive, but asking a question doesn't *necessarily* point to a lack of understanding, and even if it were so, why should an explanation be headed by pointing to an assumed lack of understanding first? This is not a very encouraging discussion style, if I may say so.

So, as an example, I had a tiny pull request hanging in hidapi for something like three months, and after I it was committed, I had to make another pull request to try and bring it into 3.7. Too late... Not a big deal at all in this case, but - as I feel - an instructive example of the potential implications of splitting out things into different repos.
Sure you can just link to another fork, but it's not particularly friendly behavior, so you might want to choose to avoid it becoming necessary.

And now I'll be quiet for a while... Have been talking a bit much lately...

**Comment by blacksound** [comment]
Please understand, my only goal here is to fascilitate more communication amogst scvim users and developers.
I'm not sure if the solution for this is making it into a submodule or not.
Crucialfelix' suggestion also seems reasonable to me. It is the same method he is using for the Atom.js SuperCollider plugin if I'm not mistaken(?)
However that would raise the question if SuperCollider should package scvim, and any other editors than sc-ide for that matter. Any opinions on this?

Miguel:
Maybe I misunderstand you but I don't see why we would need to have every commit in the submodule to be  comittef to the main repo. Wouldn't that kind of defeat the purpose of putting it into a submodule? Then you would indeed have to do 2 PRs for every commit.

+Eirik

**Comment by miguel-negrao** [comment]
> @miguel-negrao , I am likely a bit oversensitive, but asking a question doesn't necessarily point to a lack of understanding, and even if it were so, why should an explanation be headed by pointing to an assumed lack of understanding first? This is not a very encouraging discussion style, if I may say so.

@bagong Thank you for pointing that out. That was not my intention, and it is good to know that my post was construed as conflictive. I will try to work on my discussion style, you're right I could have been more constructive.  Asking a question doesn't necessary imply lack of understanding, but sometimes the way the question is asked can demonstrate that there is some confusion regarding the matter. I thought I had identified some confusion, and tried to clarify, with good intentions. Off course, I can see that if one thinks there was no confusion to start with, then a clarification can be perceived as condescending. I tried to use language which expressed only the possibility of confusion: "lead me to believe", so perhaps I was believing so wrongly; "that you might not be", but leaving the possibility that you are understanding correctly. Anyway, sorry about that. :-)

**Comment by miguel-negrao** [comment]
> Miguel: Maybe I misunderstand you but I don't see why we would need to have every commit in the submodule to be comittef to the main repo. Wouldn't that kind of defeat the purpose of putting it into a submodule? Then you would indeed have to do 2 PRs for every commit.

@blacksound That is exactly what I said, so I agree with you. :-)

**Comment by bagong** [comment]
#1930 Maybe worth a review?

**Comment by crucialfelix** [comment]
The main reason to have it as a separate repo is so that it can be loaded easily by things like Vundle and NeoBundle:

```vim
Plugin 'supercollider/vim-supercollider'
```

voila, you now have supercollider support in your vim. Other package managers use similar syntax.

Likewise, for Emacs Devotees we publish a separate repo to melpa:

https://melpa.org/

by adding a recipe to:
https://github.com/melpa/melpa

in the form of:

```emacs
(supercollider-mode :fetcher github :repo "supercollider/emacs-supercollider-mode" :files ("supercollider-mode.el"))
```

or something like that. Then all the different Emacs package managers can all access it from melpa.

I don't see why these files should continue to be distributed with SuperCollider. Doesn't everybody use a package manager on vim and emacs ?  

I'm not fussed about keeping them in though. But it's not needed IMO. It reduces maintenance, allows people to contribute more easily to those packages and get instant distribution—no need to wait for a new SuperCollider release.

**Comment by crucialfelix** [comment]
> What you can do is to fork the scvim repo and experiment with it. Then new features could be merged to the supercollider/scvim repo later.

^^ this. 

```vim
Plugin 'blacksound/vim-supercollider'
```

and you are free to hack away.

**Comment by danstowell** [comment]
It seems this is a fine idea, I don't think anyone objects much to this. Question: is there anyone who would like to supervise the scvim repo after we create it? I guess we can just create it and see what happens, but really there needs to be a nonzero number of people looking after PRs etc!

**Comment by grirgz** [comment]
I use Vim and I am interested in contributing to improve the SCvim module, so count me in =)
