### ISSUE TITLE
Qt window autosize does not always work

### ISSUE THREAD

**Issue by jleben** [supercollider/supercollider#195]
[Issue migrated from SourceForge | ID: 3388466 | Submitted by 'lijon']
[http://sourceforge.net/support/tracker.php?aid=3388466]

QWindow is supposed to autosize to the containing layout when given an empty Rect() as bounds. This mostly works, but sometimes not:

// does not work
w = Window("Test",Rect()).layout_(
   QVLayout( QStaticText().string_("Hello layout") )
).front;

// neither does this
w = Window("Test",Rect()).layout_(
   QVLayout( QStaticText().string_("Hello layout"), QButton() )
).front;

// but this works!
w = Window("Test",Rect()).layout_(
   QVLayout( QStaticText().string_("Hello layout"), QHLayout( QButton(), QButton() )
)

**Comment by scztt** [comment]
This is sort of a known-issue for Qt layouts - once you've set the string in a StaticText, you have to use sizeHint to properly measure it and resize. This requires a lot of manual intervention when using a SC chained-method style of object initialization... Creating something like View:resizeToHint could be a big improvement.

**Comment by patrickdupuis** [comment]
Would adding these two methods to QView.sc be helpful?

```

	resizeToSize { arg size;
		this.bounds_( this.bounds.resizeTo( size.width, size.height ) );
	}

	resizeToHint {
		var size = this.sizeHint;
		this.bounds_( this.bounds.resizeTo( size.width, size.height ) );
	}

```

**Comment by patrickdupuis** [comment]
This works for me.
```
w = Window("Test",Rect()).layout_(
QVLayout( QStaticText().string_("Hello layout") )
).view.resizeToHint.front;
```

**Comment by telephon** [comment]
Re: `resizeToSize`: if `size` is a rect, then it would perhaps be more idiomatic to write:

```

	resizeTo { arg h, v;
		this.bounds_( this.bounds.resizeTo( h, v ) );
	}
	resizeToBounds { arg rect;
		this.bounds_( this.bounds.resizeTo( rect.width, rect.height ) );
	}

	resizeToHint {
		var size = this.sizeHint;
		this.bounds_( this.bounds.resizeTo( size.width, size.height ) );
	}

```

**Comment by patrickdupuis** [comment]
I agree that resizeToBounds is better. I'll create a PR to add these two methods in the coming days.

**Comment by telephon** [comment]
ping

**Comment by patrickdupuis** [comment]
Are we looking to close some old issues? :)

I'll create a PR as soon as I can.

**Comment by brianlheim** [comment]
@patrickdupuis Great, thank you!
