### ISSUE TITLE
sound server - cmd line option for setting synthdefs folder

### ISSUE THREAD

**Issue by miguel-negrao** [supercollider/supercollider#1959]
In standalone sclang mode, it would be better to use a folder next to the sclang binary to store synthdefs, in order for sclang standalones not to interact with each other. Currently when using sclang without an osx bundle it will default to loading synthdefs from the user library folder. '-s' could be used for this.  What do you think ?

**Comment by crucialfelix** [comment]
right now you can do:  `-D 0` which means do not load defs.
then you can issue a d_loadDir as your first command.

but I agree, it should be easy to specify the path as long as it has a loadDir on startup function.

**Comment by timblechmann** [comment]
there is the `SC_SYNTHDEF_PATH` environment variable (both for scsynth and supernova)

**Comment by bagong** [comment]
Isn't the path a function of the appSupportDir? Would it maybe more efficient to make that configurable? There are also downloaded-quarks, Extensions, HistoryLogs, the archive.sctxar, and maybe also Help, to be considered as non IDE-folders.

**Comment by miguel-negrao** [comment]
> there is the SC_SYNTHDEF_PATH environment variable (both for scsynth and supernova)

I have a feeling you already pointed that to me once... :-). I guess for an sclang standalone that should be enough, since you can set that env variable privately just for that launcher script, right ? I guess in that case this feature is not needed.

**Comment by crucialfelix** [comment]
I forgot about SC_SYNTHDEF_PATH too. I even use that myself.

its confusing to have envs and command line flags, but we have other things to work on IMO.

**Comment by telephon** [comment]
related: #1422, #1438

**Comment by miguel-negrao** [comment]
@telephon, how are those issues related to this ?

**Comment by telephon** [comment]
@miguel-negrao sorry, it seems to have sneaked into the wrong issue. I'll remove my comment

**Comment by brianlheim** [comment]
Ping. @miguel-negrao @crucialfelix Do you mind if I close? Sounds like this is either resolved or not very much desired anymore.

**Comment by vivid-synth** [comment]
I think we'd all rather have it as a command-line option but the environment variable works for now
