### ISSUE TITLE
ide: debian/gnome using ugly style 

### ISSUE THREAD

**Issue by miguel-negrao** [supercollider/supercollider#1982]
I'm not sure if this is a problem with the Qt configuration on my system or if it is a bug of scide. By default scide looks quite ugly on my system, which is running debian with gnome. This is because it is not using the gtk+ style as it [should](https://wiki.archlinux.org/index.php/Qt):

> Qt5
> 
> Qt5 decides the style to use based on what desktop environment is used:
> 
>     In KDE Plasma, it uses the actually selected Qt style. It can be configured using KDE System Settings (systemsettings5), the settings can be found in Appearance > Application Style > Widget Style.
>     In Cinnamon, GNOME, MATE, LXDE, Xfce, it uses GTK+ (QGtkStyle).
>     In other desktop environments, it uses Fusion.

The solution seems to be to set the '`QT_STYLE_OVERRIDE`' env var to '`gtk`', then it looks fine. I'm not sure if I have any other apps built with qt5, to see if it is just scide with this issue or any qt5 app.

Anyone else running gnome or debian/gnome ?

**Comment by jamshark70** [comment]
I am running Gnome3 under Ubuntu. I don't recall being shocked by the appearance. But I'm pretty sure I've customized lots of colors, so I might never have seen the default look under Gnome3.

Screenshot?

**Comment by miguel-negrao** [comment]
QT_STYLE_OVERRIDE=""

![captura de ecra de 2016-04-21 11-59-05](https://cloud.githubusercontent.com/assets/382777/14706807/caa7a928-07b8-11e6-9edf-a9144fc870dd.png)

QT_STYLE_OVERRIDE=gtk

![captura de ecra de 2016-04-21 12-00-49](https://cloud.githubusercontent.com/assets/382777/14706819/d62ebcaa-07b8-11e6-824b-6f6fff987756.png)

**Comment by gusano** [comment]
> I'm not sure if this is a problem with the Qt configuration on my system or if it is a bug of scide

IMHO this is a problem with your distro/Qt config but it would be nice to have someone using `gnome` who could confirm that

**Comment by patrickdupuis** [comment]
Here is my scide's look in Gnome 3.18.2 Fedora 23.  
![scide gnome 3 18 2](https://cloud.githubusercontent.com/assets/11747870/14764689/31d04858-098f-11e6-9b3d-7c7d325de307.png)

**Comment by gusano** [comment]
Closing as it looks like a QT config issue

**Comment by miguel-negrao** [comment]
> Closing as it looks like a QT config issue

I can confirm this happens with any Qt5 app, so not SC related. So it is either an issue just in my system or a debian wide system.

**Comment by miguel-negrao** [comment]
The problem can be replicated with a clean install of debian. Reported [upstream](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=822697).
