### ISSUE TITLE
Plugin API docs

### ISSUE THREAD

**Issue by snappizz** [supercollider/supercollider#1995]
Is there any documentation on the scsynth plugin API? I couldn't find any when I started developing ugens.

**Comment by danstowell** [comment]
See the "Writing Unit Generators" helpfile: http://doc.sccode.org/Guides/WritingUGens.html

**Comment by snappizz** [comment]
It seems to be far from comprehensive. There are a ton of undocumented features like ZIN/ZOUT, Buffers, random number generators, etc. If I have time I will try to write up more complete help files for ugen development.

**Comment by bagong** [comment]
Brilliant!

**Comment by danstowell** [comment]
For more info see Chapter 25 of The SuperCollider Book, freely downloadable, might help:
http://www.supercolliderbook.net/danstowellch25.pdf

**Comment by snappizz** [comment]
@danstowell I really appreciate that your chapter was made freely available, but I find it a bit funky that a lot of information that's necessary for writing ugens is not part of the SC documentation proper. Some of the compilation info in that document is out of date, which confused me early on. As helpful as that chapter is, developing ugens still feels like a dark art.

Anyways, I'll quit complaining and start improving the docs.
