### ISSUE TITLE
New scvim submodule: after submodule init/update problem when switching branches

### ISSUE THREAD

**Issue by bagong** [supercollider/supercollider#2001]
Hearing of the new scvim submodule in master I did:

    git submodule init
    git submodule update

The submodule got populated, things look fine, `git status` returns everything fine.

Then I tried to switch to the 3.7 branch and got this:

````
git checkout 3.7
error: The following untracked working tree files would be overwritten by checkout:
	editors/scvim/.gitignore
	editors/scvim/BUGS
	editors/scvim/CMakeLists.txt
	editors/scvim/COPYING
	editors/scvim/NEWS
	editors/scvim/README.md
	editors/scvim/SCVim.scd
	editors/scvim/TODO
	editors/scvim/bin/sclangpipe_app
	editors/scvim/bin/scvim
	editors/scvim/extra/VimDocument.sc
	editors/scvim/extra/alex-darkblue.vim
	editors/scvim/ftplugin/supercollider.vim
	editors/scvim/indent/supercollider.vim
	editors/scvim/registry/supercollider-vim.yaml.in
	editors/scvim/scclasses/SCVim.sc
	editors/scvim/scvimrc
	editors/scvim/syntax/supercollider.vim
	editors/scvim/syntax/supercollider_lang.vim
	editors/scvim/syntax/supercollider_objects.vim
	editors/scvim/syntax/supercollider_operators.vim
Please move or remove them before you can switch branches.
Aborting
````

Not sure how to proceed... Also not sure where to report this ;)

**Comment by danstowell** [comment]
I think this is just git being confusing... looks like you may need to manually delete that folder before switching, I'm not aware of any way we could make it more fluid. Annoying!

(We should NOT backport the change into the 3.7 branch imo)

**Comment by bagong** [comment]
I haven't analyzed it yet, but my current guess is that the old files were not "git deleted" but just deleted... Which makes me fear that everybody will get that problem once they realize they need to `submodule init/update` to actually see the change... Deleting the files in the stage I am in will break the git repo scvim is now. Other submodules didn't have that problem, because they were just newly added. This one replaces the old files (which happen to be identical but not the same ;) )

**Comment by danstowell** [comment]
@bagong your guess is incorrect. I used "git rm"

**Comment by bagong** [comment]
Hmmm, okay, and you commited that, right. But the problem remains. I can't solve it by deleting the files. Can you suggest a solution?

**Comment by bagong** [comment]
Okay, I was hoping checking out a new repo would help, but same problem, once I do "git checkout -b 3.7 origin/3.7" the above mentioned error occurs. This *is really* annoying, we need a solution, otherwise this repo is restricted to master only ;). Maybe @gusano nows a solution? Otherwise I would suggest to revert the commit for now. We cannot expect everybody to be alert enough to delete the scvim folder before switching running submodule init/update. And once it happened, you're stuck.

**Comment by danstowell** [comment]
maybe if the "git rm" and the submodule addition were separated into subsequent commits rather than a single commit?

**Comment by bagong** [comment]
I don't know. But I can confirm that reverting the commit, while it produces an error, does recreate a working repo.

**Comment by timblechmann** [comment]
not a bug, standard git behaviour. don't switch branches with initialised submodules unless you know what you are doing.

**Comment by bagong** [comment]
Can you elaborate?

**Comment by bagong** [comment]
So for the mortals that try to help rather than spread dismissive and disencouraging language, the workaround is:

    git submodule deinit editors/scvim

**Comment by crucialfelix** [comment]
deinit ? that's a new one for me.

**Comment by danstowell** [comment]
A practical compromise that we *could* make: we could also use the submodule in the 3.7 branch. It's unconventional to backport such a change, but actually it's not a change to the source code so much as to the way we store it. We can point directly at the same source code version as was in 3.7, so no file changes. The adverse impact will be... what? Nothing afaict. @crucialfelix @bagong thoughts?

**Comment by bagong** [comment]
I think it's worth it, my feeling is 3.7 will be around longer than we want to believe! If you make a pull request, I will test it for it's practical consequences this time ;)

**Comment by crucialfelix** [comment]
sounds good to me. it is not an API change so it's fine
