### ISSUE TITLE
Compiling master on Windows with Visual Studio x64

### ISSUE THREAD

**Issue by llloret** [supercollider/supercollider#2007]
Hi, after doing some cleanup on the SuperCollider documentation to warm up ;), I wanted to give a try at compiling the Windows version and see if I can start doing some work on it. I am doing the work on Windows 7 64 bits, with Visual Studio 2013.

I am trying the Windows 64 flow, following the instruction in the README_WINDOWS.md. I generated the project with: cmake -G "Visual Studio 12 2013 Win64" ..\supercollider.

I think I have it mostly setup, but when I try to compile, I am getting some errors. I am focusing now on some problems on the libsclang project. I am getting this:
`D:\sc\supercollider\lang\LangPrimSource\OSCData.cpp(900): error C2065: 'PIP_ADAPTER_UNICAST_ADDRESS' : undeclared identifier`.
Now, if I follow that declaration, I get to sdkddkver.h, with the following:
`#if (NTDDI_VERSION >= NTDDI_VISTA)
typedef  IP_ADAPTER_UNICAST_ADDRESS_LH IP_ADAPTER_UNICAST_ADDRESS;
typedef  IP_ADAPTER_UNICAST_ADDRESS_LH *PIP_ADAPTER_UNICAST_ADDRESS;
#elif (NTDDI_VERSION >= NTDDI_WINXP)
typedef  IP_ADAPTER_UNICAST_ADDRESS_XP IP_ADAPTER_UNICAST_ADDRESS;
typedef  IP_ADAPTER_UNICAST_ADDRESS_XP *PIP_ADAPTER_UNICAST_ADDRESS;
#endif
`

The thing is that NTDDI_VERSION is being set to this:
`#define NTDDI_VERSION   NTDDI_VERSION_FROM_WIN32_WINNT(_WIN32_WINNT)`
and _WIN32_WINNT is being set to 0x0500, in the CMakeLists. Setting it to this value implies Windows 2000, which predates WINXP, so that the NTDDI_VERSION above is neither >= NTDDI_VISTA or >= NTDDI_WINXP, and that means that PIP_ADAPTER_UNICAST_ADDRESS is not defined.

So, is there any reason to indicate _WIN32_WINNT to Windows 2000? Would it be ok to raise this to indicate Windows XP or Windows 7?

Has someone experienced the same problem when compiling under Windows for 64 bits? Am I missing something here?

Any ideas? I have been looking at another thread about Windows, between @bagong and @sonoro1234, but that relates to mingw, and it didn't seems the same.

PS: I am seeing other errors regarding the number of arguments of some boost:: calls, but let's focus on the other issue first...

**Comment by llloret** [comment]
If in CMakeLists.txt I bump `-D_WIN32_WINNT=0x0500 to 0x0501`, which means Windows XP, then the first error I am talking about goes away, but I am not sure if that would be ok. Also not sure if other people have success compiling with that set to 0x0500.

**Comment by timblechmann** [comment]
do windows versions before xp support 64bit?

**Comment by llloret** [comment]
I don't think so, but keep in mind that this compilation problem would also be present if compiling 32 bits with Visual Studio (I don't know if that is on the roadmap or not).

Has anybody compiled the Windows 64 bits version with Visual Studio? I am guessing yes, but I do not see how, with the current CMakeLists.txt.

**Comment by bagong** [comment]
Hi Luis,

let me first say I am excited to see somebody interested in the Windows build and will be happy to assist you in any way possible. But I need a few hours today before I can dedicate more time.

The VS 64-bit build only succeeds on the 3.7 branch, that’s a known issue, the boost update broke it on master. Lucas Cornelisse did most of the work to get work for 3.7...

As to Windows versions, we have kind of “officially” dropped even XP support, so no reason to keep settings for backwards-compatibility. A thing you might want to keep in mind is that the embedded portaudio build might require some settings to succeed, and I am not clear how internal settings there might interfere with the general SC build.

But the general notion is: everything is highly experimental and you can freely make changes that seem reasonable, and they will be welcomed... 32-bit support would be nice, but not a must. If the VS build get’s stable and reliable, one might as well make it the main one for the future. Qt-support for MinGW is not looking promising anyways. A problem is that sc3-plugins and supernova can’t be built with VS yet.

As I said I’ll be happy to help in any way I can

Best
Rainer

**Comment by llloret** [comment]
Ok, that explains the issues I was having with Boost not finding some prototypes for async.

I will move to the 3.7 branch and give it a try.

**Comment by llloret** [comment]
@bagong, the branch is 3.7**win**, right? Or should I use bare 3.7?

**Comment by bagong** [comment]
> On 26 Apr 2016, at 16:31, Luis Lloret <notifications@github.com> wrote:
> 
> @bagong <https://github.com/bagong>, the branch is 3.7win, right? Or should I use bare 3.7?
> 
Ah, forgot to mention it, sorry. Yes, the release build is made from the 3.7win branch, so if you want to reproduce that, use 3.7win. There are a few commits in 3.7 since then, but nothing too important. Actually you should be able to merge 3.7 into 3.7win without problems. 3.7win contains an alternative IPC implementation by Lucas Cornelisse that avoids a serious usability problem (sclang crashing when typing or mouse-dragging in the IDE) in the Windows version.

Best
.r.

PS: if you’d want to try to fix the build in the master branch, that would be very welcome. Might not be a big deal for you ;)

**Comment by llloret** [comment]
Ok, I have been able to compile and run the IDE, lang and server, on the 3.7win branch. I had to delete Mark Polishook tutorial (the Japanese version), to stop sclang from crashing while parsing the docs.

Not sure we can make it work in the master branch for now, because it seems that VS is missing some C++11 features required for the boost::async support.

**Comment by bagong** [comment]
> On 26 Apr 2016, at 17:25, Luis Lloret <notifications@github.com> wrote:
> 
> Ok, I have been able to compile and run the IDE, lang and server, on the 3.7win branch. I had to delete Mark Polishook tutorial (the Japanese version), to stop sclang from crashing while parsing the docs.
> 
Oh, that’s interesting. Weird that I haven’t seen that particular crash before, but anything related to unicode is likely a problem candidate... I’ll inspect it...
> Not sure we can make it work in the master branch for now, because it seems that VS is missing some C++11 features required for the boost::async
> 
Might the features have been added in VS 2015? In theory that could open a path to Qt5.6, which is currently blocked for Windows, because the officially distributed MinGW build of Qt5.6 does neither contain the new Webengine nor old Webkit. The VS 2015 build of Qt5.6 does contain Webengine, and there is a prototype for SC Webengine support available as PR...

Thanks for your feedback!

Best
.r.

**Comment by llloret** [comment]
I will try to compile the master branch using VS2015, and see if we get the same errors. As far as I understand Boost disables what we need when it detects VS, but we may be able to override it (not sure if it will work...).

**Comment by llloret** [comment]
I cannot compile the master branch with VS2015 either. The MSVC compiler seems to lack something necessary for boost:: async to work. From boost->visualc.hpp:
```
// C++11 features not supported by any versions
#define BOOST_NO_SFINAE_EXPR
```

and then Boost does not support Variadic threads:
```
#if ! defined(BOOST_NO_SFINAE_EXPR) && \
    ! defined(BOOST_NO_CXX11_VARIADIC_TEMPLATES) && \
    ! defined(BOOST_NO_CXX11_DECLTYPE) && \
    ! defined(BOOST_NO_CXX11_DECLTYPE_N3276) && \
    ! defined(BOOST_NO_CXX11_TRAILING_RESULT_TYPES) && \
    ! defined(BOOST_NO_CXX11_RVALUE_REFERENCES) && \
    ! defined(BOOST_NO_CXX11_HDR_TUPLE)
#define BOOST_THREAD_PROVIDES_VARIADIC_THREAD
```

I have tried to remove the `#define BOOST_NO_SFINAE_EXPR`, but then it complained about something else.

So, I would say that at the moment VS2015 is a no-no.

**Comment by bagong** [comment]
Okay, thank you very much for looking into that. I cannot comment anything, the questions are way above my competence. But I can see that we are heading into trouble for Windows support, because if SC moves on to Qt5.6 there will be hardly any route open for SCWin for the time being. The only option I see is using MinGW with MSYS2 and sticking to Webkit. MSYS2 have said they will provide binary Webkit in their distribution of Qt5.6 too. But their 32-bit toolchain/packages seem to be quite buggy, it seems only the 64-bit version is supported well. 64-bit SCWin on MinGW doesn't build yet too...

**Comment by llloret** [comment]
Ok, for now, I will try to make the MIDI part to work.

I cannot put too much time into this atm, but I will try.

**Comment by bagong** [comment]
@llloret : Great!! Thank you so much!

**Comment by llloret** [comment]
I think I have something that sort of works using a Virtual MIDI connection (using LoopBe1). Should I issue a Pull Request to the 3.7win branch and you can have a look, and perhaps give it a try?

What I have at the moment can do MIDIOut -> noteOn events, that get captured by a MIDIFunc, I can post the example in the Pull Request comments...

Tonight I might be able to try with some real MIDI HW, but not now.

**Comment by bagong** [comment]
Sure! I won't be able to test before tonight too, but will do then!

**Comment by vivid-synth** [comment]
(can we add the windows label to this?)

**Comment by bagong** [comment]
We're back on master, I think this can be closed. Thanks @llloret , for all your work!

**Comment by llloret** [comment]
My pleasure!

Looking forward to even more interesting work!
