### ISSUE TITLE
sclang doesn't accept input?

### ISSUE THREAD

**Issue by vivid-synth** [supercollider/supercollider#2018]
Apologies in advance if I've done something obviously wrong...

I'm installing on a fairly fresh machine (Debian stable). I've compiled supercollider from source (today's ```master```), with ```-DSC_DOC_RENDER=TRUE -DSUPERNOVA=TRUE -DNATIVE=TRUE -DSC_IDE=FALSE -DSC_QT=FALSE -DSCLANG_SERVER=FALSE -DSC_WII=FALSE -DSC_ED=FALSE -DAUDIOAPI=jack```

I then had to do the "(rather radical) workaround" to another issue described in https://github.com/supercollider/supercollider/issues/1209

```scsynth``` and ```supernova``` then work well, but when I call ```sclang``` I get everything but a prompt to interact with:

> $ sclang
> init_OSC
> empty
> compiling class library...
> initPassOne started
> 	NumPrimitives = 590
> initPassOne done
> 	compiling dir: '/usr/local/share/SuperCollider/SCClassLibrary'
> 	compiling dir: '/usr/local/share/SuperCollider/Extensions'
> 	pass 1 done
> ERROR: Class extension for nonexistent class 'Document'
>      In file:'/deprecated/3.7/deprecated-3.7.sc'
> 	numentries = 1055776 / 12550368 = 0.084
> 	4376 method selectors, 2868 classes
> 	method table size 14858096 bytes, big table size 100402944
> 	Number of Symbols 12034
> 	Byte Code Size 360386
> 	compiled 364 files in 0.52 seconds
> compile done
> Class tree inited in 0.02 seconds
> Cleaning up temp synthdefs...
> 
> 
> *** Welcome to SuperCollider 3.8dev. *** For help type ctrl-c ctrl-h (Emacs) or :SChelp (vim) or ctrl-U (sced/gedit).

...and then it just hangs...

**Comment by bagong** [comment]
Might be enough to press 'enter' or 'return' ;)

**Comment by crucialfelix** [comment]
It's not intended to be a command line repl. 

You need to send a special character to indicate that you are done entering.

https://github.com/crucialfelix/supercolliderjs/blob/develop/src%2Flang%2Fsclang.js#L280

    this.process.stdin.write('\x0c', null, callback);

supercolliderjs provides a wrapper that makes it a slightly better command line repl with a prompt and optional colors for console or browser. command line is not my main concern though; embedding in apps and remote usage is (socket.io etc)

**Comment by bagong** [comment]
Why is it not intended to be a command line repl? I think it's just a buggy implementation. I remember discussions about that a few years ago...

**Comment by timblechmann** [comment]
compile with the readline interface

**Comment by crucialfelix** [comment]
It is intended to be connected with an app that provides a full repl. Like scide, vim, atom supercollider etc.

It's a rtaw socket. 

Read line provides such an interface for command line apps, as Tim says.

**Comment by danstowell** [comment]
@vivid-synth everyone is kinda correct but maybe it's clearer to spell the answer out: yes, when you compile normally, invoking `sclang` (as you showed in your message) gives you a command-line interface (thanks to the magic of readline). Now, either you didn't have the needed readline packages installed, or you did something else weird as part of your hacking, but one must presume that what you're seeing is the bare (readline-less) sclang, which doesn't actually "hang" but it's not obvious to an ordinary person how to use it.

The solution is to rebuild but make sure the build process includes the "readline" libraries described in the README, and check the cmake output (it should tell you if it can't find readline).

(It's vaguely possible that your problem isn't readline (we don't know without seeing the output from your build process) but it totally looks like it is.)

**Comment by bagong** [comment]
I assumed vivid-synth had built with readline support as all build instructions guide you to do. You can run commands "in readline" and won't get a prompt returned after it completed. It could appear as if it hung. I think I've seen sclang start and not give a prompt before you press return.

**Comment by vivid-synth** [comment]
Yes, this was missing 'libreadline' - it was in the "optional dependencies" section -- thanks for the help!
