### ISSUE TITLE
Impact of GPL on use of CMake module

### ISSUE THREAD

**Issue by leehambley** [supercollider/supercollider#2023]
Hi, I'd like to ask permission (if that's even allowable) under the GPL to use the file from https://github.com/supercollider/supercollider/blob/58a859acffbab27870e716d44659b18d2c74b9c0/cmake_modules/FindYamlCpp.cmake as part of my own CMake project.

GitHub credits the whole file in it's entirety to @timblechmann at https://github.com/supercollider/supercollider/commit/001cbc078134d9747ec4711c5680947f09a10895 

I ask because I don't know if what I am building will ever be released, but if it is, what license it will be made available under.

**Comment by vivid-synth** [comment]
IANAL but it's very likely that code is too small to be copyrighted anyway -- it's only 8 lines of cmake config.

**Comment by leehambley** [comment]
@vivid-synth good point, and there's nothing "creative" about it, I just wanted to make sure. I always feel fortunate to find the solution handed to me on a plate at GitHub and other places, credit where credit is due.
