### ISSUE TITLE
Model.sc in cmake

### ISSUE THREAD

**Issue by sonoro1234** [supercollider/supercollider#2027]
@bagong did you remember?
```
COMMAND ${CMAKE_COMMAND} -E copy_if_different "${CMAKE_SOURCE_DIR}/SCClassLibrary/Common/GUI/Base/Model.sc" $<TARGET_FILE_DIR:sclang>/SCClassLibrary/Common/GUI/Base
```
I dont know what must be done ( I just commented the line)

**Comment by bagong** [comment]
Yes, it's on my todo list. But it's a bit below the changes to 3.7 atm. Yep, the line can simply be removed, if you want to PR? But I am hoping for a few more changes that will make that stuff even simpler (no need to copy the folders then as well), we might as well see if those can be done together...
