### ISSUE TITLE
SoundFileView grid shows 1 second long segments

### ISSUE THREAD

**Issue by Nathnainiel** [supercollider/supercollider#2033]
I noticed this after updating from 3.6.6 to 3.7.1. When grid is on in SoundFileView, it draws each grid line as a 1 second long segment. Unless you set a gridResolution greater than 1, everything is blue and you cannot see the selection.
![1sgrid](https://cloud.githubusercontent.com/assets/12977989/15081261/6513e8cc-13c2-11e6-83a1-0b68b117a6a5.png)
![all_blue](https://cloud.githubusercontent.com/assets/12977989/15081260/650f4de4-13c2-11e6-9f5e-8524a47a9751.png)

**Comment by telephon** [comment]
Is this the reproducer?

```
// To zoom in/out: Shift + right-click + mouse-up/down
// To scroll: right-click + mouse-left/right
(
w = Window.new("soundfile test", Rect(200, 300, 740, 100));
a = SoundFileView.new(w, Rect(20,20, 700, 60));

f = SoundFile.new;
f.openRead(Platform.resourceDir +/+ "sounds/a11wlk01.wav");
f.inspect;

a.soundfile = f;
a.read(0, f.numFrames);
a.elasticMode = true;

a.timeCursorOn = true;
a.timeCursorColor = Color.red;
a.timeCursorPosition = 2050;
a.drawsWaveForm = true;
a.gridOn = true;
a.gridResolution = 0.2;

w.front;
)
```

seems fine here on master

**Comment by Nathnainiel** [comment]
Yes, that code gives the described result. Perhaps it is platform dependent. I am on Ubuntu 16.04.

**Comment by bagong** [comment]
I see the same as Nathainiel on Windows 3.7.1 and Mac Master with telephon's code.

**Comment by gusano** [comment]
> seems fine here on master

I can reproduce the bug on master (archlinux).

**Comment by vivid-synth** [comment]
(can we add the label "comp: QT GUI" to this?)

**Comment by muellmusik** [comment]
Can confirm this is the case on OSX as well

**Comment by deepbluesome** [comment]
I found it too. Hope that it could be fixed soon.

**Comment by brianlheim** [comment]
@deepbluesome Thanks for pinging this! I'm looking at the source right now and the problem will not be hard to solve. PR coming soon.

**Comment by brianlheim** [comment]
@deepbluesome @Nathnainiel this is now resolved!
