### ISSUE TITLE
Emacs and extBuffer.sc

### ISSUE THREAD

**Issue by simdax** [supercollider/supercollider#2035]
Installing 3.8dev I had issue with "serverRunning is not a variable" in extBuffer.sc from scide_scel extensions file.
I had to overwrite serverRunning with "this.serverRunning".

Not sure it's a bug or a problem from my configuration, so I posted this in the main list.

Have a doog day !

diff -u /usr/local/share/SuperCollider/Extensions/scide_scel/extBuffer.sc /home/simdax/prog/fixesSC/Server.sc
--- /usr/local/share/SuperCollider/Extensions/scide_scel/extBuffer.sc 2016-05-07 10:00:20.000000000 +0200
+++ /home/simdax/prog/fixesSC/Server.sc 2016-05-07 12:34:51.629299405 +0200
@@ -22,7 +22,7 @@
  this.quit;
  });
  };
- booter.value=serverRunning.binaryValue;
+ booter.value=this.serverRunning.binaryValue;
 
  killer = EmacsButton(w, ["K"], { Server.killAll });
  killer.enabled = false;
@@ -30,7 +30,7 @@
 
  active = EmacsText(w, this.name.asString, 12, \center);
  // active.background = Color.black;
- if(serverRunning,running,stopped);
+ if(this.serverRunning,running,stopped);
 
  makeDefault = EmacsButton(w, ["-> default"], {
  thisProcess.interpreter.s = this;
@@ -53,7 +53,7 @@
  SystemClock.sched(0.2, { this.stopAliveThread });
  };
  w.defineKey("n", { this.queryAllNodes })
- .defineKey(" ", { if(serverRunning.not) { this.boot } })
+ .defineKey(" ", { if(this.serverRunning.not) { this.boot } })
  .defineKey("d", {
  startDump = {
  this.dumpOSC(1);
@@ -111,7 +111,7 @@
  ctlr.remove;
  };
  });
- if(serverRunning,running,stopped);
+ if(this.serverRunning,running,stopped);
 
  w.newline;
 
@@ -134,7 +134,7 @@
  });
 
  ctlr = SimpleController(this)
- .put(\serverRunning, { if(serverRunning,running,stopped) })
+ .put(\serverRunning, { if(this.serverRunning,running,stopped) })
  .put(\counts,{
  countsViews.at(0).string = avgCPU.round(0.1);
  countsViews.at(1).string = peakCPU.round(0.1);
@@ -152,6 +152,10 @@
  }
 }

**Comment by crucialfelix** [comment]
closed with #2036

**Comment by vivid-synth** [comment]
Can this issue be closed?
