### ISSUE TITLE
Plugin example repository

### ISSUE THREAD

**Issue by snappizz** [supercollider/supercollider#2037]
This is part of the ongoing work at #1997 to improve the state of documentation for writing UGens. In the in-progress tutorial, I would like to point users to this repository with a minimal example of a server plugin:

https://github.com/snappizz/plugin-example

Can this repo belong to "supercollider" rather than my own account?

**Comment by bagong** [comment]
Sounds like a nice case for the examples folder? You could add it to your pull request?

**Comment by snappizz** [comment]
Hmm, interesting point. A separate repo is nice because users can fork it to develop their own ugens. Could it be a submodule?

**Comment by bagong** [comment]
Haha, submodules are getting a bit inflationary lately. I have contributed to that myself, so I shouldn't complain ;) They can cause trouble, but if they're added as a new folder, it is relatively painless. Oth they're nice because they can be a seed for development in kind of a separate "safe space"... But must it be a submodule in your case? I think the main function of a submodule is that you can add something external and then make sure it's development get's synchronized with the development of SC in the right way? Is such a tight link really required for this? Btw, I think sc3-plugins provides some kind of pre constructed environment for your own plugins. Maybe that's a good place? Or it could simply be "another" plugin that isn't built by default?

**Comment by snappizz** [comment]
This whole tutorial project is a sort of "message to my past self," and back when I was starting out I was missing a minimal, self-contained working example. I'm not staunchly opposed to putting it as its own directory in the main repo, but it should be a self-contained directory so past @snappizz can take it out of context and it'll still be complete.

But the sc3-plugins structure doesn't work that way. If you copy your MySawUGens directory (say), it's got your C++ file and your class file, but you still have to supply your own CMakeLists.txt. We don't want the beginners to have to work for their minimal example.

Making it its own repository adds the benefit of forkability. I'm not sure I understand the disadvantages of a separate repository.

**Comment by bagong** [comment]
I am not at home, maybe somebody more experienced can chime in. So just
short: Just a separate repo is a nobrainer. The submodule part is the
question. Why would you want your repo to be tied to the SC source tree?

**Comment by bagong** [comment]
Just in case my statement sounded ambiguous: adding another repo to the supercollider organization to have a stable address that feels like "belonging to SC" is trivial and I see no reason why not. It also allows other supercollider contributors to write directly to it. To make sense you'd have to be given write access, which from my side is more than okay. But ask the seniors. So again my question: would it really have to be bound to the sc source tree as submodule? It's not part of the SC build, is it?

**Comment by snappizz** [comment]
I think we misunderstood each other a little. I read "I think sc3-plugins provides some kind of pre constructed environment for your own plugins" as advocacy for making the repo part of sc3-plugins.

I'm not pushing very strongly for a submodule. Now that I think of it, a submodule has a slight benefit that the user can get the example from SC's source without needing network access, but if submodules are too much trouble that's fine by me.

**Comment by LFSaw** [comment]
you could add it to a gist (which is "just another git repo") and let people check it out separately. Also, I think a link within the sc-plugins README to such a resource would be great.

**Comment by snappizz** [comment]
Gist is also fine, as long as the owner is "supercollider" and not "snappizz." Adding a note to the sc3-plugins README is a good idea.

**Comment by bagong** [comment]
As far as I can see, Gist only allows forking individual files? @snappizz, I would suggest, just go ahead with a repo, and we'll add it to the SuperCollider organization. I don't see a strong argument for it to be a submodule, and that it is not a requirement to build SC is kind of a strong formal argument against it. If nobody disagrees here, I'll start it off with you. Two suggestions, maybe: as you move in the direction of something like a tutorial (which I like a lot), it seems to me at some point you would maybe want to add more "projects" to the repo, so maybe you don't want the first project in the root-folder of the repo? And maybe give it a more dignified name ;) ?

**Comment by snappizz** [comment]
I'm really liking the idea of multiple folders, each with incremental examples demonstrating different ugen features. Start with the simplest example, than introduce states, multiple calculation rates, allocation, buffers, randomness, demand rate, etc.

At that point, the tutorial could exist entirely in that repository via README files, so there's no need to tab back and forth between the documentation and the code.

**Comment by telephon** [comment]
I don't see a reason why it shouldn't be in the main supercollider repository like the other tutorials.

**Comment by bagong** [comment]
@telephon, you mean integrated in SC help, right, for exposure and accessibility? And how should the plugins projects be part of that?

**Comment by snappizz** [comment]
I think he means part of the examples/ directory in this repository. The help file would then tell the user, "Go look at examples/plugin-tutorial/ in the source code"

**Comment by bagong** [comment]
And what is your own take on that? I like both options. Having it in examples gives you fixed paths to refer to, having it as an independent repo makes it a sandbox to play with...

**Comment by snappizz** [comment]
I do prefer a separate repository because it's easier to fork and play around with. I suggested a  submodule because it brings us the best of both worlds, but I don't want to get involved in the ongoing Submodule Wars :)

**Comment by bagong** [comment]
Haha, no wars, just temporary annoyance about unexpected side effects (the war is more about discourse style). Part of it is learning how to deal with submodules. So don't take my opinion as the final word. If @telephon or somebody else thinks it's a good idea I am happy to comply ;)

**Comment by bagong** [comment]
Ah, btw, the Examples folder is located different relative to help in different OSses, not sure how that would have to be dealt with...

**Comment by bagong** [comment]
It might actually be possible to put it into help. I think the help parser only looks at files with the .schelp extension and your cmake files would only look at the files you need to build... That seems like it would be pretty ideal. So rather than the Readme, you'd use .schelp files and kind of have the best of two worlds...

**Comment by snappizz** [comment]
Forget what I said about the README's, it's not that great to have those docs separate from the regular docs. For now I think the tutorial can fit on one page, so we really only one .schelp file for the tutorial (and another for the reference).

According to [GitHub](https://help.github.com/articles/transferring-a-repository/#transferring-from-a-user-to-an-organization), we'll need the following steps to transfer ownership:

- Someone part of the organization puts me on a temporary admin team.
- I transfer the repository.
- Someone part of the organization revokes my admin access and grants me write access to that repository.

**Comment by bagong** [comment]
So you are planning to make the schelp-file part of the new repo? I think that would be nice. We could still decide to add the repo as a submodule into the HelpSource folder, or it might actually be possible to simply "include" the folder via the IDE...
I would vote for simplifying the administrative side of it by simply adding you to the "organization" (and keeping you for a hopefully long time ;) ), but I am not senior enough to decide that. So let's hope one of the oldhands does it within the next few days. If not, I'll go through it with you similar to the way you described. It sounds like you are confident in how to do the "Github wizardry" yourself ;)

**Comment by snappizz** [comment]
The repository is now at https://github.com/supercollider/plugin-example.

**Comment by LFSaw** [comment]
Thanks for the effort!
IMHO, it would be nice to mention https://github.com/supercollider/sc3-plugins in the README

**Comment by snappizz** [comment]
I've added that link to the plugin-example README. Once plugin-example has reached enough maturity, I'll add to the sc3-plugins README as well.

**Comment by snappizz** [comment]
Dang, plugin-example is a bad name since now there are multiple plugins. We should rename it to example-plugins.

I don't seem to have the privileges to rename it, can someone do that please?

**Comment by bagong** [comment]
That was an accidental misconfiguration. You should be able to do it yourself now.

**Comment by snappizz** [comment]
Thanks!
