### ISSUE TITLE
broken schelp skeleton

### ISSUE THREAD

**Issue by LFSaw** [supercollider/supercollider#2047]
the helpfile skeleton coming up when opening a non-existent help file contains 

```
:: First code examples: 
```

which is non-valid syntax for helpfiles. Unfortunately, I did not find the place where this is implemented so could not fix :/

**Comment by snappizz** [comment]
Are you talking about the "Copy and paste the text below" example when you visit an undocumented class? I'm not seeing that, e.g. on [this help file](http://doc.sccode.org/Classes/BF.html).

**Comment by snappizz** [comment]
Closing since I'm not seeing this issue.
