### ISSUE TITLE
change "source" to "Helpfile Source" in Helpfile display

### ISSUE THREAD

**Issue by LFSaw** [supercollider/supercollider#2049]
At the bottom the helpfile its source path (the .schelp) is displayed. 
Would be great to label it ```Helpfile Source```. 
Also, the implementation source at the top of the helpfile display only highlights the file and not the entire path. Would be great to have the whole path to be a link as it is the case for the ```schelp``` link.

![screen shot 2016-05-08 at 18 46 01](https://cloud.githubusercontent.com/assets/75468/15099108/22621b8e-154d-11e6-9686-7e888bd4d5ba.jpg)

**Comment by snappizz** [comment]
On doc.sccode.org, this should link to GitHub.

**Comment by LFSaw** [comment]
@snappizz , I see this as a separate issue since http://doc.sccode.org is an individual's page (not community driven)
