### ISSUE TITLE
syntax highlighting for schelp files

### ISSUE THREAD

**Issue by LFSaw** [supercollider/supercollider#2050]
…would be really cool and would make helpfile-editing more accessible to contributors. :)

**Comment by llloret** [comment]
@LFSaw, what editors would you have in mind?

**Comment by llloret** [comment]
I mean, is this for inside sc-ide? I am trying to put together an schelp syntax highlighter for atom, but I am not sure if thath's what you mean...

**Comment by crucialfelix** [comment]
I would be very interested in an schelp grammar for atom. 

But I really wish we had just used .rst or something standard.

**Comment by llloret** [comment]
Ok, I was working on something very simple on atom. It will not have the
same parsing abilities as the real schelp parser, but I am think it should
cover most cases.

The plan is to have something that highlights the known "XXXXX::"
constructs, and that knows some rules like highlighting argument:: or
return:: only withing a METHOD:: block (and highlights as an error if not
inside).

Also, of course, modal tags, links, etc.

Once I have something robust, I will post for feedback.

**Comment by crucialfelix** [comment]
I did this once for sublime text.

https://github.com/geoffroymontel/supercollider-package-for-sublime-text/blob/master/schelp.JSON-tmLanguage

You might be able to import it

**Comment by llloret** [comment]
I was doing something like this (https://github.com/llloret/schelp-atom).
Look at the top of the grammars/schelp.cson file. There is still a lot of
python stuff in there, because I started from that as a template.

This is still in very early stage, but your feedback about the approach
would be nice.

**Comment by llloret** [comment]
I have cleaned it so that it is easier to follow. It is also using includes, to simplify grammar rules. 

This is still work in progress, but has some nice highlighting capabilities now.

If anybody has a look, let me know your feedback.

**Comment by llloret** [comment]
You can see a screenshot of how it is looking here: https://github.com/llloret/schelp-atom/blob/master/README.md.

**Comment by crucialfelix** [comment]
Nice, let me know when you publish it !

On Wed, May 25, 2016 at 12:51 PM Luis Lloret <notifications@github.com>
wrote:

> You can see a screenshot of how it is looking here:
> https://github.com/llloret/schelp-atom/blob/master/README.md.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/supercollider/supercollider/issues/2050#issuecomment-221538889>
>
-- 
https://twitter.com/crucialfelix
https://medium.com/@crucialfelix
http://www.mattermind.com/

**Comment by llloret** [comment]
Ok, so I have published the atom package. The package is called schelp-syntax and it can be found in https://atom.io/packages/schelp-syntax.

One of the nice features is that it can highlight unrecognized tags, unbalaned closing tags, out of context tags, etc...

If someone can have a look and give feedback, that would be great. Hope this is useful.

This is the first atom package I publish, so there might be things in the package that are not qute right. Feedback on that is also appreciated.

**Comment by crucialfelix** [comment]
1st ! 
![screen shot 2016-05-25 at 20 15 40](https://cloud.githubusercontent.com/assets/218738/15551263/805c5e5a-22b5-11e6-99b5-0c17c61c1e87.png)

**Comment by capital-G** [comment]
Shall this be closed? There is an atom package and the SC IDE also supports syntax highlighting of schelp files.

**Comment by dyfer** [comment]
Thanks for catching this @capital-G
