### ISSUE TITLE
automatic addition of output range to UGen Helpfiles

### ISSUE THREAD

**Issue by LFSaw** [supercollider/supercollider#2051]
For beginners, it would be great to display the output range (unipolar/bipolar) in UGen helpfiles.
Can could be generated automagically via

```
LFSaw.ar.signalRange
```

**Comment by friendlyOrganisms** [comment]
if someone shows me how to add this, I'd be open for having a go at it...

**Comment by muellmusik** [comment]
Um.... At a quick glance I'd guess in SCDocHTMLRenderer:renderHeader check if the help file is for a UGen, and if so add the info by checking signalRange as above.

**Comment by LFSaw** [comment]
uh. um... now you know my (new) alter ego on github...
