### ISSUE TITLE
OSC/Trigger functionality broken in master

### ISSUE THREAD

**Issue by miczac** [supercollider/supercollider#2058]
This doesn't work anymore with  commit 80eddc87d4ab2ed8cfdf348cbe2350cfbc3c75c2

#1935 

```
(
SynthDef(\SendTrig,{
	var sig = Impulse.ar(2);
	SendTrig.ar(sig, 0, 1234);
	Out.ar(0, sig);
}).send(s);

o = OSCFunc({ arg msg;
	msg.postln;
},'/tr', s.addr);
)

t = Synth(\SendTrig);
t.free; o.free;
```
just bisected, works w/ 3.7.1  on OS X 10.9.5

**Comment by miczac** [comment]
to be more specific: according to ```git bisect``` this is the last working commit: 58a859acffbab27870e716d44659b18d2c74b9c0

**Comment by miczac** [comment]
just had a look at https://github.com/supercollider/supercollider/pull/1655 ... I'm sorry,I'm afraid this is beyond me. :/

**Comment by crucialfelix** [comment]
I don't see anything obvious yet. but maybe its something to do with .clientID_

are you positive it no longer works ?

**Comment by miczac** [comment]
On 9.May 2016, at 9:59 , Chris Sattinger <notifications@github.com> wrote:

> are you positive it no longer works ?

yup!

**Comment by telephon** [comment]
same here.

I just tried:

```
s.notify; // returns false
s.notify = true; // throws error below
```

```
ERROR: Message 'userSpecifiedClientID' not understood.
RECEIVER:
Instance of Server {    (0x11dd42048, gc=40, fmt=00, flg=00, set=05)
  instance variables [32]
    name : Symbol 'localhost'
    addr : instance of NetAddr (0x11dd41fd8, size=4, set=2)
    clientID : Integer 0
    userSpecifiedClientID : false
    isLocal : true
    inProcess : false
    sendQuit : true
    remoteControlled : true
    options : instance of ServerOptions (0x11dd42278, size=31, set=5)
    latency : Float 0.300000   33333333 3FD33333
    dumpMode : Integer 0
```

**Comment by telephon** [comment]
Ok, the fix is this: change line 270 of Server.sc to:

`	var <name, <>addr, <clientID, <userSpecifiedClientID = false;`

then you can write:

`s.notify = true;`

then it works.

**Comment by telephon** [comment]
It dawns upon me what this line in the code might mean, I had written a comment because I simply didn't get it:

`		statusWatcher.bootNotifyFirst = true; // unclear what this means.`

**Comment by telephon** [comment]
If it really means "notify after boot" then I can implement it.

**Comment by crucialfelix** [comment]
I also don't understand what bootNotifyFirst should mean.

The submodule thing should be fixed now because we put the same submodule in both 3.7 and master. just throw that folder in the trash and check out either branch and you will be fine.

**Comment by telephon** [comment]
>I also don't understand what bootNotifyFirst should mean.

If nobody speaks up, I'll remove that, I think.

**Comment by miczac** [comment]
On 9.May 2016, at 21:15 , Julian Rohrhuber <notifications@github.com> wrote:

> Ok, the fix is this: change line 270 of Server.sc to:
> 
> var <name, <>addr, <clientID, <userSpecifiedClientID = false;
> 
> then you can write:
> 
> s.notify = true;
> 
> then it works.

hm, I�m sure I�m missing something - just did that in master [3c0eb7f], but it doesn�t help.
(yes, I recompiled, I also restarted the whole shebang ;)
In fact I get more errors of the kind you posted.

I scanned ```git log``` for ```userSpecifiedClientID``` and can�t find a line where it's been changed recently.
The original commit is from Dec 2013 by Scott Wilson. There the �<� is missing.
So, I�m afraid that�s not entirely conclusive to me, but, as I said, I might be well missing something essential.

**Comment by miczac** [comment]
(PLS disregard my last msg - the source tree was not up-to-date. But then again, that's not conclusive either. But hey, maybe tomorrow ...;) )

**Comment by jamshark70** [comment]
> If it really means "notify after boot" then I can implement it.

I just reviewed its use in 3.7 and... it doesn't mean "notify after boot."

It appears to be trying to prevent something from happening twice, but the server boot code is really a bloody mess and it's impossible to see what it's doing from a quick glance. I think it's going to be necessary to trace through the state variables step by step and anticipate different cases (server wasn't started and you boot it, or it was started and you call one of the internal methods, or...).

I'd say this is a candidate for drawing up a proper spec that defines the behavior for many conceivable cases, and then gutting the current implementation in favor of a total rewrite. Right now the code looks like, "oh dear, this side case didn't work as expected, let's add in a hack to patch it up" repeated about 15 times.

**Comment by jamshark70** [comment]
As far as I can see:

- If you call s.boot, it sets bootNotifyFirst to true and then calls s.doWhenBooted. doWhenBooted remembers the bootNotifyFirst flag's value (and uses the saved value in the while loop) and then immediately clears bootNotifyFirst (the instance variable). So doWhenBooted's while loop is supposed to behave one way when called from the boot method, but another way when called directly.

- waitForBoot illustrates a case of this: If the server isn't running, it calls "boot" (which calls doWhenBooted, as noted) and then calls doWhenBooted again with the user action.

**Comment by jamshark70** [comment]
Blasted phone... Premature comment 

So the first doWhenBooted will have "true," and the second will have "false," for bootNotifyFirst.

Why this is necessary, I can't tell. It seems unnecessarily convoluted.

Certainly bootNotifyFirst is a private variable, so there's no need to worry what it means *to users*.

**Comment by jamshark70** [comment]
Sorry for the serial comments.

bootNotifyFirst may be intended to guarantee that the post-boot initialization in the "boot" method always runs before any post-boot functions registered by the user.

If so, factoring this out into some class that manages init order might be clearer than flinging obscurely-named state variables about. I started to think a queue might do it, but not really because the user can call doWhenBooted before booting, in which case the user function would be first in the queue.

In any case, my curiosity is satisfied so I'm out... hope this helps others find a good solution.

**Comment by telephon** [comment]
@jamshark70 thank you, detective, very welcome.
