### ISSUE TITLE
hid: windows: there is no support for HID in windows

### ISSUE THREAD

**Issue by llloret** [supercollider/supercollider#2059]
Hi, I am planning to complete the necessary work to have HID support on Windows, so I am opening this issue to keep track of the discussions for that.

**Comment by llloret** [comment]
Is there someone that I could contact to go through some questions I noted while I was doing an initial scan through the code?

Thanks

**Comment by sensestage** [comment]
Great!

The tricky part that needs to be solved is getting to the info from Windows on the HID report descriptor, which tells how to decode the incoming data.

So that is the backend implementation for hid_parse_element_info in ```exernal_libraries/hidapi/hidapi_parser/hidapi_parser.c```

**Comment by llloret** [comment]
Ok,

just to make sure I understand. For the initial parsing of the descriptors,
the idea is to do something similar to what is done on the Mac
implementation, right. By using the OS HID API (GetPreparsedData,
GetLinkColectionNodes, ...) to fill in the information on
hid_device_collections, hid_device_elements, etc.

NOT like on Linux in which you parse the raw descriptor yourself.

Is my understanding correct?

**Comment by sensestage** [comment]
Well, if there is a way to get to the raw descriptor on Windows, then that might be preferred. But, looking at the Windows API it is not possible to get access to this raw data. But then again, I did not have an environment available to look into this.

The downside of using the raw data would be that devices that need special drivers would not be accessible.

If we have to go through the Windows API the tricky part will be to make sure that things match up properly in terms of semantics of the controls, so that they are truly cross platform compatible.

It is a bit awkward that on the USB HID descriptor level everything is standardized, but that to get to that level you need to work around how each operating system developed their API's to access the data.

**Comment by sensestage** [comment]
So if access is possible to the raw data of the descriptor, the implementation would be in
```external_libraries/hidapi/windows/hid.c```
```int HID_API_EXPORT hid_get_report_descriptor(hid_device *dev, unsigned char *data, size_t length)```

There is one for mac as well, but in practice that did not actually work, that is why I had to make a workaround for it.

**Comment by llloret** [comment]
From what I have seen, the way to go is do something similar as you did in Mac. Use the high level native parsing API that the Windows provides. I found no way to get the raw descriptors from userspace. As you say this has some advantages over raw parsing.

**Comment by sensestage** [comment]
ok.
I just hope that we can keep the similarity of interface in SC as well, so that as little code changes as possible are needed when porting an instrument from one platform to the other.

In any case, I'm very curious to see what will come out!

**Comment by llloret** [comment]
Yes, that's what I am trying. Keep the interface the same, but using
Windows specific functions on the inside.

**Comment by llloret** [comment]
Ok, so I think I have an initial version that does the parsing of the collection and the element structures. @sensestage, if I post here the results I am getting, do you think you could have a look and see if they make sense?

I could post the HID descriptor of the Logitech Joystick I am using to test, and the results of the parsing in debug text.

Once we think that the initial parsing looks good, I could start doing the actual reading of the reports. I prefer to check with you, because I didn't have any previous experience with HID, so I might be way off...

Thanks in advance.

**Comment by llloret** [comment]
Just to keep people updated. I have a basic implementation of the collection parsing and element parsing, which looks reasonably good, but I can only test with my old Logitech Joystick, so cannot say for sure.

It is also being able to read an input report from the joystick, but when trying to parse it, so far it is not succeeding.

I will keep you posted on progress.

**Comment by sensestage** [comment]
yes, please show me what you have coming out of the Logitech Joystick.
Also good devices to test with are a generic mouse or a generic keyboard - I'm sure you have one of these around.

**Comment by sensestage** [comment]
General information on the USB HID spec:
http://www.usb.org/developers/hidpage/
http://www.usb.org/developers/hidpage/HID1_11.pdf

**Comment by llloret** [comment]
Hi, @sensestage, there is something I am not sure about regarding HID elements that are reported as having UsageMin and UsageMax, like for example groups of buttons. 

Is the idea that each usage has its own `hid_device_element` representation? What I mean, if I have a report which specifies a range through usage_min=9 and usage_max=12 (and it is not an array type), should each element usage 9, 10, 11, 12 have its own `hid_device_element`, or just one with element usageMin and usageMax set. From looking at the code, I would say that the expectation is that each usage gets its own element representation (this from how the Apple seems to return each usage separately in `hid_parse_element_info`, and how elements that are not arrays are handled in `hid_element_set_value_from_input`). 

Also, I am not sure, how arrays should be handled? My understanding is that you can have ranges that are not arrays. Would you process them differently?

I think I am quite close to have a good implementation for the input part of HID, but I would appreciate you thoughts on these questions...

Thanks

**Comment by llloret** [comment]
@sensestage, for reference to the previous comment on this issue, here is the USB HID descriptor of the Logitech Joystick:
```

        ------------------- HID Descriptor --------------------
bLength                  : 0x09 (9 bytes)
bDescriptorType          : 0x21 (HID Descriptor)
bcdHID                   : 0x0110 (HID Version 1.10)
bCountryCode             : 0x21 (33 = US)
bNumDescriptors          : 0x01
Descriptor 1:
bDescriptorType          : 0x22 (Class=Report)
wDescriptorLength        : 0x008B (139 bytes)
  05 01             Usage Page (Generic Desktop Controls)
  09 04             Usage (Joystick)
  A1 01             Collection (Application)
  A1 02               Collection (Logical)
  95 02                 Report Count (2)
  75 0A                 Report Size (10)
  15 00                 Logical Minimum (0)
  26 FF 03              Logical Maximum (1023)
  35 00                 Physical Minimum (0)
  46 FF 03              Physical Maximum (1023)
  09 30                 Usage (Direction-X)
  09 31                 Usage (Direction-Y)
  81 02                 Input (Var)
  75 04                 Report Size (4)
  95 01                 Report Count (1)
  25 07                 Logical Maximum (7)
  46 3B 01              Physical Maximum (315)
  66 14 00              Unit (0x14)
  09 39                 Usage (Hat Switch)
  81 42                 Input (Var, NullState)
  65 00                 Unit (0x00)
  75 08                 Report Size (8)
  26 FF 00              Logical Maximum (255)
  46 FF 00              Physical Maximum (255)
  09 35                 Usage (Rotate-Z)
  81 02                 Input (Var)
  A4                    Push
  95 08                 Report Count (8)
  75 01                 Report Size (1)
  25 01                 Logical Maximum (1)
  45 01                 Physical Maximum (1)
  05 09                 Usage Page (Buttons)
  19 01                 Usage Minimum (1)
  29 08                 Usage Maximum (8)
  81 02                 Input (Var)
  B4                    Pop
  09 36                 Usage (0x36)
  81 02                 Input (Var)
  95 04                 Report Count (4)
  75 01                 Report Size (1)
  25 01                 Logical Maximum (1)
  45 01                 Physical Maximum (1)
  05 09                 Usage Page (Buttons)
  19 09                 Usage Minimum (9)
  29 0C                 Usage Maximum (12)
  81 02                 Input (Var)
  95 04                 Report Count (4)
  81 01                 Input (Const)
  C0                  End Collection
  A1 02               Collection (Logical)
  26 FF 00              Logical Maximum (255)
  46 FF 00              Physical Maximum (255)
  75 08                 Report Size (8)
  95 07                 Report Count (7)
  09 02                 Usage (Button 2 (Secondary))
  91 02                 Output (Var)
  C0                  End Collection
  A1 02               Collection (Logical)
  95 04                 Report Count (4)
  75 08                 Report Size (8)
  26 FF 00              Logical Maximum (255)
  46 FF 00              Physical Maximum (255)
  06 00 FF              Usage Page (unk)
  09 01                 Usage (0x01)
  B1 02                 Feature (Var)
  C0                  End Collection
  C0                End Collection  

```
And this is what my element parsing looks like. See how the usages 9-12, and 1 to 8 have been separated into their own elements, and how in the HID descriptor they are using usage_min and max. **Is this how this is supposed to look?** Do not pay too much attention to report sizes, and indexes, because I think they are not too important for Windows parsing.
```

index: 0
parent_collection: 00000000451952D0
io_type: 1
usage_page: 1
usage_min: 0
usage_max: 0
usage: 49
type: 2
isarray: 0
isrelative: 0
isvariable: 1
logical_min: 0
logical_max: 1023
phys_min: 0
phys_max: 1023
unit: 0
unit_exponent: 0
report_id: 0
report_size: 10
report_index: 1


index: 1
parent_collection: 00000000451952D0
io_type: 1
usage_page: 1
usage_min: 0
usage_max: 0
usage: 48
type: 2
isarray: 0
isrelative: 0
isvariable: 1
logical_min: 0
logical_max: 1023
phys_min: 0
phys_max: 1023
unit: 0
unit_exponent: 0
report_id: 0
report_size: 10
report_index: 1


index: 2
parent_collection: 00000000451952D0
io_type: 1
usage_page: 1
usage_min: 0
usage_max: 0
usage: 57
type: 2
isarray: 0
isrelative: 0
isvariable: 1
logical_min: 0
logical_max: 7
phys_min: 0
phys_max: 315
unit: 20
unit_exponent: 0
report_id: 0
report_size: 4
report_index: 1


index: 3
parent_collection: 00000000451952D0
io_type: 1
usage_page: 1
usage_min: 0
usage_max: 0
usage: 53
type: 2
isarray: 0
isrelative: 0
isvariable: 1
logical_min: 0
logical_max: 255
phys_min: 0
phys_max: 255
unit: 0
unit_exponent: 0
report_id: 0
report_size: 8
report_index: 1


index: 4
parent_collection: 00000000451952D0
io_type: 1
usage_page: 1
usage_min: 0
usage_max: 0
usage: 54
type: 2
isarray: 0
isrelative: 0
isvariable: 1
logical_min: 0
logical_max: 255
phys_min: 0
phys_max: 255
unit: 0
unit_exponent: 0
report_id: 0
report_size: 8
report_index: 1


index: 5
parent_collection: 00000000451952D0
io_type: 1
usage_page: 9
usage_min: 0
usage_max: 0
usage: 1
type: 2
isarray: 0
isrelative: 0
isvariable: 1
logical_min: 0
logical_max: 0
phys_min: 0
phys_max: 0
unit: 0
unit_exponent: 0
report_id: 0
report_size: 8
report_index: 1


index: 6
parent_collection: 00000000451952D0
io_type: 1
usage_page: 9
usage_min: 0
usage_max: 0
usage: 2
type: 2
isarray: 0
isrelative: 0
isvariable: 1
logical_min: 0
logical_max: 0
phys_min: 0
phys_max: 0
unit: 0
unit_exponent: 0
report_id: 0
report_size: 8
report_index: 1


index: 7
parent_collection: 00000000451952D0
io_type: 1
usage_page: 9
usage_min: 0
usage_max: 0
usage: 3
type: 2
isarray: 0
isrelative: 0
isvariable: 1
logical_min: 0
logical_max: 0
phys_min: 0
phys_max: 0
unit: 0
unit_exponent: 0
report_id: 0
report_size: 8
report_index: 1


index: 8
parent_collection: 00000000451952D0
io_type: 1
usage_page: 9
usage_min: 0
usage_max: 0
usage: 4
type: 2
isarray: 0
isrelative: 0
isvariable: 1
logical_min: 0
logical_max: 0
phys_min: 0
phys_max: 0
unit: 0
unit_exponent: 0
report_id: 0
report_size: 8
report_index: 1


index: 9
parent_collection: 00000000451952D0
io_type: 1
usage_page: 9
usage_min: 0
usage_max: 0
usage: 5
type: 2
isarray: 0
isrelative: 0
isvariable: 1
logical_min: 0
logical_max: 0
phys_min: 0
phys_max: 0
unit: 0
unit_exponent: 0
report_id: 0
report_size: 8
report_index: 1


index: 10
parent_collection: 00000000451952D0
io_type: 1
usage_page: 9
usage_min: 0
usage_max: 0
usage: 6
type: 2
isarray: 0
isrelative: 0
isvariable: 1
logical_min: 0
logical_max: 0
phys_min: 0
phys_max: 0
unit: 0
unit_exponent: 0
report_id: 0
report_size: 8
report_index: 1


index: 11
parent_collection: 00000000451952D0
io_type: 1
usage_page: 9
usage_min: 0
usage_max: 0
usage: 7
type: 2
isarray: 0
isrelative: 0
isvariable: 1
logical_min: 0
logical_max: 0
phys_min: 0
phys_max: 0
unit: 0
unit_exponent: 0
report_id: 0
report_size: 8
report_index: 1


index: 12
parent_collection: 00000000451952D0
io_type: 1
usage_page: 9
usage_min: 0
usage_max: 0
usage: 8
type: 2
isarray: 0
isrelative: 0
isvariable: 1
logical_min: 0
logical_max: 0
phys_min: 0
phys_max: 0
unit: 0
unit_exponent: 0
report_id: 0
report_size: 8
report_index: 1


index: 13
parent_collection: 00000000451952D0
io_type: 1
usage_page: 9
usage_min: 0
usage_max: 0
usage: 9
type: 2
isarray: 0
isrelative: 0
isvariable: 1
logical_min: 0
logical_max: 0
phys_min: 0
phys_max: 0
unit: 0
unit_exponent: 0
report_id: 0
report_size: 4
report_index: 1


index: 14
parent_collection: 00000000451952D0
io_type: 1
usage_page: 9
usage_min: 0
usage_max: 0
usage: 10
type: 2
isarray: 0
isrelative: 0
isvariable: 1
logical_min: 0
logical_max: 0
phys_min: 0
phys_max: 0
unit: 0
unit_exponent: 0
report_id: 0
report_size: 4
report_index: 1


index: 15
parent_collection: 00000000451952D0
io_type: 1
usage_page: 9
usage_min: 0
usage_max: 0
usage: 11
type: 2
isarray: 0
isrelative: 0
isvariable: 1
logical_min: 0
logical_max: 0
phys_min: 0
phys_max: 0
unit: 0
unit_exponent: 0
report_id: 0
report_size: 4
report_index: 1


index: 16
parent_collection: 00000000451952D0
io_type: 1
usage_page: 9
usage_min: 0
usage_max: 0
usage: 12
type: 2
isarray: 0
isrelative: 0
isvariable: 1
logical_min: 0
logical_max: 0
phys_min: 0
phys_max: 0
unit: 0
unit_exponent: 0
report_id: 0
report_size: 4
report_index: 1


index: 17
parent_collection: 00000000451953D0
io_type: 2
usage_page: 9
usage_min: 0
usage_max: 0
usage: 2
type: 2
isarray: 0
isrelative: 0
isvariable: 1
logical_min: 0
logical_max: 255
phys_min: 0
phys_max: 255
unit: 0
unit_exponent: 0
report_id: 0
report_size: 8
report_index: 7


index: 18
parent_collection: 0000000045195350
io_type: 3
usage_page: 65280
usage_min: 0
usage_max: 0
usage: 1
type: 2
isarray: 0
isrelative: 0
isvariable: 1
logical_min: 0
logical_max: 255
phys_min: 0
phys_max: 255
unit: 0
unit_exponent: 0
report_id: 0
report_size: 8
report_index: 4
```

**Comment by llloret** [comment]
And this is what I get with HidFunc.trace, when pressing and releasing buttons 10 and 11. **Any comments on this?**:
```
HID Element Data:	devid: 0, elid: 14
	device: 	a HIDInfo(Logitech, Logitech Force 3D Pro, IDs:1133, 49798, \\?\hid#vid_046d&pid_c286#6&21162175&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}, ����������|, 4096, -1), 	page: nil 	usage: nil
	element:	a HIDElement(14: type: 2, usage: 9, 10)
				page: 9	usage: 10	raw value: 1,	value: 1.#INF
HID Element Data:	devid: 0, elid: 14
	device: 	a HIDInfo(Logitech, Logitech Force 3D Pro, IDs:1133, 49798, \\?\hid#vid_046d&pid_c286#6&21162175&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}, ����������|, 4096, -1), 	page: nil 	usage: nil
	element:	a HIDElement(14: type: 2, usage: 9, 10)
				page: 9	usage: 10	raw value: 0,	value: -1.#IND
HID Element Data:	devid: 0, elid: 15
	device: 	a HIDInfo(Logitech, Logitech Force 3D Pro, IDs:1133, 49798, \\?\hid#vid_046d&pid_c286#6&21162175&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}, ����������|, 4096, -1), 	page: nil 	usage: nil
	element:	a HIDElement(15: type: 2, usage: 9, 11)
				page: 9	usage: 11	raw value: 1,	value: 1.#INF
HID Element Data:	devid: 0, elid: 15
	device: 	a HIDInfo(Logitech, Logitech Force 3D Pro, IDs:1133, 49798, \\?\hid#vid_046d&pid_c286#6&21162175&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}, ����������|, 4096, -1), 	page: nil 	usage: nil
	element:	a HIDElement(15: type: 2, usage: 9, 11)
				page: 9	usage: 11	raw value: 0,	value: -1.#IND
```

**Comment by llloret** [comment]
@bagong did some research on output of descriptors and how they are reported on SC Mac, to shed some light in the above comments, and it was really useful.

We have started a doc to put the information that we gather for reference. You can find the doc here: https://docs.google.com/document/d/1w7jyf3Fi9xlj9B_a7KfciurVXMkAMEkVE4AUH-ATTI4/edit?usp=sharing.

**Comment by sensestage** [comment]
admittedly, it has been a while since I worked on this.
But I think for the usageMin and usageMax you should indeed make a set of elements - the report and index are important there. If you get that detailed info from the Windows backend, it seems that you get really the raw descriptor data, and you can use the parsing function that I have written for Linux for that - no need to reimplement.

There is a different case with keyboards, where you'd typically get 6 HID elements or so and they report as value the key that is pressed.
Unfortunately on Mac, you don't get access to the raw descriptor bytes, so you have to deal use their parsed info - which separates all keyboard presses into separate elements...

So I would say - given that you actually get the raw descriptor, reusing the linux parsing function is better - you may not even have to make separate #ifdef's in the hidapi_parser.c then, but just in the hidapi.c where the report descriptor is retrieved.

Although there is a fix needed for the type on the switch based on this warning:

```
> ../external_libraries/hidapi/hidapi_parser/hidapi_parser.c:665:24: warn=
ing: comparison of constant 192 with expression of type 'char' is always =
false [-Wtautological-constant-out-of-range-compare]
>             if ( descr_buf[i] == HID_END_COLLECTION ){ // JUST one =
byte
>                  ~~~~~~~~~~~~ ^  ~~~~~~~~~~~~~~~~~~
> ../external_libraries/hidapi/hidapi_parser/hidapi_parser.c:1333:16: war=
ning: enumeration value 'kIOHIDElementTypeCollection' not handled in swit=
ch [-Wswitch]
>               switch (tIOHIDElementType) {
>                  
```

I never got around to that yet, as it was kind of fiddly, as the usb spec is sometimes interpreting bytes as signed values and sometimes as unsigned.

**Comment by sensestage** [comment]
(and sorry for not replying daily to this - I am on the road at the moment...)

**Comment by llloret** [comment]
Hi, @sensestage, thanks for your input. There is no way no get the raw
descriptor with windows, at least I didn't find one. I have to the windows
provided API, Schick is different to the mac.

But it gives access to the data I need, just that I need to do some
tweaking to convert to what SC expects.

I have something quite working on the input side. I will tidy up, and do a
PR soon, so that you can have a look.

Thanks again,
Luis

**Comment by llloret** [comment]
I just want to make sure that it is clear that under windows there is no
access to the raw descriptor.

I am using HidD and HidP functions to get info on the report descriptor,
and on the reports themselves.
Luis

**Comment by sensestage** [comment]
What is strange in your HIDElement output posting are the mapped values.
Are the logical minimum and maximum detected properly?
These are used for automatic scaling of the raw value to the value.

**Comment by llloret** [comment]
Do you mean the ones for the buttons 10 and 11 that I posted some days ago?

I can see that the logical min and Max for the buttons is 0. Is that right?

I will check the data that @bagong collected.

**Comment by llloret** [comment]
You are right, the logical values for the buttons should be populated, but
they are 0. I will check and fix that.

Thanks for the feedback

**Comment by llloret** [comment]
Ok, I have vreated a Pull Request to serve as a base for discussion about the inclusion of this work. You can find it here: https://github.com/supercollider/hidapi/pull/1.

**Comment by adcxyz** [comment]
dear @llloret @sensestage @bagong, 
is this still open?

**Comment by llloret** [comment]
As far as I understand this is working.

**Comment by adcxyz** [comment]
so would you like to close ?

**Comment by adcxyz** [comment]
yay!
