### ISSUE TITLE
Very strange result...

### ISSUE THREAD

**Issue by muellmusik** [supercollider/supercollider#2073]
Try this:
```
1000000000000.do({|i| i.postln })
-> -727379968
```
No posts, just a wrong return val. Tested in latest master. Add or remove a 0 and it works as expected.

**Comment by redFrik** [comment]
not so strange i think.  compare with...
```
-1.do({|i| i.postln })
-> -1
```
your 1000000000000 is interpreted as a negative int.

**Comment by muellmusik** [comment]
Ah, of course!

**Comment by joshpar** [comment]
I wouldn't say interpreted, more overflowed.
Best
Josh

/*
Josh Parmenter
www.realizedsound.net/josh
*/

**Comment by muellmusik** [comment]
Pesky 32 bitness! Closing...

**Comment by bagong** [comment]
Looks like you should be using Windows ;)

**Comment by telephon** [comment]
or use floats:
`1000000000000.0.do({|i| i.postln })`

don't do it, it works!

**Comment by telephon** [comment]
in general, integer arithmetic with floats is the best solution in sclang for size limitation problems.

**Comment by timblechmann** [comment]
@telephon fun with floating-point arithmetics: `10000000000000000.0 + 1 == 10000000000000000.0`.

with 64bit sclang there would not be a fundamental problem to use 64bit integers, one would only have touch about every function which accesses slots. compiling the code to emit warnings when 64bit to 32bit integer conversions occur would help a lot, but the effort would be huge: i briefly had a look into this when i did the 64bit port of sclang and but didn't start as sclang is not really integer-type safe, as signed/unsigned types and int/long are wildly mixed in the interpreter code.

**Comment by muellmusik** [comment]
> in general, integer arithmetic with floats is the best solution in sclang for size limitation problems.

Yes, though of course at some stage loss of precision would mean that i in the example above could not increment by 1.

**Comment by telephon** [comment]
@timblechmann ah, that's a bit disappointing. It doesn't seem to be the interpreter though, which does a double dispatch on numbers, but the `_AddFloat` primitive. That sclang is dynamically typed is good and intentional, but that this logic isn't continued in the primitives correctly, is a drag.

>but didn't start as sclang is not really integer-type safe, as signed/unsigned types and int/long are wildly mixed in the interpreter code.

a correct method dispatch should and can take care of that.

**Comment by timblechmann** [comment]
>     but didn't start as sclang is not really integer-type safe, as
>     signed/unsigned types and int/long are wildly mixed in the
>     interpreter code.
> 
> a correct method dispatch should and can take care of that.

no. a correct use of integer types does. google has some good, guidelines:

https://google.github.io/styleguide/cppguide.html#Integer_Types

**Comment by telephon** [comment]
So what would that be in the current case? `prAddFloat` is called, and forwards to `prOpFloat` (with `addNum` as functor). Here we have:

```
template <typename Functor>
inline int prOpFloat(VMGlobals *g, int numArgsPushed)
{
	PyrSlot *a, *b;
	PyrSymbol *msg;

	a = g->sp - 1;
	b = g->sp;

	switch (GetTag(b)) {
		case tagInt :
			SetRaw(a, Functor::run(slotRawFloat(a), (double)slotRawInt(b)));
			break;
		case tagChar :
		case tagPtr :
		case tagNil :
		case tagFalse :
		case tagTrue :
			goto send_normal_2;
		case tagSym :
			SetSymbol(a, slotRawSymbol(b));
			break;
		case tagObj :
			if (isKindOf(slotRawObject(b), class_signal))
				SetObject(a, Functor::signal_fx(g, slotRawFloat(a), slotRawObject(b)));
			else
				goto send_normal_2;
			break;
		default :
			SetRaw(a, Functor::run(slotRawFloat(a), slotRawFloat(b)));
			break;
	}
```

Where the following statement is chosen:

`SetRaw(a, Functor::run(slotRawFloat(a), (double)slotRawInt(b)));`

that runs:

```
static inline double run(double lhs, double rhs)
	{
		return lhs + rhs;
	}
```

This seems fine according to the guidelines: "Use care when converting integer types. Integer conversions and promotions can cause non-intuitive behavior.". Here it shouldn't, but maybe I don't understand something basic here.


So the problem in the code above may come from the limits of 64bit floats? `10000000000000000.0 + 1` is already too much? Or where else is it?

This one is fine:

```
x = inf.asInteger.asFloat + 1;
x + 1 != x; // true
y = x * 2;
y / 2 == x; // true
```

**Comment by telephon** [comment]
Ah, now I see, misunderstanding, you said:

>with 64bit sclang there would not be a fundamental problem to use 64bit integers, one would only have touch about every function which accesses slots. compiling the code to emit warnings when 64bit to 32bit integer conversions occur would help a lot, but the effort would be huge.

I totally agree that there should be only one integer "type" in sclang. All we may need to do for higher precision integer arithmetic to implement some typical int methods also correctly for floats (like `div`). These could even have different names if the implementation would change behaviour (like `div`).

In Lua, there are only 64 bit floats, e.g., and I don't think that's a problem. Better to keep 16bit ints for efficiency and do all the rest with floats.

Or is there another  problem?

**Comment by timblechmann** [comment]
> In Lua, there are only 64 bit floats, e.g.,

https://www.lua.org/manual/5.3/manual.html

> The type number uses two internal representations, or two subtypes, 
> one called integer and the other called float. Lua has explicit
> rules about when each representation is used, but it also converts
> between them automatically as needed (see §3.4.3). Therefore, the
> programmer may choose to mostly ignore the difference between
> integers and floats or to assume complete control over the
> representation of each number. Standard Lua uses 64-bit integers and
> double-precision (64-bit) floats


> and I don't think that's a problem.

do you have any rationale why this isn't a problem?




> Better to keep 16bit ints for efficiency and do all the rest with 
> floats.
> 
> Or is there another problem?

16bit integers won't give you any performance improvements, however they
will give you lots of overflow issues (which caused the scsynth ABI
change a few years back).

**Comment by telephon** [comment]
> https://www.lua.org/manual/5.3/manual.html

ah, that's interesting, I just assumed it was the case because it has been said so often. I don't use Lua.

>do you have any rationale why this isn't a problem?

I just don't see the reasons why it should. But I'm sure there are some, and maybe you know them.

>16bit integers won't give you any performance improvements

I didn't know that. I assumed it was faster to do 16bit int than 64bit int. If this is not the case, then of course a complete switch to 64bit int seems reasonable.

**Comment by telephon** [comment]
maybe wait a little and then switch to unum?

http://insidehpc.com/2015/03/slidecast-john-gustafson-explains-energy-efficient-unum-computing/
