### ISSUE TITLE
How to Treat SC2 Backwards Compatibility in Docs and Codebase?

### ISSUE THREAD

**Issue by miczac** [supercollider/supercollider#2075]
A quick grep shows ~~more than 800~~ numerous mentions of SC2, mainly in guides and help-files.
How should they be treated in future releases of SC3? 
How much backwards compatibility still is needed?
What's the current user base for SC2?
...
?
PLS  discuss!

**Comment by crucialfelix** [comment]
SC2 only runs on Mac OS 9

It's time to move on I think.

I do have one computer that can still run that. somewhere in a box.


On Wed, May 11, 2016 at 5:05 PM Michael Zacherl <notifications@github.com>
wrote:

> A quick grep shows more than 800 mentions of SC2, mainly in guides and
> help-files.
> How should they be treated in future releases of SC3?
> How much backwards compatibility still is needed?
> What's the current user base for SC2?
> ...
> ?
> PLS discuss!
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/supercollider/supercollider/issues/2075>
>
-- 
https://twitter.com/crucialfelix
https://medium.com/@crucialfelix
http://www.mattermind.com/

**Comment by miczac** [comment]
but ... isn't that all about running SC2 code on current versions of SC3? 
I'm a freshman but intuitively (and for matters of sanity ;)  I'd be in favour of moving on too.
Also, just removing a help file would leave an undocumented class, leading to an empty help template not stating it's original purpose. (are there any means to avoid this kind of "orphans"?)

**Comment by crucialfelix** [comment]
I would have to look at those classes.

The code would have to be > 13 years old.

On Wed, May 11, 2016 at 5:38 PM Michael Zacherl <notifications@github.com>
wrote:

> but ... isn't that all about running SC2 code on current versions of SC3?
> I'm a freshman but intuitively (and for matters of sanity ;) I'd be in
> favour of moving on too.
> Also, just removing a help file would leave an undocumented class, leading
> to an empty help template not stating it's original purpose. (are there any
> means to avoid this kind of "orphans"?)
>
> —
> You are receiving this because you commented.
>
>
> Reply to this email directly or view it on GitHub
> <https://github.com/supercollider/supercollider/issues/2075#issuecomment-218498396>
>
-- 
https://twitter.com/crucialfelix
https://medium.com/@crucialfelix
http://www.mattermind.com/

**Comment by miczac** [comment]
http://doc.sccode.org/Overviews/SC3vsSC2.html

**Comment by snappizz** [comment]
(sorry about the tag, that was accidental)

**Comment by redFrik** [comment]
my opinion is that we should keep backwards compatibility just like we do it now... it's there but not very visible.  so in the case of AudioIn, keep the class but rather delete the helpfile or rewrite it to simply say: for backward compatibility only.  also not every class needs a helpfile imo.

**Comment by crucialfelix** [comment]
there is no particular need to remove those overviews. maybe add a historical note that SC3 came out in 2002 or something.

**Comment by vivid-synth** [comment]
Closing, as there seems to be consensus.
