### ISSUE TITLE
Cross-platform speech synthesis

### ISSUE THREAD

**Issue by jleben** [supercollider/supercollider#208]
[Issue migrated from SourceForge | ID: 3411566 | Submitted by 'None']
[http://sourceforge.net/support/tracker.php?aid=3411566]

QtGUI is missing the *speech method, therefore "Hi".speak fails.

Please add:

*speech { ^Speech }

to QtGUI.

**Comment by snappizz** [comment]
IMO speech synthesis is too niche to merit inclusion in the core library.

I would even advocate removal of the Speech class, since it doesn't interface at all with SC's audio ecosystem and it seems to be more or less replaceable with `say` and `.unixCmd`. Thoughts?

**Comment by telephon** [comment]
if it could be replaced by a unixCmd consistently, it could be moved to a quark.

**Comment by snappizz** [comment]
The existence of nasties like #1570 makes a pretty convincing case for removing Speech.

**Comment by snappizz** [comment]
Closing because core should be kept small. Speech synthesis implementations should be in quarks or third-party plugins.
