### ISSUE TITLE
scide: right click in the tab area inconsistency when clicking out of tabs

### ISSUE THREAD

**Issue by llloret** [supercollider/supercollider#2084]
If you right click in the editor tab area (where the script titles are), outside of all tabs, the options that are presented are not accurate. **Clicking "close" crashes the editor.**

When clocking out of the tabs, it should present an option to "Close All Tabs".

**Comment by bagong** [comment]
Confirmed on Mac. See Luis' PR #2085

**Comment by telephon** [comment]
Fixed on macos.

**Comment by brianlheim** [comment]
Closing, I think this was missed when the PR was merged.
