### ISSUE TITLE
HIDdef.element forwards arguments incorrectly

### ISSUE THREAD

**Issue by jamshark70** [supercollider/supercollider#2090]
https://github.com/supercollider/supercollider/blob/master/SCClassLibrary/Common/Control/HIDFunc.sc#L543 appears to be a typo. `key` should not be passed to `HIDFunc.element`.

**Comment by jamshark70** [comment]
Suggesting 3.7.2 -- it'll be a dirt simple fix for a method that can't function correctly under any circumstances at present.

**Comment by sensestage** [comment]
ok, seems like an easy fix.
Please apply it :)

**Comment by sensestage** [comment]
closed via https://github.com/supercollider/supercollider/pull/2105

**Comment by sensestage** [comment]
needs backportin to 3.7 branch?

**Comment by jamshark70** [comment]
I submitted the PR for 3.7. It needs to be merged forward into 3.8.

**Comment by crucialfelix** [comment]
when 3.7.2 is released (very shortly) then it will be merged into master and you will see it.  we may change that release branching policy with 3.8
