### ISSUE TITLE
What is the intended behaviour of maxFrames and scopeFrames

### ISSUE THREAD

**Issue by Factoid** [supercollider/supercollider#2100]
As a follow up to the previous question about the scope_reader pull method. I was wondering if there was any information on how maxFrames and scopeFrames are supposed to inter-operate.

In my tests, it appears that when you have scopeFrames < maxFrames, then while the buffer contains maxFrames units of data, only the first scopeFrames amount is ever used.

My presumption of the scope buffer is that it should behave like a ring buffer, where the data always fills unused values until hitting maxFrames and then wrapping back to the beginning.

If my outline for the scope buffer behaviour is the ideal one, then there is a bug, and I'd be willing to work on implementing the correct behaviour. As it stands, I can't see any way to correctly use scopeFrames, that only maxFrames should be used to control the frequency of updates, because the rest of the space in the buffer is left unused.

**Comment by telephon** [comment]
I'm not sure, but if I remember correctly, `scopeFrames` is smaller than `maxFrames` so that you can zoom on the time axis without having to allocate new memory.

**Comment by Factoid** [comment]
To clarify... here's what I'm seeing.
maxFrames = 5, scopeFrames = 0
[ 1, 2, 3, 4, 5 ]
[ 6, 7, 8, 9, 10]
[ 11, 12, 13, 14, 15 ]

maxFrames = 5, scopeFrames = 2
[ 1, 2, 0, 0, 0 ]
[ 3, 4, 0, 0, 0 ]
[ 5, 6, 0, 0, 0 ]

But I think the behaviour should be like this
[ 1, 2, 0, 0, 0 ]
[ 1, 2, 3, 4, 0 ]
[ 6, 2, 3, 4, 5 ]
[ 6, 7, 8, 4, 5 ]

Or even better.. like this.
[ 0, 0, 0, 1, 2 ]
[ 0, 1, 2, 3, 4 ]
[ 2, 3, 4, 5, 6 ]

**Comment by telephon** [comment]
I think it works like this: the `ScopeView` class just reads the frames `0 ... scopeFrames-1` and ignores the rest, which is only used when you increase scopeFrames.

**Comment by Factoid** [comment]
Is it then intended that for a scope out object, max frames is immutable, but scope frames can be adjusted on the fly? Otherwise I'm not sure what purpose scope frames serves.

For type of progression I want, I can do that on the client side assuming the other issue I logged is actually a bug, and I can proceed with fixing it.

**Comment by telephon** [comment]
>Is it then intended that for a scope out object, max frames is immutable, but scope frames can be adjusted on the fly? Otherwise I'm not sure what purpose scope frames serves.

Yes, in the current implementation this is how it is done. If you want to change that value, you just send a new synth with a different maxFrames (which is also on the fly).

But this is just the way it is currently done. If you think another scheme would be better, your contribution is very welcome.

The other issue (#2099) is probably a bug, but it would be good if someone else had another look.

**Comment by Factoid** [comment]
Just to clarify. If I create a ScopeOut2 with max frames 1024 and scope frames 256. Then I can re-use the same ScopeOut2 object to increase the scope frames up to 1024. But if I want to increase the max frames to 2048, then I need create a new ScopeOut2 object and destroy the old one?

Or was it that changing the value of either parameter requires a brand new ScopeOut2 object? It sounded like the first was how it works, and you were simply comfirming.

If I wanted to propose or experiment with a new ScopeOut UGen, I could do this as a plugin, correct? Create a ScopeOutSonicPi, which may or may not be accepted as a replacement for ScopeOut2.

I don't know if any 3rd party applications are using the scope shm interface besides us at the moment.

**Comment by telephon** [comment]
> But if I want to increase the max frames to 2048, then I need create a new ScopeOut2 object and destroy the old one?

Yes, only then.
It might be useful to have a look at the current implementation: https://github.com/supercollider/supercollider/blob/master/SCClassLibrary/Common/GUI/tools/Stethoscope.sc#L442

It just sends a new SynthDef and plays a synth from it whenever necessary.

>If I wanted to propose or experiment with a new ScopeOut UGen, I could do this as a plugin, correct? 

Yes, that would be the way to do it. I am pretty sure it can be improved.

>Create a ScopeOutSonicPi, which may or may not be accepted as a replacement for ScopeOut2.

I wouldn't choose platform specific names for anything that is in common, but otherwise, yes.
