### ISSUE TITLE
agile SC ?

### ISSUE THREAD

**Issue by miczac** [supercollider/supercollider#2117]
_I pondered and decided to put that Q here to increase chances to **involve as many collaborators as possible** into that discussion:_

On 20.May 2016, at 11:43 , Chris Sattinger crucialfelix@gmail.com wrote:

> Something I do when working with teams (doing agile sprints) is to discuss at the end of a cycle what 
> we can improve for the next cycle.

maybe it totally makes sense to consciously look at agile methods and eventually sensibly embrace (some of) them? 
then again (given the fact that SC is not really an "end-user product”) fully including docs and taking the SC-projects remote nature into account?
finding that balance, would that be too much of a challenge?

**Comment by snappizz** [comment]
I think this discussion is better for sc-dev.
