### ISSUE TITLE
allow relative Paths in LanguageConfig.includePaths and excludePaths

### ISSUE THREAD

**Issue by adcxyz** [supercollider/supercollider#2126]
Currently, LanguageConfig include/excludePaths are absolute only. 
When switching to the git versions of SCClassLibrary and HelpSource for development,
the excludepaths become /path/to/mySC.app/Contents/Resources/SCClassLibrary etc.,
and the includepaths are /path/to/git/supercollider/SCClassLibrary etc. 

a config file with these include/excludes will only work for the exact app it was made with;
if one moves or renames the app, or uses a different app version, library will not compile, 
because  /path/to/myOtherSC.app/Contents/Resources/SCClassLibrary is not excluded. 

converting all paths inside the app folder to relative paths would solve this.

**Comment by miguel-negrao** [comment]
Why not use the standalone option (in the IDE it appears as "exclude default paths") which will exclude all default paths ? Then you can include whichever paths you want, no need to put anything in the exclude list.

If you really need relative paths, my PR for projects #1978  implements that.

Btw, Does the help system also use the language config includes and excludes to pick up the help files ?

**Comment by bagong** [comment]
> Btw, Does the help system also use the language config includes and excludes to pick up the help files ?

Yep. If I remember correctly includes does and excludes doesn't.

**Comment by adcxyz** [comment]
Had not seen the  "exclude default paths" option in the IDE, that solves the dev-switching, thanks!

Thanks also for pointing out #1978, looks very interesting, havent done much with Projects yet. 
Will check them out ASAP. 

The other use for relative Paths that would make sense to me is for (adc) standalone apps, 
where I prefer putting an extra folder for quarks etc in Resources for maximum selfcontainedness.

**Comment by adcxyz** [comment]
- Yep. If I remember correctly includes does and excludes doesn't.

Just tested, HelpSource folders can also be included and excluded, like classes.

**Comment by timblechmann** [comment]
the problematic point will be to define a reasonable reference path, which works on all platforms (windows install folder, osx app bundle, unix/fhs installation)

**Comment by miguel-negrao** [comment]
> the problematic point will be to define a reasonable reference path, which works on all platforms (windows install folder, osx app bundle, unix/fhs installation)

In my PR I only activate resolving relative paths in project mode, and then a path is resolved relative to the path of the language config file, which the user is free to save wherever they want.

In normal mode I also added resolving relative to the default paths ("%ResourceDirectory%/mydir",  "%SystemExtensionDirectory%/mydir", "%UserExtensionDirectory%/mydir"), which are already mapped accordingly in all platforms by current sclang code.

I thought this should cover most use cases...

**Comment by telephon** [comment]
maybe this is solved now?

**Comment by miguel-negrao** [comment]
My PR (#3278) has not been merged yet. At the moment part of it was split (#3733) and is awating review. Once that is merged I can refactor the original PR on top of #3733 and possibly split it further into multiple PRs if that makes review easier (possibly n the sequence FileTree -> save config file in sessions -> projects).

**Comment by telephon** [comment]
> At the moment part of it was split (#3733) and is awating review. 

It seems that there is still a reply missing from your side to one of @brianlheim 's comments?

**Comment by miguel-negrao** [comment]
> It seems that there is still a reply missing from your side to one of @brianlheim 's comments?

Hum, I thought I had addressed everything. I had a look again but I can't find the comment that I didn't reply. Sorry, can you point it out to me ? :-)

thanks.

**Comment by telephon** [comment]
Ah, maybe I am wrong. I had seen the comment "there should be a corresponding setter" by brian without a reply, but there seems to be a setter (maybe you added that later, but that isn't apparent).

If it's ok, @brianlheim, can you approve?

**Comment by miguel-negrao** [comment]
Ah, I had made a comment at some point saying I agreed with all the feedback that I didn't explicitelly comment on and would act on it ... :-)

**Comment by adcxyz** [comment]
issue is stale.
