### ISSUE TITLE
asOSCArgArray flattens string into an array of chars

### ISSUE THREAD

**Issue by telephon** [supercollider/supercollider#2128]
reproducer:

```
Ndef.clear;
Ndef(\x).ar;
Ndef(\x, 0);
```

```
[ "#bundle", 15776962901962673001, 
  [ 9, [ "", !unknown tag 'y' 0x79 ! ]
]
FAILURE IN SERVER /s_new wrong argument type
```

**Comment by telephon** [comment]
```
Ndef.clear;
Ndef(\x).kr;
Ndef(\x, 0);
```

**Comment by telephon** [comment]
The reason is this:

`[9, "hello", 1007, 1].asOSCArgArray`

returns:

` [ 9, [, h, e, l, l, o, ], 1007, 1 ]`

Why has this changed?

**Comment by telephon** [comment]
This also is wrong:

`Synth(\default, ["test", 677, "freq", 500]);`

returns:

`[ 9, "default", 1006, 0, 1, [ 2907692859892 ]`

**Comment by telephon** [comment]
Caused by #2096.

**Comment by jamshark70** [comment]
2096... gahhhh... unintended consequences.

Well, another case where we don't have a functional spec and it causes confusion.

**Comment by telephon** [comment]
Btw. for me this case smells like a family of problems we tend to get from the particular hierarchy between `SequenceableCollection`, `Array`, `String`, and other subclasses of the first.
