### ISSUE TITLE
VOsc phase input is control rate

### ISSUE THREAD

**Issue by snappizz** [supercollider/supercollider#2139]
It's pretty reasonable to expect the phasein argument of VOsc to accept audio-rate input. Unfortunately, right now it's fixed at control rate. [Source is here](https://github.com/supercollider/supercollider/blob/850ce3d838cfb250901207df536ff381ce438650/server/plugins/OscUGens.cpp#L2039).

**Comment by telephon** [comment]
The audio rate phase input came for `SinOsc` also long after it was introduced. So there may be more cases like that. It is very valuable to fill in such gaps.

**Comment by snappizz** [comment]
I skimmed OscUGens and LFUGens and I couldn't find any other oscillators with phase arguments that are control rate only. Osc, SinOsc, and OscN are fine.

**Comment by telephon** [comment]
Good to hear. `LFPulse` is, but the argument name makes it clear that it is i-rate.
