### ISSUE TITLE
"jackey.h missing" build error

### ISSUE THREAD

**Issue by vivid-synth** [supercollider/supercollider#2145]
When building on a fresh machine with:

```
mkdir build
cd build
cmake -DSC_DOC_RENDER=False -DSUPERNOVA=True -DNATIVE=True -DSC_IDE=False -DSC_QT=False -DSCLANG_SERVER=False -DSC_WII=False -DSC_ED=False -DSC_VIM=False -DNO_AVAHI=True -DAUDIOAPI=jack ..
make
```

> Scanning dependencies of target server_test
> [ 96%] Building CXX object testsuite/supernova/CMakeFiles/server_test.dir/server_test.cpp.o
> In file included from /home/air/box_build/supercollider/server/supernova/./server/server.hpp:40:0,
>                  from /home/air/box_build/supercollider/testsuite/supernova/server_test.cpp:3:
> /home/air/box_build/supercollider/server/supernova/./audio_backend/jack_backend.hpp:31:24: fatal error: jackey.h: No such file or directory
>  #    include <jackey.h>
>                         ^
> compilation terminated.
> testsuite/supernova/CMakeFiles/server_test.dir/build.make:62: recipe for target 'testsuite/supernova/CMakeFiles/server_test.dir/server_test.cpp.o' failed
> make[2]: *** [testsuite/supernova/CMakeFiles/server_test.dir/server_test.cpp.o] Error 1
> CMakeFiles/Makefile2:4651: recipe for target 'testsuite/supernova/CMakeFiles/server_test.dir/all' failed
> make[1]: *** [testsuite/supernova/CMakeFiles/server_test.dir/all] Error 2
> Makefile:160: recipe for target 'all' failed
> make: *** [all] Error 2
> 

(Note that jackey.h does in fact exist, at external_libraries/jackey/jackey.h)

**Comment by vivid-synth** [comment]
Interestingly, this fails even with ```JACK_USE_METADATA_API=FALSE``` !

**Comment by flv0** [comment]
This is because JACK_USE_METADATA_API is not a cache variable but will be set each time depending on the presence of jack/metadata.h header, see server/CMakeLists.txt:40.

**Comment by vivid-synth** [comment]
@flv0 ```-DJACK_USE_METADATA_API``` (no "SC_") is the flag that actually turns off the use of jackey.h, though

**Comment by vivid-synth** [comment]
https://github.com/supercollider/supercollider/issues/2179 fixes this broken build, but can anyone comment on the atypical naming of the cmake flag?

**Comment by ventosus** [comment]
@vivid-synth as @flv0 pointed out, JACK_USE_METADATA_API is not a cmake option supposed to be toggled by the user manually. It's simply a temporary variable set by CHECK_INCLUDE_FILES telling wether the <jack/metadata.h> header exists on the user's system or not.

    CHECK_INCLUDE_FILES("jack/metadata.h" JACK_USE_METADATA_API)
