### ISSUE TITLE
merge 3.7 branch into master again before branching 3.8

### ISSUE THREAD

**Issue by danstowell** [supercollider/supercollider#2175]
Sorry if this is already obvious. I was just trying to work out why my patch #2031 wasn't in master, and it's because it happend (on 3.7 branch) too recently. It reminded me that the 3.7 branch will need re-merging into master before 3.8 gets branched.

**Comment by crucialfelix** [comment]
Ah you are right I totally forgot to do that merge.  Burned out brain.

**Comment by crucialfelix** [comment]
Working on it.
