### ISSUE TITLE
SoundFileView does not display selection

### ISSUE THREAD

**Issue by scztt** [supercollider/supercollider#2176]
Submitter: Martin Schuetz
Email: martin-schuetz@t-online.de
SuperCollider 3.8dev, Qt version 5.5.1
SoundFileView does not show selection, the background seems to be 'overpainted'.
it can be reproduced with the HelpFile Step by step examples.
the a.zoom(0.2) line show parts of the view correctly.

**Comment by snappizz** [comment]
Can reproduce:

    (
    w = Window.new;
    a = SoundFileView(w);
    w.front;

    f = SoundFile.new;
    f.openRead(Platform.resourceDir +/+ "sounds/a11wlk01.wav");

    a.soundfile = f;
    a.read(0, f.numFrames);
    )

**Comment by snappizz** [comment]
dupe of #2033
