### ISSUE TITLE
IDE server controls are incomplete

### ISSUE THREAD

**Issue by telephon** [supercollider/supercollider#2184]
1. In previous versions of the server-to-ide implementations, there were entries for `start recording` not only in the server pop up on the bottom right corner, but also in the menu. It is a good practice to put all functionality in the menu, too, because it is a minimal self-documenting feature (especially for blind users).
2. When pausing the recording, programmatically, the counter continues.

When I did the server refactoring, I also implemented pause recording and stop recording, and the updating of the counter, which was a little hard to do. It must be in the still unmerged part of the server refactoring, I don't know what of it will be going into 3.8 now.

I put this here in case anyone sees this bug.

**Comment by snappizz** [comment]
With the refactor now merged and set for 3.9, this is resolved.
