### ISSUE TITLE
Building external libs more than once?

### ISSUE THREAD

**Issue by vivid-synth** [supercollider/supercollider#2192]
I'm far from a cmake expert so it's possible I'm reading the output wrong, but when building SC from source it seems so be compiling boost (and maybe other things) more than once.

Here's an example build where a randomly-selected boost module seems to build 3 times:

https://travis-ci.org/supercollider/supercollider/jobs/137632983

```
[ 22%] Building CXX object external_libraries/CMakeFiles/boost_program_options.dir/boost/libs/program_options/src/utf8_codecvt_facet.cpp.o
```

```
[ 23%] Building CXX object external_libraries/CMakeFiles/boost_filesystem.dir/boost/libs/filesystem/src/utf8_codecvt_facet.cpp.o
```

```
[ 43%] Building CXX object lang/CMakeFiles/libsclang.dir/__/external_libraries/boost/libs/filesystem/src/utf8_codecvt_facet.cpp.o
```

**Comment by vivid-synth** [comment]
This seems like relatively low-hanging fruit in terms of speeding up the build

**Comment by brianlheim** [comment]
@vivid-synth good catch! yes, for some reason we're bundling boost sources into the sclang target, when we could link instead. i don't notice much of a speedup in build time (both before and after, about 3'00"), but it is cleaner and probably makes a noticeable difference if you're facing a longer overall build time
