### ISSUE TITLE
NdefMixer currently ignores changes made with EZControlSpecEditor

### ISSUE THREAD

**Issue by muellmusik** [supercollider/supercollider#2194]
Try this:

```
NdefMixer(s)

Ndef(\testy, { SinOsc.ar(\freq.kr(400)) })

Ndef(\testy2, { SinOsc.ar(\freq2.kr(400)) })
```

edit the Ndefs, and then double-click on 'freq' or 'freq2' to edit the spec. When you go back to the slider it ignores the changes.

**Comment by muellmusik** [comment]
This is tested in 3.7.2.

**Comment by adcxyz** [comment]
hi @muellmusik, 

Tests and comments: 

```
NdefMixer(s);
Ndef(\testy, { SinOsc.ar(\freq.kr(400)) });
Ndef(\testy2, { SinOsc.ar(\freq2.kr(400)) });
```
* send Ndef(\testy) to editor
 * -> freq range is default 20-20k - OK
* twiddle freq a bit
* double-click on freq label to edit range to 50-5000
 * -> freq range is now 50-5000 - OK

* send Ndef(\testy2) to editor
 * -> Ndef(\testy2) freq range is 20-20k - OK
* send Ndef(\testy) to editor again
 * -> freq range is back to 20-20k

I think this is actually OK: The NdefGui is temporarily used by different objects, 
so editing the range of one EZSlider will only change the local spec the slider uses 
while it's object remains the same. 
It does not send any spec changes back to the object that has the parameter, so with a new object, a new spec is passed in and the old one gone. 

If you want the object itself, here Ndef(\testy) to have a specific freq range, it is much clearer to do
```
Ndef(\testy).addSpec(\freq, [50, 5000, \exp]);
```
Then it knows that range independently of any gui or controller, and controllers can always get that spec by asking
```
Ndef(\testy).getSpec(\freq);
```
which is what JITGuis do.

so, OK to close?

**Comment by telephon** [comment]
@muellmusik what do you think?

**Comment by telephon** [comment]
feel free to reopen!
