### ISSUE TITLE
Document help typos

### ISSUE THREAD

**Issue by jamshark70** [supercollider/supercollider#2211]
```
WARNING: SCDoc: In ./HelpSource/Classes/Document.schelp
  Broken link: 'Classes/CocoaDocument'
WARNING: SCDoc: In ./HelpSource/Classes/Document.schelp
  Broken link: 'Classes/EmacsDocument'
WARNING: SCDoc: In ./HelpSource/Classes/Document.schelp
  Broken link: 'Classes/ScelDocument'
WARNING: SCDoc: In ./HelpSource/Classes/Document.schelp
  Broken link: 'Classes/CocoaDocument'
WARNING: SCDoc: In ./HelpSource/Classes/Document.schelp
  Broken link: 'Classes/CocoaDocument'
WARNING: SCDoc: In ./HelpSource/Classes/Document.schelp
  Broken link: 'Classes/ScelDocument'
WARNING: SCDoc: In ./HelpSource/Classes/Document.schelp
  Broken link: 'Classes/EmacsDocument'
WARNING: SCDoc: In ./HelpSource/Classes/Document.schelp
  Method *new has arg named 'envir', but doc has 'argument:: makeListener'.
WARNING: SCDoc: In ./HelpSource/Classes/Document.schelp
  Method *listener not found.
WARNING: SCDoc: In ./HelpSource/Classes/Document.schelp
  Method *globalKeyDownAction_ has arg named 'action', but doc has 'argument:: value'.
WARNING: SCDoc: In ./HelpSource/Classes/Document.schelp
  Method *globalKeyUpAction_ has arg named 'action', but doc has 'argument:: value'.
WARNING: SCDoc: In ./HelpSource/Classes/Document.schelp
  Broken link: 'Classes/CocoaDocument'
WARNING: SCDoc: In ./HelpSource/Classes/Document.schelp
  Method -bounds not found.
WARNING: SCDoc: In ./HelpSource/Classes/Document.schelp
  Method -== has arg named 'that', but doc has 'argument:: doc'.
WARNING: SCDoc: In ./HelpSource/Classes/Document.schelp
  Method -editable_ has arg named 'bool', but doc has 'argument:: abool'.
WARNING: SCDoc: In ./HelpSource/Classes/Document.schelp
  Method -title_ has arg named 'newTitle', but doc has 'argument:: argName'.
WARNING: SCDoc: In ./HelpSource/Classes/Document.schelp
  Method -alwaysOnTop not found.
WARNING: SCDoc: In ./HelpSource/Classes/Document.schelp
  Method -isListener not found.
WARNING: SCDoc: In ./HelpSource/Classes/Document.schelp
  Method -unfocusedFront not found.
WARNING: SCDoc: In ./HelpSource/Classes/Document.schelp
  Method -mouseDownAction_ has arg named 'action', but doc has 'argument:: value'.
WARNING: SCDoc: In ./HelpSource/Classes/Document.schelp
  Method -mouseUpAction_ has arg named 'action', but doc has 'argument:: value'.
WARNING: SCDoc: In ./HelpSource/Classes/Document.schelp
  Method -keyDownAction_ has arg named 'action', but doc has 'argument:: value'.
WARNING: SCDoc: In ./HelpSource/Classes/Document.schelp
  Method -keyUpAction_ has arg named 'action', but doc has 'argument:: value'.
WARNING: SCDoc: In ./HelpSource/Classes/Document.schelp
  Method -font not found.
WARNING: SCDoc: In ./HelpSource/Classes/Document.schelp
  Method -underlineSelection not found.
```

**Comment by jamshark70** [comment]
Also, for key actions:

> An instance of Function or FunctionList. The arguments passed to the function are: char, modifiers, unicode, keycode. See View: Key actions for details on these arguments.

But:

```
	< closed FunctionDef >   0x6dcf3c8
		arg char = <instance of Document>
		arg mods = $�
		arg unicode = 262144
		arg keycode = 65533
```

Should be "**document**, char, modifiers, unicode, keycode"

**Comment by snappizz** [comment]
CocoaDocument doesn't exist anymore, so any references to it can be safely removed. But EmacsDocument and ScelDocument are still in SC, and they might be broken links depending on what editor you're using.

There also appear to be some inconsistencies between the different Documents. The scide Document has no "makeListener", but ScelDocument does. All the other warnings are for similar reasons.

I haven't been keeping up on the development of Document. What's the reason for this madness?

**Comment by telephon** [comment]
>What's the reason for this madness?

The original Document interpretation in the cocoa version (SC 3d5 I think) was very useful and spawned interesting activities, like animated code. Its interface wasn't very cleanly done and well thought out, however. But it was used, so nobody would take the step to refactor it and break code.

Then various systems like scel added their own document classes, and because the functionality wasn't so evident, there wasn't much motivation to go beyond another ad hoc solution. Scott worked hard to fix the old document interface in the new IDE, which at least made old code work again.

A completely new version of Document with a systematic interface would certainly be a welcome step into a brighter future.

Having rich text for code would be just one of the missing features on the back end. Being able to fully control the editor from sclang would awake a lost culture of literate programming unless it is now safely dead.

**Comment by telephon** [comment]
Just for posterity, the method `makeListener` used to make the document a post window. In cocoa sclang, there was only one type of window, a rich text file. You could make a help file from it, use it for code, use it as a post window, or write a pamphlet in it. You could run code from the post window or from the pamphlet. This was very nice, but had some disadvantages.

**Comment by snappizz** [comment]
The best option for now would be to make the Document help file match Document, and disregard ScelDocument and EmacsDocument.
