### ISSUE TITLE
Quarks list is in random order by default

### ISSUE THREAD

**Issue by snappizz** [supercollider/supercollider#2212]
![screenshot_2016-06-29_11-38-36](https://cloud.githubusercontent.com/assets/1211064/16464268/40964822-3dee-11e6-90ec-1001a02ce677.png)

**Comment by snappizz** [comment]
It might be in order of most recent update... but unless that information is displayed in the list I don't see the point in sorting it that way

**Comment by crucialfelix** [comment]
Actually what happens is that by default it sorts by the first column which is INSTALLED. (no column header)

Qt cannot AFAIK sort by two columns like SQL.

If we sort by name then you don't immediately see what Quarks you have installed. If you have ZArchive you have to scroll to the bottom. It is near impossible to scroll down the list and mentally collect which ones you have installed.

Solution: assign a sort number to each Quarks when it first loads up. Your installed ones first in alphabetical order, followed by not installed ones in alphabetical order.

Then add a sort order column that uses that (with no header and maybe invisible or subtle gray text).

This solves another annoyance: when you click to install it immediately resorts and the new quark shoots to the top.  So after un/installing do *not* recalculate the sort order. Just leave them in place so they don't squirm.

**Comment by snappizz** [comment]
Thanks!

**Comment by telephon** [comment]
Couldn't that sort logic be part of the GUI itself? It knows the names and can check if the quark is installed, no?

**Comment by crucialfelix** [comment]
Qt can only sort by a column and I think it does it by string.

What I suggested was to make a fake invisible column and assign a sort number to each item. 

As it is with the fix in #2214 they are now in the perfect sort order (installed first, everything alphabetical) so that solves this issue I think.

The squirming thing could be another issue.

**Comment by telephon** [comment]
Ah I see it is not a `ListView`, but a `TreeView`, which has its hidden QT sorting scheme. I suppose one could remove all items (`QuarkRowView`s), and reinsert them in a new order. But perhaps that is not an idiomatic design then.
