### ISSUE TITLE
Improving Quarks.gui

### ISSUE THREAD

**Issue by snappizz** [supercollider/supercollider#2213]
Quarks.gui looks pretty bare -- it's just a list of quark names when you first open it up. The `\summary` parameters from the .quark files (and maybe some other metadata) should also be included somehow to give some kind of preview in the listing. One possibility is to set up a web service that periodically polls all the .quark files and rolls them into a database for the user.

A cute little icon for each quark would also be nice.

Many quarks in the quarks list have been untouched for years and probably no longer work. I suggest that we mark all quarks that have not been updated since 3.6.6 as "unmaintained" and hide them from the list by default.

Quarks.gui doesn't need to be as flashy as Google Play Store or Ubuntu Software Center, but it could be more friendly and less full of old junk.

**Comment by jamshark70** [comment]
> I suggest that we mark all quarks that have not been updated since 3.6.6 as "unmaintained" and hide them from the list by default.

Ouch, that's going to cut out a lot of my work, then (including classes that I use daily and which are unmaintained because they are still working).

Agreed that there's a lot of cruft in the list, but 3.7 has really not been out for that long. It's a bit much to require quark authors to put in a garbage commit just to keep their work alive.

**Comment by snappizz** [comment]
well, not all quarks then. Just the ones where it's clear that the quark doesn't work anymore and the author isn't interested in updating.

**Comment by jamshark70** [comment]
I'm probably too harsh about that... I think such a requirement would affect me more than others because I split my extensions into about a dozen quarks (to avoid the opposite problem of a massive all-or-nothing quark where, to use one class, you have to install a hundred others that you'll never use). So for me "check that there's been an update in the last few months since 3.7" is not a couple minutes' work, more like at least 30-60 minutes (if that includes making up some commit to drop in). Just pointing out that the burden is not uniformly distributed.

Actually there are some obvious meaningful commits I could do, it's just, finding time.

**Comment by gusano** [comment]
> Quarks.gui looks pretty bare -- it's just a list of quark names when you first open it up. The \summary parameters from the .quark files (and maybe some other metadata) should also be included somehow

@snappizz Which version of sc are you using? Quarks summary is already in there:

![quarks](https://cloud.githubusercontent.com/assets/271068/16472290/53e9683a-3e63-11e6-8b70-be9ca404c59f.gif)

> Many quarks in the quarks list have been untouched for years and probably no longer work. I suggest that we mark all quarks that have not been updated since 3.6.6 as "unmaintained" and hide them from the list by default

If some quarks are obviously broken (and most likely not to get fixed), we could simply remove them from https://github.com/supercollider-quarks/quarks/blob/master/directory.txt, but I disagree with hiding those which haven't been updated, which does not mean they are actually broken.

**Comment by snappizz** [comment]
@gusano The quark summary appears only when you specifically fetch the quark. I'm asking for the summaries to show up on all quarks, so you can browse the quark listings and pick things that look interesting.

**Comment by gusano** [comment]
@snappizz Oh I see, yeah that would be nice to have.

**Comment by crucialfelix** [comment]
I definitely agree. At the time of course I needed to build it and get it out and make sure the important stuff worked. Time to improve. Go for it !

One possibility is to fetch the README.md and cache them locally. Not all Quarks have them, but they could be autogenerated from the quarks files. That's probably too much work though.

You could fetch just the quarks files and cache them locally. Or as you say a web service or a script that gathers all quarks files into a single document.

**Comment by gusano** [comment]
Another possibility would be to add the summary to *directory.txt* so we'd have something like `name=url=summary`.

**Comment by crucialfelix** [comment]
Adding to directory should be really really easy. Just add your URL in there.

**Comment by snappizz** [comment]
We want to avoid duplicated information. If a quark author changes their `\summary`, they shouldn't have to go and update it in two places. And we don't want the user making 200 http requests, so there needs to be some kind of aggregation, which is why I brought up the web service.

I volunteer to write it. It would be a node.js server that polls all the .quark files every 15 minutes or so and assembles them into one big file. (I ballpark the size at 200 quarks * 300 bytes = 60kb.)

one question: how would we host the server?

**Comment by scztt** [comment]
@snappizz - I'd be willing to foot the bill for AWS backing, as long as it's lightweight.

In order for that to work right, there are a couple quark fields that would probably have to change, so they could be accessible outside of SC. The big one is the SC version dependency ("sc_version" I think?), which is currently a function. There may be one or two more that might have issues? The rest can be easily represented as JSON data.

Keep in mind - if we store the summary in the quark data, then it allows people to change the summary between quark versions - this seems both unnecessary and potentially very confusing for users. We should be careful to separate metadata that can change from version to version, from metadata that should be true across all versions of a quark.

**Comment by snappizz** [comment]
An alternate idea is to process the quarkfile as a raw string without parsing it and pass that to the user, which then `.interpret`'s each one. It works, although it's not secure -- someone can put a `.unixCmd` in there and execute code on the user's machine, even though our server will be unaffected. If only the quarkfiles were JSON from the start, this would all be much easier...

**Comment by scztt** [comment]
Also, in dealing with out-of-date quarks, I'd suggest something like this:
1. Add a REQUIRED non-function-based "sc_version" compatibility list. Quarks should be required to say what version(s) of SC they will work in - this seems like a good pattern regardless.
2. Assume for quarks _without_ the field, that the version compatibility is something like ["3.4.*", "3.5.*", "3.6.*"] - or whatever we can assume to be a reasonable baseline.
3. Update / allow authors to update _maintained_ quarks with newer versions that reflect what they support and have tested with.
4. In the UI, mark all incompatible Quarks with a warning, and potentially just filter them out by default for new users.

This will prevent a TON of incompatibility problems for new users who don't know that half of the quarks were built several versions ago. And, it'll gently nudge current Quark maintainers to test their quarks when new versions of SC are released, which is beneficial for both them and the community at large.

**Comment by scztt** [comment]
@snappizz They're already JSON-compatible except for one or two fields. We could enforce that moving forward, but that would require us to add better JSON encode/decode to SC - interesting work, but not really a top priority.

Btw, the unit test runner is currently collecting all quarks and their versions via github API's. See:
https://github.com/scztt/qpm/blob/qpm-unit/qpm/quarks/github_http.py
https://github.com/scztt/qpm/blob/qpm-unit/qpm/quarks/__init__.py
https://github.com/scztt/qpm/blob/qpm-unit/qpm/cli/controllers/quark.py#L34

**Comment by snappizz** [comment]
Here is a crude solution written in 15 minutes which simply curls `raw.githubusercontent.com` to retrieve quark data: https://github.com/snappizz/metaquark/blob/master/fetch.py

**Comment by scztt** [comment]
The hard part is really version numbers. Since almost no quarks have their version numbers accurately matched between git tags and quark files, you've got to plow through the history of the quark file and execute each one in SC to collect all the versions. This ends up being very complex and very slow (I added this capability to the qpm-unit stuff, and then removed it because I didn't want to support it in the future...). You'll actually max out the daily request limit of your github auth after doing this 5 or 6 times.

Not sure if there's a workaround to this, other than to provide the version list at the level of the quarks database itself, and not inside individual quarks repos.

**Comment by crucialfelix** [comment]
I did a bunch of scripts for batch operations on all the quarks when I first exported them.

https://gist.github.com/crucialfelix/69303a24b5ef9a2d8512ac5318a59d14

One of those extracts all the quark files into a single quarks.json

The other ones do batch operations using that quarks.json

These could be used as starters for doing other batch operations like creating README.md where missing or for git tagging each repo with the version.

**Comment by crucialfelix** [comment]
ironically the original SVN repo had all the quarks files in one DIRECTORY precisely so that we could checkout the whole directory without fetching everything.

**Comment by crucialfelix** [comment]
note that there are also webhooks that could be triggered when somebody pushes to a quark repository. https://developer.github.com/v3/repos/hooks/

Amazon lambda can get one of those webhooks and run a node.js or python script. It would easily qualify for the free tier. No need for polling or a server.

https://aws.amazon.com/lambda/details/

Save the generated/updated quarks.json file in an S3 bucket

**Comment by snappizz** [comment]
@crucialfelix We also have to consider whether we want to support quarks not hosted on GitHub (BitBucket, GitLab, etc.). Currently all quarks are on GitHub, so no need to worry about those for now.

**Comment by scztt** [comment]
Another possibility is a common quark .travis.yml script, that does any build/assembly/metadata-gathering steps, and posts to the central repository, any time there's a new version tagged. It's easy to set up, the compute resources are free, and its using tools that are already common to other parts of the app environment. At that point, the server could be a VERY dumb thing with 4 or 5 endpoints, backed by a simple database.

**Comment by snappizz** [comment]
nobody's worked on this one. stale issue, vague goals.
