### ISSUE TITLE
aDocument.path fails because SCIDE invokes *syncFromIDE inconsistently

### ISSUE THREAD

**Issue by jamshark70** [supercollider/supercollider#2217]
Tested in 3.7. I'm not able to test on master at the moment.

Document's `*syncFromIDE` method expects the path to be transmitted as an array of integer ASCII values. This happens correctly if documents are open in the IDE at the time the library is compiled (i.e., when launching the IDE with an active session, or when recompiling the class library while documents are open). In this case, printing the `path` input as a compile string reveals the array:

```
*syncFromIDE path: [ 47, 104, 111, 109, 101, 47, 100, 108, 109, 47, 115, 104, 97, 114, 101, 47, 115, 99, 45, 104, 106, 104, 46, 103, 105, 116, 47, 83, 67, 67, 108, 97, 115, 115, 76, 105, 98, 114, 97, 114, 121, 47, 115, 99, 105, 100, 101, 95, 115, 99, 113, 116, 47, 83, 99, 73, 68, 69, 46, 115, 99 ]
initFromIDE set path: /home/dlm/share/sc-hjh.git/SCClassLibrary/scide_scqt/ScIDE.sc
```

This is not working correctly in other cases:
- **Opening a document** (ctrl-o): The IDE constructs the ASCII array, but then for some totally unfathomable reason, it transmits this to sclang as a string representation (with an erroneous trailing comma!), which sclang treats as a symbol: `'[47,104,111,109,101,47,100,108,109,47,116,109,112,47,116,101,115,116,45,112,97,116,104,46,115,99,100,]'` Note the difference: the first example is the compile string of an array of integers. Here, we have a symbol that could be converted to a proper integer array by `path.asString.interpret.drop(-1)`.
- **Creating a new document** (ctrl-n): The IDE constructs an ASCII array for "nil" and again transmits the string representation of the ASCII array: `'[110,105,108,]'`
- **Saving the same new document to disk** (ctrl-s or ctrl-shift-s): `*syncFromIDE` _is not called at all_.

User impact: `Document.current.path` is very likely to hold an empty string, even when the IDE tab corresponds to a disk file.

**Comment by jamshark70** [comment]
I think this is it:

https://github.com/supercollider/supercollider/blob/master/editors/sc-id/core/doc_manager.cpp#L730 is in a call to `Document.syncDocs` and this appears correct:

```
        QString docData = QStringLiteral("[\'%1\', %2, %3, %4, %5, %6, %7],")
            .arg(doc->id().constData())
            .arg(doc->titleAsSCArrayOfCharCodes())
            .arg(doc->textAsSCArrayOfCharCodes(0, -1))
            .arg(doc->isModified())
            .arg(doc->pathAsSCArrayOfCharCodes())
            .arg(start)
            .arg(range);
```

https://github.com/supercollider/supercollider/blob/master/editors/sc-ide/core/doc_manager.cpp#L1307 is the call to `Document.syncFromIDE` -- note that what was `%5` above is, here, `\'%5\'` -- hm?

```
    QString command =
            QStringLiteral("Document.syncFromIDE(\'%1\', %2, %3, %4, \'%5\', %6, %7)")
            .arg(doc->id().constData())
            .arg(doc->titleAsSCArrayOfCharCodes())
            .arg(doc->textAsSCArrayOfCharCodes(0, -1))
            .arg(doc->isModified())
            .arg(doc->pathAsSCArrayOfCharCodes())
            .arg(start)
            .arg(range);
```

I might try a PR later (scared of messing up my repository though).

**Comment by telephon** [comment]
Tried to reproduce it after #2222 is merged, but can't. Maybe I don't take the right steps though.

**Comment by jamshark70** [comment]
Several people tested the pr and said it worked... plus, the changes are technically correct as far as I can see. I'll close it.
