### ISSUE TITLE
Quarks.gui: default ordering is case-sensitive

### ISSUE THREAD

**Issue by snappizz** [supercollider/supercollider#2224]
The default ordering when bringing up Quarks.gui sorts A to Z first and then a to z.

![untitled](https://cloud.githubusercontent.com/assets/1211064/16672322/449b139a-445a-11e6-98f0-0f742fae48a2.png)

Manually selecting alphabetical order gives the desired case-insensitive ordering.

**Comment by gusano** [comment]
@snappizz I don't think this is ever gonna change as sorting in sc does not consider capital letters to be identical to their corresponding lower case letters (IIRC this is also the case on osx Finder, but not on linux, might be wrong about that though..).

Consistency in quark names would probably be the best fix :japanese_ogre:

**Comment by crucialfelix** [comment]
I would not call this a bug.

You could add a custom column and do your own sort, but that will be slower and creates code that needs to be discussed and maintained.

**Comment by gusano** [comment]
> You could add a custom column and do your own sort, but that will be slower and creates code that needs to be discussed and maintained

@crucialfelix And as you know this is what is already happening to be able to get the installed ones sorted first so IMHO it's not worth adding another one.

**Comment by gusano** [comment]
```javascript
[\a, \A, \b, \B].sort
// [\A, \B, \a, \b]
```

closing..

**Comment by snappizz** [comment]
The bug is that the sort order that appears by default is inconsistent with the sort order you get when you click to sort by quark name.

![untitled](https://cloud.githubusercontent.com/assets/1211064/16696917/fa7403b0-44fb-11e6-8ffa-37b4baf320f9.png)

Needless to say, it's a very minor issue.

**Comment by crucialfelix** [comment]
oh I see what you mean now. Qt does case insensitive sorting, but the fix that @gusano did does simple character value sorting.

that could be fixed by collecting each string asLower (or whatever the method is)

we've now spent more time talking about it then simply doing it.
