### ISSUE TITLE
labelX/labelY properties of plot are not shown

### ISSUE THREAD

**Issue by michaeldzjap** [supercollider/supercollider#2225]
From the Plotter help file:

```
(
a = { (0..30).scramble }.dup(2).plot;
a.setProperties(
    \fontColor, Color.red,
    \plotColor, Color.blue,
    \backgroundColor, Color.grey(0.8),
    \gridColorX, Color.white,
    \labelX, "Humidity",
    \labelY, "Hello"
);
a.refresh;
);
```

The x and y labels are not shown for some reason.

**Comment by snappizz** [comment]
Can reproduce.

**Comment by telephon** [comment]
same here. seems to draw at a wrong position.

**Comment by Sciss** [comment]
The problem is in `Plot:drawLabels` that `Pen.strokeColor_=` is used, but it should be `Pen.fillColor_=`.

**Comment by paum3** [comment]
resolved in https://github.com/supercollider/supercollider/pull/5419
