### ISSUE TITLE
Inconsistent panning behavior of Grain ugens

### ISSUE THREAD

**Issue by snappizz** [supercollider/supercollider#2230]
Following #2136, I want to recap and figure out the scope of this issue.

The following behavior is the standard we want to strive for:

- with 1 channel, pan is ignored.
- with 2 channels, pan behaves like Pan2.
- with more than 2 channels, pan behaves like PanAz.

However, none of the grain ugens implement this correctly:

- GrainSin, GrainBuf, GrainIn, GrainFM: for 2 channels, the pan behavior outside of (-1,+1) folds around rather than clipping like Pan2. 
- TGrains (and TGrains2/TGrains3 from sc3-plugins): doesn't support 1 channel. for 2 channels, the pan behavior outside of (-1,+1) *wraps* around.

I feel this bug really exemplifies the disappointing level of quality control we have in our ugens. I am wondering if we can get some kind of test suite going for the server plugins, and if anyone wants to continue discussion on that, we can start a new issue or a thread on sc-dev (don't discuss it here, please).

**Comment by joshpar** [comment]
> On Jul 13, 2016, at 10:13 PM, Nathan Ho <notifications@github.com> wrote:
> 
> GrainSin, GrainBuf, GrainIn, GrainFM: for 2 channels, the pan behavior outside of (-1,+1) folds around rather than clipping like Pan2.

These are wrong and should be fixed. The fix will also make the panning more efficient (since it should index the stored sine table, rather than use the sin / cos functions ). 

Josh

**Comment by snappizz** [comment]
There is some duplicated code in these ugens for the pan calculations. I wonder if we can move some math into the plugin headers. The mono/Pan2/PanAz convention is useful to other plugin developers making their own granular ugens, and also makes it easy to fix these problems in TGrains2 and TGrains3 while keeping things DRY.
