### ISSUE TITLE
HelpBrowser: on OSX cmd-enter on an example in help runs code from document

### ISSUE THREAD

**Issue by kisielk** [supercollider/supercollider#2251]
shift-enter on an example runs the example code under the cursor in the help browser, but cmd-enter runs the code in the current document instead, even if the help window is the one that is focused.

This happens with both the official 3.7 release and the head version I compiled. Using Qt 5.5.1.

**Comment by snappizz** [comment]
Can't reproduce on Linux.

**Comment by telephon** [comment]
known issue: #1676. Solving it will need a bit of refactoring by someone who is well read in the IDE codebase.

**Comment by kisielk** [comment]
Sorry for the duplicate. I did search past issues but couldn't find anything, somehow missed those.

**Comment by telephon** [comment]
@kisielk no problem, this happens to everyone all the time. Thanks for noting it!
