### ISSUE TITLE
no version 3.7 on ubuntu ppa

### ISSUE THREAD

**Issue by qleonetti** [supercollider/supercollider#2255]
https://launchpad.net/~supercollider/+archive/ubuntu/ppa
the last version from 2014, is it possible to update it? 

If not, where can I get SC version 3.7 for ubuntu? 
Thanks!

**Comment by snappizz** [comment]
The Ubuntu PPA is definitely in need of an update. @danstowell, I believe you're in charge of that?

You can download the latest stable from here: http://supercollider.github.io/download

**Comment by danstowell** [comment]
Hi. I have limited effort available for supercollider now, so I prefer to focus my energy on the official debian package, which then "percolates" into ubuntu. That means that 3.7.x is going to be in Ubuntu Yakkety - see here: http://packages.ubuntu.com/search?keywords=supercollider&searchon=names

**Comment by snappizz** [comment]
closing as duplicate of #2917
