### ISSUE TITLE
Typo in 3.7.2 OSX release causes crash on CaseSensitive filesystem

### ISSUE THREAD

**Issue by morriswinkler** [supercollider/supercollider#2261]
There is a small typo in the release of supercollider 3.7.2. 

It is almost impossible to find since no one with a bit of a brain uses a case sensitive file system on OSX ( except me :).

so now the typo: 

SuperCollider.app/Contents/Resources/qt.conf 
```
[Paths]
Plugins = PlugIns
```

needs to become 

```
[Paths]
Plugins = Plugins
```

I could not find the place where the build process creates that file.  Other wise i would have send in a pull request.

**Comment by snappizz** [comment]
It was in `cmake_modules/DeployQt5.cmake`. Does #2262 fix it?

**Comment by crucialfelix** [comment]
we discussed this before. I'm trying to find the thread

**Comment by crucialfelix** [comment]
I guess I noticed it before but I'm not sure if talked about it. The fix seems correct. The alternative of course is to rename the folder. PlugIns is MoreCamely.
