### ISSUE TITLE
Change Github description?

### ISSUE THREAD

**Issue by vivid-synth** [supercollider/supercollider#2263]
Not everyone who'd love SC is looking for a new language. My suggestion:

## From
A programming language for real time audio synthesis and algorithmic composition.

## To
A language and server for real time audio synthesis and algorithmic composition.

## Alternately
A language, server, and IDE for real time audio synthesis and algorithmic composition.
A language and environment for real time audio synthesis and algorithmic composition.
An environment for real time audio synthesis and algorithmic composition.

**Comment by vivid-synth** [comment]
The reason I'd like to highlight the existence of a server is that it may not be clear to people coming to the project that besides sclang, this is a core component of:

 - TidalCycles
 - Sonic Pi
 - Overtone
 - supercollider.js
 - ScalaCollider
 - HSC3
 - Vivid
 - SCRuby
 - Supriya
 - Lua2SC
 - etc.

**Comment by snappizz** [comment]
"A real-time audio server, programming language, and IDE for audio synthesis and algorithmic composition."

**Comment by vivid-synth** [comment]
Works for me

**Comment by crucialfelix** [comment]
My favorite so far from @snappizz :

> "A real-time audio server, programming language, and IDE for audio synthesis and algorithmic composition."

"real-time" is a bit unnecessary. isn't everything real time ?

"audio server" is a bit curious and invites more questions. "audio synthesis server" might be clearer. something something "networking" ... just muddled thoughts here sorry.

for reference, supercollider.js describes it as:

> SuperCollider is an environment and programming language for real time audio synthesis and algorithmic composition. It provides an interpreted object-oriented language which functions as a network client to a state of the art, realtime sound synthesis server.

but we need a one-liner of course.

**Comment by crucialfelix** [comment]
We would change it on supercollider.github.io too. and then we make t-shirts and coffee cups

**Comment by vivid-synth** [comment]
To @crucialfelix 's suggestions, how bout:

An audio synthesis server, programming language, and IDE for synthesis and algorithmic composition.

Or, if we don't want to repeat "synthesis," just keep it simple:

An audio synthesis server, programming language, and IDE.

**Comment by crucialfelix** [comment]
Another stab:

An audio server, programming language, and IDE for sound synthesis and algorithmic composition.

(eliminates the double synthesis. it sounds fine to me now)

buzzword mining:

https://en.wikipedia.org/wiki/List_of_audio_programming_languages
https://en.wikipedia.org/wiki/Comparison_of_audio_synthesis_environments

**Comment by crucialfelix** [comment]
I think the use of "real-time" is mostly a relic of the early csound era. it used to be not real time though now it is.

**Comment by snappizz** [comment]
People used to Csound and DAWs might not automatically infer the "real-time" bit, but I'm not arguing. I can understand leaving it out if we want to keep it concise.

I can roll with @crucialfelix's proposal: "An audio server, programming language, and IDE for sound synthesis and algorithmic composition." If a shorter description is needed in other places, we can reduce it to this: "A platform for audio synthesis and algorithmic composition."

**Comment by vivid-synth** [comment]
If others don't have comments I'll change this to the last thing @crucialfelix suggested ("An audio server, programming language, and IDE for sound synthesis and algorithmic composition.") in a few days.

**Comment by vivid-synth** [comment]
Ok, it's been almost 2 weeks. Changing!
