### ISSUE TITLE
Checkboxes appear in the upper left of help files in OSX

### ISSUE THREAD

**Issue by kisielk** [supercollider/supercollider#2286]
![image](https://cloud.githubusercontent.com/assets/58618/17748529/ba1812ce-646e-11e6-8588-df1fbbf6bb2a.png)

Using 3.7.1. I have tried both the official release and building from source.

**Comment by snappizz** [comment]
Do they show up in an ordinary browser?

**Comment by kisielk** [comment]
How do I view the search page in an ordinary browser?

Also I should clarify the checkboxes are actually there, they just don't show on the screen.

**Comment by nuss** [comment]
The SuperCollider help system is a simply a collection of html files, located in your `userAppSupportDir`. Execute the following line in SuperCollider to see where that is, then open a webbrowser, hit cmd+o, navigate to that location and open `Search.html`:
    ```Platform.userAppSupportDir```

**Comment by kisielk** [comment]
The checkboxes appear fine in both Chrome and Safari

**Comment by snappizz** [comment]
That confirms that it's not a CSS problem, but some issue with the help viewer itself.

**Comment by telephon** [comment]
confirmed.

**Comment by snappizz** [comment]
we found the checkboxes -- they were out hiding from us in the upper left under the top bar, and are now visible as an accidental consequence of #2967.

**Comment by snappizz** [comment]
just a wild stab -- try `input[type=checkbox] { position: static }` in `scdoc.css`? or `position: relative`?

**Comment by brianlheim** [comment]
neither of those work :(

**Comment by brianlheim** [comment]
Found a fix, it was a Qt-level bug. #3028.
