### ISSUE TITLE
Document.new envir argument doesn't become active until after switching tabs

### ISSUE THREAD

**Issue by snappizz** [supercollider/supercollider#2289]
In scide, using the `envir` argument on `Document.new` does not immediately take effect. You have to switch back and forth between tabs. To reproduce, run this and follow the directions:

```
(
var env, instructionText;
env = Environment();
env[\foo] = 3;
instructionText = "// Evaluate this line, switch to the other tab and back, and evaluate it again\n~foo";
Document("environment test", instructionText, env);
)
```

A workaround is to set the `envir` property after the fact:

```
(
var env, doc, instructionText;
env = Environment();
env[\foo] = 3;
instructionText = "// Evaluate this -- works as expected\n~foo";
doc = Document("environment test", instructionText);
doc.envir = env;
)
```

This could be platform-dependent, so I should mention I'm on Ubuntu Studio 16.04, 64-bit.

**Comment by snappizz** [comment]
Actually the second example exhibits the same bug if you move it to a class library. The correct workaround is to open and close a new Document to force a tab switch:

    Document("", "").close;

**Comment by telephon** [comment]
related:  #3717

**Comment by snappizz** [comment]
i can't repro this anymore.
