### ISSUE TITLE
supernova does not load the same plugin paths as scsynth

### ISSUE THREAD

**Issue by snappizz** [supercollider/supercollider#2290]
supernova isn't working at all for me. I'm on Ubuntu Studio 16.04, 64-bit, latest master.

This code:

```
{ SinOsc.ar }.play;
```

results in this:

```
Exception when reading synthdef: Cannot load synth temp__0: Unit generator Control not installed
Cannot create synth (synthdef: temp__0, node id: 1001)
```

I also get many similar messages for all the synthdefs created by quarks in my class library.

Seems that supernova can't find the server plugin shared object files. It's probably because they're in an unusual place -- my CMAKE_INSTALL_PREFIX is `~/usr/local/`. But how come scsynth finds them fine?

**Comment by vivid-synth** [comment]
Looks like you can use the ```ugen-search-path``` command line argument? ```~/usr/local``` doesn't seem to be in ```set_plugin_paths``` in server/supernova/server/main.cpp

Not sure why it works with scsynth

**Comment by snappizz** [comment]
this may be related to #3391, but #3433 doesn't seem to fix this for me.
