### ISSUE TITLE
GVerb glitch

### ISSUE THREAD

**Issue by nhthn** [supercollider/supercollider#2302]
from https://github.com/supercollider/sc3-plugins/issues/49:

```
// sounds normal
{GVerb.ar(Dust.ar(5), SinOsc.kr(0.3, 0.5pi).range(10, 14), drylevel:0)}.play

// super loud glitch!
{GVerb.ar(Dust.ar(5), SinOsc.kr(0.3).range(10, 14), drylevel:0)}.play
```

**Comment by snappizz** [comment]
Problems with modulating roomsize are well-known. `SinOsc.kr(0.3, 0.5pi)` starts at 14 and decreases, while `SinOsc.kr(0.3)` starts at 12 and increases. GVerb is allocating memory according to the initial value.
