### ISSUE TITLE
Usage of Class.initClassTree(ControlSpec) can remove common mappings

### ISSUE THREAD

**Issue by antonhornquist** [supercollider/supercollider#2318]
I used this in the *initClass of a custom class:
```
Class.initClassTree(ControlSpec)
```

Afterwards I could note that the common mappings (\unipolar, \bipolar, \freq, etc) defined in ControlSpec.initClass were not available anymore when I compiled the class in 3.7.2. In 3.6.6 they still showed up.

I'm quite sure this is due to the fact that ```Spec.initClass``` is not invoked prior to ```ControlSpec.initClass``` so the common mappings are overwritten after they have been added, in the cases when Spec is inited after ControlSpec.

I think simply adding ```Class.initClassTree(Spec)``` to the top of ```ControlSpec.initClass``` would fix this problem.

**Comment by crucialfelix** [comment]
If your custom class requires those specs then it should call
initClassTree(ControlSpec)

There is no guarantee what exact order classes are initialized. That's why
initClassTree allows you to ensure a class is initialized. When you add new
classes then the order may change.

So the problem is not because controlspec or spec isn't doing something,
it's that you need them initialized so you need to request that they are
initialized before you use them.

Does that explain it ?

**Comment by antonhornquist** [comment]
Sorry if I was unclear. I *am* using Class.initClassTree(ControlSpec) in my custom class. It causes common mappings to disappear. 

Since ControlSpec.initClass does not invoke Class.initClassTree(Spec) the common specs are overwritten when Spec.initClass - by the core SuperCollider init functionality - is invoked after ControlSpec.initClass. In my 3.7.2 SC this is the case. In 3.6.6 it's not the case. 

This is a bug. The dictionary in Spec.initClass must be created before ControlSpec fills it. I can fix this in my app by initing Spec before ControlSpec explicitly myself, but I think this should be fixed in core lib.  I propose to include Class.initClassTree(Spec) in ControlSpec.initClass. 

I can create a pull request for this oneliner.

**Comment by antonhornquist** [comment]
Please also note that I revised the initial issue report just after posting it, it included a mixup of ControlSpec and Spec. It is probably clear if you reread it.

**Comment by crucialfelix** [comment]
OK, I see what you mean now.

nB: yes I noticed your error (that you later edited). If you actually did call Class.initClassTree(ControlSpec) it might cause the app to crash because it keeps calling it again and again. Hopefully it flags it as already-inited before calling.

**Comment by jamshark70** [comment]
> Hopefully it flags it as already-inited before calling.

It does -- see the usage of `classesInited` in `initClassTree`.

**Comment by crucialfelix** [comment]
Yes, I know I wrote it. I'm just wondering (while on my telephone, out and
about wandering the earth) if I did actually do it right.
