### ISSUE TITLE
Inconsistent initial state of Delay2

### ISSUE THREAD

**Issue by Sciss** [supercollider/supercollider#2322]
Compare:
- `Delay1:` first two samples output are identical, i.e. initial state
      is same as first input sample
- `Delay2:` first sample is zero. second sample is same as first input
      sample.
- `DelayN(x, SampleDur.ir, SampleDur.ir)`: first sample is zero
- `DelayN(x, 2 * SampleDur.ir, 2 * SampleDur.ir)`: first two samples are zero

While there are good arguments to let `Delay1` repeat the first input sample, clearly `Delay2` does not do anything coherent by outputting zero followed by a duplicate of the first input sample. It should either output the first input sample three times, or it should output two frames of zero, followed by the first input sample.

**Comment by snappizz** [comment]
Ack. Yet another case of sloppy ugen writing. Fixing it is yet another API change.

Zeros makes the most sense to me. A fairly standard definition in DSP theory is that an audio signal `x[t]` is defined for `t >= 0`, and for all negative times we set `x[t] = 0`. A delayed version of the signal `x'` would be defined as `x'[t] = x[t - delay]`, which would put zeros at the beginning of the delayed signal. I would propose making both `Delay1` and `Delay2` work this way.

**Comment by snappizz** [comment]
Actually -- using zeros for Delay1 and Delay2 may be the wrong idea, because one of the most common use cases for these ugens is to recreate low-order FIR filters like LPZ/HPZ. dang.

**Comment by snappizz** [comment]
My recent tribulations with Ctor functions revealed something important that is relevant to this bug -- Delay1 is not repeating the first sample.

A single-channel audio signal can be characterized as a discrete function `x[t]` of time `t >= 0`. But SuperCollider signals inside SynthDefs have an extra sample that gets propagated through the Ctor functions, which you can consider to be `x[-1]`. Most ugens will have `x[-1] = x[0]`, which is how it should be. Some do not.

**Comment by danstowell** [comment]
You asked for "mathematical" comment. Mathematically behaviour at t<0 is undefined so we have no guidance, and I don't think we have any original spec to guide us. I'd suggest that the most sensible consistent interpretation for these delays is to assume zeros in the past (since under the other alternative the initial sample is putting an unbounded amount of energy into the system). As you say, there are consequences to making this choice. I don't know.

**Comment by mtmccrea** [comment]
> since under the other alternative the initial sample is putting an unbounded amount of energy into the system

Yes, you can think of repeated first samples as inserting DC into the signal, which isn't in any definition of delay that I can think of, and which has an impact on the initial state of some filters. `RLPF` which has a "warm up" time will receive more initial energy than is actually in the (pre-delayed)  input signal, changing the impulse response of its initial output.

> Actually -- using zeros for Delay1 and Delay2 may be the wrong idea, because one of the most common use cases for these ugens is to recreate low-order FIR filters like LPZ/HPZ. dang.

This seems like a separate issue: it's up to the the one designing the LPZ/HPZ to do decide what that filter's input is at x(-1,-2) and shouldn't impact the definition of another UGen. SC's `LPZ1` UGen happens to assume the `x(-1) == x(0)`, which tbh I'm not sure about either:
https://github.com/supercollider/supercollider/blob/f65a1ef7bfb100f4ccb7dcab3a6dff6826be4344/server/plugins/FilterUGens.cpp#L1824-L1830

It would be great if someone could point to a reference describing the logic for making these negative-time samples anything other than `0`. I'll keep an eye out.

And in the most intuitive case, I think about a simple (buffered) delay line being filled with `0`s, silence, until a signal shows up, which for all we know only happens at x(0).

So anyway my vote is for `0`s.

A related bug:
`Delay2_Ctor` doesn't initialize `m_x2`, which is x(-2):
https://github.com/supercollider/supercollider/blob/f65a1ef7bfb100f4ccb7dcab3a6dff6826be4344/server/plugins/FilterUGens.cpp#L2032-L2037

So it outputs garbage for it's first sample 😕
```supercollider
// run each of these in order, observe the output
{LFSaw.ar(500, 0.5, 0, mul: 0.8)}.loadToFloatArray((10 / s.sampleRate), action: {|arr| arr.postln});
{Delay1.ar(LFSaw.ar(500, 0.5, mul: 0.8))}.loadToFloatArray((10 / s.sampleRate), action: {|arr| arr.postln});
{Delay2.ar(LFSaw.ar(500, 0.5, mul: 0.8))}.loadToFloatArray((10 / s.sampleRate), action: {|arr| arr.postln});
// garbage (random?) y(0)!

// the following line is identical to the previous
{Delay2.ar(LFSaw.ar(500, 0.5, mul: 0.8))}.loadToFloatArray((10 / s.sampleRate), action: {|arr| arr.postln});
// DIFFERENT (random?) y(0)!

// though that value is consistent after this point (unless you start from the top)
{Delay2.ar(LFSaw.ar(500, 0.5, mul: 0.8))}.loadToFloatArray((10 / s.sampleRate), action: {|arr| arr.postln});
```

**Comment by mtmccrea** [comment]
Note also in the above `Delay2_Ctor` that `ZOUT0(0) = 0.f;` So the author is assuming an initial state of `0`! (for one sample anyway...but in fact this initial sample isn't actually output because of improper UGen initialization 🙄, which is [rampant](https://github.com/supercollider/supercollider/issues/4127) throughout the core ugens).

**Comment by mtmccrea** [comment]
Some further insight regarding what the first values output by Delay UGens should be. 

1. The more I've looked into UGen `Ctors` and the many many initialization bugs, I would say most come down to the assumption that _x(-1)_ can be set to _x(0)_ for the purpose of initialization. I'm more and more convinced this is a bad assumption.

2. I recently came across this in the SC book, at the end of Ch. 26, "Inside scsynth":
> Delay lines typically output zeros until the delay time reaches the first input sample. One way to handle this is to zero the internal delay storage when the delay is created or reset. The delay unit generators in scsynth (see `DelayUGens.cpp`) avoid this time-consuming (and hence real-time unsafe) operation by using a separate UnitCalcFunc during the startup phase. For example, `BufDelayN_next_z()`􏰆􏰋 outputs zeros for the first `bufSamples` samples, at which point the `UnitCalcFunc` is switched to `BufDelayN_next()`􏰆􏰋, which outputs the usual delayed samples.

So there's further evidence in baked into scsynth's efficiency strategies the that Delay UGens should output zeros until the delay time has elapsed, at which point it should output the input signal.
