### ISSUE TITLE
Can't compile SC 3.7.2 on recent Arch Linux

### ISSUE THREAD

**Issue by jmaibaum** [supercollider/supercollider#2332]
I'm trying to build SuperCollider 3.7.2 from the source tarball on Archlinux (their official package for SC stuck at 3.6.6 for months, perhaps for a reason?). I am aware of #2204 but this seems to be unrelated, as the error messages are pointing towards boost.

Relevant versions on my system:
- GCC 6.2.1 (I'm trying to get around this for a while, I got the same error when GCC 6.1.1 was still around)
- boost 1.61.0 (was the same while I was still on 1.60.x)
- Qt 5.7.0

`make` fails on building the file `lang/CMakeFiles/libsclang.dir/LangPrimSource/PyrMathPrim.cpp.o` with 3094 error messages like the following (all 3093 other errors are similar):

```
[ 43%] Building CXX object lang/CMakeFiles/libsclang.dir/LangPrimSource/PyrMathPrim.cpp.o
...
<cut out ~70,800 lines of similar error messages>
...
/usr/include/boost/math/special_functions/trigamma.hpp:325:7: error: unable to find numeric literal operator 'operator""Q'
   BOOST_MATH_BIG_CONSTANT(T, 113, 2.53795636200649908779512969030363442),
   ^
/usr/include/boost/math/special_functions/trigamma.hpp:325:7: note: use -std=gnu++11 or -fext-numeric-literals to enable more built-in suffixes
make[2]: *** [lang/CMakeFiles/libsclang.dir/build.make:331: lang/CMakeFiles/libsclang.dir/LangPrimSource/PyrMathPrim.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:3525: lang/CMakeFiles/libsclang.dir/all] Error 2
make: *** [Makefile:161: all] Error 2
```

(The log file only for that portion is 6.7MB in size. If anyone really needs the whole file, I will put it somewhere for you to download.)

I tried it with and without `-DSYSTEM_BOOST=ON`, but I get the same error in both cases.

I'm not at all familiar with boost, should I follow the note and try building with `-std=gnu++11` and/or `-fext-numeric-literals`?

**Comment by Magicking** [comment]
Using this https://aur.archlinux.org/packages/supercollider-git/ at commit https://github.com/supercollider/supercollider/commit/476fbc94c07dbb14aca72bd762177919e4210e24 is compiling fine on my Arch Setup.
Packages version:
GCC: 6.1.1
Boost: 1.60.0
Qt: 5.7.0

**Comment by jmaibaum** [comment]
I can confirm now that building the `supercollider-git` formula from AUR works. I then tried to build the 3.7.2 release with the same build configuration as in the AUR formula, but it still fails with the same error as above. So this is an issue explicitly with the 3.7.2 release version.

**Comment by shimpe** [comment]
I just compiled  f5d8917dbafe3c2f96ff6d774c72da0e0de0ab87 (latest git revision in master) on Arch with gcc 6.2.1 and qt 5.7 with no apparent issues (apart from having to remove an SC_VIM section from editors/CMakeLists.txt)

**Comment by jmaibaum** [comment]
Yes, as I've said in my previous comment: When building the latest git revision in master, there is no issue. But when trying to build the current stable release tarball (aka version 3.7.2, from the official download page on supercollider.github.io) it fails. So any change in master between 3.7.2 and current HEAD seems to have resolved this issue. Unfortunately, I don't have time atm to bisect.

**Comment by shimpe** [comment]
Ok, sorry I had misinterpreted your previous comment.

**Comment by vivid-synth** [comment]
@jmaibaum now that 3.8 is out does the current stable release tarball work for you? (from http://supercollider.github.io/download )

**Comment by jmaibaum** [comment]
Yes, the issue is gone with the 3.8.0 tarball. I think this issue can be closed.

Just for reference, I just checked with the Arch Linux `PKGBUILD` scripts where they eventually had also put out a version 3.7.2 package. Apparently they had success building that version by adding `-DCMAKE_CXX_FLAGS="$CXXFLAGS -DBOOST_MATH_DISABLE_FLOAT128"` to the cmake configuration. I did not verify this, though.

**Comment by telephon** [comment]
thanks for reporting!
