### ISSUE TITLE
Help files: spaces in some links are rendered with %20 

### ISSUE THREAD

**Issue by crucialfelix** [supercollider/supercollider#2337]
This:

```
(See: link::#NodeProxy elastic behavior setting::)
```

renders as:

```
(See: NodeProxy%20elastic%20behavior%20setting)
```

Source is at:

```
 HelpSource/Other/JITLibChanges3.7.schelp
```

The link is correctly escaped and is clickable but the visible text should not have been escaped.

This happens when there is only an anchor.  `#NodeProxy elastic behavior setting` The link is to something on the current page.

**Comment by jamshark70** [comment]
It happens for all links: haven't pushed yet but I'm working on one: `link::Classes/Ringz#Interaction with sample rate::` which renders as "Ringz: Interaction%20with%20sample%20rate"

**Comment by brianlheim** [comment]
I'm pretty sure the solution is as simple as having `SCDocHTMLRenderer::escapeSpacesInAnchor`, shown below, return the original string unchanged.

```supercollider
*escapeSpacesInAnchor { |str|
	^str.replace(" ", "%20") // reduce to ^str?
}
```

**Comment by brianlheim** [comment]
(Of course we'd just eliminate the method altogether.)

I did a couple tests with that change; links work, and I don't see any `%20` in link names.

**Comment by brianlheim** [comment]
Gah, never mind, I found the trail back to why this method was introduced. I will keep looking for a solution.

**Comment by brianlheim** [comment]
problem is somewhere in `SCDocHTMLRenderer:*htmlForLink`

**Comment by enedrio** [comment]
I just replaced the %20 with spaces where the label for "in same document"-links is created.

Then line 97 in SCDocRenderer.sc says:
`f = if(m.size>0) {m.replace("%20", " ")} {"(empty link)"};`

It seems to work.
It's a stupid hack, though. :-\

**Comment by brianlheim** [comment]
I am working on a fix here: https://github.com/brianlheim/supercollider/tree/issue/2337
Comparison: https://github.com/supercollider/supercollider/compare/master...brianlheim:issue/2337

I found myself having to rewrite the method because it is so full of cramped notation and single-letter variables. Hopefully the comments help to explain what is going on.

**Comment by brianlheim** [comment]
#3033.

**Comment by enedrio** [comment]
Thanks! You improved the readability of the code a lot. 👍 good work
