### ISSUE TITLE
scide: sc:doc: find textfield double triggers

### ISSUE THREAD

**Issue by redFrik** [supercollider/supercollider#2344]
using osx with sc3.7.2 the scdoc help system's find feature only matches every second item.

to see it in action open a helpfile (SinOsc)
in the upper right corner search for something (freq)
press return on your keyboard to find the first item.
press return again and i skips over one 'freq' in the help file.

**Comment by telephon** [comment]
While you type it already tries to find, so you can see that it starts highlighting the first one. Then, when you hit enter, it goes to the next. You can see that clearer, in your example, when you search "complex", it's further down.

So a fix would be to switch off the "life" searching, but again this might be useful. The highlight color here is grey, which is rather cautious.

**Comment by redFrik** [comment]
thanks @telephon - i didn't spot that 'life' feature.  still, how to step through results?  when i press return i expect it to jump to the next - not skipping over.  makes no sense to me.  compare how it works in for example Atom or Safari - life search without skip.
i clam this is a bug.

**Comment by telephon** [comment]
Hm, in Firefox, if I hit cmd-f, then type, it jumps to the word I searched. If I hit enter it jumps to the next. Is that what you expect or does that count as skipping?

**Comment by brianlheim** [comment]
Can confirm that this is an issue for me as well on macOS 10.11 / SC 3.9dev. When I press enter, the finder very quickly steps through one match and then immediately to the next one. This can easily be seen by opening up a file like Object.schelp and searching for a single letter like `a`.
