### ISSUE TITLE
OffsetOut glitches

### ISSUE THREAD

**Issue by telephon** [supercollider/supercollider#2347]
Routing a signal that is written by an `OffsetOut` through an `InFeedback` causes glitches. This is severe, because internally, this combination is of very common usage.

```

(
SynthDef(\pulsar, { |out=0, pan=0.0, amp=0.2, sustain=0.1, overlap=0.03|
    var signal = SinOsc.ar(200) * EnvGen.ar(Env.sine(sustain * overlap),
doneAction:2);
    OffsetOut.ar(out, Pan2.ar(signal, pan));
}).add;
)


(
b = Bus.audio(s, 2);
{ InFeedback.ar(b, 2) }.play;


Pbind(
    \instrument, \pulsar,
    \dur, Pgeom(0.01, 1.01),
    \out, b
).play;
)



// replacing the synth def with one that uses Out makes the glitch disappear:
(
SynthDef(\pulsar, { |out=0, pan=0.0, amp=0.2, sustain=0.1, overlap=0.03|
    var signal = SinOsc.ar(200) * EnvGen.ar(Env.sine(sustain * overlap),
doneAction:2);
    Out.ar(out, Pan2.ar(signal, pan));
}).add
)

```

**Comment by telephon** [comment]
It could be related to this:

eccaf796b57ff554f2cb0dd8c516fbfc72d7826e

But I can't check out the branch before the change somehow to test it.

**Comment by telephon** [comment]
@timblechmann can you reproduce this with supernova?

**Comment by telephon** [comment]
I've simplified the above example a bit, and it seems that the glitches happen in both cases, but look differently:

```
(
SynthDef(\pulsar, { |out=0, amp=0.2, sustain=0.1|
	var signal;
	signal = SinOsc.ar(200) * EnvGen.ar(Env.sine(sustain), doneAction:2);
	OffsetOut.ar(out, signal);
}).add;
)


(
b = Bus.audio(s, 2);
{ InFeedback.ar(b, 2) }.play;


Pbind(
	\instrument, \pulsar,
	\dur, Pgeom(0.00003, 1.01),
	\out, b
).play;
)



// replacing the synth def with one that uses Out makes the glitch disappear:
(
SynthDef(\pulsar, { |out=0, amp=0.2, sustain=0.1|
	var signal;
	signal = SinOsc.ar(200) * EnvGen.ar(Env.sine(sustain), doneAction:2);
	Out.ar(out, signal);
}).add;
)
```

**Comment by snappizz** [comment]
Here is a shorter example demonstrating what's happening:

    { Line.ar(0, 1, 0.01) }.plot(0.02);

    b = Bus.audio(s, 1);
    (
    { OffsetOut.ar(b, Line.ar(0, 1, 0.01)); }.play;
    { InFeedback.ar(b); }.plot(0.02);
    )

It looks like one control period is getting removed from the beginning of the output, causing glitches.

**Comment by telephon** [comment]
fixed.
