### ISSUE TITLE
nonexisting commit in submodule external_libraries/hidapi referenced?

### ISSUE THREAD

**Issue by shimpe** [supercollider/supercollider#2357]
When doing: 

git update submodules --recursive

I get the following error message:

Fetched in submodule path 'external_libraries/hidapi', but it did not contain 4112eae29ab751337dc4170da8fd3f1f365c564d. Direct fetching of that commit failed.

**Comment by crucialfelix** [comment]
Git submodule sync

Fixes it.

**Comment by shimpe** [comment]
Thanks. I learned something today!
