### ISSUE TITLE
LocalIn can have garbled initial input

### ISSUE THREAD

**Issue by Sciss** [supercollider/supercollider#2363]
I'm opening this issue, although I don't have a simple self-contained example to reproduce (I have a ScalaCollider patch now that when instantiating the same synth for long enough, shows the problem).

The symptoms are this:
- at some point, running the same synth, using `play {}`, i.e. each time with a freshly sent `SynthDef`, the initial contents of `LocalIn.kr(8)` are not zero as expected.
- once this happens, you can stop and play over and over again, and the contents remains exactly the same (e.g. a number of values around ` -6.51138e-27`). 
- but then, if you start _a second_ synth, with the identical synth-def code, it has again the correctly zero'ed content.

This leads me to believe that the problem is that some portion of memory is used again and again in the first case, and somewhere there is a missing initial clear of the allocated memory.

Here is the link to the Ctor of LocalIn, although I cannot see any mistake: https://github.com/supercollider/supercollider/blob/f7464ac463b02add1fe490ac3785e8dc222502e7/server/plugins/IOUGens.cpp#L1562

**Comment by Sciss** [comment]
Ok, next step -- a reproducible code:

```scala
def mkSynths() = Seq.fill(8)(play {
  val numVoices   = 4

  val stateIn     = LocalIn.kr(numVoices * 2)
  var voiceFreq   = Vector.tabulate(numVoices)(i => stateIn \ i): GE
  var voiceOnOff  = Vector.tabulate(numVoices)(i => stateIn \ (i + numVoices)): GE
  val voiceNos    = (0 until numVoices): GE
  
  val trPoll      = "poll".tr
  
  var activated   = Vector.fill(numVoices)(0: GE): GE
  
  for (vIdx <- 0 until numVoices) {
    (voiceFreq \ vIdx).poll(trPoll, s"fr-in [$vIdx]")
  }
  
  voiceOnOff = activated  // release unused voices
  val stateOut = Flatten(voiceFreq ++ voiceOnOff)
  LocalOut.kr(stateOut)
})

// execute the following line-by-line
val xs = mkSynths()
xs.foreach(_.set("poll" -> 1))
xs.foreach(_.free())
val ys = mkSynths()
ys.foreach(_.set("poll" -> 1))  // some garbled contents
```

I will try to translate this into sclang.

**Comment by Sciss** [comment]
Well. I found the origin of this.

https://github.com/supercollider/supercollider/commit/58279623b3045debfc16197d3c51435e5a1f56e6

This lovely kind of API breaking I have been talking about multiple times. Stuff like this goes under the radar for any kind of third-party client. I sucks big time, really.

sclang equivalent:

```supercollider
~mkSynths = { Array.fill(4, { play {
	var numVoices, numVoicesM, stateIn, voiceFreq, voiceOnOff, trPoll, activated, stateOut;
	numVoices   = 2;
	stateIn     = LocalIn.kr(numVoices * 2);
	numVoicesM =	(0..(numVoices - 1));
	voiceFreq   = numVoicesM.collect { |i| stateIn[i] };
	voiceOnOff  =  numVoicesM.collect { |i| stateIn[i + numVoices] };
	trPoll      = \poll.tr;
	activated   = 0 ! numVoices;

	numVoicesM.do { |i|
		voiceFreq[i].poll(trPoll, i.asString);
	};

	voiceOnOff = activated;
	stateOut = voiceFreq ++ voiceOnOff;
	LocalOut.kr(stateOut);
}})};

~xs = ~mkSynths.();
~xs.do { |x| x.set(\poll, 1) };
~xs.do { |x| x.free() };
~ys = ~mkSynths.();
~ys.do { |x| x.set(\poll, 1) };   // ?
~ys.do { |x| x.free() };
```

Scala UGen graph:

![scala](https://cloud.githubusercontent.com/assets/131300/18913169/a5a65c54-8586-11e6-9e85-dd93cefc0ad7.png)

sclang UGen graph:

![sclang](https://cloud.githubusercontent.com/assets/131300/18913179/ad77a55a-8586-11e6-8fef-24e52f8962f4.png)

Find the difference...

**Comment by snappizz** [comment]
A ugen metadata system, as proposed in #2300, would have caught this kind of discrepancy very quickly. This problem could also have been prevented with a louder advertisement of API changes, but I'm not entirely sure what this would entail.

**Comment by Sciss** [comment]
One thing that could be investigated - I don't know if this is feasible - is the server behaviour. Because this is not the first time the number of UGen arguments changes (I don't remember the other case, but there was one, very long ago). The problem would be immediately visible if the server complained if a synth-def tries to instantiate a UGen with the wrong number of inputs. Wouldn't that be a simple check?

**Comment by telephon** [comment]
@Sciss nowadays, we tag API changes in github and you can read them in the change log. 

But you are right that it would be convenient to be able to document such changes automatically, given that they should be rare, it may not be worth the effort. One could add a unit test relatively easily though.

Nevertheless: It should be possible to add arguments to a UGen, and in some case even change them. This has always happened in the past (maybe you remember the change in Klank, which led to the addition of Old_Klank?).

**Comment by Sciss** [comment]
@telephon If one adds a UGen argument and there is a sensible default, couldn't the server fill that in if it sees that the number of arguments declared is too small? At least it could warn that there is a mismatch.

**Comment by telephon** [comment]
This would be nice, and safer indeed. 

But the server doesn't know the number of inputs of a UGen. The only place where it is defined is in the sclang UGen definition, which *should* match the implementation in the plugin.

As you know too well, there are many places in sc where there is no safety net, it is just assumed that you look at the code.

**Comment by crucialfelix** [comment]
We need a dump to JSON of each UGEN and it's args.  That would make changes
between releases easily monitorable

**Comment by telephon** [comment]
something like: `UGen.allSubclasses.collect { |each| each.class.findMethod(\ar).argNames }` and then to json .. ?

**Comment by crucialfelix** [comment]
Much more than that data for each one but that is the general idea.  We
need it for generating UGEN classes in andere Sprache

**Comment by Sciss** [comment]
As you might know, I have this: https://github.com/Sciss/ScalaColliderUGens/tree/master/spec/src/main/resources/de/sciss/synth/ugen

Whether this is XML or JSON doesn't matter much. The problem will be that sclang/ScalaCollider will have different requirements and preferences for the meta data, the style and focus of the documentation, etc. Perhaps a common denominator can be found that would be usable by multiple languages. Every other client, Clojure, Lua, Haskell, ... is basically maintaining a similar meta data file.
