### ISSUE TITLE
sc3-plugins and sourceforge

### ISSUE THREAD

**Issue by snappizz** [supercollider/supercollider#2369]
The [sourceforge website](http://sc3-plugins.sourceforge.net/) is still up and the [project page](https://sourceforge.net/projects/sc3-plugins/) doesn't have any link to the github repo. Anyone want to fix?

**Comment by danstowell** [comment]
Thanks, fixed in https://github.com/supercollider/sc3-plugins/commit/fb7f4cc0a577b9ec219870390a19bbc43fa2c3cc

(Would be better as an issue on the sc3-plugins project BTW)
