### ISSUE TITLE
EnvirGui calls `this.widgets` but has none

### ISSUE THREAD

**Issue by telephon** [supercollider/supercollider#2371]
There is no instance variable `widgets` anywhere, but it is called by two methods:

- `EnvirGui.updateSliderSpecs`
- `NdefParamGui.updateSliderSpecs`

e.g.:
```
updateSliderSpecs { |editKeys|
		var currState;

		if (object.isNil) { specs.clear; ^this };

		currState = object.getKeysValues;

		editKeys.do { |key, i|
			var currValue = currState.detect { |pair| pair[0] == key }[1];
			var newSpec = this.getSpec(key, currValue);
			var widge = this.widgets[i];
			if (newSpec != specs[key]) {
				specs.put(key, newSpec);
				if (widge.isKindOf(EZSlider) or:
					{ widge.isKindOf(EZRanger) }) {
					widge.controlSpec = newSpec;
					widge.value_(currValue);
				};
			};
		}
	}
```

It throws the error:

```
ERROR: Message 'widgets' not understood.
RECEIVER:
Instance of NdefParamGui {    (0x11d09aaf8, gc=CC, fmt=00, flg=00, set=05)
```

**Comment by jamshark70** [comment]
https://github.com/supercollider/supercollider/commit/62a8dd1d2b898dc7be970dfc7fcfe7e19c7ea054

But https://github.com/supercollider/supercollider/commit/f8b56a3e55d85d75d7c6058744b10415ad14ee95 appears to have removed references to `widgets` from the main class library... are you sure the currently-offending methods are defined in the class library, and not in the JITLibExtensions quark? I reported the JITLibExtensions bug probably, oh, a year ago, still unfixed.

**Comment by crucialfelix** [comment]
Doesn't look updateSliderSpecs is in the main library at all: https://github.com/supercollider/supercollider/search?utf8=%E2%9C%93&q=updateSliderSpecs&type=Code

**Comment by telephon** [comment]
Oh dear, yes. This should go to the JITLibExtensions, sorry for the noise.

**Comment by telephon** [comment]
Part of the problem seems to be that issues reported on Quarks don't show up in the notifications.

**Comment by jamshark70** [comment]
> Part of the problem seems to be that issues reported on Quarks don't show up in the notifications.

I'd vote for notifications going to quark authors, but let's not send all notices to the dev list for every quark everywhere.
