### ISSUE TITLE
Deprecations for 3.9

### ISSUE THREAD

**Issue by crucialfelix** [supercollider/supercollider#2372]
I didn't create a `deprecated/3.8` folder previously, and there are a lot of deprecated methods now throughout the library.

Proposal: deprecate all those for 3.9 (moving them into `deprecated/3.9`) and then remove then in the 3.10 release.

3.8 came quickly after 3.7 (even with the extra 3 months)

There are 6 methods currently scheduled for removal in 3.9; we can remove them from master now.

RFC

**Comment by crucialfelix** [comment]
supercollider ❯ ag deprecated SCClassLibrary/**/*.sc
SCClassLibrary/Common/Audio/InOut.sc
299:		warn("SharedOut is deprecated and will be removed. Please use Bus-getSynchronous instead.");
309:		warn("SharedIn is deprecated and will be removed. Please use Bus-setSynchronous instead.");

SCClassLibrary/Common/Audio/InterplEnv.sc
8:		"InterplEnv is deprecated, please use Env.new instead.".warn;
20:		"InterplXYC is deprecated, please use Env.xyc instead.".warn;
28:		"InterplPairs is deprecated, please use Env.pairs instead.".warn;
36:		"InterplChord is deprecated, please use Env.pairs instead.".warn;

SCClassLibrary/Common/Audio/Splay.sc
72:		"SplayZ is deprecated, because its geometry is wrong.

SCClassLibrary/Common/Audio/SynthDef.sc
680://		this.deprecated(thisMethod, Function.findRespondingMethodFor(\play));

SCClassLibrary/Common/Core/Error.sc
211:DeprecatedError : MethodError {
256:		string = "WARNING: Called from %, method % is deprecated and will be removed.".format(
287:		^"DeprecatedError"

SCClassLibrary/Common/Core/Object.sc
315:	deprecated { arg method, alternateMethod;
316:		DeprecatedError(this, method, alternateMethod, this.class).throw;

SCClassLibrary/Common/Files/PathName.sc
252:	// deprecated messages
254:	*fromOS9 { | path | ^this.deprecated(thisMethod) }
255:	foldersWithoutCVS { | path | ^this.deprecated(thisMethod) }
256:	isCVS { ^this.deprecated(thisMethod) }
257:	foldersWithoutSVN { | path |^this.deprecated(thisMethod) }
258:	isSVN { ^this.deprecated(thisMethod) }
259:	filesDoNoCVS { | func | ^this.deprecated(thisMethod) }
260:	filesDoNoSVN { | func | ^this.deprecated(thisMethod) }
261:	streamTreeNoCVS { | str, tabs=0 | ^this.deprecated(thisMethod) }
262:	helpFilesDo { |func| ^this.deprecated(thisMethod) }

SCClassLibrary/Common/GUI/backwardsCompatibility/classNameRedirects.sc
79:		this.deprecated(thisMethod, this.class.findRespondingMethodFor('drawFunc_'));
87:		this.deprecated(thisMethod, this.class.findRespondingMethodFor('drawFunc_'));

SCClassLibrary/Common/GUI/backwardsCompatibility/deprecated-3.7.sc
4:		this.deprecated(thisMethod, this.class.findMethod(\openPanel));

SCClassLibrary/Common/GUI/iphone/Base/GUIScreen.sc
164:		this.deprecated(thisMethod, this.class.findMethod(\drawFunc));
168:		this.deprecated(thisMethod, this.class.findMethod(\drawFunc_));

SCClassLibrary/Common/GUI/iphone/Base/SCView.sc
958:		this.deprecated(thisMethod, SCView.findMethod(\background));
962:		this.deprecated(thisMethod, SCView.findMethod(\background_));

SCClassLibrary/Common/Math/Signal.sc
331:		//this.deprecated(thisMethod, Buffer.findRespondingMethodFor(\cheby));

SCClassLibrary/JITLib/ProxySpace/InBus.sc
354:		this.deprecated(thisMethod);
357:		this.deprecated(thisMethod);

SCClassLibrary/JITLib/ProxySpace/NodeMap.sc
86:		^this.deprecated(thisMethod, this.class.findRespondingMethodFor(\set))
90:		^this.deprecated(thisMethod, this.class.findRespondingMethodFor(\set))
94:		^this.deprecated(thisMethod, this.class.findRespondingMethodFor(\set))
183:		//this.deprecated(thisMethod); // maybe deprecate later
193:		this.deprecated(thisMethod);

SCClassLibrary/JITLib/ProxySpace/NodeProxy.sc
259:		this.deprecated(thisMethod);
325:		"NodeProxy: mapn is deprecated, please use map instead".postln;

SCClassLibrary/Platform/Platform.sc
81:	*deprecatedStartupFiles {|paths|
85:				warn("Deprecated startup file found: %\n".format(path));
90:			postln("Please use % as startup file.\nDeprecated startup files will be ignored in future versions.\n".format(defaultStartupFile));

SCClassLibrary/Platform/iphone/iPhonePlatform.sc
10:		var deprecated = [this.systemAppSupportDir +/+ filename, this.userAppSupportDir +/+ filename];
11:		Platform.deprecatedStartupFiles(deprecated);
12:		^(deprecated ++ super.startupFiles)

SCClassLibrary/Platform/linux/LinuxPlatform.sc
4:		var deprecated = #["~/.sclang.sc"];
5:		Platform.deprecatedStartupFiles(deprecated);
6:		^(deprecated ++ super.startupFiles)

SCClassLibrary/Platform/osx/OSXPlatform.sc
15:		var deprecated = [this.systemAppSupportDir +/+ filename, this.userAppSupportDir +/+ filename];
16:		Platform.deprecatedStartupFiles(deprecated);
17:		^(deprecated ++ super.startupFiles)

SCClassLibrary/Platform/windows/WindowsPlatform.sc
4:		var deprecated = ["startup.sc", "~\\SuperCollider\\startup.sc".standardizePath];
5:		Platform.deprecatedStartupFiles(deprecated);
6:		^(deprecated ++ super.startupFiles)

SCClassLibrary/SCDoc/Help.sc
2:	// These classvars and vars are part of the deprecated Help.tree stuff. When that stuff is removed from the classlib, this can be removed too.

SCClassLibrary/scide_scqt/ScIDE.sc
858:		this.deprecated(thisMethod, Document.findMethod(\title));
863:		this.deprecated(thisMethod, Document.findMethod(\title_));

**Comment by snappizz** [comment]
we are down to:

```
scide_scqt/ScIDE.sc
869:        this.deprecated(thisMethod, Document.findMethod(\title));
874:        this.deprecated(thisMethod, Document.findMethod(\title_));

Platform/windows/WindowsPlatform.sc
4:      var deprecated = ["startup.sc", "~\\SuperCollider\\startup.sc".standardizePath];
5:      Platform.deprecatedStartupFiles(deprecated);
6:      ^(deprecated ++ super.startupFiles)

Platform/osx/OSXPlatform.sc
15:     var deprecated = [this.systemAppSupportDir +/+ filename, this.userAppSupportDir +/+ filename];
16:     Platform.deprecatedStartupFiles(deprecated);
17:     ^(deprecated ++ super.startupFiles)

Platform/linux/LinuxPlatform.sc
4:      var deprecated = #["~/.sclang.sc"];
5:      Platform.deprecatedStartupFiles(deprecated);
6:      ^(deprecated ++ super.startupFiles)

Common/GUI/backwardsCompatibility/classNameRedirects.sc
79:     this.deprecated(thisMethod, this.class.findRespondingMethodFor('drawFunc_'));
87:     this.deprecated(thisMethod, this.class.findRespondingMethodFor('drawFunc_'));

Common/GUI/backwardsCompatibility/deprecated-3.7.sc
4:      this.deprecated(thisMethod, this.class.findMethod(\openPanel));

Common/GUI/iphone/Base/GUIScreen.sc
164:        this.deprecated(thisMethod, this.class.findMethod(\drawFunc));
168:        this.deprecated(thisMethod, this.class.findMethod(\drawFunc_));

Common/GUI/iphone/Base/SCView.sc
958:        this.deprecated(thisMethod, SCView.findMethod(\background));
962:        this.deprecated(thisMethod, SCView.findMethod(\background_));
```

**Comment by snappizz** [comment]
these are pretty much taken care of
