### ISSUE TITLE
String:replace change in behaviour in 3.8

### ISSUE THREAD

**Issue by muellmusik** [supercollider/supercollider#2383]
```
"--f".replace("--");
->nilf
```

In 3.7 it was

```
->f
```

Is this intentional or a bug?

**Comment by jamshark70** [comment]
Ironically enough, it's your commit -- https://github.com/supercollider/supercollider/commit/66ff6ea708bad5802b640b46f64f8fd70d80d926

The new implementation is reasonable -- the lack of a proper default for the 'replace' arg is not. I'd fix it like so:

```
replace { arg find, replace = ("");
```

**Comment by muellmusik** [comment]
Ha! I knew it was some irresponsible fool!

That seems reasonable to me! Any objections!

**Comment by vivid-synth** [comment]
lgtm. Probably worth adding a unit test for the case where there's no replace arg
