### ISSUE TITLE
Ndef gui loses drag sink

### ISSUE THREAD

**Issue by muellmusik** [supercollider/supercollider#2384]
```
Ndef(\test, {
	\in.ar([0, 0])
})

Ndef(\test).gui
```
<img width="394" alt="untitled" src="https://cloud.githubusercontent.com/assets/1315053/19196407/54a071c2-8cad-11e6-848d-51fad78b2590.png">
I can't drag another input to that slider.

This has also been a bit off at various points throughout the 3.8 cycle.

**Comment by telephon** [comment]
@adcxyz what do you think?

**Comment by adcxyz** [comment]
my mistake - cleaning up the mess with EnvirGui widgets, 
I overlooked that NdefParamGui drags are never set to visible. 
Easy to fix with below, and uncritical to just commit:
```
+ NdefParamGui
	showFields { |num = 0|
		paramViews.do { |pv, i|
			var isInUse = i < num;
			pv.visible_(isInUse);
			drags[i].visible_(isInUse);
		}
	}
```

**Comment by adcxyz** [comment]
closed with 8caa0a0

**Comment by telephon** [comment]
that was quick! thank you ...

**Comment by telephon** [comment]
Btw. what does the split slider mean?

<img width="395" alt="screen shot 2016-10-07 at 20 36 44" src="https://cloud.githubusercontent.com/assets/1810559/19201395/eb17bf5a-8ccd-11e6-94c5-304b3a4cff87.png">

**Comment by adcxyz** [comment]
in the previous fixes to JITLibExtensions, I had looked at just that, 
but had not cross-checked again in main distro - so it was easy to guess 
where and when I broke it ;-)

**Comment by muellmusik** [comment]
Thanks Alberto!

**Comment by telephon** [comment]
… and what does the split slider mean?

**Comment by adcxyz** [comment]
an input for two numbers automagically turns into a rangeslider with two values.

**Comment by telephon** [comment]
ah I see, it is because it is a "stereo" control.
