### ISSUE TITLE
Protecting master branch

### ISSUE THREAD

**Issue by gusano** [supercollider/supercollider#2388]
It recently happened that someone pushed directly to master without submitting a PR (cd3a2bf) therefore breaking the class library (Travis build would have [failed](https://travis-ci.org/supercollider/supercollider/builds/165817568) in a PR).
What about protecting master branch and enforcing submitting/reviewing PR for any change? https://help.github.com/articles/about-protected-branches/

cc @adcxyz

**Comment by adcxyz** [comment]
yes, all for it. 
apologies for the silliness, and thanks to @nuss for catching it so quickly.

**Comment by snappizz** [comment]
Yes, let's enable this.

**Comment by gusano** [comment]
OK I'm gonna enable it now.
I'd strongly suggest merging https://github.com/supercollider/supercollider/pull/2319 while we're at it so travis builds are 2 times faster ;)

**Comment by nuss** [comment]
@adcxyz rather I got caught ;) - anyway, no big deal since it's so easy
to fix and and quickly commit. No need for complaints, just do. That's
great.

Am 2016-10-08 um 17:00 schrieb Alberto de Campo:
> yes, all for it. 
> apologies for the silliness, and thanks to @nuss for catching it so quickly. 
>

**Comment by telephon** [comment]
What would make the Travis part far more efficient would be to not rebuild the whole application for every change in the class library (which sometimes makes 90 % of the changes), but just run the tests. But I don't know if /how that is possible.

**Comment by gusano** [comment]
@telephon I don't see how we could run the tests without a built app in the first place =)

**Comment by adcxyz** [comment]
I think Julians point is that or every commit that only goes to SCClassLibrary and HelpSource, 
nothing changes in the compiled app itself, so no need to even compile the full app at all. 
Does the travis build run unit tests in SC as well? 
If so, a cached built app from the last build run could be updated with the new 
classlib and helpsource folders to run only the sclang unit tests.

best a

**Comment by snappizz** [comment]
I was able to [make a commit directly to the master branch](https://github.com/supercollider/supercollider/commit/80437193fa727eddbc750d3b01fab8c1527e2bb9) through the web interface. What's up with that?

**Comment by gusano** [comment]
@snappizz It seems that protected branches only diable **force push** to those branches, therefore anyone can still just push to master :/

**Comment by telephon** [comment]
>I don't see how we could run the tests without a built app in the first place =)
@gusano Travis could simply use the older (that is most recent) binary in those cases.

**Comment by gusano** [comment]
> Travis could simply use the older (that is most recent) binary in those cases

AFAIK travis builds know nothing about "older" builds

**Comment by danstowell** [comment]
2016-10-09 21:31 GMT+01:00 Yvan Volochine <notifications@github.com>:

> Travis could simply use the older (that is most recent) binary in those
> cases
>
> AFAIK travis builds know nothing about "older" builds
>
Is travis able to use ccache? Not being familiar with travis, it's not
clear to me if it'll automatically make use of it (ccache isn't mentioned
in the travis scripts)

**Comment by gusano** [comment]
> Is travis able to use ccache?

@danstowell Yes, gonna submit a PR for that

@adcxyz @telephon We could decrease again the build time with ccache but detecting if there were some changes in some part of the lib and then using an older sc build isn't part of travis capabilities (AFAIK), neither should it be as the point of using travis is checking that something still build with some proposed changes ;)
