### ISSUE TITLE
Default font on macOS is not monospace

### ISSUE THREAD

**Issue by telephon** [supercollider/supercollider#2389]
Knowing that fonts can be a bone of contention, I still would like to propose a more suitable default font for the IDE code editor. Helvetica is good as a text font, but for programming it is not. Beginners who open sc often take very long to find out tha a different font may be good.

The original version of supercollider used Monaco 9, which was beautiful on a low resolution screen. Still `Monaco` would be ok, or even `Courier`. I personally prefer `Droid Sans Mono`, which seems a perfect match for SuperCollider.

Any opinions or idas?

**Comment by snappizz** [comment]
I suggest [Meslo LG S](https://github.com/andreberg/Meslo-Font), which I use for all coding these days. Any monospace font is fine, thouh.

**Comment by deNsuh** [comment]
I use ```Inconsolata``` all the time

**Comment by telephon** [comment]
… also good. Let's collect a few alternatives. Maybe someone knows how to bundle in the app such a default font?

**Comment by brianlheim** [comment]
I like `Droid Sans Mono` as well, as well as Paul Hunt's [`Source Code Pro`](https://fonts.google.com/specimen/Source+Code+Pro) which more clearly distinguishes between 0, O and among l, L, i, I, and 1.

**Comment by snappizz** [comment]
If we're bundling the font with the program, licenses are the only really important factor to consider:

- Monaco is proprietary.
- The SIL Open Font is NOT GPL compatible. This rules out Inconsolata and Source Code Pro.
- Apache License v2 is compatible with GPL v3, so Meslo and Droid Sans Mono is in the clear.

**Comment by brianlheim** [comment]
Ah. In that case Droid Sans Mono would be my choice. The main reason I prefer SCPro over it is that it has a slightly taller line height.

Just curious though, what do you mean by incompatible? Everything I've read seems to suggest it would just be a matter of including the OFL text alongside the GPL.

**Comment by crucialfelix** [comment]
I don't think that the font has to be GPL. Helvetica isn't. If the license for the font is identified in LICENSING then it is perfectly fine to include it. 

But also IDEs don't include fonts normally AFAIK.  Fonts should be system wide, no ? not owned by an application.

**Comment by brianlheim** [comment]
If the font is bundled with SC then it'll be available system-wide on install, just like Adobe fonts used to be before creative cloud. That's the difference between bundling and embedding. True, IDEs don't normally bundle with fonts. I would be fine with Courier New (even though it is serifed) or Lucida Console/Monaco--anything monospaced would be a better choice IMO than Helvetica.

**Comment by gusano** [comment]
Monaco, Helvetica, ... are not available in linux world

**Comment by crucialfelix** [comment]
Anonymous Pro is good too. But I think it is a bad idea to get into the graphics industry.

**Comment by jamshark70** [comment]
Could the IDE have a list of acceptable fonts that are likely to be installed on various systems and, if the IDE configuration file doesn't specify a font, use the first one it finds on the machine?

I've never assumed that an editor would install fonts for me and I tend to agree with Chris. I don't understand why we need to push fonts on users.

FWIW the IDE in Linux defaults to a monospace font (I forget which one), and to Courier in Windows (which I don't like but it's been mentioned as an acceptable alternative above). So, if it goes to Helvetica in OSX, sounds to me like an OSX-specific problem and perhaps the fix should be specific to OSX.

**Comment by brianlheim** [comment]
#3404

**Comment by brianlheim** [comment]
Coincidentally, from what I can recall this is the very first conversation I ever participated in on this project's GitHub page. Wow, I do not agree with myself from back then.

**Comment by snappizz** [comment]
i've seen a few 3.10 users on macOS who still have the default, non-monospace font enabled. i think this is because they started using SC before 3.9 and their font got saved. i don't like the idea of changing their fonts for them -- seems like a kinda paternalistic move -- but screenshots and videos of SC with this non-monospace font negatively affects the public image of SC... any thoughts?

**Comment by telephon** [comment]
Ahrg, we should have never saved a font that was never set by the user, now we can't distinguish the two -- a silly design mistake in the preference handling. 

But wouldn't you always save the changes as a new theme anyway? I think it is not paternalistic to reserve the freedom to change default themes. We may want to make more adjustments in the future.

I'd suggest to change it **right now** (for 3.10) and mention under recent fixes that this was necessary.
