### ISSUE TITLE
support capf completion-at-point-functions in Emacs

### ISSUE THREAD

**Issue by stardiviner** [supercollider/supercollider#2393]
I found `sclang-complete-symbol` does not compatible with Emacs new built-in `completion-at-point-functions`. When I set like this:

``` elisp
(setq completion-at-point-functions '(sclang-complete-symbol))
```

It will popup a completion buffer `*SCLang:Completions*`. And Emacs also show warning info in minibuffer:

```
Warning: sclang-complete-symbol failed to return valid completion data!
```

And because `company-mode` has a backend called `company-capf` for `completion-at-point-functions`. Most people now use `company-mode`.

So really hope to imporve `sclang-complete-symbol` to support `completion-at-point-functions`.

**Comment by stardiviner** [comment]
Is there any new progress on this?

**Comment by snappizz** [comment]
Sorry, but scel is not very actively maintained :(

**Comment by stardiviner** [comment]
I see, I'll try to dive in at some time. Thanks.

**Comment by widp** [comment]
This issue was moved to supercollider/scel#2
