### ISSUE TITLE
WiiMote classes under OSX

### ISSUE THREAD

**Issue by jleben** [supercollider/supercollider#241]
[Issue migrated from SourceForge | ID: 3479748 | Submitted by 'nufets']
[http://sourceforge.net/support/tracker.php?aid=3479748]

There's a number of WiiMote related classes that currently don't seem to work under OSX. E.g. the following should discover a new device:

WiiMote.discover;

This throughs a 'primitive not bound' error on my machine (MBP CoreDuo, OS 10.6.8, SC 3.5 beta). During compilation of SC I get a warning when it comes to compiling the underlying library (SC_WiiMote - don't rember their names exactly). Wouldn't it be nice making SC independant from having to use third party tools like OSCulator when working with a WiiMote?

**Comment by scztt** [comment]
Man, does anyone even have a wiimote anymore?

**Comment by sensestage** [comment]
Given that there is no one currently who can maintain or update this code, I'd say that we take it out. There are third-party tools with dedicated developers to keep them up-to-date to get the same functionality.

**Comment by brianlheim** [comment]
Pinging this - does anyone object to solving this by removing the WiiMote classes? Would Marije be interested in maintaining/solving this? I don't know how to contact her.

**Comment by gusano** [comment]
@brianlheim You can ping her @sensestage :)

**Comment by vivid-synth** [comment]
I'm fine with removing WiiMote - if people want it, maybe someone can volunteer to take it on as a Quark?

**Comment by snappizz** [comment]
I was wrong -- this wasn't completely fixed by #2697, there are still some other Wii classes hanging around.

**Comment by brianlheim** [comment]
OK! Thanks for repoening.
