### ISSUE TITLE
Pattern:record with no path fails if recordings dir not already created

### ISSUE THREAD

**Issue by muellmusik** [supercollider/supercollider#2415]
The platform specific recordings directory seems to be created in Server:prepareForRecord. But Pattern:record does not use that method. There may be other cases where this happens, so not sure if the correct fix is to add it in Pattern:record or somewhere more general?

**Comment by vivid-synth** [comment]
Just a thought: maybe Pattern:record should call Server:prepareForRecord?

**Comment by adcxyz** [comment]
quickest option:  create default recordingsDir in an initClass method, e.g. in Server:initClass

maybe better: write a Recorder class and factor out recording to that class in Server and Pattern.
RecNodeProxy seems rather close to that. 
2c, adc

**Comment by telephon** [comment]
@adcxyz there is a Recorder class in the still to be merged server refactoring branch.
