### ISSUE TITLE
What changed in SinOsc, Osc, or Saw between 3.6.6 and 3.7.2?

### ISSUE THREAD

**Issue by snappizz** [supercollider/supercollider#2417]
Thread is here: http://new-supercollider-mailing-lists-forums-use-these.2681727.n2.nabble.com/Sound-differs-between-3-6-6-and-3-7-2-td7628398.html

As best as I can tell, the phase relationship between SinOsc/Osc and Saw changed at some point. (My attempt at investigation was hindered by the fact that I can't roll back and compile 3.6.6.) The question is, what changed, and how can the old behavior be emulated?

**Comment by snappizz** [comment]
Very short reproducer:

    { SinOsc.ar(100 * Saw.ar(100, mul: 10, add: 1)) * 0.2!2 }.play;

Would appreciate if someone using 3.6.6 could record the output. Phase drift is audible in 3.8.

**Comment by telephon** [comment]
Yes, also visible in:
`{ Saw.ar(800) }.plot`. 

It is only the phases, the frequency distribution is constant.

While it is something that would be good to check, we should note that if you wanted a saw as a frequency modulator, you'd probably want to use `LFSaw`, because it is a "clean" sawtooth rather than a bandlimited "wiggly" one.

**Comment by snappizz** [comment]
LFSaw also has phase drift with Osc/SinOsc. The problem here is not phase drift, but the fact that something changed and we don't know why.

**Comment by telephon** [comment]
yes

**Comment by vivid-synth** [comment]
If anyone wants to look into what changed, here's the diff between the versions:

> git diff Version-3.6.6..Version-3.7.2 server/plugins/{LF,Osc}UGens.cpp

And here are the commits that created changes:

> git log -p Version-3.6.6 Version-3.7.2 server/plugins/{LF,Osc}UGens.cpp

**Comment by snappizz** [comment]
I don't think it's in `OscUGens`, for two reasons. First, I tried reverting the source file on my machine and couldn't get the old behavior back. Second, the user who discovered this transplanted the shared library from 3.6.6 and didn't see a regression either.

**Comment by vivid-synth** [comment]
@snappizz so it's probably not in LFUGens either?

**Comment by snappizz** [comment]
Probably not, unless SinOsc/Osc/Saw depends on code in LFUGens (which is unlikely).

**Comment by snappizz** [comment]
stale issue, no resolution.
