### ISSUE TITLE
Should we deprecate AudioIn?

### ISSUE THREAD

**Issue by snappizz** [supercollider/supercollider#2429]
It's provided "for backward compatibility with SC2." Unfortunately, [people are still using it](https://github.com/search?l=SuperCollider&q=audioin&ref=searchresults&type=Code&utf8=%E2%9C%93) instead of SoundIn. Would it be too drastic to put this thing to rest?

**Comment by muellmusik** [comment]
Yes, deprecate. SC2 was a long time ago.

**Comment by vivid-synth** [comment]
I'm fine with doing this but seeing as it's apparently in active use let's tell the community about it before shutting it off!

**Comment by jamshark70** [comment]
Generally, "deprecate" means to move the class/method into a folder for future removal, and add a warning method so that users of AudioIn will be warned in the post window that it will be removed.

Deprecation does not mean immediate deletion.

**Comment by snappizz** [comment]
What has me concerned is that this is a really commonly used ugen, and when eventually removed a lot of things could break. How about deprecate in 3.9, but wait until 3.11 to remove it?

**Comment by gusano** [comment]
@snappizz I vote for deprecate now and remove it asap, it's easy enough to replace it with `SoundIn` and it should already have been deprecated ages ago :)

**Comment by vivid-synth** [comment]
I'm with @snappizz  --- AudioIn isn't really hurting anyone, is it? It's just not the best way to do things. I'm fine with a looong deprecation cycle, and a very clear this-is-what-you-need-to-change-and-how deprecation message.

**Comment by muellmusik** [comment]
@snappizz There is nothing gained from waiting to deprecate. Deprecation is a warning, and probably the most effective one. It is telling the community. There has already been a warning to not use AudioIn in its helpfile, saying that it may be deprecated and removed, for almost 9 years. This has not been rushed.

Can stay awhile longer and eventually go into an 'SC2 compatibility' Quark. (Not that code ever was compatible...)

**Comment by vivid-synth** [comment]
Agreed, deprecate asap, but then have a long deprecation cycle before removal.

**Comment by gusano** [comment]
@snappizz Sorry to insist guys but after looking at the first 5 pages from [your search results](https://github.com/search?l=SuperCollider&q=audioin&ref=searchresults&type=Code&utf8=%E2%9C%93) showing that `AudioIn` is *still widely used* shows various user classes ranging from 2006 til 2011, a lot of them are just using @crucialfelix's `AudioInPlayer` (from cruciallib) and others are just random small copy/paste tests.. I really don't think we should wait one year before removal (#2482), that seems a bit overkill, really..

**Comment by jamshark70** [comment]
@gusano I agree with you about "deprecate now," but I don't agree about "remove ASAP." You may be right: a year could be too long. But I don't think AudioIn is hurting anybody, especially if it prints a deprecation warning.

**Comment by snappizz** [comment]
@gusano note that my comment says "3.11 or November 2017, whichever comes first."

**Comment by vivid-synth** [comment]
We should probably make a decision on this - it's been 10% of the deprecation period already :smile:

**Comment by snappizz** [comment]
Yes, let's try to get consensus here.

**Comment by snappizz** [comment]
knock knock

**Comment by brianlheim** [comment]
Yes, deprecate. It was pretty confusing as a newbie and I still get them mixed up sometimes.

**Comment by snappizz** [comment]
We all agree to deprecate, but we haven't reached an agreement on whether it should have an exceptionally long deprecation cycle (I'm suggesting removal in November).

**Comment by brianlheim** [comment]
Ah, sorry. I think removing it ASAP after deprecation is fine; I agree with @muellmusik above.

**Comment by snappizz** [comment]
Dammit Brian! Now we're split 3 vs. 3.

Should we straw poll sc-users then?

**Comment by brianlheim** [comment]
Oops! Yeah, might want to see if there are any other strong objectors out there.

**Comment by gusano** [comment]
@snappizz let's move on and deprecate!
Later it can be decided when to remove it so we can keep it for another 9 years if we want :)
