### ISSUE TITLE
s.stopRecording posts "nil" instead of the file path (Win-3.8.0-beta1)

### ISSUE THREAD

**Issue by alln4tural** [supercollider/supercollider#2432]
Version: SuperCollider-Win-3.8.0-beta1_64bit-0962eaf
OS: Windows 7 enterprise (on intel core i5-6300U @ 2.4 GHz)

tested my usual setup out for half an hour, everything seems to work -- cool, congrats, thanks!

i noticed one (very) minor thing that may not be new (i jumped straight from 3.6 to 3.8):
s.stopRecording posts "nil" instead of the file path

s.record(thisProcess.platform.recordingsDir +/+ Date.getDate.format("%Y%m%d_%H%M%S_%A") ++ "_test.aiff")
// Recording: C:/e/Dropboxalln4t/sc-win-recordings\20161026_134543_Wednesday_test.aiff

// wait a bit

s.stopRecording
// Recording Stopped: nil

back in 3.6, it used to say, instead of nil: C:/e/Dropboxalln4t/sc-win-recordings\20161026_134543_Wednesday_test.aiff

Not a big deal, but "nil" makes me nervous, as if something had gone wrong (it hadn't, thankfully, afaict).
Also maybe an indication of a deeper problem ..

cheers,
eddi

**Comment by snappizz** [comment]
I've been seeing this too on Linux.

**Comment by bagong** [comment]
OSX too.
Apparently recordBuf.close deletes the path. So either invert the order of recordBuf.close and the postf line, or assign recordBuf.path to a variable?

**Comment by telephon** [comment]
… or if you know what it could be, give it a try.

**Comment by bagong** [comment]
Like this?
````
	stopRecording {
		var recordPath;
		if(recordNode.notNil) {
			recordNode.free;
			recordNode = nil;
			recordPath = recordBuf.path;
			recordBuf.close({ |buf| buf.freeMsg });
			"Recording Stopped: %\n".postf(recordPath);
			recordBuf = nil;
		} {
			"Not Recording".warn
		};
	}
`````

**Comment by telephon** [comment]
looks good. I'll have to update also the refactored branch, but maybe it works there: https://github.com/supercollider/supercollider/pull/2422

**Comment by bagong** [comment]
I don't see where it prints a path in #2422 ;)

**Comment by telephon** [comment]
Yes, it probably just doesn't do it :). We could add this as a feature ...
