### ISSUE TITLE
Windows: fetching quarks fails if username contains space

### ISSUE THREAD

**Issue by bagong** [supercollider/supercollider#2440]
`Quarks.gui` initial fetching fails with:

```
Fetching https://github.com/supercollider-quarks/quarks.git
ERROR: Failed to read quarks directory listing: https://github.com/supercollider-quarks/quarks.git a PrimitiveFailedError
-> a QuarksGui
```

`Quarks.folder` returns in this test case (user name "test sc")

```
-> C:\Users\test sc\AppData\Local\SuperCollider\downloaded-quarks
```

I haven't been able to understand the underlying code yet, but it might have to do with unix "escaping" of spaces in paths. You don't escape in Windows, you put the path containing spaces in apostrophe "".

Non ASCII characters in the username seem to work for Quarks, as opposed to SCDoc, which tolerates a space, but not a non-ASCII character.

**Comment by telephon** [comment]
maybe the method `standardizePath` should delegate to the `Platform` class?

**Comment by Chosko** [comment]
Any news on this? I can't install Quarks because of this issue....
There's a workaround to make it work?

**Comment by bagong** [comment]
For 3.8 just to create a user account without space. Or you modify your classes. The problem is that paths are not escaped in a way that works for Windows.

It's fixed here: https://github.com/supercollider/supercollider/pull/2778

You can problably adapt it quite easily in your class files:

So should be gone in 3.9.

**Comment by snappizz** [comment]
@Chosko sorry about that... the simple workaround would be to manually download the quarks you want and copy them into `Platform.userExtensionDir`

**Comment by Chosko** [comment]
ok thanks
