### ISSUE TITLE
Windows: Qt doesn't handle high resolution displays well

### ISSUE THREAD

**Issue by bagong** [supercollider/supercollider#2442]
Observed on 3.7 and 3.8
- compared to text, buttons and icons are tiny
- help text is tiny too

In "normal" resolution, e.g. 1440:900, and on the Mac this is not the case.

**Comment by LFSaw** [comment]
this might be fixed with #3165 ?

**Comment by muellmusik** [comment]
@bagong is this still an issue after #3165 or should we close?

**Comment by jamshark70** [comment]
We have a user report that UI objects are not scaled in Windows, using 3.10. #3165 did not fix it.

https://scsynth.org/t/problem-with-high-resolution-screen-display/823

**Comment by dyfer** [comment]
I found a temporary workaround, which will make the supercollider (both the IDE and the GUIs) scale to the proper size, but the fonts will be blurry. 
To try this, create a text file called `qt.conf` in the same folder as the `scide` executable and put the following in it:
```
[Platforms]
WindowsArguments = dpiawareness=0
```

**Comment by brianlheim** [comment]
is this fixed by #4846 and #4850?

**Comment by brianlheim** [comment]
yes, i see so (https://github.com/supercollider/supercollider/pull/4850#issuecomment-609108772)

**Comment by brianlheim** [comment]
thanks @dyfer and @elgiano !
