### ISSUE TITLE
Current Issues-page on Homepage

### ISSUE THREAD

**Issue by bagong** [supercollider/supercollider#2443]
We should have a highly visible page that lists current annoyances with SC. Something to refer people to who write to sc-users about something puzzling. Currently for example it could contain:
- macOS Sierra: SC build broken because of broken homebrew-qt55 (original qt55 also broken)
- update submodules when switching between the 3.8- and master branches
- Windows usernames must not contain non-ASCII characters or spaces.
  ...

Such a page might fail because of lack of visibility or maintenance, but I think we should try...

**Comment by vivid-synth** [comment]
It seems like this would be hard to keep up-to-date -- can we not point people to the github issue? That'd have the bonus of letting people know when it's fixed.

If we want to have "a bigger signpost," i.e. something that's visible even before you ask the question, I'd be for that although I don't have an answer to how.

**Comment by bagong** [comment]
Yea, I see the risk, if it fails, we can delete that page again. Probably it would work best if somebody felt responsible for it, and supplement/maintain the contributions. Pointing to a github issue is a very good idea. I just thought it's easier to find the 5 to 10 currently notorious issues if they were listed in a page.

We could try to make the page known in the community by referring to it in answers in the mailing lists or on Facebook, also maybe by pointing to it in Readmes, and create a fat visible link on the homepage. If the page became well known enough it could have the effect of occasionally warning people before they run into a problem.

**Comment by telephon** [comment]
I think it is worth a try.

**Comment by bagong** [comment]
I would volunteer for this, but I can't follow discussions much during the next two months. So if anybody steps forward, that would be great, otherwise I'll take it up in January.

**Comment by vivid-synth** [comment]
@bagong my only concern was creating another thing that wouldn't have maintanership. If you or someone else wants to take it on, please don't let me get in your way!

**Comment by crucialfelix** [comment]
We could at least link to issues with a filter for SEVERE+BUGS or something.

**Comment by crucialfelix** [comment]
This are known bugs for the 3.8 release: https://github.com/supercollider/supercollider/issues?q=is%3Aopen+is%3Aissue+label%3Abug+milestone%3A3.8
