### ISSUE TITLE
cmake fails, gl.h not found

### ISSUE THREAD

**Issue by telephon** [supercollider/supercollider#2447]
After an update of xcode to `Version 8.0 (8A218a)`, cmake fails, probably a path issue.

```
-- SuperCollider Version: 3.8dev
-- Building from branch topic-server-refactoring-reordered, commit hash is f75f65b
-- Build type defaulting to "RelWithDebInfo"
-- Compiling with Qt GUI
-- building boost libraries manually
-- using bundled libyaml-cpp
-- HIDAPI components:
--     mac
--     hidapi_parser
-- Audio API: coreaudio
-- Found a homebrew install of readline /usr/local/opt/readline
-- Found GNU Readline version 6.3: /usr/local/opt/readline/lib/libreadline.dylib
CMake Error at /usr/local/opt/qt5/lib/cmake/Qt5Gui/Qt5GuiConfigExtras.cmake:9 (message):
  Failed to find "gl.h" in
  "/System/Library/Frameworks/OpenGL.framework/Headers;/System/Library/Frameworks/AGL.framework/Headers".
Call Stack (most recent call first):
  /usr/local/opt/qt5/lib/cmake/Qt5Gui/Qt5GuiConfig.cmake:141 (include)
  /usr/local/opt/qt5/lib/cmake/Qt5Widgets/Qt5WidgetsConfig.cmake:81 (find_package)
  QtCollider/CMakeLists.txt:6 (find_package)
  lang/CMakeLists.txt:182 (include)


-- Configuring incomplete, errors occurred!
```

**Comment by bagong** [comment]
Which qt-version is installed?

I built with Xcode 8 and homebrew qt 5.5.1 provided as qt55. That release can be installed in el capitan (and earlier OSX versions) with via "homebrew-versions". I don’t remember the link in the command exactly, but it must be something like `brew install homebrew-versions/qt55`. Anyways `brew install qt55` will search the taps and produce the correct link. I didn’t have your problem with that qt release.

Best
.r.

PS: just a warning for people considering a Sierra update: qt55 is broken in Sierra.

**Comment by telephon** [comment]
>PS: just a warning for people considering a Sierra update: qt55 is broken in Sierra.
made an issue for that, so it doesn't get overlooked.

**Comment by bagong** [comment]
Thanks!

**Comment by telephon** [comment]
I could fix it via

`sudo xcode-select --install`

and

`brew update`


brew doctor gave me the hint:

```
You have Xcode 8 installed without the CLT;
this causes certain builds to fail on OS X El Capitan (10.11).
Please install the CLT via:
  sudo xcode-select --install
```
