### ISSUE TITLE
QT5.5 is broken on OSX Sierra, but we depend on it.

### ISSUE THREAD

**Issue by telephon** [supercollider/supercollider#2448]
the title says it all ... Thanks, @bagong

**Comment by crucialfelix** [comment]
Shiiiiiiiit

**Comment by crucialfelix** [comment]
This means we have to port Web view and some others to make them work on qt 6 or ?

That's the blocker, right ? I'm on mobile so sorry I didn't research this fully yet

**Comment by bagong** [comment]
Yes.
For people who already updated and find themselves here: There is one exception: if you had installed qt55 in el capitan and made an in place update, it will still work. But you cannot install a fresh working qt55 in Sierra. I don't know what happens to a qt5 pinned to qt 5.5.1. Maybe it also works, but don't change anything. People discussing this on homebrew are sceptical that 5.5.1 will be updated to work, but then homebrew has a very active community, so there is hope.

**Comment by bagong** [comment]
@timblechmann had a PR once for the switch to 5.6 which worked in Linux. But it was closed/retracted as reaction to conflict concerning a different matter. Not sure if we can revive that? ;)

**Comment by crucialfelix** [comment]
Well it's open source so we just go fetcheck the code.  It was AFAIR a sketch that needs completing.

**Comment by kisielk** [comment]
Is there anything that can be done to move this forward? Got my new MBP this week but now cannot use SC.

**Comment by telephon** [comment]
Maybe a workaround:

https://github.com/thoughtbot/capybara-webkit/wiki/Installing-Qt-and-compiling-capybara-webkit

writes
>Qt 5.5 compilation is broken on Sierra, but we can work around that by directly using the Qt 5.5 binaries.

and gives instructions.

**Comment by telephon** [comment]
There is also this: https://github.com/Homebrew/homebrew-science/issues/4333

maybe it works now?

**Comment by kisielk** [comment]
@telephon I think that's fixed by the fact that there is qt5.7.0 available now, not that qt5.5 was made available. I tried building qt5.5 on my machine but I cannot.

**Comment by kisielk** [comment]
I also tried the workaround from the previous comment but the binary installer just freezes part way through the process.

**Comment by michaelmusick** [comment]
This is something I have also run into with a new MBP. I would like to build from source, but obviously cannot install QT5.5. 

I am interested in contributing to the development community side of SC, so maybe this is a place to start? What kind of specific tasks would be necessary to start addressing qt5.7 compliance in SC? Or is that even in the development roadmap?

**Comment by brianlheim** [comment]
@michaelmusick Thanks for your interest! It's definitely in the development roadmap. I would recommend talking to @scztt, as he's (I think) done the most work on approaching a switch to 5.7. The main issue is the difference between WebKit and WebEngine - in the move from 5.5 to 5.6 Qt discontinued the synchronous WebKit and only supports the asynchronous WebEngine. That's about all I know about it at the moment.

**Comment by bagong** [comment]
@michaelmusick, the Qt 5.5. issue is fixed in homebrew. I'll close this. But if you'd like to help moving on with Qt, that's definitely one of the highest priority issues!
If somebody ends up here, stuck with Qt5.5 on Mac, as it's not selfevident how to find it, the package is now called qt55 or qt@5.5 (check `brew info qt55`)
