### ISSUE TITLE
same font looks different in qt/cocoa

### ISSUE THREAD

**Issue by jleben** [supercollider/supercollider#245]
[Issue migrated from SourceForge | ID: 3482177 | Submitted by 'wsnoei']
[http://sourceforge.net/support/tracker.php?aid=3482177]

In 3.5 beta3 it seems that the font anti-aliasing is set to a different mode, resulting in fonts to be thinner and thus less readable. Picture of difference attached, code below:

// alternate between these two:
GUI.qt;
GUI.cocoa;

(
w = Window().front;
w.addFlowLayout;
[9,10,12,14,18].do({ |item|
StaticText( w, 390@24 )
.string_( "The quick brown fox jumps over the lazy dog" )
.font_( Font( "Helvetica", item ) );
})
)

**Comment by scztt** [comment]
I can't see any evidence of this problem anymore, and qt5 font handing is radically improve over earlier versions, so I wouldn't be surprised if this was fixed.

**Comment by crucialfelix** [comment]
Cocoa is retired now, so the ticket is irrelevant now.
