### ISSUE TITLE
lang: "RESULT =" posting from unixCmd cannot be disabled without disabling post output entirely

### ISSUE THREAD

**Issue by snappizz** [supercollider/supercollider#2452]

**Comment by miguel-negrao** [comment]
What is the desired change in behaviour ?

**Comment by snappizz** [comment]
i suggest we remove the `RESULT = #` post entirely and leave it up to whoever is calling `.unixCmd` to see the exit code for themselves. this is how many other programming languages work.

in the context of SC, `RESULT = #` posts appear most often when the server exits. this is a good opportunity to replace this rather cryptic message with a more friendly one: `Server process exited with return code #.`
