### ISSUE TITLE
Update boost.sync to avoid deprecation warnings

### ISSUE THREAD

**Issue by bagong** [supercollider/supercollider#2459]
Getting rid of this warning would make the build output a lot cleaner:

`This header is deprecated, use boost/detail/winapi/get_last_error.hpp instead.`

**Comment by vivid-synth** [comment]
Maybe modernizing our boost use (https://github.com/supercollider/supercollider/issues/2301) is the fix

**Comment by brianlheim** [comment]
We need to update boost.sync, which is not covered in #2772 because it is not part of official boost releases. They've fixed the header deprecations here: https://github.com/boostorg/sync/commit/8ffa2807f4928aa091800b67b670a60249d48bcf.

**Comment by bagong** [comment]
Yea, the other day I also thought that the deprecation warnings actually come from boost calling boost, but wasn't sure. I didn't find the updated sync... nice!

**Comment by bagong** [comment]
The VS build is starting to look pretty with updated boost.sync. Solving the following would bring the warnings down from around 300 to a few dozens ;) :

No 1 (50% of the warnings):
````
SuperCollider\common\SC_AllocPool.h(210): warning C4334: '<<': result of 32-bit shift implicitly converted to 64 bits (was 64-bit shift intended?) [C:\Users\Rainer\Projects\sc\supercollider\build_VS64_2015_SN_Rl\lang\libsclang.vcxproj]
````
These are the most common in SC proper (i.e. not from submodules or dependencies)
````
C:\Users\Rainer\Projects\sc\supercollider\server\scsynth\SC_World.cpp(585): warning C4297: 'World_NonRealTimeSynthesis': function assumed not to throw an exception but does [C:\Users\Rainer\Projects\sc\supercollider\build_VS64_2015_SN_Rl\server\scsynth\libscsynth.vcxproj]
C:\Users\Rainer\Projects\sc\supercollider\common\SC_fftlib.cpp(207): warning C4334: '<<': result of 32-bit shift implicitly converted to 64 bits (was 64-bit shift intended?) [C:\Users\Rainer\Projects\sc\supercollider\build_VS64_2015_SN_Rl\server\scsynth\libscsynth.vcxproj]
C:\Users\Rainer\Projects\sc\supercollider\lang\LangSource\PyrObject.cpp(1085): warning C4068: unknown pragma [C:\Users\Rainer\Projects\sc\supercollider\build_VS64_2015_SN_Rl\lang\libsclang.vcxproj]

bunch of conversion "double to float requires a narrowing of conversion" in plugins:
Loudness.cpp (31)
Beattrack.cpp (53,54)
Keytrack.cpp (39,43)
MFCC.cpp (38,46,54)
Beattrack2 (30,35,37,39)
````
