### ISSUE TITLE
views don't show they are receiving drag in Qt

### ISSUE THREAD

**Issue by jleben** [supercollider/supercollider#246]
[Issue migrated from SourceForge | ID: 3482181 | Submitted by 'wsnoei']
[http://sourceforge.net/support/tracker.php?aid=3482181]

when something is dragged to a view in Cocoa, it shows a clear blue frame around the view. In qt this doesn't happen, which makes it hard to see which object you are actually dragging to.

**Comment by scztt** [comment]
Workaround is to use mouseEnter + mouseLeave + View.currentDrag, but lets fix this at the Qt level in future versions.
