### ISSUE TITLE
Windows: update portaudio to latest release version

### ISSUE THREAD

**Issue by bagong** [supercollider/supercollider#2462]
Portaudio has been updated recently. We should incorporate those changes. The difficulty lies in applying the adjusted changes in our repo, which mainly serve to allow for building with the combination of MinGW and cmake. If we have to give up the MinGW builds anyways because of lacking Webengine support, those changes can be reduced to a minimum. The VS portaudio build works significantly better and is officially supported by PA.

PA plans to add hotplugging. I am not sure if this is already incorporated in the current release or whether this is their next project (for which the current release would form the base).

**Comment by brianlheim** [comment]
Is this fixed by the recent PRs? (https://github.com/supercollider/portaudio/pull/1)

**Comment by bagong** [comment]
Yes!
