### ISSUE TITLE
PV_JensenAndersen and PV_HainsworthFoote are misnomers

### ISSUE THREAD

**Issue by snappizz** [supercollider/supercollider#2470]
They are FFT analysis ugens, not PV ugens. They should be renamed, and the old names should be deprecated.

**Comment by telephon** [comment]
All the UGens that operate on FFT chains are called `PV_` by convention in supercollider. Or do you mean they are misnamed because they don't *return* an FFT chain?

**Comment by jamshark70** [comment]
This might be a change for SC4 but I think here, the gain in conceptual clarity is minimal, the gain in functionality is 0, and the pain from breaking people's code is certain to be larger than you expect.

I'd say, nope, please not now.

**Comment by snappizz** [comment]
Yes. I've always heard the term "phase vocoder" used to refer to the FFT -> processing -> IFFT pipeline. It follows that these two ugens aren't really PV. Our other analysis ugens have no PV_ prefix: SpecCentroid, SpecFlatness, etc.

**Comment by jamshark70** [comment]
It appears that PV_JensenAndersen and PV_HainsworthFoote are older than the Spec* analysis units. It might even be that the Spec* units established the convention of frequency domain *processors* being named PV_* while frequency domain analyzers drop the prefix. Prior to that point, the thinking might have been that PV_ is for anything taking an FFT chain as input. (I'm guessing as to the history.)

In any case, I agree that it's technically correct to rename these two units without PV_, but it will incur a cost (breakage of user code) that we can't measure right now, in exchange for a microscopic benefit.

For quite some time now, the general (vague) plan floating around is that SC4 would be the version to clean up mistakes in programming interfaces, remove extraneous "alternate ways" of doing things, etc. This issue would fall under that category. I have doubts about introducing more incompatibilities into the SC3 line, unless there's a really clear functional benefit.

**Comment by snappizz** [comment]
I still disagree, and I think there is a way to proceed here without breaking backward compatibility -- simply introduce new names. But I appear to be in the minority here, so I won't argue further.

**Comment by telephon** [comment]
In any case, id wouldn't hurt to just make redirects immediately now, and correct the helpfile.

**Comment by telephon** [comment]
Just a note: I don't want to press the issue, I've just added this PR to provide a solution in case we can agree on it. Feel free to ignore/close.

**Comment by Sciss** [comment]
May I remind everyone that simply renaming the plugin and adding a redirection in the class library makes life miserable for everyone that maintains a client that is not tied to a particular 3.x version of scsynth. I would really appreciate if that goes into the reasoning. If you rename, please simply rename the .sc class file and not the server plugin name.

**Comment by jamshark70** [comment]
I wouldn't have set this "wontfix" -- it's a fine thing to do in SC4.

I tend to agree with sciss that, as a rule, we are far too cavalier about changing names, method signatures etc without considering the impact outside of a narrowly drawn field of view. It is a bad habit for SC developers, and perhaps an inevitable consequence of SC being a "do-ocracy" without such inconveniences as program managers.

**Comment by Sciss** [comment]
I'm not categorically against fixing mistakes, but you always have to make a cost evaluation, and I think breaking the name on the server is a thing that should wait till SC 4.

**Comment by telephon** [comment]
not a big issue, as I said.

**Comment by snappizz** [comment]
Closing, adding to [breaking changes project](https://github.com/supercollider/supercollider/projects/5).
