### ISSUE TITLE
Use full version in CFBundleShortVersionString

### ISSUE THREAD

**Issue by timsutton** [supercollider/supercollider#2471]
I work at a university where we mass-deploy Mac software for studios and computer labs, and one thing that always makes this easier is if applications use the "full" version strings in their installation or application metadata.

`CFBundleShortVersionString` in the Mac app's Info.plist is typically used for the version string visible to users in the Finder, and `CFBundleVersion` can be a machine-parseable version like a build number (although it's sometimes used for a combination of both, i.e. `major.minor.patch.build`)

In the [template Info.plist](https://github.com/supercollider/supercollider/blob/772bdd6946a7253390ba0b1b23eb3adc0acb97ea/cmake_modules/MacOSXBundleInfo.plist.in#L145), the `CFBundleShortVersionString` contains only major and minor, and the patch version (with a dot) is placed in `CFBundleVersion`. Is patch omitted from the `CFBundleShortVersionString` for a particular reason? I would think that if someone looks at the app in the Finder, it would be preferable that they see the same version number they see on the website.

Would you be willing to accept a simple PR to put the full major.minor.patch in at least _one_ of these two fields for the Mac build?

As a systems administrator it doesn't really matter to me which one as long as it's consistent, but from a user perspective I'd think showing the full version is totally acceptable in `CFBundleShortVersionString`, and if you had any more specific integer build value, for example, to put in `CFBundleVersion`, that's great, but otherwise it's not really gaining anything to put just the patch version in that field.

The idea is that a computer or human should be able to compare one of these fields across multiple versions and be able to tell which is newer. It's mechanisms like this which are used by mass deployment tools to determine whether or not the desired version is really installed, without resorting to things like checksums of the binaries themselves.

I used SuperCollider in a past life, so it's exciting to come back to it and see how far it has come. Thanks!

**Comment by telephon** [comment]
This looks perfectly reasonable to me. Please, if you can, do make a PR and we can check if there is anything that needs to be discussed.

**Comment by brianlheim** [comment]
Closed by #2487.
