### ISSUE TITLE
Keep better changelogs

### ISSUE THREAD

**Issue by snappizz** [supercollider/supercollider#2485]
Right now our changelogs are not that useful for determining what changed between major versions. For our 3.8 announcement I [manually went through the PR list and selected what I considered most important](http://supercollider.github.io/releases/2016/11/06/supercollider-3.8.0). By "most important," I mean changes that nontrivially affect users. That excludes refactors and minor helpfile fixes.

Let's consider putting some more love into our changelogs. Instead of someone having to go through the entire list, let's create a human-readable changelog as we go. This little manifesto is nice, although we don't need to conform to its specific format: http://keepachangelog.com/en/0.3.0/

We are early enough in 3.9 that we can start assembling this pretty easily. Instead of cluttering the commit history of the repo, we should probably maintain this list on the [github wiki](https://github.com/supercollider/supercollider/wiki) or something.

I hate to create extra labor for everyone but I really feel this is worth it. Thoughts?

**Comment by scztt** [comment]
I would suggest a simple, limited set of tags to use in commit notes, that we can capture later on to extract useful data. It makes commit notes more readable, but also means changelog-ish information is stored WITH the actual changes.

Example (for an imaginary change):
```
classlib: Refactor some message syncing functionality.

@RELEASENOTE Improved server message bundling and sync functions.
@API Server:queueBundle, Server:sendSynchronized added
@DEPRECATED Server:schedSync removed (use Server:queueBundle instead)
@TESTING Test all Server messaging commands (sendMsg, sendBundle, etc). Ensure Server:sync works as expected.
```

This is only four tags, but if we could search across all changes for these, we could generate:
1. A descriptive, high-level set of release notes
2. A list of API changes and deprecations
3. A comprehensive set of testing areas when a new alpha/beta build is released.

**Comment by snappizz** [comment]
I realize that my original post may have given the impression that I was complaining about manually constructing the changelogs from the pull requests. It's not that painful really. I would just prefer if we write it as we go along rather than hastily filter it just before release. A benefit of incrementally creating the changelog is that users can see what's changed while the release is in progress.

We're already tracking API changes and deprecations, but notifying beta testers of testing areas is a pretty great idea.

What I disagree with is the proposal to automate the changelog. It's nice in theory, but I can see it going wrong easily:

- Most major changes have multiple commits. Having release notes on individual commits seems to contradict the idea of collecting "descriptive, high-level" release notes.
- If a commit is merged with an absent or inaccurate release note, there is no way to go back and correct it.
- If a commit has a correct release note but is reverted, it can't be corrected.
- We can't change our minds post-merge on whether a commit is deemed significant or not.

These mistakes can all easily happen, and you end up with a noisy changelog that still must be manually edited. Considering that the changelog of major features is pretty small (maybe 20 or 30 bullet points) for each 3.x release, I'm not convinced that the steps required to implement and maintain an automated changelog are any less work than manually creating a changelog in the first place.

Typically, at least three people are involved in a nontrivial PR: one person to file it, one person to review it, and one person to merge it. I don't think it's unreasonable to expect at least one of those people to go and quickly write a sentence about it on the github wiki. If that's too idealistic, I happily volunteer to assist in maintaining the log.

**Comment by snappizz** [comment]
Another thing to tack onto my original proposal: let's try to have have CHANGELOG.md, the "News in 3.x" helpfile, the website blog post, and the announcement post all match. It helps to be redundant, since we really want to trumpet the API changes and deprecations. It helps to be redundant, since we really want to trumpet the API changes and deprecations.

**Comment by kisielk** [comment]
It would be good to have an actual release notes as opposed to just a changelog.

The best I've seen has been from the Go project, see for example https://golang.org/doc/go1.7

I always know what the most important changes in a Go release are, and reading the release notes is actually quite enjoyable :)

**Comment by scztt** [comment]
@snappizz I was considering the multi-checkin problem --- The way we manage the SC codebase, basically every SET of changes enters by way of a pull request, which means there's always a merge commit in addition to the granular commits that are being merged in. I think probably we'd say that release notes go in the pull requests notes, and API / testing notes go on individual commits (though they could ALSO go on the PR if they're more general). In particular, this provides a chance to edit the release notes a bit before the final merge, to make sure everyone is clear on what is going in. (We could also just have a policy that the PR title IS the release note, though this doesn't really leave room for multiple RN's or multiline things etc)

I agree that there's room for mistake / error / lost things. I suppose I'd argue that - as it is now, a day after a PR is merged we should basically assume we've lost all context on writing release notes for that feature / bug fix. The creator and the merger may be not around, they may not be contributing to release notes, they may not remember what API's they added or even remember a clear one-line description of the feature... It seems critical to capture as good information as is possible at the time of the check-in. There will always be editing / fixing up later on.

I think a policy that developers should do this as part of the commit / PR process encourages developers and reviewers to think carefully about the implications of what they're adding... If there are 10 tagged deprecations, or the testing notes include "retest every UGen", it provides a good chance to reflect on how to organize testing, how to deal with existing code, and/or whether the impact can be minimized with a little more massaging of code.

**Comment by telephon** [comment]
Could it perhaps be a simple procedure to add a specific set of flags to the PR? Then this can also be done after the commit itself, and perhaps even after the merge (?). You could toggle them off and on as well.

**Comment by scztt** [comment]
I tested earlier - doing it in the merge commit works. The only annoying thing is - you can only write the detailed comments when you actually do the merge. So, the workflow would require the person that merges the PR paste in the notes from e.g. the pull requesters provided description. You can't do it after the commit - but again, I wouldn't want that because it's REALLY best if done while the change is being looked at and discussed. Pushing it off till later is just creating work that someone has to do with less context, later on.

It would be super easy to extract these notes as part of the travis job and update some release notes on a wiki, so they would be live. I suspect there are probably non-dev users who would be interested in a high-level digest of changes going in as well.

**Comment by crucialfelix** [comment]
Here is the code I used to make the automated CHANGELOG.  

https://gist.github.com/crucialfelix/c37441a2381efbfe97fbcc8ca286f061

It was just about the only way to make 3.7 happen. Now that releases are closer together and people are actively preparing releases, you could manually do it. 3.7 was a different story; that was 3 years of "what happened?"

Any way you want to do it going forward is fine by me.

The automated one is not yet clean or perfect. It could still be used to dump markdown with the items and then manually edited.

A few notes though:
- Both closed Issues and Pull Requests are included. This does result in duplicates. The issues are usually not titled correctly. They have different viewpoints (what is wrong, what was changed to fix it)
- The text comes from the Issues/Pull-requests, not from the commit. The text can be edited at any time, you can even go back and revise past releases and re-generate the changelog.

**Comment by crucialfelix** [comment]
> Could it perhaps be a simple procedure to add a specific set of flags to the PR?

This is already the case. It is only included if it is assigned one of the active labels.

> because it's REALLY best if done while the change is being looked at and discussed. Pushing it off till later is just creating work that someone has to do with less context, later on.

In practice things get merged without being tagged correctly. It is easy to label and set milestones later and even to edit the title.

> Most major changes have multiple commits, or even spread across multiple PRs. Having release notes on individual commits seems to contradict the idea of collecting "descriptive, high-level" release notes.

Again - it is the pull request that is shown, not the commits.

```
classlib: Refactor some message syncing functionality.

@RELEASENOTE Improved server message bundling and sync functions.
@API Server:queueBundle, Server:sendSynchronized added
@DEPRECATED Server:schedSync removed (use Server:queueBundle instead)
@TESTING Test all Server messaging commands (sendMsg, sendBundle, etc). Ensure Server:sync works as expected.
```

Hmm. I don't think this is going to happen ;)  It would also make contribution harder. Even I would fail to include all that.

> The best I've seen has been from the Go project, see for example https://golang.org/doc/go1.7

That is lovely, but that is a very high profile and well funded project. Those people are professionals being paid solid salaries.

**Comment by danstowell** [comment]
I agree with everything @crucialfelix just said ;)

**Comment by scztt** [comment]
What about a non-pie-in-the-sky pragmatic starting point.... :) I just noticed that github supports pre-baked templates for both issues and pull requests - they auto-populate when you create a new PR.

What if we make a template with one or two fields that could easily be searched on, and then ask people to try to follow that when creating PR's, and see how it goes for the next release.

https://help.github.com/articles/creating-an-issue-template-for-your-repository/

**Comment by crucialfelix** [comment]
Also there is the well known angular commit message convention:

https://gist.github.com/stephenparish/9941e89d80e2bc58a153
https://github.com/conventional-changelog/conventional-changelog-angular/blob/master/convention.md

```
feat($compile): simplify isolate scope bindings

```

```
fix($compile): couple of unit tests for IE9

Older IEs serialize html uppercased, but IE9 does not...
Would be better to expect case insensitive, unfortunately jasmine does
not allow to user regexps for throw expectations.

Closes #392
Breaks foo.bar api, foo.baz should be used instead
```

Look down at the bottom for examples. They have really large commit bodies.

It's a whole movement and lifestyle now: https://github.com/conventional-changelog

**Comment by crucialfelix** [comment]
Templates would be good. I hate when they are too long though.

From my experience doing the merges I found that every single one needed tags, fixed explanations and titles. Even PR from core developers.

**Comment by crucialfelix** [comment]
I added a script that generates the contributors list:

https://gist.github.com/crucialfelix/c37441a2381efbfe97fbcc8ca286f061

```
/**
 * Prints contributors list sorted by number of issues and pull requests.
 * Closed issues and successfully merged pull-requests only.
 */
```

**Comment by snappizz** [comment]
I've started a changelog for 3.9 here, and to date maintaining it has required minimal, sporadic work: https://github.com/supercollider/supercollider/wiki/Changelog

I'm willing to consider automated systems, but I'm not convinced that they save any labor compared to simply Getting It Done :)

**Comment by snappizz** [comment]
I think we have enough momentum on the above wiki page to consider this taken care of. We can reopen if we want to consider moving to an automated system.
