### ISSUE TITLE
Pstep needs better documentation

### ISSUE THREAD

**Issue by kisielk** [supercollider/supercollider#2489]
The description of both the class and new seem totally opaque to me. The description simply states:

"Pstep is good for representing chord progressions, scale progressions, accent patterns, etc."

Which describes what it can be used for, but not what it does.

The description for the "new" method talks about "levelpattern" and "durpattern" which don't correspond to the names of the arguments (I assume they mean levels and durs, but that took a while to figure out).

**Comment by brianlheim** [comment]
This was fixed! (#2511)
