### ISSUE TITLE
collect on IdentityDictionary loses state variables

### ISSUE THREAD

**Issue by jamshark70** [supercollider/supercollider#2499]
```
e = (a: 1).parent_((b: 2));
f = e.collect(_+10);
-> ( 'a': 11 )

[e.parent, f.parent]
-> [ ( 'b': 2 ), nil ]
```

`f.parent == nil` seems wrong to me. I would assume "collect" would preserve state variables. 

So now, after https://github.com/supercollider/supercollider/commit/cce6208d9bc2292aac91a8521728a0d0ebbc63f7, the problem is, if a child pattern (such as, in Pchain) calls processRest on an Event, now it uses collect on the Event (which it didn't before), and this throws away the input event's parent.

```
p = Pchain(
	Pfunc { |ev| ev.parent.debug("parent 2"); ev },
	Pfunc { |ev| ev.parent.debug("parent 1"); ev }
).asStream;

e = p.next(().parent_((b: 2)));
parent 1: ( 'b': 2 )
parent 2: nil   // what the...???

e.parent;
-> nil   // what the...???
```

I think the proper fix is to implement "collect" for IdentityDictionary, separately from Dictionary, to migrate the proto and parent into the new dictionary. Possibly this should be done for select, reject etc. I could make a strong case that "collect" should have been doing this for years -- i.e., this bug has been there ever since the proto and parent variables were introduced, and nobody noticed because we don't usually collect on events with parents. 
 
But, this might have a performance impact on anything doing "processRest" on an Event. An alternate would be to define processRest as a no-op for events. It smells funny to me, so I would consider this a last resort, but it might be justifiable. 
 
(So this time, I kept my mouth shut until figuring out that it was my action that exposed the bug (though, if my analysis is correct, the bug is someone else's). But I will note that the trend holds: this bug is really spectacularly obscure -- over an hour to track down -- and I wonder how the hell it is that nobody besides myself has to waste so much time on things like this.)

**Comment by jamshark70** [comment]
> this bug has been there ever since the proto and parent variables were introduced

https://github.com/supercollider/supercollider/commit/e89082f212a45aeaf27e303335ea2f91194f3fbc
"add parent to IdentityDictionary"
Nov 16, 2003

*Thirteen* @#*$&#@&#$ years old bug. (To the day!)

**Comment by jamshark70** [comment]
Fixes it:

```
	collect { arg function;
		var res = this.class.new(this.size).parent_(parent).proto_(proto);
		this.keysValuesDo { arg key, elem; res.put(key, function.value(elem, key)) }
		^res;
	}
	select { arg function;
		var res = this.class.new(this.size).parent_(parent).proto_(proto);
		this.keysValuesDo { arg key, elem; if(function.value(elem, key)) { res.put(key, elem) } }
		^res;
	}
	reject { arg function;
		var res = this.class.new(this.size).parent_(parent).proto_(proto);
		this.keysValuesDo { arg key, elem; if(function.value(elem, key).not)
			{ res.put(key, elem) } }
		^res;
	}
```

**Comment by jamshark70** [comment]
Better:

```
	collect { arg function;
		var res = this.class.new(this.size, proto, parent, know);
		this.keysValuesDo { arg key, elem; res.put(key, function.value(elem, key)) }
		^res;
	}
	select { arg function;
		var res = this.class.new(this.size, proto, parent, know);
		this.keysValuesDo { arg key, elem; if(function.value(elem, key)) { res.put(key, elem) } }
		^res;
	}
	reject { arg function;
		var res = this.class.new(this.size, proto, parent, know);
		this.keysValuesDo { arg key, elem; if(function.value(elem, key).not)
			{ res.put(key, elem) } }
		^res;
	}
```

**Comment by telephon** [comment]
>I think the proper fix is to implement "collect" for IdentityDictionary, separately from Dictionary, to migrate the proto and parent into the new dictionary. 

Yes, agreed. There is a slight asymmetry here, which may have been the reason for it being not yet implemented (aka not yet decided).

```
a = (p: 9).parent_((q:10));
a[\q] // returns 10
b = a.collect(_ + 1);
b[\q] // still returns 10
```

I tend to think this is a documentation issue only.

Don't worry too much about `processRest`, we'll have to get rid of it anyhow …

**Comment by jamshark70** [comment]
> Yes, agreed. There is a slight asymmetry here, which may have been the reason for it being not yet implemented (aka not yet decided).

I don't think it was deliberately avoided - I think it was just never considered. The above-referenced commit is actually a fairly large one - I can't blame JMc for overlooking a small detail that escaped notice for 13 years.

> I tend to think this is a documentation issue only.

Yes, and it's consistent with other looping operations for Dictionary, which ignore parent and proto.

I'll submit a PR later, with the help update as well.
