### ISSUE TITLE
Class files can wrongly trigger "open-ended string" msgs

### ISSUE THREAD

**Issue by jleben** [supercollider/supercollider#251]
[Issue migrated from SourceForge | ID: 3488401 | Submitted by 'jamshark70']
[http://sourceforge.net/support/tracker.php?aid=3488401]

In a recent patch I posted to sc-users, to reduce the amount of function text that gets printed, initially I wrote:

if(tempStr.size >= 512) { out << "...etc...\"\n" };

But the compiler claims that this causes an open-ended string. It shouldn't, because the middle quote mark is escaped and shouldn't be treated as a delimiter, but for some reason, when compiling a class file, it breaks.

It seems to be an issue only if there is another string somewhere later in the class file.

Quote {
*test {
^"abc\"\n";
}
*test2 {
^"xyz"  // open-ended string is "started" here
}
}

If you remove *test2 completely (commenting it out might not be sufficient), there will be no open-ended string message.

Not urgent, I think. I'd hold off until post-3.5 (unless the fix is very easy).

**Comment by snappizz** [comment]
This appears to be fixed.
