### ISSUE TITLE
The repository 'http://ppa.launchpad.net/supercollider/ppa/ubuntu xenial Release' does not have a Release file.

### ISSUE THREAD

**Issue by jhw** [supercollider/supercollider#2513]
Hi,

Trying to upgrade from default 3.6 version of Supercollider on Ubuntu 16.04 to something that will run Tidal (3.7 or 3.8)

Following the instructions here

https://github.com/supercollider/supercollider/wiki/Installing-SuperCollider-on-Ubuntu-systems

But on

sudo apt-get update

I get the following

W: The repository 'http://ppa.launchpad.net/supercollider/ppa/ubuntu xenial Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: Failed to fetch http://ppa.launchpad.net/supercollider/ppa/ubuntu/dists/xenial/main/binary-amd64/Packages  404  Not Found
E: Some index files failed to download. They have been ignored, or old ones used instead.

??

Thanks in advance,

Justin

**Comment by jhw** [comment]
It seems there is no 'xenial' entry in the PPA

http://ppa.launchpad.net/supercollider/ppa/ubuntu/dists/

Is this repo not being updated for latest versions of Ubuntu ? Should I be installing 3.7/3.8 from source ?

Thx

**Comment by snappizz** [comment]
Right now the only option is to install from source, sorry :(

**Comment by ajyoon** [comment]
Who maintains the ppa? It's been years since it was last updated, and building from source involves all sorts of environment headaches. I'm 5 hours into trying to get this to work, and I'm sure I wouldn't be the first person to be turned off trying out sc due to the out-of-date ppa.

**Comment by vivid-synth** [comment]
@ajyoon I don't think anyone is actively maintaining the Ubuntu package. I agree we definitely don't want to lose people who want to work with SC because there's no package for it. Having up-to-date packages for the most popular Linux distros is something that's a priority for me. In the meantime, are there issues with building that aren't covered in https://github.com/supercollider/supercollider/blob/master/README_LINUX.md ?

**Comment by freckletonj** [comment]
(I'm in the same boat as OP nearly a year later. Thanks for all the hard work, of course, but I hope I don't struggle buildling myself for the next 5 hours :) )

**Comment by snappizz** [comment]
related issue #2917. i am working on debian packaging currently.

**Comment by brianlheim** [comment]
i haven't heard anything on this in a while. i don't know if it's still a problem, but probably a new ticket would be better at this point since there have been new releases of Ubuntu and SC in between.
