### ISSUE TITLE
focus lost on window switching

### ISSUE THREAD

**Issue by stahlnow** [supercollider/supercollider#2520]
Bug description: The text cursor focus is lost, when switching to another application.

Steps to reproduce:
1. place cursor in scide editor
2. switch to other application (chrome, sublime, ..)
3. switch back to scide

Actual result: text cursor is not visible and typing is not possible, pressing ESC brings focus back. but this cannot be the solution right?

Expected result: cursor should be visible and ready for typing.

Using: supercollider 3.9dev, qt 5.7.0, arch linux ^ gnome 3.22

**Comment by bagong** [comment]
Could you check whether it's gone with current master? I couldn't reproduce it any more (on both Linux and MacOS).

**Comment by patrickdupuis** [comment]
I can't reproduce this on current master in Fedora 25 with Gnome 3.22, or Ubuntu 16.04 with Unity or Gnome.

**Comment by stahlnow** [comment]
Can't reproduce it anymore. Maybe was some strange Qt problem.

**Comment by brianlheim** [comment]
thanks @stahlnow !
