### ISSUE TITLE
Server window GUI not reflecting activity in 3.8

### ISSUE THREAD

**Issue by bdwhiti2** [supercollider/supercollider#2521]
Hello!

As of 3.8.0, invoking either ~serverVariable.makeGui or ~serverVariable.makeWindow results in a Server window that will not reflect server and CPU activity (the widget in the IDE still works properly). This is particularly problematic when using multiple servers and/or a text editor rather than the IDE. I've encountered this problem in both OS X 10.9.5 and 10.12.1, and presume it is an issue across all versions of macOS that can run SC 3.8.

Cheers,

Benjamin

**Comment by jamshark70** [comment]
Known issue. A fix is in the works but waiting for code review.

**Comment by adcxyz** [comment]
closed with pull request #2422.
