### ISSUE TITLE
Update deprecated macros in scel

### ISSUE THREAD

**Issue by rukano** [supercollider/supercollider#2525]
The current version of scel gives some deprecated warnings for some macros

```
.emacs.d/private/supercollider/local/sclang/sclang-interp.el: ‘flet’ is an obsolete macro (as of 24.3); use either ‘cl-flet’ or ‘cl-letf’.
.emacs.d/private/supercollider/local/sclang/sclang-language.el: ‘flet’ is an obsolete macro (as of 24.3); use either ‘cl-flet’ or ‘cl-letf’. [2 times]
.emacs.d/private/supercollider/local/sclang/sclang-help.el: ‘flet’ is an obsolete macro (as of 24.3); use either ‘cl-flet’ or ‘cl-letf’.
.emacs.d/private/supercollider/local/sclang/sclang-server.el: ‘flet’ is an obsolete macro (as of 24.3); use either ‘cl-flet’ or ‘cl-letf’.
```

In general, some love for scel would be nice. :)

**Comment by snappizz** [comment]
Both scel and scvim suffer from a major developer shortage. I'm sorry, but you will probably have to fix this yourself if you want it resolved in a timely manner :(

**Comment by rukano** [comment]
I am working on it, and try to fix it. Just wanted to put it in the backlog o it doesn't just disappear until it's broken for all emacs users. :)

**Comment by jamshark70** [comment]
FWIW I quit using scel because the IDE's autocompletion and auto-indent are so much better. Improve that area and I might reconsider (because I'm starting to chafe against the IDE's lack of a snippets feature).

**Comment by widp** [comment]
This issue was moved to supercollider/scel#4
