### ISSUE TITLE
implement boot conflict handling strategies 

### ISSUE THREAD

**Issue by adcxyz** [supercollider/supercollider#2529]
@telephon, @snappizz, @crucialfelix  

Moving the discussion from #2524 here:
the branch topic-server-boot-recover, commit c45bf31 is a first implementation of the strategies failAndAsk, reboot, hijack, and useFreePort. 
Two little glitches remain to be fixed:
A hijacked server tends to think it is alive after a crash, 
and the reboot function runs twice for some reason. 

Nonetheless already testable and discussable :-), see
ServerRecover.openHelpFile;

**Comment by adcxyz** [comment]
@jamshark70 - I'd be curious what you think of this branch as a fix proposal for eternal server boot woes. I quite like the behaviors now, and it covers ca. 99.9% of all cases I can think of ;-)

**Comment by muellmusik** [comment]
@adcxyz can this be closed as it was handled in #2524?

**Comment by adcxyz** [comment]
none of it was merged anywhere, but so what, it wans't thought through fully. 
Should be easy to address when/if I manage to find time to do the ServerProcess refactor proposed in the ServerProcess issue #3310 ...
