### ISSUE TITLE
Import Decimator from sc3-plugins

### ISSUE THREAD

**Issue by snappizz** [supercollider/supercollider#2531]
Bitcrushing and decimation are pretty standard operations in electronic music production, and I personally use Decimator a lot. I don't feel too strongly about it, but can we consider moving it to core?

**Comment by vivid-synth** [comment]
I am definitely in favor of moving mature and frequently-used ugens to core. Should this be the first one we do? We should strenuously code-review, of course!

**Comment by vivid-synth** [comment]
I'd like to ask the original author about this - anyone know who the mysterious "krgn" is?

**Comment by redFrik** [comment]
Karsten Gebbert
last active here ~2009.
https://github.com/krgn
_f

> 8 jan 2017 kl. 05:34 skrev vivid-synth <notifications@github.com>:
> 
> I'd like to ask the original author about this - anyone know who the mysterious "krgn" is?
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 


  #|
     fredrikolofsson.com     musicalfieldsforever.com
  |#

**Comment by vivid-synth** [comment]
@krgn any objections?

**Comment by krgn** [comment]
Hi!
 
I have no objections whatsoever (and feel quite honored that you use it)! It's been a long, long time, but hey...

All the best!

Karsten

**Comment by snappizz** [comment]
On second thought, I'm not so sure this is worth it. There are two concerns I have with Decimator. The first is that it's not that hard to simulate with other UGens, and the second is that Decimator has no antialiasing.

It would be better to start with a new UGen with antialiasing, and maybe support for different kinds of bit reduction (linear, ulaw, alaw, maybe DPCM). Timing jitter would also be fun.
