### ISSUE TITLE
Use the new CommonTests location in Travis

### ISSUE THREAD

**Issue by snappizz** [supercollider/supercollider#2536]
After #2414 Travis needs to be updated.

**Comment by snappizz** [comment]
This is pretty important since we're starting to unit test most new PRs. I'm looking at [.travis/qpm-prep.sh](https://github.com/supercollider/supercollider/blob/master/.travis/qpm-prep.sh) and I don't see any obvious way to fix this. Anyone got ideas?

**Comment by telephon** [comment]
@snappizz is this fixed?

**Comment by snappizz** [comment]
@telephon doesn't seem to be

**Comment by snappizz** [comment]
dupe of #3132

**Comment by brianlheim** [comment]
oops, sorry
