### ISSUE TITLE
nowExecutingPath is improperly cleared by .stop'ping any Routine

### ISSUE THREAD

**Issue by jamshark70** [supercollider/supercollider#2540]
Save this in a document somewhere, and run the blocks.

```
(
c = Condition.new;
r = Routine {
	3.do { |i| i.postln; 1.yield; };
	c.hang;
	3.do { |i| i.postln; 1.yield; };
};

r.play;
)

// wait for it to hang, then:
(
thisProcess.nowExecutingPath.debug("before stop");
r.stop;
thisProcess.nowExecutingPath.debug("after stop");
)

before stop: /home/dlm/share/SC/scd/tests/thread-path.scd
after stop: nil
```

"after stop: nil" -- we are still executing a block in the same file! So `thisProcess.nowExecutingPath` should not have changed.

**Comment by jamshark70** [comment]
Simpler:

```
r = Routine { loop { 1.yield } }.play;

thisProcess.nowExecutingPath.debug("before stop"); r.stop; thisProcess.nowExecutingPath.debug("after stop");
```

**Comment by brianlheim** [comment]
Seems like the problem is in this area:
[PyrPrimitive.cpp](https://github.com/supercollider/supercollider/blob/f5d8917dbafe3c2f96ff6d774c72da0e0de0ab87/lang/LangPrimSource/PyrPrimitive.cpp):3349-3379

```
int prRoutineStop(struct VMGlobals *g, int numArgsPushed)
{
	PyrThread *thread;
	int state;
	//post("->prRoutineStop\n");
	//assert(g->gc->SanityCheck());
	//CallStackSanity(g, "prRoutineStop");

	thread = slotRawThread(g->sp);
	state = slotRawInt(&thread->state);


	if (state == tSuspended || state == tInit) {
/*!!*/		slotCopy(&g->process->nowExecutingPath, &thread->oldExecutingPath);
		SetNil(&g->thread->terminalValue);
		SetRaw(&thread->state, tDone);
		slotRawObject(&thread->stack)->size = 0;
```

As [this search](https://github.com/supercollider/supercollider/search?utf8=%E2%9C%93&q=oldExecutingPath&type=Code) shows, there's a grand total of **0** instances of `oldExecutingPath` ever being set to anything other than nil.

This suggests two possible solutions, and I don't have enough knowledge of the SC kernel to tell which is right.

1. Replacing `oldExecutingPath` with `executingPath` in the C++ snippet above might solve the issue, and since `oldExecutingPath` is never used, it can be safely deleted or deprecated.

2. `oldExecutingPath` might be able serve some useful function, and code can be added elsewhere so that the line marked `/*!!*/` does what it appears to do.

**Comment by brianlheim** [comment]
Well, I learned a valuable lesson today—don't trust GitHub's search engine. I found an instance of `oldExecutingPath` being set on [PryPrimitive.cpp:3237](https://github.com/supercollider/supercollider/blob/f5d8917dbafe3c2f96ff6d774c72da0e0de0ab87/lang/LangPrimSource/PyrPrimitive.cpp#L3237):

```
slotCopy(&thread->oldExecutingPath,&g->process->nowExecutingPath);
```

But this still appears to be the only time `oldExecutingPath` is set—at least in PyrPrimitive—and it happens within `prRoutineResume`, which is not guaranteed to be called when starting and stopping a routine. Again, I'm not sure about the logic of these fields, just sniffing out relevant code. :)

**Comment by telephon** [comment]
`_RoutineResume` is called in all those methods of Thread / Routine:

```// resume, next, value, run are synonyms
	next { arg inval;
		_RoutineResume
		^this.primitiveFailed
	}
	value { arg inval;
		_RoutineResume
		^this.primitiveFailed
	}
	resume { arg inval;
		_RoutineResume
		^this.primitiveFailed
	}
	run { arg inval;
		_RoutineResume
		^this.primitiveFailed
	}
```

Routine-play is delegated to the clock you (implicitly or explicitly) pass, and this will call `prTempoClock_Sched`. That might be a place to take a closer look at.

**Comment by telephon** [comment]
(but note that the above reproducer have the same issue with all kinds of clocks).

**Comment by jamshark70** [comment]
At first glance, the line marked /*!!*/ should probably just be deleted.

AFAIK oldExecutingPath is supposed to work like this:

- When the routine resumes, this variable saves the current process nowExecutingPath, so that nowExecutingPath can be set to the routine's executingPath.

- When the routine yields, the process nowExecutingPath should be restored.

That is, oldExecutingPath should have a value only when the routine's state is "running."

But, look below, prRoutineStop is forbidden from doing anything while in a "running" state. So, if we enter the branch that actually stops the routine, then the routine is already sleeping, and the exec path has already been restored, and it's a faulty assumption to think that "stop" needs to do it again.

**Comment by jamshark70** [comment]
For reference, https://github.com/supercollider/supercollider/commit/0d1ab3c04ed2e001be68bda58f978296d4bfb446.

And:
```
	} else if (state == tRunning) {
		error("Do not call .stop from within the Routine.\n");
		post("A Routine should stop itself using nil.alwaysYield.\n");
		return errFailed;
	} else {
```

I'm going to run SC for awhile with that line commented out and see if I find anything weird. It passes the simple test.

I think my analysis is correct, though. oldExecutingPath is valid only when `state == tRunning`.

**Comment by telephon** [comment]
It breaks `loadRelative`.

**Comment by jamshark70** [comment]
@telephon Thanks for reviving the issue. I've been running with my suggested fix for a month, and it's all fine. So I just put in a PR.
