### ISSUE TITLE
[Feature Request] supernova OSC endpoint to obtain version

### ISSUE THREAD

**Issue by samaaron** [supercollider/supercollider#2544]
It would be lovely if it was possible to send scsynth an OSC message such as `/version` and have it reply back with the version number.

**Comment by snappizz** [comment]
Sounds good. I think it should also identify itself as scsynth or supernova, so the reply to `/version` would look something like `/version scsynth 3.9dev`.

**Comment by snappizz** [comment]
Reopening this because the work isn't done for supernova.

**Comment by vivid-synth** [comment]
Supernova work here: https://github.com/supercollider/supercollider/pull/2598

**Comment by vivid-synth** [comment]
@samaaron this is good to go on master now
