### ISSUE TITLE
Some UnitTests make noise

### ISSUE THREAD

**Issue by vivid-synth** [supercollider/supercollider#2548]
Ha! While running `UnitTests.testAll` I started hearing some strange noises coming from my computer -- looks like the tests are really running :)

The sounds are reproduceable and play while these lines are being printed:

> PASS:a TestCoreUGens:test_muladd - "ar5.madd(ar5, kr2)"                                                                                
> PASS:a TestCoreUGens:test_bufugens - data->loadCollection->PlayBuf->RecordBuf->loadToFloatArray->data (1 channels)                     
> PASS:a TestCoreUGens:test_bufugens - data->loadCollection->PlayBuf->RecordBuf->loadToFloatArray->data (2 channels)                     
> PASS:a TestCoreUGens:test_bufugens - data->loadCollection->PlayBuf->RecordBuf->loadToFloatArray->data (8 channels)                     
> PASS:a TestCoreUGens:test_bufugens - data->loadCollection->PlayBuf->RecordBuf->loadToFloatArray->data (16 channels)                    
> PASS:a TestCoreUGens:test_bufugens - data->loadCollection->PlayBuf->RecordBuf->loadToFloatArray->data (32 channels)                    
> PASS:a TestCoreUGens:test_bufugens - data->loadCollection->PlayBuf->RecordBuf->loadToFloatArray->data (33 channels)                    
> PASS:a TestCoreUGens:test_demand - Duty should free itself after a limited sequence                                                    
> PASS:a TestCoreUGens:test_demand - Duty+LFTri should not output NaN                                                                    
> PASS:a TestCoreUGens:test_pitchtrackers - ZCR.ar() tracking a SinOsc

**Comment by snappizz** [comment]
It's music, man

**Comment by danstowell** [comment]
Not a bug.
The noises are nice.

**Comment by snappizz** [comment]
I'm fine either way.
