### ISSUE TITLE
Translating Supercollider GUI and Tutorials to other languages

### ISSUE THREAD

**Issue by tiagmoraismorgado** [supercollider/supercollider#2557]
guys, yesterday I was contributing to sonic pi. one of the things I notice they do there, and pretty well, is that they basically got a website that has binds to GitHub, and allows you to translate the whole software gui and documentation to other languages, with linkings to GitHub files. for this I should credit sam Aaron and his community. while this is still a bit of work to be done, and would take some time to get it finished, and then would have to get maintained across different iterations and reviews of supercollider development, you should definitely consider to open the possibility for the supercollider community to get it done, so that more people could you It, more easily. here's my tip. looking forward. tiago

**Comment by snappizz** [comment]
Good idea. Added to [long-term, large-scale projects](https://github.com/supercollider/supercollider/projects/2).
