### ISSUE TITLE
creating a lemur like set of easy to use controllers straight in the supercollider environment

### ISSUE THREAD

**Issue by ghost** [supercollider/supercollider#2558]
Hey guys. I have been working in this repository for past two months. https://github.com/tiagmoraismorgado/TMM_QML_UI_UX_FRAMEWORK_ALPHA_0_0_1 my goal here was to provide some kind of lemur like controllers, that could be instantiated straight from the user code of another application. so for an instance let's say that I have like a slider implemented in qtqunck there, and by doing so, it can do basically be associated with a parameter in the supercollider code you are running. would be nice to wrap the ui work I did there. and getting a possibility of instantly creating the ui element straight in supercollider. looking forward

**Comment by telephon** [comment]
you could get in touch with @adcxyz @sensestage @woutersnoei  et al of the modality group: http://modalityteam.github.io/team/

**Comment by sensestage** [comment]
Seems like a candidate for a quark.
referenced repo does not exist anymore though.
