### ISSUE TITLE
re-designing the supercollider UI using qtquick in qml (gpu accelerated currently via OpenGL, Vulkan Render coming soon)

### ISSUE THREAD

**Issue by tiagmoraismorgado** [supercollider/supercollider#2559]
hey guys. it's clear that Jakob Leben, an ex-colleague of mine from the sonology department, did a terrific work porting the whole supercollider User Interface, to QT, while he was still in sonology. that was all actually pretty cool. but remember one thing, he didn't take advantage of QtQuick, and QtQuick, despite being a bit harder to user, but even though pretty easily, is gpu accelerated and allows you to do some really amazing things out of it. so I was considering to suggest you guys to: re-designing the supercollider UI using qtquick in qml (gpu accelerated currently via OpenGL, Vulkan Render coming soon). I already opened an issue, containing a link to a repository I created, containing some ui elements, that could be used to create a lemur like controller that we could instantiate and get some nice controllers for supercollider straight in the ui, but it would be nice if the whole ui would be based in qtquick. I am willing to help you guys with that. cheers

**Comment by novadeviator** [comment]
in those last years when Jakob was quite active and already done the work with IDE and stuff he was very excited about QML and how it is much more simple than current SC GUI framework. browsing his repos, sometime ago already spotted his repo called quickcollider: https://github.com/jleben/quickcollider 
perhaps it is of use.

**Comment by timblechmann** [comment]
i'd recommend using a synchronous approach of loading a qml file into a view and bind sclang getters/setters to qt properties of the qml engine.
qtcollider has most of the sclang/qt binding magic implemented already and i'd recommend do build it into qtcollider rather than using a separate process (as jakob has done in quickcollider). mainly to allow synchronous access from sclang to qml (sclang lacks abstractions to hide the asynchronous communication in a synchronous interface (in futures)) and do avoid the need of handling subprocesses.

--

i have a fair amount of experience with using qml in a similar context (https://www.native-instruments.com/en/products/komplete/effects/replika/) and while i won't do any coding, i can do some consulting for the project.

**Comment by tiagmoraismorgado** [comment]
@timblechmann  all insight you may provide is more then welcome. i am currently in the process of re-organizing myself so when i have time to finish a couple of things. like a work for a violinist friend, shipping some recordings of my label, etc. working on some proejcts, and preparing a gig in late december. i will then definetely want to grab this framework i've been working on, and at least making a couple of bindings with the supercollider user interface. bearing this in mind, all your feedback is more then welcome. looking forward. kind regards

**Comment by LucaDanieli** [comment]
Scott Wilson, Scott Carver and I were right now developing the actual IDE to support multi-windows in SuperCollider. We were approaching this by improving the Document management ( https://github.com/supercollider/supercollider/pull/2555 ) and the next step would have been directed to add multi-windows support.

This would become and improved version of the 2014 commit: https://github.com/LucaDanieli/supercollider/tree/Rework-Splits

Should we pause to start considering qtquick, or would we be able to develop simultaneously both projects? @muellmusik

**Comment by tiagmoraismorgado** [comment]
@LucaDanieli probably developing both projects simultaneously would be a good idea, and integrating the qtquick thing in the multi-windows thing. looking forward. kind regards, tiago.

**Comment by brianlheim** [comment]
closing as it seems this has gone stale, and there doesn't seem to be an 'issue' here that we can actually work on
