### ISSUE TITLE
links in qt Help browser are broken when using Emacs

### ISSUE THREAD

**Issue by novadeviator** [supercollider/supercollider#2564]
When opening QT help browser from Emacs using Help.gui; (or C-c h), the help browser open, but many (not all) links simply do not work. When clicked they just get round dashed border but the browser does not load target. Using Quick Lookup search on top works, taking you directly to the Help page of specific Class if it exists. On the search page links do not work.

If Help is started from SC IDE links work as they should.

James Harkins @jamshark70  via mailing list explained it as:
> A link to another help file works if the target help file has already
> been rendered and its .html file is cached under
> Platform.userAppSupportDir +/+ "Help." If the link target isn't
> cached, then the Help GUI is supposed to render the .schelp before
> going to the link. Currently, that isn't happening: the webView's
> onLinkActivated is not called at all, so SC has no chance to
> intervene and create the target html file.

**Comment by jamshark70** [comment]
Closing b/c #2565 is a more precise and more actionable issue description. Thanks for the report.
