### ISSUE TITLE
Supercollider installer - add setup wizard

### ISSUE THREAD

**Issue by ghost** [supercollider/supercollider#2580]
Heyho!!! It would be cool if we could actually could bring in a setup wizard, which is as cool and easy to use, for all the operative systems, just like Sam Aaron did with sonic pi for mac, which allows you to costumize your installation process, tweak some options during the installation process, including languages, if we manage to get supercollider translated, and options within the software configuration itself, links to quarks repositories, etc.. looking forward to hear feedback from you guys. Kind regards. tiago

**Comment by crucialfelix** [comment]
What options are to be configured ?

I think all of these are things you can only configure after you have used the software and moved on to an advanced usage.

**Comment by tiagmoraismorgado** [comment]
this could go like:
- having pre-made settings for editor etc, that you could preview during the installation process, and use as your installation defaults;
- having different installation sizes, that could be both fixed and adjustable depending on the quarks installed by default (so, you could have small, mid, large size, and custom, and custom you could choose which quarks to install by default)
- being able to choose supercollider language (future, whenever things get translated)
- other features
