### ISSUE TITLE
implementing some pfft gpgpu ugens for supercollider

### ISSUE THREAD

**Issue by tiagmoraismorgado** [supercollider/supercollider#2585]
greetings
it could be interested if gpgpu ugens could be implemented in supercollider. this could be about:
- having some gpgpu accelerated pfft filters;
- having a powerful pfft convolution reverb gpgpu accelerated with advanced physics
i have forked a couple of repositories where you can actually see some pfft transformations being used for things like water see generation. it could be interesting if we could these algorithms, to convert sound into an fft image matrix, processing it and then getting it back to sound. looking forward. kind regards

**Comment by tiagmoraismorgado** [comment]
https://github.com/ikarienator/webgl_fft
https://github.com/29rou/2d_fft_with_C_AMP

**Comment by snappizz** [comment]
Sorry, but for the time being I'd say no. We have a UGen API that allows third parties to develop such things. It's a nice idea for a project that could be built *on* SuperCollider, but I don't see a strong argument that it should be *part* of SuperCollider.

Once a plugin making use of the GPU has already been developed separately from SC, then we may consider incorporating into core if the work is well done and proves potentially useful to a lot of SC users. But for now, this proposal is too far disconnected from our current development path, and some independent progress needs to be made first before it's worth discussing.
