### ISSUE TITLE
Isolated bug, possibly non-reproducible: Pitch.kr stopped working, until server reboot

### ISSUE THREAD

**Issue by esluyter** [supercollider/supercollider#2586]
I just hit a weird bug where suddenly my code stopped working, and I traced it to a Pitch ugen. I'm still on 3.8.0-beta1 so if this resulted from something that has been fixed already, apologies. I'm running it on Mac OS X 10.11 (15A284)

Before I rebooted the server, executing e.g. this line
`{ Pitch.kr(SinOsc.ar(550)).poll; }.play`
would result in a series of
```
UGen Array [0]: 440
UGen Array [1]: 0
...
```

After reboot, it behaved normally:
```
UGen Array [0]: 440
UGen Array [1]: 0
UGen Array [0]: 548.845
UGen Array [1]: 1
UGen Array [0]: 548.846
UGen Array [1]: 1
...
```

**Comment by snappizz** [comment]
Very odd, I've never seen a bug like this. I don't see anything special in the Pitch source code that would make this happen.

The calc function appears to be calling, but it's acting as if you're just feeding silence into Pitch.

**Comment by esluyter** [comment]
Just to note, other ugens behaved, sounded, and polled normally, so it wasn't like the server just stopped processing audio or anything like that.

Also to note, in case this has anything to do with it, I was working in a ProxySpace when this began, and this was the offending code:
`~freq = { var in = ~sig.ar; Pitch.kr(in[0])[0] };`

Then, I was able to reduce the issue to the line I posted above.

**Comment by snappizz** [comment]
I found something suspicious in the code. The median filter size is [incorrectly set from the input audio instead of the `median` argument](https://github.com/supercollider/supercollider/blob/28713cd79e212c0cdd9b6efd18a4eda83fec46bc/server/plugins/DelayUGens.cpp#L1789). I don't see any possible causal connections with this issue, however.

**Comment by telephon** [comment]
can you still reproduce it?

**Comment by esluyter** [comment]
I've never been able to since that one time.. probably safe to close it

Eric Sluyter
http://www.ericsluyter.com/

**Comment by brianlheim** [comment]
Thanks for the update, @esluyter. Feel free to reopen if you find a way to reproduce!

**Comment by vivid-synth** [comment]
@snappizz you note that

```
The median filter size is incorrectly set from the input audio instead of the median argument. 
```

Should we make a separate ticket for this?

**Comment by snappizz** [comment]
yes please

**Comment by snappizz** [comment]
more evidence that something is wrong with Pitch: http://new-supercollider-mailing-lists-forums-use-these.2681727.n2.nabble.com/Pitch-hasFreq-broken-from-sc3-8-td7637215.html

**Comment by brianlheim** [comment]
Not enough info here and nabble link is broken, please reopen if there is more to act on.
