### ISSUE TITLE
incorrect documentation on how to build standalone sc app for mac

### ISSUE THREAD

**Issue by precabal** [supercollider/supercollider#2593]
In the `standalones.schelp` there is a section explaining how to build a standalone app based on a template for an xcode project, supposedly located at: `platform/mac/Language.xcodeproj`, however, there is no such file, at least in 3.7.1 and 3.8 releases.

**Comment by precabal** [comment]
investigating the commit log, I can see the `Language.xcodeproj` file is gone in the commit from version 3.6.6 to 3.7.0

**Comment by telephon** [comment]
https://gist.github.com/adcxyz/81c6be8cda432b222e4aea3a97406a55#file-making_a_standalone_w_3-7-0-scd

**Comment by vivid-synth** [comment]
@precabal ^^

**Comment by precabal** [comment]
thanks @telephon, will try that out!

**Comment by adcxyz** [comment]
Hi @precabal, 
I guess this issue is obsolete now? 
There is a newer helpfile for making a standalone, and the Standalone quark ...

**Comment by snappizz** [comment]
closing as stale
