### ISSUE TITLE
Improve unit test coverage of UGens

### ISSUE THREAD

**Issue by snappizz** [supercollider/supercollider#2595]
What are some short-term goals to aim for when improving our unit tests? What problems and insufficiencies are most important?

**Comment by vivid-synth** [comment]
- It seems like UGen coverage is a big one -- maybe the biggest
  - Maybe we should have a goal of adding unit tests to test for correct behavior whenever we fix bugs

**Comment by snappizz** [comment]
Closing because this is more of a vague long-term project than an issue.
