### ISSUE TITLE
WARNING:  server 'localhost' not running.  nil

### ISSUE THREAD

**Issue by jleben** [supercollider/supercollider#260]
[Issue migrated from SourceForge | ID: 3510997 | Submitted by 'georgnik']
[http://sourceforge.net/support/tracker.php?aid=3510997]

I used supercollider 3.4 for windows before and i didnt have any problem.now i installed the version 3.5 for windows and the most of the time the local host server reports that error at once when i do the evaluation, even the button boot is pressed:
WARNING:
server 'localhost' not running.
nil

Sometimes it works but if i press Quit and then Boot again, then always reports that error again.
i am using windows xp sp3,but when i tried it for windows 7 in another machine,i didnt have any problem and it works perfectly there.
Does anyone know,how to solve this in xp?
thanks

**Comment by bagong** [comment]
This was the most serious Win XP bug in the past. It may rest peacefully with XP support :)

**Comment by bagong** [comment]
Closed as Windows XP support is dropped
