### ISSUE TITLE
[Feature Request] enable boot with mismatched in/out rates on macOS

### ISSUE THREAD

**Issue by samaaron** [supercollider/supercollider#2608]
One of the main causes of boot failure for Sonic Pi on macOS is scsynth failing to boot due to mismatched audio in and out rates:

```
input and output sample rates do not match. 44100 != 48000
```

We already attempt to mitigate this by detecting when the rates aren't the same and trying to ask the OS to set them to a similar value. However, many users use Bluetooth and USB headsets that only allow very low input rates and are therefore completely incompatible with scsynth as it currently stands.

Ideally, scsynth could be modified to automatically handle and do rate conversion on the fly in the cases the rates don't match. However, it is likely that this is not trivial.

The main usecase for scsynth within Sonic Pi is for the generation of audio - input is available but is rarely used by the majority of users. Would it therefore be possible to enable input to be completely disabled on boot. There is already a feature that allows input channels to be optionally enabled/disabled via the `-I` flag. However, when setting this to all zeros, scsynth still fails to boot. 

Would it be possible to have a flag which disables *all* input and therefore bypass any rate mismatch issues?

**Comment by samaaron** [comment]
Note that setting `-i 0` doesn't appear to help either. Perhaps a new flag isn't necessary - but if the user specified 0 inputs via `-i 0` then the input could be completely disabled?

**Comment by samaaron** [comment]
@snappizz this appears to work splendidly. With this patch, I can now boot scsynth with mismatched in and out audio rates and the input appears to be disabled as expected. :-)

**Comment by vivid-synth** [comment]
@samaaron should be good to go

**Comment by vivid-synth** [comment]
(I assume we're not trying for the loftier work-with-mismatched sample rates? If so we can reopen)

**Comment by samaaron** [comment]
For the Sonic Pi booting issues I've observed in the wild related to this issue - this work-around is perfectly sufficient (and I've even implemented a fix assuming `-i 0` ignores mismatch errors).

Thank-you so much to everyone who helped fix this :-)

**Comment by snappizz** [comment]
I'm curious what other macOS audio software programs do with mismatched SRs.

**Comment by scztt** [comment]
@snappizz Most pro audio applications have an explicit sample rate, which they request and causes the driver to change. I think CoreAudio can give you freebee sample rate conversion if you work at a slightly higher layer than SC, but obviously we don't want another layer (nor do we want SRC).

SuperCollider only really exhibits this problem when you don't specify the SR. It would be SLIGHTLY better IMHO to lock in an explicit sample rate, since the auto switching can lead to some unexpected + hard to diagnose (mis)behaviors -- especially for users who don't know (case in point: sample playback without BufRateScale... if something changes your SR, then your samples will magically play back at a different rate than they did last time).

**Comment by rseymour** [comment]
If supercollider could automatically give up on input (printing an error) if they were mismatched it would be a much better user experience for folks using ever more present bluetooth mic/headphone setups.  Those often have hardcoded (aka based on the bluetooth spec) input rates so the only option is opening up the startup file and turning off input anyway.  It could be more useful to just drop it for most users.

**Comment by jamshark70** [comment]
> If supercollider could automatically give up on input (printing an error) if they were mismatched it would be a much better user experience for folks using ever more present bluetooth mic/headphone setups.

That's not necessarily a bad idea.

I can think of a couple of use cases to handle:

- "I don't care about audio input, just boot the server with minimum fuss."

- "My code depends on input; if there's no input, I need to know about it programmatically."

Currently we don't always meet the first requirement, but we do meet the second (server fails to boot). The proposal to boot anyway if no input, or mismatched input rate, would meet the first and break the second (unless it's off by default, but then that doesn't count as "minimum fuss").

One alternative would be to include the number of active input and output channels in the `/status.reply` message. Then, if input is a problem, report 0 input channels. The user then has the opportunity to check whether enough inputs are open.

For new users, I think it's fair to say that the I/O requirements are possibly too strict. But many users have use cases that *are* strict, and we shouldn't leave those with "at your own risk." Allowing failure to be detected programmatically might be a good balance.
