### ISSUE TITLE
ide opens new tab far away

### ISSUE THREAD

**Issue by telephon** [supercollider/supercollider#2612]
I don't know if this is solved in some pending PR, but in the IDE, when making a new document it opens in a tab not next to the currently selected document, but after the very last document. This makes navigation more complicated than necessary because it separates (usually) related documents.

**Comment by telephon** [comment]
This is still an issue, I find.

**Comment by telephon** [comment]
and even after forgetting it, it still is :)

**Comment by gusano** [comment]
@telephon you mentioned firefox behaving correctly, on linux, new tab are placed at the end on the right :)

**Comment by telephon** [comment]
ah really. Maybe report it as a bug on Mozilla ? :)
