### ISSUE TITLE
Object:perform crashes when selector is an Array whose first element is not a Symbol

### ISSUE THREAD

**Issue by snappizz** [supercollider/supercollider#2615]
Okay:

    2.perform("") // -> ERROR: perform selector not a Symbol or Array.
    2.perform([]) // -> ERROR: Array must have a selector.

I didn't know you could do this, and it's undocumented, but I guess it's okay:

    2.perform([\squared]) // -> 4
    2.perform(['+', 2]) // -> 4

This is definitely not okay:

    2.perform([0]) // crash!

**Comment by brianlheim** [comment]
Offending code is [here](
https://github.com/supercollider/supercollider/blob/f5d8917dbafe3c2f96ff6d774c72da0e0de0ab87/lang/LangPrimSource/PyrPrimitive.cpp#L1491):

```
listSlot = selSlot;
if (slotRawObject(listSlot)->classptr == class_list) {
	listSlot = slotRawObject(listSlot)->slots;
}
if (NotObj(listSlot) || slotRawObject(listSlot)->classptr != class_array) {
	goto badselector;
}
PyrObject *array = slotRawObject(listSlot);
if (array->size < 1) {
	error("Array must have a selector.\n");
	return errFailed;
}
selSlot = array->slots;
selector = slotRawSymbol(selSlot);
```

When the first arg is an array, `objectPerform` only checks that the array is non-empty, and then attempts to use the first slot as a raw symbol.

**Comment by snappizz** [comment]
None of these crash the interpreter:

```
0.performList([0], [])
0.performWithEnvir([0], ())
0.performKeyValuePairs([0], [])
0.tryPerform([0])
0.superPerform([0])
0.superPerformList([0], [])
0.multiChannelPerform([0])
```

As far as I can tell, the problem is restricted to Object:perform.
