### ISSUE TITLE
sysex out on windows must be sent in a single command

### ISSUE THREAD

**Issue by zazze** [supercollider/supercollider#2622]
Sysex MIDI out does not work on Windows build 3.8.0

The following code works nicely on MacOS, e.g. the first line on the LCD on Ableton Push get updated.

`
// Use for MacOS
//m = MIDIOut.newByName("Ableton Push", "User Port");

// Use for Windows 10
m = MIDIOut.newByName("MIDIOUT2 (Ableton Push)", "MIDIOUT2 (Ableton Push)");

// Write to first row
(
m.sysex(Int8Array[240, 71, 127 , 21 , 24 , 0 , 69 , 0]);
m.sysex('Welcome to       '.ascii.as(Int8Array));
m.sysex('Supercollider!   '.ascii.as(Int8Array));
m.sysex('Let\'s test some  '.ascii.as(Int8Array));
m.sysex('ASCII signs:      '.ascii.as(Int8Array));
m.sysex(Int8Array[247]);
)
`
Johan

**Comment by llloret** [comment]
This is because of how sysex is handled by the underlaying portmidi library and how it is being used.

It works if instead of sending the message in portions, it is sent in just one sysex command. This was confirmed by the original reporter after I asked him to test that.

@snappizz, would that be ok as a workaround?

**Comment by llloret** [comment]
Well, in fact, instead of calling it a "workaround", what I would suggest is updating the docs, so that the expected way to use sysex (at least under Windows) is issuing just one function call with the full message.

**Comment by snappizz** [comment]
Good to hear. As long as there is a way to send sysex on Windows, this is just a doc issue.

Would be nice if there was some way to fix it, but this is no longer high priority because the functionality isn't completely blocked.

**Comment by llloret** [comment]
I will document it

**Comment by llloret** [comment]
Hi, I have made a PR that documents this requirement. Can someone check and pull it?

Thanks
