### ISSUE TITLE
[Qt] UserView doesn't pass click count for control clicks

### ISSUE THREAD

**Issue by jleben** [supercollider/supercollider#263]
[Issue migrated from SourceForge | ID: 3516996 | Submitted by 'cruxxial']
[http://sourceforge.net/support/tracker.php?aid=3516996]

w = Window.new;
w.front;
u = UserView(w);
u.background = Color.rand;

u.mouseDownAction = { |uvw, x, y,modifiers, buttonNumber, clickCount|

[uvw, x, y,modifiers, buttonNumber, clickCount].debug;
};

all other modifiers seem to work fine,
but with control you cannot double click

**Comment by scztt** [comment]
This is fixed in Qt5 on mac, with all mod key combinations. @crucialfelix wanna close?

**Comment by crucialfelix** [comment]
If you confirmed it fixed then yes.

**Comment by crucialfelix** [comment]
yep, fixed
