### ISSUE TITLE
sccode.org and PatchStorage integration

### ISSUE THREAD

**Issue by snappizz** [supercollider/supercollider#2640]
Towards a more user-friendly SCIDE, there should be easy ways to submit code to either of these sites.

**Comment by telephon** [comment]
… and to retrieve from them?

**Comment by snappizz** [comment]
Sure. For a concrete proposal, there should be a menu item titled "Submit code to PatchStorage/sccode," which opens a browser window to the relevant submission form with the code already entered.

**Comment by brianlheim** [comment]
http://patchstorage.com/developers/

Doesn't look like PatchStorage's API handles uploading patches yet. Anyone know if they're planning to implement that? And does sccode even have an API?

**Comment by telephon** [comment]
@LFSaw has it?

**Comment by LFSaw** [comment]
AFAIK, sccode does, yes... but its long ago that I tried it... Check with @vividsnow  ; I believe, he did the sccode stuff.

**Comment by snappizz** [comment]
chicken-and-egg problem i guess, but there hasn't been an upload from the SC community to patchstorage in nearly a year. closing due to lack of interest.
