### ISSUE TITLE
simplify Mix implementation

### ISSUE THREAD

**Issue by telephon** [supercollider/supercollider#2642]
Mix can be implemented as sum. 

Here is a test:

```

x = { |n| SynthDef(\test, { Out.ar(0, Mix({ SinOsc.ar }.dup(n))) }) };
y = { |n| SynthDef(\test, {  Out.ar(0, { SinOsc.ar }.dup(n).sum) }) };

x.(1).children // [ a SinOsc, an Out ]
y.(1).children // [ a SinOsc, an Out ]

x.(2).children // [ a SinOsc, a SinOsc, a BinaryOpUGen, an Out ]
y.(2).children // [ a SinOsc, a SinOsc, a BinaryOpUGen, an Out ]

x.(3).children // [ a SinOsc, a SinOsc, a SinOsc, a Sum3, an Out ]
y.(3).children // [ a SinOsc, a SinOsc, a SinOsc, a Sum3, an Out ]

x.(4).children // [ a SinOsc, a SinOsc, a SinOsc, a SinOsc, a Sum4, an Out ]
y.(4).children // [ a SinOsc, a SinOsc, a SinOsc, a SinOsc, a Sum4, an Out ]

x.(5).children // [ a SinOsc, a SinOsc, a SinOsc, a SinOsc, a Sum4, a SinOsc, a BinaryOpUGen, an Out ]
y.(5).children // [ a SinOsc, a SinOsc, a SinOsc, a SinOsc, a Sum4, a SinOsc, a BinaryOpUGen, an Out ]

x.(6).children [ a SinOsc, a SinOsc, a SinOsc, a SinOsc, a Sum4, a SinOsc, a SinOsc, a Sum3, an Out ]
y.(6).children [ a SinOsc, a SinOsc, a SinOsc, a SinOsc, a Sum4, a SinOsc, a SinOsc, a Sum3, an Out ]

```

All are the same.

One difference is:

```
x = { |n| SynthDef(\test, { Mix({ SinOsc.ar }.dup(n)) }) };
y = { |n| SynthDef(\test, { { SinOsc.ar }.dup(n).sum }) };

x.(3).children // [ a SinOsc, a SinOsc, a SinOsc, a Sum3 ]
y.(3).children // nil
```
So when using `sum`, the pure ugens (without side effects) are getting optimized away.

For non-pure ugens, the optimization is correct:

```
y = { |n| SynthDef(\test, { { Line.kr }.dup(n).sum }) };
y.(3).children // [ a Line, a Line, a Line ]
```

**Comment by telephon** [comment]
But, as I just tested, the UGen build phase is more efficient with `Mix`.

```
bench { x.(80) }; // 0.0047
bench { y.(80) }; // 0.0177
```

So this is definitely an argument against the change.

**Comment by telephon** [comment]
… although the result can sometimes be better when you use `sum`:

```

x = { |n| SynthDef(\test, { Out.kr(0, Mix(f.dup(n))) }) };
y = { |n| SynthDef(\test, {  Out.kr(0, f.dup(n).sum) }) };


f = { |i| [2, 3, 4, 5, 6, Line.kr, SinOsc.ar] @@ i };
x.(6).children.collect { |x| [x, x.rate] }.do(_.postln)
y.(6).children.collect { |x| [x, x.rate] }.do(_.postln)


f = { |i| [ SinOsc.ar, 2, 3, 4, 5, 6, Line.kr, SinOsc.ar] @@ i };
x.(6).children.collect { |x| [x, x.rate] }.do(_.postln)
y.(6).children.collect { |x| [x, x.rate] }.do(_.postln)

``

Here, `sum` just sums numbers instead of making a `Sum3` UGe for them.

**Comment by telephon** [comment]
this could be improved by adding a check in the `Sum3` UGen.

**Comment by scztt** [comment]
It seems like a separate but good optimization to automatically sum constant values at build time when they're present in Sum3 and Sum4.

**Comment by snappizz** [comment]
As discussed at last week's meeting, let's make sure we stringently unit test any changes to SynthDef optimization.

**Comment by jamshark70** [comment]
Is anyone thinking risk/effort vs benefit?

The benefit of this change has not been well established.

We don't know if it will affect existing user code.

While we're stringently unit testing (as Nathan is correct to insist on), we aren't working on other, more pressing problems.

My gut feeling is that this PR, though "interesting" in some ways, is not especially useful.

**Comment by telephon** [comment]
The whole thing really was just an easy way to get rid of duplicate implementations, because this reduces maintenance and explanation efforts. The result is subtle though.

>It seems like a separate but good optimization to automatically sum constant values at build time when they're present in Sum3 and Sum4.

That is what I would do.

**Comment by telephon** [comment]
Feel free to reopen if desired.

**Comment by jamshark70** [comment]
I'll admit, I was perhaps a bit too negative, but motivated by the Americanism "If it ain't broke, don't fix it." I don't think any one person (myself) should stifle innovation, but we have no shortage of open issues with active user impact. This is one place, in commercial software companies, where a program manager would mark it as super low priority and move on.

That `sum` is slower gives me pause. My last finished work mixes a *lot* of oscillators in one SynthDef, and SynthDef building was slow enough. It strikes me as a wash: easier maintenance, offset by impaired performance.

**Comment by telephon** [comment]
your opinion is always welcome! I just decided that beauty-in-simplicity isn't really important in this case as much as efficiency. The main issue is that `Mix` leaves unnecessary UGens, so that is something to fix. I don't think it's hard.

**Comment by timblechmann** [comment]
`Mix` generates the `Sum3` or `Sum4` ugens explicitly while `.sum` will only do this in the ugen graph optimisation phase, which is much slower, as the ugen graph will have to be rewritten, which is super-slow.
this is especially important when compiling large synthdefs with a lot summing/mixing. 

the class library implementations for muladd or binary operators do similar things

**Comment by telephon** [comment]
@timblechmann yes, that is better. Only that the `SumN` ugens are also created when they are not needed, that is if there are numbers to be added, or when the output of a pure ugen is never used. I admit that this is not such a common case, however, so I'm fine with how it is.
