### ISSUE TITLE
If environment uses SVG-logo for SC-IDE, it is very tiny in some cases (Gnome, KDE, MacOS)

### ISSUE THREAD

**Issue by patrickdupuis** [supercollider/supercollider#2646]
![scide_tiny_icon](https://cloud.githubusercontent.com/assets/11747870/21961542/3ab64d38-dada-11e6-96c4-d054ea6c5f40.png)

I just built latest SC on Fedora 25 (GNOME 3.22). Looks like SCIDE's icon shrunk a bit...

It has the correct size in the application launcher. Not so in the side bar (shown in picture), the alt-tab window switcher, or in the SCIDE->Help->About SuperCollider window.

**Comment by bagong** [comment]
Hahaha, this - as a side-effect - is fixed in the cmake_sclang_flag PR. Same problem on Mac if scide is used outside of the application bundle:

https://github.com/supercollider/supercollider/pull/1939

Some environments seem not to play well with the SVG-icon added for scide.

You could try it ;)

**Comment by patrickdupuis** [comment]
That fixed it! 

Now, how do I close this issue?

**Comment by bagong** [comment]
Hahaha, everybody can close her own issue ;)

Hey, it would be great if you reported on your experiences with that PR in the respective thread. It's a quite longstanding PR into which lot's of work went. Please, if you find time, let us know about issues that you find. Also success feedback is useful! Thanks! (did you try tooltip?)

**Comment by bagong** [comment]
I'll reopen this, we have better info on how to fix this in a less invasive manner ;) At the end of:

https://github.com/supercollider/supercollider/pull/2769

Not a show stopper, but an easy fix in things esthetics, it seems ;)

**Comment by patrickdupuis** [comment]
What needs to be done?

**Comment by bagong** [comment]
Look at susnux's last comment in the linked thread on OpenSuse, the line reading "If I slightly change the svg (adding <g>...</g> around all the <use... (diff.patch.txt) it works..". Might be enough to apply the patch.

**Comment by patrickdupuis** [comment]
Just an update to say that my system has begun experiencing this issue again.

**Comment by snappizz** [comment]
any reason why SCIDE logo is different from SuperCollider cube logo?

**Comment by patrickdupuis** [comment]
it's because scide and scsynth are different applications :p

Scide was not adopted right away. A lot of users preferred using the old OSX multi window cocoa environment. At first, it must have made sense to treat scide as a separate app with a different logo. Things are different now. Maybe we can have a discussion about the logos in the near future?

**Comment by telephon** [comment]
the main reason for keeping two distinct logos is that they visually represent running processes, e.g. on macos where they appear in the dock.

**Comment by kisielk** [comment]
I didn't understand it at first, but it's very handy to have two distinct icons especially on OSX. It makes it easier to switch focus between the IDE and any Qt windows that may have been spawned.

**Comment by patrickdupuis** [comment]
It's interesting to note that the cube icon appears in the correct size.

**Comment by noahadvs** [comment]
> ![scide_tiny_icon](https://cloud.githubusercontent.com/assets/11747870/21961542/3ab64d38-dada-11e6-96c4-d054ea6c5f40.png)

This is still a problem.

**Comment by brianlheim** [comment]
fixed in #4859, thanks @noahadvs !
