### ISSUE TITLE
Configurability of file watcher

### ISSUE THREAD

**Issue by jamshark70** [supercollider/supercollider#2650]
The part of the IDE that watches for changes to files currently open in an editor tab is too "pushy." Frequent occurrence for me: I change to another branch in some git repository, causing an open file to change on disk. ScIDE *immediately* leaps to the front because **OMG OMG something happened! something happened! you have to stop what you're doing and take care of it right this second** -- meanwhile, I was just thinking about what I needed to do with git and I do *not* need the interruption.

I'm not sure how to fix it -- simplest would be a configuration option to turn off the immediate activity in the editor. For me, it would be enough if the IDE popped up a warning if I try to type into a code tab where the underlying file changed, or if I tried to save. Emacs does it like this and it's much less intrusive. If the file is merely open, there is no need to pester the user.

(Closing and adding to https://github.com/supercollider/supercollider/projects/3 -- not urgent.)

**Comment by brianlheim** [comment]
I agree, this should at the very least be configurable capability.

**Comment by snappizz** [comment]
It doesn't need to be configurable, it just needs to be better. The dialog shouldn't interrupt other windows, and it should only show up when the tab containing the problematic file is opened.

Sublime Text also silently reloads the file if you don't have any unsaved changes. That's pretty reasonable to me.

**Comment by jamshark70** [comment]
For future: The file watcher is also unreliable. It fires when I don't need it, but just now, I *did* need it to tell me to reload a file, and it completely missed the change. I can't discern any pattern.

It would be better not to have the feature at all, if it doesn't behave consistently.
