### ISSUE TITLE
plugins: FOS init bug?

### ISSUE THREAD

**Issue by telephon** [supercollider/supercollider#2656]
A first order flter section configured as an integrator returns wrong output in the first audio rate block.

```
// compare with Integrator
(
{
	var in, out, int;
	in = Impulse.ar(SampleRate.ir / 4);
	out = FOS.ar(in, 1, 0, 1); // integrator
	int = Integrator.ar(in, 1);
	[in, out, int]
}.plot(0.0009)
)
```

**Comment by telephon** [comment]
Maybe related: #2333.

**Comment by snappizz** [comment]
I don't think it's related to Ctor init bugs. FOS is just incorrectly implemented. It's incorrect even for an identity function:

```
(
{
	var in, out;
	in = Impulse.ar(SampleRate.ir / 4);
	out = FOS.ar(in, 1);
	[in, out]
}.plot(0.0009)
)
```

Source code for FOS boils down to this:

```
y0 = in[i] + b1 * y1;
out[i] = a0 * y0 + a1 * y1;
y1 = y0; // feedback
```

I did the math and it does work out to the desired transfer function of `out / in = (a0 + a1 z^-1) / (1 - b1 z^-1)`. So I'm not quite sure what's wrong.

**Comment by snappizz** [comment]
Aha, it's not the formula -- the issue seems to be local to one of the calculation functions:

```
{ FOS.ar(Impulse.ar(SampleRate.ir / 4), 1, 0, 0); }.plot(0.0009)
{ FOS.ar(Impulse.ar(SampleRate.ir / 4), DC.ar(1), DC.ar(0), DC.ar(0)); }.plot(0.0009)
```

**Comment by snappizz** [comment]
It's because the filter is initializing the coefficients at zero and linearly interpolating:

```
{ FOS.ar(Impulse.ar(SampleRate.ir / 4), 1, 0, 0); }.plot(0.01)
```

**Comment by snappizz** [comment]
#2658
