### ISSUE TITLE
scvim: some character literals don't highlight

### ISSUE THREAD

**Issue by vivid-synth** [supercollider/supercollider#2660]
In scvim some characters don't highlight correctly:

Repro:
  - open a .scd file in vim, with ```:syntax on```

  - type:

```supercollider
x = [ $1 , $a , $* , $# ]
```

observe ```$*``` and ```$#``` are not displaying properly

(Someone with the IDE can test if this also occurs there)

**Comment by brianlheim** [comment]
Works fine on IDE.

**Comment by gusano** [comment]
@vivid-synth more importantly, characters are not evaluated.
Closing this and opening another issue in scvim repo.
