### ISSUE TITLE
Linefeed escape in "Literals" helpfile

### ISSUE THREAD

**Issue by snappizz** [supercollider/supercollider#2667]
The "Literals" helpfile says about string escaping:

> To insert non-printing characters into a string: `\n` for newline, `\t` for tab, `\l` for linefeed, `\r` for carriage return. (This usage is valid only for Strings, not Symbols.)

This is wrong -- sclang does not seem to support `\l`:

    "\l" == "l" // true

Was it supposed to be implemented, or is it just a help error?

**Comment by brianlheim** [comment]
This should definitely be updated to the actual list of whitespace escape characters, which are

- \f form feed
- \n newline / line feed ('newline' is probably clearest here)
- \r carriage return
- \t tab ("horizontal tab")
- \v vertical tab

My guess, doc error.

**Comment by brianlheim** [comment]
Also - thanks for catching this. I hate nonsense like this that rots away in what's supposed to be the authoritative documentation.

**Comment by snappizz** [comment]
Yeah, I think bringing the core language docs up to par would be a worthwhile project

**Comment by brianlheim** [comment]
Fixed via #2666.
