### ISSUE TITLE
Links in help files are broken when sclang running on the command line

### ISSUE THREAD

**Issue by jamesopstad** [supercollider/supercollider#2679]
If I open help from the command line e.g.

`HelpBrowser.openBrowsePage("UGens>Buffer")`

the links within the document browser don't work. All links work correctly within the SC IDE. This also impacts browsing help files when running SC in other text editors.

**Comment by brianlheim** [comment]
Some links work for me, not for others. @jamesopstad What's your environment? (OS/SC version)

Does anyone know if there's a debug enable option for SCDoc/HelpBrowser?

**Comment by jamshark70** [comment]
@jamesopstad @brianlheim This is a known issue. #2295 

I'll close this one. Fixing 2295 will fix it.

**Comment by brianlheim** [comment]
@jamshark70 awesome, thanks!
