### ISSUE TITLE
Merge in Bela support

### ISSUE THREAD

**Issue by vivid-synth** [supercollider/supercollider#2682]
As noted here https://github.com/supercollider/supercollider/pull/2680, there exists a fork of SC for Bela. It's based on a very divergent fork of SC. In the interest of keeping code from diverging to the point we can't rejoin, and to support another platform, we can add Bela support to the main repo (after 3.9)

**Comment by patrickdupuis** [comment]
Looks like SC for Bela is based on SC 3.9dev from some time ago.

To compare `3.9` and this port:
https://github.com/supercollider/supercollider/compare/3.9...sensestage:bela_hackery_v02

I wouldn't be in favour of merging in Bela-SC. Ideally, the Bela port should closely follow the upstream project. Could the Bela modifications be made in such a way as to allow them to be cleanly applied onto the current stable SC?

**Comment by brianlheim** [comment]
Status update on this: PR #5295 is getting closer and closer to merge, i think possibly in the next week or two. remaining work:

- before merge
  - update readme (Giulio)
  - revise C++ code (me)
  - revise cmake code (me)
  - format sc code (me)
- after merge (will make a new issue for this when appropriate)
  - update scsynth to use a modern program options library (probably boost::program_options)
  - change CLI for bela arguments from single letter options to long options
  - anything else? it's been a while since i thought about this so i may have forgotten something

**Comment by giuliomoro** [comment]
> change CLI for bela arguments from single letter options to long options

Bela already has its own command-line argument parsers which is currently unused. What I would like to have is a way to pass a group of command-line options to that instead of the duplicated effort that is currently happening. Something like `<regular options> --bela <bela-specific options>`

**Comment by brianlheim** [comment]
You mean that instead of `--bela-option-one 1 --bela-option-two 2` you would write `--bela --option-one 1 --option-two 2`?

**Comment by giuliomoro** [comment]
Yes, with `--option-one 1 --option-two 2` being the normal Bela options as parsed by the Bela parser. A mostly complete list is [here](https://github.com/BelaPlatform/Bela/wiki/Bela-command-line-arguments). Then the Sc parser would only have to scan until it finds `--bela` and then pass the rest over to the Bela parser.

**Comment by brianlheim** [comment]
got it. there are tradeoffs either way -- the scheme you're proposing adds an element of surprise to the CLI, namely that option ordering matters now. it also means usage output and option parsing behavior will not be consistent. but, if the bela options and parsing scheme is actually used by a lot of other applications on the bela platform (is it?) then it's probably better to be consistent with that.

there is a CLI convention that everything after a `--` in the command line is treated as positional, unparsed arguments. cmake and git both do this, and apparently it's also part of POSIX specifications/guidance (https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap12.html#tag_12_02). perhaps this is a viable solution as well? both using `--` and `--bela` as end-of-scsynth-options delimiters would be fairly easy to do, but `--` in my view is a little more standardized for this kind of thing and also makes clear that what follows is forwarded verbatim to another part of the application.

**Comment by giuliomoro** [comment]
`--` sounds good. 

> If the bela options and parsing scheme is actually used by a lot of other applications on the bela platform (is it?)

It is, but that's not even my main concern. My point is to minimise code duplication and the number of interventions on the C++ side. Say we use Bela's parser, then if Bela adds a command-line option, that will be handled by `libbela` and there won't be need to even rebuild `scsynth`. The language side will have to be amended in any case, but not having to touch C++ is a good thing I think.

PS: as a mostly external observer, it seems to me that in the bigger scheme of Sc things, it'd be great if there was a single place where command-line options are specified, a sort of "interface specs" file which is used by both sclang and scsynth to specify the interface between the two, to simpify maintenance... and something similar for Ugens ... But you probably already discussed this somewhere!

**Comment by brianlheim** [comment]
> if Bela adds a command-line option, that will be handled by libbela and there won't be need to even rebuild scsynth. The language side will have to be amended in any case, but not having to touch C++ is a good thing I think.

ah, so libbela is being linked dynamically, i didn't know that.

> it seems to me that in the bigger scheme of Sc things, it'd be great if there was a single place where command-line options are specified, a sort of "interface specs" file which is used by both sclang and scsynth to specify the interface between the two, to simpify maintenance... and something similar for Ugens ... But you probably already discussed this somewhere!

sorry, not sure what you are imagining here...

**Comment by brianlheim** [comment]
Status update on this: PR #5295 will probably be merged this week!

- before merge
  - update readme (Giulio)
  - revise C++ code (me) - [one review patch PR to merge](https://github.com/BelaPlatform/supercollider/pull/91/files)
- after merge (will make a new issue for this when appropriate)
  - update scsynth to use a modern program options library
  - use Bela options parser and `--` delimiter as discussed above
  - better [version checks](https://github.com/supercollider/supercollider/pull/5295#discussion_r572433994)
  - discuss and possibly implement a [C API for BelaScope](https://github.com/supercollider/supercollider/pull/5295#issuecomment-772109585)

**Comment by brianlheim** [comment]
hey @giuliomoro and @sensestage, now that we have Bela support here, what would you like to do with https://github.com/BelaPlatform/supercollider ? should we migrate its issues here and mark that repo as deprecated? i've just created an "os: Bela" label to mark Bela and BelaUGens related tickets.

**Comment by giuliomoro** [comment]
Here's my suggestion:
I'll find a time to go through the open issues in the next few weeks. I'll close the fixed ones, keep there those that are related to Bela integration (e.g.: using Sc through the Bela IDE) and move upstream the ones that belong here. Going forward, maybe I can remove issues from there altogether and have them filed on the main Bela repo if they pertain to integration or the upstream Sc repo otherwise.

**Comment by brianlheim** [comment]
sounds good to me!

**Comment by brianlheim** [comment]
splitting this out into smaller issues as detailed above.
