### ISSUE TITLE
Array:permute -- which algorithm?

### ISSUE THREAD

**Issue by LFSaw** [supercollider/supercollider#2687]
in  [PyrArrayPrimitives.cpp](https://github.com/supercollider/supercollider/blob/master/lang/LangPrimSource/PyrArrayPrimitives.cpp#L1744-L1771), I found the latter but was wondering, which algorithm it is and how I can use it systematically, e.g. to move the `n`th element in an array one to the left.

```cpp
int prArrayPermute(struct VMGlobals *g, int numArgsPushed)
{
	PyrSlot *a, *b, *slots1, *slots2, temp;
	PyrObject *obj1, *obj2;
	int i, j, m, z, size;

	a = g->sp - 1;
	b = g->sp;
	if (NotInt(b)) return errWrongType;

	obj1 = slotRawObject(a);
	size = obj1->size;
	obj2 = instantiateObject(g->gc, obj1->classptr, size, false, true);
	obj2->size = size;
	slots1 = obj1->slots;
	slots2 = obj2->slots;
	memcpy(slots2, slots1, size * sizeof(PyrSlot));
	z = slotRawInt(b);
	for (i=0, m=size; i<size-1; ++i, --m) {
		j = i + sc_mod((int)z, (int)(size-i));
		z = sc_div(z,size-i);
		slotCopy(&temp,&slots2[i]);
		slotCopy(&slots2[i],&slots2[j]);
		slotCopy(&slots2[j],&temp);
	}
	SetRaw(a, obj2);
	return errNone;
}
```

**Comment by brianlheim** [comment]
Interesting. It's not Heap's algorithm, or Steinhaus-Johnson-Trotter.

If anyone wants to dig (don't have time atm): https://en.wikipedia.org/wiki/Category:Permutations

This should be documented both in the C++ and in schelp.

**Comment by brianlheim** [comment]
Here's a simplified version of the algorithm, in psuedo/C++
```cpp
permute(arr, n) {
  int i, j, m, size;
  size = arr.length();
  
  for (i = 0, m = size; i < size-1; i++, m--) {
    j = i + (z % (size - 1));
    z = z / (size - 1);
    arr.swap(i, j);
  }
}
```

**Comment by telephon** [comment]
nice. In sclang:

```
(
p = { |arr, n|
	var j, l;
	l = arr.lastIndex;
	arr.size.do { |i|
		j = i + (n % l);
		n = n div: l;
		arr.swap(i, j);
	};
	arr
};
)

p.((0..6), 3)
permute((0..6), 3)
```

**Comment by brianlheim** [comment]
Okay, I think `obj1->size` does not do what I think it does. _This_ is the real algorithm:

```cpp
permute(Array arr, int n) {
  int i, j, size;
  size = arr.length();
  
  for (i = 0; i < size; i++) {
    j = i + (n % size);
    n = n / size;
    arr.swap(i, j);
  }
}
```

**Comment by brianlheim** [comment]
Okay, I've been staring at the output of this algorithm for awhile now and I don't really get why this is an interesting permutation pattern. It definitely has one thing going for it, which is that it's O(n).

I don't know about yall, but when I think of permutations I think of [lexicographic ordering](https://en.wikipedia.org/wiki/Lexicographical_order). In fact, I would really like to introduce a new primitive that does that.

**Comment by LFSaw** [comment]
you mean what is written in the [Finite subsets](https://en.wikipedia.org/wiki/Lexicographical_order#Finite_subsets) section of the page, @brianlheim ?

**Comment by brianlheim** [comment]
@LFSaw yep, that's correct

**Comment by telephon** [comment]
(aside note) it does what it claims, give all permutations one after the other:

```
b = a.dup(a.size).allTuples.select { |x| x.as(Set) == a.as(Set) }.as(Set);
b == a.size.factorial.collect { |i| a.permute(i) }.as(Set)
```

**Comment by LFSaw** [comment]
small update:

JmC writes on the mailinglist:

> An array of size N has factorial(N) permutations.
The nthPermutation parameter is taken as an index into all possible permutations.
For each position in the output list the corresponding factor of the factorial is used to determine which item to choose.
The basic idea is explained here: https://en.wikipedia.org/wiki/Factorial_number_system

[source](http://new-supercollider-mailing-lists-forums-use-these.2681727.n2.nabble.com/How-permute-works-td7632241.html)

**Comment by brianlheim** [comment]
Closing this because the question seems to have been answered as best it can. But, I'm opening a new ticket to add lexicographic permute.
