### ISSUE TITLE
ServerOptions:new

### ISSUE THREAD

**Issue by snappizz** [supercollider/supercollider#2693]
I'm making a lot of `ServerOptions` for the UGen regression tests (required by `Score.recordNRT`). This syntax is really getting annoying:

```supercollider
o = ServerOptions();
o.sampleRate = 48000;
o.blockSize = 64;
```

Would it be a good idea to introduce a `ServerOptions.new`?

```supercollider
o = ServerOptions(
    sampleRate: 48000,
    blockSize: 64
);
```

**Comment by jamshark70** [comment]
It's perhaps only slightly less irritating, but you can write a chain of setters:

```
o = ServerOptions()
.sampleRate_(48000)
.blockSize_(64);
```

I don't think adding arguments to `new` is a massive improvement over this. One could argue that the chained-setter approach is better for objects with lots of properties where it's likely that you'll set only a few of them. GUI objects are one such case; ServerOptions is another.

I'm not saying "no, don't do it," but there's a valid reason to leave it as it is, too.

**Comment by snappizz** [comment]
Ah, the chained setters didn't occur to me. I'm content with that.
