### ISSUE TITLE
Extreme CPU load on newer Mac devices

### ISSUE THREAD

**Issue by snappizz** [supercollider/supercollider#2694]
Threads:

http://new-supercollider-mailing-lists-forums-use-these.2681727.n2.nabble.com/Download-size-of-recent-SuperCollider-releases-td7629540.html

http://new-supercollider-mailing-lists-forums-use-these.2681727.n2.nabble.com/2016-Macbook-Pro-woes-td7630484.html

@scztt wrote in the first thread that this may be because SCIDE has a rendering inefficiency that scales up with screen resolution. In particular, it seems that every update to the status bar causes a re-render of the entire IDE window. Since the re-rendering is infrequent compared to the audio blocksize, this is consistent with the high peak CPU, low avg CPU reported in the second thread.

**Comment by snappizz** [comment]
Untagging as severe and top priority since this seems to be a general problem with Mac rather than SuperCollider. We should still investigate graphical sources of inefficiency in the IDE.

**Comment by muellmusik** [comment]
Seems pretty severe to me! Mac is a major platform for SC; probably still the largest. Shouldn't that be a top priority?

**Comment by brianlheim** [comment]
"Making Macs better" is top priority, yes, but not for us luckily.

**Comment by snappizz** [comment]
Brian and I discussed this over Gitter -- the dropouts are pretty bad even without SCIDE.

**Comment by muellmusik** [comment]
Forgive me if I've misunderstood, but changed behaviour resulting in refreshing an entire window when only a small part needs it doesn't seem like a hardware issue. Nor does it seem likely to have been caused by "less powerful but more energy and battery-efficient" machines. Or?

**Comment by muellmusik** [comment]
> Brian and I discussed this over Gitter -- the dropouts are pretty bad even without SCIDE.

I see. Are people seeing this with other audio software on Mac, or only SC?

**Comment by snappizz** [comment]
In the second thread linked above, Wouter Snoei wrote that dropouts are also occurring in Logic Pro.

I don't think there's necessarily a conclusive answer, however. It is likely a combination of SC bugs/inefficiencies and Macs generally getting crappier.

**Comment by muellmusik** [comment]
I just did some tests with Quartz Debug. 3.7 through latest build all show that the server running triggers updates of the whole window. This however is not simultaneous with the refreshes for the status bar: it lags a little behind. This is on a 4 year old machine, running 10.11. So that at least is not something that's happening because of recent hardware changes.

I'd be happier if there was some attempt to confirm things before just blaming this on hardware rumours, etc.

**Comment by vivid-synth** [comment]
> Brian and I discussed this over Gitter -- the dropouts are pretty bad even without SCIDE.

https://github.com/supercollider/supercollider/issues/2144 might be the cause of that

I.e. it seems we have performance problems with both our IDE and headless code (both having to do with checking server status!)

**Comment by vivid-synth** [comment]
Someone on a Mac could try the "s.statusWatcher.stopAliveThread" workaround to see if it helps headless sclang performance.

**Comment by brianlheim** [comment]
Just tried it – MacOS 10.11, SC 3.9dev – and I don't notice much of a difference. You did mean I should try it on SC built with Qt, right?

**Comment by vivid-synth** [comment]
@brianlheim if your sclang process isn't eating a lot of CPU, and you're running without the IDE, and you're still getting a lot of dropouts, I don't know what the cause is.

This is, obviously, kind of a problem. Peoples' perception of the quality of SC audio could drop significantly, and we can't really tell people not to use macOS. (Or Apple hardware?)

**Comment by brianlheim** [comment]
Ok so we need to establish some baselines here. What is the build configuration that goes out to users in the prepackaged .zip? And what OS/architecture was it built on?

This is the line against which I'm testing all my builds:

```supercollider
300.do {{SinOsc.ar(1000.rand(3000), 0, 0.005)}.play}
```

I've been using the Debug configuration, which uses `-O0` (no optimization) as a compiler flag. With that, scsynth takes about 65% CPU. Under the Release config (which uses `-O3`) I get about 10%.

**Comment by brianlheim** [comment]
I should also add that I'm building the `install` target in XCode 8.2.1.

**Comment by brianlheim** [comment]
(btw, there's a `macOS Deployment Target` option that is still set to 10.11)

**Comment by muellmusik** [comment]
FWIW, I did a little review through the statusbar and related code, trying to see what was triggering the complete refresh. Nothing obvious, but I'll try a few more tests today.

That said, are we sure that a single window refresh, every second or two, on a multiprocessor machine with modern graphics would cause serious audio dropouts?

**Comment by telephon** [comment]
is this issue still reproducible ?

**Comment by snappizz** [comment]
stale issue, reopen if still a problem.
