### ISSUE TITLE
What is Module?

### ISSUE THREAD

**Issue by snappizz** [supercollider/supercollider#2699]
https://github.com/supercollider/supercollider/blob/master/SCClassLibrary/Common/Control/Module.sc

It was introduced in 2002 with b3527f5 and never touched again. It's undocumented and used nowhere else in the class library. What does it do?

**Comment by brianlheim** [comment]
Along the same lines—is the .scpreset extension even a valid extension recognized by SC? I can't find any other references to it in the repo.

**Comment by jamshark70** [comment]
`scpreset` appears there as an extension for `writeArchive`. Pathnames for archives can be whatever you want. It seems that it's not intended to open those files in the IDE so there is no need to be concerned about whether it's a valid extension or not.

IMO, quark it. This doesn't need to be in the main library.

**Comment by brianlheim** [comment]
Ah sorry, should have been clearer. I didn't mean whether or not it's a filetype that you'd open in the IDE, just wanted to clarify if any other component of SC or another Quark uses it. It seems like you're saying it's a more or less arbitrary choice?

**Comment by jamshark70** [comment]
Oh ok, no, I think it's arbitrary.

IIRC Module was supposed to be a component of a composition that you could load at runtime, but it appears to be underdeveloped (in particular, relying on text archives limits the types of objects that you can store in it) and it never took off with users. I don't recall even one question about it in over 10 years. I don't think we need to deprecate, even, just pitch it off into a quark. I bet nobody will notice.

**Comment by snappizz** [comment]
Agree that no deprecation is needed here. I'm not sure a quark is even necessary. It seems unlikely that this will ever be revived.

**Comment by brianlheim** [comment]
I vote to at least leave it around somewhere on the off chance that someone found it and is quietly using it for something interesting. It doesn't belong in this repository though IMO.

**Comment by snappizz** [comment]
#2703
