### ISSUE TITLE
Platform.recordingsDir in SuperCollider 3.8

### ISSUE THREAD

**Issue by prko** [supercollider/supercollider#2713]
ERROR: Message 'recordingsDir' not understood.
RECEIVER:
class Platform (0x1174d8400) {
  instance variables [19]
    name : Symbol 'Platform'
    nextclass : instance of Meta_Platoo (0x116b1a900, size=19, set=5)
    superclass : Symbol 'Object'
    subclasses : instance of Array (0x119a7bac0, size=1, set=2)
    methods : instance of Array (0x1174d8580, size=34, set=6)
    instVarNames : instance of SymbolArray (0x1174d8a00, size=5, set=2)
    classVarNames : instance of SymbolArray (0x1174d8bc0, size=5, set=2)
    iprototype : instance of Array (0x1174d8ac0, size=5, set=3)
    cprototype : instance of Array (0x1174d8c80, size=5, set=3)
    constNames : nil
    constValues : nil
    instanceFormat : Integer 0
    instanceFlags : Integer 0
    classIndex : Integer 1268
    classFlags : Integer 0
    maxSubclassIndex : Integer 1270
    filenameSymbol : Symbol '/Users/prko/Dropbox/prko/Lecture/KWU/2017-1/SuperCollider/SuperCollider.app/Contents/Resources/SCClassLibrary/Platform/Platform.sc'
    charPos : Integer 0
    classVarIndex : Integer 531
}
ARGS:
PATH: /Users/prko/Dropbox/prko/Lecture/KWU/2017-1/SuperCollider/SuperCollider.app/Contents/Resources/HelpSource/Tutorials/A Korean Guide/07/K07_04 Convolution.schelp
CALL STACK:
	DoesNotUnderstandError:reportError   0x11c053258
		arg this = <instance of DoesNotUnderstandError>
	Nil:handleError   0x11a5eb118
		arg this = nil
		arg error = <instance of DoesNotUnderstandError>
	Thread:handleError   0x11a5df4e8
		arg this = <instance of Thread>
		arg error = <instance of DoesNotUnderstandError>
	Object:throw   0x11c052a48
		arg this = <instance of DoesNotUnderstandError>
	Object:doesNotUnderstand   0x11a662e38
		arg this = <instance of Meta_Platform>
		arg selector = 'recordingsDir'
		arg args = [*0]
	Interpreter:interpretPrintCmdLine   0x119fc3098
		arg this = <instance of Interpreter>
		var res = nil
		var func = <instance of Function>
		var code = "Platform.recordingsDir"
		var doc = nil
		var ideClass = <instance of Meta_ScIDE>
	Process:interpretPrintCmdLine   0x114e6a338
		arg this = <instance of Main>
^^ The preceding error dump is for ERROR: Message 'recordingsDir' not understood.
RECEIVER: Platform

**Comment by jamshark70** [comment]
As far as I know, `recordingsDir` has never been a class method. It was always necessary to write `thisProcess.platform.recordingsDir`.

Btw this is one thing that could be cleaned up in Platform... a bit sloppy that some of the paths are available as class methods while others are not (and there is no apparent systematic reason why).

**Comment by brianlheim** [comment]
Closed by #2877.
