### ISSUE TITLE
SendReply example doesn't work

### ISSUE THREAD

**Issue by Sciss** [supercollider/supercollider#2716]
This is the example:

```
(
{
    SendReply.kr(Impulse.kr(3), '/the_answer', [40, 41, 42, 43] + MouseX.kr, 1905);
}.play(s);
)

o = OSCFunc({ |msg| msg.postln }, '/the_answer');
```

It doesn't work (tested with SC 3.7.2). I suspect the problem is the way the OSC function is registered.

**Comment by brianlheim** [comment]
Works in 3.9dev. Can you try recreating in a newer version (and post environment details when you do)?

**Comment by Sciss** [comment]
Sorry, false alarm, seems to have been a network problem or so, restarting helped
