### ISSUE TITLE
Remaining uses of OSCresponder and OSCpathResponder

### ISSUE THREAD

**Issue by jamshark70** [supercollider/supercollider#2721]
"Officially" we're supposed to be using OSCFunc for everything now, but several methods are still using OSCresponder and OSCpathResponder.

In the grep results here, I deleted the occurrences from OSCresponder.sc because those are from the class definitions -- no need to change those, just update the following places where those classes are used.

```
$ cd SCClassLibrary/
$ grep -rE 'OSC(pathR|r)esponder' .
./Common/Audio/Poll.sc:o = OSCresponderNode(s.addr, '/tr', {arg time, resp, msg;
./Common/Streams/Patterns.sc:			OSCpathResponder(server.addr, ['/n_end', recsynth], { |time, resp, msg|
./Common/Control/Bus.sc:			OSCpathResponder(server.addr, ['/c_set', index], { arg time, r, msg;
./Common/Control/Bus.sc:		OSCpathResponder(server.addr, ['/c_setn', index], { arg time, r, msg;
./Common/Control/Node.sc:		OSCpathResponder(server.addr, ['/n_set', nodeID, index], { arg time, r, msg;
./Common/Control/Node.sc:		OSCpathResponder(server.addr, ['/n_setn', nodeID, index], {arg time, r, msg;
./Common/Control/Buffer.sc:		OSCpathResponder(server.addr, ['/b_set', bufnum, index], { arg time, r, msg;
./Common/Control/Buffer.sc:		OSCpathResponder(server.addr, ['/b_setn', bufnum, index], {arg time, r, msg;
./DefaultLibrary/Main.sc:		OSCresponder.respond(time, replyAddr, msg);
```

**Comment by jamshark70** [comment]
Note also that fixing this will resolve a genuine bug: currently, it doesn't work properly to issue multiple requests at the same time against the same bus or buffer.

```
c = Bus.control(s, 1);
c.set(100);

(
c.get(_.debug("one"));
c.get(_.debug("two"));
)

POSTS:
two: 100
```

What happened to "one"?

But, we get both of them if we simulate `Bus:get` and replace the OSCpathResponder with an OSCFunc.

```
(
["one", "two"].do { |str|
	OSCFunc({ |msg| msg[2].debug(str) }, '/c_set', s.addr, argTemplate: [c.index]).oneShot;
	s.sendMsg("/c_get", c.index);
};
)

POSTS:
one: 100
two: 100
```

(Kudos, btw, to Scott Wilson for providing a framework that handles the case properly, without even realizing this was a bug!)

**Comment by muellmusik** [comment]
> (Kudos, btw, to Scott Wilson for providing a framework that handles the case properly, without even realizing this was a bug!)

Cheers! I've been succeeding accidentally for most of my adult life! :-)
