### ISSUE TITLE
Add modality toolkit and third-party tutorials to the repository

### ISSUE THREAD

**Issue by tiagmoraismorgado** [supercollider/supercollider#2727]
I would like to suggest the following:

- adding the modality toolkit, as part of supercollider default package;
- adding the sense stage tutorials on live electronic instruments as part of the default supercollider package
- adding the Scott Wilson supercollider book tutorials, as part of the default supercollider package
- adding the Stelio's Manousakis Supercollider tutorials, DXArts courses (most recent one of course), as part of the main supercollider package

**Comment by brianlheim** [comment]
Are all of these GPL-compatible?

**Comment by crucialfelix** [comment]
I think the core package should be smaller, not larger. 
It is easy for users to add packages. 
It is essential to reduce bloat and maintenance costs.

**Comment by brianlheim** [comment]
Agree 100%. I'm closing this for now. @tiagmoraismorgado if you want you can open a PR or issue to add these to the github.io website! (Although the SuperCollider book is already prominent there)

**Comment by bagong** [comment]
Well, I do think the code examples in the SC-book would make a nice addition to the examples folder. Might be a motivation for the authors to keep them up to date too... Just my 2c...

**Comment by telephon** [comment]
Generally, the examples folder could contain much more. Good examples have always been the strengths of sc!
