### ISSUE TITLE
adding p5.js or three.js bindings to supercollider

### ISSUE THREAD

**Issue by tiagmoraismorgado** [supercollider/supercollider#2728]
it's true that you can run OpenGL code inside SuperCollider by default;
however, it would be pretty interesting if we could, within a sense call the p5.js processing package or, even better three.js (webgl library), from within the supercollider code

**Comment by vivid-synth** [comment]
I think this is a great idea, but closing as it really should be implemented as a quark or separate program

**Comment by vivid-synth** [comment]
If you implemented this, I would definitely use it!
