### ISSUE TITLE
Ugen polling doesn't work at all?

### ISSUE THREAD

**Issue by andywarhol** [supercollider/supercollider#2740]
I've tried the helpfile examples for both Poll and Ugen.poll... nothing at all is printed to the post window.

Is anyone else experiencing this? Right now I'm on 3.9dev, Mac OS 10.12.3

**Comment by bagong** [comment]
Seems to work fine here, same system...

**Comment by andywarhol** [comment]
That's very strange... I'm not using any extensions, or doing anything out of the ordinary... I simply open SuperCollider, boot the server and go straight to Poll.ar/Ugen.poll... nothing is revealed in the post window except for the usual "Synth('temp__0' : 1000)"

**Comment by bagong** [comment]
Could you post the individual steps you do literally here:

**Comment by andywarhol** [comment]
Ah, I just found it! It seems my startup file had this line:

`Server.default.options.verbosity_(-2);`

-2 apparently suppresses Ugen polling.

**Comment by andywarhol** [comment]
Is it up for debate if a server verbosity of -2 should silence Poll's voice?

**Comment by bagong** [comment]
Glad it works!
Make your case and see ;)

**Comment by brianlheim** [comment]
Certainly worth asking! I'm closing this since the original issue has been resolved.
