### ISSUE TITLE
Server verbosity of -2 will silence the Poll Ugen

### ISSUE THREAD

**Issue by andywarhol** [supercollider/supercollider#2743]
A server verbosity of -2 will render Poll.ar/kr and Ugen.poll to become completely silent.

I think if someone wants to quiet the server's voice a bit, they wouldn't necessarily want to suppress messages that are explicitly demanded by the code they've written themselves.

If someone does want to suppress Poll messages, it should be up to them to delete any message generators that they themselves have full control over. The power to silence Poll should not belong to an instance of the server's configurations, because in order to gain that power back, the programmer might have to drown in a post stream full of 'late' messages.

Snuffing Poll's output could also lead to a situation where the programmer is unaware that a poll generator is silently devouring their CPU.

**Comment by brianlheim** [comment]
> If someone does want to suppress Poll messages, it should be up to them to delete any message generators that they themselves have full control over.

I disagree. This is why verbosity control exists—so you don't have to manually delete every instance of message generation when you want to silence a class of messages.

> the programmer might have to drown in a post stream full of 'late' messages.

Aren't there already simple ways of eliminating these messages? If not, there should be in a way that doesn't conflict with 

> Snuffing Poll's output could also lead to a situation where the programmer is unaware that a poll generator is silently devouring their CPU.

I don't think this is a realistic scenario; programmers who use aggressive verbosity settings are typically aware of the consequences.

I think generally speaking, this functionality should exist for the server. .poll is a very good diagnostic tool and it would be really annoying to comment/uncomment poll requests every time you want to turn on and off diagnostics. Likewise, it would annoying to have to roll your own verbosity control for the same purpose. I think what we're getting at here is that there should probably be more refined or clearly-defined settings for verbosity control in scsynth, which is something I would definitely push for. At the very least, the usage info that scsynth.exe gives should make it clear that -2 suppresses more informational messages than -1.

**Comment by snappizz** [comment]
What if you want to control the verbosity via a SynthDef input?

**Comment by andywarhol** [comment]
@brianlheim: I see your argument, except for the part about typical programmers understanding the consequences... we would have to 'poll' every programmer to find out what's typical ;)

I am, however, probably the most ignorant of all of us here, because I don't know a thing about development... but for all the real devs here, I have a few ideas/suggestions:

1) Clear documentation regarding the specifics of server verbosity settings.

2) A new setting of -3 which suppress the Poll ugen, while -2 does not.

3) The freedom to write a custom configuration script for server verbosity, alongside the option to punch in one of three numbers and hope that it does exactly what you want. 

4) s.options.verbosity could exist alongside a ServerVerbosity class, which is built similar to ServerOptions, and we would be able to set any of the specific instances of server messaging individually... as in: myServerVerbosity.poll_(true)

We're both essentially arguing about the freedom of the programmer, coming from different perspectives and experiences of our own practice with the language. The only true solution would have to be an expanded sense of convenience and freedom for both/all styles of practice.

We could keep the convenience of buying cigarettes from the gas station, and include the option to roll our own configuration if we want something more suited to our taste ;))

**Comment by joshpar** [comment]
An important part of the Server architecture is keeping it as lightweight as possible. Checking SynthDef parameters for verbosity would add considerable overhead. Adding MORE layers of verbosity would add more overhead.
The default is 0, so the typical programmer would get ALL messages. If someone sets it to -2 (as @andywarhol did, whenever you did) silences everything as that property states it should. And since no one else set it there for you, there is responsibility you take for how your code performs. -1  lets more through. Personally, I already think this is more granularity than there should be (I would opt for on or off only, and argue that any Server code writing to stdout is something that is a debug tool only). 
Please - don't clutter the server with more checks than are already in there.

**Comment by joshpar** [comment]
I will also note that when I wrote Poll, its intent was primarily for debugging purposes. Printing from the server is very expensive, and could lead to glitches. Please watch out for that! I'd had to see a side effect of this UGen ruin a performance.

**Comment by andywarhol** [comment]
Thanks Josh

**Comment by brianlheim** [comment]
> Clear documentation regarding the specifics of server verbosity settings.

This is the one I'm on board with. The explanation for -2 could be worded more clearly.

**Comment by brianlheim** [comment]
This is addressed by #2750
