### ISSUE TITLE
Deprecate OSCresponder and related classes

### ISSUE THREAD

**Issue by snappizz** [supercollider/supercollider#2745]
This issue depends on #2721. An sc-dev discussion is here:

http://new-supercollider-mailing-lists-forums-use-these.2681727.n2.nabble.com/Deprecate-OSCresponderNode-etc-td7630313.html

Judging by this discussion, we don't seem to have unanimous consensus on this issue, so this issue is a good place to dispute it.

**Comment by telephon** [comment]
On sccode.org, I only found four matches for OSCresponder:
http://sccode.org/search?q=OSCresponder&type=0
and one for OSCpathResponder:
http://sccode.org/search?q=OSCpathResponder&type=0

On the other hand, it is one of these things that *many* people might stumble over.

**Comment by brianlheim** [comment]
My interpretation of the mailing list conversation is that there is no opposition to deprecation:

Daniel Mayer wrote:

> I don't know how much effort it would be for me to shift this all to OSCFunc / OSCDef, but a very long deprecration cycle would be appreciated (if deprecation is necessary at all, don't know how much stuff from other people is depending on OSCresponder etc ...)

and:

> I'll have to check how much effort it is to base these classes on OSCFunc,
actually it's only two accuracies of OSCpathResponder in the code,
could be very easy - I should have a closer look in February. 

I think we should deprecate for a year, maybe more if necessary, and then remove.

**Comment by bdwhiti2** [comment]
Just as a heads-up: BroadcastServer in JITLibExtensions makes use of OSCresponderNode.

**Comment by telephon** [comment]
Thanks! I have no time right now to look into it. also `Client` and `Dispatch` classes use it. We could think about deprecating the whole bunch and moving any missing functionality to https://github.com/muellmusik/Utopia/

**Comment by muellmusik** [comment]
> We could think about deprecating the whole bunch and moving any missing functionality to https://github.com/muellmusik/Utopia/

Which is overdue for Quarkification. Mostly just missing some doc.

**Comment by jamshark70** [comment]
I'd also remind that, from time to time, we note that an obstacle for new users learning SC is that there are too many ways to do the same thing... but then, when there's a concrete place to remove an older, slower and flawed implementation, it's "Well, let's not be so hasty."

I'd say, SC4 should definitely dump the old classes.

3.x, I'm less sure... compatibility is a good goal, but OTOH if SC4 is years out into the future, it's ok to trim it down -- with a *long* deprecation cycle.

**Comment by telephon** [comment]
yes, very much agreed. It should be easy to restore older behavior through the Quarks. 

Maybe we need a clearly named series of Quarks that matches different versions, also by dependency? I think it is possible, but I'm not exactly sure how.
