### ISSUE TITLE
ServerTree - adding and removing from the default server

### ISSUE THREAD

**Issue by dyfer** [supercollider/supercollider#2747]
Hello,

It seems there's a bug when one is adding an object to the server tree while not specifying the server. Reproducer:
```
s = Server.default;
f = {"It's me".postln};

ServerTree.add(f);
ServerTree.objects //adds to \all
ServerTree.remove(f); //tries to remove from \default; the function is still there
ServerTree.objects; 

//when specifying the server, works as expected
ServerTree.add(f, s);
ServerTree.objects;
ServerTree.remove(f, s); //this works
ServerTree.objects;
```
This is in the SystemActions.sc file. I think that the *add method should add object with a key ```\default```, like
```if (server.isNil)  { server = \default };```
instead of 
```if (server.isNil)  { server = \all };```
but I haven't used this mechanism extensively so I'm not sure if this is the correct solution...

Marcin

**Comment by brianlheim** [comment]
Fix was proposed by both #2238 and #2748, for the record. Since #2748 had documentation I merged that one.
