### ISSUE TITLE
/s_getn with a named control returns zeros beyond first control value

### ISSUE THREAD

**Issue by snappizz** [supercollider/supercollider#2755]
Found while unit testing #2746 (turns out, tests pay off).

```supercollider
s = Server.default;
s.boot;

// make a dummy SynthDef
(
SynthDef(\test, {
    |control1 = 2, control2 = 2, control3 = 2|
}).add;
)

// create a node and print all /n_set and /n_setn messages
(
n = Synth(\test, [control1: 8, control2: 88, control3: 888]);
OSCFunc(_.postln, \n_set, s.addr, argTemplate: [n.nodeID]);
OSCFunc(_.postln, \n_setn, s.addr, argTemplate: [n.nodeID]);
)

s.sendMsg(\s_get, n.nodeID, 0);
// prints [ /n_set, xxxx, 0, 8 ] -- OK

s.sendMsg(\s_get, n.nodeID, \control1);
// prints [ /n_set, xxxx, control1, 8 ] -- OK

s.sendMsg(\s_getn, n.nodeID, 0, 3);
// prints [ /n_setn, xxxx, 0, 3, 8, 88, 888 ] -- OK

s.sendMsg(\s_getn, n.nodeID, \control1, 3);
// prints [ /n_setn, xxxx, control1, 3, 8, 0, 0 ] -- ???
```

The docs for `/s_getn` don't seem to hint at any such issue. If there isn't any good way to fix this, then we can just document it.

I honestly don't know this part of SuperCollider too well, so I may be missing something here...

**Comment by Sciss** [comment]
I think the intended behaviour is to query named multi-channel controls. This works as expected:

```supercollider
// make a dummy SynthDef
(
SynthDef(\test, {
	var ctl = \control1.kr([2, 3, 4]);
}).add;
)

// create a node and print all /n_set and /n_setn messages
(
n = Synth(\test, [control1: [8, 88, 888]]);
OSCFunc(_.postln, \n_set, s.addr, argTemplate: [n.nodeID]);
OSCFunc(_.postln, \n_setn, s.addr, argTemplate: [n.nodeID]);
)

s.sendMsg(\s_getn, n.nodeID, 0, 3);
// prints [ /n_setn, xxxx, 0, 3, 8, 88, 888 ] -- OK

s.sendMsg(\s_getn, n.nodeID, \control1, 3);
// prints [ /n_setn, xxxx, control1, 3, 8, 88, 888 ] -- OK
```

So I would think this should be closed as "not a bug".

**Comment by snappizz** [comment]
I see. As I said, not part of SC that I really know well...

**Comment by telephon** [comment]
I do think it is a (possible) issue that if you ask for more controls than you have, you get `0`:

`s.sendMsg(\s_getn, n.nodeID, \control1, 6);`

returns

`[ /n_setn, 1000, control1, 6, 8, 88, 888, 0, 0, 0 ]`

**Comment by Sciss** [comment]
I think this is actually good. It's an error of the client to ask for a wrong number of controls. _But:_ given the specification of ` \s_getn` message, the server returns an exact and predictable number of values. If anything at all, I could imagine that `[\s_getn, n.nodeID, \control1, -1]` could be used to query all channels of a control without having to specify the number of values to be returned. Nevertheless, I see little use for this, the client architecture should know what controls were created. Because this is exactly the same situation with querying buses.

**Comment by jamshark70** [comment]
> If anything at all, I could imagine that [\s_getn, n.nodeID, \control1, -1] could be used to query all channels of a control without having to specify the number of values to be returned.

If you write, in a SynthDef, `arg a = #[1, 2, 3], b = 4;`, SC's SynthDef builder produces a single Control with 4 channels. While executing the UGen function, `a` gets an array with the first 3 OutputProxies and `b` gets the last one.

The only knowledge of the argument sizes is in the client -- the server doesn't currently know how many Control channels belong to `a` and how many to `b`. Should `[\s_getn, n.nodeID, \a, -1]` then return 3 values or 4? If it's a long arg list, it might be, should it return 3 values or 50?

**Comment by telephon** [comment]
The server side graph knows the number of channels of every control, it is kept in the `ParamSpec`.

When we map controls, we check and protect from overrun:

https://github.com/supercollider/supercollider/blob/18d7638a1fbe6d0f6cc7a849e0052c768b0b9984/server/scsynth/SC_Graph.cpp#L586

So there is no reason why \s_get_n shouldn't work that way, or even return all values if we send `-1` for `n`.
