### ISSUE TITLE
TestBus:test_free failures

### ISSUE THREAD

**Issue by snappizz** [supercollider/supercollider#2758]
Is this failing for anyone else?

```
sclang> UnitTest.runTest("TestBus:test_free")

ERROR: Meta_Bus:audio: failed to get an audio bus allocated. numChannels: 1 server: localhost
ERROR: Meta_Bus:audio: failed to get an audio bus allocated. numChannels: 1 server: localhost
ERROR: Meta_Bus:audio: failed to get an audio bus allocated. numChannels: 1 server: localhost
ERROR: Meta_Bus:audio: failed to get an audio bus allocated. numChannels: 1 server: localhost
[huge number of copies of the above line omitted]

FAIL:a TestBus:test_free - after freeing, should be able to re-allocate all busses


FAIL:a TestBus:test_free -  should be numAudioBusChannels busses 
Is:
	 108 
Should be:
	 1020 



UNIT TEST.............
There were failures:
a TestBus:test_free - should be able to allocate all busses
a TestBus:test_free -  should be numAudioBusChannels busses 
Is:
	 108 
Should be:
	 1020 

a TestBus:test_free - after freeing, should be able to re-allocate all busses
a TestBus:test_free -  should be numAudioBusChannels busses 
Is:
	 108 
Should be:
	 1020 

```

**Comment by telephon** [comment]
Yes, I can reproduce this. The problem seems to be that `Server.newBusAllocators` accounts for the `audioBusOffset` twice.

**Comment by telephon** [comment]
I'm not too familiar with the details of `ContiguousBlockAllocator`. @jamshark70 ?

**Comment by jamshark70** [comment]
I modeled ContiguousBlockAllocator's interface after the older PowerOfTwoAllocator -- the two were initially meant to be interchangeable. We dropped PowerOfTwoAllocator only after a couple of years of testing, during which ContiguousBlockAllocator didn't show any faulty behavior.

The point being that the meaning of the arguments to `XyzAllocator.new()` hasn't changed since the beginning of SC Server... so if there is new wrong behavior, it must be the usage of the allocator rather than the allocator itself.

I now see two (competing?) PRs about this issue and unfortunately this is happening during my busiest teaching days... so I have no time to unravel who is doing what, and why, and I have no further comment.

**Comment by telephon** [comment]
no problem, james, we have time.

**Comment by telephon** [comment]
The two PRs (#2760, #2761) are separate and independent.

**Comment by telephon** [comment]
The problem in both allocators, `PowerOfTwoAllocator` and `ContiguousBlockAllocator` is the *meaning* of the term `size`. When creating the allocator, you pass in `pos`, and that is effectively subtracted from `size`, so the latter is not really the size, but the last number.

**Comment by jamshark70** [comment]
If you shift perspective slightly: `size` refers to the size of the available "world" of numbers to be allocated, and `pos` removes some of that world from consideration.

It's reasonable to guess that `size` would refer to the number of items available for allocation *after* accounting for `pos`, but it isn't the only way to interpret the word "size."

It would have been clearer to call it "totalAllocatorSize," perhaps, but that ship already sailed.

**Comment by telephon** [comment]
yes, totally fine once you know it!

**Comment by snappizz** [comment]
i'm glad to see there's a lot of work and discussion being poured into this issue, but it's taken months by now and pretty urgent that we have failing tests in master. can we just disable these tests momentarily by prefixing them with `ignore_`?

**Comment by telephon** [comment]
wherever that is harmless, I'd prefer to sometimes merge a preliminary solution and continue from that point!

**Comment by snappizz** [comment]
imo tests should always pass in master, which is a minimum standard used by many, many quality software projects. as a general rule i don't think we should merge incomplete work either, and definitely not work that introduces new bugs.

even more strictly, i would like to propose that we only file PRs when the work is complete or near complete. i'm concerned that we have far too many PRs open right now, and it's getting really overwhelming. that's why i'm trying to go back and close a few that seem to have been abandoned. i have faith that, with some effort, we can finish up and merge more than half of our current backlog.

**Comment by miguel-negrao** [comment]
> even more strictly, i would like to propose that we only file PRs when the work is complete or near complete. i'm concerned that we have far too many PRs open right now, and it's getting really overwhelming. that's why i'm trying to go back and close a few that seem to have been abandoned. i have faith that, with some effort, we can finish up and merge more than half of our current backlog.

Maybe we can use a "sketch" tag for PRs which are still exploratory, and maintainers can ignore all of those with a search filter. For sketching ideas I find it  useful to show some code with a PR, even if it's very far from the completed version, but I do appreciate your point regarding dealing with PRs and the organizational hassle.

**Comment by brianlheim** [comment]
i'm also opposed to merging incomplete work. it's messy for both the git log and discussion threads. if we had a separate dev branch from master, it might be a possibility.

i'm open to a 'sketch' tag, so long as we recognize that the sketches are only temporary and should be closed if they become inactive. but i think the fact that it's on the main repo is what makes it somewhat frustrating for @snappizz . if it's really a matter of the means of expression, and the PR is the clearest way to explain something, there is always the option of opening a PR against your own fork, and linking others there. we certainly don't have to have every discussion here.

**Comment by LFSaw** [comment]
> we certainly don't have to have every discussion here.

really? Not necessarily my personal point of view... I like having discussions on SuperCollider collected in one place. 

just my 2c

**Comment by bagong** [comment]
I'd also say: if one isn't interested in a discussion, just ignore it. No need to take it away from others.
