### ISSUE TITLE
SequenceableCollection:join performance

### ISSUE THREAD

**Issue by snappizz** [supercollider/supercollider#2767]
Haven't tested myself, but @brianlheim reports that `x.reduce('++') ? ""` is faster than `x.join("")`.

**Comment by brianlheim** [comment]
OK so my statement that it was 6-10x faster was definitely an exaggeration—it's more like 2-3x. Sorry about that; I'm looking back through my code to see if I might have confused that with another benchmarked bit.

```supercollider
a = ["abc", "def", "ghi", "zebra"];

bench {
10000.do {
	a.join("");
};
};
// 0.27 sec

bench {
10000.do {
	a.reduce('++');
};
};
// 0.12 sec
```

I think this difference in performance is reasonable. After all `join` is also handling a second argument.

**Comment by telephon** [comment]
`join` has more levels of indirection, I suppose. It uses `<<`, which is delegated to`printOn`, which then performs `addAll`.

But maybe it is something else?


```
reduce { arg operator;
		var once = true, result;
		if(this.size==1){ ^this[0] };
		this.doAdjacentPairs {|a, b|
			if (once) {
				once = false;
				result = operator.applyTo(a, b);
			}{
				result =  operator.applyTo(result, b);
			};
		};
		^result
	}
	join { arg joiner;
		^String.streamContents { arg stream;
			var stop;
			if(joiner.isNil) {
				this.do { arg item; stream << item };
			} {
				stop = this.size - 1;
				this.do { arg item,i;
					stream << item;
					if(i < stop) { stream << joiner };
				};
			}
		}
	}

```

**Comment by brianlheim** [comment]
I'm going to close this, because the performance difference is acceptable, and because you can find situations like this sprinkled throughout SC.
