### ISSUE TITLE
Backup of SC repo

### ISSUE THREAD

**Issue by bagong** [supercollider/supercollider#2776]
Github could go bankrupt, or malicious attacks could harm it, in theory even somebody could delete the SC repo. Github does not seem to provide backups for non-commercial organizations, so I guess one way of trying to anticipate the case that will hopefully never occur, is taking a backup. While the SC repo is forked/mirrored in many instances, appart from being unreliable, such copies do not contain all the stuff surrounding the actual repos: issue, comments, wikis etc - and those are a interesting part of the SC history by now.

I haven't yet come across a really professional solution, and I'd expect one would have to pay for one. But there are a few free/libre scripts that seem to do a reasonable job. I've been experimenting with this one:

    http://github-backup.branchable.com/

It seems to get all abovementioned things and just leave out stuff like line numbers and inline comments. These seem to be missing in part because it hasn't been implemented yet in github-backup, and in part because the Github API seems not to offer a way to get them.

One shortcoming though: it doesn't download submodules. This would usually not be a problem, as submodules are contained as separate repos within the SC.org (and github-backup backups the entire org). Yet this is not the case for nova-tt and nova-simd. These two are retrieved directly from Tim Blechman's original repos, and are therefore neither being backed up nor directly accessible by members of the SC.org. It's a somewhat sensitive issue as Tim is the author and I think *sole* maintainer of these modules, and they have been in good hands. And yet it seems a wise long-term policy that the SC-repo shouldn't depend on submodules it can't control itself.

I'll leave it at that as something that may be worth a discussion and shared action.

**Comment by bagong** [comment]
This actually looks like a good service to me:

https://backhub.co/

They are explicit in the crucial question of restore: there are some limitations, PRs can only be restored as issues and Wikis cannot be restored automagically, but they seem to offer a service to do that. Other that that it seems (claims) to be a full, daily automatic backup of the whole organization. Which means deleting a repo and accidental force-pushes cannot do much harm any more.

It's free for public repos in organizations, so it follows a similar business model to travis CI and Github itself.

I'd suggest this: let's fork Tim's two repos into the SC organization, but leave the original ones as the actual source for now. No need to "cut the tie" ;) After that I could go and setup a backup with BackHub.

Thoughts?

**Comment by bagong** [comment]
I've done this now and will be observing it and experimenting during the next week. Let's see how it behaves... ;)

**Comment by brianlheim** [comment]
@bagong pinging you on this. any news?

**Comment by bagong** [comment]
Well, I enabled backup on backhub.co back then, and since then it has just been doing it, daily backups. Each backup replaces the old one. So it's good for total loss, but doesn't protect against force pushes. All repos in the SuperCollider org get backed up. I guess the most interesting thing is the "Metadata". As I said the status is that it get's wikis, issues, and it claims to convert PRs into issues. Not sure about stuff like tags, milestones etc. I was hoping to inspect it a bit more in detail, try a restore for a fake repo, but sofar the plan got pushed back by other stuff, sorry...

**Comment by brianlheim** [comment]
@bagong Thanks. Unless anyone has objections, I am going to close this since it sounds like we have a solution. There doesn't seem to be much community interest in preserving PR/issue/commit comments, but there is of course nothing stopping others from keeping backups of those.

**Comment by telephon** [comment]
It is a good thing to keep them somewhere – I had understood that @bagong had solved it though.

**Comment by bagong** [comment]
Yea, nothing changed. It's just keeping a set of copies that are renewed 3 or 4 times per day... Includes metadata with a few limitations, and is - inshaAllah - restorable ;)

**Comment by telephon** [comment]
Thank you for that, already now …

**Comment by crucialfelix** [comment]
maybe we could copy everything into the blockchain. then the central
bankers can never erase our history...

**Comment by telephon** [comment]
i'm sure it'll add some nice entropy to it
