### ISSUE TITLE
scsynth switch for audio device info

### ISSUE THREAD

**Issue by jleben** [supercollider/supercollider#278]
[Issue migrated from SourceForge | ID: 2829280 | Submitted by 'sciss']
[http://sourceforge.net/support/tracker.php?aid=2829280]

Currently, the only way to find out about connected audio devices is via ServerOptions.devices. This has three disadvantages:
- it puts audio hardware code in sclang and thereby duplicates stuff that is already in scsynth
- it does not provide any information about the number of available inputs and outputs
- the information is not accessible by other scsynth clients other than sclang (JCollider, Eisenkraut, ScalaCollider...)

The proposed solution is to add a new command line switch to scsynth. -L would be an obvious choice and is still free. The proposed operation of scsynth is that it outputs the device infos in a clearly formatted way that can be easily processed by the clients reading from the console. After printing, scsynth will terminate. Here is an example using an XML like syntax:

```
$ ./scsynth -L
<devices>
   <device name="Built-in Microphone" ins="2" outs="0"/>
   <device name="Built-in Input" ins="2" outs="0"/>
   <device name="Built-in Output" ins="0" outs="2"/>
   <device name="MOTU 828mk2" ins="28" outs="28"/>
</devices>
$ _
```

The advantage of XML is that it can be easily parsed by almost every language (including sclang with the help of jens gulden's quark) and it can be easily extended in the future. For example, on OS X stream information could be added, or supported sample rates or hardware buffer sizes, etc.

Someone on linux needs to evaluate how this approach scales to the Jack audio connection kit.

**Comment by LFSaw** [comment]
@Sciss , since you are the original author (and might not even know this issue still exists), do you have an idea how to implement this?

**Comment by Sciss** [comment]
@LFSaw I'm now on Linux, so it goes through Jack and has no notion about sound cards, so from my perspective the issue has dissolved...

**Comment by muellmusik** [comment]
Though recently mentioned, this is very old and hasn't progressed, so I'm going to mark stale and close.

**Comment by samaaron** [comment]
As a heads up if anyone is interested in reviving and working on this - we would absolutely love to have this functionality from Sonic Pi's perspective.

Just to clarify - is the reason this has been closed only due to a lack of interest in implementing such a feature as opposed to it not specifically wanted from a design perspective?

**Comment by muellmusik** [comment]
Hi Sam. It’s 10 years old and no progress had been made, so yes, lack of interest. Having long lists of stale feature requests becomes a management problem in itself, so we periodically clear out the seemingly dead ones.

We can reopen if there’s a realistic prospect of progress, ie someone who will commit to working on this. Hope that makes sense.

**Comment by samaaron** [comment]
Hey Scott! No worries at all - I *completely* understand. I was merely testing the waters to see if, in principle, this feature would still be considered for inclusion :-)

**Comment by muellmusik** [comment]
Sure. Of course nobody’s against it. ;-) Like so many things it just needs someone to do it. :-)
