### ISSUE TITLE
Write regression tests for lexer, parser, and compiler

### ISSUE THREAD

**Issue by snappizz** [supercollider/supercollider#2783]
This paves the way for safely making changes such as:

- [Mixing extensions and classes in class files](https://github.com/supercollider/supercollider/issues/52)
- [Disallowing "^" in interactive code](https://github.com/supercollider/supercollider/issues/2674)
- [Allowing "_" in keyword arguments](https://github.com/supercollider/supercollider/issues/2800)
- [Allowing symbol literals like \1a](https://github.com/supercollider/supercollider/issues/2673)
- [Disallowing lexer edge cases with scale degree notation and key binary ops](https://github.com/supercollider/supercollider/issues/2568)

Already in progress at [#2751](https://github.com/supercollider/supercollider/pull/2751), this is just for bookkeeping.

This is high priority for 3.9.

**Comment by snappizz** [comment]
Closing via #2751.

**Comment by brianlheim** [comment]
Thanks!
