### ISSUE TITLE
maintenance of supercolliderau and supercollider audio unit builder would be appreciated

### ISSUE THREAD

**Issue by tiagmoraismorgado** [supercollider/supercollider#2789]
**Hello Everyone**

In the past there was used to be a project called - **_SupercolliderAU_**. However:

- SupercolliderAU is **32 bits only;**
- **Modern Supercollider Distributions** are mostly **64 bits;**

It would be cool if:

- SupercolliderAU would be **maintained and ported to 64 bits;**
- There would be a modern version of the old quark, capable of compiling audio units with 3**.8 and, in the future, 3.9;**

Not only that but:

- allowing plugins to be compiled for environments **other then MacOSX (i.e.: Linux/Windows);**

This would be great because:

- It would allow users to **play with supercollider code in their favorite DAW**
- loading code into **other environments;**
- it is an easy way to **play with supercollider code modularly;**

**Comment by brianlheim** [comment]
Request noted.

**Comment by bagong** [comment]
You could first make a PR from

https://github.com/tiagmoraismorgado/linux

I am sure Linus would like to hear about it. We can discuss Windows after you're done ;)

**Comment by snappizz** [comment]
I agree that it's unfortunate that SuperColliderAU has fallen out of maintenance. Unfortunately, we (the core dev team) are unable to prioritize this any time soon.
