### ISSUE TITLE
a new NRT mode with full OSC socket

### ISSUE THREAD

**Issue by jleben** [supercollider/supercollider#279]
[Issue migrated from SourceForge | ID: 2829287 | Submitted by 'sciss']
[http://sourceforge.net/support/tracker.php?aid=2829287]

SuperCollider supports offline rendering via the special NRT mode command line switch. The approach is to read in a binary OSC file and process its messages. The advantage is that this will work without any client involved. The big disadvantage is that code written in the client (e.g. sclang) does not run equally well in realtime and offline. In particular it cannot rely on reply messages (/done from buffer manipulation, /n_go, /n_end etc., /tr...). This in general poses a strong burden on writing NRT-savvy code. When looking at SendTrig and /tr it even makes a lot of code impossible to run in offline.

The solution is to add new NRT mode that, instead of making scsynth read OSC messages from a binary file, will open a regular OSC socket and await messages from a client. However, DSP is done as fast as possible instead of performing it in realtime on some audio hardware. For this to work, on the client side (sclang) a corresponding clock class, e.g. NRTClock, is needed that will advance the NRT clock on the server. That way, for example a Routine will run as fast as possible while still providing corrent thisThread.seconds feedback and hence correct bundle times.

This idea was also presented and discussed on sc-users:
http://www.listarc.bham.ac.uk/lists/sc-users/msg52040.html

**Comment by snappizz** [comment]
If such a mode is implemented, I suggest it be called "turbo mode."

**Comment by snappizz** [comment]
Added to long-term, large-scale projects.

**Comment by metakeule** [comment]
@snappizz Why did you close the issue?

**Comment by vivid-synth** [comment]
@metakeule I think the idea is to close any any long-term/"waiting for someone to lead" ideas, so the pressing issues don't get lost

**Comment by metakeule** [comment]
@vivid-synth 
This is really unusual and strongly suggest to review the issue handling process for the following reasons:

1. You could use labels like "long-term", "important", "needs help" etc. to organize issues without having to close them.
2. Closing an issue does not communicate the intention: Was it a duplicate? Is it intended behavior/wont fix? Is it implemented already? etc.
3. Most people don't look after closed issues. Therefor issues gets reported multiple times, are not discovered etc.
4. How do you know that there is nobody to lead? Closing the issue makes it invisible so possible leaders would not see it.
5. Even bigger projects don't close issues to mark them as "long-term/help wanted".
6. For a larger project with good issue organization, have a look at https://github.com/golang/go/issues

**Comment by snappizz** [comment]
especially in proportion to the size of our project and our contributor base, we have a really overwhelming wall of open issues. during a particularly stressful period of development where we really wanted to stay focused on bug fixes, we reached a consensus to archive major "this would be nice to have" feature requests that clearly aren't going to be taken care of soon.

**Comment by Sciss** [comment]
It would probably better suited as a ['project'](https://github.com/supercollider/supercollider/projects) instead of an issue, as this is a complex project rather than an isolated enhancement or bug fix.

**Comment by Sciss** [comment]
Seems the original sc-users link is no longer available on listarc.bham.ac.uk ; searching on net, I found this document which I guess shows the same design: https://gist.github.com/Sciss/eca59f10653dadbdc9a0
