### ISSUE TITLE
changing Startup.scd path to application source code by default

### ISSUE THREAD

**Issue by tiagmoraismorgado** [supercollider/supercollider#2790]
It would be awesome, if the startup.scd would be:

- inside the application source bundle;

this would be a good decision because:

- it is easy to implement;
- anyone can contribute to it;
- you can see which settings everyone is using;
- you can even add different profiles to startup.scd

And example of the last topic would be:

- OS dependent settings (Linux, OSX, Windows);
- hardware dependent settings (lowest, Low, mid, high, ultra)

**Comment by brianlheim** [comment]
The purpose of `startup.scd` is to precisely _not_ do this, and allow the user a totally free space to customize their setup.

> you can even add different profiles to startup.scd

This might be interesting as an addition to documentation.
