### ISSUE TITLE
binaries for other platfforms

### ISSUE THREAD

**Issue by tiagmoraismorgado** [supercollider/supercollider#2794]
Heyho

I see that we already have like binaries for:

- windows
- linux
- macosx
- iphone
- jailbroken iphone

however:

- it would be nice to have binaries for android as well (a lot of people still seem to use android)
- it would be nice to have binaries for ubuntu mobile as well (some people still use ubuntu mobile)
- it would be nice to have binaries for windows 10 mobile (for the same reason)
- it would be nice to have binaries for raspberry pi (for the same reason)

i see this as a valid standing point because:

- mobile and embedded platforms start representing a major part of the user market niche
- not everyone is able to compile supercollider from scratch
- this would allow more users to come onboard as scusers

**Comment by bagong** [comment]
We are well aware of these shortcomings. Unfortunately the priority of these interesting projects is far lower than the things we have a hard time keeping up with already. So unfortunately not really an issue at this time.
