### ISSUE TITLE
TGrains amp argument has no effect

### ISSUE THREAD

**Issue by jreus** [supercollider/supercollider#2807]
It seems the TGrains Ugen's amp argument has no effect on the amplitude of the grains. I'm running this on SC 3.8.0 on a macbook pro (Yosemite). 

Here's some code to illustrate:

```
b = Buffer.read(s, Platform.resourceDir +/+ "sounds/a11wlk01.wav");
{ // This should fade in... but starts at full volume
	TGrains.ar(2, Impulse.ar(15), b, centerPos: Line.ar(0, 5, 10, doneAction: 2), amp: Line.ar(0, 1, 10));
}.play;
```

**Comment by brianlheim** [comment]
It looks like #2136 is probably the cause (https://github.com/supercollider/supercollider/pull/2136/commits/f35a3f7f1552266fda04e326474dd678177b2ba5)

**Comment by brianlheim** [comment]
#2809. Thanks for catching this!

**Comment by snappizz** [comment]
Ah damn. Sorry, this one's my fault.

**Comment by brianlheim** [comment]
@snappizz No worries! That PR was overall great, and we don't have tests in place yet so there was no easy way to confirm none of the behavior of TGrain's 20 parameters changed.
