### ISSUE TITLE
Warn on an audio-rate signal passed to "bus" argument of Out

### ISSUE THREAD

**Issue by snappizz** [supercollider/supercollider#2816]
This morning, I was debugging a SynthDef that was making weird crackly noises, and had a stereo image despite being a center-panned mono signal. Turns out I had accidentally written

    Out.ar(snd, snd);

instead of

    Out.ar(0, snd);

and the crackling was coming from the fact that Out's "bus" input is read at control rate.

Would it be a good idea to warn/error if an audio-rate signal is passed to the "bus" input of Out and similar ugens?

**Comment by telephon** [comment]
I could imagine usages of `Out` that modulate the index at audio rate.

**Comment by Sciss** [comment]
I agree with Julian, there is no logical reason why the bus parameter could not be an audio rate signal.

**Comment by snappizz** [comment]
I think the fact that nobody has ever asked for it may be a good enough reason...

**Comment by brianlheim** [comment]
Sorry if this is a naïve question, but isn't this a hardware limitation? i.e. don't bus writes have to be done in control-rate blocks?

**Comment by telephon** [comment]
subsequent samples within one audio rate block can originate from different audio busses, and can also be written into different audio busses.

i think of it this way: busses are horizontal, synths are vertical. Only vertically, we have blocks, horizontally ugens can do what they want

**Comment by jamshark70** [comment]
I felt it was worth verifying how the server handles bus initialization at the beginning of every control block. (If there's no "reset," then every control block will feed back the signal from the previous block.) I wasn't sure if it's a simple matter of zeroing out the bus data, or if there was something more complex.

So I did a quick test, putting a signal on a bus by `XOut` with a mix factor of 0.5, reading it back from the bus and comparing. The bus signal was half, so, there's no magic.

Initially I thought the behavior of switching buses in the middle of a block might be undefined, but with that test, I'm convinced it's safe.

**Comment by telephon** [comment]
good that you checked. It would have been surprising though, because each block is always completed
