### ISSUE TITLE
JITLib .clear -> "/n_set Node x not found"

### ISSUE THREAD

**Issue by jamshark70** [supercollider/supercollider#2818]
For some reason I can't quite figure out, on my system, very often I get a `/n_set Node x not found` message in the post window after `clear`-ing a NodeProxy.

Dumping OSC messages:

```
p = ProxySpace.new.push;

~b = { DC.kr(2) };  // this is OK
->
[ "#bundle", 1, 
  [ 5, DATA[458] ],
  [ 21, 1400, 1, 1 ],
  [ "/sync", 1038 ]
]
[ "#bundle", 15890370949474061091, 
  [ 9, "temp__0b1156849135_0", 1401, 1, 1400, "out", 1, "i_out", 1 ]
]

~b.clear;

[ "#bundle", 15890371165666350431, 
  [ 15, 1400, "fadeTime", 0 ],
  [ "/error", -1 ],
  [ 15, 1401, "gate", -1, "fadeTime", 0 ],
  [ "/error", -2 ]
]
-> NodeProxy.nil(localhost, nil)
[ "#bundle", 1, 
  [ "/c_fill", 1, 1, 0 ]
]
[ "#bundle", 1, 
  [ 53, "temp__0b1156849135_0" ],
  [ "/sync", 1039 ]
]
[ 11, 1400 ]
FAILURE IN SERVER /n_set Node 1400 not found
```

In the `clear` sequence, only one `n_set` message addresses node 1400 (the first one), and this is in a bundle with a timestamp. `[ 11, 1400 ]`, freeing the group, is sent without a timestamp.

I see in the source code that the group-free message is scheduled for fadeTime + latency later, and in fact, as I watch the post window, I see that the server reposts that last message after a short delay. So, *in theory*, the server should be waiting to free the group... but in practice, on my machine, the group-free message is evaluating first and the timestamped messages are happening just slightly later.

I suspect the issue may be occurring in Linux without being noticed in OSX because time values in Linux are large floats -- meaning that the resolution beneath the decimal point is smaller.

I'm not going to try to fix this, but I think the group-free needs to be timestamped as well. We'd like to assume that two different scheduling methods would mesh seamlessly, but it seems that you can't make this assumption for all environments.

(Despite the dev backlog, I guess this will be an easy fix -- and it is user facing. It looks untidy to see errors for a properly-written instruction.)

**Comment by telephon** [comment]
i'll check asap

**Comment by telephon** [comment]
@jamshark70 take a look if this helps in your case.

**Comment by telephon** [comment]
this is fixed, isn't it?

**Comment by telephon** [comment]
closing. if it reappears, feel free to reopen.
