### ISSUE TITLE
Use indentation at 4 spaces in all C/C++ project files

### ISSUE THREAD

**Issue by brianlheim** [supercollider/supercollider#2819]
More discussion at #2094.

Inb4 flame war etc. etc.

# Proposal

Use 4 spaces for indentation in all C/C++ code files in the SuperCollider repo. This would (by my estimate) include most of the files in /lang, /server/scsynth, /server/plugins, /include, and /common. I'd like to keep the argument over spaces and tabs to a minimum when it doesn't involve reasons that are directly related to this repo, please.

# Justification 

This **needs** to happen at some point. Yes, some of us can configure our editors to use one convention and not the other in certain project folders, but for some IDEs (Xcode) it's not possible, and jumping around between project files when targeting a header in /common, like I'm doing with `SC_DirUtils.h` right now, gets incredibly tedious.

This is a significant reason for developers to avoid the SC codebase. Requiring a special introduction to Indentation in SuperCollider for every new developer is a time-waster and immediately sours people on the project. Moreover, if it's not fixed, discussions just like this and #2094 are inevitably going to crop up time after time. If you don't think that's a problem, just spend a minute thinking about how much time was spent on the discussion at #2094.

# Why Spaces

## Modernization

As @timblechmann pointed out, most modern projects (including Boost and Qt) use spaces for indentation, and `git blame -w` is a fix for the blame/history concern.

See style guides for [Google](https://google.github.io/styleguide/cppguide.html#Spaces_vs._Tabs), [Boost](http://www.boost.org/development/requirements.html), [Qt](https://wiki.qt.io/Qt_Coding_Style), which all propose spaces; Boost's also gives a rationale.

[Microsoft](https://msdn.microsoft.com/en-us/library/aa260844(VS.60).aspx) just recommends consistency.

C++ audio libraries such as [JUCE](https://github.com/julianstorer/JUCE) use 4 spaces.

## Recent code is in spaces

It is true as @muellmusik pointed out that the older (original) code was written in tabs. However, I would argue that this is not a point distinctly in favor of either side. While it's definitely a good idea to respect existing conventions, it's also true that a good deal of that code has barely been touched since the initial commit or a few years thereafter. This means that the code people are most used to looking at and maintaining is in spaces, not tabs. For instance, look at the average time-since-last-commit values for the code in spaces:

- https://github.com/supercollider/supercollider/tree/master/editors/sc-ide
- https://github.com/supercollider/supercollider/tree/master/SCDoc
- https://github.com/supercollider/supercollider/tree/master/server/supernova/server

and tabs

- https://github.com/supercollider/supercollider/tree/master/lang/LangSource
- https://github.com/supercollider/supercollider/tree/master/lang/LangPrimSource
- https://github.com/supercollider/supercollider/tree/master/server/scsynth

I see far more files that are 4-6 years untouched in the second group.

## Clarity

This is the only thing I'll say from a non-repo-specific point of view. Tabs are inconsistent. Every editor has a different default setting, and when you use different sizes, handmade alignments in the code that depend on tab spacing break and the code becomes difficult to read despite the original author's effort. Even if you set it consistently across all your editors to something readable like 2 or 4, GitHub's viewer uses ~8~ 4.

# Why 4 Spaces

The existing files that use spaces, use 4 spaces.

**Comment by muellmusik** [comment]
> git blame -w is a fix for the blame/history concern

Can github be configured to blame a la -w? Given that we have a rather gh integrated workflow it would still be a major issue if responsibility for thousands(?) of lines were obscured in this way.

**Comment by gusano** [comment]
@muellmusik from http://codeinthehole.com/tips/pull-requests-and-other-good-practices-for-teams-using-github:

> Github easter egg: add ?w=0 to diff URLs (eg a commit, compare view or pull request) to ignore whitespace.

although I never tried it

**Comment by brianlheim** [comment]
@gusano, I love using that for PRs. It doesn't seem to work for blame though (maybe it's just me.

@muellmusik: This is another reason I would argue in favor of spaces. About half of the blame history being veiled by this change would be from very, very old commits (2002-2003, including 'initial commit'). Not so for the IDE and supernova. I find myself editing files and running into this problem much more frequently than using `git blame`, FWIW :)

```bash
[brianheim@BrianMBP supercollider]$ for file in ./lang/*/*.*; do git blame $file | grep 200[23] | wc -l >>counts.txt; done; awk '{s+=$1} END {print s}' counts.txt
22144 # lines in ./lang that are from 2002-3 (it's a few thousand less for just 2002)

[brianheim@BrianMBP supercollider]$ for file in ./lang/*/*.*; do git blame $file | grep -v 200[23] | wc -l >>uncounts.txt; done; awk '{s+=$1} END {print s}' uncounts.txt
32661 # lines in ./lang from later

[brianheim@BrianMBP supercollider]$ for file in ./lang/*/*.*; do git blame $file | grep "2009-09-26 06:17:48" | wc -l >>timcounts.txt; done; awk '{s+=$1} END {print s}' timcounts.txt
4305  # lines in ./lang that are from Tim's "remove trailing whitespaces" commit (i.e. already veiled)

[brianheim@BrianMBP supercollider]$ for file in ./server/scsynth/*.*; do git blame $file | grep 200[23] | wc -l >>serveruncounts.txt; done; awk '{s+=$1} END {print s}' serveruncounts.txt
7171  # lines in ./server/scsynth from 2002-3

[brianheim@BrianMBP supercollider]$ for file in ./server/scsynth/*.*; do git blame $file | grep -v 200[23] | wc -l >>servercounts.txt; done; awk '{s+=$1} END {print s}' servercounts.txt
9522  # lines in ./server/scsynth from later
```

**Comment by scztt** [comment]
Timing-wise - maybe do this as soon as a 3.9 branch is created? This should protect devs from having to make laborious adjustments to 3.9-critical fixes - and post-3.9 PR's will have a little more time to get cleaned up per new rules. It might be best to (1) create a "whitespace cleanup" branch, (2) halt all commits to master (since they'll immediately conflict with ws branch), (3) when whitespace cleanup is complete, squash-merge back to master so there's only one "great 2017 \s cleanup" commit, (4) reconcile existing PR's against the new cleaned-up master.
And, since it'll smack the commit history of the whole repo a bit (blame -w notwithstanding), maybe it's a good opportunity to set aside some time to fix OTHER code cleanliness issues too (trailing whitespace, other weird / non-standard indentation, newlines, etc).

**Comment by brianlheim** [comment]
@scztt Yes, great ideas! I'm in favor of all of that.

**Comment by gusano** [comment]
@brianlheim Don't forget that we use `lintspaces-cli` as well :)
https://github.com/supercollider/supercollider/blob/master/.travis/before-script-linux.sh#L3
https://github.com/supercollider/supercollider/blob/master/.editorconfig

**Comment by smoge** [comment]
Sounds like a solid idea, and scztt's plan will reduce many of the negative aspects of this change. Why not also including the sc class lib, and maybe writing down a short and simple "style guide" for both c++ and sclang code?

**Comment by telephon** [comment]
the class lib has always been tabs, so the change is likely to create a mix in people's own libraries

**Comment by muellmusik** [comment]
> the class lib has always been tabs, so the change is likely to create a mix in people's own libraries

Yes, please do not do that. It is a recipe for a mess.

**Comment by brianlheim** [comment]
I also don't support SC class lib spaceification, or I at least see it as a separate issue that I'd like to avoid tying to this one. There exists on the github.io site a brief style guide, but it mostly points out that many conventions in the code are loosely applied. :) Since the style guide would probably be brief, I think it would make sense to put it in a Contributing.md

**Comment by smoge** [comment]
There are some conventions in the class lib that are not documented in a style guide. Not that the variety in the way of writing is a bad thing; but for projects with several programmers, it is good to have a reference even that would be helpful even for outside the class lib (collaborative quarks etc).

**Comment by vivid-synth** [comment]
I'm fine with doing or not doing this, but if we do, let's make the change quickly and be loud about the fact we're doing it beforehand (so we don't make too many merge conflicts for in-progress work)

This is gonna make a *lot* of merge conflicts!
