### ISSUE TITLE
Make JNA interop easier

### ISSUE THREAD

**Issue by jleben** [supercollider/supercollider#282]
[Issue migrated from SourceForge | ID: 2963287 | Submitted by 'nobody']
[http://sourceforge.net/support/tracker.php?aid=2963287]

I would like to use JNA to interface with libscsynth.
But this does not work because the World_Options struct is not JNA compatible
and is platform dependent.
I would like to propose some additional functions for starting scsynth in a more JNA friendly manner.
An example can be found over here:
http://github.com/mozinator/clj-scsynth/tree/master/supercollider-changes/

**Comment by vivid-synth** [comment]
If nobody is actively working on this or asking for it we can close it, no?

**Comment by scztt** [comment]
Close it!
