### ISSUE TITLE
scide -> recent files doesn't work

### ISSUE THREAD

**Issue by ycollet** [supercollider/supercollider#2823]
I use supercollider compiled from sources on fedora 25 64 bits.
When I click on a file in the "recent file" list in scide, the file is not opened.

**Comment by snappizz** [comment]
Does this happen even when the file has not been moved or deleted?

**Comment by ycollet** [comment]
The file I try to open has not been deleted.

But supercollider is installed in a non usual directory: 
/opt/supersollider-devel

I also have supercollider-3.7.2 installed as a standard fedora package.

**Comment by snappizz** [comment]
Is the problem consistently reproducible if you save a new file?

**Comment by ycollet** [comment]
Yes, the same problem happens if I create a new file via scide saves it and then try to reopen it via recent files menu.

**Comment by patrickdupuis** [comment]
I don't have a Fedora machine to test on at the moment. I'm pretty certain that I've used 'recent files' without problem in the past. Could be related to your particular system.

**Comment by ycollet** [comment]
I just noticed something today (after total git clone + submodule update + recompilation): when I try to open /home/me/test.sc via recent file menu, a message is printed in the status bar:
" Cannot open file /&home/me/test.sc (file doesn't exist)" ...

**Comment by ycollet** [comment]
Informations related to qt5 installed on Fedora 24:

Nom         : qt5-qtbase
Architectur : x86_64
Époque      : 0
Version     : 5.6.2
Révision    : 3.fc24

**Comment by patrickdupuis** [comment]
Tested on Fedora 25. Scide could create, save, and open file from 'Recent Files' menu when installed into /usr/local and /opt/supercollider. I could not get the interpreter to run when built into /opt/supercollider, however (that's another story).

Try removing the sc3.7.2 package from your system to see if that helps.

**Comment by ycollet** [comment]
I removed all the supercollider packages from my linux box.
I opened scide, enter some text, saves it, restart scide and try to reopen the saved file via recent files and it doesn't work.
I found a message in the console:
```
QSortFilterProxyModel: index from wrong model passed to mapFromSource
```
