### ISSUE TITLE
Potential build fail due to yaml-cpp (serialization.o) being moved to a submodule

### ISSUE THREAD

**Issue by michaeldzjap** [supercollider/supercollider#2825]
I'm trying to build the latest SC from source on OSX 10.12.4, but it fails not too far into the build:

```
/.../supercollider/build/editors/sc-ide/SuperCollider.build/RelWithDebInfo/SuperCollider.build/Objects-normal/x86_64/serialization.o

** BUILD FAILED **


The following build commands failed:
	CompileC build/editors/sc-ide/SuperCollider.build/RelWithDebInfo/SuperCollider.build/Objects-normal/x86_64/sc_introspection.o editors/sc-ide/core/sc_introspection.cpp normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
```

**Comment by bagong** [comment]
Withoug having tried, ( think it's because of the yamlcpp update (serialization). You need to:

````
git submodule init
git submodule update
`````

yamlcpp is a submodule now...

If you confirm that that is the issue, could you rename your issue to something that explains the problem. It's likely that a few others bump into the same problem

Thanks!

**Comment by michaeldzjap** [comment]
Yes, that was it. Thanks for pointing me in the right direction. Would it make sense to add a line about this to the readme? Probably a bit of a overkill, since this could only pose a problem for people who had already cloned the SC source (like me) prior to yaml-cpp being moved to a submodule.

**Comment by brianlheim** [comment]
I'll make a post in sc-dev and sc-users to let people know.

**Comment by slpopejoy** [comment]
To help future web searchers, the error I got today related to this is:

```
/Users/stuart/sc/supercollider/editors/sc-ide/core/settings/serialization.cpp:23:10: fatal error: 'yaml-cpp/yaml.h' file not found
  #include <yaml-cpp/yaml.h>
           ^~~~~~~~~~~~~~~~~
```
