### ISSUE TITLE
Graphical node viewer

### ISSUE THREAD

**Issue by jleben** [supercollider/supercollider#283]
[Issue migrated from SourceForge | ID: 3005241 | Submitted by 'nobody']
[http://sourceforge.net/support/tracker.php?aid=3005241]

I think it would really make life easier if there was a graphical view of the node tree with the following functionalities:
- get a trace of a synth. 
- get a meter view of the output of the synth (detect to which busses the synth is writing, and then make a level meter listener synth checking the level of those buses, immediatelly after the synth in the node graph).

This would be very helpfull for debugging.

and eventually:
- reorder synths.
- pause, un-pause synths.
- free synths.

The graphical view of the node tree in ScalaCollider looks great, and could be of inspiration.

**Comment by snappizz** [comment]
supriya (a Python client for SC) has a pretty cool node viewer based on GraphViz:

![](https://raw.githubusercontent.com/josiah-wolf-oberholtzer/supriya/master/graph.png)

If we don't mind having GraphViz as a dependency, that seems straightforward to make. The major question is whether this functionality is worth having in the core library.

**Comment by vivid-synth** [comment]
Ooh nice! Imo, GraphViz is probably a fine dependency: it's small and well-tested.

**Comment by snappizz** [comment]
I just realized I posted a SynthDef viewer, not a node viewer. The point still stands.

**Comment by crucialfelix** [comment]
IMO core should be kept small and things like this should be in Quarks. but that does mean it has to include cross platform GraphViz somehow.

**Comment by gusano** [comment]
> IMO core should be kept small and things like this should be in Quarks

:+1:

**Comment by scztt** [comment]
There are decent graphviz renderers build in javascript / for browsers. I've tested and they run well in a WebView. Wrapping up a js graphviz view in a decent web page and running it as a webview would be a totally acceptable / easy way to get cross platform graph rendering.

**Comment by crucialfelix** [comment]
BTW there is ServerTools quark which displays node tree with useful annotations and links to view synthdef etc. Osc log too.

But its all in slow sc gui. Someday I will do one in react. Supercollider js has the node state tree as a subscribe able  stream so it's very easy to render that with react

**Comment by snappizz** [comment]
Added to long-term projects list.
