### ISSUE TITLE
Deprecate schedBundle?

### ISSUE THREAD

**Issue by smrg-lm** [supercollider/supercollider#2831]
The extensions in: ./SCClassLibrary/Common/Control/schedBundle.sc do not seem to be used in any place and do not seem to contribute much either (besides undocumented methods).

**Comment by brianlheim** [comment]
They're used in `OSCBundle:-sendAtTime`.

`Class.findAllReferences(\schedBundle)` is an easy way to determine this.

`sendAtTime` doesn't seem to be a very popular method though. Maybe we could deprecate it. @telephon, do you have any thoughts on this?

**Comment by smrg-lm** [comment]
I missed that. Maybe just documentation is missing if is a public method. I was thinking about method pollution in class library though.

**Comment by telephon** [comment]
It is probably used by crucial library. The `atTime` interface is there, I think - maybe the method could be moved there as an extension.

**Comment by brianlheim** [comment]
As long as it's being used somewhere and exists in the main lib, I don't see a reason to move it out.

**Comment by brianlheim** [comment]
Re: pollution, do you mean having unnecessary methods or having namespace pollution? If it's the first, I think it would be a better use of time to discuss suspect methods en masse rather than on an individual basis unless there is a pressing reason to do so.

**Comment by scztt** [comment]
If it's at all useful, I believe the DependencyWalker class in the [QuarkEditor quark](https://github.com/scztt/QuarkEditor.quark) can tell you if a method is being used anywhere in the class library + included extensions. It might be DependencyWalker:*methodsForSelector that does this?

**Comment by crucialfelix** [comment]
It's used extensively in crucial but isn't something native to my library. It's just a way to schedule a bundle and let the argument calculate the delta.

There are other better candidate for euthanasia I think.

Always search quarks for usage btw.

**Comment by telephon** [comment]
@crucialfelix Yes, and the `atTime` interface that you wrote might be a good standard anyhow. But the essential bits are in crucial library, aren't they.

**Comment by brianlheim** [comment]
Sounds like this is good to keep around.

**Comment by smrg-lm** [comment]
A late note I want to share.

For many cases some general purpose functionality provided by quarks should be merged into the main library. Depending on a quark to give sense a main library method doesn't seems to be good at all, it would be reasonable to move that method to the quark.

Also, something important, crucial-library and ctk have many of this cases (.gui and .render are just two examples), and I know the history on this. Ctk solves the nrt problems and crucial-library adds basic functionality for patching but they add overlapping abstractions (another kind of events, buses, synthdefs, etc.), wouldn't it be possible to merge this functionality to the already existing main library classes as part of a more general model? what functionality need to re-implement the whole system? and why not if it is better? This was my thinking for years, but I can't do much about it.

**Comment by joshpar** [comment]
One of the goals of Ctk was to provide an interface where the syntax between RT and NRT could be less divergent. In the 10 years or so since I wrote the bulk of it, I’m sure I could do it much better now! Or someone else. I wouldn’t feel hurt at all if someone could take it over or create something new since maintenance isn’t something I can do much of anymore on it. Ctk had reached a point where I generally found it useful and it eased my own composing. But if something better came along, I’m more than happy to see it deprecate.
