### ISSUE TITLE
CTRL D not working

### ISSUE THREAD

**Issue by bitwo** [supercollider/supercollider#2838]
Bug description: supercollider version 3.9dev CTRL D does not work on 4 lapotp and 2 PC ubuntu studio installations. 

Steps to reproduce:
1. fresh installation
2.
3.

Actual result:

Expected result:

**Comment by bitwo** [comment]
All machines are 64 bit and have installed ubuntu studio (I think is 
based on ubuntu 16.10, low latency kernel) and the latest update/upgrade.

bb@bb-MS-7713:~$ qmake --version
QMake version 3.0
Using Qt version 5.5.1 in /usr/lib/x86_64-linux-gnu
bb@bb-MS-7713:~$



Am 11.04.2017 um 15:52 schrieb Yvan Volochine:

**Comment by bagong** [comment]
Current Qt on Ubuntu Studio 16.10 is 5.6.1. (qmake is 3.0). I cannot reproduce this...

**Comment by bitwo** [comment]
bb@bb-MS-7713:~$ qmake --version
QMake version 3.0
Using Qt version 5.5.1 in /usr/lib/x86_64-linux-gnu
bb@bb-MS-7713:~$

My os version:

bb@bb-MS-7713:~$ cat /etc/*-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.2 LTS"
NAME="Ubuntu"
VERSION="16.04.2 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.2 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
bb@bb-MS-7713:~$

Sorry, not ubuntu 16.10? Obviously upgrade does not upgrade?


Am 11.04.2017 um 16:25 schrieb Rainer Schütz:

**Comment by bagong** [comment]
sudo apt dist-upgrade

**Comment by bitwo** [comment]
That's what I did, and just did again, no change of the output cat 
/etc/*-release!

Have to install the new version Ubuntu Studio 16.10 (released October 
14, 2016).


Am 11.04.2017 um 16:49 schrieb Rainer Schütz:

**Comment by bagong** [comment]
Well, if you have to anyways, give it a try. But don't blame me if it doesn't have the wished effect as to ctrl-d ;). You could also try to simulate a brand new SC install by deleting everything in ~/.local/share/SuperCollider and (more importantly) in ~/.config/SuperCollider. The two folder contain local configuration data... (but be aware that this also deletes any Quarks and other extensions, customizations you might have done)

I don't know why sudo apt(-get)) dist-upgrade doesn't bring you to 16.10. Maybe some setting restricts you to long-term-supported releases? 16.10 is just a short-term-support release... Check in the package manager or google how to make that setting in Ubuntu Studio. But a clean slate install also has its advantages and is probably as quick. So it's about what you have to lose ;)

**Comment by snappizz** [comment]
#2785?

**Comment by snappizz** [comment]
Maybe it isn't that. Let's try to bisect this and see whether it's scide or sclang. Does `HelpBrowser.openHelpFor("Object")` work?

**Comment by bitwo** [comment]
https://www.youtube.com/watch?v=7-fd8tWN8lw

Hedwig's Fugue zu Ostern.

**Comment by bagong** [comment]
Ebenfalls frohe Ostern ;)

**Comment by bitwo** [comment]
https://www.vorwaerts.de/artikel/afd-politiker-jens-maier-breivik-handelte-verzweiflung

https://www.youtube.com/watch?v=Bc0XNKJQjdI

Das Originalvideo wurde wohl gelöscht? Finde ich nicht, zumindest nicht 
einfach.

https://www.youtube.com/watch?v=Qm3_UKRtFzM

Höche hat auch wieder einen Skandal. Klingt schon ganz normal und das 
ist auch Absicht.

BERND Höcke schafft es endlich ins ZDF heute journal 19.04.2017 mit 
Marietta Slomka:

https://www.youtube.com/watch?v=yn1dkc_-j3U
