### ISSUE TITLE
textView Iphone Supercollider

### ISSUE THREAD

**Issue by jleben** [supercollider/supercollider#285]
[Issue migrated from SourceForge | ID: 3006612 | Submitted by 'nobody']
[http://sourceforge.net/support/tracker.php?aid=3006612]

Add textView functionality to GUI classes of Iphone port

**Comment by vivid-synth** [comment]
(can we create an "os: iOS" label and add it to this?)

**Comment by vivid-synth** [comment]
Similar to https://github.com/supercollider/supercollider/issues/289 , can anyone who uses iOS SC comment if these are still relevant tickets?

**Comment by vivid-synth** [comment]
Given nobody's said they need these, and the discussion about incompatibilities with the App Store, closing this and https://github.com/supercollider/supercollider/issues/289
