### ISSUE TITLE
sclang: freed buffer can still send OSC messages

### ISSUE THREAD

**Issue by brianlheim** [supercollider/supercollider#2851]
See discussion at #2846.

### Issue description

Since `nil` is replaced with `0` when converting an array to an OSC message in sclang, the following code behaves unexpectedly:

```
s.boot;
b = Buffer.read(s, Platform.resourceDir +/+ "sounds/a11wlk01.wav");
a = { PlayBuf.ar(1, b, loop: 1).dup }.play;
c = Buffer.alloc(s, 4096, 1);

c.free; // c.bufnum is now nil

c.write; // writes buffer `b`
c.set(0, 1); // adds a single-sample impulse to buffer `b`
c.zero; // zeros out buffer `b`
```

The expected behavior is that the last three lines do nothing.

#2846 solved this problem for one command only (`.free`), but it persists in the others mentioned above and potentially for `Bus`es as well (as @jamshark70 mentioned).

### Proposed solution

A freed buffer or bus should no longer send OSC messages once it's been freed. Trying to do so should also post a warning message. This makes it easier for the user to catch logic errors, and it is easy to avoid the warning by (properly) wrapping a potentially bad call in a buffer validity check.

**Comment by telephon** [comment]
Good point. In Bus, there is already `isSettable`, which can be extended if we allow ourselves a mor general error message.

**Comment by patrickdupuis** [comment]
This issue should be milestoned 3.9.

**Comment by patrickdupuis** [comment]
I'd be willing to start working on the Buffer class, with some guidance of course :)

**Comment by patrickdupuis** [comment]
i've created a branch in my fork https://github.com/patrickdupuis/supercollider/commit/372d364fe9d1b7a5c5c247b3051b6983f8646634 This is a proposed fix with more that needs to be done. Please have a look and review/critique away!
