### ISSUE TITLE
Improve debug output for Rest

### ISSUE THREAD

**Issue by snappizz** [supercollider/supercollider#2854]
I'm not a fan of the debug output when printing, say, a list with a Rest in it:

    [3, Rest(3)]
    // -> [3, a Rest]

Just want a quick answer on this -- would it be a good idea if this instead printed `[3, Rest(3)]`?

I tried adding a `Rest:asString` but it doesn't seem to do anything for printing collections.

**Comment by telephon** [comment]
This is implemented in #2802

**Comment by telephon** [comment]
if you want to add support for the post window, you have to implement `printOn`, and if you want to support `asCompileString` (or `cs`), you implement `storeOn`.

**Comment by jamshark70** [comment]
Yes, it's there. Quite a lot of new stuff in that branch since `printOn` was added -- it's worth pulling the newer branch before testing further.

I'll close.
