### ISSUE TITLE
Full Unicode compatibility within strings

### ISSUE THREAD

**Issue by jleben** [supercollider/supercollider#288]
[Issue migrated from SourceForge | ID: 3054190 | Submitted by 'nobody']
[http://sourceforge.net/support/tracker.php?aid=3054190]

Currently when one wants to use non-English language in the user interface, he musts type ASCII codes rather than typing the letters directly. As SC appears to gain more and more success, it would be nice if other languages could be used within the strings, so plain Unicode compatibility would be nice.

**Comment by scztt** [comment]
Implemented.

**Comment by muellmusik** [comment]
I think maybe this should request stay open if we want "full" unicode compatibility. Indexing into a unicode string  doesn't work for instance. We should also support unicode Chars.

**Comment by muellmusik** [comment]
But could have the 3/7 milestone removed.

**Comment by bagong** [comment]
To echo @muellmusik: I am pretty sure the original poster meant that we can have unicode in strings and operate with them just the way we can with ASCII strings."

**Comment by brianlheim** [comment]
Operating on strings as a collection of grapheme clusters [as in Swift](https://developer.apple.com/library/content/documentation/Swift/Conceptual/Swift_Programming_Language/StringsAndCharacters.html) would require totally changing the implementation of String and/or Char, which is not high priority at the moment. Closing, but left a note [here](https://github.com/supercollider/supercollider/projects/2#card-1370321).
