### ISSUE TITLE
landscape view and "save to file" iphone

### ISSUE THREAD

**Issue by jleben** [supercollider/supercollider#289]
[Issue migrated from SourceForge | ID: 3097608 | Submitted by 'nobody']
[http://sourceforge.net/support/tracker.php?aid=3097608]

it is not possible to save code and type normally in current state of iphone supercollider, we need landscape mode and ability to save code to file to re-use it later.

**Comment by vivid-synth** [comment]
(can we create an "os: iOS" label and add it to this?)

**Comment by vivid-synth** [comment]
(Honest question!:) Is iPhone SC still supported and working? Can someone who uses it comment on if this is still an issue?
