### ISSUE TITLE
[Bugs] WiiMote Class - MacOS

### ISSUE THREAD

**Issue by tiagmoraismorgado** [supercollider/supercollider#2899]
# <b>I should make clear that:</b>

-    _WiiMote class is stable in terms of Syncing and communication within Linux_
-    _The Same doesn't happen in MacOS_

**among recurrent bugs in WiiMote class are the facts that:**

-    _it doesn't sync properly_ **(sometimes it doesn't simply sync)**
-    _it doesn't communicate properly within the server_ **(faulty/jittery communication, sometimes stops responding)**

**Even though stating that it's not necessarely a priority to fix this, i think:**

-    _we should add it to the list of things to fix in supercollider on the mid-long run_ (low priority)._ 

**please feel free to drop your comments on my statement. Looking forward to hear from you**

**Kind regards
T.**

**Comment by snappizz** [comment]
hi tiago, thanks for the report. unfortunately [wii classes have been deprecated in 3.9](https://github.com/supercollider/supercollider/pull/2697) and will be removed in a future version of sc.

**Comment by tiagmoraismorgado** [comment]
maybe that's a good option

**Comment by brianlheim** [comment]
@tiagmoraismorgado Unfortunately it can't be maintained as a quark; the code supporting it includes C++ primitives.

**Comment by snappizz** [comment]
best option right now is to use a third party wii implementation in another language and use inter-process communication with sclang.

**Comment by tiagmoraismorgado** [comment]
such as osculator
