### ISSUE TITLE
Feature Request - [SC-Doc] Further Developing the CSS and overall layout of the Documentation

### ISSUE THREAD

**Issue by tiagmoraismorgado** [supercollider/supercollider#2901]
<b>Hey Ho Everyone</b>

I would like ask you guys to consider, further developing the overall _css layout_ of **supercollider documentation,** by bridging it with technologies such as:

- <b>_**angular, bootstrap, foundation, synphony, sass, etc.**_</b>

One way to do so, would be grabbing a **css template** and try to coming up with something that is actually a bit neater. Please give me your insights on this regard. if you find it relevant, i may eventually start working on it.

<b>Kind regards</b>
<b>Tiago</b>

**Comment by brianlheim** [comment]
Another spurious request to connect one technology to another without any significant benefit. You are welcome, as always, to work on any of these proposals.

**Comment by tiagmoraismorgado** [comment]
hey @brianlheim i honestly believe that the css of the documentation should be improved. it's not about linking to technologies. it's about trying to find better ways to do things. in my perspective, such an improvement would benefit supercollider UI within a considerable regard. for me linking technologies with one another is one of the greatest advantages of opensource. and that's where for instance openframeworks excels. in bringing together different things, that once encapsulated into a main project, can bring a tremendous and powerful thing. that's why openframeworks is such a powerful thing (not to say that supercollider isn't). and I believe that supercollider is far much more about narrowing technologies, and staying consistent, and even a bit orthodox, with something that has already been there for a certain amount of time, and seems to work fine, for most people. for me the technologies used to accomplish such a goal, may perfectly be the ones which are already there, i have nothing against that. but i think there should be done something done about the supercollider css. maybe i have too many ideas. and instead starting shouting them once in a while, i should grab a few and working on it. that said i think there's no way to adjectivate my requests in such a way. but i see your point. thanks for your insight

**Comment by brianlheim** [comment]
@tiagmoraismorgado, again, as many people have said to you already, you should work on some of these ideas and see how they play out; we are not opposed to making SC more open and bridgeable, but we only have so many people and so much time.

if you prefer throwing ideas from the sidelines, i would encourage you to email the sc-dev list first. more people will see it and people will be more receptive to brainstorming.

**Comment by snappizz** [comment]
i would not be opposed to modernizing our javascript codebase and/or improving the design of scdoc. however, as far as web design tasks go, fixing up our website is way more urgent.
