### ISSUE TITLE
Pitch.kr median is incorrectly set

### ISSUE THREAD

**Issue by vivid-synth** [supercollider/supercollider#2904]
As eagle-eyed @snappizz noted in #2586 , the median filter size for Pitch.kr is set from the input audio, when it should be set from the median argument. That's here: https://github.com/supercollider/supercollider/blob/28713cd79e212c0cdd9b6efd18a4eda83fec46bc/server/plugins/DelayUGens.cpp#L1789

**Comment by tiagmoraismorgado** [comment]
I definitely think we should fix this for version 3.9
