### ISSUE TITLE
problems building on macOS

### ISSUE THREAD

**Issue by tiagmoraismorgado** [supercollider/supercollider#2905]
<h1><b>[BUG]</b> <i>Server Status On Supercollider 3.9dev MacOs Sierra #2905</i></h1>

I have recently gone throughout the process of compiling **supercollider 3.9 dev** on **macos sierra.** First i tried to **compile it by pre-fixing qt 5** and it compiled but then **crashed at loading.** when I compiled it with **qt 5.5,** i was **successful** doing so, but i **_encountered a couple of bugs:_**

- **supercollider help doesn't run** _(that has something to do with the porting of some qt creator assets, and there are people already handling that)_
- **status bar doesn't load when  when you boot the server** _(keeping white, and not showing cpu load)_

i've **compiled supercollider on:**

**macos 10.12.5**, using an upgraded **mac a1278,** **mid 2011,** with **8 gb of ram,** an **ssd drive**, and a **sata drive.** i used **qt 5.5,** and i used **xcode 8.3.2.** i follow the **exact instructions found on the readme file in supercollider 3.9 dev**.

![captura de ecra 2017-05-31 as 13 58 38](https://cloud.githubusercontent.com/assets/7303598/26632818/48f7bde2-4609-11e7-8348-de006f9218c0.png)

**Comment by brianlheim** [comment]
Hi @tiagmoraismorgado, I just built this morning with nearly the same equipment and software (only difference is mid-2015 instead of mid-2011 model). Can you please retry, and post the steps you took here?

**Comment by tiagmoraismorgado** [comment]
hey @brianlheim  here are the steps i followed

```
cd ~/workspace
git clone --recursive https://github.com/SuperCollider/SuperCollider.git
cd Supercollider
mkdir -p build
cd build
brew update
brew upgrade git cmake libsndfile readline qt5.5
xcode-select --install
sudo softwareupdate -irv
cmake -G Xcode -DCMAKE_PREFIX_PATH=`brew --prefix qt55`  ..
(won't compile with prefix qt 5)
cmake --build . --target install --config RelWithDebInfo
```

**Comment by tiagmoraismorgado** [comment]
**_by the way, i would like to add the following (as discussed with @brianlheim and @snappizz) on gitter this is what i get when i run a git status on the repository:_**
```
git status
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working tree clean
```

**_brew --prefix qt55_**
```
brew --prefix qt55
/usr/local/opt/qt@5.5
```

output of compiling
```
-- Analyzing app='/Users/a____/workspace/supercollider/build/Install/SuperCollider/SuperCollider.app'
-- bundle='/Users/a____/workspace/supercollider/build/Install/SuperCollider/SuperCollider.app'
-- executable='/Users/a____/workspace/supercollider/build/Install/SuperCollider/SuperCollider.app/Contents/MacOS/SuperCollider'
-- valid='1'
-- executable file 1: /Users/a____/workspace/supercollider/build/Install/SuperCollider/SuperCollider.app/Contents/MacOS/sclang
-- executable file 2: /Users/a____/workspace/supercollider/build/Install/SuperCollider/SuperCollider.app/Contents/MacOS/SuperCollider
-- executable file 3: /Users/a____/workspace/supercollider/build/Install/SuperCollider/SuperCollider.app/Contents/Resources/scsynth
-- verified='1'
-- info='Verified 3 executable files in '/Users/a____/workspace/supercollider/build/Install/SuperCollider/SuperCollider.app''
-- 
-- verified='1'
-- info=''
-- 
-- fixup_bundle: done
** BUILD SUCCEEDED **
```

**_output of brew info_**
```
qt@5.5: stable 5.5.1 (bottled) [keg-only]
Cross-platform application and UI framework
https://www.qt.io/
/usr/local/Cellar/qt@5.5/5.5.1_1 (7,330 files, 330.5MB)
  Poured from bottle on 2017-05-30 at 21:16:08
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/qt@5.5.rb
==> Requirements
Build: xcode ✔
Required: macOS >= 10.8 ✔
==> Caveats
We agreed to the Qt opensource license for you.
If this is unacceptable you should uninstall.

This formula is keg-only, which means it was not symlinked into /usr/local,
because this is an alternate version of another formula.

If you need to have this software first in your PATH run:
  echo 'export PATH="/usr/local/opt/qt@5.5/bin:$PATH"' >> ~/.bash_profile

For compilers to find this software you may need to set:
    LDFLAGS:  -L/usr/local/opt/qt@5.5/lib
    CPPFLAGS: -I/usr/local/opt/qt@5.5/include
For pkg-config to find this software you may need to set:
    PKG_CONFIG_PATH: /usr/local/opt/qt@5.5/lib/pkgconfig
```

**_cmake config phase_**
```
-- SuperCollider Version: 3.9dev
-- Building from branch master, commit hash is 4f12ca025
-- Please specify the build configuration in the next step
-- Compiling with Qt GUI
-- building boost libraries manually
-- using bundled libyaml-cpp
-- HIDAPI components:
--     mac
--     hidapi_parser
-- Building with HID support
-- Audio API: coreaudio
-- Found a homebrew install of readline /usr/local/opt/readline
-- Found GNU Readline version 7.0: /usr/local/opt/readline/lib/libreadline.dylib
-- Found Qt: /usr/local/opt/qt@5.5/lib/QtCore.framework/QtCore
-- Compiling with Readline support
-- Building the Qt IDE
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/a____/workspace/supercollider/build
```

**Comment by tiagmoraismorgado** [comment]
by the way @brianlheim thanks for all the support on gitter to troubleshoot this tiny little bug

**Comment by brianlheim** [comment]
@tiagmoraismorgado Thanks for the info. Nothing looks immediately wrong to me, except that your config phase is missing a line about `libpthread`. In a [Gist,](https://gist.github.com/) can you post the contents of `./build/CMakeCache.txt`?

**Comment by tiagmoraismorgado** [comment]
https://gist.github.com/tiagmoraismorgado/94891bc476d4ae07b20c8a7fb940de81

**Comment by brianlheim** [comment]
Hm okay, I'm not sure what to suggest now. Our machines are very similar, and I used to have no problem on my older mac (mid 2011) either, so I think this is an issue specific to your machine or specific build steps. If you haven't already, try removing your build directory `rm -rf build` and start the build process again from scratch. This time, try compiling with `--config Debug`. Also, what are your steps to run after building? Which application are you running?

**Comment by tiagmoraismorgado** [comment]
hey brian can you just point me to the whole command to build with --config Debug? cheers

**Comment by brianlheim** [comment]
```
cd ~/workspace
git clone --recursive https://github.com/SuperCollider/SuperCollider.git
cd Supercollider
mkdir -p build
cd build
brew update
brew upgrade git cmake libsndfile readline qt5.5
xcode-select --install
sudo softwareupdate -irv
cmake -G Xcode -DCMAKE_PREFIX_PATH=`brew --prefix qt55`  ..
#wontcompilewithprefixqt5
cmake --build . --target install --config Debug
```

**Comment by brianlheim** [comment]
this has gotten stale, and doesn't seem like anyone can reliably reproduce, so i'm closing. please continue to share updates if you have them @tiagmoraismorgado
