### ISSUE TITLE
[IMPROVEMENT] Adding All The Necessary Binaries For Compiling Locally To The Supercollider Main Repo

### ISSUE THREAD

**Issue by tiagmoraismorgado** [supercollider/supercollider#2909]
# Greetings
**This is not really a bug**, and **since we have been busy mostly fixing bugs on supercollider,** to make it **rocket solid,** rather then **being constantly implementing new features,** i **don't know how far could this be an advantage, but i see it as so.** I would like to **suggest you all to:**
- _adding a folder with all the **macosx necessary dependencies for building** (including the ones you get from homebrew)_.
- _doing the same with **linux**, **windows**, and **all the other plattforms**_.
- _linking those accordingly to **cmake plattform dependent building scripts**_
- _linking the **binaries of all the necessary tools for building supercollider for each maintained plattform**_

**Comment by brianlheim** [comment]
No. This is why we have package managers. This would bloat the repo to a ridiculous size, especially with Qt. We bundle enough as it is (boost, portaudio, libsndfile). If there is a specific item that you want, please suggest it.

**Comment by tiagmoraismorgado** [comment]
**maybe you are right @brianlheim. bearing this in mind. i would like to suggest the following:**
- _we create an universal script for compiling supercollider for all plattforms, that goes throughout installing the package managers, when necessarry (in case of homebrew) and installs all the necessary binaries automatically, while giving the users the possibility to tweak things along the way_

**Comment by brianlheim** [comment]
That's been suggested before, and there are scripts out there. IMO we don't need one in the main repo.

**Comment by miguel-negrao** [comment]
A build script that installs a package manager is not very common. I wouldn't want a build script to do that for me.
Installing the needed packages would require a lot checks for each package manager and os/distro version. I wouldn't recommend using sc-dev time to maintain such a script.
 It could be interesting to make sc packages for package managers where packages are sort of self-contained such as snaps or nix package manager, but I reckon that's low priority.
