### ISSUE TITLE
style: Notation and placement of argument lists

### ISSUE THREAD

**Issue by brianlheim** [supercollider/supercollider#2913]
# Issue

## Placement

We should decide on where we prefer to place argument lists in the class library. We have a few options:

### Same line as opening brace
```supercollider
*func { arg input;
    var result = input.doSomething;
    ^result;
}
```

### Line after opening brace
```supercollider
*func {
    arg input;
    var result = input.doSomething;
    ^result;
}
```

## Notation

We should decide on which we prefer in the class library:

### 'arg'

```supercollider
arg input, multiplier, offset;
```

### Pipe notation, with commas

```supercollider
| input, multiplier, offset |
```

### Pipe notation, without commas

```supercollider
| input multiplier offset |
```

**Comment by gusano** [comment]
- arg: mmmhhhh so we stay in the 90s right? but at least *please* not on a new line
- pipe notation with commas: yes :+1: 
- pipe notation without commas: I don't mind but I feel this would be a huge jump into modernism :) maybe with commas first

**Comment by miguel-negrao** [comment]
completely subjective, but I prefer "Pipe notation, with commas"... I didn't even know you could use without commas... :-)

**Comment by brianlheim** [comment]
So am I right in thinking that the reason we prefer `func { | a, b, c |` over
```supercollider
func { arg a, b, c; /* ... */ }
// or
func {
    | a, b, c |
    /* ... */
}
```
is because it's semantically closer to `func(a, b, c) {` and to smalltalk `func: [ :a :b :c |` (not a smalltalk user, but I think I've got that right)? And so then @gusano's

> pipe notation without commas: I feel this would be a huge jump into modernism :)

is also from a desire to move toward the smalltalk notation? I feel like there's something unspoken here that I'm not 100% getting.

**Comment by jamshark70** [comment]
To my knowledge, nobody in over 10 years has ever suggested switching the class library to pipe notation without commas. It's not only that it's unspoken... it just isn't there.

I concur with previous posters: args on the same line, and prefer pipe notation with commas.

**Comment by miguel-negrao** [comment]
> So am I right in thinking that the reason we prefer func { | a, b, c | over
> 
> func { arg a, b, c; /* ... */ }
> // or
> func {
>     | a, b, c |
>     /* ... */
> }
> 
> is because it's semantically closer to func(a, b, c) {

In my case, yes.

**Comment by snappizz** [comment]
pipes and commas all the way.

but should we have equal signs? `|x = 3, y = 4|` looks better than `|x(3), y(4)|`, but `|x(3.rand), y(2 ** 16)|` looks better than `|x = (3.rand), y = (2 ** 16)|` :/

**Comment by telephon** [comment]
>To my knowledge, nobody in over 10 years has ever suggested switching the class library to pipe notation without commas. It's not only that it's unspoken... it just isn't there.

James McCartney suggested to do that, he changec `Collection`, but stopped, I think because I had suggested (incorrectly, I think today) that it doesn't look so good for class files.

What is really entirely unidiomatic is to add a newline before `arg`. There may be good arguments for doing this, but hardly anyone does it …

**Comment by telephon** [comment]
… but james, you are right that ever since nobody has suggested it!

**Comment by brianlheim** [comment]
> What is really entirely unidiomatic is to add a newline before arg. There may be good arguments for doing this, but hardly anyone does it …

Hahaha, this is exactly how I'm used to doing it, I think because I just felt so bad about putting anything after `{`. But going with pipes is much more readable to me. Let's consider that settled!

> but should we have equal signs?

Here's a couple examples

```supercollider
func { | x = (3.rand), y = (2**16) | // 1
func { | x = 3.rand, y = 2**16 | // 2
func { |x = 3.rand, y = 2**16| // 3

func { | x(3.rand), y(2**16) | // 4
func { |x(3.rand), y(2**16)| // 5
```

It seems to me like using equal signs is the prevailing style in the class lib regardless of whether `arg` or `|` is used. (2) and (3) seem equally used depending on the file. I have a slight preference toward (2). Compare:

https://github.com/supercollider/supercollider/blob/master/SCClassLibrary/Common/Collections/Collection.sc

https://github.com/supercollider/supercollider/blob/master/SCClassLibrary/Common/Control/ResponseDefs.sc

**Comment by telephon** [comment]
Yes, I tend toward your preference, @brianlheim. Much of this is actually getting used to a certain layout. But (2) won't work, will it?

`f = { | x = 3.rand, y = 2**16 | x + y };`  fails.

But of course 

f = { | x = 3, y = 2 | x + y };` works and looks good.

A less intrusive convention I've been following when cleaning up was in methods to keep the `arg` keyword as it mostly is, and only use the pipes for functions within the method. But this is arg-uably making a difference where there maybe shouldn't be one.

**Comment by brianlheim** [comment]
>  But (2) won't work, will it?

ha! You're right. I didn't realize that. This makes sense on second thought, you could easily back yourself into an unparseable corner with `| x = 3.rand y = 2 ** 16 |`. So, revised:

```supercollider
// option one
func { | a = 3, b = 4 |
func { | a = (3.rand), b = (5**16) |

// option two
func { |a = 3, b = 4|
func { |a = (3.rand), b = (5**16)|
```

I still prefer the former option.

> A less intrusive convention I've been following when cleaning up was in methods to keep the arg keyword as it mostly is, and only use the pipes for functions within the method. But this is arg-uably making a difference where there maybe shouldn't be one.

Hm, I think this distinction is interesting, but perhaps a little difficult to explain why... A `Method` is different than a `Function` of course, but does the parameter list have much of a role to play in making that difference? It seems to me that the use of the assignment operator is what plays the major role here: `func { /* ... */ }` vs `func = { /* ... */ }`. Perhaps it's too easy to confuse them, but I'm not sure everyone would immediately 'get' `arg`-vs-`||` since the two are in fact interchangeable.

**Comment by telephon** [comment]
I would prefer to think of functions and methods syntactically uniform. It's a bit dishonest to distinguish the two by a syntax that is in fact exchangeable! So for me, not changing `arg` in files has been more about politeness than consistency.

I could agree on either options. I have to admit that in functions, I havealways been using the second:

`array.collect { |x| x + 8 }`

which to me reads better than  

`array.collect { | x | x + 8 }`

But once the list gets longer, and where the body is in a new line, the first seems better.

**Comment by jamshark70** [comment]
The unparseable corner is this (and it's mentioned in the Functions help file:

```
{ |a = b | c | d }
```

... which is, as a specific example, pointless but it shows the parsing problem: it's equally legitimate to parse as `{ |a = (b) | c | d }` (return value is `c|d`) or `{ |a = (b | c) | d }` (return is `d`). So `=` with no parens is valid only for literals, and in `{ | a = 2 | a | b }`, the second pipe is always a closing delimiter and not the operator.

In my own code, I consistently use `|a = 1, b(2.rand)|`.

We have also not talked about spacing. I very strongly dislike spaces immediately inside the pipe delimiters.

- `x.do { | item | item * 2 }` -- what are those pipes for?
- `x.do { |item| item * 2 }` -- visually obvious that the pipes are delimiters, and inside the function, you have fewer distinct visual elements for the human eye to parse.

My rules are:

- `()`, `[]`, quotes, and pipes for arguments:
  - No space inside.
  - No space for nesting: `[[1, 2], 3]`, not `[ [ 1, 2 ], 3 ]` (so I don't like SC's array printing, but I can live with it).
  - In general, spaces between these delimiters and words immediately outside them: `[1, 2] + a` instead of `[1, 2]+a`.
  - *But* I prefer no space between a method name and its arguments: `rrand(1, 10)` rather than `rrand (1, 10)`. Flow of control keywords are methods in SC, so I apply the same rule here: `if(condition)`, `switch(something)`.

- `{ }` - I rigorously put spaces both inside and outside braces: always `{ x }`, never `{x}`. Never, ever the latter. One thing is that a brace looks a lot like a parenthesis. I use spacing to help differentiate them visually.

These are totally subjective, but I am right about all of these points :lol:

**Comment by jamshark70** [comment]
Spaces around arg pipes: I just posted this in #2915, but I think I should bring it here too.

> I justify my preference by noting that we prefer spaces around binary operators (and I agree with that), but if we encourage spaces around arg-pipes, there is no immediate visual distinction between pipe = arglist or pipe = bit-or. IMO that would be a mistake. `{ |a = 1| a }` -- obvious that `|` is a delimiter. `{ | a = 1 | a }` -- when I see `1 | a` here, I have to look backward and see if there's a matching/opening `|` -- it takes more work to read and understand the code.

**Comment by brianlheim** [comment]
@jamshark70 thanks for that! Personally more and more I find myself preferring additional spaces. I think you've got a good argument with single-line notation; let's consider the following examples:

```supercollider
x.collect { |item| item*2 } // 1
x.collect { | item | item*2 } // 2
x.collect { | item | item|2 } // 3

// 4
x.collect { | item |
    item = item*2;
    item = item.abs;
    item
}

// 5
x.collect { |item|
    item = item*2;
    item = item.abs;
    item
}

// 6
func { | time = 0, offset = 3, flowers = true |

    var x = time + offset * 3;
    if( flowers ) {
        ^x
    } {
        ^x.asString ++ "flowers"
    }
}

// 7
func { |time = 0, offset = 3, flowers = true|

    var x = time + offset * 3;
    if( flowers ) {
        ^x
    } {
        ^x.asString ++ "flowers"
    }
}

// 8
func { | time, offset, flowers |

    var x = time + offset * 3;
    ^flowers.if( { x }, { x / 2 } )
}

// 9
func { |time, offset, flowers|

    var x = time + offset * 3;
    ^flowers.if( { x }, { x / 2 } )
}
```

The method bodies are just for context, let's ignore them for the purpose of this discussion.

You're right that (1) is definitely clearer than (2) and especially (3), especially if you were to space out the binary operators (which I personally don't in that particular situation). However, when the block is unrolled over multiple lines, I tend to agree less. I still prefer (5) to (4), but definitely prefer (6) to (7) and marginally (8) to (9). I think this is a situation where the amount of whitespace depends on the conciseness of the overall statement. When we are trying to cram together a couple statements and basically write a small lambda function, I prefer no spaces within the pipes because I'm looking for what one or two functions are being applied, and not the parameter name or default value (there is usually none anyway). But within a larger class method definition, we have more space, and omitting the spaces makes certain notations like 
```supercollider
func { |offset = 3, flowers = true|
```
feel rather cramped to me. In fact, I would just as much prefer
```supercollider
func { | offset=3, flowers=true |
```
because it's easier to visually group the argument with its prototype value.

The size of the list also matters. If there are one or two parameters, it's fine, but if there are three or more, the spaces between commas make the _lack_ of spaces around pipe delimiters a little awkward.
```supercollider
func { |offset|
func { |harp, offset|
func { |harp, tuba, offset|
func { |harp, rotation, tuba, offset| // pipes make it hard for me to scan the list here

// vs


func { | offset | // a bit stodgy
func { | harp, offset |
func { | harp, tuba, offset |
func { | harp, rotation, tuba, offset | // feels very natural to read
```

I'm not suggesting anything right now, but I think there is room for nuance here, both because of personal taste and because arg lists can have so much variation.

**Comment by snappizz** [comment]
just to put my vote in the hat, i use the exact same rules as james. i've always done no spaces inside the pipes, because the contents of argument lists look a little like arrays or argument lists in method calls — `func.value(apples, bananas, oranges)` vs `[apples, bananas, oranges]` vs `|apples, bananas, oranges|`.  i don't put spaces inside delimiters except `{ }`.

**Comment by telephon** [comment]
I also use the same rules, so it seems that we can continue to do so more or less. Your last example is actually kind of nice... If we had syntax colorization for argument lists, this would stand out pretty clearly.

**Comment by brianlheim** [comment]
It sounds like we've reached agreement on this notation:

```supercollider
grow { |maple, spruce|
    /* ... */
}

grow { |maple = 4, spruce = false|
    /* ... */
}

grow { |maple| maple.branchUp }
```

Everyone so far has been in favor of pipes, and if I read the comments correctly, Nathan, Julian, and James all prefer `|gorilla|` to `| gorilla |`, with strength of preference ranging to moderate to strong.

----

These discussions clearly have the potential to stretch on for awhile, so I am going to recommend that we give each style point a few days' worth of time (I'm going to arbitrarily say until Tuesday) and then consider it settled, at which point I will move it to the [WIP guidelines page](https://github.com/supercollider/supercollider/wiki/%5BWIP%5D-Code-style-guidelines). We can continue to modify things in the class library bit by bit, but I think @scztt's idea to glob a bunch of style changes together when we also tackle indentation is a good plan. Thanks to @snappizz for the deadline idea on today's call.

By the way, if anyone wants to discuss another point on that wiki page or something that isn't listed there, feel free to open an issue!

**Comment by jamshark70** [comment]
One final potential case: SynthDef argument lists, at least in my usage (as I strive to make the sound designs configurable), often don't fit on a single line. (I'm referring specifically to SynthDefs because, in properly modular code, functions should be clear and simple without too many arguments, but SynthDefs use arguments for a different purpose and you might legitimately have a ton of them.)

Maybe it doesn't need discussion: long arg lists are likely to be rare in the class library and help. If they don't exist at all, then style guides for the class library and help might not need to consider it.

With that said, this is what I do currently, but I admit it might not be ideal.

```
SynthDef(\name, { |out, freq = 440, amp = 0.1, pan = 0,
	ffreq = 2000, rq = 0.1, ffreqTop = 12000, ffreqDcy = 0.08,
	... etc. etc.
	... etc.|
	var internalSig = ...,
	anotherInternalSig = ...,
	...;
	blah blah
}).add;
```

The closing `|` is almost hidden... but I guess I don't *feel* the obscurity because, if I'm writing a SynthDef that's complex enough to require two or three lines of arguments, it will certainly declare local variables -- so `var` (highlighted as a keyword!) becomes the visual separator.

There might not be a better alternative, though. Visually, it might make more sense to introduce each line of arguments with `arg`, but the SC parser allows only one `arg` block (but multiple `var` blocks).

```
sc3> { arg x; arg y; var z; x+y+z }
ERROR: syntax error, unexpected ARG, expecting '}'
  in file 'selected text'
  line 1 char 12:

  { arg x; arg y; var z; x+y+z } 
           ^^^
-----------------------------------
ERROR: Command line parse failed
```

So `arg` would leave you with only a trailing semicolon as a terminator, which is not any more visible than the `|` (perhaps less visible).

Practically speaking, that's mostly about my private code, but if we're nailing down best practices, might not hurt to make a decision about that as well.

**Comment by brianlheim** [comment]
> Maybe it doesn't need discussion: long arg lists are likely to be rare in the class library and help.

Let's find out!

```
[brianheim@BrianMBP SCClassLibrary]$ egrep -rIw "(arg|\|)([a-zA-Z_ ]*,){7,}[a-zA-Z_ ]*(;|\|)" .
```

```
./Common/Audio/SynthDef.sc:62:	*writeOnce { arg name, func, rates, prependArgs, variants, dir, metadata, mdPlugin;
./Common/Control/HID_API.sc:155:	*doPrAction { | value, physValue, rawValue, arrayValue, usage, page, elid, devid |
./Common/Control/HID_API.sc:235:	*prHIDElementData { | devid, elid, page, usage, rawValue, value, physValue, arrayValue |
./Common/Control/HIDFunc.sc:21:	value { | value, rawValue, usage, page, elid, ele, devid, device|
./Common/Control/HIDFunc.sc:106:	value { | value, rawValue, usage, page, elid, ele, devid, device|
./Common/Control/HIDFunc.sc:155:	value { | value, rawValue, usage, page, elid, ele, devid, device|
./Common/Control/HIDFunc.sc:214:			| value, rawValue, usage, page, elid, ele, devid, dev|
./Common/Control/HIDFunc.sc:230:	*usageID { arg func, elUsageID, elPageID, deviceName, deviceInfo, argTemplate, argTemplateType, dispatcher;
./Common/Control/HIDFunc.sc:304:	initUsageID { | argFunc, elUsageID, elPageID, devName, deviceInfo, argtemplate, argtemplatetype, argdisp |
./Common/Control/HIDFunc.sc:459:	*usage { arg key, func, elUsageName, devUsageName, deviceInfo, argTemplate, argTemplateType, dispatcher;
./Common/Control/HIDFunc.sc:479:	*usageID { arg key, func, elUsageID, elPageID, deviceName, deviceInfo, argTemplate, argTemplateType, dispatcher;
./Common/Control/HIDFunc.sc:500:	*device { arg key, func, elUsageName, deviceName, deviceInfo, argTemplate, argTemplateType, dispatcher;
./Common/Control/HIDFunc.sc:540:	*element { arg key, func, elID, deviceName, deviceInfo, argTemplate, argTemplateType, dispatcher;
./Common/Control/HIDFunc.sc:620:	value { | value, rawValue, usage, page, elid, ele, devid, device, key|
./Common/Control/HIDFunc.sc:644:	value { | value, rawValue, usage, page, elid, ele, devid, device, key|
./Common/Control/ResponseDefs.sc:908:	*new { arg key, func, msgNum, chan, msgType, srcID, argTemplate, dispatcher;
./Common/GUI/Base/EZSpecEditor.sc:10:	init { arg parentView, bounds, label, argControlSpec, labelWidth, labelHeight, argLayout, argGap, argMargin;
./Common/Math/Date.sc:8:	*new { arg year, month, day, hour, minute, second, dayOfWeek, rawSeconds;
./JITLib/GUI/ProxyMonitorGui.sc:31:	init { |w, bounds, showLevel, showPlayN, showName, showPauseSend, makeWatcher, skin|
./JITLib/ProxySpace/BusPlug.sc:326:	playNToBundle { | bundle, outs, amps, ins, vol, fadeTime, group, addAction |
```

So, a handful of cases using 8+ args (only 2 use 9, none have 10).

```
[brianheim@BrianMBP SCClassLibrary]$ egrep -rIn "(arg|\|)([a-zA-Z_ ]*,){6,}[a-zA-Z_ ]*(;|\|)" . | wc -l
      41
[brianheim@BrianMBP SCClassLibrary]$ egrep -rIn "(arg|\|)([a-zA-Z_ ]*,){5,}[a-zA-Z_ ]*(;|\|)" . | wc -l
      80
[brianheim@BrianMBP SCClassLibrary]$ egrep -rIn "(arg|\|)([a-zA-Z_ ]*,){0,}[a-zA-Z_ ]*(;|\|)" . | wc -l
    6386
```

arg lists of 6+ args are pretty rare, about 1.2% of cases. Surprisingly, in help files, even rarer, about 0.17%:

```
[brianheim@BrianMBP HelpSource]$ egrep -rIn "(arg|\|)([a-zA-Z_ ]*,){7,}[a-zA-Z_ ]*(;|\|)" . | wc -l
       3
[brianheim@BrianMBP HelpSource]$ egrep -rIn "(arg|\|)([a-zA-Z_ ]*,){6,}[a-zA-Z_ ]*(;|\|)" . | wc -l
       5
[brianheim@BrianMBP HelpSource]$ egrep -rIn "(arg|\|)([a-zA-Z_ ]*,){5,}[a-zA-Z_ ]*(;|\|)" . | wc -l
       7
[brianheim@BrianMBP HelpSource]$ egrep -rIn "(arg|\|)([a-zA-Z_ ]*,){0,}[a-zA-Z_ ]*(;|\|)" . | wc -l
    4107
```

I can imagine a few ways to notate huge arg lists readably, but most of them are dependent on using spaces instead of tabs, and that's out of course 😿 

What about this @jamshark70 ? Treating the pipes as a legitimate set of braces:
```supercollider
// yours
func = { | size, name, offset, key, entry,
    number, index, geode, amplitude
    gazebo, mayor, powerGrid, freq |
    var x;
}

// Allman style
func = {
    |
        size, name, offset, key, entry,
        number, index, geode
    |
    var x;
}

// K&R
func = { |
        size, name, offset, key, entry,
        number, index, geode
    |
    var x;
}

// same as yours, but following lines have arg lists indented
func = { | size, name, offset, key, entry,
        number, index, geode, amplitude
        gazebo, mayor, powerGrid, freq |
    var x;
}
```

A pipe on its own as a closing brace seems extremely out of place at first glance, but it follows from what others have said above and I could get used to it.

> so var (highlighted as a keyword!) becomes the visual separator.

I think this is a fair point. One thing I would like to recommend, if using the style you have above, is leaving an empty line between argument list and the body of the function.

```supercollider
// yours
func = { | size, name, offset, key, entry,
    number, index, geode, amplitude
    gazebo, mayor, powerGrid, freq |
    var x;
    freq = mayor * gazebo.clip( offset );
}

// with empty line
func = { | size, name, offset, key, entry,
    number, index, geode, amplitude
    gazebo, mayor, powerGrid, freq |

    var x;
    freq = mayor * gazebo.clip( offset );
}
```

I think that small change helps a lot; in a block of code with that many arguments, there is probably going to be some need to visually separate the segments anyway. In any case, I don't have strong feelings about it, and if we came to a decision about it, that would be nice, but I am just as happy to leave this as a special case to be resolved by the individual author.

**Comment by vivid-synth** [comment]
Just a +1 for ```{ | foo, bar | x }``` over ```{ |foo, bar| x }```. I think additional spaces are nice for quick reading -- the reason why ```{ |x| 2 * x }``` feels more readable than ```{|x|2*x}```.

**Comment by jamshark70** [comment]
@vivid-synth The benefit of spacing is that it's different from un-spaced entities. To me, both of your examples are unreadable because there's no differentiation between a large number of single-character units.

**Comment by brianlheim** [comment]
Thank you again everyone for the discussion. I've boiled down what we discussed here and moved it into the WIP style guidelines: https://github.com/supercollider/supercollider/wiki/%5BWIP%5D-Code-style-guidelines#parameter-lists

**Comment by eleses** [comment]
It would be somewhat useful if spacing around the ellipse were discussed/decided too.

```
{ |x, y...a| }   // vs
{ |x, y... a| }  // vs
{ |x, y ...a| }  // vs
{ |x, y ... a| }
```

And also when ellipsis is not preceded by other names

```
{ |...a| }   // vs
{ |... a| }  // vs
{ | ...a| }  // vs
{ | ... a| }
```

Maybe as a different discussion though. (Somewhat related to that, the spacing around dot-dot  #5004, which is actually more complicated because dot-dot is part of two different mixfix operators.)

**Comment by JordanHendersonMusic** [comment]
Just jumping in a *few* years after the fact.

`a = 1` and `a(1)` behave differently if you pass nil, they are **not** a matter of style. In fact, we should pretty much always be using `a(1)` unless you know what `a = 1` does.

Regards new line of arguments, it feels odd to me in this situation.

```supercollider
Cat.meow { |a1, a2, a3, a4 }
    ....
} { |b1, b2, b3, b4|
   ...
} { |c1, c2, c3, c4|
   ...
};
```
vs 
```supercollider
Cat.meow { 
   |a1, a2, a3, a4 }
    ....
} { 
   |b1, b2, b3, b4|
   ...
} { 
   |c1, c2, c3, c4|
   ...
};
```
