### ISSUE TITLE
Make memory addresses in error printing optional and off by default

### ISSUE THREAD

**Issue by snappizz** [supercollider/supercollider#2923]
again, here's the error output for `Server.default.bla`.

```
ERROR: Message 'bla' not understood.
RECEIVER:
Instance of Server {    (0x2ef84b8, gc=48, fmt=00, flg=00, set=05)
  instance variables [27]
    name : Symbol 'localhost'
    addr : instance of NetAddr (0x2ef6bd8, size=4, set=2)
    clientID : Integer 0
    userSpecifiedClientID : false
    isLocal : true
    inProcess : false
    sendQuit : nil
    remoteControlled : true
    options : instance of ServerOptions (0x2ef86e8, size=38, set=6)
    latency : Float 0.200000   9999999A 3FC99999
    dumpMode : Integer 0
    nodeAllocator : instance of NodeIDAllocator (0x2ef6418, size=6, set=3)
    controlBusAllocator : instance of ContiguousBlockAllocator (0x2ef7f38, size=5, set=3)
    audioBusAllocator : instance of ContiguousBlockAllocator (0x2ef77a8, size=5, set=3)
    bufferAllocator : instance of ContiguousBlockAllocator (0x2ef62f8, size=5, set=3)
    scopeBufferAllocator : instance of StackNumberAllocator (0x2ef6288, size=4, set=2)
    tree : nil
    syncThread : nil
    syncTasks : nil
    window : nil
    scopeWindow : nil
    emacsbuf : nil
    volume : instance of Volume (0x26331d8, size=14, set=4)
    recorder : instance of Recorder (0x262b118, size=14, set=4)
    statusWatcher : instance of ServerStatusWatcher (0x2ef99d8, size=20, set=5)
    pid : nil
    serverInterface : nil
}
ARGS:
CALL STACK:
	DoesNotUnderstandError:reportError   0x8b738c8
		arg this = <instance of DoesNotUnderstandError>
	Nil:handleError   0x8b73818
		arg this = nil
		arg error = <instance of DoesNotUnderstandError>
	Thread:handleError   0x8b74058
		arg this = <instance of Thread>
		arg error = <instance of DoesNotUnderstandError>
	Object:throw   0x8b73ad8
		arg this = <instance of DoesNotUnderstandError>
	Object:doesNotUnderstand   0x8b74318
		arg this = <instance of Server>
		arg selector = 'bla'
		arg args = [*0]
	Interpreter:interpretPrintCmdLine   0x7f6ab18
		arg this = <instance of Interpreter>
		var res = nil
		var func = <instance of Function>
		var code = "Server.default.bla"
		var doc = nil
		var ideClass = <instance of Meta_ScIDE>
	Process:interpretPrintCmdLine   0x8b74688
		arg this = <instance of Main>
^^ The preceding error dump is for ERROR: Message 'bla' not understood.
RECEIVER: localhost
```

all the `0x125cbe428` hex memory addresses (that's what they are, right?) should be off by default. also whatever the hell `gc=E4, fmt=00, flg=00, set=05` means, i think we can safely say it is useful to almost nobody.

if they are useful information, then they should be configurable.

**Comment by jamshark70** [comment]
FWIW I have used memory addresses in the past, in cases where I thought two variables had distinct objects but in fact they were pointing to the same one. So you can disable them by default, but I will immediately turn them back on for myself.

**Comment by vivid-synth** [comment]
Yep, error messages are very noisy, and in my experience perplexing to beginners. I'd support removing anything that's not useful to beginners (with the option to turn on more)

**Comment by jamshark70** [comment]
I guess the trick is to give users enough information to be useful, but not so much that it's overwhelming, but also just enough that clever users will start to ask questions about it when the time comes. That is, if too much is hidden, users never get a sense of the deeper world.

I understand the motivation here, but let's also not baby the users too much. My instinct is to be more permissive about the default info level than some of the responses here.

**Comment by joshpar** [comment]
I wonder if the answer is in formatting? Put common user stuff in an initial block, and more detailed info in a second block of text?
I agree with James - this is info that I think should be on by default.
Josh

**Comment by snappizz** [comment]
as a user i'm more than willing to be babied. these memory addresses are nothing but noise to me.

**Comment by jamshark70** [comment]
Hm, on a closer look, the memory addresses of DebugFrame objects are useless, indeed.

Sorry, I had gotten confused about which issue this was... the issue is specific, but my comment is general and doesn't really belong here.

**Comment by crucialfelix** [comment]
I would keep it on. It is essential to tell if an object is identical to another one in the stack trace. I think you will end up confusing people who spend hours thinking they are looking at the same objects.

But then I use atom-supercollider which is much less noisy and yet has more information in the stack trace. It has a much higher information to ink ratio.

**Comment by jamshark70** [comment]
@crucialfelix, I thought so at first too... but then I looked more carefully, and saw that the hex addresses are for the stack frame objects (or methods?) only. Why do you need the address of `Object:doesNotUnderstand`? There are no addresses for objects in method args or vars... which is where they would be useful.

The one and only hex address I see in Nathan's post that is useful is the one in the Server object dump. *That* one, I would keep. The others are useless.

**Comment by snappizz** [comment]
regarding the memory addresses that are useful, we should get cutesy and use the addr to seed a random two words like "telepathic llama", in such a way that it is unlikely for two different memory addresses to have the same representation. it's much easier to visually distinguish "happy manatee" and "spiritual monkey" than `0x2ef6bd8` and `0x2ef86e8`

**Comment by brianlheim** [comment]
Is there still a desire to make this an optional feature? Otherwise, I think this can be closed.

**Comment by snappizz** [comment]
yeah, let's close.
