### ISSUE TITLE
allowing Buffer to read and store format files other then Wav and Aif/Aiff

### ISSUE THREAD

**Issue by tiagmoraismorgado** [supercollider/supercollider#2928]
**Heyho**

Wouldn't it actually be nice if we could allow Buffer to read and store format files other then **Wav** and **Aif/AIff.** A possible mean to do so would be using some of the **ffmpeg** **source** (personal suggestion) - **though this is not a suggestion to strictly merge other technologies with supercollider, but rather using part of another app source, to extend supercollider functionality**.

<img src="https://lh5.googleusercontent.com/-LX53aOM1JLI/AAAAAAAAAAI/AAAAAAAAAGo/cBe-_Z4t4EI/photo.jpg" ></img> <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/d/df/FFmpeg.PC.png/300px-FFmpeg.PC.png"></img>

https://github.com/FFmpeg/FFmpeg

**Comment by joshpar** [comment]
libsndfile is responsible for R/W - it supports much more than WAV / AIFF: http://www.mega-nerd.com/libsndfile/ <http://www.mega-nerd.com/libsndfile/>

**Comment by tiagmoraismorgado** [comment]
libsndfile is just one of the components used by ffmpeg.

**Comment by brianlheim** [comment]
Closing since, as noted by Josh, libsndfile lets us read and store files other than .wav and .aiff, and so the original feature request is already met by current implementation.

**Comment by tiagmoraismorgado** [comment]
my apologies for my un-accuracy
