### ISSUE TITLE
excessive memory usage by sysex MIDIFunc with specified srcID

### ISSUE THREAD

**Issue by jmckernon** [supercollider/supercollider#2937]
When registering a sysex MIDIfunc and specifying a srcID, sclang's CPU activity spikes for a second and then consumes an unreasonable amount of RAM, on the order of hundreds of megabytes. In particular, the amount of memory used seems proportional to the size of the srcID interpreted as an integer. The same thing doesn't seem to happen on e.g. a noteOn MIDIFunc.

```
r = MIDIFunc.sysex(func: { "hello, world".postln }); // no noticable effect on memory usage
r = MIDIFunc.sysex(func: { "hello, world".postln }, srcID: 1); // no noticable effect on memory usage
r = MIDIFunc.sysex(func: { "hello, world".postln }, srcID: 1000000); // bumps memory usage to ~14% of 4GB
r = MIDIFunc.sysex(func: { "hello, world".postln }, srcID: 2000000); // bumps memory usage to ~25% of 4GB
r = MIDIFunc.sysex(func: { "hello, world".postln }, srcID: 3000000); // bumps memory usage to ~40% of 4GB
r = MIDIFunc.noteOn(func: { "hello, world".postln }, srcID: 3000000); // no noticable effect on memory usage
```

(I recompiled sclang and checked that the memory usage had gone back down to the normal level, about 3%, inbetween each of those measurements.)

I'm using 3.8.0 on Arch Linux (though the same thing seemed to be happening on a more recent git checkout).

**Comment by davedre** [comment]
I just ran into what I believe is the same bug on OSX 10.11.6 with SC 3.8.0, using MIDIdef instead of MIDIFunc.

Here is my code:
```
MIDIClient.init;
MIDIIn.connectAll;
MIDIdef.sysex(\testSysex, { | data, src | "got sysex".postln}, srcID: 102347329);
```

This results in a CPU spike, the interpreter freezing, then an OSX notification that the interpreter has crashed.

**Comment by brianlheim** [comment]
Looking at this code: 
https://github.com/supercollider/supercollider/blob/master/SCClassLibrary/Common/Control/ResponseDefs.sc#L623-L679

Led me to try this:
```supercollider
MIDIFunc.sysex(srcID: 1000000); // *** memory spike
MIDIFunc.noteOn(srcID: 1000000); // no noticable effect on memory usage
MIDIFunc.touch(srcID: 1000000); // no noticable effect on memory usage
MIDIFunc.smpte(srcID: 1000000); // *** memory spike
MIDIFunc.songPosition(srcID: 1000000); // no noticable effect on memory usage
MIDIFunc.sysrt(srcID: 1000000); // no noticable effect on memory usage
MIDIFunc.tick(srcID: 1000000); // no noticable effect on memory usage
```

So something is wrong with this code:

https://github.com/supercollider/supercollider/blob/d5a9550b7b14c051ecad17b024cecacae40f670d/SCClassLibrary/Common/Control/ResponseDefs.sc#L468-L486

and it's also inherited by this code:

https://github.com/supercollider/supercollider/blob/d5a9550b7b14c051ecad17b024cecacae40f670d/SCClassLibrary/Common/Control/ResponseDefs.sc#L559-L575

**Comment by jamshark70** [comment]
Nope, not there... but it is a useful clue, because there are a lot of dispatcher object in that section that have no problem, while only the sysex dispatcher has a problem.

`getKeysForFuncProxy` should always return a collection, because of where it's used:

https://github.com/supercollider/supercollider/blob/master/SCClassLibrary/Common/Control/ResponseDefs.sc#L131-L132

```
		keys = this.getKeysForFuncProxy(funcProxy);
		keys.do({|key| active[key] = active[key].addFunc(func) }); // support multiple keys
```

All of the other MIDI***Dispatcher classes do `asArray` in `getKeysForFuncProxy`... `MIDISysexDispatcher`, uniquely, does not:

```
	getKeysForFuncProxy {|funcProxy| ^(funcProxy.srcID ? \all)}
```

So, when the srcID is a very large integer, `keys` becomes a large integer, and then `keys.do` will add a new item into `active` that number of times.

Easy fix. I'll do a PR.

**Comment by brianlheim** [comment]
Glad to help :)
