### ISSUE TITLE
strings ending in $ (dollar) return nil and prevent evaluation of rest of code

### ISSUE THREAD

**Issue by jmckernon** [supercollider/supercollider#2941]
returns nil, nothing gets posted:
```
(
	"abc$";
	5.do { |i| i.postln };
	"hello, world".postln;
)
```
ditto:
```
(
	"$";
	5.do { |i| i.postln };
	"hello, world".postln;
)
```
works:
```
(
	"abc";
	5.do { |i| i.postln };
	"hello, world".postln;
)
```
works:
```
(
	"abc$d";
	5.do { |i| i.postln };
	"hello, world".postln;
)
```
This is in 3.8.0. I think (but can't check) it used to work in an earlier version, maybe 3.6.

**Comment by snappizz** [comment]
it works for me in scide on linux. what editor and OS?

**Comment by jmckernon** [comment]
Yeah, I just tried it directly in sclang at the command line and it works there, so I guess it's a bug in SCVIM. I guess that has a separate tracker?

**Comment by snappizz** [comment]
yep, [right here](https://github.com/supercollider/scvim).

**Comment by jmckernon** [comment]
Thanks. I'll close this.

**Comment by bagong** [comment]
I think it's fixed in scvim, you need to update to the latest version...

**Comment by jmckernon** [comment]
Ah, I'll check, thanks.
