### ISSUE TITLE
scdoc: rewrite SCDocHTMLRenderer

### ISSUE THREAD

**Issue by brianlheim** [supercollider/supercollider#2946]
## Problem

The current HTML renderer is slow, written in sclang, and open to vulnerabilities.

## Solution

We should rewrite it in a template language.

@snappizz said on #2944:

> constructing html strings by hand this way is a complete freakin drag (to say nothing of xss vulnerabilities) and we should be using a proper template language

Maybe you can clarify which language to use, and how easy that would be to integrate with the existing repo. I have always kind of shaken my head at `SCDocHTMLRenderer` so I would be all for this.

**Comment by snappizz** [comment]
at #2897 we discussed overhauling scdoc completely. we could lump this in with that proposal.

i like jinja2, but it's python-based, so idk

**Comment by brianlheim** [comment]
Sure! this is vague enough that i'd consider it a dupe of #2897 (which is also quite vague)
