### ISSUE TITLE
Implement methods to classify sclang method names

### ISSUE THREAD

**Issue by snappizz** [supercollider/supercollider#2952]
## Problem

in #2948 i found a need to query whether a method name can be written using the standard method call syntax, or whether it's a valid binary operator. this functionality is probably useful enough to belong in the core class library, no?

## Solution

i'd like to propose the methods `Symbol:isIdentifier`, and `Symbol:isBinaryOperator`.

`Symbol:isIdentifier` checks whether symbol *foo* can be written in a syntactically valid way as `bar.foo()`, which i believe is equivalent to asking whether it is a valid variable name. as far as i can tell, the precise algorithm is that *foo* must start with a lowercase letter, and all other characters are alphanumeric or underscores.

`Symbol:isBinaryOperator` checks whether the symbol is a valid binary operator. in other words, the symbol must consist only of the characters `!@%&*-+=|<>?/`, must not be the string `=`, and must not start with `/*` or `//`. (`-/*-` parses as a single binary operator... what the hell?) let's set the class variable `Char.binaryOperatorCharacters` to the string `"!@%&*-+=|<>?/"`.

**Comment by brianlheim** [comment]
++

Once `isBinaryOperator` is written we should deprecate `isBasicOperator` (https://github.com/supercollider/supercollider/blob/master/SCClassLibrary/JITLib/ProxySpace/extStoreOn.sc#L10-L12).

I would prefer the abbreviated terminology `BinaryOp`, which is used frequently throughout the class library.

> -/*- parses as a single binary operator

Do we consider this a lexing error? I certainly would.

> that we set the class variable Char.binaryOperatorCharacters to the string "!@%&*-+=|<>?/".

++

**Comment by snappizz** [comment]
> I would prefer the abbreviated terminology BinaryOp, which is used frequently throughout the class library.

ah man. i prefer unabbreviated names for things, but i guess consistency wins.

> Do we consider this a lexing error? I certainly would.

yeah me too

**Comment by brianlheim** [comment]
Thinking about #2954... shouldn't these also have `name` at the end of the method name? (`isIdentifierName`?) Without it, someone could easily make the assumption that this asks whether it's a defined identifier name, not a possible one. Same (even moreso I'd say) with `isBinaryOp`.

**Comment by telephon** [comment]
Please feel free to change the JITLib method name!

**Comment by snappizz** [comment]
i disagree with `isIdentifierName` since an identifier IS a name. i think `isBinaryOp` is probably okay, any ambiguity is cleared up by docs.

**Comment by brianlheim** [comment]
> i disagree with isIdentifierName since an identifier IS a name.

Good point

> i think isBinaryOp is probably okay, any ambiguity is cleared up by docs.

I thought through this again and it makes more sense to me now. The orthogonality I was imagining between this and `isPrimitiveName` / `isPrimitive` can't exist.

**Comment by brianlheim** [comment]
Closed by #2955.
