### ISSUE TITLE
\.isPrimitiveName is true

### ISSUE THREAD

**Issue by nhthn** [supercollider/supercollider#2954]
## Problem

`Symbol:isPrimitiveName` is supposed to test for a string that begins with `_`, but it returns true for an empty symbol.

## Solution

`Symbol:isPrimitiveName` calls the undocumented primitive method `Symbol:isPrefix`, which appears to be the source of this bug. it's found in `prSymbolIsPrefix` in `PyrSymbolPrim.cpp`. it compares the strings to see if theyre equal up to the minimum of their two lengths, so it can return a false positive if the receiver is shorter than the argument.

also, whoever's fixing this should take the opportunity to document `Symbol:isPrefix`.

**Comment by brianlheim** [comment]
source: https://github.com/supercollider/supercollider/blob/b542c0037761b4c9cc7ba6af8c27c35003a5a84e/lang/LangPrimSource/PyrSymbolPrim.cpp#L49-L67

**Comment by brianlheim** [comment]
> for a string that ends in _

I think you mean that begins in _?

So the solution is
```supercollider
		^this.isPrefix(\_) and { this.size > 0 }
```

**Comment by brianlheim** [comment]
Updated that last comment. `_` by itself is not a valid primitive name, but `_x` (or `__`) is!

**Comment by dyfer** [comment]
I think #5708 fixes this.
