### ISSUE TITLE
[various/improvements] - documentation, bugs, etc

### ISSUE THREAD

**Issue by tiagmoraismorgado** [supercollider/supercollider#2957]
hi everyone

on my standing point, it is important to:

- include extensive tutorials on live electronic instrument design, as that seems to be a major topic on super collider usage (among other things, such as algorithmic composition, or even specific topics, such as algorave coding, as there starts to be a significant users community on that regard, and that might perfectly be a way of attracting users from dance music scenes into supercollider, that wouldn't use supercollider otherewise, and then may turn into getting into electroacoustic music composition, and other kinds of things);
- documentaton and overall css should take advantage of modern responsive frameworks. on my standing point a good way to accomplish that, would be grabbing some opensource web templates, and just grab their css, tweak it and add it to the supercollider help		
- sometimes when you send messages to the server at an high speed, you may encounter syncing issues, among other things, such as interpreting errors, or even server crash; that may become particularly problematic when dealing with jitlib (i am a jitlib user myself);

**Comment by snappizz** [comment]
> include extensive tutorials on live electronic instrument design, as that seems to be a major topic on super collider usage

live electronic rig design is highly personalized and artistic, definitely out of scope for our docs.

> documentaton and overall css should take advantage of modern responsive frameworks.

i don't think we need to adopt anything asap, but we could offer better mobile support. to me there are much more important design issues in the docs though.

> sometimes when you send messages to the server at an high speed, you may encounter syncing issues, among other things, such as interpreting errors, or even server crash

can you provide a minimal example that reproduces this?

**Comment by brianlheim** [comment]
Hi @tiagmoraismorgado ,

Please open separate tickets for separate issues, rather than grouping them in the same ticket when they are unrelated. Also, as nathan suggested above, without a way to reproduce an error or bug we have no way of knowing how to fix it, or whether it is already in another existing ticket. Thanks.

**Comment by jamshark70** [comment]
> live electronic rig design is highly personalized and artistic, definitely out of scope for our docs.

Though the issue has been closed, something that is not out of scope for docs and that's lacking is "how-to" material for common topics, such as:

- How to get data from a GUI or the server into a pattern

- How to manage a larger GUI (possibly including a bit of MVC, which... well, so many times when I think, "oh, mvc is overkill for this," I end up rewriting it with mvc

**Comment by jamshark70** [comment]
... dangit, wrong button on the phone. Closing. I'll finish that comment shortly by editing.
