### ISSUE TITLE
Spectogram and Qt

### ISSUE THREAD

**Issue by jleben** [supercollider/supercollider#296]
[Issue migrated from SourceForge | ID: 3383701 | Submitted by 'nobody']
[http://sourceforge.net/support/tracker.php?aid=3383701]

Spectogram appears not to be compatible with the Qt Gui. 

a = Spectrogram.new;
a.start;

this works with SwngOsc - but is broken with Qt.. the error I get is: 

ERROR: Message 'image' not understood.
RECEIVER:
class QtGUI (0x11b936640) {
  instance variables [19]
    name : Symbol 'QtGUI'
    nextclass : instance of Meta_QuadC (0x11844e340, size=19, set=5)
    superclass : Symbol 'Object'
    subclasses : nil
    methods : nil
    instVarNames : nil
    classVarNames : nil
    iprototype : nil
    cprototype : nil
    constNames : nil
    constValues : nil
    instanceFormat : Integer 0
    instanceFlags : Integer 0
    classIndex : Integer 466
    classFlags : Integer 0
    maxSubclassIndex : Integer 466
    filenameSymbol : Symbol '/Users/marinosk/.sclang/SCClassLibrary/QtCollider/QtGUI.sc'
    charPos : Integer 0
    classVarIndex : Integer 588
}
ARGS:
CALL STACK:
DoesNotUnderstandError:reportError   0x11cb35378
arg this = <instance of DoesNotUnderstandError>
Nil:handleError   0x12148bcb8
arg this = nil
arg error = <instance of DoesNotUnderstandError>
Thread:handleError   0x121be5988
arg this = <instance of Thread>
arg error = <instance of DoesNotUnderstandError>
Object:throw   0x11736b168
arg this = <instance of DoesNotUnderstandError>
Object:doesNotUnderstand   0x117604828
arg this = <instance of Meta_QtGUI>
arg selector = 'image'
arg args = [*0]
Meta_ViewRedirect:doesNotUnderstand   0x121ca70d8
arg this = <instance of Meta_Image>
arg selector = 'color'
arg args = [*3]
var impl = nil
Spectrogram:prCreateImage   0x121183138
arg this = <instance of Spectrogram>
arg width = 600
Spectrogram:setWindowImage   0x117581ba8
arg this = <instance of Spectrogram>
arg width = 600
Spectrogram:createWindow   0x121cb61e8
arg this = <instance of Spectrogram>
arg parent = nil
arg boundsarg = nil
var bounds = <instance of Rect>
Spectrogram:initSpectrogram   0x117648998
arg this = <instance of Spectrogram>
arg parent = nil
arg boundsarg = nil
arg bufSizearg = nil
arg col = nil
arg bg = nil
arg lowfreqarg = 0
arg highfreqarg = inf
< closed FunctionDef >  (no arguments or variables)
Interpreter:interpretPrintCmdLine   0x11ff5c6d8
arg this = <instance of Interpreter>
var res = nil
var func = <instance of Function>
var code = "a = Spectrogram.new;"
var doc = <instance of ScelDocument>
Process:interpretPrintCmdLine   0x11e4a0ef8
arg this = <instance of Main>
For advice: [http://supercollider.sf.net/wiki/index.php/ERROR:_Message_'image'_not_understood.]

**Comment by snappizz** [comment]
Closed because the issue proper is invalid. Image is now supported in Qt, so this is up to the developer of Spectrogram.

**Comment by machty** [comment]
@jleben did you ever find a solution? Seems no one's touched or really talks about Spectrogram at all, but I'd definitely be interested in getting something working (or do you know of any alternatives?)

**Comment by jleben** [comment]
@machty I thought this issue was resolved, according to comment by @snappizz. No?

**Comment by machty** [comment]
@jleben he was saying that it was up to Spectogram devs to fix their plugin code, and fortunately that has since happened here: https://github.com/supercollider-quarks/Spectrogram/issues/2
