### ISSUE TITLE
help doc: drop down text is out of scale

### ISSUE THREAD

**Issue by telephon** [supercollider/supercollider#2968]
the drop down views in the help doc look funny:

<img width="679" alt="screen shot 2017-06-19 at 10 20 02" src="https://user-images.githubusercontent.com/1810559/27275774-3cbb0d20-54d9-11e7-8d2c-f451e9ac8ef6.png">

less bad with normal font, but still:

<img width="459" alt="screen shot 2017-06-19 at 10 22 53" src="https://user-images.githubusercontent.com/1810559/27275795-550a260e-54d9-11e7-9ad2-9e06108ba40a.png">

not a big issue, but as we are at it...

**Comment by kisielk** [comment]
Is this still relevant? Maybe it was fixed by the help redesign? Mine looks like this:
<img width="301" alt="screen shot 2017-07-17 at 22 38 40" src="https://user-images.githubusercontent.com/58618/28302193-bebdd0fa-6b40-11e7-9b42-a75296b95e30.png">
