### ISSUE TITLE
including examples on live electronic instrument design in the supercollider examples

### ISSUE THREAD

**Issue by tiagmoraismorgado** [supercollider/supercollider#2972]
hello guys. it would be nice to:
- include examples of supercollider tutorials on live electronic instrument design, as it is one of the main usages supercollider usually gets, and there's not so much extensive examples in the supercollider documentation. sensestage (marije baalman - steim), may perfectly be a nice way of approaching this issue

**Comment by jamshark70** [comment]
I agree with Nathan's comment from the other issue that the SC docs are not responsible for topics of instrument *design*. He is correct when he says instrument design is highly personal and SC docs should not appear to prescribe a "right" way.

But I also agree with you that the docs currently don't say much about common implementation problems for live instruments. Those topics are totally fair game.

Also: In general, in SC's main documentation, we avoid dependencies on extension libraries. SenseStage would not be ok for the kind of tutorial you propose. It would be ok for an external tutorial.

**Comment by tiagmoraismorgado** [comment]
we could add it to the folders of examples, i think that sounds perfectly reasonable

**Comment by vivid-synth** [comment]
Can I suggest linking to these resources from a blog instead of the main SC repo?

**Comment by LFSaw** [comment]
I agree with @vivid-synth here. plenty of information is freely available on the web and only a google search away.

**Comment by jamshark70** [comment]
> plenty of information is freely available on the web and only a google search away.

But not so much about "common implementation problems for live instruments."

**Comment by LFSaw** [comment]
IMHO this is more like a book to be written (anyone?) rather than a topic for the helpfile system in SC.

related (and shameless plug):
	https://3dminalmanac.wordpress.com/
