### ISSUE TITLE
bug - high speed osc messages in jilib may cause server to crash

### ISSUE THREAD

**Issue by tiagmoraismorgado** [supercollider/supercollider#2973]
sometimes when you send messages to the server at an high speed, you may encounter syncing issues, among other things, such as interpreting errors, or even server crash; that may become particularly problematic when dealing with jitlib (i am a jitlib user myself);

that happens mostly if you trigger instantiations of synths via jitlib. i recommed you to inspect this issue, and try to come up with a mean of fixing it.

looking forward
kind regards
T.

**Comment by joshpar** [comment]
messaging is tied to network performance. can you post a piece of sample code please?

**Comment by tiagmoraismorgado** [comment]
i don't have nothing here with me that i can share. but i can point out that if you try to:
- create synth definitions with jitlib;
- making midi mappings to midi or osc;
- trigger controller to the synth parameters at an high rate;
- in the midst of the process you try to stop and start new synths
supercollider may crash. that is something i encountered myself several times, and i know people who had the same problem. that particularly became an issue when working with ~xxx and NDefs, an you either try to map new pre-stored synths into the ndefs, or load new simple synthesis definitions via osc

**Comment by brianlheim** [comment]
@tiagmoraismorgado Please post reproducing code. We can't do anything to diagnose or solve an issue if there's no reliable way to reproduce it.

**Comment by joshpar** [comment]
what is a high rate? 10 per second? 1000?
That is a lot of code you are asking someone here to write to debug this problem. Please try to post SOMETHING that we can reproduce with. This is a common step in open-source bug reporting. Thanks.

**Comment by tiagmoraismorgado** [comment]
ok, i will do that in the upcoming days

**Comment by tiagmoraismorgado** [comment]
thanks for the insight

**Comment by tiagmoraismorgado** [comment]
i recorded this video https://vimeo.com/222422338 here you get messages quite often with the content:
- FAILURE IN SERVER /n_free Node 1040 not found
this is exactly one of the bugs that i got when the problem happened except that:
- i got a more complex error with some memory addresses, etc.;
- i was using external MIDI/OSC controllers, to send data;
- i was sending the synth definitions with the message, alongside with synth parameters;
- i was mapping those to an NDef on the fly

but you get the idea, this is sort of the same error structure i was getting before, except that in some cases server would crash, thanks to the high volume of data + sending synthdefinition via osc to map to an ndef

**Comment by telephon** [comment]
yes, of course, you shouldn't be redefining proxies at such a high rate.

There is a helpfile here, that explains it: http://doc.sccode.org/Tutorials/JITLib/jitlib_efficiency.html
