### ISSUE TITLE
Proper documentation of PV_Copy

### ISSUE THREAD

**Issue by spluta** [supercollider/supercollider#2995]
The documentation on how to or how not to use PV_Copy is not clear at all. All of the documentation shows how to use PV_Copy, but the help file for PV_Copy says not to use it. It would be great if the correct syntax for creating multiple streams of processing from one FFT were shown somewhere in the doc.

**Comment by LFSaw** [comment]
@spluta , would you mind to write up a proposal for a better `PV_Copy` helpfile, either here or as a PR? It seems to me that you have a decent understanding about it. :)

**Comment by spluta** [comment]
Hah.  I mostly thought I sounded like an idiot in the conversation about it. But I’m glad to do it!

Sam

**Comment by spluta** [comment]
committed pull request #3162. hopefully this correctly resolves the issue

**Comment by JordanHendersonMusic** [comment]
Closed by #3162
