### ISSUE TITLE
function plot starts server, but doesn't do anything

### ISSUE THREAD

**Issue by telephon** [supercollider/supercollider#2996]
reproducer:

```

s.quit;

{ SinOsc.ar }.plot
```

server is running, plot window stays empty.

**Comment by telephon** [comment]
I have a fix here, I can make a PR on demand: https://github.com/telephon/supercollider/tree/topic-refactor-function-buffer

**Comment by brianlheim** [comment]
thanks again for the PR @telephon . this has bugged me for some time.
