### ISSUE TITLE
/b_gen plugins for wavetable format conversion

### ISSUE THREAD

**Issue by jleben** [supercollider/supercollider#301]
[Issue migrated from SourceForge | ID: 3424022 | Submitted by 'jamshark70']
[http://sourceforge.net/support/tracker.php?aid=3424022]

At Fri, 14 Oct 2011 15:09:42 +0200,
nonprivate wrote:

> hi all,
> i love waveshaping but have always found it a bit of a pain due to having to mess with wavetables.

I have _no_ time to work on it now, but I'd love to see a b_gen plug-in to convert a buffer into wavetable format. Actually, maybe two plug-ins:
- Convert in-place: you would allocate a buffer with twice the number of input samples, load the data into the first half of the buffer, and then convert.
- Put the wavetable data into a different buffer: like "/b_gen, copy" but including wavetable calculations.

That would save the trouble of bringing the data into the language for asWavetable and sending back to the server.

"Feature request" in 3... 2... 1...
hjh

**Comment by xavriley** [comment]
:+1:
