### ISSUE TITLE
auto-indent should be optional

### ISSUE THREAD

**Issue by snappizz** [supercollider/supercollider#3010]
report via Rhian Lloyd on Facebook:

> make an option to turn th fcking indent/whatever thing OFF ..
> Having to run old ver purely to edit stuff, it's mental, i mean how hard can it be just to have an option to turn that enforced formatting off.

**Comment by alln4tural** [comment]
I don't think that qualifies as a report.

-- 
https://soundcloud.com/all-n4tural

**Comment by bagong** [comment]
It's pretty clear though ;) And not the first time this was asked for...

**Comment by telephon** [comment]
I agree that auto-indent should be an option, and be applicable to selections only.

related: #530, #552, #1240.
There is also some discussion here: #596.

**Comment by brianlheim** [comment]
dupe of #552.
