### ISSUE TITLE
UnitTesting quark helpfile still advertises installing (deprecated) CommonTests quark

### ISSUE THREAD

**Issue by LFSaw** [supercollider/supercollider#3016]
I guess that when deprecating [CommonTests](https://github.com/supercollider-quarks/CommonTests), its mentioning in the `UnitTest` helpfile at [UnitTesting](https://github.com/supercollider-quarks/UnitTesting) was forgotten... 
I can fix this myself but I'd need some information about the current state of the art for UnitTesting then... my current "workflow" for Core library functions is (as done for #2802), to

  + install the `UnitTesting` quark
  + manually add the folder `supercollider/testsuite/classlibrary` to my `config.yaml` file. 

The latter seems a little weird... and is AFAICS not documented... I guess I am doing something wrong.

Also, is there a guideline on how to manage tests written for quarks? This is interesting e.g. for the [Modality-Toolkit](https://github.com/ModalityTeam/Modality-toolkit/)...

**Comment by telephon** [comment]
I think it is also a problem that the `supercollider/testsuite` doesn't work without the `UnitTesting` Quark installed. Maybe the Quark should be moved there? OTOH, other test authors may depend on it.

**Comment by LFSaw** [comment]
https://github.com/supercollider-quarks/UnitTesting now tells about its deprecation
