### ISSUE TITLE
SCDoc: lists of inherited methods should be alphabetized

### ISSUE THREAD

**Issue by brianlheim** [supercollider/supercollider#3018]
## Current behavior

<img width="310" alt="image" src="https://user-images.githubusercontent.com/15369640/27912608-86e8ec82-622b-11e7-88c5-1fe3c20c7876.png">

## Expected behavior

(same, but alphabetized)

## Purpose/motivation

Since these lists are usually small and lack structure (no subheadings), it is much easier to find what you want if it's sorted alphabetically.

**Comment by kisielk** [comment]
It looks like they are already sorted, but there's two different lists: undocumented methods and documented methods (in the example, `gui` and `hasGlobalDictionary` are undocumented)

**Comment by brianlheim** [comment]
Dupe of #2052
