### ISSUE TITLE
"WARNING: Called from Meta_OSCpathResponder:new, method Meta_OSCresponder:new is deprecated" messages everywhere

### ISSUE THREAD

**Issue by kisielk** [supercollider/supercollider#3038]
I just built Supercollider from the latest master revision (8324bf51661b2b1dd2a224e1684e77778d3c06d2)

As soon as I boot the server and start running any code my console is constantly spammed with messages like the following:

```
WARNING: Called from Meta_OSCpathResponder:new, method Meta_OSCresponder:new is deprecated and will be removed. Use Meta_OSCFunc:new instead.
```

I'm not using any OSC functions anywhere, though I am using JITLib (maybe that uses OSC somewhere under the hood?).

Is there some way I can turn off these messages?

**Comment by jamshark70** [comment]
In current master, the OSCresponder classes are no longer used. I confirmed by searching here on github.

The most likely explanation is that you have an extension somewhere, or user code (maybe in your startup file), that tries to create a responder. You'll have to find it and replace it.

Also note, it looks like that code is repeatedly creating a responder, which is normally not needed.

**Comment by kisielk** [comment]
I don't have anything in my startup file, but I do see it mentioned in the `JITLibExtensions` quark which I have installed.

I noticed in `SCClassLibrary/DefaultLibrary/Main.sc` there's a call to `OSCresponder.respond`. When I comment that out all the warnings go away, though I assume that makes any code relying on `OSCresponder` not work any more. 

That being said, I'm not sure how useful this deprecation warning is if it's reported for things inside of installed quarks, when it doesn't provide any context such as a line number of file where it was generated. How is a user supposed to track down the source of the warning and then silence it? In my case it makes the Post Window in the IDE completely unusable since it's constantly scrolling warnings along.

**Comment by jamshark70** [comment]
> I don't have anything in my startup file, but I do see it mentioned in the JITLibExtensions quark which I have installed.

I took a quick look at the instances in JITLibExtensions. It isn't obvious which of them would be called repeatedly. Are you sure you don't have any other quarks that might have it?

I'll be glad to log an issue with JITLibExtensions if we're sure that's where it's happening.

> I noticed in SCClassLibrary/DefaultLibrary/Main.sc there's a call to OSCresponder.respond.

Irrelevant. The deprecated call is OSCresponder.new, not .respond. *But*, because it's deprecated, you could go ahead and comment that out for the time being. The main class library will be unaffected.

> That being said, I'm not sure how useful this deprecation warning is if it's reported for things inside of installed quarks, when it doesn't provide any context such as a line number of file where it was generated.

Line numbers are not available to errors or warnings. There's an issue logged for that, but it's a deep architectural change.

> In my case it makes the Post Window in the IDE completely unusable since it's constantly scrolling warnings along.

It is extremely atypical use for OSC responders to be created repeatedly. Normal use is to create one responder to listen to many incoming messages in sequence. Nobody expected this.

**Comment by kisielk** [comment]
I'm not really sure how commenting out that code in `Main.sc` helped fix the warnings in that case...

I've narrowed down the warning to the `ProxyMeter` class from `JITLibExtensions`. The following code (specifically the `addMixer` method):

```
m = ProxyMixer(p);
ProxyMeter.addMixer(m);
```

results in a forever repeating sequence of these warnings:

```
WARNING: Called from OSCpathDispatcher:value, method Meta_OSCpathResponder:new is deprecated and will be removed. Use Meta_OSCFunc:new instead.


WARNING: Called from Meta_OSCpathResponder:new, method Meta_OSCresponder:new is deprecated and will be removed. Use Meta_OSCFunc:new instead.


WARNING: Called from OSCpathDispatcher:value, method Meta_OSCpathResponder:new is deprecated and will be removed. Use Meta_OSCFunc:new instead.


WARNING: Called from Meta_OSCpathResponder:new, method Meta_OSCresponder:new is deprecated and will be removed. Use Meta_OSCFunc:new instead.
```

**Comment by telephon** [comment]
can you try again after:

`Quarks.update("JITLibExtensions")`

I hope I've fixed it.

**Comment by kisielk** [comment]
No more warnings, but the meter doesn't seem to work any more, I just see the standard ProxyMixer

**Comment by telephon** [comment]
ah good ;)

Actually, the meter never worked for me. I'll check again.

**Comment by telephon** [comment]
ok, once more - sorry!

**Comment by jamshark70** [comment]
> I'm not really sure how commenting out that code in Main.sc helped fix the warnings in that case...

I guess the warnings were coming from an OSCresponder that was created in an OSC response function... by stopping the responses from firing, you stop the warnings.

But Julian has got the better idea: fix the culprit.

**Comment by kisielk** [comment]
That seems to have done it, thanks :)
