### ISSUE TITLE
Implement ServerOptions.devices on Windows & Linux

### ISSUE THREAD

**Issue by jleben** [supercollider/supercollider#305]
[Issue migrated from SourceForge | ID: 3518672 | Submitted by 'None']
[http://sourceforge.net/support/tracker.php?aid=3518672]

Running 
ServerOptions.devices;
and
s.options.devices;
return :
ERROR: A primitive was not bound. 0 624

On Windows (and I was told)  Linux whereas it works on OSX.

It could be nice if it would be cross platform.

Thanks!

**Comment by sensestage** [comment]
related to #1557

**Comment by telephon** [comment]
I get a 404 error on the sourceforge link.

**Comment by snappizz** [comment]
Any updates on this, please?

**Comment by jamshark70** [comment]
Just a comment about Linux: s.options.device, if specified, is the name of a running Jack server instance and not the name of a hardware device.

Currently there's some work being done to support PortAudio as a server backend in Linux, bypassing Jack. It's unclear, then, what devices should return, as it would need to know which backend you plan to use, to know which device names would be meaningful.

(Copied from #1949 - this is a better place for the remark.)

**Comment by vivid-synth** [comment]
Closing in favor of #1557
