### ISSUE TITLE
Duty init bug

### ISSUE THREAD

**Issue by dkmayer** [supercollider/supercollider#3062]
Duty swallows first values with very short duty durations, e.g.

```supercollider
x = 1 / s.sampleRate;
{ Duty.ar(x, 0, Dser([1, 0.5], 5), 2) }.plot(x * 10, minval: 0, maxval: 1); 
```

Behaviour after demand ugen end is inconsistent also, see this thread for a comparison

http://new-supercollider-mailing-lists-forums-use-these.2681727.n2.nabble.com/Strange-Duty-init-behaviour-bug-td7633651.html

**Comment by telephon** [comment]
a clearer display:

```supercollider
x = 4 / s.sampleRate;
{ Duty.ar(x, [0, 1], Dser([1, 0.5], 5), 2) }.plot(x * 10, minval: -1.4, maxval: 1.4).plotMode_(\points); 
```

**Comment by telephon** [comment]
When I originally wrote the Duty ugens, I didn't take care enough about the first frames that come out. I'll do some systematic tests and work out solutions, may tale a while.

**Comment by telephon** [comment]
https://github.com/telephon/supercollider/tree/topic-duty-fixes

**Comment by dkmayer** [comment]
Thanks for your diving into this -
in my first tests the ar examples work fine !

**Comment by telephon** [comment]
Very good. Let's have someone else take a peek at it.

**Comment by brianlheim** [comment]
Closed in #3073.

**Comment by dkmayer** [comment]
Julian, thanks for this fix !
Just one question: is the kr case still open ?

**Comment by telephon** [comment]
I just tested, the kr case seems to work fine:

```supercollider
x = 400 / s.sampleRate;
{ Duty.kr(x, 0, Dser([1, 0.5], 5), 2) }.plot(x * 10, minval: -1.4, maxval: 1.4);
```

**Comment by dkmayer** [comment]
Sorry, this example doesn't work here (on my dutyfix-branch build from 2.8.), the last plateau is too long.

The kr examples which I posted on the mailing list work neither:

http://new-supercollider-mailing-lists-forums-use-these.2681727.n2.nabble.com/Strange-Duty-init-behaviour-bug-td7633651.html

And now I checked additional ar examples and they also don't work here.

x = 0.001;
{ Duty.ar(x, 0, Dser([1, 0.5], 5), 2) }.plot(x * 10, minval: -1.4, maxval: 1.4);

Is my build too old ?

**Comment by telephon** [comment]
I see. Yes, same here: the last plateau is the time until the done action is called and the synth is freed. It is the block size.

```supercollider
(
var x = 0.001;
{ 
	
	var a = Duty.ar(x, 0, Dser([1, 0.5], 5), 2);
	var b = Trig1.ar(Impulse.ar(ControlRate.ir), ControlDur.ir / 8);
	[a, b]
}.plot(x * 8, minval: -1.4, maxval: 1.4);
)


(
var x = 0.0039;
{
	
	var a = Duty.ar(x, 0, Dser([1, 0.5], 5), 2);
	var b = Trig1.ar(Impulse.ar(ControlRate.ir), ControlDur.ir / 8);
	[a, b]
}.plot(x * 8, minval: -1.4, maxval: 1.4);
)

```

**Comment by telephon** [comment]
<img width="512" alt="image" src="https://user-images.githubusercontent.com/1810559/30531619-cb72f074-9c4f-11e7-875f-52915444ee77.png">

**Comment by dkmayer** [comment]
So you mean this is inevitable or a different bug ?
If so it should maybe go to a new issue thread.

Even if I take blocksize as length I got unexpected behaviour.

y = s.options.blockSize / s.sampleRate;

{ Duty.kr(y, 0, Dser([1, 0.5], 5), 2) }.plot(y * 10, minval: 0, maxval: 1);
{ Duty.kr(y, 0, Dser([0.5, 1], 5), 2) }.plot(y * 10, minval: 0, maxval: 1);

But I have no access to the new builds ATM.

**Comment by telephon** [comment]
uuh - yes. That looks bad. #3194.
