### ISSUE TITLE
link to plugin definition / c_next in UGen helpfiles?

### ISSUE THREAD

**Issue by LFSaw** [supercollider/supercollider#3067]
is it at all possible to dynamically extract the c_next source code or, alternatively, have a link to the C sources for UGen definitions in the helpfile system?

I am asking because I notice that plenty UGen help files are very scarce in their information regarding the actual implementation and sometimes it is very easy to express in source code rather than describing it with words.

Examples are:

+ LinCongN -- "The output signal is automatically scaled to a range of [-1, 1]." << what does automatically mean?
+ Hasher -- "Scrambled value with a hash function." << which hash function?
+ [this conversation](https://www.listarc.bham.ac.uk/lists/sc-users/msg56560.html) on the sc-users mainlinglist

However, I think it'd be great for many more implementations and also for interested people to see how straight forward many implementations actually are.

**Comment by timblechmann** [comment]
lots of ugens do not only have one ugen function, but several and the function may even change during operation (e.g. when delay lines wrap around)

**Comment by LFSaw** [comment]
thanks for your contribution, tim; anyone has constructive critique?

**Comment by LFSaw** [comment]
In the light of tims comment, maybe it is really "just" a link to the plugin's source file(s) (if they are installed). It'd give at least a starting point.

**Comment by kisielk** [comment]
A binary distribution won't include the source files, so I'm not sure this would be helpful in most cases. Maybe the link could be to github, including the specific revision from which the binary was built?

**Comment by timblechmann** [comment]
@LFSaw always great to hear how contributions are appreciated

**Comment by telephon** [comment]
@LFSaw - isn't @timblechmann right that it isn't easily linked? 

Well, on the other hand, for each UGen there is one single constructor, which could be found and linked at least. Would that help in your opinion?

**Comment by LFSaw** [comment]
> @LFSaw always great to hear how contributions are appreciated

thanks
