### ISSUE TITLE
HelpFile browser empty/not responding when testsuite/classlibrary included

### ISSUE THREAD

**Issue by LFSaw** [supercollider/supercollider#3076]
in current HEAD ( ad78bc5 ), when adding UnitTest classes to the interpreter (via sclang_conf.yaml), the HelpFile Browser is stuck after startup and does not show any helpfiles.

Reproducer:
1. `"UnitTest".include;`
2. recompile
3. add "$SC_PATH/testsuite/classlibrary" to your sclang_conf.yaml
4. close and reopen SCIDE (recompile/reboot the interpreter does not show the result) 

Everything else (apart from getting help) works as expected.

**Comment by muellmusik** [comment]
I can't reproduce this in 3.10. @LFSaw can you confirm?

**Comment by friendlyOrganisms** [comment]
currently not able to do this... deadlines...

**Comment by LFSaw** [comment]
currently not able to do this... deadlines...
