### ISSUE TITLE
OSCresponder removal oversight?

### ISSUE THREAD

**Issue by obneq** [supercollider/supercollider#3081]
There is a remaining OSCresponder in SCClassLibrary/DefaultLibrary/Main.sc. It looks like it was forgotten in issue #2721. 
There is a big comment in OSCresponder.sc: 
```javascript
//////////////////////////////////////////////////////////////////////////////
//  _____________________________________
// / HEY YOU! When you're removing this  \
// | class, also make sure to remove the |
// | "OSCresponder.respond" line from    |
// \ Main:recvOSCmessage. Thanks!        /
//  -------------------------------------
// \                             .       .
//  \                           / `.   .' "
//   \                  .---.  <    > <    >  .---.
//    \                 |    \  \ - ~ ~ - /  /    |
//          _____          ..-~             ~-..-~
//         |     |   \~~~\.'                    `./~~~/
//        ---------   \__/                        \__/
//       .'  O    \     /               /       \  "
//      (_____,    `._.'               |         }  \/~~~/
//       `----.          /       }     |        /    \__/
//             `-.      |       /      |       /      `. ,~~|
//                 ~-.__|      /_ - ~ ^|      /- _      `..-'
//                      |     /        |     /     ~-.     `-. _  _  _
//                      |_____|        |_____|         ~ - . _ _ _ _ _>
//
//////////////////////////////////////////////////////////////////////////////
```

This prevents LNX_Studio from working, Deleting the line as indicated by the dinosaur solves this issue.

**Comment by telephon** [comment]
Hm, `OSCresponder` is deprecated, but not yet gone. It is so widely used that we need to keep it around a little longer. Also  #2721 only concerns the usage of the class, not this one place where it is called.

What kind of error are you getting?

**Comment by obneq** [comment]
it looks like i get an error like this for every message, dozens per second:

	Main:recvOSCmessage
		arg this = <instance of Main>
		arg time = 7.441432688
		arg replyAddr = <instance of NetAddr>
		arg recvPort = 57121
		arg msg = [*2]
Execution warning: Class 'OSCresponder' not found
ERROR: Message 'respond' not understood.

**Comment by telephon** [comment]
you're welcome - thanks for reporting!
