### ISSUE TITLE
Date improvements: create valid Date without filling all arguments; add ability to compare

### ISSUE THREAD

**Issue by totalgee** [supercollider/supercollider#3087]
Hi there, I wanted to create a Date object (based on data I read from a file, e.g. a date string in the form "YYYY-MM-DD HH:MM:SS", or one produced using `Date.stamp` in the form "YYMMDD_HHMMSS").  The Date.new method requires you to fill in *all* the arguments, including `dayOfWeek` and `rawSeconds`; otherwise they're nil and this doesn't make most of the other methods very happy.  If you don't do provide everything, it seems you don't have a valid Date object, e.g. you can't print it out (though some methods may work, e.g. `Date(2017, 6, 23).dayStamp` works), and you certainly can't query rawSeconds or compare two Date objects in time.  You could provide arbitrary/bogus values for dayOfWeek and rawSeconds, but it would be nice if they were "correct" (i.e. they can be computed from the other info, so why should I have to?).

So, it would be very nice to be able to specify a Date like this:

```
d = Date(2016, 6, 20); // default 00:00:00 as time, would calculate dayOfWeek and rawSeconds for you
e = Date(2017, 3, 31, 14, 22, 55); // calculates dayOfWeek and rawSeconds for you
```

What we get now is:

> ERROR: Primitive '_AscTime' failed.
Wrong type.
RECEIVER:
Instance of Date {    (0x11f6b5998, gc=54, fmt=00, flg=00, set=03)
  instance variables [8]
    year : Integer 2017
    month : Integer 3
    day : Integer 31
    hour : Integer 14
    minute : Integer 22
    second : Integer 55
    dayOfWeek : nil
    rawSeconds : nil
}

It would also be nice to be able to compare Date objects using (d < e) or at least (d.rawSeconds < e.rawSeconds) ... which you could if `rawSeconds` had been properly computed for you.

```
if (d < e) { "% is earlier than %".format(e.rawSeconds, d.rawSeconds).postln };  
```

I searched for this issue in GitHub and in the sc-users list, the only thing I found was a [message from Marije in 2009](http://new-supercollider-mailing-lists-forums-use-these.2681727.n2.nabble.com/Date-stamp-to-Date-td3164085.html), wanting to do the same thing (with no response).

Or maybe there's a Quark that already handles this?

Thanks,
Glen.

**Comment by totalgee** [comment]
BTW, the other thing Marije wanted in the above-mentioned thread was the ability to parse strings to create Date objects.

**Comment by telephon** [comment]
i remember i stumbled upon this, too. it's a good idea to improve the date implementation
