### ISSUE TITLE
Quarks: Check dependencies before uninstalling a quark

### ISSUE THREAD

**Issue by jamshark70** [supercollider/supercollider#3093]
I don't have time to work on this now, but it would eliminate a class of library-compilation problems if the quark uninstall process would look for installed quarks that depend on the quark being uninstalled.

That sentence is confusing. Concrete example:

1. `"CommonTests".include` and recompile library.

   ```
   Installing CommonTests
   Installing UnitTesting
   UnitTesting installed
   Adding path: /home/dlm/.local/share/SuperCollider/downloaded-quarks/CommonTests
   CommonTests installed
   ... the class library may have to be recompiled.
   ```

2. Oops, that was the wrong one... I really wanted the testsuite from git. OK.

   ```
   Quarks.uninstall("UnitTesting");
   Quarks.uninstall("CommonTests");
   ```

3. Recompile:

   ```
   ERROR: Superclass 'UnitTest' of class 'TestKMeans' is not defined in any file.
   /home/dlm/.local/share/SuperCollider/downloaded-quarks/KMeans/KMeans.sc
   ERROR: There is a discrepancy.
   ```

That is, in step 2, I didn't realize that KMeans depends on UnitTesting. Quarks didn't tell me there would be a problem -- it cheerfully removed the directory from the include paths and got the library into an inconsistent state.

*I* knew how to fix it locally (open sclang_conf.yaml and add the path by hand), but typical users should not be expected to know that.

When uninstalling a quark, we should check the dependencies of all installed quarks and, at the very least, fail if there's a problem. Quarks.gui could pop up a window telling the user which quarks will be affected and allowing the user to a/ abort, b/ keep quarks that are required by other quarks (but uninstall others) or c/ uninstall quarks that require the uninstall target. In my case above:

a- Fail.
b- Uninstall CommonTests, but *keep* UnitTesting.
c- Uninstall CommonTests, UnitTesting *and* KMeans (the user will already have been alerted that this would be the consequence of this option).

**Comment by muellmusik** [comment]
James, can you assign yourself to this? Otherwise I think we should mark stale and close
