### ISSUE TITLE
Interpreter crash with Function:play and Function:plot

### ISSUE THREAD

**Issue by LFSaw** [supercollider/supercollider#3107]
```
s.boot;

b = Buffer.read(s, Platform.resourceDir +/+ "sounds/a11wlk01.wav")
b = { PlayBuf.ar(1, b) }
{ b.() }.plot(2)
```

this crashes the interpreter; took me quite a while to figure out what was happening (maybe you see it easier; I stripped away all unnecessary code).

I wonder if we can/should do something about it but @joshpar wants to have a look at it and urged me to create a bug report ;)

**Comment by adcxyz** [comment]
is that any different from infinite recursion in general? 
// these crash sclang
f = { PlayBuf.ar(1, f) }; f.();
f = { PlayBuf.ar(1, f) }; f.play;
f = { PlayBuf.ar(1, f) }; f.plot;
// this infinitely loops without crashing
f = { f.value }; f.value;

**Comment by brianlheim** [comment]
yeah, this is just endless recursion. works if you rename the second `b` to `c`.

**Comment by LFSaw** [comment]
Although I generally do not object to closing this, I'd also like to point out that @joshpar explicitly asked me to open the issue. Therefore I'd assume (and also because he's assigned to the issue) that either he or myself (as I opened the issue) should be the ones to close is again. Sorry brian, I think you are often a little too fast in judging what others might find important.

Also, if you are so easy with the solution of " just endless recursion", why does this throw an error, then?

```
s.boot;

b = Buffer.read(s, Platform.resourceDir +/+ "sounds/a11wlk01.wav")
b = { PlayBuf.ar(1, b.bufnum) }
{ b.() }.plot(2)
```

**Comment by brianlheim** [comment]
> Also, if you are so easy with the solution of " just endless recursion", why does this throw an error, then?

Because you're reassigning `b` to a function in the fourth line of your example. When it is evaluated in the fifth line, you are evaluating `{ PlayBuf.ar(1, { PlayBuf.ar(1, b.bufnum}.bufnum) }`, which is of course going to throw an error.

> Therefore I'd assume (and also because he's assigned to the issue) that either he or myself (as I opened the issue) should be the ones to close is again.

You don't need someone else to look at this to know it's simple programmer error. We already have an issue that was opened, discussed, and closed, about what to do in the case of infinite recursive method calls. https://github.com/supercollider/supercollider/issues/628

> Sorry brian, I think you are often a little too fast in judging what others might find important.

lol

**Comment by adcxyz** [comment]
in the version with bufnum:
``` b = { PlayBuf.ar(1, b.bufnum) }; { b.() }.plot(2) ```
the error is that the function b does not understand .bufnum. 
in ``` b = { PlayBuf.ar(1, b) }; { b.() }.plot(2) ```
it is a bit strange that you get a crash, not just a hang:
having a func in a ugen input calls .asUgenInput on the func, 
which calls .value(<theUgen>) on the func, so this is where the recursion happens.

I think I have a lead where the difference comes from: 
```b = { b.() }; b.();    // > just hangs, no crash - nothing is allocated, so interpreter is just busy
b = { [ b.() ] }; b.(); // > crashes after a few seconds - out of memory by allocating [[[[array..]]]?
```
hth, best a

**Comment by telephon** [comment]
feel free to reopen if needed, though I think it is "solved". Thanks!
