### ISSUE TITLE
Strange behaviour when rebooting muted Server

### ISSUE THREAD

**Issue by patrickdupuis** [supercollider/supercollider#3110]
A Server that had been muted prior to reboot will keep it's muted status but will produce sound. Sound will only be killed once the server is unmuted and re-muted.

Relate issue #3108 (and probably #3105). 

### Reproducer
```supercollider
s.boot;
s.mute;
{ SinOsc.ar * 0.1 }.play // no sound
s.reboot;
s.volume.isMuted; // true
{ SinOsc.ar * 0.1 }.play // hear sound
s.mute; // no change
s.unmute;
s.mute; // sound halts
```

**Comment by tiagmoraismorgado** [comment]
sometimes you also get clicks with these kinds of things

**Comment by LFSaw** [comment]
is this fixed with #3120 ?

**Comment by brianlheim** [comment]
afaict, yes

**Comment by patrickdupuis** [comment]
thanks for closing!
