### ISSUE TITLE
Travis failing test appears green

### ISSUE THREAD

**Issue by vivid-synth** [supercollider/supercollider#3115]
https://travis-ci.org/supercollider/supercollider/jobs/260020249 fails some tests (and it's my fault!) but the travis result is green.

**Comment by brianlheim** [comment]
https://github.com/supercollider/supercollider/blob/master/.travis/test.sh#L11

should be changed to

```bash
$TRAVIS_BUILD_DIR/testsuite/sclang/launch_test.py $SCLANG || echo "Test launch failed, aborting" && exit 1

**Comment by LFSaw** [comment]
related to #3132

**Comment by brianlheim** [comment]
closing now that we've moved to GHA
