### ISSUE TITLE
Mailing list subscription process is broken

### ISSUE THREAD

**Issue by yurivict** [supercollider/supercollider#3130]
Clicking on the link in the confirmation e-mail:
http://www.mailhub.bham.ac.uk/cgi-bin/confirm?auth%20a4eb60cab1b3391a%20subscribe%20sc-users%20xxx@xxx.com
fails with this error:
```
You are not allowed access to this Web object:
http://www.mailhub.bham.ac.uk/cgi-bin/confirm?auth%20a4eb60cab1b3391a%20subscribe%20sc-users%20yuri@rawbw.com
```

You should switch to the mailman-based type of subscription like most MLs use: https://lists.llvm.org/mailman/listinfo/llvm-dev
It always works, easy to use, and works like a charm.

**Comment by brianlheim** [comment]
possibly because Nabble is down for maintenance? (http://new-supercollider-mailing-lists-forums-use-these.2681727.n2.nabble.com/SuperCollider-Users-New-Use-this-f2676391.html)

anyway, this is a better question for the mailing list. i personally don't have an issue with it, but it's come up in the past.

**Comment by muellmusik** [comment]
I just went to subscribe you manually, but yuri@rawbw.com is already added.

**Comment by jamshark70** [comment]
@brianlheim the message in the original issue report was about bham.ac.uk, which doesn't care what Nabble is doing.

At least one other user reported that bham.ac.uk said the subscription attempt failed, but then the list was working for them. So there is something wrong with the web front end that's not necessarily reflecting a backend failure.

**Comment by muellmusik** [comment]
If someone can provide a detailed description of the problem I can forward it.

**Comment by yurivict** [comment]
De-facto, it is much harder to subscribe compared to most other lists.
It offers choices:
* to click the link that is broken
* to send an e-mail with a particular line. When I copy-paste it the e-mail fails too because this likne contains html-ified e-mail. So users should figure out to type it manually.

All these choices are entirely not necessary. This doesn't happen with other MLs.

**Comment by muellmusik** [comment]
Sorry, I don't understand this. Please tell me exactly what happens at each step. Thanks.

**Comment by yurivict** [comment]
Try subscribing again.
step 1 fails with message from my OP.
step 2 fails with html message that has been copied and pasted.

It is way to complicated to subscribe currently.

**Comment by brianlheim** [comment]
@muellmusik I tried this myself.

1. Send "subscribe sc-users" to majordomo@lists.bham.ac.uk
2. Received two emails: "Majordomo results" and "Confirmation for subscribe sc-users". The second one has the link to click to confirm subscription. When I click it, I'm taken to a page with this text. Screenshot below.

```
You are not allowed access to this Web object:
http://www.mailhub.bham.ac.uk/cgi-bin/confirm?auth%20b0280173ca503223%20subscribe%20sc-users%20brian.heim@yale.edu
```

![image](https://user-images.githubusercontent.com/15369640/29330259-ade285cc-81c6-11e7-84a5-8c64c8bfe664.png)

3. Send requested auth message via email instead, copy-pasted from original message.
4. Received two emails: "Majordomo results" and "Welcome to sc-users"

I would not rate that as "way too complicated." But it is annoying that the first link doesn't work. It is also somewhat confusing that the "Majordomo results" emails will hide the "succeeded" message inside error/warning messages about HTML elements not being recognized:

```
>>>> --94eb2c0df18c51c9760556cf0d74
**** Command '--94eb2c0df18c51c9760556cf0d74' not recognized.
>>>> Content-Type: text/plain; charset="UTF-8"
**** Command 'content-type:' not recognized.
>>>>
>>>> auth xxx subscribe sc-users brian.heim@yale.edu
Succeeded.
>>>>
>>>> --94eb2c0df18c51c9760556cf0d74
**** Command '--94eb2c0df18c51c9760556cf0d74' not recognized.
>>>> Content-Type: text/html; charset="UTF-8"
**** Command 'content-type:' not recognized.
>>>> Content-Transfer-Encoding: quoted-printable
**** Command 'content-transfer-encoding:' not recognized.
>>>>
>>>> <div dir=3D"ltr"><span style=3D"font-size:12.8px">auth b0280173ca503223 sub=
**** Command '<div' not recognized.
>>>> scribe sc-users=C2=A0</span><a href=3D"mailto:brian.heim@yale.edu" style=3D=
**** Command 'scribe' not recognized.
>>>> "font-size:12.8px">brian.heim@yale.edu</a><br></div>
**** Command '"font-size:12.8px">brian.heim@yale.edu</a><br></div>' not recognized.
>>>>
>>>> --94eb2c0df18c51c9760556cf0d74--
**** Command '--94eb2c0df18c51c9760556cf0d74--' not recognized.
```

@yurivict I would recommend reading our [contributing.md](https://github.com/supercollider/supercollider/blob/master/CONTRIBUTING.md#issues) document which has tips on how to submit helpful issue tickets.

**Comment by yurivict** [comment]
> I would recommend reading our contributing.md document which has tips on how to submit helpful issue tickets.

On step 4 I got an e-mail with a lot of errors because my client (TB) have sent a multi-part message. This was triggered by an e-mail being a link.

I can't see what was not helpful with my message.

**Comment by brianlheim** [comment]
> I can't see what was not helpful with my message.

I think @muellmusik hinted at it already - it helps to have clear steps to reproduce and full error messages. The initial report was a little vague because you started reporting in the middle of the process, after you'd sent the first email. A statement like

> When I copy-paste it the e-mail fails too because this line contains html-ified e-mail

could also be made more specific by posting the actual result rather than simply saying "fails."

**Comment by muellmusik** [comment]
Thanks Brian.

**Comment by jamshark70** [comment]
@muellmusik I just remembered another issue. Awhile back, I tried to subscribe using an outlook.com account, but it was impossible because that free mail service can send only base64 encoded email, not plain ASCII, and majordomo didn't understand the encoding. Maybe not much your IT department can do about that, but it was an obstacle (though perhaps a blessing, since it convinced me to look for an alternative to Microsoft).

**Comment by brianlheim** [comment]
@muellmusik any updates on this?

**Comment by brianlheim** [comment]
@muellmusik - any updates?

**Comment by muellmusik** [comment]
Sorry, back in August I was told this:

> It is fairly clear why the emailed version did not work as smoothly as expected; this must be sent in plain text and the message was sent as text and html.  I am a little surprised it worked at all.  This was the main reason for providing the web link version.

But there wasn't a clear indication of why the web link had failed. I've chased it again.

**Comment by muellmusik** [comment]
I also tried it at the time, and there seemed to be a problem in Safari, but not Chrome. The IT staff couldn't see the problem in Safari. Hmm...

**Comment by muellmusik** [comment]
Got this reply:

>It’s possible this web link is only available onsite could this be the reason for the link working in some cases and not others. If this is a possibility I can check this out for you.
 
>Other possible issues with web clients are usually down to them having visited a badly configured onsite webserver that is promiscuous with their auth cookies (given the age of this web interface we have some extended security on these web pages). Can you test the interface again with ‘private browsing’ (or similar) turned on.
 
@brianlheim could you give this a try? Also can you confirm if it's a problem in all browsers or only Safari for you?

**Comment by brianlheim** [comment]
Doesn't seem to be an issue anymore
