### ISSUE TITLE
Fails to open some wavs

### ISSUE THREAD

**Issue by yurivict** [supercollider/supercollider#3137]
Instruction
```
c=Buffer.read(s,"/path/to/1.wav");
```
fails on some wavs with such error:
```
-> Buffer(3, nil, nil, nil, /path/to/1.wav)
File '/path/to/1.wav' could not be opened: Error in WAV/W64/RF64 file. Malformed 'fmt ' chunk.
```

This file is identified as:
```
$ file /path/to/1.wav
/path/to/1.wav: RIFF (little-endian) data, WAVE audio, MPEG Layer 3, stereo 8000 Hz
```

It has some MPEG encoded in it. mplayer plays it fine.

**Comment by brianlheim** [comment]
That's a RIFF format, not WAV. RIFF is not one of libsndfile's supported filetypes, and the author has no intention to add support for mp3, so at most you'd be able to extract the wav portion.

**Comment by yurivict** [comment]
Ok than. Thanks!
