### ISSUE TITLE
s.record records stereo with only one channel

### ISSUE THREAD

**Issue by yurivict** [supercollider/supercollider#3141]
This script:
```
    (
      play({SinOsc.ar(freq: 1000)});
      s.record(path: "out.wav".standardizePath);
      3.wait;
      s.stopRecording;
    )
```

creates the wav file that only has the left channel, and the right channel is empty. It doesn't make sense that stereo file is created when synthesizer writes only one channel.

Additionally, ```sox out.wav out1.wav remix 2``` complains:
```
sox WARN sox: `out1.wav' output clipped 183 samples; decrease volume?
```

This means that samples have too high values?

**Comment by snappizz** [comment]
this is expected behavior. `Server:record` (and `Recorder:record`) has a `numChannels` argument, which defaults to the server's number of output channels. you may be playing a mono synth, but it's a stereo server.

i'm not seeing the sox warning over here.

**Comment by telephon** [comment]
on one server you can have many synths simultaneously that may have all kinds of channel setups. just because you play a mono synth doesn't mean that your recording of the server output is mono. 

if you want to record mono, you can pass the number of channels as parameters to the ` record` method, if

**Comment by telephon** [comment]
... i remember correctly.

**Comment by telephon** [comment]
again this would be better in the mailing list

**Comment by yurivict** [comment]
@snappizz 
> Server:record (and Recorder:record) has a numChannels argument

If you mean that ```s.record(path: "out.wav", numChannels: 1);``` is supposed to create 1-channel audio, this doesnt't work, the audio is still stereo.

**Comment by snappizz** [comment]
hmmm, seems to be working here. test case:

    (
    Routine.run {
        var numChannels, filePath, soundFile;
        numChannels = 1;
        filePath = "~/out.wav".standardizePath;
        s.record(path: filePath, numChannels: numChannels);
        s.sync;
        0.1.wait;
        s.stopRecording;
        s.sync;
        soundFile = SoundFile();
        soundFile.openRead(filePath);
        "The file has % channel(s)".format(soundFile.numChannels).postln;
    };
    )

for me this prints "The file has 1 channel(s)"

**Comment by yurivict** [comment]
Your testcase still creates the stereo file in sclang:

```
$ sclang TestChannels.scd 
init_OSC
compiling class library (debug build)...
initPassOne started
	NumPrimitives = 688
initPassOne done
	compiling dir: '/usr/local/share/SuperCollider/SCClassLibrary'
	compiling dir: '/usr/local/share/SuperCollider/Extensions'
	pass 1 done
	numentries = 1169685 / 16464642 = 0.071
	5267 method selectors, 3126 classes
	method table size 17702080 bytes, big table size 131717136
	Number of Symbols 13641
	Byte Code Size 390129
	compiled 438 files in 0.35 seconds

Info: 3 methods are currently overwritten by extensions. To see which, execute:
MethodOverride.printAll

compile done
Class tree inited in 0.02 seconds
Cleaning up temp synthdefs...
WARNING: Extension in '/usr/local/share/SuperCollider/SCClassLibrary/Platform/linux/extMIDIOut.sc' overwrites Meta_MIDIClient:externalSources in main class library.
WARNING: Extension in '/usr/local/share/SuperCollider/SCClassLibrary/Platform/linux/extMIDIOut.sc' overwrites Meta_MIDIClient:externalDestinations in main class library.
WARNING: Extension in '/usr/local/share/SuperCollider/SCClassLibrary/Platform/linux/extMIDIOut.sc' overwrites Meta_MIDIIn:connectAll in main class library.
Intentional overwrites must be put in a 'SystemOverwrites' subfolder.


*** Welcome to SuperCollider 3.8.0. *** For help type ctrl-c ctrl-h (Emacs) or :SChelp (vim) or ctrl-U (sced/gedit).
booting 57110
server already booting
Found 242 LADSPA plugins
*** ERROR: dlopen '/usr/local/lib/SuperCollider/plugins/StkInst_supernova.so' err '/usr/local/lib/SuperCollider/plugins/StkInst_supernova.so: Undefined symbol "_ZN3stk3Stk13showWarnings_E"'
Faust: supercollider.cpp: sc_api_version = 2
Faust: FaustGreyholeRaw numControls=7
Faust: supercollider.cpp: sc_api_version = 2
Faust: FaustJPverbRaw numControls=11
JackDriver: client name is 'SuperCollider'
SC_AudioDriver: sample rate = 48000.000000, driver's block size = 1024
cannot use real-time scheduling (FIFO at priority 5) [for thread 65110784, from thread 65110784] (1: Operation not permitted)
JackDriver: connected  system:capture_1 to SuperCollider:in_1
JackDriver: connected  system:capture_2 to SuperCollider:in_2
JackDriver: max output latency 21.3 ms
JackDriver: connected  SuperCollider:out_1 to system:playback_1
JackDriver: connected  SuperCollider:out_2 to system:playback_2
SuperCollider 3 server ready (debug build).
Receiving notification messages from server localhost
Shared memory server interface initialized
WARNING: keyword arg 'numChannels' not found in call to Server:record
Recording: /home/yuri/out.wav
Recording Stopped: /home/yuri/out.wav
The file has 2 channel(s)
```

**Comment by snappizz** [comment]
looks like you're running 3.8 -- can you try the latest dev version 
instead?

**Comment by yurivict** [comment]
If this feature is only in the dev version, this is fine then. There is no bug.

Thanks!
