### ISSUE TITLE
PanAz: misleading helpfile examples "Comparison to Pan2"

### ISSUE THREAD

**Issue by dkmayer** [supercollider/supercollider#3149]
The example uses an ar pos arg, which behaves different from a kr pos arg, #3148. 
The comparison would actually make sense, but should be based on well-defined behaviour of PanAz, so #3148 probably needs attention first.

http://new-supercollider-mailing-lists-forums-use-these.2681727.n2.nabble.com/PanAz-bug-ar-position-arg-is-scaled-wrongly-td7634788.html

**Comment by LFSaw** [comment]
since you have good examples in your mail at the list, would you mind adjusting the helpfile accordingly?

**Comment by dkmayer** [comment]
Ok, I'll do also in the evening.

**Comment by brianlheim** [comment]
closed by #3153
