### ISSUE TITLE
Integration of sc guis into IDE window

### ISSUE THREAD

**Issue by miguel-negrao** [supercollider/supercollider#315]
- Dockable GUI windows.
- Abilitiy to use "full screen" mode without the need to manage window z-depth.

DONE- integrated server windows, could be just a collapse strip that hangs on the bottom of the screen.

**Comment by brianlheim** [comment]
@miguel-negrao or anyone else - I'm having trouble visualizing this. How exactly would this work?

**Comment by snappizz** [comment]
This proposal is about making GUI windows created in sclang dockable into SCIDE.

**Comment by brianlheim** [comment]
Huh. Very cool. Anyone have thoughts about how easy it would be to implement?

**Comment by timblechmann** [comment]
should not be too hard: qtcollider provides some proxy objects to communicate between qt and sclang. one could hook into them and communicate with the ide instead. btw, if qml would be used, it may be even easier to achieve ...

**Comment by miguel-negrao** [comment]
not a priority. closing.
