### ISSUE TITLE
Document all repository development tools & practices (add a DEVELOPING.md)

### ISSUE THREAD

**Issue by brianlheim** [supercollider/supercollider#3163]
#3075 is a component of this.

### Problem

Many of our development tools & practices are undocumented, with information fragmented across multiple files, mailing list posts, etc.

### Solution

Add a DEVELOPING.md which contains a comprehensive guide to understanding and using these tools.

### Progress

I've been working on a WIP guide on the wiki here: https://github.com/supercollider/supercollider/wiki/%5BWIP%5D-Developer-info-(DEVELOPING.md)

Please discuss with me before editing.

List of components that should be documented:
- [ ] boost lib maintenance
- [ ] 3rd party lib maintenance (i'm not sure if any other libraries need specific documentation, but it would be nice to have a sentence or two about each)
- [ ] lexer/parser/compiler regression test suite
- [ ] debug capabilities present from within sclang (these exist for at least SCDoc and QtGUI)
- [ ] unit test suite (testsuite/) including organization of test suite
- [ ] source code organization
- [ ] style

The expected form for this documentation is:
- A main `DEVELOPING.md` in root
- If needed, a more detailed `README_<SUBJECT>.md` present in the relevant directory. Example: https://github.com/supercollider/supercollider/blob/master/external_libraries/README_BOOST.md

**Comment by brianlheim** [comment]
Note: #3161 - document that testsuite/classlibrary/server contains all tests that need the server, and are not run by travis.

**Comment by LFSaw** [comment]
You imply that the `UnitTest` tutorial/guide ( #3075 ) should be part of that? 
I.e. it'll be an `.md` file rather than a `.schelp`. I'm open for both ideas but would like to know which format is thought favourable before I start formatting the text for it.

**Comment by LFSaw** [comment]
also IMHO at least @telephon should take part in this discussion :) ( *wave* )

**Comment by LFSaw** [comment]
oh, and: great initiative!

**Comment by LFSaw** [comment]
To answer my own question:

IMHO, the core information about what is where should go into DEVELOPING.md. Where needed/applicable (e.g. in the case of UnitTests), it should point towards more in-depth information. This can be either located in SCDoc (e.g. for UnitTests) or in subdirectories (`.travis`, 
sclang Lexer, Parser, & Compiler Regression Test Suite, ...). 

This would prevent us from creating a montrousity of a document and also, to point to that information more fine-grained from other resources (e.g. from within SCDoc helpfiles).

**Comment by brianlheim** [comment]
@LFSaw I think all info for developers should be in txt or md. schelp has the downside of requiring the reader to open the IDE. It can't be easily read in-browser or with a text editor (or at least, it's rather ugly to do so). And, we would be forced to place it in HelpSource/, away from the actual directory in which it is relevant.

I think a secondary schelp file, providing a brief and user-friendly intro, which points to the more detailed documentation is not a bad idea. I just want to avoid both (a) duplicating documentation and (b) fragmenting its format and organization.

**Comment by LFSaw** [comment]
I'm totally with you here. I totally digg Markdown and it more and more becomes my second tongue (after LaTeX... :P ).
 
However, a "How to write a UnitTest and where to put it", should be easy to find also from within SuperCollider, no? One solution would be a help-system reform :) 

Seriously, IMHO we have to split up the information: Organisational/structural information on how to _run_ the tests and where to find them need to go into a MarkDown document. Everything that deals with actually creating and maintaining the tests should IMHO be in an sc helpfile.

**Comment by cianoc** [comment]
Maybe developer information that is specific to the SuperCollider language should be accessible in the IDE, and everything else should be in md files? I agree with LFSaw that unit test information should be in an SC helpfile, and that there should also be stuff on SuperCollider style (which in my opinion is super helpful and should be aggressively pushed). And then maybe some of the other stuff can at least be linked to from the SuperCollider help files.

**Comment by brianlheim** [comment]
In this conversation:

users = people that write programs in supercollider
developers = people that contribute to the supercollider core library or C++ codebase

what you're describing (unit testing, style) is of interest to users, so yes, that should be released with the main package in some form. i agree with that.

i am going to write my developer-facing documentation in markdown first. i think from that we can easily figure out what subset should be excerpted for user-facing documentation. sound good? the important thing is just getting all the information written out in the first place, and i think it will be much easier to collaborate on a document in human-readable format. :)

**Comment by telephon** [comment]
yes, that sounds good ! 


we actually should have a way to render md to ( simple) schelp

**Comment by jamshark70** [comment]
> we actually should have a way to render md to ( simple) schelp

Related: I started, but never finished, an Emacs org-mode exporter for schelp.

Basic org features are not too different from markdown, actually.

MD:

```
# Heading
## Subheading

Text with *italics* and **bold**.
```

Org:

```
* Heading
** Subheading

Text with /italics/ and *bold*.
```

Lists are handled similarly, as well.

The drawback, of course, is that not everybody likes Emacs...

**Comment by brianlheim** [comment]
this is all documented on the wiki now, future discussions about what should be documented where and how probably belong in new tickets.
