### ISSUE TITLE
Add content of UnitTesting quark to common lib

### ISSUE THREAD

**Issue by LFSaw** [supercollider/supercollider#3164]
To ease the process of UnitTesting and also allow people to easily write their own UnitTests for their Quarks, I'd strongly suggest including the UnitTest framework (`UnitTest, UnitTestResult, UnitTestScript`) to the main repository. This will also ensure that travis builds always use the right UnitTest framework for their tests.

**Comment by gusano** [comment]
:+1: Been asking that for a long time now :)

**Comment by LFSaw** [comment]
@scztt @telephon @adcxyz @brianlheim @muellmusik @miguel-negrao 
any reason not to?

**Comment by telephon** [comment]
Let's do this, sure.

**Comment by LFSaw** [comment]
#3168

**Comment by miguel-negrao** [comment]
Sounds good to me.

**Comment by adcxyz** [comment]
yes, makes sense, all for it.

**Comment by brianlheim** [comment]
Fixed in #3168
