### ISSUE TITLE
Proposal - make ReadableNodeIDAllocator default

### ISSUE THREAD

**Issue by adcxyz** [supercollider/supercollider#3174]
PR #3106 includes an optional new scheme for nodeID allocation in the ReadableNodeIDAllocator class. 
ReadableNodeIDAllocator is now in a separate PR, #3179.

NodeIDAllocator is hard-limited to a maximum of 32 clientIDs, and allocates a max of 
67 mio nodeIDs before wrapping. support for the 32 possible clientIDs is implemented by a 5-bit-mask, i.e. an offset of (2 ** 26) * clientID added to each node. 

ReadableNodeIDAllocator allows an arbitrary number of clients, 
and creates human-readable decimal prefixes for nodeIDs: 
10 ** 8 for 1-2 clients, 10**7 for 3-21, 10**6 for 22-213, etc. 

For example, with 32 clients and clientID 13, first temp nodeIDs are:
NodeIDAllocator  ReadableNIDAll.
67109864            130001000

Thus, I propose in PR #3106 to make ReadableNodeIDAllocator the default allocator class;
for backwards compatibility, switching to NodeIDAllocator can be done in one line of code:
```Server.nodeAllocClass_(NodeIDAllocator);```
In fairness, the 32-clients limit in NodeIDAllocator could also be lifted by making the bitmask variable depth.

Detailed comparisons: 
* Number of IDs that can be allocated for different numbers of clients:
ReadableNodeIDAllocator is better from 1-21 (1000 mil resp 100 mil vs 67 mil), 
NodeIDAllocator is better from 22 - 31 (67 mil vs 10 mil,
NodeIDAllocator stops hard at 32, ReadableNodeIDAllocator works above that.
```
// Plot numIDs: top array is NodeIDAllocator, 
// second array is ReadableNodeIDAllocator.
(1..64).collect { |numClients, i|
	var niaNumIDs = if (numClients < 32, { 2**26 - 1000 }, 0);
	var rnia = ReadableNodeIDAllocator(0, 1000, numClients);
	var rniaNumIDs = rnia.numIDs; 
	"%: ".postf(i);
	[niaNumIDs, rniaNumIDs ].postln;
}.flop.plot("5bit vs decimal nodeIDs", Rect(0,0,400,400), minval: 0, maxval: 100000000)
```

* Time before nodeIDs begin to wrap, and overlaps become theoretically possible:
Nodes that never get a second message should always use nodeID -1 for clarity and efficiency;
nodes shorter than one blockSize are not reachable by any message before they end.
Thus, the minimum duration for a synth with a meaningful nodeID is one blocksize.
```
f = { |numIDs = (2 ** 26 - 1000), polyphony = 64, sr = 44100, blockSize = 64|
	var timeBeforeIDsWrap = numIDs * (blockSize / polyphony) / sr;
	timeBeforeIDsWrap.asTimeString.postln;
	timeBeforeIDsWrap
};

// NodeIDAllocator, 64 voices, 
// dur always minimum, i.e. samples ~= one blocksize
f.value((2 ** 26 - 1000), 64); // 25 minutes
f.value((2 ** 26 - 1000), 32); // 50 minutes

// ReadableNodeIDAllocator, 1-2 users, 64 voices, minimum dur
64 samples ~= one blocksize
f.value((1000000000 - 1000), 64); // 6h 18mins 
// ReadableNodeIDAllocator, 3-21 users, 64 voices, minimum dur
f.value((100000000  - 1000), 64); // 37mins 
// ReadableNodeIDAllocator, 22-213 users, 64 voices, minimum dur
f.value((10000000   - 1000), 64); // 3min64 
```
An actual clash occurrence would require:
A high density of parallel synths, say 64; 
a new synth starting on every single sample;
the need to send meaningful control messages to potentially each one of them;
and then having some of these synths live for 25-50 minutes to send to them again.
This combination of circumstances seems extremely unlikely to me, so IMHO all these nodeID ranges seem quite safely sufficient - which is good to know.

**Comment by brianlheim** [comment]
@adcxyz - is this resolved? I can't remember if you made this change or not, i seem to remember people wanting to have it be opt-in

**Comment by adcxyz** [comment]
Hi @brianlheim, 
current 3.9 dev leaves the default, NodeIDAllocator as was, 
and shows how to opt-in:
```
	*initClass {
...
		nodeAllocClass = NodeIDAllocator;
		// nodeAllocClass = ReadableNodeIDAllocator;
		bufferAllocClass = ContiguousBlockAllocator;
		busAllocClass = ContiguousBlockAllocator;
...
	}
```
Multi-Client Setups guide file demonstrates using ReadableNodeIDAllocator, 
and it has a help file. 
so, good to go AFAIAC.

**Comment by brianlheim** [comment]
great, thanks for the update :)
