### ISSUE TITLE
[Help] TOC dropdown awkward without fixed top bar

### ISSUE THREAD

**Issue by patrickdupuis** [supercollider/supercollider#3176]
There are two issues related to the Help Browser's Table of Contents functionnality :

1. **with TOC open from the top bar**
Try opening the TOC of `ServerOptions` from the top bar. The bottom part of the TOC is obscured. There should be a way to scroll within the TOC. 

2.  **with TOC popped out**
It is possible to scroll within the TOC when popped out. However, the last line is always partially obscured.

**Comment by telephon** [comment]
1. I can scroll down by scrolling the page. Does that work for you?

2. I can't reproduce this on  on macos.

**Comment by snappizz** [comment]
this is a design consequence of #2967 that i didn't entirely think through. with the top bar no longer being `position: fixed`, using the TOC dropdown is now very awkward to use.

i have a simple solution -- there's an option to pop out the TOC to the left. we can get rid of the dropdown and just go straight to the pop out.

**Comment by patrickdupuis** [comment]
> 1. I can scroll down by scrolling the page. Does that work for you?

No. The top bar floats now, as @snappizz pointed out. Scrolling does not reveal the bottom part of the TOC.

> 2. I can't reproduce this on on macos.

I wonder if this is OS specific. I would expect changed to CSS styling to affect all systems.

@snappizz  Now that I've discovered the pop out TOC, I quite prefer it. I'd be in favour of having it be the default behaviour.

**Comment by snappizz** [comment]
hmm, in addition to the design issues there seems to be a bug happening on your system. can you post a screenshot?

**Comment by patrickdupuis** [comment]
Do you need a screenshot of the bottom of the popped out TOC? This is as far I can can scroll.

![toc_popup](https://user-images.githubusercontent.com/11747870/30254561-94ec9aec-9668-11e7-8b42-e57179846b8c.png)

**Comment by patrickdupuis** [comment]
What do you think the issue is on my system? Could it be related to Gnome?

**Comment by patrickdupuis** [comment]
I had a custom CSS file that was theming my Help Browser. I believe this was causing the above issue.

**Comment by brianlheim** [comment]
> the above issue

Meaning the entire issue or just part of it. i.e. do we even need to keep this open and/or merge #3346? I have to admit I've never bothered to examine this.

**Comment by patrickdupuis** [comment]
Yes, we have to keep this issue because of @snappizz's comment above :

> this  is a design consequence of #2967 that i didn't entirely think through. with the top bar no longer being position: fixed, using the TOC dropdown is now very awkward to use.

I've updated the issue title, and we can close when #3346 is merged.
