### ISSUE TITLE
linux: OS intermittently hangs when leaving scide+sclang open for a long time

### ISSUE THREAD

**Issue by snappizz** [supercollider/supercollider#3182]
i've noticed that my laptop (ubuntu studio 16.04) has experienced issues where the OS hangs completely for a few seconds at a time, and the keyboard doesn't respond. every time i notice this, i realize that i've left scide+sclang open for a long time -- usually many hours across multiple laptop suspensions. every time i close scide, the problem goes away instantly.

i will try to isolate the problem to either scide or sclang, so stay tuned.

**Comment by snappizz** [comment]
update: this happened when leaving scide open with an inactive interpreter, so it seems to be the IDE

**Comment by brianlheim** [comment]
have you observed a memory leak? i.e. when you kill it is the process taking up way more memory than it did initially? that seems like the most likely culprit.

**Comment by snappizz** [comment]
hmmm... probably not SC
