### ISSUE TITLE
PitchShift can crash the server

### ISSUE THREAD

**Issue by muellmusik** [supercollider/supercollider#3183]
Accidentally did something equivalent to this today:

```{ PitchShift.ar(SinOsc.ar, SinOsc.ar) }.play```

I know window size is not modulatable, but this shouldn't bring the server down.

This behaves similarly: ```{ PitchShift.ar(SinOsc.ar, 0) }.play ```

**Comment by telephon** [comment]
I think it's not the fact that it is modulated, but that it is (or starts, in this case) zero:

`{ PitchShift.ar(SinOsc.ar, 0) }.play`

also crashes.

**Comment by telephon** [comment]
Might be around here: https://github.com/supercollider/supercollider/blob/master/server/plugins/DelayUGens.cpp#L5684

**Comment by snappizz** [comment]
can reproduce

**Comment by snappizz** [comment]
more generally, scsynth freezes if the window size is <= `2 * SampleDur.ir`

**Comment by brianlheim** [comment]
@snappizz, can we please not add new issues/prs to the 3.9 milestone? i think multi-client is the last thing that should go in. in other words, let's make a 3.9.1 and/or 3.10 milestone and add this to it.

**Comment by telephon** [comment]
better `3.9.1`, I think. (I'll make a suggestion on sc-dev)

**Comment by snappizz** [comment]
resolved with #3186
