### ISSUE TITLE
evaluating empty case crashes interpreter

### ISSUE THREAD

**Issue by scacinto** [supercollider/supercollider#3187]
Mac OS 10.12.5
Confirmed on SC3.8 and 3.9dev (Built from branch 'HEAD' [40323ce])

Evaluating a case with multiple empty results in Interpreter crash: 
Interpreter has crashed or stopped forcefully. [Exit code: 0]

`case {} {} {} {} `

Crash also occurs with empty first case even if following cases contain valid code.

`case {} {} {2 > 0} {"true!".postln}`

**Comment by brianlheim** [comment]
Probably related to #1005 (or both could be closed with a good fix).

**Comment by jamshark70** [comment]
Yes, I'm sure it's a dup. I'm pretty sure both are related to building the hash table for the ControlOpcode's branches.

**Comment by brianlheim** [comment]
Closing as dup of #1005.
