### ISSUE TITLE
[SC-IDE] text documents embedded with code.

### ISSUE THREAD

**Issue by miguel-negrao** [supercollider/supercollider#319]
Come up with a format for text documents embedded with code that are written in plain text.  This would be useful for tutorials, presentations, etc where you explain concepts and then present code. At the simplest some way to distinguish normal text from code.

**Comment by snappizz** [comment]
One interesting idea to this end would be [Jupyter](http://jupyter.org/) integration.

**Comment by brianlheim** [comment]
Does anyone object to closing this? Seems very low-priority and more trouble than it's worth to implement.

**Comment by snappizz** [comment]
It's not a bad idea, but I don't think we should talk about it until someone makes progress.

**Comment by ax3l** [comment]
> One interesting idea to this end would be Jupyter integration.

Just for the interested reader: `xeus` could be a good candidate for Supercollider-Jupyter integration https://github.com/jupyter-xeus/
The same team also provides many C++-HTML widgets for Jupyter, including controls and a simple audio playback: [`xwidgets`](https://github.com/jupyter-xeus/xwidgets)

**Comment by telephon** [comment]
The simplest solution might be to use a QT rich text view in the IDE.
