### ISSUE TITLE
sc3plugins API version mismatch in fresh build

### ISSUE THREAD

**Issue by telephon** [supercollider/supercollider#3201]
After having built the sc3plugins and the developer branch of sclang, the plugins are no longer considered compatible. When starting the server, I get an error:

```
ERROR: API version mismatch: /Users/wanninger/Library/Application Support/SuperCollider/Extensions/SC3plugins/TagSystemUGens/TagSystemUgens.scx
    This plugin is not compatible with SuperCollider >=3.9.0
    The plugin has not been loaded; please find or compile a newer version.
    Releases of sc3-plugins can be downloaded from https://github.com/supercollider/sc3-plugins/releases
    (Plugin's API version: 2. Expected: 3)
```

The error message is incorrect in so far as this in fact *is* the newest version of the plugins.

**Comment by brianlheim** [comment]
You're on the develop branch, not a release branch... what did you expect? We are planning to release a new version of sc3-plugins at the same time as SuperCollider 3.9.

**Comment by brianlheim** [comment]
You can certainly recompile sc3-plugins yourself with the updated headers if you need working versions. But it would not make sense to release a new version of sc3-plugins before SuperCollider proper has been released.

**Comment by telephon** [comment]
I know that we are planning a new version of sc3-plugins. But the developer branch should be fully functional. So we need to keep the plugins in sync with supercollider. In other words, we need a developer branch for sc3plugins that works with the developer branch of supercollider.

**Comment by brianlheim** [comment]
What is out of sync or not functional about this? The current master branch of sc3-plugins _does_ work with the developer branch of SuperCollider, just compile it yourself.

**Comment by telephon** [comment]
No, it doesn't here - that's the motivation of this issue.

**Comment by telephon** [comment]
I see, when I copy by hand the sc3plugin build over, then it suddenly works. I always had them linked. Did anything change in the filesystem?

**Comment by telephon** [comment]
@brianlheim btw. just in terms of procedure, might it be better to leave an issue open until at least the author of the issue has had a chance to reply and maybe close it? I would have closed this myself.

**Comment by brianlheim** [comment]
yeah, that is a fine idea. :) sorry i closed it early.
