### ISSUE TITLE
linking SC 3.8.0 against boost 1.63 on debian

### ISSUE THREAD

**Issue by danstowell** [supercollider/supercollider#3203]
Hi - I'm trying to import SC 3.8.0 into debian. One thing that's a bit complex is that on debian we re-patch the source code to use system boost and NOT the bundled boost that comes with SC. (This is because of debian packaging policies.) So I've got boost 1.63 on my machine here and when I compile SC I hit this problem:

<pre>
[ 70%] Linking CXX executable sclang
cd /home/dan/dev/multimedia_team/buildarea/supercollider-3.8.0/obj-i686-linux-gnu/lang && /usr/bin/cmake -E cmake_link_script CMakeFiles/sclang.dir/link.txt --verbose=1
/usr/bin/g++  -g -O2 -fdebug-prefix-map=/home/dan/dev/multimedia_team/buildarea/supercollider-3.8.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2   -msse -msse -mfpmath=sse -msse2 -O2 -g -DNDEBUG  -Wl,-z,relro -rdynamic CMakeFiles/sclang.dir/LangSource/cmdLineFuncs.cpp.o  -o sclang -lboost_regex libsclang.a -lpthread /usr/lib/i386-linux-gnu/libQt5WebKitWidgets.so.5.9.1 /usr/lib/i386-linux-gnu/libQt5WebKit.so.5.9.1 /usr/lib/i386-linux-gnu/libQt5PrintSupport.so.5.9.1 /usr/lib/i386-linux-gnu/libQt5OpenGL.so.5.9.1 /usr/lib/i386-linux-gnu/libQt5Widgets.so.5.9.1 /usr/lib/i386-linux-gnu/libQt5Sensors.so.5.9.1 /usr/lib/i386-linux-gnu/libQt5Quick.so.5.9.1 /usr/lib/i386-linux-gnu/libQt5Gui.so.5.9.1 /usr/lib/i386-linux-gnu/libQt5Qml.so.5.9.1 /usr/lib/i386-linux-gnu/libQt5Network.so.5.9.1 /usr/lib/i386-linux-gnu/libQt5Sql.so.5.9.1 /usr/lib/i386-linux-gnu/libQt5Positioning.so.5.9.1 /usr/lib/i386-linux-gnu/libQt5Core.so.5.9.1 -lX11 ../external_libraries/hidapi/linux/libhidapi.a -ludev ../external_libraries/hidapi/hidapi_parser/libhidapi_parser.a -lboost_thread -lboost_regex -lboost_filesystem ../server/scsynth/libscsynth.so.1.0.0 ../external_libraries/libtlsf.a -ldl -lavahi-common -lavahi-client -ljack -lboost_system -lfftw3f -lreadline -lasound -lsndfile -lrt ../external_libraries/libyaml.a 
libsclang.a(PyrStringPrim.cpp.o): In function `boost::cpp_regex_traits<char>::transform_primary(char const*, char const*) const':
/usr/include/boost/regex/v4/cpp_regex_traits.hpp:966: undefined reference to `boost::re_detail_106300::cpp_regex_traits_implementation<char>::transform_primary(char const*, char const*) const'
libsclang.a(PyrStringPrim.cpp.o): In function `boost::cpp_regex_traits<char>::transform(char const*, char const*) const':
/usr/include/boost/regex/v4/cpp_regex_traits.hpp:962: undefined reference to `boost::re_detail_106300::cpp_regex_traits_implementation<char>::transform(char const*, char const*) const'
collect2: error: ld returned 1 exit status
lang/CMakeFiles/sclang.dir/build.make:131: recipe for target 'lang/sclang' failed
make[3]: *** [lang/sclang] Error 1
make[3]: Leaving directory '/home/dan/dev/multimedia_team/buildarea/supercollider-3.8.0/obj-i686-linux-gnu'
CMakeFiles/Makefile2:3486: recipe for target 'lang/CMakeFiles/sclang.dir/all' failed
make[2]: *** [lang/CMakeFiles/sclang.dir/all] Error 2
make[2]: Leaving directory '/home/dan/dev/multimedia_team/buildarea/supercollider-3.8.0/obj-i686-linux-gnu'
Makefile:165: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/dan/dev/multimedia_team/buildarea/supercollider-3.8.0/obj-i686-linux-gnu'
</pre>

It's not easy for you to reproduce this particular situation, but does anyone have a clue about what is causing it and how it might be addressed? Perhaps you've seen it in previous situations and patched up your boost lib somehow.

(The machine is running Debian Wheezy on x86_64. gcc is 5.3.1)

**Comment by brianlheim** [comment]
I found a similar bug report here: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=823978

It seems very suspicious, and I don't have a good idea for how to solve it. It sounds like trying again with gcc >= 6 is worth a shot.

**Comment by brianlheim** [comment]
I think without too much effort we could switch over to std::regex. Not sure what that would mean for support on older compilers though.

**Comment by danstowell** [comment]
Thanks, good find, and good suggestion to try other GCC versions. It didn't help in my case: GCC 6 gave an internal compiler error, and GCC 7 errors out complaining about "cannot convert" some type mismatch (presumably it's being stricter than prev, and the SC codebase may need updating for forward-compatibility?).

Not sure which direction to go to try and resolve this. Given that SC uses patched boost, one could argue for using that - though if there's a patch for boost it should be spread more widely than just SC, surely. Will ask debian maintainers.

**Comment by danstowell** [comment]
Those patches that SC applies to boost - do you have any backstory on them? In particular: have they been upstreamed i.e. submitted to "official" boost? If not, is there a reason? Would you be in favour of the patches being submitted to official boost, and also perhaps as patches for debian's own version of boost? (I don't know boost's dev procedures at all.)

**Comment by brianlheim** [comment]
> GCC 6 gave an internal compiler error

Oh right, forgot about that.

> GCC 7 errors out complaining about "cannot convert" some type mismatch (presumably it's being stricter than prev, and the SC codebase may need updating for forward-compatibility?).

Idk, if you post the errors I can have a look. I would happily put time toward fixing that.

> Those patches that SC applies to boost - do you have any backstory on them?

No, I just found all the changes we've applied and kept track of them because that was requested by other maintainers. One fixes the ICE and iirc most of the others are marking methods inline.

> Would you be in favour of the patches being submitted to official boost, and also perhaps as patches for debian's own version of boost?

Yes for the ICE fix.

> (I don't know boost's dev procedures at all.)

I haven't contributed to Boost before; your guess is as good as mine!

**Comment by danstowell** [comment]
>> GCC 7 errors out complaining about "cannot convert" some type mismatch (presumably it's being stricter than prev, and the SC codebase may need updating for forward-compatibility?).
>
> Idk, if you post the errors I can have a look. I would happily put time toward fixing that.

Here: http://paste.debian.net/987665 - though it's unlikely to be the only error, if indeed it's because of general compiler strictness

**Comment by brianlheim** [comment]
oh, that looks like that error we had awhile ago with gcc7 on fedora. iirc it's because std::bind is only in the <functional> header now, so if you #include it at the top of that TU it might work.

**Comment by brianlheim** [comment]
only in the *functional header now (github ate my angle brackets)

**Comment by miguel-negrao** [comment]
In debian stretch the boost source package is at version [1.62.0.1](https://packages.debian.org/source/stretch/boost-defaults) and the [changelog](http://metadata.ftp-master.debian.org/changelogs/main/b/boost-defaults/boost-defaults_1.62.0.1_changelog) for that package mentions:

>  boost-defaults (1.58.0.1) unstable; urgency=medium
> 
>   * Set default to 1.58.0 with C++'11 ABI. (Closes: #783002, #773111)
>   * Add dependencies to ensure C++'11 ABI capable tool chain is pulled. (Closes: #790351)

Also, ticket [790351](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=790351) was "boost: should be rebuilt using gcc5 to export c++11 symbols". So maybe in debian stretch it is already using the version compiled with the c++'11 ABI ?

@danstowell  I suppose you trying to get SC into the next version of debian (buster) ? Since you are running wheezy could it be that you still have a version of boost compiled with c++'03 ABI and that is causing problems ? Just a wild guess, have no idea if that's the case.

**Comment by danstowell** [comment]
Thanks all of you for your useful comments :)

The error I pasted in reply to Brian is indeed caused by "functional" (as [confirmed](http://lists.alioth.debian.org/pipermail/pkg-multimedia-maintainers/2017-September/060622.html) via the debian multimedia maintainers mailing list).

Having patched that I'm back to thornier problems such as "internal compiler error" and the issue with which I started this thread, both of which might be fixable by upgrading debian. I will upgrade my debian and try again, and I'll come back and reopen this if it remains stuck.

**Comment by danstowell** [comment]
Thanks all of you for your useful comments :)

The error I pasted in reply to Brian is indeed caused by "functional" (as [confirmed](http://lists.alioth.debian.org/pipermail/pkg-multimedia-maintainers/2017-September/060622.html) via the debian multimedia maintainers mailing list).

Having patched that I'm back to thornier problems such as "internal compiler error" and the issue with which I started this thread, both of which might be fixable by upgrading debian. I will upgrade my debian and try again, and I'll come back and reopen this if it remains stuck.

**Comment by Sciss** [comment]
I had no problem with boost on Debian Stretch for 3.8.0 (I had to remove supernova from the build through):

    sudo apt install build-essential libjack-jackd2-dev libsndfile1-dev libasound2-dev libavahi-client-dev libicu-dev libreadline6-dev libfftw3-dev libxt-dev libudev-dev pkg-config cmake qt5-default qt5-qmake qttools5-dev qttools5-dev-tools qtdeclarative5-dev libqt5webkit5-dev qtpositioning5-dev libqt5sensors5-dev libqt5opengl5-dev

    cmake -DSC_WII=no -DSC_EL=no -DSUPERNOVA=no -DCMAKE_BUILD_TYPE="Release" ..

**Comment by danstowell** [comment]
HH - thanks. I imagine that's using bundled boost? Also, did you have to remove supernova *because* of build problems such as these?

**Comment by miguel-negrao** [comment]
@danstowell I'm running stretch, and I've cloned the git repository from debian-multimedia. If you tell me what commands I should issue, I can try to build in my system. Are you using gbp to build ?

**Comment by danstowell** [comment]
@miguel-negrao yes, basically I run

           gbp buildpackage --git-export-dir=../buildarea

I'm drafting a blog with notes of how we maintain this debian stuff, which has more detail. I can send it you if you'd like to have a peep.

**Comment by miguel-negrao** [comment]
@danstowell  Yes, I would be interested in learning a bit more about debian packaging, please send it to me. I tried running that command from master but [it fails](https://pastebin.com/m0pHV2CT). Maybe I'm not in the right branch ? I think it's still using the old source from 3.7 ?

**Comment by danstowell** [comment]
oh damn I need to push sth. ok will email

**Comment by danstowell** [comment]
OK, now I've done a big update of many packages on my machine, and I have a successful build! Hurrah!

My build succeeded as of commit 79d7a5320, plus a local commit in which I ensured it was using GCC 6.

**Comment by brianlheim** [comment]
@danstowell That's great news! Thanks for doing that.

Is that the correct commit hash? Github isn't forming a link for it, which it usually does.

**Comment by danstowell** [comment]
Yes, the commit in debian's git, not SC's git.

(My built SC is not yet running correctly, ahem. Story continues)

**Comment by snappizz** [comment]
@danstowell i had no idea you were working on this -- i'm currently working with @edmondhowser on packaging 3.9. if you could share what you know so far, we could avoid duplicating work.

**Comment by danstowell** [comment]
@snappizz the debian packaging of 3.8.0 is now basically done. It's in [debian multimedia's git repo](https://anonscm.debian.org/cgit/pkg-multimedia/supercollider.git), via the same process as all the debian releases for the past few years. I've some draft notes which I'll publish once I'm back from travelling, approx 4 weeks from now.

not sure what you mean by "working on packaging" - FWIW definitely best to work with the debian multimedia team on this, it's a good way to get a solid version into debian as well as ubuntu

**Comment by danstowell** [comment]
Hi all - FWIW I finally published my blog about Debian SuperCollider packaging:
http://mcld.co.uk/blog/2017/how-to-package-supercollider-for-debian-and-ubuntu-linux.html
