### ISSUE TITLE
branch for pull requests: develop?

### ISSUE THREAD

**Issue by dyfer** [supercollider/supercollider#3205]
Hello,
I'm getting ready to make some contribution and I just wanted to ask about the branches...
Base on the [discussion on the dev list](http://new-supercollider-mailing-lists-forums-use-these.2681727.n2.nabble.com/supercollider-releases-td7635002i20.html) the topic/issue branch should now be created from develop branch, instead of master, but [contributing instructions](https://github.com/supercollider/supercollider.github.io/blob/master/contributing/index.md ) don't indicate that.
Is this correct, I mean should new pull requests be branched from and pulled into the develop branch? If so we should probably include that in the contributing manual.

**Comment by telephon** [comment]
If I understand this correctly, "master" is now "develop", so it makes no difference as such. Indeed you should branch from develop.

**Comment by dyfer** [comment]
But master is still around and hasn't been updated since Sept 20... so whatever the master's status is, we should update contributing instructions accordingly to point to develop, isn't that right?

**Comment by jamshark70** [comment]
Master won't be removed. It's now the stable branch.

Yes, the contributor guidelines should be updated.

**Comment by patrickdupuis** [comment]
I believe this documentation is up-to-date :
https://github.com/supercollider/supercollider/wiki/git-workflow-and-guidelines

**Comment by dyfer** [comment]
I made the changes to reflect this: #3208. Please take a look when you have a chance. Thanks!

**Comment by brianlheim** [comment]
closed by #3208
