### ISSUE TITLE
.openOS behaviours

### ISSUE THREAD

**Issue by prko** [supercollider/supercollider#3222]
Bug description:
".".openOS
"~".openOS

Steps to reproduce:
1. type the following lines in SC-IDE:
".".openOS;
"~".openOS;
2. evaluate the lines.

Actual result:
".".openOS;
- Under Windows, "File Explorer" shows the folder where SuperCollider is installed.
- Under macOS, "Finder" shows the root folder where macOS is installed.

"~".openOS;
- Under Windows, "File Explorer" shows the following error message:
> Windows cannot find '~'. Make sure you've typed the name correctly, then try again.
- Under macOS, "Finder" shows the user's home folder.

Expected result:
It will be fine if the same codes show the same results in Windows and macOS.

**Comment by muellmusik** [comment]
Correct me if I'm wrong, but ~ does not work as a shortcut to home on Windows? (I believe you can use %HOMEPATH% or something like that)

If that's true than it does show the 'same' results, i.e. it opened the indicated path. Duplicating nixy path stuff on Windows would seem like a can of worms...

**Comment by muellmusik** [comment]
Closing for now. Reopen if needed.

**Comment by jamshark70** [comment]
To clarify:

> ".".openOS;

"." refers to the current working directory of the sclang process, *not* to the current document's folder. IDE preferences have a setting for the language process working directory. The default may be different for different systems.

Because the working directory can be set by the user, you can't count on it pointing to a specific location. In general, don't use it this way.

What information did you mean to get this way?

> "~".openOS

It's a reasonable request, for the Windows primitive to translate the tilde. Maybe a can of worms, but the current situation is a bit awkward.

**Comment by muellmusik** [comment]
> It's a reasonable request, for the Windows primitive to translate the tilde. Maybe a can of worms, but the current situation is a bit awkward.

I really think it's not. If you start doing this you will mangle paths on any platform in which tilde is valid in paths, but is not a shortcut for home. I'm not a Windows user, but AFAICS it looks like ~ in fact has a _different_ meaning there, so even worse.

I think we'd be better off abstracting this into a clearly defined separate method, i.e. openHomeDir or resolveToHomeDir which hides the platform specific stuff.

**Comment by jamshark70** [comment]
> I really think it's not. If you start doing this you will mangle paths on any platform in which tilde is valid in paths, but is not a shortcut for home. I'm not a Windows user, but AFAICS it looks like ~ in fact has a different meaning there, so even worse.

Ok, that's fair.

Funny how we don't have documentation about paths, since it doesn't fit neatly into the scheme of method documentation... but I repeat myself.

**Comment by brianlheim** [comment]
FWIW - `pathMatch` aka globbing will treat ~ as home on both Windows and POSIX-systems. It expands to $HOME iff `~` is either (1) the only character in the string or (2) the first element in a path. So `~/My Documents` expands, but not `~001.tmp`.

**Comment by brianlheim** [comment]
standardizePath will behave the same way. So @prko, if you really want: 

```supercollider
"~".standardizePath.openOS
```

**Comment by brianlheim** [comment]
The `standardizePath` behavior is documented; `pathMatch` just says "wildcards apply". I should have updated that with my big PR awhile ago, but I forgot.
