### ISSUE TITLE
Default groups should be running in a ParGroup optionally

### ISSUE THREAD

**Issue by vivid-synth** [supercollider/supercollider#3230]
Now that we've got one default group per client in a multi-client setup (https://github.com/supercollider/supercollider/pull/3180), should we switch the groups to Parallel Groups? It would get us a free huge speedup in some cases, at (I believe) no cost.

Specifically, I'm proposing changing the 3 `g_new`s in https://github.com/supercollider/supercollider/pull/3180/files to `p_new`

**Comment by telephon** [comment]
interesting idea. we'd need to carefully check the constraints, especially with respect to shared resources

**Comment by vivid-synth** [comment]
@telephon are there examples of things we'd need to check with `p_new` that we don't have to check with `g_new`? E.g. I can imagine we want to be careful about reading from and writing to Control Buses, but we want to be careful about that even with `g_new`, right?

**Comment by muellmusik** [comment]
AFAIK the cost would be that you can’t have any order dependency. ParGroups don’t do any dependency stuff so synths could run in the wrong order. So not a good idea to force that.

**Comment by jamshark70** [comment]
Scott is correct. Users may now assume:

- If I place nodes into my default group in a specific order, I can rely on them running in that order.

- And if I place nodes before or after my default group (e.g. monitoring synths), they will run in order.

The first is broken if you use `p_new` to create my group.

It *might* be feasible to create a container group using `p_new` and put clients' default groups (`g_new`) into that, but it means the second usage would be invalid. That may or may not be an acceptable sacrifice.

A parallel group doesn't mean that it executes in parallel relative to other nodes in the group containing it (which is what seems to be assumed, for the idea of creating client groups as parallel). That isn't what it means. Rather, it's that the parallel group's immediate children may evaluate on different CPU cores -- therefore, if the children are A, B, C in that order, you have no guarantee that A will finish before B and B before C. A and B may run in parallel and B may finish first.

Parallel groups are emphatically not appropriate for users' default groups.

**Comment by jamshark70** [comment]
Well, it would be "OK" for scsynth only because ParGroups evaluate the same as Groups in scsynth... but then, the user will take code over to supernova and it will suddenly not work.

If the user's default group is parallel, then something basic like this will fail in supernova:

```
~globalReverb = { |wet = 0.4|
	var sig = In.ar(0, 2);
	FreeVerb2.ar(sig[0], sig[1], wet, 0.8)
}.play(s.defaultGroup, outbus: 0, addAction: \addToTail);

~src = {
	var sig = SinOsc.ar(220, 0, 0.1),
	eg = EnvGen.kr(Env.perc(0.01, 0.1), Impulse.kr(1));
	(sig * eg).dup
}.play(s.defaultGroup, 0, addAction: \addToHead);
```

`s.defaultGroup` *must* be a normal group, or, chaos.

I'll go ahead and close this for that reason.

**Comment by telephon** [comment]
Ah right, I forgot how pargroups work. The idea that I found at least worth considering is making the group in which the defaultgroups live a pargroup. This would mean that on supernova you could process each client like a separate server. 

The downside is that you then can't share resources. But wherever *all* allocators are local to each client anyhow, then this might be worth an option.

So, optionally, one would have the following structure:

```
NODE TREE Group 0 group
   1003 pargroup
      1006 group
      1005 group
      1004 group

```

**Comment by jamshark70** [comment]
Do be careful about metering synths, which go at the head and tail of the server's RootNode:

NODE TREE Group 0
   1000 localhostInputLevels
   1 group
   1001 localhostOutputLevels

Also, I think it might be polite to create the "client-container" only when the second client registers. The overwhelming majority of usage will still be single-client. I'm not sure we need to add one more layer of grouping for everybody, when it will remain a relatively rare case.

I'm not opposed to a parallel group (in principle, different clients' synths shouldn't be talking to each other), but it's going to be important, I think, to draw up a thorough spec. It *might* work to dump every user's meter/scope/freqscope synths into the RootNode, but if it doesn't?

**Comment by telephon** [comment]
>Do be careful about metering synths, which go at the head and tail of the server's RootNode:

the metering synths would go before and after the pargroup then.

>Also, I think it might be polite to create the "client-container" only when the second client registers.

Yes. Also I think this kind of scheme would certainly need to be optional, because in general, people would expect to be able to share resources between their synths (in the "tandem-mode").

> It might work to dump every user's meter/scope/freqscope synths into the RootNode, but if it doesn't?

You are right that this is to be checked really carefully. But in that example, I don't see why it should fail.

**Comment by vivid-synth** [comment]
> A parallel group doesn't mean that it executes in parallel relative to other nodes in the group containing it (which is what seems to be assumed, for the idea of creating client groups as parallel). Rather, it's that the parallel group's immediate children may evaluate simultaneously on different CPU cores -- therefore, if the children are A, B, C in that order, you have no guarantee that A will finish before B and B before C. A and B may run in parallel and B may finish first. If B needs to read A's output, it will be unreliable.

@jamshark70 you're exactly right -- I had this backwards, in the way that you guessed. Apologies! I still find the solutions @telephon is proposing quite tempting: e.g. 4 performers on one 4-core machine could see performance similar to if they were all on their own separate machines, without having to do much of anything in the way of setup.

**Comment by sonoro1234** [comment]
https://github.com/supercollider/supercollider/issues/3568#issuecomment-377271515

**Comment by jamshark70** [comment]
I'm surprised this is still open.

It's extremely risky to thrust ParGroups upon users without being very careful and clear about the scope. I believe the risks have been underestimated in some of the discussion above.

Specifics, please.

**Comment by sonoro1234** [comment]
```
ParGroup
      Group
          Instrument
          channel
          send
      Group
          ParGroup
               Instrument
               Instrument
          channel
          send

```
Each parGroup parallelizes (Both first level Groups and in the second group several parallelized instruments). 
Group keeps sons sequenced:
1- First Group: Instrument, channel, sends.
2-second  Group sequences parGroup (with Instrument sons pararelized) channel, sends.

I am using this setting now (in Lua2SC) and it works without problems.

**Comment by jamshark70** [comment]
Yes, of course that will work without problems. But the enhancement request is to use ParGroups for... something... by default, under... some... circumstances, and not break features. So @sonoro1234 's comment is interesting for presenting a design that works well for a specific use case (and I've done something similar in some compositions myself) -- but it isn't directly relevant to the question at hand.

To demonstrate what I mean by being specific -- here's one possible way of handling it. There's a big problem with this approach. But I think alternate approaches need to be described in at least this much detail, or I'm quite sure there will be nasty surprises later.

- Node 0 is a normal group. (If node 0 is a parallel group, then it becomes impossible to ensure order of execution at the topmost level. That sounds dangerous to me.)

- Within node 0 could be a parallel container group (maybe node 1).

- Within the container, each clientID would get two nested groups, as follows:
  - A "clientID" group (normal group), analogous to the current single-user node 0.
    - The specific client's default group, analogous to the current single-user node 1.

Synths for the level meter, frequency scope etc. are all normal node IDs -- they should apply the clientID mask and be "local" to the client. In principle, then, they should belong to the client's group and not be tacked onto the global root node.

So you might end up with arrangements such as the following (groups in italics):

- *Root node 0*
  - *Container (parallel group 1)*
    - *Client ID 0's root node*
      - localhostInputLevels
      - *Client ID 0's default group*
      - localhostOutputLevels
      - system_freqScope1_shm
    - *Client ID 1's root node*
      - *Client ID 1's default group*

The problem with this is that the clientID concept currently supports localized group structures, but not localized access to the hardware I/O busses (particularly output). We don't have a way for client 0's level meter to look only at client 0's signals. If we wanted to do it properly, then each client should have proxy HW I/O busses that are automatically routed to the main I/Os, and metering would read the proxy output levels.

Without solving that design flaw (and that would be a difficult, invasive change -- hard to justify even though it's technically correct and would be better than what we have now), then, it might be better to put all metering synths in "true" node 0, before/after the container parallel group. Then you *might* be able to simplify a little:

- *Root node 0*
  - localhostInputLevels
  - *Container (parallel group 1)*
    - *Client ID 0's default group*
    - *Client ID 1's default group*
  - localhostOutputLevels

I would be opposed to any proposal that replaces clients' default groups with parallel groups. Clients must be able to assume ordering within their default groups.

**Comment by sonoro1234** [comment]
Yes, I was skipping Root node 0 with Vumenters and so on in my explanation. Sorry.

**Comment by dyfer** [comment]
Reading through this issue I think we should close it, as it was pointed out that such default setting would have adverse side effects.

**Comment by brianlheim** [comment]
Agreed
