### ISSUE TITLE
libscsynth: regression on master

### ISSUE THREAD

**Issue by hlolli** [supercollider/supercollider#3234]
Hey SC people, I'm developing Overtone which uses libscsynth. I'll skip the drama theater of how long it took me to realize this was a regression but not wrong paths to plugins.

So if I compile SC from commit done in june via `git checkout 765236af2f0d9f58094147ae88b1770f27e80b92` everything works. Now the bug:

```
exception in GraphDef_Recv: UGen 'Control' not installed.
exception in GraphDef_Recv: UGen 'Control' not installed.
exception in GraphDef_Recv: UGen 'Control' not installed.
```
this repeats many times plus some warnings (but I think these are more harmless).
```
*** ERROR: API Version Mismatch: ./native/linux/plugins/DemandUGens.so
*** ERROR: API Version Mismatch: ./native/linux/plugins/ML_UGens.so
*** ERROR: API Version Mismatch: ./native/linux/plugins/DelayUGens.so
*** ERROR: API Version Mismatch: ./native/linux/plugins/GrainUGens.so
*** ERROR: API Version Mismatch: ./native/linux/plugins/PanUGens.so
...etc..
```
I will compile libscsynth from this older hash for now, but I thought it would make sense to report this.

**Comment by joshpar** [comment]
This actually isn’t a bug. The API interface has a version change, so plugins will need to be recompiled as well, including sc3-plugins. When the 3.9 release happens, all should be in sync. If you are compiling from master, you will need to do a full recompile.

Best,

Josh

**Comment by patrickdupuis** [comment]
Also, I would recommend you compile the 3.9 branch and not master. Development is happening in the 3.9 branch, and we are nearing a beta release. The 3.9 branch will be merged into master after release.


Cheers,

Patrick


________________________________

**Comment by hlolli** [comment]
@joshpar I actually fully recompile this is my bash script
```
	echo "Fetch submodules"
	git submodule init && git submodule update
	cd supercollider
	git submodule init && git submodule update
	cd ../sc3-plugins/
	git submodule init && git submodule update
	cd ../target
	rm -rf scmake scmake-extras
	mkdir scmake scmake-extras
	cd scmake
	cmake ../../supercollider -DSUPERNOVA:BOOL=OFF -DLIBSCSYNTH:BOOL=ON
	make -j6
	cd ../scmake-extras
	cmake ../../sc3-plugins -DSC_PATH=../../supercollider
	make -j6
	cd ../../native
	rm -rf linux
	mkdir linux linux/plugins linux/scsynth
	cd linux
	echo "Copy artifacts to native/linux"
	cp ../../target/scmake/server/scsynth/*.so* ./scsynth
	cp ../../target/scmake/server/plugins/*.so ./plugins
	cp ../../target/scmake-extras/source/*.so ./plugins
	cp ../../target/scmake-extras/source/StkInst/*.so ./plugins
	echo "Finish"
```
this is for linux library files.

But ok, I'll keep my eyes open for when the merge takes place, can also just give the develop branch a try too. Thanks for these pointers.
