### ISSUE TITLE
SuperDirt quark not found on SuperCollider 3.8

### ISSUE THREAD

**Issue by Darkinferno13** [supercollider/supercollider#3236]
include("SuperDirt") should work as far as my research as shown me, but instead I get the following error:

RECEIVER: SuperDirt
	SVN not found! Quarks placed in the directory

		/home/ben/.local/share/SuperCollider/quarks

	will be available, but you need svn to checkout updated versions.

	svn can be downloaded from:

		http://subversion.tigris.org/project_packages.html
SuperDirt  not found in local quarks; checking out from remote ...
ERROR: Quark not found in repository.
CALL STACK:
	Exception:reportError   0x4bb2908
		arg this = <instance of Error>
	Nil:handleError   0x46f41a8
		arg this = nil
		arg error = <instance of Error>
	Thread:handleError   0x46c0738
		arg this = <instance of Thread>
		arg error = <instance of Error>
	Object:throw   0x4bb8508
		arg this = <instance of Error>
	Quarks:checkout   0x59292f8
		arg this = <instance of Quarks>
		arg name = "SuperDirt"
		arg version = nil
		arg sync = true
		var q = nil
	Quarks:install   0x59298e8
		arg this = <instance of Quarks>
		arg name = "SuperDirt"
		arg includeDependencies = true
		arg checkoutIfNeeded = true
		var q = nil
		var deps = nil
		var installed = nil
		var dirname = nil
		var quarksForDep = nil
	Meta_Quarks:install   0x5929a18
		arg this = <instance of Meta_Quarks>
		arg name = "SuperDirt"
		arg includeDependencies = true
		arg checkoutIfNeeded = true
	String:include   0x462d808
		arg this = "SuperDirt"
	Interpreter:interpretPrintCmdLine   0x592abe8
		arg this = <instance of Interpreter>
		var res = nil
		var func = <instance of Function>
		var code = "include("SuperDirt")"
		var doc = nil
		var ideClass = <instance of Meta_ScIDE>
	Process:interpretPrintCmdLine   0x45b1088
		arg this = <instance of Main>
^^ The preceding error dump is for ERROR: Quark not found in repository.
SuperDirt  not found in local quarks; checking out from remote ...
ERROR: Quark not found in repository.

Any ideas why this may be happening? I followed the installation processes to the letter.

**Comment by telephon** [comment]
In 3.8, no quark should really be looking for svn. All should be git.

Can you try to check it out directly? 

`Quarks.install("https://github.com/musikinformatik/SuperDirt")`

**Comment by Darkinferno13** [comment]
No, seems to be bringing up a similar output:

init_OSC
empty
compiling class library...
	NumPrimitives = 679
	compiling dir: '/usr/share/SuperCollider/SCClassLibrary'
	compiling dir: '/usr/share/SuperCollider/Extensions'
	pass 1 done
	numentries = 1177793 / 18231720 = 0.065
	5655 method selectors, 3224 classes
	method table size 18386616 bytes, big table size 145853760
	Number of Symbols 14569
	Byte Code Size 466693
	compiled 462 files in 1.15 seconds
compile done
Couldn't set realtime scheduling priority 1: Operation not permitted
Help tree read from cache in 0.063904047012329 seconds
LID: event loop started
Class tree inited in 0.12 seconds
Welcome to SuperCollider 3.6.6. For help press Ctrl-D.
Couldn't set realtime scheduling priority 1: Operation not permitted
SCDoc: Indexing help-files...
SCDoc: Indexing old helpfiles...
Help files scanned in 0.14275693893433 seconds
SCDoc: Indexed 2130 documents in 2.29 seconds
	SVN not found! Quarks placed in the directory

		/home/ben/.local/share/SuperCollider/quarks

	will be available, but you need svn to checkout updated versions.

	svn can be downloaded from:

		http://subversion.tigris.org/project_packages.html
https://github.com/musikinformatik/SuperDirt  not found in local quarks; checking out from remote ...
ERROR: Quark not found in repository.
CALL STACK:
	Exception:reportError   0x304a8c8
		arg this = <instance of Error>
	Nil:handleError   0x30985c8
		arg this = nil
		arg error = <instance of Error>
	Thread:handleError   0x305c8f8
		arg this = <instance of Thread>
		arg error = <instance of Error>
	Object:throw   0x3091498
		arg this = <instance of Error>
	Quarks:checkout   0x440ae28
		arg this = <instance of Quarks>
		arg name = "https://github.com/musikinfo..."
		arg version = nil
		arg sync = true
		var q = nil
	Quarks:install   0x440b548
		arg this = <instance of Quarks>
		arg name = "https://github.com/musikinfo..."
		arg includeDependencies = true
		arg checkoutIfNeeded = true
		var q = nil
		var deps = nil
		var installed = nil
		var dirname = nil
		var quarksForDep = nil
	Meta_Quarks:install   0x440c4b8
		arg this = <instance of Meta_Quarks>
		arg name = "https://github.com/musikinfo..."
		arg includeDependencies = true
		arg checkoutIfNeeded = true
	Interpreter:interpretPrintCmdLine   0x440c718
		arg this = <instance of Interpreter>
		var res = nil
		var func = <instance of Function>
		var code = "Quarks.install("https://gith..."
		var doc = nil
		var ideClass = <instance of Meta_ScIDE>
	Process:interpretPrintCmdLine   0x33633f8
		arg this = <instance of Main>
^^ The preceding error dump is for ERROR: Quark not found in repository.

(This includes the startup logs in case they have any info).

**Comment by telephon** [comment]
I don't know what is wrong, maybe someone else has seen this before.

As a quick fix, you can just copy the SuperDirt folder into your supercollider extensions folder.

**Comment by jamshark70** [comment]
I checked the Quarks code: all except for QuarksGui.sc here: https://github.com/supercollider/supercollider/tree/3.8/SCClassLibrary/Common/Quarks

There is no posting of any message related to SVN anywhere in the quarks code for 3.8.

Possible explanations:

- It's not really 3.8.

- Or, it's 3.8 but it's using older quarks code (not from 3.8).

- Or there is some extension overwriting the proper quarks implementation.

The posted error text about svn is certainly not coming from 3.8, in any case.

**Comment by jamshark70** [comment]
Also, this method `Quarks:checkout` is in the call stack, but it doesn't exist anymore.

Not a 3.8 issue. Something is wrong with the installation or the environment.

**Comment by Darkinferno13** [comment]
@jamshark70  and @telephon yes, you're correct, it doesn't seem to be a 3.8 issue...... I read over the log again and noticed the following line
`Welcome to SuperCollider 3.6.6`
it seems that the installation process has installed a version of SuperCollider that is rather outdated, and running `sudo apt-get upgrade supercollider` returns that it is already at the most recent version... I'll see what I can do by way of getting the proper latest version and try again.

**Comment by jamshark70** [comment]
In the absence of feedback, and considering that the startup text posted above says "Welcome to SuperCollider 3.6.6," I think I'll close this with the recommendation to upgrade. Feel free to reopen if you encounter issues installing SuperDirt in 3.8.

**Comment by telephon** [comment]
yes, the debian packaging is still to be figured out. The version on debian is really outdated.

**Comment by Darkinferno13** [comment]
@telephon ah, that's alright then. Thanks for trying to help and I'll see what I can do by way of getting it to do something (might use my Windows laptop instead).

**Comment by telephon** [comment]
probably the best is to use debain and compile it yourself, most people do that.

**Comment by jamshark70** [comment]
FWIW (and, at the risk of dragging out the thread), building it is actually quite easy in up-to-date debian/ubuntu systems, like:

```
sudo apt-get install build-essential libjack-dev or libjack-jackd2-dev libsndfile1-dev libasound2-dev libavahi-client-dev libicu-dev libreadline6-dev libfftw3-dev libxt-dev libudev-dev pkg-config git cmake qt5-default qt5-qmake qttools5-dev qttools5-dev-tools qtdeclarative5-dev libqt5webkit5-dev qtpositioning5-dev libqt5sensors5-dev libqt5opengl5-dev

cd (sc source directory)
mkdir build
cd build
cmake .. -DSC_EL=OFF -DSC_ED=OFF -DSC_VIM=OFF
make
sudo make install
```

In the `cmake` line, you could save some time with `-DSUPERNOVA=OFF` if you're not going to use the multicore aware server. The apt package names are listed in README_LINUX.md.

I had to set up a new machine a bit more than a month ago, Ubuntu Studio 16.04. I might be misremembering a few details, but I pretty much did the above and was up and running in, like, 30 minutes. Building SC isn't hard in itself (but maybe hard to figure out if you never did it before) -- maybe why the packaging situation persisted so long.

**Comment by miguel-negrao** [comment]
> probably the best is to use debain and compile it yourself, most people do that.

While testing the 3.8 debian packages I created these packages from the debian git repo. Feel free to use them while the official ones don't arrive at the debian package system. [Link here.](https://48hzcloud.duckdns.org/index.php/s/socvRAPtsBT3mqx)

Use at your own risk obviously.

**Comment by miguel-negrao** [comment]
> probably the best is to use debain and compile it yourself, most people do that.

While testing the 3.8 debian packages I created them locally from the debian git repo. Feel free to [download](https://48hzcloud.duckdns.org/index.php/s/socvRAPtsBT3mqx/download), while the official packages are not available from debian. Use at your own risk, off course.

Packages can be installed and removed with dpkg:

install:
```
sudo dpkg -i libscsynth1_3.8.0-1_amd64.deb supercollider-common_3.8.0-1_all.deb supercollider-language_3.8.0-1_amd64.deb  supercollider-server_3.8.0-1_amd64.deb supercollider-ide_3.8.0-1_amd64.deb
```

remove:
    
    sudo dpkg -r supercollider-ide supercollider-language supercollider-server supercollider-common libscsynth1

**Comment by Darkinferno13** [comment]
@jamshark70 your method seemed to work well up to the cmake command, which returned 
`
CMake Error at external_libraries/CMakeLists.txt:2 (message):
  nova-simd submodule is missing: please run `git submodule init && git
  submodule update' from the toplevel of your git working tree
'
Where do I have to run the suggested commands from? I am not familiar enough with git to know, and attempting to make sense of the log has made me none the wiser.

**Comment by jamshark70** [comment]
Oh drat, I knew I forgot something.

The "top level" is the "source directory"... the directory containing the build/ folder that you mkdir'ed.

**Comment by Darkinferno13** [comment]
I ran it from the source directory, and it's still returning the following:

`-- SuperCollider Version: 3.9dev
-- Building from branch not_a_git_checkout, commit hash is na
-- Build type defaulting to "RelWithDebInfo"
-- Compiling with Qt GUI
-- building boost libraries manually
CMake Error at external_libraries/CMakeLists.txt:2 (message):
  nova-simd submodule is missing: please run `git submodule init && git
  submodule update' from the toplevel of your git working tree


-- Configuring incomplete, errors occurred!
See also "/home/ben/Documents/supercollider-develop/build/CMakeFiles/CMakeOutput.log".
`
There appears to be a file missing, any ideas why?

**Comment by brianlheim** [comment]
@Darkinferno13 

Run the commands in `/home/ben/Documents/supercollider-develop`.

If you get the same error again, try cleaning your build folder (i.e. deleting it) and starting from scratch.

**Comment by Darkinferno13** [comment]
@brianlheim I ran the commands in that directory, then tried re-doing from scratch and received the following output:

`-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- SuperCollider Version: 3.8.0
-- Building from branch not_a_git_checkout, commit hash is na
-- Build type defaulting to "RelWithDebInfo"
-- Compiling with Qt GUI
-- Found Pthreads: /usr/lib/x86_64-linux-gnu/libpthread.so  
-- building boost libraries manually
CMake Error at external_libraries/CMakeLists.txt:2 (message):
  nova-simd submodule is missing: please run `git submodule init && git
  submodule update' from the toplevel of your git working tree


-- Configuring incomplete, errors occurred!
See also "/home/ben/Documents/supercollider-3.8/build/CMakeFiles/CMakeOutput.log".
`
This still occurs after having deleted the entire source code file and downloading the 3.8 (and 3.9) branch rather than the development branch.

**Comment by jamshark70** [comment]
Then the git submodule commands are failing.

What is the output of those commands?

**Comment by Darkinferno13** [comment]
@jamshark70 there isn't one. It processes for a second and then moves on, there is nothing logged to the console nor any log file that I've been made aware of.
`
~/Documents/supercollider-3.9 $ git submodule init && git submodule update
 ~/Documents/supercollider-3.9 $
`
is the exact thing I see when I run the command as it is stated in the error, running them separately gives no different.

**Comment by brianlheim** [comment]
> Building from branch not_a_git_checkout, commit hash is na

this is a red flag to me. what exactly are you doing to get the source code? it looks like you didn't clone at all..

**Comment by Darkinferno13** [comment]
I got the .zip from the github page (Clone or download -> Download .zip) and extracted it, if cloning from the git link is what I was supposed to do then I apologize for wasting some time here and I'll get right on that and redo.

**Comment by brianlheim** [comment]
@Darkinferno13 could you please retry with cloning via git? It sounds like downloading the zip does not grab the submodules as well, so i'm not sure how you would solve that in your current situation other than by manually downloading those repositories as well and placing them in the correct directories, which is not really for the best because you'll have to repeat that process every time there is an update.

Since you don't actually have git initialized in that directory, it makes sense that git commands would fail. Glad we finally got to the bottom of it.

**Comment by Darkinferno13** [comment]
@brianlheim yes, that worked perfectly, many thanks to all of you! Now just to install sc3-plugins and check that the SuperDirt quark works properly.

**Comment by brianlheim** [comment]
glad to help :)

**Comment by jamshark70** [comment]
Should we add something to the main README advising users not to download the repository as a zip?

**Comment by brianlheim** [comment]
i think the current readme is already quite clear about using git, but i guess it couldn't hurt
