### ISSUE TITLE
exception in GraphDef_Recv: UGen 'Tartini' not installed.

### ISSUE THREAD

**Issue by jonathancoon** [supercollider/supercollider#3239]
None of the sc3-plugins are working. Getting an exception that they aren't installed, even though SuperCollider compiles both /Library/Application Support/SuperCollider/Extensions and ~/Library/Application Support/SuperCollider/Extensions. I have tried placing the sc3-plugins folder in each of those folders (not at the same time, as that causes a conflict error). I have tried using the plugins with SuperCollider 3.7.2, 3.8.0, and 3.9dev with no luck. I am running macOS Sierra 10.12.6.

**Comment by brianlheim** [comment]
Closing since there is a duplicate on sc3-plugins (https://github.com/supercollider/sc3-plugins/issues/163)
