### ISSUE TITLE
VSTLua

### ISSUE THREAD

**Issue by AlexFundorin** [supercollider/supercollider#3242]
Hi, Victor. Did you manage to find a decent substitute for VSTLua? I need a midi<>osc bridge that would sit in my DAW or in tray and would convert osc from DAW (Reaper) to midi controller (including feedback for LEDs and sysex for LCD). Couldn't find anything worth it for a couple of years, yet.

**Comment by brianlheim** [comment]
Hi @AlexFundorin,

It looks like this wasn't intended to be posted here. I'm going to close it for now, but if I'm wrong please feel free to reopen and describe the issue in more detail.
