### ISSUE TITLE
error loading plugins in supercollider (ubuntu)

### ISSUE THREAD

**Issue by DuvanArcos** [supercollider/supercollider#3243]
I followed this tutorial https://github.com/supercollider/supercollider/wiki/Installing-SuperCollider-on-Ubuntu-systems

and in the final step of making the plugins

"Finally, building the plugins

From within sc3-plugins/build, run the following:

make
sudo make install
sudo ldconfig
"
i get this error message:

[ 15%] Building CXX object source/CMakeFiles/OteyPianoUGens_supernova.dir/OteyPianoUGens/OteyPiano.cpp.o
In file included from /usr/include/SuperCollider/plugin_interface/SC_World.h:27:0,
                 from /usr/include/SuperCollider/plugin_interface/SC_PlugIn.h:24,
                 from /home/duvan/sc3-plugins/source/OteyPianoUGens/dwgs.h:4,
                 from /home/duvan/sc3-plugins/source/OteyPianoUGens/piano.h:8,
                 from /home/duvan/sc3-plugins/source/OteyPianoUGens/OteyPiano.cpp:7:
/usr/include/SuperCollider/plugin_interface/SC_SndBuf.h:27:35: fatal error: nova-tt/rw_spinlock.hpp: No such file or directory
 #include "nova-tt/rw_spinlock.hpp"
                                   ^
compilation terminated.
source/CMakeFiles/OteyPianoUGens_supernova.dir/build.make:62: recipe for target 'source/CMakeFiles/OteyPianoUGens_supernova.dir/OteyPianoUGens/OteyPiano.cpp.o' failed
make[2]: *** [source/CMakeFiles/OteyPianoUGens_supernova.dir/OteyPianoUGens/OteyPiano.cpp.o] Error 1
CMakeFiles/Makefile2:559: recipe for target 'source/CMakeFiles/OteyPianoUGens_supernova.dir/all' failed
make[1]: *** [source/CMakeFiles/OteyPianoUGens_supernova.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2

then i cannot do anything else, i tried uninstalling and re-doing it as the tutorial suggest, but i run into the same error. any help?

**Comment by brianlheim** [comment]
Hi  @DuvanArcos ,

it looks like you forgot to initialize the submodules for the supercollider repository when you cloned it. Can you please try again after running `git submodule update --init --recursive` on your supercollider clone?

**Comment by DuvanArcos** [comment]
the problem persist

**Comment by jamshark70** [comment]
Well, we don't know

A/ exactly what steps you took to initialize the submodules, and

B/ the terminal output of those commands.

So, as of now, the best anybody can do is to guess, which only wastes time.

Can you give us some detail?

**Comment by BUCK23** [comment]
Hi @DuvanArcos 

Not sure if you have managed to solve this - but I had the exact same error setting up on a new xubuntu system. Comparing to my old system - it seems the header files are going to /usr/include and they should be going to /usr/local/include. I'm not sure why as it worked perfectly well on my old system.

Anyway.
I solved it by purge removing supercollider-ide and supercollider-dev and then followed this guide for installing from source.

https://github.com/supercollider/supercollider/wiki/Installing-SuperCollider-from-source-on-Ubuntu

Hope that helps!

**Comment by brianlheim** [comment]
I am closing this because there is a lack of information and generally build errors on this project are user-side. @DuvanArcos feel free to provide more information or re-open if this assessment is incorrect.
