### ISSUE TITLE
MIDIFunc.noteOn does not work with floats

### ISSUE THREAD

**Issue by gesellkammer** [supercollider/supercollider#325]
**MIDIFunc.noteOn** fails silently if _noteNum_ is passed a float. If an Integer is needed, it should call .asInteger on the received argument or at least throw an Error .

**Comment by crucialfelix** [comment]
note: main reason that users supply floats is that we used a number input in a gui

**Comment by muellmusik** [comment]
I think this issue may have been prematurely closed. See my comment in #1425. Reopening for now.

**Comment by crucialfelix** [comment]
the commit does fix the bug that this ticket is for: casting a supplied float to an integer

what you commented over there is about handling arrays.  that is a separate issue.

**Comment by crucialfelix** [comment]
please file a separate issue for discussion if you feel its important.  I'm reclosing this because the issue as reported has been fixed.

**Comment by muellmusik** [comment]
> please file a separate issue for discussion if you feel its important. I'm reclosing this because the issue as reported has been fixed.

Sure. Done: #1426
