### ISSUE TITLE
Import debian/ directory from debian-multimedia

### ISSUE THREAD

**Issue by snappizz** [supercollider/supercollider#3264]
would it be a good idea if we imported the debian directory made by the [debian-multimedia team](https://anonscm.debian.org/git/pkg-multimedia/supercollider.git)? this would let us maintain our own debian packaging without having to go grab things from a third party, and potentially help with reviving the launchpad PPA.

cc @danstowell

**Comment by danstowell** [comment]
I am agnostic.

I don't know if it would cause confusion: for example when doing debian packaging the source needs to be stripped/repackaged, and would you actually do this "upstream" or would you just package from the latest git checkout? I'm not clear whether the proposal would simplify things or complicate things. I'd suggest you ask on the debian-multimedia mailing list before doing it - there's probably good advice there, as well as projects that already do it this way.

I guess, if you did do it, then for Debian itself we have the option of stripping out your debian folder and replacing it with our own, so downstream is probably safe!

Some related advice here (and in links):
https://wiki.debian.org/PackagingWithGit#Upstream_import_methods

**Comment by Sciss** [comment]
I'm not sure what this implies, but many people advise against starting to add debian-multimedia to package sources, because it can mess with the regular repositories; at least I had that situation back with Debian 8, and it was messy so reverted to canonical debian repositories and just built SC from source. I think having a separately downloadable .deb would be great.

**Comment by miguel-negrao** [comment]
> I think having a separately downloadable .deb would be great.

I think its easy to generate a single deb file by using [checkinstall](https://wiki.debian.org/CheckInstall). Instead of doing 'sudo make install' one does 'checkinstall --install=no' and it generates a deb file. This can be useful for releasing beta versions as .debs for instance.

**Comment by danstowell** [comment]
@miguel-negrao though that probably would clash with existing packages users might have installed already - specifically, if it wasn't the same package layout as in the official deb, it would fail to **replace** and instead would be installed alongside it, so might cause problems eg users accidentally running the old ver and thinking they were running the beta

**Comment by Sciss** [comment]
I'm totally noob here, but can't one build a self-contained .deb that requires no longer other system-wide dependencies?

**Comment by miguel-negrao** [comment]
> @miguel-negrao though that probably would clash with existing packages users might have installed already - specifically, if it wasn't the same package layout as in the official deb, it would fail to replace and instead would be installed alongside it, so might cause problems eg users accidentally running the old ver and thinking they were running the beta

True. It would require first uninstalling all the SuperCollider related packages already installed. 

> I'm totally noob here, but can't one build a self-contained .deb that requires no longer other system-wide dependencies?

A .deb is for system-wide installs. If you install a deb it might conflict with something else already installed.

**Comment by Sciss** [comment]
> A .deb is for system-wide installs. If you install a deb it might conflict with something else already installed.

yes, of course, but I mean the .deb could be dependency-less; so it
would only conflict with another SuperCollider .deb but not jack or QT
or whatever libraries are used.

**Comment by miguel-negrao** [comment]
> A .deb is for system-wide installs. If you install a deb it might conflict with something else already installed.
> 
> yes, of course, but I mean the .deb could be dependency-less; so it
> would only conflict with another SuperCollider .deb but not jack or QT
> or whatever libraries are used.

Maybe [flatpak](flatpak.org) is better for that use case ? I have no experience with it, but I read that you can bundle dependencies with a package.

**Comment by danstowell** [comment]
I suspect you're talking at cross purposes? Sure it may be possible to put dependencies inside some package or other (it seems you're both saying that) - but dependencies aren't really the problem.

The problem is when a user installs two versions of SC: the stable version from `apt` and some beta version from some kind of direct download. They'll get confused, and it'll be hard to get them cleanly out of the hole.

The only sanity-preserving way to avoid that while also using some kind of packaging to provide betas, would be to use the debian-multimedia folder as a basis (e.g. the initial proposal!). However, I personally don't think that providing betas as debs is as important as all that...

**Comment by Sciss** [comment]
> However, I personally don't think that providing betas as debs is as important as all that...

I agree. I see the problem of having several sc installations at the same time, but assume that in the overwhelming number of cases, what a user wants is the last stable release (unless they build from source themselves). And then distros like Debian are just too slow to catch up, so you have too old SC releases with the standard repository, and it would be great if one could just install a more recent .deb and that overrides the previous installation.

**Comment by danstowell** [comment]
@Sciss this is a good statement of the situation. I guess then "reviving the launchpad PPA" (in the original proposal) is the way to address it.

As I said earlier, I'd prefer to ask debian-mm community for their advice, since there may be a really good existing model for the OP

**Comment by snappizz** [comment]
@miguel-negrao 

> Maybe flatpak is better for that use case ? I have no experience with it, but I read that you can bundle dependencies with a package.

i looked a little bit into flatpak, and as far as i can tell it's specifically for GUI applications. we could package the IDE, but i'm not sure if flatpak would provide the option for the user to use only sclang or scsynth at the command line.

**Comment by snappizz** [comment]
agree with dan, let's consult the multimedia team and ask them about the best way for us to maintain our own deb releases.

**Comment by brianlheim** [comment]
ping. any updates on this?

**Comment by snappizz** [comment]
no resolution.
