### ISSUE TITLE
SynthDef not found error gives no hint which

### ISSUE THREAD

**Issue by telephon** [supercollider/supercollider#3281]
It would be so nice, after almost two decades of guessing, to finally get information about which SynthDef wasn't found …

```
*** ERROR: SynthDef  not found
FAILURE IN SERVER /s_new SynthDef not found
```

Just noting it, no hurry.

**Comment by LFSaw** [comment]
implemented in https://github.com/supercollider/supercollider/blob/develop/common/SC_Errors.cpp#L36

I fear this'd need a new OSC message...

**Comment by jamshark70** [comment]
Hm, seems not implemented there. SC_Errors.cpp lists the string constants that are posted after `/FAILURE`.

The `*** ERROR` line looks like it thinks it's concatenating a string into the message, but it's getting no string. So the part of the server sending the failure message back to the client is not populating the OSC message correctly.

I don't think it should require a new message. The OSC command reference specifies:

> /fail
> An error occurred.
> string	the name of the command
> string	the error message.
> other	(optional) some commands provide other information, for example a buffer index.

The type of `other` is not specified. I guess normally it will be a number, but the documented spec allows strings.

**Comment by jamshark70** [comment]
Hmm... 3.9beta here:

```
Synth(\nope)

-> Synth('nope' : 1000)
*** ERROR: SynthDef nope not found
FAILURE IN SERVER /s_new SynthDef not found
```

So, @telephon, what is different about your environment?

**Comment by telephon** [comment]
I have no idea - it must have been either a corner case (I'll be alert) or some older version (but I don't see how).

Great that it is finally fixed - I'll take a look if it is mentioned in the changes list somewhere.

**Comment by alln4tural** [comment]
FWIW, i recall getting posts of the type
*** ERROR: SynthDef nope not found
as a far back as 3.6, on both windows and macos, and i get them with 3.8 on windows today.
I don't think this was ever a problem.
