### ISSUE TITLE
PSinGrain's constantly growing amplitude 

### ISSUE THREAD

**Issue by patrickdupuis** [supercollider/supercollider#3292]
```supercollider
{ PSinGrain.ar * 1e-4 }.play
```
Running the above code creates a sine tone that keeps growing in amplitude. I'm assuming this is not intended. It's output is excessively loud when using the default arguments. Since it's a core UGen, `PSinGrain` should be fixed, and, if not useful, deprecated in 3.10.

**Comment by snappizz** [comment]
i recommend deprecation. it seems to have been implemented because it's an efficient DSP algorithm and not because it's anything musically useful.

**Comment by telephon** [comment]
that alone wouldn't be a reason to deprecate it: also musical plans you can only realize within the bounds of practical computability.

But indeed, the UGen seems to be broken and inefficient.

**Comment by telephon** [comment]
I've just fixed it in one line. Into what branch should it go?

**Comment by telephon** [comment]
I'd fix it and adjust the default amplitude to `0.1` as usual.

**Comment by vivid-synth** [comment]
Closing now that we've got https://github.com/supercollider/supercollider/pull/3494
