### ISSUE TITLE
Pbrown does not correctly handle a pattern for the length argument

### ISSUE THREAD

**Issue by shimpe** [supercollider/supercollider#3294]
by changing "length.value" to "length.asStream.value" in patterns.sc, line 454, it appears to work as expected

**Comment by telephon** [comment]
All the `length` and `repeats` arguments in patterns are not patterns themselves, but numbers, functions, or streams. They are, so to speak, not on the same level as the rest.

If we were to decide, for the sake of convenience, to do such a conversion, it should be done everywhere. Right now it is intended.

**Comment by shimpe** [comment]
Hmm... is there any rationale for this distinction? It seems a rather random limitation. I guess I can create my own patterns for the time being.

**Comment by shimpe** [comment]
Maybe I should give some context about  my use case so better ways can be suggested. I'm trying to have patterns with random length, so I was trying to write

Pbrown(0.1, 0.4, 0.01, Pfunc({ 10.rrand(20); }));

**Comment by telephon** [comment]
you can write this as 

`Pbrown(0.1, 0.4, 0.01, Pfunc({ 10.rrand(20) }).asStream);`

or simply

`Pbrown(0.1, 0.4, 0.01, { 10.rrand(20) });`

**Comment by shimpe** [comment]
Doh! Of course. Thanks a million.

**Comment by telephon** [comment]
The rationale is that every value for length is only used once per whole pattern anyway. And patterns are mostly there to generate sequences of values rather than just one value.

**Comment by jamshark70** [comment]
I realize it's already closed, but say you wanted a sequence 0, 0, 1, 0, 1, 2, 0, 1, 2, 3 etc. Currently you can write:

```
Pn(Pseries(0, 1, Pseries(1, 1, inf).asStream), inf)
```

With this change, you might think you could write:

```
Pn(Pseries(0, 1, Pseries(1, 1, inf)), inf)
```

... but then you'll get 0, 0, 0, 0, 0...

So the "mishandling" of pattern arguments is really a clue pointing to a misunderstanding of the objects' behavior. I agree, better not to change it.
