### ISSUE TITLE
3.9 beta HelpBrowser Header

### ISSUE THREAD

**Issue by prko** [supercollider/supercollider#3296]
Bug description:
The header of the HelpBrowser is not fixed but included in the help document.
Steps to reproduce:
1. install
2. launch

Actual result:
The header of the HelpBrowser is not fixed but included in the help document.
See the files below:
https://www.dropbox.com/sh/35xmd7fo26moaoy/AABIaYD1fQ4cUIzmBPYHoHk4a?dl=0

Expected result:
The header of the HelpBrowser should be fixed on the top of the window (below the Help browser title bar).

**Comment by jamshark70** [comment]
I would tend to agree that it's inconvenient to have to scroll to the top in order to choose something from the document's contents menu.

I recall that there were extensive discussions about the style sheet rework, which for whatever reason I didn't follow closely, but (too little too late) I disagree with the particular design decision to make the header menu scroll with the text.

**Comment by jamshark70** [comment]
https://github.com/supercollider/supercollider/commit/a65d17cc68c03114507ca137ad5ec371a62fac29#diff-b68a2f2b19cf953b6e69566d113f1633 removes `position: fixed;` from `#menubar`.

https://github.com/supercollider/supercollider/pull/2967

> i'd like to point out that no other documentation system i've seen has this position: fixed menu.

Maybe we can be better than them, then.

> ~~also, i don't think i've been in a situation where i need to know what page i'm on.~~ duhhhh i forgot about internal links

Exactly the point. We lost functionality. That table of contents, easily accessible no matter where you've scrolled to, is ace. I use it frequently. Real bummer that it's gone.

**Comment by telephon** [comment]
you could pop out the table of contents.

**Comment by brianlheim** [comment]
i was thinking of making this issue myself tbh. it really annoys me that i have to scroll to the top to click the search or browse buttons.

**Comment by prko** [comment]
"pop out" feature is good, but I should select "pop out" whenever launching supercollider.

**Comment by snappizz** [comment]
yeah, i think the best solution here is to make it pop-out only. will fix once i have time.

**Comment by prko** [comment]
Thank you very much!

**Comment by snappizz** [comment]
fixed via #3346
