### ISSUE TITLE
No prompt appears in command line sclang

### ISSUE THREAD

**Issue by patrickdupuis** [supercollider/supercollider#3297]
When I ssh into my BeagleBone Black (debian 9.2), running `sclang` compiles the library and give me a prompt. Doing the same on my laptop (fedora 26) compiles the library, but gives no prompt. I have to hit ESC and RETURN at the end of a block of code in order to evaluate it. Both systems are running 3.9-beta.

**Comment by vivid-synth** [comment]
Do you have readline installed? https://github.com/supercollider/supercollider/issues/2018

**Comment by snappizz** [comment]
i already have `libreadline-devel` installed. oddly, i also have a prompt now. coulda sworn i didn't have it at some point.

**Comment by patrickdupuis** [comment]
That's weird. A least it's there now :)

The thing that bothers me is that cmake has been telling me that my build was configured with readline support this whole time. What exactly is cmake looking for when it make this call?
