### ISSUE TITLE
some schelp files do not show the "Table of Contents" bar and "pop out".

### ISSUE THREAD

**Issue by prko** [supercollider/supercollider#3298]
Bug description:
some schelp files do not show the "Table of Contents" bar and "pop out".

Steps to reproduce:
1. writing schelp files 
2. compiling schelp document system
3. using the sc-help system

Actual result:
The  "Table of Contents" bar and "pop out" are disappeared in some help documents.
[working examples]
1. https://www.dropbox.com/s/xji9h41jb679ekb/K_00-aKoreanGuide.schelp?dl=0
2. https://www.dropbox.com/s/86l4x1z30662xqa/K_01-Imprint.schelp?dl=0
3. https://www.dropbox.com/s/erk1yk9kqtxlo75/K01_00-First_Aid.schelp?dl=0
[strange exampless]
1. https://www.dropbox.com/s/am22m7lj8opmh6a/K_02-about.schelp?dl=0
2. https://www.dropbox.com/s/49kgp2pi2cegdml/K_03-How_to_Use.schelp?dl=0

Expected result:
title and subtitle should appear in the "Table of Contents" bar and "pop out".

**Comment by prko** [comment]
I found a reason.
It occurs when a symbol is included in the "title::".
I don't know if it is a bug or not.

**Comment by brianlheim** [comment]
@prko can you explain what you mean by "symbol"? does that mean a non-ascii character?

**Comment by prko** [comment]
'Korean Guide'
<- This is a symbol because it is enclosed by two single quotation marks.

I think it is not important here if there is a non-ascii character or not.

**Comment by telephon** [comment]
I've tried to reprodice this by adding `' ' quotes around words in another existing guide, and did a `SCDoc.renderAll`, and `SCDoc.indexAllDocuments(true)`. But nothing I could do to get the guide out of the index. But I am not sure what kind of cashes there are around. Maybe you can check if the character `'` is really a `'` and not some other kind of non-ascii character?

**Comment by prko** [comment]
In the following file
https://www.dropbox.com/s/am22m7lj8opmh6a/K_02-about.schelp?dl=0
I changed the following line:
`title:: About 'A Korean Guide'`
->
`title:: About A Korean Guide`
and I just refreshed the document. Then the index appears.
When I add the ' ' quote again, the index disappears.

**Comment by brianlheim** [comment]
I can recreate this here (macOS 10.13). It was fairly simple, the generated javascript does not use escaped single-quotes, so any 's in the title will result in unparseable code.

#3301 fixes this. For now the workaround is to use double-quotes.

Thank you for the debugging information @prko - knowing that it was caused by single quotes was a huge help!

**Comment by prko** [comment]
thanks!
