### ISSUE TITLE
Use standard recording path for Windows 10 in Recorder.makePath

### ISSUE THREAD

**Issue by antonhornquist** [supercollider/supercollider#3307]
On Windows 10 ```Date.localtime.stamp``` evaluates to YYMMDD_HHMMSS for both SuperCollider 3.8.0 and 3.9.0-beta.

Why is there still an override to use ```Main.elapsedTime.round(0.01)``` for Windows platforms?

https://github.com/supercollider/supercollider/blob/769f78c0367ab03c6412e37636f310a68f0d5a56/SCClassLibrary/Common/Control/Recorder.sc#L175

Is Date broken on earlier versions of Windows?

I would suggest to find a way to use ```Date.localtime.stamp``` at least for Windows 10 which appears to be working fine in this regard.

**Comment by brianlheim** [comment]
hey @antonhornquist, thanks for the report! I think `Date` used to be broken in earlier versions of SuperCollider (it relies on an OS API call that perhaps hadn't been ported properly), but it's fine now. We actually just removed similar code in `History`, so there should be no problem getting rid of it here.
