### ISSUE TITLE
No way to specify different or additional extensions / plugins dir

### ISSUE THREAD

**Issue by sorki** [supercollider/supercollider#3314]
I'm trying to add sc3plugins to supercollider package on nixos but it doesn't seem possible due to $subj. I can't install directly to supercollider folder as this is considered separate build product. Would it be possible to add this functionality?

**Comment by brianlheim** [comment]
Yes, definitely, this will be added in a future version, probably 3.10. I believe there is a somewhat esoteric workaround you can do right now by adding extra command line arguments to the scsynth/supernova invokation.

**Comment by miguel-negrao** [comment]
I would imagine that nix has ways to deal with that, no ? Can't you create a third package which uses both packages and imports contents or as access to both ? How does nix create ghcWithPackages for a haskell environment where ghc has access to many packages, for instance ?

**Comment by sonoro1234** [comment]
-U followed by a folder path (or several paths separed by " ;")  in the command line will make all plugins in this folder to load.

**Comment by sonoro1234** [comment]
Should be closed. Solution provided above.

**Comment by sonoro1234** [comment]
I have not tried with last master but it should work as ever has done. (i use it in my client)

**Comment by snappizz** [comment]
there are two ways to do this. if you want to override all default paths, use `-U`. to specify one or more paths in addition to the default ones, use the environment variable `SC_PLUGIN_PATH`. note that supernova had incorrect plugin path loading until recently (#3815).

we do need to overhaul the server reference and document this kind of thing properly.

**Comment by asheshambasta** [comment]
I'm sorry for bumping up an old issue, but I seem to be having trouble with this. 
I've added sc3plugins via a custom derivation on NixOS; which adds the plugins dir. to /nix/store. 
Then I'm trying launch scide with: 
```
scide -U /nix/store/2ijljjr03b98knvj6p76h76g0rdmzrvi-sc3-plugins/share/SuperCollider/Extensions/SC3plugins
```

This launches scide without warnings; however, when doing 
```
SuperDirt.start
```
I still see warnings: 

```
 ---- SC3-Plugins not found. This is not a problem.Note that we are using a comb delay, which may not sound the same as SwitchDelay from the plugins
---- core synth defs loaded ----
...
WARNING: Dirt could not load some synths from default-synths.scd, because sc3plugins are necessary and missing.
...

loading 217 sample banks:
```

How does one need to handle this? 

SC version: 3.10.4

**Comment by brianlheim** [comment]
@asheshambasta mailing list, scsynth.org, or slack are better places for questions about using SuperCollider.

you need to pass -U to scsynth. not scide.

**Comment by asheshambasta** [comment]
@brianlheim thanks and my apologies.

**Comment by jamshark70** [comment]
Also note that scsynth's -U option totally overrides the default plugin locations (this is documented in ServerOptions help). You can omit this option and use the default locations, or include -U and specify all locations (and you'll have to write the default locations in as well). As you wrote -U, standard UGens wouldn't be found (bigger problem).The easier solution for sc3-plugins is to install them into the user or system level extensions directory, after which you wouldn't need -U at all.
