### ISSUE TITLE
Installing SuperDirt on SC 3.6.6

### ISSUE THREAD

**Issue by ionakathryn** [supercollider/supercollider#3319]
I'm trying to run tidalcycles and opened up Supercollider. I went through all the steps to download and recieved this message:

`supercollider-ide is already the newest version (1:3.6.6~repack-2-2):ubuntu`

However when I open the ide it says it's version 3.6.6. I need 3.7 to use tidal cycles as I am trying to use SuperDirt and getting error messages when including:

` The preceding error dump is for ERROR: Quark not found in repository.`
Hopefully someone can help.Thanks

**Comment by patrickdupuis** [comment]
What version of Ubuntu are you using? Recent Ubuntu versions should have at least SuperCollider 3.7 available in the repositories.

**Comment by ionakathryn** [comment]
Ubuntu 16.04.2 LTS - how can i move this forward?

**Comment by patrickdupuis** [comment]
Unfortunately, the PPA has not been kept up-to-date in recent years. The latest version of Ubuntu has a newer version of SC available in it's repositories. 

Building SC from source is your best option. It's not that difficult, and you can get help from people over on the SC mailing list if you need it. There is also this guide: https://github.com/supercollider/supercollider/wiki/Installing-SuperCollider-from-source-on-Ubuntu

**Comment by patrickdupuis** [comment]
There apparently is a way to get SuperDirt to run on SC 3.6. See the section in the README: https://github.com/musikinformatik/SuperDirt

**Comment by jamshark70** [comment]
> The latest version of Ubuntu has a newer version of SC available in it's repositories.

I, for one, will only use LTS versions of the operating system. So, to me, it doesn't matter that 3.7+ is in "the latest" Ubuntu repositories. Doesn't exist for me and for a whole class of users.

It doesn't bother me for SC because I build from source anyway, but if a user is already on the latest LTS version, it's 100% our fault that she can only install an ancient version from packages.

That said, @ionakathryn, building from source is, as Patrick says, a lot easier than you would expect. Worth a shot.

**Comment by patrickdupuis** [comment]
> ... it's 100% our fault that she can only install an ancient version from packages.

100% in agreement with you @jamshark70. We did briefly speak of linux packaging during the dev meeting today. We need to remedy this situation post 3.9.

**Comment by yaxu** [comment]
SuperDirt does not work at all well on 3.6.x
It is possible to compile from supercollider from source, you could ask on the toplap slack for help
  https://toplap.org/toplap-on-slack/

**Comment by ionakathryn** [comment]
OK i will go down the route of compiling from source then, thanks all for your responses

**Comment by miguel-negrao** [comment]
> Ubuntu 16.04.2 LTS - how can i move this forward?

16.04 is [based on debian stretch](https://askubuntu.com/questions/445487/what-debian-version-are-the-different-ubuntu-versions-based-on). Could you check if the debian package for stretch of supercollider (v3.7) installs on your system ?

https://packages.debian.org/stretch/supercollider

You would need to get 

* supercollider-ide
* supercollider-language
* supercollider-server
* supercollider-doc
