### ISSUE TITLE
[SC-IDE] Navigation history

### ISSUE THREAD

**Issue by miguel-negrao** [supercollider/supercollider#332]
Go back and forth to where you were before in the document or other documents.  For instance, select a class hit cmd-D which jumps to the definition, then you want to go back to where you were you do alt-cmd-<-  and you're back in the original document. This is implemented in IDEs like Intellij or Eclipse.  
It think alt-cmd-left arrow and alt-cmd-right arrow are good shortcuts.

From eclipse:

![](http://img822.imageshack.us/img822/953/capturadeecr20120518s10.png)

**Comment by brianlheim** [comment]
Closing as dupe of #3396.
