### ISSUE TITLE
the state of cwiid

### ISSUE THREAD

**Issue by dvzrv** [supercollider/supercollider#3320]
Hi all,

I'm now maintaining supercollider for Arch Linux and (by proxy) [cwiid](https://github.com/abstrakraft/cwiid).
However, the latter is by now more than obsolete/unmaintained. ~~I'm not able to build it on a current Arch Linux and~~ its latest package build was done in 2013.
As the maintainer (releasing that build), has been missing in action for more than two years, I will have to rebuild the package eventually (in the very likely case that he won't return) to have it signed with a current and valid gpg key, when the packagers status is dropped. ~~Failing to do that, it (and all packages that depend on it) will be dropped.~~
Cwiid is only an optional dependency for supercollider and in Arch Linux otherwise only dependency to kodi.

This leads me to the follow up question(s):
Is there a library to replace cwiid for supercollider?
Is there the will to further depend on/make available the functionality, that cwiid offers?

I'm currently thinking about building supercollider without cwiid support, as I don't want to be involved in its (i.e. cwiid's) further development and additionally don't see the possibility of fixes being merged upstream anytime soon (when looking at bug tracker and pull requests).

What do you think? Is there a reasonable future for the inclusion of an outdated and unmaintained library such as cwiid?

**Comment by dvzrv** [comment]
According to murphies law, I have to update my issue report ;-)
Nonetheless, the fundamental question remains.

**Comment by brianlheim** [comment]
@dvzrv Thanks for the question!

Wiimote-related classes have been [deprecated for 3.9](https://github.com/supercollider/supercollider/pull/2698). We plan to remove it in 3.10 (I think, someone can correct me on this if I'm wrong).

**Comment by gusano** [comment]
> I'm currently thinking about building supercollider without cwiid support

:+1:

**Comment by brianlheim** [comment]
@dvzrv - has your question been answered? mind if i close this?

**Comment by dvzrv** [comment]
Just figured out, that it was disabled by default for supercollider-3.8.0 in Arch already (cwiid was just a dead dependency).
The dependency is gone and after removing it from another package's build process cwiid will be gone from Arch alltogether.
