### ISSUE TITLE
A formal note (am I wrong here?)

### ISSUE THREAD

**Issue by holonen** [supercollider/supercollider#3322]
**New to SC. But shouldn't the parentheses in this example (italic by me):** 

   You can mix regular and keyword style if you like, but the regular args must come first:
   f = { arg a, b, c, d; _(a + b)_ * c - d };
   f.value(2, c:3, b:4, d: 1); // 2 + 4 * 3 - 1
   (Note that SC has no operator precedence, i.e. math operations are done in order, and division 
   and multiplication are not done first. To force an order use parentheses. e.g. 4 + (2* 8) )

**be after the comment, in the second line? Like this:**

   f.value(2, c:3, b:4, d: 1); // _(2 + 4)_ * 3 - 1

**in order for the note after the code to make sense? 
(It's from 04. Functions and Other Functionality in the Getting Started tutorial.)**

**Comment by jamshark70** [comment]
For readability, yes.

For functionality, no. In fact, you quoted the bit that explains why: "Note that SC has no operator precedence, i.e. math operations are done in order" -- which really should say "left to right order."

`2 + 4 * 3 - 1` *is* `((2 + 4) * 3) - 1`, and *not* `2 + (4*3) - 1`.

**Comment by brianlheim** [comment]
I think @jamshark70 is right, but just for clarity's sake, changed in #3323.

**Comment by holonen** [comment]
I guess my point - and what makes no sens - is the actual code, and the comment. If the code says:
(2+4)*3-1 
then the comment (which is not part of the language, but should be a clarification of what’s actually going on) should  read:
// (2+4)*3-1  
In the example code the value of the function is 17. The comment indicates that the value would be 13 (since the comment should reflect our ordinary way of writing things). It makes no sense to exclude the parentheses in the comment, when they’re there in the code. This made the example confusing, It makes a lot more sense to have the parentheses in the comment, and not in the code, to illustrate the way SC evaluates an expression, as stated in the note.
