### ISSUE TITLE
[SC-IDE] Document implementation

### ISSUE THREAD

**Issue by miguel-negrao** [supercollider/supercollider#333]
I know this is a bit particular, but at least it's a use case to think about in terms of how to allow some degree of scripting of the editor.

For instance I would like to run a function on the result value of anything that I evaluate, with a special keyboard shortcut. I think I could have done this in the old Document class, right ?

**Comment by scztt** [comment]
@miguel-negrao You okay closing this, since the Document class was revived? Is there still missing functionality?

**Comment by telephon** [comment]
For 3.7 it is fine. We'll need a more particular issue for individual features.
