### ISSUE TITLE
Raspberry Pi Build issues

### ISSUE THREAD

**Issue by Electromaster232** [supercollider/supercollider#3338]
Following the instructions [here](http://supercollider.github.io/development/building-raspberrypi) I recieved an error on the `make` command. I have a raspberry pi 3.
```[  0%] Building C object external_libraries/hidapi/linux/CMakeFiles/hidapi.dir/hid.c.o
*** Error in `/usr/bin/cc': double free or corruption (top): 0x0122bfe8 ***
Aborted
external_libraries/hidapi/linux/CMakeFiles/hidapi.dir/build.make:62: recipe for target 'external_libraries/hidapi/linux/CMakeFiles/hidapi.dir/hid.c.o' failed
make[2]: *** [external_libraries/hidapi/linux/CMakeFiles/hidapi.dir/hid.c.o] Error 134
CMakeFiles/Makefile2:408: recipe for target 'external_libraries/hidapi/linux/CMakeFiles/hidapi.dir/all' failed
make[1]: *** [external_libraries/hidapi/linux/CMakeFiles/hidapi.dir/all] Error 2
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by Electromaster232** [comment]
https://www.raspberrypi.org/forums/viewtopic.php?f=28&t=139091&p=922980
this seems to have some information but im not sure what to do with it

**Comment by redFrik** [comment]
in the instructions there's a note...
"if the make -j 4 build step stops or returns an error the compiler might just have run out of memory. try to reboot and run the make command again without -j 4 or decrease the gpu memory in raspi-config under advanced (set it to 16)."
so try make again. else redo everything from scratch. it should work.

**Comment by Electromaster232** [comment]
yea I tried that. Seems to be a GCC Compiler bug that was patched, but Debian (RasPi might be the only flavor of Debian with this actually, not sure.) has not been updated for the GCC patched, as mentioned in the above thread. I'm not sure if theres much we can do about it, if anyone knows anything it would be greatly appreciated!

**Comment by b1tfl0w** [comment]
Hello, I'm having the same issue here:
`make -j 4
[  0%] Building C object external_libraries/hidapi/linux/CMakeFiles/hidapi.dir/hid.c.o
[  0%] Building C object external_libraries/hidapi/hidapi_parser/CMakeFiles/hidapi_parser.dir/hidapi_parser.c.o
*** Error in `/usr/bin/cc': double free or corruption (top): 0x00e55f98 ***
Aborted
external_libraries/hidapi/hidapi_parser/CMakeFiles/hidapi_parser.dir/build.make:62: recipe for target 'external_libraries/hidapi/hidapi_parser/CMakeFiles/hidapi_parser.dir/hidapi_parser.c.o' failed
make[2]: *** [external_libraries/hidapi/hidapi_parser/CMakeFiles/hidapi_parser.dir/hidapi_parser.c.o] Error 134
CMakeFiles/Makefile2:463: recipe for target 'external_libraries/hidapi/hidapi_parser/CMakeFiles/hidapi_parser.dir/all' failed
make[1]: *** [external_libraries/hidapi/hidapi_parser/CMakeFiles/hidapi_parser.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
*** Error in `/usr/bin/cc': double free or corruption (top): 0x01661fe8 ***
Aborted
external_libraries/hidapi/linux/CMakeFiles/hidapi.dir/build.make:62: recipe for target 'external_libraries/hidapi/linux/CMakeFiles/hidapi.dir/hid.c.o' failed
make[2]: *** [external_libraries/hidapi/linux/CMakeFiles/hidapi.dir/hid.c.o] Error 134
CMakeFiles/Makefile2:408: recipe for target 'external_libraries/hidapi/linux/CMakeFiles/hidapi.dir/all' failed
make[1]: *** [external_libraries/hidapi/linux/CMakeFiles/hidapi.dir/all] Error 2
[  0%] Building CXX object server/plugins/CMakeFiles/PV_ThirdParty.dir/Convolution.cpp.o
[  0%] Building CXX object server/plugins/CMakeFiles/PV_ThirdParty.dir/FFT2InterfaceTable.cpp.o
*** Error in `/usr/bin/c++': double free or corruption (top): 0x009ffcf0 ***
Aborted
server/plugins/CMakeFiles/PV_ThirdParty.dir/build.make:62: recipe for target 'server/plugins/CMakeFiles/PV_ThirdParty.dir/Convolution.cpp.o' failed
make[2]: *** [server/plugins/CMakeFiles/PV_ThirdParty.dir/Convolution.cpp.o] Error 134
make[2]: *** Waiting for unfinished jobs....
[  0%] Building CXX object server/plugins/CMakeFiles/PV_ThirdParty.dir/FeatureDetection.cpp.o
*** Error in `/usr/bin/c++': double free or corruption (top): 0x00cb9ca8 ***
*** Error in `/usr/bin/c++': double free or corruption (top): 0x00a86cc0 ***
Aborted
Aborted
server/plugins/CMakeFiles/PV_ThirdParty.dir/build.make:86: recipe for target 'server/plugins/CMakeFiles/PV_ThirdParty.dir/FFT2InterfaceTable.cpp.o' failed
make[2]: *** [server/plugins/CMakeFiles/PV_ThirdParty.dir/FFT2InterfaceTable.cpp.o] Error 134
server/plugins/CMakeFiles/PV_ThirdParty.dir/build.make:110: recipe for target 'server/plugins/CMakeFiles/PV_ThirdParty.dir/FeatureDetection.cpp.o' failed
make[2]: *** [server/plugins/CMakeFiles/PV_ThirdParty.dir/FeatureDetection.cpp.o] Error 134
CMakeFiles/Makefile2:624: recipe for target 'server/plugins/CMakeFiles/PV_ThirdParty.dir/all' failed
make[1]: *** [server/plugins/CMakeFiles/PV_ThirdParty.dir/all] Error 2
[  0%] Building CXX object server/plugins/CMakeFiles/DiskIO_UGens.dir/DiskIO_UGens.cpp.o
*** Error in `/usr/bin/c++': double free or corruption (top): 0x017eacf0 ***
Aborted
server/plugins/CMakeFiles/DiskIO_UGens.dir/build.make:62: recipe for target 'server/plugins/CMakeFiles/DiskIO_UGens.dir/DiskIO_UGens.cpp.o' failed
make[2]: *** [server/plugins/CMakeFiles/DiskIO_UGens.dir/DiskIO_UGens.cpp.o] Error 134
CMakeFiles/Makefile2:587: recipe for target 'server/plugins/CMakeFiles/DiskIO_UGens.dir/all' failed
make[1]: *** [server/plugins/CMakeFiles/DiskIO_UGens.dir/all] Error 2
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2
`
Might be related to this bug? [https://github.com/Tencent/rapidjson/issues/707](url)
[https://www.raspberrypi.org/forums/viewtopic.php?f=28&t=139091&p=922980](url)
[https://gcc.gnu.org/bugzilla/show_bug.cgi?id=70132](url)

**Comment by redFrik** [comment]
couldn't reproduce. instructions are fine. i tested them again on both raspbian full and lite with a rpi3. make sure you're on raspbian stretch though. for rasbian jessie use an older version of these instructions https://github.com/supercollider/supercollider.github.io/blob/1f578b5fa71e1acae0ce40d14bc0ef116062093d/development/building-raspberrypi.md where also the older gcc4.8 is used.

**Comment by b1tfl0w** [comment]
That's probably the reason..becouse my version is jessie..I will try to upgrade to stretch in the next days. Thank you very much!
