### ISSUE TITLE
supernova crashes after starting a larger number of synths

### ISSUE THREAD

**Issue by dyfer** [supercollider/supercollider#3341]
On linux (Ubuntu 17.10) supernova crashes when number of running synths exceeds certain number. Increasing real time memory size changes that number.
This seems to happen in similar circumstances as https://github.com/supercollider/supercollider/issues/1840, but on linux it crashes instead of going silent.
```
(
Server.supernova;
s.options.memSize = 8192; // crashes around 400 synths
// s.options.memSize = 16384; // crashes around 800 synths
// s.options.memSize = 32768; // plays all 1000 synths
s.waitForBoot({

	SynthDef(\sinoscfb, {
		arg vol = 1;
		var sig = SinOscFB.ar([ExpRand(100.0, 6000), ExpRand(100.0, 6000)], MouseX.kr(0, 1));
		Out.ar(0, sig * vol);
	}).send(s);

	fork{
		var maxsynth = 1000;
		1.wait;  // give the SynthDef some more time
		p = ParGroup.new;
		maxsynth.do({
			Synth(\sinoscfb, [\vol, 0.1/maxsynth.sqrt], target: p);
			".".post;
			0.05.wait;
		});
		postf("\n% synths launched.\n", maxsynth);
	}
})
)
```

**Comment by brianlheim** [comment]
I'm going to consider this a dupe of #1840 since they have the same reproducer. If they turn out to be different issues we can reopen. Just want to avoid fragmented discussion. Thanks for testing!
