### ISSUE TITLE
NodeProxy bundling is broken

### ISSUE THREAD

**Issue by telephon** [supercollider/supercollider#3344]
Repeatedly sending new synths in `Ndef` is broken:

```
(
Ndef(\a).play;
fork {
	loop {
		Ndef(\a, { SinOsc.ar([1200, 1000, 800].choose, 0, 0.1) });
		0.2.wait;
	}
}
)
```

dumping the OSC gives bundle ordering errors like this:

```
[ "#bundle", 15987389872449688363, 
  [ "/error", -1 ],
  [ 15, 1005, "gate", -1.02, "fadeTime", 0.02 ],
  [ "/error", -2 ],
  [ 9, "temp__0a-1496504151_0", 1006, 1, 1001, "out", 7, "fadeTime", 0.02, "i_out", 7 ]
]
[ "#bundle", 1, 
  [ 5, DATA[524] ],
  [ 53, "temp__0a-1496504151_0" ],
  [ "/sync", 1405 ]
]
*** ERROR: SynthDef temp__0a-1496504151_0 not found
FAILURE IN SERVER /s_new SynthDef not found
[ "#bundle", 15987389873296669112, 
  [ "/error", -1 ],
  [ 15, 1006, "gate", -1.02, "fadeTime", 0.02 ],
  [ "/error", -2 ],
  [ 9, "temp__0a-1496504151_0", 1007, 1, 1001, "out", 7, "fadeTime", 0.02, "i_out", 7 ]
]
```

**Comment by telephon** [comment]
Well, having thought about it a little more, I see that it is really more of a specification issue.

What should happen when a proxy is overloaded with requests? Should it be blocked while it completes the previous?

I think it should have one queued object that is the last one that was pushed and which should be completed once the first locking one has completed. Maybe this even allows us to get rid of the cancellation of OSC bundles.

@jamshark70 and @adcxyz what do you think?

**Comment by jamshark70** [comment]
Huh. Tricky one indeed. The idea of canceling previous, not-completed requests makes sense. But if you send a bundle with latency, you can't retract it. I guess the only way would be to schedule the sending for *almost* the latency period -- meaning, there's a difference between latency and messaging latency. Latency is already confusing enough to users.

I'm not sure the bundles are necessarily out of order, given that the SynthDef-sending bundle is not timestamped. But it looks like each request reuses the SynthDef name. That's a bit dangerous. What if you appended a UniqueID to each defname? You could still `d_free` old defs, but that would solve one problem in your example: that the new SynthDef being sent, and the old one being freed, have the same name (`53, "temp__0a-1496504151_0"` followed by `9, "temp__0a-1496504151_0"`).

**Comment by telephon** [comment]
the problem is that even if this is done correctly, you never get any sound because you cancel each previous one before it is ready. 


one solution could be to ignore new requests while the first is still on its way, and only keep the last ignored request to be activated when the first has ended.

**Comment by jamshark70** [comment]
> you never get any sound because you cancel each previous one before it is ready.

I don't understand. The bundle for the new synth, for instance, frees 1005 and creates 1006.

Currently the SynthDef bundle sends a def for the nodeproxy's hash, and deletes a def for the same hash. That's a problem. Ensuring unique def names would solve that.

I can see, if the SynthDef bundle goes out with no timestamp and the synth bundle goes out with a timestamp, it's possible to have two SynthDef bundles in the latency gap, where the second removes the def needed for the first synth. You could address that by tying SynthDef removal to the old synth's `/n_end` notification. Deleting it in the SynthDef bundle is a shortcut, but it isn't formally correct.

**Comment by adcxyz** [comment]
I like the idea of an internal def version count: 
for one reason, the defname then documents better what is going, 
and makes the order of removing the old and adding the new synthdef irrelevant, 
which is more robust in any case.
worth trying whether this already alleviates the issue (if not fully fixing it)

**Comment by telephon** [comment]
Changing the synthdef name only cures the symptom. The problem is what I have described above: You'll just get no sound at all if you cancel. If you don't, you get a buildup of unfinished business.

Let me explain. The basic situation is that a task builds a new synthdef every say 0.1 seconds, faster than it can be loaded by the server.

You get the following dialog:
1. nodeproxy sends synthdef and waits for the `sync` (this happens in OSCBundle/SynthDefControl).
2. the next request comes in: nodeproxy cancels the message, so no synth is started, GOTO 1.

**Comment by telephon** [comment]
(this is not what happens now, but I realised this while fixing the bug)

**Comment by jamshark70** [comment]
Correct me if I'm wrong, but if each version of the NodeProxy's synth has a different defname, then it isn't necessary to cancel any messages.

The idea to "send a new def / clear the old def" is sound, but the fact that the two defs have the same name means that clearing the old def has a side effect that affects the new synth. Syncing is a workaround to try to control that side effect, but as far as I can see, it would be better to eliminate the side effect altogether.

If the names are unique, then the old and new synths can overlap seamlessly. Clearing the old def would have no effect on the new synth, so you could run them both -- the different names would isolate one from the other.

Even simpler than doing `/d_free` in response to `/n_end` would be just to put the `/d_free` message in that bundle with the command setting the gate to 0.

**Comment by telephon** [comment]
yes, you are right. I thought the same but excluded this option because it would mean that you accumulate unfinished osc messages indefinitely.

**Comment by jamshark70** [comment]
> you accumulate unfinished osc messages indefinitely.

Sorry if I'm being dense, but I don't understand what you mean by "accumulating unfinished messages."

"Messages" = OSCBundle, I guess. In that case, messages would be unfinished if you cancel a bundle after the preparation messages were sent, but before the active messages.

But if the sequence is:

1. Send synthdef with unique version ID in the name (no timestamp);
2. Send /s_new for that def (timestamp);
3. After the 0.1 sec, send a bundle setting that synth's gate to 0 and freeing the versioned defname -- I'm assuming here that this will be done before repeating the process for the next nodeproxy version...

... then you can have many of these processes running in parallel, even with very very short time offsets, without collisions. No "version" would touch another version's synthdef. You would have short-lived synths crossfading against each other, but that's a totally justifiable result -- perhaps even easier to justify to users than canceling requests.

**Comment by telephon** [comment]
>Even simpler than doing /d_free in response to /n_end would be just to put the /d_free message in the bundle with the command setting the gate to 0.

Then you can't reuse the synthdef anymore (`spawn` or `send`). I suppose we need a list of unfinished business …

**Comment by scztt** [comment]
I had to solve a similar problem in a class recently. I think the desired behavior is pretty clear: Ndef should be idempotent, and it’s state should (eventually) reflect the last set source/synth/arguments. Getting the queueing right for this is tougher: commands that change synth A have to be sent only after synth A is actually running - likewise Synth B. But, you don’t want to synchronize synth B on synth A, else you’ll end up with a growing backlog of old synths that no longer reflect the current state of the Ndef. I *think* the right solution is to have a queue for each synth the Ndef creates, one that looks something like:
- Send SynthDef
- {synchronize}
- Create Synth
- {synchronize}
- Send argument
- Send argument
- Free Synth
Possibly, freeing means you can ditch other scheduled things like `n_set`, but if you batch everything into a bundle the server will take care of this properly anyway. Importantly, you’d need one of these per synth, as sending a new synth should be done immediately and not interrupt the queue of a synth that’s still in an intermediate state. You can still build up messages like this, but the backlog should be constant and related to the difference between the server latency and the actual time it takes to instantiate new synths.

I worry a little about a model where setting a new synth cancels in-flight ones - whether something is “in-flight” could depend on server latency, server speed, whether a synthdef is loaded from disk or from a bundle, and other ephemeral things - it seems like a problem that synths could be run or not run depending on so many context-specific variables.
One other possibility: it’s pretty easy to detect when you’re changing an NodeProxy:source too fast for the server to keep up - perhaps simply warning in this case? No matter what behavior occurs, it’s probably not what the user wants anyway.

I’ve got an experimental-ish class that does this kind of queueing, I’d be happy to share if it would be useful for testing out solutions.
