### ISSUE TITLE
AppClock eats Exceptions

### ISSUE THREAD

**Issue by snappizz** [supercollider/supercollider#3357]
adding this to the class library:

    TestFoo : UnitTest {
        test_foo {
            //"this will be silently ignored".throw;
        }
    }

and running `TestFoo.run` correctly gives the report:

    UNIT TEST.............
    There were no failures

but if you uncomment the `.throw` line, the unit test silently exits and no report is given. even worse, attempts to `UnitTest.runAll` will suddenly stop at this test and never print a report for the entire suite of unit tests.

in the current 3.9 branch, `UnitTest.runAll` silently exits because of a thrown exception in `TestUGen_Duty`.

**Comment by telephon** [comment]
I've just tried to reproduce, but failed:

```TestUGen_Duty.run```

```
UNIT TEST.............
There were no failures
PASS:a TestUGen_Duty:test_ar_1_frame_demandrate_reset - Duty should output exact values at audio rate. Tested with 1 frames per value
PASS:a TestUGen_Duty:test_ar_1_frame_demandrate_reset - Duty should output exact values at audio rate. Tested with 1 frames per value
PASS:a TestUGen_Duty:test_ar_1_frame_demandrate_reset - Duty should output exact values at audio rate. Tested with 1 frames per value
PASS:a TestUGen_Duty:test_ar_1_frame_demandrate_reset - Duty should output exact values at audio rate. Tested with 16 frames per value
PASS:a TestUGen_Duty:test_ar_1_frame_demandrate_reset - Duty should output exact values at audio rate. Tested with 256 frames per value
```
I don't understand where the error posting is caught in your example …

**Comment by telephon** [comment]
The reason is elsewhere: A thread scheduled on `AppClock` swallows errors:

```supercollider
fork({ "yes yes".throw }, AppClock) // nothing
fork({ "yes yes".throw }, SystemClock) // ERROR: yes yes
```

**Comment by telephon** [comment]
… just noting some evidence from adding posts in `handleError` in Thread:

```
// fork({ "yes yes".throw }, SystemClock)
[ 'exceptionHandler', nil, 'parent', nil ]
[ 'exceptionHandler', nil, 'parent', nil ]
[ reportingError, yes yes ]
ERROR: yes yes
```


```
// fork({ "yes yes".throw }, AppClock)
[ 'exceptionHandler', nil, 'parent', nil ]
[ 'exceptionHandler', { | error | "open Function" }, 'parent', nil ]
```

**Comment by telephon** [comment]
The line
`delta = item.awake( beats, seconds, clock );`

in `Scheduler` swallows the error in the `AppClock` case.

**Comment by telephon** [comment]
This is the commit that introduced that bit of code: https://github.com/supercollider/supercollider/commit/3747d2b3bf30997fd11f2fe77003c5e8f6a6f8ee

**Comment by jamshark70** [comment]
But you aren't throwing an Exception. You're throwing a string. I'm not sure the behavior of throwing non-exceptions is fully defined.

`try` ignores thrown objects that are not Exception instances. I'm surprised it's reporting at all for SystemClock.

**Comment by telephon** [comment]
ah I didn't know that.

**Comment by telephon** [comment]
for completeness:

```supercollider
// Function
try { arg handler;
		var result = this.prTry;
		if (result.isException) { ^handler.value(result); }
		{ ^result }
	}


// and Object

isException { ^false }
```

**Comment by jamshark70** [comment]
Ah, now I see the original case in this issue is for throwing a string. AFAIK that was never fully supported. The fix for the unit test would be `Exception("blah blah").throw`.

Worth considering other cleanups:

- Why can we throw any object, but only Exceptions really count?

- Why does `try` swallow non-exceptions but `protect` halts on them?

**Comment by telephon** [comment]
that would make a good next issue :)

**Comment by muellmusik** [comment]
> Why can we throw any object, but only Exceptions really count?

Somehow reminds me of https://yosefk.com/c++fqa/exceptions.html#fqa-17.6
