### ISSUE TITLE
Write crude markdown-to-scdoc converter for changelog

### ISSUE THREAD

**Issue by snappizz** [supercollider/supercollider#3360]
we maintain our changelogs in markdown, but they also have to be converted to scdoc for the "News in 3.x" helpfiles. would be preferable to do this automatically. the changelogs are done with a very small subset of markdown, so this could probably be done pretty quickly.

in addition the script needs to strip all parenthesized pull request links. so, for example:

    `Server:userSpecifiedClientID` is deprecated. Use `Server:clientID` instead ([#3275](https://github.com/supercollider/supercollider/pull/3275)).

becomes

    code:: Server:userSpecifiedClientID :: is deprecated. Use code:: Server:clientID :: instead.

**Comment by brianlheim** [comment]
https://gist.github.com/443ae188dee8f7a85e7f34c04cc66d2b

**Comment by snappizz** [comment]
sweet, thanks. this works to strip out the PR numbers:

    # remove parenthesized text with a # in it
    LOG=`echo "$LOG" | sed "s/\s\+([0-9a-zA-Z, ]*#[#0-9a-zA-Z, ]\+)//g"`

**Comment by brianlheim** [comment]
@snappizz That's updated in the gist now. Mind if I close this and put a note in the WIP developer notes?

**Comment by snappizz** [comment]
cool. maybe the script could be merged into the `package/` directory for safe keeping?
