### ISSUE TITLE
Move supernova/utilities/malloc_aligned to common

### ISSUE THREAD

**Issue by snappizz** [supercollider/supercollider#3362]
currently, scsynth includes the header `supernova/utilities/malloc_aligned.hpp`. since that's the only dependency of scsynth on supernova code, i think it would make sense to move it to common. it just makes more sense that way (especially considering the unclear future of supernova).

**Comment by jamshark70** [comment]
No argument with the move.

I would like to see supernova have a more secure future. I've glanced at its source code and tbh I don't understand it at all (whereas, scsynth, I can start to grasp some of it). So maybe that one just is what it is.
