### ISSUE TITLE
document continuous testing via guard-sclang

### ISSUE THREAD

**Issue by aspiers** [supercollider/supercollider#3368]
I'm happy to announce the general availability of [`guard-sclang`](https://github.com/aspiers/guard-sclang).  Naturally I'm biased, but I think this is useful enough that it deserves documenting somewhere appropriate as another tool for SuperCollider developers ;-)  Suggestions on the best locations welcome.

**Comment by brianlheim** [comment]
there is a developing.md WIP that I've been working on on the wiki for this project. that would be a good place to add it.

**Comment by aspiers** [comment]
@brianlheim Where is this developing.md?

**Comment by brianlheim** [comment]
https://github.com/supercollider/supercollider/wiki/%5BWIP%5D-Developer-info-(DEVELOPING.md)

**Comment by aspiers** [comment]
Thanks!  I've added the info now.

**Comment by brianlheim** [comment]
Thank you!
