### ISSUE TITLE
codecvt not supported in mingw-w64

### ISSUE THREAD

**Issue by sonoro1234** [supercollider/supercollider#3378]
@brianlheim What should be the alternative

**Comment by brianlheim** [comment]
Visual Studio, until we upgrade Qt libs.

**Comment by brianlheim** [comment]
Or, you can use a version of gcc >= 5 and build Qt 5.5 from source.

**Comment by sonoro1234** [comment]
this is the first time mingw is not taken in account

**Comment by brianlheim** [comment]
@sonoro1234 I don't know what to tell you. We don't have anyone to maintain that toolchain. Why do you need to compile with mingw-w64?

**Comment by brianlheim** [comment]
This was also discussed on the mailing list about 6 months ago - http://new-supercollider-mailing-lists-forums-use-these.2681727.n2.nabble.com/3-9-release-and-final-fixes-td7634126.html

**Comment by sonoro1234** [comment]
Obviously I have been out too long and didn`t read any thread. The reason for using mingw is not being tied to microsoft compiler which is so complicated in its phylosophy and dll deployment. Mingw was the path that allowed supernova compilation on windows.
As it was said in the thread, I agree that those who are willing to maintain should decide what toolchain can they work with. In my personal case I can only afford to work on the audio-server part (scsynth, supernova and plugins). I think this part should maintain its relative separation from the whole project and keep the compatibility with mingw.

I can help in this issue with utf to unicode as I simply did in
```
https://github.com/sonoro1234/luafilesystem/blob/unicode/lfs_ffi.lua#L169
```
I must first correctly understand the specifications needed by utf8_to_native_str, specially in tems of allocations

**Comment by brianlheim** [comment]
> The reason for using mingw is not being tied to microsoft compiler which is so complicated in its phylosophy and dll deployment.

I'm not sure what you mean.

> Mingw was the path that allowed supernova compilation on windows.

Supernova will compile with later MSVC toolchains (2015 works IIRC).

In the two months we've been in beta I have not heard one request for a release that includes supernova. So while I understand the desire to include it, getting this general release out the door with a fix for a much more severe issue was more important than trying to maintain three separate toolchains in my judgment.

> In my personal case I can only afford to work on the audio-server part (scsynth, supernova and plugins). I think this part should maintain its relative separation from the whole project and keep the compatibility with mingw.

They are compatible with MinGW, just not pre-5.

**Comment by brianlheim** [comment]
> I must first correctly understand the specifications needed by utf8_to_native_str, specially in tems of allocations

Is the in source documentation unclear? What do you mean by "in terms of allocations"?

**Comment by brianlheim** [comment]
Also, is there a specific need to use MinGW 4.x aside from being compatible with Qt's binaries? That would be really good to know.

**Comment by sonoro1234** [comment]
I have downloaded mingw-builds with gcc 7.2 and everything seems to build correctly

**Comment by sonoro1234** [comment]
All test seem ok
