### ISSUE TITLE
supernova plugins not working / loading on OSX  (issue with patch provided)

### ISSUE THREAD

**Issue by florian-grond** [supercollider/supercollider#3391]
Hi SC devs,

Nicolas Bouillot and I could recently resolved an issue with SC3plugins and supernova on OSX:
supernova Ugens worked on Linux, but could not be found by the supernova server under OSX.
in fact, the supernova Ugens worked, when they resided in the specific folder Extension/plugins

however when they reside in
Extension/SC3plugins   (as stated in the SC3plugins documentation)
they don't work

This is the 3.8 code that needs fixing:
in supernova/server/main.cpp
[( https://github.com/supercollider/supercollider/blob/develop/server/supernova/server/main.cpp)]

```
#ifdef __linux__
        const path home = resolve_home();
        std::vector<path> folders = { "/usr/local/lib/SuperCollider/plugins",
                                      "/usr/lib/SuperCollider/plugins",
                                      home / "/.local/share/SuperCollider/Extensions",
                                      home / "share/SuperCollider/plugins" };

        for (path const & folder : folders)
            factory->load_plugin_folder(folder);
#else
        char plugin_dir[MAXPATHLEN];
        sc_GetResourceDirectory(plugin_dir, MAXPATHLEN);
        factory->load_plugin_folder(path(plugin_dir) / "plugins");

        char extension_dir[MAXPATHLEN];
        sc_GetSystemExtensionDirectory(extension_dir, MAXPATHLEN);
        factory->load_plugin_folder(path(extension_dir) / "plugins");

        sc_GetUserExtensionDirectory(extension_dir, MAXPATHLEN);
        factory->load_plugin_folder(path(extension_dir) / "plugins");

```
Looks like for the non-Linux platforms copy-paste made the plugins folder from the Resource directory (where it makes perfect sense) propagate to  SystemExtensionDirectory as well as UserExtensionDirectory
For the latter two cases / "plugins"   needs to be removed from the code:
**factory->load_plugin_folder(path(extension_dir));**
is enough for the  SystemExtensionDirectory as well as UserExtensionDirectory.

then, the supernova plugins are perfectly well recognized in any directory under Extension such as Extensions/SC3plugins for instance.

in 3.9 the same part of the code reads:
```
  factory->load_plugin_folder(SC_Filesystem::instance().getDirectory(DirName::Resource) / "plugins");
        factory->load_plugin_folder(SC_Filesystem::instance().getDirectory(DirName::SystemExtension) / "plugins");
        factory->load_plugin_folder(SC_Filesystem::instance().getDirectory(DirName::UserExtension) / "plugins");

```
again for SystemExtension as well as UserExtension

/ "plugins" needs to be removed.

```
factory->load_plugin_folder(SC_Filesystem::instance().getDirectory(DirName::SystemExtension) );
factory->load_plugin_folder(SC_Filesystem::instance().getDirectory(DirName::UserExtension) );

```
We compiled and tested for 3.8 and fro 3.9.
Thanks for applying the patch,

Florian and Nicolas

**Comment by patrickdupuis** [comment]
Thanks for the issue and patch @florian-grond! 

We discussed this briefly at the dev meeting this afternoon. @brianlheim thinks that there should be no problem getting this fixed for `3.9.1`. The release date of `3.9.1` is currently set to the end of the January.

**Comment by florian-grond** [comment]
If you could backport to 3.8 that would be great! should be quick!

**Comment by patrickdupuis** [comment]
I'll let @snappizz reply on the backport question.

I assume this is needed for SATIE? Have you though about patching the `3.8.1` source locally? (i'm assuming you are building from source on OSX). Otherwise, you have a fairly simple workaround until you can move to `3.9.x`.

 If you think that there are issues with SATIE that will keep the project from quickly moving to `3.9.x`, I can help test things out so that you don't have to mess around with your production systems.

**Comment by florian-grond** [comment]
Yes it is to some degree for SATIE, and we patched it locally, but also for anyone who want's to use supernova SC3plugins under OSX in any subfolder of Extensions.
I also added an OSX warning to my most recent SC-HOA PR, so that OSX users know where to put supernova plugins.
