### ISSUE TITLE
Resolve cppcheck warnings

### ISSUE THREAD

**Issue by shimpe** [supercollider/supercollider#3392]
Just for fun and giggles I tried to run cppcheck on the supercollider source code (checkout ea28126e28 of master branch) and it found some interesting problems: 

- supercollider/server/plugins/Loudness.cpp

 line **189**: Array 'phons[11]' accessed at index 11, which is out of bounds.

- supercollider/server/scsynth/SC_ComPort.cpp

 line **407**: Parameter 'bindTo' is passed by value. It could be passed as a (const) reference which is usually faster and recommended in C++.

- supercollider/server/scsynth/SC_CoreAudio.cpp

 line **558**: 'auto_ptr' destroys objects using operator 'delete'. But this object is created with new[] and therefore should be deleted with delete[] instead. Don't use auto_ptr objects created by new[].

- supercollider/server/scsynth/SC_GraphDef.cpp

 lines **845** and **858**: Common realloc mistake: 'refs' is nulled but not freed upon failure

- supercollider/server/scsynth/SC_Group.cpp

 lines **175** and **361**: Memory leak "names"

- supercollider/server/scsynth/SC_SequencedCommand.cpp

 macro SEND_COMPLETION_MSG fails to initialize struct member: packet.mIsBundle

- supercollider/server/scsynth/SC_World.cpp

 line **1291**: va_list 'vargs' was opened but not closed by va_end()

- supercollider/server/supernova/sc/sc_osc_handler.cpp

 line **194**: No 'return' statement in non-void function causes undefined behavior

- supercollider/server/supernova/server/server.hpp

 line **294**: va_list 'vargs' was opened but not closed by va_end()

- supercollider/server/supernova/server/synth_factory.hpp

 lines **37**, **62**, **79**: The iterator 'it' is invalid after the element it pointed to has been erased. Dereferencing or comparing it with another iterator is invalid operation.

- supercollider/server/supernova/sc/sc_synth.cpp

 line **280**: va_list 'vargs' was opened but not closed by va_end()

- supercollider/server/supernova/server/server.cpp

 line **366**:  va_list 'vargs' was opened but not closed by va_end()

**Comment by brianlheim** [comment]
@shimpe - Thanks! This is related to #2927, which I started but lost track of. I'm going to rename this to match. Are these all the errors, or are these just the most severe?

**Comment by shimpe** [comment]
these are the errors that cppcheck could find; however it chokes in many files on parsing errors (apparently it has trouble resulting the PluginLoad macro)

**Comment by shimpe** [comment]
And now I notice I only examined the errors in the server directory... maybe it's easier if I just append the results in cppcheck's native xml format.

[result.txt](https://github.com/supercollider/supercollider/files/1609206/result.txt)

**Comment by muellmusik** [comment]
I guess we should write some boost projects? ;-)

**Comment by brianlheim** [comment]
@shimpe - OK to close this now?
