### ISSUE TITLE
SCDoc is not print-friendly

### ISSUE THREAD

**Issue by prko** [supercollider/supercollider#3395]
Bug description:
Only the first pages of the HTML files produced by SC Help document system are printed in web browsers. Tested in Chrome, Safari and Edge under High Sierra and Windows 10.

Steps to reproduce:
1. Install 3.9 rc2 or rc1
2. Select '04. Functions and Other Functionality' under "Tutorials > Getting-Started"
3. evaluate the following code in SC:
(Platform.userAppSupportDir+/+"Help/Tutorials/Getting-Started/04-Functions-and-Other-Functionality.html").openOS
4. Print

Actual result:
Only the first page is recognised in the print menu,

Expected result:
If an HTML exceeds one page when printing, the whole pages must be [identified.](url)
When doing this using 3.8 version, 3.8 works without problems.
It is apparently a bug of 3.9.

Please try the following page using web browsers.
http://doc.sccode.org/Tutorials/Getting-Started/04-Functions-and-Other-Functionality.html
In this case, all pages are recognised and printed.

**Comment by snappizz** [comment]
i don't advise printing out the SC docs for the sake of trees, but this should be easy to fix.

**Comment by prko** [comment]
Hi,

I appreciate you for developing supercollider!

I have found that by changing the line 2 in the file scdoc.css, the problem of printing only the first page of the HTML produced through SC 3.9 is resolved:
`
height: auto;
`
I am not sure if it is a correct resoultion.... Thus, I am not sure if I could make a PR...

I have further questions about HTML.
In 3.8, the font size of an HTML automatically resized when printing the HTML if even a line inside `code:: ::` is too long. I don't remember what was the maximal number of characters per line.

Today, I have recognised that the HTML produced by SC 3.9 is printed out without resizing its font size even if there is a long line inside of `code:: ::`

Will the behaviour of 3.9 be maintained in the SC 3.10 release?
I think the behaviour of 3.10 is better...

Thanks

**Comment by snappizz** [comment]
please see #3831 -- it addresses this and several other SCDoc things that i messed up in 3.9.

**Comment by snappizz** [comment]
fixed!

**Comment by prko** [comment]
Thank you very much!
