### ISSUE TITLE
"Go Back" & "Go Forward" in the Help Document System do not preserve position on page

### ISSUE THREAD

**Issue by prko** [supercollider/supercollider#3396]
Bug description:
When going back and forward in the help document system, it goes the upper section of the document.
In the previous versions, it goes to the lines which I read at last time.

Steps to reproduce:
1. CTRL + D
2. scroll to bottom
3. click method
4. Go Back by selecting the Go Back button or by pressing backspace
5. Go Forward by selecting the Go Forward button

Actual result:
In 3.9 rc2, SC-IDE does not remember the last opened position of the help documents.
It shows only the first upper section of the documents. 

Expected result:
It must show the position of the documents which the user read lastly.

**Comment by brianlheim** [comment]
Hey @prko, thanks for the report. We will fix this in 3.9.1!

**Comment by patrickdupuis** [comment]
I've noticed that if you click on a TOC entry, navigate to a new page, and then go back, you'll be brought to the position in the original page that corresponds to the TOC entry.

**Comment by brianlheim** [comment]
That's probably because the URL including the anchor is being remembered?

**Comment by brianlheim** [comment]
As discussed in the previous two dev meetings, this is unlikely to be fixed because the problem lies in Qt's webview/webengine implementation, and fixing it would IMO require more time than it's worth. I propose closing this issue as wontfix.

**Comment by prko** [comment]
oh, it is regrettable, but thank you very much for your effort and time.

**Comment by htor** [comment]
there's a property `scrollPosition` in the `QWebEngingePage` class which could be pushed and popped on a stack for each forward/back call. see https://doc.qt.io/qt-5/qwebenginepage.html#scrollPosition-prop

**Comment by prko** [comment]
I think it has already been patched. I will close it. Thanks for your time and effort!
