### ISSUE TITLE
implementing python style multi-line strings?

### ISSUE THREAD

**Issue by prko** [supercollider/supercollider#3403]
I don't know if I might request a feature or an implementation here.
If it would be not possible, I am sorry for my misunderstanding.

Is it possible to implement python style multi-line strings in SC 3.9.1?
It is not related to sound processing but will be very convenient to organise lots of things including algorithmic composition and sound designing.

using .quote is good, but python style multi-line strings make lots of things easier.

**Comment by brianlheim** [comment]
> I don't know if I might request a feature or an implementation here.
> If it would be not possible, I am sorry for my misunderstanding.

This is a great place to do that!

> Is it possible to implement python style multi-line strings in SC 3.9.1?

Just to clarify – patch releases are for bugfixes only. New features go into minor releases, e.g. 3.10.x, 3.11.x. This scheme (called "semantic versioning") is a sort of new adoption for this project, starting with 3.8.

> using .quote is good, but python style multi-line strings make lots of things easier.

If you could, please be more specific, with examples of situations where this feature would be useful. To be honest I don't make much use of multiline strings in Python or Swift, the two languages I use that have this feature. The notation and indentation/character insertion rules are hard for me to retain, personally.

SuperCollider's syntax rules for string literals is already pretty flexible. It has:
```supercollider
(
"abc

xyz"
// produces "abc\n\nxyz"
)
(
"abc"
"xyz"
// produces "abcxyz"
)
```

What specifically are you missing from this notation?

**Comment by prko** [comment]
Thanks for your answer.
It is great that I can request a new feature here.

For example, when producing a MIDI note selected from a random text like this:

>This is a "test" text for a 'test'.
>like this example
>
I should write as follows:
```
~aTest= ("This is a"+"test".quote+"text for a 'test'.
like this example
").split($ ).ascii
```
However, I can simplify the code as follows with python style multi-line strings:

```
~aTest= '''This is a "test" text for a 'test'.
like this example'''.split($ ).ascii
```
With python style multi-line strings, we do not need to break a string to insert double quotation mark for example.

**Comment by brianlheim** [comment]
> I should write as follows:

I agree that your example is hard to read, but there is also this option:

```supercollider
~aTest= ("This is a \"test\" text for a 'test'.\nlike this example").split($ ).ascii
```

which does not seem so bad in this case. Even with a few lines of text it's not that painful.

> With python style multi-line strings, we do not need to break a string to insert double quotation mark for example.

You don't have to with the current set of features, either. Just escape it with a backslash: `\"`.

**Comment by prko** [comment]
Oh, thank you for your advice.

For me, the method of python style multi-line strings is simpler to work than the method suggested by you.
However, your suggestion is much simpler than .quote.
If many users do not need python style multi-line string, it might not be so necessary to be implemented.

**Comment by brianlheim** [comment]
OK. I'm going to close this for now since there doesn't seem to be a huge need for this feature. But, if more users ask for it, I'd certainly be open to considering it.
