### ISSUE TITLE
supercollider won't load in linux debian 9 stretch with i3wm

### ISSUE THREAD

**Issue by tiagomoraismorgado88** [supercollider/supercollider#3408]
[Bug Report] - supercollider/supercolldier - supercollider won't load in linux debian 9 stretch with i3wm

Greetings

I find the following issue when trying to run supercollider on debian 9 stretch with i3wm on a macbook a1278 2018:

- supercollider won't load;
- i have installed supercollider with apt-get install, which uses a build of 3.7 (which is considered stable according to debian standards)

I would like to state that it's important to figure out whethe this is derived of:

- a bug, so something which needs to be fixed
- wrong utilization of the software

when i press cmd-d on mac, only supernova shows up, and i can't load it not even from the command line. i don't seem to be able to load supercollider not even from the terminal, not even from the i3wm ui

I should make clear that supercollider loads on gnome

**Comment by gusano** [comment]
@tiagomoraismorgado88 can you please avoid using this weird formatting (why `<sub>`) so the text can be read easily?

Also, when submitting an issue please consider providing the following info:
- steps to reproduce the problem exactly
- expected behavior
- problematic behavior

Thank you

**Comment by miguel-negrao** [comment]
I can start SuperCollider compiled from develop (plus [some commits](https://github.com/supercollider/supercollider/pull/3278)) without issues in debian 9 and i3, so I can't reproduce the problem. I also have a macbook pro, although that should be irrelevant. I doubt that it is related to 3.7 vs dev version...

I agree with @gusano the extra format makes your issues harder to read.

**Comment by tiagomoraismorgado88** [comment]
@gusano my apologies. i collaborate with different organizations and do PR to different repositories, on github, and sometimes it's hard to keep track for me, what is acceptable and what is not, in each organization. 

---

@miguel-negrao ola, tudo bem? 

can you please tell me: 
- what do you exactly type when you try to load supercollider on debian (i am new within using supercollider in debian on mac)
- do you write in on the upper part of the screen, with cmd-d, or if you do it via the terminal? 

i will try your steps to figure out if this is really wrong usage, as i guess it is). and if it's related to 3.7) also can you can tell me exactly which version of supercollider are you using?

thank you

**Comment by miguel-negrao** [comment]
Olá, tudo bem.

> can you please tell me:
> 
>     what do you exactly type when you try to load supercollider on debian (i am new within using supercollider in debian on mac)
>     do you write in on the upper part of the screen, with cmd-d, or if you do it via the terminal?

Ctrl-d then SuperCollider IDE

**Comment by gusano** [comment]
@tiagomoraismorgado88 what happens when you type the following in a terminal:

- `scide`
- `sclang`

**Comment by tiagomoraismorgado88** [comment]
@miguel-negrao @gusano thank you so much. it works perfectly with scide/sclang, pointed out by @gusano. as i said, i am relatively fresh with linux. and even fresher with i3wm. feel free to close this issue. but don't delete it. may be useful in the future for someone looking for the same topic on the internet
