### ISSUE TITLE
scsynth exception handling: return error code, post message

### ISSUE THREAD

**Issue by jamshark70** [supercollider/supercollider#342]
Processes are supposed to return a nonzero error code if they terminate due to some sort of error. For many months, maybe even longer than a year, scsynth doesn't do that. It used to exit with error codes, but not anymore.

A quick way to illustrate:

```
a = {
    var sig = SoundIn.ar(0),
    stopper = Line.kr(0, 1, 1, doneAction: 2),
    fft = FFT(0, sig);
    IFFT(fft)
}.play;
```

When the synth ends, either FFT or IFFT (or both) try to release memory that was not allocated, so the server segfaults. But:

```
RESULT = 0
```

Segfault != success

If possible, it would be really nice to have a default exception handler in scsynth, at least to try to print something a little more informative than an incorrect "success" code.

**Comment by vivid-synth** [comment]
@jamshark70 I don't see this anymore, on Linux.

Repro steps:

File foo.scd:

```
s.waitForBoot {
   Routine {
      s.dumpOSC(1);
      s.dumpOSC(1);
      3.wait;
      a = {
         var sig = SoundIn.ar(0),
         stopper = Line.kr(0, 1, 1, doneAction: 2),
         fft = FFT(0, sig);
         IFFT(fft)
      }.play;
   }.play
}
```

```
$ SC_JACK_DEFAULT_INPUTS="system" SC_JACK_DEFAULT_OUTPUTS="system" scsynth -u 57110
```

Then in another window I call ```sclang foo.scd```, and see this output in the ```scsynth``` stdout:

```
[ "/d_recv", DATA[632], DATA[56] ]
FFTBase_Ctor error: Buffer 0 not initialised.
FFTBase_Ctor error: Buffer 0 not initialised.
Segmentation fault

$ echo $?
139
```

139 seems to be the Linux segfault exit code

**Comment by brianlheim** [comment]
Still seeing this on macOS.
```
FFTBase_Ctor error: Buffer 0 not initialised.
FFTBase_Ctor error: Buffer 0 not initialised.
RESULT = 0
server 'localhost' disconnected shared memory interface
```

**Comment by JordanHendersonMusic** [comment]
Can confirm this works on Linux, any mac users out there who wouldn't mind retesting?

**Comment by muellmusik** [comment]
No crash on 3.13.0, MacOS 13.5.2

```
[ "/d_recv", DATA[632], DATA[56] ]
FFTBase_Ctor error: Buffer 0 not initialised.
FFTBase_Ctor error: Buffer 0 not initialised.
[ "/d_free", "temp__0" ]
```
