### ISSUE TITLE
Avoid installing Qt/GUI classes if SC_QT is turned off on compilation

### ISSUE THREAD

**Issue by rukano** [supercollider/supercollider#3420]
Feature request:
Right now the Qt classes in Common/GUI and JITLib/GUI are bundled in the SCClassLibrary, which causes some error on initialization. Wouldn't it be nicer to avoid copying these classes in the first time, if the SC_QT option is disabled? This would give a clean start, when using headless sclang. For the moment, platforms like the raspberry pi, sonic pi, and sclang working on servers, etc have to manually remove these 2 folders for a clean start.

**Comment by vivid-synth** [comment]
Related: https://github.com/supercollider/supercollider/issues/1209

**Comment by telephon** [comment]
we could try and establish a standard name for the gui folder, which can then be excluded?
