### ISSUE TITLE
[scusers&developers: use this] shell script for automatic pull requests in debian

### ISSUE THREAD

**Issue by tmm2018** [supercollider/supercollider#3440]
[scusers&developers: use this] shell script for automatic pull requests in debian

hey guys

i recently wrote this script in shell for unix debian. it's a way of drastically simplifying the amount of time necessary to pull a request from shell. if you are interested, please use this:

- https://github.com/tmm2018/tmm_shell/blob/master/_scripts/_tmmScrp/mgc.sh

**Comment by brianlheim** [comment]
This can be accomplished easily without installing dependencies and also in far fewer commands.

**Comment by jamshark70** [comment]
I would also add that it's unwise to commit all unstaged changes without verifying them (`git add .`), *especially* for something to push publicly. The chance of something slipping into the commit that you didn't want or expect is very high, resulting in poor-quality PRs that need more work to clean up.

Using the commit message as the branch name is very strange. Branch names should be shorter; commit messages are for humans and should explain briefly what the commit is about. And, the commit message comes from pwgen (`git commit -m $VAR1`)?

PRs generated by this script are almost guaranteed to be rejected.
