### ISSUE TITLE
https://supercollider.github.io/ contains example that cannot be run with standard install

### ISSUE THREAD

**Issue by shimpe** [supercollider/supercollider#3448]
I'd like to flag some shortcomings of the webpage. After all, there's only one chance to make a first impression.

* The atari example on the web page apparently requires one to install an Atari UGen. This is not mentioned or explained anywhere on that page (I had to check the source code to find out where to get it!). New users pasting the example code in supercollider for the first time therefore are met with error messages without any clue how to go about solving them = instant turn-off.
* Examples on the front page probably should also explicitly mention that one has to boot a server first (or should be rewritten using s.waitForBoot).

**Comment by brianlheim** [comment]
Migrated to https://github.com/supercollider/supercollider.github.io/issues/122. Thanks for the report!
