### ISSUE TITLE
[SC-IDE] Equivalent of cocoa menus and items

### ISSUE THREAD

**Issue by jamshark70** [supercollider/supercollider#346]
One very handy feature in the OSX sc.app is the ability to add new menus into the application's menu bar, and new menu items (with optional keyboard shortcuts).

It hasn't been feasible to add this into sclang because of the many different editors.

Since sc-ide has its own menu bar, there's no apparent technical reason why sc-ide could not allow users to add menus or items.

**Comment by snappizz** [comment]
Currently in progress! #2504
