### ISSUE TITLE
Normalize include guards

### ISSUE THREAD

**Issue by brianlheim** [supercollider/supercollider#3479]
Right now this project uses a couple different naming conventions for include guards, including some that are technically illegal (macros beginning with `_` followed a capital letter are reserved for the compiler). Aside from being un-tidy, having too-short header guard macros like `_SC_Errors_` is a debugging nightmare waiting to happen.

I'd like to propose normalizing the header include guards using the file's full path name. For instance, the file `editors/sc-ide/core/sc_server.hpp` would have the include guard:

```
#ifndef EDITORS_SCIDE_CORE_SC_SERVER_HPP_INCLUDED
#define EDITORS_SCIDE_CORE_SC_SERVER_HPP_INCLUDED
```

The way to get the correct macro is:
- put everything in caps
- remove hyphens
- replace `.` and `/` with `_`
- add `_INCLUDED` to the end

Schemes similar to this are used in various parts of the project, but all of them leave off parts of the path. I think this is reasonably safe in most cases, BUT, using the full path eliminates any potential for collisions and makes it easy to mechanically update the guard if the file moves. We lose nothing by being specific.

Side note: I'm pretty sure there's an open issue for the illegal macros thing I mentioned above, but I can't find it anywhere.

**Comment by scztt** [comment]
Is there a more modern C++ way of doing include guards? Should we just replace with `#pragma once`?

**Comment by brianlheim** [comment]
@scztt - I would be happy with using `#pragma once`, it's nicer for obvious reasons. The only conceivable drawback is that it isn't supported by one well-known compiler (Portland group, according to https://en.wikipedia.org/wiki/Pragma_once) and likely other small compilers.

But since it doesn't look like we're going to be expanding that coverage anytime soon, and all the compilers we currently use have supported it at least since C++11 support, I guess it's hard to argue for not using pragma once.

**Comment by LFSaw** [comment]
so is this still something to work on or is the tendency more towards refactoring it to `pragma once`?

**Comment by brianlheim** [comment]
I think we should just go with pragma once. It would be easy to change that if we ever needed to, and the chance of us needing to seems vanishingly small.

**Comment by sbl** [comment]
hi @brianlheim see the start of my work here https://github.com/supercollider/supercollider/compare/topic/webengine...sbl:pragma_once it's currently based off https://github.com/supercollider/supercollider/pull/3165 

Let me know if this is what you had in mind, then I'll prepare a PR once https://github.com/supercollider/supercollider/pull/3165 is merged back.

**Comment by brianlheim** [comment]
@sbl YES that's it! You are a saint.

**Comment by brianlheim** [comment]
@sbl you are good to go on this now!
