### ISSUE TITLE
3.9 Regression:grain event type fails to find group and fails to play

### ISSUE THREAD

**Issue by cappelnord** [supercollider/supercollider#3481]
This code worked in 3.8 but does not work anymore in 3.9 (tested on Mac and Windows)

```supercollider
(
SynthDef(\grain, {|freq=440, amp=0.1, out=0, pan=0, len=0.005|
	var sig = SinOsc.ar(freq, phase: Rand(0, 2pi));
	var env = EnvGen.ar(Env.sine(len), doneAction: 2);
	sig = sig * amp * env;
	OffsetOut.ar(out, sig);
}).add;
)

(
Pbind(
	\instrument, \grain,
	\type, \grain,
	\dur, 1 / 32,
	\amp, 0.1,
	\freq, Pwhite(200, 400)
).play;
)
```

Expected: Grains
Result: No sound but "FAILURE IN SERVER /s_new Group XXX not found" error messages for every event.

**Comment by cappelnord** [comment]
Just playing a single Event also does not work:

`(
	\instrument: \grain,
	\type: \grain,
	\amp: 0.1,
	\freq: 400
).play;
`

**Comment by patrickdupuis** [comment]
Thanks for the report Patrick!


This does seem to be broken. Probably happened back in September 2017.


A workaround that appears to work is to add \group, s.defaultGroupID to the Pbind.


If you can, please open an issue on GitHub.


Cheers,

Patrick Dupuis

**Comment by telephon** [comment]
This is a bug now in many of the event types.

The reason is that now we have:

`group: { ~server.defaultGroup.nodeID }`

so you need to call 

`~group.asControlInput`
or
`[..., ~group, ...].asOSCArgArray`.

Which happens in the default `note` event, but not in some others.
