### ISSUE TITLE
Request: Adding Version Information to the Path of Platform.userAppSupportDir

### ISSUE THREAD

**Issue by prko** [supercollider/supercollider#3503]
Hi,

Would it be possible that SC Platform.userAppSupportDir includes the version of the SC release?

Currently, Platform.userAppSupportDir under Windows is
_%homepath%\AppData\Local\SuperCollider_

Under macOS
_~/Library/Application Support/SuperCollider/_

If my idea is accepted, then Platform.userAppSupportDir under Windows will be
_%homepath%\AppData\Local\SuperCollider\3.8_

under macOS
_~/Library/Application Support/SuperCollider/3.8_

The advantage is that we can use 3.8 and 3.9 simultaneously and independently because SC3.8 uses _%homepath%\AppData\Local\SuperCollider\3.8_ as its AppSupportDir under Windows,

_~/Library/Application Support/SuperCollider/3.8_ under macOS,

and SC3.9 uses 
_%homepath%\AppData\Local\SuperCollider\3.9_ as its AppSupportDir under Windows.

_~/Library/Application Support/SuperCollider/3.9_ under macOS.

It will also solve the problem described in http://new-supercollider-mailing-lists-forums-use-these.2681727.n2.nabble.com/Sc3plugins-needs-to-be-in-system-wide-extensions-dir-td7637820.html.

best

**Comment by brianlheim** [comment]
I support this, I believe @snappizz also suggested it on the dev list a few weeks ago.

**Comment by brianlheim** [comment]
For compatibility I don't think this can't be changed on versions pre-3.10, though. Thoughts on that welcome...

**Comment by prko** [comment]
I think the compatibility is not a big problem when the code algorothm is as follows:
```
(
~userAppSupportDir =
PathName(Platform.userAppSupportDir+/+Main.version).isFolder.if
{ Platform.userAppSupportDir+/+Main.version}
{Platform.userAppSupportDir}
)
``

sorry... It is a sc code...
