### ISSUE TITLE
classlib: consider deprecating File.openDialog, File.saveDialog, File.openDialogs

### ISSUE THREAD

**Issue by brianlheim** [supercollider/supercollider#3506]
I think File.openDialog, File.saveDialog, File.openDialogs should all be deprecated

### Reasoning

File.openDialog and File.saveDialog:
- forward directly to Dialog.openPanel and Dialog.savePanel. 
- have no documentation
- are another way of doing something, which adds confusion
- are arguably part of the wrong class. `File` should not be involved in GUI creation. Just adds cruft having them here

File.openDialogs is never used. Presumably it would be used in an observer pattern so that you could get a list of currently open dialogs. However, that pattern was never implemented, and would have no realistic usage IMO.

**Comment by snappizz** [comment]
i support deprecation.

**Comment by jamshark70** [comment]
FWIW I agree. In my own code, I'm using only the Dialog.*Panel methods.

**Comment by brianlheim** [comment]
#3507 fixes this :)
