### ISSUE TITLE
scide should take -h/--help command line argument

### ISSUE THREAD

**Issue by snappizz** [supercollider/supercollider#3511]
easy one: i'd expect `scide -h` and `scide --help` to print a help message instead of booting the IDE.

**Comment by brianlheim** [comment]
Sorry to ask what seems like an obvious question, but does the IDE application currently take command-line arguments as it is? I can't find documentation for this.

Also, note that on macOS the program is named `SuperCollider` (even inside the bundle)

**Comment by snappizz** [comment]
i tried running `scide foo.scd` and it seems to work. of course the entire point of `-h/--help` would be documenting this :)

**Comment by dyfer** [comment]
closed in #4950
