### ISSUE TITLE
Download link to 3.9.1 linux source release contains 3.9.0 source

### ISSUE THREAD

**Issue by vogre** [supercollider/supercollider#3516]
After compiling the download SuperCollider-3.9.1-Source-linux.tar.bz2 (sha1 b223171b8d722d7b251de8520240a76489d33faf) the resulting binary had version 3.9.0, also `SCVersion.txt `contains `PROJECT_VERSION_PATCH .0` and commits between 3.9.0 and 3.9.1 are absent.

The Source code (tar.gz) download seems to have the right files, and the macOS download seems to have 3.9.1 as the version.

**Comment by snappizz** [comment]
oops. fixed
