### ISSUE TITLE
Float.sign returns Float not Integer

### ISSUE THREAD

**Issue by aspiers** [supercollider/supercollider#3522]
Maybe this is just me, but I would expect `sign` to always return `Integer`, even when called on a `Float`.  Currently there is a weird and surprising interaction with `switch`:

```supercollider
~direction = { |val| 
	switch (val.sign) 
	{-1} {"down"}
	{ 0} {"same"}
	{ 1} {"up"};
};
~direction.value(-3)  // returns "down" as expected
~direction.value(-3.2)  // returns nil?!
```

I'm assuming this is because it's somehow comparing -1.0 to -1 and the equality fails.

**Comment by telephon** [comment]
I suppose it is consistent with the UGen method:

`{ a = SinOsc.ar; [a, a.sign] }.plot`

But I see your point, it is a little irritating.

**Comment by brianlheim** [comment]
I see where you're coming from; OTOH it's kind of a slippery slope to make `sign` return an int type. This breaks from the standard behavior of numerical methods returning the same type as the receiver. I'm not sure there's a convincing argument for why `sign` and not `ceil`, `floor`, `trunc`. Of course they are somewhat different in that `sign` has a very small set of return values. BUt I guess I still would feel strange about making an exception in this case.

Am I maybe misunderstanding how switch works? The difference between these two lines doesn't make sense to me:

```supercollider
switch("meow") {"meow"} {1} {0} // 1
switch(3) {3.0} {1} {0} // 0
```

**Comment by brianlheim** [comment]
`switch` is not being inlined correctly:

```supercollider
a = {3}
b = {3.0}
switch(a.value) {b.value} {1} {0} // 1
switch(3) {3.0} {1} {0} // 0
```

**Comment by brianlheim** [comment]
I'd like to close this if nobody minds. I don't think there is a strong enough reason to change it.

**Comment by aspiers** [comment]
I'm a bit lost, I'm afraid - probably don't have enough understanding of how sclang works (e.g. I know nothing whatsoever about its byte code).

You seem to be saying that there is a bug in `switch`, and certainly it looks that way to me - I don't understand why the two examples above would be treated differently other than the fact that the first one would need to do some extra work to send the `value` message to `a` and `b` as early steps.  But once it's done that, shouldn't the rest of the byte code be identical?

Anyway, inlining and byte code aside, what's the actual behaviour here?  Is it that different types of equality tests are applied in each case? It seems that in the second case it treats `3` as inequal to `3.0`, which is extremely surprising.

So I'd say that for sure there's an issue with `switch` which should be fixed, but that deserves a separate issue. If you're asking whether the request for `Float.sign` to return an `Integer` can be dropped then I'd say probably yes on grounds of keeping consistency with the other numerical methods, since fixing the switch issue would solve the original problem even if `Float.sign` continued to return a `Float`.

**Comment by jamshark70** [comment]
> I'm a bit lost, I'm afraid - probably don't have enough understanding of how sclang works (e.g. I know nothing whatsoever about its byte code).

You can explore it:

```
{ ... some code... }.def.dumpByteCodes;
```

Everything I know about sclang's byte codes, I learned this way, by observation.

> You seem to be saying that there is a bug in `switch`, and certainly it looks that way to me

`switch` currently handles floats badly. I'm now of the opinion that floats should prevent the inlining optimization. As of now, they don't. I just opened #3564 to think that through.

> I don't understand why the two examples above would be treated differently other than the fact that the first one would need to do some extra work to send the `value` message to `a` and `b` as early steps.

The variables are just a trick to force the compiler not to inline. No other significance.

> But once it's done that, shouldn't the rest of the byte code be identical?

No: one is inlined and the other is not. Inlining produces different, more efficient, byte codes when the input code meets certain conditions. The problem here is that we inline `switch` involving floats, but we shouldn't.

> Anyway, inlining and byte code aside, what's the actual behaviour here?  Is it that different types of equality tests are applied in each case? It seems that in the second case it treats `3` as inequal to `3.0`, which is extremely surprising.

```
3 == 3.0
-> true

3 === 3.0
-> false
```

The first test is equality; the second is identity. Two expressions are identical only if they result in the exact same object (in C terms, same pointer).

If you have two distinct arrays with the same contents, they are equivalent, but not identical.

3 is not identical to 3.0 because they are different data types, so by definition, they must be two distinct objects. 3 *is* identical to 3, though (same atomic data type, same value).

**Comment by aspiers** [comment]
> > But once it's done that, shouldn't the rest of the byte code be identical?
> 
> No: one is inlined and the other is not. Inlining produces different, more efficient, byte codes when the input code meets certain conditions. The problem here is that we inline switch involving floats, but we shouldn't.

You're saying that we shouldn't inline either, right?  So isn't the answer to my question "yes"?  By "shouldn't" I was talking about the ideal scenario, not how it behaves right now.

> The first test is equality; the second is identity. Two expressions are identical only if they result in the exact same object (in C terms, same pointer).

Yes, I understand the difference between equality and identity ;-)  My point was that use of anything but an equality test (i.e. *not* an identity test) in a `switch` branch decision is surprising.  In any case, given the presence of #3564 which ensures the inlining issue is tracked, I think it's fine to close this now.  Thanks a ton for your time on this!!
