### ISSUE TITLE
optimize .linlin, .explin, .lincurve, .curvelin

### ISSUE THREAD

**Issue by snappizz** [supercollider/supercollider#3524]
`.linlin`, `.explin`, `.lincurve`, `.curvelin` should be implemented as native UGens for efficiency.

`.linexp` is currently implemented as a native ugen `LinExp`, but `LinLin` is a pseudo-ugen, and `ExpLin`/`CurveLin`/`LinCurve` don't exist.

thanks to @LFSaw for bringing this one up on slack.

the efficiency hits of the pseudo-ugen versions are quite noticeable for embedded systems.

**Comment by LFSaw** [comment]
oh, the thanks should go to @sensestage since it was her bringing it to my attention :)

**Comment by vivid-synth** [comment]
Would be great for non-sclang client devs too :smile:

**Comment by snappizz** [comment]
seems like nobody else is interested in this, so i'll reopen this when i get around to it.
