### ISSUE TITLE
The "scheduler queue is full."

### ISSUE THREAD

**Issue by telephon** [supercollider/supercollider#3533]
This happens sometimes, when `schedAdd` in `PyrSched` runs into a limit. But if I read this correctly, it should add to the heap (`addheap`). A heap shouldn't get full, should it?

https://github.com/supercollider/supercollider/blob/43fa8855735cdc914261311b2fe09834db440ab4/lang/LangPrimSource/PyrSched.cpp#L359

Reproducer for an everyday situation:

```supercollider

s.options.maxNodes = 2 ** 16;
s.reboot;


(
SynthDef(\x, { |out, sustain, freq, amp = 0.1, pan|
	var env, sig;

	env = EnvGen.ar(Env.perc(0.1, 0.9), timeScale:sustain, doneAction:2);
	sig = SinOsc.ar(freq, 0.5pi);
	amp = AmpCompA.kr(freq) * amp;

	sig = Pan2.ar(sig, pan, amp * env);

	OffsetOut.ar(out, sig)
}).add
)


// fine.
128.do { (instrument: \x, sustain: 1, freq: rrand(70.0, 12000)).play };

// scheduler queue is full.
4096.do { (instrument: \x, sustain: 1, freq: rrand(70.0, 12000), amp: 0.001).play };

```

**Comment by jamshark70** [comment]
I believe releases are scheduled first on the default TempoClock. TempoClock.new specifies a maximum size for the queue. If you exceed that, you'll get this error no matter how much memory is available for the heap.

Also note that the queue consists of one item for the number of scheduled actions, followed by three array elements per scheduled item. So the practical queue size is `(maxSize - 1) / 3`.

I don't see any bug here.

**Comment by telephon** [comment]
Ahh, that's it. I see that it also happens with type `\grain`:, which has no release:

`4096.do { (type: \grain, instrument: \x, sustain: 1, freq: rrand(70.0, 12000), amp: 0.001).play }`

This is because we are using the clock scheduler even when we are sending right now. It is in 

Event: `schedBundleArray` (https://github.com/supercollider/supercollider/blob/develop/SCClassLibrary/Common/Collections/Event.sc#L317)

And 

```supercollider
schedBundleArrayOnClock { |clock, bundleArray, lag = 0, server, latency|
		clock.sched(this, {
					if (lag != 0) {
						SystemClock.sched(lag, {
							server.sendBundle(latency ? server.latency, *bundleArray)
						})
					} {
						server.sendBundle(latency ? server.latency, *bundleArray)
					}
		})
	}
```

schedules even when `this = 0`.

We could save a lot of electricity if we added an exceptional case there, seems.

**Comment by telephon** [comment]
OK, I've made a PR here, to see what happens.
