### ISSUE TITLE
Can't type anything on linux.

### ISSUE THREAD

**Issue by Stain2608** [supercollider/supercollider#3537]
I'm currently using the last 32 bits version of linux, but when i try to type nothing happens, then i switch from desktop 1 to desktop 2 and back i can type, but if i click on the brackets window i can't type again.

It is just installed without any extension, What could it be?

**Comment by brianlheim** [comment]
Hi @stain2608 - are you sure you've opened this issue on the right project? This isn't the Brackets repository.

If so, can you please give more details about the issue you're seeing? The Linux distribution, whether you're seeing this in the IDE or sclang CLI, and maybe give some very clear instructions for how to reproduce this bug? Thanks in advance.

**Comment by brianlheim** [comment]
Closing, lack of info.
