### ISSUE TITLE
`load(path)` fails if file ends with newline or semicolon

### ISSUE THREAD

**Issue by telephon** [supercollider/supercollider#3541]
This happens when you use `load(…)` to compile some supercollider script file.

A file that ends with newlines:

```
"
);

"
```

`compile` throws an error:

```
ERROR: syntax error, unexpected ';', expecting $end
  in interpreted text
  line 165 char 2:

  );
   ^
  
-----------------------------------
ERROR: Command line parse failed
-> [ nil ]
```

This is in the `prCompileString` primitive.

A file that has no newline or semicolon at the end is fine.

**Comment by telephon** [comment]
This is a bug, because `load()` should be valid for all strings that are valid for `interpret`.

```supercollider
"( ); \n\n\n".interpret
```

**Comment by jamshark70** [comment]
@telephon -- Is this still an issue?

It doesn't happen in Linux -- e.g., a file containing

```
(1+1);

```

is fine.

Or perhaps it's something specific about the file that you were loading at the time.

**Comment by telephon** [comment]
thanks for asking!  it seems to have gone away, I can't reproduce it anymore.
