### ISSUE TITLE
Server fails to boot after Windows 10 Update

### ISSUE THREAD

**Issue by trampbunny** [supercollider/supercollider#3542]
I the the following error when I try to boot.

I also have no 'zombie' synth, I checked Task Manager

Here's the error
 An attempt was made to access a socket in a way forbidden by its access permissions
RESULT = 1

Thanks

**Comment by brianlheim** [comment]
@trampbunny are you still experiencing this? You might want to try asking on sc-users, someone will be able to help you more quickly there.

**Comment by trampbunny** [comment]
No, I turned off my firewall completely and restarted and now it works fine!

**Comment by brianlheim** [comment]
Great, thanks for the update!

**Comment by vivid-synth** [comment]
Maybe we need to include a note about this in the Windows instructions?

**Comment by jamshark70** [comment]
There must be a way to configure the Windows firewall to allow SC to operate. I don't even like to run Linux without a firewall, let alone Windows.

**Comment by brianlheim** [comment]
> Maybe we need to include a note about this in the Windows instructions?

Specifically about what to do when seeing this error after updating windows? Couldn't hurt I guess.

> There must be a way to configure the Windows firewall to allow SC to operate.

Yes, there is.
