### ISSUE TITLE
No way to use a system provided hidapi library.

### ISSUE THREAD

**Issue by Apteryks** [supercollider/supercollider#3559]
The build system currently always use the bundled hidapi copy. It should be possible to provide it from the system, the same way the build system automatically detects and use a system provided icu4c library instead of the bundled 'icu' one.

Unbundling is desirable because it reduces maintenance burden on software distributions (as well as cutting down the size of the software packages and making build times faster).

**Comment by brianlheim** [comment]
Normally I'd agree but our org's hidapi fork is significantly ahead of signal11's hidapi master, and contains important fixes for multiple platforms. The upstream here seems to be pretty stale (no merges in 2 years).

**Comment by Apteryks** [comment]
Hello Brian!

I see! Thanks for explaining. Have the changes been sent to hidapi upstream so that they might merge it in?

Thanks again!

**Comment by brianlheim** [comment]
Like I said, upstream is kind of dead at this point. https://github.com/signal11/hidapi

They have 50 unmerged PRs and the last commit to master was 2 years ago.

**Comment by brianlheim** [comment]
This is all to say I think this issue is valid but probably low-priority for us. hidapi is a small library and doesn't take long to build; the 3rd party libs that really drag our build times in my observation are Boost's, portaudio, and to a lesser extent yaml-cpp.

**Comment by sensestage** [comment]
The extensions for SC on the hidapi library are quite substantial,
involving the parsing of the hid descriptor.
The purpose of the original hidapi library was more toward custom-made
devices for which people would write their own software to read, so our
extensions are also unlikely to fit into the purpose of the hidapi library.

**Comment by Apteryks** [comment]
I see, it makes sense. Thank you for taking the time to explain. Feel free to close this issue.
