### ISSUE TITLE
Error message flooding on failed RTAlloc with JACK

### ISSUE THREAD

**Issue by nhthn** [supercollider/supercollider#3563]
running the following code:

    { DelayN.ar(DC.ar(0), 1000) }.play;

attempts to allocate 1000 seconds of delay line memory. it doesn't crash the server (unlike some ugens -- see #782). it prints an error message:

    JackDriver: exception in real time: alloc failed, increase server's memory allocation (e.g. via ServerOptions)

the problem is not the message, but the rate -- it *floods* the post window as long as the ugen is running. it should only print once.

**Comment by snappizz** [comment]
this just came up for me again. a user error in this case, but i think there's overall room for improvement in the user feedback here. in addition to fixing the message flooding, it would be awesome if we had a meter that keeps track of RT memory use so a concerned user can anticipate such problems. (i'm just leaving this comment as a note to self to investigate this at some point)
