### ISSUE TITLE
checksum change for 3.9.1 assets?

### ISSUE THREAD

**Issue by dvzrv** [supercollider/supercollider#3565]
Has there been a change in the assets for the 3.9.1 release?
I have downloaded the `SuperCollider-3.9.1-Source-linux.tar.bz2` on February 8th 20:42 (UTC+1) with a sha512sum of `cd18f250f53c576a6636b98f2c53d0a2d58e885b37b2612d227a7e8043e14b2840e34a32bcfa69a04da56cc9ef96a1e5aa1cd8de15e54db65ace665a1dd0770b` and have been doing the package build tests for Arch Linux with it since then.

However, it seems the current asset has a sha512sum of `01652f61498c84bf1b7c18ebe091794539d8f9cbb2112a04d0cb9d8b2e7f226d9876cffc76f6fa5519528c243c3ccc1380ace3bef5d70ff85e2bf32337b3d483`!

This breaks reproducible builds and leads to [downstream bugs](https://bugs.archlinux.org/task/57767). Please don't change the assets without notification of some sort!

**Comment by Scimmia22** [comment]
It also leaves people wondering if the tarball has been compromised. Bad idea all around.

**Comment by dvzrv** [comment]
Err... so I guess I've been building something like 3.9.0 plus a few commits, judging from the attached diff. oO
[version.diff.txt](https://github.com/supercollider/supercollider/files/1797737/version.diff.txt) (-a is my above mentioned tarball -b is the current tarball).

However, the file I have been using is also not 3.9.0 as that has a sha512sum of `52274ce0c5e604e44f844e77bb7245d6829c49a002ac0c383c3d150f48c60bd79b8f0481cd629e13544d6a01f2c5fd05d92d24d2c24602df2bf798cff94c0b0f  SuperCollider-3.9.0-Source-linux.tar.bz2`

Please shine some light on this!

**Comment by brianlheim** [comment]
@snappizz

**Comment by snappizz** [comment]
yes, sorry, the Linux source tarball was reuploaded because i had initially uploaded the wrong version (#3516).

**Comment by dvzrv** [comment]
@snappizz hmm, why is this possible, when using the package script for the assets?
the script should circumvent issues like this one. It has cost me quite some time figuring out what was wrong while poking around #3513.

As a sidenote: Please review my assets script for sc3-plugins (which should be able to circumvent this sort of issues).

**Comment by brianlheim** [comment]
the package script is run manually by the release manager and the zip archive can be renamed. we ought to automate that as we do for the macos and Windows binaries and make a strict rule of not touching that asset. We could also publish the checksums and add distinct assets for cases like the issue linked above. I admit that I've also reuploaded binaries for the macos and Windows releases but this seems somewhat different to me as (1) the binaries are not signed anyway and (2) no packaging process relies on those checksums.
