### ISSUE TITLE
supernova priority and affinity win32

### ISSUE THREAD

**Issue by sonoro1234** [supercollider/supercollider#3568]
I have managed to set thread priority and affinity in win32 but performance seems worse.
what should be done in win32 for supernova to work?

**Comment by brianlheim** [comment]
We don't officially support supernova on Windows right now. Sorry, but there's nothing I can do to help with this.

**Comment by sonoro1234** [comment]
are this warnings relevant?
```
Scanning dependencies of target LFUGens_supernova
[ 76%] Building CXX object server/plugins/CMakeFiles/LFUGens_supernova.dir/LFUGens.cpp.obj
In file included from C:/supercolliderrepos/scfork/supercollider/external_libraries/nova-simd/vec.hpp:36:0,
                 from C:/supercolliderrepos/scfork/supercollider/external_libraries/nova-simd/simd_memory.hpp:
26,
                 from C:\supercolliderrepos\scfork\supercollider\server\plugins\SIMD_Unit.hpp:26,
                 from C:\supercolliderrepos\scfork\supercollider\server\plugins\LFUGens.cpp:23:
C:/supercolliderrepos/scfork/supercollider/external_libraries/nova-simd/vec/vec_sse.hpp:58:30: warning: ignori
ng attributes on template argument '__m128 {aka __vector(4) float}' [-Wignored-attributes]
     vec_base<float, __m128, 4>
                              ^
C:/supercolliderrepos/scfork/supercollider/external_libraries/nova-simd/vec/vec_sse.hpp:62:38: warning: ignori
ng attributes on template argument '__m128 {aka __vector(4) float}' [-Wignored-attributes]
     typedef vec_base<float, __m128, 4> base;
                                      ^
In file included from C:/supercolliderrepos/scfork/supercollider/external_libraries/nova-simd/vec.hpp:42:0,
                 from C:/supercolliderrepos/scfork/supercollider/external_libraries/nova-simd/simd_memory.hpp:
26,
                 from C:\supercolliderrepos\scfork\supercollider\server\plugins\SIMD_Unit.hpp:26,
                 from C:\supercolliderrepos\scfork\supercollider\server\plugins\LFUGens.cpp:23:
C:/supercolliderrepos/scfork/supercollider/external_libraries/nova-simd/vec/vec_sse2.hpp:51:32: warning: ignor
ing attributes on template argument '__m128d {aka __vector(2) double}' [-Wignored-attributes]
     vec_base<double, __m128d, 2>
                                ^
C:/supercolliderrepos/scfork/supercollider/external_libraries/nova-simd/vec/vec_sse2.hpp:53:40: warning: ignor
ing attributes on template argument '__m128d {aka __vector(2) double}' [-Wignored-attributes]
     typedef vec_base<double, __m128d, 2> base;
                                        ^
```

**Comment by sonoro1234** [comment]
I have remaked my groups settings: I am using now par_groups to paralelize not only polyphony of one instrument, but all instruments are now in the same par_group and the change in performance between scsynth and supernova is giant.
In my experience is better dont setting neither priority nor affinity.

**Comment by sonoro1234** [comment]
@jamshark70 It seems to me that in ddwMixerChannel there is one ParGroup per channel (synthgroup)
Perhaps could be tried to have only a ParGroup for all channels to paralelize

**Comment by jamshark70** [comment]
> Perhaps could be tried to have only a ParGroup for all channels to paralelize.

No, because there can be signal processing dependencies between channels: submixes and sends. Parallelizing across those dependencies would be wrong.

It's not a high priority for me to analyze the dependencies and figure out which channels may be embedded in a parallel group, sorry.

**Comment by telephon** [comment]
sorry, can you explain? (do you mean "having as subgroups"?)

**Comment by sonoro1234** [comment]
````
ParGroup
      Group
          Instrument
          channel
          send
      Group
          ParGroup
               Instrument
               Instrument
          channel
          send

````

**Comment by dyfer** [comment]
Hey @sonoro1234 
I'm working on fixing supernova's msvc build and as I noticed these warnings when starting SN I was wondering about the thread priority and affinity on Windows. I'd be curious to see the changes you've made to set affinity/priority to see if on my system that also results in worse performance. Cheers!

**Comment by sonoro1234** [comment]
here are the changes for priority
https://github.com/sonoro1234/supercollider/commit/30279c870ea8112d416d80f4d024c085d4d4c4a8

also made changes for affinity in nova-tt but did not saved then anywhere when I saw that performance got worse.

**Comment by dyfer** [comment]
> also made changes for affinity in nova-tt but did not saved then anywhere when I saw that performance got worse.

I see. I think these changes were the ones I was interested to see, the ones in `server.cpp` don't seem to have any actual thread functionality.

I'm just getting fairly poor performance on my Windows 10 machine (seems worse than scsynth, load would go up and down depending on other processes or something else?). I think I need to investigate further...

Thanks!
