### ISSUE TITLE
almost integers are rendered to look like integers

### ISSUE THREAD

**Issue by aspiers** [supercollider/supercollider#3573]
Here's another tricky gotcha which just sucked up a couple of hours of my time!

    (1000000 - 1e-10).postln            // shows 1000000
    (1000000 - 1e-10).asInteger.postln  // shows 999999!

Obviously `asInteger` is rounding down here.  I think this highlights a conflict caused by the stored precision being greater than the precision rendered:

    (1000000 - 1e-8).postln  // shows 999999.99999999
    (1000000 - 1e-9).postln  // shows 1000000!

Firstly, why is the rendered value using less precision than the stored value?  Secondly, wouldn't it be less misleading for the last case here to show `1000000.0000000` rather than something which looks just like an integer?  By truncating the decimal point and everything after it, IMHO it implies that the *stored* value is as close to the integer 1000000 as it possibly could be given the internal precision available to Floats.

This is kind of related to #3570, since if we had C-style `printf` with `%.9f` then there'd be no risk of Floats being accidentally masquerading as integers.

BTW, here's a slightly entertaining and vaguely related fact which you might or might not already know: "almost integers" are [actually a thing](https://en.wikipedia.org/wiki/Almost_integer) ;-)

**Comment by jamshark70** [comment]
If we print floats with full precision, you'll have a surprise for values like 0.1 which are finite decimals but infinitely repeating in binary.

There's no ideal solution. I vote for: live with it.

**Comment by aspiers** [comment]
Argh yeah, I forgot about that annoying "feature" of mathematics ;-)  But the main thrust of my suggestion was not that floats should be printed with full precision, merely that they are never masqueraded as integers.  Let's take a look how other languages handle it:

```
$ python
Python 2.7.13 (default, Jan 03 2017, 17:41:54) [GCC] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> 1000000 - 1e-10
999999.9999999999
>>> 1000000 - 1e-11
1000000.0
```

```
$ irb
2.4.1 :001 > 10000 - 1e-12
 => 9999.999999999998
2.4.1 :002 > 10000 - 1e-13
 => 10000.0
```

I think this is a good approach, because it makes it clear that a Float is always a Float, even when it's so close to being an integer that there is no numerical difference at the rendered precision.

**Comment by brianlheim** [comment]
#3585
