### ISSUE TITLE
": table of contents" in the popout

### ISSUE THREAD

**Issue by prko** [supercollider/supercollider#3576]
Hi,
Every popup indicates the tail:
": table of contents"
in the top of the popout.
It is very complicated when the title is long.
Could it be removed or showed with a smaller size?
![2018-03-14_22-06-41_scide](https://user-images.githubusercontent.com/416281/37404059-14ad0aa8-27d4-11e8-93c8-cd84aaf854b8.png)

**Comment by telephon** [comment]
I think everyone sees that it is a TOC, so it would be fine with me to just remove that bit.

**Comment by telephon** [comment]
It's here: https://github.com/supercollider/supercollider/blob/develop/SCClassLibrary/SCDoc/SCDocRenderer.sc#L258

**Comment by prko** [comment]
`		<< "<div id='toctitle'>" << displayedTitle << ": table of contents</div>\n"`
may be changed as follows:
`		<< "<div id='toctitle'>" << displayedTitle << ":</div>\n"`

**Comment by brianlheim** [comment]
@prko Feel free to submit a PR if you have time!

**Comment by prko** [comment]
I did!
;}

**Comment by brianlheim** [comment]
@prko - a PR is different from posting the change you want in this thread. You can read about how to do it [here](https://github.com/supercollider/supercollider/blob/develop/CONTRIBUTING.md#pull-requests) if you're interested.

**Comment by prko** [comment]
Oh, sorry for changing the online document.
I will test submitting a PR and see if I can do it.
Thank you.

**Comment by patrickdupuis** [comment]
Fixed in #3590.
