### ISSUE TITLE
help search misses results

### ISSUE THREAD

**Issue by aspiers** [supercollider/supercollider#3578]
If I search the help for `classvar`, `Writing Classes` is not shown as a match despite that being the only place I can find where `classvar` is really explained.

**Comment by telephon** [comment]
yes, it is unfortunately not a full text search. I'm often tricked by this.

**Comment by brianlheim** [comment]
This is a dupe of #3030.

**Comment by aspiers** [comment]
Oops missed that, sorry for the noise!
