### ISSUE TITLE
const is not documented

### ISSUE THREAD

**Issue by aspiers** [supercollider/supercollider#3579]
I see `const` used to define constants in classes such as `Char`, but I don't see it documented anywhere.  I think it should at least be mentioned in `Writing Classes`.

**Comment by aspiers** [comment]
In particular:

- From where can the constant be accessed?
- How should it be accessed?
- Can it be used in other class-level assignments? (AFAICS the answer is no)

**Comment by gusano** [comment]
@aspiers `const` is used like in most programming languages constants:

- they can be accessed from anywhere in the class or in a subclass
- they cannot be set (altered), but you can get their values

From https://en.wikipedia.org/wiki/Constant_(computer_programming):
> In computer programming, a constant is a value that cannot be altered by the program during normal execution, i.e., the value is constant. ... This is contrasted with a variable, which is an identifier with a value that can be changed during normal execution, i.e., the value is variable

```js
// Lol.sc
Lol {
  const <foo = "foo";
  const <bar = "bar";

  constants {
    [\foo, foo].postcs;
    [\bar, bar].postcs;
  }
}

// try it
l = Lol();
l.foo;
l.bar;
l.constants();
```

**Comment by aspiers** [comment]
@gusano Thanks, personally I'm well familiar with constants ;-)  But you did answer my third question ("Can it have a read accessor outside the class?").  However I was trying to make two other points:

1. `const` should be documented, not just for those who aren't familiar with the basics of constants, but also to cover the finer details which are being discussed here, including:
2. Apparently constants *can't* be used as default values for class or instance variables, as hinted at by my previous comment and explicitly shown [here](https://github.com/supercollider/supercollider/pull/3569#issuecomment-373504134).

**Comment by scztt** [comment]
This is a good task - I think it would first require figuring out what exactly const DOES :)
I actually only just noticed that it exists a few months ago, after 10+ years of using SuperCollider....

**Comment by aspiers** [comment]
BTW in case anyone hasn't already seen this trick, it's a nice way to tie issues and PRs together: https://help.github.com/articles/closing-issues-using-keywords/

**Comment by brianlheim** [comment]
@aspiers - we usually do that! But, when the issue gets merged into a non-main branch (i.e. 3.9, as #3605 was), the issue won't be closed. IIUC, to get the closing thing to work, the commit (not the PR) has to reference the issue, and then it's only closed once merged into develop.

**Comment by aspiers** [comment]
Oh yeah, good point :-)
