### ISSUE TITLE
Notify arbitrary client OR SendReply to specific Address

### ISSUE THREAD

**Issue by bennigraf** [supercollider/supercollider#358]
It would be great to have a way to send OSC messages directly from the server to any client to send i.e. bus values or other data from any Ugen to control interfaces like TouchOSC.

Right now a client has to register to the server, where one can then use the SendTrig oder SendReply Ugen. But for example TouchOSC cannot register itself. So it would be helpful if 

a) one could add clients to be notified "externally" with an IP-Address and Port, for example add TouchOSC on iPad X as notify-client to Server on Laptop Y from SCLang on Laptop Y.

Or:

b) Create the possibility to give SendReply an IP-Address/Port to send to (or create an extra Ugen for that).

This feature has been requested a couple of times now on the list, i.e. in this thread:
http://new-supercollider-mailing-lists-forums-use-these.2681727.n2.nabble.com/Sending-OSC-from-server-to-another-app-tt7579249.html#none

**Comment by vivid-synth** [comment]
@bennigraf have you found another way to solve this problem?

**Comment by bennigraf** [comment]
Hi @vivid-synth ,
I don't remember exactly what I did in this case, but from today's perspective I'd also say that's not necessarily something that needs to be implemented server side. Instead you could have a simple synth that automatically (with a Trig.kr, not by polling from the language!) sends values via the existing methods to the language and use the latter as a proxy to send data to other apps. I'm pretty sure I went that way back then. Also note that for displaying values in a GUI 15-20 fps usually are enough ;-). (In my setup with TouchOSC on the iPad 2, the WiFi is usually the bottleneck in both latency and bandwidth.)

**Comment by brianlheim** [comment]
@bennigraf Do you mind if I close this? We could open a new issue to make it easier to do the setup you're describing language-side.

**Comment by bennigraf** [comment]
Hey,

I don't mind at all. Also I think the solution using the lang as "proxy" is easy enough to implement already and don't see the requirement to open another issue. SendTrig/SendReply/OSCFunc/Netaddr all are already there ;-).

Thanks for following up,
Benjamin.

**Comment by brianlheim** [comment]
Awesome, thanks!
