### ISSUE TITLE
Windows shortcuts in class lib or extensions dir are ignored

### ISSUE THREAD

**Issue by jleben** [supercollider/supercollider#36]
[Issue migrated from SourceForge | ID: 1870525 | Submitted by 'jamshark70']
[http://sourceforge.net/support/tracker.php?aid=1870525]

If I put a shortcut to a folder into the userExtensionsDir in Windows, .sc files referenced by the shortcut are not compiled.

Among other problems, if there is ever an effort to make Quarks windows-compatible, this shortcoming would prevent Quarks from working altogether because installing a quark would create a shortcut in Extensions to the real quark directory.

**Comment by bagong** [comment]
As not even aliases on Mac are supported properly, one might chose to ignore this, and just make sure the LangConfig include folders work properly on Windows. This seems to be the case. I get both classes and help files from a folder included via LangConf (in help files there seem to be issues parsing links, not seen on other platforms - probably a general Windows issue).

**Comment by bagong** [comment]
Close?
