### ISSUE TITLE
[Code Style] Document how If statements should be written

### ISSUE THREAD

**Issue by patrickdupuis** [supercollider/supercollider#3600]
Class files often contain multiple code styles. Our Code Style Guide would benefit from clarifying our style preferences with regards to If statements. My recommendation would be :
- If a file has a dominant style, write If statements to match.
- If a file has no dominant style, write If statements like so:
  ```
  if (condition) { 
      trueBlock
  } {
      falseBlock
  }
  ```

**Comment by telephon** [comment]
yes!
just a minor thing, usually, we have no space after messages:


```
if(condition) { 
    trueBlock
} {
    falseBlock
}
```

**Comment by patrickdupuis** [comment]
Oh! I added the space thinking that it was correct. Personally, I think prefer it this way.

**Comment by telephon** [comment]
both are OK, and you are right that sometimes it looks better.

```

if(7 < 0) { this } { that }
if (7 < 0) { this } { that }

max(7, 0)
max (7, 0)

sum([1, 2, 6, 7]) { |i| i.squared }
sum ([1, 2, 6, 7]) { |i| i.squared }

```

I have to say, even though I've so far used the first versions, now that you say it, the second is probably nicer: it balances the whole expression better.

**Comment by brianlheim** [comment]
I prefer it as Patrick has it. We can have this discussion on a new issue, but I think in general any message whose argument list ends in one or more code blocks should not wrap them in the parens of the main parameter list: do, collect, if, while, etc.

I think multiline is only necessary if the branches are complex (if either has more than one method call or more than one statement; this is heuristic but an OK rule of thumb IMO). I agree with Patrick's style for multiline except for the space in `if (`.

The style consistently shown in our docs and codebase is that we don't put a space before the argument list left paren. I strongly prefer to keep it that way.

**Comment by brianlheim** [comment]
documented [here](https://github.com/supercollider/supercollider/wiki/Code-style-guidelines#trailing-closure-syntax)
