### ISSUE TITLE
[suggestion/improvement/enhacment] - supercollider/supercollider - github release page - include linux binaries

### ISSUE THREAD

**Issue by tmm2018** [supercollider/supercollider#3601]
SUBJECT: [suggestion/improvement/enhacment] - supercollider/supercollider - github release page - include linux binaries

IMHO, it would be important to:
- include linux binaries in supercollider releases in github

main motivation behind such:
- making it easier for linux users, to install supercollider, without having to wait for it to compile

**Comment by snappizz** [comment]
closing as duplicate of #2917.
