### ISSUE TITLE
[suggestion] - supercollider/supercollider - updating linux repositories (current version is only 3.6)

### ISSUE THREAD

**Issue by tmm2018** [supercollider/supercollider#3602]
SUBJECT: [suggestion] - supercollider/supercollider - updating linux repositories (current version is only 3.6)

Greetings

IMHO it would be important to:
- update linux repositories after version 3.6 (the currently available option at least in apt-get)

You can always download the souce and install it but:
- 1st) it's a very tedious process and takes a lot of time (doesn't mean it isn't worth it) - and i am sure, it is
- 2nd)  it should be available "from scratch" / "OOB"

I know i already pointed this about debian, and i got a reply from @snappizz saying that it was already being handled. but it was like two or three months, and it isn't stll. i know it takes time and effort, and it's not such an easy thing, but that's something that must be handled

thank you so much for everything, friends

**Comment by brianlheim** [comment]
This is a known issue and fits into #2917. Thanks for your report but please, if an issue already exists, just leave a comment there.
