### ISSUE TITLE
parseYAML for parsing JSON is misleading

### ISSUE THREAD

**Issue by diegodorado** [supercollider/supercollider#3609]
It would be better for newcomers to have a parseJSON function aliasing parseYAML .... it doesnt make sense to parse json with a parseYAML function

**Comment by telephon** [comment]
Also for non-newcomers. But if YAML is a  superset of JSON, is this the correct assumption?

**Comment by diegodorado** [comment]
I t seems so, I wasn't aware of that: 
http://yaml.org/spec/1.2/spec.html#id2759572

Anyway I stiil think that an parseJSON alias won't harm

**Comment by brianlheim** [comment]
I think this is a good suggestion. Feel free to submit a patch!
