### ISSUE TITLE
Implicit string concatenation is broken in SCDoc code fields

### ISSUE THREAD

**Issue by telephon** [supercollider/supercollider#361]
In the help code field, strings that exceed a single line and should be concatenated by the interpreter do not behave properly.

An example is in Semaphore.help:

    "thread 2> this took until the other thread has released the semaphore. "
    "Blocking for 4 seconds.".postln;

Which returns:

SCHelp
• ERROR: syntax error, unexpected STRING, expecting $end
  in file 'selected text'
  line 2 char 33:

  † † † † "Blocking for 4 seconds.".postln; 
##            ^^^^^^^^^^^^^^^^^^^^^^^^

• ERROR: Command line parse failed
nil

**Comment by telephon** [comment]
Reproduced just now.

**Comment by brianlheim** [comment]
Best guess - the SCDoc renderer is using non-breaking spaces to indent the lines. I copied the line in question and reduced it to this:
```supercollider
a = "\"
        \"."
```

When I run `a.ascii` I get this:
```supercollider
[ 34, 10, -62, -96, 32, -62, -96, 32, -62, -96, 32, -62, -96, 32, 34, 46 ]
```

Also, I copied and pasted that text into this [encoding converter](https://www.percederberg.net/tools/text_converter.html) as 'plaintext ASCII' and the UTF-8 result is
```
"thread 2> this took until the other thread has released the semaphore. "
Â  Â  Â  Â  "Blocking for 4 seconds.".postln;
```
which seems to be [the signature move of &nbsp;](http://stackoverflow.com/questions/1461907/html-encoding-issues-%C3%82-character-showing-up-instead-of-nbsp).

So either (1) the HTML renderer needs to change (not sure how we'll render indentation without non-breaking spaces) or (2) this is an issue with the lexer not being able to handle Unicode strings, which it probably never will. Does anyone know if there's any easy way to do (1)?

**Comment by brianlheim** [comment]
Actually, I think it may be better to shoot for lexing in UTF-8. Then a nbsp would be interpreted as Unicode whitespace, and this would all make sense.

**Comment by telephon** [comment]
yes, UTF-8 may be a good direction anyhow. 

But normally, all sclang code in the IDE is tabs, so this is a source of possible inconsistent format when you copy from a helpfile.

**Comment by brianlheim** [comment]
> this is a source of possible inconsistent format when you copy from a helpfile.

That's a fair point, and because there are nbsp's in the source code copied, forcing a retab doesn't get rid of them.

**Comment by telephon** [comment]
fixed.
