### ISSUE TITLE
Strangeness of Env: its behavoiur and documentation

### ISSUE THREAD

**Issue by prko** [supercollider/supercollider#3629]
Hi,

I found a strangeness of the Env class.

The loop defined in the code below works:
```supercollider
{ RLPF.ar(Blip.ar(100, 200!2, 0.5), Env([300, 600, 1200, 1800], [1, 1, 1], \exp, 2, 0).kr.poll) }.play
```
However, the loop defined in the code below does not work:
```supercollider
{ RLPF.ar(Blip.ar(100, 200!2, 0.5), Env([300, 600, 1200], [1, 1], \exp, 2, 0).kr) }.play
```

As far as I understand, the loop node and release node are the indexes of the level array [300, 600, 1200, 1800].
I.e., the release node 2 is 1200, and loop node 0 is 300.
I don't understand why the second code does not loop even if it has the both of its release node and loop node in the level array.

It seems to be a bug.

Furthermore, the first code seems to not work as described in the help document.

The third code block in the "Examples" section of  the Env help document begins with the following paragraph:
> If a loop node is given, the EnvGen outputs the nodes between the loop node and the release node (not including the release node itself) until it is released:

According to the quotation, the Env in the first code must loop
- between 300 (including 300 itself) and 1200 (not including 1200 itself)

or

- between 300 (including 300 itself) and 600 (including 600 itself).

However, it loops between 1200 to 600. The post window output of the first code evaluation is as follows:
> -> Synth('temp__174' : 1768)
> UGen(EnvGen): 300.302	// ca. 300
> UGen(EnvGen): 321.888
> UGen(EnvGen): 345.026
> ...
> UGen(EnvGen): 1046.55
> UGen(EnvGen): 1121.78
> UGen(EnvGen): 1197.59	// ca. 1200
> UGen(EnvGen): 1117.28
> UGen(EnvGen): 1043.4
> ...
> UGen(EnvGen): 687.972
> UGen(EnvGen): 641.836
> UGen(EnvGen): 601.208	// ca. 600
> UGen(EnvGen): 644.424
> UGen(EnvGen): 690.052
> ...
> UGen(EnvGen): 1046.55
> UGen(EnvGen): 1121.78
> UGen(EnvGen): 1197.59	// ca. 1200
> ...

The post window output of the following code (loop node is removed from the first code.)

``supercollider
{ RLPF.ar(Blip.ar(100, 200!2, 0.5), Env([300, 600, 1200, 1800], [1, 1, 1], \exp, 2).kr.poll) }.play
``
is as follows:

> -> Synth('temp__175' : 1773)
> UGen(EnvGen): 300.302
> UGen(EnvGen): 321.888
> UGen(EnvGen): 345.026
> ...
> UGen(EnvGen): 976.371
> UGen(EnvGen): 1046.55
> UGen(EnvGen): 1121.78
> UGen(EnvGen): 1200
> UGen(EnvGen): 1200
> UGen(EnvGen): 1200

Please compare them. 
The loop node and release node seem to not correctly work... 

There is one more thing to say.
I think the terminologies here are too difficult to grasp when learning this concept.
I think the following terms would be much easier:
- sustainIndex instead of releaseNode
- loopStartingIndex instead of loopNode

How do you think about it?
I have been not sure of these things. There might be my misunderstanding here, but the evaluation results show that my unsureness is not only my misunderstanding.

I would be happy if this is reviewed and reflected in the next version of SC.

**Comment by prko** [comment]
Probably, I have been misunderstanding the loopNode.
According to the example code in the help document:

> // release node is node 2, loop node is node 0: so loops around nodes 0 (lvl 1, dur 0.5)
> // and 1 (lvl 0.1, dur 0.5)         //until released after 3.5 seconds
> Env.new([0,1,0.1,0],[0.5,0.5,2], 'lin', 2, 0).test(3.5).plot;  

The loop node starts from the second item of the level array.
Is it right?
Then the loop of the first code is correct.

However, I still don't understand why the second code does not loop.

Is it not confusing that the loop node starts from the level array index number one while the release node starts from the level array index number zero?

**Comment by jamshark70** [comment]
> Is it not confusing that the loop node starts from the index number one of the level array in an Env while the release node starts from the index number zero of the same array?

This is a common misunderstanding. We often think an envelope segment goes from level A to level B, and the next segment from B to C. But that's not correct. An envelope segment always goes from *the envelope's current output level* to the segment's target level.

An envelope segment has no fixed, unchanging start level. If it did, it would be impossible to jump early to the release segment, or to loop back.

But, when the EnvGen starts, it has no current level at first. So the Env provides one extra level, at the beginning. `levels[0]` initializes the EnvGen, and then this level is never touched again. So, `levels[0]` doesn't correspond to any envelope node. It's only a start value. The first envelope segment goes *to* `levels[1]`.

**Comment by prko** [comment]
Thank you for the explanation.
According to your mention, Env class works correctly.
In the first code
```supercollider
{ RLPF.ar(Blip.ar(100, 200!2, 0.5), Env([300, 600, 1200, 1800], [1, 1, 1], \exp, 2, 0).kr) }.play
```
the value of the release node is 1800 and the value of the loop node is 600.
Thus it correctly loops between 600 and 1200.
 
The second code
```supercollider
{ RLPF.ar(Blip.ar(100, 200!2, 0.5), Env([300, 600, 1200], [1, 1], \exp, 2, 0).kr.poll) }.play
```
cannot loop because it does not have the release node. 
In y opinion, it would be nice in this case if sclang gives feedback with a warning message as follows:
> Warning: release node does not exist. a loop is not available.

However, the warning message might make the behaviour of sclang inconsistent because sclang does not give a warning or an error in the following code:
```supercollider
[1,2,3][3]
```
> -> nil

The half of this issue was written from my misunderstanding. I am sorry about it.

If you do not agree that using other terms instead of releaseNode and loopNode will be helpful for the user's understanding, this thread can be closed.

**Comment by brianlheim** [comment]
@prko - I would really recommend asking questions like this on the users list or another more user-oriented group before opening an issue here. First, because you're more likely to get a quick response in those places. But secondly and more importantly, because this tracker is for maintainers. We are happy to help with issues, as you've seen in the last couple issues you've opened, but we also appreciate that you'll do some work beforehand to make sure that your issue is clear and legitimate.

> If you do not agree that using other terms instead of releaseNode and loopNode will be helpful for the user's understanding, this thread can be closed.

The terms you suggested are a little better IMO, but changing these parameter names is a breaking change. Given how widespread usage of `Env` is, I think we have to stick to the parameter names. Do you think more explanation in the documentation would help? If so, I propose you close this and open a new issue for only that point, so that people coming to this in the future don't have to reread this discussion.

> I would be happy if this is reviewed and reflected in the next version of SC.

The best way to achieve this, is to submit a pull request yourself with the changes. :) We have good advice on this in our [contributing guide](https://github.com/supercollider/supercollider/blob/develop/CONTRIBUTING.md).

**Comment by prko** [comment]
Yes, I have realised this issue is not proper to this tracker. 
I am sorry for it. 
Changing the parameter names is not a good idea.
I will read the help document carefully once again.
Then I will open another issue only for the documentation or will submit a pull request.

Thank you for your time and kind response.
I close this issue.
