### ISSUE TITLE
Plug-in API for user extensions to editing functionality

### ISSUE THREAD

**Issue by jamshark70** [supercollider/supercollider#363]
I feel really strongly that the sc-ide editor needs to be user-extensible. Nobody could expect Jakob and Tim to implement everything on everybody's wish list for editor behavior -- and my wish list is pretty long! And the options are:
- Do nothing, "Everybody has to give up something" for the sake of standardization. I'm not crazy about that. Actually, I'm crazy against it. It's painful to consider going from an editor that makes the text dance (i.e., Emacs) to an editor based on the point-and-click methodology that's been around since Xerox PARC and which was standardized by the first Mac. The Mac made it intuitive by stripping away powerful but "confusing" features, and now we're stuck with it. It's like giving up a 21-speed racing bike for a three-speed.
- Make the main developers responsible for every feature request. Too much burden on too few people.
- Or, open the API and let clever users build new features themselves.

At this point, I don't have a clear idea what the API would look like or what extension language should be used. For the language, I'd favor a straightforward, easy to learn language like Python or Ruby over Lisp or C++. We'd want to _encourage_ people to write plugins, not scare them away.

Use cases, all of which exist and work nicely in Emacs:
- Version control integration, including commit, diff, revert working copy, blame, log.
- Interactive diff between two documents, without opening a separate tool (ediff-buffers).
- Registers, both for bookmarking locations in files and interactively saving snippets (Cx r spc, Cx r j, Cx r s, Cx r i).
- Kill ring (multiple copy/paste, including pasting any of the last n things that were copied).
- Rectangle selection and manipulation of text (Cx r t, Cx r d, Cx r r to save rectangular text into registers).
- Automatic syntax-aware indentation -- select a block of code, hit a key, and all of it is reindented according to opening and closing brackets. (This isn't 100% perfect in sclang-mode, but it's pretty close, definitely usable.) (C-M-backslash)

If these are implemented as plug-ins (by somebody -- anybody), then users can choose which features they are interested in -- bringing the added benefit of avoiding interface clutter for users who don't need advanced features.

**Comment by brianlheim** [comment]
Pinging. @jamshark70 would you be opposed to adding this to the list of 'stretch goals'? Really doubt it will be done anytime soon.

**Comment by jamshark70** [comment]
Sure, long-term project.

Actually I'm bumping up against this limitation again, where I would really like to have snippets, and/or argument help for custom functions in ddwChucklib-livecode, and the only way to do it now is with a document key action (which rules out tooltips floating above the code, not to mention "interesting" issues with window focus). I've yet to decide whether to stick with a sclang implementation or just jump ship and do live coding in emacs or atom.

**Comment by telephon** [comment]
the simplest first step would be to be able add menu items from sclang that call functions in sclang.

**Comment by snappizz** [comment]
closing as it is unlikely this will happen soon unless someone actively steps up to create this.
