### ISSUE TITLE
allocReadChannel last optional argument is required in supernova

### ISSUE THREAD

**Issue by sonoro1234** [supercollider/supercollider#3631]
allocReadChannel example should read 1 channel but instead it reads two.

**Comment by sonoro1234** [comment]
Must be an sclang error as I get expected behaviour in Lua2SC and scsynth.
@timblechmann With supernova I must set the last optional argument (according to "server command reference") to get the correct behaviour instead of "invalid buffer size"

**Comment by sonoro1234** [comment]
according to this
```
https://github.com/supercollider/supercollider/blob/188c452dd9899d3a0d935f1ceb0165072bb7525e/server/supernova/sc/sc_osc_handler.cpp#L2360
```
It seems that we should not skip last argument in supernova, but also make sure that sclang dont sends completion message as an osc int instead of osc blob

**Comment by telephon** [comment]
>If `completionMessage` is `nil`, then scsynth will parse that as 0 and think it has to read channel 0 in addition to the channel array actually desired.

If `completionMessage` is `nil`, it woudn't be appended in such a case:

```[1, 2, 3] ++ nil```

But what happens is this: 

```[1, 2, 3] ++ [nil]```

So this will then become

```[1, 2, 3, nil]```

and by interpretation of nil as zero:

```[1, 2, 3, 0]```

It would be better to write:

instead of:
```
	^["/b_allocReadChannel", bufnum, path, startFrame, (numFrames ? -1).asInt] ++ channels ++ [completionMessage.value(this)]
```
better:
```
	completionMessage !? { completionMessage = [completionMessage.value(this)] };
	^["/b_allocReadChannel", bufnum, path, startFrame, (numFrames ? -1).asInt] ++ channels ++ completionMessage
```

(untested)

**Comment by jamshark70** [comment]
That won't be right. The completion message must stay an array:

```
// not ok
[1, 2, 3] ++ [\msg, 4] = [1, 2, 3, \msg, 4]

// ok
[1, 2, 3] ++ [[\msg, 4]] = [1, 2, 3, [\msg, 4]]
```

**Comment by telephon** [comment]
if it is an array and not nil, it'll stay an array.

**Comment by jamshark70** [comment]
> if it is an array and not nil, it'll stay an array.

No, that isn't how the concatenation operator works.

```
a = [\aCompletionMsg, 0, 1];
c = [0];

["/b_allocReadChannel", 0, "/abc/def", 0, -1] ++ c ++ a
-> [ /b_allocReadChannel, 0, /abc/def, 0, -1, 0, aCompletionMsg, 0, 1 ]

// ^^ that is a flat array.
// There is no way to know that (aCompletionMsg, 0, 1) belong together

["/b_allocReadChannel", 0, "/abc/def", 0, -1] ++ c ++ [a]
-> [ /b_allocReadChannel, 0, /abc/def, 0, -1, 0, [ aCompletionMsg, 0, 1 ] ]

// ^^ this is the right format for a completion message:
// note that the second of these is what Buffer.readMsg does:
Buffer.new(s, 2048, 1, 1000).readMsg("/abc/def", 0, -1, 0, false, { |buf| buf.queryMsg })
-> [ /b_read, 1000, /abc/def, 0, -1, 0, 0, [ b_query, 1000 ] ]
```

**Comment by telephon** [comment]
I suggested: 

```supercollider
	completionMessage !? { completionMessage = [completionMessage.value(this)] };
	^["/b_allocReadChannel", bufnum, path, startFrame, (numFrames ? -1).asInt] ++ channels ++ completionMessage
```

this is equivalent with:
```supercollider
(
a = ["/alloc", 7];
a !? { a = [a] };
[1, 2, 3] ++ a
)

// -> [ 1, 2, 3, [ /alloc, 7 ] ]


```

if it is nil:

```supercollider
(
a = nil;
a !? { a = [a] };
[1, 2, 3] ++ a
)

// -> [ 1, 2, 3 ]


```

**Comment by lnihlen** [comment]
Thinking of looking in to this today if nobody else is.

**Comment by lnihlen** [comment]
Uploaded for feedback. I'm relatively new to supercollider programming but to me providing no arguments or an empty array to ```channels``` would mean that I am expecting **0** channels to be read from the audio file, instead of one. So that is how the supernova patch is implemented. If ya'll agree happy to fix the documentation and scserver to suit. Or, if there's good reason to keep the current behavior that's fine too.
