### ISSUE TITLE
Server will not boot

### ISSUE THREAD

**Issue by supercollider22** [supercollider/supercollider#3644]
Bug description:
I try to boot the server, and get this message:
Exception in World_New: boost::interprocess::intermodule_singleton initialization failed
RESULT = -1073740791

it was working great yesterday
Steps to reproduce:
1.
2.
3.

Actual result:

Expected result:

**Comment by patrickdupuis** [comment]
What OS and version of SC are you using?

**Comment by brianlheim** [comment]
Dupe of #2409; please add more details there if you have them, @supercollider22 !
