### ISSUE TITLE
Is Platform.resourceDir really necassary?

### ISSUE THREAD

**Issue by prko** [supercollider/supercollider#3661]
Hi,

I have realised that all of the following codes work properly:

```supercollider
"sounds".openOS

(Platform.resourceDir+"/sound/").openOS
```
```supercollider
"sounds/a11wlk01-44_1.aiff".openOS

(Platform.resourceDir+"/sound//a11wlk01-44_1.aiff").openOS
```
```supercollider
b = Buffer.read(s, "sounds/a11wlk01-44_1.aiff")
b.play

c = Buffer.read(s, Platform.resourceDir+/+"sounds/a11wlk01-44_1.aiff")
c.play
```
I think ```Platform.resourceDir +/+``` is unnecessary.
It seems to be better to remove ```Platform.resourceDir +/+``` from all example codes in future help documents.

**Comment by brianlheim** [comment]
Actually, yes this is required, because the cwd is not guaranteed to be the resource directory. We may add the ability to change cwd in future versions, and on macOS the cwd at startup is `/`, so this is a more robust notation.

**Comment by jamshark70** [comment]
AFAIK, you can already set the cwd in the IDE's preferences, so it's already very easy for any user to set up their environment so that examples without resourceDir will fail.

**Comment by prko** [comment]
Thank you for reviewing this!
