### ISSUE TITLE
what is cmd_s_newargs?

### ISSUE THREAD

**Issue by sonoro1234** [supercollider/supercollider#3669]
I saw that exploring the scsynth code and also in "server command reference"

**Comment by brianlheim** [comment]
@sonoro1234, I've asked you multiple times to provide more information when opening issues. Please do this, it's in our main contributing guide.

**Comment by sonoro1234** [comment]
It is just a question of something completely unknown for me!
I dont have more information than: it can be found in "server command reference" and this:
https://github.com/supercollider/supercollider/blob/develop/server/scsynth/SC_MiscCmds.cpp#L847

**Comment by joshpar** [comment]
Please ask this on the sc-dev list. I can answer there. Thanks!
