### ISSUE TITLE
Slider2D background transparency is not as expected

### ISSUE THREAD

**Issue by jamshark70** [supercollider/supercollider#3704]
If view A = `View()` and view B = `View(a, ...)`, and I set B's background color to anything where alpha = 0, I expect the background to be fully transparent -- that is, you should see A's colors coming through the background unmodified.

This works correctly for two View instances, or View and UserView, but it does not work as expected if B is, for instance, a Slider2D.

```
z = Image(10, 10);
10.do { |x| 10.do { |y| z.setColor(Color.gray(1.0.rand), x, y) } };

v = View(nil, Rect(800, 200, 100, 100)).front;
v.setBackgroundImage(z, 10);

u = View(v, v.bounds.moveTo(0, 0)).background_(Color.clear);
u.background = Color(1, 1, 1, 0);
u.background = Color(0.5, 0.5, 0.5, 0);
```

When adding `u` on top of `v`, the display does not change -- `u` is completely transparent.

Continuing:

```
u.remove;

u = Slider2D(v, v.bounds.moveTo(0, 0)).background_(Color.clear);  // darker
u.background = Color(1, 1, 1, 0);  // lighter
u.background = Color(0.5, 0.5, 0.5, 0);  // lower contrast
```

It looks to me like, in this case, alpha = 0 is producing the display I would expect for alpha = 0.5.

I don't have time right now to test all views.

It's funny -- I was trying this approach to work around a bug with #2575 (you can't apply a background image to a Slider2D directly), when... surprise, surprise... I find a bug with the workaround. So close to something kind of cool and then... the only way to get what I really want is to re-implement Slider2D's logic as a UserView...? Fun. (I'll accept the faded colors for now.)

**Comment by jamshark70** [comment]
```
(
var widgets = [Slider, MultiSliderView, Slider2D,
	RangeSlider, Button, PopUpMenu,
	StaticText, ListView, Knob
].clump(3),
views = Array(widgets.size);

w = Window("test", Rect(100, 100, 600, 600));
w.layout = GridLayout.rows(*(
	widgets.collect { |row, i|
		row.collect { |widget, j|
			var new = View();
			views.add(new);
			StaticText(new, Rect(50, 50, 120, 120))
			.background_(Color.white).stringColor_(Color.black)
			.align_(\center).string_("under");
			widget.new(new, Rect(0, 0, 120, 120)).background_(Color.clear);
			new
		}
	}
));

w.front;
)
```

Slider, MultiSliderView, Slider2D, RangeSlider all exhibit this bug.

Button and PopUpMenu do not support transparency at all (perhaps justifiably).

StaticText, ListView and Knob do support transparency.

I can't figure out what is the difference in C++... any Qt gurus know why those 4 views are handling transparency incorrectly?

**Comment by elgiano** [comment]
found the cause: drawing shadows using a hardcoded `alpha=150` version of background color:

https://github.com/supercollider/supercollider/blob/89f9b125a5f8d75996c014c00684a0943ecc3678/QtCollider/style/routines.hpp#L160C5-L166C55

this function drawSunken is used by all the widgets mentioned by @jamshark70 + QcGraph (a.k.a. EnvelopeView)

I don't have time to think about the best way to fix it right now, but I have a local fix that disables shadows if background is not fully opaque.
