### ISSUE TITLE
No need to have the fifth argument 'buttonNumber' of .mouseUpAction?

### ISSUE THREAD

**Issue by prko** [supercollider/supercollider#3715]
Currenty the method .mouseUpAction does not report buttonNumber while the method .mouseDownAction does report buttonNumber.
It seems to be logical to provide the corresponding argument 'buttonNumber' for the method .mouseUpAction as well.
How do you think about it?

**Comment by brianlheim** [comment]
It already gets passed that. See #3765.

**Comment by prko** [comment]
Thank you!
