### ISSUE TITLE
Windows Unicode: /b_read etc. don't work with non-ASCII characters in paths

### ISSUE THREAD

**Issue by jamshark70** [supercollider/supercollider#3719]
Related to #3673 -- my Windows-using students found also that reading a buffer from a file fails if the file path includes Unicode characters.

```
b = Buffer.read(s, "C:/path/to/昨天.wav");
```

(Of course, to reproduce it, you'll have to rename some audio file on your system to include Chinese characters, and provide the correct path.)

The students are using code that gets paths either from the file system (`pathMatch`) or from a GUI file dialog. They aren't typing the paths directly. Typos aren't the issue.

The SC string object becomes part of an OSC message. Then the server has to unpack the message. Somewhere in there (sclang encoding, network transmission, or scserver string encoding) the path is getting garbled.

Windows 10, I believe, with SC 3.9.1 at least.

(Sorry @brianlheim ... we were both hoping these were all gone...)

**Comment by brianlheim** [comment]
Thanks for opening this! I think I mentioned in my PR to fix the other case of this that I had found some more... well, this is one of those cases. Basically just ctrl-f for fopen and those are the spots that need to be updated.

The conference here just ended so i need a few days off to relax, but i'll be back to fix this soon. :)
