### ISSUE TITLE
sc 3.9.3 64-bit: crash booting server on windows 7 pc when inserting USB headset

### ISSUE THREAD

**Issue by shimpe** [supercollider/supercollider#3727]
Supercollider 3.9.3 64-bit  on win7 OS.

Server boots fine without the headset, however when a headset is inserted it causes scsynth.exe to crash when booting the server. (The headset works just fine with other programs on the computer)

Message in the Post window:
Booting with:
  In: MME : Microphone (2- C-Media USB Head
  Out: MME : Speakers (2- C-Media USB Headph
SC_PortAudioDriver: PortAudio failed at Pa_OpenStream with error: 'Device unavailable'
could not initialize audio.
RESULT = 1

Screenshot of the error attached:

![crash](https://user-images.githubusercontent.com/732258/40068858-e7c98306-5869-11e8-87d5-71960480ff5b.png)

(Also I notice the "In" and "Out" device name in the error message is cut off at 37 characters)

**Comment by shimpe** [comment]
@brianlheim should I build a debug version on windows for this? I've never built sc on windows before, but I can give it a try tonight.

**Comment by brianlheim** [comment]
I think you will want to use this: https://support.microsoft.com/en-us/help/241215/how-to-use-the-userdump-exe-tool-to-create-a-dump-file

I've never used it before but it sounds very similar to how core dumps work on Linux. If you do use it please report on it because we might want to include it in our project documentation!

**Comment by brianlheim** [comment]
This also looks relevant, maybe try it first since it doesn't seem to require installing anything. https://blogs.msdn.microsoft.com/calvin_hsia/2013/07/31/scan-the-windows-event-log-for-your-application-crashes-and-hangs/

**Comment by shimpe** [comment]
I know that the "process explorer" tool from Mark Russinovich allows for forcing creation of a dump file.
(side note: I'm starting to think the crash will probably be in port audio more than in scsynth itself)

**Comment by brianlheim** [comment]
Not enough info, closing
