### ISSUE TITLE
Stated License in Readme/file headers unequal to the COPYING file

### ISSUE THREAD

**Issue by Johnnynator** [supercollider/supercollider#3729]
The Copying file is GPLv3 while the Readme and the Headers of the source files I checked are stating GPL-2 or later which is a bit confusing to me.

**Comment by brianlheim** [comment]
This project consists of several subprojects, some of which are licensed "GPLv2 or any later version", some of which are licensed "GPLv3 or any later version." scvim and sced are the main GPLv3+ licensed projects. It is possible to compile the project for release strictly under GPLv2 by using the `-DNO_GPL3` flag.

The READMEs are incorrect, they should state that SuperCollider as a whole is GPLv3+, or give the longer explanation that it is possible for it to be GPLv2 or GPLv3 if desired. The headers and COPYING file are correct. Thanks for pointing this out!

**Comment by brianlheim** [comment]
#3761.
