### ISSUE TITLE
the behaviour of the method .writeDefFile

### ISSUE THREAD

**Issue by prko** [supercollider/supercollider#3730]
Currently, the method .writeDefFile does not update the SynthDef in real time and it is only usable after rebooting. Could it be changed?

[steps]
1. evaluate a new SynthDef with the method .writeDefFile:
```supercollider
SynthDef(\qq, {Out.ar(0, SinOsc.ar*Env.perc.kr(doneAction:2))}).writeDefFile
```
2. evaluating the following code
```supercollider
Synth(\qq)
```
returns the following error:
```
-> Synth('qq' : 1005)
*** ERROR: SynthDef qqq not found
FAILURE IN SERVER /s_new SynthDef not found

```
3. reboot the server
4. repeat the step 2, then it works.

I think it would be better if the SynthDef created with the method .writeDefFile is accessible without rebooting the scsynth server.

**Comment by prko** [comment]
I had thought this behaviour as a bug. I changed my thought after carefully reading the help document.

**Comment by brianlheim** [comment]
We already have a method for this: SynthDef.load. Is that a solution for you?

**Comment by prko** [comment]
yes, thank you!
