### ISSUE TITLE
Receiving MIDI SPP quits SC 3.9.3 Interpreter (Windows x64)

### ISSUE THREAD

**Issue by alfonso73** [supercollider/supercollider#3740]
Hi all,
i'm working with SC3.9.3 with ReaRoute ASIO and loopBE30 internal MIDI ports connected to my Reaper DAW.
Everything works fine except that i have to disable Reaper sending SSP to SC via MIDI. If SPP (MIDI song position pointer) is enabled as soon as i stop Reaper playing the interter just quits and i have to reboot server and init the midi clients.

**Comment by brianlheim** [comment]
Thanks.

> How can i do a dump/stack trace for the process?

I am not an experienced Windows developer but there are some suggestions in this comment and the comments below: https://github.com/supercollider/supercollider/issues/3727#issuecomment-395686261

**Comment by brianlheim** [comment]
Stale/not enough info

**Comment by alfonso73** [comment]
Hi, i totally forgot this one. So i received the "Closed Issue" email and i tried to generate the .dmp file for sclang.exe that still crashes on SC 3.10.2 on Win7 64bit when Reaper 5.982rc1 stops while sending MIDI clock and SPP to Supercollider. The Dump file is quite big...more than 500Mb...Can it still be useful for sort the issue out? thanks.
