### ISSUE TITLE
Floating point division

### ISSUE THREAD

**Issue by smrg-lm** [supercollider/supercollider#3743]
The code 0.7 / 0.1 prints 7.0 while (0.7 / 0.1).floor gives 6.0, same with 0.3 and didn't tested more. I think this is wrong despite floating point representation.

**Comment by smrg-lm** [comment]
Python 3 prints 6.999999999999999, maybe is the print function, is confusing...

**Comment by brianlheim** [comment]
Floating point computation is inherently unstable like this. Not a bug in SuperCollider. I believe we print out to about 7 decimal places by default.

**Comment by smrg-lm** [comment]
I didn't configure it, it prints 7.0

**Comment by smrg-lm** [comment]
Ok, now I understand, "we print [up] to about 7 decimals" but those should be nines, I believe. Sorry to bother but I think is interactively confusing.

**Comment by smrg-lm** [comment]
Yeah, C does it with doubles, the different with python and js is that they print one more digit.
