### ISSUE TITLE
Supercollider as a VST/i ? (AKA SupercolliderAU for Windows)

### ISSUE THREAD

**Issue by alfonso73** [supercollider/supercollider#3745]
Hi all,
given that recently VST SDK has been GPLed, can we think of a SC VST in the future?
Wich would be the good/better strategies to implement this? (Juce and the likes, what kind of wrapper mechanism, etc.)
best!

**Comment by Sciss** [comment]
I believe somebody at IEM Graz is working on this, as we want to able to use the Ambisonics plug-ins of IEM with SuperCollider, and VST seemed the simplest possible bridge. (I don't see a repository yet, though - https://git.iem.at/ressi )

**Comment by snappizz** [comment]
@Sciss that's great news! i think it would be best if the person responsible could reach out to the dev list to discuss the progress so far and/or future work

**Comment by alfonso73** [comment]
@Sciss That's a wonderful news! I wonder if you're talkin' about a VST/i host for SC or SC as a VST/i usable in other daws and hosts. Both are great things to reach. But i think that the second one would be far better. best!

**Comment by Sciss** [comment]
(just to clarify - we're working on the opposite thing, embedding VST plug-ins as UGens with scsynth)

**Comment by alfonso73** [comment]
@Sciss that is what i was afraid of :-D good to know you are working on a plugin host UGen but i think that having SuperCollider as a VST (as SupercolliderAU works) would be a milestone for DAW integration and SC popularity.

**Comment by snappizz** [comment]
this is a *very* large project since there so many things to integrate (tempo sync, automations, etc.). unfortunately this probably won't happen soon, and we tend to close feature requests which are too ambitious to be on the project's priorities for the foreseeable future. see also #1251.

**Comment by jamshark70** [comment]
> tempo sync, automations

Though this is closed, I'm curious: SuperColliderAU faces the same requirements. How does it handle them?

Either it has some mechanism and there's an existing infrastructure (which is currently undergoing maintenance, sure, but it might not be necessary to start from scratch), or it doesn't and there's a precedent to argue that a proposed VST bridge would need only (at first) to replicate the AU's functionality.

Better might be to create an abstract SC-as-plugin framework (though that's a bigger job).

**Comment by snappizz** [comment]
yeah, i have no idea. i don't have a mac, so i don't know anything about the AU thing.

if and when VST integration is implemented, its developers need to have a complete understanding of the feature set that the user base wants -- and the only way to do that is for the same people to be actually using it for compositional work. otherwise it's certainly doomed to the realm of half-baked, unused, and unmaintained SC components.

**Comment by alfonso73** [comment]
Hi guys sorry if i keep this alive.
I really understand very good how diffcult could be to deal with this kind of integration. Maybe is a better route to post this "request" to the SupercolliderAU github. Maybe people there can suggest some strategies and a port from OSX AU to Win VST/VST3 format probably would be not so hard.
Do you suggest me to go that way?
thanks and all the best

**Comment by sonoro1234** [comment]
https://github.com/asb2m10/plugincollider
