### ISSUE TITLE
Windows: System Extension directory is now user-specific (roaming)

### ISSUE THREAD

**Issue by jamshark70** [supercollider/supercollider#3750]
A user reported on the mailing list that the system extension directory in Windows is now the user's roaming data directory, and not any system-wide directory.

The source code confirms this, but doesn't explain why. The change coincides with restructuring path functions into SC_Filesystem -- it's entirely possible that the rewrite didn't check against the older functionality. (I totally agree that the new code structure is better, btw.)

3.8:

https://github.com/supercollider/supercollider/blob/3.8/common/SC_DirUtils.cpp#L352

```
win32_GetKnownFolderPath(CSIDL_COMMON_APPDATA, str, size);
```

(Note, above is the app support directory. 3.8 uses another function to append "Extensions" to this.)

develop:

https://github.com/supercollider/supercollider/blob/develop/common/SC_Filesystem_win.cpp#L126

```
const HRESULT hr = SHGetKnownFolderPath(FOLDERID_RoamingAppData, 0, nullptr, &wptr);
```

**Comment by brianlheim** [comment]
I had this [test script](https://gist.github.com/brianlheim/7735a484e54b59dce5dd524651586d2a) that I used to check for accidental changes during the change, but I must have missed this. Thanks for the ticket!
