### ISSUE TITLE
SuperNova fails to compile on Windows

### ISSUE THREAD

**Issue by LFSaw** [supercollider/supercollider#3766]
The `README_WINDOWS.md` states that "SuperNova is not available" on Windows. This is just a duplication of that note in the issue tracker.

If closing this, make sure to remove the remark in `README_WINDOWS.md`

**Comment by brianlheim** [comment]
The official toolchain for the project is VS.

**Comment by LFSaw** [comment]
> The officially supported toolchain for the project on Windows is VS.

This is documented in [`README_WINDOWS.md`](https://github.com/supercollider/supercollider/blob/develop/README_WINDOWS.md):

> SuperCollider uses CMake as its build system. The main toolchain supported by the development team is Visual Studio - Microsoft's IDE for C++ - which also includes Visual C++, the official Microsoft C++ compiler. Use of other build environments and toolchains (such as MinGW, gcc, and Cygwin) is not currently supported.
