### ISSUE TITLE
EnvGate issues

### ISSUE THREAD

**Issue by dyfer** [supercollider/supercollider#3768]
I've noticed few inaccuracies with EnvGate.

- using the ```{}.play``` for testing EnvGate-containing synth graphs yields inconsistent behavior, since ```{}.play``` creates ```gate``` and ```fadeTime``` named controls. In case of the fadeTime, this causes the release time to be improper (the ```{}.play```'s default, instead of the provided value), while the attack time works as intended.
```
a = { LPF.ar(Saw.ar(200), 600) * EnvGate.new(fadeTime: 3) }.play; //3s fade-in works
s.queryAllNodes(true); //fadeTime control (created by {}.play) has a value of ~0.02
a.release; //releases in 0.02, instead of 3s
```
This maybe is not a big deal since using SynthDef class is better, but as I was testing things it took me a while to figure out what's going on. If there's no way to prevent ```{}.play``` from creating these ```NamedControl```s, maybe we should make a note about this in the examples.

- Unrelatedly, `i_level` parameter is described as the initial level in the help, but in the implementation it is used as `levelScale` parameter in the EnvGen, scaling the whole Env effectively. If this is the desired behavior, documentation should probably be updated... but I think the ability to set starting value directly would be desirable.

- the actual starting level is defined as ```startVal = (synthFadeTime <= 0);``` so it is 0 for positive fadeTimes and 1 for negative fadeTimes; again, not the behavior documented. Is this the way it should work?

**Comment by snappizz** [comment]
my vote is to document it as a legacy feature. it's weirdly specific functionality, and the implicit nature of the NamedControls can result in sneaky bugs. with the arrival of the `Env:ar` and `Env:kr` convenience methods in 3.7, writing envelope generators is not as verbose. i think code like

    Env.asr(0.2, 1, 0.2).kr(\gate.kr(1), Done.freeSelf, timeScale: \fadeTime.kr(0.05))

strikes a good balance between terseness and explicitness. trickery like `EnvGate` is unnecessary bloat.

**Comment by telephon** [comment]
It seems better to fix implicit control name generation. Explicitly passing controls everywhere is not a good solution in many cases, especially when graph generators are deeply nested. See `SynthDef.wrap` and how complicated it gets.

I do see your point though. Maybe we find a better way to solve such graph generation.

**Comment by telephon** [comment]
@dyfer the problem is not so much in `EnvGate` but in the combination with `{ }.play`, both of which implicitly create controls.

**Comment by dyfer** [comment]
@snappizz I actually didn't know about ```EnvGate``` until recently and it seems to me being quite useful - a quick plug-in solution for avoiding start/stop click resulting from signal discontinuity. But maybe your Env example is a better solution because of the verbosity...

@telephon yes, I realized that; the point here is that since it leads to unexpected behavior when modifying test examples off of help file, we could consider documenting it (that is the interaction between ```EnvGate``` and ```{}.play```. 

There still is an issue I believe with the ```i_level``` being incorrectly implemented.

**Comment by telephon** [comment]
Definitely this needs to be documented, if not maybe fixed. I think these simple classes should just work as perfectly as possible.

>There still is an issue I believe with the i_level being incorrectly implemented.

I don't see why this is incorrect: the level is 1.0 and it is multiplied by `i_level`. Sorry, maybe I am being dense, but I can't see the error.

**Comment by dyfer** [comment]
@telephon the [help file](https://github.com/supercollider/supercollider/blob/9b270e05bd9c007dc74f7508be42ae1ada5b5011/HelpSource/Classes/EnvGate.schelp#L14) states:
```argument::i_level
initial level of envelope (if set to 1, it starts open)```
From this my understanding is that that envelope should start at ```i_level``` and then go to 1. Instead, the the ```i_level``` acts as ```levelScale``` for the whole envelope. This looks like different behavior than described, am I missing something? (IMO the behavior in the help is the more useful one)

**Comment by telephon** [comment]
I have an idea how to improve it, made a pull request. 

I am surprise the example you gave worked for yo, it threw an error here:

`a = { LPF.ar(Saw.ar(200), 600) * EnvGate.new(fadeTime: 3) }.play;` 
-> 
`ERROR: EnvGen arg: '5' has bad input: false`

Another thing to fix.

**Comment by telephon** [comment]
>From this my understanding is that that envelope should start at i_level and then go to 1.

The idea is/was that when you use a `fadeTime` of zero, your initial value is really `1` and nothing else. This is important for ugen graphs like `{ Impulse.ar(0) }` where you wan the first sample to be one. But of course, one could also implement this differently, the way you understood it. The envelope may not have the length expected, but that would be fine. We should separate issues.

**Comment by dyfer** [comment]
@telephon I created a separate [issue](https://github.com/supercollider/supercollider/issues/3785) to discuss the ```i_level``` parameter.

> I am surprise the example you gave worked for you, it threw an error here:
> 
> a = { LPF.ar(Saw.ar(200), 600) * EnvGate.new(fadeTime: 3) }.play;
> ->
> ERROR: EnvGen arg: '5' has bad input: false
I tested this on macOS on 3.9.3, latest develop and an older 3.9 build and couldn't reproduce this error.
