### ISSUE TITLE
Non-Qt builds: extensions to non-existent classes

### ISSUE THREAD

**Issue by snappizz** [supercollider/supercollider#3769]
when building sclang without Qt, the following class extensions cause harmless (but annoying) errors:

    compiling class library...
        Found 716 primitives.
        Compiling directory '/home/nathan/usr/local//share/SuperCollider/SCClassLibrary'
        Compiling directory '/home/nathan/usr/local//share/SuperCollider/Extensions'
        Compiling directory '/home/nathan/.local/share/SuperCollider/Extensions'
    ERROR: Class extension for nonexistent class 'QWebView'
         In file:'deprecated/3.10/QWebView.sc'
    ERROR: Class extension for nonexistent class 'HistoryGui'
         In file:'deprecated/3.9/HistoryGui.sc'

the HistoryGui one is easy, since we'll be removing the `deprecated/3.9` folder once we go into release mode shortly. the `deprecated/3.10` can be easily taken care of by moving the extension to `deprecated/3.10/GUI`.

(this is a very simple fix, but i'm trying to get into the habit of filing issues to clearly explain what's wrong before filing PRs.)

**Comment by jamshark70** [comment]
> this is a very simple fix, but i'm trying to get into the habit of filing issues to clearly explain what's wrong before filing PRs.

IMO it's sufficient to explain the issue in the PR text.

We already have too many emails. Opening issues that will be closed by PRs is just email spam IMO.

**Comment by snappizz** [comment]
okay whataver man
