### ISSUE TITLE
3.9 help Table of Contents is unwieldy to use

### ISSUE THREAD

**Issue by jamshark70** [supercollider/supercollider#3771]
Sorry to say this -- it isn't urgent to fix, but the more I use the new help-page table of contents, the more I dislike it. It would have been better to leave it alone.

The thing that happened just now, which pushed me over the edge to open this issue:

1. Open the Server Command Reference.

2. Click "Table of Contents."

3. Scroll down to Buffer commands and click on b_read. The help page jumps, correctly, to the right command. So far, so good.

4. Close the table of contents (which, by the way, is already an interface inconvenience because you can't close the table of contents without scrolling to the top of the TOC -- why can't I click on the contents entry, and then dismiss the TOC with a single click?).

5. Now the help page window has moved to look at a totally different command -- because the text width has changed, the page got reformatted and the previous "top" position is no longer valid. So I have to scroll through the page to find the part that I had previously selected.

I realize there were scrolling bugs with the old pop-up menu, but the current design is quite far from a fluent interface. Frankly, whenever I have to use the new TOC, I get frustrated. Sometimes not just frustrated. I would very strongly suggest that it be reconsidered.

**Comment by snappizz** [comment]
i'll get around to these in a few days, busy week for me, thanks for your patience
