### ISSUE TITLE
help-browser: cmd-enter on code evaluates all

### ISSUE THREAD

**Issue by telephon** [supercollider/supercollider#3777]
The expected behavior of `cmd-enter` is evaluate region, if there is no explicit region  (by parentheses) then evaluate the line (as `shift-enter` would do).

In the help browser, after the webview reform,  `cmd-enter` assumes the whole block between `code::` sections to be a region. This makes many helpfile examples unusuable, as the assume that you step line by line through them.

I'm assigning you @scztt because you have just finished all these excellent improvements, and maybe you know where the glitch comes from.

It is kind of urgent, as it affects a larger portion of the helpfiles.

**Comment by telephon** [comment]
A good example are the `ProxySpace examples`

**Comment by telephon** [comment]
Hm, maybe, with shift-arrow down, yes. But most people don't know that AFAIK, so that would mean moving between mouse and keyboard for each line, wouldn't it?

**Comment by telephon** [comment]
(btw. `cmd-i` gives the text in italic ...)

**Comment by brianlheim** [comment]
AFAICT this has to do with the JavaScript code in `HelpSource/scdoc.js`

**Comment by snappizz** [comment]
i'm not convinced it's the javascript. at least in #3829, "evaluate as code" in the context menu works fine, but the shortcuts are broken.

**Comment by scztt** [comment]
The behavior for finding the region of code to run is.in the JavaScript. I had to add additional behavior by way of keyboard event detection to the js, since the webview basicly intercepts all keyboard events.

**Comment by htor** [comment]
i'd like to take a shot at this issue, being familiar with js. but first, how do you `console.log` stuff or debug webviews in sc? and do i need to restart scIDE to render the webview/docs on each change?

just to be clear. the code eval should work exactly the same as in the editor, right?

**Comment by htor** [comment]
after fiddling with this problem it looks to me like the js is fine, but there's something going on in the help browser widget which causes the js function `selectRegion()` to be called regardless of input.

i think `evaluateRegion` is always true here: 
https://github.com/supercollider/supercollider/blob/develop/editors/sc-ide/widgets/help_browser.cpp#L368
