### ISSUE TITLE
EnvGate throws an error when fadeTime is a number

### ISSUE THREAD

**Issue by telephon** [supercollider/supercollider#3795]
EnvGate throws an error when fadeTime is a number: it expects a UGen input (usually it is a control).

Reproducer:
`{ EnvGate(fadeTime:2) }.asSynthDef`

**Comment by dyfer** [comment]
@telephon thanks for investigating the multiple issues with EnvGate!
However, I just want to put on the record that I can't reproduce this on 3.9.x on macOS...

**Comment by telephon** [comment]
interesting. How does the implementation of `EnvGate` look in your version? I see no change since four years (https://github.com/supercollider/supercollider/blame/develop/SCClassLibrary/Common/Control/GraphBuilder.sc)

**Comment by dyfer** [comment]
My implementation of ```EnvGate``` looks exactly the same.

**Comment by brianlheim** [comment]
I am able to reproduce this (mac 10.13, develop at ce66ee973). Here is the full message:

```
EnvGen arg: '5' has bad input: false
 ARGS:
   gate: an OutputProxy OutputProxy
   levelScale: 1 Integer
   levelBias: 0.0 Float
   timeScale: 2 Integer
   doneAction: 2 Integer
   5: false False
   6: 2 Integer
   7: 1 Integer
   8: -99 Integer
   9: 1.0 Float
   10: 1.0 Float
   11: 3 Integer
   12: 0 Integer
   13: 0.0 Float
   14: 1.0 Float
   15: 3 Integer
   16: 0 Integer
SynthDef 1362123819 build failed
ERROR: EnvGen arg: '5' has bad input: false

PROTECTED CALL STACK:
	SynthDef:checkInputs	0x117f60e80
		arg this = a SynthDef
		var firstErr = EnvGen arg: '5' has bad input: false
	SynthDef:finishBuild	0x117f59c40
		arg this = a SynthDef
	a FunctionDef	0x117f4da80
		sourceCode = "<an open Function>"
	Function:prTry	0x11420a440
		arg this = a Function
		var result = nil
		var thread = a Thread
		var next = nil
		var wasInProtectedFunc = false
	
CALL STACK:
	Exception:reportError
		arg this = <instance of Error>
	Nil:handleError
		arg this = nil
		arg error = <instance of Error>
	Thread:handleError
		arg this = <instance of Thread>
		arg error = <instance of Error>
	Object:throw
		arg this = <instance of Error>
	Function:protect
		arg this = <instance of Function>
		arg handler = <instance of Function>
		var result = <instance of Error>
	SynthDef:build
		arg this = <instance of SynthDef>
		arg ugenGraphFunc = <instance of Function>
		arg rates = nil
		arg prependArgs = nil
	Interpreter:interpretPrintCmdLine
		arg this = <instance of Interpreter>
		var res = nil
		var func = <instance of Function>
		var code = "{ EnvGate(fadeTime:2) }.asSy..."
		var doc = nil
		var ideClass = <instance of Meta_ScIDE>
	Process:interpretPrintCmdLine
		arg this = <instance of Main>
^^ The preceding error dump is for ERROR: EnvGen arg: '5' has bad input: false
```

**Comment by jamshark70** [comment]
`startVal = (synthFadeTime <= 0)`

Casually assumes `synthFadeTime` will always be a UGen.

I'm not sure if it's more elegant to check for a Boolean result and replace it, or to force a BinaryOpUGen, or to use asUGenInput to convert Booleans to 0 or 1. The last option is certainly the most clever, but that can have unforeseen consequences too.

**Comment by telephon** [comment]
Luckily, the solution #3797 doesn't need this comparison.

**Comment by dyfer** [comment]
For the sake of completeness:
I investigated why is it that I was not getting this error. It turns out it was thanks to a quark I had installed - wslib. It has this extension of Boolean class:

```
// wslib 2012
// make true/false valid inputs for UGens
+ Boolean {
	writeInputSpec { |file, synth| this.binaryValue.writeInputSpec(file, synth) }	isValidUGenInput { ^true }
}
```
which prevented this error.

**Comment by telephon** [comment]
btw. the standard way would be
```
asUGenInput {
    ^this.binaryValue
}
```

**Comment by brianlheim** [comment]
#3797
