### ISSUE TITLE
CMake module for building custom UGens

### ISSUE THREAD

**Issue by snappizz** [supercollider/supercollider#3799]
the officially prescribed method of creating build systems for custom UGens requires a [very long CMake file](https://github.com/supercollider/example-plugins/blob/master/01a-BoringMixer/CMakeLists.txt) to ensure correct compiler flags. instead of making every plugin author duplicate this code, let's provide a cmake module that people can import.

whoever takes this on should know, or be willing to learn about, the best practices for creating and distributing cmake modules.

**Comment by cianoc** [comment]
I’m willing and motivated to learn.

**Comment by snappizz** [comment]
resolved in #4055
