### ISSUE TITLE
MIDIOut help file is misleading for Linux

### ISSUE THREAD

**Issue by jamshark70** [supercollider/supercollider#3806]
While #3805 is pending, we can still fix some rather severe errors in the MIDIOut help file for Linux.

> MIDIOut.new(port, uid)
> Arguments:
> port	the index of the MIDIEndPoint in the MIDIClient.destinations array.

Nope. If `port` is 0, it will look for the SuperCollider:out0 port in the `MIDIClient.sources` array (yes, *sources*! ... which makes sense for the ALSA MIDI architecture, but how should a user guess that from reading our help?).

> Linux: using the uid is optional as described below.

"Optional" here, but if you leave it out, then it's mandatory to `.connect`. The "below" discussion is worded in a very confusing way.

There was just an sc-users thread about this. Small wonder the user couldn't get it working on his own.

I don't mind to rewrite it myself, in a day or two (assigning to myself).

**Comment by brianlheim** [comment]
Thanks for taking this on! I was following the thread too and was also bewildered
