### ISSUE TITLE
PopUpMenu: tab is not rendered correctly

### ISSUE THREAD

**Issue by dyfer** [supercollider/supercollider#3820]
The `PopUpMenu` does not render tab correctly.
When the menu is open, the tab is rendered too wide (occupies ~90% of the remaining width of the menu, the rest of the text is cut).  When the menu is closed, and displays a line with a tab, the tab is rendered as a single space.
```
m = PopUpMenu(nil, Rect.aboutPoint(Window.screenBounds.center, 180, 20)).front;
m.items = ["no tab", "with\ttab and other text"]; //when the menu is open, tab takes too much space
m.items = ["with\ttab", "without tab"]; //when the menu is closed, the tab is displayed as a single space
```
Tested on 3.9.x on macOS 10.12.

**Comment by jamshark70** [comment]
Is this a SuperCollider problem or a Qt problem?

It's a valid concern, but SC doesn't draw the menu. It uses a Qt object to draw it. If the Qt object does it wrong, it may be either a Qt property that we're using incorrectly or a Qt limitation (or bug). If the latter, there isn't much we can do.

**Comment by jamshark70** [comment]
With apologies, I'm going to close this.

It seems this has been logged as a bug with Qt (10 years ago!), rated low priority, and closed on their end with no solution.

That is, they don't think it's an important problem. I don't think SC as a project has enough clout to make them reconsider. I think we have to live with it.

https://bugreports.qt.io/browse/QTBUG-2871

**Comment by dyfer** [comment]
Thank you @jamshark70 for investigating this. 
I totally understand that fixing QT bugs is outside of scope of SC, I just didn't expect this would be something deep in QT.

**Comment by scztt** [comment]
fwiw this renders correctly if you use Menu's:
```
m = Menu(
	MenuAction("no tab\texcept here"),
	MenuAction("with\ttab and other text")
).front;
```

**Comment by dyfer** [comment]
Thanks @scztt 
I can try to look into it... however what is this Menu class? I don't see it in my build.

**Comment by brianlheim** [comment]
@dyfer - it's soon to be merged to develop-  #2504

**Comment by dyfer** [comment]
@brianlheim - I see, thanks! I'll look into it once it's in.

**Comment by brianlheim** [comment]
@dyfer it's in :)
