### ISSUE TITLE
Help example code does not evaluate on linux

### ISSUE THREAD

**Issue by gusano** [supercollider/supercollider#3829]
With recent Qt changes, it seems I cannot evaluate any code in Help files anymore on linux, `CTRL+ENTER` does nothing.
Can anyone reproduce that?

- `4.16.13-1-ARCH`
- `qt-5.11.0`
- `develop` branch (latest commit as of today)

As a side note, I realized that one can edit Help code content on the fly, not sure if it always has been like that or not but I find it a bit weird..

**Comment by brianlheim** [comment]
Yes, this is related to #3777. For some reason the browser no longer intercepts most key commands, I'm sure it's a simple fix.

**Comment by brianlheim** [comment]
And yes it's always been possible to edit code blocks :)

**Comment by patrickdupuis** [comment]
One thing that I find meet is that you can select the code, and right-click "evaluate as code".

**Comment by unculcated** [comment]
While you are on it. Open right-click tab on Class would be useful

**Comment by snappizz** [comment]
i've been trying to look into this (since it prevents me from investigating #3777), but the reasons still escape me. other shortcuts are also broken: zooming in works (Ctrl++), but zooming out (Ctrl+-) and resetting zoom (Ctrl+0) don't. anyone have some insights?

**Comment by snappizz** [comment]
fixed in #3936.
