### ISSUE TITLE
error on dragging macos window title icon

### ISSUE THREAD

**Issue by htor** [supercollider/supercollider#3834]
on my mac it displays an error if i drag the little sc icon in the title bar before saving the document. after saving the doc it works normally (dragging the title lets me treat it as a dragged file). macos 10.13, sc version: 3.9.3.

![image](https://user-images.githubusercontent.com/1709263/42126540-c9b75aec-7c8a-11e8-8788-aa241e1890c8.png)
after saving:
![image](https://user-images.githubusercontent.com/1709263/42126543-cd2bb600-7c8a-11e8-9537-f3d03028f59d.png)

maybe this is the desired behaviour, or if not, maybe the problem can be avoided if the editor creates a blank project as a temporary file in `%temp%` on windows or `$TMPDIR` on unix systems.

**Comment by brianlheim** [comment]
Thanks for the report, this is the desired behavior I think.

**Comment by htor** [comment]
apparently this is a regression in qt upstream. it was a bug that was fixed but appeared again in later versions:
https://bugreports.qt.io/browse/QTBUG-30064
