### ISSUE TITLE
adding subsubsection to the table of contents in schelp documents

### ISSUE THREAD

**Issue by prko** [supercollider/supercollider#3843]
Hi,
 
Currently, I need one lower level under subsection, which corresponds to subsubsection in LaTex document structure.

Latex provides seven levels of depth for defining sections.
(Please refer to [https://en.wikibooks.org/wiki/LaTeX/Document_Structure](https://en.wikibooks.org/wiki/LaTeX/Document_Structure))

1. part: level -1
2. chapter: level 0
3. section: level 1
4. subsection: level 2
5. subsubsection: level 3
6. paragraph: level 4
7. subparagraph: level 5

One schelp document seems to be a chapter in LaTex section definition, and we probably do not need all levels in LaTex section definition, but adding one or two lower levels might be necessary. 

What do you think about adding subsubsection to the structure of the table of contents in schelp documents?

**Comment by LFSaw** [comment]
Can you give an example case for this, please? 
It seems to not have been necessary until now and for the > 1000 Help documents we have...

**Comment by prko** [comment]
The following is an example of a SCHELP using subsubsection:
```supercollider
title:: 1.07. SuperCollider
summary:: preparations for Using SuperCollider
categories:: Tutorials>aKoreanGuide>1 Introduction
related:: Tutorials/aKoreanGuide/aKoreanGuide, Tutorials/aKoreanGuide/01/K01_00_-_Introduction

section:: Overview

section:: References
subsection:: Installation, Information, Developers etc.
subsection:: Videos
subsection:: Learning Materials
subsection:: Social Networking

section:: SuperCollider vs. Other Language
subsection:: Audio Programming Languages
subsubsection:: Characteristics of Csound, Pure Data and Max
subsubsection:: A Comparison of Sine Wave Generation Codes (Patches)
subsection:: Programming Languages
subsubsection:: Characteristics of  C, sclang and Python
subsubsection:: A Comparison of Using Functions
subsubsection:: A Comparison of Using If Statements
subsubsection:: A Comparison of Using Arrays
subsubsection:: A Comparison of Using Libraries

section:: Installation and First Launching

section:: SuperCollider IDE
subsection:: How to Use
subsection:: Using Help Documents
subsection:: Using Online and Offline HTML Documents

section:: Overview of SuperCollider Help Documents
subsection:: Overviews
subsection:: Tutorials
subsection:: Guides
subsection:: References
```
Currently, the section "SuperCollider vs. Other Languages" exists as an independent SCHELP file because subsubsection is not provided. The section "Overview of SuperCollider Help Documents" was originally an independent SCHELP file, but I integrated it into this file.  

My documentation consisted of 9 main parts with about 90 SCHELP files. The first SCHELP files of each part have the table of contents only. Recently I combined some SCHELP files into a single SCHELP file, and now I have about 80 SCHELP files.

Subsubsection allows to writing a long SCHELP file more reader-friendly, and the structure of upper levels will be more compact. However, how reader-friendly a documentation is is somewhat subjective... One of my students thinks some of my SCHELP files are too long, and they should be fragmented, but I don't prefer to having too many files.


Most help documents of more than 1000 SCHELP files are Class documentation. They have four levels.
level 1: section
level 2: subsection
level 3: method
level 4: argument, returns, discussion
However, other documentation files have level 1 and 2 only. I believe allowing more levels in tutorials and guides make possible to organise the whole documentation structure better and will help authors in writing more reader-friendly tutorials and guides.
I am not the author of the following tutorials, but they seem to be combined into one file using subsubsections.
- jitlib_basic_concepts: 01, 02, 03 and 04
- Pattern Guide 06: 06a, 06b, 06c, 06d, 06e, 06f, and 06g

However, I am not sure about combining them into a single file will be better than now because the current documentation is good enough!

I think you and James can decide it better than me... You have had more experience in this field. Would you combine jitlib_basic_concepts 01, 02, 03 and 04 as one single file if SCDoc syntax allows subsubsection?

**Comment by prko** [comment]
@ LFSaw and telephon: I am sorry that I confused the usernames.

Here are other examples:
```supercollider
title:: 3.08. Using Files, Folders and OS commands
summary:: Getting Paths, Opening/Loading an SCD File, Working with Folders, Files and OS Commands
categories:: Tutorials>aKoreanGuide> 3 Programming in SuperCollider
related:: Tutorials/aKoreanGuide/aKoreanGuide, Tutorials/aKoreanGuide/03/K03_00_-_Programming_in_SuperCollider

section:: Getting Paths
subsection:: The Path of Home (The User Account Folder)
subsection:: The Path of the Document Which Is Now Evaluated
subsection:: Changing the Level of Path from a Document

section:: Using SCD Files through SC-codes and System Commands
subsection:: Opening SCD File in SC-IDE
subsection:: AutoRun
subsection:: Load
subsubsection:: SCD is not a Function
subsubsection:: SCD is a Function without any assigned variable
subsubsection:: SCD is a Function with an assigned variable
subsection:: Running SCD File Using System Command Line Interface

section:: Using System Commands
subsection:: Asynchronous
subsubsection:: .unixCmd
subsubsection:: .runInTerminal
subsection:: Synchronous
subsubsection:: .systemCmd
subsubsection:: Pipe and unixCmdGetStdOut
subsubsection:: Understanding Different Behaviour while Synchronous Excution 
subsection:: Controlling Other Applications
subsubsection:: Launching a Specific Application
subsubsection:: Opening a Document in System Default Application
subsubsection:: Opening a Document in a Specific Application
subsubsection:: Reveal Folders in System File Explorer

Section:: Writing and Reading of Folders and Files in SuperCollider

Section:: Practices
subsection:: Referencing Files from an SCD File in SC
subsection:: Changing File Names in a Folder System Independently inside SC
subsection:: Automatically Connecting JacjRouter with other Applications inside SC
subsection:: Coverting a Plain Text File into an Array and a Dictionary of SC

```

**Comment by snappizz** [comment]
if you'd like to take a crack at fixing this, check `SCDocRenderer:renderTOC`. extending the code to cover subsubsections seems straightforward.

**Comment by prko** [comment]
I already tried to change 
- SCDocRenderer.sc
and
- SCDoc.sc

What I did is as follows:
1. Finding subsection
2. copying the code block including subsection
3. pasting it under the code block of NO. 2
4. change subsection to subsubection
5. 'addDivAfter' in SCDoc.sc is duplicated. Thus, I changed it to 'addDivMorr'

However, I get the following error when using 'subsubsection:: hello'

> At line 256: syntax error, unexpected ::, expecting end of file

I do not submit a PR because it does not work.

**Comment by snappizz** [comment]
you can share patches with other developers without opening a PR. two easy ways to do this:

- for small, single-commit patches, make a patch file (`git diff > mypatch.patch`)
- for multiple-commit patches, push to a branch on your fork and just link me to the branch

**Comment by prko** [comment]
Here you are:

- SCDoc.sc: https://github.com/supercollider/supercollider/compare/develop...prko:patch-3
- SCDocRenderer.sc: https://github.com/supercollider/supercollider/compare/develop...prko:patch-4

**Comment by snappizz** [comment]
the syntax error seems to be a parser thing, not a renderer thing. try going back to the original version and see if you still get the error. something is probably wrong with the .schelp file you're plugging in.

also, make sure you took the turtle's advice (scroll to the top of SCDoc.sc)

**Comment by prko** [comment]
The error occurs only when I insert the following lines in any schelp which works without errors.
```supercollider
section:: section
test
subsection:: subsection
test
subsubsection:: test
test
```
I confirmed 'subsection' in all of three documents:
- SCDoc.sc
- SCDocRenderer.sc
- test.schelp
I think I followed Turtle's advice by doing this...

**Comment by prko** [comment]
I retried it, but have no success.

This question may be idiot-like : 
Should I know c-plus-plus to understand .sc file correctly?
They seem to be similar to familiar sclang syntax, but sometimes I see differences from sclang.

**Comment by prko** [comment]
I searched the word "section" and "subsection" in the SuperCollider installation folder and subfolders. The file docmap.js contains them, but inserting the word "subsubsection" in this file does not resolve the problem described above.

**Comment by prko** [comment]
Currently the method seems to be used as a subsection.

In the following source files there are 5 files related to this issue:
- https://github.com/supercollider/supercollider/blob/develop/SCDoc/lex.scdoc.cpp
- https://github.com/supercollider/supercollider/blob/develop/SCDoc/SCDoc.l
- https://github.com/supercollider/supercollider/blob/develop/SCDoc/SCDoc.y
- https://github.com/supercollider/supercollider/blob/develop/SCDoc/SCDoc.tab.cpp
- https://github.com/supercollider/supercollider/blob/develop/SCDoc/SCDoc.tab.hpp

I think these parts should be changed to make my wish come true, but I cannot do it....

What I can do has been done in the following:
https://github.com/prko/supercollider/tree/subsubsection

**Comment by prko** [comment]
I closed it because it is too old.
