### ISSUE TITLE
slack invite link not working

### ISSUE THREAD

**Issue by htor** [supercollider/supercollider#3845]
link from https://supercollider.github.io/ is not working: 
https://scsynth.slack.com/join/shared_invite/enQtMjk0MzA0NzgyOTkyLTYwNjdmYjFmNWY4NGIyZWM2YWY1NzZhMjM3MWQ0MmEwZTZkZDExOTRjMWI2NjBiMGQ1NTg1NDQyZjExNWFjZGM

by the way, is there a sc irc channel somewhere too?

**Comment by patrickdupuis** [comment]
Officially, there's no IRC. The slack invite link is supposed to keep working, but it fails periodically. Sorry about that.

**Comment by htor** [comment]
no problem, it worked now.

**Comment by brianlheim** [comment]
Clicking the link still shows "this link is no longer active" for me. Why Slack is deactivating what is calls "permanent links" is beyond me

**Comment by brianlheim** [comment]
Fixed in 3.10 branch (#3886)
