### ISSUE TITLE
[doubt] - supercollider/supercollider - how to use writedefsynths, to store and load supercollider synths from disk?

### ISSUE THREAD

**Issue by tmm2018** [supercollider/supercollider#3849]
[doubt] - supercollider/supercollider - how to use writedefsynths, to store and load supercollider synths from disk?

what i want to do is write down a synthdef to a local container within my hard-disk, and then dinamically loading it, rather then loading a class written with the same synth

thank you so much
kind regards/best wishes

**Comment by Sciss** [comment]
Please use a mailing list or forum for questions; this is a bug tracker.

The help file of `SynthDef` explains this (e.g. `writeDefFile`, `load`). You can also use `server.sendMsg("/d_load", "mydef.scsyndef")` if you have written the definition to disk.
