### ISSUE TITLE
(Platform.resourceDir+/+"examples").openOS does not work under all platforms

### ISSUE THREAD

**Issue by prko** [supercollider/supercollider#3854]
```supercollider
(Platform.resourceDir+/+"examples").openOS
```
works under Windows.
Under macOS works the following: 
```supercollider
Platform.resourceDir.replace("SuperCollider.app/Contents/Resources", "examples").openOS
```
Under Linux (Ubuntu 16.0.4 and SC3.6.6), I cannot find the "examples" folder.

It is better that this code works under all three platforms as 
```supercollider
(Platform.resourceDir+/+"sounds").openOS
```
does.
Could it be fixed?

**Comment by brianlheim** [comment]
The current version of SC is 3.9.3, can you please try again with that version?

**Comment by prko** [comment]
I have followed the ppa install instruction, and it only installs 3.6.6.
I see the 3.9.3 package releases, but do not find any installation instruction for it.

**Comment by brianlheim** [comment]
You will have to build it from source. @snappizz @patrickdupuis do you have this issue with the current version?

**Comment by prko** [comment]
Then only on macOS, the folder "examples' is located on a different location...
Could the folder be moved into "SuperCollider.app/Contents/Resources/"?
An alias of "example" folder in the parent folder of "SuperCollider.app" would be then necessary.

**Comment by brianlheim** [comment]
I'm not sure I understand - when is this actually a problem in everyday usage? This seems kind of trivial to me, the examples directory shouldn't need to be opened that often compared to sounds. Is there documentation that indicates this should work cross platform? Maybe we just need to change how that is communicated.

**Comment by snappizz** [comment]
i'm not seeing the linux issue either -- i have an installed `examples` dir.

**Comment by jamshark70** [comment]
> I'm not sure I understand - when is this actually a problem in everyday usage?

I agree with prko. Many people learn by trying examples, and cool examples are often how people get hooked, or decide that SC is worth the effort. But that only works if you can find the examples. In Linux, examples/ is in a place where users will not think to look. Windows, I don't remember, and macOS seems to be a quite odd bird here.

> The difference arising from platform difference takes lots of time when having practice in lectures.

Let's not underestimate the seriousness of that. It is a massive pain when you have a room full of students and they run into problems. Anything we can do to smooth out beginners' steps is a good thing.

Perhaps a menu option in the IDE to open the examples folder...?

**Comment by prko** [comment]
> Perhaps a menu option in the IDE to open the examples folder...?

It sounds very good!

**Comment by telephon** [comment]
… and then we do a thorough re-edition of the examples. I think they should be brought to style standards and improved if we can.

**Comment by snappizz** [comment]
i'm having doubts as to whether a curated examples directory is worth keeping around. it doesn't seem like people look at these much, since there are many other places to find great SC code samples

**Comment by telephon** [comment]
Examples are much more important than documentation. It is just that we have forgotten how important they are.

In other places, there is no opportunity for curation and formatting. Please, let's keep them in.

**Comment by gusano** [comment]
> Examples are much more important than documentation. It is just that we have forgotten how important they are.
> 
> In other places, there is no opportunity for curation and formatting. Please, let's keep them in.

+10000 :)

**Comment by jamshark70** [comment]
> it doesn't seem like people look at these much

Perhaps one reason why people aren't looking at the examples very much is because, as the issue summary above implies, *the folder is too hard to find*.

I wouldn't say, though, that examples are more important than documentation. I would say different people have different learning styles. Some people learn in a more systematic way, while others would rather take a code snippet that does something cool and rip it apart to see how it works.

Examples can lead users to functionality that they wouldn't know how to search for in the help system. (With every kind of software, there's a learning curve for the terminology that you need in order to use the documentation effectively.)

With that said, in our help files, we do tend to document by example too much, in place of describing arguments, return values and expected behavior.

**Comment by htor** [comment]
doesn't work here too on macos + sc 3.9.3. since it is a location referenced by docs i think this should work on macos and linux too. saves people alot of trouble. where is the examples dir on macos by the way?

also want to add that the documentation for sc is *excellent* because it has plenty of good examples. this really impressed me, coming from other places where you only have the api reference and no clue how to use it.

**Comment by jamshark70** [comment]
> since it is a location referenced by tutorials/docs i think this should work on macos and linux too.

It's referenced in one place: https://github.com/supercollider/supercollider/blob/develop/HelpSource/Classes/Ndef.schelp#L285

```
code::
(Platform.resourceDir +/+ "examples/demonstrations/single_sample_feedback.scd").openDocument;
::
```

According to grep, there are no other lines anywhere in the documentation containing both `resourceDir` and `examples`.

As for Linux:

```
("ls " ++ Platform.resourceDir +/+ "examples").unixCmd;

between_languages
demonstrations
GUI examples
other
pieces
research_and_tools
```

prko reported the Linux failure using SC 3.6.6, which is (sadly) the latest version available in Ubuntu packages. All Linux users who have built SC 3.9.x report that the examples folder is definitely there.

It's possible that the old 3.6.6 package is incomplete.

Really, we should remove that PPA.

I'm pretty sure the macOS problem is that we just put `examples/` in the wrong place in the app bundle.

**Comment by prko** [comment]
The following code works under macOS and Windows.
```supercollider
(Platform.resourceDir.replace("/SuperCollider.app/Contents/Resources", "")+/+"examples").openOS
```
I do not have a Linux version of develop branch built. In SC 3.8 for Ubuntu, the code above does not work.

**Comment by dyfer** [comment]
On macOS the examples are included in the disk image, but it's up to the user to copy them to a location of choice.
IMO I don't believe there's a way or a point in making this consistent across platforms, but feel free to reopen if desired.
