### ISSUE TITLE
Help TOC needs more padding at bottom

### ISSUE THREAD

**Issue by patrickdupuis** [supercollider/supercollider#3855]
The newly redesigned Help TOC needs a little extra padding. Tthe last element in the TOC can be obscured if the help browser's horizontal scroll bar is visible.

![scroll bar](https://user-images.githubusercontent.com/11747870/42486942-a3faec08-83cc-11e8-859e-44e81b381ca1.png)

**Comment by snappizz** [comment]
oops!

**Comment by snappizz** [comment]
looks like this is fixed -- thanks to @/htor and @/prko for cleaning up the mess i left with scdoc css!
