### ISSUE TITLE
Help TOC small scrolling issue

### ISSUE THREAD

**Issue by patrickdupuis** [supercollider/supercollider#3856]
The super awesome new Help TOC has a small issue with scrolling. If you scroll the TOC all the way to the bottom, the rest of the document will start to scroll. 

Not a big deal! Thanks @snappizz  :smile:

**Comment by snappizz** [comment]
i don't consider this a bug.

**Comment by brianlheim** [comment]
This seems like fine behavior to me too, I noticed it while testing. I've used UIs that go both ways and this has never bothered me.

**Comment by patrickdupuis** [comment]
Ok, not a big deal. We can keep this. I only mentioned it because the same issue was fixed in the last redesign: https://github.com/supercollider/supercollider/pull/3346#issuecomment-353124128
