### ISSUE TITLE
.systemCmd works differently only under macOS when running GUI-based applications

### ISSUE THREAD

**Issue by prko** [supercollider/supercollider#3862]
Under macOS, .systemCmd correctly works synchronously only for terminal commands. 

The following works as expected under macOS and Linux:
```supercollider
(
fork{ 
	"echo cmd1; sleep 1; echo cmd2; sleep 1".systemCmd;

	//"echo cmd1 & timeout /t 1 & echo cmd2 & timeout /t 1 ".systemCmd;
	// Strangely under Windows, "timeout /t 1" does not work by this...

	4.do{ |i| (\_sc++i).postln; { SinOsc.ar((69+i).midicps.postln) * Env.perc.kr(doneAction:2) }.play; 1.wait };
	"extra".postln
}
)
```
But the following works not as expected under macOS:
```supercollider
(
fork{
	Platform.case(
		\osx,       { "open -a TextEdit" },
		\linux,       { "gedit" },
		\windows,   { "notepad.exe" }
	).systemCmd;
	// ).unixCmd;
	1.wait;
	5.do{ |i|
		{ SinOsc.ar((69+i).midicps.postln) * Env.perc.kr(doneAction:2) }.play;
		1.wait
	}
}
)
```
Under Linux and Windows, I can hear the sounds from scsynth after closing the text editor.
Under macOS, there is no difference between .systemCmd and .unixCmd.

What I found is as follows:
When running commands through .unixCmd, I can check pid using pidRunning.
Under Windows, a cmd.exe works in the background, and it disappears when the notepad is closed.
Under macOS, a Terminal process quits shortly after calling TextEdit.
I think the same process also occurs in .systemCmd.

It is a bit confusing. Could this behaviour be consistent on all three platforms?

**Comment by jamshark70** [comment]
I think, no.

If I recall, "open" is a macOS specific command that launches the right app for the document *and then `open` itself exits*. At that point, the systemCmd itself is finished so SC correctly advances to the next thing.

You'll get the same result in Linux with `xdg-open`, I'm pretty sure (though I'm not at my computer to test). 

SC does not have the power to force an operating system to change the behavior of its executables. I believe this should be closed as "can't fix."

**Comment by miguel-negrao** [comment]
I agree here, that is the expected behaviour of open or xdg-open, it will not block, it will just return immediately. This is not related with SC.

**Comment by prko** [comment]
Thank you for reviewing this!
