### ISSUE TITLE
sc-doc layout:

### ISSUE THREAD

**Issue by prko** [supercollider/supercollider#3864]
Hi,

The followings are minor things and not crucial in using SC, but I am sure that they are related to readability.

1. The space above the section title (level 1) is smaller than space above the subsection title (level 2).
However, usually, the space above the level 1 is taller than level 2

2. The font sizes of the level 1 title, the level 2 and body text could be more resized:
    - The size difference between the level 1 and the level 2 should be more distinct
    - The font size of the body could be a bit bigger
    - The font size of the code and teletype could be bigger. (They are extremely small in android devices)

On the computer, they could be minor matters:

<img width="608" alt="onpc" src="https://user-images.githubusercontent.com/416281/42610314-f2d32434-85cb-11e8-9b3d-48d8e130f368.png">

However, on Android devices, these decrease readability remarkably. There is a "simplified view" option in the android version chrome, but it appears not always, and in the simplified view some parts are not displayed:
![onandroidtablet](https://user-images.githubusercontent.com/416281/42610307-eb4fe972-85cb-11e8-8dd7-61395dfb09f2.png)

It would be great to improve this.

**Comment by brianlheim** [comment]
@prko - if you know CSS feel free to submit a PR!

**Comment by prko** [comment]
I think I did it, but I am not sure if I did it correctly... If not sorry.

**Comment by prko** [comment]
Hi, I closed my PR
Something seems to be wrong.
I will reopen it.

**Comment by prko** [comment]
I could not change the code of PR.
I created a new PR: #3881
It seems ok!
