### ISSUE TITLE
[help browser] cmd-shift-p shortcut doesn't work

### ISSUE THREAD

**Issue by prko** [supercollider/supercollider#3879]
When using the latest version which I compiled on July 14 under macOS 10.11.6, I experience so often that CMD + SHIFT + P does not work.
In order to rework it, I should recompile sclang, but it works just shortly.

I do not know how it works under other versions of macOS.

**Comment by brianlheim** [comment]
Hey @prko - just fyi, when reporting it's generally more helpful if you give the hash of the commit rather than the date you compiled it. That is the clearest way to identify a specific revision of the codebase. You can find this by checking `git status` or (I think) by clicking "About SuperCollider" in the IDE main menu. Just the first 7 hex digits should be enough (like 575ab8)

**Comment by prko** [comment]
Ok. Thank you!

The hash of the commit is [233ebeb4b].

**Comment by prko** [comment]
CMD + P do not work in the same way...

**Comment by prko** [comment]
CMD + P does not work in the same way.

**Comment by brianlheim** [comment]
Also fyi it's fine to just put the commit hash (or version tag, if you are not building it yourself) in the report, it doesn't need to go in the title. That's typically how we do things and it seems to work - normally the issue title fits the format "[component] brief description", so here we would typically title it something like "[help browser] cmd-shift-p shortcut doesn't work". this should really go in our contributing guide!

**Comment by prko** [comment]
sorry. I changed it!
And thank you for this comment!

**Comment by brianlheim** [comment]
no need to apologize - this is just stuff you pick up being around for awhile :)

**Comment by brianlheim** [comment]
As of current 3.10 I cannot reproduce this; I was able to execute Cmd+Shift+P 100 times in a row without failure. Similar story with Cmd+P.

If you can find a more reliable way of reproducing this bug, please re-open.

**Comment by prko** [comment]
Thank you for reviewing and closing this issue. 
Yesterday, I considered closing this issue, because I did not experience it in [60daca83].
It seems to be resolved silently!

**Comment by prko** [comment]
This is the report while using [0f779a49] under El Capitan.
I am experiencing again the phenomenones.

I found the way of reproducing this bug.

- CMD + SHIFT + P works only when the help browser is activated. In the code editor it does not work.  
- CMD+P does not work.

I think this should be open.

Could you reproduce it?

**Comment by brianlheim** [comment]
I tested that also and cannot reproduce.
