### ISSUE TITLE
sclang: String.interpret 's error is not caught with try {}

### ISSUE THREAD

**Issue by dyfer** [supercollider/supercollider#3890]
Hello,
It seems that one is unable to catch errors in `String.interpret` using `try {}`:
```
try {"notDefinedVar".interpret} {"I'd like to catch that".postln}
```
Is there a known way of catching such error?

(tested on 3.9.x and 3.10dev on macOS)

**Comment by dyfer** [comment]
Well, silly me. It looks that `"Variable '' not defined"` errors are not caught in general. Closing...

**Comment by dyfer** [comment]
Thank you @jamshark70. 
I tried this, but `try {"notDefinedVar".compile} {"I'd like to catch that".postln}` still posts the error. Doesn't seem like I can catch syntax errors anyway, can I?

**Comment by dyfer** [comment]
Thanks @brianlheim 
Well, I wanted to avoid error posting :) but I see this is not possible. Thank you both for the insight!

**Comment by brianlheim** [comment]
Yes, sorry about that. Errors from the parser are written directly to stdout/stderr during parsing so it would take no small amount of engineering to get around that.
