### ISSUE TITLE
Error in Sync-Async.schelp examples

### ISSUE THREAD

**Issue by tremblap** [supercollider/supercollider#3896]
There are a few errors in the documentation of Synchronous vs Asynchronous, which confused me as I was trying to understand proper handshake between the language and the server.

Confirmed on the SC-list by Frederik Olofsson, here is the message:

> that Synchronous and Asynchronous Execution helpfile has several problems.  the code excerpt under "Let's take a look at the method definition for SynthDef-play" is wrong and the broken example you found should look something like this...

```
b = Buffer.read(s, Platform.resourceDir +/+ "sounds/a11wlk01.wav", action: { arg buffer;
       // synth send its s_new msg to follow
       // after the buffer read completes
       s.sendBundle(nil, y.newMsg(s,[\bufnum,buffer],\addToTail));
   }
);
```

> i.e. it's an action function and not a completionMsg, so we need to manually send the s_new message using .sendBundle.

I would propose a pull request but I feel I'm not good enough to propose a solution.

**Comment by brianlheim** [comment]
Thanks for the report @tremblap ! You are more than welcome to propose a PR; it's more likely to get fixed that way; once the ball is rolling people can help you with improving the code if it needs to be improved.
