### ISSUE TITLE
[WebView and HelpBrowser] Some on-line pages are not displayed

### ISSUE THREAD

**Issue by prko** [supercollider/supercollider#3899]
commit: c6bb5ae6e
OS: macOS 10.11.6

Steps to reproduce:
1. launch SC
2. evaluate the following codes to access to https://youtu.be/Y-ELYzjFQcU:
  - using HelpBrowser.goTo
```supercollider
HelpBrowser.goTo("https://youtu.be/Y-ELYzjFQcU")
```
Sometimes it works well, sometimes It shows a blank page after showing the login screen shorty. 
  - using HelpBrowser.new.goTo
```supercollider
HelpBrowser.new.goTo("https://youtu.be/Y-ELYzjFQcU")
```
Sometimes the movie on the page is not played back.

At the first time, the following errors occur (the fifth error occasionally not occurs):
```
JavaScript Message: <link rel=preload> must have a valid `as` value
JavaScript Error: Styling master document from stylesheets defined in HTML Imports is deprecated, and is planned to be removed in M65, around March 2018. Please refer to https://goo.gl/EGXzpw for possible migration paths.
JavaScript Error: Uncaught (in promise) Unable to open IndexedDB.
JavaScript Error: The resource https://r3---sn-ab02a0nfpgxapox-bh2ek.googlevideo.com/generate_204?conn2 was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it Please make sure it has an appropriate `as` value and it is preloaded intentionally.
JavaScript Error: The resource https://r3---sn-ab02a0nfpgxapox-bh2ek.googlevideo.com/generate_204 was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it Please make sure it has an appropriate `as` value and it is preloaded intentionally.
```
At second time, the following errors occur:
```
JavaScript Message: <link rel=preload> must have a valid `as` value
JavaScript Error: The resource https://r3---sn-ab02a0nfpgxapox-bh2ek.googlevideo.com/generate_204?conn2 was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it Please make sure it has an appropriate `as` value and it is preloaded intentionally.
JavaScript Error: The resource https://r3---sn-ab02a0nfpgxapox-bh2ek.googlevideo.com/generate_204 was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it Please make sure it has an appropriate `as` value and it is preloaded intentionally.
```
- a link in a help document:
```supercollider
link::https://youtu.be/Y-ELYzjFQcU::
```
Sometimes it works well, sometimes It shows a blank page after showing the login screen shorty.

3. evaluate the following codes to access to https://www.youtube.com/watch?v=Y-ELYzjFQcU&feature=youtu.be
In each case, the movie on the page is playedback and it does not show a blank screen.
```supercollider
HelpBrowser.goTo("https://www.youtube.com/watch?v=Y-ELYzjFQcU&feature=youtu.be")
```
```supercollider
HelpBrowser.new.goTo("https://www.youtube.com/watch?v=Y-ELYzjFQcU&feature=youtu.be")
```
```supercollider
link::https://www.youtube.com/watch?v=Y-ELYzjFQcU&feature=youtu.be::
```

**Comment by brianlheim** [comment]
If the issue only occurs on JS heavy sites like YTube, I would say this is simply out of scope. We don't intend for WebView to be a fully functional web browser.

**Comment by prko** [comment]
The following sites are not displayed:
- After showing all the contents, it shows a blank page. Here I see no error message. 
```supercollider
HelpBrowser.goTo("https://www.mitpressjournals.org/doi/abs/10.1162/014892602320991383?journalCode=comj")
// James McCartney. (1996). SuperCollider: A New Real Time Synthesis Language. In: International Computer Music Conference Proceedings
```
```supercollider
HelpBrowser.goTo("https://www.ebs.co.kr/tv/show?prodId=345&lectId=1183648")
// sorry, this is in Korean language... 
```
- After showing all the contents, it shows a dark page. Here I see no error message. 
```supercollider
HelpBrowser.goTo("https://www.flickr.com/photos/cu_atlas/8869964282")
// James McCartney (2013)
```
- a page is partially loaded without error messages.
```supercollider
HelpBrowser.goTo("https://supercollider.github.io/")
// the current home of supercollider

**Comment by htor** [comment]
i'd say this can be closed, as we don't need to provide a fully-functional web browser inside scide, only a functional *help* browser. what do you say, @prko?

**Comment by prko** [comment]
I think it would be great to have a built-in web browser which can
- read/evaluate the code on any webpage
- show some sc tutorial video in youtube and other sites
- download/upload data
- do more interactive things to do data-driven project inside SC. 

However, I cannot request it steadly because I am not a person who understand C++ and contribute some this as a developer.

If the majority of the developers think it is unnecessary, we can close this thread.

**Comment by prko** [comment]
What I would like to more say is that Max has better web browser, and it was very good in class and in some projects.

**Comment by htor** [comment]
i hear you, a modern browser would be nice to have. if you're wondering about the cababilites of the help browser, it's basically using https://wiki.qt.io/QtWebEngine, which is using code from the chromium project. it may not have the latest version though.

**Comment by snappizz** [comment]
closing as out of scope. at the end of the day, supercollider is a synthesizer and there's only so much effort that should be put into auxiliary components.
