### ISSUE TITLE
[Help browser] it skips the history irregularily

### ISSUE THREAD

**Issue by prko** [supercollider/supercollider#3901]
commit: c6bb5ae
OS: macOS 10.11.6

Steps to reproduce:
1. recompile the library by pressing cmd + shift + L.
2. go to the home of the help browser by pressing the "Home" button on the "help browser".
3. go to "Getting Started tutorial series" by pressing the link to it.
4. go to "01. Introductory Remarks" by pressing the link to it.
5. go to "02. First Steps" by pressing the link to it.
6. press "go to the previous page" button

Occasionally it skips one or more steps.
It seems to happen more if the title of schelp contains non-ASCII characters.

**Comment by brianlheim** [comment]
Cannot reproduce. I am seeing that if I click on the button rapidly, some clicks are dropped. There appears to be a debounce time that prevents fast clicks from registering. Is this what you mean?

Using the forward and back keyboard shortcuts does not suffer from this issue.

**Comment by prko** [comment]
I understand what you mean, and almost agree with you
I close this issue.
If I find related problems, then I will open again.

**Comment by prko** [comment]
Hi,

I would like to reopen it. I feel it does not work properly. There never were this kind of buggy operations in previous versions.
I am attaching a link to the video. I am sorry for the language of the document. It is Korean.
https://www.dropbox.com/s/6syz33ml3flr252/koreanGuide.mov?dl=0
You see find skipping as follows:
- 13"-14"
- 31"-32"
Could it be a language-specific phenomenon?
