### ISSUE TITLE
Compiling 3.9.3 in Ubuntu 16.04, cmake can't configure for legacy QT5 bits

### ISSUE THREAD

**Issue by CJunit** [supercollider/supercollider#3906]
Hello. I am following the instructions in the Linux readme. I am at the step where I would type
cmake -DCMAKE_PREFIX_PATH=/home/user/Qt/5.11.1 ..
and it gets started, but fails to configure, listing SDK bits which I know are no longer distributed (Qt5WebKit) to others I suspect are only for mobile use (Qt5Sensors, Qt5Positioning). Any ideas where I should go from here? Are those modules included elsewhere, or is their a safe way to omit them from the build?

> cmake -DCMAKE_BUILD_TYPE=Release ..
> -- SuperCollider Version: 3.9.3
> -- Building from branch HEAD, commit hash is 1c1a180
> -- Compiling with Qt GUI
> -- building boost libraries manually
> -- using bundled libyaml-cpp
> -- HIDAPI components:
> --     linux hidraw
> -- libudev stable: 1
> -- Found UDev: /usr/lib/x86_64-linux-gnu/libudev.so
> --    include: /usr/include
> --     hidapi_parser
> -- Building with HID support
> -- Using fftw3f
> -- Found jack: /usr/lib/x86_64-linux-gnu/libjack.so
> -- Audio API: jack
> -- Found GNU Readline version 6.3: /usr/lib/x86_64-linux-gnu/libreadline.so
> CMake Warning at QtCollider/CMakeLists.txt:8 (find_package):
>   By not providing "FindQt5WebKit.cmake" in CMAKE_MODULE_PATH this project
>   has asked CMake to find a package configuration file provided by
>   "Qt5WebKit", but CMake did not find one.
> 
>   Could not find a package configuration file provided by "Qt5WebKit" with
>   any of the following names:
> 
>     Qt5WebKitConfig.cmake
>     qt5webkit-config.cmake
> 
>   Add the installation prefix of "Qt5WebKit" to CMAKE_PREFIX_PATH or set
>   "Qt5WebKit_DIR" to a directory containing one of the above files.  If
>   "Qt5WebKit" provides a separate development package or SDK, be sure it has
>   been installed.
> Call Stack (most recent call first):
>   lang/CMakeLists.txt:189 (include)
> 
> 
> CMake Warning at QtCollider/CMakeLists.txt:9 (find_package):
>   By not providing "FindQt5WebKitWidgets.cmake" in CMAKE_MODULE_PATH this
>   project has asked CMake to find a package configuration file provided by
>   "Qt5WebKitWidgets", but CMake did not find one.
> 
>   Could not find a package configuration file provided by "Qt5WebKitWidgets"
>   with any of the following names:
> 
>     Qt5WebKitWidgetsConfig.cmake
>     qt5webkitwidgets-config.cmake
> 
>   Add the installation prefix of "Qt5WebKitWidgets" to CMAKE_PREFIX_PATH or
>   set "Qt5WebKitWidgets_DIR" to a directory containing one of the above
>   files.  If "Qt5WebKitWidgets" provides a separate development package or
>   SDK, be sure it has been installed.
> Call Stack (most recent call first):
>   lang/CMakeLists.txt:189 (include)
> 
> 
> CMake Warning at QtCollider/CMakeLists.txt:12 (find_package):
>   By not providing "FindQt5Sensors.cmake" in CMAKE_MODULE_PATH this project
>   has asked CMake to find a package configuration file provided by
>   "Qt5Sensors", but CMake did not find one.
> 
>   Could not find a package configuration file provided by "Qt5Sensors" with
>   any of the following names:
> 
>     Qt5SensorsConfig.cmake
>     qt5sensors-config.cmake
> 
>   Add the installation prefix of "Qt5Sensors" to CMAKE_PREFIX_PATH or set
>   "Qt5Sensors_DIR" to a directory containing one of the above files.  If
>   "Qt5Sensors" provides a separate development package or SDK, be sure it has
>   been installed.
> Call Stack (most recent call first):
>   lang/CMakeLists.txt:189 (include)
> 
> 
> CMake Warning at QtCollider/CMakeLists.txt:16 (find_package):
>   By not providing "FindQt5Positioning.cmake" in CMAKE_MODULE_PATH this
>   project has asked CMake to find a package configuration file provided by
>   "Qt5Positioning", but CMake did not find one.
> 
>   Could not find a package configuration file provided by "Qt5Positioning"
>   with any of the following names:
> 
>     Qt5PositioningConfig.cmake
>     qt5positioning-config.cmake
> 
>   Add the installation prefix of "Qt5Positioning" to CMAKE_PREFIX_PATH or set
>   "Qt5Positioning_DIR" to a directory containing one of the above files.  If
>   "Qt5Positioning" provides a separate development package or SDK, be sure it
>   has been installed.
> Call Stack (most recent call first):
>   lang/CMakeLists.txt:189 (include)
> 
> 
> -- Found Qt: /usr/lib/x86_64-linux-gnu/libQt5Core.so.5.11.1
> -- Compiling with Readline support
> -- Compiling with ALSA midi support
> -- Building the Qt IDE
> CMake Warning at editors/sc-ide/CMakeLists.txt:9 (find_package):
>   By not providing "FindQt5LinguistTools.cmake" in CMAKE_MODULE_PATH this
>   project has asked CMake to find a package configuration file provided by
>   "Qt5LinguistTools", but CMake did not find one.
> 
>   Could not find a package configuration file provided by "Qt5LinguistTools"
>   with any of the following names:
> 
>     Qt5LinguistToolsConfig.cmake
>     qt5linguisttools-config.cmake
> 
>   Add the installation prefix of "Qt5LinguistTools" to CMAKE_PREFIX_PATH or
>   set "Qt5LinguistTools_DIR" to a directory containing one of the above
>   files.  If "Qt5LinguistTools" provides a separate development package or
>   SDK, be sure it has been installed.
> 
> 
> CMake Warning at editors/sc-ide/CMakeLists.txt:11 (find_package):
>   By not providing "FindQt5Positioning.cmake" in CMAKE_MODULE_PATH this
>   project has asked CMake to find a package configuration file provided by
>   "Qt5Positioning", but CMake did not find one.
> 
>   Could not find a package configuration file provided by "Qt5Positioning"
>   with any of the following names:
> 
>     Qt5PositioningConfig.cmake
>     qt5positioning-config.cmake
> 
>   Add the installation prefix of "Qt5Positioning" to CMAKE_PREFIX_PATH or set
>   "Qt5Positioning_DIR" to a directory containing one of the above files.  If
>   "Qt5Positioning" provides a separate development package or SDK, be sure it
>   has been installed.
> 
> 
> CMake Warning at editors/sc-ide/CMakeLists.txt:15 (find_package):
>   By not providing "FindQt5Sensors.cmake" in CMAKE_MODULE_PATH this project
>   has asked CMake to find a package configuration file provided by
>   "Qt5Sensors", but CMake did not find one.
> 
>   Could not find a package configuration file provided by "Qt5Sensors" with
>   any of the following names:
> 
>     Qt5SensorsConfig.cmake
>     qt5sensors-config.cmake
> 
>   Add the installation prefix of "Qt5Sensors" to CMAKE_PREFIX_PATH or set
>   "Qt5Sensors_DIR" to a directory containing one of the above files.  If
>   "Qt5Sensors" provides a separate development package or SDK, be sure it has
>   been installed.
> 
> 
> CMake Warning at editors/sc-ide/CMakeLists.txt:17 (find_package):
>   By not providing "FindQt5WebKitWidgets.cmake" in CMAKE_MODULE_PATH this
>   project has asked CMake to find a package configuration file provided by
>   "Qt5WebKitWidgets", but CMake did not find one.
> 
>   Could not find a package configuration file provided by "Qt5WebKitWidgets"
>   with any of the following names:
> 
>     Qt5WebKitWidgetsConfig.cmake
>     qt5webkitwidgets-config.cmake
> 
>   Add the installation prefix of "Qt5WebKitWidgets" to CMAKE_PREFIX_PATH or
>   set "Qt5WebKitWidgets_DIR" to a directory containing one of the above
>   files.  If "Qt5WebKitWidgets" provides a separate development package or
>   SDK, be sure it has been installed.
> 
> 
> CMake Error at editors/sc-ide/CMakeLists.txt:239 (qt5_add_translation):
>   Unknown CMake command "qt5_add_translation".
> 
> 
> -- Configuring incomplete, errors occurred!
> See also "/home/user/Code/supercollider/build/CMakeFiles/CMakeOutput.log".
>

**Comment by brianlheim** [comment]
3.9.3 is only usable with Qt <= 5.5. It looks like you're following the readme from develop to build on a much older commit.

**Comment by snappizz** [comment]
the instructions for building on linux for 3.9 are included with your source distribution, or can be found online [in the README_LINUX of the 3.9 branch](https://github.com/supercollider/supercollider/blob/3.9/README_LINUX.md).

**Comment by CJunit** [comment]
True enough! Yes, I was reading an older readme. I think I was cloning the master branch and telling it to checkout 3.9.3. Also I needed to point it one directory deeper. Trying Qt 5.5 now. Thanks!
