### ISSUE TITLE
libQt5WebKit.so.5.5.1: undefined reference

### ISSUE THREAD

**Issue by CJunit** [supercollider/supercollider#3908]
Yes, me again! I have installed Qt 5.5, emacs, newer libgstreamer, and made some progress. While compiling now I get a different error, which sounds more like an issue with the SDK content itself. But could entirely be some mistake on my end. Make ends with:

> 
> [ 67%] Linking CXX static library libsclang.a
> [ 67%] Built target libsclang
> [ 67%] Building CXX object lang/CMakeFiles/sclang.dir/LangSource/cmdLineFuncs.cpp.o
> [ 68%] Linking CXX executable sclang
> /home/user/QtSC/5.5/gcc_64/lib/libQt5WebKit.so.5.5.1: undefined reference to `QWindowSystemInterface::registerTouchDevice(QTouchDevice*)'
> /home/user/QtSC/5.5/gcc_64/lib/libQt5WebKit.so.5.5.1: undefined reference to `QQuickFlickable::contentItem()'
> collect2: error: ld returned 1 exit status
> lang/CMakeFiles/sclang.dir/build.make:127: recipe for target 'lang/sclang' failed
> make[2]: *** [lang/sclang] Error 1
> CMakeFiles/Makefile2:3618: recipe for target 'lang/CMakeFiles/sclang.dir/all' failed
> make[1]: *** [lang/CMakeFiles/sclang.dir/all] Error 2
> Makefile:160: recipe for target 'all' failed
> make: *** [all] Error 2

Any ideas? I don't even want to use touch devices. Thanks for your patience!

**Comment by snappizz** [comment]
hmmm... first thing i would try is wiping the build directory and starting again from cmake in case there are remnants of the qt 5.7+ stuff

**Comment by CJunit** [comment]
That was what I thought also, I wiped it and cloned the repository again before I started.

**Comment by snappizz** [comment]
strange. could you post CMakeCache.txt via pastebin, and the complete post output of `cmake ..`?

if you desperately need to get an SC installation going and we can't figure this out, you can always work from the 3.10.0 beta (checkout branch "3.10") -- the qt situation is much less painful, and all the API changes and known issues since 3.9 are fairly minor.

**Comment by brianlheim** [comment]
@CJunit any progress on this?

**Comment by snappizz** [comment]
3.10 is out and this is no longer an issue.
