### ISSUE TITLE
3.10 cmake tries to install examples into `/usr/local/SuperCollider`

### ISSUE THREAD

**Issue by LFSaw** [supercollider/supercollider#3931]
Environment
-----------

* SuperCollider version: 3.10 ( ade01ec82, tested on this but it seems to be the same for `develop`)
* Operating system and version: OSX 10.13.5

Expected Behavior
-----------------

examples should be installed into `build/Install/SuperCollider/` (see `README_OSX`)

I suspect the wrong code to be here:
https://github.com/supercollider/supercollider/blob/3.10/CMakeLists.txt#L472
(at least uncommenting that line helped me to build successfully).
My cmake skills are not so good, unfortunately, to exactly understand what's going on there...

Current Behavior
----------------

examples are tried to be installed (and fail to because of user rights) into  `CMAKE_INSTALL_PREFIX` which is, as per build instructions in `README_OSX` set to default (`/usr/local/`)

Steps to reproduce (for bugs)
-----------------------------

```sh
cmake -G Xcode -DCMAKE_PREFIX_PATH=`brew --prefix qt5`  ..
cmake --build . --target install --config RelWithDebInfo
```

Error message (for bugs)
------------------------

```sh
[...]
=== BUILD AGGREGATE TARGET install OF PROJECT SuperCollider WITH CONFIGURATION RelWithDebInfo ===

Check dependencies

PhaseScriptExecution CMake\ PostBuild\ Rules build10/SuperCollider.build/RelWithDebInfo/install.build/Script-AE42D25A242C480E8B7AC698.sh
    cd /localvol/sound/src/supercollider
    /bin/sh -c /localvol/sound/src/supercollider/build10/SuperCollider.build/RelWithDebInfo/install.build/Script-AE42D25A242C480E8B7AC698.sh
/usr/local/Cellar/cmake/3.11.1/bin/cmake -DBUILD_TYPE=RelWithDebInfo -P cmake_install.cmake
-- Install configuration: "RelWithDebInfo"
-- Installing: /usr/local/SuperCollider/examples
CMake Error at cmake_install.cmake:36 (file):
  file INSTALL cannot make directory "/usr/local/SuperCollider/examples": No
  such file or directory
```

**Comment by prko** [comment]
Could you consider the location of exampls mentioned in #3854 when fixing it?

**Comment by brianlheim** [comment]
I cannot reproduce this, and our CI, which builds the install target, hasn't caught it. Can you please try rebuilding from a fresh build directory?

**Comment by miczac** [comment]
Hi Brian, I'm on 10.12.6 and can reproduce this. 
I regularly compile master from scratch, as I do right now.

**Comment by LFSaw** [comment]
this was from a fresh build dir.

**Comment by miczac** [comment]
I’m sorry, heat induced human error: it should read “… and can’t reproduce this.”!  
Deleted my comment but email notification was faster. :(
I compiled master and also just tried ade01ec:

   @ build mz$ ll Install/SuperCollider/
   total 384
   22172113   0 drwxr-xr-x  9 mz  staff     306 Aug  3 16:51 .
   22172112   0 drwxr-xr-x  3 mz  staff     102 Aug  3 16:51 ..
   22172187  16 -rw-r--r--  1 mz  staff    5820 Nov 13  2016 AUTHORS
   22172185 248 -rw-r--r--  1 mz  staff  125992 Aug  3 15:00 CHANGELOG.md
   22172186  72 -rw-r--r--  1 mz  staff   35147 Sep 24  2016 COPYING
   22172183  16 -rw-r--r--  1 mz  staff    4360 Aug  3 15:00 README.md
   22172184  32 -rw-r--r--  1 mz  staff   14889 Aug  3 15:00 README_MACOS.md
   22172188   0 drwxr-xr-x  3 mz  staff     102 Aug  3 16:51 SuperCollider.app
   22172114   0 drwxr-xr-x  9 mz  staff     306 Aug  3 16:51 examples
   @ build mz$

**Comment by LFSaw** [comment]
re-checked, now works strangely. maybe it's the heat (that makes me see things)...
