### ISSUE TITLE
Reclaim freenode IRC channel

### ISSUE THREAD

**Issue by dvzrv** [supercollider/supercollider#3932]
Hi all,

I'd like to reclaim the #supercollider freenode IRC channel, in which from time to time users actually ask things and people post their stuff. The channel needs a topic update and some love I guess, but I'm in there all the time.
The network has been hit with a wave of spambots lately, but there was noone to set proper channel modes to keep the bots from posting their nonsense.

I'd like to register [supercollider as a group](https://freenode.net/groupreg) and offer myself as the primary contact (as I'm on IRC daily anyhow). Is anyone up for acting as secondary contact?

**Comment by brianlheim** [comment]
@dvzrv Thanks! I'm not sure how many people here are in the IRC channel. I've never been there to be honest. Have you tried asking in other venues (mailing list, forum, Facebook)?

**Comment by dvzrv** [comment]
@brianlheim I'm not sure either. All in all it's 22 in there atm though.
I've sent a [mail to sc-dev about the spam](https://www.listarc.bham.ac.uk/lists/sc-dev/msg58490.html), but not about the group registration (that idea came after talking to freenode staff, because there's none yet).
I've now also opened [a topic in the new forum](https://scsynth.org/t/reclaim-supercollider-irc-channel-on-freenode/271) (who hosts that btw?)

**Comment by dvzrv** [comment]
@brianlheim I sent a (templated) e-mail to freenode's staff (after writing to the staff member "Fuchs" earlier), with you in CC. It would be great, if you could reply "yes" to that!
Thanks!

**Comment by Fuchs** [comment]
Hi, Fuchs would be me, replied with information on what we need  (basically some sort of verification that this was indeed signed off by you, but I think I'd even accept that being done here in this ticket for simplicity), then I'll hand the channel over.

Thanks in advance and sorry for the little administrative overhead, this is just a safety measure.

**Comment by brianlheim** [comment]
Hi Fuchs, yes I received your email and yes I am happy to have David handling the IRC channel.

-Brian

**Comment by Fuchs** [comment]
Great, thanks, I'll do the remaining "paperwork" with him and then hand the channel over. 
I assume he can close this issue once done, at least from our (freenode) side it's all fine now.

**Comment by brianlheim** [comment]
Great!

**Comment by dvzrv** [comment]
Thanks @brianlheim! The channel is re-registered and a new topic is set!
