### ISSUE TITLE
Understanding Streams, Patterns and Events – Example Typing error

### ISSUE THREAD

**Issue by ZeCraum** [supercollider/supercollider#3964]
* SuperCollider version: 3.9.3
* Operating system and version: MAC OSx 10.9.5

Expected Behavior
-----------------
Understanding Streams, Patterns and Events - Part 7
Manipulating an EventStreamPlayer in Realtime

(
e.stream = Pbind(
    [\degree, \dur], Pseq(
        [
            Pseq([[0,0.1],[2,0.1],[3,0.1],[4,0.1],[5,0.8]],2),
            Ptuple([Pxrand([6,7,8,9],4), 0.4]),
            Ptuple([Pseq([9,8,7,6,5,4,3,2]), 0.2])
        ], inf
    ),
    \amp, 0.05,
    \octave, 5,
    \instrument, \help_SPE7_CFString1
).asStream;
)

The h letter from the name of the synthdef should be lowercase (\**h**elp_SPE7_CFString1)

Current Behavior
----------------

(
e.stream = Pbind(
    [\degree, \dur], Pseq(
        [
            Pseq([[0,0.1],[2,0.1],[3,0.1],[4,0.1],[5,0.8]],2),
            Ptuple([Pxrand([6,7,8,9],4), 0.4]),
            Ptuple([Pseq([9,8,7,6,5,4,3,2]), 0.2])
        ], inf
    ),
    \amp, 0.05,
    \octave, 5,
    \instrument, \Help_SPE7_CFString1
).asStream;
)

Error message (for bugs)
------------------------

```
** ERROR: SynthDef Help_SPE7_CFString1 not found
FAILURE IN SERVER /s_new SynthDef not found
FAILURE IN SERVER /n_set Node 5011 not found
*** ERROR: SynthDef Help_SPE7_CFString1 not found
FAILURE IN SERVER /s_new SynthDef not found
FAILURE IN SERVER /n_set Node 5012 not found
*** ERROR: SynthDef Help_SPE7_CFString1 not found
FAILURE IN SERVER /s_new SynthDef not found
```

**Comment by brianlheim** [comment]
@ZeCraum Feel free to open a PR!
