### ISSUE TITLE
sc-ide: multiple preferences windows open at the same time

### ISSUE THREAD

**Issue by htor** [supercollider/supercollider#3975]
in the ide, when you press `cmd+,` you always get a new preferences window opened up, ignoring that you already have one opened. this behaviour is prevented when you use the menu, because the "Preferences..." menu item is greyed out when you have it opened, so the problem exists only with the keyboard shortcut.

Environment
-----------

* SuperCollider version: 3.10.0-beta1 Built from branch 'develop' [49a674608]
* Operating system and version: macos 10.13

Expected Behavior
-----------------

when you press `cmd+,` you don't get a new preferences window opened up if you already have one opened.

Current Behavior
----------------

when you press `cmd+,` you always get a new preferences window opened up, ignoring that you already have one opened.

Steps to reproduce (for bugs)
-----------------------------

hit `cmd+,` twice on macos and see two pref windows open on top of each other.

**Comment by brianlheim** [comment]
#3988. thanks for the suggestion!
