### ISSUE TITLE
[SC-IDE] new colour scheme renders screen-element boundaries indiscernible

### ISSUE THREAD

**Issue by miczac** [supercollider/supercollider#3982]
* SuperCollider version:  3.10' [4dca509f9] / macOS 10.12.6 / Qt 5.11.1 via homebrew

pre https://github.com/supercollider/supercollider/pull/3978
![screen shot 2018-08-13 at 20 29 48](https://user-images.githubusercontent.com/1922103/44051938-839eb6da-9f3b-11e8-95e9-327094484f9d.png)

now, at [4dca509f9] :
![screen shot 2018-08-13 at 20 33 23](https://user-images.githubusercontent.com/1922103/44051968-9b0fa00e-9f3b-11e8-8a94-65b0519d469d.png)

While I can totally understand the point made in https://github.com/supercollider/supercollider/issues/3792, this changes make working with floating windows and docklets hard!

**Comment by snappizz** [comment]
thanks for your patience, the appearance of SCIDE is going to be a bit of a bumpy road in the near future :)

basically we need to change the color of the black borders -- in addition to this issue, they're also ugly on light themes. simple workaround for now is to set the background to a dark gray.

**Comment by miczac** [comment]
i c - no worries, I'll find my way around it! Thanks!!

**Comment by miczac** [comment]
nothing to do here ...

**Comment by miczac** [comment]
BTW, with https://github.com/supercollider/supercollider/pull/3992 this is much better (thanks!), but still remains sometimes challenging. Also since this little pop-up for searching help docs wouldn't appear on the same screen position (admittedly I can't see when it's popping where):

![screen shot 2018-08-22 at 14 09 08](https://user-images.githubusercontent.com/1922103/44462775-fcc39400-a615-11e8-9e65-d54ca249f932.png)
With the 'right' text on the editor window it can become quite a needle in a haystack!  ;)

**Comment by miczac** [comment]
correction - it appears in the middle of the current window, has been doing that since 3.9.3 (at least)
And BTW, the ESC-key won't work anymore. This works in 3.9.3 -> new issue?
