### ISSUE TITLE
can't copy version and hash from "About"-window anymore

### ISSUE THREAD

**Issue by miczac** [supercollider/supercollider#3984]
* SuperCollider version: 3.10' [4dca509] / macOS 10.12.6 / Qt 5.11.1 via homebrew

Expected Behavior
-----------------
It's possible to mark portions of the "About"-pop-up information and copy it.

![screen shot 2018-08-14 at 04 53 08](https://user-images.githubusercontent.com/1922103/44069386-c8998df8-9f7e-11e8-876b-8cc0d7d956fc.png)

Current Behavior
----------------
It's not possible to mark and copy information from the "About"-pop-up anymore:

![screen shot 2018-08-14 at 04 56 30](https://user-images.githubusercontent.com/1922103/44069390-cb2d9a8c-9f7e-11e8-972c-1bb35bb4b500.png)
On macOS the texts behave like images, when dragged with the mouse.

**Comment by brianlheim** [comment]
I have similar libs and macOS version and cannot reproduce. In your second screenshot you can even see that you have text selected. It is standard macOS behavior to show that kind of image drag when you click and drag on selected text.

**Comment by miczac** [comment]
Sorry Brian, you're right - it was merely a colour issue! :/
