### ISSUE TITLE
First time starting server scsynth results in "Windows Installer" popup

### ISSUE THREAD

**Issue by sw1tch73ch** [supercollider/supercollider#3997]
Environment
-----------

SuperCollider 3.9.3 (downloaded 64 bit from "Downloads" page)
Windows 10 Pro (1803) 64-bit 
Input/Output via Sound Blaster ZxR.

I also have several other Sound Devices installed to the system - wireless headphones, motherboard onboard drivers, HDMI Digital Audio drivers.

I previously had SuperCollider 3.8.0 with SonicPI loaded. When I tried to run it prior to trying to upgrade to 3.9.3 I got the same error I'm getting now (which is why I was upgrading - thinking maybe 3.8.0 had become incompatible with Win10)

Steps to reproduce (for bugs)
-----------------------------
Clean Install of SuperCollider 3.9.3 (64 bit) with default directorie (removed 3.8.0 and SonicPI and power cycled the system).
Launch SuperCollider IDE.
Attempt to boot server from scide (Control-B or Right click server status bar and select Boot Server)

Error message (for bugs)
------------------------
I get no errors from SuperCollider. Last message in Post window is:

*** Welcome to SuperCollider 3.9.3. *** For help press Ctrl-D.
SCDoc: Indexing help-files...
SCDoc: Indexed 1338 documents in 0.76 seconds
booting server 'localhost' on address: 127.0.0.1:57110

The section in Task Manager showing scsynth.exe running the installer:
![supercollider-scsynth exe-task](https://user-images.githubusercontent.com/15176315/44336144-1dd08d00-a43c-11e8-8298-f801adfbd533.png)

Expected Behavior
-----------------

Normal startup of SCSYNTH.EXE 

Current Behavior
----------------

Observe several windows pop for Windows Installer. The flip too fast to read the window until it stops at "Windows Installer" with message "Preparing to Install"
Task Manager shows scsynth.exe is the owner of the "Windows Installer" pop up.

**Comment by sw1tch73ch** [comment]
I did some digging through the Windows Event Viewer and found where scsynth.exe was stumbling over an old ASOI MIDI driver (Yamaha Steinberg ASIO 1.9 from 2017) which I'm not currently using. I got that uninstalled and the scsynth server launched as expected.

**Comment by jamshark70** [comment]
I wonder if PortAudio has some switch to poll devices "non-invasively" (i.e. without triggering driver reinstalls)... bc this behavior is bu******. In what other kind of environment (I mean OS) would a basic query for driver name and i/o channels force an installation update?

Would Audacity (which also uses PortAudio) choke on the same driver? There may be no way to know now since the offending driver is removed, but if Audacity or Bitwig or others query devices by some more polite means, maybe it's possible to avoid this.

Then again, in 16 years with SC, this is the one and only time I've heard of this. Other issues are more pressing.

**Comment by sw1tch73ch** [comment]
I do use Audacity. It did not trigger that particular driver to try to install. I don't know why SuperCollider did. The keyboard the driver supports hasn't been plugged in for a while (the part I'm guessing that is in play is that keyboard does Audio Over USB via ASIO - not just MIDI) and so that driver _should_ be inactive. It is definitely inactive now (at least on this computer). Happily, SuperCollider is happy to play sounds now and I have to get back to learning how to make interesting sounds with it.
