### ISSUE TITLE
Clean up SCDoc rendering complaints

### ISSUE THREAD

**Issue by adcxyz** [supercollider/supercollider#3998]
SCDoc.renderAll currently finds one error, and more than 30 complaints in the help source files.
I am starting a branch to clean these up, and have some questions for some of them

macOS 10.13.6, SC 3.10. beta1 

```supercollider
// get the list: 
unixCmd("rm" + quote(SCDoc.helpTargetDir));
SCDoc.renderAll;
```
The glitches in NodeMap, NodeProxy, and Buffer are simple to fix, already done here: 
https://github.com/adcxyz/supercollider/tree/fix_help_glitches

Questions:
```
WARNING: SCDoc: In .../HelpSource/Classes/Pipe.schelp
  Method *argv has arg named 'args', but doc has 'argument:: executableAndArguments'.
WARNING: SCDoc: In .../HelpSource/Classes/Pipe.schelp
  Method -openArgv has arg named 'args', but doc has 'argument:: executableAndArguments'.
```
-> change the argument names in source or in doc? 

```
ERROR: In .../HelpSource/Guides/WritingTests.schelp:
  At line 21: syntax error, unexpected CODE
-> Beside the rendering bug, this is out of date (it still points to UnitTesting quark). 
```
-> @brianlheim - will this be replaced by your extended description soon? 
or should I quick-fix it now, and point forward to it? 

Finally, what to do for the 22 glitches in Image.schelp ?

**Comment by adcxyz** [comment]
Would be nice if 3.10 rendered all help with zero nagging :-)

**Comment by brianlheim** [comment]
The best thing to do for now is fix the documentation so it is accurate. Anything else that you feel is worth changing should be dealt with in a separate ticket.
