### ISSUE TITLE
Server.killAll behavior when switching between scsynth and supernova

### ISSUE THREAD

**Issue by dyfer** [supercollider/supercollider#3999]
Environment
-----------

* Your SuperCollider version: 3.10-beta1
* Your operating system and version: macOS 10.13.06

Steps to reproduce (for bugs)
-----------------------------

```supercollider
//caution - this will force close the interpreter!
(
Server.scsynth;
s.addr.port = 57130; //set non-default port
s.waitForBoot({
	"killall sclang".unixCmd; //kill sclang (no cleanup - server will keep running)
})
)
//-----
//boot the interpreter manually, then:
//-----
//check if the old server is still running - it probably is
"ps ax | grep -E '[s]csynth|[s]upernova'".systemCmd; 

(
Server.supernova; //switch servers;
Server.killAll; //tries to kill supernova; scsynth keeps running;
s.boot; //boots fine, since the old server was using a non-default port
)

//check for scsynth and supernova - both are running
"ps ax | grep -E '[s]csynth|[s]upernova'".systemCmd; 

//you can manually kill scsynth... but should Server.killAll have done it?
"killall scsynth".systemCmd;
```

Error message (for bugs)
------------------------

(No error message)

Expected Behavior
-----------------
This is maybe a very edge case...
If one ends up with a dangling server, and then switches from ```scsynth``` to ```supernova``` (or vice versa), then ```Server.killAll``` option will not necessarily kill the old process. This happens only if the dangling process was booted with a non-default port number or if it's not responding to OSC messages anymore.

Current Behavior
----------------

```Server.killAll``` attempts to kill only the currently chosen server - either ```scsynth``` or ```supernova```. However it also sends ```\quit``` OSC message, so any dangling but responsive server _should_ still quit.

I'm considering whether ```Server.killAll``` should kill both ```supernova``` and ```scsynth``` instances. What do you think?

**Comment by brianlheim** [comment]
Yea, I think it should kill both supernova and scsynth processes, good idea! Mind filing a PR?

**Comment by dyfer** [comment]
I started looking into this... and it's more complicated than I though (to do it in platform-agnostic manner).

- I need to check whether ```thisProcess.platform.killAll("scsynth")``` works on Windows (as opposed to ```.killAll("scsynth.exe")```) 
  - if it does, maybe hardcoding executable names would be fine
- This makes me think about the whole concept of setting ```Server.program``` (in ```*Platform.sc``` file) 
  - it sets the proper name only for ```scsynth```, not ```supernova```
  - Switching from ```scsynth``` to ```supernova``` replaces the executable name in the whole path to the server (```Server.program```)
    - since on macOS it's a full path, this actually fails if SC is put in a folder containing either of these words (e.g. if one puts the app bundle in ```/Applications/SuperCollider_3.9_supernova/``` or similar)
- Finally, why choice of scsynth vs supernova is a class method? I feel that conceptually maybe makes more sense as an instance variable, e.g. ```Server.default.scsynth``` and not ```Server.scsynth```. Although I can see how practically it's very unlikely to have a need for both scsynth and supernova running simultaneously on the same machine.

So what I'm considering is:
- adding two new classvars to Server - ```Server.programScsynth``` and ```Server.programSupernova```
- setting both in the respective ```Platform``` files
- having ```Server.scsynth```/```Server.supernova``` switch the ```Server.program``` to values of (platform-specific) predefined ```.programScsynth``` and ```.programSupernova```
- _possibly_ adding ```.scsynth``` and ```.supernova``` as instance variables, so they can be set per instance if needed

What do you think?
