### ISSUE TITLE
[scide]  crashes when copying a color scheme which just has been copied

### ISSUE THREAD

**Issue by miczac** [supercollider/supercollider#4033]
Versions 
-----------------------------
* SC  3.10' [70b4ba14f] / macOS 10.12.6 / Qt 5.11.1 via homebrew,
* but is also reproducible with SC 3.8.0, 3.8.1, 3.9.3 and most likely anything between 
(didn't check earlier versions)

Steps to reproduce 
-----------------------------
1. In SC-IDE invoke  _Preferences_ -> _Editor_ -> _Font & Colors_

1. Under _Colors_ pick any 'theme' (color setting) or leave what's been presented
1. Click _copy_ and enter new name, confirm with _Enter_ or by clicking _OK_.

1. Then, __immediately__
click _copy_ again and enter another name, confirm with _Enter_ or by clicking _OK_.

Expected Behavior
-----------------
We should get two duplicates of the original theme (from step 2 above)
Of course that's not a typical use-case, but SC shouldn't crash.

Current Behavior
----------------
SC-IDE crashes, language and server gone

Workaround
--------------------
After steps 1 - 3 click _Apply_, then proceed with step 4.

**Comment by miczac** [comment]
I have a hunch that this would happen on all OSs - unless the theme management has been implemented in an entirely different way.
@ Windows and Linux users: Could you confirm (or not) PLS?

**Comment by miczac** [comment]
```
$ ./build/Install/SuperCollider/SuperCollider.app/Contents/MacOS/SuperCollider 
Failed to find theme "default5" ""
Failed to find key  "text"
Received signal 11 SEGV_MAPERR ffff801ae90e0000
 [0x00010811a723]
 [0x7fff8f04cb3a]
 [0x000000000000]
... (skipped)
 [0x7fff7926bb46]
 [0x7fff7926b544]
 [0x7fff787caebc]
[end of stack trace]
Segmentation fault: 11
```

**Comment by snappizz** [comment]
i can repro on linux. the crash seems to be happening in `ScIDE::Settings::EditorPage::loadThemeFormats`. i'll bet you the theme object is a null pointer for some reason.

**Comment by nuss** [comment]
I can confirm this too.
SC 3.9.3
Ubuntu Studio 16.04.5 with kernel 4.14.59-rt37 (I guess it's the same with newer kernels)
Qt 5.51

**Comment by snappizz** [comment]
this seems like a fairly simple issue to debug with a basic understanding of C++, so if anyone would like to have at it, please do. if nobody gets to this in a few days i'll take a look at it.

**Comment by brianlheim** [comment]
The relevant code is here: https://github.com/supercollider/supercollider/blob/develop/editors/sc-ide/widgets/settings/editor_page.cpp#L143

and here: https://github.com/supercollider/supercollider/blob/b284f981fa361abd90a9188f383b5ea50806041c/editors/sc-ide/core/settings/theme.cpp#L108
