### ISSUE TITLE
scsynth on Windows does not guard denormals

### ISSUE THREAD

**Issue by jamshark70** [supercollider/supercollider#4046]
Environment
-----------

* Your SuperCollider version: 3.9.3 (32-bit and 64-bit)
* Your operating system and version: Windows 10 Pro

Issue
-----

We have a report on sc-users of scsynth behavior in Windows matching the profile of denormals *not* being flushed to 0: both reverbs and allpass delays with feedback caused the CPU to ramp up dramatically if they had been receiving a signal, but then the input signal stopped (allowing the feedback to get smaller and smaller).

Beginning of the thread: https://www.listarc.bham.ac.uk/lists/sc-users/msg62124.html

The user says he is using SC3.9.3 downloaded from https://supercollider.github.io/download, tried both the 32-bit and 64-bit builds. OS is Win10 Pro (64 bit).

We are supposed to be flushing denormals -- logging this for investigation into why we might not be.

EDIT: If it's a denormal problem, this should reproduce it. The test case that the user posted to the mailing list uses FreeVerb2. (In my Linux system, CPU use remains stable after running this.)

```
(
s.waitForBoot {
	SynthDef(\reverb, {
		arg in, out, dry = 1, room = 0.5, damp = 0.35;
		var sig = In.ar(in, 2);
		sig = FreeVerb2.ar(sig[0], sig[1], 1 - dry, room, damp);
		ReplaceOut.ar(out, sig);
	}).add;
	s.sync;
	x = Synth(\reverb, [dry: 0.5], addAction: \addToTail);
	{
		var sig = SinOsc.ar(220, 0, 0.1),
		eg = EnvGen.kr(Env.perc(0.01, 0.15), doneAction: 2);
		(sig * eg).dup
	}.play;
};
)
```

**Comment by sonoro1234** [comment]
sc_SetDenormalFlags is the function. The only reason for not being applied seems to be compiling whitout SSE (which I dont thing it is happening)

**Comment by zeos** [comment]
Hi, I ran into this issue and wrote about it on the mailing list. Didn't try with sc 3.8 / supernova, but it is present in 3.9.x

**Comment by sonoro1234** [comment]
I have tried my compiled scsynth from develop: no issue.
Also checked scsynth 3.9.2 with my Lua2SC client and sclang client: issue is happenning, CheckBadValues reports denormals.

Has to be a compilation issue (perhaps SSE not defined?)

**Comment by jamshark70** [comment]
Oh, @ me? I don't even have access to a working Windows machine for the moment, and I definitely don't have MSVC.

I just reported it out of courtesy; I'm afraid I'm not in a position to do any more with it.

**Comment by snappizz** [comment]
i can confirm that FreeVerb2 in scsynth on 3.10.0-beta2 experiences denormal issues.

**Comment by sonoro1234** [comment]
On windows?

**Comment by snappizz** [comment]
yes. i just used the binary from the github release page.

**Comment by sonoro1234** [comment]
Who can implement things pointed in
https://github.com/supercollider/supercollider/issues/4046#issuecomment-419872211

**Comment by sonoro1234** [comment]
zapgremlins is not needed when denormal handling is setted.
So we should first let denormal handling work in windows (msvc) builds

**Comment by sonoro1234** [comment]
This should be added before the code in 
https://github.com/supercollider/supercollider/blob/develop/server/scsynth/SC_World.cpp#L167
and
https://github.com/supercollider/supercollider/blob/develop/server/supernova/server/server.cpp#L230
```
#ifdef _MSC_VER
#if (defined(_M_AMD64) || defined(_M_X64))
#define __SSE2__
#define __SSE__
#elif _M_IX86_FP == 2
#define __SSE2__
#define __SSE__
#elif _M_IX86_FP == 1
#define __SSE__
#endif
#endif 
```

**Comment by sonoro1234** [comment]
It is just that I cant test it with msvc

**Comment by jrsurge** [comment]
ran into this yesterday while writing a reverb synthdef, currently testing your fix @sonoro1234

**Comment by sonoro1234** [comment]
> ran into this yesterday while writing a reverb synthdef, currently testing your fix @sonoro1234

Did it work?

**Comment by snappizz** [comment]
i'm not wild about redefining `__SSE__` and `__SSE2__`. seems hacky. i'd be more comfortable with abstracting the presence of these instruction sets with something like `SC_SSE` and `SC_SSE2`.

**Comment by sonoro1234** [comment]
It is not redefining as they are not defined in MSVC. The purpose is to trigger
https://github.com/supercollider/supercollider/blob/develop/server/scsynth/SC_World.cpp#L153
and
https://github.com/supercollider/supercollider/blob/develop/server/supernova/server/server.cpp#L210

**Comment by jrsurge** [comment]
> Did it work?
yup, it does work. Sorry, forgot to reply.

**Comment by sonoro1234** [comment]
PR should be done!!

**Comment by jrsurge** [comment]
sorry @sonoro1234, I didn't see this mention.

I was reluctant to submit a PR because it wasn't my fix, and I don't fully understand it.

From my perspective, shouldn't definitions like these be set with cmake rather than def'd in the source files?

**Comment by snappizz** [comment]
victor has the correct way of *detecting* SSE on windows, but `#defining` `__SSE__` and `__SSE2__` is a reserved identifier violation. usually this will create compiler warnings.

instead we should make new macros like SC_SSE and SC_SSE2 in `include/common` or something.

**Comment by jrsurge** [comment]
> victor has the correct way of _detecting_ SSE on windows, but `#defining` `__SSE__` and `__SSE2__` is a reserved identifier violation. usually this will create compiler warnings.
> 
> instead we should make new macros like SC_SSE and SC_SSE2 in `include/common` or something.

I'd vote for having the detection of features being done by the build system, setting the definition (SC_SSE etc.) as needed via that? IIUC, that is what this code was expecting.

Since cmake-v3.10, looks like cmake can do it:

https://cmake.org/cmake/help/v3.10/command/cmake_host_system_information.html

But that'd involve bumping our cmake_minimum_required
