### ISSUE TITLE
scsynth should support long command-line options like supernova

### ISSUE THREAD

**Issue by snappizz** [supercollider/supercollider#4048]
scsynth only supports short command-line options (`-h`) while supernova also supports long (`--help`).

the scsynth command-line arguments code should be refactored to use `boost::program_options` like supernova uses.

this is a great task to do if you want to try your hand at C++ but don't want to do any really deep server architecture stuff.

**Comment by brianlheim** [comment]
I am going to close this because it is kind of equivalent to #3117 - I wouldn't want anyone to fix this without moving to boost::program_options, and once the CLI moves to that, it'll be easy to add the longopts.
