### ISSUE TITLE
SC 3.10 beta 2 : no fadein for Ndef

### ISSUE THREAD

**Issue by geoffroymontel** [supercollider/supercollider#4060]
Environment
-----------

SC 3.10 beta 2 (binary release)
SC3 plugins 3.10 beta 1 (binary release)
Mac OS X 10.12.6

Steps to reproduce (for bugs)
-----------------------------

If I run

```supercollider
Ndef(\x).fadeTime = 10;
Ndef(\x).play;
Ndef(\x, { SinOsc.ar(440) * 0.1 });
```

then
```supercollider
Ndef(\x, { SinOsc.ar(880) * 0.1  });
```

I can hear the 440 hz sine fading out for 10 second, but but the 880 hz sine plays right away, there’s no fade in

Expected behaviour
-----------------------------
The 880 sine wav would fade in for 10 seconds

**Comment by snappizz** [comment]
i can repro this. cc @telephon

**Comment by telephon** [comment]
This has happened here: https://github.com/supercollider/supercollider/commit/9965e422c20a1e3281f8532498ff0ac1e33be2dc#diff-fcf23ae680444b9a7c283c5064036bdd

I don't remember the discussion. Probably that change was too intrusive.

**Comment by geoffroymontel** [comment]
thanks !!
