### ISSUE TITLE
SC 3.10 beta 2: help system not available with EMACS on Ubuntu Trusty

### ISSUE THREAD

**Issue by novadeviator** [supercollider/supercollider#4074]
Environment
-----------

* Your SuperCollider version: SC 3.10 beta 2
* Your operating system and version: Ubuntu Linux Trusty with QT 5.10

Steps to reproduce (for bugs)
-----------------------------

download source-linux tarball from github releases page - SC 3.10 beta 2
install QT 5.10 for trusty using ppa as instructed
compile SC using cmake and make

Expected Behavior
-----------------
In emacs, loading supercollider, and running help system with C-c C-y
one should see fully functional Help system.

Current Behavior
----------------

white qt window appears but help system is not available

emacs reports in SC post window
```
QObject::connect: No such slot QtCollider::WebView::onRenderProcessTerminated(RenderProcessTerminationStatus, int)
SCDoc: Indexing help-files...
SCDoc: Indexing help-files...
SCDoc: Indexed 1383 documents in 1.48 seconds
SCDoc: Indexed 1383 documents in 1.68 seconds
````

in SCIDE it works as expected - also using assinged (dark) qt theme, while this does not happen with EMACS invocation - it's peculiarly white.

(dark gray of scide help system is a consequence of slightly modified scdoc.css)

![screenshot - 20 09 2018 - 08 43 48](https://user-images.githubusercontent.com/744626/45800983-d7788300-bcb2-11e8-83f2-2145467ee913.png)
![screenshot - 20 09 2018 - 08 52 49](https://user-images.githubusercontent.com/744626/45800982-d7788300-bcb2-11e8-81fb-34fa57675466.png)

**Comment by novadeviator** [comment]
help system works out of the box with final 3.10 release with Emacs. I think this issue could be closed.

**Comment by snappizz** [comment]
thanks for retesting! closing.
