### ISSUE TITLE
ServerStatusWatcher now returns sampleRate as Floats

### ISSUE THREAD

**Issue by blacksound** [supercollider/supercollider#4107]
Environment
-----------

* Your SuperCollider version: 3.10.0-beta2
* Your operating system and version: macOS 10.13.5 (17F77) 
SHA: 937a2615bf30208e09aaa93ecd3b1d13aa862950
branch: develop

Steps to reproduce (for bugs)
-----------------------------

```supercollider
//in 3.9.3 release
s.boot;
s.sampleRate; // --> 44100 (an Integer)

//in 3.10.0-beta2 @937a261
s.boot;
s.sampleRate; // --> 44100.0  (a Float)

```

Expected Behavior
-----------------

`s.sampleRate` should IMO return integer values. E.g. ATK switch statements for kernel selection depends on it.

Current Behavior
----------------
The latest version return sample rate as floats. I have tried to look into the ServerStatusWatcher but could not find any change there. Has anything changed in the status message that is sent from the scsynth?

**Comment by blacksound** [comment]
Here is the output from the ServerStatusWatcher. The difference is in what format is sent to sclang from scsynth.

```
//output in 3.9.3
AAA: [ /status.reply, 1, 0, 0, 2, 108, 0.048607379198074, 0.0739880874753, 44100, 44099.928089238 ]
AAA: [ /status.reply, 1, 0, 0, 2, 108, 0.052758786827326, 0.09427236020565, 44100, 44099.964657314 ]
AAA: [ /status.reply, 1, 0, 0, 2, 108, 0.058001361787319, 0.10947480797768, 44100, 44099.963523244 ]
AAA: [ /status.reply, 1, 0, 0, 2, 108, 0.04792807623744, 0.16347146034241, 44100, 44099.850339479 ]
AAA: [ /status.reply, 1, 0, 0, 2, 108, 0.044928975403309, 0.16347146034241, 44100, 44099.945223984 ]
AAA: [ /status.reply, 1, 0, 0, 2, 108, 0.044845536351204, 0.074332617223263, 44100, 44099.938285824 ]
AAA: [ /status.reply, 1, 0, 0, 2, 108, 0.027277939021587, 0.11762297153473, 44100, 44099.942955884 ]
AAA: [ /status.reply, 1, 0, 0, 2, 108, 0.053817231208086, 0.15979360044003, 44100, 44099.936876193 ]


//3.10 beta 2
BBB: [ /status.reply, 1, 0, 0, 2, 108, 0.057094238698483, 0.11175732314587, 44100.0, 44100.064457193 ]
BBB: [ /status.reply, 1, 0, 0, 2, 108, 0.05881916731596, 0.11175732314587, 44100.0, 44100.072974733 ]
BBB: [ /status.reply, 1, 0, 0, 2, 108, 0.062828935682774, 0.12048257887363, 44100.0, 44099.998097418 ]
BBB: [ /status.reply, 1, 0, 0, 2, 108, 0.053151618689299, 0.34402307868004, 44100.0, 44099.940466851 ]
BBB: [ /status.reply, 1, 0, 0, 2, 108, 0.048190362751484, 0.066434241831303, 44100.0, 44099.933421811 ]
BBB: [ /status.reply, 1, 0, 0, 2, 108, 0.083089001476765, 0.3684675693512, 44100.0, 44100.163109594 ]
BBB: [ /status.reply, 1, 0, 0, 2, 108, 0.057129316031933, 0.3684675693512, 44100.0, 44100.17489691 ]

```

Notice that the sample rate value is sent as Integer in 3.9.3 and in 3.10 it is sent as Floats.

**Comment by blacksound** [comment]
The type tag for the `/server.status` package is indeed `d` ( https://github.com/supercollider/supercollider/blob/2ccd227192d7d2b08f5b7425ae0650bcbf8775be/server/scsynth/SC_SequencedCommand.cpp#L1241 ). This hasn't been changed in years. So i'm reading that the intention has for a long time been that the sample rate should been sent as doubles.

I therefore propose the following solution:
Make Server-sampleRate getter that returns integers.
optionally in addition:
Make Server-sampleRateFloat to return the float value from the ServerStatusWatcher.

I'd like to get some feedback on this before I make a pull request.

**Comment by patrickdupuis** [comment]
Thanks for the report. I'm able to reproduce.

This is probably the result of: https://github.com/supercollider/supercollider/pull/3585

It's likely that `s.sampleRate` always returned a Float, but it used to look like an Int.

**Comment by blacksound** [comment]
Closing this issue, see #4108
