### ISSUE TITLE
Quarks.install( bad/file) leads to library failure

### ISSUE THREAD

**Issue by celesteh** [supercollider/supercollider#4109]
Environment
-----------

* Your SuperCollider version: 3.93
* Your operating system and version: Recent OS X

Steps to reproduce (for bugs)
-----------------------------

I asked my students to install a folder containing a quark and some of them didn't unzip it first - ergo it wasn't a valid quark.  When they later tried to recompile their class library, it failed

```supercollider
Quarks.install("/A/Real/File/That/Is/Not/A/Quark")
```

Expected Behavior
-----------------

The Quarks install, ideally should check if the thing it is installing is actually a quark. If it is missing key features - such as being the wrong file type, not having any sccode files, etc, it should not install it and throw an error.

Current Behavior
----------------

Currently, junk data is installed in such a way that causes the library to fail to compile, so that students are stuck and have to look online for solutions.

**Comment by brianlheim** [comment]
This is a nice-to-have feature, and I'd review a PR if someone wanted to implement it.

Since we don't have any strict requirements on what is and isn't a quark, I think the best we can do is show a warning that gives the command to uninstall whatever you just installed. Not having any .sc files seems like a good condition for that. I'm not sure what you mean by "the wrong file type".

**Comment by celesteh** [comment]
When I say wrong file type, I mean that some of my students tried to install a zipfile as a quark.  If this wants a folder or an a Supercollider file (code or help?) then we should check it's one of those things.

**Comment by geoffroymontel** [comment]
@celesteh can we close this issue now that you can't install a Quark if the path is not a folder ? is it good enough ?

**Comment by lvm** [comment]
In addition to the path being a directory, the Quark class already provides a method ([parseQuarkFile](https://github.com/supercollider/supercollider/blob/develop/SCClassLibrary/Common/Quarks/Quark.sc#L256)) to verify if the Directory has a `.quark` file.

**Comment by celesteh** [comment]
Thanks for this!
