### ISSUE TITLE
Sessions: fix persistence of dock widget sizes

### ISSUE THREAD

**Issue by jamshark70** [supercollider/supercollider#411]
I like the post window to the left on my screen, but it's a bit narrow for my taste. If I drag the divider to make it wider and then quit the IDE, that arrangement is not saved and I start again with a narrow post window.

The position also seems not to be saved into a session.

**Comment by scztt** [comment]
This is fixed in qt5, on osx. Someone want to verify on Linux? I have a feeling we can close....

**Comment by telephon** [comment]
feel free to reopen if this comes up again. I suppose it happens only when you have not yet created a single session.
