### ISSUE TITLE
Possible uninitialized memory with StkInst --> HPF

### ISSUE THREAD

**Issue by jamshark70** [supercollider/supercollider#4111]
Environment
-----------

* Your SuperCollider version: 90f968b23e (sc3-plugins: 0ef50c2a10)
* Your operating system and version: Ubuntu Studio 16.04

Issue summary
-------------

I'm just reporting this. I'm afraid I'm not going to be able to do extensive testing beyond what I've already done.

valgrind reports uninitialized memory in zapgremlins(), coming from HPF_next_1(). However, I can reproduce this only when HPF's input is StkInst. So I suppose the problem is really there.

I can simplify it this far.

```supercollider
Server.default = s = Server.remote(\debug, NetAddr("127.0.0.1", 57110), s.options);

// in a terminal, run:
// valgrind --track-origins=yes scsynth -u 57110 -a 1024 -i 2 -o 2 -b 1026 -m 131072 -R 0 -C 0 -l 1

// then:
(
SynthDef(\stkflute, { |out, gate = 1, amp = 0.1, freq = 440, hpfreq = 150|
	var sig = StkInst.ar(Stk.at("Flute"),
		freq,
		gate,
		onamp: amp, offamp: amp,
		args: [
			2, 70,  // jet delay
			4, 20,  // noise gain
			11, 55,  // vibrato freq
			1, 50,  // vibrato gain
			128, 70,  // breath pressure
		]
	);
	sig = HPF.ar(HPF.ar(sig, hpfreq), hpfreq);
	DetectSilence.ar(sig, doneAction: 2);
	Out.ar(out, sig.dup);
}).add;
)

(instrument: \stkflute).play;
```

Result:

```
==32052== Thread 9:
==32052== Conditional jump or move depends on uninitialised value(s)
==32052==    at 0x361D8370: zapgremlins (SC_InlineUnaryOp.h:342)
==32052==    by 0x361D8370: HPF_next_1 (FilterUGens.cpp:2879)
==32052==    by 0x44FB7D: Graph_FirstCalc(Graph*) (SC_Graph.cpp:443)
==32052==    by 0x456539: Group_Calc (SC_Group.cpp:72)
==32052==    by 0x456539: Group_Calc (SC_Group.cpp:72)
==32052==    by 0x44F281: SC_JackDriver::Run() (SC_Jack.cpp:529)
==32052==    by 0x44F5BB: sc_jack_process_cb(unsigned int, void*) (SC_Jack.cpp:187)
==32052==    by 0x5AF8C1D: ??? (in /usr/lib/x86_64-linux-gnu/libjack.so.0.1.0)
==32052==    by 0x5AF8057: ??? (in /usr/lib/x86_64-linux-gnu/libjack.so.0.1.0)
==32052==    by 0x5B1067F: ??? (in /usr/lib/x86_64-linux-gnu/libjack.so.0.1.0)
==32052==    by 0x50466B9: start_thread (pthread_create.c:333)
==32052==    by 0x6CEA41C: clone (clone.S:109)
```

I began investigating this because the synth produced a large "pop" at onset, but only sometimes. The fact that it's sporadic made me suspect uninitialized memory. I don't know how to interpret the valgrind results, but I can note the following:

- When I run StkInst without HPF (comment out the HPF line), valgrind reports no issue.
- When I run HPF without StkInst, valgrind reports no issue. (`a = { HPF.ar(PinkNoise.ar, 1000) }.play`)
- When I run StkInst --> HPF, issue.
  - I can consistently reproduce this by playing the `\stkflute` synth immediately after starting the server. It isn't consistently reproducible after some other synth has already played.

(My workaround was to add a quick fade-in to suppress the "pop." I think that shouldn't be necessary, though.)

**Comment by snappizz** [comment]
StkInst is in sc3-plugins. could you move this issue there please? thanks

**Comment by jamshark70** [comment]
OK.

I thought it wasn't unreasonable to put it here because all of the stack frames from valgrind are in core (at least, I don't see any sc3-plugins source files named there). But if the rule is "if you need something from sc3-plugins to reproduce it, then we'll assume initially it's an sc3-plugins issue," I can live with that.

**Comment by snappizz** [comment]
i'm certain it's just a Ctor sample that wasn't set, which is always an issue in the plugin code and not scsynth.
