### ISSUE TITLE
[SC-IDE] Add shortcut to open the class browser

### ISSUE THREAD

**Issue by jamshark70** [supercollider/supercollider#412]
In Emacs, I created a key binding to open the class browser for the identifier where the cursor is.
- If the identifier is an existing class, open the browser to that class.
  
  `'Synth'.asClass.browse`
- If the identifier begins with a capital letter but is not an existing class, open the browser with a class search for that string.
  
  `Object.browse.searchClasses("NodeW", 0, 0)`
- If it begins with a lowercase letter, open the browser with a method search.
  
  `Object.browse.searchClasses("set", 1, 0)`
- If there is no identifier, open the browser to Object.
  
  `Object.browse`

It's really handy. The class browser is lighter weight than the help browser and doesn't have the problem of out of date help sources.

This shouldn't be especially difficult, but obviously not a critical feature request.

**Comment by brianlheim** [comment]
Checking up on some old issues - is this still valid?

**Comment by htor** [comment]
isn't this what cmd-d does?
