### ISSUE TITLE
[scsynth] Accessing allocated memory from RT pool using C++ style wrapper fails

### ISSUE THREAD

**Issue by michaeldzjap** [supercollider/supercollider#4124]
Environment
-----------

* Your SuperCollider version: 3.9.3
* Your operating system and version: macOS High Sierra 10.13.6

Steps to reproduce (for bugs)
-----------------------------

It is necessary to build two example UGens to reproduce the problem. Source for this:
[UGenTests.zip](https://github.com/supercollider/supercollider/files/2475246/UGenTests.zip). After building the two UGens and moving the relevant files to the _Extensions_ folder try the following 3 cases:

1. This fails (see next section for error)
```supercollider
s.boot; s.scope;

{ Test.ar(WhiteNoise.ar(0.1) ! 2) }.play
```

2. This works
```supercollider
s.boot; s.scope;

{ Test2.ar(WhiteNoise.ar(0.1) ! 2) }.play
```

3. This also works (kind of...)
```supercollider
s.boot; s.scope;

{ Test2.ar(WhiteNoise.ar(0.1) ! 2) }.play
```

Now free the synth and try
```supercollider
{ Test.ar(WhiteNoise.ar(0.1) ! 2) }.play
```
Now this does work if you start the synth right away. If you wait for a minute or so it fails again (garbage collection of allocated memory???)

Error message (for bugs)
------------------------
For the first case, the server quits unexpectedly posting this in the SC console:
```
RESULT = 0
server 'localhost' disconnected shared memory interface
```

Expected Behavior
-----------------

I would expect, given that I've done the memory allocating and free'ing in the UGen code correctly, that the `Test` UGen should not crash the server when ran.

Current Behavior
----------------

Clearly something goes wrong with allocating memory using the C++ style wrapper. It could very well be that I am misunderstanding something and hence, the error is entirely my fault. However, I cannot figure out myself what I might have done wrong. As far as I can tell I have followed the appropriate steps translating the old C way of doing this to the new C++ way.

**Comment by sonoro1234** [comment]
may be that
https://github.com/supercollider/supercollider/blob/develop/include/plugin_interface/SC_PlugIn.hpp#L270

should be called at the end of constructor?

**Comment by michaeldzjap** [comment]
Ah I see! Good catch. That indeed seems to be the problem: Looking at its definition, `set_calc_function()` doesn't only set the calculation function, it also computes the first sample using the specified function. Hence, if you do this as the very first thing in your constructor before defining / initialising your state variables then things will go wrong understandably. Replacing the `next()` call with `set_calc_function()` solved it.

So actually there are some errors in the example files:

This:
https://github.com/supercollider/example-plugins/blob/d0622ac6a4919bc7db134561d292d71337a9823d/02b-MySaw/MySaw2.cpp#L15
should _not_ happen first, but last and
https://github.com/supercollider/example-plugins/blob/d0622ac6a4919bc7db134561d292d71337a9823d/02b-MySaw/MySaw2.cpp#L30
is redundant

Same for https://github.com/supercollider/example-plugins/blob/d0622ac6a4919bc7db134561d292d71337a9823d/01b-BoringMixer/BoringMixer.cpp#L17
that seems redundant as well.

Actually, there are already two open issues for this:
https://github.com/supercollider/example-plugins/issues/9
https://github.com/supercollider/example-plugins/issues/8

Will leave a comment there and this can be closed I guess. Thanks for your help @sonoro1234
