### ISSUE TITLE
[suggestion/discussion] - supercollider/supercollider - renewing IDE (possible future layouts)

### ISSUE THREAD

**Issue by tem44** [supercollider/supercollider#4143]
TOPIC - [suggestion/discussion] - supercollider/supercollider - kodi style IDE

Heyho Everyone 

First of all:
- I didn't really know how to label this;
 - a feature request would be probably be asking too much of the supercollider dev community which is within sense pretty small
 - calling it a suggestion/discussion seemed to be far much more a better idea, once that's really what it is (without being willing to sound way too pretentious, in fact)

So bearing this in mind, I would like to point out the following need:
- supercollider hasn't seen a major update in terms of UI since 2012, or 2013, at least as far as I am concerned
- It would be interesting, within certain regard, to consider some major updates in terms of UI/UX/Frontend, namely in what regards to getting a new UI/UX/Frontend for the major supercollider distribution which would be:
 - extremely smooth, lightweight, minimalistic, fast, elegant
 - automatically scalable in terms of its overall layout in what regards to overall:
 - - machine performance, machine robustness, graphic sex appeal, etc.

my suggestion is bearing in mind for instance:
- some current react.js/electron/node.js apps which are there on the market, and allow for:
 - developing integrated solutions out javascript which:
  - run on any platform (by being universal in their demands and specifications)
  - are lightweight, fast sophisticated and robust

in terms of apps that follow these kinds of specifications, you have:
- skype, discord, slack

with a different stack and a different concept, perhaps also definitely worth checking for:
- some apps based on supercollider which follow this kind of concept (like the Fluxus IDE which follows a very interesting concept, just would need specific language bindings and a couple iterations to fit supercollider stack)
- some app such as Kodi, which follow a pretty interesting concept and layout and could definitely be adopted as a test case for what we are here looking for

**Comment by Sciss** [comment]
I don't understand - Kodi, do you mean this: https://kodi.wiki/view/Skin_screenshots - how would that be a test case for SuperCollider IDE ?

**Comment by tem44** [comment]
@Sciss  when I talk about Kodi and Fluxus, I am more talking about an overall UI/UX concept, in the sense of having a graphics accelerated full-screen application that works as a frontend to something like in this case supercollider. I think that could work quite well, and in the end, a thesis vs anthesis of the two concepts can work. something like, ok let's set up a UI that's electron/react/node based, whatever, and then let's bind it to some cool frameworks such as p5.js, three.js, or other javascript based frameworks which allow for accelerated graphics, and let's in the end, allow them to interact with scsynth by keeping the same syntax style. that could work pretty decently/effectively

**Comment by brianlheim** [comment]
I think it's fair to say overhauling our toolchain is not only out of scope for current development but would also be a waste of time since there is no good reason for doing so. You are more likely to achieve the goals listed by working within the existing effort. I believe this has also been discussed in previous tickets and the outcome was the same.
