### ISSUE TITLE
Interval(0,1,1/3).asArray crashes sclang because forBy doesn't count with floats <1

### ISSUE THREAD

**Issue by olafklingt** [supercollider/supercollider#4154]
Environment
-----------

* Your SuperCollider version:  3.9.3 
* Your operating system and version: on arch linux

Steps to reproduce (for bugs)
-----------------------------

```supercollider
Interval(0,1,1/3).asArray
```
crashes

forBy is called within asArray  (from Interval:do)
```supercollider
forBy(0, 1, 0/3, {|i|i.postln});
```

outputs a endless stream of 0 and crashes

I would expect that forBy would count on the basis of floats as well but it seems that the fractional part of the float is cut.

```supercollider
forBy(0, 1, 1.6, {|i|i.postln});
```
counts by steps of 1

**Comment by brianlheim** [comment]
Thanks for the report, I'm happy to say this was already fixed in 3.10 (#3804). Please check existing issues before opening new ones.
