### ISSUE TITLE
help browser: content scrolls out of viewport

### ISSUE THREAD

**Issue by htor** [supercollider/supercollider#4163]
when scrolling vertically and horizontally against document boundaries in the help browser, the content gets dragged out of the viewport and snapped back again. (this might be only on macOS). 

in normal web browsers this does not happen, unless the content overflows and you have `overflow:  scroll` or similar. here, the entire motion takes about a second until it animates/eases back into position. this is makes it very *annoying* to scroll inside the help browser.

Environment
-----------

* Your SuperCollider version:
SuperCollider 3.10.0-rc1
Built from branch 'HEAD' [9bec036]
* Your operating system and version:
macos 10.13

Steps to reproduce (for bugs)
-----------------------------

scroll inside the help browser against document boundaries and see the "scroll-snapping" take place.

Expected Behavior
-----------------

scrolling against boundaries doesn't move content outside the viewport.

Current Behavior
----------------

scrolling against boundaries moves content outside the viewport.

**Comment by htor** [comment]
can't reproduce this behaviour anymore in 3.10.2. so, somebody on a mac, windows or linux could test it and confirm this fixed, i'll close it.

**Comment by snappizz** [comment]
fixed!
