### ISSUE TITLE
Float:asCompileString returns x.0.0 for .0 values

### ISSUE THREAD

**Issue by LFSaw** [supercollider/supercollider#4164]
Environment
-----------

* Your SuperCollider version: cb6e2ee62

* Your operating system and version: OSX 10.13.6

Steps to reproduce (for bugs)
-----------------------------

calling `asCompileString` on a float with zero in its mantissa (fractional part is 0) results in strange behviour.

```supercollider
1.0.asCompileString
```

Expected Behavior
-----------------

-> 1.0

Current Behavior
----------------

-> 1.0.0

of course, trying to evaluate `1.0.0`  (which is the point for `asCompileString`) results in a parse error.

**Comment by snappizz** [comment]
thanks for the report. this isn't an issue in SC but rather the consequence of a poor decision in the adclib quark to override this method. this can be solved by updating or uninstalling adclib.

**Comment by LFSaw** [comment]
Thanks for the note. I updated adclib and it works fine now. Too many places to look for possible errors...
