### ISSUE TITLE
"web address".openOS is executed with a long delay (at least 25 seconds)

### ISSUE THREAD

**Issue by prko** [supercollider/supercollider#4174]
Environment
-----------

* Your SuperCollider version: 3.10.0-rc1
* Your operating system and version: macOS 10.14.1

Steps to reproduce (for bugs)
-----------------------------

```supercollider
"https://supercollider.github.io/".openOS
```

Error message (for bugs)
------------------------

```
no error
```

Expected Behavior
-----------------
The webpage must be open in a short moment

Current Behavior
----------------
The following message
```
-> https://supercollider.github.io/
```
appears in the post window about 25 seconds later after evaluating the code, and then the web-page is open in the default web-browser.

It is strange because of the following two reasons:
1. I have never experienced this.
2. The following code
```
(
(Platform.resourceDir.replace("/SuperCollider.app/Contents/Resources", "")
+/+ "examples/pieces/hommage_a_duerer.scd").openOS//openDocument
)
``` 
works normally.

**Comment by brianlheim** [comment]
this is an issue with Mojave and codesigning. I believe @scztt has more info. Closing as we already have an open issue for codesigning. (#3438)
