### ISSUE TITLE
[IDE] Can only have one instance of IDE open at a time

### ISSUE THREAD

**Issue by brianlheim** [supercollider/supercollider#4177]
Environment
-----------

* Your SuperCollider version: 3.10.0
* Your operating system and version: MacOS 10.13.6

Steps to reproduce (for bugs)
-----------------------------

Try two open two separate instances of the IDE. The second one doesn't open.

This is a direct result of https://github.com/supercollider/supercollider/pull/3960; the second IDE instance tries to open its web socket on the same port and fails. When run from the command line this is the output:

```
Failed to open web socket server.
Received signal 6
 [0x000117450773]
 [0x7fff67fa6f5a]
 [0x00011585a960]
 [0x7fff67d441ae]
 [0x000110a8dadd]
 [0x00010f268ba3]
 [0x7fff67c98015]
[end of stack trace]
Abort trap: 6
```

Not sure if this is a 'bug' or a 'feature'. If it's a bug, the IDE could communicate to the help browser what port it's using, and find one by linearly scanning if the hardcoded one isn't available. Not sure off the top of my head how to do that. Maybe by setting local storage in the web view or executing a JS snippet on creation. At any rate this value needs to be available in the help browser's JS code.

If it's a 'feature', we should just show a popup that says 'you can't do that!' and quit.

**Comment by snappizz** [comment]
fixed in #4267. thanks for the help @brianlheim!!!! :) :)
