### ISSUE TITLE
SeqenceableCollection:-order doesn't correctly pass (array) objects to its function's arguments

### ISSUE THREAD

**Issue by mtmccrea** [supercollider/supercollider#4179]
Environment
-----------

* Your SuperCollider version: 3.10.0
* Your operating system and version: macOS 10.12.6

Steps to reproduce (for bugs)
-----------------------------
Case 1: new array to order on every iteration, breaks when arr.size >= 14
```supercollider
(
block { |break|
	5000.do{ |i|
		var arr, order;
                // interleave zeros into the array, make pairs
		arr = 14.collect{ rrand(0, 1.0) };
		arr = [0.dup(arr.size), arr].lace(arr.size*2).clump(2);
		
		order = arr.order{|a, b| 
			// test 
			try {a.minItem} { |err|
				postf("oops broke on iter %, a.minItem\n\ta: %\n\tb: %\n\ta should be: %\n\tarr: %\n \tarr shape, num elems: %, %\n\n", 
					i, a, b, arr.select(_.includes(a))[0], arr, arr.shape, arr.flat.size
				);
				err.errorString.postln; break.();
			};
			try {b.minItem} { |err|
				postf("oops broke on iter %, b.minItem\n\ta: %\n\tb: %\n\tb should be: %\n\tarr: %\n \tarr shape, num elems: %, %\n\n", 
					i, a, b, arr.select(_.includes(b))[0], arr, arr.shape, arr.flat.size
				);
				err.errorString.postln; break.();
			};
			
			a.minItem >= b.minItem and: { a.maxItem >= b.maxItem };
		};
	};
	"Made it! Lucky you.";
};
)
```
Case 2: array to order is defined outside the loop, seems OK
```supercollider
(
// interleave zeros into the array, make pairs
var arr = 14.collect{rrand(0, 1.0)};
arr = [0.dup(arr.size), arr].lace(arr.size*2).clump(2);

block { |break|
	5000.do{ |i|
		var order = arr.order{|a, b| 
			// test 
			try {a.minItem} { |err|
				postf("oops broke on iter %, a.minItem\n\ta: %\n\tb: %\n\ta should be: %\n\tarr: %\n\n", 
					i, a, b, arr.select(_.includes(a))[0], arr
				);
				err.errorString.postln;
				break.();
			};
			try {b.minItem} { |err|
				postf("oops broke on iter %, b.minItem\n\ta: %\n\tb: %\n\tb should be: %\n\tarr: %\n\n", 
					i, a, b, arr.select(_.includes(b))[0], arr
				);
				err.errorString.postln;
				break.();
			};
			
			a.minItem >= b.minItem and: { a.maxItem >= b.maxItem };
		};
	};
	"Made it! Lucky you.";
};
)
```

Expected Behavior
-----------------

The args `a` and `b` of the function supplied to `order` should each be arrays of size 2, in the case of the above example.

Current Behavior
----------------

_Sometimes_ the `b` arg  only contains one element of the the array, not the whole array.

Observations: 
- It seems to always break with the `b` argument, `a` never errors out.
- The problem isn't specific to this shape of array (`[14, 2]`), but seems to break if the arrays sizes are above some functioning minimum. e.g. Trying less than 14 initial elements in **case 1** works
- Given that there's a lot of `flop`ing going on in `SequenceableCollection:-order`, this could be related to #3454.
- **case 2** shows that if you run the same process on a single array multiple times, it works (assuming safe initial conditions)

**Comment by brianlheim** [comment]
Without any additional supporting information to the contrary, I'm going to consider this part of #3454 and migrate your comment there. Thanks for the report!
