### ISSUE TITLE
autocompletion for brackets

### ISSUE THREAD

**Issue by timblechmann** [supercollider/supercollider#419]
creating bug separate from #410. we should try to auto-complete on `()`, `[]` and `{}`. `{}` is the least ambiguous syntax.

regarding `[]` james harkins wrote:

> For [], you would also have to look at the token preceding the bracket pair:
> `x[something]` is not guaranteed to be an array
> `List [...]`, `FloatArray [...]`, `Set []` and `Dictionary []` etc should not present the same method lists.

regarding `()`

> x.value(arg: value) -- ":" pairs found inside and an identifier precedes the opening paren. The () could only be an argument list. Similar: value(x, arg: value). As far as I know, there is no case where identifier(key: value) denotes an event. Function-call syntax for a method call on an event would require double parentheses: method((key: value)), but "method" doesn't precede the event's delimiter.
> 
> (key: value) -- ":" pairs found inside, no preceding identifier. () is an event.
> 
> aPattern <> (key: value) -- "<>" is an operator (method name consisting entirely of punctuation). There is a monkey wrench here: adverbs. I don't think adverbs are implemented in a meaningful way for operations that could take an event as the second operand, but this is legal syntax: aPattern <>.adverb (key: value), and the presence of "adverb" before the event doesn't mean that the event is not an event. So it seems, if there is an identifier before the opening paren, you also have to check what the identifier belongs to.
> 
> x + (y \* 2) -- no ":" pairs, couldn't be an event.

will need some more thoughs, not sure if it can even be done sufficiently accurate

**Comment by brianlheim** [comment]
Pinging. Maybe I'm misunderstanding but isn't this already implemented in some form?

**Comment by gusano** [comment]
@brianlheim Yes, I implemented that in 2013 :) Closing..

**Comment by brianlheim** [comment]
@gusano Awesome, thanks!
