### ISSUE TITLE
verify app fails

### ISSUE THREAD

**Issue by MarinosK** [supercollider/supercollider#4196]
I have an issue similar to #4099, although my problem is not just libogg but a whole bunch of other libs. Build fails on the very last step with a verifying app error. I am trying to compile the latest branch on Mac Os X 10.14.1 - all dependencies are installed with macports (qt is 5.11). Note that despite the failed build, SC seems to work fine (from within emacs). 

`cmake -DCMAKE_PREFIX_PATH=/opt/local/libexec/qt5 -DREADLINE_LIBRARY=/opt/local/lib/libreadline.dylib NATIVE:BOOL=ON SC_EL:BOOL=ON -DCMAKE_OSX_ARCHITECTURES='x86_64'  .. `

`cmake --build . --target install`

results in this: 

> -- Verifying app
-- ===========================================================================
-- Analyzing app='/Users/marinoskoutsomichalis/sources/supercollider/build/Install/SuperCollider/SuperCollider.app'
-- bundle='/Users/marinoskoutsomichalis/sources/supercollider/build/Install/SuperCollider/SuperCollider.app'
-- executable='/Users/marinoskoutsomichalis/sources/supercollider/build/Install/SuperCollider/SuperCollider.app/Contents/MacOS/SuperCollider'
-- valid='1'
-- executable file 1: /Users/marinoskoutsomichalis/sources/supercollider/build/Install/SuperCollider/SuperCollider.app/Contents/MacOS/SuperCollider
-- executable file 2: /Users/marinoskoutsomichalis/sources/supercollider/build/Install/SuperCollider/SuperCollider.app/Contents/MacOS/sclang
-- executable file 3: /Users/marinoskoutsomichalis/sources/supercollider/build/Install/SuperCollider/SuperCollider.app/Contents/Resources/scsynth
-- executable file 4: /Users/marinoskoutsomichalis/sources/supercollider/build/Install/SuperCollider/SuperCollider.app/Contents/Frameworks/QtWebEngineCore.framework/Versions/5/Helpers/QtWebEngineProcess.app/Contents/MacOS/QtWebEngineProcess
-- verified='0'
-- info='external prerequisites found:
f='/Users/marinoskoutsomichalis/sources/supercollider/build/Install/SuperCollider/SuperCollider.app/Contents/Frameworks/QtWebEngineCore.framework/Versions/5/Helpers/QtWebEngineProcess.app/Contents/MacOS/QtWebEngineProcess'
external_prereqs='/opt/local/lib/libbz2.1.0.dylib;/opt/local/lib/libcrypto.1.0.0.dylib;/opt/local/lib/libfreetype.6.dylib;/opt/local/lib/libglib-2.0.0.dylib;/opt/local/lib/libgraphite2.3.dylib;/opt/local/lib/libgthread-2.0.0.dylib;/opt/local/lib/libharfbuzz.0.dylib;/opt/local/lib/libiconv.2.dylib;/opt/local/lib/libicudata.58.dylib;/opt/local/lib/libicui18n.58.dylib;/opt/local/lib/libicuuc.58.dylib;/opt/local/lib/libintl.8.dylib;/opt/local/lib/libpcre.1.dylib;/opt/local/lib/libpcre2-16.0.dylib;/opt/local/lib/libpng16.16.dylib;/opt/local/lib/libssl.1.0.0.dylib;/opt/local/lib/libz.1.dylib;/opt/local/libexec/qt5/lib/QtCore.framework/Versions/5/QtCore;/opt/local/libexec/qt5/lib/QtGui.framework/Versions/5/QtGui;/opt/local/libexec/qt5/lib/QtNetwork.framework/Versions/5/QtNetwork;/opt/local/libexec/qt5/lib/QtPositioning.framework/Versions/5/QtPositioning;/opt/local/libexec/qt5/lib/QtQml.framework/Versions/5/QtQml;/opt/local/libexec/qt5/lib/QtQuick.framework/Versions/5/QtQuick;/opt/local/libexec/qt5/lib/QtWebChannel.framework/Versions/5/QtWebChannel;/opt/local/libexec/qt5/lib/QtWebEngineCore.framework/Versions/5/QtWebEngineCore'
'
-- 
CMake Error at /opt/local/share/cmake-3.13/Modules/BundleUtilities.cmake:1134 (message):
  error: verify_app failed
Call Stack (most recent call first):
  editors/sc-ide/cmake_install.cmake:70 (verify_app)
  editors/cmake_install.cmake:37 (include)
  cmake_install.cmake:55 (include)

**Comment by brianlheim** [comment]
Migrating to #4099.
