### ISSUE TITLE
Plugin Build issue on Raspberry Pi 3B+ Raspian Lite  

### ISSUE THREAD

**Issue by carstenheisterkamp** [supercollider/supercollider#4199]
I am trying to compile SC natively on Raspberry Pi Raspbian stretch Lite and get the following error when trying to compile the plugins.

Environment
-----------
SuperCollider  3.10.0
Raspian Stretch Lite 4.14.79-v7+

Steps to reproduce (for bugs)
-----------------------------
Follow the steps of "Compiling SC natively on Raspberry Pi Raspbian Lite" according to the
[documentation](https://supercollider.github.io/development/building-raspberrypi)
until sc3-plugins step 5
make -j 4

Error message (for bugs)
------------------------
make: *** No targets specified and no makefile found.  Stop.

Expected Behavior
-----------------
Make compliles the plugins

Current Behavior
----------------
stops with above error

**Comment by brianlheim** [comment]
Hi @carstenheistercamp. Please report all the commands you used along with the output of each. if there is no makefile either you are in the wrong directory or an earlier command failed.
