### ISSUE TITLE
When using Sonic Pi on a Mac mini 2018 Mojave scsynth fails to launch with error messages

### ISSUE THREAD

**Issue by Swissmorgy** [supercollider/supercollider#4216]
Hello insiders
I am trying to install Sonic Pi on a new set of Mac minis at a school. However, Sonic Pi cannot start properly. While trying to solve the problem, other users told me it is probably due to Supercollider scxynth, which cannot handle that the 2018 Mac mini has no hardware support for an input microphone.
[I posted about this here on Github](https://github.com/samaaron/sonic-pi/issues/1999)
[And I also posted about it here on SonicPi](https://in-thread.sonic-pi.net/t/cant-open-sonic-pi-3-1-0-error/1527/13)

So here's what is suspected to be a Supercollider issue. Thanks for help or development:

# Starting SuperCollider 2018-12-18 08:38:10

Found 0 LADSPA plugins

Number of Devices: 1

0 : "Mac mini Lautsprecher"

get kAudioDevicePropertyStreamFormat error on input ?ohw

could not initialize audio.

The same error ocrus when trying to launch scsynth directly with
Copy Code

./scsynth -u 4556 -i 0 -o 16

Environment
-----------

* Your SuperCollider version: The one inside Sonic Pi 3.1.0 (Sorry, don't know more...)
* Your operating system and version: OSX Mojave

**Comment by dvzrv** [comment]
I think this is not a problem with scsynth, but with how sonic-pi is using scsynth. From the original bug report of yours:

```
Boot - /Applications/Sonic Pi.app/app/server/native/scsynth -u 4556 -a 1024 -m 131072 -D 0 -R 0 -l 1 -i 16 -o 16 -U /Applications/Sonic Pi.app/app/server/native/supercollider/plugins/ -b 4096 -B 127.0.0.1
```

If indeed your hardware doesn't have any inputs, it's plain wrong to start scsynth using `-i 16` (16 inputs).
