### ISSUE TITLE
sclang <-> python tcp communication

### ISSUE THREAD

**Issue by fschlatt** [supercollider/supercollider#4217]
This issue is more of a question/feature request than an actual bug.

For context, we are trying to develop a wrapper for sclang in python, to integrate it into jupyter notebooks, essentially allowing data analysis in python with sound synthesis in SC. A direct connection to scsynth is possible, but would require lots of effort to emulate all the functionality sclang provides. Currently, we see three possible options to communicate between sclang and python:

* Pipe connection via stdin and stdout (would require ineffecient string parsing to obtain data)
* OSC messages using UDP (has data limit and may drop packets)
* OSC messages using TCP (only uni directional connection possible, explained below)

Environment
-----------

* SuperCollider version: 3.9.3
* Operating system and version: Windows 10 Pro

Code Example
-----------------------------
When creating a TCP server on python and connecting to it from sclang, sclang uses a random port from which it is unable to listen for incoming messages. Also, there seems to be no possibility to access that port to open it or listen on that port manually.

Python:
```python
import socket
from pythonosc import osc_message, osc_message_builder 

if __name__ == "__main__":
    sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)

    sock.bind(('127.0.0.1', 12345))

    print('Listening for TCP Connection...')

    sock.listen(0)

    conn, addr = sock.accept()

    print('Connection established at %s, %s' % (addr))
    
    return_message = conn.recv(1024)
    return_message = osc_message.OscMessage(return_message)
    print(return_message.address)
    print(return_message.params)

    message = osc_message_builder.OscMessageBuilder("/cmd")

    message.add_arg("lala")

    message = message.build()

    conn.send(message.dgram)

    print('Sent message')

    conn.close()
    sock.close()

```
Supercollider:
```supercollider
OSCFunc.trace(true);

n = NetAddr.new("127.0.0.1", 12345);

n.connect();

n.sendStatusMsg();
```

Python output:
```
Listening for TCP Connection...
Connection established at 127.0.0.1, 52885
/status
[]
Sent message
```

In this example, the port 52885 was used by sclang, but any other random port could have been used. Sending a message over the python connection does not yield any response though and it seems the message is not received by sclang, even though sending the message is successful.  Sending messages over UDP to the `NetAddr.langport` on the other hand works perfectly fine:

```python

import socket
from pythonosc import osc_message, osc_message_builder 

if __name__ == "__main__":
    sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)

    message = osc_message_builder.OscMessageBuilder('/cmd')

    message.add_arg("lala")

    message = message.build()

    sock.sendto(message.dgram, ('127.0.0.1', 57120))

    sock.close()

```
gives the following output from `OSCTrace(true)`:

```
OSC Message Received:
	time: 2567.9111203
	address: a NetAddr(127.0.0.1, 61862)
	recvPort: 57120
	msg: [ /cmd, lala ]
```
Using sclang as the TCP server instead of the client is also not possible, as any TCP connections from python (even to `NetAddr.langport`) are declined. Therefore, any help or suggestions of how a connection over TCP to sclang could be established would be greatly appreciated.

**Comment by dyfer** [comment]
AFAIK sclang doesn't have TCP server capabilities. 
I had a need for a TCP server when I developed a [web-based gui](https://github.com/dyfer/wsGUI.quark) for SC that's using websockets. For that I ended up using python to handle TCP traffic:

**sclang** <--(local OSC over UDP)--> **python** <--(websockets over TCP - local or on the network)--> **web browser** (JavaScript)

I'm not sure that packet loss is a real consideration if you use UDP locally, I don't think I had problems there. Packet size limitations still apply though.
