### ISSUE TITLE
Line, XLine: Incorrect starting value, early arrival, etc.

### ISSUE THREAD

**Issue by mtmccrea** [supercollider/supercollider#4279]
## Environment

* SuperCollider version: 3.10.1
* Operating system: MacOS

## Steps to reproduce

```supercollider
/* Case 1 */
(
s.waitForBoot({ // ar - BUG: doesn't start at 0, arrives 1 sample early
	{
		Line.ar(0, 7, (5 / s.sampleRate))
	}.loadToFloatArray((6 / s.sampleRate), action: {|arr| arr.do(_.postln)});
})
)
/* Case 2 */
(
s.waitForBoot({ // kr - BUG: same as AR
	{
		Line.kr(0, 7, (5 * s.options.blockSize / s.sampleRate))
	}.loadToFloatArray((6 * s.options.blockSize / s.sampleRate), action: {|arr| arr.do(_.postln)});
})
)
/* Case 3 */
(
// kr variant - BUG: despite non-zero duration, Line "starts" at the end
// Update: this isn't a bug, see conversation below
s.waitForBoot({ 
	{
		Line.kr(0, 7, (5 / s.sampleRate)) // NOTE: dur shorter than control period
	}.loadToFloatArray((6 * s.options.blockSize / s.sampleRate), action: {|arr| arr.do(_.postln)});
})
)
```

## Expected vs. actual behavior
I expect `Line` to start at ... the starting value, and end after the duration has elapsed (the first sample marking time `0`).
Also, I would expect that if the `duration` is non-zero, the output will always begin with the starting value. If the `duration` is less than the sample duration (at either `ar` or `kr`), the end value would occur at the sample immediately following the end of 'duration` (see Case 3).

There are identical bugs in `XLine`.

### The solution: underway
I have a fix for Case 1, and 2 as part of a larger overhaul of UGen initialization, but found Case 3 today and wanted to document it so I remember to come back around to it.

This bug is related to the many initialization sample bugs I've noted in a number of other places, but this particular problem looks to be related to the slope being incremented before writing out the initialization sample, not after.

**Comment by mtmccrea** [comment]
Will be fixed by #6035
A closer look shows that "case 3" above isn't a bug: `duration` rounds to nearest sample period, which is 0 in that case.
```supercollider
/* Case 3 */
// Duration rounds to nearest sample period:
( 
s.waitForBoot({ 
	{
		[
			Line.kr(0, 7, (1.49  * s.options.blockSize / s.sampleRate)), // period rounds down to 0
			Line.kr(0, 7, (1.5 * s.options.blockSize / s.sampleRate))  // period rounds up to 1
		]
	}.loadToFloatArray(
		3 * s.options.blockSize / s.sampleRate, 
		action: { |arr| arr.unlace(2).do(_.postln) });
})
)
// A slight exception is with a duration less than one sample period:
// <= 0.5 rounds down, > 0.5 round up
( 
s.waitForBoot({ 
	{
		[
			Line.kr(0, 7, (0.5  * s.options.blockSize / s.sampleRate)), // period rounds down to 0
			Line.kr(0, 7, (0.51 * s.options.blockSize / s.sampleRate))  // period rounds up to 1
		]
	}.loadToFloatArray(
		3 * s.options.blockSize / s.sampleRate, 
		action: { |arr| arr.unlace(2).do(_.postln) });
})
)
```

**Comment by dyfer** [comment]
> A closer look shows that "case 3" above isn't a bug: `duration` rounds to nearest sample period, which is 0 in that case.

It's a subtlety, it would be great to document this explicitly (not necessarily a request for 6035, but I propose to keep this issue open until this is added to the documentation).

**Comment by mtmccrea** [comment]
Sure, the rounding behavior, while sensible, may not be obvious. It's equally sensible that an endpoint never be reached _before_ the specified duration (equivalent to `ceil`)... or that alternatively that it's _guaranteed_ to be reached by the time duration elapses (i.e. `floor`).

So I agree it's worth documenting.
