### ISSUE TITLE
Running as root

### ISSUE THREAD

**Issue by johhnry** [supercollider/supercollider#4301]
## Environment

* SuperCollider version: 3.10.0
* Operating system: debian Linux 4.19.0-kali1-amd64
* Other details (Qt version, audio driver, etc.): 

## Steps to reproduce

I don't know why but SuperCollider was working last day and when I try to run sclang from the command line as root, it says : 
It means that I can't run sc as root? Does it come from the last update?

## Expected vs. actual behavior

```supercollider
root@johk:~# sclang
compiling class library...
[5702:5702:0210/004412.084934:ERROR:zygote_host_impl_linux.cc(90)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.
terminate called without an active exception
Received signal 6
#0 0x7f8224a02bde <unknown>
#1 0x7f8224a02cf0 <unknown>
#2 0x7f8224a03327 <unknown>
#3 0x7f82290eb6b0 <unknown>
#4 0x7f821fd4c85b gsignal
#5 0x7f821fd37535 abort
#6 0x7f82200ff943 <unknown>
#7 0x7f82201058a6 <unknown>
#8 0x7f82201058e1 std::terminate()
#9 0x5572a55938dd std::thread::~thread()
#10 0x7f821fd4ee3c <unknown>
#11 0x7f821fd4ef6a exit
#12 0x7f8223f8baf8 <unknown>
#13 0x7f8223b4a467 <unknown>
#14 0x7f8223b4f062 <unknown>
#15 0x7f822349e79c <unknown>
#16 0x7f822349fab4 <unknown>
#17 0x7f822341d890 QtWebEngineCore::BrowserContextAdapter::defaultContext()
#18 0x7f82290be195 QWebEngineProfile::defaultProfile()
#19 0x7f82290c3b69 QWebEngineSettings::defaultSettings()
#20 0x5572a56bc8a0 <unknown>
#21 0x5572a567f5a9 <unknown>
#22 0x5572a559cb10 <unknown>
#23 0x5572a563a330 <unknown>
#24 0x5572a563a8c6 <unknown>
#25 0x5572a563a964 <unknown>
#26 0x5572a5582fc6 <unknown>
#27 0x5572a5571cab <unknown>
#28 0x7f821fd3909b __libc_start_main
#29 0x5572a558030a <unknown>
  r8: 0000000000000000  r9: 00007ffe1a734ca0 r10: 0000000000000008 r11: 0000000000000246
 r12: 00007f821fed0718 r13: 00000000000002e6 r14: 00007f821fed5428 r15: 00005572a5f23150
  di: 0000000000000002  si: 00007ffe1a734ca0  bp: 0000000000000001  bx: 0000000000000006
  dx: 0000000000000000  ax: 0000000000000000  cx: 00007f821fd4c85b  sp: 00007ffe1a734ca0
  ip: 00007f821fd4c85b efl: 0000000000000246 cgf: 002b000000000033 erf: 0000000000000000
 trp: 0000000000000000 msk: 0000000000000000 cr2: 0000000000000000
[end of stack trace]
Calling _exit(1). Core file will not be generated.

```

**Comment by snappizz** [comment]
hi, thanks for the report. i believe this error is coming from qt according to [this thread](https://forum.qt.io/topic/94721/running-as-root-without-no-sandbox-is-not-supported), and is likely a side effect of the update to qtwebengine.

could you try `export QTWEBENGINE_DISABLE_SANDBOX=1` and running sclang again?

since you're running sclang as root, you might prefer to compile sclang without Qt entirely. (`-DSC_QT=OFF` at the cmake stage)

**Comment by johhnry** [comment]
Hello,

Thanks for your quick reply.
The `export QTWEBENGINE_DISABLE_SANDBOX=1` is working fine thanks !

Have a great day :+1:

**Comment by dvzrv** [comment]
> Thanks for your quick reply.
> The `export QTWEBENGINE_DISABLE_SANDBOX=1` is working fine thanks !

Sorry for necro-bumping.
Out of curiosity: Why are you running sclang as root?

**Comment by johhnry** [comment]
Hey @dvzrv 
It's just that I am on Kali Linux and I keep the primary account as root.
