### ISSUE TITLE
UnitTest:assertFloatEquals message string is wrongly constructed

### ISSUE THREAD

**Issue by jamshark70** [supercollider/supercollider#4317]
## Environment

* SuperCollider version: bdfb09564
* Operating system: Ubuntu Studio 18.04

## Steps to reproduce

```supercollider
UnitTest.runTest("TestArray:test_arraystats");
```

Prints:

```
PASS: a TestArray: test_arraystats - stdDev should be invariant to reversing
Is:
	 % 
Should equal (within range 0.0001):
	 0.28571526521082
```

Clearly the `%` is supposed to be replaced by a number, but it isn't.

## Expected vs. actual behavior

https://github.com/supercollider/supercollider/commit/3a763cad953d177a1c9ae70910bf3d99a8e147ef#diff-142275b33b93af8f404407aec0fcc46bL152

```
	assertFloatEquals { |a, b, message = "", within = 0.0001, report = true, onFailure|
		var details =
		"Is:\n\t % \nShould equal (within range" + within ++ "):\n\t %".format(a, b);
		this.assert((a - b).abs <= within, message, report, onFailure, details);
	}
```

`format` should be `"format string".format(args)`, but somebody here wrote:

```
"string with % placeholder" ++ something ++ "other string".format(a, b)
```

... whereupon `format` will not apply to the first string.

```
"Is:\n\t % \nShould equal (within range %):\n\t %".format(a, within, b);
```

**Comment by telephon** [comment]
So it should be:

```
("Is:\n\t % \nShould equal (within range %):\n\t %").format(a, within, b);
```

instead.

**Comment by brianlheim** [comment]
wouldn't it have been easier to just submit a PR for this?

**Comment by jamshark70** [comment]
> wouldn't it have been easier to just submit a PR for this?

Maybe, but I spotted this in the middle of working on something unrelated. Dealing with git branching at that time would have been more disruptive to the other thing, and I didn't want this to get lost either. So I had to decide between a quick write-up or double-checking a lot of stuff to be sure to pass review.

**Comment by brianlheim** [comment]
> So I had to decide between a quick write-up or double-checking a lot of stuff to be sure to pass review.

???

this patch is easy to visually review/confirm, and you already wrote it right here in the ticket. next time, use the web UI to submit a PR if you don't want to create a branch locally.
