### ISSUE TITLE
SC 3.10.0 Help Browser/Search not working on Linux (scide and Emacs)

### ISSUE THREAD

**Issue by lucdoebereiner** [supercollider/supercollider#4319]
## Environment

* SuperCollider version: 3.10.0
* Operating system: Debian Linux buster

## Steps to reproduce
In both scide and Emacs, opening the Help causes the following error:
```
JavaScript Message: Uncaught ReferenceError: $ is not defined
JavaScript Message: Uncaught ReferenceError: CodeMirror is not defined
JavaScript Message: Uncaught ReferenceError: $ is not defined
```
Browse and search are not working. Page remains empty.

Looks like jQuery is not being loaded.

**Comment by lucdoebereiner** [comment]
The error does not occur with 3.10.2. installed from the sources. Could it be an issue with the debian package?

**Comment by snappizz** [comment]
hi, thanks for looking into this. iirc nothing changed in this area between 3.10 and 3.10.2, so you're probably right that this is an issue with the package, so SC contributors don't really have control over this.

**Comment by snappizz** [comment]
per discussion at #4392 this is actually an upstream issue with debian or ubuntu packaging. we do not support outdated versions in linux packages. to fix, build SC from source (you should really be on 3.10.2 anyway -- 3.10.0 and 3.10.1 have a serious gradual memory leak in sclang).
