### ISSUE TITLE
Quarks "latest" is latest master, not Default branch.

### ISSUE THREAD

**Issue by telephon** [supercollider/supercollider#4321]
## Steps to reproduce

```supercollider
Quarks.gui;
```
Then install `SuperDirt`. Select `latest`. In terminal, verify what branch is checked out. Something like this: 

```
$ git branch
* (HEAD detached at 613af25)
  master
```

In this case, 613af25 is in *master*, although the Default branch is `develop`.

## Expected vs. actual behavior

"latest" should be the head of `develop` (Default branch)

**Comment by brianlheim** [comment]
I don't think it's worth special casing things this way; to me, it's not so unreasonable that we say the master branch is what will be checked out if no other branch is given. Since the entire purpose of these repos is to be linked into Quarks, we can institute some clear standards here.

**Comment by telephon** [comment]
I simply had assumed that the default branch that is being pushed to is also the default branch that is being pulled from.

**Comment by yaxu** [comment]
Maybe it is worth changing the GUI so that it shows 'master' rather than 'LATEST'?

**Comment by brianlheim** [comment]
on further research I was wrong -- GitHub uses the HEAD ref to indicate the "default" branch. it looks like it would be possible to check it out after cloning: https://stackoverflow.com/questions/28666357/git-how-to-get-default-branch

I still don't know if it is worth being flexible on this though

**Comment by yaxu** [comment]
I originally raised this issue with @telephon, but after some thought I think it's fine for the default checkout to be master.. As I think often you will not want the default for users to be the default development branch..
But still I think it's not clear what 'latest' means.

**Comment by brianlheim** [comment]
> Maybe it is worth changing the GUI so that it shows 'master' rather than 'LATEST'?

sgtm. that is definitely misleading -- it could also mean "latest release". "latest master" is least ambiguous IMO.

i don't have any strong feelings on this. it's easier to document existing practice than make a code change (which, btw, could potentially break guides/workflows that rely on this pulling from master). and this existing practice seems reasonable. but i am not opposed to changing it if people feel it's confusing.

**Comment by yaxu** [comment]
Ok no strong feelings here either, really.
My main concern is making life easier for non supercollider experts installing tidal/superdirt. For them we can simply make sure that a good release is in master.

**Comment by telephon** [comment]
I'm preparing a short pull request with a changed gui.

I do still see a related problem that the _actual branch_ checked out is not mentioned in the GUI at all, and this is confusing.

Still, there are "versions" displayed when you are not on any of those.


The cause of this is that

```supercollider
isDownloaded {
		^File.exists(this.localPath)
	}
```

is not always true, obviously. You may have your own repository, which is not "downloaded". I'm not sure how this was intended.

**Comment by telephon** [comment]
I've managed to change the GUI so it displays the current branch. Would you prefer to have this in a separate PR, @brianlheim?
