### ISSUE TITLE
add() does not work for one-length arrays

### ISSUE THREAD

**Issue by thiagoskapata** [supercollider/supercollider#4322]
## Environment

* SuperCollider version: 3.10.0
* Operating system: GNU/Linux (Debian Buster Testing)

## Steps to reproduce
Type this in sclang command line:
```supercollider
a = []; a.add(1); a.add(2);
```

## Expected vs. actual behavior
Expected: array ```a``` should have two elements after adding two elements just after creating it as an empty array.

Got: after adding the first element, all other messages ```add``` sent to the array do not work. The array remains unchanged.

**Comment by patrickdupuis** [comment]
This is expected behaviour. Please see the note at the top the Array help file for explanation.
