### ISSUE TITLE
[jitlib] ProxyMixer widget actions are not bound to the environment

### ISSUE THREAD

**Issue by jamshark70** [supercollider/supercollider#4335]
## Environment

* SuperCollider version: e44217de
* Operating system: Ubuntu Studio

## Steps to reproduce

In my system for automatically reloading JITLib patches, I've been struggling with an inconsistency in the GUI.

ProxyMixer assumes that the ProxySpace it's displaying is always the current environment -- but it does nothing to guarantee this.

This can break the display, in the `editGui`, of inputs that are mapped to other NodeProxies. It's supposed to look up the source proxy's key in the environment (that is, `currentEnvironment`). But if you happen to be outside the proxy space and you click, say, an "ed" button, then `currentEnvironment` is incorrect, and it can't find the key, and it falls back to `a = NodeProxy.new` for display.

```supercollider
s.boot;
p = ProxySpace.new.push;

~out = { \in.ar(0!2) };
~osc = { SinOsc.ar(440).dup };
~osc <>> ~out;

g = p.gui;

// If you skip this line and set the button as below, it displays `~src` for `in`
// If you run the line and set the button, you get `a = NodeProxy.new`
p.pop;

i = g.arGuis.detectIndex { |gui| gui.nameView.string == "out" };
g.arGuis[i].edBut.valueAction_(1);
```

But... ProxyMixer always knows which ProxySpace is being displayed (its `object`). So there is no reason for any of the views contained in a ProxyMixer to leave the current environment up to chance.

Now, why would the wrong environment be current? It's very easy to get into this state if you're binding an IDE code document to a proxyspace environment. Switch to a different code tab, manipulate the ProxyMixer, and boom... it's broken.

Note that switching to the right environment and clicking "ed" again doesn't update the display, because the GUI slot's value has not changed. You have to go into the environment, `set` the control to something, and then set it back to the thing you wanted. Kind of a long way around.

## Expected vs. actual behavior

- Expected: ProxyMixer should be responsible for ensuring that it's looking for objects in the right environment.

- Actual: ProxyMixer assumes that you have manually pushed the right environment before touching anything in the GUI.

Possible solutions:

- ProxyMixer should set all of its action functions to run within the right environment. I confirmed that `.action_(inEnvir { arg btn, mod; ... })` in `ProxyMixer:setEdButs` prevents the problem. I haven't looked deeply into the structure to see how many buttons would be affected. Definitely the edit button is affected because it changes the `editGui` display, where I see the problem (and, this is the only place where you see the problem in ProxyMixer).

- Probably a bad idea: Use `toFrontAction` / `endFrontAction` to set the current environment. This would be OK in the common case (one ProxyMixer, one window) but... in theory, you can put two or more ProxyMixers into one window, each with a different ProxySpace. *All* views' `toFrontAction`s will be called, so it's pure chance which environment would be activated.

FWIW I am working around this temporarily: https://github.com/jamshark70/JITModular/commit/30366b8395cf4ebc9a44fcc8fdeadb6872c58cd3

**Comment by adcxyz** [comment]
@jamshark70 thanks for the report and clear discussion! 
While Ndefs know their own key, NodeProxies have to ask their proxyspace (if there is one), 
but they don't know which proxyspace they are in ... 

How about this: Like ProxyMixer, NdefGui gets an  instvar proxyspace, 
which gets set e.g. when ProxyMixer editButton sets the NdefGui's object. 
NdefGui asks its object with``` object.key(proxyspace) ```, and 
then there is no need to manipulate currentEnvironment temporarily 
(which may be risky, e.g. if code fails before flipping back). 

does that make sense?

**Comment by adcxyz** [comment]
hm, not working, because it actually happens in the nodeMap, 
which again for decoupling reasons is unaware of the proxyspace the nodeproxy is in.

**Comment by jamshark70** [comment]
> which may be risky, e.g. if code fails before flipping back

This is what `protect` is for ;-) as I recall, `environment.use` was the original reason why JMc added error handling in the first place.

**Comment by adcxyz** [comment]
ok, more testing done: when you switch a proxy mapping later, as in :
```p.pop;
p[\osc2] = { Pulse.ar(440).dup };
p[\osc2] <>> p[\out];
```
this does not get reflected properly. 
So, the least invasive thing would be to change a line in ProxyMixer:checkUpdate:
	// editGui.checkUpdate; 
	this.proxyspace.use { editGui.checkUpdate };

Can you try if that works for all your  tests? 

best adc

**Comment by telephon** [comment]
Maybe it would be the easiest if the `NdefGui` kept the key as an instance variable.  (is it correct that there is an `NdefGui` for each proxy in the `ProxyMixer`?).

**Comment by jamshark70** [comment]
Maybe the NodeProxy should store its key (set at creation time). The key isn't a property of the GUI -- it's a property of the proxy, isn't it?

**Comment by telephon** [comment]
A `NodeProxy` may be part of any environment, or even several environments at once, may be moved while playing etc. So it should have no key. 

Also when you print the compile string, you may want different keys for the same proxy, depending on where you access it from. This is different for `Ndef` of course.

So in a way, the current behaviour is correct, the problem is more that the `ProxyMixer` is not bound to the environment it refers to.

**Comment by adcxyz** [comment]
dear @jamshark70 @telephon, 
please take a look whether 4339 fixes all concerns: 
AFAICT everything on the ProxyMixer now always shows code/names relative to its proxyspace, 
irrespective of the currentEnvironment. 

Of course, users may assume that the code shown on the mixer will "just work", 
but that depends on what the currentEnvironment is, so this is a source of user confusion;
when using multiple proxyspaces, users would always have to do 
```
<mixer>.proxyspace.use { 
... pasted/posted code here
}
```

**Comment by telephon** [comment]
This looks good, thanks a lot! The slightly complicated cases could perhaps be simplified in the future.
