### ISSUE TITLE
ASync command server hang with b_query completion message

### ISSUE THREAD

**Issue by weefuzzy** [supercollider/supercollider#4338]
## Environment

* SuperCollider version: 10.2, 10.0, 3.9.3
* Operating system: Mac OS 10.12.6
* Other details (Qt version, audio driver, etc.): Built-in audio; no quarks or extensions 

## Steps to reproduce

```supercollider
a = Buffer.read(s, Platform.resourceDir +/+ "sounds/a11wlk01.wav");
s.sendMsg(\cmd, \pluginCmdDemo, 0, 0, \mno, [\b_query,a.bufnum]);
a.play; 
```

## Expected vs. actual behavior

Expected: `a` plays, Actual: `a` doesn't play, server becomes unresponsive 

I can confirm that the \b_query is executed, and the reply sent back to the language. It just seems that something bad happens as a result. 

## Additional Context 

Not as pervserse as it seems. I'm developing some buffer processing things using ASyncCmd, and hit this problem trying to arrange for an action to happen after all the `Buffer`s involved have had their info updated. The idea was to do something similar to the `Buffer` class by using `\b_query` as a completion message, and then running the user action when `b_info` is received. Because I'm processing multiple buffers, I can't use `\b_gen` for this. 

I was having this sort of problem with my own code, so have tried with `\pluginCmdDemo` to see if the problem was solely down to me or not (it's the only built-in thing I know of using `ASyncCmd`). 

## Workaround
Not using `b_query` as a completion message for custom Async commands. I should be able to use something else, and then use Buffer.updateInfo from the language to get the desired effect.

**Comment by brianlheim** [comment]
Hey @weefuzzy -- what exactly is `s.sendMsg(\cmd, \pluginCmdDemo, 0, 0, \mno, [\b_query,a.bufnum]);` supposed to do? i've never seen this before and a quick google search doesn't show any results for "pluginCmdDemo".

if you want to send a `/b_query` command to the server, why not use `s.sendMsg("/b_query", a.bufnum);`?

btw, the commands are OSC addresses -- they start with a forward slash. `\b_query` is a symbol literal with contents "b_query".

**Comment by weefuzzy** [comment]
Hi @brianlheim, 
Apologies, I had thought the additional context above explained why I was testing with such a strange thing, but I wasn't al\ that clear.  Thanks for responding. 

`s.sendMesg(\cmd, \pluginCmdDemo...` runs a built-in example of using the server's facilitilities for cus asycnhronous commands. See `UIUGens.mm` in the core code, particularly the `cmdDemoFunc`. As far as I can tell, it's the only code in the core distribution that uses these facilities, which I am also using to develop a set of buffer processsing plugins. 

The command in the list at the end is run by the server once the asynchronous task is done (see `SC_SequencedCommand.cpp`, `AsyncPlugInCmd`) , in the same way that the built-in asynchronous commands, like `b_alloc` etc, allow. You'll see a similar pattern in `Buffer.sc`

`\pluginCmdDemo`'s virtue here is being (a) built-in and (b) not my code, so I could test whether the same bad things happen with /b_query as a completition message. If folk are able to reproduce then this helps rule out my configuration as the culprit, and narrows it down to either something in `AsyncPlugInCmd`, or a common badness between the demo in `UIUGens.mm` and my code.

* `What is...supossed to do`?
Nothing especially useful, except help me narrow down the problem (server hangs under these conditions), and reproduce it in a minimal way, that doesn't rely on my code. If anyone else can reproduce, then 

* `Why not use...`?
Because the point is to test the *combination* of something that uses the server's `AsyncPlugInCmd` stuff and having /b_query as a completion message. FWIW, the completion message itself works: a reply comes back to the language. It's just that something horrible seems to happen server side that leaves it inoperable. 

* `\b_query` is a symbol literal with contents "b_query".
Ooops [blush]. The crash still happens with "/b_query"

**Comment by jamshark70** [comment]
> btw, the commands are OSC addresses -- they start with a forward slash. \b_query is a symbol literal with contents "b_query".

I forget whether it's sclang or scsynth that does it, but if the OSC path omits the leading slash, it's added for you. `s.sendMsg(\something, ...)` is a very common idiom in sclang (though technically incorrect).

**Comment by brianlheim** [comment]
Thanks for the explanation @weefuzzy, that helps a lot.

I would still like to know, is this something you found documentation for somewhere? i can find no indication for how this is meant to be used, which means you're more knowledgeable than i am about how to debug it at this point. :) there is a fair amount of code in this codebase that is legacy/outdated, and I would rather remove it than support it if it doesn't do anything particularly interesting. it seems like this is mostly meant as a feature demo, which serves a purpose in itself.

**Comment by brianlheim** [comment]
> I forget whether it's sclang or scsynth that does it, but if the OSC path omits the leading slash, it's added for you. `s.sendMsg(\something, ...)` is a very common idiom in sclang (though technically incorrect).

sclang does it (https://github.com/supercollider/supercollider/blob/develop/lang/LangPrimSource/OSCData.cpp#L214-L216). and thanks, i forgot about that!

**Comment by weefuzzy** [comment]
> I would still like to know, is this something you found documentation for somewhere?

Documentation might be stretching it :-D Apart from that lurking example:

* There's a list post from James McCartney, after he added the feature in 2003: https://www.listarc.bham.ac.uk/lists/sc-dev-2003/msg03275.html
* And, IIRC, there's a mention in Ross Bencina's SC book chapter (don't have it to hand right now). 

So, the `PluginCmdDemo` itself I'm just using here to minimally reproduce the bug. The code I'm actually working on uses the `DoAsynchronousCommand` stuff to things like `b_gen` but that deal properly with multiple buffers (this is for some offline signal decomposition processes). I have a mess of C++ templates  that it didn't seem productive or kind to inflict on innocent people!

I'd be kind of sad if `DoAsynchronousCommand` disappeared from the server API, as I haven't found any other way to do what we need to do. (Open to any suggestions for a more painless life though). 

As for debugging, I've not tried debugging scsynth before, but I do know which bits of code to look at. If it's as simple as just doing a debug build of scsynth without having to try and build the whole app, I should be able to try and figure it out.

**Comment by weefuzzy** [comment]
Apologies for the long lag on this. 

The cause *seems* to be that `AsyncPlugInCmd` tries to free its completion message data twice, once in its own destructor, and also in the desctructor of its base class, `SC_SequencedCommand`. Calling `World_Free` twice on the same patch of data appears to do bad things: once its happened the FIFO queue seems to get stuck trying to allocate memory for subsequent messages. 

(One could be forgiven for thinking that `World_Free` oughtn't be called twice, because `SC_SequencedCommand` checks for `nullptr` before calling it; however, the pointer isn't null after `World_Free` is called the first time.) 

Commenting out line 1629 of SC_SequencedCommand.cpp (the call to `World_Free` in AsyncPlugInCmd's desctructor) seems to cure the server hangs. 

I can happily submit a PR for this, but would just like to check with someone who understands the memory model better than I that this is sensible.

**Comment by Spacechild1** [comment]
> The cause _seems_ to be that `AsyncPlugInCmd` tries to free its completion message data twice, once in its own destructor, and also in the desctructor of its base class, `SC_SequencedCommand`.

I just had a look at the code and I think you're right. Please make a PR! 

BTW, I'm successfully using `DoAsynchronousCommand` in my VSTPlugin UGen for searching/probing VST plugins on the Server (so please don't remove it :-)), but I don't use completion messages, so that's why I didn't experience a crash.

**Comment by weefuzzy** [comment]
@Spacechild1 Heartened to know someone else is using it! I'll do a PR as soon as I can
