### ISSUE TITLE
Very frequent IDE freeze

### ISSUE THREAD

**Issue by Bubobubobubobubo** [supercollider/supercollider#4360]
SuperCollider version: 3.10.2
Operating system: Mac Os Mojave 10.14
Other details (Qt version, audio driver, etc.): vanilla install. Default audio drivers. No special modifications to startup.scd, or any other file that could explain why SuperCollider does that.

## Steps to reproduce

I open SuperCollider (at this point my computer freeze for 2-3 seconds before I can have the control again). I boot the server (same freeze for 2-3 seconds). I insert a DDWSnippet (2-3 seconds freeze). The freeze are happening very often, especially when booting or when dealing with the various windows of the iDE. 

## Expected vs. actual behavior

SuperCollider must be smooth and I should not experience freezes. I've checked videos to see what is the normal expected behaviour. 

## More about the error

I've created a topic on the SuperCollider Forum about this issue:  https://scsynth.org/t/ide-is-freezing-my-computer-and-other-newcomer-problems/876/6.

**Comment by LFSaw** [comment]
possibly related to https://github.com/supercollider/supercollider/issues/4362

**Comment by gusano** [comment]
@Bubobubobubobubo Did you try if the same happens with all Quarks disabled?

**Comment by sebshader** [comment]
When opening SC 10.10 from the App Icon, it freezes my entire computer for a few minutes and I have to force quit. If I let it open all the way it takes about 10 minutes of being basically frozen.

However, if I open from the Terminal (/Applications/Contents/Resources/MacOS/Supercollider) everything works fine

**Comment by joshpar** [comment]
Which version OS X?

**Comment by sebshader** [comment]
sorry, 10.14 Mojave

**Comment by joshpar** [comment]
Please try this version and let me know if it resolves the problem. This is a test build that is developer signed:

https://www.realizedsound.net/josh/SuperCollider.zip <https://www.realizedsound.net/josh/SuperCollider.zip>

Josh

**Comment by sebshader** [comment]
well, at first I got "Supercollider.app couldn't be opened. You should move it to the Trash". 
I ran sudo xattr -rd com.apple.quarantine as described https://apple.stackexchange.com/questions/262355/xxx-cant-be-opened-you-should-move-it-to-trash-for-flash-projector-applicat
and clicking the Icon worked after that

**Comment by Bubobubobubobubo** [comment]
It looks that the developer build is fixing the issue for me!

Many thanks!
