### ISSUE TITLE
References to build directory (vendored boost_sync) in binaries (sclang, supernova) and libraries (libscsynth.so)

### ISSUE THREAD

**Issue by dvzrv** [supercollider/supercollider#4361]
## Environment

* SuperCollider version: 3.10.2 (also current develop)
* Operating system: Arch Linux
* Other details (Qt version, audio driver, etc.): boost 1.69.0

## Steps to reproduce

When building SuperCollider (3.10.2 or develop) using system boost, there are three remaining references to the vendored boost (i.e. the initial build directory).
Further (minimal) cleanup is required to remove remaining includes from the codebase, when they're not required (i.e. building with vendored or system boost).

```
/usr/bin/sclang
boost::sync::semaphore constructor failed in sem_init -> /build/supercollider/src/supercollider-3.10.2/external_libraries/boost_sync/include/boost/sync/detail/semaphore/semaphore_posix.hpp

/usr/bin/supernova
semaphore post failed: semaphore counter overflow -> /build/supercollider/src/supercollider-3.10.2/external_libraries/boost_sync/include/boost/sync/detail/semaphore/semaphore_posix.hpp

/usr/lib/libscsynth.so
semaphore post failed: semaphore counter overflow -> /build/supercollider/src/supercollider-3.10.2/external_libraries/boost_sync/include/boost/sync/detail/semaphore/semaphore_posix.hpp
```

## Expected vs. actual behavior

After a build in a clean chroot, there should be no reference to the build directory anymore.

Offenders seem to be:
https://github.com/supercollider/supercollider/blob/develop/lang/CMakeLists.txt#L11
https://github.com/supercollider/supercollider/blob/develop/server/scsynth/CMakeLists.txt#L94
https://github.com/supercollider/supercollider/blob/develop/server/supernova/CMakeLists.txt#L83

I don't think this breaks anything, but it is a clear sign for further devendoring ([as soon as upstream releases it](https://github.com/boostorg/sync/issues/8)).

**Comment by brianlheim** [comment]
i think this can be closed, since boost_sync is actually not part of the standard boost distribution and it seems likely we will move to C++20 and be able to remove it entirely before that changes.
