### ISSUE TITLE
macOS Mojave: Permissions issues running code or booting server

### ISSUE THREAD

**Issue by LFSaw** [supercollider/supercollider#4362]
## Environment

* SuperCollider version: 3.10.2
* Operating system: OSX 10.14 Mojave
* Other details (Qt version, audio driver, etc.):

external audio interface

## Steps to reproduce

```supercollider
s.boot;
```

then open Server Meter

## Expected vs. actual behavior

There should be input level showing, microphone (i.e. all input) is blocked. 

There are several things to be done, a guideline is here:

https://developer.apple.com/documentation/avfoundation/cameras_and_media_capture/requesting_authorization_for_media_capture_on_macos

specifically, `Info.plist` needs to have a section

```xml
    <key>NSMicrophoneUsageDescription</key>
    <string>${PRODUCT_NAME} needs Microphone input to operate properly.</string>
```

**Comment by jparmentervf** [comment]
I've had this happen a number of times as well, and I have had to manually deny access to SuperCollider in system settings, then approve it again. However, when this happens, OS X says it already has approved access! So, this may actually be an OS X bug.

**Comment by LFSaw** [comment]
Further, I get immediatly

```txt
-> localhost
Booting server 'localhost' on address 127.0.0.1:57110.
Found 98 LADSPA plugins
Faust: supercollider.cpp: sc_api_version = 3
Faust: FaustJPverbRaw numControls=11
Faust: supercollider.cpp: sc_api_version = 3
Faust: FaustGreyholeRaw numControls=7
Number of Devices: 7
   0 : "Built-in Microph"
   1 : "Built-in Output"
   2 : "USB Camera-B4.09.24.1"
   3 : "Fireface UFX (23610321)"
   4 : "Z1 + cameras"
   5 : "Babyface + cameras"
   6 : "camera + builtin"

"Fireface UFX (23610321)" Input Device
   Streams: 5
      0  channels 8
      1  channels 4
      2  channels 2
      3  channels 8
      4  channels 8

"Fireface UFX (23610321)" Output Device
   Streams: 5
      0  channels 8
      1  channels 4
      2  channels 2
      3  channels 8
      4  channels 8

SC_AudioDriver: sample rate = 48000.000000, driver's block size = 512
SuperCollider 3 server ready.
```

followed by a freeze of sclang (not the IDE, for about 3-5 seconds), followed by

```txt
Requested notification messages from server 'localhost'
Requested notification messages from server 'localhost'
Requested notification messages from server 'localhost'
Requested notification messages from server 'localhost'
Requested notification messages from server 'localhost'
Requested notification messages from server 'localhost'
Requested notification messages from server 'localhost'
/notify : already registered
/notify : already registered
/notify : already registered
/notify : already registered
/notify : already registered
/notify : already registered
localhost: server process's maxLogins (1) matches with my options.
localhost: keeping clientID (0) as confirmed by server process.
localhost: server process's maxLogins (1) matches with my options.
localhost: keeping clientID (0) as confirmed by server process.
localhost: server process's maxLogins (1) matches with my options.
localhost: keeping clientID (0) as confirmed by server process.
localhost: server process's maxLogins (1) matches with my options.
localhost: keeping clientID (0) as confirmed by server process.
localhost: server process's maxLogins (1) matches with my options.
localhost: keeping clientID (0) as confirmed by server process.
localhost: server process's maxLogins (1) matches with my options.
localhost: keeping clientID (0) as confirmed by server process.
localhost: server process's maxLogins (1) matches with my options.
localhost: keeping clientID (0) as confirmed by server process.
Shared memory server interface initialized
```

possibly caused by a piling up of OSC status requests that are not answered in time.

**Comment by LFSaw** [comment]
jparmentervf:

>  So, this may actually be an OS X bug.

I am quite sure this is because of a lack of handling the permissions correctly (I added more detail to the initial description of the bug above)

**Comment by jparmentervf** [comment]
In this case, it is an OS X enhancement that we need to add.

**Comment by LFSaw** [comment]
I added the scsynth label since needs to be `AVAuthorizationStatus` needs to be tested there... (I guess)

**Comment by LFSaw** [comment]
It seems to me that the freeze is not happening with built-in Audio, I get it, however, with my RME interfaces and with Aggregate Devices:

set up an aggregate device in `Audio MIDI Setup`:

<img width="482" alt="Screenshot 2019-03-16 at 15 36 10" src="https://user-images.githubusercontent.com/75468/54476784-8977ae80-4801-11e9-8978-cf8d72c07605.png">
 

```
s.options.device_("builtinIO");
s.boot; // takes around 30seconds to get up and running
```

**Comment by mtmccrea** [comment]
> I get it, however, with my RME interfaces and with Aggregate Devices

I have found that when installing fresh RME drivers, you need to grant the **driver** access (System Preferences > Security & Privacy), after your first reboot (which is required after installation).

If you don't do this within 30 minutes, you'll need to install the driver again and make sure to grant permissions within that time.

**Comment by joshpar** [comment]
@LFSaw  - can you try this build? I think I have signed it correctly.

https://www.realizedsound.net/josh/SuperCollider.zip

**Comment by LFSaw** [comment]
thanks josh!

after initial testing, I am happy to tell that this version seems to fix this issue as well as #4364 (plus other weird behaviour of not always following trackpad clicks in the Help browser) . It also correctly asks for Microphone access. You think checking `AVAuthorizationStatus` is still needed?

**Comment by joshpar** [comment]
Yes - I think this is still worth exploring. I haven’t had a chance to follow up on it yet though. But at least this gets you through your performance (hopefully).

**Comment by LFSaw** [comment]
thanks so much for this! it means that i do not have to carry around two laptops (linux, osx) plus not having to install all kind of additional software on the linux machine... but i start thinking of a dedicated performance machine now... :)

**Comment by snappizz** [comment]
an update to everyone affected by this: @joshpar discovered some roadblocks to getting codesigning running in CI. however, he can still sign releases manually, which we'll do for 3.10.3.

**Comment by brianlheim** [comment]
major praise for @joshpar for digging in on it!

**Comment by snappizz** [comment]
@sonoro1234 please don't unpin issues, thanks!

**Comment by sonoro1234** [comment]
Sorry, i was not aware i had modified this issue.

**Comment by joshpar** [comment]
@LFSaw or others - can we close this as being resolved with releases being signed for now?

**Comment by brianlheim** [comment]
yes, this has been resolved with signing/notarizing, thanks @joshpar!
