### ISSUE TITLE
SCIDE : scdoc.js $ is not defined

### ISSUE THREAD

**Issue by johhnry** [supercollider/supercollider#4367]
## Environment

* SuperCollider version: 3.10.0.
* Operating system: Kali Linux 4.19.0-kali3-amd64 #1 SMP Debian
* Other details (Qt version, audio driver, etc.):
Qt version 4.8.7

## Steps to reproduce
When run the scide from the command line, I get : 

## Expected vs. actual behavior

```supercollider
*** ERROR in JavaScript: "Uncaught ReferenceError: $ is not defined"
* line: 215
* source ID: "file:///root/.local/share/SuperCollider/Help/scdoc.js"
*** ERROR in JavaScript: "Uncaught ReferenceError: CodeMirror is not defined"
* line: 3
* source ID: "file:///root/.local/share/SuperCollider/Help/editor.js"
*** ERROR in JavaScript: "Uncaught ReferenceError: $ is not defined"
* line: 157
* source ID: "file:///root/.local/share/SuperCollider/Help/scdoc.js"
*** ERROR in JavaScript: "Uncaught ReferenceError: $ is not defined"
* line: 215
* source ID: "file:///root/.local/share/SuperCollider/Help/scdoc.js"
*** ERROR in JavaScript: "Uncaught ReferenceError: $ is not defined"
* line: 157
* source ID: "file:///root/.local/share/SuperCollider/Help/scdoc.js"
```

And the help browser doesn't work. (does $ refers to jquery ?)

Thanks in advance

**Comment by jamshark70** [comment]
> Qt version 4.8.7

The documented Qt requirement is ">= 5.7 with QtWebEngine and QtWebSockets" -- https://github.com/supercollider/supercollider/blob/develop/README_LINUX.md

I can't say for sure that this is the cause of the specific problem, but you mentioned that the help browser isn't working. The help browser definitely needs Qt >= 5.7. I'd address the environmental requirement first and then see if there's still an issue.

**Comment by johhnry** [comment]
@jamshark70 Thanks for your answer

You are right, this might be the problem.
I tried uninstalling the qt4-qmake to install a newer version but I don't understand something, when I run : 

`sudo apt-get install qt5-default qt5-qmake qttools5-dev qttools5-dev-tools qtdeclarative5-dev qtwebengine5-dev libqt5svg5-dev libqt5websockets5-dev`

It says that I have already installed all the libraries.
`qt5-qmake is already the newest version (5.11.3+dfsg-5).`
Now I don't have anymore the command `qt5-qmake`

```
$ qt5-qmake --version
bash: qt5-qmake : can't find command
```

**Comment by johhnry** [comment]
Ok nevermind I think that I understand, it's because there's no "qt5" suffix, there's `qmake`.

I still have : `Using Qt version 5.11.3 in /usr/lib/x86_64-linux-gnu`
and the errors with the scide.

**Comment by snappizz** [comment]
is there a file at `/root/.local/share/SuperCollider/Help/lib/jquery.min.js`?

**Comment by johhnry** [comment]
@snappizz Yes it's there : 

```Shell
root@johk:~/.local/share/SuperCollider/Help/lib# ls
codemirror-5.39.2.min.js  codemirror-addon-simple-5.39.2.min.js  jquery.min.js
```

**Comment by snappizz** [comment]
hmmm, could you check the paths of the `<script>` tags in `/root/.local/share/SuperCollider/Help/Help.html`?

also, since you're running as root, maybe investigate to check for any signs of a permissions issue with the `lib` directory or the files within.

**Comment by gusano** [comment]
@johhnry may I ask why you run sc as root? this is not exactly recommended..

**Comment by jamshark70** [comment]
I looked up Kali Linux... It's a distribution for network security penetration testing (ethical hacking).

I can't imagine this is the best distribution for day to day work. The intent was to keep Kali clean and minimal so that you have more confidence that network traffic is under your control and not from malware (and if you see something strange, it's probably malware and not a chat app). Installing apps like SC which use network protocols a/ compromises the purpose of the OS and b/ in Kali, there's only root so every app becomes a security risk (dubious, in a distro aimed at security).

It's a strange choice of OS for music but maybe there are other reasons to use it.

**Comment by gusano** [comment]
@johhnry what about [adding a non-root user account and testing again?](https://www.interfacett.com/blogs/adding-a-new-non-root-user-in-kali-linux/)

**Comment by johhnry** [comment]
@snappizz 
This is the result of the `<script>` tags : 

```
root@johk:~# grep "<script>*" /root/.local/share/SuperCollider/Help/Help.html
<script src='./lib/jquery.min.js'></script>
<script src='./lib/codemirror-5.39.2.min.js' type='text/javascript'></script>
<script src='./lib/codemirror-addon-simple-5.39.2.min.js' type='text/javascript'></script>
<script>
<script src='./scdoc.js' type='text/javascript'></script>
<script src='./docmap.js' type='text/javascript'></script>
<script src='qrc:///qtwebchannel/qwebchannel.js' type='text/javascript'></script>
<p>These help files are published under the Creative Commons CC-BY-SA-3 license: <a href="./Other/HelpDocsLicensing.html">HelpDocsLicensing</a>.<div class='doclink'>helpfile source: <a href='file:///usr/share/SuperCollider/HelpSource/Help.schelp'>/usr/share/SuperCollider/HelpSource/Help.schelp</a><br>link::Help::<br></div></div><script src='./editor.js' type='text/javascript'></script>

```
And the `lib` folder permissions seems normal : `drwxr-xr-x  2 root root 4,0K mars  23 19:07 lib`

@jamshark70 
Yes you are right, it's just that I am interested in network security and livecoding (yes I know... ;)

@gusano 
Yes I did it before (if have a `nonroot` account) if running sc as root is really not recommended, I would use it.

**Comment by gusano** [comment]
@johhnry you should never run sc as root, and it might just solve your issue

**Comment by snappizz** [comment]
given this is an infosec-related OS, my best guess is that there's probably some security feature blocking qtwebengine from running javascript code. unfortunately i don't think we can provide much support for issues when running SC IDE as root in a specific linux distribution, so i'm going to have to close this issue, sorry.

**Comment by snappizz** [comment]
hmm, maybe it is a more general issue. other linux users are also reporting this: #4392

**Comment by kleinm90** [comment]
I habe the same problem.

**Comment by bartart3d** [comment]
with the help of the ubuntu chatroom, I found my way here.. I filed a report in launchpad : https://bugs.launchpad.net/ubuntu/+source/supercollider/+bug/1833752

seems like the same issue here, on two machines.

**Comment by gusano** [comment]
@snappizz  As shown in #4392 comments, it seems that SuperCollider package for Ubuntu is missing javascript library files (`$HOME/.local/share/SuperCollider/Help/lib` is empty), leading to a broken Help system

**Comment by bartart3d** [comment]
as an addition to what I tried in the other bugreport, [ `#4392`](https://github.com/supercollider/supercollider/issues/4392), the help documentation also is installed in 
`/usr/share/SuperCollider/HelpSource/lib/`
And it has the same problem. I noticed because SuperCollider threw a bunch of warnings and errors, which dissapeared when pasting the javascript files in that directory too.

In other words, the installation package also creatis broken symlinks in 
`/usr/share/SuperCollider/HelpSource/lib/`

**Comment by snappizz** [comment]
per discussion at #4392 this is actually an upstream issue with debian or ubuntu packaging. we do not support outdated versions in linux packages. to fix, build SC from source (you should really be on 3.10.2 anyway -- 3.10.0 and 3.10.1 have a serious gradual memory leak in sclang).
