### ISSUE TITLE
Issues with bidirectional reference of two Environments

### ISSUE THREAD

**Issue by dyfer** [supercollider/supercollider#4377]
## Environment

* SuperCollider version: 3.10.2
* Operating system: macOS 10.13.6

## Steps to reproduce

```supercollider
e = Environment();
f = Environment.make({~ref = e; ~something = "f"});
e.use({~ref = f; ~something = "e"});
"test".postln; //OK so far

e[\ref][\something]; //works
f[\ref][\something]; //works
e.postln;//works, since it's truncated
e[\ref]; //works, similar to above

EnvirGui(e);//hangs the interpreter
e.postcs;//also hangs the interpreter
```

## Expected vs. actual behavior

Since there's no issue in making this kind of assignment, it would be ideal to avoid lockup when trying to use ```EnvirGui```.

More context:

I am trying a new workflow to split project into multiple files, and that (ideally) requires to have two (or more) ```Environment```s referencing each other.

This does not pose a problem when using these Environments to store various objects, but it locks up the interpreter when one attempts to use `EnvirGui` (or post the object as a ```compileString```).

After investigating further, I can see why that is (sclang goes through all objects recursively which puts it in an endless loop), but I was wondering whether:
- there's a way to detect this somehow and avoid locking up
- or maybe this kind of circular reference should be avoided

I'd appreciate any feedback on this, thanks!

**Comment by jamshark70** [comment]
> there's a way to detect this somehow and avoid locking up

This has been discussed. It's really hard, and would make an already slow interpreter even slower.

> or maybe this kind of circular reference should be avoided

I use named references for this. In ddwChucklib, a `BP` is a named reference to a Proto.

```
Proto {
    ~otherKey = \b;
    ~method = { BP(~otherKey).doSomething };
} => BP(\a);

Proto {
    ~otherKey = \a;
    ~method = { BP(~otherKey).doSomething };
} => BP(\b);
```

**Comment by telephon** [comment]
Btw, `LazyEnvir` catches call loops (however not the ones you are trying to avoid).

**Comment by dyfer** [comment]
I guess there is no "solution" to this. Thank you for your comments!

**Comment by eleses** [comment]
This would be more difficult to solve than what happens with inf-repeating empty sub-Patterns (see #4642 for that) because here you have mutual recursion without a clear "top level" object that can detect it (as you have in the Pattern case).
