### ISSUE TITLE
Unable to boot/launch server

### ISSUE THREAD

**Issue by ranjithshegde** [supercollider/supercollider#4381]
Greetings,

I am new to supercollider. I just installed it unto Ubuntu 18..04 LTS using instructions from github

When I launch the server I get the following error

**_compiling class library...
	Found 715 primitives.
	Compiling directory '/usr/share/SuperCollider/SCClassLibrary'
	Compiling directory '/usr/share/SuperCollider/Extensions'
	Compiling directory '/home/ranjith/.local/share/SuperCollider/Extensions'
	numentries = 1247993 / 18318432 = 0.068
	5478 method selectors, 3344 classes
	method table size 19245064 bytes, big table size 146547456
	Number of Symbols 14454
	Byte Code Size 430985
	compiled 546 files in 0.31 seconds

Info: 4 methods are currently overwritten by extensions. To see which, execute:
MethodOverride.printAll

compile done
localhost : setting clientID to 0.
internal : setting clientID to 0.
Couldn't set realtime scheduling priority 1: Operation not permitted
Class tree inited in 0.01 seconds

*** Welcome to SuperCollider 3.9.1. *** For help press Ctrl-D.
Couldn't set realtime scheduling priority 1: Operation not permitted
SCDoc: Indexing help-files...
SCDoc: Indexed 1897 documents in 0.8 seconds
booting server 'localhost' on address: 127.0.0.1:57110
*** ERROR: API Version Mismatch: /usr/lib/SuperCollider/plugins/DynNoiseUGens.so
*** ERROR: API Version Mismatch: /usr/lib/SuperCollider/plugins/LFUGens.so
*** ERROR: API Version Mismatch: /usr/lib/SuperCollider/plugins/ChaosUGens.so
*** ERROR: API Version Mismatch: /usr/lib/SuperCollider/plugins/NoiseUGens.so
*** ERROR: API Version Mismatch: /usr/lib/SuperCollider/plugins/BinaryOpUGens.so
*** ERROR: API Version Mismatch: /usr/lib/SuperCollider/plugins/PhysicalModelingUGens.so
*** ERROR: API Version Mismatch: /usr/lib/SuperCollider/plugins/GrainUGens.so
*** ERROR: API Version Mismatch: /usr/lib/SuperCollider/plugins/TriggerUGens.so
*** ERROR: API Version Mismatch: /usr/lib/SuperCollider/plugins/FilterUGens.so
*** ERROR: API Version Mismatch: /usr/lib/SuperCollider/plugins/GendynUGens.so
*** ERROR: API Version Mismatch: /usr/lib/SuperCollider/plugins/TestUGens.so
*** ERROR: API Version Mismatch: /usr/lib/SuperCollider/plugins/DelayUGens.so
*** ERROR: API Version Mismatch: /usr/lib/SuperCollider/plugins/IOUGens.so
*** ERROR: API Version Mismatch: /usr/lib/SuperCollider/plugins/UnaryOpUGens.so
*** ERROR: API Version Mismatch: /usr/lib/SuperCollider/plugins/OscUGens.so
*** ERROR: API Version Mismatch: /usr/lib/SuperCollider/plugins/ML_UGens.so
*** ERROR: API Version Mismatch: /usr/lib/SuperCollider/plugins/PV_ThirdParty.so
*** ERROR: API Version Mismatch: /usr/lib/SuperCollider/plugins/FFT_UGens.so
*** ERROR: API Version Mismatch: /usr/lib/SuperCollider/plugins/UIUGens.so
*** ERROR: API Version Mismatch: /usr/lib/SuperCollider/plugins/UnpackFFTUGens.so
*** ERROR: API Version Mismatch: /usr/lib/SuperCollider/plugins/PanUGens.so
*** ERROR: API Version Mismatch: /usr/lib/SuperCollider/plugins/MulAddUGens.so
*** ERROR: API Version Mismatch: /usr/lib/SuperCollider/plugins/DemandUGens.so
*** ERROR: API Version Mismatch: /usr/lib/SuperCollider/plugins/DiskIO_UGens.so
*** ERROR: API Version Mismatch: /usr/lib/SuperCollider/plugins/ReverbUGens.so
jackdmp 1.9.12
Copyright 2001-2005 Paul Davis and others.
Copyright 2004-2016 Grame.
Copyright 2016-2017 Filipe Coelho.
jackdmp comes with ABSOLUTELY NO WARRANTY
This is free software, and you are welcome to redistribute it
under certain conditions; see the file COPYING for details
JACK server starting in realtime mode with priority 10
self-connect-mode is "Don't restrict self connect requests"
audio_reservation_init
Acquire audio card Audio0
creating alsa driver ... hw:0|hw:0|1024|2|48000|0|0|nomon|swmeter|-|32bit
configuring for 48000Hz, period = 1024 frames (21.3 ms), buffer = 2 periods
ALSA: final selected sample format for capture: 32bit integer little-endian
ALSA: use 2 periods for capture
ALSA: final selected sample format for playback: 32bit integer little-endian
ALSA: use 2 periods for playback
JackDriver: client name is 'SuperCollider'
SC_AudioDriver: sample rate = 48000.000000, driver's block size = 1024
JackDriver: connected  system:capture_1 to SuperCollider:in_1
JackDriver: connected  system:capture_2 to SuperCollider:in_2
JackDriver: connected  SuperCollider:out_1 to system:playback_1
JackDriver: connected  SuperCollider:out_2 to system:playback_2
SuperCollider 3 server ready.
JackDriver: max output latency 42.7 ms
Requested notification messages from server 'localhost'
localhost: no maxLogins info from server process.
localhost: keeping clientID (0) as confirmed by server process.
exception in GraphDef_Recv: UGen 'Control' not installed.
exception in GraphDef_Recv: UGen 'Control' not installed.
exception in GraphDef_Recv: UGen 'Control' not installed.
exception in GraphDef_Recv: UGen 'Control' not installed.
exception in GraphDef_Recv: UGen 'Control' not installed.
exception in GraphDef_Recv: UGen 'Control' not installed.
exception in GraphDef_Recv: UGen 'Control' not installed.
exception in GraphDef_Recv: UGen 'Control' not installed.
exception in GraphDef_Recv: UGen 'Control' not installed.
exception in GraphDef_Recv: UGen 'Control' not installed.
exception in GraphDef_Recv: UGen 'Control' not installed.
exception in GraphDef_Recv: UGen 'Control' not installed.
exception in GraphDef_Recv: UGen 'Control' not installed.
exception in GraphDef_Recv: UGen 'Control' not installed.
exception in GraphDef_Recv: UGen 'Control' not installed.
exception in GraphDef_Recv: UGen 'Control' not installed.
exception in GraphDef_Recv: UGen 'Control' not installed.
exception in GraphDef_Recv: UGen 'Control' not installed.
exception in GraphDef_Recv: UGen 'Control' not installed.
exception in GraphDef_Recv: UGen 'Control' not installed.
exception in GraphDef_Recv: UGen 'Control' not installed.
exception in GraphDef_Recv: UGen 'Control' not installed.
exception in GraphDef_Recv: UGen 'Control' not installed.
exception in GraphDef_Recv: UGen 'Control' not installed.
exception in GraphDef_Recv: UGen 'Control' not installed.
exception in GraphDef_Recv: UGen 'Control' not installed.
exception in GraphDef_Recv: UGen 'Control' not installed.
exception in GraphDef_Recv: UGen 'Control' not installed.
exception in GraphDef_Recv: UGen 'Control' not installed.
exception in GraphDef_Recv: UGen 'Control' not installed.
exception in GraphDef_Recv: UGen 'Control' not installed.
exception in GraphDef_Recv: UGen 'Control' not installed.
exception in GraphDef_Recv: UGen 'Control' not installed.
exception in GraphDef_Recv: UGen 'Control' not installed.
exception in GraphDef_Recv: UGen 'Control' not installed.
exception in GraphDef_Recv: UGen 'Control' not installed.
exception in GraphDef_Recv: UGen 'Control' not installed.
exception in GraphDef_Recv: UGen 'Control' not installed.
exception in GraphDef_Recv: UGen 'Control' not installed.
exception in GraphDef_Recv: UGen 'Control' not installed.
exception in GraphDef_Recv: UGen 'Control' not installed.
exception in GraphDef_Recv: UGen 'Control' not installed.
exception in GraphDef_Recv: UGen 'Control' not installed.
exception in GraphDef_Recv: UGen 'Control' not installed.
exception in GraphDef_Recv: UGen 'Control' not installed.
exception in GraphDef_Recv: UGen 'Control' not installed.
exception in GraphDef_Recv: UGen 'Control' not installed.
exception in GraphDef_Recv: UGen 'Control' not installed.
exception in GraphDef_Recv: UGen 'Control' not installed.
exception in GraphDef_Recv: UGen 'Control' not installed.
exception in GraphDef_Recv: UGen 'Control' not installed.
exception in GraphDef_Recv: UGen 'Control' not installed.
exception in GraphDef_Recv: UGen 'Control' not installed.
exception in GraphDef_Recv: UGen 'Control' not installed.
exception in GraphDef_Recv: UGen 'Control' not installed.
exception in GraphDef_Recv: UGen 'Control' not installed.
exception in GraphDef_Recv: UGen 'Control' not installed.
exception in GraphDef_Recv: UGen 'Control' not installed.
exception in GraphDef_Recv: UGen 'Control' not installed.
exception in GraphDef_Recv: UGen 'Control' not installed.
exception in GraphDef_Recv: UGen 'Control' not installed.
exception in GraphDef_Recv: UGen 'Control' not installed.
exception in GraphDef_Recv: UGen 'Control' not installed.
exception in GraphDef_Recv: UGen 'Control' not installed.
exception in GraphDef_Recv: UGen 'Control' not installed.
exception in GraphDef_Recv: UGen 'Control' not installed.
exception in GraphDef_Recv: UGen 'Control' not installed.
exception in GraphDef_Recv: UGen 'Control' not installed.
exception in GraphDef_Recv: UGen 'Control' not installed.
exception in GraphDef_Recv: UGen 'Control' not installed.
exception in GraphDef_Recv: UGen 'Control' not installed.
exception in GraphDef_Recv: UGen 'Control' not installed.
exception in GraphDef_Recv: UGen 'Control' not installed.
exception in GraphDef_Recv: UGen 'Control' not installed.
exception in GraphDef_Recv: UGen 'Control' not installed.
exception in GraphDef_Recv: UGen 'Control' not installed.
exception in GraphDef_Recv: UGen 'Control' not installed.
exception in GraphDef_Recv: UGen 'Control' not installed.
exception in GraphDef_Recv: UGen 'Control' not installed.
exception in GraphDef_Recv: UGen 'Control' not installed.
exception in GraphDef_Recv: UGen 'Control' not installed.
exception in GraphDef_Recv: UGen 'Control' not installed.
exception in GraphDef_Recv: UGen 'Control' not installed.
exception in GraphDef_Recv: UGen 'Control' not installed.
exception in GraphDef_Recv: UGen 'Control' not installed.
exception in GraphDef_Recv: UGen 'Control' not installed.
exception in GraphDef_Recv: UGen 'Control' not installed.
exception in GraphDef_Recv: UGen 'Control' not installed.
exception in GraphDef_Recv: UGen 'Control' not installed.
exception in GraphDef_Recv: UGen 'Control' not installed.
exception in GraphDef_Recv: UGen 'Control' not installed.
exception in GraphDef_Recv: UGen 'Control' not installed.
exception in GraphDef_Recv: UGen 'Control' not installed.
exception in GraphDef_Recv: UGen 'Control' not installed.
exception in GraphDef_Recv: UGen 'Control' not installed.
exception in GraphDef_Recv: UGen 'Control' not installed.
exception in GraphDef_Recv: UGen 'Control' not installed.
exception in GraphDef_Recv: UGen 'Control' not installed.
exception in GraphDef_Recv: UGen 'Control' not installed.
exception in GraphDef_Recv: UGen 'Control' not installed.
exception in GraphDef_Recv: UGen 'Control' not installed.
exception in GraphDef_Recv: UGen 'Control' not installed.
exception in GraphDef_Recv: UGen 'Control' not installed.
exception in GraphDef_Recv: UGen 'Control' not installed.
exception in GraphDef_Recv: UGen 'Control' not installed.
exception in GraphDef_Recv: UGen 'Control' not installed.
Shared memory server interface initialized_**

**Comment by patrickdupuis** [comment]
These errors are due to the fact that your installed version of sc3-plugins isn't compatible with your installed version of SuperCollider:
` *** ERROR: API Version Mismatch `

You should try removing SC and sc3-plugins from your system, and them follow this guide: https://github.com/supercollider/supercollider/wiki/Installing-SuperCollider-from-source-on-Ubuntu

**Comment by ranjithshegde** [comment]
Thank you patrick for your help. I uninstalled the plugins and supercollider.
from the link you sent me I reinstalled supercollider and the server boots fine
but when I try to install the plugins I get this error message

~/sc3-plugins/build$ cmake -DSC_PATH=~/supercollider
CMake Error: The source directory "/home/ranjith/sc3-plugins/build" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
Any ideas?

**Comment by snappizz** [comment]
@ranjithshegde looks like you forgot the `..` at the end of the cmake path :)

**Comment by ranjithshegde** [comment]
goodness thats right. How silly of me
 Thanks mate!

**Comment by snappizz** [comment]
you're welcome! closing as the issue seems to be resolved.

**Comment by ranjithshegde** [comment]
Sorry but it does not seem to be fully resolved. I run two machines, so far on the desktop everything went fine following the above link but on my laptop I encounter the following error when booting the server.

Couldn't set realtime scheduling priority 1: Operation not permitted
SCDoc: Indexing help-files...
SCDoc: Indexed 1908 documents in 1.24 seconds
Booting server 'localhost' on address 127.0.0.1:57110.
Found 0 LADSPA plugins
jackdmp 1.9.12
Copyright 2001-2005 Paul Davis and others.
Copyright 2004-2016 Grame.
Copyright 2016-2017 Filipe Coelho.
jackdmp comes with ABSOLUTELY NO WARRANTY
This is free software, and you are welcome to redistribute it
under certain conditions; see the file COPYING for details
JACK server starting in realtime mode with priority 10
self-connect-mode is "Don't restrict self connect requests"
audio_reservation_init
Acquire audio card Audio0
creating alsa driver ... hw:0|hw:0|1024|2|48000|0|0|nomon|swmeter|-|32bit
Released audio card Audio0
audio_reservation_finish
could not initialize audio.
Server 'localhost' exited with exit code 0.

**Comment by patrickdupuis** [comment]
This is a JACK configuration issue. You need to make sure you are able to get JACK running (using qjackctl for example). If JACK can boot, the SC server will likely be able to boot also.

**Comment by ranjithshegde** [comment]
Yes, trying to launch jack through terminal gives me this error

01:23:24.119 Statistics reset.
01:23:24.147 ALSA connection change.
01:23:24.242 D-BUS: Service is available (org.jackaudio.service aka jackdbus).
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
01:23:24.354 ALSA connection graph change.
01:23:30.451 D-BUS: JACK server could not be started. Sorry
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
Fri Apr 12 01:23:30 2019: Starting jack server...
Fri Apr 12 01:23:30 2019: JACK server starting in realtime mode with priority 10
Fri Apr 12 01:23:30 2019: self-connect-mode is "Don't restrict self connect requests"
Fri Apr 12 01:23:30 2019: ERROR: Cannot lock down 82280346 byte memory area (Cannot allocate memory)
Fri Apr 12 01:23:30 2019: Acquired audio card Audio0
Fri Apr 12 01:23:30 2019: creating alsa driver ... hw:0|hw:0|1024|2|44100|0|0|nomon|swmeter|-|32bit
Fri Apr 12 01:23:30 2019: ERROR: ALSA: Cannot open PCM device alsa_pcm for playback. Falling back to capture-only mode
Fri Apr 12 01:23:30 2019: Released audio card Audio0
Fri Apr 12 01:23:30 2019: ERROR: Cannot initialize driver
Fri Apr 12 01:23:30 2019: ERROR: JackServer::Open failed with -1
Fri Apr 12 01:23:30 2019: ERROR: Failed to open server
Fri Apr 12 01:23:31 2019: Saving settings to "/home/ranjith/.config/jack/conf.xml" ...
01:23:44.249 Could not connect to JACK server as client. - Overall operation failed. - Unable to connect to server. Please check the messages window for more info.
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock

**Comment by patrickdupuis** [comment]
this is a JACK config problem. it has nothing to do with SC. Linux audio is often hard until you figure things out. you should look for resources online on how to config JACK.
