### ISSUE TITLE
FR: UnitTest needs class-wide setUp / tearDown

### ISSUE THREAD

**Issue by aspiers** [supercollider/supercollider#4385]
`UnitTest` currently supports `setUp` and `tearDown` methods, which perform setup and teardown for the isolated environment of each `test_*` method (thanks to #3836).  However it would be useful to add support for class-wide setup and teardown, e.g. so that external dependencies could be set up correctly.

The setup would get run once before the first test in the class is run, and the teardown would get run once after the last test in the class is run.  They could be called `setUpClass` and `tearDownClass` [like they are in Python](https://docs.python.org/3/library/unittest.html#setupclass-and-teardownclass).

**Comment by telephon** [comment]
We could also simply implement setUp and tearDown also as class methods.

**Comment by aspiers** [comment]
True, although personally I think the clarity of the different names is less taxing on the brain when skim-reading code, and therefore helpful.  Plus it would be less to remember for those coming from the Python world.

**Comment by snappizz** [comment]
could someone provide an example of a unit test class that would benefit from being written with `setUpClass` and `tearDownClass`? just want to gauge the importance of this feature a bit.

**Comment by telephon** [comment]
@aspiers - do you have an example in mind?

**Comment by aspiers** [comment]
I must have had one in mind when I submitted this, but I can't recall it right now, sorry.  This feature request is definitely not urgent, but I think it would be useful long term; it's a totally standard feature of every other xUnit-style testing framework I've seen.
