### ISSUE TITLE
Unable to run synthdef without loading foxdot

### ISSUE THREAD

**Issue by ranjithshegde** [supercollider/supercollider#4386]
Greetings,
Despite booting the server, I am not able to run synthdef function with having to launch FoxDot via python.
If I dont then I get this error

*** ERROR: SynthDef pulseTest not found
FAILURE IN SERVER /s_new SynthDef not found

Is foxdot being launched a default requirement to use synthdef?

FYI: Ubuntu 18.04LTS
       Supercollider version3.10.2 with sc3-plugins installed and running properly

**Comment by snappizz** [comment]
hi, thanks for the report. can you post complete instructions for reproducing the issue?

**Comment by ranjithshegde** [comment]
Its following a tutorial

(
SynthDef.new(\pulseTest, {
	arg ampHz=4, fund=40, maxPartial=4, width=0.5;
	var amp1, amp2, freq1, freq2, sig1, sig2;
	amp1 = LFPulse.kr(ampHz,0, 0.12) * 0.75;
	amp2 = LFPulse.kr(ampHz, 0.5, 0.12) * 0.75;
	freq1 = LFNoise0.kr(4).exprange(fund, fund*maxPartial).round(fund);
	freq2 = LFNoise0.kr(4).exprange(fund, fund*maxPartial).round(fund);
	freq1 = freq1 * LFPulse.kr(8, add:1);
	freq2 = freq2 * LFPulse.kr(6, add:1);
	sig1 = Pulse.ar(freq1, width, amp1);
	sig2 = Pulse.ar(freq2, width, amp2);
	sig1 = FreeVerb.ar(sig1, 0.7, 0.8, 0.25);
	sig2 = FreeVerb.ar(sig2, 0.7, 0.8, 0.25);
	Out.ar(0, sig1);
	Out.ar(1, sig1);
}).add
)

x = Synth.new(\pulseTest);

The same works once I launch foxdot via terminal using sudo python -m FoxDot

**Comment by snappizz** [comment]
please use triple backticks (```) to enclose code.

the code works for me in the SCIDE -- i get sound if i run the first block then the second. (i have never used foxdot and i don't have it installed.) can you give more complete reproduction instructions? how exactly are you running the code?

**Comment by ranjithshegde** [comment]
I press shift+enter on this line 
x = Synth.new(\pulseTest);

Is that what you mean by reproduction instructions?

This is the tutorial
https://www.youtube.com/watch?v=LKGGWsXyiyo

**Comment by snappizz** [comment]
did you run the first block of code also?

**Comment by ranjithshegde** [comment]
Not in this case. And this method (learned from the tutorial) worked for me so far. i.e declaring x to contain block one and executing second block (x).

I will give running the first block and then the second a try

**Comment by ranjithshegde** [comment]
You are right. It works when I run the first and then the second, although after launching foxDot I can just run the second. 
Either ways, this solves my issue.

Thanks for your help mate
Cheers

**Comment by snappizz** [comment]
you're welcome! basic usage of sclang is a bit tough to understand at first and you have to be careful to follow all steps correctly if you're a beginner. (also, if you do file future issues with SC, please make sure to use the issue template.)

**Comment by jamshark70** [comment]
@ranjithshegde I would also suggest joining scsynth.org and raising this sort of question there.

This is a bug tracker, not a support forum. To my recollection, you've posted two usage questions that are not, in fact, bugs. They are certainly valid usage questions -- but as such, they belong on a support forum (scsynth.org). This is not really the best place for them.

At the forum (and on the sc-users mailing list), you'll find a lot of people willing to help.

**Comment by ranjithshegde** [comment]
@jamshark70 
I was unaware of the forum you mentioned. All I found to ask for help was this page and a facebook group that had not confirmed my membership at the time of this query
Thank you for the info. I will join it.
