### ISSUE TITLE
PanAz returns incorrect signal for the first block

### ISSUE THREAD

**Issue by telephon** [supercollider/supercollider#4387]
## Environment

* SuperCollider version: branch 'develop' [63783ae]

## Steps to reproduce

```supercollider
{ PanAz.ar(2, SinOsc.ar(100), 0) }.plot
```

## Expected vs. actual behavior

I'd expect to see a sine wave, but the signal fades into a sine wave instead. This might be one of these init bugs.

<img width="403" alt="image" src="https://user-images.githubusercontent.com/1810559/56159333-af40d080-5fc4-11e9-9d63-26b77b7f1fe4.png">

**Comment by jamshark70** [comment]
Here:

https://github.com/supercollider/supercollider/blob/develop/server/plugins/PanUGens.cpp#L1485

```
		std::fill_n(unit->m_chanamp, numOutputs, 0);
```

If `pos` is kr or scalar, we assume 0 as the starting amplitude for all channels.

**Comment by mtmccrea** [comment]
At a quick glance there are actually 3 problems with this `Ctor`:

1. In the case `INRATE(1) == calc_FullRate` case, the initial sample(s) aren't set (`ZOUT0(i)`):
https://github.com/supercollider/supercollider/blob/63783aeca007c1e1d2a7cf73b3f3da056913f077/server/plugins/PanUGens.cpp#L1470-L1473
  - this would be solved by calling `PanAz_next_aa(unit, 1)` directly after `SETCALC(PanAz_next_aa);`.
2. `unit->m_chanamp` should be set to `nullptr` at the top of the `Ctor`, not just in the `INRATE(1) == calc_FullRate` case.  If `RTAlloc` fails, the uninitialized pointer may cause a crash once the `Dtor` is called. 
3. The bug identified in this issue: the erroneous assumption that all amplitudes start at 0, effectively hard-coding a "fade-in" in the control-/scalar-rate cases, which is bad design.
  - To fix this, you'd have to run the panning coefficient algorithm in the `Ctor`, which is probably best done by just creating a new calc function, and calling it at the tail of the `else` case of the `INRATE(1) == calc_FullRate` test. This new calc function is a paired down version of `PanAz_next_ak`:

```
// untested!!
void PanAz_init_ak(PanAz *unit)
{
	float pos = ZIN0(1);
	float level = ZIN0(2);
	float width = ZIN0(3);
	float orientation = ZIN0(4);
	
	int numOutputs = unit->mNumOutputs;
	float rwidth = sc_reciprocal( width );
	float range = numOutputs * rwidth;
	float rrange = sc_reciprocal( range );
	
	pos = pos * 0.5f * numOutputs + width * 0.5f + orientation;
	
	for (int i=0; i<numOutputs; ++i) {
		float nextchanamp;
		float chanpos = pos - i;
		chanpos *= rwidth;
		chanpos = chanpos - range * sc_floor(rrange * chanpos);
		if (chanpos > 1.f) {
			nextchanamp = 0.f;
		} else {
			nextchanamp  = level * ft->mSine[(long)(4096.f * chanpos)];
		}

		ZOUT0(i) = ZIN0(0) * chanamp;
		unit->m_chanamp[i] = nextchanamp;
	}
}
```

**Comment by mtmccrea** [comment]
The corrected `Ctor` would look like this (again, untested):
```
void PanAz_Ctor(PanAz *unit)
{
	unit->m_chanamp = nullptr;               // MOVED
	
	if (INRATE(1) == calc_FullRate) {
		SETCALC(PanAz_next_aa);
		PanAz_next_aa(unit, 1);              // ADDED
	} else {
		int numOutputs = unit->mNumOutputs;
		// for (int i=0; i<numOutputs; ++i)  // REMOVED
		//	ZOUT0(i) = 0.f;                  // REMOVED
		
		unit->m_chanamp = (float*)RTAlloc(unit->mWorld, numOutputs*sizeof(float));
		if (!unit->m_chanamp) {
			Print("PanAz: RT memory allocation failed\n");
			SETCALC(ClearUnitOutputs);
			return;
		}
		
		// std::fill_n(unit->m_chanamp, numOutputs, 0); // REMOVED
#ifdef NOVA_SIMD
		if (boost::alignment::is_aligned( BUFLENGTH, 16 ))
			SETCALC(PanAz_next_ak_nova);
		else
			SETCALC(PanAz_next_ak);
#else
		SETCALC(PanAz_next_ak);
#endif
		PanAz_init_ak(unit);      // ADDED
	}
}
```

**Comment by elgiano** [comment]
@mtmccrea I was looking into PanAz for another issue, but I would be interested in getting this fixed as well. I was wondering (open question), instead of PanAz_init_ak, why not PanAz_next_ak(unit, 1)?
