### ISSUE TITLE
[link] aLinkClock.beatsPerBar_() breaks beat continuity

### ISSUE THREAD

**Issue by jamshark70** [supercollider/supercollider#4401]
## Environment

* SuperCollider version: 63783aeca00
* Operating system: Ubuntu Studio

## Issue

Currently, if a LinkClock is connected to other Link peers and it changes `beatsPerBar`, it will either skip beats or elongate beats in an attempt to adjust the timeline to be in phase sync with other peers.

See https://github.com/Ableton/link/issues/66.

According to [Link developers](https://github.com/Ableton/link/issues/66#issuecomment-490520655), "Unfortunately Link can not provide continuous beat times when changing the quantum" -- so, by including `setQuantum` in `LinkClock:setMeterAtBeat`, we are actually not using the Link API correctly.

Link devs say:

> Here is how we deal with a related scenario in Live: We set the quantum when starting playback. In case the time signature in the arrangement timeline changes, we still query the beat time using the initial quantum and just iterate beat time from there - accepting that the phase of the new time signature might not match phase with peers using the same time signature.

In other words, do *not* change quantum to match `beatsPerBar`. We misinterpreted the spec to assume that these were the same concept.

We have to handle two things:

- Sync with non-SC peers. Ableton's recommendation for this will work. Before beginning a performance, set `quantum` appropriately -- a beat may be discontinuous, but you're not hearing anything at that time. 

- `baseBarBeat` sync with other SC peers. This is trickier. If you started SC with quantum = 4, but switched to beatsPerBar = 3, and then a new SC peer joins the network, the new one's base beats will be in sync according to 4/4 -- to line up 3/4, the SC peers will need to communicate `baseBarBeat` alignment separately. I believe we will need our own OSC protocol for this.

For now, we will have to document that changing `beatsPerBar` in LinkClock is unstable. (One reason to file the bug report is so that users encountering this problem could find it when searching the bug tracker.)

For future (I hope near future), I'm interested in this problem and I'm willing to work on the OSC protocol. I've got some ideas, but no time at the moment to write them down. Maybe soon.

**Comment by jamshark70** [comment]
I'd like some feedback on this proposal.

### Goals:

- Main use case: Keep meter and barlines in sync over all peers at all times.

- Secondary use case: Meter and barlines don't have to be in sync, but the user may want to have information about other peers' metrical alignment.

Initially, I was considering a strategy where the local SC instance, changing meter, would identify which peers are already on the new meter and then figure out where the barline should fall. But you have no guarantee of a common barline and every automated approach would fail in some cases. So now I'm thinking to keep it simpler: provide an option for total metrical sync, and otherwise, it's up to the user.

### Why:

- SC instance A starts a LinkClock with `beatsPerBar` and `quantum` both == 4.

- Somewhere in the middle of the session, it changes `beatsPerBar` to 3 (but not `quantum` -- as noted above, we shouldn't, not while playing). To keep the timeline short, we'll say this happens at beat 4: `baseBarBeat == 4`.

- A bit later, another peer (B) joins the session -- we should keep Link's quantum == 4, but we want to join SC's user-facing meter 3/4. Link places B's beat 0 (B0) in q=4 alignment, at beat A8. But A's barlines are now 4, 7, 10, 13, 16... so B is, from the user's perspective, out of phase.

```
  Meter: bpb=4       bpb=3
A beats: 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14
  Beats: |--|--|--|--|--|--|--|--|--|--|--|--|--|--|
   Bars: |           |        |        |        |
B beats:                         0  1  2  3  4  5  6
```

I would like to be able to write `t = LinkClock.new.latency_(0.2).syncMeter_(true)` and B would automatically determine that `beatsPerBar` = 3 and `baseBarBeats` = 2.

### Proposal:

- A LinkClock instance variable `syncMeter` which, if true, would a/ broadcast meter changes originating from this instance and b/ receive meter changes from other instances.
  - Setting this `true` should ping the other peers and adjust the local `baseBarBeats` to match.
  - All `syncMeter` peers should have the same `beatsPerBar` and phase alignment. If a discrepancy is found, post a message and fail.
  - When adjusting `baseBarBeats`, we can't do anything about patterns/routines that are already playing. User's responsibility.

- A method `queryMeter` which would asynchronously ask all peers (whether `syncMeter` is on or not) about their current meter and phase alignment, calling an action function with an array of Events. The user can calculate the desired metrical alignment however she likes.
  - Send `["/LinkClockMeterQuery", beatsPerBar, this.beatInBar.trunc]`.
  - Receive `["/LinkClockMeterReply", beatsPerBar, this.beatInBar.trunc]`. We don't have a good way to identify specific peers.

- We can already control `baseBarBeats` using `setMeterAtBeat`, but it might be nice to have another method, say, `adjustPhase(myPhase, remotePhase)`. If the query finds out that my phase 0 (barline) matches up to the network's phase 1, then `baseBarBeats = baseBarBeats + ((myPhase - remotePhase) % beatsPerBar)`. The user shouldn't have to remember that.

Comments?

**Comment by jamshark70** [comment]
I'm starting to work on this now: https://github.com/jamshark70/supercollider/commits/topic/LinkClockSetQuantum

One wrinkle is that I can't reproduce the beat discontinuity today... will try again later.

**Comment by jamshark70** [comment]
OK, now I can reproduce it.

There's a dumb mistake in `LinkClock:setMeterAtBeat` that never got corrected in the development branch:

```
	setMeterAtBeat { |newBeatsPerBar, beats|
		this.prSetQuantum(beatsPerBar);
		super.setMeterAtBeat(newBeatsPerBar, beats);
	}
```

... where we are setting the clock's SC-side meter to the new beats per bar, but the quantum to the old one...? After correcting that, I can reproduce the issue again.

So my plan is:

1. Reproduce the problem in a unit test.
2. Fix it.
3. Confirm the fix using the unit test.
4. Add features for automatic meter sync as described above, and make sure it doesn't break anything (unit tests).

Might take some time.

**Comment by jamshark70** [comment]
I'm running into another bug: Sometimes, if I `schedAbs` something for 1.0 beats, it wakes up at 1.476374 or 2.19347372 or 1.1823741321 beats. Which is nonsense. Beats should be beats, always.

I don't know why yet. Just reporting.

**Comment by brianlheim** [comment]
@jamshark70 is this fixed with #4484?

**Comment by jamshark70** [comment]
Yes, good catch -- #4484 fixes it. Users have to call `quantum_` explicitly to see the beat discontinuity. I'll close this one.

**Comment by brianlheim** [comment]
cool, thanks again!
