### ISSUE TITLE
Help system crashing SC(Nvim) since 3.10.1

### ISSUE THREAD

**Issue by madskjeldgaard** [supercollider/supercollider#4403]
Hey guys

Something strange started happening in SC 3.10.1 which is still going on in 3.10.2 for us who don't use the SCIDE, particularly SCNvim. 

When I look up something in the help system once, it works fine.

If I keep the help window open and look up a second class, SuperCollider crashes.
If I on the other hand close the help window before looking up a second class, SuperCollider is fine.

Downgrading my SC to 3.10.0 solves the problem. 

## Environment

* SuperCollider version: 3.10.2
* Operating system: MacOS 10.14.4
* Other details (Qt version, audio driver, etc.): SCNvim

## Steps to reproduce
Open NVIM and SCNvim with a scd file.
Write a class name (SinOsc for example)
Look it up (using shift-K) in the help system
Do not close the help file window but keep it open.
Return to NVIM and look up another class.
Boom: Crash.

**Comment by snappizz** [comment]
thanks for the report. does #4267 fix this?

**Comment by davidgranstrom** [comment]
@snappizz Can confirm that #4267 fixes the issue, the HelpBrowser no longer hangs. I got this printout when starting the HelpBrowser the first time, that you might want to know about:
```
QObject::connect: No such slot QtCollider::WebView::onRenderProcessTerminated(RenderProcessTerminationStatus, int)
```
