### ISSUE TITLE
Cmd + [´] instantly kills 3.10.2 on OSX (Swedish keyboard layout).

### ISSUE THREAD

**Issue by lukiss** [supercollider/supercollider#4417]
## Environment

* SuperCollider version: 3.10.2 (3.10.2)
* Operating system: OS X 10.11.6 

Macbook Pro, Swedish keyboard.

## Steps to reproduce

Boot Computer.
OpenSupercollider.
press Cmd + [ ´ ] 

Instant Crash

https://gist.github.com/lukiss/2aa13c7f09bb1a27f65553e30fc319b3

(My first issue ever on GitHub, so please be gentle if failed to file this correctly)

**Comment by redFrik** [comment]
same crash here.  (macOs 10.12.6 - swedish keyboard)
also it doesn't happen under sc3.9.3 nor under sc3.8.0

**Comment by jamshark70** [comment]
Stack trace from the console?

**Comment by gusano** [comment]
@jamshark70 there's a link to the full backtrace in the issue description

**Comment by jamshark70** [comment]
D'oh! Ok, my mental filter wasn't processing links at that time. Sorry for the noise.

**Comment by jpburstrom** [comment]
I can reproduce the crash on the compiled 3.10.2 release, but if I compile it myself (3.10.2 834c036d3) it doesn't crash. Maybe due to a different Qt version? The released version has Qt 5.9.1, while I compiled my own with Qt 5.12.3.

Maybe a simple fix is to upgrade the Qt version for the next release?

**Comment by dyfer** [comment]
@lukiss @jpburstrom does this issue still occur with the current release (3.12.x)?

**Comment by jpburstrom** [comment]
@dyfer No, this is no longer an issue on my computer (current release, 3.12.2). I think this could be closed!
