### ISSUE TITLE
Supernova doesn't guarantee OSC message ordering

### ISSUE THREAD

**Issue by Spacechild1** [supercollider/supercollider#4424]
Supernova has actually two NRT queues which are performed on different threads: 
1) the "system" thread for asynchronous tasks
2) the "io" thread for outgoing OSC messages.

While simply commands like /b_info send the reply on the "io" thread, asynchronous commands send the `/done` message (in stage 4) on the "system" thread, mostly because they have to finish some work (e.g. freeing memory).

In practice this can lead to various race conditions, e.g.:
* `/synced` sent *before* `/done`
* `/b_info` (from a `/b_query` completion message) sent *after* `/done`

See the following discussions:

https://www.listarc.bham.ac.uk/lists/sc-dev/msg59118.html
https://www.listarc.bham.ac.uk/lists/sc-dev/msg59108.html

---

I see three solutions:

1) Always send `/done` messages on the io thread
If this works as expected, it should be the most elegant solution as it keeps the advantage of having a dedicated io thread (so that long asynchronous commands don't block synchronous commands or node replies)

2) Only keep a single NRT thread
This means we get the same design as scsynth and don't run into any race conditions. Note that the FIFO must be multi-producer because triggers/node replies might be sent from RT helper threads.

3) Only keep the `io_interpreter` for client notifications which are sent autonomously from UGens, e.g. node replies and triggers, so they are not blocked by long asynchronous tasks.
The question is what to do with Node state messages (e.g. '/n_end'). One the one hand, they might be sent as the result of a completion message and should therefore go to the 'system_interpreter'; on the other hand, they might be sent from RT helper threads via plugin interface methods (`done_action`, `node_end`, `node_set_run`) and should therefore go to the thread-safe 'io_interpreter'.

Here's a PR which implements 1): https://github.com/supercollider/supercollider/pull/4460

**Comment by Sciss** [comment]
I think that, no matter how the code is restructured, the outcome should be that we have a unit test with the kind of scenario from the original report (`/b_allocRead` with synchronous completion message (`/b_query`) and subsequent `/sync`) that ensures it matches scsynth's order (which I would say constitutes the "spec"). 2c
