### ISSUE TITLE
SimpleNumber:series can overshoot its last value

### ISSUE THREAD

**Issue by mtmccrea** [supercollider/supercollider#4452]
## Environment

* SuperCollider version: SC develop at 7227a4d2d
* Operating system: macOS 10.14

## Steps to reproduce

This fixes a bug wherein `SimpleNumber:series` can overshoot its last value if the step is specified as a `float` and does not evenly divide into the range of the series.

The problem is illustrated here:

```supercollider
(0, 39952.0 .. 958845).last
// -> 958848.0 // overshoots 'last' value
(0, 39952   .. 958845).last
// -> 918896   // int type stops short of 'last', as expected
(0, 2.00001 .. 8).last
// -> 8.0004   // overshoots when step is near an even division
(0, 3.0 .. 8.0).last
// -> 6.0      // otherwise stops short of the 'last' value
```

## Expected vs. actual behavior

I would expect all returned values to be within the range of `first` and `last`, with the `returnedArray.last <= last`.

The problem is here:
https://github.com/supercollider/supercollider/blob/7227a4d2d3b1d37273815245ced1f4e71b87da41/lang/LangPrimSource/PyrMathPrim.cpp#L865
Where it looks like the algorithm may have been just copied from the commented-out `sclang` method it replaced:
https://github.com/supercollider/supercollider/blob/7227a4d2d3b1d37273815245ced1f4e71b87da41/SCClassLibrary/Common/Math/SimpleNumber.sc#L616-L624

If it's agreed this is is in fact a bug, I have a PR ready to go.

**Comment by snappizz** [comment]
good catch! i wonder why on earth it was written that way in the first place.
