### ISSUE TITLE
Ndef.copy not copying fadeTime

### ISSUE THREAD

**Issue by madskjeldgaard** [supercollider/supercollider#4458]
## Environment

* SuperCollider version: 3.10.0
* Operating system: MacOS
* Other details (Qt version, audio driver, etc.):

## Steps to reproduce

```supercollider
Ndef('a').fadeTime_(1);
Ndef('a').copy('b');
Ndef('b').fadeTime.postln;// ->0.02
```

## Expected vs. actual behavior
Expected it to copy fadeTime as well as internal state.

**Comment by madskjeldgaard** [comment]
This seems like an easy fix (by adding `this.fadeTime = proxy.fadeTime` to the copyState method of NodeProxy. But I just want to make sure it's not a bug and not a feature before I submit a PR on that account :)

**Comment by telephon** [comment]
Please submit a PR, it's an oversight! It would be good if we had unit tests for copying, do you think you could write one? Otherwise I can do it.

**Comment by madskjeldgaard** [comment]
> Please submit a PR, it's an oversight! It would be good if we had unit tests for copying, do you think you could write one? Otherwise I can do it.

I would love to do a PR. It would be a nice first proper PR for me to do. I'm not sure about the UnitTesting. I've only done basic things with it before but I'd like to learn so can I maybe give it a shot in the PR and then we discuss it there?

**Comment by telephon** [comment]
Yes, the best thing is to do it step by step! Please go ahead and try, of you have questions, let me know...

**Comment by madskjeldgaard** [comment]
fixed by https://github.com/supercollider/supercollider/pull/4701
