### ISSUE TITLE
clang-format: format vs. lint missed whitespace case

### ISSUE THREAD

**Issue by mtmccrea** [supercollider/supercollider#4464]
## Environment

* SuperCollider version: c565bc859dc503392c3cfc1709458bd61f59506e (forked fairly recently from `develop`)
* Operating system: macOS 10.14.5

## Steps to reproduce

Discovered in #4454. In commit c565bc859dc503392c3cfc1709458bd61f59506e you'll see there was a line with auto-indent spaces at the beginning but the line was otherwise empty. At this point, running `clang-format` will **not** remove this whitespace. However it is caught by the linter:
```
-> python3 ../tools/clang-format.py lint
--- lang/LangPrimSource/PyrMathPrim.cpp	(before formatting)
+++ lang/LangPrimSource/PyrMathPrim.cpp	(after formatting)
@@ -867,7 +867,7 @@
         } else {
             size = (int)((last - first) / step) + 1;
         }
-        // << THERE ARE SPACES HERE
+
         if ((size < 1) || ((step >= 0) && (last < first)) || ((step <= 0) && (last > first))) {
             post("prSimpleNumberSeries: arguments do not form an arithmetic progression:\n\tfirst: %f, step: %f, last "
                  "%f\n",
```
So if you run
```
-> python3 ../tools/clang-format.py format
```
you'll expect that if you then submitting your PR, you should clear the CI build stage. But it's caught when CI lints the file.

## Expected vs. actual behavior
I would expect that `lint` and `format` would analyze and correct the same formatting, respectively.

**Comment by jrsurge** [comment]
Is this issue related to the following?
https://github.com/supercollider/supercollider/issues/4428#issuecomment-498010693

**Comment by brianlheim** [comment]
I can't reproduce this, but I'm not sure I understand what exactly you did. Can you please come up with clear steps to reproduce?

**Comment by mtmccrea** [comment]
I'm having trouble reproducing now as well. I think what might have happened is that it was committed before actually running the format. So when it broke CI, I went back to try to format it, but there were not staged commits so the format didn't actually touch any files. So I think I just didn't realized that the file had to be changed before format would run on it again. So this could be just a workflow flub. In hindsight this makes sense because format presumably uses git history to see what files have changed and only check those.

The line in question is line 870 in `PyrMathPrim.cpp`. If your curious, you could checkout 41348515378a8ea5d8a90ede402e4b563c14da5a and run the formatting, but basically`format.py` doesn't post any output about what it touched, so it isn't obvious if there were no changes. Is it possible for there to be some minimal output about what was/wasn't don't by format?

**Comment by mtmccrea** [comment]
Actually I was able to reproduce it:
checkout: 1a2d75153786dc391f75c9fdfa336e7c918dfc7f
Have a look in `PyrMathPrim.cpp`, line **870**. There are floating spaces that should be formatted out.
Now, on line **873** there's also a format violation, that will be caught by formatting. 
So just touch line, **873**, say, add a space at the beginning.
Formatting will make the change that you see in 41348515378a8ea5d8a90ede402e4b563c14da5a.
Note that despite correcting lines **816-818**, **873** is untouched. 
At this point we assume format has worked, you save and commit, and it will break CI on line **873**.

**Comment by mtmccrea** [comment]
FWIW, I'm using Xcode, but running formatting from the command line, on account of the `format` build target not working for me.

**Comment by mtmccrea** [comment]
> Is this issue related to the following?
> [#4428 (comment)](https://github.com/supercollider/supercollider/issues/4428#issuecomment-498010693)

Note sure... as I'm not sure the error that @snappizz is referring to:
>found a bug in tools/clang-format.py :( turns out it throws an error if it encounters a commit in the branch that makes only whitespace changes.
The branch has more than whitespace changes.

**Comment by brianlheim** [comment]
Sorry, I'm not seeing how this is unexpected behavior. The script usage instructions say:

> 2. `format` will apply formatting rules to the diff between working directory and given commit

@mtmccrea , in this comment (https://github.com/supercollider/supercollider/issues/4464#issuecomment-505588951), you say you've only touched line 873 before running format, right? Then line 870 isn't part of the diff, and there is no guarantee that it will be touched by clang-format. In fact, you should expect it not to. If you want to format your entire branch, you could use, for instance, `tools/clang-format.py format develop`.

**Comment by mtmccrea** [comment]
> line 870 isn't part of the diff, and there is no guarantee that it will be touched by clang-format. In fact, you should expect it not to.

Thanks for the clarification. I was relying on the instruction [wiki's descriptions](https://github.com/supercollider/supercollider/wiki/Cpp-formatting-instructions#cmake-targets) for what each command does (it's odd to me that this is in the "CMake targets" section), which varies slightly from the usage instructions (which I didn't know about). The difference isn't significant at first glance, but it lacks just enough detail for the easily-confused people (me) and those who want to use it like a black box 😉.

Now I see there's reference to "more information" and a command at the end of [this paragraph](https://github.com/supercollider/supercollider/wiki/Cpp-formatting-instructions#possible-workflows-and-scripts). Maybe the list of command descriptions should just be identical to the usage instructions? I hope this doesn't come off as too nitpicky, but as someone that is unfamiliar with this I feel like between installation and usage I don't know where exactly to go for specific problems.

Thanks for the clarification. Please let me know if this is accurate:

- `lint`/`format` do their work **only on uncommited** changes in your working directory.
  - _unless_ you pass a commit as an argument, in which case it will run the process on all changes (committed or not) after the specified commit.
  - if you instead pass a **branch** as the argument, the process will be run on all changes that have happened since your branch diverged from the specified branch.

Sorry to get off track with comments on documentation, I'll try to incorporate this into some of the revisions I'm planning to suggest.


 is that there's an argument to `format` and `lint` that is either a commit to compare

**Comment by mtmccrea** [comment]
BTW, now that I've gotten the hang of this, it's all straightforward. I'm just lingering on the details with the hope that it might prove useful for revising the docs.

Thanks again for the great work on the formatting undertaking!
