### ISSUE TITLE
Moving CONTRIBUTING.md and DEVELOPING.md to wiki pages

### ISSUE THREAD

**Issue by snappizz** [supercollider/supercollider#4480]
## Motivation

our developer documentation is split in a few different places:

- [project wiki](https://github.com/supercollider/supercollider/wiki)
- [CONTRIBUTING.md](https://github.com/supercollider/supercollider/blob/develop/CONTRIBUTING.md) -- a guide for getting started with SC dev
- [DEVELOPING.md](https://github.com/supercollider/supercollider/blob/develop/DEVELOPING.md) -- a more comprehensive guide to the development process
- a few pages on [the website](https://supercollider.github.io/pages)

this fragmentation is confusing and makes the docs harder to edit effectively, especially with the in-repo markdown files cross-referencing the project wiki.

a quick check of the history of CONTRIBUTING.md and DEVELOPING.md shows that they are not often edited compared to the wiki pages. i attribute this to the amount of time it takes to open up a pull request and go through the review process. it's just more convenient to edit the wiki directly, and that's why most of our dev docs have gone there.

furthermore, development processes are not really specific to the SC version, so keeping them embedded in the git repo history isn't necessary.

this is motivated by recent efforts to help with onboarding new code reviewers, where there's been a lot of confusion due to lack of project documentation. the first step is to make them more convenient to write and edit.

## Plan for Implementation

i will do the following:

- [x] migrate all project docs to the wiki
- [x] edit CONTRIBUTING.md and DEVELOPING.md to point to the new location
- [x] modify the issue, pull request templates, README, and website to also point to the new location

**Comment by brianlheim** [comment]
> a quick check of the history of CONTRIBUTING.md and DEVELOPING.md shows that they are not often edited compared to the wiki pages. i attribute this to the amount of time it takes to open up a pull request and go through the review process. it's just more convenient to edit the wiki directly, and that's why most of our dev docs have gone there.

:+1:

> furthermore, development processes are not really specific to the SC version, so keeping them embedded in the git repo history isn't necessary.

:+1:

> migrate all project docs to the wiki

what is included in "all project docs"?

other than that all sounds good to me, thanks!!

**Comment by snappizz** [comment]
> what is included in "all project docs"?

DEVELOPING.md, CONTRIBUTING.md, and anything worth salvaging from the "development" section of the supercollider website

**Comment by brianlheim** [comment]
awesome, let's do ih

**Comment by snappizz** [comment]
sick

**Comment by snappizz** [comment]
alright check it out, i moved CONTRUBING.md to become the "Guide for New Contributors" and broke off the part about pull requests since it was getting long. some further revisions are necessary, but at least they're way more convenient to edit now: https://github.com/supercollider/supercollider/wiki

DEVELOPING.md is now the "Developer Reference". it is way too long and i intend to split it into separate pages.

**Comment by brianlheim** [comment]
thanks @snappizz!

Guide for New Contributors sounds good to me. As we discussed on slack I agree it would be a good idea to break up the developer reference page into a couple subpages and then reference them from the main wiki page, which will then become a kind of overview of guides and references.

let's leave this issue open until contributing.md and developing.md have been updated.

**Comment by snappizz** [comment]
#4503
