### ISSUE TITLE
TCP connection to the server is not properly closed when recompiling library

### ISSUE THREAD

**Issue by dyfer** [supercollider/supercollider#4482]
## Environment

* SuperCollider version: 3.10
* Operating system: macOS 10.13
* Other details (Qt version, audio driver, etc.):

## Steps to reproduce

```supercollider
// 1. check initial state
thisProcess.recompile;
"lsof -nP -iTCP:57110".unixCmd; //check who's listening on default scsynth's port 57110 on TCP
// should give no output message


// 2. boot scsynth on tcp
(
Server.scsynth;
s.options.protocol_(\tcp);
s.waitForBoot({
	"lsof -nP -iTCP:57110".unixCmd;
})
)
```
```
// output:
COMMAND   PID   USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
sclang  91167 marcin   88u  IPv4 0x25d72d5c1ddb305d      0t0  TCP 127.0.0.1:61168->127.0.0.1:57110 (ESTABLISHED)
scsynth 91200 marcin   12u  IPv4 0x25d72d5c1d4529bd      0t0  TCP *:57110 (LISTEN)
scsynth 91200 marcin   13u  IPv4 0x25d72d5c1e68005d      0t0  TCP 127.0.0.1:57110->127.0.0.1:61168 (ESTABLISHED)
```
```supercollider
// 3. recompile (without quitting server first)
thisProcess.recompile;
// then repeat step 2.
```
```
//output:
COMMAND   PID   USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
sclang  16145 marcin   71u  IPv4 0x25d72d5c1b0639bd      0t0  TCP 127.0.0.1:52912->127.0.0.1:57110 (CLOSE_WAIT)
sclang  16145 marcin   72u  IPv4 0x25d72d5c0b6c39bd      0t0  TCP 127.0.0.1:52977->127.0.0.1:57110 (ESTABLISHED)
scsynth 17366 marcin   13u  IPv4 0x25d72d5c310e49bd      0t0  TCP *:57110 (LISTEN)
scsynth 17366 marcin   20u  IPv4 0x25d72d5c3845831d      0t0  TCP 127.0.0.1:57110->127.0.0.1:52977 (ESTABLISHED)
scsynth 17366 marcin   71u  IPv4 0x25d72d5c1b0639bd      0t0  TCP 127.0.0.1:52912->127.0.0.1:57110 (CLOSE_WAIT)
```
```supercollider
// repeat 3. and 2.
```
```
COMMAND   PID   USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
sclang  91167 marcin   88u  IPv4 0x25d72d5c1ddb305d      0t0  TCP 127.0.0.1:61168->127.0.0.1:57110 (CLOSE_WAIT)
sclang  91167 marcin   92u  IPv4 0x25d72d5c303bd5dd      0t0  TCP 127.0.0.1:61203->127.0.0.1:57110 (CLOSE_WAIT)
sclang  91167 marcin   93u  IPv4 0x25d72d5c1edbd31d      0t0  TCP 127.0.0.1:61243->127.0.0.1:57110 (ESTABLISHED)
scsynth 91278 marcin   12u  IPv4 0x25d72d5c1e6809bd      0t0  TCP *:57110 (LISTEN)
scsynth 91278 marcin   13u  IPv4 0x25d72d5c2194fc7d      0t0  TCP 127.0.0.1:57110->127.0.0.1:61243 (ESTABLISHED)
scsynth 91278 marcin   88u  IPv4 0x25d72d5c1ddb305d      0t0  TCP 127.0.0.1:61168->127.0.0.1:57110 (CLOSE_WAIT)
scsynth 91278 marcin   92u  IPv4 0x25d72d5c303bd5dd      0t0  TCP 127.0.0.1:61203->127.0.0.1:57110 (CLOSE_WAIT)
```
Moreover, supernova will not boot at all when there are dangling close_wait connections:
```supercollider
s.quit;
(
Server.supernova;
s.options.protocol_(\tcp);
s.waitForBoot({
	"lsof -nP -iTCP:57110".unixCmd;
})
)
```
However, the connection is properly closed when quitting the server without recompiling.
```supercollider
thisProcess.platform.killAll("sclang"); //clean previously opened connections
// afterwards manually boot interpreter

// 1. check who's listening
"lsof -nP -iTCP:57110".unixCmd;
// should give no output message


// 2. boot scsynth on tcp
(
Server.scsynth;
s.options.protocol_(\tcp);
s.waitForBoot({
	"lsof -nP -iTCP:57110".unixCmd;
})
)

// 3. quit the server
s.quit;

// 4. check open ports again
"lsof -nP -iTCP:57110".unixCmd;
// should give no output

```

## Expected vs. actual behavior

I think that TCP connections should be closed when recompiling the library. 
This was observed while reviewing #4435.

**Comment by miguel-negrao** [comment]
Would a possible way to fix this be that prNetAddr_Connect would add the created SC_TcpClientPort to a vector (stored is a global variable ?) and that at recompile time all ports in the vector would be closed ?

Or from sclang side, is it possible to register a function to do something before recompile ? If so, maybe it would work to register a function which calls NetAddr.disconnectAll ?

**Comment by jamshark70** [comment]
> Would a possible way to fix this be that prNetAddr_Connect would add the created SC_TcpClientPort to a vector (stored is a global variable ?)

It already does that (if it didn't, there could be no `disconnectAll`).

> Or from sclang side, is it possible to register a function to do something before recompile ? If so, maybe it would work to register a function which calls NetAddr.disconnectAll ?

NetAddr could implement `*doOnShutDown` to call disconnectAll and then its `"initClass` would do `ShutDown.add(NetAddr);`.

**Comment by miguel-negrao** [comment]
> > Would a possible way to fix this be that prNetAddr_Connect would add the created SC_TcpClientPort to a vector (stored is a global variable ?)
> 
> It already does that (if it didn't, there could be no `disconnectAll`).

I meant on the c++ side. 
> 
> > Or from sclang side, is it possible to register a function to do something before recompile ? If so, maybe it would work to register a function which calls NetAddr.disconnectAll ?
> 
> NetAddr could implement `*doOnShutDown` to call disconnectAll and then its `"initClass` would do `ShutDown.add(NetAddr);`.

This seems  like the simplest approach.

**Comment by dyfer** [comment]
Thank you for your responses.

Language approach seems easiest for sure. Do you think this is the best way to proceed, or should c++ side be investigated for a more "proper" approach?

**Comment by miguel-negrao** [comment]
I think in this case, since all that is needed is already present in sclang, I think the proper approach would be to do it in there...

**Comment by dyfer** [comment]
While working on a fix, I noticed that we are actually [failing to store a list of tcp connections](https://github.com/supercollider/supercollider/blob/develop/SCClassLibrary/Common/Control/NetAddr.sc#L143) which happens when the disconnectHandler is `nil`.
`NetAddr.disconnectAll` is actually [called from Kernel.sc](https://github.com/supercollider/supercollider/blob/develop/SCClassLibrary/Common/Core/Kernel.sc#L224) anyway. So the proper fix is to make `NetAddr` add connections to the connection list even if the disconnect handler is `nil`. PR to follow.
