### ISSUE TITLE
scsynth's network socket should bind to 127.0.0.1 by default rather than 0.0.0.0

### ISSUE THREAD

**Issue by snappizz** [supercollider/supercollider#4496]
## Environment

* SuperCollider version: 3.10.2

## Description

supercollider is intended to be run on local machines, and security is not really a top priority for the platform. however, right now, scsynth binds its UDP or TCP socket to `0.0.0.0` by default:

https://github.com/supercollider/supercollider/blob/develop/server/scsynth/scsynth_main.cpp#L140

which means that it listens on all interfaces. usually this means that anyone in your local network can mess with scsynth, which isn't what 99% of users want. even laptop ensembles tend to have everyone run their own client/server and most of the communication happens between clients.

simply changing this to `127.0.0.1` will be a more reasonable default configuration. this will not affect most users, but will impact people doing networked clients, who will need to set `-B 0.0.0.0`. see #4497.

disclaimer: i am not really great with network programming, so any insight from someone who knows better would be greatly appreciated!

## Securing an existing supercollider installation

until this is fixed, this hack can secure scsynth by placing it in your startup file:

`Server.program = "scsynth -B 127.0.0.1";`

## What about supernova?

supernova, as far as i can tell, does not support the `-B` flag, so getting supernova up to speed with scsynth is more involved. i'm not personally interested in maintaining supernova anymore, so i can't help with such issues.

**Comment by snappizz** [comment]
UPDATE: at today's dev meeting @jrsurge suggested that this might be the root cause of #4362 and some other permissions issues on Windows.

**Comment by snappizz** [comment]
@joshpar and i have been discussing whether this should go into 3.10.3 or 3.11. it technically constitutes a breaking change for people who rely on the 0.0.0.0 behavior, in particular users of networked servers, and properly fixing #4368 means adding a small new feature.

normally, breaking changes + small new features = delay to 3.11. but this is such an alarming (and embarrassing) security misconfiguration that pushing it into 3.10.3 seems to be the better choice. if anyone feels differently then please let me know.

**Comment by muellmusik** [comment]
I suppose the main thing is that this change is prominently and clearly documented so that people's network music systems don't break mysteriously.

I guess a more complete fix would be an extension of password support to UDP? We've sometimes wondered about the issue of running network music systems on mixed networks. It's not always practical to make your own network, so increased security would be nice.

With that feature you could add another layer of default security by having the lang randomly generating a password at server launch if one is not specified.

**Comment by snappizz** [comment]
@muellmusik yeah for sure -- i'll advertise this change heavily in the changelog and such

closing as this is fixed in #4516
