### ISSUE TITLE
Midi SysEx Message Bug

### ISSUE THREAD

**Issue by jleben** [supercollider/supercollider#45]
[Issue migrated from SourceForge | ID: 1887774 | Submitted by 'nobody']
[http://sourceforge.net/support/tracker.php?aid=1887774]

SuperCollider currently does not receive successfully SysEx messages.
It's hard to give an example since it is dependant of the hardware you use. And using IACDriver for this purpose is not a good idea since it would feed itself again and again for large messages.

Most trials i have done were with a Waldorf MicroQ, from wich i was sending full program dumps of 392bytes each. the MIDIIn.doSysexAction was never triggered and occasionally it crashed.

I made 3 propositions after working on the code (in SC_CoreMidi.cpp file).
After those modifications i was able to receive successfully SysEx messages.
You can find those modifications/suggestions in the dev-list :

http://lists.create.ucsb.edu/pipermail/sc-dev/2008-February/011903.html

Anyway more tests with different machines should be better.

charles a picasso
thelych@gmail.com

**Comment by Sciss** [comment]
apologies for polluting multiple issues with automatic mentions from unrelated commits; I accidentally pushed non-overlapping ScalaCollider branches to my fork of SuperCollider (a wrongly set-url remote). I deleted those branches again, but seems the mentions are still in the ticket system, now pointing to orphaned commits.
