### ISSUE TITLE
Quarks: ext_dependancy vs ext_dependency

### ISSUE THREAD

**Issue by dyfer** [supercollider/supercollider#4502]
[Help for Quark file](https://github.com/supercollider/supercollider/blob/develop/HelpSource/Guides/UsingQuarks.schelp#L257) mentions a category called `ext_dependancy`. FWIW [Wiktionary](https://en.wiktionary.org/wiki/dependancy) indicates `dependancy` to be an archaic form of `dependency`. Not being a native English speaker, I might be missing something. Is `dependancy` a typo or an intended form?

**Comment by snappizz** [comment]
definitely a mistake.

this is why we do things such as code review now, haha

**Comment by dyfer** [comment]
Closed in #4514
