### ISSUE TITLE
sclang: document that 'nil' can't be used as a Dictionary value

### ISSUE THREAD

**Issue by dyfer** [supercollider/supercollider#4521]
## Environment

* SuperCollider version: 3.10
* Operating system: macOS

## Steps to reproduce

```supercollider
d = Dictionary();
d.put(\one, 1);
d.put(\two, "");
d.put(\three, nil); //doesn't add the key

d.keys; // -> Set[ two, one ]
```

## Expected vs. actual behavior

It seems we can't add `nil` to a `Dictionary`.

On one hand it makes sense, since the `Dictionary` will just respond `nil` whether there's an association at a given key or not. However, if the code depends on the keys alone, then one could expect the key to be added even if the value is `nil`.

I'm not sure if this behavior should be fixed or just documented, I'd like others to chime in on that.

Discovered while working on #4518

**Comment by jamshark70** [comment]
I'll suggest against changing this. There is almost certainly user code out there that uses `.put(key, nil)` intentionally to remove the key. If we suddenly stop deleting keys in this case, we have no idea how much code will break.

My vote is to document it.

**Comment by brianlheim** [comment]
This should be documented, it's very reasonable behavior.
