### ISSUE TITLE
project wiki: "git cheat sheet" vs "creating pull requests"

### ISSUE THREAD

**Issue by dyfer** [supercollider/supercollider#4532]
## Motivation

It seems that https://github.com/supercollider/supercollider/wiki/git-cheat-sheet and https://github.com/supercollider/supercollider/wiki/Creating-pull-requests have some overlapping information (e.g. how to keep the repository updated and create pull requests). 

## Description of Proposed Feature

My proposal is that `git cheat sheet` is stripped from the information already present in `creating pull requests` and is more like an actual "cheat sheet". I don't have a strong opinion though, I'm logging this here so we can discuss.

**Comment by snappizz** [comment]
sounds great, feel free to fix 'em

**Comment by brianlheim** [comment]
closing as stale, the wiki is free to edit though :)
