### ISSUE TITLE
Improve our source tarball packaging process

### ISSUE THREAD

**Issue by snappizz** [supercollider/supercollider#4545]
## Motivation

the source .tar.gz and .zip files that github creates on our release page do not include submodules (#1807), so we provide our own tarball uploads using the shell script `package/package` to create a full source package and a more minimal linux-only package. this script has a number of long-standing issues:

- it doesn't run in CI and i, nathan ho, have to manually run it every time. i don't necessarily mind this since i am over here being paid by the hour ($0). however, i definitely have screwed this up and uploaded source tarballs from the wrong branch in the past and people were alarmed when the hashes changed. the supercollider project can be saved from my own blithering ineptitude thanks to the power of computers.
- it requires python 2. there was #2896 but somehow with this recent 3.10.3-rc1 release, i had to switch back to 2 to get it working. shrug emoji. how to enter shrug emoji github

## Description of Proposed Feature

thanks to @dvzrv, sc3-plugins currently has a [nicer packaging script](https://github.com/supercollider/sc3-plugins/blob/master/package/create_package.sh) than core SC. way better code, downloads code from github rather than trying to catch local changes, etc. so i'd like to see our old script gone and replaced with this one. it would need some modifications for the stripped-down linux package.

second, it should run on travis and upload builds automatically on release.

## Plan for Implementation

pretty easy! someone who knows CI processes decently well could probably knock this out in a few hours.

**Comment by dvzrv** [comment]
I can start working on this.

I also noticed some macOS hidden files in the source tarball for 3.11.0:

```
usr/share/SuperCollider/HelpSource/._OldHelpWrapper.html
usr/share/SuperCollider/HelpSource/._Search.html
usr/share/SuperCollider/HelpSource/._Browse.html
usr/share/SuperCollider/HelpSource/._BrokenLink.html
usr/share/SuperCollider/HelpSource/Other/._Licensing.html
usr/share/SuperCollider/HelpSource/Other/._HelpDocsLicensing.html
usr/share/SuperCollider/sounds/._SinedPink.aiff
usr/share/SuperCollider/sounds/._a11wlk01.wav
usr/share/SuperCollider/sounds/._a11wlk01-44_1.aiff
```

The above should not be there and should be ignore by the cmake installation process!

**Comment by dvzrv** [comment]
This should now be sufficiently improved by #4837 and the updated [git workflow and guidelines wiki page](https://github.com/supercollider/supercollider/wiki/git-workflow-and-guidelines/82ee67fd4c21f277b68e7514aa9e644a431253e4).

As a follow-up we could cleanup and eventually remove the scripts used initially.
