### ISSUE TITLE
ScIDE should not implement `findMethod` (breaks introspection)

### ISSUE THREAD

**Issue by jamshark70** [supercollider/supercollider#4557]
## Environment

* SuperCollider version: 3.10
* Operating system: Ubuntu Studio 18.04

## Steps to reproduce

```supercollider
Class.allClasses.select { |cl| cl.findMethod(\duration).notNil };
```

Error:

```
ERROR: Message 'split' not understood.
RECEIVER:
   nil
ARGS:
   Character 46 '.'
CALL STACK:
	DoesNotUnderstandError:reportError
		arg this = <instance of DoesNotUnderstandError>
... snip ...
	Object:doesNotUnderstand
		arg this = nil
		arg selector = 'split'
		arg args = [*1]
	Meta_ScIDE:findMethod
```

## Expected vs. actual behavior

Expected: `findMethod` is an important introspection method defined by a deep-core class. Its meaning should be consistent for every class, everywhere.

Actual: `ScIDE` overrides the definition with a different meaning. So it is really inconvenient to query a class whether it implements a given method (because now you have to check `class === ScIDE`).

ScIDE should call its method `findMethodForSelector` or perhaps `findMethodForText`.

**Comment by jamshark70** [comment]
Upon further investigation -- I cannot find anywhere in SC source code or the class library that calls `ScIDE.findMethod`. It was committed with the first version of the autocompleter (https://github.com/supercollider/supercollider/commit/0b5c739c968e96350b4233243d6c67561b200b73) but, if I comment the method out, all autocompletion features still function normally.

It appears to be vestigial. So, I think, delete it: no benefit, causes confusion, breaks core class.

**Comment by brianlheim** [comment]
i agree this can be deleted, and as it's an obscure method with no documentation, deprecation shouldn't be needed either
