### ISSUE TITLE
Sc unresponsive after install

### ISSUE THREAD

**Issue by ronherrema** [supercollider/supercollider#4564]
## Environment

* SuperCollider version: 3.10.3
* Operating system: Windows 10 (version 1803)
* Other details (Qt version, audio driver, etc.): 

## Steps to reproduce

Install SC and attempt to run

## Expected vs. actual behavior

Post window shows the following but then becomes completely unresponsive, regardless of command given. Interpreter is 'active', server shows 0% usage:

compiling class library...
	Found 833 primitives.
	Compiling directory 'C:\Program Files\SuperCollider-3.10.3\SCClassLibrary'
	numentries = 813877 / 11974982 = 0.068
	5399 method selectors, 2218 classes
	method table size 13098592 bytes, big table size 95799856
	Number of Symbols 12055
	Byte Code Size 362970
	compiled 318 files in 1.08 seconds

Info: 2 methods are currently overwritten by extensions. To see which, execute:
MethodOverride.printAll

compile done
localhost : setting clientID to 0.
internal : setting clientID to 0.
Class tree inited in 0.01 seconds

*** Welcome to SuperCollider 3.10.3. *** For help press Ctrl-D.

**Comment by geoffroymontel** [comment]
Hello @ronherrema 
Can you check if the server starts after a 60s wait ?
Is it the same issue as https://github.com/supercollider/supercollider/issues/4368 ?

**Comment by ronherrema** [comment]
@geoffroymontel The server does not start after 60s. The server never starts. I tried installing version 3.9.3, but the behaviour is the same. I also tried installing the 32 bit version, which also does the same thing.

**Comment by snappizz** [comment]
@ronherrema when you execute code in a document window, does it get highlighted when you attempt to execute it?

**Comment by ronherrema** [comment]
@snappizz yes when I execute it gets highlighted. And yes, I am choosing Server ~> Boot Server.

**Comment by ronherrema** [comment]
The idea that this is related to a Windows update seems likely, as my Windows laptop always ran SC with no problems, but now does not, after updating through auto-update.

**Comment by geoffroymontel** [comment]
OK ! Maybe you can try to add the scsynth.exe *process* to Windows Defender exclusion list, as described in #4368

**Comment by ronherrema** [comment]
Apologies - my laptop version actually seems to be working now :-/ but I can try adding scsynth.exe to Defending in any case on the other machines.

**Comment by ronherrema** [comment]
I can verify that this turned out to be a duplicate of issue [#4214](https://github.com/supercollider/supercollider/issues/4214)

**Comment by geoffroymontel** [comment]
Thanks for your reply ! I'm closing this issue then as it is a duplicate.
