### ISSUE TITLE
Buttons do not react when they are on different windows

### ISSUE THREAD

**Issue by Xon77** [supercollider/supercollider#4567]
## Environment

* SuperCollider version: 3.10.3
* Operating system: Mac 10.14.6
* Other details (Qt version, audio driver, etc.): Qt 5.13 and the preferences in trackpad should be "press to click".

## Steps to reproduce

```supercollider
(
w = Window.new("1", Rect(0,0,250,100));
x = Window.new("2", Rect(250,0,250,100));

a = Button(w, Rect(20, 20, 200, 30))
.states_([
	["there is suffering", Color.black, Color.red],
	["the origin of suffering", Color.white, Color.black],
]).action_({ arg butt; butt.value.postln });

b = Button(x, Rect(20, 20, 200, 30))
.states_([
	["there is suffering", Color.black, Color.red],
	["the origin of suffering", Color.white, Color.black],
]).action_({ arg butt; butt.value.postln });

w.front;
x.front;
)
```

## Expected vs. actual behavior

Expected behavior (SC 3.10.3 RC1) : The buttons should react immediately when by switching alternatively between the 2 windows you press on the buttons. The behaviour is ok when you click on it. The problem is by pressing. 

Actual behavior (SC 3.10.3) : The buttons never react immediately when by switching alternatively between the 2 windows you press on the buttons. You need to press twice to act on the buttons (the 1rst press seems to get the focus on the window). Even when you press on a button within the same window, sometimes (very rare) the button do not react.

This issues comes with the jump with Qt 5.13.
Theres was no issue with Qt 5.9 which was in SC 3.10.3 RC1

**Comment by brianlheim** [comment]
Will look into it, but it sounds like a problem with upstream. We are not going to downgrade our Qt version as this fixed a known issue.

**Comment by jamshark70** [comment]
Adding macOS label. This definitely isn't the case in Linux (at least not for XFCE window manager) and I'm pretty sure it isn't the case in Windows either.

FWIW I've seen the same behavior in macOS Finder windows: e.g., to eject removable storage on my Linux machine, even if the file browser is not focused, I click only once on the eject icon. MacOS requires two clicks: once to focus the Finder window, and another to eject. It's quite annoying but the fact that it happens in other parts of macOS suggests that it might be an Apple interface design spec that Qt was not respecting (speculation there).

Maybe there's a system preference for it?

**Comment by Xon77** [comment]
To me, it is a bug within Qt or the interfacing with Qt when preferences in trackpad are on "press to click" on Mac. With Qt 5.13, it happens to me sometimes that the buttons are even not switched to their new states on the same window : The button is pressed down, but not up again.
With different windows, the problem is always there and was not present before Qt 5.13 on Mac.
The problem is also more present with some variations like RoundButton or SmoothButtom from wslib.

**Comment by Xon77** [comment]
I don't know why exactly... but the Buttons react correctly with the 3.10.4 beta version.
This issue is now solved and can be closed to me.

**Comment by joshpar** [comment]
Thanks for verifying!
