### ISSUE TITLE
MainMenu issue

### ISSUE THREAD

**Issue by dyfer** [supercollider/supercollider#4568]
## Environment

* SuperCollider version: 3.10.3
* Operating system: macOS 10.13
* Other details (Qt version, audio driver, etc.):

## Steps to reproduce
This is an example from the `MainMenu` help file:
```supercollider
(
~show = MenuAction("Show Window", {
    ~window ?? {
        ~window = TextView().string_("Here it goes!").minSize_(300@200);
        ~window.onClose = { ~window = nil };
        ~window.front;
    }
});
~hide = MenuAction("Hide Window", {
    ~window !? {
        ~window.close();
        ~window = nil;
    }
});

MainMenu.register(Menu(~show, ~hide).title_("My Quark"), "Quarks", "My Quark")
)
```

## Expected vs. actual behavior

I'm getting the following error:
```
ERROR: Message 'detectIndex' not understood.
RECEIVER:
   nil
(...)
```
The menu is not created.
I haven't investigated further, wanted to quickly test `MainMenu` and the example didn't work. At some point it _has_ worked (not sure in what conditions), but after recompiling the library it never works for me.

**Comment by jrsurge** [comment]
The release notes for 3.10.2 mentions something about this:

"Due to immature development status and lack of cross-platform compatibility, MainMenu is no longer enabled by default (#4285). It can be re-enabled by running ```MainMenu.initBuiltInMenus``` (add this to your startup file to permanently re-enable). The API for MainMenu is subject to change in the future."

Is this related?

**Comment by dyfer** [comment]
Thanks @jrsurge 
Indeed, running `MainMenu.initBuiltInMenus` first gets rid of the error. Not sure if this should be fixed now or if we need to wait on advancing the discussion about `MainMenu` in general. IMO it would be good to discuss it again, including possible cross-platform solutions. On platforms/window managers without the concept of main menu at the top of the screen, menus with applicable functionality usually exist inside the application's window(s). I think it would be great to be able to create these as well...

**Comment by muellmusik** [comment]
If there's no objection I'd like to put forward a simple PR to fix this bug. https://github.com/supercollider/supercollider/commit/423a54e35f38ca22dea4cfd2a6b7b2f69e78a175 as I understand it was meant to disable the default menu set, not break MainMenu. Personally I don't normally want File, Quarks, etc. created in any case, and I'd guess many users feel the same. 

The fix would be very simple just add this:

```
*initClass { 
		systemMenus = [];
		registered = List();
	}
```

I understand there is some desire to perhaps rethink this, but this has lain broken for for almost two years, and I don't think there's any reason why people should continue to use a workaround to keep using functionality which in fact predates the IDE. We can rework later if someone takes that up.

**Comment by jrsurge** [comment]
I was under the impression that this was done to buy us time to fix a memory leak (whose status I'm not sure of)?
https://github.com/supercollider/supercollider/issues/4268
https://github.com/supercollider/supercollider/issues/4288

**Comment by muellmusik** [comment]
Hey @jrsurge! That is indeed a super-weird problem. IIUC my proposed change will not reintroduce that issue however, as it does not add the dependants again. It just makes the workaround in 423a54e slightly less disruptive.

#4268 and #4288 aside I don't think it was a great choice to automatically add Server menus etc in any case. People may not want them, and it's dumb to make them remove them. So it's also a slight improvement in design, IMO anyway, and I'd suggest leaving it this way once #4288 is fixed.

**Comment by muellmusik** [comment]
Any last objections or should I put forward a PR?

**Comment by jrsurge** [comment]
Thanks for looking into this @muellmusik - no objections from me if we're happy it won't cause issues, also happy to be put down as a reviewer for it

**Comment by muellmusik** [comment]
I've been testing it for some time here with the server booted, both with or without a menu added, and I can't see any increase in memory over time, which is what I'd expect since neither creates the server menus.

TBH though I couldn't see any memory leak even after calling initBuiltInMenus! I don't know if it's possible that this has been inadvertently fixed or something. This is on SC 3.11.0.

Perhaps the best thing is just to do the PR and then others can test.

**Comment by muellmusik** [comment]
> also happy to be put down as a reviewer for it

Ta!
