### ISSUE TITLE
Unable to load library 'scsynth': Native library (darwin/libscsynth.dylib) not found in resource path

### ISSUE THREAD

**Issue by theronic** [supercollider/supercollider#4577]
For more context, see [StackOverflow question](https://stackoverflow.com/q/57909082/198927).
 
## Environment

* SuperCollider version: 3.10.3
* Operating system: macOS Mojave 10.14.5
* Other details (Qt version, audio driver, etc.): n/a

## Steps to reproduce

```
brew cask install supercollider
lein new sc-test
# add dependency [overtone "0.10.6"]
```

Trying to use Overtone from a Clojure REPL:

```clojure
(require 'overtone.live)
=> Starting nREPL server...
--> Loading Overtone...
java.lang.UnsatisfiedLinkError: Unable to load library 'scsynth': Native library (darwin/libscsynth.dylib) not found in resource path 
...
Sep 13, 2019 8:03:54 PM clojure.lang.Reflector invokeMatchingMethod
WARNING: 
Sep 13, 2019 8:03:55 PM clojure.lang.Reflector invokeMatchingMethod
SEVERE: Unable to load native libs c and scsynth. Please try an external server with (use 'overtone.core)
Exception in thread "Thread-6" java.lang.NullPointerException
```

I can run `/Applications/SuperCollider.app/Contents/Resources/scsynth` just fine. However, adding `/Applications/SuperCollider.app/Contents/Resources` to PATH does not resolve the issue.

## Expected vs. actual behavior

I expect `scsynth` to be in the path, or that adding `/Applications/SuperCollider.app/Contents/Resources` to PATH should resolve this, but the JVM still complains about finding it. I read README_MACOS.md, but I don't understand what I have to do with paths to fix this behaviour.

**Comment by snappizz** [comment]
hi @theronic! if there's a supercollider homebrew package, it's not something we maintain or support. the correct way to install supercollider is to download the latest release or build it from source.

**Comment by brianlheim** [comment]
@snappizz is right; this should be reported upstream, we do not maintain this formula.
