### ISSUE TITLE
LanguageConfig.store writes to default yaml file even if interpreter is using another one

### ISSUE THREAD

**Issue by dyfer** [supercollider/supercollider#4595]
## Environment

* SuperCollider version: 3.10.3
* Operating system: macOS 10.13
* Other details (Qt version, audio driver, etc.):

## Steps to reproduce

1. in the IDE, open preferences -> interpreter
2. add new configuration file
3. save changes
4. reboot interpreter
then:

```supercollider
LanguageConfig.addIncludePath("/any/path");
LanguageConfig.store; //stores in the default sclang_conf.yaml file
```
Reboot the interpreter - the changes are not applied.
## Expected vs. actual behavior

`LanguageConfig.store` by default stores the configuration in the default `sclang_conf.yaml` file, not in the one currently used by the interpreter.

While this is sort of documented:
```
Arguments:
file | Path to the configuration file to store. If the value is nil it defaults to Platform.userConfigDir +/+ "sclang_conf.yaml"
```
I would argue that this is not a desired behavior and that the configuration changes should by default be saved to the file currently used by the language. 

What do others think about this?

**Comment by brianlheim** [comment]
> I would argue that this is not a desired behavior and that the configuration changes should by default be saved to the file currently used by the language.

I agree, but it is a breaking change so if a PR is made it should go into develop. Thanks for catching this!

**Comment by jamshark70** [comment]
Actually, it's a ridiculously easy fix: simply provide a default for the path to store to. LanguageConfig already knows the `currentPath` being used -- it's just that we don't use it here.

```
	*store { |file(LanguageConfig.currentPath)|
		_LanguageConfig_writeConfigFile
		^MethodError("Could not write to file %".format(file.asCompileString), this).throw
	}
```
