### ISSUE TITLE
sclang: add instance method to Document to save a file

### ISSUE THREAD

**Issue by dmartinp** [supercollider/supercollider#4597]
##  Motivation

`Document` currently has many features to control the IDE, such as `Document.new` to open a new document in the IDE. Sometimes, the IDE crashes (not often!!!) and so saving the file could be implemented at the top of one's code to ensure changes aren't lost (maybe?). Personally, I have implemented an automatic git commit upon code evaluation, but this only works if the file has been saved.

## Description of Proposed Feature

To automatically have sclang save the current document, using something like: `Document.current.save`

## Plan for Implementation

This shouldn't take a ton of time. I have limited C++ experience, otherwise, I could do this myself (maybe I will when I get more time!), but maybe someone who knows C++ really well could implement this relatively quickly. I see that in doc_manager.cpp there is a function `handleScLangMessage` but "save" or "saveDocument" is not one of the sclang messages it responds to.

**Comment by jamshark70** [comment]
Sclang, if I'm not mistaken, already has everything you need to implement this.

The Document instance has access to its text. (There's a bug with this in Windows but there's also a back-door way to get the text asynchronously from the IDE -- https://github.com/jamshark70/JITModular/blob/master/JITModPatch.sc#L223 .)

The Document also knows its path.

`File` can write any text to any path.

Put those two together and you get the important part (text saved on disk). This wouldn't necessarily update the document's "saved" state in the interface, but that's gravy.

Btw the IDE, for some years now, has had an auto-backup feature, but I think it has a few minutes between auto-save so it isn't guaranteed to catch everything.

**Comment by dmartinp** [comment]
Yes, this is possible and I do have that implemented. The problem is that `File` will force overwrite the file and the IDE will respond to the file having been changed externally asking to reload, close or ignore the file. Upon which the undo history is lost. 

I guess the option would be to not reload the file into the IDE and just trust that it has been saved anyway. But even the dialog popping up in the IDE every time I run the code is mildly annoying. The IDE can save files, so I see no reason why this can't be exposed to the `Document` class other than that someone who knows the inner workings of the IDE has to take the time to implement it.

**Comment by gusano** [comment]
I would argue that being able to set the interval time for IDE auto-save feature would make more sense.

> I have implemented an automatic git commit upon code evaluation, but this only works if the file has been saved

You might want to take a look at Alberto De Campo `History` class.

**Comment by jamshark70** [comment]
> The problem is that File will force overwrite the file and the IDE will respond to the file having been changed externally asking to reload, close or ignore the file.

That's a good point. I hadn't thought of that.

I think it's a good idea to implement this anyway (even though the IDE has auto-save). Currently we can do just about everything to a Document from the language, except tell the IDE to save it. I can't think of a good reason to maintain this exclusion.

**Comment by muellmusik** [comment]
I'm taking a look at this and will post a PR soon.
