### ISSUE TITLE
Add info about RFCs to project docs

### ISSUE THREAD

**Issue by snappizz** [supercollider/supercollider#4603]
## Motivation

the [new RFC system](https://github.com/supercollider/rfcs) is important to our project's leadership, but currently lacks any visibility or discoverability.

## Description of Proposed Feature

i think a mention of the RFC process would be good in:

- README.md, in the section about contributing
- the contributing guide https://github.com/supercollider/supercollider/wiki
- possibly a mention on the supercollider website

## Plan for Implementation

i won't have time to do this until next weekend, so if anyone wants to pick this up that would be great.

**Comment by brianlheim** [comment]
I've added some small references to the wiki page, and submitted #4635. If that wording looks good, I'll submit a similar PR to the website.

**Comment by brianlheim** [comment]
PR is up against website https://github.com/supercollider/supercollider.github.io/pull/207
