### ISSUE TITLE
ScIDE 3.10.3 Will not open on OSX 10.11.6

### ISSUE THREAD

**Issue by cupcake99** [supercollider/supercollider#4609]
Hello, it seems that the precompiled unsigned binary of 3.10.3 is built against the OSX 10.12 SDK and will not run in OSX/macOS 10.11 as expected. 

3.10.2 release works fine and is using Qt 5.9.1.

I do not have the time to set up the build environment for 3.10.3 at present, so have to revert to 3.10.2 release.

## Environment

* SuperCollider version: 3.10.3
* Operating system: OSX 10.11.6
* Other details (Qt version, audio driver, etc.): Qt 5.13

## Steps to reproduce

1. Download binary archive
2. Extract binary folder
3. Open SuperCollider.app
4. OSX shows error dialog "SuperCollider cannot be opened because of a problem"
5. The log file generated mentions Qt being built for 10.12

Sorry this has been filed as a bug incorrectly. I don't know how to re-label it as an IDE issue...

**Comment by cupcake99** [comment]
Right, i'm obviously very stupid and just realised i have most of the packages required to build SC already installed via homebrew, just need Qt5.

Will give it a go and report back.

**Comment by cupcake99** [comment]
Minimum supported platform for Qt 5.13 is macOS is 10.12. Bugger. Guess that's why it won't work.

**Comment by brianlheim** [comment]
1. Update your OS! 
2. As long as we make any changes that require Qt > 5.7, we could perhaps offer a build with 5.9 which would support macOS 10.10-10.12: https://doc-snapshots.qt.io/qt5-5.9/supported-platforms.html

I could bring that up at a developer meeting, I think it wouldn't be too much trouble to add as long as Travis's homebrew cache stays at Qt 5.9 or there is some other easy way to obtain it.

Regardless, we should update documentation to reflect this.

**Comment by cupcake99** [comment]
Hi Brian, thank you for the reply. I would update my OS, and perhaps one day will go to High Sierra, but am not all that impressed with Apple's recent nannying approach to user-end interaction with the system. I don't want to have to remonstrate with my computer when i need to do some computing... what is this, 2019: a space oddysey?

Anyway, a reflection of the current requirements would be most helpful for others in a similar situation to me no doubt, as i thought the base supported system for 3.10.x was OSX 10.11, hence surprise at finding SC wouldn't run here.

BTW it looks like current homebrew qt package is at 5.13, not sure if that's what you were referring to.

**Comment by brianlheim** [comment]
> Hi Brian, thank you for the reply. I would update my OS, and perhaps one day will go as far as installing High Sierra, but am not all that impressed with Apple's recent nannying approach to user-end interaction with the system.

Neither am I, but unfortunately an unpaid open source development team has limited ability to manage that situation.

> i thought the base supported system for 3.10.x was OSX 10.11

Sorry, there seems to be some confusion. You can use 3.10.3 on OSX 10.11, but you will need a version of Qt that supports it. Qt 5.9 is your best bet.

> BTW it looks like current homebrew qt package is at 5.13, not sure if that's what you were referring to.

In Travis, which is what we use for macOS CI, the Qt package is already installed and cached at 5.9 until you update it via homebrew. So if we don't request that update, everything is fine. That was what we did for the 3.10.2 builds, which is why that one works on your system. However, there was a bug using that version of Qt that led to a crash, so we used Qt 5.13 for SC 3.10.3.

**Comment by cupcake99** [comment]
Aha, i see, thank you for the clarification. I was referring to the pre-compiled binary of 3.10.3 there. I did figure i could get it working by building SC from source against the older qt but it's work i don't have time for either. So yes, i think i will have to get around to setting up my own build environment one day.

Also, one other thing is that my old Mac Pro will not run any OS beyond 10.11! I forgot about that.

**Comment by cupcake99** [comment]
BTW off-topic but just looked up Travis CI. Nice to know that something like that is available gratis for FOSS.
