### ISSUE TITLE
SuperCollider-specific translation files are not loaded on Mac

### ISSUE THREAD

**Issue by claremacrae** [supercollider/supercollider#4619]
## Environment

* SuperCollider version: revision 069818b80335a862ae0f46e2f95149c8ef0bc54b checked out
* Operating system: macOS Mojave 10.14.6
* Other details (Qt version, audio driver, etc.): Qt 5.13.1, installed vie home-brew

## Steps to reproduce

* Edit `editors/sc-ide/translations/scide_fr.ts` and change all `<translation type="unfinished"></translation>` to `<translation>sfafdafa</translation>`
* `cmake  --build . --target install --config RelWithDebInfo`
* Change the default system language to French
* ~Reboot~
* Run `Install/SuperCollider/SuperCollider.app`

## Expected vs. actual behavior

Expect behaviour: Most of the UI elements get renamed to `sfafdafa`
Actual behaviour: No change

**Comment by claremacrae** [comment]
I realise that this is not a real-world problem right now, as all the translation files are empty, but I want to change how the IDE is built, and make sure that I do not make this any worse than it already is, so spent some time tracking down what was going on.

And to capture the things I tried, and learned.

**Comment by claremacrae** [comment]
I added some debug output to main.cpp, to investigate the behaviour of the translation code - and this is what I got:

```
QLocale::system().name() = en_GB
QLibraryInfo::location(QLibraryInfo::TranslationsPath) = /Users/clare/Documents/develop/Audio/SuperCollider/build/Install/SuperCollider/SuperCollider.app/Contents/translations
ideTranslationPath = /Users/clare/Documents/develop/Audio/SuperCollider/build/Install/SuperCollider/SuperCollider.app/Contents/Resources/translations
QLocale::system().name() = en_GB
QLocale::languageToString( QLocale::system().language() ) = English
QLocale::countryToString( QLocale::system().country() ) = United Kingdom
ideTranslationFile = scide_en_GB
```

Things that are really weird in this:

* I have changed the system language to French and rebooted - lots of other applications show a French UI, yet the above output (obtained by double-clicking on the application icon, not launching from the terminal) still shows English
* The filenames `editors/sc-ide/translations/` have 2-character language names, e.g. `scide_fr.ts` - but `QLocale::system().name()` is producing 5 chars i.e. `en_GB`

If I hard-code `ideTranslationFile` to be `scide_fr` then my hacked translation file is loaded correctly.

**Comment by claremacrae** [comment]
I think the answer is to change SuperCollider so that it does not identify the translation filename to use, and instead defers to Qt to use the QLocale to search for a range of valid file names.

This overload looks to be what is needed:

https://doc.qt.io/qt-5/qtranslator.html#load-1

```c++
bool QTranslator::load(const QLocale &locale, const QString &filename, 
    const QString &prefix = QString(), const QString &directory = QString(), 
    const QString &suffix = QString())
```

**Comment by claremacrae** [comment]
This looks to be useful example code:

https://github.com/KDAB/GammaRay/blob/master/common/translator.cpp#L53

**Comment by claremacrae** [comment]
Re this overload:

```c++
bool QTranslator::load(const QString &filename, const QString &directory = QString(), 
    const QString &search_delimiters = QString(), const QString &suffix = QString())
```

https://doc.qt.io/qt-5/qtranslator.html#load

It also does some mangling of file names to try and find alternative files... So I wonder whether the only problem is the language coming back as `en_GB` from the system instead of the `fr_FR` that I was expecting...

**Comment by claremacrae** [comment]
I am having a look at this... I don't seem to have permission to assign it to myself.

**Comment by joshpar** [comment]
I added us both so I can help if anything comes up.

**Comment by claremacrae** [comment]
I've pushed a fix for this in https://github.com/claremacrae/supercollider/commit/3668bf9e887f042e3babd773d777bf5d0f18f76c.

In order to set up a test of the change, I did the following:

1. Create a new translation file, `scide_en.ts` which was a copy of one of the existing ones
2. Add that new file to `editors/sc-ide/CMakeLists.txt`
3. Copy the text below in to `editors/sc-ide/translations/hack_translation.sh`
4. Build the install target

Then to actually test it, on a Mac:

1. Change the default Language & Region to French
    * **There is no need to reboot the Mac.** Just restarting SuperCollider is enough to pick up the new language
2. Start SuperCollider and confirm that all the menu items and widgets are called `scide_fr.ts`
3. Switch language to German, restart SuperCollider, and test that UI contains `scide_de.ts`
4. Switch to English, repeat, and test that UI contains `scide_en.ts`

```sh
# Copy in to editors/sc-ide/translations/hack_translation.sh
# This edits each .ts file so that it is obvious which language file was loaded
for file in *.ts ; do
  cat <<EOF > sedscr
s|<translation type="unfinished"></translation>|<translation>$file</translation>|
EOF
  sed -i.bak -f sedscr $file
  rm ${file}.bak
done
rm sedscr
```

**Comment by claremacrae** [comment]
@joshpar If you feel it's appropriate, please could you review the PR for this - #4620 - and if possible, merge it, as it's a precursor to my making a PR for #4617?

**Comment by claremacrae** [comment]
I've picked this up again... Right now, when I create an install on my Mac, there is no translations folder in 

`build/Install/SuperCollider/SuperCollider.app/Contents/Resources/`

This needs debugging before I can reinstate my code to make sure that the translations are found....
