### ISSUE TITLE
Mac Travis CI builds fail to find Qt

### ISSUE THREAD

**Issue by claremacrae** [supercollider/supercollider#4621]
## Environment

* SuperCollider version: Travis CI Mac builds on Default
* Operating system: macOS
* Other details: 

## Steps to reproduce

Trigger a Travis CI build in this project, and see that the Mac build fails.

An example failure is:

https://travis-ci.org/supercollider/supercollider/jobs/605778915#L2865

```
2865  CMake Error at QtCollider/CMakeLists.txt:30 (find_package):
2866  By not providing "FindQt5.cmake" in CMAKE_MODULE_PATH this project has
2867  asked CMake to find a package configuration file provided by "Qt5", but
2868  CMake did not find one.
2869
2870  Could not find a package configuration file provided by "Qt5" (requested
2871  version 5.7) with any of the following names:
2872
2873    Qt5Config.cmake
2874    qt5-config.cmake
```

There are lots of warnings further up.

## Expected vs. actual behavior

Expected: Travis Mac CI builds pass if the code is good
Actual: Travis Mac CI builds fail to find Qt

## Other comments

There was a successful build 25 days ago, so it looks like it has failed sometime since then:
https://travis-ci.org/supercollider/supercollider/jobs/594348082?utm_medium=notification&utm_source=github_status

I first observed the problem on a build on my fork 2 days ago:
https://travis-ci.com/claremacrae/supercollider/jobs/250688604

So it may be a change in Travis Mac environment in between.

**Comment by brianlheim** [comment]
It looks like homebrew has dropped support for macos 10.12:

```
Warning: You are using macOS 10.12.
We (and Apple) do not provide support for this old version.
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Discourse, Twitter or IRC. You are responsible for resolving any issues you
experience while you are running this old version.
```

[i am beginning to wish there was an alternative to homebrew, i really do not like their attitude.]

i am going to try to find a version of macOS that will be supported.

**Comment by claremacrae** [comment]
Thanks for spotting that... Fingers crossed that you can just switch the builds to macOS 10.13...

**Comment by brianlheim** [comment]
I pushed a branch that updates to the `xcode9.4` image, which according to travis uses macOS 10.13 -- https://travis-ci.org/supercollider/supercollider/builds/605796050

**Comment by brianlheim** [comment]
The first commit on that branch didn't work, because homebrew didn't install ccache. In a second commit I tried just installing ccache a few times in a row, and that worked for some reason. I'm trying a third commit now (https://travis-ci.org/supercollider/supercollider/jobs/605803830) to try to get to the bottom of it.

**Comment by claremacrae** [comment]
Thanks for working on this @brianlheim 

I checked the builds after the PR was merged to develop. https://travis-ci.org/supercollider/supercollider/builds/605846541

The Mac build passed, which is great.

The Linux build with Qt enabled had a test failure: https://travis-ci.org/supercollider/supercollider/jobs/605846542#L3900

```
3900    1 TESTS FAILED, 11 skipped, out of 366 (total duration: 7.0s)
3901 Search for ? or ! to find failed tests.
3902 The command "$TRAVIS_BUILD_DIR/.travis/test.sh" exited with 1.
```

The failure was at https://travis-ci.org/supercollider/supercollider/jobs/605846542#L3882

```
3882    [!] TestNoOps:test_arithmetics (0.0s) (Did not complete.)
3883           ! Error: "ERROR: UnitTest halted with onFailure handler."
```

(It's good to see tests being run in the builds - I wasn't aware of `.travis/test.sh` - very useful)

**Comment by claremacrae** [comment]
The merge of the PR to the `3.10` branch worked fine - tests passed.

https://travis-ci.org/supercollider/supercollider/builds/605846527

I don't know the project well enough to know if the failure on `develop` could be real and due to different code between the two branches, or if the failure was something like a flickering test...
