### ISSUE TITLE
Documentation for Pflatten missing

### ISSUE THREAD

**Issue by wolfgangschaltung** [supercollider/supercollider#4625]
## Environment

* SuperCollider version: SuperCollider 3.10.3
* Operating system: macOS 10.14.6 (18G103)
* Other details (Qt version, audio driver, etc.): n/a

## Steps to reproduce
(0) Start Supercollider
(1) In SC Help Browser, search for "Pflatten"
(2) SC Help Browser returns "<del>Pflatten</del>"
(3) Click on "<del>Pflatten</del>"

## Expected vs. actual behavior
- Actual:  SC Help Browser explains that this class is missing documentation.
- Expected: SC Help Browser shows documentation for "Pflatten"

## Notes
I am a real newbie to programming in general and SC in specific, so please excuse that I can not provide the documentation text itself. The only meager thing I can provide is a (hopefully) useful example.

I wanted realtime manipulation of an already playing pattern, so I used `Pfunc`to call a variable with an array of degree notes to change the running pattern. But instead of the `Pbind` playing `~notes` as a chord (as it does if the `\degree`pattern below would read `Pseq([Pfuncn({~notes})], inf)`), I wanted `~notes` to be played as a sequence of notes. Sending the `.flatten` message to the `Pfunc` achieved this.  

```
// evaluate this first…
~notes = [0, 2, 4, 6];

// …then this
(
Pbind(
	\degree, Pseq([Pfuncn({~notes}).flatten], inf),
).trace.play
)

// …and finally this
~notes = [1, 3, 5, 7]; //
```

Thanks to @dkmayer who pointed me into this direction.

**Comment by brianlheim** [comment]
thanks! please see my note here: https://scsynth.org/t/newbie-question-changing-pattern-during-playback/1428/7?u=virtualdog
