### ISSUE TITLE
Add usage example for missing Pflatten documentation

### ISSUE THREAD

**Issue by wolfgangschaltung** [supercollider/supercollider#4626]
## Motivation
* SuperCollider version: SuperCollider 3.10.3
* Operating system: macOS 10.14.6 (18G103)

SC Help Browser is missing documentation for "Pflatten" class. Learning about Pflatten can be helpful when doing realtime manipulation of an already playing pattern, see example below.

## Usage Example for Documentation
For realtime manipulation of an already playing pattern, `Pfunc` can be used to call a variable with an array of degree notes that changes the running pattern. As an alternative to the `Pbind` playing `~degrees` as a chord (as it does if the `\degree`pattern below would read `Pseq([Pfuncn({~degrees})], inf)`), the  `~degrees` can be played as a sequence of notes. Sending the `.flatten` message to the `Pfunc` achieves this.

```
// evaluate this first…
~degrees = [0, 2, 4, 6];

// …then this
(
Pbind(
	\degree, Pseq([Pfuncn({~degrees}).flatten], inf),
).trace.play
)

// …and finally this
~degrees = [1, 3, 5, 7];
```

## Plan for Implementation
Unfortunately, I am a real newbie to programming in general and SC in specific, so please excuse that I can not provide the documentation text itself. The only meager thing I can provide is the (hopefully) useful example above.

**Comment by brianlheim** [comment]
thank you for this, but this is still an issue, not a PR (pull request).

we certainly want to improve our documentation, but the best and most efficient way to do so is to submit the change yourself. we have a contributing guide here[1] and a guide to writing documentation for sclang here[2], i'd encourage you to give it a try!

i am going to close this as it simply isn't what our issue tracker is meant to do. anyone (including yourself) is free to submit the example in a new pull request.

[1] https://github.com/supercollider/supercollider/wiki
[2] http://doc.sccode.org/Guides/WritingHelp.html

**Comment by jamshark70** [comment]
> i am going to close this as it simply isn't what our issue tracker is meant to do.

If there is a new user (as in this case) who doesn't yet understand the language well enough to contribute documentation, but who wishes to request that a help file be written, *and* if the bug tracker is not the appropriate place to do that, then where is the appropriate place to do it?

**Comment by jamshark70** [comment]
(Deleted comment, apologies for noise, I hadn't read the comment on scsynth.org)

**Comment by wolfgangschaltung** [comment]
Sorry, I am confused now. I first wrote an issue, which got closed as it describes an already existing issue, and on scsynth I was told by VIRTUALDOG to file a PR instead, now the PR got closed as well, because it is not the requested documentation itself, but just the request for documentation.

While I do value the encouragement to have a go at documenting `Pflatten`, I don't think it would be a reasonable undertaking, as
1) I am real newbie to programming in general and SC in specific, as I have said in the issue, the PR and the communication on scsynth.
2) And as such a newbie I really do not know anything about `Pflatten`. Nothing. Except for that little example I gave.

If you think that such an example can be used in an upcoming documentation for Pflatten, please let me know how I can contribute it.

**Comment by jamshark70** [comment]
> Sorry, I am confused now. I first wrote an issue, which got closed as it describes an already existing issue, and on scsynth I was told by VIRTUALDOG to file a PR instead, now the PR got closed as well, because it is not the requested documentation itself, but just the request for documentation.

The issue here is not in fact a PR -- it's an issue report, in the same category as the first one.

A pull request means that you have forked the git repository, cloned your copy, added a branch, changed and committed files to your fork, and *then* you can open a pull request to incorporate those changes.

Brian had actually said "leave a comment on the general “undocumented classes” issue here" and left a link: https://github.com/supercollider/supercollider/issues/2434 You could go here and add a comment.

I think it's correct that we shouldn't maintain a separate open issue for every instance of missing documentation. But I also think we as a community could strive to be more welcoming of new users.

**Comment by brianlheim** [comment]
my apologies if any of this seemed unwelcoming. however, this is an issue tracker for developers and it is not intended to be an educational experience for new users. when people participate here, we expect them to read and follow our guidelines for contributing, as that saves time and energy for everyone involved (this thread being a perfect example).

@wolfgangschaltung i've already given you a few links that explain how to effectively contribute to this project. if you have any more specific questions after reading them, i or @jamshark70 would be happy to answer them for you. if you have no intent to make a contribution at this time, then perhaps you could ask another person to make it for you.

**Comment by wolfgangschaltung** [comment]
Thanks for the explanation. I am sorry having taken up your time. If I will ever get fluent enough at SC to really know what `Pflatten` does, I'll write the documentation for it (and learn how to handle github before!).
