### ISSUE TITLE
CMake warnings

### ISSUE THREAD

**Issue by dyfer** [supercollider/supercollider#4648]
## Environment

* SuperCollider version: develop
* Operating system: macOS 10:13
* Other details (Qt version, audio driver, etc.):

## Steps to reproduce

configure for building
```
cmake -G Xcode -DCMAKE_PREFIX_PATH=`brew --prefix qt5`  ..
```

## Expected vs. actual behavior
CMake output starts with this:
```
 CMake Warning (dev) at CMakeLists.txt:1 (project):
   Policy CMP0048 is not set: project() command manages VERSION variables.
   Run "cmake --help-policy CMP0048" for policy details.  Use the
 cmake_policy
   command to set the policy and suppress this warning.

   The following variable(s) would be set to empty:

     CMAKE_PROJECT_VERSION
     CMAKE_PROJECT_VERSION_MAJOR
     CMAKE_PROJECT_VERSION_MINOR
     CMAKE_PROJECT_VERSION_PATCH
 This warning is for project developers.  Use -Wno-dev to suppress it.
```
This is followed by expected configuration messages.
Is this something we could address? Either by providing these values or somehow making CMake not care about them?

**Comment by brianlheim** [comment]
agree this is annoying, could you look into what's causing this? actually, i thought it was fixed in https://github.com/supercollider/hidapi/pull/10, maybe that change hasn't yet been introduced to this repo.

**Comment by dyfer** [comment]
It looks that the new way of defining versions is with 
```cmake
project(SuperCollider VERSION 3.10.3)
```
which sets `PROJECT_VERSION_MAJOR`, `PROJECT_VERSION_MINOR` and `PROJECT_VERSION_PATCH`.
We then would need to set 
```cmake
cmake_policy(SET CMP0048 NEW)
```
In that case I don't know how to properly get this data from `SCVersion.txt`, where version information is stored.

If we'd instead do this:
```cmake
cmake_policy(SET CMP0048 OLD)
```
then a warning is printed:
```
CMake Deprecation Warning at CMakeLists.txt:1 (cmake_policy):
  The OLD behavior for policy CMP0048 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.
```
which is equally annoying, and indicates deprecated functionality.

So... how to get `3.10.3` etc. from the `SCVersion.txt` file?

**Comment by brianlheim** [comment]
can you include the version file before calling project()?
