### ISSUE TITLE
Pdefn (and other proxy objects?) proliferate when using string as key

### ISSUE THREAD

**Issue by madskjeldgaard** [supercollider/supercollider#4667]
## Environment

* SuperCollider version: 3.10.3
* Operating system: Ubuntu Studio 18.04
* Other details (Qt version, audio driver, etc.): Running in SCNVIM

## Steps to reproduce

```supercollider
// Put something in the "hej" Pdefn
Pdefn("hej", 123);

// Put something else in the "hej" Pdefn
Pdefn("hej", 456);

// Whoops - there are now two objects?
Pdefn.all.do{|p| 
	p.source.postln
};

// Clear the dict
Pdefn.all.clear

// Do the same with a symbol as key
Pdefn('hej', 123);
Pdefn('hej', 456);

// Only one object
Pdefn.all.do{|p| 
	p.source.postln
};
```

## Expected vs. actual behavior
I would expect only one object to be made when defining an object with a string as key (and actually to have "hej" and 'hej' as key refer to the same object behind the scenes, but that's a seperate issue). If it is erronous to use a String then an error should be posted.

It seems more objects are created when using a string.

**Comment by telephon** [comment]
Yes, behind these classes there are `IdentityDictionaries`. It is intentional that matching is via identity, so you could use any object as key, and for that matter, also your own custom dictionary. You shouldn't use Strings ...

**Comment by nuss** [comment]
@telephon ... which seems a bit inconsistent with e.g. the `SynthDef` interface:
```SuperCollider
SynthDef("lalala", {}).add;
SynthDescLib.global["lalala"]; // nil
SynthDescLib.global[\lalala]; // -> SynthDesc 'lalala' 
```
In case of `Pdef`, `Pdefn` and the like wouldn't it be enough to implicitly convert the key to a `Symbol` in `*new` (resp. `copy`) (just quickly skimmed through the source. Maybe other places are affected as well...):
```SuperCollider
*new { arg key, item;
	var res = this.at(key.asSymbol);
	if(res.isNil) {
		res = super.new(item).prAdd(key.asSymbol);
	} {
		if(item.notNil) { res.source = item }
	}
	^res
}
```

**Comment by telephon** [comment]
Well, despite the name, `SynthDef` is very different from all the jitlib `def`s, and the above example shows that it can even be confusing to do this conversion secretly.

The thing is, it is a feature, not a bug. By converting everything to a symbol, you'd lose that feature. Maybe it should be documented somewhere more clearly?

**Comment by nuss** [comment]
Maybe. maybe you're right. I think I haven't even once tried to initialize a `Pdef` with string given as the key. But aside from the confusion strings may cause in this case, what's the purpose of that _feature_?

**Comment by telephon** [comment]
The purpose is to have no purpose (i.e. to be transparent). You know that it is only an interface to a dictionary and you can rely on it.

**Comment by nuss** [comment]
Ok, I think I (kinda) understand. If it's an explicit philosophy behind all JITLib `def`s then it should probably just be documented.
