### ISSUE TITLE
IDE is unreadable, preferences are blacked out

### ISSUE THREAD

**Issue by jon-myers** [supercollider/supercollider#4669]
## Environment

* SuperCollider version: 3.10.3
* Operating system: Mac OS 10.15.1
* Other details (Qt version, audio driver, etc.): Macbook Pro Mid 2014

## Steps to reproduce

Open Supercollider.

## Expected vs. actual behavior
IDE windows are very dark grey, while all text is black, making it very difficult to read anything. Attempts to change the view settings via preferences are also impossible due to preferences window being mostly blacked out: 
<img width="815" alt="Screen Shot 2019-12-10 at 12 24 48 PM" src="https://user-images.githubusercontent.com/6957461/70566051-29235c80-1b48-11ea-9827-8fb350c6f955.png">

**Comment by joshpar** [comment]
I don't see this happening - have you ever set any custom font / IDE colors? Or is this a fresh install?

**Comment by jon-myers** [comment]
I have not ever set any custom fonts / IDE colors, and this was a fresh install. (I should have mentioned that this is the apple notarized version)

**Comment by brianlheim** [comment]
@jon-myers can you please try temporarily renaming or removing the file at `~/Library/Application Support/SuperCollider/sc_ide_conf.yaml`? i believe there is an issue with how the IDE in 3.10.3 interacts with old IDE config files.

**Comment by brianlheim** [comment]
This is the issue - https://github.com/supercollider/supercollider/issues/4218

**Comment by jon-myers** [comment]
@brianlheim  Yes, removing the old sc_ide_conf.yaml file solved the issue. Thanks.

**Comment by brianlheim** [comment]
happy to help!
