### ISSUE TITLE
Docs: consolidate documentation for math ops

### ISSUE THREAD

**Issue by brianlheim** [supercollider/supercollider#4676]
## Environment

N/A

## Steps to reproduce

N/A

## Expected vs. actual behavior

Initially mentioned in https://github.com/supercollider/supercollider/pull/4604#issuecomment-537789535

Many functions have implementations across 'AbstractFunction', 'Operators', 'SimpleNumber', and 'SequenceableCollection' that look very similar. However, the documentation for them is quite varied. We should figure out how to resolve those inconsistencies and if possible prevent doc/code rot in the future.

I see two possibilities -- simply resolve all the consistencies now and try to keep them the same going forward, or put them all in one document and redirect everyone to that. I prefer the former because I like documentation being as dead-simple as possible, but I wish there was a way to synchronize these sections, or perhaps even better have them all point to the same document or document segment under the hood.

**Comment by mtmccrea** [comment]
I think `copymethod::` is underutilized and could help here. I've described a related issue and requested a feature here: #4724

**Comment by brianlheim** [comment]
i'm no longer concerned about this and have no plan to fix it, so closing it to reduce clutter
