### ISSUE TITLE
Class method autocompletion and method signatures of view redirect classes

### ISSUE THREAD

**Issue by jamshark70** [supercollider/supercollider#469]
`Window(` -- the argument list pops up, because Window itself defines *new

`Window.screenB` -- no autocompletion because Window doesn't implement screenBounds -- the call will fall through to the implementing class. Ctrl-space doesn't respond.

I also couldn't get method signatures to appear.

Could be hard, but it's probably worth cleaning up as GUI objects are fairly popular.

**Comment by scztt** [comment]
Gui redirects have been removed, so this is no longer an issue.
