### ISSUE TITLE
TestXYZ.runAll gives misleading result

### ISSUE THREAD

**Issue by dyfer** [supercollider/supercollider#4720]
## Environment

* SuperCollider version: current develop
* Operating system: macOS 10.13
* Other details (Qt version, audio driver, etc.):

## Steps to reproduce

```supercollider
// 1. make/modify a chosen unit test so it fails
// 2. run it with .runAll method
TestXYZ.runAll;
// result: 
// UNIT TEST.............
// There were no failures
// but 
TestXYZ.run;
// reports error as expected
```

## Expected vs. actual behavior

`.runAll` is a class method of `UnitTest` to be used as follows: `UnitTest.runAll`. However,  all tests are subclassing `UnitTest` and thus inherit this method. Running `TestXYZ.runAll` does not run the test, but still prints 
```
UNIT TEST.............
There were no failures
```
which is misleading. I think that `TestXYZ.runAll` should either throw an error, or a warning, or at the very least not print the "no failures" message.

**Comment by telephon** [comment]
Good that you mention this! I think `TestXYZ.runAll` should do just that, namely run all tests in `TestXYZ`.

**Comment by dyfer** [comment]
> I think `TestXYZ.runAll` should do just that, namely run all tests in `TestXYZ`.

But `TestXYZ.run` already runs all the tests in `TestXYZ` so we'd end up with two classes methods with the same functionality (not the end of the world, but maybe less optimal?)

**Comment by telephon** [comment]
Ah I see. So `runAll`  in `UnitTest` basially means run all subclasses, right? Maybe it should be renamed then.

**Comment by dyfer** [comment]
@telephon yes. Are you suggesting renaming `UnitTest.runAll`?
Either way, all tests will inherit that method. Whatever it is called, it should somehow be handled differently in subclasses IMO.

**Comment by telephon** [comment]
Yes, I thought it might be a good idea to just make it work for any subclass of `UnitTest` and perhaps even renaming it to `runAllSubclasses`. But I see that this would make a refactoring because `reset` changes global state. So better throw an error for now, maybe `notYetImplemented`.

**Comment by dyfer** [comment]
based on a [comment](https://github.com/supercollider/supercollider/pull/4722#discussion_r363008051) from @jamshark70 it seems that making `*runAll` work for subclasses makes sense...

**Comment by telephon** [comment]
ok, then just do that.

**Comment by dyfer** [comment]
It seems that discussion in #4722 gravitates towards throwing an error for `*runAll`, let's continue discussing there.
