### ISSUE TITLE
Cursor degradation after typing any character

### ISSUE THREAD

**Issue by fmiramar** [supercollider/supercollider#4726]
## Environment

* SuperCollider version: 3.10.3
* Operating system: Windows 10
* Other details (Qt version, audio driver, etc.): Dell XPS 9570

## Steps to reproduce
When the keyboard cursor is idle and you type anything the mouse cursor arrow gets degraded. It comes back to the normal error when you move the mouse once again. 

I am not sure if it is a QT problem, because Windows 10 on Dell XPS 9570 is presenting several resolution scaling issues...

**Comment by brianlheim** [comment]
thanks for the report. could you perhaps share screenshots of what you're seeing? it's difficult for me to understand just based on the description.

**Comment by fmiramar** [comment]
The mouse pointer does not appears on print screen, so here is a photo from my mobile. The degraded icon below the SinOsc is the mouse pointer. 

![20200107_120549](https://user-images.githubusercontent.com/54965070/71905376-cfae4d80-3146-11ea-8ae0-183eab7226d7.jpg)

**Comment by fmiramar** [comment]
PS: the keyboard cursos was blinking next to `a`

**Comment by brianlheim** [comment]
closing this as an upstream Qt issue -- it's highly unlikely that this is something we can solve ourselves, as we don't do anything especially fancy with cursors. sorry about that.
