### ISSUE TITLE
FR: add docs for testsuite

### ISSUE THREAD

**Issue by dyfer** [supercollider/supercollider#4728]
## Motivation

There's little information currently on the c++ testsuite, AFAICT.

## Description of Proposed Feature

Add documentation about running c++ tests.

## Plan for Implementation
Put info about running `ctest` on the SC wiki.

What do you think?

**Comment by brianlheim** [comment]
done. if you have any other info you'd like to add, please edit the wiki directly!

https://github.com/supercollider/supercollider/wiki/Unit-Testing-Guide#other-tests
