### ISSUE TITLE
Documentation at ".removeAllSuchThat" wrong

### ISSUE THREAD

**Issue by DjTuxeedo** [supercollider/supercollider#4730]
In the written description of what the function does the logic is swapped once. I might be wrong but i think it works just the other way around.
Thank you

**Comment by brianlheim** [comment]
the documentation is correct.

```supercollider
var a;
a = List[1, 2, 3, 4];
a.removeAllSuchThat({ arg item, i; item < 3 });
a;
```

executing these lines as a block, `a` is `List[3, 4]` at the last line. all items `item` for which `item < 3` have been removed. if you execute just the first three lines, you see that `a.removeAllSuchThat(...)` returns `List[1, 2]`, which is the list of object that have been removed.
