### ISSUE TITLE
Image throws an error if size is a float

### ISSUE THREAD

**Issue by dyfer** [supercollider/supercollider#4731]
## Environment

* SuperCollider version: 3.10.4
* Operating system: macOS 10.13
* Other details (Qt version, audio driver, etc.):

## Steps to reproduce

```supercollider
Image.new(400.0);
// ERROR: Primitive '_QImage_NewEmpty' failed.
```

## Expected vs. actual behavior

`View` generally does't mind getting bounds in floating point values, however `Image` throws an error. This came up when I was fixing some old code that inadvertently passed a float to one of the arguments in the `Image.color` method (supposedly this worked in Cocoa).
Maybe it's not a big deal but since `View` doesn't mind floats, then maybe `Image` could be more permissive too?
```supercollider
View(nil, 200.0@200.0); //seems OK
```

**Comment by brianlheim** [comment]
could document and just leave it be or make it more permissive, either is fine with me.

i'm going to close this one, but that doesn't mean you can't fix it if you want or that it isn't worthwhile to fix. in general, a small API inconsistency like this doesn't rise to the level of importance where it justifies cluttering the issue tracker. if we logged one for every instance of this we'd be left with a lot of noise, and it wouldn't be very helpful for maintainers. until we're at a point where more severe API inconsistencies are resolved and the number of issues is a little more manageable, i'd recommend against keeping tickets for things like this.
