### ISSUE TITLE
[3.10] EnvGen reports done when not triggered

### ISSUE THREAD

**Issue by jamshark70** [supercollider/supercollider#4738]
## Environment

* SuperCollider version: 3.10.x

Per discussion at https://scsynth.org/t/confused-by-done-ugen/1621/6 -- an EnvGen that has not been triggered yet causes `Done.kr` to answer 1, in any 3.10 version. This doesn't happen in develop.

https://github.com/supercollider/supercollider/commit/8190ba700e542f2f94678466cee9ff44c9b3dd1c is relevant to this issue and was merged into develop, but not into 3.10.

So I believe it should be backported into 3.10 (as it fixes buggy behavior).

**Comment by brianlheim** [comment]
3.10.4 was the last 3.10 release, we are moving onto 3.11 now since it's been quite a while since a minor release
