### ISSUE TITLE
3.10.4: (still) unable to build against system boost

### ISSUE THREAD

**Issue by dvzrv** [supercollider/supercollider#4743]
The fix for vendored/ system boost and vendored/system yaml-cpp (#4185) has to be backported for 3.10.x.

In the current situation, it's impossible to build against system boost, as cmake force builds against the vendored boost all over the place.

As soon as I've fixed this locally, I'll try to open a pull request for this against the 3.10 branch.

## Environment

* SuperCollider version: 3.10.4
* Operating system: Arch Linux
* Other details (Qt version, audio driver, etc.): 
  - boost 1.71.0
  - qt5 5.14.0
  - yaml-cpp 0.6.3

## Steps to reproduce

```
rm -rvf external_libraries/boost
  cmake -DCMAKE_INSTALL_PREFIX=/usr \
        -DCMAKE_BUILD_TYPE=Release \
        -DBoost_NO_BOOST_CMAKE=ON \
        -DLIBSCSYNTH=ON \
        -DFORTIFY=ON \
        -DSYSTEM_YAMLCPP=ON \
        -DSYSTEM_BOOST=ON \
        -DSC_VIM=OFF \
        -B build \
        .
  make VERBOSE=1 -C build
```

## Expected vs. actual behavior

- Expected: Build commences and links against system boost.

- Actual: Build fails, because it builds and links against vendored boost: 
[supercollider-3.10.4-build.log](https://github.com/supercollider/supercollider/files/4081196/supercollider-3.10.4-build.log)

**Comment by brianlheim** [comment]
3.10.4 was the last 3.10 release, so there will be no backporting. Sorry about that

**Comment by dvzrv** [comment]
:-/

**Comment by brianlheim** [comment]
i know. but, it's been over a year since the 3.10 release, and we originally wanted to make a 3.11 release after 4 months. so, time to move on. there will always be things that can be backported, but for a team of this size, we've decided it's not worthwhile to maintain multiple release branches at once.

**Comment by dvzrv** [comment]
I understand.

I'm more concerned over carrying so many fixes/ patches and hope that with 3.11 we'll arrive at a smoother experience.

I'll try to improve the cmake setup and also find some time to make CI build against system boost, so that breakage is discovered earlier.

**Comment by brianlheim** [comment]
3.11 should be a lot smoother! for that release we will be doing an alpha or beta release first, so that would be a good time to report and fix any patches that have to be made on Arch Linux.

**Comment by dvzrv** [comment]
If anyone is interested in using a backport fix for this, here it is:
https://github.com/dvzrv/supercollider/commit/21f5c7f765223a77621c9a46beb95d0ac00115a4
