### ISSUE TITLE
TGrains2 does not respond to triggers from Impulse.ar

### ISSUE THREAD

**Issue by markHadman** [supercollider/supercollider#4755]
## Environment

* SuperCollider version: 3.10.4
* Operating system: Linux 5.4.13-rt7-MANJARO
* Other details (Qt version, audio driver, etc.): Qt 5.14.0, ALSA Driver version: k5.4.13-rt7-MANJARO, Library version:    1.2.1.2, Utilities version:  1.2.1, jack 0.125.0-8

## Steps to reproduce
```
b = Buffer.read(s, Platform.resourceDir +/+ "sounds/a11wlk01.wav");
{TGrains2.ar(1,Impulse.ar(5),b)}.play
```

## Expected vs. actual behavior
No sound is output. 
I would expect this to normally work, since the documentation for TGrains2 states that "If the trigger is audio rate then the grains will start with sample accuracy."
Replacing Impulse.ar with Impulse.kr causes it to work.
Changing to TGrains.ar causes it to work.

**Comment by joshpar** [comment]
TGrains2 is a third party UGen (and not core SC) - please file a report on sc3-plugins.
