### ISSUE TITLE
Infinite loop (sclang and SC IDE hang) with nil-returning pattern and Pn

### ISSUE THREAD

**Issue by totalgee** [supercollider/supercollider#4765]
## Environment

* SuperCollider version: 3.10.3
* Operating system: Windows 10 Pro
* Other details (Qt version, audio driver, etc.):

## Steps to reproduce

```supercollider
// A simple Pbind
p = Pbind(\degree, Pseq([ 0, 1 ], 1), \dur, 0.5);

// returns two events, then nil, as expected
p.asStream.nextN(3, ());
// -> [ ( 'degree': 0, 'dur': 0.5 ), ( 'degree': 1, 'dur': 0.5 ), nil ]

// (p*2 was a live-coding typo, but the Pbinop should return nil...and does)
(p*2).asStream.nextN(3, ()); 
// -> [ nil, nil, nil ]

// this causes an infinite loop...sclang freezes and must be killed externally
// (can't even "Quit Interpreter" via SC IDE menu)
Pn(p*2).asStream.nextN(3, ());
```

## Expected vs. actual behavior

I ran into this sequence of events (pardon the pun) during a live-coding performance, unfortunately. I mistakenly typed a "*2" that applied to the Pbind itself, rather than to something inside it ( e.g. if I wanted `Pbind(…, \dur, 0.5*2)` but instead wrote `Pbind(…, \dur, 0.5)*2` ). Easy to do under the pressure of performance. (-; Further exploration today shows that this returns a Pbinop, that returns `nil` when evaluated as a stream. Sounds harmless...but this pattern was then sent to an infinite Pn, so it loops forever.

It would be nice if the infinite `Pn` above returned `nil` (when its pattern argument is a Pattern returning nil on its first evaluation). But I guess it can't, since the whole point of `Pn` is to repeat (in this case, I did want the pattern `inf` times). So...is this a bug? If not, how can I avoid this freeze happening again when I mistakenly give it a bad input?

**Comment by jamshark70** [comment]
I don't think we should change the behavior of Pn -- it's too fundamental.

The ddwPatterns quark has `PnNilSafe` which will terminate in the case you describe.

**Comment by totalgee** [comment]
Thanks, maybe I'll look into using PNilSafe (or something similar that
checks the source pattern) in my own code rather than Pn, then.

**Comment by jamshark70** [comment]
To fill in a bit more about why I doubt Pn should be changed for this:

`PnNilSafe` detects a possible infinite loop by checking the clock's logical time -- if it is asked to output more than *n* values at the same logical time, then it assumes the loop is hanging and it exits. I can't think of a better way -- because the interpreter has no thread preemption, we can't implement a watchdog thread in the language itself.

So it's useful in the context of a Pbind, where you expect successive values to be drawn after some time delta.

But:

```
Pn(Pseries(0, 1, 3), inf).asStream.nextN(100);
-> [ 0, 1, 2, 0, 1, 2, ... ]

PnNilSafe(Pseries(0, 1, 3), inf).asStream.nextN(100);
-> nil (actually I didn't test this, maybe it's a short array)
```

That type of usage pulls all the values at once, so PnNilSafe assumes something is wrong and finishes early.

Pn needs to "just work" for generic stream usage.

Should we add PnNilSafe (maybe under a different name) into core? @totalgee is right that this is a massive risk for live coding, which often involves looping structures (Pn) and if something is accidentally not initialized and Pn's child pattern is empty, then *boom* you're rebooting on stage.

**Comment by totalgee** [comment]
Maybe (probably) this is naïve, but couldn't Pn just check if it pulls two embedded `nil`s in a row? (Or...even simpler: stop (return or throw an error) if the very first result it gets from its sub-pattern on embedding is `nil`)? It doesn't make any sense to embed a `nil` pattern two, three or `inf` times...

I would be much happier to get an error thrown (or have the pattern end "normally") rather than get an infinite loop.

**Comment by jamshark70** [comment]
> Maybe (probably) this is naïve, but couldn't Pn just check if it pulls two embedded nils in a row?

Unfortunately that's not possible.

A crucial but subtle point is that there are two concepts of a "return value," which are neither compatible nor interchangeable.

- the *yield* value (what you get back from `next`)
- the `embedInStream` return value (by definition, the next `inval` to be processed)

It would be easy to detect that the child pattern *yielded* nil... but the problem occurs when the child pattern doesn't yield anything at all (i.e. it calls `yield` 0 times). The embedInStream call simply returns. The value it returns is the input argument to the user's `next` call, so you can't use it to know that the child pattern didn't yield.

**Comment by totalgee** [comment]
Well, what about something like this (which seems to work, at least for my case):

```supercollider
PnSafe : FilterPattern {
	var <>repeats, <>key;
	*new { arg pattern, repeats=inf, key;
		^super.newCopyArgs(pattern, repeats, key )
	}
	storeArgs { ^[pattern,repeats, key] }

	prEmbed { arg stream, inval;
		var outval;
		var returnedSomething = false;
		while {
			outval = stream.value(inval);
			outval.notNil
		}{
			inval = outval.yield;
			returnedSomething = true;
		};
		if (returnedSomething.not) { Error("PnSafe sub-pattern returned no Events").throw };
		^inval
	}

	embedInStream { | event |
		if(key.isNil) {
			repeats.value(event).do {
				event = this.prEmbed(pattern.asStream, event)
			}
		} {
			repeats.value(event).do {
				event[key] = true;
				event = this.prEmbed(pattern.asStream, event)
			};
			event[key] = false;
		};
		^event;
	}
}
```

Use it like this:

```supercollider
p = Pbind(\degree, Pseq([ 0, 1 ], 1), \dur, 0.5);

// returns two events, then nil, as expected
p.asStream.nextN(3, ());

// (p*2 was a live-coding typo, but the Pbinop should return nil...and does)
(p*2).asStream.nextN(3, ()); 

// Safe version of Pn that throws an error if its sub-pattern doesn't return any events
PnSafe(p*2).asStream.nextN(3, ());
// ERROR: PnSafe sub-pattern returned no Events
```

**Comment by totalgee** [comment]
Or even, instead of throwing an Error, maybe it could simply yield a `nil` (in the `returnedSomething.not` case above). This way it will nicely exit, no infinite sclang loop -- the PnSafe stream just ends if the sub-pattern happens to never return *any* Events.

```supercollider
...
		if (returnedSomething.not) {
			"PnSafe sub-pattern returned no Events".warn;
			inval = nil.yield;
		};
		^inval
...
```

**Comment by jamshark70** [comment]
I'd written a nice long explanation of why you need to count the number of consecutive embedInStream calls that didn't yield any events and terminate only if that count exceeds a limit set by the user -- then crashed my computer and lost all of it. I'm afraid I don't have time to rewrite it, so the short version is:

This idea for PnSafe is basically fine, but it *is* legitimate to embed a pattern once or a few times when that pattern happens (sometimes) not to yield anything, as long as it eventually yields something in the future. A concrete example would be a series of scale fragments, where the starting degree of every scale fragment is one degree higher than the previous one, but there's a 20% chance of skipping a starting step.

```
Pn(
    Pseries(
        // starting step
        Pseries(-7, 1, inf).asStream,
        1,
        // length of each scale segment
        // 20% chance of 0 here
        Pwrand([0, Pwhite(4, 7, 1)], [0.2, 0.8], inf).asStream
    ),
    inf
)
```

PnSafe would kill this as soon as the segment length is 0. I think that's not ideal. Not too hard to deal with.

**Comment by jamshark70** [comment]
Oh, IDE autosave rescued my revisions to PnSafe! So...

```supercollider
PnSafe : FilterPattern {
	var <>repeats, <>key, <>numEmpty;
	*new { arg pattern, repeats = inf, key, numEmpty = 10;
		^super.newCopyArgs(pattern, repeats, key, numEmpty)
	}
	storeArgs { ^[pattern, repeats, key, numEmpty] }

	embedInStream { |event|
		var countEmpty = 0;
		var embedOnce = { |inval|
			var stream = pattern.asStream;
			var outval;
			var returnedSomething = false;
			while {
				outval = stream.value(inval);
				outval.notNil
			} {
				inval = outval.yield;
				returnedSomething = true;
			};
			if(returnedSomething) {
				countEmpty = 0;
			} {
				countEmpty = countEmpty + 1;
			};
			if(countEmpty >= numEmpty) {
				nil.alwaysYield;
			};
			inval
		};
		if(key.isNil) {
			repeats.value(event).do {
				event = embedOnce.value(event);
			}
		} {
			repeats.value(event).do {
				event[key] = true;
				event = embedOnce.value(event);
			};
			event[key] = false;
		};
		^event;
	}
}
```

**Comment by totalgee** [comment]
Thanks for coming up with example where it would fail, that makes sense. And thanks for the version with the `numEmpty` counter... In my case, I could use my original version, but likely I'll stick with your more general solution. Thanks again for looking into this!
