### ISSUE TITLE
can't uninstall/reinstall correctly in Ubuntu

### ISSUE THREAD

**Issue by Hunterwolf88** [supercollider/supercollider#4772]
Hello,
I needed to uninstall SuperCollider for test purposes (Ubuntu).
For some reason now, after reinstalling, it's stuck because of old Quarks it can't find anymore.
SuperCollider looks completely stuck and I can't access Quarks GUI or run commands.
I just get "Library has not been compiled successfully.".

I tried these commands:
```
sudo apt-get purge --auto-remove supercollider
sudo apt-get purge --auto-remove supercollider-ide
sudo apt-get purge --auto-remove supercollider-dev
```
I followed this guide for reinstalling:
https://github.com/supercollider/supercollider/wiki/Installing-SuperCollider-on-Ubuntu-systems

Also "enable realtime access priority" is not showing anymore and it looks like it's not working.

There must be some kind of configuration file somewhere even after the purge.
Am I missing something?

**Comment by jamshark70** [comment]
Quarks are not subject to apt package requirements. So you might have to take some extra steps.

Configuration files are located under `~/.config/SuperCollider`. If you want a clean slate, it's safe to delete everything here.

> enable realtime access priority

I think that's outside of SC? I'm afraid I don't have this option at my fingertips; it's been a couple of years since I set up a new system.

**Comment by Hunterwolf88** [comment]
Got it :) thanks!

**Comment by Hunterwolf88** [comment]
Sorry for reopening this, but I cant no longer get Supercollider working on Ubuntu again.
I installed it (3.8.0) running
`sudo apt-get install supercollider` (also tried supercollider-ide and supercollider-dev)
but when I run it I have those warnings. Not sure I got them before uninstalling-reinstalling.

WARNING: Extension in '/usr/share/SuperCollider/SCClassLibrary/Platform/linux/extMIDIOut.sc' overwrites Meta_MIDIClient:externalSources in main class library.
WARNING: Extension in '/usr/share/SuperCollider/SCClassLibrary/Platform/linux/extMIDIOut.sc' overwrites Meta_MIDIClient:externalDestinations in main class library.
WARNING: Extension in '/usr/share/SuperCollider/SCClassLibrary/Platform/linux/extMIDIOut.sc' overwrites Meta_MIDIIn:connectAll in main class library.
Intentional overwrites must be put in a 'SystemOverwrites' subfolder.

Not sure how to move without messing things up.

**Comment by snappizz** [comment]
the warnings you see are harmless, but you've got an old version of SC (3.8 was released in 2016). those warnings have been silenced in newer versions.

unfortunately, the ubuntu repos lag behind stable releases. the only way to upgrade here would be to build SC from source. see #2917 for discussion.
