### ISSUE TITLE
GUI Barely working while using Windows8.1 High Contrast Theme

### ISSUE THREAD

**Issue by ritchse** [supercollider/supercollider#4774]
## Environment

* SuperCollider version: 3.10.3
* Operating system: Windows 8.1 Pro
* Other details (Qt version, audio driver, etc.): -

## Steps to reproduce

1-Go to the customization settings on Win8.1
2-Set a high contrast theme (Personally using a customization of 'black on high contrast'
3-Open Supercollider IDE
4-GUI will not update on command, only if the window is deselected/minimized and then selected/opened; The changes to the code will be done, just not shown to the user.
5-Same thing happens while scrolling and while changing files

**Comment by brianlheim** [comment]
this is a Qt issue and out of our control, sorry.
