### ISSUE TITLE
FreeSelf.kr not freeing synths with short/fast envelopes

### ISSUE THREAD

**Issue by salkin-mada** [supercollider/supercollider#4781]
## Environment

* SuperCollider version: 3.11.0-beta1
* Operating system: Windows 10
* Interface: Motu 828ES

## Steps to reproduce

```supercollider
(SynthDef('freemee', {
	|out, gate = 1, amp = 0.5, attack = 0.5, sustain = 0.5, release = 0.5|
	var noi, sig, env, sum;
	noi = PinkNoise.ar(0.2);
	env = EnvGen.ar(Env.linen(attack, sustain, release), gate);
	FreeSelf.kr(TDelay.kr(Done.kr(env),0.1));
	sig = noi*env;
	sum = LeakDC.ar(sig);
	Out.ar(out, sum!2);
}).add;
)

Pdef(\dooo, Pbind(\instrument, 'freemee', \dur, Pseq([1/2,Rest(1/2)],inf))).play // OK
Pdef(\dooo, Pbind(\instrument, 'freemee', \dur, Pseq([1/2,Rest(1/2)],inf), \attack, 0.001)).play // OK
Pdef(\dooo, Pbind(\instrument, 'freemee', \dur, Pseq([1/2,Rest(1/2)],inf), \attack, 0.001, \release, 0.001)).play // OK
Pdef(\dooo, Pbind(\instrument, 'freemee', \dur, Pseq([1/2,Rest(1/2)],inf), \attack, 0.001, \sustain, 0.1, \release, 0.001)).play // OK
Pdef(\dooo, Pbind(\instrument, 'freemee', \dur, Pseq([1/2,Rest(1/2)],inf), \attack, 0.001, \sustain, 0.01, \release, 0.001)).play // OK
Pdef(\dooo, Pbind(\instrument, 'freemee', \dur, Pseq([1/2,Rest(1/2)],inf), \attack, 0.001, \sustain, 0.001, \release, 0.001)).play // OK
Pdef(\dooo, Pbind(\instrument, 'freemee', \dur, Pseq([1/2,Rest(1/2)],inf), \attack, 0.001, \sustain, 0.0001, \release, 0.001)).play // synths are not freed
```

## Expected vs. actual behavior

Synths should be freed even when the envelopes used are very short. They are not in the `3.11.0-beta1`. 

* tested with both `EnvGen.kr` and `EnvGen.ar` (including `.perc` `.linen` and `.adsr`)
* there is small variations in the issue trigger threshold 
* The problem seems to be triggered when \sustain is around 0.0005 and below.
* Playing around with this threshold - using 0.0006 will create a small click and the synth will be freed most of the time. Suddenly the click disappears, silence arrives and the synth count will go up. Suddenly the click comes back and the new synths are freed. This shift in behavior continues. On and on. Back and Forth. So leaving a "clicky" synth pattern playing for some hours will create 1000+ synths running which all have envelopes that ended.

### Version Issue

last line of reproducer code is working as expected in version `3.10.4-rc1`, `3.10.3` and `3.10.2`

**Comment by patrickdupuis** [comment]
I can confirm the issue on `3.11`. I can also confirm that the problem isn't present on `3.10.4`.

**Comment by brianlheim** [comment]
almost certainly due to https://github.com/supercollider/supercollider/commit/8190ba700e542f2f94678466cee9ff44c9b3dd1c#diff-ffe91b8ce506cad17ce50cc8e3e65342 since this is the only functional change to EnvGen since 2017. @sonoro1234 , do you have time to take a look?

**Comment by sonoro1234** [comment]
This is a very intrincate issue. It begins in #334 and those interested should read https://github.com/supercollider/supercollider/issues/3094 and several related issues. 

The commit was very small, three lines of code, and solved some of this issues, but the main lesson was that gates changing state more than once in a control period will be lost.

I dont expect to be able to do any more than deleting this 3 lines, but that would make reapear the issues solved.

**Comment by patrickdupuis** [comment]
PR #4783 seems to fix the problem for me (Linux). @salkin-mada could you try it out on your system?

**Comment by salkin-mada** [comment]
PR #4783 also fixes the problem on my debian 10 system. Will check on the Windows 10 machine asap.

**Comment by brianlheim** [comment]
there is no need to test across multiple OS's, the code is the same on both platforms.
