### ISSUE TITLE
sc-el missing CMakeLists.txt file in supercollider

### ISSUE THREAD

**Issue by muziker** [supercollider/supercollider#4798]
## Environment
Supercollider tag Version-3.10.4

## Steps to reproduce
Checkout the tag, and cmake the build

## Expected vs. actual behavior
cmake errors out with Missing CmakeLists.txt file in editors/sc-el

Well, according to the scel repo, this has been taken out to be a separate module. So to get past this error, i had to add a dummy CMakeLists.txt to the editors/sc-el directory.

**Comment by brianlheim** [comment]
make sure to update submodules with `git submodule update --init --recursive`
