### ISSUE TITLE
Pdef.play should use clock (and quant) if set in the instance

### ISSUE THREAD

**Issue by totalgee** [supercollider/supercollider#4803]
## Environment

* SuperCollider version: 3.10.4
* Operating system: Windows 10 Pro
* Other details (Qt version, audio driver, etc.):

## Steps to reproduce

When you `play` a Pdef (without arguments), it uses the parent class (Pattern) version of `play`, which requires you to specify the `clock` and `quant` arguments explicitly. If you play a Pdef which has its `clock` and/or `quant` members set, one would expect it to use those by default. So maybe it should just have its own overload of `play`? Or is there a reason it doesn't do this?

(I think the `quant` seems to work okay, so the problem may be only with the clock.)

```supercollider
(
c = TempoClock(1.5, 10); d = TempoClock(2, 20);
Pdef(\a).clock_(c).quant_(8).play;
Pdef(\b).clock_(d).quant_(7).play;
Pdef(\a).source = Pbind(\dummy, Pfunc{ thisThread.clock.beats.debug("a beats") }, \dur, 1);
Pdef(\b).source = Pbind(\dummy, Pfunc{ thisThread.clock.beats.debug("b beats") }, \dur, 1);
)
```

## Expected vs. actual behavior

Would expect the "beats" logged for 'a' and 'b' to be different, since they should be running on different Clocks. Instead, they're both on TempoClock.default (instead of `c` or `d`).

```txt
b beats: 7.0 // <-- b starts quantized to 7, but on TempoClock.default
b beats: 8.0
a beats: 8.0 // <-- a starts quantized to 8, but also on TempoClock.default
b beats: 9.0 // <-- a and b are obviously on the same (wrong) clock!
a beats: 9.0
b beats: 10.0
a beats: 10.0
b beats: 11.0
a beats: 11.0
...
```

It *does* work if you explicitly specify the clock in the `play` call...but what's the point of having the Pdef set to a Clock if you're not going to use it? Is there a reason you might want to quantify to one clock but play on a different one?

```supercollider
(
c = TempoClock(1.5, 10); d = TempoClock(2, 20);
Pdef(\a).clock_(c).quant_(8).play(c); // <-- note: added the clock to the play calls
Pdef(\b).clock_(d).quant_(7).play(d);
Pdef(\a).source = Pbind(\dummy, Pfunc{ thisThread.clock.beats.debug("a beats") }, \dur, 1);
Pdef(\b).source = Pbind(\dummy, Pfunc{ thisThread.clock.beats.debug("b beats") }, \dur, 1);
)
```

Good output:

```txt
b beats: 21.0 // <-- b starts quantized to 7, and on the correct (d) clock which began at 20
b beats: 22.0
b beats: 23.0
b beats: 24.0
b beats: 25.0
b beats: 26.0
b beats: 27.0
b beats: 28.0
a beats: 16.0 // <-- a starts quantized to 8, and on the correct (c) clock which began at 10
b beats: 29.0 // <-- a and b are definitely running on different clocks, as they should!
a beats: 17.0
b beats: 30.0
a beats: 18.0
b beats: 31.0
b beats: 32.0
a beats: 19.0
...
```

**Comment by jamshark70** [comment]
> When you play a Pdef (without arguments), it uses the parent class (Pattern) version of play, which requires you to specify the clock and quant arguments explicitly.

Pdef inherits from EventPatternProxy, which implements its own `play`.

https://github.com/supercollider/supercollider/blob/develop/SCClassLibrary/JITLib/Patterns/Pdef.sc#L568

But here, it passes `argClock` through instead of `argClock ?? { this.clock }`.

> If you play a Pdef which has its clock and/or quant members set, one would expect it to use those by default.

I'd tend to agree. If there's a member variable that is unused, then either it's cruft to remove, or the fact that it's unused is a bug. (Why does `playOnce` say `argClock ? this.clock` while `play` falls back to the global default clock?)

**Comment by telephon** [comment]
That is silly, yes. Sorry! The desired behaviour for all methods is simple: 

If you pass a clock, play on that clock. If you don't pass a clock, play on the proxy's clock, and if this is nil, use TempoClock.default. 

I'm not sure what to do when you pass a clock to a proxy that is already playing on a different clock.

It shouldn't be hard to fix, but I don't have the time right now to look after it.
