### ISSUE TITLE
Error 'didBecomeKey' when switching IDE tabs

### ISSUE THREAD

**Issue by eleses** [supercollider/supercollider#4813]
## Environment

* SuperCollider version: 3.10.4
* Operating system: Win 10
* Other details (Qt version, audio driver, etc.):

## Steps to reproduce

Again I have no clear steps to repro this, but after using the IDE for a while with several documents opened, it sometimes stars to spew `ERROR: Message 'didBecomeKey' not understood.` when switching tabs by clicking on their name/tab in the tab-line above the edit window.

## Expected vs. actual behavior

```
ERROR: Message 'didBecomeKey' not understood.
RECEIVER:
   nil
ARGS:
CALL STACK:
	DoesNotUnderstandError:reportError
		arg this = <instance of DoesNotUnderstandError>
	Nil:handleError
		arg this = nil
		arg error = <instance of DoesNotUnderstandError>
	Thread:handleError
		arg this = <instance of Thread>
		arg error = <instance of DoesNotUnderstandError>
	Object:throw
		arg this = <instance of DoesNotUnderstandError>
	Object:doesNotUnderstand
		arg this = nil
		arg selector = 'didBecomeKey'
		arg args = [*0]
	Meta_Document:prCurrent_
		arg this = <instance of Meta_Document>
		arg newCurrent = nil
	Meta_Document:setActiveDocByQUuid
		arg this = <instance of Meta_Document>
		arg quuid = '{03e959f5-07f6-4cba-87a3-dc868f3b5154}'
		var newCurrent = nil
	< closed FunctionDef >  (no arguments or variables)
	Process:interpretCmdLine
		arg this = <instance of Main>
^^ The preceding error dump is for ERROR: Message 'didBecomeKey' not understood.
RECEIVER: nil

```

**Comment by geoffroymontel** [comment]
I'm getting this as well if I recompile the class library.
See https://github.com/supercollider/supercollider/issues/4413

**Comment by avdrd** [comment]
@hr30 I think it's related to some quarks, oddly enough. What quarks do you have installed when it happens?
