### ISSUE TITLE
builds: Travis CI has started failing (at least on PRs)

### ISSUE THREAD

**Issue by claremacrae** [supercollider/supercollider#4820]
## Environment

The most recent 3 PRs have all failed only on one Travis build.

The build config that is failing is:

* AMD64
* Linux
* C++
* QT=false DO_LINT=true

The PRs are:

* #4817
    * Failed Build: https://travis-ci.org/github/supercollider/supercollider/jobs/660905941?utm_medium=notification&utm_source=github_status
    * Failure: https://travis-ci.org/github/supercollider/supercollider/jobs/660905941#L504
    * `tar: clang.tar.xz: Cannot open: No such file or directory`
* #4815
    * Failed Build: https://travis-ci.org/github/supercollider/supercollider/jobs/661106339?utm_medium=notification&utm_source=github_status
    * Failure https://travis-ci.org/github/supercollider/supercollider/jobs/661106339#L501
    * `tar: clang.tar.xz: Cannot open: No such file or directory`
* #4819
    * Failed build: https://travis-ci.org/github/supercollider/supercollider/jobs/661194700?utm_medium=notification&utm_source=github_status
    * https://travis-ci.org/github/supercollider/supercollider/jobs/661194700#L504
    * `tar: clang.tar.xz: Cannot open: No such file or directory`

The full text of the error is:

```
[0K$ $TRAVIS_BUILD_DIR/.travis/before-install-$TRAVIS_OS_NAME.sh --qt=$QT
Downloading and extracting Clang 8.0.0
tar: clang.tar.xz: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
/home/travis/build/supercollider/supercollider/.travis/before-install-linux.sh: line 10: cd: clang+llvm-8.0.0-x86_64-linux-gnu-ubuntu-14.04/bin: No such file or directory
Added clang-format in /home/travis/build/supercollider to PATH
Running tools/clang-format.py lintall
  File "tools/clang-format.py", line 600, in main
    do_lintall(options.clang_format)
  File "tools/clang-format.py", line 496, in do_lintall
    clang_format = ClangFormat(clang_format)
  File "tools/clang-format.py", line 234, in __init__
    self._validate_version()
  File "tools/clang-format.py", line 245, in _validate_version
    CLANG_FORMAT_ACCEPTED_VERSION_STRING)

*** ERROR:
clang-format found, but incorrect version at clang-format with version: clang-format version 5.0.0 (tags/RELEASE_500/final)
```

**Comment by claremacrae** [comment]
For comparison, #4811 is the last of the successful builds - and here is its output for DO_LINT=true:
https://travis-ci.org/github/supercollider/supercollider/jobs/660285951?utm_medium=notification&utm_source=github_status

**Comment by claremacrae** [comment]
I will compare a good and bad log, and report any differences here....

**Comment by claremacrae** [comment]
The last good build had these lines:

```
Downloading and extracting Clang 8.0.0
Added clang-format in /home/travis/build/supercollider/clang+llvm-8.0.0-x86_64-linux-gnu-ubuntu-14.04/bin to PATH
Running tools/clang-format.py lintall
```

Where the first failed had this:

```
ownloading and extracting Clang 8.0.0
tar: clang.tar.xz: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
/home/travis/build/supercollider/supercollider/.travis/before-install-linux.sh: line 10: cd: clang+llvm-8.0.0-x86_64-linux-gnu-ubuntu-14.04/bin: No such file or directory
Added clang-format in /home/travis/build/supercollider to PATH
```

**Comment by eleses** [comment]
This was fixed as a bug, but pending pull requests affected by this cannot be so easily restarted it seems (that action requires write access). There are some suggested workarounds on StackOverflow, but I for one am holding off for now from doing any of those as they might invalidate code reviews etc.

**Comment by brianlheim** [comment]
i will restart PR CI builds as needed. thanks @claremacrae for the ticket!

**Comment by claremacrae** [comment]
For my own education, how will you get the change in to the other PRs, @brianlheim ?

**Comment by brianlheim** [comment]
@claremacrae there are two types of CI builds, "branch" and "pr". "pr" checks the result of merging the branches, while "branch" checks the current state of the branch. "branch" jobs only run for commits on branches on this repo.

until 3.11 is merged into master and then master into develop, all  "pr" CI jobs against develop will fail. all "branch" jobs for branches that don't include this fix will fail until they are rebased to include the fix or have the fix merged in. i would currently not consider a "branch" job failure for the issue identified in this ticket to be a reason not to merge a PR.

**Comment by claremacrae** [comment]
Awesome - thank you!

**Comment by eleses** [comment]
@brianlheim I'm probably out of my depth here, but can't this fix (#4824) be cherry-picked into develop? Won't that achieve the same effect of restarting the "pr" CI jobs?

**Comment by brianlheim** [comment]
@eleses it's a fair point and i have done that in the past. if the 3.11->master->develop merges take longer than expected i will make the same change in develop.

**Comment by eleses** [comment]
@brianlheim I see the curl-clang fix has now propagated to develop. And that seems to have auto-triggered a new travis build from my PR (i.e. there was no need to manually restart the failed one.) [7476](https://travis-ci.org/github/supercollider/supercollider/builds/661461943?utm_medium=notification&utm_source=github_status) vs [7477](https://travis-ci.org/github/supercollider/supercollider/builds/661465430?utm_medium=notification&utm_source=github_status). It's nice when automation works as expected...
