### ISSUE TITLE
prSymbol_envirPut and prSymbol_envirGet always call into the identDict base class, ignoring any subclassing

### ISSUE THREAD

**Issue by eleses** [supercollider/supercollider#4829]
I'm no sure if this really counts as a bug or more like a feature request, but here it goes...

## Environment

* SuperCollider version: 3.11
* Operating system: any

## Steps to reproduce

When extending `IdentityDictionary` or its subclasses (`Environment` etc.) the subclass' `put` method doesn't get called from within a `use` setter, i.e.

```
e.use { ~stuff = 1 } // doesn't call into the subclass put
```

A showcasing example, addapted  by stripping down the OEM class from wslib

```
WannabeOrderedE : Environment  {

	var <keys;

	*new { arg ...pairs;
		^super.new(8, nil,nil, true).putPairs( pairs );
	}

	put { |key, value|
		"In MY put: % %\n".postf(key, value.cs);
		if( value.isNil ) {
			keys.remove( key );
		} {
			if( keys.isNil or: { keys.includes( key ).not } ) {
				keys = keys.add(key);
			};
		};
		super.put( key, value );
	}
}
```

## Expected vs. actual behavior

And now

```
e = WannabeOrderedE.new;
e.['foo'] = 2; // posts the "In MY put" debugging message
e.use { ~nope = 44 }; // does not post anything
e.keys // returns only [foo]
```

This happens because of the implementation(s) of `prSymbol_envirPut` and `prSymbol_envirGet`, always [call](https://github.com/supercollider/supercollider/blob/c4824dbe62f6558908feb8d94720f4b7627deb15/lang/LangPrimSource/PyrListPrim.cpp#L486) `identDictPut` and `identDict_lookup`, ignoring any subclassing.

Notably `EnvironmentRedirect` solves this problem by not subclassing anything (well, other than Object), but that solution has other issues, namely not passing checks for `isKindOf(Dictionary)` which are done is a few critical spots in the class library.

**Comment by telephon** [comment]
>but that solution has other issues, namely not passing checks for isKindOf(Dictionary) which are done is a few critical spots in the class library.

I only found three places in the class library where `"isKindOf(Dictionary)"`is used. EnvirGui, EventStreamCleanup, and SCDoc. Did I miss some?

Generally speaking, I don't think it is a good idea to make this check in the class library. Primitives need those checks, but it isn't optimal to have them. Subclassing is mainly a convenience for avoiding code duplication. Everything beyond that makes it hard to extend the system.

But yes, your point is good. I've had a discussion with James McCartney about that long ago, will try to find it.

**Comment by jamshark70** [comment]
> This happens because of the implementation(s) of prSymbol_envirPut and prSymbol_envirGet, always call identDictPut and identDict_lookup, ignoring any subclassing.

If these primitives fail, then it bounces back to the class library to call `at` or `put` as a normal method call on currentEnvironment. But the primitive has to fail before it can do that. A subclass, with the same storage implementation, won't fail here.

The primitive failure has a performance cost -- and Events need to be as performant as possible, so I'd be cautious about every IdentityDictionary `at` and `put` needing to go through an extra method dispatch to determine which primitive function to call. I estimate about 50 `envirGet`s to play one `\type, \note` event -- efficiency matters here. (FWIW, this is not the only method override that doesn't work -- when a particular usage of `if`, `switch` etc is inlined, it bypasses method dispatch and we lose flexibility in redefining control structures for other classes -- but in exchange for significant performance gains.)

**Comment by telephon** [comment]
can a primitive check what class it was called from?

**Comment by eleses** [comment]
> can a primitive check what class it was called from?

I think so because the dict is obtrained as 

```
PyrObject* dict = slotRawObject(currentEnvironmentSlot);
```

currentEnvironment is set OK in the above example, i.e.

```
e.use { currentEnvironment.class } // -> WannabeOrderedE 
```

**Comment by eleses** [comment]
@telephon You might be interested in a few discoveries (of sorts) I've [posted](https://github.com/supercollider/supercollider/issues/4830#issuecomment-599583996) on the "alt-bug/alt-fix" page. I'm not posting all their details here because they don't quite pertain to the problem I raised here. But in summary: 

* There's an undocumented `forward` feature in `EnvironmentRedirect` (ER henceforth) that does allow ERs to be played "directly".

* Surprisingly this "direct play" of ERs doesn't break on cleanups, despite the subclassing check in `EventStreamCleanup`, because the method-call forwarding feature of ER has the effect of returning objects of class Event (or whatever class the underlying `envir` class is.)

* But that also means that ERs can't replace `Event` subclassing exactly because any custom `dispatch`  in ER is no longer called once the ER is "gone" after the first forwarded call and only its base is getting called/referenced directly! So ER is no real hack/substitute for Event subclassing, thus using ER is not an alternative to fixing this bug (4829)!

**Comment by jamshark70** [comment]
> I don't see why the primitive needs to fail at all for (user) subclasses of Event.

When a sclang method calls a primitive, the primitive can either succeed (`return errNone`) or fail. On success, the primitive method stub in the class library simply returns. On failure, it executes the sclang code following the primitive ID, as a fallback. The fallback may construct a `PrimitiveFailedError` or it might dispatch to a different method that could succeed.

E.g., `1 + [2, 3]` initially calls `_AddInt`, but this method doesn't handle arrays. So the primitive fails, and the fallback is `^aNumber.performBinaryOpOnSimpleNumber('+', this, adverb)` --> `[2, 3] + 1` and you get the right answer.

This is *the* way for a primitive to go back into the interpreter for alternate method dispatch. I'm pretty sure the interpreter is not reentrant in this way -- a primitive can't set up a method call on the stack and dispatch. I think I might have tried it at one point, and it broke horribly. (You'll find in MIDI and OSC responders' C++ backend that it does push entries onto the stack and call into a method -- but the interpreter is not actively doing anything at that moment, so it's *entering* but not *re-*entering the interpreter.)

`maxsubclassindex` might very well work to distinguish between "standard" identity dictionary subclasses end user subclasses -- but AFAIK the only way to get back into the interpreter to call the user's method is by failing the primitive.

**Comment by jamshark70** [comment]
Oh, just noticed this one.

> On the other hand, there's one potential complication making Event subclasses a bit more work if one wants to customize reads (i.e. ats) because prEvent_Delta also assumes it can just do identDict_lookup, so it bypasses dynamic dispatching as well.

I think, if a user is really intent on subclassing Event, then she could also provide `delta` in that subclass.

The reason why `Symbol:envirGet` and `Symbol:envirPut` bypass subclass implementations is because they call into the primitive first -- and, crucially, the methods calling the primitives do not belong to the identity dictionary subclass (so, an IDict subclass has no opportunity to override the Symbol behavior).

That's not the case for `delta` -- the method calling this primitive *is* in Event. So if you subclass Event and override `delta`, then it will dispatch to the subclass method.

**Comment by eleses** [comment]
@jamshark70 

> a primitive can't set up a method call on the stack and dispatch

I see. I'm not convinced this is a show stopper here though, as I don't see right now why there would need to be a method call explicitly set up the stack to do the "virtual dispatching" from the C++ level. Seen from the "interpreted side" of sclang, you already have `prSymbol_envirPut` "on the stack" and it just does *something*. Whether it calls into `identDictPut`'s or something else to "do the work" should be oblivious to the layers above, but I could be missing some other details, like the reentrancy issue you've mentioned, i.e. the VM state in  `prSymbol_envirPut` might not allow the equivalent of a virtual dispatch at that point.

As the saying goes "talk is cheap, show me the code" at this point. (And that "show" is addressed to myself.)

**Comment by eleses** [comment]
But to make this discussion a bit more focused on solutions, are the objections to the idea I posted a few messages above along the lines of adding a 

```
Event.maxOptimizedSubclass = SomeClass;
```

type of configurability? This could simply work by failing from the primitive(s) `prSymbol_envir{Get,Put}` via the `class_identdict_maxsubclassindex` ISKINDOF check (already in place), so the "pure sclang" code could do the virtual dispatch in that case for SomeClass and its subclasses. With this proposal, a user would typically set `Event.maxOptimizedSubclass` to `Event` to "disable" `prSymbol_envir{Get,Put}` for its own subclasses of Event. The default Event.maxOptimizedSubclass could well be `nil`, with the meaning that the VM would provide the current behavior of optimizing for all subclasses of IDict (and thus all subclasses of Event), as it happens right now, providing change from the current hard-coded behavior, unless explicitly desired by the user (even though this might be an abundance of caution given the discussion(s) that nobody really seems to have subclassed Event until now.)

**Comment by eleses** [comment]
I just realized I can simply do from the "pure" SC level:

```
+ Symbol {

	envirPut { arg aValue;
		//("envirPut hook for a" + currentEnvironment.class).postln;
		if(Event.superclasses.add(Event).includes(currentEnvironment.class).not,
			{"overrrided native".postln; ^currentEnvironment.put(this, aValue)},
			{^this.nativePut(aValue)}
		);
	}

	nativePut { arg aValue;
		_Symbol_envirPut
		currentEnvironment.put(this, aValue);
		^aValue
	}
}
```

to bypass the optimizations, exactly because these are actual method calls generated, and not something inlined....

I thought based on the comments in Symbol.sc that `~foo = 12` *completely* bypasses Symbol.sc and calls directly into _Symbol_envirPut so the code there was "conceptual pseudocode", but that's not actually the case, it really gets run, so `envirPut` can still be pre-hooked in `Symbol`... duh.

This basically provides a trivial workaround to my bug/feature request, i.e. an equivalent to setting `class_identdict_maxsubclassindex`, so there's hardly any need to bother with a C++ fix/implementation for configuring that, albeit at the cost of some performance penalty with the redundant class-hierarchy check/search I've done.
