### ISSUE TITLE
Checks for isKindOf(Dictionary) are incompatible with EnvironmentRedirect

### ISSUE THREAD

**Issue by eleses** [supercollider/supercollider#4830]
This an "alternative" bug report for #4829, in the sense that one could either fix that one (which seems to be a bit more C++ work) or perhaps this one, which might be an easier fix, albeit it has the potential for future brittleness still.

## Environment

* SuperCollider version: 3.11
* Operating system: any

## Discussion

Basically `EnvironmentRedirect` cannot (and does not) subclass `Environment` because doing that would trip some VM "magics" that disable some dynamic dispatching as detailed in #4829. 

Therefore any checks like `isKindOf(Dictionary)`, `isKindOf(Environment)` etc., fail for `EnvironmentRedirect` and they have to be replaced with "duck typing" checks.

Currently identified such `isKindOf` checks:

* `isKindOf(Dictionary)` in
  * `EventStreamCleanup` (which needs serious rewriting anyway)
  * `EnvirGui`
  * `SCDoc`, probably a non-issue
* `isKindOf(Environment)`
  * `Ptrace`
* `isKindOf(IdentityDictionary)`: none

This is not a complete fix for #4829 because one cannot hope to use just `Environment` (never mind `EnvironmentRedirect`) instead of `Event`, because the latter have a magic `prEvent_Delta` and probably more special stuff I didn't think of which `EnvironmentRedirect` doesn't try to emulate.

```
Pbind(\dur, Pseq([0.3, 0.5], inf)).play(protoEvent: Environment());
// ERROR: Message 'synchWithQuant' not understood
```

Thus if one wants to `play` `EnvironmentRedirects` the only real choice is to go "a layer below" to the actual `Event` redirected, i.e.

```
(
var order;
order = OrderedIdentitySet();
e = EnvironmentRedirect(());
e.dispatch = {
	|key, val|
	order.remove(key);
	order.add(key);
};
)

p = Ptrace(Pbind (\dur, Pseq([0.3, 0.5], inf))).play(protoEvent: e.envir); // ok
p = Ptrace(Pbind (\dur, Pseq([0.3, 0.5], inf))).play(protoEvent: e); // hopeless
```

In contrast one *can* play subclasses of `Event`, although there are the #4829 magics to worry about. (There's a [semi-]working example on the that other page.)

Therefore, making `EnvironmentRedirect` a more plausible Environment substitute will help in some cases e.g. (probably) in `EnvirGui` but won't help in others where the check really is for `isKindOf(Event)`, as it happens to be the case in `EventStreamCleanup` (I mean you can attach cleanups to just `Environments`, but they won't `play` anyway, not with the `Event`'s player, you'd have to "roll your own" player...)

**Comment by eleses** [comment]
In hindsight this is too broad and confusing as a bug report. I'll file one for EnvirGui, which I have checked and indeed has this problem, and would be helped by fixing it.

**Comment by eleses** [comment]
Also, I've discovered the undocumented feature on EnvironmentRedirect that does allow itself to be played:

```
e = EnvironmentRedirect(());
p = Pbind(\dur, Pseq([0.3, 0.5], inf)).trace.play(protoEvent: e); // silent
p.stop;
e.envir = (forward: e.envir); // an undocumented feature
p = Pbind(\dur, Pseq([0.3, 0.5], inf)).trace.play(protoEvent: e) // plays!
```

**Comment by telephon** [comment]
Thank you very much indeed for your careful investigation! This is a typical case for a lack of generality of an implementation (I wrote it long ago). I didn't think of using it as an Event replacement in patterns;  EventStreamCleanups didn't exist that time, if I remember correctly.

But it would be very good if that worked properly.

Btw., the dispatch is only meant to work for `put`.

**Comment by telephon** [comment]
Btw. the correct fix for the `isKindOf` problem would be to introduce some criterion for which all those objects return true which have the correct interface. In `EventStreamCleanup`, e.g. the point is only whether it is something that implements `put` with a key. So `respondsTo(\put)` would be wrong. We don't have explicit interfaces, unfortunately.

Perhaps: `isLookup` 
```supercollider
Object {
   isLookup {  ^false }
}

Dictionary {
   isLookup {  ^true }
}

EnvironmentRedirect {
   isLookup {  ^true }
}

```

**Comment by eleses** [comment]
> Perhaps: isLookup

James mentioned something similar; he proposed `isDictionary` if I recall correctly (can't find out where he said right now).

**Comment by telephon** [comment]
yes, that was my first thought too, I just hesitated because all we want here is "some object that responds to put and at like a dictionary". Nothing else is presupposed. Now consider someone uses `isDictionary` to check for some other part of the dictionary interface, e.g. `collect` or `merge`, this would certainly fail for the redirect. If we had an abstract object (#3467), this would be much easier to implement.

**Comment by eleses** [comment]
Found where James mentioned his preference to me https://scsynth.org/t/is-there-an-order-preserving-environment-quark/1881/16?u=rfluff

I'm not really the guy to advocate for a particular solution in a project I've barely touched, but a post above that one, I gave my brain dump of what a PE544 "protocol-like" solution could look in SC (sans the static type checker, of course).
