### ISSUE TITLE
Keep tagging uniformity

### ISSUE THREAD

**Issue by dvzrv** [supercollider/supercollider#4835]
Hi! I package supercollider for Arch Linux. Currently I'm having troubles retrieving the current version from upstream (this repository), because [3.11-beta1](https://github.com/supercollider/supercollider/releases/tag/3.11-beta1) shadows the current latest stable ([Version-3.11.0](https://github.com/supercollider/supercollider/releases/tag/Version-3.11.0)).

Tools, such as [nvchecker](https://github.com/lilydjwg/nvchecker) are used by many downstreams (such as me) to track new versions of upstreams (such as supercollider). These tools - depending on configuration - rely on the tags of upstream repositories.

As `3.11-beta1` orders before `Version-3.11.0` (according to [semver](https://semver.org/)), the tracking of versions is now stuck at `3.11-beta1` (and this tag has to be added to the list of ignored tags, which already contains `3.3` `3.6-branch-point` `3.4branchpoint`)

A potential route out of this could be to switch to a tagging theme without the conventional prefix `Version-`, or deleting/replacing the `3.11-beta1` tag.

Looking at the output of `git ls-remote -t https://github.com/supercollider/supercollider` I also see many random tags, that should be subject to removal/renaming as they serve no versioning purpose or are not following the `Version-` convention.

## Environment

* SuperCollider version: n/a
* Operating system: Arch Linux
* Other details (Qt version, audio driver, etc.): n/a

## Steps to reproduce

```bash
git ls-remote -t https://github.com/supercollider/supercollider
```

## Expected vs. actual behavior

* All tags are done with the conventional `Version-` prefix.
* Tags without the conventional `Version-` shadow the ones with.

**Comment by brianlheim** [comment]
i'm aware of this and have asked @joshpar to fix it at his convenience

**Comment by joshpar** [comment]
I should have this done later today.
Josh

/*
Josh Parmenter
www.realizedsound.net/josh
*/

**Comment by brianlheim** [comment]
done now!
