### ISSUE TITLE
Building 3.11 issues: Ubuntu 18.04.4 LTS

### ISSUE THREAD

**Issue by derekxkwan** [supercollider/supercollider#4867]
Recently updated to on Ubuntu 18.04.4 LTS (finally) and running into a few issues building 3.11:

`[ 94%] Creating byte-compiled Emacs lisp /home/dxk/scstuff/repos/supercollider/build/editors/sc-el/el/sclang.elc
/usr/local/bin/emacs: error while loading shared libraries: libMagickWand-6.Q16.so.2: cannot open shared object file: No such file or directory
editors/sc-el/el/CMakeFiles/sclang.elc.dir/build.make:60: recipe for target 'editors/sc-el/el/sclang.elc' failed
make[2]: *** [editors/sc-el/el/sclang.elc] Error 127
CMakeFiles/Makefile2:4150: recipe for target 'editors/sc-el/el/CMakeFiles/sclang.elc.dir/all' failed
`

I do use emacs with sc but i tried to disable the SC_EL option anyways in building sc but still running into this error. `libmagickwand-6.q16-2` seems to be a thing in the repos for 16.04? but not 18.04.

The build also seems to have trouble finding `libudev.so`. it looks for it in `/usr/lib/x86_64-linux-gnu/libudev.so` even though in cmake `UDEV_LIBRARIES` is set to `/lib/x86_64-linux-gnu/libudev.so`. copying the files over/symbolic linking seems to work but maybe a hacky solution (not sure whether it's my install of ubuntu installing `libudev.so` in a weird place...

` 66%] Built target libsclang
make[2]: *** No rule to make target '/usr/lib/x86_64-linux-gnu/libudev.so', needed by 'lang/sclang'.  Stop.
CMakeFiles/Makefile2:3804: recipe for target 'lang/CMakeFiles/sclang.dir/all' failed
make[1]: *** [lang/CMakeFiles/sclang.dir/all] Error 2
`

**Comment by brianlheim** [comment]
the emacs issue is already fixed for 3.11.1. you can update the scel submodule to the latest master to fix it if you want. regarding libudev i would recommend starting from a clean build directory and configuring with scel disabled, then trying to build again.

**Comment by derekxkwan** [comment]
got it compiled, thx!
