### ISSUE TITLE
Object:writeDefFile creates hidden files in the synthDefDir

### ISSUE THREAD

**Issue by salkin-mada** [supercollider/supercollider#4873]
## Environment

* SuperCollider version: 3.11.0-4
* Operating system: Arch Linux
* Other details (Qt version, audio driver, etc.): n/a

## Steps to reproduce

```supercollider
// this creates a dotted/hidden synthdef in "SynthDef.synthDefDir"
nil.writeDefFile("");
```

## Behavior

like `.store` it should throw an error instead of creating a hidden file in the "SynthDef.synthDefDir"

**Comment by brianlheim** [comment]
sounds reasonable to me! feel free to submit a patch.
