### ISSUE TITLE
scsynth scans hidden __MACOSX folders on macOS

### ISSUE THREAD

**Issue by jamshark70** [supercollider/supercollider#4877]
## Environment

* SuperCollider version: 3.10.3
* Operating system: macOS 10.14.4

## Steps to reproduce

Forwarding for investigation.

There is a [report on the toplap live coding forum](https://forum.toplap.org/t/supercollider-plugins-error/1246) of a SC installation on Mac scanning plugins in the Mac hidden metadata folders:

```
*** ERROR: dlopen ‘/Users/xyz/Library/Application Support/SuperCollider/Extensions/__MACOSX/SC3plugins/AYUGens/._AY_UGen.scx’ err ‘dlopen(/Users/xyz/Library/Application Support/SuperCollider/Extensions/__MACOSX/SC3plugins/AYUGens/._AY_UGen.scx, 2): no suitable image found. Did find:
/Users/xyz/Library/Application Support/SuperCollider/Extensions/__MACOSX/SC3plugins/AYUGens/._AY_UGen.scx: file too short
/Users/xyz/Library/Application Support/SuperCollider/Extensions/__MACOSX/SC3plugins/AYUGens/._AY_UGen.scx: file too short’
```

## Expected vs. actual behavior

Expected: scsynth should ignore macOS specific hidden folders and files (__MACOSX, ._blah.scx).

Actual: It's trying to read them as normal directories.

I don't remember this coming up before, so, logging as a new issue.

**Comment by brianlheim** [comment]
i fixed the original issue, by the way, it was more to do with apple than SC. personally i think with cross platform apps, simpler is better here but since sclang already skips over some notion of hidden files and folders scsynth's behavior should be consistent with that. however, now we have 3 different platforms' notions of hidden file and folder. should they all be skipped on every platform?

**Comment by jamshark70** [comment]
Since it's avoidable and it hasn't been a common problem, I think it's not very high priority and could be closed.

With that said, trying to dlopen plugin files that we can predict will not be valid based on the path (contains "__MACOSX" or matches regexp `\._.*\.scx`) does seem like a bug.

AFAICS it would be an easy fix. We already check `SC_Filesystem::instance().shouldNotCompileDirectory(path)` here:

https://github.com/supercollider/supercollider/blob/develop/server/scsynth/SC_Lib_Cintf.cpp#L385

So the macOS filesystem could check for the hidden directory in that function.

**Comment by brianlheim** [comment]
> Since it's avoidable and it hasn't been a common problem, I think it's not very high priority and could be closed.

sounds good to me. i see this as part of a larger design issue (path management in sc) and in that context keeping this ticket around is not especially helpful either.
