### ISSUE TITLE
MacOS: String:runInTerminal doesn't open a terminal window

### ISSUE THREAD

**Issue by dkmayer** [supercollider/supercollider#4878]
This is an issue my colleague Gerhard Eckel has reported to me. OSX 10.13.6, SC 3.11.0

E.g.

```supercollider
"ls Library".runInTerminal
```
It works still for me in SC 3.10.4 though, Gerhard suggested this fix

...
			file.close;
			fpath = fpath.escapeChar($ );
...

**Comment by dyfer** [comment]
thank you @dkmayer for the report! 
fixed in #4880 
the fix will go into 3.11.1
