### ISSUE TITLE
SC audio cuts out with no errors

### ISSUE THREAD

**Issue by dariushde** [supercollider/supercollider#4902]
Hi everyone!

I'm having a weird issue. The issue occured on SuperCollider v10.0.3 so I downloaded the latest version and the issue is still there.

When I start playing around with my patch in SC (couple of pbinds and synths running at the same time) the audio abruptly cuts out with no errors and won't come back on unless I do a hard stop + reboot. I tried a simple {SinOsc.ar()}.play; after the audio cut out to see if the issue was with my synths and/or pbinds, but that wasn't the case.

Any idea how I can fix this issue?! any and all help would be greatly appreciated!!

Thank you

**Comment by jparmentervf** [comment]
Which operating system are you using? It sounds like you are sending an 'inf' to the sound card, and then it can't recover. Can you post a sample of the patch that is causing the initial problem?

**Comment by dariushde** [comment]
> Which operating system are you using? It sounds like you are sending an 'inf' to the sound card, and then it can't recover. Can you post a sample of the patch that is causing the initial problem?

I think you're spot on with your diagnoses. I removed the suspicious Synthdef that might send 'inf' to the sound card and the issue went away. Now the problem is: I don't know what is causing this error with my synthdef. I'm going to copy the synthdef code here for you to check. I really appreciate it, Joshua! Thank you
`(SynthDef(\noise,{
	arg mul= 1, ggate=0, time=1, caps=0, smr=0, atk = 0.05;
	var sig, env;
	sig = Latoocarfian2DL.ar(
		11025,
		48000,
		Henon2DC.kr(rrand(30,60),LFNoise1.kr(rrand(0.3,1.2)).range(rrand(250,300),rrand(500,600)),1.03, 0.36),
		LFNoise1.kr(rrand(5,10)).range(3.35,4),
		LFNoise1.kr(rrand(0.1,0.3)).range(0.3,0.4).round(0.10), 0.01,
		mul:0.6);
	env = EnvGen.kr(Env.new([0,1],[atk], rrand(3,6)));
	sig = OnePole.ar(sig,EnvGen.kr(Env.new([0,0.998],[rrand(0.1,0.3)],3, 1),caps),0.98);
	sig = NLFiltC.ar(
		sig,
		0.6,
		-0.04,
		0.2,
		0.2,
		LFCub.kr(10, 0.9 * pi, 10, rrand(10,500)));
	sig = WaveLoss.ar(sig,EnvGen.kr(Env([0,rrand(60,90),rrand(30,60),rrand(30,50),0],[time,time+time*2,time,time+time*3],rrand(-10,10)), smr, doneAction: 0),100,2);
	sig = WaveLoss.ar(sig,EnvGen.kr(Env([0,rrand(60,90),rrand(20,60),90,100],[time,time+time*2,time,time+time*3],rrand(-10,10)), ggate, doneAction: 2),100,2);
	sig = MembraneCircle.ar(sig,LFNoise1.kr(0.1).range(rrand(0.020,0.045).round(0.001),rrand(0.050,0.095).round(0.001)),0.985);
	sig = LeakDC.ar(sig);
	sig = sig * env;
	sig = OffsetOut.ar(0,sig);
}
).add;)`

**Comment by dariushde** [comment]
Just in case the code above is messy, here's the attached sc file with the synthdef.
[synthdef.scd.zip](https://github.com/supercollider/supercollider/files/4553768/synthdef.scd.zip)

**Comment by dyfer** [comment]
@dariushde I edited your comment for code formatting. You can use
\```supercollider

\```
for code blocks

**Comment by dyfer** [comment]
I don't know what the problem is but you might want to take a look at the `Sanitize` UGen - it should replace any problematic values with zero. I'd try putting that before the `OffsetOut` maybe?

**Comment by jamshark70** [comment]
I'll guess it's NLFiltC -- help says:

> Implements the filter Y{n} =a Y{n-1} + b Y{n-2} + d Y^2{n-l} + X{n} - c described in Dobson and sigmoid clipping. **This filter is inherently unstable**, so pick some sane values and move slowly from there.

By using random coefficients, there's a very high probability of getting the filter into an unstable state.

**Comment by dariushde** [comment]
You guys are really badass for how quickly you were able to fix the issue. I really appreciate it!!
I applied both solutions and it totally resolves the issue. I'll definitely be using Sanitize from now on!

Thanks again, everyone.

Cheers
