### ISSUE TITLE
boost/sync doesn't compile with latest boost (1.73.0)

### ISSUE THREAD

**Issue by brianlheim** [supercollider/supercollider#4914]
Logging this before @dvzrv gets a chance :)

## Environment

* SuperCollider version: develop
* Operating system: arch linux

## Steps to reproduce

Tried compiling supercollider with the latest source release of boost (downloaded from the boost website, as it's not yet in arch's pacman repos).

## Expected vs. actual behavior

Use of BOOST_THROW_EXCEPTION_CURRENT_FUNCTION in boost/sync causes compilation to fail. I don't have a full error log, but the errors all centered around that macro, which appears to have been removed from boost recently.

## Possible & proposed solutions

after some analysis, i think the best way forward would be to remove boost::sync as a dependency and replace its usage with official boost objects. this is how i see it:
- patching boost.sync ourselves is a last resort
- using existing boost.sync with 1.73 is impossible
- using newer boost.sync with our current 1.66 doesn't work (i tried)
- finding a version of boost.sync that builds with 1.66 and 1.73 is just delaying the inevitable and also time consuming
- we don't want to bump boost in 3.11 branch from 1.66 to 1.73, because that could cause bugs and/or change behavior and we don't want to introduce instability to 3.11.x releases
- ~boost.sync is only used for its `semaphore`, which boost.interprocess contains since 1.66 in [interprocess_semaphore](https://www.boost.org/doc/libs/1_73_0/doc/html/boost/interprocess/interprocess_semaphore.html). i would wager they might even be the same implementation, since the interprocess header is under a directory called "sync".~
- ~so, porting over the boost sync code should be very easy and safe, even in 3.11. then both 3.11 and develop can build with a system boost at 1.73.0 if desired; and at the same time we manage to lose a dependency!~

**Comment by dyfer** [comment]
Since removing boost_sync doesn't seem to be the right option per discussion in #4918, what should we do with this issue? Is this an upstream issue with boost itself?

**Comment by brianlheim** [comment]
the solution is to update boost_sync

**Comment by brianlheim** [comment]
ok, coming back to this now after reviewing #4986 -- it's a little more complicated.

on develop, we should simply update boost and boost_sync to their latest versions.

on 3.11, it would be nice if there is a version of boost_sync compatible with both 1.66 and 1.73. i don't know if such a version exists. if not, [this commit](https://github.com/supercollider/supercollider/pull/4986/commits/43b2b27c14186a9a3eff917d7598751ed298ae20) presents a workaround.

**Comment by marcan** [comment]
I moved the aforementioned commit to #4990, so that #4986 can be merged as-is into develop. Feel free to merge if you choose to use it on 3.11, otherwise feel free to close it. Just didn't want it to get lost in #4986.

**Comment by TristanCacqueray** [comment]
Here is a build log of supercollider-3.10.4 + 56cdef47103ec39727c735d371a861e6d308f851 and boost-1.73.0 : https://kojipkgs.fedoraproject.org/work/tasks/9513/45259513/build.log

If fixing that in 3.10.4 is not an option, then I can have a look at updating the next fedora version to 3.11.0

**Comment by marcan** [comment]
I think the same patch in #4990 should work on 3.10.4, given that log.

**Comment by TristanCacqueray** [comment]
Thank you @marcan, here are successful build logs of supercollider-3.10.4 with boost-1.73.0 using bf464b68842d5709b9104f5d44f1079b92670f56 and 56cdef47103ec39727c735d371a861e6d308f851 here: https://koji.fedoraproject.org/koji/taskinfo?taskID=45325368  (the rpm spec and patches are located here: https://src.fedoraproject.org/rpms/supercollider/tree/master ).

**Comment by brianlheim** [comment]
this is fixed by #4990. i will work on updating to latest boost & boost_sync in develop when i get a chance! thanks @marcan and @TristanCacqueray !
