### ISSUE TITLE
Supernova /d_loadDir does not ignore non-scsyndef files

### ISSUE THREAD

**Issue by jamshark70** [supercollider/supercollider#4916]
## Environment

* SuperCollider version: 3.11
* Operating system: Any

## Steps to reproduce

```supercollider
Server.supernova;

// start clean
(SynthDef.synthDefDir +/+ "testMD.*").pathMatch.do(File.delete(_));

(
SynthDef(\testMD, { |out, freq = 440|
	Out.ar(out, SinOsc.ar(freq));
}).store;
)

// scsyndef file without corresponding txarcmeta file, OK
s.boot;

(
SynthDef(\testMD, { |out, freq = 440|
	Out.ar(out, SinOsc.ar(freq));
}, metadata: (specs: (freq: \freq))).store;
)

// scsyndef file WITH corresponding txarcmeta file:
s.reboot;

Exception when reading synthdef: corrupted synthdef
Exception when reading synthdef: corrupted synthdef
Exception when reading synthdef: corrupted synthdef
... over 15000 times (!)

// or, same error
s.sendMsg("/d_loadDir", SynthDef.synthDefDir);
```

## Expected vs. actual behavior

scsynth checks the file extension before trying to load a SynthDef file. If it isn't "scsyndef" then it ignores the file.

supernova appears not to include this check.

So,

Expected: Don't try to load something that you know in advance won't be in the right format.

Actual: Tries to load everything.

This is more of an issue in 3.11 because we are now writing metadata files to disk by default. Previous versions did not. (This affects *only* SynthDefs written to disk, which is already a minority of cases, and of those, only SynthDefs with contents in the metadata. But this has been reported for dkmayer's miSCellaneous library... so we have to fix it. Should be easy.)

(In some cases, supernova might crash. In the above test case, it doesn't.)

**Comment by dkmayer** [comment]
> This affects only SynthDefs written to disk, which is already a minority of cases, and of those, only SynthDefs with contents in the metadata. But this has been reported for dkmayer's miSCellaneous library

But my SynthDefs don't contain metadata. Their \ir rates arg is also irrelevant, so is something causing a false metadata writing ?!
Might it be that now metadata files are written to the synthdef folder on OSX and to another place on Linux ? (#4872)

**Comment by dyfer** [comment]
#4917 closes this. But feel free to continue discussing (maybe better in #4872, or open a new issue) if there's a problem with writing the metadata.

**Comment by jamshark70** [comment]
> But my SynthDefs don't contain metadata.

As of 3.11, a metadata file will be written when a SynthDef is `.store`d and its `metadata.size > 0`. Previously, the user would also have to specify a metadata plugin -- the default was a dummy plugin that doesn't write anything. The default now is the text archive metadata plugin.

So there are two possible explanations:

- Your SynthDefs always had metadata, but they were not written to disk before.

- Or, scztt's recent changes to NamedControl building introduce metadata into your SynthDefs that didn't exist before.
