### ISSUE TITLE
consider using vcpkg on Windows

### ISSUE THREAD

**Issue by dyfer** [supercollider/supercollider#4928]
Per discussion below, let's use this thread to discuss possible switch to using vcpkg for dependencies on Windows. Relevant portion of the comment from @brianlheim  to follow

------------

### vcpkg

vcpkg is definitely worth another look based on what i'm seeing and what you said here. i searched around for what other people in C++ think of vcpkg, and based on [this reddit thread](https://www.reddit.com/r/cpp/comments/gch3i5/your_thoughts_on_vcpkg/), it seems they are still working on some basic core features, and given that we already have a workflow with submodules that works OK, i am somewhat hesitant to say let's go ahead and spend time switching everything over. it would be really helpful to know if other people have used vcpkg and what their experience was.

> They have Qt too, but last time I looked webengine was missing.

it appears to be present now - https://repology.org/project/qt/versions - but at 5.12.8, not 5.14. perhaps they are sticking to LTS intentionally. in any case, Qt is the least difficult part of the Windows build to configure, in my experience. if we can use vcpkg for fftw3, readline, libsndfile, and portaudio, that would be a huge simplification to our build process!

also, for reference i see that vcpkg is available on Appveyor build machines by default, but not in Travis's beta Windows support, where they do have chocolatey.

_Originally posted by @brianlheim in https://github.com/supercollider/supercollider/pull/4925#issuecomment-628332780_

**Comment by bagong** [comment]
I'll put in some anecdotal info: I remember better now that the problem with portaudio was not fundamentally getting it to build on Windows using MinGW, but doing so using cmake. Quite some time back the PA maintainers decided that they'd accept in (without a commitment to support) cmake build scripts for the MS toolchain, and stick to their old unixy build tools for MinGW. I don't think that has changed until now, so I *suspect* moving away from the current SC repo might make it more complicated for those who build "server-only" using one of the MinGW flavors (not sure how many there are). Within the MinGW-world the PA maintainers have even shown themselves unappreciative of MSYS2, the "other Windows homebrew" that has established itself well during the last decade or so.
As to VCPKG, I know that libsndfile made very active moves to support cmake and establish vcpkg as their - let's say - distribution channel for an easy but rich and consistent build system, with the potential to become a provider for binaries. Using libsndfile through vcpkg gives an easy alley to additional audio file-formats added to libsndfile through indirect dependencies (the Xiph.org stuff can be pulled in with a flag), very much the same way it is done on MacOS and Linux. I think the fftw3 and PA packages have little connection to the maintainers of the original projects, but then I found that the vcpkg maintainers were extremely responsive to community input, even actively helpful ;-). Not sure if that is bound to change (or already has ;-)). Establishing vcpkg was obviously part of MS' move towards the Unix world and Open Source. The move might have created something some perceive as threatening competition to another, but quite different package manager called Conan. When I read discussions belittling vcpkg's achievements in public fora, surprisingly often Conan is brought in as the "real thing" - while I've found Conan is much more geared at the enterprise market and cross platform considerations, while VCPKG makes it easy to add libraries from the unixy world to VS projects (at the time MS established VCPKG they also deepened cmake support within VS). All in all VCPKG seems to me like an amazing fit to SCs requirements. Not sure though, what its long term outlook is, and if some good competition has arisen in the past years. (Chocolatey seemed to be quite a different animal in the past, more like the "cask" part of homebrew, or the actual packages in the Linux world, not the libraries, as supplied by VCPKG. Not sure if that has changed, Chocolatey certainly seemed very alive when I was aware of it).

**Comment by dyfer** [comment]
That's interesting, thanks.

Re: cmake: It seemed that the CMake build in PA worked fine (now this sentence seems like it should be put in the PR thread... but let's keep the larger discussion here). I built SC with upstream PA using both MSVC and MinGW from QT... do we need to consider more build environments?

Also, forgive my ignorance, what is the workflow to use MSYS (or MSYS2) to build SC? If I install MinGW with/from QT, that's not MSYS, right?

Thinking more about PA itself, I think it might be useful to keep at least the option to built it from source to be able to get the latest version (as opposed to the released one or one available in vcpkg or elsewhere). I think something like `USE_SYSTEM_PORTAUDIO` CMake option would make more sense, instead of platform switch (the default would still be set depending on the platform, at least until we figure out the package manager situation on Win).

**Comment by bagong** [comment]
As I won't get involved in the actual switch I won't promote anything here, just provide background from memory: I am surprised the cmake build of vanilla PA works with MinGW as provided by Qt. That's good! MSYS, or its - now, I guess - effective successor MSYS2 add a unixy shell on top of MinGW so that you can move around unix style and use unixy build tools that wouldn't work in a Windows shell. Additionally you get a pacman clone as package manager. This used to be relevant when SCWin was distributed as MinGW builds, because using MSYS2 to assemble the dependencies would make things a lot easier and consistent. MSYS2 seemed to develop into a de facto standard for MinGW builds on Windows, and was as comfortable to use as a Linux distribution. Nowadays, especially since webengine is not available in MinGW, that's not so relevant any more for SC. The question of building PA in MSYS2 is even less relevant now, as MSYS2 does provide binary packages of PA (which aren't used though in the current setup of SC's Windows build system, because PA is set to be built regardless of environment there).

**Comment by brianlheim** [comment]
it doesn't seem like there's been enough team interest in this to warrant keeping the ticket open. perhaps worth revisiting in a year or two.
