### ISSUE TITLE
Array.mirror1 with size==1 returns an empty array

### ISSUE THREAD

**Issue by elgiano** [supercollider/supercollider#4930]
## Environment

* SuperCollider version: 3.11
* Operating system: Arch Linux

## Steps to reproduce

```supercollider
[60].mirror1 
// Expected -> [60]
// Actual -> [ ]
```

## Expected vs. actual behavior
From Help:
Return a new Array which is the receiver made into a palindrome with the last element removed. This is useful if the list will be repeated cyclically, the first element will not get played twice

I don't think it's a valid behavior to empty a sequence with only one element. A valid palyndrome in that case would be the unchanged sequence, since if the sequence is one element long, then the first element would be played only once per cycle.

[60].mirror // -> [60]
[60].mirror1 // -> [60]
[60].mirror2 // -> [60,60]

## Proposed fix
- just redirect mirror1 to mirror if size == 1 (easy)
- or add a check in the related primitive (more proper?)

**Comment by brianlheim** [comment]
thanks! i agree, it's more useful and predictable for [x].mirror1 to return [x]. the documentation should be clarified a bit too, right now it sounds like returning [] is the correct behavior. i haven't looked at the code for this but if the implementation can all be kept in a single place that's best. feel free to submit a patch!

-------- Original Message --------

**Comment by elgiano** [comment]
Yes, it looks like the mirror primitive needs some attention anyway (#4931). So I guess that's the way to go, I'll look into it :)
