### ISSUE TITLE
Server's `wait` method doesn't wait inside a Routine.

### ISSUE THREAD

**Issue by tsmtzs** [supercollider/supercollider#4942]
## Environment

* SuperCollider version: 3.11.0
* Operating system: Arch Linux 5.6.2
* Other details (Qt version, audio driver, etc.):

## Steps to reproduce

```supercollider
Server.default.boot;

(
SynthDef(\sendMsg, { |time = 3|
	var line;

	line = Line.kr(0, 1, time, doneAction: Done.none);

	SendTrig.kr(Done.kr(line));
	// SendReply.kr(Done.kr(line), '/name');

	0.0
}).add;
)

(
var server = Server.default;
var time = 2;

Routine({
	var synth;

	synth = Synth.basicNew(\sendMsg, server);

	server.sendMsg(*synth.newMsg(args: [\time, time]));

	"Synth started.".postln;

	server.wait('/tr');
	// server.wait('/name');

	"Stopped after % secs?\n".postf(time);

	server.sendMsg(*synth.freeMsg);
	
}).play;
)
```

## Expected vs. actual behavior
Currently, the `Routine` instance doesn't wait for server's message. 
`Server`'s `wait` method is defined as (lines 763 - 768):
```supercollider
wait { |responseName|
		var routine = thisThread;
		OSCFunc({
			routine.resume(true)
		}, responseName, addr).oneShot;
}
``` 
I think that a line with
```
nil.yield
```
_after_ the OSCFunc, is all that is required.

**Comment by jamshark70** [comment]
It should really use `Condition` (which didn't exist at the time `wait` was originally implemented). `Condition` (I think) tries to resume the thread on the clock where it was playing before; the `routine.resume` here will not do that.

There's also no way to clean up the OSCFunc in case of failure. So this method probably needs a more thorough review.

FWIW I found James McCartney's original commit of this method and it *did* do `true.yield` at the end. This was accidentally removed at some point, but I couldn't find it in the history.

**Comment by tsmtzs** [comment]
So, after jamshark70, something like
```supercollider
wait { |responseName|
		var routine = thisThread;
                var condition = Condition.new;
		OSCFunc({
			condition.test = true;
                        condition.signal
		}, responseName, addr).oneShot;

                condition.wait
}
```
for `Server`'s `wait` implementation might be a better approach?

**Comment by jamshark70** [comment]
IMO Condition `hang` and `unhang` are better if it's only used as a pause mechanism. (The test isn't actually used as a test.)

**Comment by tsmtzs** [comment]
@jamshark70  I suppose that you mean something like 
```supercollider
wait { |responseName|
	var routine = thisThread;
	var condition = Condition.new;
	OSCFunc({
		condition.unhang
	}, responseName, addr).oneShot;

	condition.hang;
}
```
On the other hand, the pattern with `Condition`'s `test` value and `wait`, `signal` messages is used in the methods `sendMsgSync`, `bootSync` of `Server`.  Should a similar approach be used in all three cases?

**Comment by jamshark70** [comment]
> On the other hand, the pattern with Condition's test value and wait, signal messages is used in the methods sendMsgSync, bootSync of Server.

In one sense, it doe

**Comment by jamshark70** [comment]
> On the other hand, the pattern with Condition's test value and wait, signal messages is used in the methods sendMsgSync, bootSync of Server.

In one sense, it doesn't matter: `unhang` is the same as `signal` when the test is true. When using Condition as a pause mechanism only (without waiting for an external condition), I personally prefer `hang` and `unhang` for being semantically clearer. (The `test` is really for the case where, for example, you want one or more threads to wait for another thread to finish loading a number of buffers. The waiting threads `wait` on the same Condition object. The buffer loader increments a counter and `signal`s the condition -- a `Condition(counter >= numBufs)` will fire only when the condition is met. There's no need to invoke that semantic baggage in this case.)

The existing uses might predate the existence of `hang` and `unhang`; I don't think they should be taken as prescriptive.

(Sorry for the mobile phone finger slip awhile ago -- the "Close and comment" button is in a dangerous place for mobile use.)

**Comment by telephon** [comment]
looks good to me. Also no need for the `var routine = thisThread;` line anymore.

**Comment by tsmtzs** [comment]
@telephon Yes, indeed!
@jamshark70  Many thanks for your helpful comments! I think you 're right about `hang` and `unhang`. As far as I can get it, they 're more "_economical_" than `wait`, `signal` and `test`, in cases like this. But I' ll stick, for start, with the later approach opening a PR. Maybe some comments from the other developers are needed before closing this issue. The word `wait` has a conceptual effect on me that is more suitable for a thead that _runs_ on a clock.
