### ISSUE TITLE
String.splitext splits path components with dot characters

### ISSUE THREAD

**Issue by frozenbears** [supercollider/supercollider#4944]
## Summary

When fed a path, the splitext method will interpret dot characters in a directory as the beginning of a file extension. If there is no extension at the end of the path, the components will be split incorrectly. This is problematic for users whose home directory structure follows the convention below:

`/Users/firstname.lastname/`

## Environment

* SuperCollider version: 3.11.0
* Operating system: macOS Catalina
* Other details (Qt version, audio driver, etc.): N/A

## Steps to reproduce

```supercollider
"foo.bar/baz".splitext
--> [ foo, bar/baz ]
```
## Expected vs. actual behavior
My expectation would be that the result of the above method call should be `[foo.bar/baz, nil]`. I originally encountered this when playing a large anonymous SynthDef, which failed with an error message about not being able to write a txarcmeta file, and realized it was trying to write it to `/Users/myFirstName`, instead of `/Users/myFirstName.LastName/Library/Application Support/Supercollider/synthdefs/`. I expect it's a potential issue elsewhere as well.

I wasn't sure whether this is a known issue or expected behavior for some reason I'm not aware of. I patched it on my machine by adding an early return in splitext, e.g.

```
splitext {
	var sep = thisProcess.platform.pathSeparator;
	block{|break|
		this.reverseDo({ arg char, i;
			// Break after the first path separator
			if ((char == sep), {break.value;});
			if (char == $\., {
				^[this.copyFromStart(this.size - 2 - i), this.copyToEnd(this.size - i)]
			});
		});
	}
	^[this, nil]
}
```

This is my first time contributing, so let me know if this is off base. If it's legit, I can open a PR.

**Comment by jamshark70** [comment]
IMO legit. We should definitely not search for the first dot, but rather the last.

`block { ... }` isn't strictly necessary because `^` already exits early from the loop.

**Comment by frozenbears** [comment]
Thanks @jamshark70. I'll open a PR later today.

**Comment by brianlheim** [comment]
thanks @frozenbears for opening and fixing this!
