### ISSUE TITLE
server not booting with scide, jack, and linux when jack isn't already running

### ISSUE THREAD

**Issue by garpu** [supercollider/supercollider#4945]
## Environment

* SuperCollider version: 3.11.0
* Operating system: Linux, slackware-current (5.4.41)
* Other details (Qt version, audio driver, etc.): qt5 5.13.2, jack2: 1.9.14, supercollider built from Eric Hameleers's package at: http://www.slackware.com/~alien/slackbuilds/supercollider/build/

## Steps to reproduce
Start scide without jack already running.
Boot server.
Server fails with exit code 0.

## Expected vs. actual behavior

Before upgrading to 3.10.4 and 3.11.0, scide would start jack, if it wasn't already running.  Since 3.10.4, the server won't start jack and exit with exit code 0.  If I start jack before starting supercollider, the server will boot, and it will work normally.  

Text from console:

Booting server 'localhost' on address 127.0.0.1:57110.
could not initialize audio.
Server 'localhost' exited with exit code 0.

Contents of my .jackdrc (also same command as I use to start it via command line): jackd -v -R -m -dalsa -r44100 -p128 -n2 -m -D -Chw:M1010LT -Phw:M1010LT

**Comment by elgiano** [comment]
@garpu Thanks for reporting this. 
Are you sure your jack configuration is ok? It boots all right on my linux system. I noticed that in my .jackdrc i have `/bin/jackd` instead of just `jackd`. And if I put only jackd, server doesn't boot. 
Could it maybe be just this?

**Comment by garpu** [comment]
Ah yeah.  I gave jackd a complete pathname in my jackdrc, and it boots fine without starting jack first.  I'll close this one.  Thanks!
