### ISSUE TITLE
NdefGui is in need of some love

### ISSUE THREAD

**Issue by madskjeldgaard** [supercollider/supercollider#4952]
Hello everyone

I am a hardcore user of the NdefGui and I have always loved it, but I have come to the conclusion that it needs some love and modernization plus a few bug fixes. This issue is an attempt to gather some of those (related) problems in one issue, which I hope is not terrible Github etiquette.

For some of the issues, I have some ideas that may turn into PR's at some point but I will post it here to see what everyone has to say on the matter.

I think NdefGui is super important for both testing purposes and accessibility for newcomers to SuperCollider so I hope others feel like me in that this deserves some love.

For those not in the know, this is what I mean:

```supercollider
Ndef(\synthy, {|freq| SinOsc.ar(freq)}).play.gui;
```

## Environment

Using SCNvim as the IDE plus:

* SuperCollider version: 3.11
* Operating system: Arch Linux
* Other details (Qt version, audio driver, etc.): Run on the I3wm

### Text is too small + gets truncated on long names
![ndefgui](https://user-images.githubusercontent.com/22474608/82468095-b76e1800-9ac2-11ea-8e11-b400ed82722e.png)

Perhaps this is OS / PC Specific but at least on my computer, the text is far too small and cramped to be read properly and the parameter labels are almost always truncated

### Strange default specs
For a lot of parameters, the specs that are used as default are somewhat arbitrary. 
For example, when adding a node proxy role filter:
```
Ndef(\test)[1] = \filter -> {|in| in}
```
This adds a \wet1 parameter to the ndef which gets picked up by the NdefGui. But the default scale seems to be from 0.05 to 20.0 and not 0.0-1.0 which should be the natural choice. 

This could be a problem with nodeproxy roles but I am posting it here just in case.

### Not responsive
![2020-05-20-175821_1920x1080_scrot](https://user-images.githubusercontent.com/22474608/82468872-9b1eab00-9ac3-11ea-978a-eae11044323d.png)

When resizing the GUI's window, it is not responsive. 

This could probably easily be fixed by switching to a LineLayout based gui instead, like in this (EXTREMELY SIMPLIFIED) example:

```supercollider
(
Ndef(\yo, {|freq, amp, pan, what|
	var sig = SinOsc.ar(freq) * amp;

	what;

	Pan2.ar(sig, pan)
}).play;

// Gui function
~ndefgui = {|ndef|
	var window, sliders, transport, play, clear, name, scope, fade, fadeLabel;

	var params = IdentityDictionary.new();
	var paramNames = ndef.controlKeys;

	// Populate param dict
	paramNames.do{|paramname| 
		var spec = Spec.specs.at(paramname);
		spec = if(spec.isNil, { [0.0,1.0].asSpec }, { spec });

		params.put(paramname, spec)
	};

	// GUI
	window = Window.new(ndef.key);
	sliders = [];
	params.keysValuesDo{|pName, spec|

		// Slider
		var slider = Slider.new()
		.orientation_(\horizontal)
		.action_({|obj|
			var sliderVal = obj.value;
			var mappedVal = spec.map(sliderVal);
			valueBox.value = mappedVal;
			ndef.set(pName, mappedVal);
		});

		// Label
		var label = StaticText.new
		.string_(pName);

		// Value box
		var valueBox = NumberBox.new();

		// Slider Layout
		var sliderLayout = HLayout([label, s: 1], [slider, s: 4], [valueBox, s:1]);

		sliders = sliders.add(sliderLayout);
	};

	// Transport
	play = Button.new()
	.states_([
		["play"], 
		["stop"]
	])
	.action_({|obj|
		var val = obj.value;

		if(val==1, {
			ndef.play;
		}, {
			ndef.stop
		})

	});

	// Get current play state
	ndef.isPlaying.if({
		play.value_(1)
	}, {
		play.value_(0)
	});

	clear = Button.new()
	.states_([
		["clear"]
	])
	.action_({|obj|
		ndef.clear
	});

	scope = Button.new()
	.states_([
		["scope"]
	])
	.action_({|obj|
		ndef.scope
	});

	fadeLabel = StaticText.new()
	.string_("fade:");

	fade = NumberBox.new()
	.step_(0.01)
	.clipLo_(0.0)
	.clipHi_(100.0)
	.action_({|obj|
		var val = obj.value;
		ndef.fadeTime = val;
	});

	transport = HLayout(
		play, clear, scope, fadeLabel, fade 
	);

	window.layout = VLayout([transport, s:1], *sliders);

	window.front;
};

// Make gui
~ndefgui.value(Ndef(\yo));
)
```

which looks sort of like this:

![2020-05-20-180616_1920x1080_scrot](https://user-images.githubusercontent.com/22474608/82534622-b7fbc280-9b45-11ea-8cf7-0dd520df90ad.png)

**Comment by brianlheim** [comment]
thanks! can you please open these as separate issues so we can track them one at a time?

**Comment by telephon** [comment]
this would be really good. @adcxyz do you already have some sketches?

**Comment by madskjeldgaard** [comment]
> thanks! can you please open these as separate issues so we can track them one at a time?

sure!

**Comment by adcxyz** [comment]
@madskjeldgaard 
- thanks for the detailed list of proposals, 
this is great, and they all make sense!

Generally, NdefGui is quite old now, and back then, FlowLayout and EZSliders and  were the hippest ways to make guis ;-)
To address each one briefly: 
- For switching to JITGuis to Layout style, it would be necessary that the EZGuis work in them, 
as it makes no sense to duplicate them by hand. Don't know how hard that would be, EZGui is rather complex, and does a lot of its own layouting ...
Maybe better rewrite it as LGui, LSlider (L for Layout), 
and push the layouting to the layout classes?

Anyway, currently this fails:
```
w = Window().front;
w.layout = VLayout(EZSlider()); // single test:

w = Window().front;
w.layout = VLayout(*EZGui.allSubclasses); // all of them
```
NdefGui

- text too cramped:
labelWidth could be set with an entry in the NdefGui(... options) argument, I'll think about it. 
I wrote something to shift that border in EZGuis for something, cant remember details now.
- Strange default specs
true, Spec.guess could be smarter; this one is simple. 
I often write something in the startup that adds lot of wet1 ... specs. 
- not responsive while resizing?
what do you mean exactly? is it not updating changing values?

again, thanks!

**Comment by madskjeldgaard** [comment]
I opened up seperate issues for this now:
NdefGui has strange default specs: https://github.com/supercollider/supercollider/issues/4957
NdefGui not responsive: https://github.com/supercollider/supercollider/issues/4956
NdefGui text size issues: https://github.com/supercollider/supercollider/issues/4955

**Comment by madskjeldgaard** [comment]
Thanks for the responses everyone. Let's continue this on the seperate issues :)

**Comment by brianlheim** [comment]
thanks for that @madskjeldgaard !

**Comment by madskjeldgaard** [comment]
No problem :)




On Fri, May 22, 2020 at 1:10 AM +0200, "Brian Heim" <notifications@github.com> wrote:















thanks for that @madskjeldgaard !
