### ISSUE TITLE
Pdef with fading dies on some streams that generate (internal) cleanup, e.g. PmonoArtic

### ISSUE THREAD

**Issue by eleses** [supercollider/supercollider#4954]
## Environment

* SuperCollider version: 3.11

## Steps to reproduce

This was [reported](https://scsynth.org/t/pmonoartic-crossfade-and-synthdef-switch/1447) on the user forum, but seemingly not here yet:

```
Pdef(\one).fadeTime_(2);
Pdef(\one, PmonoArtic(\default, \dur, 0.2, \freq, Pwhite(1,8) * 100 , \legato, 1)).play
Pdef(\one, PmonoArtic(\default, \dur, 0.2, \freq, Pwhite(1,8) * 100, \legato, 0.2 )).play // ok
Pdef(\one, PmonoArtic(\default, \dur, 0.2, \freq, Pwhite(1,8) * 100 , \legato, 1)).play // stops w/err
```

## Expected vs. actual behavior
The first crossfade is ok; the last one is not; the legato-1 synth is inappropriately released, resulting in a lot of `FAILURE IN SERVER /n_set Node XXXX not found…`

## Discussion

I've tried to determine what's causing it, and I can't say for certain beside that it has something to do with cleanups getting evaluated incorrectly. Internally Pdef with non-nil fading does:

```
				Ppar([
					EmbedOnce(
						PfadeOut(stream, fadeTime, delta, tolerance),
						cleanup
					),
					PfadeIn(newStream, fadeTime, delta, tolerance)
				]).asStream
```

Basically the problem is how Pdef reuses its cleaup object internally because the next attempt to "repro" the internal doesn't manage to repro the bug:

```
x = PmonoArtic(\default, \dur, 0.2, \freq, Pwhite(9,16) * 100, \legato, 0.2, \amp, 0.05);
y = PmonoArtic(\default, \dur, 0.2, \freq, Pwhite(1,5) * 100 , \legato, 1, \amp, 0.2);

p = Ppar([EmbedOnce(PfadeOut(x, 5), EventStreamCleanup.new), PfadeIn(y, 5)]).play //ok
```

One needs something closer to what Pdef actually does:

```
// reusing x, y from above
(p = Prout({ |inval|
	var cleanup = EventStreamCleanup.new, stream = x.asStream, oldstr = stream, cnt = 15, outval;
	loop {
		cnt = cnt-1;
		if (cnt == 0) {
			"source swap".postln;
			stream = Ppar([EmbedOnce(PfadeOut(oldstr, 5), cleanup), PfadeIn(y, 5)]).asStream;
		};
		outval = stream.next(inval);
		outval = cleanup.update(outval);
		inval = outval.yield;
	};
}).play) // dies like the initial example
```

Without the `EmebedOnce ... cleanup` this problem goes away, but there are others which pop up, but these are less serious of the double-cleanup type #4806 e.g. 

```
(fork { 
	p = Ppar([PfadeOut(y, 5),  PfadeIn(x, 5)]).play;
	6.wait;
	p.stop; // prints some failure if called after y fully fades (5s)
})

// vs

(fork {
	p = Ppar([EmbedOnce(PfadeOut(y, 5), EventStreamCleanup.new), PfadeIn(x, 5)]).play;
	6.wait;
	p.stop // seems to prevent that failure
})
```

So it might be the case the EmbedOnce was added just for that, but I probably don't fully comprehend its role there.

**Comment by telephon** [comment]
Imagine you have a stream, let's call it `S`. Then you make a new stream with the rest of `S` (let's call it `Pfindur(S)`), and create the new stream with the rest and a new pattern that you have inserted, let's call it `S'` . Then you get `Pseq([Pfindur(S), S'])` (ignoring the conversion pattern to stream for simplicity). If you repeat this, you get an endlessly growing chain of `Pseq([Pfindur(Pseq([Pfindur(Pseq([Pfindur(Pseq([Pfindur(S), S'])), S''])), S'''])), S'''])` etc.

Here, `EmbedOnce` has the purpose to allow the inner stream to be garbage collected once it has reached its end.

I'd also suspect that there is a problem with the cleanup, but not sure where this happens. Maybe you can reproduce the problem in an `EmbedOnce(Pevent(PmonoArtic()).asStream)` alone?

**Comment by eleses** [comment]
Actually, it doesn't matter much what the `y` is in the innards-repro above; it never gets played past the crossfade

``
x = PmonoArtic(\default, \dur, 0.2, \freq, Pwhite(9,16) * 100, \legato, 0.2, \amp, 0.05);	
y = Pfset({}, Pbind(\dur, Pn(0.2, 20)), { "bye".postln })

//p = y.play

(p = Prout({ |inval|
	var cleanup = EventStreamCleanup.new, stream = x.asStream, oldstr = stream, cnt = 15, outval;
	loop {
		cnt = cnt-1;
		if (cnt == 0) {
			"source swap".postln;
			stream = Ppar([EmbedOnce(PfadeOut(oldstr, 5), cleanup), PfadeIn(y, 5)]).asStream;
		};
		outval = stream.next(inval);
		outval = cleanup.update(outval);
		inval = outval.yield;
	};
}).play)
```

**Comment by jamshark70** [comment]
EventStreamCleanup is supposed to be like a function scope, applying to everything contained within. You can't have a parallel-split function scope: in `{ var a, b = { a = a + 1 }, c = { a = a + 2 } ... }`, both `b` and `c` affect the same `a`, and there is no way to make `b` and `c` independent without altering the scoping.

Similarly, if you have more than one stream sharing the same EventStreamCleanup, it's expected that the cleanup will apply to all of them. E.g., in `Pfindur(3.0, Ppar([...]))`, after the three beats, *everything* in the Ppar should be cleaned up. There's no concept of "clean up some of them, but leave others alone."

Here, we have:

- `EmbedOnce(PfadeOut(stream, fadeTime, delta, tolerance), cleanup)` that *should* clean up.
- `PfadeIn(newStream, fadeTime, delta, tolerance)` that should *not* clean up.

This requires two distinct cleanup objects. It will never work with only one EventStreamCleanup instance.

I'm not familiar enough with these internals to make the change myself, but it might look something like this:

```
				// need `var oldCleanup` above
				oldCleanup = cleanup;
				cleanup = EventStreamCleanup.new;
				Ppar([
					EmbedOnce(
						PfadeOut(stream, fadeTime, delta, tolerance),
						oldCleanup
					),
					PfadeIn(newStream, fadeTime, delta, tolerance)
				]).asStream
```

But I can anticipate a problem -- if the old stream manipulates the cleanup, then the Pdef's new cleanup will be updated according to the returned event -- and you're back with the same problem.

So it might require an alternate version of Ppar that maintains multiple, independent cleanups.

**Comment by jamshark70** [comment]
Playing with this a little more -- the other problem is that `cleanup` is local to `embedInStream`, so there is no way, when doing the cross fade, to swap in a new EventStreamCleanup in place of the old one.

Possible solutions might include:

- A stream wrapper for event pattern proxies: the cleanup object would be local to the wrapper object, and there could be an interface to ask it to switch to a new cleanup object.

- Or, add an `era` counter to EventStreamCleanup. Then, somehow, the `EmbedOnce` would have to be able to tell the cleanup only to process its own `era`.

> But I can anticipate a problem -- if the old stream manipulates the cleanup, then the Pdef's new cleanup will be updated according to the returned event -- and you're back with the same problem.

Hm... but maybe that's correct.

![pdef-fade-cleanups](https://user-images.githubusercontent.com/318301/82721207-a523f200-9ced-11ea-8d3f-315d66de4119.png)

A's cleanup is used if you `stop` the Pdef in the middle of the cross fade. In that case, you *want* all the cleanups to execute. "... if the old stream manipulates the cleanup, then the Pdef's new cleanup will be updated according to the returned event" -- it *should* be updated in this way.

The current issue arises because, at present, A and C and E all share the same cleanup object.

The `oldCleanup` idea was supposed to do this at crossfade time:

- C uses the oldCleanup (inheriting any old, un-fired cleanups).
- F (new Pmono) has its own, separate cleanup.
- A has a new cleanup object. Any new cleanups created in both D (e.g. PmonoArtic) *and* F will be added here (necessary for manual stop). So the one remaining thing is that any un-fired cleanups from D should be duplicated in A: `oldCleanup = cleanup; cleanup = EventStreamCleanup(oldCleanup.functions.copy)`.

I think. It's all quite confusing.

**Comment by jamshark70** [comment]
Aha... but... as often happens in programming, sometimes when you invert the problem, the solution presents itself.

In the last couple of messages, I suggested creating a new cleanup for the new pattern that is fading in. But I realized over lunch that the new cleanup could be for the *old* cleanup actions, belonging to the pattern that is fading out. Then there should be no need to alter Pdef's architecture, as its stream can keep using the same EventStreamCleanup that it had been using.

If constrainStream declares `var fadeOutCleanup;`, then the crossfade branch can look like this:

```
				fadeOutCleanup = EventStreamCleanup.new.functions_(cleanup.functions.copy);
				cleanup.clear;
				Ppar([
					EmbedOnce(
						PfadeOut(stream, fadeTime, delta, tolerance),
						fadeOutCleanup
					),
					PfadeIn(newStream, fadeTime, delta, tolerance)
				]).asStream
```

`cleanup.functions.copy` might not need the `copy`, because `cleanup.clear` replaces the IdentitySet anyway. Just being extra careful in this sketch.

So, when the `EmbedOnce` hits the end of the fadeout stream, it runs whatever was in `fadeOutCleanup`, which does not include any cleanups added by the new stream.

```
Pdef(\x).fadeTime = 5;

Pdef(\x, Pmono(\default, \degree, Pwhite(-7, 7, inf), \dur, 0.5, \amp, 0.5)).play;

Pdef(\x, Pmono(\default, \degree, Pwhite(7, 14, inf), \dur, 0.25, \amp, 0.5)).play;

// let the fadeout finish;
// old node is cleared, nothing bad happens to the new one

Pdef(\x).stop;
```

I also tested `Pdef(\x).stop` before the cross fade is complete. Both nodes are stopped, correctly. It took a while to figure out why: `stop` calls `player.stop`, and the EventStreamPlayer has its own cleanup, which is unaffected by the crossfade switcheroo (contains both cleanups). (But if the crossfade finishes, then `\removeFromCleanup` causes the expired cleanup function to be removed from the stream player's cleanup too.) This is all correct behavior.

So the above might be the solution.

**Comment by eleses** [comment]
The lasts bit also because Ppar "merges" the cleanups of its sub-streams, so they both end up passed to the ESP. 

I can confirm this idea (just two cleanups) works correctly with/in my "simulacre" too in all 3 cases (stop called before, during, or after the fade out).

```
x = Pfset({}, Pbind(\dur, 0.3, \degree, 1), { "bye1".postln })
y = Pfset({}, Pbind(\dur, 0.2, \degree, 5), { "bye2".postln })

(p = Prout({ |inval|
	var cleanup = EventStreamCleanup.new, stream = x.asStream, oldstr = stream, cnt = 15, outval, fadeOutCleanup;
	loop {
		cnt = cnt-1;
		if (cnt == 0) {
			"source swap".postln;
			fadeOutCleanup = EventStreamCleanup.new.functions_(cleanup.functions.copy);
			cleanup.clear;
			stream = Ppar([EmbedOnce(PfadeOut(oldstr, 5), fadeOutCleanup), PfadeIn(y, 5)]).asStream;
		};
		outval = stream.next(inval);
		cleanup.update(outval);
		inval = outval.yield;
	};
}).play)

p.stop // do 3 runs: hit before swap; during cross-fade and after
```

**Comment by jamshark70** [comment]
> It seems entirely sufficient to do
> ```
> 			fadeOutCleanup = cleanup;
> 			cleanup = EventStreamCleanup.new;
> ```

I thought so too, but `cleanup` here is local to the method, not to the Pdef object. So switching `cleanup` to a different instance will not affect the instance belonging to the stream player -- it still has both cleanups.

I had tested it like this, and found that it didn't solve the problem. `cleanup` must remain the same object, and be cleared.

**Comment by eleses** [comment]
Yeah, you're right. I missed that `cleanup` is passed as an argument to `constrainStream`...

By the way this fix is necessary only to the Ppar section; the Pseq...Pfindur one (right above in Pdef.constrainStream) doesn't need it because the `newStream` there doesn't start to emit anything (so can't set/send any cleanups) until the previous entry in Pseq is completely done and has executed its cleanups.

```
					Pseq([
						EmbedOnce(
							Pfindur(delta, stream, tolerance).asStream,
							cleanup // ok like this
						),
						newStream
					]).asStream
```

**Comment by telephon** [comment]
Btw. thank both of you for this detective work. I am never sure I understand this cleanup system! Please do feel free to make a PR if you think you have solved the issue.

Sometimes I thought about moving the functionality out into a dedicaced class - the method is pretty complicated.

**Comment by eleses** [comment]
@telephon While the fix itself for this is only a couple of lines, the catch is that is if I also write a unit test for this fix, it would have issues with the double cleanup bug at the moment (#4806). (And the hold-up with that is what to do with Thunks at the moment... should we have hacky Thunk that works well for cleanups but could be confusing for users in other contexts... or roll a separate class. More input on that wouldn't hurt.)

Presumably I could just write a partial test for this for now, which instead of fully checking that the proper cleanups called in all 3 cases (stop called before, during or after xfade is complete), would only check that there's no *premature* cleanup called for the 2nd stream (the one used as replacement), but would ignore other issues (like the number of cleanups called).

**Comment by telephon** [comment]
You could open a separate issue that notes the missing test and the reasons for it. 

Do you have a pageful of informal, practical tests that make sure everything works fine? If the change in the code is well readable it should be OK as a first step.

**Comment by eleses** [comment]
I've been trying to write a unit test for this, but Pdef "is not your usual pattern". Swapping a Pdef's source while a stream is insantiated from it seems to bomb out with an error. The kind of test I want to do

```
Pdef(\one).fadeTime_(2);
Pdef(\one, Pbind(\dur, 0.3, \degree, 1)).play
Pdef(\one, Pfset({}, Pbind(\dur, 0.2, \freq, 440), { "bye".postln })).play
```

But since the test suite runs serverless, I though to pull events with `next()`. Alas:

```
Pdef(\one, Pbind(\dur, 0.3, \degree, 1))
r = Pdef(\one).asStream
r.next(())
Pdef(\one, Pfset({}, Pbind(\dur, 0.2, \freq, 440), { "bye".postln }))
r.next(())
//  ERROR: binary operator '*' failed. RECEIVER: nil
```

**Comment by eleses** [comment]
Basically, this is the unit test I'm going to do (although it's not written as a unit test below) as easy enough to understand

```
(
p = EventPatternProxy.new.fadeTime_(2);
p.source = Pbind(\dur, 1.1, \degree, 1, \amp, 0.1);
r = p.asStream;
r.next(()).postln; // << necessary to prime the old stream
p.source = Pdef(\one, Pfset({}, Pbind(\dur, 1.3, \freq, 440, \amp, 0.4), { "bye".postln }));
// Pull enough events to exhaust the xfade.
// There should NOT be a cleanup of the 2nd stream executed,
// since it's an infinite stream (of the same event).
// Three more events should be enough to pull here to
// end the cross-fade, but "just in case" we pull 6.
6 do: { r.next(()).postln};
)
```

**Comment by telephon** [comment]
> I'm not sure what is the exact (extra) dependency of fadeTime on Event.default.

It is in `PfadeOut` and `PfadeIn` – should be very easy to fix, so we don't have to assume that the pattern is used with a standard default event.

**Comment by eleses** [comment]
Well, the cross fade (PfadeOut and PfadeIn) need to change the `amp` to be meaningful, so I think they're actually ok the way they are, i.e. no more "standard" (Event.default) fields are assumed than strictly necessary for an actual fade.

**Comment by telephon** [comment]
What about just adding an instance variable `<>defaultAmp = 0.1`?

```supercollider
outval[\amp] = c.max(0) * (outval[\amp] ? defaultAmp)
```

I think this would make sense.

**Comment by eleses** [comment]
> What about just adding an instance variable <>defaultAmp = 0.1?

I don't feel strongly about this either way, and it's a side-issue at point, but I kinda preferred that they did error (as they do) rather than used some (yet another) default value that one has to keep track of where it can come from... (Having to [deal with](https://scsynth.org/t/where-does-the-magic-frequency-261-6255653006-come-from/2177) Events.defaults being different that those one sets up in a SynthDef is already annoying enough for me in that department. If event Patterns started doing this too, i.e. provide various defaults, it could get "out of hand" in terms of keeping track where some data may have originated.)

**Comment by telephon** [comment]
> but I kinda preferred that they did error (as they do) rather than used some (yet another) default value that one has to keep track of where it can come from...

You are right, that makes sense. So let's leave it as it is.

**Comment by eleses** [comment]
I'll leave a note here that person who first reported this bug says (on the forum link in the initial report) that this fix didn't work for them. I have no idea why. It worked for me in literally all the instances of SC I've patched with this.
