### ISSUE TITLE
NdefGui has strange default specs

### ISSUE THREAD

**Issue by madskjeldgaard** [supercollider/supercollider#4957]
This is in continuation of https://github.com/supercollider/supercollider/issues/4952

## Environment

Using SCNvim as the IDE plus:

* SuperCollider version: 3.11
* Operating system: Arch Linux
* Other details (Qt version, audio driver, etc.): Run on the I3wm

For a lot of parameters when using NdefGui, the specs that are used as default are somewhat arbitrary. 

For example, when adding a node proxy role filter:
```
Ndef(\test)[1] = \filter -> {|in| in}
Ndef(\test).gui;
```
This adds a \wet1 parameter to the ndef which gets picked up by the NdefGui. But the default scale seems to be from 0.05 to 20.0 and not 0.0-1.0 which should be the natural choice. 

In my opinion, any spec that isn't recognzed by the guessing mechanism should have a default range of 0.0 to 1.0, especially for the ones added by nodeproxy roles that expect that range.

**Comment by madskjeldgaard** [comment]
@adcxyz you mentioned that Guess.spec could be a bit smarter. Let me just post the method as it is now for reference:
```supercollider
+ Spec {
	*guess { |key, value|

		if (value.isKindOf(SimpleNumber).not) { ^nil };

		^if (value.abs > 0) {
			ControlSpec(value/20, value*20, \exp, 0, value, \guess);
		} {
			ControlSpec(-2, 2, \lin, 0, 0, \guess);
		};
	}

	*suggestString { |key, value|
		^"Spec.add(" + this.guess(key, value).storeArgs + ");"
	}
}
```
It would be nice to expand on this method and make it a bit more rigorous. I am not 100% sure about the best way to do this but I will have a think

**Comment by madskjeldgaard** [comment]
This is before my time with SC so I'm curious if anyone can enlighten me on the choices of the two default control specs here

```supercollider
ControlSpec(value/20, value*20, \exp, 0, value, \guess);
```
and
```supercollider
ControlSpec(-2, 2, \lin, 0, 0, \guess);
```

**Comment by adcxyz** [comment]
Hi Mads, this seems to work for me:

```
/* tests: 
Ndef('x').gui;
Ndef('x')[5] = \mix -> { Dust2.ar };
// -> should should show wet5 at 1, full level
// true: 
\wet1.isFilterRole  // true
\mix5.isFilterRole  // true
\wet.isFilterRole    //false
\mix5berta.isFilterRole // false
\wet2234d.isFilterRole  // false
*/

+ Symbol {
	// support for nodeproxy filter roles
	isFilterRole {
		var str, splitIndex, head, tail;
		str = this.asString;
		splitIndex = str.detectIndex(_.isDecDigit);
		if (splitIndex.isNil) { ^false };

		head = str.keep(splitIndex);
		// roles could be looked up somewhere
		if ([ "wet", "mix" ].any (_ == head).not) { ^false };

		tail = str.drop(splitIndex);
		^tail.every(_.isDecDigit);
	}
}

+ Spec {

	*guess { |key, value|

		// nodeproxy filter roles we know:
		if (key.isFilterRole) { ^[0, 1, \amp].asSpec };

		if (value.isKindOf(SimpleNumber).not) { ^nil };

		// label units as \guess so one can throw spec away later.
		^if (value.abs > 0) {
			ControlSpec(value/20, value*20, \exp, 0, value, \guess)
		} {
			ControlSpec(-2, 2, \lin, 0, value, \guess)
		};
	}
}
```

**Comment by adcxyz** [comment]
The default guess heuristics are based on two assumptions: 
if 0, it is likely something like amp or pan, thus +-2 stays mostly in that range, 
plus extra margin for more flexible testing, thus:
``` ControlSpec(-2, 2, \lin, 0, 0, \guess);```
if nonzero, it is likely a param like freq, density, etc, where exponential ranges
are perceptually linear; thus expontial variation of times/by 20 seems a reasonably large
flexible range, thus:
``` ControlSpec(value/20, value*20, \exp, 0, value, \guess); ```

Generally guess is a last resort / first response measure: 
If users make processes with params, they may not know what ranges are good initially, so SC helps by making a first guess. As users have or develop a better idea for what the useful range would be, they can and should tweak them as they develop their Xdefs, with:
```Ndef(\x).addSpec(\whatever, [0.5, 500, \amp]);```

**Comment by adcxyz** [comment]
aehm, not working correctly yet - will check ASAP

**Comment by jamshark70** [comment]
Note that we have fuzzy string matching now (I think), so you could look for the nearest known spec in the dictionary.

**Comment by adcxyz** [comment]
OK, will propose something here soon.

**Comment by adcxyz** [comment]
> Note that we have fuzzy string matching now (I think), so you could look for the nearest known spec in the dictionary.

@jamshark70 - what fuzzy string matching do you mean? 
I only found fuzzyEqual, which only goes with numbers;  
String only has pathMatch and matchRegexp AFAICT.

**Comment by brianlheim** [comment]
String:-editDistance and String:-similarity in `develop`

-------- Original Message --------

**Comment by madskjeldgaard** [comment]
Ooh. Thats exciting!




On Thu, May 28, 2020 at 2:19 PM +0200, "Brian Heim" <notifications@github.com> wrote:














String:-editDistance and String:-similarity in `develop`





-------- Original Message --------

**Comment by madskjeldgaard** [comment]
On a similar note to this:
The (amazing really!) window you get when you evaluate `SynthDescLib.global.browse;`, choose a synth and press `window` needsa an update too to correspond to the potential update that would happen to NdefGui as well. The window in the synthdesc cannot scroll for example.

**Comment by madskjeldgaard** [comment]
Screenshot of abovementioned here:

![2021-01-19-140958_1920x1080_scrot](https://user-images.githubusercontent.com/22474608/105041071-d7474880-5a62-11eb-81a1-06b6f03bac9b.png)

**Comment by madskjeldgaard** [comment]
I'm closing this issue because it is a bit too unclear in scope
