### ISSUE TITLE
scide doesn't remember sessions 

### ISSUE THREAD

**Issue by nuss** [supercollider/supercollider#4959]
## Environment

* SuperCollider version: 3.11
* Operating system: Linux, Ubuntustudio 20.04
* Other details (Qt version, audio driver, etc.): Qt 5.12

## Steps to reproduce

1. in 'General' within preferences select 'load last session'
2. open a few documents
3. quit SuperCollider
4. open SuperCollider again

## Expected vs. actual behavior

SuperCollider resp. SCide should open the documents that were open when it got quit. Instead SC starts with a single untitled document.

**Comment by eleses** [comment]
I happen to me a few times on Windows 10 too.  But most of the time it starts with all the previous documents. So it seems it's an intermittent bug, at least on Windows.

**Comment by nuss** [comment]
I guess I was under the wrong assumption that SCide creates a new anonymous session when first opening it. That isn't the case. Now, after I have saved my open documents in a new session SCide starts with all documents opened in that session. I'm closing this issue now.
