### ISSUE TITLE
NRT via GPU

### ISSUE THREAD

**Issue by VictorKolb** [supercollider/supercollider#4961]
## Motivation
It might sound silly.
Today non-realtime rendering works really very fast. But it is computing through CPU. Maybe computing with GPU can speed up rendering process? 
Maybe there are some ways to speed up rendering process?

## Description of Proposed Feature
Some flag in NTR recordNRT method?

## Plan for Implementation
I have absolute no idea

**Comment by brianlheim** [comment]
this is an out-of-scope feature for the project, sorry. i wouldn't mind if someone came along and explained what would work and exactly how to do it, but right now we have no plans to implement this and nobody who would know how to do it.

feel free to continue discussion if more info is available.
