### ISSUE TITLE
Class 'Document' (SCIDE) unicode problems

### ISSUE THREAD

**Issue by bgola** [supercollider/supercollider#4977]
## Environment

* SuperCollider version: 3.11
* Operating system: ArchLinux
* Other details (Qt version, audio driver, etc.): Qt 5.14.2

## Steps to reproduce

```supercollider
n = Document.new("n", "é")
n.string.postln
�
-> �
n.string.ascii
-> [ -23 ]
"é".ascii
-> [ -61, -87 ]
```

## Expected vs. actual behavior

Whenever using non-ascii characters the Document class can't really retrieve the string properly, leading to bad unicode. 

I didn't have time to understand better what is going on here, but I will try to explore deeper and give more information.

**Comment by bgola** [comment]
@adcxyz this is the reason why non ascii characters break SyncText :)

**Comment by adcxyz** [comment]
ha, good catch! 
Until this is fixed, we can just filter them for SyncText, 
or better replace them with some special character sequence like '?'

**Comment by bgola** [comment]
I found the issue.

In https://github.com/supercollider/supercollider/blob/develop/editors/sc-ide/primitives/sc_ipc_client.cpp#L352 it is returning a string using Latin1 when it should be using Utf8 as far as I understand.

**Comment by adcxyz** [comment]
Great! that should be a very simple and obvious pull request :-)
