### ISSUE TITLE
Discrepancy between documentation and actual behavior of Pfunc on resetFunc argument

### ISSUE THREAD

**Issue by eleses** [supercollider/supercollider#5009]
## Environment

* SuperCollider version: 3.11
* Operating system: any

## Steps to reproduce

I was told not to file bug reports on documentation, but this one seems more than a mere omission, meaning that the documentation promises something that the code doesn't deliver. 

Pfunc's help says:

> resetFunc:	Function that is called when the stream is reset. In an event stream receives the current Event as argument.

But the `FuncStream` returned from `Pfunc` (or any `FuncStream` for that matter) doesn't actually take an argument for its `reset`, unlike for its `next` method:

```
Pfunc : Pattern {
	// ...
	asStream {
		^FuncStream.new(nextFunc, resetFunc)
	}
}

FuncStream : Stream {
	// ...
	next { arg inval;
		^envir.use({ nextFunc.value(inval) })
	}
	reset {
		^envir.use({ resetFunc.value })
	}
}
```

Frankly it's not even clear what "the current Event" means for a reset in order to write an actual reporducer, but neither of those below work

```
p = Pfunc { 42 } { |inarg| inarg.postln };
p.asStream.reset  // posts nil
p.asStream.next(())
p.asStream.reset((really: \no)) // posts nil
```

## Expected vs. actual behavior

The documentation should be sync'ed with the actual implementation.

**Comment by brianlheim** [comment]
> I was told not to file bug reports on documentation, but this one seems more than a mere omission, meaning that the documentation promises something that the code doesn't deliver.

yes, please don't file them.

**Comment by eleses** [comment]
Ok so then I'll assume the code is authoritative and file a PR for adjusting the doc to match the code.
