### ISSUE TITLE
Rebuild the Bison parser regularly from its (generator) source, for CI at least

### ISSUE THREAD

**Issue by eleses** [supercollider/supercollider#5021]
## Motivation

Presently the Bison parser generator code itself is not being actively recompiled, i.e. bison is not run as part of the builds, meaning the output of the last Bison (2.4.1) run **from about eight years ago** has been (re)used ever since. 

Without regular builds, there's a some risk that SC may run "out of sync" with more recent Bison versions. Someone actually thought that was the case in 2016, roughly when Bison 3 came out (#2259), although that was a "red herring", the actual problem being that the contributed `sh` file that was supposed to run bison was just wrong from the beginning (missing a flag), but that wasn't discovered until bison (3) started to output a slightly different header compared to its predecessor (so using the old header, not regenerated resulted in strange grammar failures.)

## Description of Proposed Feature

So, I think the `develop` code should be regularly recompiled with newer/current bison versions, much in the way boost etc is being tracked. Arguably, bison doesn't have that many bugs... but it's more of a case of "technical debt" potentially accumulating undetected by not regenerating the parser with newer versions.

Perhaps there should be a CMake flag (and rule) to run bison. And perhaps that flag should be "off" by default so that users who download the source code don't need bison to build SC, but for the CI builds that regen-parser-from-bison-source flag would be turned on.

## Plan for Implementation

TBD.

**Comment by bagong** [comment]
There is a Windows problem under the hood here to be taken into consideration... Don't remember exactly what it was, but well, at first sight it's maybe just that a sh-script doesn't run on Windows. The script itself might require an Unix environment.

**Comment by eleses** [comment]
@bagong That's why I'm hoping/proposing that this be CMake rule, not a (sh) script.

**Comment by eleses** [comment]
I've been working on CMake for this but I'm stumped by some CMake nonsense:

```
iff --git a/lang/CMakeLists.txt b/lang/CMakeLists.txt
index 933cfd38e..cf3f8c3b9 100644
--- a/lang/CMakeLists.txt
+++ b/lang/CMakeLists.txt
@@ -22,6 +22,7 @@ include_directories(${CMAKE_SOURCE_DIR}/include/common
 
 if(CMAKE_SYSTEM_NAME MATCHES "Linux")
        find_package(ALSA)
+       find_package(BISON)
 endif()
 
 find_package(Readline 5.0)
@@ -104,6 +105,14 @@ file(GLOB_RECURSE external_headers ../external_libraries/*.h* )
 list(APPEND sclang_sources ${headers} ${external_headers}) # make qt creator happy
 
 set(sclang_parser_source LangSource/Bison/lang11d_tab.cpp)
+set(sclang_parser_header LangSource/Bison/lang11d_tab.h)
+set(sclang_parser_grammar LangSource/Bison/lang11d)
+
+if(BISON_FOUND)
+       message(STATUS "sclang: out-of-date parser will be regenerated from grammar.")
+       BISON_TARGET(SclangParser ${sclang_parser_grammar} ${sclang_parser_source}
+               DEFINES_FILE ${sclang_parser_header})
+endif()
 
 # audio API for listing devices, selected the same way as in the server
 if(AUDIOAPI STREQUAL "default")
```

That goes relatively well except it tries to build the parser twice and there's some issue with the directories where it actually tries to find the files.... Any hints would be appreciated

```
Scanning dependencies of target yaml
[ 35%] Building CXX object external_libraries/CMakeFiles/yaml.dir/libyamlcpp.cpp.o
[ 36%] Linking CXX static library libyaml.a
[ 36%] Built target yaml
[ 36%] [BISON][SclangParser] Building parser with bison 3.5.1
LangSource/Bison/lang11d:36.1-14: warning: deprecated directive: ‘%error-verbose’, use ‘%define parse.error verbose’ [-Wdeprecated]
   36 | %error-verbose
      | ^~~~~~~~~~~~~~
      | %define parse.error verbose
LangSource/Bison/lang11d: warning: fix-its can be applied.  Rerun with option '--update'. [-Wother]
Scanning dependencies of target libsclang
[ 36%] Building CXX object lang/CMakeFiles/libsclang.dir/LangPrimSource/PyrPrimitive.cpp.o
[ 36%] Building CXX object lang/CMakeFiles/libsclang.dir/LangSource/PyrLexer.cpp.o
[ 36%] Building CXX object lang/CMakeFiles/libsclang.dir/LangSource/SC_TerminalClient.cpp.o
[ 36%] [BISON][SclangParser] Building parser with bison 3.5.1
LangSource/Bison/lang11d:36.1-14: warning: deprecated directive: ‘%error-verbose’, use ‘%define parse.error verbose’ [-Wdeprecated]
   36 | %error-verbose
      | ^~~~~~~~~~~~~~
      | %define parse.error verbose
LangSource/Bison/lang11d: warning: fix-its can be applied.  Rerun with option '--update'. [-Wother]
[ 37%] Building CXX object lang/CMakeFiles/libsclang.dir/LangSource/Bison/lang11d_tab.cpp.o
c++: error: /home/om/gitsc/supercollider/build/lang/LangSource/Bison/lang11d_tab.cpp: No such file or directory
c++: fatal error: no input files
compilation terminated.
make[2]: *** [lang/CMakeFiles/libsclang.dir/build.make:2190: lang/CMakeFiles/libsclang.dir/LangSource/Bison/lang11d_tab.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:3457: lang/CMakeFiles/libsclang.dir/all] Error 2
make: *** [Makefile:163: all] Error 2
```

**Comment by brianlheim** [comment]
> So, I think the develop code should be regularly recompiled with newer/current bison versions, much in the way boost etc is being tracked.

the difference here is that many people downstream actually use devendored boost because there is a compelling reason to do so, i.e. not duplicating dependencies and using system libraries instead. there is no 'devendored' version of our parser, and adding a new option for it creates additional complexity. i don't think this is a good tradeoff -- we would have to think about both the committed code and whatever the latest version of Bison produces, and it creates additional complexity in CI. given how rarely the parser files change, and how unlikely GNU Bison is to break backward compatibility, i would prefer to leave this as a manual, as-needed development task. adding it as a cmake target instead of a bash script couldn't hurt though, since that actually removes a dependency for this task. this would be the code to do it:

```cmake
find_program(BISON_COMMAND bison)
add_custom_target(build_sclang_parser
  WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/lang/LangSource/Bison
  COMMAND ${BISON_COMMAND} --defines=lang11d_tab.h --output=lang11d_tab.cpp lang11d
)
```

> I hate CMake.

please don't say things like this, it doesn't help anyone and just creates friction. if you want help, you can just ask for it.

**Comment by brianlheim** [comment]
also just to make sure we're on the same page -- there are two general approaches to this:
1. generate the parser source from your bison grammar specification during each build
2. commit bison output files to your codebase and use those directly

i think we're in agreement here that we're sticking with (2), right?

**Comment by eleses** [comment]
Yeah, I'm not trying to change the default from 2, but trying to make 1 an option. I actually got it working via CMake now too, but need to actually add flag check clean up the hairy code a bit:

```
--- a/lang/CMakeLists.txt
+++ b/lang/CMakeLists.txt
@@ -14,7 +14,7 @@ include_directories(${CMAKE_SOURCE_DIR}/include/common
                     LangPrimSource
 
                     ${CMAKE_SOURCE_DIR}/external_libraries/nova-tt
-                    LangSource/Bison
+                   #                    LangSource/Bison (not actually needed)
 
                     ${YAMLCPP_INCLUDE_DIR}
 )
@@ -22,6 +22,7 @@ include_directories(${CMAKE_SOURCE_DIR}/include/common
 
 if(CMAKE_SYSTEM_NAME MATCHES "Linux")
        find_package(ALSA)
+       find_package(BISON)
 endif()
 
 find_package(Readline 5.0)

@@ -104,6 +105,25 @@ file(GLOB_RECURSE external_headers ../external_libraries/*.h* )
 list(APPEND sclang_sources ${headers} ${external_headers}) # make qt creator happy
 
 set(sclang_parser_source LangSource/Bison/lang11d_tab.cpp)
+#set(sclang_parser_header LangSource/Bison/lang11d_tab.h)
+set(sclang_parser_grammar LangSource/Bison/lang11d)
+
+if(BISON_FOUND AND POLICY CMP0088) #todo: config flag
+       message(STATUS "sclang: parser will be regenerated from grammar.")
+       cmake_policy(SET CMP0088 NEW) # regen in build dir
+       set(sclang_parser_output_dir generated)
+       # includes in CPP files are of the form #include "Bison/lang11..."      
+       set(sclang_parser_output_subdir ${sclang_parser_output_dir}/Bison)
+       file(MAKE_DIRECTORY ${CMAKE_CURRENT_BINARY_DIR}/${sclang_parser_output_subdir})
+       set(sclang_parser_header ${sclang_parser_output_subdir}/lang11d_tab.h)
+       set(sclang_parser_source ${sclang_parser_output_subdir}/lang11d_tab.cpp)
+       BISON_TARGET(SclangParser ${sclang_parser_grammar} ${sclang_parser_source}
+               DEFINES_FILE ${sclang_parser_header})
+       #set(sclang_parser_source ${BISON_SclangParser_OUTPUT_SOURCE}) #redundant
+       include_directories(${CMAKE_CURRENT_BINARY_DIR}/${sclang_parser_output_dir})
+       #else()
+       #       include_directories(LangSource/Bison)
+endif()

```

**Comment by brianlheim** [comment]
erm, maybe add_custom_target would be better than this findBISON module in the end? they do basically the same thing, and add_custom_target / add_custom_command are much better documented and well known in CMake. unless you plan to make use of the versioning capability?

**Comment by eleses** [comment]
`if(POLICY CMP0088)` is implicitly making use of CMake versioning; it's only true >= 3.14.

But yeah, that `BISON_TARGET` macro is not providing all that much; I can just run find_package(BISON) which is useful, but then manually implement what CMP0088 = NEW does instead of calling `BISON_TARGET`.

**Comment by eleses** [comment]
If you're happy with
```
find_program(BISON_COMMAND bison)
add_custom_target(build_sclang_parser
  WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}/lang/LangSource/Bison
  COMMAND ${BISON_COMMAND} --defines=lang11d_tab.h --output=lang11d_tab.cpp lang11d
)
```
you can commit it yourself. I for one was hoping to stick to an out-of-tree build and rebuild the parser like that too, but I've hit a rather nasty snag with that: PyrLexer.cpp still includes the header from source tree somehow. Even with `include_directories(BEFORE ${CMAKE_CURRENT_BINARY_DIR}/${sclang_parser_output_dir})` It's probably getting included by before the BEFORE at a higher directory level. Also adding an actual dependency of PyrLexer on the out-of-tree header (for incremental builds) turned out [will only work on linux](https://cmake.org/cmake/help/v3.16/prop_sf/OBJECT_DEPENDS.html). 

I'm not terribly inclined to debug this any further given the low interest in this feature and how many gotchas CMake has in this area.
