### ISSUE TITLE
Ubuntu install wiki page needs updating

### ISSUE THREAD

**Issue by eleses** [supercollider/supercollider#5022]
https://github.com/supercollider/supercollider/wiki/Installing-SuperCollider-on-Ubuntu-systems

suggests to install from a 3rd party PPA repo. But that one presently only has SC 3.9 while the defatult Ubuntu repo comes wtih 3.10.0, albeit with broken help (no code examples shown, due to some jQuery issue/error.)
```
*** ERROR in JavaScript: "Uncaught ReferenceError: $ is not defined"
* line: 215
* source ID: "file:///home/om/.local/share/SuperCollider/Help/scdoc.js"
*** ERROR in JavaScript: "Uncaught ReferenceError: CodeMirror is not defined"
* line: 3                                                                 
* source ID: "file:///home/om/.local/share/SuperCollider/Help/editor.js"  
*** ERROR in JavaScript: "Uncaught ReferenceError: $ is not defined"
* line: 157
* source ID: "file:///home/om/.local/share/SuperCollider/Help/scdoc.js"
```

So I suggest maybe dropping the PPA, but also mention the help-examples bug on 3.10.0 as shipped by Canonical. 

Also their (Canonical) packages say this...

```
Canonical does not provide updates for supercollider-language. Some updates may be provided by the Ubuntu community.
```

A better solution would be of course if there was actually a good SC and up-to-date package for Ubuntu, e.g. with SC 3.11.

**Comment by brianlheim** [comment]
thanks! updated. please edit the wiki if there are any details i got wrong. shouldn't this also be reported upstream?

**Comment by eleses** [comment]
I'm not sure if the javascript bug was a bug SC 3.10.0 or if Ubuntu's team managed to introduce it... They have 3.10.4 slated for Groovy Gorilla (the fall 2020 Ubuntu) from what I can tell from their repos, but I haven't tried that one (likely links to a different Qt lib version so the packaged won't run on 20.04.)

**Comment by brianlheim** [comment]
it was a packaging issue. looks like it was fixed in the 3.10.4 package: https://bugs.launchpad.net/ubuntu/+source/supercollider/+bug/1833752

**Comment by eleses** [comment]
It seems they had changed some files https://bugs.launchpad.net/ubuntu/+source/supercollider/+bug/1833752/comments/9

**Comment by brianlheim** [comment]
that's a solution for fixing the bad packaging

**Comment by bartart3d** [comment]
I recently upgraded to ubuntustudio 20.10 and encountered this issue yet again. I managed to fix it the exact same way as I did in ubuntustudio 19.04 ([https://github.com/supercollider/supercollider/issues/4392](https://github.com/supercollider/supercollider/issues/4392)) .
