### ISSUE TITLE
Make develop builds print a non-release build string when booted

### ISSUE THREAD

**Issue by eleses** [supercollider/supercollider#5025]
## Motivation

Right now when you boot a `develop` build it prints exactly the same string as a released build e.g.

```
Welcome to SuperCollider 3.11.0
```

## Description of Proposed Feature

It should print something different, e.g. SuperCollider develop-ac271e7 

where that id is the last commit id.

## Plan for Implementation

TBD.

**Comment by eleses** [comment]
I see the info in already loaded in `SC_Version.hpp`:

```
static const int SC_VersionMajor = 3;                                                                   
static const int SC_VersionMinor = 11;                                                                  
static const int SC_VersionPatch = 0;                                                                   
static const char SC_VersionTweak[] = "";                                                               
static const char SC_Branch[] = "develop";                                                              
static const char SC_CommitHash[] = "ac271e7f0";                                                        
                                                                                                        
// For backward compatibility in scsynth and supernova only.                                            
static const char SC_VersionPostfix[] = ".0";                                                           
                                                                                                        
static inline std::string SC_VersionString()                                                            
{                                                                                                       
        std::stringstream out;                                                                          
        out << SC_VersionMajor << "." << SC_VersionMinor << "." << SC_VersionPatch << SC_VersionTweak;  
        return out.str();                                                                               
}                                                                                                       
                                                                                                        
static inline std::string SC_BuildString()                                                              
{                                                                                                       
    std::stringstream out;                                                                              
    out << "Built from branch '" << SC_Branch << "' [" << SC_CommitHash << "]";                         
    return out.str();                                                                                   
}                                                                     
```

So, I guess the only issue is whether anything calls/prints the `SC_BuildString`....

**Comment by brianlheim** [comment]
i just want to point out that ("Built from branch 'develop' [ac271e7f0]") is mostly a lie anyway. if you don't re-run cmake in between commits, `Version.hpp` won't be updated and will continue to show the old commit hash from when CMake was last run. you could also make a ton of changes to your working directory and not commit them and that fact also wouldn't be reflected. this is desirable because otherwise we would have to recompile and relink several components every time the current commit and/or dirty state changed.

if you want something more specific -- and i agree it would be helpful to be more specific -- probably the output of `git describe --tags` would be best. it will print the short tag name ("Version-3.11.0-rc1") when HEAD is at a tag, and a more descriptive string ("Version-3.11.0-rc1-142-g33d7a90c91") otherwise. see `git help describe`.

**Comment by brianlheim** [comment]
> if you want something more specific -- and i agree it would be helpful to be more specific -- probably the output of git describe --tags would be best. 

and this output looks normal enough that you could include it unconditionally, i think.

**Comment by eleses** [comment]
> you could also make a ton of changes to your working directory and not commit them and that fact also wouldn't be reflected. 

Alas `git describe` will not report those in any way, as far as I can tell. But perhaps make the build abort for uncommitted changes  (with `git status`) unless you pass some "force" flag, might also be a reasonable safeguard.

**Comment by kneitinger** [comment]
> But git status doesn't seem return any (shell-level) exit status

In `bash`, we can call it with `--short` and obtain an exit status via a `-z` test
```
[ -z "$(git status --short)" ]
```
This reliably returns an exit code of 0 if there are no local changes and 1 if there are local changes.

Demo:
```
# Starting from clean repo
$ [ -z "$(git status --short)" ] && echo "exit code 0" || echo "exit code 1"
exit code 0
$ touch foo && [ -z "$(git status --short)" ] && echo "exit code 0" || echo "exit code 1"
exit code 1
$ rm foo && [ -z "$(git status --short)" ] && echo "exit code 0" || echo "exit code 1"
exit code 0
```
That can be translated into CMake with a combination of `execute_process` on `git status --short` and a test of `STREQUAL ""` (assuming no newline, but those too can be accounted for).

> But perhaps make the build abort for uncommitted changes (with git status) unless you pass some "force" flag, might also be a reasonable safeguard.

I like what you're getting at here regarding correctness, but I feel like it could be bothersome to require committed changes or a force flag when attempting to build. What if instead, the version string is further modified to reflect that there are local changes:

Demo:
```
# First, define a function for legibility!
$ sc_ver(){ echo "$(git describe --tags)$( [ -z "$(git status --short)" ] || echo "-dirty")"; }
# Test it in various scenarios
$ git checkout 3.11 && sv_ver
Version-3.11.1-rc1
$ rm INSTALL && sc_ver
Version-3.11.1-rc1-dirty
$ git restore INSTALL && sc_ver
Version-3.11.1-rc1
$ git checkout develop && sc_ver
Version-3.11.1-rc1-352-gfd48a9d05
$ rm INSTALL && sc_ver
Version-3.11.1-rc1-352-gfd48a9d05-dirty
```
as with last example, demoed in bash, but absolutely doable in CMake (but perhaps using a more confidence inspiring or precise word than "dirty" :slightly_smiling_face:)

This method (so long as its intent is clear in the version string) could perhaps be the most helpful in all of the use-cases

**Comment by dyfer** [comment]
We currently have a proposal to use the next minor version number of the develop branch and append `-dev` suffix (#5566). While it is not as extensive, it would provide some differentiation form the release builds. Would #5566 be a sufficient "fix" to address this issue?

**Comment by dyfer** [comment]
I think that #5566 solves this at least partially. Feel free to reopen if you think we should change this further.
