### ISSUE TITLE
scide on Linux doesn't seem to allow opening files with dots in dir paths

### ISSUE THREAD

**Issue by eleses** [supercollider/supercollider#5026]
## Environment

* SuperCollider version: develop ac271e7 
* Operating system: Lubuntu 20,  Qt 5.12.8

## Steps to reproduce

If I have file named

```
/home/om/.local/share/SuperCollider/Extensions/own/classes/cldupe-fix-v2.sc
```

I cannot open it in SC from its file-open dialog box. The file-open dialog just refuses "ok" the file, even though it exists.  I think the problem is with the dots in the paths.

## Expected vs. actual behavior

I should be able to open that file from SC.

## Another example (with screenshot)

![image](https://user-images.githubusercontent.com/9859213/85089492-736a5200-b1eb-11ea-9fc2-bc8924e86189.png)

The "open" checkbox is grayed out and clicking on open... does nothing.

The file exists and is accessible though:

```
om@lubvm:~$ ls -l ~/.local/share/SuperCollider/SCClassLibrary/Common/Streams/PmonoStreams.sc
-rw-r--r-- 1 om om 3617 Jun 17 17:33 /home/om/.local/share/SuperCollider/SCClassLibrary/Common/Streams/PmonoStreams.sc
```

Trying the path without `~` (i.e. `/home/om/.local/share/SuperCollider/SCClassLibrary/Common/Streams/PmonoStreams.sc`) doesn't work either.

And since it seems that depends on the Qt version...

```
apt list --installed "qt*" 
Listing... Done
qt5-assistant/focal,now 5.12.8-0ubuntu1 amd64 [installed,automatic]
qt5-default/focal,now 5.12.8+dfsg-0ubuntu1 amd64 [installed]
qt5-gtk-platformtheme/focal,now 5.12.8+dfsg-0ubuntu1 amd64 [installed,automatic]
qt5-image-formats-plugins/focal,now 5.12.8-0ubuntu1 amd64 [installed,automatic]
qt5-qmake-bin/focal,now 5.12.8+dfsg-0ubuntu1 amd64 [installed,automatic]
qt5-qmake/focal,now 5.12.8+dfsg-0ubuntu1 amd64 [installed]
qt5-qmltooling-plugins/focal,now 5.12.8-0ubuntu1 amd64 [installed,automatic]
qtattributionsscanner-qt5/focal,now 5.12.8-0ubuntu1 amd64 [installed,automatic]
qtbase5-dev-tools/focal,now 5.12.8+dfsg-0ubuntu1 amd64 [installed,automatic]
qtbase5-dev/focal,now 5.12.8+dfsg-0ubuntu1 amd64 [installed,automatic]
qtchooser/focal,now 66-2build1 amd64 [installed,automatic]
qtdeclarative5-dev-tools/focal,now 5.12.8-0ubuntu1 amd64 [installed,automatic]
qtdeclarative5-dev/focal,now 5.12.8-0ubuntu1 amd64 [installed]
qterminal-l10n/focal,focal,now 0.14.1-0ubuntu2 all [installed,automatic]
qterminal/focal,now 0.14.1-0ubuntu2 amd64 [installed,automatic]
qtermwidget5-data/focal,focal,now 0.14.1-3ubuntu1 all [installed,automatic]
qtgstreamer-plugins-qt5/focal,now 1.2.0-5 amd64 [installed,automatic]
qtpass/focal,now 1.3.2-1build1 amd64 [installed,automatic]
qtpositioning5-dev/focal,now 5.12.8+dfsg-0ubuntu1 amd64 [installed,automatic]
qttools5-dev-tools/focal,now 5.12.8-0ubuntu1 amd64 [installed]
qttools5-dev/focal,now 5.12.8-0ubuntu1 amd64 [installed]
qttranslations5-l10n/focal,focal,now 5.12.8-0ubuntu1 all [installed,automatic]
qtwayland5/focal,now 5.12.8-0ubuntu1 amd64 [installed,automatic]
qtwebengine5-dev/focal,now 5.12.8+dfsg-0ubuntu1 amd64 [installed]
qtwebengine5-doc/focal,focal,now 5.12.8+dfsg-0ubuntu1 all [installed,automatic]
```

**Comment by eleses** [comment]
There is thankfully a workaround for this: if I create a symlink to the SC-inaccessible file in a directory it does like opening files from, then I can open that file.

**Comment by miguel-negrao** [comment]
I can open files in the extensions folder (~/.local/share/SuperCollider/Extensions) without issue on the develop branch (from this week), on debian 10.

**Comment by eleses** [comment]
Hmm, it might be related to Qt file-open widget then somehow. I'll post the full Qt version...

**Comment by eleses** [comment]
Actually, this turned out to be some kind of stupid Lubuntu problem. While I don't know how to solve it yet, it's 100% reproducible in "featherpad", which uses the same file-open (Qt) dialog box. And it's not only paths with dots, it seems you can't open any paths with slashes anywhere. Basically the file-open dialog from Lubuntu 20 only accepts files from the current directory; it won't open any paths with dirs whatsoever. Stupid Lubuntu.
