### ISSUE TITLE
SCHelp: question

### ISSUE THREAD

**Issue by sonoro1234** [supercollider/supercollider#5040]
Hi,

I have looked `HelpSource` in SC installation but it seems different than the htm files needed for the online help
How can be the htm files on `https://doc.sccode.org/` be generated?

Thanks for answering
victor

**Comment by jamshark70** [comment]
http://doc.sccode.org/Classes/SCDoc.html#*renderAll

Btw - in general we prefer the bug tracker to be used for bugs rather than usage questions. (This would be a great question for the user forum or mailing list!)

**Comment by jamshark70** [comment]
PS I think I'll just close this as it's a straightforward question. If it turns out there's a bug with this or a new feature needed, feel free to open an issue for it.

**Comment by sonoro1234** [comment]
Done
