### ISSUE TITLE
build with gcc nova-simd warnings

### ISSUE THREAD

**Issue by sonoro1234** [supercollider/supercollider#5092]
While building with gcc there are a lot of warnings as
```
/home/victor/programacion/supercollider1/external_libraries/nova-simd/vec/vec_sse2.hpp:51:32: warning: ignoring attributes on template argument ‘__m128d’ {aka ‘__vector(2) double’} [-Wignored-attributes]
   51 |     vec_base<double, __m128d, 2>

```
related with nova-simd, they seem not harmful but they are quite annoying.
What could be done?

**Comment by brianlheim** [comment]
we have a general ticket for this already: https://github.com/supercollider/supercollider/issues/2927

> What could be done?

internet search for the warning and submit a fix upstream, and/or mark these include directories as system includes so they don't generate warnings.
