### ISSUE TITLE
How should SC support quarks with other default branch names than "master"?

### ISSUE THREAD

**Issue by adcxyz** [supercollider/supercollider#5096]
## Motivation 
In https://github.com/supercollider/rfcs/pull/10, a related side aspect turned up: 
Authors of supercollider-quarks will likely decide to follow the github recommendation 
to rename default branches from "master" to "main"; the current implementations 
of the Quark and Git classes in SC have "master" branch names hardcoded in 3 places. 

## Description of Proposed Feature
SuperCollider should checkout default branches of quarks regardless of their names. 

More specifically, four compatibility use cases should work transparently: 
1 new-style SC versions (using default branch) should find new-style quarks (using default branch) 
2 new-style SC versions (using default branch) should find old-style quarks  (with "master" branch) 
3 old-style SC versions ("master" branch) should find new-style quarks (using default branch) 
4 old-style SC versions ("master" branch) should find old-style quarks  (with "master" branch) 

1 and 4 are trivial, 2 is easy, 3 will likely be clumsy, and require a transition period. 

## Plan for Implementation
- The relevant methods could have branch name arguments for full flexibility
-  New-style quarks could list their default branch name in the description file
- checkout branch name given in description file
- if none given, Strategy for checkout could be: 
-- ask for default branch , then for main, then master

case 3 would require that quark authors keep a "master" branch around for a transition period;
if there is a way to redirect a call to "master" to another branch, this is easy. 

Questions for the git experts: 
- how to checkout the default branch without calling its explicit name? 
- what is the simplest way to set up an alias branch name in a repo, such that 
  asking for hardcoded "master" name returns default branch?

**Comment by brianlheim** [comment]
i'm going to focus on implementing my RFC before even beginning to think about this, FYI, but thanks for bringing it up!
