### ISSUE TITLE
OSX double-click bracket matching fails in Windows files

### ISSUE THREAD

**Issue by jleben** [supercollider/supercollider#51]
[Issue migrated from SourceForge | ID: 1898422 | Submitted by 'jamshark70']
[http://sourceforge.net/support/tracker.php?aid=1898422]

Edit a .sc or .scd file on a Windows machine. Then open that file in SC on OSX.

If there is something like

(
... some code...
)

... then double-clicking inside the open-paren does not select the whole text. It stops at EOL.

This is b/c OSX saves text files with EOL (ascii 10) for line breaks. Windows saves with LF-CR (10, then 13). The presence of ascii 13 stops the bracket matcher.

Related annoyance: in OSX, use cmd-[ or cmd-] to shift text left or right on a Windows file. Magically everything selected changes to double-spaced.

**Comment by scztt** [comment]
This appears fixed in 3.7 - bracket matching and selection works identically for win, mac, and unix line ending files.
