### ISSUE TITLE
Quarks system does not seem to respect version tags

### ISSUE THREAD

**Issue by lnihlen** [supercollider/supercollider#5100]
## Environment

* SuperCollider version: have reproduced on 3.10 and 3.11 builds
* Operating system: have tested and reproduced on Ubuntu Linux Focal, PopOS! 20.04, MacOS Catalina, Windows 10

## Steps to reproduce

```supercollider
Quarks.install("Scintillator");
```

Produces the following log stream:
```
Installing Scintillator
Adding path: /home/luken/.local/share/SuperCollider/downloaded-quarks/Scintillator
Scintillator installed
-> Quark: Scintillator[0.0.6]
```

Which is consistent with the current Quark setup, from Scintillator.quark:

```supercollider
(
	name: "Scintillator",
	summary: "A Vulkan-based video synthesizer for SuperCollider",
	author: "Luke Nihlen",
	version: "0.0.6",
	schelp: "Guides/Scintillator-User-Guide",
	license: "GPL",
	copyright: "Luke Nihlen 2020",
	since: 2018
)
```

but if you change directory to the quark and look at the git log:
```
luken@roci:~/.local/share/SuperCollider/downloaded-quarks/Scintillator$ git log -n1
commit 256d84988bcdd5a70b00e24f0cbc81662e1342ed (HEAD -> master, origin/master, origin/HEAD)
Author: Luke Nihlen <luke.nihlen@gmail.com>
Date:   Sun Jul 12 16:12:09 2020 -0700

    Adds support for frame-rate VGens (#135)
luken@roci:~/.local/share/SuperCollider/downloaded-quarks/Scintillator$ 
```

It shows it's actually tracking HEAD, which is 12 or so commits ahead of the 0.0.6 tag:

```
commit edee8e04c4a073ff37305ee21eb72fd730230629 (tag: 0.0.6)
Author: Luke Nihlen <luke.nihlen@gmail.com>
Date:   Sun May 10 09:26:04 2020 -0700

    change argument to cygpath for windows paths
```

## Expected vs. actual behavior

If I tag a specific commit in the master branch, I would expect checkouts of the Quark to checkout that specific tag, instead of checking out the tip of tree.

**Comment by dyfer** [comment]
The docs say that one needs to specify a tag if one doesn't want to check out the tip of tree:
```
Quarks.install(name, refspec)
Arguments:
name	
Name of a quark that is listed in the directory, or the url of a git repository or the path (absolute or relative to current working directory) of a folder to install.

refspec	
Optional git refspec. By default it will install the latest version. Optionally you can specify a tag: "tags/1.0.0" A sha commit: "15e6ea822a18d06b286c3f10918f83b8d797d939" "HEAD" nil (default)
```
This seems to work:
```supercollider
Quarks.install("Scintillator", "tags/0.0.6");
```
When I `cd` to quark directory to check the status, I get
```shell
-> git status
HEAD detached at 0.0.6
nothing to commit, working tree clean
```

**Comment by lnihlen** [comment]
Ah thanks for explaining. I guess I assumed that by specifying a version: tag in the quark metadata, the Quark system would check out that specific tag if nothing else was specified. I'm going to look at revising my quark release process to account for this. Closing the issue as WAI.
