### ISSUE TITLE
Sample sound file corrupted? a11wlk01.wav doesn't sound like a11wlk01-44_1.aiff

### ISSUE THREAD

**Issue by bhagerty** [supercollider/supercollider#5102]
A sound file packaged with SuperCollider seems to be weird or corrupted. The sample .aiff file in the /sounds directory `a11wlk01-44_1.aiff` is fine - it plays back "Columbia, this is Houston, over." 

But the corresponding .wav file, `a11wlk01.wav`, is crazy. It sounds like a little girl speaking nonsense. It does sound like it is somehow derived from the .aiff file (you can hear a beep, and something like "Columbia"), but it is absolutely not the same audio. 

Note that I confirmed the problem not just from my installed copy of SuperCollider, but also by downloading and unzipping both the  latest nightly Windows x64 build (`SC-Windows-x64-435ab9106a4abdb2e3d5c076dc90a9ea9a9fd75e.zip`) and the latest Linux tarball (`SuperCollider-3.11.0-Source.tar.bz2`). And I confirmed it by opening the .wav file in two different programs (the Groove player and VLC Player). 

## Environment
* SuperCollider version: 3.11
* Operating system: Windows 10 Pro

**Comment by jparmentervf** [comment]
This is not a problem. They are, indeed, different recordings.

**Comment by joshpar** [comment]
Closing as these are the items that we include

**Comment by bhagerty** [comment]
I see. Thank you both for your quick response. FWIW, I would add two things:

(1) I thought it was a problem because I was going through [Programming Digital Music with SuperCollider by Peter Fitton](https://www.amazon.com/gp/product/B00EA1USLG), and some of his examples use the .wav file, which he describes as having the same content as the .aiff file. I'm not sure if Fitton was wrong when he wrote the book (2014) or if the file was changed since then. If it was changed since then, the change broke his tutorial. I wonder if it broke others. 

(2) Having two files with basically the same name but different content doesn't make a lot of sense to me. It seems like some kind of an inside joke, and inside jokes are not friendly to newcomers. Maybe there's a good reason for having the two files with essentially the same name, but it's hard for me to see what that reason would be. 

Thanks again for your prompt responses.

**Comment by jamshark70** [comment]
> I'm not sure if Fitton was wrong when he wrote the book (2014) or if the file was changed since then. If it was changed since then, the change broke his tutorial. I wonder if it broke others.

It appears it's a mistake in the book -- the last commit on that file was 10 years ago, 2010, before 2014.

> Having two files with basically the same name but different content doesn't make a lot of sense to me.

You have a point. I'm not quite sure what to do about it. Renaming it and `sed`-ing helpfiles would be straightforward but would also invalidate hundreds of web tutorials. We're probably stuck with it.

**Comment by joshpar** [comment]
thanks for the feedback. That file has been in place since the mid-2000s I believe. Definitely before the primary SC book was written. Sorry that causes confusion. It was created to finally include a 44 k sound file (the original file's sample rate was 11k I believe).

**Comment by bhagerty** [comment]
@jamshark70 @joshpar Thanks to you both for your thoughtful responses. You are right, there's probably nothing to be done. 

One semi-reasonable solution might be to drop a README.txt (or .md) into the /sounds folder alongside these files telling the reader what they contain. Personally, I would have read such a README when I first encountered the mismatch between Fitton's book and the file, and such a README would have saved me (and both of you) this confusion and time.

But I don't have a strong opinion about it. I think if I were a core dev, I would create such a README. But opinions could vary on its desirability, and I don't feel like I'm in a position to decide that. 

Thanks again. I hope some day I'll be in a position to contribute to SC.
