### ISSUE TITLE
EnvGen wit h 3-element Env and initial \hold segment

### ISSUE THREAD

**Issue by jeeger** [supercollider/supercollider#5104]
## Environment

* SuperCollider version: sclang-3.11.0 built from source
* Operating system: Gentoo linux
* Other details (Qt version, audio driver, etc.): QT 5.14.2, Jack driver, using supernova 3.11.0.

## Steps to reproduce

```supercollider
Env.new(curve: [\hold, \lin]).test
```

## Expected vs. actual behavior

Expected behavior: 1 second of silence, one second of decaying \note output.
Actual behavior: Silence.

`Env.new(curve: [\hold, \lin]).plot` looks correct, so it seems the EnvGen is at fault here. I don't know enough about Supercollider to know whether this has something to do with issue #1027 or issue #1124, but the problem only occurs when using an envelope with three segments. 
`Env.new(levels: [0, 1, 1, 0], times: [1, 0, 1], curve: [\hold, \lin, \lin]).test` works correctly.
The bug occurs with both supernova and scsynth.

**Comment by jamshark70** [comment]
I'd have to guess that EnvGen, at the end of the first segment, is probably not updating its level to the hold segment's end level. I've just been glancing at the code a bit and it isn't obvious to me where that's being done.

FWIW I've never used `\hold` -- I'd have just written it `Env([0, 0, 1, 0], [1, 0, 1], \lin)` and thereby never run into the bug (which is probably why the issue went undiscovered for a long time).

**Comment by elgiano** [comment]
> I'd have to guess that EnvGen, at the end of the first segment, is probably not updating its level to the hold segment's end level. 
Totally accurate, and no other shape needs to do that, as all others update their level as they run. So, if we want to fix it as a special case, maybe we should do it in initSegment?

```
diff --git a/server/plugins/LFUGens.cpp b/server/plugins/LFUGens.cpp
index b5502892a..855ba8ed5 100644
--- a/server/plugins/LFUGens.cpp
+++ b/server/plugins/LFUGens.cpp
@@ -2398,6 +2398,8 @@ static bool EnvGen_initSegment(EnvGen* unit, int& counter, double& level, double
     }
 
     float previousEndLevel = unit->m_endLevel;
+    if(unit->m_shape == shape_Hold)
+        level = previousEndLevel;
     float** envPtr = unit->mInBuf + stageOffset;
     double endLevel = *envPtr[0] * ZIN0(kEnvGen_levelScale) + ZIN0(kEnvGen_levelBias); // scale levels
     if (dur < 0)
```
