### ISSUE TITLE
Main.recompile works on linux too

### ISSUE THREAD

**Issue by ndr-brt** [supercollider/supercollider#5108]
I was reading the Main class reference, and read that `recompile` method 
>Currently macOS (SuperCollider.app) only
https://github.com/supercollider/supercollider/blob/bcac8f3aaa4e5561031ac0a440422bbbe3cf32cc/HelpSource/Classes/Main.schelp#L193

But, I tried it on linux (sc 3.10.4 on ubuntu 20.04) and it worked.
Can this documentation be updated?

**Comment by elgiano** [comment]
Thanks for reporting this! I checked git history and it looks like that Help File hasn't been updated when Library Recompilation was implemented 9 years ago :)
I'm going to make a PR now to fix it

**Comment by muellmusik** [comment]
Let's all pause to enjoy the rare inversion of something working when it _isn't_ supposed to! :-)

**Comment by dyfer** [comment]
fixed in #5109
