### ISSUE TITLE
LanguageConfig:getExcludeDefaultPaths primitive not bound on 3.11 fresh install (arch linux)

### ISSUE THREAD

**Issue by iani** [supercollider/supercollider#5139]
## Environment

* SuperCollider version: 3.11.0
* Operating system: arch linux
* Other details (Qt version, audio driver, etc.):

Manjaro install. 
Updated to last sc version with "yay -S supercollider"

## Steps to reproduce

Recompile class library.  (This is a primitive not bound error that appears immediately after compiling).

## Expected vs. actual behavior

SClang reports primitve failed when re-compiling the SCClassLibrary. (see error message below).
I am using SCClassLibrary only, as freshly installed. 

Otherwise, sclang works as expected. 

Is this primitive really not available on 3.11?

```
ERROR: A primitive was not bound. 0 861
Instance of Method {    (0x564c7e26f7c0, gc=01, fmt=00, flg=11, set=04)
  instance variables [15]
    raw1 : Float 0.000000   00000000 0060000C
    raw2 : Float 0.000000   00000100 01000001
    code : instance of Int8Array (0x564c7e26f940, size=4, set=2)
    selectors : nil
    constants : nil
    prototypeFrame : instance of Array (0x564c7c056f00, size=1, set=2)
    context : nil
    argNames : instance of SymbolArray (0x564c7c056fc0, size=1, set=2)
    varNames : nil
    sourceCode : nil
    ownerClass : class Meta_LanguageConfig (0x564c7e26ce40)
    name : Symbol 'excludeDefaultPaths'
    primitiveName : Symbol '_LanguageConfig_getExcludeDefaultPaths'
    filenameSymbol : Symbol '/home/iani/Dev/SC/scmods20200816/supercollider/SCClassLibrary/Common/Core/LanguageConfig.sc'
    charPos : Integer 944
}
```

**Comment by jamshark70** [comment]
I'm away from my computer for a few days so I can't check in detail, but I haven't seen this error in Ubuntu (building from source). So I think the primitive probably exists.

A plausible explanation would be a mismatch between an older sclang binary and a newer class library.

**Comment by brianlheim** [comment]
> Is this primitive really not available on 3.11?

it is not in 3.11; it was merged to develop after 3.11.

**Comment by jamshark70** [comment]
Then 3.11 should not be shipping a class library referring to this primitive.

@iani how did you get a "develop" class library with a 3.11 binary?

**Comment by brianlheim** [comment]
> Then 3.11 should not be shipping a class library referring to this primitive.

it isn't -- looking at the class library path from above

> ` filenameSymbol : Symbol '/home/iani/Dev/SC/scmods20200816/supercollider/SCClassLibrary/Common/Core/LanguageConfig.sc'`

it's clearly not the class library that would be installed with `yay`.

**Comment by iani** [comment]
Hello,
James and Brian, thanks for answering.
You are right, and your writings together clarify my situation.
To answer @jamshark70 

I updated to 3he develop.11 with yay, and then modified my config.yaml paths to use a library freshly cloned to my laptop from develop. So while yay may not install a reference to this primitive - as @brianlheim writes, the reference is in the current develop branch.  So fine, I will modify my own branch from develop using the code for LanguageConfig given by the yay install, and wait for the next release.

Iannis
