### ISSUE TITLE
Pseg in Pn: Message 'put' not understood

### ISSUE THREAD

**Issue by madskjeldgaard** [supercollider/supercollider#5140]
## Environment

* SuperCollider version: 3.11.0
* Operating system: Arch Linux
* Other details (Qt version, audio driver, etc.):

## Steps to reproduce

```supercollider
(
// WORKS:
// Change octave when degree sequence is done. Works because Pseq is in Pn
Pbind(
 	\dur, 0.125,
 	\degree, Pn(Pseq((1..4), 1), inf, key:\degDone),
 	\octave, Pgate(Pseq((6..4),inf), inf, key:\degDone),
).play;
)
(
// DOES NOT WORK:
// Change octave when degree sequence is done. Does not work with Pseg
// Resulting in error:
// ^^ The preceding error dump is for ERROR: Message 'put' not understood.
// RECEIVER: a Pseg
Pbind(
	\dur, 0.125,
	\degree, Pn(Pseg([1,4], 4, \lin, 1), inf, key:\degDone),
	\octave, Pgate(Pseq((6..4),inf), inf, key:\degDone).trace,
).play;
)
```
## Expected vs. actual behavior

When using Pseg with a non-infinite repetition value in a Pn, I get this strange error when the Pseg is done. Pn/Pgate seem to work fine with Pseq for example but not with Pseg. I don't know Pseg and it's superclasses well enough to know exactly where this happens. 

Error message in full:
```
ERROR: Message 'put' not understood.
RECEIVER:
Instance of Pseg {    (0x559571068078, gc=54, fmt=00, flg=00, set=02)
  instance variables [4]
    list : instance of Pseq (0x559571068008, size=3, set=2)
    durs : Integer 4
    repeats : Integer 1
    curves : Symbol 'lin'
}
ARGS:
   Symbol 'degDone'
   true
PATH: /home/mads/code/sc/grainstages/garbage-rhythms.scd
CALL STACK:
	DoesNotUnderstandError:reportError
		arg this = <instance of DoesNotUnderstandError>
	Nil:handleError
		arg this = nil
		arg error = <instance of DoesNotUnderstandError>
	Thread:handleError
		arg this = <instance of Thread>
		arg error = <instance of DoesNotUnderstandError>
	Thread:handleError
		arg this = <instance of Routine>
		arg error = <instance of DoesNotUnderstandError>
	Thread:handleError
		arg this = <instance of Routine>
		arg error = <instance of DoesNotUnderstandError>
	Thread:handleError
		arg this = <instance of Routine>
		arg error = <instance of DoesNotUnderstandError>
	Object:throw
		arg this = <instance of DoesNotUnderstandError>
	Object:doesNotUnderstand
		arg this = <instance of Pseg>
		arg selector = 'put'
		arg args = [*2]
	< FunctionDef in Method Pn:embedInStream >  (no arguments or variables)
	Float:do
		arg this = inf
		arg function = <instance of Function>
		var i = 1.0
	Pn:embedInStream
		arg this = <instance of Pn>
		arg event = <instance of Pseg>
	Routine:prStart
		arg this = <instance of Routine>
		arg inval = <instance of Event>
^^ The preceding error dump is for ERROR: Message 'put' not understood.
RECEIVER: a Pseg
```

**Comment by jamshark70** [comment]
I'm traveling without my computer so I can't PR it right now, but it's an easy fix. An `embedInStream` method must always return the last input event/value. In TimePatterns.sc, Pstep does this but Pseg omits the final `^inval`. That's the whole cause of the problem: Pn expects to be operating on an input event but it receives the pattern object instead.

The bug apparently dates back 15 years... cheers for current improved unit testing practices.

**Comment by madskjeldgaard** [comment]
> I'm traveling without my computer so I can't PR it right now, but it's an easy fix. An `embedInStream` method must always return the last input event/value. In TimePatterns.sc, Pstep does this but Pseg omits the final `^inval`. That's the whole cause of the problem: Pn expects to be operating on an input event but it receives the pattern object instead.
> 
> The bug apparently dates back 15 years... cheers for current improved unit testing practices.

Nice one @jamshark70  !

**Comment by madskjeldgaard** [comment]
Great work. Thanks a lot guys
