### ISSUE TITLE
3.11.2 Discussions

### ISSUE THREAD

**Issue by brianlheim** [supercollider/supercollider#5146]
Use this thread to discuss plans for the 3.11.2 release.

This is a complaint we got for the 3.11.1 release: https://scsynth.org/t/announce-supercollider-version-3-11-1-rc1-now-available-for-download/2485/3

So i'd like to fix that one, but aside from that i don't have any plans for a 3.11.2 release.

We also have several documentation improvements that can be cherry-picked onto the 3.11 branch.

I think 3.11.2 should be the last patch release for 3.11, and then we should release 3.12 not long after. We already have one major feature in (supernova+msvc on Windows), and many small features over the last several months.

What do people think of October or November for a 3.11.2 release?

**Comment by brianlheim** [comment]
i think once we merge https://github.com/supercollider/supercollider/pull/4883, we can do a patch release. i would like to aim for smaller releases, and there are already 5 non-documentation PRs that can be cherry-picked into 3.11 (https://github.com/supercollider/supercollider/projects/19).

**Comment by brianlheim** [comment]
https://github.com/supercollider/supercollider/issues/5033 and https://www.listarc.bham.ac.uk/lists/sc-users-2019/msg66260.html (longer discussion on the same issue) would also be good to tackle

**Comment by dyfer** [comment]
> What do people think of October or November for a 3.11.2 release?

I think that would be great. #4883 would be really nice to get in.
I'd love if #5033 was addressed but I'm not sure I'll have time to look into it myself.

**Comment by dyfer** [comment]
Not sure if we cherry-picked #5014 - I think that might be reasonable addition to fix possible build issues...?

**Comment by brianlheim** [comment]
mhm, couldn't hurt

**Comment by dyfer** [comment]
Another possible bugfix to cherry-pick: #5182

**Comment by brianlheim** [comment]
thanks @dyfer , added it to the board

**Comment by brianlheim** [comment]
at least from my notes from the last meeting, we have the following left to do:
- fix #5176 
- merge #4883 
- merge cherry-pick PRs

**Comment by brianlheim** [comment]
2 cherry-pick PRs are up now: #5214 (docs only) #5215 (non docs changes), i figured it would be easier to review if they were separate.

**Comment by brianlheim** [comment]
after reviewing the PRs merged into develop after 3.11.1 i've also cherry-picked #5011 (a constrained and tested bugfix PR) and #5172 (a documentation PR). after those are merged i'll start the release process.

**Comment by brianlheim** [comment]
alright! i'm going to start on the 3.11.2 release now. i don't believe there's anything left that's a must-fix or must-cherry-pick since we've gone over it a couple times, but if something critical does come up we can discuss it here.  thanks everyone

**Comment by brianlheim** [comment]
hey all, just to give an update, i am still planning to make the 3.11.2 release, but life has been a bit busy the last week or so. there is still #5229 to fix; it is easy but does require a PR. i hope to finish that and the full release by the weekend. thanks for your patience!

**Comment by dyfer** [comment]
thanks for the update @brianlheim !

**Comment by brianlheim** [comment]
#5242 and #5243 are the last functional PRs for 3.11.2; after that we will merge 3.11 into master, tag the release, and merge master to develop.

**Comment by dvzrv** [comment]
Please consider https://github.com/supercollider/supercollider/pull/5014 for whatever is the next release.
The patch is fairly cumbersome to maintain downstream, as it does not apply cleanly (neither on 3.11.1 nor on 3.11.2).

Also, https://github.com/supercollider/supercollider/pull/4836 would be very nice to have! :)

**Comment by brianlheim** [comment]
@dvzrv it's too late for these suggestions; i've already tagged the release. the right time to ask would have been anytime in the last 3 weeks after the rc was announced. would it help to have a direct mention next time? i know you are watching a lot of projects.

i thought i cherry-picked #5014 in #5215 according to your comment here: https://github.com/supercollider/supercollider/issues/4992#issuecomment-686620818, but apparently i misunderstood, sorry.

both #5014 and #4836 are in develop, they will be in the next release which is 3.12.0.

**Comment by brianlheim** [comment]
the 3.11.2 release is now out, so i'm going to close this issue and open a new one for discussing the next release, 3.12.0. thanks to everyone who helped with this release!

**Comment by dvzrv** [comment]
> both #5014 and #4836 are in develop, they will be in the next release which is 3.12.0.

Thanks, that's good enough for me! :)
