### ISSUE TITLE
Supernova doesn't support remote login

### ISSUE THREAD

**Issue by jamshark70** [supercollider/supercollider#5151]
## Environment

* SuperCollider version: 3.11
* Operating system: Doesn't matter

## Steps to reproduce

In a terminal:

```
$ sclang
...
sc3> Server.supernova;
sc3> s.options.maxLogins = 2; s.boot;
```

Then in IDE:

```supercollider
Server.default = s = Server.remote(\remote, NetAddr("127.0.0.1", 57110));
```

## Expected vs. actual behavior

Expected behavior should match scsynth:

```
Requested notification messages from server 'remote'
remote: server process has maxLogins 2 - adjusting my options accordingly.
remote: setting clientID to 1, as obtained from server process.
remote : setting clientID to 1.
```

Actual behavior:

```
Requested notification messages from server 'remote'
remote: no maxLogins info from server process.
remote: setting clientID to 1, as obtained from server process.
WARNING: Server remote couldn't set clientID to 1 - outside of allowed server.maxNumClients range of 0 - 0. clientID is still 0.
```

Updates to scsynth boot/handshaking logic changed the OSC spec for `/notify` done and failure replies. Supernova was never updated for the new spec.

TBH I'm a bit worried about supernova's maintenance status. It's starting to smell like an abandoned project -- nobody's intention to let this happen, but let's be honest. There are years-old bugs and nobody is stepping up to fix them. It may be time for an RFC about the future of multicore support in SC. I hesitate to open an RFC by myself because parallel real-time processing is *way* outside my expertise -- just reminding for now that the current situation is not really sustainable.

**Comment by brianlheim** [comment]
there were 5 bugs fixed in supernova for this last release: https://github.com/supercollider/supercollider/blob/develop/CHANGELOG.md#scsynth-and-supernova-fixed. it's not abandoned.

**Comment by brianlheim** [comment]
there was a long discussion in slack about merging scsynth and supernova. IIRC people there thought it would be feasible and that it would probably look like adding multithreaded support to scsynth rather than the other way around.

**Comment by jamshark70** [comment]
> it's not abandoned.

Glad to hear that.

The supernova showstoppers for me are: moving groups around can crash supernova (I thought I logged this, but I can't find it now -- a couple years ago I had to abandon supernova for a show because it would crash about half the time in a transition section halfway through -- I think it's because of supernova's analysis of dependencies between groups -- if there are too many moves in a short time, it can't keep up), and #3100 about n_order (I hit the crashing bug by trying to work around this bug).

You're right that my comment is too harsh. But, there's no movement on these bugs and I just can't use supernova in that condition. I don't dare take it onstage if managing group order is fragile.

> IIRC people there thought it would be feasible and that it would probably look like adding multithreaded support to scsynth rather than the other way around.

I'd be ok with that.

**Comment by jamshark70** [comment]
Oh, now I see I should close this as a dup: #3337 (2017, milestoned for 3.9) and #3860 (2018). So I'll close it, but let's maybe pay off this bit of technical debt.

**Comment by brianlheim** [comment]
> You're right that my comment is too harsh. But, there's no movement on these bugs and I just can't use supernova in that condition. I don't dare take it onstage if managing group order is fragile.

some of the bugs fixed in this patch release were also really bad ones (multithreading FFT on macOS, crashing when trying to read metadata files). there is movement, just not where you want it at the moment, and it's okay to be frustrated about that; but it misses the bigger picture that good work is happening on supernova -- incrementally, like all things in this project. in the 3.12 release we will have supernova included in the windows distribution for the first time since 3.8.0 in 2016, which may increase interest in it and draw more attention to fixing these bugs.
