### ISSUE TITLE
exception in real time with new SC update

### ISSUE THREAD

**Issue by twistin** [supercollider/supercollider#5152]
Hi, today I updated Supercollider to the version 3.11.1 , and when I use PBind or as the attached case, a pattern I get the following error:
"exception in real time: alloc failed, increase server's memory allocation (e.g. via ServerOptions)"

I modified the memory using ServerOptions but did not solve the problem 
## Environment

* SuperCollider version: 3.11.1
* Operating system: OSX Catalina 
* Other details (Qt version, audio driver, etc.): Saffire pro 40 , AKAI MPK25

## Steps to reproduce

```supercollider
Server.local.boot;


BPF
(
SynthDef(\sine, {
	arg atk = 2, sus = 0, rel = 3, c1 = 1, c2 = (-1), freq = 345, amp = 1, out = 0;
	var sig, env, rev;
	env = EnvGen.kr(Env([0,1,1,0],[atk,sus,rel],[c1,0,c2]), doneAction:2);
	sig = Saw.ar(freq);
	sig = sig * env;
	rev = JPverb.ar(sig,  1.0, 0.0,  1.0,  0.707,  0.1, 2.0,  1.0,  1.0,  1.0,  500.0,  2000.0);
	Out.ar(out, rev*0.1 );
}).add;
)
(
[58,65,68,73].midicps.do{
	arg f;

Synth.new(
		\sine,
		[
			\freq, f,
			\amp, 0.25,
		]
	);
};
)
```

## Expected vs. actual behavior

exception in real time: alloc failed, increase server's memory allocation (e.g. via ServerOptions)
exception in real time: alloc failed, increase server's memory allocation (e.g. via ServerOptions)
exception in real time: alloc failed, increase server's memory allocation (e.g. via ServerOptions)
exception in real time: alloc failed, increase server's memory allocation (e.g. via ServerOptions)
exception in real time: alloc failed, increase server's memory allocation (e.g. via ServerOptions)
exception in real time: alloc failed, increase server's memory allocation (e.g. via ServerOptions)
exception in real time: alloc failed, increase server's memory allocation (e.g. via ServerOptions)
exception in real time: alloc failed, increase server's memory allocation (e.g. via ServerOptions)
exception in real time: alloc failed, increase server's memory allocation (e.g. via ServerOptions)
exception in real time: alloc failed, increase server's memory allocation (e.g. via ServerOptions)
exception in real time: alloc failed, increase server's memory allocation (e.g. via ServerOptions)
exception in real time: alloc failed, increase server's memory allocation (e.g. via ServerOptions)
exception in real time: alloc failed, increase server's memory allocation (e.g. via ServerOptions)
exception in real time: alloc failed, increase server's memory allocation (e.g. via ServerOptions)
exception in real time: alloc failed, increase server's memory allocation (e.g. via ServerOptions)
exception in real time: alloc failed, increase server's memory allocation (e.g. via ServerOptions)
exception in real time: alloc failed, increase server's memory allocation (e.g. via ServerOptions)
exception in real time: alloc failed, increase server's memory allocation (e.g. via ServerOptions)
exception in real time: alloc failed, increase server's memory allocation (e.g. via ServerOptions)
exception in real time: alloc failed, increase server's memory allocation (e.g. via ServerOptions)
exception in real time: alloc failed, increase server's memory allocation (e.g. via ServerOptions)
exception in real time: alloc failed, increase server's memory allocation (e.g. via ServerOptions)
exception in real time: alloc failed, increase server's memory allocation (e.g. via ServerOptions)
exception in real time: alloc failed, increase server's memory allocation (e.g. via ServerOptions)
exception in real time: alloc failed, increase server's memory allocation (e.g. via ServerOptions)
exception in real time: alloc failed, increase server's memory allocation (e.g. via ServerOptions)
exception in real time: alloc failed, increase server's memory allocation (e.g. via ServerOptions)
exception in real time: alloc failed, increase server's memory allocation (e.g. via ServerOptions)
exception in real time: alloc failed, increase server's memory allocation (e.g. via ServerOptions)
exception in real time: alloc failed, increase server's memory allocation (e.g. via ServerOptions)
exception in real time: alloc failed, increase server's memory allocation (e.g. via ServerOptions)
exception in real time: alloc failed, increase server's memory allocation (e.g. via ServerOptions)
exception in real time: alloc failed, increase server's memory allocation (e.g. via ServerOptions)
exception in real time: alloc failed, increase server's memory allocation (e.g. via ServerOptions)
exception in real time: alloc failed, increase server's memory allocation (e.g. via ServerOptions)
exception in real time: alloc failed, increase server's memory allocation (e.g. via ServerOptions)
exception in real time: alloc failed, increase server's memory allocation (e.g. via ServerOptions)

**Comment by brianlheim** [comment]
your code produces that printout for me on macOS Catalina with both 3.11.0 and 3.11.1, but running:

```supercollider
Server.local.options.memSize_(1024*1024)
Server.local.reboot
```

fixes the issue in both versions. does that work for you?

**Comment by twistin** [comment]
@brianlheim perfect, problem solved I close the thread. Thank you very much!!!!
