### ISSUE TITLE
DrawGrid etc now plots log grids, but incorrectly

### ISSUE THREAD

**Issue by sternsc** [supercollider/supercollider#5156]
Environment

* SuperCollider version: 3.11.x
* Operating system: Windows 10 64-bit, 32-bit
* Other details (Qt version, audio driver, etc.): Qt 5.11.3 

## Steps to reproduce

```supercollider code:
(
c = ControlSpec.new(0,20000, \exp, units:"Hz");
g = GridLines(c);
DrawGrid.test(nil, g);
)
```

## Expected vs. actual behavior
Before 3.11, DrawGrid-GridLines entirely ignored the \exp warp in the associated ControlSpec. 
Now a log grid is plotted, but not fully, if it extends over more than one decade.
See also issue #3428.

**Comment by sternsc** [comment]
Sorry, the title of this issue should include "from a ControlSpec". Typing slip.
/ST

**Comment by sternsc** [comment]
I searched for relevant changes in "Grid.sc" but could not find any. Maybe issue #4817 is implicated here as well. /ST

**Comment by brianlheim** [comment]
ControlSpec underwent some change for the 3.11 release. I'm not all that familiar with it or with GridLines so maybe this a naive observation, but exponential ranges starting at 0 are kind of buggy by definition, and I wouldn't expect them to be supported well by any standard library utilities. Also (since I've never used this piece of the library before), is the new behavior (log-scale grid) better or definitely not?

**Comment by brianlheim** [comment]
> Maybe issue #4817 is implicated here as well. /ST

that PR is in 3.11.1, but not 3.11.0, so not related. this is the PR that made the Spec changes: https://github.com/supercollider/supercollider/pull/3814

**Comment by jamshark70** [comment]
> exponential ranges starting at 0 are kind of buggy by definition

They're mathematically impossible in the real number domain.

Probably should close this one. There is no way to implement the example that was given.

**Comment by brianlheim** [comment]
hmm, the reason i left it open was because of this:

> Before 3.11, DrawGrid-GridLines entirely ignored the \exp warp in the associated ControlSpec

when we're talking about the diff before and after sc 3.11.0, does the above statement apply to all ControlSpecs with \exp warp or is it only for those that start at 0?

**Comment by sternsc** [comment]
Clumsy of me, to set the lower limit as zero in the example. The problem is there also with 20,20000 as limits, or anything spanning more than a decade. It's very quick to try with the code snippet I gave.

Hämta Outlook för Android<https://aka.ms/ghei36>

________________________________

**Comment by dyfer** [comment]
I think grid was updated in #4223 to support non-linear specs.

Is the plotting "incorrect", i.e. are the lines with values shown in wrong places? Or is the spacing/distribution of the grid less-than-ideal? I thought it's the latter, but I might be wrong.

**Comment by sternsc** [comment]
I think that with warp:\exp, the lines that are plotted are in the right places. But there are not enough of them, if the range is larger than one power of ten. Just try it and you will see. (This code gives different results on 3.11 and on earlier versions.)

(
c = ControlSpec.new(20,20000, \exp, units:"Hz");
g = GridLines(c);
DrawGrid.test(nil, g);
)

While we're at it, I have two other issues with drawing grids:
1) I have never been able to control the desired number of ticks on a grid axis, even though the code seems to provide for that. The docs are not very clear about how it _should_ work. Not sure if I am doing something wrong or if the code is not working.
2) As from 3.10.0, Float:asString appends a ".0" to floats without a fraction (#3585). This is annoying when plotting tick labels because it makes the chart busier, quite unnecessarily.

I wrote some method overrides for GridLines:getParams and GridLines:formatLabel that worked around these things, and drew log grids correctly, but now that the class library behavior has changed, these overrides no longer work. 

I'd be very happy to try and help resolve this, if I can do so without having to hack the class libraries myself. I'm just a scientist writing signal analysis software, and I need log grids.

Best, 
Sten T

**Comment by dyfer** [comment]
> I think that with warp:\exp, the lines that are plotted are in the right places. But there are not enough of them, if the range is larger than one power of ten. Just try it and you will see.

Of course I tried :) I wanted to confirm that I interpret what I see correctly and understand what you mean. And I agree that the spacing of the grid lines is not "good".

> 
> While we're at it, I have two other issues with drawing grids:
> 
> 1. I have never been able to control the desired number of ticks on a grid axis, even though the code seems to provide for that. The docs are not very clear about how it _should_ work. Not sure if I am doing something wrong or if the code is not working.

I don't think I have worked on it myself, but I remember that the source mentioned some "intelligent" way of determining the position of the gridlines. It's not perfect for sure, and _it hasn't been adjusted after \exp warp support was added_, AFAIU.

> 2. As from 3.10.0, Float:asString appends a ".0" to floats without a fraction (#3585). This is annoying when plotting tick labels because it makes the chart busier, quite unnecessarily.

I'd support dropping ".0" from the plots.

> I wrote some method overrides for GridLines:getParams and GridLines:formatLabel that worked around these things, and drew log grids correctly, but now that the class library behavior has changed, these overrides no longer work.
> 
> I'd be very happy to try and help resolve this, if I can do so without having to hack the class libraries myself. I'm just a scientist writing signal analysis software, and I need log grids.

I would really like to see improved log grids! 
Since you wrote method overrides, you clearly have hacked the class library yourself :) Would you be willing to provide a PR with a solution? Or at least post your previous workarounds? Thanks!

**Comment by sternsc** [comment]
OK, thanks @dyfer for your comments. I have pored over the class library code in Spec.sc and Grid.sc for 3.10 and 3.11 but I can't find any difference; so I don't know why only the latter heeds the \exp warp. But I did manage to modify my overriding code so that it produces the output I want, in either SC version. I attach it here as a text file. 

[GridLinesExp.sc.txt](https://github.com/supercollider/supercollider/files/5167526/GridLinesExp.sc.txt)

For y-axis log grids, it is nicer to place the tick labels above rather than below the gridline:
(
c = ControlSpec.new(20,20000, \exp, units:"Hz");
g = GridLines(c);
d = DrawGrid.test(nil, g, Rect(0,0,400,800));
d.y.labelOffset_(4 @ -11);      // could go in DrawGridY:init 
)

**Comment by dyfer** [comment]
Thanks @sternsc 
I _think_ the change was done [here in Grid.sc](https://github.com/supercollider/supercollider/pull/4223/files#diff-274088026b8d5c04d035237a8a78029cR110)

Are you willing to put together a pull request with your changes? or would you rather have someone else to use them and prepare a PR?

**Comment by sternsc** [comment]
Ah, interesting.

I think my changes need to be reviewed for general use, as they are tailored for the appearance of a particular application, and might not be ideal as a more general solution. I’d feel more comfortable if someone well versed in the class library used them and made the PR.

For instance, I find the cross-linking of ControlSpec-GridLines a bit confusing, with each containing a reference to the other, and the order of instantiation not being explicit (they seem to create each other, if missing). Also, I still haven’t been able to set a desired number of ticks (using ControlSpec:step, or what?) in a way that has any effect. It would be nice to get that explained.

Many thanks for being so helpful!

**Comment by brianlheim** [comment]
@dyfer or @sternsc could one of you please summarize what the purpose of this ticket is now if you have time?

**Comment by dyfer** [comment]
@brianlheim I think the summary could be as follows:

> Spacing of log Grids is illegible
> 
> GridLines display non-linear Grids by drawing lines spaced equally in data, not pixels, resulting in visual representation that is too sparse on one end and too condensed on the other end of the grid.

Example:
```supercollider
(
c = ControlSpec.new(20,20000, \exp, units:"Hz");
g = GridLines(c);
d = DrawGrid.test(g, nil, 500@100);
)
```
Result:
![Screen Shot 2020-09-10 at 9 49 43 AM](https://user-images.githubusercontent.com/1589177/92766382-06c6a580-f34b-11ea-9be7-135797a4ee36.png)

I started incorporating @sternsc's fix/suggestions into a PR but I'm still working on it.

**Comment by sternsc** [comment]
Thanks @dyfer for dealing with this. I think that the problem with log Grids is that the library only plots the gridlines for the highest power of 10 in the requested range, and not for the lower decades. My workaround solves that.

Also I recently found that, with very small tick values, the label formatting for log values in my workaround fails due to rounding. I think this is a minor problem, since any sensible plotting would probably add SI prefixes (nano-, micro-, kilo-, Mega-, etc) to keep the numbers within a readable range. Anyway, here is a fix for the fix:

                // This GridLines method added by S.T.
                formatLabelExp { arg val, numDecimalPlaces;
                                var strVal, strUnit, valLog;
                                valLog = val.log10;
                                if(valLog.frac < 0.01,
                                                { strVal = val.round(10**(valLog.round)).asString; strUnit = (spec.units ? "")},
                                                { strUnit = "";
                                                                if (val==this.niceNum(val,false),
                                                                                { strVal = val.asString;},
                                                                                { strVal = "" }
                                                                )}
                                );
                                if (strVal.endsWith(".0"), { strVal = strVal.split($.)[0] });
                                ^(strVal + strUnit)
                }

**Comment by dyfer** [comment]
>Also I recently found that, with very small tick values, the label formatting for log values in my workaround fails due to rounding. I think this is a minor problem, since any sensible plotting would probably add SI prefixes (nano-, micro-, kilo-, Mega-, etc) to keep the numbers within a readable range. 

Could you provide example code to show the problem? How small should the values be to show the issue?
