### ISSUE TITLE
The SCIDE should tell if a document is "dirty"

### ISSUE THREAD

**Issue by Spacechild1** [supercollider/supercollider#5163]
Currently, the IDE doesn't tell users that a document has unsaved changes ("dirty").

A common solution is to add a "*" to the document title.

**Comment by brianlheim** [comment]
is this perhaps a duplicate of https://github.com/supercollider/supercollider/issues/5008?

**Comment by Spacechild1** [comment]
Most certainly :-). I tried to search first, but didn't see this.
