### ISSUE TITLE
macOS builds fail on Travis

### ISSUE THREAD

**Issue by dyfer** [supercollider/supercollider#5167]
## Environment

* SuperCollider version: current
* Operating system: macOS
* Other details (Qt version, audio driver, etc.): TravisCI

## Steps to reproduce

Push a new commit to a branch with TravisCI active.

## Expected vs. actual behavior

CI on macOS fails in the testing stage (`qpm`)

Let's use this ticket to track progress on this issue.

**Comment by brianlheim** [comment]
one example: https://travis-ci.org/github/supercollider/supercollider/jobs/727715631

also: https://api.travis-ci.com/v3/job/387251453/log.txt

```
2020-09-18 23:18:02,516 (DEBUG) qpm : sclang was not launched.

2020-09-18 23:18:02,516 (DEBUG) qpm : output:

compiling class library...



2020-09-18 23:18:02,516 (DEBUG) qpm : error:

The available OpenGL surface format was either not version 3.2 or higher or not a Core Profile.

Chromium on macOS will fall back to software rendering in this case.

Hardware acceleration and features such as WebGL will not be available.



[31mERROR:

Process not running[39m
```

**Comment by dyfer** [comment]
This seems to be a problem with QT 5.15.1
I can confirm on macOS 10.13, QT 5.15.1 - sclang doesn't start:
```
-> ./sclang
compiling class library...
Could not find QtWebEngineProcess
Abort trap: 6
```

**Comment by dyfer** [comment]
Closing in favor of #5175
