### ISSUE TITLE
Raise C++ standard from 11 to 17

### ISSUE THREAD

**Issue by brianlheim** [supercollider/supercollider#5170]
Qt 6 will require C++17. This is ticket for general discussion on how feasible that is for us.

Reference for compiler support: https://en.cppreference.com/w/cpp/compiler_support

gcc7 and clang4 are a minimum.

**Comment by brianlheim** [comment]
Compiler requirements:
- MSVC 2017
- gcc 7
- clang 4
- appleclang -- not sure? looks to be at the latest xcode 11 for most features

these are all within our platform support guarantees for toolchains. for OS's, checking how easy it is to get a supported toolchain:
- macOS - no problem
- Windows - no problem
- Ubuntu: 4 years, 2 LTS releases - bionic has gcc 7, focal has gcc 9
- Debian: 4 years, 2 major releases - buster has gcc 7. debian's package search seems to be down right now. i can see that gcc 6.3 is the default in stretch, but can't see if there is a newer version in backports/updates. clang 4 is also available, so stretch does have a toolchain to build supercollider.
- Fedora: latest release  - no problem
- Arch Linux: latest release - no problem
- Raspberry Pi (Raspbian): latest release - based on buster, should be OK
- BeagleBone Black (Debian): latest release - seems OK but i'm not sure

We could also bump the cmake version to 3.8 (released in 2017 i think), since it is the first version of cmake to support `set(CMAKE_CXX_STANDARD 17)` and know about c++17 in general, that would let us simplify some code. ubuntu bionic has 3.10, and debian stretch-backports has 3.16.

**Comment by timblechmann** [comment]
> appleclang

problem is not necessarily appleclang, but the minimum deployment target of macos. the c++ runtime library of older macos versions may not support every stl library feature.

though the other question is: do people on old systems need the latest sc?

**Comment by brianlheim** [comment]
good point. i just built sc with C++17 (including supernova) on Catalina with 10.10 as a deployment target, so it seems OK if we aren't using new features. it does error out if you use something from std::filesystem for example, unless you set the deployment target to 10.15.

when Qt6 is actually released it may use std::filesystem or something else which would require us to bump up the lowest supported.

idk if you are aware but we only guarantee support for two macOS versions now (currently Mojave and Catalina).

**Comment by timblechmann** [comment]
qt6 has 10.13 as minimum requirement: https://doc-snapshots.qt.io/qt6-dev/supported-platforms.html

**Comment by brianlheim** [comment]
https://github.com/supercollider/supercollider/wiki/Platform-Support

**Comment by brianlheim** [comment]
Note from discussion in #5396: https://github.com/supercollider/supercollider/pull/5396#issuecomment-803434947: we will ensure that the 3.12.0 release (and maybe 3.12.x as a whole) is gcc-6.3 compatible and then raise the requirements for later releases once the newer Bullseye Bela system is out.
