### ISSUE TITLE
SuperCollider doesn't run with QT 5.15.1 on macOS

### ISSUE THREAD

**Issue by dyfer** [supercollider/supercollider#5175]
## Environment

* SuperCollider version: develop
* Operating system: macOS 10.13
* Other details (Qt version, audio driver, etc.): QT 5.15.1

## Steps to reproduce

1. build supercollider (builds fine)
2. run sclang
result:
```
-> ./sclang
compiling class library...
Could not find QtWebEngineProcess
Abort trap: 6
```
This also causes our Travis builds to fail currently (as reported in #5167)
The error message in Travis suggest an issue with QtWebEngine, but I'm not sure if this is the right lead.
## Expected vs. actual behavior

SuperCollider/sclang is expected to run after it builds :)

EDIT: additional info
SC runs if built in XCode using XCode project. However, it fails if built using CMake.

EDIT 2: we could consider updating our Travis jobs to use newer VM images, but not update Qt, which is currently at 5.15.0 on these newer images. This is orthogonal to fixing this issue, more directly related to #5167. I have a [branch](https://github.com/dyfer/supercollider/tree/topic/travis-macos-speedup) that has Travis builds updated and these jobs do run successfully

**Comment by brianlheim** [comment]
> SC runs if built in XCode using XCode project. However, it fails if built using CMake.

which version of cmake are you using?

**Comment by dyfer** [comment]
> which version of cmake are you using?

I just upgraded to CMake 3.18.3 and it keeps happening. It happened before the upgrade as well, but I'm not sure which version was that, possibly 3.16.x...

**Comment by dyfer** [comment]
I think I've found a [bug in Qt Issue Tracker](https://bugreports.qt.io/browse/QTBUG-86759) for this. I can confirm that in my 5.15.1 build `/SuperCollider.app/Contents/Frameworks/QtWebEngineCore.framework/Versions/5/Helpers/QtWebEngineProcess` has zero bytes, while in previous builds it has 30 KB.

It says `Resolution: Done` but `Fix Version/s: None`. Does that mean presumably that this won't be fixed until the next release?

**Comment by brianlheim** [comment]
yeah it will be in 5.15.2, the fix was merged into both 5.15 and dev branches

**Comment by brianlheim** [comment]
https://bugreports.qt.io/browse/QTBUG-86759?focusedCommentId=528795&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-528795

> I just copy the QWebEngineView framework manually:
>
> ```
> rm -rf "MyQt.app/Contents/Frameworks/QtWebEngineCore.framework/Versions/5/Helpers"
> cp -R "PATH_TO_QT/Qt/5.15.1/clang_64/lib/QtWebEngineCore.framework/Versions/5/Helpers" "MyQt.app/Contents/Frameworks/QtWebEngineCore.framework/Versions/5/"
> ```
>
> But it looks like there are some other things missing, too:
> 314785: Revert "macdeployqt: Don't copy .prl files into the Resources folder"
> 
> > This was skipping other files from Resources/ as well, such as “en-GB.pak” and “QtWebEngineProcess”.`
> 
> So be careful, you might need to copy additional stuff.

**Comment by brianlheim** [comment]
i am working on a fix now

**Comment by brianlheim** [comment]
that recommended solution doesn't work for basic reasons -- doesn't fixup loader paths or permissions.

**Comment by dyfer** [comment]
I think #5178 closes this. Thanks @brianlheim
