### ISSUE TITLE
Boolean singularity when comparing Pkeys within Pif

### ISSUE THREAD

**Issue by kezkabarra** [supercollider/supercollider#5179]
* SuperCollider version: 3.11.1
* Operating system: Ubuntu 18.04.5 LTS

\rel, Pif(Pkey(\buf) >= 12,2,0.2) // it returns 2 when Pkey(\buf) is 12

\rel, Pif(Pkey(\buf) <= 12,2,0.2) // it also returns 2 when Pkey(\buf) is 12

\rel, Pif(Pkey(\buf) == 12,2,0.2) // it returns 0.2 when Pkey(\buf) is 12

As far as I know about logics, == should return 2 too.
Here's the answer of a reddit user that might set the bugfix on the right track:

__honestly looks like a bug to me... open an issue on github!

EDIT: every object implements it's own version of '==' so probably something wrong with Pkey or one of it's ancestors implementation

EDIT2: i briefly looked at the docs and it seems like it inherits <= and >= from AbstractFunction which evaluates the objects before checking equality, however it inherits '==' from Object which doesn't seem to evaluate before checking equality. so in `Pkey(\buf) >= 12` it's evaluating Pkey(\buf) before checking equality, whereas in Pkey(\buf) == 12 it's just comparing a Pkey object to the number 12... definitely a bug if you ask me._

**Comment by jamshark70** [comment]
Unfortunately this is not fixable.

There are many places in the class library where it's necessary to check an object for equality without evaluating it. A notable place is where we check for "degenerate cases" in UGen math -- in `aUGen + 0`, the + is effectively a no-op and can be deleted. But the only way to know that it's safe to delete is by checking `b == 0`, and we need the Boolean answer right now -- it isn't OK in this case to compose a UGen that calculates `==` later.

Changing the meaning of `==` now would break many places in the class library -- I tried it once and there were many problems that I didn't expect. You're correct that this inconsistency is irritating, but changing it results in a broken class library (not to mention unknown amounts of user code that depends on the current behavior). So, unfortunately, that isn't going to happen.

The currently available workaround is to compose the operator manually: `Pbinop('==', Pkey(\buf), 12)`. This isn't pretty but it does work.

It might be possible to introduce a new operator, say, `|==|`, which would always compose when applied to an AbstractFunction. I'm not totally sure that would work; I could try it a couple of days later.

**Comment by kezkabarra** [comment]
A pity it cannot be fixed. Anyway, thanks a lot for the explanation, the quite robust workaround and your suggestions.

**Comment by telephon** [comment]
Wouldn't it be useful to have a simple answer to this kind of issues by adding a pattern `Pequals` (a pattern) and `Equals` (a UGen)?

**Comment by jamshark70** [comment]
I had proposed a couple of alternate solutions in my earlier message. A `|==|` operator would be syntactically closer to what users expected to write in the first place. An adverb would be less expected but it is a valid way to modify the behavior of an operator for specific cases.

**Comment by jamshark70** [comment]
I was going to post this as an edit to my last comment, but since the issue is closed, nobody would see it. I promise I won't spam this issue any further 😆 tomorrow I may have time to try some things.

Pros and cons:

- Pequal/Equal: Pro: The class of the return value will always be known. Con: Users have to know why to write equality differently for patterns, UGens and other objects -- that is, the form of the expression is tied to the class rather than the intended semantic.

- `|==|`: Pro: Expresses the meaning "check equality based on values to be calculated later if relevant" -- you could write `a |==| b` for just about any a and b, and it would resolve appropriately. (`aPattern |==| aUGen` could never work, though `aNumber |==| aNumber` could resolve immediately.) Con: I can't see one.

- Adverb: Pro: Nothing, really. Con: It looks weird, and it would add an adverb check to every `==`, slowing Dictionary and Set down. So actually the adverb is a pretty bad idea.

**Comment by jamshark70** [comment]
FWIW, I did get `|==|` working (see #5183).

So you would write `\rel, Pif(Pkey(\buf) |==| 12, 2, 0.2)`.

**Comment by lgvr123** [comment]
>     * `|==|`: Pro: Expresses the meaning "check equality based on values to be calculated later if relevant" -- you could write `a |==| b` for just about any a and b, and it would resolve appropriately. (`aPattern |==| aUGen` could never work, though `aNumber |==| aNumber` could resolve immediately.) Con: I can't see one.

Con: I would say, pretty difficult to discover for non expert users ;-)

By the way, when is this available ? I just installed 3.11.2 and |==| is still not there.

**Comment by jamshark70** [comment]
> By the way, when is this available?

Scroll up a bit -- it's been merged into the development branch, which means, next release.

**Comment by lgvr123** [comment]
> Scroll up a bit -- it's been merged into the development branch, which means, next release.
Good news. I saw the "merged", but it was unclear to which branch it was merged, and when that branch meant to be released as RC or final version. Seeing the merge date (Sep 20) I expected it to be part of November 20 release. Still a little bit of patience.
