### ISSUE TITLE
New Groups should have `isPlaying` set

### ISSUE THREAD

**Issue by totalgee** [supercollider/supercollider#5194]
## Environment

* SuperCollider version: 3.11.0
* Operating system: Windows 10
* Other details (Qt version, audio driver, etc.):

## Steps to reproduce

```supercollider
g = Group();
Ndef(\a).parentGroup_(g).source = {SinOsc.ar(440!2) };
```

## Expected vs. actual behavior

Expected the new NodeProxy's internal Group to be created inside the Group `g`. However, you get an error message instead:

```txt
NodeProxy:parentGroup_ : cannot make non-playing node parentGroup
```

According to @jamshark70, the new Group should have `isPlaying` set by default, as soon as it's "alive" on the Server, as this is the mechanism used by `NodeWatcher`. See discussion here, beginning with this message: https://scsynth.org/t/cpu-headroom-supernova-multiple-servers/2752/6

My "workaround" (which shouldn't be necessary) is the following -- manually setting `isPlaying`:

```supercollider
g = Group().isPlaying_(true);
Ndef(\a).parentGroup_(g).source = {SinOsc.ar(440!2) };
```

**Comment by jamshark70** [comment]
That wasn't my recommendation.

My recommendation was to call `.register` on the group immediately after creating it. This will set the `isPlaying` flag.

I don't think we should change the default behavior here -- too many unknown consequences for user code.

**Comment by totalgee** [comment]
Okay, that was my misunderstanding of what you said. I guess that means this can be closed... (I confirmed that calling `.register` instead of `.isPlaying_(true)` does indeed work for my purposes! 👍)
