### ISSUE TITLE
README_LINUX does not describe release installation 

### ISSUE THREAD

**Issue by MushiTheMoshi** [supercollider/supercollider#5202]
#4554  Environment

* SuperCollider version: 3.11
* Operating system: ubuntu:20.04
* Other details (Qt version, audio driver, etc.):

Hi there, linux guide does not contains instructions using the release version , would it be please possible some guidance using the version in the release section?

thanks in advance,
Julio

**Comment by brianlheim** [comment]
hi, i'm not sure exactly what the issue is. there are instructions for building a release build here: https://github.com/supercollider/supercollider/blob/develop/README_LINUX.md#compiler-optimizations

**Comment by brianlheim** [comment]
the readme also lists how to install and run SC, which would include release configurations.

**Comment by MushiTheMoshi** [comment]
I'm sorry, let me elaborate. I'm trying using this [tar](https://github.com/supercollider/supercollider/releases/download/Version-3.11.1/SuperCollider-3.11.1-Source.tar.bz2), after extract the tar I find a bunch of files and a linux guide which does not match with the current files, do I need to follow the cmake building in order to make to run?

**Comment by MushiTheMoshi** [comment]
I tried this:
```root@eb3f4f1b1f82:/opt/supercollider# ls -l
total 732
-rw-r--r--  1 1000 1000   5820 Aug 21 16:24 AUTHORS
-rw-r--r--  1 1000 1000 174506 Aug 21 16:24 CHANGELOG.md
-rw-r--r--  1 1000 1000 261850 Aug 21 16:24 CHANGELOG_archive.md
-rw-r--r--  1 1000 1000  22112 Aug 21 16:24 CMakeLists.txt
-rw-r--r--  1 1000 1000   9936 Aug 21 16:24 CODE_OF_CONDUCT.md
-rw-r--r--  1 1000 1000    117 Aug 21 16:24 CONTRIBUTING.md
-rw-r--r--  1 1000 1000  35147 Aug 21 16:24 COPYING
-rw-r--r--  1 1000 1000    160 Aug 21 16:24 DEVELOPING.md
drwxr-xr-x 11 1000 1000   4096 Aug 21 16:24 HelpSource
-rw-r--r--  1 1000 1000    167 Aug 21 16:24 INSTALL
drwxr-xr-x  7 1000 1000   4096 Aug 21 16:24 QtCollider
-rw-r--r--  1 1000 1000   5662 Aug 21 16:24 README.md
-rw-r--r--  1 1000 1000   6102 Aug 21 16:24 README_BEAGLEBONE_BLACK.md
-rw-r--r--  1 1000 1000    399 Aug 21 16:24 README_IPHONE.md
-rw-r--r--  1 1000 1000   2573 Aug 21 16:24 README_JAILBROKEN_IPHONE.md
-rw-r--r--  1 1000 1000  13804 Aug 21 16:24 README_LINUX.md
-rw-r--r--  1 1000 1000  14678 Aug 21 16:24 README_MACOS.md
-rw-r--r--  1 1000 1000   8226 Aug 21 16:24 README_RASPBERRY_PI.md
-rw-r--r--  1 1000 1000  62953 Aug 21 16:24 README_WINDOWS.md
drwxr-xr-x 11 1000 1000   4096 Aug 21 16:24 SCClassLibrary
drwxr-xr-x  2 1000 1000   4096 Aug 21 16:24 SCDoc
-rw-r--r--  1 1000 1000   1363 Aug 21 16:24 SCVersion.txt
-rw-r--r--  1 1000 1000     39 Aug 21 16:24 build_sclang.cfg.in
drwxr-xr-x  2 1000 1000   4096 Aug 21 16:24 cmake_modules
drwxr-xr-x  2 1000 1000   4096 Aug 21 16:24 common
drwxr-xr-x  6 1000 1000   4096 Aug 21 16:24 editors
drwxr-xr-x  8 1000 1000   4096 Aug 21 16:24 examples
drwxr-xr-x  3 root root   4096 Oct 18 09:02 extensions
drwxr-xr-x 17 1000 1000   4096 Aug 21 16:24 external_libraries
drwxr-xr-x  2 1000 1000   4096 Aug 21 16:24 icons
drwxr-xr-x  6 1000 1000   4096 Aug 21 16:24 include
drwxr-xr-x  4 1000 1000   4096 Aug 21 16:24 lang
drwxr-xr-x  6 1000 1000   4096 Aug 21 16:24 platform
drwxr-xr-x  5 1000 1000   4096 Aug 21 16:24 server
drwxr-xr-x  2 1000 1000   4096 Aug 21 16:24 sounds
drwxr-xr-x  5 1000 1000   4096 Aug 21 16:24 testsuite
drwxr-xr-x  5 1000 1000   4096 Aug 21 16:24 tools
root@eb3f4f1b1f82:/opt/supercollider# cmake
Usage

  cmake [options] <path-to-source>
  cmake [options] <path-to-existing-build>
  cmake [options] -S <path-to-source> -B <path-to-build>

Specify a source directory to (re-)generate a build system for it in the
current working directory.  Specify an existing build directory to
re-generate its build system.

Run 'cmake --help' for more information.

root@eb3f4f1b1f82:/opt/supercollider# make
make: *** No targets specified and no makefile found.  Stop.
```

**Comment by brianlheim** [comment]
yes, you need to build from source on linux.

**Comment by MushiTheMoshi** [comment]
Alright, thanks sorry about the noise, one las question. Is it possible without QT or in a headless/unattended/scripted mode?

**Comment by brianlheim** [comment]
looks like 3.10.0 is available in focal (20.04) - https://packages.ubuntu.com/search?keywords=supercollider&searchon=names but we don't have anyone packaging recent releases (help very much wanted :) )

**Comment by brianlheim** [comment]
> Is it possible without QT or in a headless/unattended/scripted mode?

yes! you will want to pass the following flags to CMake:  `-DSC_IDE=OFF -DNO_X11=ON -DSC_QT=OFF `. this is covered in our raspberry pi instructions but not in the linux instructions (we should probably add them there): https://github.com/supercollider/supercollider/blob/develop/README_RASPBERRY_PI.md#step-4-compile-and-install-supercollider

basically your commands will look like

```bash
# cd to source directory
mkdir build && cd build
cmake .. -DCMAKE_BUILD_TYPE=Release -DSC_IDE=OFF -DNO_X11=ON -DSC_QT=OFF # other flags as desired
make # -j<n> as desired
make install
```

**Comment by MushiTheMoshi** [comment]
Thanks a lot!!!
