### ISSUE TITLE
scsynth_main.cpp: unistd.h is not included so _POSIX_MEMLOCK is undefined

### ISSUE THREAD

**Issue by giuliomoro** [supercollider/supercollider#5210]
## Environment

* SuperCollider version: 6abb4ff483918b390ba57b3e9cffe69b98221ce3
* Operating system: any

## Expected vs. actual behavior

in several places in `server/scsynth/scsynth_main.cpp`, the macro `_POSIX_MEMLOCK` is checked to decide whether to enable memory locking.  However, `unistd.h` is not included, so the macro is always undefined. As far as I can tell, this means that the `mlockall()` call in `World_New()` is never executed.

**Comment by brianlheim** [comment]
thanks for pointing this out! fixed here i think: #5211
