### ISSUE TITLE
sclang: Complex.sqrt is missing

### ISSUE THREAD

**Issue by joslloand** [supercollider/supercollider#5213]
## Motivation

At the moment complex number support implemented in sclang does not include a named instance method to return the square root of a value. Users expecting to manipulate complex numbers would usually expect this unary operator to be supported.

## Description of Proposed Feature

While `Complex.pow(2.reciprocal)` may be used to return the expected value, a named method would be more ergonomic and expected, aligning with support of `sqrt` across various magnitude classes.

The proposal is to: 
- add `sqrt` as a method to `Complex`.
- add supporting documentation to accompanying Help

## Plan for Implementation

- [x] review current implementation of `Complex.pow(2.reciprocal)`
- [x] simplify & refactor for single square root case
- [x] submit PR

**Comment by jamshark70** [comment]
Good idea.

Some notes: https://math.stackexchange.com/questions/44406/how-do-i-get-the-square-root-of-a-complex-number

**Comment by joslloand** [comment]
Thanks @jamshark70

After some tests I've picked the [Wolfram](https://mathworld.wolfram.com/SquareRoot.html) algorithm to return the [principal square root](https://mathworld.wolfram.com/PrincipalSquareRoot.html).

This is simple to implement and appears to return good results without much numerical noise.

**Comment by brianlheim** [comment]
C++ has a builtin sqrt on complex numbers; i would suspect we'll use that unless there is a serious reason not to: https://en.cppreference.com/w/cpp/numeric/complex/sqrt

**Comment by joslloand** [comment]
@brianlheim notes:

> C++ has a builtin sqrt on complex numbers; i would suspect we'll use that unless there is a serious reason not to: https://en.cppreference.com/w/cpp/numeric/complex/sqrt

Ah, ok... that makes sense. Doing so might also imply refactoring `Complex` to further take advantage of the C++ builtins.

I started looking at this in terms of simplifying `Complex.sqrt` as a special case of `Complex.pow`. Given the C++ numerics library also [includes pow](https://en.cppreference.com/w/cpp/numeric/complex/pow), there could be a case here for replacing the current `Complex.pow` implementation, which is [quite verbose](https://github.com/supercollider/supercollider/blob/cc56c994fa205e3df53db9b6615753b55cc259fa/SCClassLibrary/Common/Math/Complex.sc#L98-L126).

Relatedly, with a closer inspection there may be [more complex builtins](https://en.cppreference.com/w/cpp/numeric/complex) with which it would make sense to refactor `Complex`.

**Comment by joslloand** [comment]
As a follow up... I'm up for having a look at refactoring `Complex` to [deploy C++ builtins](https://en.cppreference.com/w/cpp/numeric/complex). It isn't clear to me, however, how to re-write appropriate calls in Complex.sc to do so.

Can anyone point me to a quick example on how to get started? I particular, I don't immediately see get what the call should look like. This certainly _doesn't work_:

`sqrt { _Sqrt; ^this.primitiveFailed }`

Presumable the `real` and `imag` instance vars need to be passed. And maybe a new primitive, `_CmpxSqrt` (?), would need to be imported?

**Comment by joslloand** [comment]
Note: PR #5220 is _just_ the [Wolfram algebraic implementation](https://mathworld.wolfram.com/SquareRoot.html) in sclang.

**Comment by brianlheim** [comment]
@joslloand thanks for the PR!

i've opened #5221 to discuss using C++ for the complex implementation
