### ISSUE TITLE
macOS: some app bundle contents are unexpectedly unwriteable

### ISSUE THREAD

**Issue by brianlheim** [supercollider/supercollider#5222]
## Environment

* SuperCollider version: 3.11.2-rc1
* Operating system: macOS
* Other details (Qt version, audio driver, etc.): Qt 5.15.1

## Steps to reproduce

Only appears as a problem when running `xattr -rc`

## Expected vs. actual behavior

Unlike previous releases, the following files inside the QtWebEngineProcess.app bundle are given permissions 444 instead of 644: `Contents/{Info.plist,PkgInfo,Resources/*}`. this is because permissions on these files are not changed by the Qt 5.15.1 deploy step in the build system. it's an easy fix.

This is mainly an inconvenience for me as release manager, I have to run an extra command before signing. It generally doesn't affect users on macOS, the one case it might pop up is when trying to un-quarantine the app, but one can work around it by running `xattr` as sudo instead.

this doesn't affect the 3.11.2-rc1 release, but we should fix it for 3.11.2.

**Comment by dyfer** [comment]
What would be a proposed fix for this? change the permissions with `chmod` in the `fixup_bundle` stage of the build?

**Comment by brianlheim** [comment]
yep: https://github.com/supercollider/supercollider/blob/develop/editors/sc-ide/CMakeLists.txt#L541-L544

(also note my ironic comment)
