### ISSUE TITLE
Big Sur support - SC IDE hangs on launch

### ISSUE THREAD

**Issue by joshpar** [supercollider/supercollider#5227]
## Environment

* SuperCollider version: 3.11.2 RC1
* Operating system: maacOS 11
* Other details (Qt version, audio driver, etc.):

## Steps to reproduce

On Mac OS Big Sur, download and launch the RC binary

## Expected vs. actual behavior

The application process appears to hang at 100% for minutes. A sample of the process is attached below. Builds made on my Big Sur machine launch.

[Sample of SuperCollider.txt](https://github.com/supercollider/supercollider/files/5452892/Sample.of.SuperCollider.txt)

**Comment by brianlheim** [comment]
@joshpar gonna move this to #5160
