### ISSUE TITLE
Some syntax errors are not caught by the interpreter

### ISSUE THREAD

**Issue by dyfer** [supercollider/supercollider#5232]
## Environment

* SuperCollider version: 3.11, develop
* Operating system: macOS
* Other details (Qt version, audio driver, etc.):

## Steps to reproduce
Compare two syntactically incorrect examples:

```supercollider
// no error thrown (nor is the true function evaluated)
(
if(true.isFloat.not {
	"yes".postln;
});
)

// syntax error thrown
(
if(true {
	"yes".postln;
});
)
```

## Expected vs. actual behavior

The first examples should throw a syntax error. Why doesn't it do it?

**Comment by jamshark70** [comment]
It is legal syntax.

A method call using dot syntax is `receiver.selector(arguments...)` *but* if the trailing arguments are functions, they may be appended after the parentheses, without commas.

These are equivalent.

```
for(1, 10, { |i| i.postln })

for(1, 10) { |i| i.postln }
```

We commonly use this notation for flow-of-control method calls, but there is no rule restricting this construction to control-flow methods. It's valid for every method, whether it makes semantic sense or not.

This allows users to define new control structures, so I would argue against changing it.

**Comment by dyfer** [comment]
Thank you for the explanation, I wasn't familiar with that syntax.
That's certainly a tricky case then for the first example... but I can see there's no way around it.
