### ISSUE TITLE
could not initialize audio error

### ISSUE THREAD

**Issue by steamedzucchini** [supercollider/supercollider#5240]
## Environment

* SuperCollider version: 3.11.1
* Operating system: Manjaro (Arch based)

## Steps to reproduce

`SuperDirt.start`

## Expected
Audio

## Actual behaviour
No Audio 

```

Booting server 'localhost' on address 127.0.0.1:57110.
Faust: supercollider.cpp: sc_api_version = 3
Faust: FaustGreyholeRaw numControls=7
Faust: supercollider.cpp: sc_api_version = 3
Faust: FaustJPverbRaw numControls=11
Found 0 LADSPA plugins
jackd 0.125.0
Copyright 2001-2009 Paul Davis, Stephane Letz, Jack O'Quinn, Torben Hohn and others.
jackd comes with ABSOLUTELY NO WARRANTY
This is free software, and you are welcome to redistribute it
under certain conditions; see the file COPYING for details

could not initialize audio.
Server 'localhost' exited with exit code 0.
```

**Comment by steamedzucchini** [comment]
Just solved installing:
supercollider, sc3-plugins, jack2, python-dbus, qjackctl and pulseaudio-jack.

**Comment by php4fan** [comment]
I had the same issue.

Then I started jack with `systemctl --user start jack@example` and now the server booted without errors, but I can't hear anything. 

Not only that, now there's no audio whatsoever even from other applications. For example, Google Chrome. The system audio icon shows up as muted and says "no output or input devices found".

As soon as I stop the Jack service, the audio for the rest of the system works again.

This feels like the 1980s. Why can't Supercollider just attach to the system audio inputs and outputs like every other program?
