### ISSUE TITLE
3.12.0 Discussions

### ISSUE THREAD

**Issue by mossheim** [supercollider/supercollider#5247]
Use this thread to discuss plans for the 3.12.0 release.

The current 3.12.0 release progress can be seen on the milestone page: https://github.com/supercollider/supercollider/milestone/23

Notable things we've already merged:
- Supernova on Windows #4763 
- bigger build matrix #4906 
- fuzzy equals #4468 
- runInTerminal fixes #4882 
- typo fix suggestions on method not found #4866  #4929 
- updated portaudio submodule #4925 
- (probably more i've missed)

There are a few things people have identified as potential todos:
1. #5110 (clip output on macOS)
2. implement RFC 10 (master->main, etc.) https://github.com/supercollider/rfcs/pull/10
3. update to C++17 #5170 
4. improve release process #4974 
5. sclang fix for midi message crash #5200
6. merge in Bela support https://github.com/BelaPlatform/supercollider/issues/73 / #2682
7. Big Sur support #5168
8. automate cherry-picking #5132 

i think we should plan to complete a couple of these and release a 3.12.0 beta before the end of the year. of the above, the ones most important to me to have for this release are the first 5.

<details>

Congrats on finding the easter egg! I'm just uploading these images so I can use them in a wiki page, please ignore!

<img width="1040" alt="Screen Shot 2020-11-22 at 11 19 47 AM" src="https://user-images.githubusercontent.com/15369640/99910682-fb7de780-2cb4-11eb-90b8-e6ef1aff4462.png">
<img width="1016" alt="Screen Shot 2020-11-22 at 11 19 00 AM" src="https://user-images.githubusercontent.com/15369640/99910684-fc167e00-2cb4-11eb-8fa7-e457bbb85fa8.png">
<img width="844" alt="Screen Shot 2020-11-22 at 11 18 34 AM" src="https://user-images.githubusercontent.com/15369640/99910685-fcaf1480-2cb4-11eb-8c4d-0723f89fd306.png">
</details>

**Comment by joshpar** [comment]
I think Big Sur support may just need us building with Big Sur and the latest Xcode. Since I'm looking for build server / services, I'll keep this in mind. Though I know Qt says it doesn't really support macOS 11, since I CAN build and run SC on macOS 11, I think that may be lower hanging fruit if we can find support for building on it. 
ARM support, though, is a different story.
Thanks @brianlheim for kicking this off.

**Comment by dyfer** [comment]
Thanks!

I'd like to suggest adding #4725 to potential todos, if that's okay.

**Comment by brianlheim** [comment]
now that i've opened #5248 , i'm going to start adding milestones tentatively to these issues, and opening tickets for the things that don't have tickets yet.

another big thing we should make sure to solve ASAP is a new CI provider.

**Comment by brianlheim** [comment]
i've also added #5188, it should be an easy one to solve

**Comment by capital-G** [comment]
Could https://github.com/supercollider/supercollider/pull/5106 be also considered for 3.12.0? Would really love to see this feature and would gladly invest some time to resolve the remaining open issues.

**Comment by brianlheim** [comment]
sure, i'll add it to the milestone!

**Comment by telephon** [comment]
Should we add #5238 ? Would make a nice interface improvement.

**Comment by brianlheim** [comment]
yeah, i agree, just added it.

**Comment by telephon** [comment]
thanks!

**Comment by brianlheim** [comment]
hey all, i need to take a break from programming for a while to avoid burnout, and i think @joshpar is also not in a great place to take on release management, so at the last meeting we agreed to postpone the release indefinitely until one of us is feeling better, or until development starts picking up again and someone else is able to do it. as for myself i will probably be back to open source in mid or late January. take care.

**Comment by alln4tural** [comment]
Thanks for all the effort you put into this project, @brianlheim. I wish you an excellent "vacation"!

**Comment by brianlheim** [comment]
if anyone is interested in serving as the release manager for 3.12.0 (which means, updating the milestone, organizing the release, and doing everything else necessary to create official release artifacts), please contact me at my personal email and i'll help you to get set up with any credentials or permissions you need. i don't want me taking a break to cause unnecessary delays.

**Comment by brianlheim** [comment]
i am slowly returning back to SC, for now only focusing strictly on 3.12.0 release items. glad to see some PRs still going through :)

**Comment by brianlheim** [comment]
as discussed on the last dev call, i've given the [3.12.0 milestone](https://github.com/supercollider/supercollider/milestone/23) a due date of May 1. this is a long way out but reflects that there are still a lot of tasks remaining. i would really appreciate other contributors focusing on these tasks if they're able, so that the release can happen on schedule. there is python work for #5132 and #4974, C++ work for #3117 and #4725, and general planning work/discussion for #5248 and #5251.

the good news is that some of these are complex, organizational tasks that, once out of the way, will free us up to make more frequent and more reliable releases.

**Comment by patrickdupuis** [comment]
Can we add #5363 to `3.12` since it reverts a change that is causing some unitt tests to fail?

**Comment by brianlheim** [comment]
yes, fine with me ^^

**Comment by brianlheim** [comment]
I've also added #5318 since it seems quite pernicious for macOS development work and is likely to come up during beta testing

**Comment by patrickdupuis** [comment]
Issue #5366 should be added to the `3.12.0` milestone instead of #5363.

**Comment by brianlheim** [comment]
done!

**Comment by brianlheim** [comment]
i've added #5382 to the milestone since it goes along with #5251 somewhat and would only take a couple minutes of work.

**Comment by brianlheim** [comment]
Note from discussion in #5396: https://github.com/supercollider/supercollider/pull/5396#issuecomment-803434947: we will ensure that the 3.12.0 release (and maybe 3.12.x as a whole) is gcc-6.3 compatible and then raise the requirements for later releases once the newer Bullseye Bela system is out.

**Comment by brianlheim** [comment]
i've opened #5410 and #5411 as some remaining issues from the Bela merge. I don't think either are showstoppers for the 3.12 release, so I haven't added them to the milestone, but #5411 might be nice to have since changing it would require an API version change, or we'd just deprecate the old header.

**Comment by dyfer** [comment]
I just wanted to put on our radar that clipping output values on macOS is currently implemented in scsynth only. IMO we should at least consider implementing it in supernova as well for 3.12.

**Comment by brianlheim** [comment]
could you make a ticket for it @dyfer ? i'm a little reluctant to add more to the milestone at this point but if someone makes a PR for it i would review it quickly

**Comment by dyfer** [comment]
Issue added: #5412

**Comment by dyfer** [comment]
I think it would be good to ship 3.12 with updated PortAudio, since they've released a version recently: #5293

**Comment by brianlheim** [comment]
the scripts i used to prepare release artifacts are here: https://gist.github.com/brianlheim/27aba00cf6ccc46690208f01f1b790b8

**Comment by dyfer** [comment]
Just wanted to let everyone know that me and @joshpar are now starting the 3.12.0-rc1 release process

**Comment by dyfer** [comment]
I'm closing this, as all major points seem to have been addressed and we are releasing 3.12.0 now.
