### ISSUE TITLE
Improve documentation in header files for plugin developers

### ISSUE THREAD

**Issue by madskjeldgaard** [supercollider/supercollider#5249]
## Motivation
To make the development experience with LSP-based tools a bit more rewarding, the header files that users make use of when writing plugins could do with a bit of a documentation update. Some of the functions have nice comments but they are inside the functions, and not above them (like at least my LSP setup expects). 

## Description of Proposed Feature

Additionally, adding a section about this to the cpp coding guidelines would be awesome https://github.com/supercollider/supercollider/wiki/Cpp-Code-Style-Guidelines

I think that this:
```cpp
/// set calc function & compute initial sample
    template <typename UnitType, void (UnitType::*PointerToMember)(int)> void set_calc_function(void) {
        mCalcFunc = make_calc_function<UnitType, PointerToMember>();
        (mCalcFunc)(this, 1);
    }
```
Is a nice example. 

On a code hover in my editor, it looks like this:
![code_hover](https://user-images.githubusercontent.com/22474608/99409460-b131ea80-28f1-11eb-8b8e-a7b089deb04a.png)

## Plan for Implementation
If others agree this would be a good idea I would suggest doing this, at least to begin with, in the header files that are directly used by plugin developers. SC_PlugIn.hpp already has pretty good comments but `SC_Rgen.h` could use some love, eg coin:
```cpp
inline float fcoin(uint32& s1, uint32& s2, uint32& s3) {
    // only return one of the two values -1.0 or +1.0
    union {
        uint32 i;
        float f;
    } u;
    u.i = 0x3F800000 | (0x80000000 & trand(s1, s2, s3));
    return u.f;
}
```
could look like this
```cpp
/// only return one of the two values -1.0 or +1.0
inline float fcoin(uint32& s1, uint32& s2, uint32& s3) {
    union {
        uint32 i;
        float f;
    } u;
    u.i = 0x3F800000 | (0x80000000 & trand(s1, s2, s3));
    return u.f;
}
```
as well as the unary and binary operators described in [the plugin api help file](http://doc.sccode.org/Reference/ServerPluginAPI.html).

**Comment by brianlheim** [comment]
yes, this would be great. do you want me to assign this issue to you?

the triple-backslash comments are also called doxygen- or javadoc-style comments because they were popularized by those tools. we don't use either tool but if editors are integrating with them in that way, it definitely doesn't hurt to standardize it for these headers. by 'standardize' i just mean make all the single line comments use `///` and block comments use

```cpp
/**
 *
 */
```

i don't mean using all the special commands doxygen has (https://www.doxygen.nl/manual/docblocks.html).

**Comment by madskjeldgaard** [comment]
> yes, this would be great. do you want me to assign this issue to you?
> 
> the triple-backslash comments are also called doxygen- or javadoc-style comments because they were popularized by those tools. we don't use either tool but if editors are integrating with them in that way, it definitely doesn't hurt to standardize it for these headers. by 'standardize' i just mean make all the single line comments use `///` and block comments use
> 
> ```c++
> /**
>  *
>  */
> ```
> 
> i don't mean using all the special commands doxygen has (https://www.doxygen.nl/manual/docblocks.html).

Yes please assign me. I can have a look at this :)
