### ISSUE TITLE
launch_test.py is broken

### ISSUE THREAD

**Issue by capital-G** [supercollider/supercollider#5256]
## Environment

* SuperCollider version: 3.11.0
* Operating system: Ubuntu 20.10
* Other details (Qt version, audio driver, etc.):

## Steps to reproduce

```shell
python launch_test.py <PATH_TO_SCLANG>
```

## Expected vs. actual behavior

Expected: The test should have the possibility to fail

Actual:

https://github.com/supercollider/supercollider/blob/7c16838b00b0af26314431246e6b68a2a0ce9cc0/testsuite/sclang/launch_test.py#L69

`proc.poll()` always returns `None` here (check [python docs why](https://docs.python.org/3/library/subprocess.html#subprocess.Popen.poll)) which results in boolean `False` in Python, so the block is never evaluated and therefore it is not checked if sclang shuts down as expected.

Also the test is Python2 only which has been deprecated since 2020-01-01.

The only reference I could find was https://github.com/supercollider/supercollider/blob/f65a1ef7bfb100f4ccb7dcab3a6dff6826be4344/.travis/test.sh#L9
where the test is commented out.

I actually do not care about the test but it led me to a wrong direction on a project where I work with the REPL (see https://github.com/capital-G/sc_kernel/issues/7 ).
If a test is broken and not used, should it be considered for deletion?

If someone has a good way to insert/poll the REPL I would be really interested in this.
Also if a Python3 port of this is needed I can help - or if the test should be deleted.

**Comment by brianlheim** [comment]
this file can be removed; it is not very different from qpm (https://github.com/supercollider/qpm), which we do actually use in our CI testing. would you mind submitting a PR?

**Comment by sbl** [comment]
Probably off topic: 

> this file can be removed; it is not very different from qpm (https://github.com/supercollider/qpm), which we do actually use in our CI testing.

Is `qpm` the "official" test runner for sclang? And as such is it intended to keep it around for longer? If so the [python3](https://github.com/supercollider/qpm/issues/4) upgrade becomes likely more relevant. I can take a look if this effort would be worthwhile.

> Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021.

**Comment by brianlheim** [comment]
@sbl yes, we want to keep qpm around and porting it to python 3 is an important task!
