### ISSUE TITLE
Help Browser is without content in Documents, Classes, Methods (indexing problem?)

### ISSUE THREAD

**Issue by tabache** [supercollider/supercollider#5258]
## Environment

* SuperCollider version: 3.10.0
* Operating system: Ubuntu 20.04.1 LTS (**lubuntu** distribution)

## Steps to reproduce
just lunch the software

## Description
Hello, I've just installed Supercollider on my lubuntu, but the Help Browser is almost empty. The only content inside are about entries "Getting Started tutorial series", Glossary, "Client vs Server", "more on getting help", "Class Tree" (in this entry I can also click on each single class!).
Instead I can't find nothing in [Search](https://i.postimg.cc/J4NyDxNy/3.jpg), Browse, All Documents, Documents, [Classes](https://i.postimg.cc/Y0j4mBxM/2.jpg), [Methods](https://i.postimg.cc/sXTQXg7T/1.jpg) (in methods it remain on "Generating method index, please wait...").

It  seems to me that is a indexing problem, like the engine is not responding.

I saw that there are many other issues about Help Browser, but it seems to me that this report does not exist.

## start-up messages
_here my start-up messages, if it could help:_
compiling class library...
	Found 845 primitives.
	Compiling directory '/usr/share/SuperCollider/SCClassLibrary'
	Compiling directory '/usr/share/SuperCollider/Extensions'
	Compiling directory '/home/tabache/.local/share/SuperCollider/Extensions'
	numentries = 819910 / 12168006 = 0.067
	5437 method selectors, 2238 classes
	method table size 13245656 bytes, big table size 97344048
	Number of Symbols 12276
	Byte Code Size 368207
	compiled 318 files in 0.89 seconds

Info: 4 methods are currently overwritten by extensions. To see which, execute:
MethodOverride.printAll

compile done
localhost : setting clientID to 0.
internal : setting clientID to 0.
Couldn't set realtime scheduling priority 1: Operation not permitted
Class tree inited in 0.01 seconds

*** Welcome to SuperCollider 3.10.0. *** For help press Ctrl-D.
Couldn't set realtime scheduling priority 1: Operation not permitted
SCDoc: Indexing help-files...
SCDoc: Indexed 1349 documents in 7.98 seconds

**Comment by brianlheim** [comment]
hey @tabache thanks for the report! i would recommend using the [sc-users mailing list and/or the discourse forum (scsynth.org)](https://github.com/supercollider/supercollider#discuss) for help with installation and usage issues. you'll get a reply much faster, and those conversations are more appropriate there.
