### ISSUE TITLE
Linux environment variables not working (being overwritten by default)

### ISSUE THREAD

**Issue by madskjeldgaard** [supercollider/supercollider#5260]
The Linux readme (https://github.com/supercollider/supercollider/blob/develop/README_LINUX.md#environment) mentions the use of environment variables `SC_JACK_DEFAULT_INPUTS` and `SC_JACK_DEFAULT_OUTPUTS` as ways to decide which jack client to connect to on startup. This is a cool feature but for some reason these environment variables are just overwritten in the startup method for the linux platform class and thus do not work:

https://github.com/supercollider/supercollider/blob/7b958f7116ef50389930e280e46ce5ca10ddd97a/SCClassLibrary/Platform/linux/LinuxPlatform.sc#L22

My expectation would be that SC would check to see if these environment variables are nil and then if they are set the default to `system`. 

this can be easily done using the `.getenv` method.

**Comment by madskjeldgaard** [comment]
I can do a PR for this

**Comment by brianlheim** [comment]
@madskjeldgaard sure! that would be very helpful
