### ISSUE TITLE
"Disabling" a ugen

### ISSUE THREAD

**Issue by giuliomoro** [supercollider/supercollider#5264]
Hi there,
on Bela we have some custom Ugens for reading and writing the digital and analog I/Os. The user may be specifying some out of range values (e.g.: reading channel 7 when only 4 channels are available). At the moment we only print a warning on the server console and call `SETCALC(ClearUnitOutputs);`.
Is there a better way of doing this? E.g.: can the Ugen be completely removed from the processing graph?

I see things like `Unit_DoneAction` or `Unit_EndCalc` or `Unit::mDone`, but it seems like the former is never called and the latter is never checked ...

**Comment by jamshark70** [comment]
> can the Ugen be completely removed from the processing graph?

No. The server can never change the structure of a synthesis graph.

**Comment by giuliomoro** [comment]
OK, so do you recommend `SETCALC(ClearUnitOutputs);` for this use case?

Also , tangentially, what is the use case for `Unit::mDone` and `Unit_DoneAction` ?

**Comment by jamshark70** [comment]
I'd also consider this use case:

```
x = Synth(\pin, [pin: 27]);

// user: "oh, that wasn't right"
x.set(\pin, 2);
```

If the calc function is simply clear-outputs, then nothing will be there to check for new input values. So the only way for the user to recover is to free the synth and recreate. So, if it were my UGen, I think I would set the calculation function as normal, and handle bad values at the top of that function.

> Also , tangentially, what is the use case for Unit::mDone and Unit_DoneAction ?

For example, an EnvGen or Line or PlayBuf can release the *entire* synth node.

There's never been any provision for a UGen to delete itself while keeping the rest of the synth node.

**Comment by giuliomoro** [comment]
Good point. I guess we have a combination of the two cases: creating a `DigitalIn` ugen when there are no digital input channels available on the server will result in `SETCALC(ClearUnitOutputs);`. If there are channels available but the selected channel is wrong, then that will be handled in the callback.

Thanks!
