### ISSUE TITLE
adding a server message n_queryTree that generalizes g_queryTree

### ISSUE THREAD

**Issue by olafklingt** [supercollider/supercollider#5272]
## Motivation

I make use g_queryTree to receive information about the current state of groups and synths on the server. But sometimes I only need information about the current state of a synth. Including synth name and parameter values.

## Description of Proposed Feature

Add a n_queryTree message to the server and related methods to the node class.

for the a default synth at node id 1000
s.sendMsg("/n_queryTree", 1000,1) would return:

```
[ /n_queryTree.reply, 1, 1000, -1, default, 5, out, 0.0, freq, 440.0, amp, 0.10000000149012, pan, 0.0, gate, 1.0 ]
```

and s.sendMsg("/n_queryTree", 1000,0) would return:

```
[ /n_queryTree.reply, 0, 1000, -1, default ]
```

## Plan for Implementation

I implemented it in SuperNova. It seems my formatting is a bit off, but please have a look here:
https://github.com/supercollider/supercollider/compare/develop...olafklingt:develop

If such a feature is welcome, I am happy to implement it in scsynth too.

In g_queryTree the requested node is treated specially. In the reply message, the third int is the count of child nodes. And it is always positive. Whereas in child nodes, a negative count of children is used to indicate that a node is a synth.

```c++
osc::OutboundPacketStream p(data.c_array(), max_msg_size);	 
 p << osc::BeginMessage("/g_queryTree.reply") << (flag ? 1 : 0) << node_id	 
 << osc::int32(group->child_count());	 
 group->apply_on_children([&](server_node const& node) { g_query_tree_fill_node(p, flag, node); });	 
 p << osc::EndMessage;
```

In n_queryTree, one would simply treat all nodes like child nodes in the current implementation. This makes the implementation (at least in SuperNova) trivial.

```c++
 osc::OutboundPacketStream p(data.c_array(), max_msg_size);	 
  p << osc::BeginMessage("/n_queryTree.reply") << (flag ? 1 : 0);	 
  g_query_tree_fill_node(p, flag, *node);	 
 p << osc::EndMessage;
```

**Comment by muellmusik** [comment]
Sorry, I'm not sure I understand the intention here? Do you just want the control info for a single synth in an OSC message? Would it make more sense to add a flag for this to n_query? This would be consistent with g_queryTree.

**Comment by josiah-wolf-oberholtzer** [comment]
See https://github.com/supercollider/rfcs/pull/5
