### ISSUE TITLE
Some demand-rate units don't work?

### ISSUE THREAD

**Issue by jamshark70** [supercollider/supercollider#5276]
## Environment

* SuperCollider version: 3.11.2
* Operating system: any

## Steps to reproduce

With sc3-plugins:

```supercollider
(
SynthDef(\neuron,{
	arg out = 0;
	var dt, module;
	dt = 0.01;
	module = Dneuromodule.kr(dt,2,
		theta: [MouseX.kr(-2, 2), MouseY.kr(-2, 2)],
		x: [0.1, 0.3],
		weights: [-3, 2, -2, 0]);
	Out.ar(out,SinOsc.ar(module * 400 + 600) * 0.1)
}).add;
)
```

## Expected vs. actual behavior

Actual: `^^ The preceding error dump is for ERROR: rate must be Symbol.`

https://github.com/supercollider/supercollider/blob/develop/SCClassLibrary/Common/Audio/SynthDesc.sc#L349

```
rate = #[\scalar,\control,\audio][rateIndex];
```

Here, we are assuming rateIndex is 0, 1 or 2. But in this stack trace, rateIndex == 3.

But I can't reproduce it with Dwhite...? I'm puzzled.

If I change that line to `rate = #[\scalar,\control,\audio,\demand][rateIndex];` then the error goes away.

**Comment by telephon** [comment]
In `UGen`, the `rateIndex` of 3 is defined: https://github.com/supercollider/supercollider/blob/2b228184ce5da90c73384ac83ca340ac86537068/SCClassLibrary/Common/Audio/UGen.sc#L455

That has existed since very long before the `Dneuromodule` UGen. Maybe it was never used?
Or I did something that was not intended originally.

**Comment by jamshark70** [comment]
Closing this one. The problem is `initOutputs` in MultiOutDemandUGen from sc3-plugins.

**Comment by jamshark70** [comment]
Hmm... on second thought, I think the fix is really here.

Adding some debug posts, I get:

```
e = SynthDef(\dwhite, { |out, gate = 1|
	var duty = Duty.kr(1, 0, Dwhite(0, 1, inf));
	Out.kr(out, duty);
});

e.add;

-->

-> SynthDef:dwhite
dwhite: [ 3, 3, 1 ]
newFromDesc: [ class Dwhite, nil ]
newFromDesc: [ class Duty, control ]
newFromDesc: [ class Out, control ]
```

`newFromDesc` is posting the UGen class retrieved from the graphdef binary stream and a rate that is passed in.

We have always been passing a `nil` rate to demand UGens! ... which... it has happened not to throw errors until now, but clearly that's not a good idea.

I think it's not an issue for Dwhite because, as a single-output UGen, it doesn't have to `initOutputs` so it never hit a place where the rate was needed.

Extending the concept of a demand unit to a MultiOutDemandUGen exposed the flaw in SynthDesc:readUGenSpec(2).

So I have to change my mind about closing this issue. MultiOutDemandUGen makes a reasonable assumption that a valid rate will be passed in -- the root of the problem is that SynthDesc doesn't do that. So, fix it at the root.
