### ISSUE TITLE
Improve macOS installation instructions clearer to avoid translocation

### ISSUE THREAD

**Issue by brianlheim** [supercollider/supercollider#5278]
## Environment

* SuperCollider version: i believe this affects all recent versions
* Operating system: macOS
* Other details (Qt version, audio driver, etc.): N/A

## Description

i've noticed that a lot of people are noticing and/or complaining about [app translocation](https://lapcatsoftware.com/articles/app-translocation.html) on macOS. it's easy to see why this happens -- the official release .zip decompresses into a folder containing the .app and a set of examples, so many people assume the right thing to do is drag the entire folder into `/Applications`. however, this doesn't remove the quarantine attribute, because the .app itself was not dragged into the folder. as far as i can tell, the .app itself must be moved into `/Applications` to remove the quarantine attribute. the other way i know of to remove this attribute is to use the `xattr` command line tool which we should of course not require people to do themselves.

we should make things easier for people by communicating the correct installation steps. i'm not sure what the best thing would be, mainly just wanted to log this issue so we can be sure to address it for 3.12.0. some ideas off the top of my head are (1) better documentation, (2) releasing an installer (.dmg or something else), (3) only releasing a zipped .app.

**Comment by dyfer** [comment]
A common way to do this is to create a .dmg image (without making an installer) and providing shortcut to `/Applications` in the .dmg, possibly with a background image that hints the user to drag the app to `/Applications`. I've seen this on multiple occasions. Example:
![Screen Shot 2020-12-09 at 9 20 33 PM](https://user-images.githubusercontent.com/1589177/101724967-907a3200-3a64-11eb-962a-2e4ce82a1702.png)
