### ISSUE TITLE
SuperNova fails to boot when Server options outDevice is null 

### ISSUE THREAD

**Issue by zacksettel** [supercollider/supercollider#5279]
## Environment

* SuperCollider version: 3.10.4 and 3.11.2
* Operating system: MacOS 10.14.6 (Mojave) freshly installed. 

* Other details (Qt version, audio driver, etc.):
Mac Pro (2013) with no audio hardware (no mic) - note that the only audio device on the machine is the "built-in audio".

## Steps to reproduce

```supercollider
Paste code here. Use a minimal example please.
```

To demonstrate the issue:
s = Server.supernova.local;
s.boot;

## Expected vs. actual behavior

EXPECTED:  
supernova boots

ACTUAL:
supernova fails and displays the following:

Booting server 'localhost' on address 127.0.0.1:57110.
Supernova booting
Available Audio Devices:
0: Built-in Output (0 inputs, 2 outputs)

Found 0 LADSPA plugins
Server 'localhost' exited with exit code 0.

WORKAROUND 1

s = Server.supernova.local;
// EXPLICIT SETTING OF OUT DEVICE
s.options.outDevice= "Built-in Output";
s.boot;

WORKAROUND 2
add an additional audio device to the system (e.g. LoopBack, Soundflower etc..) and the issue does not manifest.

**Comment by dyfer** [comment]
thanks for the report @zacksettel 
Does disabling input (`s.options.numInputBusChannels = 0`) also solve this?

**Comment by zacksettel** [comment]
So far neither 
s.options.outDevice= "Built-in Output";
nor
s.options.numInputBusChannels = 0

prevent 

Server 'localhost' exited with exit code 0.


NO LUCK EITHER when trying:

s = Server.supernova.local;
// EXPLICIT SETTING OF OUT DEVICE
s.options.outDevice= "Display Audio";
s.options.numInputBusChannels = 0
s.boot;


THE CONSOLE DISPLAYS:

-> a ServerOptions
-> localhost
Booting server 'localhost' on address 127.0.0.1:57110.
Supernova booting
Available Audio Devices:
0: LED Cinema Display (0 inputs, 2 outputs)
1: LED Cinema Display (0 inputs, 2 outputs)
2: Display Audio (1 inputs, 2 outputs)
3: M4 (4 inputs, 4 outputs)
4: iMac Pro Microphone (1 inputs, 0 outputs)
5: iMac Pro Speakers (0 inputs, 2 outputs)
6: VLC-MIC_2_Hubs (4 inputs, 0 outputs)
7: Chrome (2 inputs, 2 outputs)
8: ZoomAudioDevice (2 inputs, 2 outputs)

Found 0 LADSPA plugins
opening portaudio device name: nil / Display Audio
opening portaudio device name:  / Display Audio
||PaMacCore (AUHAL)|| Error on line 1316: err='-66748', msg=Unknown Error
||PaMacCore (AUHAL)|| OpenStream @ 44100 returned: -9986: Internal PortAudio error
could not open portaudio device name:  / Display Audio
PortAudio error: Internal PortAudio error
Server 'localhost' exited with exit code 0.

**Comment by dyfer** [comment]
I should've asked before... could you try the "develop" build of SC and check how that behaves? PortAudio backend in supernova was updated after 3.11.2.

**Comment by zacksettel** [comment]
Sounds great.  Do you mean that there is a build of the app in the develop branch?  

Where would that be?


cheers

Zack

**Comment by dyfer** [comment]
> Sounds great. Do you mean that there is a build of the app in the develop branch? Where would that be? cheers Zack

https://supercollider.github.io/download
see **Bleeding Edge** / **Latest build** under **Previous releases**

**Comment by zacksettel** [comment]
Using the build in Bleeding Edge / Latest build under Previous releases

Supernova boots successfully:

s = Server.supernova.local;
s.boot;


thanks!

Zack

**Comment by zacksettel** [comment]
Using the Bleeding Edge / Latest build under Previous releases,

s = Server.supernova.local;
s.boot;

will boot without error

thanks!

**Comment by dyfer** [comment]
Great! Closing now, as this fix will be included in the upcoming 3.12 release.
