### ISSUE TITLE
Remove old news from the Writing Help help file

### ISSUE THREAD

**Issue by madskjeldgaard** [supercollider/supercollider#5290]
The Writing Help help file has a bunch of outdated information about the scdoc parser changes introduced in 3.5 at the top of it's document ("writing new help" and "converting old help files"). This is a confusing thing to deal with when met with this help file while trying to learn how to write help files and I think both of those two sections should be removed. The rest of the help file seems really nice.

http://doc.sccode.org/Guides/WritingHelp.html

**Comment by dyfer** [comment]
fixed in #5633
