### ISSUE TITLE
Bug with Ndef <<> and BusPlug \elastic reshaping

### ISSUE THREAD

**Issue by geoffroymontel** [supercollider/supercollider#5303]
## Environment

* SuperCollider version: 3.11.2
* Operating system: Mac OS 10.14.6,
* Other details (Qt version, audio driver, etc.):

## Steps to reproduce

```supercollider
BusPlug.defaultReshaping = \elastic;

(
Ndef(\sound, {
	(\in1.ar([0,0]) * \in2.ar([0,0])).tanh
}).play;
)

Ndef(\a, { SinOsc.ar(MouseX.kr(300, 1000, 1) * [1, 1.2]) });
Ndef(\b, { LFNoise2.ar(MouseY.kr(3, 1000, 1) * [1, 1.2]) });

Ndef(\sound) <<>.in1 Ndef(\a);

// after the following line, there's some sound
Ndef(\sound) <<>.in2 Ndef(\b);

// evaluate the following line -> silence
Ndef(\sound) <<>.in1 Ndef(\a);
```

## Expected vs. actual behavior

The last line should not stop the sound.
@scztt analyzed the problem on [scsynth.org](https://scsynth.org/t/bug-with-ndef-operator/3032/3)

**Comment by telephon** [comment]
The issue is related a wrongly assigned control default value (reasons are a little complicated). So the first thing to fix is this:

```supercollider

Ndef(\test, { \in.ar(7) });
Ndef(\controlTest, { DC.ar(1) });
Ndef(\test).xmap(\in, Ndef(\controlTest));
Ndef(\test).controlNames.detect { |x| x.name == \in }.defaultValue // is Ndef('controlTest'), should be 7

```

**Comment by telephon** [comment]
Actually, the above is correct, only the operator `<<>` should use `.controlNames(addNodeMap: false)`.


```supercollider

Ndef(\test, { \in.ar(7) });
Ndef(\controlTest, { DC.ar(1) });
Ndef(\test).xmap(\in, Ndef(\controlTest));
Ndef(\test).controlNames(addNodeMap: false).detect { |x| x.name == \in }.defaultValue // is Ndef('controlTest'), should be 7
```

Omitting `addNodeMap: false` returns the controls from the node map, which have the node proxies as a default value, which in turn return number of channels 1, instead of 2. This leads to a wrong control `numChannels` and therefore to a silent bus.

Sorry for the rough explanation, but I'll write up the fix first.

**Comment by telephon** [comment]
@geoffroymontel thanks for reporting – can you test the fix? That would be great!

**Comment by geoffroymontel** [comment]
Hi @telephon ! Thanks for the super quick fix ! I can't test it until Thursday, because I'm not home and don't have any compiler installed here. But I will and keep you posted. Thanks again !
