### ISSUE TITLE
fatal: reference is not a tree (portaudio submodule)

### ISSUE THREAD

**Issue by telephon** [supercollider/supercollider#5306]
## Environment

* SuperCollider version: 6b046b23e80b7c4bd52dfc289cb4e92f573a423c
* Operating system: macOS 10.15.7 (19H114)

see also: #5288

## Steps to reproduce

In the shell, delete the external_libraries folder
```
$ rm -r external_libraries/
$ git submodule update --init --recursive
```
This fails in one submodule:
```
Submodule path 'external_libraries/hidapi': checked out 'd1c0c5ff25c53850fcea0dbb4c8f9848dfd5cebc'
Submodule path 'external_libraries/link': checked out 'c1449edb28ccba86396a46a9989b8795960160a9'
Submodule path 'external_libraries/link/modules/asio-standalone': checked out '722f7e2be05a51c69644662ec514d6149b2b7ef8'
Submodule path 'external_libraries/nova-simd': checked out '2bdc68bc5704a42578300a4c18411df2405cb307'
Submodule path 'external_libraries/nova-tt': checked out '55da93741e76632579b63004d3378139e32d634f'
fatal: reference is not a tree: a63ed32b997abb2f7791bd8931d5a866e0f9c16e
Submodule path 'external_libraries/yaml-cpp': checked out '728e26e42645d4d70ca65522990f915f47b47a50'
Unable to checkout 'a63ed32b997abb2f7791bd8931d5a866e0f9c16e' in submodule path 'external_libraries/portaudio/portaudio_submodule'
```

## Expected vs. actual behavior

It should recover all necessary modules.

```
$ git reset --hard
```

restores it almost, but leaves a dirty subproject commit:

```
+Subproject commit 8f5ce9ddd60d9fb5f1d52e4e3a4c91e258b2b44b-dirty
```

**Comment by dyfer** [comment]
If I run:
```
git clone --recursive https://github.com/supercollider/supercollider.git
cd supercollider/
rm -r external_libraries/
git submodule update --init --recursive
git reset --hard
```
I end up with
```
$ git status
On branch develop
Your branch is up to date with 'origin/develop'.

nothing to commit, working tree clean
```
I'd try to remove the submodule with local changes (the one with dirty commit), update submodules and maybe reset as well. And definitely pull upstream changes: 
```
git checkout develop
git fetch upstream
git pull upstream develop
```
assuming that `upstream` is the main sc repository.

**Comment by telephon** [comment]
In my (not fresh) repository, I get (after both series of lines):

```
$ git status
On branch develop
Your branch is up-to-date with 'origin/develop'.
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)
  (commit or discard the untracked or modified content in submodules)

	modified:   external_libraries/portaudio/portaudio_submodule (new commits, modified content)
```

I'd like to avoid starting from scratch and try keep my local git repository, if I can.

**Comment by dyfer** [comment]
If you go to `external_libraries/portaudio/portaudio_submodule`, what's the git status there? Do you have changes in that repository? Can you reset that repository to origin remote? Does it have its remote pointing to `https://github.com/PortAudio/portaudio.git`? 
After resetting it manually to remote's HEAD, it will be on the "wrong" commit, but in a clean state; maybe afterwards resetting submodules in `supercollider` would bring it back to the proper commit...

**Comment by telephon** [comment]
Indeed, the problem is there somehow.
The remote inside the submodule is a different one:
```
$ git remote -v
origin	https://github.com/bagong/portaudio (fetch)
origin	https://github.com/bagong/portaudio (push)
```

I have removed it and replaced it by the URL that you suggested:
```
$ git remote remove origin
$ git remote add origin https://github.com/PortAudio/portaudio.git
```

Then I've set the tracking information as suggested by git:
```
$ git branch --set-upstream-to=origin/master master
$ git reset --hard

Your branch and 'origin/master' have diverged,
and have 585 and 672 different commits each, respectively.
  (use "git pull" to merge the remote branch into yours)
```

I don't understand how the result of `git reset --hard` can still have a divergence ...

**Comment by dyfer** [comment]
You're welcome!

> I don't understand how the result of git reset --hard can still have a divergence ...

IIUC, if the submodule's remote does not have the commit set in the main supercollider repo (i.e. the submodule's commit `git reset --hard` would revert to), then there's no way to checkout that commit. 

It would be nice if git was able to indicate what the problem is...

Should we close this issue then?

**Comment by telephon** [comment]
yes :)
