### ISSUE TITLE
MainMenu doesn't work unless you call initBuiltInMenus first

### ISSUE THREAD

**Issue by muellmusik** [supercollider/supercollider#5313]
## Environment

* SuperCollider version: 3.11.0
* Operating system: MacOS 10.14.6 
* Other details (Qt version, audio driver, etc.):

## Steps to reproduce

```supercollider
// run this first example
(
~testTone = MenuAction("Test Tone", {
    { SinOsc.ar(400) * 0.1 }.play;
});

MainMenu.register(~testTone, "Tests");
)
```

## Expected vs. actual behavior

Throws the error below. My guess is this goes back to 423a54e35f38ca22dea4cfd2a6b7b2f69e78a175

Seems easily fixed by adding these lines to initClass:
```
systemMenus = [\SuperCollider, \File, \Edit, \Server, \Quarks, \Help];
registered = List();
```
I can do a PR but just wanted to confirm that we need need File, Edit, etc, here, as they're not referred to elsewhere in the file.

ERROR: Message 'detectIndex' not understood.
RECEIVER:
   nil
ARGS:
Instance of Function {    (0x126ca68c8, gc=14, fmt=00, flg=00, set=02)
  instance variables [2]
    def : instance of FunctionDef in Method Meta_MainMenu:prGetMenu
    context : Frame (0x127514cc8) of Meta_MainMenu:prGetMenu
}
PATH: /private/var/folders/0b/jsry71ph8xj9wc006s6btl_80000gp/T/AppTranslocation/46922546-F1EF-4EA3-963F-C780DD0AC42C/d/SuperCollider.app/Contents/Resources/SCClassLibrary/Common/GUI/Base/Menu.sc
CALL STACK:
	DoesNotUnderstandError:reportError
		arg this = <instance of DoesNotUnderstandError>
	Nil:handleError
		arg this = nil
		arg error = <instance of DoesNotUnderstandError>
	Thread:handleError
		arg this = <instance of Thread>
		arg error = <instance of DoesNotUnderstandError>
	Object:throw
		arg this = <instance of DoesNotUnderstandError>
	Object:doesNotUnderstand
		arg this = nil
		arg selector = 'detectIndex'
		arg args = [*1]
	Meta_MainMenu:prGetMenu
		arg this = <instance of Meta_MainMenu>
		arg name = 'Tests'
		var menu = <instance of List>
		var insertIndex = nil
	Meta_MainMenu:prGetMenuGroup
		arg this = <instance of Meta_MainMenu>
		arg menuName = 'Tests'
		arg groupName = 'none'
		var menu = nil
		var group = nil
	Meta_MainMenu:register
		arg this = <instance of Meta_MainMenu>
		arg action = <instance of MenuAction>
		arg menu = 'Tests'
		arg group = 'none'
		var menuList = nil
		var existingIndex = nil
	Interpreter:interpretPrintCmdLine
		arg this = <instance of Interpreter>
		var res = nil
		var func = <instance of Function>
		var code = "(
~testTone = MenuAction("Te..."
		var doc = nil
		var ideClass = <instance of Meta_ScIDE>
	Process:interpretPrintCmdLine
		arg this = <instance of Main>
^^ The preceding error dump is for ERROR: Message 'detectIndex' not understood.
RECEIVER: nil

**Comment by dyfer** [comment]
I think this is a duplicate of #4568. I'd suggest following up there. Not sure if the problems in MainMenu mentioned in the linked issue still apply, although I don't remember seeing any related PRs in the last year or so...

**Comment by telephon** [comment]
by coincidence, just yesterday I ran into this problem, too.

**Comment by muellmusik** [comment]
@dyfer Okay will bring up there.
