### ISSUE TITLE
Dropouts in Record Wav-File, but not in played sound

### ISSUE THREAD

**Issue by Gloria-Ignazia** [supercollider/supercollider#5321]
## Environment

* SuperCollider version: 3.11.1
* Operating system: Mac OS 10.14.6
* Other details (Qt version, audio driver, etc.): VSTPluginController, \binauralDecoder, \ambiFX, \stereoEncoder

## Steps to reproduce

```supercollider
(
s.quit;
s.recHeaderFormat = "WAV";
s.recorder.recHeaderFormat = "WAV";
s.freeAll;
s.options.memSize_(2.pow(20));
Server.default.waitForBoot({
	s.prepareForRecord;
	s.sync;
	s.record;
	 ...

```

## Expected vs. actual behavior
Expected: The sound that I hear via .play is also recorded.
Actual behavior: I hear a perfect audio signal while recording (via .play) but the recorded file includes dropouts. The dropouts are always at the same position at the same channel, while the second channel shows no dropout. No error message.
The audio is very intense, I do have a lot of nodes and synths. Also I'm using ambisonics VST plugins. I'ld understand if I heard the dropouts also when just playing the composition, but they are only in the recorded wav file, and there only in one channel (I'm recording a stereo file for binaural listening.) The dropouts also occur when I'm recording ambisonics 16 channels. Does anybody have an idea what this can be? I could do a workaround and record the sound I'm listening to via soundflower but I'ld love to have a more elegant solution. Thank you a lot!

**Comment by joshpar** [comment]
What bit depth are you using? If 16-bit, it could be that something plays fine over speakers but is out of range of what that file format can record. Try writing the file out as ‘float’ to see if that helps.

/*
Josh Parmenter
www.realizedsound.net/josh
*/

**Comment by brianlheim** [comment]
closing due to lack of response from reporter
