### ISSUE TITLE
Quarks aren't showing up / downloading

### ISSUE THREAD

**Issue by nathanielvirgo** [supercollider/supercollider#5334]
I am unable to load any quarks - see details below.

## Environment

* SuperCollider version:

SuperCollider 3.11.2
Built from branch 'HEAD' [9a34118e]

* Operating system:

MacOS Catalina 10.15.7

* Other details (Qt version, audio driver, etc.):

git is installed at `/usr/bin/git`, and running `git --version` shows `git version 2.24.3 (Apple Git-128)`. I didn't do anything special to install this, so I guess it came with the OS.

## Steps to reproduce

1. Run Quarks.gui

At this point I see a window with a big white space for the list of quarks, but no quarks in it.

2. Click "check for updates" in the gui

## Expected vs. actual behavior

Expected behaviour: the list becomes populated with quarks and I can install them.

Actual behaviour: the following is printed to the post window when I click "check for updates"

```
ERROR: Failed to read quarks directory listing: https://github.com/supercollider-quarks/quarks.git
ERROR: Primitive '_FileReadLine' failed.
Failed.
```

The gui keeps running and shows the message "Directory has been updated" in green, but no quarks appear in the list - it's still just a big white screen.

Note that the above is the complete error message. There is no stack trace or any other indication of which code is producing the error. I am happy to put some debugging in, but will need some instruction on what to try.

I thought maybe it's not able to run the git command, but `Git.checkForGit` returns `true`, and `Git(".").git` prints the same output as running `git` with no arguments on the command line (i.e. prints the usage instructions), so at least that side of things seems to be working.

## Other information

* I've recently updated the OS, and recently installed SuperCollider after not using it for a few years. I have made a new account on this machine, so we can be fairly sure there are no old configuration files messing things up, unless they're stored somewhere other than my home folder.

* This is the same error message as issue #1585, but that's from 2015 and it seems like it was closed because it was fixed, so I'm assuming the cause here is different.

**Comment by dyfer** [comment]
Does running `"git --version".unixCmd` in SC output the version number correctly? And what does `"which git".unixCmd` output?
I've seen issues with some PATH variables differing between SC and regular shell, but if you have git in `/usr/bin` that might not be the issue...

**Comment by nathanielvirgo** [comment]
Hi! `which git` gives me

```
/usr/bin/git
```

and `"git --version".unixCmd` gives me

```
git version 2.24.3 (Apple Git-128)
```

These are the same outputs I get from running the same commands in the shell.

**Comment by dyfer** [comment]
Hi! 
This all looks good with `git`, so the problem must be elsewhere. Unfortunately I don't have more ideas... one shot in the dark would be to check if SC is not being blocked from using some resources in Security -> Privacy, however I just checked and I can install quarks with no special permissions granted to SC...

**Comment by bryn19** [comment]
Having this same issue!
Also Catalina 10.15.7, git version 2.30.1. when I run "git --version".unixCmd I only get the process ID number returned, no output.

**Comment by dyfer** [comment]
Hi @bryn19 
if you are not getting output from `"git --version".unixCmd` then your issue is most likely with SC not finding your git.
In terminal check where git is located: `which git`, and then add that path in SC to the $PATH environment variable, see https://doc.sccode.org/Classes/String.html#-setenv

**Comment by bryn19** [comment]
Hi @dyfer, thanks for the reply! Unfortunately the bug is persisting. The output of "$PATH".getenv.postln; is  /usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin/git, but "git --version".unixCmd still has no output. "which git".unixCmd displays "/usr/bin/git", but through terminal "which git" outputs /usr/local/bin/git.

**Comment by bryn19** [comment]
nvm, changed order of folders in the $PATH variable. seems to be working now!

**Comment by nathanielvirgo** [comment]
Hi, just an update on my version of this issue: I installed SuperCollider on a brand new machine and quarks works fine.

This is with the same version of git ("2.24.3 (Apple Git-128)"), which is installed automatically the first time you try to run git from the command line. So I guess there is some other configuration file on the other machine that stops it from working. I'll be using this new machine for music from now on, so it's not a big issue for me.

**Comment by nathanielvirgo** [comment]
@bryn19 I noticed that your $PATH contains "/usr/local/bin/git", which is odd because presumably that's a file rather than a folder - maybe your problem is/was related to that?

**Comment by gotascii** [comment]
Hi all, Just wanted to chime in, I am having this same issue on macOS 12.2.1 on my M1 mac. I've never installed SC before, so fresh install on this machine. I installed SC and when I tried to install SuperDirt via:

`Quarks.checkForUpdates({Quarks.install("SuperDirt", "v1.7.2"); thisProcess.recompile()})`

I got:
```
-> Quarks
Fetching https://github.com/supercollider-quarks/quarks.git
ERROR: Failed to read quarks directory listing: https://github.com/supercollider-quarks/quarks.git
ERROR: Primitive '_FileReadLine' failed.
Failed.
ERROR: Quark 'SuperDirt' not found
```

`"git --version".unixCmd` returns:
```
-> 78895
git version 2.32.0 (Apple Git-132)
```

`"which git".unixCmd` returns:
```
-> 78940
/usr/bin/git
```

Curiously, `"$PATH".getenv.postln` returns:
```
nil
-> nil
```

I am _very_ new to SC, so I'll keep digging, but any suggestions would be appreciated, thanks!

**Comment by dyfer** [comment]
I assume this has been solved. Please reopen in case the issue persist.
