### ISSUE TITLE
BinaryOpUGen's pow implementation returns negative values

### ISSUE THREAD

**Issue by rgkeith3** [supercollider/supercollider#5339]
## Environment

* SuperCollider version: 3.11.0
* Operating system: Mac Mojave 10.14.6
* Other details (Qt version, audio driver, etc.):

## Steps to reproduce

```supercollider
-10.pow(2);

({
K2A.ar(-10).pow(2).poll;
}.play)

```

## Expected vs. actual behavior

compare the output of the two operations above. the BinaryOpUGen pow operation is returning -100. this is mathematically incorrect and inconsistent with the sclang operation.

**Comment by brianlheim** [comment]
this is intended and documented behavior: https://doc.sccode.org/Overviews/Operators.html#.pow
