### ISSUE TITLE
TreeView problem

### ISSUE THREAD

**Issue by paum3** [supercollider/supercollider#5343]
Hi, I am using ```TreeView``` class as my project object inspectorish thing.  When I try to clear more items from ```TreeView``` it deletes some and then throws an  **ERROR: Primitive '_QObject_InvokeMethod' failed.**  In my attached expamle  I am clearing all the table - this is just example and I know that there is a method ```clear``` to erease all items from ```TreeView```, which works out of a box.
`

## Environment

* SuperCollider version: 3.11.2
* Operating system: Arch Linux
* Other details (Qt version, audio driver, etc.):

## Steps to reproduce

```supercollider
(
~t = TreeView().front;
~t.columns_(["a", "b", "c", "d"]);
20.do({
	~t.addItem([30.rand, 30.rand, 30.rand, 30.rand]);
})
)

~t.numItems.do({ |i| ~t.removeItem( ~t.itemAt(i) ) }) // deletes a few and thorws an error..
```

## Expected vs. actual behavior

ERROR: Primitive '_QObject_InvokeMethod' failed.
Failed.
RECEIVER:
Instance of TreeView {    (0x55df814d7578, gc=48, fmt=00, flg=00, set=06)
  instance variables [36]
    qObject : RawPointer 0x7f5ba800b8e0
    finalizer : instance of Finalizer (0x55df814ff5e8, size=2, set=1)
    virtualSlots : nil
    wasRemoved : false
    font : nil
    resize : Integer 1
    alpha : Float 1.000000   00000000 3FF00000
    decorator : nil
    layout : nil
    userCanClose : true
    deleteOnClose : true
    action : nil
    mouseDownAction : nil
    mouseUpAction : nil
    mouseEnterAction : nil
    mouseLeaveAction : nil
    mouseMoveAction : nil
    mouseOverAction : nil
    mouseWheelAction : nil
    keyDownAction : nil
    keyUpAction : nil
    keyModifiersChangedAction : nil
    keyTyped : nil
    focusGainedAction : nil
    focusLostAction : nil
    dragLabel : nil
    beginDragAction : nil
    canReceiveDragHandler : nil
    receiveDragHandler : nil
    toFrontAction : nil
    endFrontAction : nil
    onClose : nil
    onResize : nil
    onMove : nil
    itemPressedAction : nil
    onItemChanged : nil
}
PATH: /home/paum/Projekty/__2021/ambisonic/test.scd
CALL STACK:
	MethodError:reportError
		arg this = <instance of PrimitiveFailedError>
	Nil:handleError
		arg this = nil
		arg error = <instance of PrimitiveFailedError>
	Thread:handleError
		arg this = <instance of Thread>
		arg error = <instance of PrimitiveFailedError>
	Object:throw
		arg this = <instance of PrimitiveFailedError>
	Object:primitiveFailed
		arg this = <instance of TreeView>
	TreeView:removeItem
		arg this = <instance of TreeView>
		arg item = nil
	Integer:do
		arg this = 20
		arg function = <instance of Function>
		var i = 10
	Interpreter:interpretPrintCmdLine
		arg this = <instance of Interpreter>
		var res = nil
		var func = <instance of Function>
		var code = "~t.numItems.do({ |i| ~t.remo..."
		var doc = <instance of Document>
		var ideClass = nil
	Process:interpretPrintCmdLine
		arg this = <instance of Main>
^^ The preceding error dump is for ERROR: Primitive '_QObject_InvokeMethod' failed.
F

**Comment by alln4tural** [comment]
hi Fero,

i believe this is a programming error on your part: The number of items is reduced each time you call `~t.removeItem`, so at some point, `i `will be larger than that number ..

There are ways you could do this poperly, for example:

```
~t.numItems.reverseDo({ |i| ~t.removeItem( ~t.itemAt(i) ) }) // start with the largest i instead of the smallest
~t.numItems.do({ |i| ~t.removeItem( ~t.currentItem ) }) // 
~t.numItems.do({ |i| (i < ~t.numItems).if{ ~t.removeItem( ~t.itemAt(i) ) } {"oops, i is % but ~t.numItems is %\n".postf(i, ~t.numItems)}}) // 
~t.numItems

```

cheers,
eddi
https://soundcloud.com/all-n4tural/sets/spotlight

**Comment by paum3** [comment]
oh, yes!
Thank @alln4tural you for putting me on the correct path.

best
