### ISSUE TITLE
Combine "comp: UnitTest" and "comp: test suite" labels

### ISSUE THREAD

**Issue by brianlheim** [supercollider/supercollider#5379]
## Motivation

The difference between the meaning of these labels is not clear to most people, and the labels are often used incorrectly. Also, the separation seems a bit too fine-grained -- given how few issues and PRs we have using these two labels (15 in total, of which 2 use both!), and given that changes in UnitTest often have an impact on the test suite itself, I think it would actually be more helpful to lump them all together.

## Description of Proposed Feature

Merge "comp: UnitTest" and "comp: test suite" into a single label, "comp: testing", to be used for anything related to testing. for PRs, it should only be used when the _focus_ of the PR is testing. I would say it shouldn't be used if the PR just adds new tests for a bugfix or feature, since this is standard procedure, and the label would quickly lose its value if we used it that way. We can note this in the description for the label.

## Plan for Implementation

Rename "comp: UnitTest" to "comp: testing", relabel all open and closed tickets using the "comp: test suite" label so that they use "comp: testing" instead, and delete the "comp: test suite" label. Just to have some time constraint, I'll leave this ticket open for a couple days and if nobody objects I'll make the change this weekend.

**Comment by dyfer** [comment]
I think this is a good change.

One question:
> I would say it shouldn't be used if the PR just adds new tests for a bugfix or feature

What label should be used in that case? The one relevant to the tested class itself, like `comp: class library` or `comp: server plugins` ?

**Comment by brianlheim** [comment]
this is done now!
