### ISSUE TITLE
Cmd+Alt+<Arrow key> shortcuts not saved correctly

### ISSUE THREAD

**Issue by jleben** [supercollider/supercollider#538]
Cmd+Alt+<Arrow key> shortcuts work OK just after being set via configuration dialog, but are not saved correctly, so fail after IDE restart.

Seems like the string to represent the arrow key is not representable by the saving/parsing encoding? Afaik, the string should be simply "Left", "Right", etc.., but as a matter of fact it is not. Maybe the combination of modifiers before the arrow key make Qt produce a weird character instead of the aforementioned strings.

**Comment by scztt** [comment]
Appears to be fixed in 3.7. I get this in my shortcuts, and they work fine after an app restart:
    editor-go-to-next-region: Ctrl+Alt+Right
    editor-go-to-prev-region: Ctrl+Alt+Left
