### ISSUE TITLE
Remove ableist language

### ISSUE THREAD

**Issue by mossheim** [supercollider/supercollider#5382]
## Motivation

After discussion at https://scsynth.org/t/terminology-question/3372 it came to my attention there's a couple uses of ableist language in our project that we could easily replace with more inclusive language -- specifically "crazy" and "idiot". This would be really easy to do, so let's do it!

## Description of Proposed Feature

Replace with better words :)

## Plan for Implementation

This would be really easy to do, so let's do it!

**Comment by KenCox94** [comment]
@brianlheim can I tackle this?

**Comment by brianlheim** [comment]
sure, go ahead!

**Comment by brianlheim** [comment]
@KenCox94 are you still interested in this?

**Comment by rozNum** [comment]
If the open issue is still on the table, I would be able to assist. -roz

**Comment by dyfer** [comment]
hello @rozNum 
I think most of the issues have been addressed, the latest one in #5470
However, if you find any other problematic language, definitely feel free to propose changes!
