### ISSUE TITLE
scide.exe - Enrty Point Not Found [TryAcquireSRWLockExclusive]

### ISSUE THREAD

**Issue by satourne** [supercollider/supercollider#5387]
## Environment

* SuperCollider version: SuperCollider-3.11.2-Windows-32bit-VS.exe or SuperCollider-3.10.4_Release-x86-VS-95e9507.exe
* Operating system: Windows Vista SP1
* Other details (Qt version, audio driver, etc.): ???

## Steps to reproduce

- Install software on D:\Program Files\SuperCollider-3.11.2
- Launch Program
- An error occured

## Expected vs. actual behavior

Window Title :    scide.exe - Enrty Point Not Found
Window Text:     The procedure entry point TryAcquireSRWLockExclusive could not be located in the dynamic library KERNEL32.dll

EVENT :
Application défaillante scide.exe, version 0.0.0.0, horodatage 0x5fb07b58, module défaillant KERNEL32.dll!TryAcquireSRWLockExclusive, version 6.0.6001.18000, horodatage 0x4791a7a6, code d’exception 0xc0000139, décalage d’erreur 0x00009cac, ID du processus 0x1654, heure de début de l’application 0x01d711e5a53e6b4c.

EVENT DETAILS :
- System 

  - Provider 

   [ Name]  Application Error 
 
  - EventID 1000 

   [ Qualifiers]  0 
 
   Level 2 
 
   Task 100 
 
   Keywords 0x80000000000000 
 
  - TimeCreated 

   [ SystemTime]  2021-03-05T17:33:27.000Z 
 
   EventRecordID 96172 
 
   Channel Application 
 
   Computer Sony-VGN-AW21Z 
 
   Security 
 

- EventData 

   scide.exe 
   0.0.0.0 
   5fb07b58 
   KERNEL32.dll!TryAcquireSRWLockExclusive 
   6.0.6001.18000 
   4791a7a6 
   c0000139 
   00009cac 
   1654 
   01d711e5a53e6b4c

**Comment by brianlheim** [comment]
Thanks for the report @satourne !

This Win32 function (TryAcquireSRWLockExclusive) appears to be supported only by [Windows 7 and later](https://docs.microsoft.com/en-us/windows/win32/api/synchapi/nf-synchapi-tryacquiresrwlockexclusive). We in fact believed that we supported Windows Vista in these releases, but were planning to drop support in the next release. We won't be making further patch releases of 3.11.2, so I would recommend upgrading your system if you want to use newer versions of SC.

Out of curiosity, are you on a 64-bit Windows system? If so, can you try the 64-bit release builds?
