### ISSUE TITLE
Issue loading devices on post window

### ISSUE THREAD

**Issue by elliemayaaa** [supercollider/supercollider#5395]
Hi, I am new here It is my first time using SuperCollider..

I am currently trying to load an Arduino device however once I have input the code the post window does not load anything. 

SerialPort.devices;
~port = SerialPort.new();

That is the code that I put in to receive the device fyi

Please let me know if it is me missing something here??

**Comment by alln4tural** [comment]
Hi there and welcome!

Github is for bugs ..
Please join us over on 
https://scsynth.org/c/questions/
for usage questions

**Comment by brianlheim** [comment]
Yes, this is probably a better topic for our forum. If it turns out that there is a bug here which is reliably reproducible please feel free to open another issue with more details!
