### ISSUE TITLE
Warp nodeproxy values using specs

### ISSUE THREAD

**Issue by madskjeldgaard** [supercollider/supercollider#5408]
## Motivation

Hello!

It would be great if it was possible to use the specs of a Nodeproxy to map incoming nodeproxies' values to certain ranges using the receiving nodeproxy's catalogue of specs, or the global spec space or as a fallback a reasonable default spec (0.0 to 1.0 in my opinion). 

It seems to have been the intent at some point but currently at least to a notyetimplemented bug pointing to here:
https://github.com/supercollider/supercollider/blob/18c4aad363c49f29e866f884f5ac5bd35969d828/SCClassLibrary/JITLib/ProxySpace/BusPlug.sc#L128

## Description of Proposed Feature
Here is a simple test scenario where I use a very verbose way of doing this or trying to do it:

```
(
Ndef(\zzz, { 
	SinOsc.ar(
		\freq.kr(100, spec: Spec.specs[\freq]).poll
	) 
});

// Fine: Map singular scalar values
Ndef(\zzz).set(
	\freq, Ndef(\zzz).specs[\freq].map(0.5)
);

// Not fine: Map modulated values
Ndef(\lfo, { SinOsc.kr(\freq.kr(1)) });
Ndef(\zzz).set(
	\freq, Ndef(\zzz).specs[\freq].map(Ndef(\lfo))
);
)
```

it should perhaps be a seperate method for nodeproxies ala `mapped` or something distinguishing it more from map/set that don't seem to be using specs at all. 

## Plan for Implementation
Sorry, no plan as of yet, writing this in a bit of a hurry :) 

best!

**Comment by telephon** [comment]
Hm, then you limit the proxies that you can map to the `freq` argument of `zzz`. Wouldn't it be better to make the mapping inside `Ndef(\zzz)` and assume only unipolar ranges outside? Then you are pretty free in what you map to it.

**Comment by madskjeldgaard** [comment]
> Hm, then you limit the proxies that you can map to the `freq` argument of `zzz`. Wouldn't it be better to make the mapping inside `Ndef(\zzz)` and assume only unipolar ranges outside? Then you are pretty free in what you map to it.

Aha, okay, so if I understand you correctly, something like this is what you suggest doing instead?

```
(
Ndef(\l, { LFSaw.kr(0.01).unipolar });

Ndef(\zzz, { 
	var lfoval = Ndef(\l).kr;
	var freq = Spec.specs[\freq].map(lfoval).poll;
	SinOsc.ar(freq)
}).play;
)
```
But then how is it supposed to work with a Nodeproxy/Ndef's own "local" specs? It doesn't seem to be possible to create an argument using NamedControl with a custom spec in it and also allow it to be mapped like this at the same time, or is it? 

Thanks for your help!

**Comment by telephon** [comment]
> It doesn't seem to be possible to create an argument using NamedControl with a custom spec in it and also allow it to be mapped like this at the same time, or is it?

I would have thought something like this:
```
Ndef(\zzz, { 
	var freq = \freq.asSpec.map(\lfo.kr).poll;
	SinOsc.ar(freq)
}).play;

```
