### ISSUE TITLE
Getting no sound on whenever I play anything. How can I fix this?

### ISSUE THREAD

**Issue by varun1024** [supercollider/supercollider#5417]
Bug description:
Whenever I try to play anything in supercollider, There's no sound coming in from my end. 
Steps to reproduce:
1.
2.
3.

Actual result:

Expected result:

**Comment by jparmentervf** [comment]
What is? What code are you executing?

**Comment by varun1024** [comment]
(
SynthDef.new(\pbind_test, {
	arg freq=400,atk=0.01,rel=1,amp=0.2,out=0;
	var sig, env;
	env = EnvGen.kr(Env.perc(atk,rel), doneAction:2);
	sig = Saw.ar([freq, freq * 0.2.midiratio]);
	sig = sig * env * amp;
	Out.ar(out, sig);
}).add;
)


(
p = Pbind(
	\instrument, \pbind_test, //specify the SynthDef's name
	\dur, 0.2,
	\scale, Scale.minorPentatonic,
	\degree, Pxrand([0,1,2,3,4,5], inf),
	\amp, Pexprand(0.05, 0.3),
	\atk, 0.01,
	\rel, 0.3,
	\out, 0,
);

x = p.play;
)

x.stop;

**Comment by varun1024** [comment]
the play function is working but no sound is coming

**Comment by jparmentervf** [comment]
Does this play any sound?

s.boot.doWhenBooted({
	{SinOsc.ar(440, 0, XLine.kr(0.5, 0.01, 2, doneAction: 2))}.play;
})

Your example played for me on BigSur... please let me know about the above for you.

**Comment by dyfer** [comment]
@varun1024 are you running the special big sur build? (available on our download/release pages)

**Comment by varun1024** [comment]
> Does this play any sound?
> 
> s.boot.doWhenBooted({
> {SinOsc.ar(440, 0, XLine.kr(0.5, 0.01, 2, doneAction: 2))}.play;
> })
> 
> Your example played for me on BigSur... please let me know about the above for you.

yep it worked
