### ISSUE TITLE
Enable running sclang without Qt.

### ISSUE THREAD

**Issue by Zaabson** [supercollider/supercollider#5420]
## Motivation
Using [tidalcycles](https://github.com/tidalcycles/Tidal) means running [superdirt](https://github.com/musikinformatik/SuperDirt) from supercollider. I can execute the needed script with sclang and don't need scide. I am using windows subsystem for linux where Qt can't connect to display and sclang simply doesn't open - even though it doesn't open a gui app when it does open.
Is it the case that sclang doesn't need Qt?

## Description of Proposed Feature
As I understand - not requiring scide is not specific to tidal users. Creating an option to install supercollider without Qt dependency would alleviate troubles on wsl and in general would provide a more lightweight installation.

## Details on my case
Running sclang or scide from the terminal on wsl2 yields an error: "qt.qpa.xcb: could not connect to display".

This is because wsl2 as of now can't run gui apps. There are workarounds involving running Windows X server on Windows and connecting wsl with it via ssh, then wsl sends graphics for Windows to display it. I managed to do that and then correctly run sclang - showing that the installation is working and all Qt dependencies are satisfied. But running sclang doesn't pop up any window, the interface stays inside the terminal what makes me wonder why couldn't it open initialy.

### Previous issue
Am I even correct assuming that Qt dependency can be eliminated for a subset of supercollider?
[This issue](https://github.com/supercollider/supercollider/issues/4980#issue-625962641) suggests that it is. Maybe mine will provide more motivation for this change.

**Comment by dyfer** [comment]
Hi @Zaabson 
I think you might be able to run sclang by specifying Qt "offscreen" platform plugin (?):
```
export QT_QPA_PLUGIN=offscreen
sclang
```
It seems to work on linux in terminal (no X session). Could you try it in wsl?

**Comment by Zaabson** [comment]
Thanks!
Setting QT_QPA_PLUGIN didn't help but I think you meant QT_QPA_PLATFORM. Setting that one to offscreen indeed lets me run sclang!

**Comment by dyfer** [comment]
Ah yes, my bad! I was typing that on another computer. I glad it worked!

It would be nice to document this, just not sure where would be a good place to do so.

**Comment by Zaabson** [comment]
There is `Environment` section in `README_LINUX` but this variable is not specific to Supercollider. There would be no problem if I went with the Qt-free installation but I used a script from [there](https://github.com/lvm/build-supercollider) and I guess a lot of poeple do.

**Comment by dyfer** [comment]
I've proposed the addition in the "Running sclang" section in Readme: #5423

**Comment by Zaabson** [comment]
Good! I've also added a single line to [tidal install guide](https://tidalcycles.org/Linux_installation) mentioning to go with Qt-free installation on wsl.

**Comment by dyfer** [comment]
closed in #5423
