### ISSUE TITLE
catenated symbols don't compare equal to written out symbol

### ISSUE THREAD

**Issue by rd--** [supercollider/supercollider#5430]
hello all

not sure if this is exactly a bug, but it's odd because the string variant works, as does just going to and from string...

```supercollider
("freq" ++ 1.asString).asSymbol == 'freq1' // true
('freq' ++ 1.asSymbol) == 'freq1' // false
('freq' ++ 1.asSymbol).asString.asSymbol == 'freq1' // true
```

best,
rohan

environment:

$ sclang -version # debian testing
sclang 3.11.2 (Built from branch 'not_a_git_checkout' [na])
$ uname -a
Linux x270 5.10.0-3-amd64 #1 SMP Debian 5.10.13-1 (2021-02-06) x86_64 GNU/Linux
$

**Comment by telephon** [comment]
It would be convenient, but there is one good reason for this: When you concatenate many symbols, each subsequent combination would be registered in the symbol table and fill it up unnecessarily.

**Comment by rd--** [comment]
ah, i see, thanks very kindly for the explanation!  i'll close this

best,
rohan
