### ISSUE TITLE
SCIDE doesn't highlight class names when loading files at startup from a session

### ISSUE THREAD

**Issue by jamshark70** [supercollider/supercollider#5434]
## Environment

* SuperCollider version: develop
* Operating system: Ubuntu Studio 20.04
* Other details (Qt version, audio driver, etc.): Qt 5.12.8

## Steps to reproduce

1. Save a session in SCIDE.
2. Quit and relaunch SCIDE.
3. Syntax colorizing / highlighting appears to get everything *except* class names.

In this screenshot, KrBusWatcher, Window, File, BP and PR should all be highlighted blue. They aren't.

![no-class-highlights](https://user-images.githubusercontent.com/318301/116811366-87a50c80-ab7b-11eb-8ee3-80c6c590e81d.png)

## Expected vs. actual behavior

Highlighting should be updated immediately after class library init.

Hackaround: Select-all and tab to reformat.

**Comment by telephon** [comment]
Maybe came from this? #4890

**Comment by jamshark70** [comment]
> Maybe came from this? 4890

Yeah, that sounds right.

I hadn't quite worked it out in my head at the time of posting, but the behavior would be explained by the fact that class library introspection data are not available at the moment of opening session file(s). So the bug is that receiving introspection data does not trigger re-highlighting documents that are already open.

I wouldn't mind it at all if highlighting is incomplete for the first few seconds after opening IDE, but when you're accustomed to seeing class names in color and suddenly they aren't in color, it's a readability/usability issue -- so we should use introspection data as soon as they're available.

**Comment by jrsurge** [comment]
Apologies - a slight oversight on my part. I'll look into it today. My current plan is to wait for introspection before doing any highlighting so it all appears at once.

Just to point out that this is current only in the develop branch, not a public release. @jamshark70 I'm going to update the ticket to reflect that, just for clarity.

J
