### ISSUE TITLE
Function plot fail with argument nil

### ISSUE THREAD

**Issue by redFrik** [supercollider/supercollider#5435]
## Environment

* SuperCollider version: 3.11.2
* Operating system: macOS 10.14.6

## Steps to reproduce

```supercollider
{|a| SinOsc.ar(999, a, 0.1)}.play  //ok with no value for a

{|a| SinOsc.ar(999, a, 0.1)}.plot  //fails

SinOsc arg: 'phase' has bad input: nil
 ARGS:
   freq: 999 Integer
   phase: nil Nil
SynthDef 361064639 build failed
ERROR: SinOsc arg: 'phase' has bad input: nil
```

## Expected vs. actual behavior

it's a minor issue and a corner case, but i'd expect .plot to behave similar to .play here.  i.e. assume that argument a is 0 by default.

**Comment by shimpe** [comment]
hmm maybe it would make more sense if play also fails? Assuming things that were not specified sounds like a disaster waiting to happen.

**Comment by telephon** [comment]
@shimpe It is no disaster at all if the phase is 0 (this is the default) – unspecified control values default to 0, not to nil.

**Comment by jamshark70** [comment]
> hmm maybe it would make more sense if play also fails?

For what it's worth -- I use `{}.play` with arguments converted to synth controls *routinely*, like, *everywhere*. It's really convenient to produce a one-off effect synth with specific controls (e.g. `mix`). Removing the ability to do this would break *a lot* of the instruments in my live setup. Fair enough to brainstorm solutions, but in general I would be skeptical about thought processes along the lines of "we have related features A and B; B is more restricted than A; therefore perhaps A should be made equally restricted."

Glad that the solution was easy.

**Comment by shimpe** [comment]
No worries. If everyone is happy, I'm happy too :) I just know from painful experience (outside sc) that default behavior can cause very hard to find bugs if one didn't intend for the behaviour to be default but just forgot to pass in a value. For this reason I'm on a bit of a personal war against default arguments and prefer to have it crash and force me to specify the behavior I expect. But of course, if people already widely rely on default behavior it's a bad idea to remove it for backward compatibility reasons (unless perhaps there's some way to enable an optional "strict" mode).

**Comment by jamshark70** [comment]
> For this reason I'm on a bit of a personal war against default arguments and prefer to have it crash and force me to specify the behavior I expect.

A "strict" mode would be possible by having Control and NamedControl check for nil defaults (or I guess for any invalid type).

After a couple of decades of allowing nil to be replaced by 0 in synth control defaults, a strict mode would have to be optional for sure.

Tangentially, it's important not to forget the live-coding use case. From a computer science perspective, unspecified defaults are a risk factor that should be disallowed. But, when one is programming/jamming on stage, one wants the system to continue functioning as much as possible with sensible defaults. SC does have to serve multiple user bases whose goals may not always overlap.
