### ISSUE TITLE
Examples missing

### ISSUE THREAD

**Issue by joesh1** [supercollider/supercollider#5447]
I've downloaded SC 3.11.2 which almost works fine on Big Sur, however, I have a rather odd issue which is that I have no examples when I select Cmd + D. The help file shows up fine, but all the examples are blank!

I didn't see any mentions here - I did a quick search, so any suggestions, or is it an issue to be submitted?

**Comment by dyfer** [comment]
I haven't seen that behavior... so maybe an issue should be submitted. Just to make sure, are you running the "special" Big Sur build (`3.11.2+BigSur.aed25fa`)?

**Comment by joesh1** [comment]
Yes, I reloaded it again (just in case I'd made a mistake and loaded something else), but no luck. I've posted this issue on the scsynth.org forum, but nobody reacted which I find a bit odd. Could I be the only one with an issue?

If you have any suggestions of something I could try, I'd be happy to have a go as maybe it's me? Just for the information, I"m on a MacBook Pro (Retina, 13-inch, Early 2015), running Big Sur version 11.2.3.

**Comment by dyfer** [comment]
When you switched versions, have you cleaned up the `~Library/Application Support/SuperCollider` folder? If you do that you'd want to back up any extensions etc you might have installed. But I'd try that - move (rename etc) that folder temporarily and start SC (the newest one) again and see if the issue persists. Then gradually start adding things to the new `~Library/Application Support/SuperCollider` folder (restarting SC each time) and see if there's anything there that prevents the examples from showing up.

**Comment by joesh1** [comment]
@dyfer, that did it, thanks. Maybe you can explain - simply - what the problem was? 

And lastly, I imagine I can delete the old file - it had nothing important in it, as I just changed computers, and everything else is still on the old computer.

**Comment by dyfer** [comment]
> @dyfer, that did it, thanks. Maybe you can explain - simply - what the problem was?

I don't know for sure... but my guess was that it was either something in the QtWebEngine settings, or the rendered Help files, which both live in the there...

...which made me realize that we haven't tried something "trivial": rebuilding help files! So if anyone comes across this again, my first advice is to run:

 `SCDoc.indexAllDocuments(true)`

If that doesn't help, remove/clean up the `SuperCollder` folder in `Application Support` (saving extensions and quarks if desired).

**Comment by joesh1** [comment]
Okay, thanks again. I was - before you solved the problem - about to rebuild the help files, but your solution was simpler and everything works fine now.
