### ISSUE TITLE
Cant init midi after upgrading to BigSur

### ISSUE THREAD

**Issue by sentinelweb** [supercollider/supercollider#5455]
I am having issue with midi after upgrading to big sur - I had a working fine  midi configuration going before upgrading to BigSur - was the same supercollider version (i think!! :/)

## Environment

* SuperCollider version: '3.11.2-BigSur' [aed25fa]
* Operating system: macOS bigSur 11.3.1
* Other details (Qt version, audio driver, etc.):MacBook Pro (15-inch, 2019)

## Steps to reproduce

```supercollider
Execute `MIDIClient.init;`
```

## Expected vs. actual behavior

```
Could not create MIDI client. error: ERROR: Primitive '_InitMIDI' failed.
Failed.
RECEIVER:
class MIDIClient (0x7fe9c845f3c0) {
  instance variables [19]
    name : Symbol 'MIDIClient'
    nextclass : instance of Meta_MIDIEndPoint (0x7fe9a167f340, size=19, set=5)
    superclass : Symbol 'Object'
    subclasses : nil
    methods : nil
    instVarNames : nil
    classVarNames : instance of SymbolArray (0x7fe9c845f540, size=5, set=2)
    iprototype : nil
    cprototype : instance of Array (0x7fe9c845f600, size=5, set=3)
    constNames : nil
    constValues : nil
    instanceFormat : Integer 0
    instanceFlags : Integer 0
    classIndex : Integer 50
    classFlags : Integer 0
    maxSubclassIndex : Integer 50
    filenameSymbol : Symbol '/private/var/folders/dm/vf2dc5694rv10tp6dyngbm4h0000gn/T/AppTranslocation/FA13396C-76EB-43D9-9F64-44A5561D60BD/d/SuperCollider.app/Contents/Resources/SCClassLibrary/Common/Control/MIDIOut.sc'
    charPos : Integer 212
    classVarIndex : Integer 420
}
PATH: /Users/robmunro/repos/personal/supercollider/projects/tr8s/test.scd
CALL STACK:
	MethodError:reportError
		arg this = <instance of PrimitiveFailedError>
	Nil:handleError
		arg this = nil
		arg error = <instance of PrimitiveFailedError>
	Thread:handleError
		arg this = <instance of Thread>
		arg error = <instance of PrimitiveFailedError>
	Object:throw
		arg this = <instance of PrimitiveFailedError>
	Object:primitiveFailed
		arg this = <instance of Meta_MIDIClient>
	Meta_MIDIClient:init
		arg this = <instance of Meta_MIDIClient>
		arg inports = 0
		arg outports = 0
		arg verbose = true
	Interpreter:interpretPrintCmdLine
		arg this = <instance of Interpreter>
		var res = nil
		var func = <instance of Function>
		var code = "MIDIClient.init;"
		var doc = nil
		var ideClass = <instance of Meta_ScIDE>
	Process:interpretPrintCmdLine
		arg this = <instance of Main>
^^ The preceding error dump is for ERROR: Primitive '_InitMIDI' failed.
Failed.
RECEIVER: MIDIClient
```

**Comment by dyfer** [comment]
Hello, thanks for the report.
Unfortunately I can't reproduce this on Big Sur (though it's a fresh install, not an upgrade).
To debug this, could you try these procedures, followed by running  `MIDIClient.init;`:
- try the latest "bleeding edge" build (found on our regular download page)
- temporarily remove all extensions and quarks
- prevent SuperCollider from being translocated by moving it directly to `/Applications` (not `/Applications/SuperCollider/`) (though this really shouldn't matter...)

**Comment by sentinelweb** [comment]
Ok so i moved all out plugins of the plugins directory and `MIDIClient.init;` works! 

Then i moved the plugins back and it still works ...

Not sure if that would clear some cached files or something ... anyway thanks for the help ....

**Comment by sentinelweb** [comment]
Ok ... I didn't update the device driver to the masOS 11 version ... Sorry to take up your time ... I am suitably embarrassed...
