### ISSUE TITLE
Win XP only: TempoClock scheduling crashes sclang

### ISSUE THREAD

**Issue by jamshark70** [supercollider/supercollider#547]
In win XP (3.6 dev), this example causes sclang to stop responding. Sometime after that, the language will crash.

    TempoClock.sched(0.5, { "hello".postln });

Use SystemClock or AppClock instead, and all is well.

In win7, all clocks behave properly.

My XP build, using Jakob's copies of the dlls, doesn't resolve this problem.

3.5 did not have this problem - hence, it's a regression.

**Comment by bagong** [comment]
Is Win XP support still an issue? I vote for no.

**Comment by scztt** [comment]
Windows XP is older than SuperCollier 3 itself. So, I vote no too. :)

**Comment by bagong** [comment]
XP-specific so closed.
