### ISSUE TITLE
keep a number of file backups

### ISSUE THREAD

**Issue by timblechmann** [supercollider/supercollider#548]
when storing a file, we should keep a number of  backups of the file to avoid data loss when accidentally saving a file.
files could have an additional extension like .~1~.

**Comment by scztt** [comment]
This is admirably handled in the JetBrains IDE apps. They keep an internal document history that can be logged and diff'd almost exactly like a git history - you can even restore deleted files. I've found it's honestly one of the killer features of that suite.
