### ISSUE TITLE
How do I compile all the .schelp files into .html?

### ISSUE THREAD

**Issue by Sleepful** [supercollider/supercollider#5489]
## Environment

* SuperCollider version: latest
* Operating system: macos

The issue is that I am trying to open the helpfiles through my own browser, but it seems like they aren't compiled into `.html` until I actually open the files in the `scide` browser. Then they appear inside `~/Library/Application Support/SuperCollider/Help`.

**Comment by Sleepful** [comment]
Found it! `SCDoc.renderAll`, [Thanks!](https://doc.sccode.org/Overviews/Methods.html#renderAll)

**Comment by jamshark70** [comment]
Glad you found it.

I'd like to suggest that this sort of question may be better for the forum at scsynth.org. Github should be used primarily for bug reports and feature requests. This is more of a usage question, and as such, it really belongs on the forum.
