### ISSUE TITLE
Naming of SCApp, IDE, and SuperColliderCocoa are incompatible

### ISSUE THREAD

**Issue by telephon** [supercollider/supercollider#549]
While in the closed issue #473 it is stated that the renaming of the SCApp to "SuperColliderCocoa" is intentional to allow the parallel usage with the IDE, this whole naming scheme creates incompatibility across versions (at least on OS X).

Currently, the only stable version is SC3.5.5, which is (properly) called SuperCollider and uses the extension folder of SuperCollider

SuperCollider 3.6 compiled with the IDE is also called SuperCollider, but doesn't implement the same functionality, which is why it throws sclang errors on startup (e.g. when trying to add to the library menu).

SuperCollide 3.6 compiled without IDE (using SCApp) is renamed SuperColliderCocoa, which makes it use a different startup file than 3.5.5, while it actually should use the same (being the newer version of the compatible application).

Additionally it needs to be said that the renaming to SuperColliderCocoa is also quite awkward, just as awkward as if Firefox were called FirefoxCocoa or SuperCollider were called SuperColliderKDE.

**Comment by adcxyz** [comment]
this is obsolete by now, so closing.
