### ISSUE TITLE
NdefGui (EnvirGui) ignores local specs from NamedControls

### ISSUE THREAD

**Issue by madskjeldgaard** [supercollider/supercollider#5515]
## Environment

* SuperCollider version: 3.11.2
* Operating system: Arch Linux
* Other details (Qt version, audio driver, etc.): scnvim

## Steps to reproduce

```supercollider
// In this gui, the range of the \fff parameter 10 to 4000.
Ndef(\1, {SinOsc.ar(freq: \fff.kr(200, spec: Spec.specs[\freq]))}).gui;

// Checking local specs:
Ndef(\1).specs;

// -> ( 'fff': a ControlSpec(20, 20000, 'exp', 0, 440, " Hz") )

```

The problem seems to be in EnvirGui's getSpec method:
https://github.com/supercollider/supercollider/blob/de60e3405b417779bd35c19add1c6b2cca3bd194/SCClassLibrary/JITLib/GUI/EnvirGui.sc#L324-L335

As a user I don't think having to install JITLibExtensions to get correct behaviour is the expected way for this to work. 

I experimented with overriding the method to adding a check to see if the object contains a spec and if so use it:

```
+ EnvirGui {
  getSpec { |key, value|
    var spec = specs[key] ?? object.specs.at(key) ?? { key.asSpec };
    if (spec.isNil) {
      spec = Spec.guess(key, value);
      specs.put(key, spec);
    };
    ^spec
  }
}
```

This seems to fix it for me - but not sure if this breaks other things.

**Comment by rd--** [comment]
Hello,

I'm here for almost the same reason, so adding to this issue.

I **do** have JITLibExtensions installed, but here (sclang 3.11.2) to get metadata specs from the SynthDef to set the `.gui` range it seems I need to add them to the Halo object, as below.

This works, but I was also wondering if the `.gui` could lookup them up directly?  Or am I doing this the wrong way?

````
        ...
        var anNdef = Ndef.new(aSymbol, aBlock).mold(2).play;
        var specData = aBlock.asSynthDef.metadata.at(\specs);
        specData.keysValuesDo({arg key, value; anNdef.addSpec(key, value)});
        anNdef.gui;
        ProxyPresetGui.new(NdefPreset.new(aSymbol)); /* JITLibExtensions */
        ...
````

Best,
Rohan

**Comment by telephon** [comment]
The underlying problem is that SynthDefs do not remember their specs (I think), even though `NamedControl` defines it. One could perhaps hack this by inspecting `currentControls` in the build process, but it would be better if we could solve this more generally.

**Comment by rd--** [comment]
Hello!  I think they must, because that's how I'm getting them in order to write them into the Halo?  They're in `.metadata.at(\specs)`.  I cut the method definition a little short above, here's the whole thing for context.  It works here (3.11.2) and I'm fine with doing it this way but also it might make sense for `.gui` to just grab them itself? Best, Rohan

````
    *playFunctionWithNdefUi {
        arg aBlock;
        var aSymbol = ("_gensym_" ++ Date.getDate.stamp).asSymbol;
        var anNdef = Ndef.new(aSymbol, aBlock).mold(2).play;
        var specData = aBlock.asSynthDef.metadata.at(\specs);
        specData.keysValuesDo({arg key, value; anNdef.addSpec(key, value)});
        anNdef.gui;
        ProxyPresetGui.new(NdefPreset.new(aSymbol)); /* JITLibExtensions */
    }
````

**Comment by telephon** [comment]
Yes, sorry, I was wrong!

**Comment by telephon** [comment]
> This works, but I was also wondering if the .gui could lookup them up directly? 
Yes, you can simple get the specs by `Ndef(\x).specs`. I don't know how this should be done in NdefMixer etc. (@adcxyz, what do you think)

**Comment by rd--** [comment]
Ah yes, thanks kindly, that is it!  So now I have the below, which works nicely, but does seem a bit circular! :)

````
        anNdef.specs.keysValuesDo({arg key, value; anNdef.addSpec(key, value)});
````

But if I delete this line, the `.gui` in the next line (ie. `anNdef.gui`) has the default ranges again...

Thanks,
R

**Comment by telephon** [comment]
The specs that you assign with `addSpec` are "outer specs" kept separately for an Ndef.  They are stored globally in a so called Halo, an object that can keep stuff for another object. A Halo is independently stored, so one has to take care to delete it when its object is not needed anymore.

The specs that you retrieve with `specs` come from the internal UGen function that is the `Ndef`s current source.

```supecollider

Ndef(\x, { \aafreq.kr(spec:\freq) });

// these are the specs
Ndef(\x).specs
-> ( 'aafreq': a ControlSpec(20, 20000, 'exp', 0, 440, " Hz") )


// function to retrieve the specs from the current source(s) and store it for the Ndef
f = { |x| x.specs.keysValuesDo({arg key, value; x.addSpec(key, value)}) };

f.(Ndef(\x));

// now add another source
Ndef(\x, { \bbfreq.kr(spec:\rate) });
Ndef(\x).specs

// new specs, found by calling .specs
-> ( 'bbfreq': a ControlSpec(0.125, 8, 'exp', 0, 1, "") )

// old specs, found by calling .getSpec
Ndef(\x).getSpec
-> ( 'aafreq': a ControlSpec(20, 20000, 'exp', 0, 440, " Hz") )


```

**Comment by rd--** [comment]
Ah, thank you, that's very clear!  So in this case, I will just send `clearHalo` when the window goes away.

````
        anNdef.gui.parent.onClose_({anNdef.clearHalo});
````

I just looked up WeakArray &etc. in SC and they're not there!

**Comment by telephon** [comment]
> I just looked up WeakArray &etc. in SC and they're not there!

Long ago, I asked James McCartney if we could have weak arrays, but he said it would be quite complex to implement.

In the meantime I have something else, but it needs some work (some of it beyond my ability) to get it into sclang properly:

https://github.com/telephon/rfcs/blob/master/rfcs/0002-abstract-object.md

**Comment by telephon** [comment]
ah good – Probably it will have to make a difference between those specs that have been added extrenally and those that result from the synthDef (which may change when replacing it).

**Comment by dmorgan-github** [comment]
Hello, I just wanted to upvote this feature request...
Thank you

**Comment by adcxyz** [comment]
ok, some progress on this:
 #5681 fixes the embedded specs using LagControl that got lost. 

design question: what is the best name for these specs inside synth functions?
I had called them "implicit specs", but maybe "embedded specs" is better? 
I am asking so that we have a good name for a method that finds a single embedded spec:
```Ndef(\x).findEmbeddedSpec(\freq);```
which should be in the SCClassLibrary, 
so it works for NdefGuis with and without JITLibExtensions quark installed.

**Comment by dmorgan-github** [comment]
maybe "named spec"? since they're defined as part of a named control...but "embedded spec" sounds good to me

**Comment by telephon** [comment]
Specs could be used for all kinds of thing. To me, it would be clearer to say where it searches for it. So something like `Ndef(\x).findControlSpec(\freq)` ?

**Comment by adcxyz** [comment]
Thanks for the proposals! 
I moved "control" to the arg name, so the lower levels are:
```
SynthDefControl:findSpecFor(controlName)
SynthDef:findSpecFor(controlName)
```
at the top level, nodeproxies may have multiple objects, 
possibly with more than one spec for the same controlName;
as this is for fast spec lookup for guis and controllers, 
we only take the first one, so this is called
```
NodeProxy:findFirstSpecFor(controlName)
```
which is then used in NdefGui:getSpec to check for 
any embedded specs before using guessed ones. 

are these names clear enough?

**Comment by telephon** [comment]
yes, they are clear, I think.

**Comment by madskjeldgaard** [comment]
> yes, they are clear, I think.

I agree!

**Comment by telephon** [comment]
`gestSpec`is an extension method to `Object` in the `JITLibExtensions` Quark (the `Halo` interface allows to store extra data with any object whatsoever, think of it as a backpack attached to the object. The name halo comes from Squeak/Smalltalk).

`getSpec`looks like this:
```supercollider
getSpec { |name|
		var spec;
		var specs = Halo.at(this, \spec);
		if (name.isNil) { ^specs };
		if (specs.notNil) { spec = specs.at(name) };
		if (spec.isNil and: { name == '#' }) {
			name = this.key;
			if (specs.notNil) { spec = specs.at(name) };
		};
		^spec ?? { name.asSpec }
	}
```

**Comment by capital-G** [comment]
If anyone comes across the problem that explicitly stated specs do not get picked up by the NdefGUI, make sure you have updated https://github.com/supercollider-quarks/JITLibExtensions

I thought I updated it via the Quarks GUI, but in fact it didn't (although it suggested it). What helped me instead was updating the repo manually via a shell, for example for macOS

```shell
cd ~/Library/Application\ Support/SuperCollider/downloaded-quarks
git pull origin master
```
