### ISSUE TITLE
macOS Release 3.12.0-rc1 preferences interpreter options not working properly

### ISSUE THREAD

**Issue by redFrik** [supercollider/supercollider#5521]
## Environment

macOS 10.14.6
SuperCollider 3.12.0-rc1

## Steps to reproduce

* open preferences / interpreter tab.
* add a directory containing a class with the '+' button.
* hit apply and recompile.

the classes in the new directory aren't found and the directory just added isn't listed in the post window (no Compiling directory '' entry).

if i quit and restart the program the directory show up in post (i get a Compiling directory '') and the new classes are found.

same problem apply when trying to remove a directory from within the preferences window (the - button).
the sclang_conf.yaml file is correctly modified but somehow SCIDE is not picking up the changes at recompile like in previous sc version(s).

(adding / removing classes from the Quarks.gui window works like expected though - without the need to restart the whole app).

**Comment by dyfer** [comment]
Thanks for the report @redFrik 
This change was part of a PR, see [this comment](https://github.com/supercollider/supercollider/pull/3733#issuecomment-395006842). I haven't read through all the comments but it seems that there was a reason why rebooting the interpreter is now needed and people discussing the PR agreed to that change.
To clarify: what is now needed is _rebooting the interpreter_, instead of just recompiling the library. The dialog that pops up after changing the preferences does indicate the need to reboot the interpreter. Restarting SC is not necessary.

Can we treat this as an intended behavior?

**Comment by redFrik** [comment]
ah, i didn't notice that the dialog warning had changed.  you're absolutely right and i'll close this now.  thanks.

but it's an unfortunate change and i really don't like it.  there are tutorials out there that now will be incorrect and worse, this change is so subtle that many will miss it.  for sure it'll cause confusion.

**Comment by dyfer** [comment]
I can't say that I like this change either, but I think it was difficult to have some preferences (excluding default library) take effect without restarting the interpreter. I don't think I'll be able to look into changing this anytime soon... PRs are always welcome :)

**Comment by jamshark70** [comment]
There are two ways to change the library configuration:

1. Using `LanguageConfig` methods. This changes the RAM image of the config, which is useful for testing (add a directory for this session, and it will be forgotten when rebooting the interpreter.
2. Changing the yaml file (independent of language activities), and reloading when the interpreter reboots.

In the first case, you don't want to load the config from disk automatically.

In the second case, you do (but we don't, currently, I think to avoid breaking the first case).

I suppose the preferences panel could tell the language to reload, except there's no method for it. That is -- 1. Add a `LanguageConfig.read` method. 2. Call it when OK'ing or applying config changes from the preferences panel.

**Comment by jamshark70** [comment]
There are two ways to change the library configuration:

1. Using `LanguageConfig` methods. This changes the RAM image of the config, which is useful for testing (add a directory for this session and it will be forgotten when rebooting the interpreter, unless you explicitly call `LanguageConfig.store`).

2. Changing the yaml file (independent of language activities), and reloading when the interpreter reboots.

In the first case, you don't want to load the config from disk automatically. (This is why library compilation doesn't read the config from disk.)

In the second case, you do (but we don't, currently, I think to avoid breaking the first case).

I suppose the preferences panel could tell the language to reload, except there's no method for it. That is -- 1. Add a `LanguageConfig.read` method (which tbh I can't think of a good reason why this was omitted...?). 2. Call it when OK'ing or applying config changes from the preferences panel.
