### ISSUE TITLE
Collection's class method interface fails for 26 of it's subclasses

### ISSUE THREAD

**Issue by bla3kw3b** [supercollider/supercollider#5531]
##  #Environment

* SuperCollider version: 3.12.0rc1
* Operating system: Windows 10 Pro

## Steps to reproduce

- Call *`.fill .fill2D .fill3D .fillND .newFrom` or `.with`* on a subclass of *`Collection`* ...one that is included in the following `~failPerform List`

```supercollider
(((
    c = Collection.allSubclasses; // c.size -> 40

    ~failPerform = List[] ;

    c.do{ |x| { x.fill2D(8, 8, { |...xy| xy } ) } .try { ~failPerform.add(x) } };

    ~failPerform.printAll.size // -> 26 
)))

```

## Expected vs. actual behavior

Expected subclasses of Collection that are documented as inheriting it's class methods to be able to perform them reliably.

An example: 

`Array.fill2D(8, 8, { |...xy| xy })` 

Array2D is the highest collection in the hierarchy below Collection... and it has a separate class file, where at line one, it extends Collection's interface, however... *none* of it's class methods perform reliably, except for those it defines itself (*`.new` & `.fromArray`*)

This is probably a case by case or class by class fix... for Array2D, this could ideally be solved by tweaking the interface... or more simply perhaps by removing the inheritance, and thus removing the failed methods from it's documentation.
```
ERROR: 'add' should have been implemented by Array2D.
RECEIVER:
Instance of Array2D {    (000001BDD6E9F248, gc=CC, fmt=00, flg=00, set=02)
  instance variables [3]
    rows : Integer 8
    cols : Integer 1
    array : instance of Array (000001BDD721BF88, size=8, set=3)
}
CALL STACK:
	MethodError:reportError
		arg this = <instance of SubclassResponsibilityError>
	Nil:handleError
		arg this = nil
		arg error = <instance of SubclassResponsibilityError>
	Thread:handleError
		arg this = <instance of Thread>
		arg error = <instance of SubclassResponsibilityError>
	Object:throw
		arg this = <instance of SubclassResponsibilityError>
	Object:subclassResponsibility
		arg this = <instance of Array2D>
		arg method = Collection:add
	< FunctionDef in Method Meta_Collection:fill2D >
		arg col = 0
	Integer:do
		arg this = 8
		arg function = <instance of Function>
		var i = 0
	< FunctionDef in Method Meta_Collection:fill2D >
		arg row = 0
		var obj2 = <instance of Array2D>
	Integer:do
		arg this = 8
		arg function = <instance of Function>
		var i = 0
	Meta_Collection:fill2D
		arg this = <instance of Meta_Array2D>
		arg rows = 8
		arg cols = 8
		arg function = <instance of Function>
		var obj = <instance of Array2D>
	Interpreter:interpretPrintCmdLine
		arg this = <instance of Interpreter>
		var res = nil
		var func = <instance of Function>
		var code = "Array2D.fill2D(8, 8, { |...x..."
		var doc = nil
		var ideClass = <instance of Meta_ScIDE>
	Process:interpretPrintCmdLine
		arg this = <instance of Main>
^^ The preceding error dump is for ERROR: 'add' should have been implemented by Array2D.
RECEIVER: Array2D[ [ nil ][ nil ][ nil ][ nil ][ nil ][ nil ][ nil ][ nil ] ]
```
One more example:

`Dictionary.fill2D(8, 8, { |...xy| xy -> xy })`
```
ERROR: Message 'key' not understood.
Perhaps you misspelled 'keys', or meant to call 'key' on another receiver?
RECEIVER:
Instance of Dictionary {    (000001BDD6F22E08, gc=CC, fmt=00, flg=00, set=02)
  instance variables [2]
    array : instance of Array (000001BDD5C8CDE8, size=32, set=5)
    size : Integer 8
}
ARGS:
CALL STACK:
	DoesNotUnderstandError:reportError
		arg this = <instance of DoesNotUnderstandError>
	Nil:handleError
		arg this = nil
		arg error = <instance of DoesNotUnderstandError>
	Thread:handleError
		arg this = <instance of Thread>
		arg error = <instance of DoesNotUnderstandError>
	Object:throw
		arg this = <instance of DoesNotUnderstandError>
	Object:doesNotUnderstand
		arg this = <instance of Dictionary>
		arg selector = 'key'
		arg args = [*0]
	Dictionary:add
		arg this = <instance of Dictionary>
		arg anAssociation = <instance of Dictionary>
	< FunctionDef in Method Meta_Collection:fill2D >
		arg row = 0
		var obj2 = <instance of Dictionary>
	Integer:do
		arg this = 8
		arg function = <instance of Function>
		var i = 0
	Meta_Collection:fill2D
		arg this = <instance of Meta_Dictionary>
		arg rows = 8
		arg cols = 8
		arg function = <instance of Function>
		var obj = <instance of Dictionary>
	Interpreter:interpretPrintCmdLine
		arg this = <instance of Interpreter>
		var res = nil
		var func = <instance of Function>
		var code = "Dictionary.fill2D(8, 8, { |...."
		var doc = nil
		var ideClass = <instance of Meta_ScIDE>
	Process:interpretPrintCmdLine
		arg this = <instance of Main>
^^ ERROR: Message 'key' not understood.

Perhaps you misspelled 'keys', or meant to call 'key' on another receiver?
RECEIVER: Dictionary[ ([ 0, 2 ] -> [ 0, 2 ]), ([ 0, 4 ] -> [ 0, 4 ]), ([ 0, 5 ] -> [ 0, 5 ]), ([ 0, 0 ] -> [ 0, 0 ]), ([ 0, 3 ] -> [ 0, 3 ]), 
  ([ 0, 6 ] -> [ 0, 6 ]), ([ 0, 7 ] -> [ 0, 7 ]), ([ 0, 1 ] -> [ 0, 1 ]) ]
```

These fail-performs *almost* work in certain / sensible cases... and so this issue is understandably non-urgent... it exists for the sake of recording an area for strong improvement in SC's intermediate stage of future development.

**Comment by jamshark70** [comment]
> removing the inheritance

There's no way to do that. Subclasses can add or override, but never remove, methods.

For Collection abstract methods that don't make sense for specific subclasses, you can do:

Class file:

```
+ Array2D {
	*fill3D {
		^this.shouldNotImplement(thisMethod)
	}
}
```

Help file:

```
CLASSMETHODS::
private::fill3D
```

(Similar for instance methods.)

```
Dictionary.fill2D(8, 8, { |...xy| xy -> xy })
```

What would be a meaningful implementation of this? I suspect there isn't one.

**Comment by bla3kw3b** [comment]
(
```Library.fill3D(4,4,4, { |x y z n| // n is the total running iteration number
// it is currently implemented nowhere... however
}))

"
> ```
> Dictionary.fill2D(8, 8, { |...xy| xy -> xy })
> ```
> 
> What would be a meaningful implementation of this? I suspect there isn't one.

It was provided as a secure example... avoiding any possible extraneous or error-provoking behavior, solely for the sake of staying focused on the issue.

It's (apparent) sense of redundancy was intended in a way as a statement, reflecting this sense of focus.

I am however in partial agreement... the premise of the argument inherent to the issue is that the *resolution* of such would be in some way *useful* to us... and in this stroke redundancy is the very *antithesis* of *worthwhile usage*, so to speak.

I felt that this implication of worth would arise solely from the relationship between class `Dictionary` it's inherited method `fill2D`... it appears now however, that this is not the case... and from now on I will surely refrain from using content in such a way that may it appear to be *asinine*, at any length... surely one would ever possess such intent.

Thank you for focusing this towards it's greater improvement.

**Comment by bla3kw3b** [comment]
> ```
> Dictionary.fill2D(8, 8, { |...xy| xy -> xy })
> ```
> 
> What would be a meaningful implementation of this? I suspect there isn't one.

It was provided as a secure example while avoiding any possible extraneous, distracting, or error-provoking behavior... & solely for the sake of staying focused on the issue.

It's sense of redundancy was purposely allowed to remain apparent, in some way to reflect this sense of focus.

I am however to an extent in agreement... the premise of the argument inherent to the issue is that the *resolution* of such would be in some way *useful* to us... and in this stroke redundancy is the very *antithesis* of *usefulness*.

I felt that this implication of worth would arise solely from the relationship between class `Dictionary` it's inherited method `fill2D`... it appears now however that this is not the case... I will surely refrain from exhibiting such forms of content in such a way that it may it appear to be *asinine*, at any length... surely one would never possess such intent.

Thank you for focusing this towards it's greater improvement.

**Comment by telephon** [comment]
Probably, this is based on a misunderstanding: subclasses do not implement all superclass interface.

**Comment by jamshark70** [comment]
@bla3kw3b There's nothing wrong with asking a question whether something should be implemented or not -- but, the answer might be "No, there's not really a good way to do that."

For these specific methods, inheritance is a sticky problem. It's tempting to say that they make sense primarily for Arrays and Lists (SequenceableCollections), but then:

```
FloatArray.fill2D(5, 5, { 1.0.rand })

ERROR: Primitive '_ArrayAdd' failed.
Wrong type.
RECEIVER: FloatArray[  ]
```

... because a FloatArray may only contain Floats. A FloatArray cannot contain FloatArrays (which would be the implication of fill2D). All RawArray subclasses will run into this problem (e.g. `String.fill2D`, where it may be even easier to see why it's problematic -- what is a "String of Strings"?).

So, even if we say `fill2D`, `fill3D` etc don't make sense for many subclasses of Collection while they do apply to SequenceableCollection, it only pushes the problem down a level because they don't make sense for *every* subclass.

So my suggestion here is to work out a best practice for superclass methods that can't be supported in certain subclasses, and then use it. I think the best practice looks like:

1. `shouldNotImplement` in the subclass (e.g. `+ RawArray { *fill2D { this.shouldNotImplement(thisMethod) } }` changes the messaging to "ERROR: 'Meta_RawArray-fill2D' Message not valid for this subclass: Meta_FloatArray" and then the meaning is clear: it isn't supported and won't be in the future (where "Primitive '_ArrayAdd' failed" does indeed sound like something is supposed to work but doesn't).

2. Mark the method selectors as private in the help system, so that they do not appear and users aren't tempted to try them.

**BUT** for no. 2 -- I just tested adding this to RawArray.schelp:

```
CLASSMETHODS::
private:: fill2D, fill3D
```

... and it doesn't affect the list of inherited methods at all.

So we probably need to log this as a separate feature request. There should be a way to hide inherited methods from subclass help files, but currently there is no way.

telephon:
> subclasses do not implement all superclass interface.

Yes -- and the issue report is correct to point out that the error messages, and the presence of the method selectors in help files, are misleading.

**Comment by JordanHendersonMusic** [comment]
Should this be closed now?

On one hand, in object-oriented programming principles all parent classes should be substitutable with a child (Liskov), but on the other, this is such a pervasive feature in supercollider that fixing it would require an entire class rewrite. Is this a fundamental design limitation/feature of growing over 20 years, or is it something that should or even could be changed?

**Comment by cdbzb** [comment]
I think you can close as the only practical response is now in #5535.
