### ISSUE TITLE
Supernova cannot set thread affinity on Windows

### ISSUE THREAD

**Issue by bla3kw3b** [supercollider/supercollider#5540]
## Environment

* SuperCollider: 3.12.0 x64 WinZip

* Windows 10 Pro 
* Version: 10.0.19042 
* Build 19042

* Intel(R) Core(TM) i7 CPU       
* L 620  @ 2.00GHz, 2000 Mhz, 
* 2 Core(s), 4 Logical Processor(s)

## Steps to reproduce
```
(((
    (
        (
            (
                Server
            )
            .supernova
        )
        .default // pure default
    )
    .options_
    (
        ServerOptions ( )

        .maxSynthDefs_(2 ** 8)

        .maxNodes_(2 ** 10)

        .memSize_(2**18)
    )
    .boot
)))
```
## Expected vs. actual behavior
Expected no warnings... have never seen before and did not experience in 3.12.0 rc2

Server seems to be running boot successfully despite everything... have yet to test or determine any changes in server performance.

All `s.options` are default values except where clearly visible... I have never altered `.maxLogins`

After boot, a quick check still returns `1` for `s.options.maxLogins`

Code has been tested:

- after OS reboot

- in isolation

- after multiple server quit server killall exit IDE and restart SC cycles

- tested with & without OS networking on (via dedicated hardware killswitch)

- running scide normally and running scide using 'run as administrator' option in windows

- tested without any quarks or extensions

- using default input/output devices

```
compiling class library...
Found 853 primitives.
Compiling directory 'C:\Users\ . . . \SuperCollider\SCClassLibrary'
Compiling directory 'C:\ProgramData\SuperCollider\Extensions'
Compiling directory 'C:\Users\ . . . \AppData\Local\SuperCollider\Extensions'
numentries = 835291 / 12386250 = 0.067
5505 method selectors, 2250 classes
method table size 13404192 bytes, big table size 99090000
Number of Symbols 12296
Byte Code Size 369084
compiled 329 files in 1.97 seconds

Info: 2 methods are currently overwritten by extensions. To see which, execute:
MethodOverride.printAll

compile done
localhost : setting clientID to 0.
internal : setting clientID to 0.
Class tree inited in 0.04 seconds


*** Welcome to SuperCollider 3.12.0. *** For help press Ctrl-D.
SCDoc: Indexing help-files...
SCDoc: Indexed 1360 documents in 3.25 seconds
-> localhost
Booting server 'localhost' on address 127.0.0.1:57110.
Supernova booting
Available Audio Devices:
0: MME : Microsoft Sound Mapper - Input (2 ins, 0 outs)
1: MME : Stereo Mix (Realtek High Defini (2 ins, 0 outs)
2: MME : Microsoft Sound Mapper - Output (0 ins, 2 outs)
3: MME : Speakers (Realtek High Definiti (0 ins, 2 outs)
4: Windows DirectSound : Primary Sound Capture Driver (2 ins, 0 outs)
 5: Windows DirectSound : Stereo Mix (Realtek High Definition Audio) (2 ins, 0 outs)
6: Windows DirectSound : Primary Sound Driver (0 ins, 2 outs)
7: Windows DirectSound : Speakers (Realtek High Definition Audio) (0 ins, 2 out
 8: Windows WASAPI : Speakers (Realtek High Definition Audio) (0 ins, 2 outs)
9: Windows WASAPI : Stereo Mix (Realtek High Definition Audio) (2 ins, 0 outs)
        10: Windows WDM-KS : Stereo Mix (Realtek HD Audio Stereo input) (2 ins, 0 outs)
        11: Windows WDM-KS : Speakers (Realtek HD Audio output) (0 ins, 2 outs)
        12: Windows WDM-KS : Microphone (Realtek HD Audio Mic input) (2 ins, 0 outs)

        Exception when reading synthdef: Cannot load synth system_env_1_audio: Unit generator  not installed
        Exception when reading synthdef: Cannot load synth system_env_1_control: Unit generator  not installed
        Requested audio devices:
        In: (default)
        Out: (default)

        Selecting default system input/output devices

        Opening audio devices:
        In: MME : Stereo Mix (Realtek High Defini
            Out: MME : Speakers (Realtek High Definiti
                Sample rate: 44100.000
                Latency (in/out): 0.026 / 0.183 sec
                Audio devices opened successfully
                Supernova ready
                Warning: cannot raise thread priority
                Warning: cannot set thread affinity of audio helper thread
                Warning: cannot set thread affinity of main audio thread
                Requested notification messages from server 'localhost'
                localhost: no maxLogins info from server process.
                localhost: keeping clientID (0) as confirmed by server process.
                
                Shared memory server interface initialized
```

```
// as a final check...
supernova <> internal // no warnings
scsynth <> internal // no warnings
scsynth <> local // no warnings
supernova <> local // same warning
```

Supernova ready
Warning: cannot raise thread priority
Warning: cannot set thread affinity of audio helper thread
Warning: cannot set thread affinity of main audio thread
Requested notification messages from server 'localhost'
localhost: no maxLogins info from server process.
localhost: keeping clientID (0) as confirmed by server process.
Shared memory server interface initialized
```

**Comment by bagong** [comment]
I am not sure this is a bug (the warning has been there for ages, I think the issue was already discussed in Tim's times). I have a very limited understanding, but I think it means which priority the scsynth process should get compared to others. You can actually set process priority on the command line and even in the Windows Task manager. If it were set by SC, the question would still be which priority to set, as different users might have different priorities.

**Comment by dyfer** [comment]
Thanks for the report. Few comments:
Supernova hasn't been available in Windows builds for some time (since 3.8.0), so this is not something that's been widely tested in recent years. I am seeing the same on my Windows machine and I was wondering about that.

As for thread priority, I don't know why that fails. For reference it's called from [here](https://github.com/supercollider/supercollider/blob/develop/server/supernova/server/server.cpp#L227-L275) and the actual implementation is [here](https://github.com/timblechmann/nova-tt/blob/55da93741e76632579b63004d3378139e32d634f/nova-tt/thread_priority_win32.hpp)

With thread affinity (AFAIU that means assigning threads to the available cores so that they're not moved from core to core by the OS), it seems it's actually [not implemented on Windows](https://github.com/timblechmann/nova-tt/blob/55da93741e76632579b63004d3378139e32d634f/nova-tt/thread_affinity.hpp#L74-L81), IIUC. I don't know why, this would be a question to @timblechmann

**Comment by bla3kw3b** [comment]
Interesting... Thanks for the input.

I did update the build for Windows 10 Pro to 20H2 over a week ago, and so that may be the issue.

So far, it seems the issue only occurs with Supernova, the local server, and on Windows 10 (Pro) build 19042, which is also nicknamed 20H2, or the October 2020 update.

Since the warning the never occurred until I installed this update, I can verify that this 20H2 update contains the root of the issue.

Here's another one that must also be linked to this build in particular:

Booting server 'localhost' on address 127.0.0.1:57110.
Server: possible boot delay.
On some Windows-based machines, Windows Defender sometimes delays server boot by one minute.
You can add scsynth.exe and/or supernova.exe *processes* to Windows Defender exclusion list to avoid this delay. It's safe.
<*waits one minute*>
Device options:
  - MME : Microsoft Sound Mapper - Input   (device #0 with 2 ins 0 outs)
  - MME : Stereo Mix (Realtek High Defini   (device #1 with 2 ins 0 outs)
  - MME : Microsoft Sound Mapper - Output   (device #2 with 0 ins 2 outs)
  - MME : Speakers (Realtek High Definiti   (device #3 with 0 ins 2 outs)
  - Windows DirectSound : Primary Sound Capture Driver   (device #4 with 2 ins 0 outs)
  - Windows DirectSound : Stereo Mix (Realtek High Definition Audio)   (device #5 with 2 ins 0 outs)
  - Windows DirectSound : Primary Sound Driver   (device #6 with 0 ins 2 outs)
  - Windows DirectSound : Speakers (Realtek High Definition Audio)   (device #7 with 0 ins 2 outs)
  - Windows WASAPI : Speakers (Realtek High Definition Audio)   (device #8 with 0 ins 2 outs)
  - Windows WASAPI : Stereo Mix (Realtek High Definition Audio)   (device #9 with 2 ins 0 outs)
  - Windows WDM-KS : Stereo Mix (Realtek HD Audio Stereo input)   (device #10 with 2 ins 0 outs)
  - Windows WDM-KS : Speakers (Realtek HD Audio output)   (device #11 with 0 ins 2 outs)
  - Windows WDM-KS : Microphone (Realtek HD Audio Mic input)   (device #12 with 2 ins 0 outs)

Requested devices:
  In:
  - (default)
  Out:
  - (default)

Selecting default system input/output devices

Booting with:
  In: MME : Stereo Mix (Realtek High Defini
  Out: MME : Speakers (Realtek High Definiti
  Sample rate: 44100.000
  Latency (in/out): 0.013 / 0.091 sec
SC_AudioDriver: sample rate = 44100.000000, driver's block size = 64
SuperCollider 3 server ready.
Requested notification messages from server 'localhost'
localhost: server process's maxLogins (1) matches with my options.
localhost: keeping clientID (0) as confirmed by server process.
Shared memory server interface initialized

**Comment by bla3kw3b** [comment]
@dyfer do you also see this as well for thread affinity?

`localhost: no maxLogins info from server process`

**Comment by bla3kw3b** [comment]
I'd also like to add in to this issue that the warning messages for thread affinity (as well as the one minute delay boot) occur regularly, though unpredictably.

I will try uncover which state will more reliably reproduce the message as I go along if I can. 

The last attempt, after rebooting the interpreter from within the IDE, was successful:

```
Booting with:
  In: MME : Stereo Mix (Realtek High Defini
  Out: MME : Speakers (Realtek High Definiti
  Sample rate: 44100.000
  Latency (in/out): 0.013 / 0.091 sec
SC_AudioDriver: sample rate = 44100.000000, driver's block size = 64
SuperCollider 3 server ready.
Requested notification messages from server 'localhost'
localhost: server process's maxLogins (1) matches with my options.
localhost: keeping clientID (0) as confirmed by server process.
Shared memory server interface initialized
```

**Comment by bla3kw3b** [comment]
I believe I was already running build 19042, and the update I installed 
was a bundled feature & security update for that build specifically... but the actual build itself wasn't updated or changed.

I'm going to uninstall each update as I can go along... and at some point I'll be able to verify which one is responsible for triggering the issue.

**Comment by dyfer** [comment]
> localhost: no maxLogins info from server process

I can't remember if I saw that on Windows. BTW `maxLogins` is unrelated to thread affinity or priority. IIRC server should report maxLogins so that we compare that with the requested number. This might indicate an issue with OSC communication (e.g. security settings) but that's a shot in the dark.

**Comment by bla3kw3b** [comment]
I've narrowed it down to a few select possible number of build / security updates that may be the initial environment for triggering the issue... 

I also looked into task manager for supernova, and thread affinity was by default marked for all four processors, and thread priority was set to normal.

I understand that supernova simply requires more refinement on Windows OS... I don't know how much more I can help for this specific issue... I'm think just going to revert to using scsynth for the time being.

```
Opening audio devices:
  In: MME : Stereo Mix (Realtek High Defini
  Out: MME : Speakers (Realtek High Definiti
  Sample rate: 44100.000
  Latency (in/out): 0.026 / 0.183 sec
Audio devices opened successfully
Supernova ready
Warning: cannot raise thread priority
Warning: cannot set thread affinity of audio helper thread
Warning: cannot set thread affinity of main audio thread
Requested notification messages from server 'localhost'
Requested notification messages from server 'localhost'
Requested notification messages from server 'localhost'
Requested notification messages from server 'localhost'
Requested notification messages from server 'localhost'
Requested notification messages from server 'localhost'
Requested notification messages from server 'localhost'
Requested notification messages from server 'localhost'
Requested notification messages from server 'localhost'
Requested notification messages from server 'localhost'
Requested notification messages from server 'localhost'
Requested notification messages from server 'localhost'
Requested notification messages from server 'localhost'
Requested notification messages from server 'localhost'
Requested notification messages from server 'localhost'
Requested notification messages from server 'localhost'
Requested notification messages from server 'localhost'
Requested notification messages from server 'localhost'
Requested notification messages from server 'localhost'
Requested notification messages from server 'localhost'
Requested notification messages from server 'localhost'
Requested notification messages from server 'localhost'
Requested notification messages from server 'localhost'
Requested notification messages from server 'localhost'
Requested notification messages from server 'localhost'
Requested notification messages from server 'localhost'
Requested notification messages from server 'localhost'
Requested notification messages from server 'localhost'
Requested notification messages from server 'localhost'
Requested notification messages from server 'localhost'
Requested notification messages from server 'localhost'
Requested notification messages from server 'localhost'
Requested notification messages from server 'localhost'
Requested notification messages from server 'localhost'
Requested notification messages from server 'localhost'
Requested notification messages from server 'localhost'
Requested notification messages from server 'localhost'
Requested notification messages from server 'localhost'
Requested notification messages from server 'localhost'
Requested notification messages from server 'localhost'
Requested notification messages from server 'localhost'
Requested notification messages from server 'localhost'
Requested notification messages from server 'localhost'
Requested notification messages from server 'localhost'
Requested notification messages from server 'localhost'
Requested notification messages from server 'localhost'
Requested notification messages from server 'localhost'
Requested notification messages from server 'localhost'
Requested notification messages from server 'localhost'
Requested notification messages from server 'localhost'
Requested notification messages from server 'localhost'
Requested notification messages from server 'localhost'
Requested notification messages from server 'localhost'
Requested notification messages from server 'localhost'
Requested notification messages from server 'localhost'
Requested notification messages from server 'localhost'
Requested notification messages from server 'localhost'
Requested notification messages from server 'localhost'
Requested notification messages from server 'localhost'
Requested notification messages from server 'localhost'
Requested notification messages from server 'localhost'
Requested notification messages from server 'localhost'
Requested notification messages from server 'localhost'
localhost: no maxLogins info from server process.
localhost: keeping clientID (0) as confirmed by server process.
localhost: no maxLogins info from server process.
localhost: keeping clientID (0) as confirmed by server process.
localhost: no maxLogins info from server process.
localhost: keeping clientID (0) as confirmed by server process.
localhost: no maxLogins info from server process.
localhost: keeping clientID (0) as confirmed by server process.
localhost: no maxLogins info from server process.
localhost: keeping clientID (0) as confirmed by server process.
localhost: no maxLogins info from server process.
localhost: keeping clientID (0) as confirmed by server process.
localhost: no maxLogins info from server process.
localhost: keeping clientID (0) as confirmed by server process.
localhost: no maxLogins info from server process.
localhost: keeping clientID (0) as confirmed by server process.
localhost: no maxLogins info from server process.
localhost: keeping clientID (0) as confirmed by server process.
localhost: no maxLogins info from server process.
localhost: keeping clientID (0) as confirmed by server process.
localhost: no maxLogins info from server process.
localhost: keeping clientID (0) as confirmed by server process.
localhost: no maxLogins info from server process.
localhost: keeping clientID (0) as confirmed by server process.
localhost: no maxLogins info from server process.
localhost: keeping clientID (0) as confirmed by server process.
localhost: no maxLogins info from server process.
localhost: keeping clientID (0) as confirmed by server process.
localhost: no maxLogins info from server process.
localhost: keeping clientID (0) as confirmed by server process.
localhost: no maxLogins info from server process.
localhost: keeping clientID (0) as confirmed by server process.
localhost: no maxLogins info from server process.
localhost: keeping clientID (0) as confirmed by server process.
localhost: no maxLogins info from server process.
localhost: keeping clientID (0) as confirmed by server process.
localhost: no maxLogins info from server process.
localhost: keeping clientID (0) as confirmed by server process.
localhost: no maxLogins info from server process.
localhost: keeping clientID (0) as confirmed by server process.
localhost: no maxLogins info from server process.
localhost: keeping clientID (0) as confirmed by server process.
localhost: no maxLogins info from server process.
localhost: keeping clientID (0) as confirmed by server process.
localhost: no maxLogins info from server process.
localhost: keeping clientID (0) as confirmed by server process.
localhost: no maxLogins info from server process.
localhost: keeping clientID (0) as confirmed by server process.
localhost: no maxLogins info from server process.
localhost: keeping clientID (0) as confirmed by server process.
localhost: no maxLogins info from server process.
localhost: keeping clientID (0) as confirmed by server process.
localhost: no maxLogins info from server process.
localhost: keeping clientID (0) as confirmed by server process.
localhost: no maxLogins info from server process.
localhost: keeping clientID (0) as confirmed by server process.
localhost: no maxLogins info from server process.
localhost: keeping clientID (0) as confirmed by server process.
localhost: no maxLogins info from server process.
localhost: keeping clientID (0) as confirmed by server process.
localhost: no maxLogins info from server process.
localhost: keeping clientID (0) as confirmed by server process.
localhost: no maxLogins info from server process.
localhost: keeping clientID (0) as confirmed by server process.
localhost: no maxLogins info from server process.
localhost: keeping clientID (0) as confirmed by server process.
localhost: no maxLogins info from server process.
localhost: keeping clientID (0) as confirmed by server process.
localhost: no maxLogins info from server process.
localhost: keeping clientID (0) as confirmed by server process.
localhost: no maxLogins info from server process.
localhost: keeping clientID (0) as confirmed by server process.
localhost: no maxLogins info from server process.
localhost: keeping clientID (0) as confirmed by server process.
localhost: no maxLogins info from server process.
localhost: keeping clientID (0) as confirmed by server process.
localhost: no maxLogins info from server process.
localhost: keeping clientID (0) as confirmed by server process.
localhost: no maxLogins info from server process.
localhost: keeping clientID (0) as confirmed by server process.
localhost: no maxLogins info from server process.
localhost: keeping clientID (0) as confirmed by server process.
localhost: no maxLogins info from server process.
localhost: keeping clientID (0) as confirmed by server process.
localhost: no maxLogins info from server process.
localhost: keeping clientID (0) as confirmed by server process.
localhost: no maxLogins info from server process.
localhost: keeping clientID (0) as confirmed by server process.
localhost: no maxLogins info from server process.
localhost: keeping clientID (0) as confirmed by server process.
localhost: no maxLogins info from server process.
localhost: keeping clientID (0) as confirmed by server process.
localhost: no maxLogins info from server process.
localhost: keeping clientID (0) as confirmed by server process.
localhost: no maxLogins info from server process.
localhost: keeping clientID (0) as confirmed by server process.
localhost: no maxLogins info from server process.
localhost: keeping clientID (0) as confirmed by server process.
localhost: no maxLogins info from server process.
localhost: keeping clientID (0) as confirmed by server process.
localhost: no maxLogins info from server process.
localhost: keeping clientID (0) as confirmed by server process.
localhost: no maxLogins info from server process.
localhost: keeping clientID (0) as confirmed by server process.
localhost: no maxLogins info from server process.
localhost: keeping clientID (0) as confirmed by server process.
localhost: no maxLogins info from server process.
localhost: keeping clientID (0) as confirmed by server process.
localhost: no maxLogins info from server process.
localhost: keeping clientID (0) as confirmed by server process.
localhost: no maxLogins info from server process.
localhost: keeping clientID (0) as confirmed by server process.
localhost: no maxLogins info from server process.
localhost: keeping clientID (0) as confirmed by server process.
localhost: no maxLogins info from server process.
localhost: keeping clientID (0) as confirmed by server process.
localhost: no maxLogins info from server process.
localhost: keeping clientID (0) as confirmed by server process.
localhost: no maxLogins info from server process.
localhost: keeping clientID (0) as confirmed by server process.
localhost: no maxLogins info from server process.
localhost: keeping clientID (0) as confirmed by server process.
localhost: no maxLogins info from server process.
localhost: keeping clientID (0) as confirmed by server process.
localhost: no maxLogins info from server process.
localhost: keeping clientID (0) as confirmed by server process.
Requested notification messages from server 'localhost'
localhost - already registered with clientID nil.
localhost - handling login request though already registered - 
localhost - notify response did not contain already-registered clientID from server process.
Assuming all is well.
node id 1 already in use
node id 1 already in use
node id 1 already in use
node id 1 already in use
node id 1 already in use
node id 1 already in use
node id 1 already in use
node id 1 already in use
node id 1 already in use
node id 1 already in use
node id 1 already in use
node id 1 already in use
node id 1 already in use
node id 1 already in use
node id 1 already in use
node id 1 already in use
node id 1 already in use
node id 1 already in use
node id 1 already in use
node id 1 already in use
node id 1 already in use
node id 1 already in use
node id 1 already in use
node id 1 already in use
node id 1 already in use
node id 1 already in use
node id 1 already in use
node id 1 already in use
MIDI: device 0 3 1696039856  (Microsoft GS Wavetable Synth)
Shared memory server interface initialized
Interpreter has crashed or stopped forcefully
```

**Comment by dyfer** [comment]
Thanks @bla3kw3b 

> I also looked into task manager for supernova, and thread affinity was by default marked for all four processors, and thread priority was set to normal.

As for thread affinity - it makes sense that it's using all processors, AFAIU. IIUC the idea is to prevent the OS from moving the threads between cores, but I might be wrong. In any case, this seems not to be implemented on Windows right now.

We probably want a higher priority, but this should only be for the DSP threads, so I don't know how to check for that exactly. As established earlier, elevating priority, although implemented, seems to fail

> I understand that supernova simply requires more refinement on Windows OS... I don't know how much more I can help for this specific issue... I'm think just going to revert to using scsynth for the time being.

I'd encourage you to work with supernova (for non-critical, i.e. non-real-time-performance work) so that we have a better idea how it performs. It would be good to know how it performs, especially compared to scsynth.

**Comment by Spacechild1** [comment]
> Warning: cannot set thread affinity of audio helper thread
> Warning: cannot set thread affinity of main audio thread

It is definitely possible on Windows to pin a thread to a CPU core (see https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-setthreadaffinitymask). It's just that `nova-tt` doesn't implement it.

> Warning: cannot raise thread priority

I think there's a bug in the code:

https://github.com/supercollider/supercollider/blob/8ff17affaf821ea3800b670de6762d1c0afde125/server/supernova/server/server.cpp#L266

I guess this should rather be `if (!success) { ... }`

**Comment by bagong** [comment]
Maybe @sonoro1234 might be interested in the issue too...

**Comment by dyfer** [comment]
> I guess this should rather be `if (!success) { ... }`

That whole block is confusing, between all the ifdefs that are there... are you sure this is the issue?

**Comment by sonoro1234** [comment]
I did some work some time ago. It can be found at https://github.com/supercollider/supercollider/issues/3568

I did some corrections to server.cpp related to `success` above and also some modifications to nova-tt to have thread affinity for win32.

My conclusions were that performance got worse!!

**Comment by Spacechild1** [comment]
> 
> 
> > I guess this should rather be `if (!success) { ... }`
> 
> That whole block is confusing, between all the ifdefs that are there... are you sure this is the issue?

It might look a bit confusing at first, but the general pattern is simply "try different things until one succeeds".

In the code in question the jack backend checks if the current thread priority is already real-time. If so, it skips the call to `thread_set_priority` by setting `success` to `true`. Otherwise, we call `thread_set_priority` with the desired priority.

`if (success) ... ` is clearly wrong. It inadvertently skips the call to `thread_set_priority`, so `success` will stay `false` and we get said error message.

**Comment by bla3kw3b** [comment]
Here is a (long) boot log for the first 10 boots after updating the OS.

A copy of this log is at [https://github.com/bla3kw3b/boot-log-21H2/](https://github.com/bla3kw3b/boot-log-21H2/)

No relevant information was omitted, and no statements were made without 100% confidence.

***

Boot log for:

- Windows 10 build 19043 (21H1), released May 2021 (latest build), 
- SC 3.12.0 
- scide 
- supernova 
- local server 

Task manager carefully checked before & after each log,

Windows 10 build 21H2 running with clean restart each time.

code for each boot:

```
(
    (
        (
            Server 
        )
        .supernova
    )
    .default
)
.options_
(
    ServerOptions ( )

    .maxSynthDefs_(2 ** 8)

    .maxNodes_(2 ** 10)

    .memSize_(2**18)
)
.boot
```

A successful boot is denoted as active CPU update values in the ide

Task manager is carefully checked after each log... no processes were found

The first log occurs just after a fresh updated build install


1: 
 ```
Audio devices opened successfully
Supernova ready
Warning: cannot raise thread priority
Warning: cannot set thread affinity of audio helper thread
Warning: cannot set thread affinity of main audio thread
```

Successful boot

2: 
```
-> localhost
Booting server 'localhost' on address 127.0.0.1:57110.
Supernova booting
Server: possible boot delay.
On some Windows-based machines, Windows Defender sometimes delays server boot by one minute.
You can add scsynth.exe and/or supernova.exe *processes* to Windows Defender exclusion list to avoid this delay. It's safe.
Exception when reading synthdef: Cannot load synth system_env_1_control: Unit generator  not installed
Exception when reading synthdef: Cannot load synth system_env_1_audio: Unit generator  not installed
Requested audio devices:
  In: (default)
  Out: (default)

Selecting default system input/output devices

Opening audio devices:
  In: MME : Stereo Mix (Realtek High Defini
  Out: MME : Speakers (Realtek High Definiti
  Sample rate: 44100.000
  Latency (in/out): 0.026 / 0.183 sec
Audio devices opened successfully
Supernova ready
Warning: cannot raise thread priority
Warning: cannot set thread affinity of audio helper thread
Warning: cannot set thread affinity of main audio thread
Requested notification messages from server 'localhost'
***THE PRECEDING LINE REPEATS ANOTHER 45 TIMES*** 
localhost: no maxLogins info from server process.
localhost: keeping clientID (0) as confirmed by server process.
***THE PRECEDING LINE REPEATS ANOTHER 25-30 TIMES*** 
Requested notification messages from server 'localhost'
localhost - already registered with clientID nil.
localhost - handling login request though already registered - 
localhost - notify response did not contain already-registered clientID from server process.
Assuming all is well.
node id 1 already in use
***THE PRECEDING LINE REPEATS ANOTHER 26 TIMES*** 
Shared memory server interface initialized
```
Successful boot 

For all of the following boot attempts:
- Networking is turned off via hardware killswitch

3: 
```
Booting server 'localhost' on address 127.0.0.1:57110.
Server 'localhost' exited with exit code 1.
```
Failed boot attempt -> Task manager shows no servers -> no attempt made to kill servers

4: 
```
Booting server 'localhost' on address 127.0.0.1:57110.
Server 'localhost' exited with exit code 1.
```
Failed boot attempt -> Task manager shows no server -> Server.killAll ran from scide

Networking is still off, switching networking back to on before restart

Networking will remain on for all following boot attempts... 

5: identical to log # 2... Successful boot

6: 
```
-> localhost
Booting server 'localhost' on address 127.0.0.1:57110.
server 'localhost' already booting
-> localhost
Server 'localhost' exited with exit code 1.
SCDoc: Indexed 1360 documents in 28.13 seconds
-> localhost
Booting server 'localhost' on address 127.0.0.1:57110.
Server 'localhost' exited with exit code 1.
-> localhost
Booting server 'localhost' on address 127.0.0.1:57110.
Server 'localhost' exited with exit code 1.
```
Server was inadvertently booted in process (boot file was evaluated twice ctrl+E)
...failing immediately, then -> Server.killAll (ide) -> boot attempt ctrl + e -> fail -> Server.killAll (ide) -> fail 

Networking is verified to be on... this log highlights a separate but still relevant issue

Battery is almost dead... now carefully checking task manager once more, before performing
complete shutdown.

7:
 ```
-> localhost
Booting server 'localhost' on address 127.0.0.1:57110.
Server 'localhost' exited with exit code 1.
```
// Server.killAll (ide) ->
```
-> localhost
Booting server 'localhost' on address 127.0.0.1:57110.
Server 'localhost' exited with exit code 1.
```
// Server.killAll (code) ->
```
-> Server
-> localhost
Booting server 'localhost' on address 127.0.0.1:57110.
Server 'localhost' exited with exit code 1.
```
// thisProcess.platform.killAll("supernova.exe") ->

...cannot get supernova to boot with local, trying supernova with internal 

8: 
```
/*
Now returning to this boot log... data for this log was lost due to unexpected shutdown. 

...as I clearly recall, the initial attempt to boot supernova with the internal server... 
after many failed attempts with the local server, took a record breaking 
55-65 seconds to boot... the internal server typically boots in 3-8 seconds
*/
```

9:
```
/*
Data for this log was lost due to unexpected shutdown.. 
I clearly recall testing scsynth, with the local server... exit code 1
*/
```

10: 
```
/*
24 hours have passed since shutdown... 
2 missing logs were added, 
networking is on,
notepad is running this log alongside scide...

Final boot using supernova... with the local, default, server:
*/
compiling class library...
	Found 853 primitives.
	Compiling directory 'C:\Users\bla3kw3b\SuperCollider\SCClassLibrary'
	Compiling directory 'C:\ProgramData\SuperCollider\Extensions'
	Compiling directory 'C:\Users\bla3kw3b\AppData\Local\SuperCollider\Extensions'
	numentries = 835291 / 12386250 = 0.067
	5505 method selectors, 2250 classes
	method table size 13404192 bytes, big table size 99090000
	Number of Symbols 12296
	Byte Code Size 369084
	compiled 329 files in 9.91 seconds

Info: 2 methods are currently overwritten by extensions. To see which, execute:
MethodOverride.printAll

compile done
localhost : setting clientID to 0.
internal : setting clientID to 0.
Class tree inited in 0.06 seconds


*** Welcome to SuperCollider 3.12.0. *** For help press Ctrl-D.
SCDoc: Indexing help-files...
SCDoc: Indexed 1360 documents in 29.76 seconds
-> localhost
Booting server 'localhost' on address 127.0.0.1:57110.
Server 'localhost' exited with exit code 1.
// s.quit
// s.boot
'/quit' message sent to server 'localhost'.
-> localhost
-> localhost
Booting server 'localhost' on address 127.0.0.1:57110.
Server 'localhost' exited with exit code 1.
// Server.killAll
// s.boot
-> Server
-> localhost
Booting server 'localhost' on address 127.0.0.1:57110.
Server 'localhost' exited with exit code 1.
```
[https://github.com/bla3kw3b/boot-log-21H2/](https://github.com/bla3kw3b/boot-log-21H2/)

**Comment by bla3kw3b** [comment]
After log six, there was a shutdown, a brief charging period, and then I decided to continue working, despite the low battery, and after fresh OS startup, log numbers seven, eight, and nine were performed back to back...while writing the logs, the battery died and after 24 hours plus a full charge, I discovered only the information from log number seven was saved... just so everything makes sense as far as the timeline.

I was very careful not to make any mistakes, and I think I made it fairly clear, that while testing supernova on the latest OS build, I managed to somehow damage the boot process and render the local server entirely disabled / unreachable.

There was never any sign of the process in Task Manager... and at one one point, during the next day or following morning, I made another attempt... still with `exit code 1`.

24 hours later (according to the timeline... it's been ***~60 hours*** since the server first crashed) and after after several heavy work cycles, with multiple startup & full shutdowns, and using applications other than SC, I considered doing a full networking reset, and decided to perform one final check, and was finally achieved a successful boot with the local server... using scsynth, and not supernova.

```
-> localhost
Booting server 'localhost' on address 127.0.0.1:57110.
Server: possible boot delay.
On some Windows-based machines, Windows Defender sometimes delays server boot by one minute.
You can add scsynth.exe and/or supernova.exe *processes* to Windows Defender exclusion list to avoid this delay. It's safe.
***
SuperCollider 3 server ready.
Requested notification messages from server 'localhost'
localhost: server process's maxLogins (1) matches with my options.
localhost: keeping clientID (0) as confirmed by server process.
Shared memory server interface initialized
```

**Comment by bla3kw3b** [comment]
To end this, I just ran `s.quit` `Server.supernova` `s.boot` and was able to achieve at a record lightning speed of less then 3 seconds... still with:
```
Supernova ready
Warning: cannot raise thread priority
Warning: cannot set thread affinity of audio helper thread
Warning: cannot set thread affinity of main audio thread
Requested notification messages from server 'localhost'
localhost: no maxLogins info from server process.
localhost: keeping clientID (0) as confirmed by server process.
Shared memory server interface initialized
```
Successful boot.
