### ISSUE TITLE
Many meters we have.

### ISSUE THREAD

**Issue by danielmkarlsson** [supercollider/supercollider#5545]
## Environment

* SuperCollider version: 3.12
* Operating system: Mac OS 10.13.6

## Steps to reproduce

Press Cmd+M more than once. 
Move a meter. 
See! 
More than one meter.

## Expected vs. actual behavior

I dare to dream of a world where SuperCollider does not open up more than one server meter. 
Instead SC would show me the one I already have open when I press Cmd+M.

**Comment by capital-G** [comment]
This is not too hard to do - I proposed a change

https://github.com/supercollider/supercollider/pull/5549

You can try this out manually by changing the lines in your `QWindow.sc` file.

I am unsure if something drastic like this would get approval as Window is used a lot, also in external code.
The identification of windows would be done through their given names.

**Comment by danielmkarlsson** [comment]
I have followed the discussion over at https://github.com/supercollider/supercollider/pull/5549 and I am rooting for you and I really hope that you can find a way to navigate the different concerns that folks have in that thread. 

My life has changed a lot for the better as a direct consequence of coming into contact with SuperCollider. I am now at the point where I feel that most folks lives would be improved in some way by working with SuperCollider. I often find myself getting very excited when I talk to people I meet about SuperCollider. I want new users to get the sense that SuperCollider is a piece of software that behaves well, and that it can be trusted. This many meters thing inevitably comes up, and it surprises new users. I then have a strange, mixed emotion where one component is something resembling embarrassment. I make apologies and cross my fingers that some day, someone will care enough to try to fix this. For the good of the community.
