### ISSUE TITLE
SCIDE Syntax Highlighting (screenshot/overview)

### ISSUE THREAD

**Issue by bla3kw3b** [supercollider/supercollider#5551]
SC: ***3.12.0***

This issue is opened for general discussion or comments regarding to 
classifications of syntax type labeling & definitions, etc.

It's open for general reference, in case anyone is doing work in this area in the future.

More specifically:

-  `.keywordWarnings` is a Boolean instance method, and should be deprecated & moved to `LanguageConfig` as `.keywordWarnings` & `.keywordWarnings_`

- There appear to be multiple mistakes across the documentation for `SCDocEntry.keywords` ... the results of indexing all `.keywords` across the documentation ( 3.12 ) can be seen in the details below.

- There is a subtle ambiguity regarding the term *`keyword`* across the entire language & documentation. (    IMO this is:
    -  most pertinent regarding next major version 
    - fairly trivial in current 
    - still should be logged    )

**Comment by madskjeldgaard** [comment]
I'm not sure I understand the purpose of this discussion - what are we discussing exactly? Could you elaborate a bit?

Anyway, my 2 cents: I think using tree-sitter is the future. This allows advanced syntax highlighting and is already in use in neovim https://github.com/madskjeldgaard/tree-sitter-supercollider

I personally won't invest in adding this to SCIDE but if anyone wants to add tree-sitter support I suppose it wouldn't be too difficult with the grammar already out there.

**Comment by dyfer** [comment]
I'm also not clear on what is the purpose of this issue. @bla3kw3b could you clarify?

**Comment by bla3kw3b** [comment]
It's open for general reference, in case anyone is doing work in this area in the future

There seems to be a bug in SCDocEntry.keywords, across the documentation, and there is also the ambiguity of the term keyword, across the language.

Nothing needs to be fixed immediately, and all concerns raised in this thread are subtle, while perhaps dead last in terms of of urgency... still concerns nonetheless. (`.keywordWarnings` should really be in `LanguageConfig`, instead as a Boolean instance method)

This started as a question in the issue about self-referencing variables, and someone recommend that it should be a separate issue.

While ***`this`*** belongs to the same class of syntax as ***`thisThread`*** *&* ***`thisProcess`***, etc. it's highlighted as a 'keyword' ... while 'keywordArguments' are highlighted as 'Symbols' ... ***this*** is listed as a 'Related Keyword' in Main, but ScDocEntry.keywords doesn't reflect this at all... this seems to be the initial point of confusion that started this thread as a question, but in the end, it still serves mostly as a reference.

**Comment by dyfer** [comment]
Thanks @bla3kw3b that makes more sense.
I think it would be helpful if the first post contained most information from your last comment, indicating that this issue is used for tracking issues with the IDE's syntax highlighting.

It would be useful if you listed the issues mentioned as a list, maybe with checkboxes (and, if possible, update it as more issues are reported in the thread), so that it's easier to follow progress of the work on this (I've done this in https://github.com/supercollider/supercollider/issues/5359 for example). I'd also personally prefer to either remove the screenshot or hide it in a `<detatails>  </details>` section, as it takes a lot of space and does not IMO provide a lot of concrete information.

**Comment by bla3kw3b** [comment]
> <details> </details> 

Done. #5551

**Comment by JordanHendersonMusic** [comment]
I'm going to move this to a discussion because this isn't an issue.
