### ISSUE TITLE
Interval is a subclass of Collection not SequenceableCollection

### ISSUE THREAD

**Issue by rd--** [supercollider/supercollider#5552]
## Environment

* SuperCollider version: 3.11.2
* Operating system: debian

I'm not sure if this is a bug?  Perhaps there's an excellent reason it's this way.  I think in Smalltalks it's normally somewhere in Collection-Sequenceable.  As it is:

````
4 * 1.to(10) // error
````

If it is moved to SequenceableCollection or ArrayedCollection we get:

````
4 * 1.to(9) == [4, 8, 12, 16, 20, 24, 28, 32, 36]
`````

I know about `(1..9)` and `1.series(nil,9)` but it'd be nice if `to` worked as well.

Would it be possible to move it?

Also, while there, would it be possible to add:

````
    asUGenInput {
        ^this.asArray.asUGenInput;
    }
````

Bests

**Comment by telephon** [comment]
I think `Interval` should be a subclass of `AbstractFunction`, or at least behave like functions when it comes to math. To me, the whole point of an interval seems to be to provide lazy values for the `do`  and the `at` et al messages.

To illustrate, just for `at`:
```


(
f = { |start, end, step|
	var size = end - start div: step + 1;
	size.postln;
	{ |index|
		if(index < 0 or: { index >= size }) 
		{ 
			nil 
		} {
			step * index + start
		}
	}
};
i = f.value(0, 9, 1)
)

i.(5)

j = i * 3;

j.(5)
```

**Comment by rd--** [comment]
Yes, you're correct of course, and I was being lazy (and in being lazy making Interval strict!)...

Adding:

````
	+ {arg number; ^ (start + number).to(end + number, step)}
	- {arg number; ^ (start - number).to(end - number, step)}
	* {arg number; ^ (start * number).to(end * number, step * number)}
````

Gives you:

````
1.to(9) + 1 == Interval(2, 10, 1) // true
1.to(9) - 1 == Interval(0, 8, 1) // true
1.to(9) * 3 == Interval(3, 27, 3) // true
(1.to(9) * 3).asArray == (3,6..27) // true
(0.to(9) * 3).at(5) == 15 // true
````

These are the Squeak definitions.  They don't give `*`, I wonder why not?  Is there any other math you'd want?

`/` would makes sense (if `*` does), but `0.5.to(4.5,0.5)` is an error since `to` is defined at `Integer`.

Perhaps initially SC could add these three (two?) methods and `asUGenInput` and leave Interval under Collection?

Moving to SequenceableCollection gives all the other non interval math, which is maybe not a good idea...

````
1.to(9) ** 2 == [1,4,9,16,25,36,49,64,81] // true
````

I don't know.

**Comment by rd--** [comment]
Ps. Squeak has `to:by:` defined at `Number`

````
(0.5 to: 4.5 by: 0.5) asArray "=> #(0.5 1.0 1.5 2.0 2.5 3.0 3.5 4.0 4.5)"
````

Perhaps if SC did make the above changes to `Interval` it could move `to` to `Number` at the same time, and then it could add `\` at `Interval` as well?

**Comment by telephon** [comment]
Hm, I am unsure.

The mathematical definition works differently:

>The intervals are precisely the connected subsets of R {\displaystyle \mathbb {R} } \mathbb {R} . It follows that the image of an interval by any continuous function is also an interval. This is one formulation of the intermediate value theorem. 

https://en.wikipedia.org/wiki/Interval_(mathematics)

If we really want to change the implementation, then it should have some conceptual and practical benefit.
I can imagine that some lazy object that represents an array but tries to stay a description as long as possible might be interesting. But I guess it will also be hard to use and hard to explain.

```


LazyArray : AbstractFunction {
	var <>func, specialValues;
	
	*fill { |func|
		^super.newCopyArgs(func, SparseArray.new)
	}
	
	at { |index|
		^specialValues.at(index) ? func
	}

	put { |index, item|
		specialValues.put(index, item)
	}
	
	composeUnaryOp { arg aSelector;
		^this.class.fill(function.composeUnaryOp(aSelector), specialValues.perform(aSelector))
	}
		
	// etc.
		
	
}
```

But apart from this: to do a larger change, we'd need some real benefits of using Intervals in math, I think.

**Comment by rd--** [comment]
Ah yes, but ST-80 used the name `Interval` for something a bit different...

> ...the class of collections called Intervals consists of finite arithmetic progressions.

And yes, a LazyArray could be interesting!  But it's too difficult for me think through at the moment.

I'd still like to make `Interval` be a bit more like in ST-80.

Do you think that would be ok?

I could make a patch that adds `+-*/` and moves `to` to `Number`?

(I'm still a bit worried why `*/` aren't in Squeak, are they not always `Intervals`?)

Do you think `Interval` could be safely moved to `SequenceableCollection`?

And is adding `asUGenInput` agreeable?

Or should I just write `1.to(9).asArray` and leave Interval alone?

Best,
Rohan

Ps. I wonder why `asUGenInput` is at `Array` and not `SequenceableCollection`?

**Comment by telephon** [comment]
> I could make a patch that adds +-*/ and moves `to` to Number?

Yes, that would be good.

> Do you think Interval could be safely moved to SequenceableCollection?

not sure about that

> And is adding asUGenInput agreeable?

yes, it is unproblematic

> Or should I just write 1.to(9).asArray and leave Interval alone?

Hard to say. :)

> Ps. I wonder why asUGenInput is at Array and not SequenceableCollection?

I don't think there is a good reason.

**Comment by rd--** [comment]
Apologies slowness.  I tried moving Interval to SequenceableCollection but it's a bit awkward in various subtle ways.  I don't know enough SC to do it properly, and I'm not entirely sure that Interval interacts particularly well with `performBinaryOpOnSeqColl`.  Everything else I can just do locally,  so I think it's best to leave the class library alone.  'll close this. 

For the archives, * and / need to special case zero (as below) else the size of the Interval changes, and even so I suspect rounding can make this a little problematic in other cases still.  

Also for the archives, iota as below is another nice way to get by...   

````
SimpleNumber>>
  iota {arg start=0, step=1; ^start.series(start + step, start + (this - 1 * step))}

Interval>>
    * {arg number; ^(number == 0).if({this.asArray * 0},{(start * number).to(end * number, step * number)})}
    / {arg number; ^(number == 0).if({this.asArray / 0},{(start / number).to(end / number, step / number)})}
````

**Comment by telephon** [comment]
Thank you, @rd! 

Btw. the usualy way to do a `iota` is via `Array.iota`.

**Comment by rd--** [comment]
Hello,

Yes!  The iota above is Olin Shivers' variation, the unary form is Array.iota and the ternary form is Array.series.

If, for eccentric reasons, you have an Sc parser that doesn't parse `(i .. k)` or `(i, j .. k)` then `Number>>to` is quite an important part of the namespace!

<https://gitlab.com/rd--/stsc3/-/blob/master/Language/Smalltalk/SuperCollider/Parser.y>

````
(1 .. 9)
1.to(9)
9.iota(1)
9.iota + 1
1.series(nil, 9)
Array.iota(9) + 1

(1, 3 .. 9)
1.to(9, 2)
5.iota(1, 2)
5.iota * 2 + 1
1.series(3, 9)
Array.series(5, 1, 2)
````
