### ISSUE TITLE
Switch away from using AIFF as default recHeaderFormat

### ISSUE THREAD

**Issue by madskjeldgaard** [supercollider/supercollider#5557]
## Motivation

When installing SuperCollider from fresh, it will by deffault recording the server output in the .aiff format unless changed ala `s.recHeaderFormat_("wav")` in a startup file. 

AIFF is a more MacOS centric format and it just doesn't work as well on Linux for example when converting files, importing/exporting from other programs etc. On Linux (and Windows?) users have to intervene to change this default to remedy the situation and I think it should be the other way around - if you want a more platform specific suffix/headerformat it should be something demanding intervention - just my 2 cents.

## Description of Proposed Feature

Change the default to "wav"

## Plan for Implementation

Change this line:
https://github.com/supercollider/supercollider/blob/e4743da23948f6ce1cfe7750273814d0f489cc20/SCClassLibrary/Common/Control/Server.sc#L98

**Comment by RhnSharma** [comment]
I would like to take this one.

**Comment by madskjeldgaard** [comment]
> I would like to take this one.

awesome!
