### ISSUE TITLE
shift-click behaviour, extending selection

### ISSUE THREAD

**Issue by telephon** [supercollider/supercollider#556]
Given a selection from i_0 to i_1. It would be nice if shift-click on an index i_2 smaller than (further up from)  i_0 would extend the selection from the last one i_1 and not from i_0. This allows to extend the selection on both sides. Not essential but nice.

**Comment by brianlheim** [comment]
Pinging. Can we find consensus here @jamshark70 @telephon?

My preference is for what Julian suggests.
