### ISSUE TITLE
Server.remote does not work as documented: raises an error when options is nil

### ISSUE THREAD

**Issue by dreinsch** [supercollider/supercollider#5568]
## Environment

* SuperCollider version: 3.12 (since https://github.com/supercollider/supercollider/commit/c1eb86075c77293c29b9cb6020f06d7e5132f9fb)
* Operating system: should occur on all systems, tested on Windows 10
* Other details (Qt version, audio driver, etc.): -

## Steps to reproduce

```supercollider
~remote = Server.remote('remote')
```

## Expected vs. actual behavior

expected: remote server gets created even without providing `options`. 
actual: Method raises an error as `options` is nil and has no message `protocol`

```
ERROR: Message 'protocol' not understood.
RECEIVER:
   nil
ARGS:
CALL STACK:
	DoesNotUnderstandError:reportError
		arg this = <instance of DoesNotUnderstandError>
	Nil:handleError
		arg this = nil
		arg error = <instance of DoesNotUnderstandError>
	Thread:handleError
		arg this = <instance of Thread>
		arg error = <instance of DoesNotUnderstandError>
	Object:throw
		arg this = <instance of DoesNotUnderstandError>
	Object:doesNotUnderstand
		arg this = nil
		arg selector = 'protocol'
		arg args = [*0]
	Meta_Server:remote
		arg this = <instance of Meta_Server>
		arg name = 'sc3nb_remote'
		arg addr = nil
		arg options = nil
		arg clientID = nil
		var result = <instance of Server>
	< closed FunctionDef >  (no arguments or variables)
	Interpreter:interpretPrintCmdLine
		arg this = <instance of Interpreter>
		var res = nil
		var func = <instance of Function>
		var code = "~remote = Server.remote('sc3..."
		var doc = nil
		var ideClass = <instance of Meta_ScIDE>
	Process:interpretPrintCmdLine
		arg this = <instance of Main>
^^ ERROR: Message 'protocol' not understood.
RECEIVER: nil

```

solution: create default instance of ServerOptions like described in the [Server.remote docs](https://doc.sccode.org/Classes/Server.html#*remote)

This currently causes a issue in sc3nb https://github.com/interactive-sonification/sc3nb/issues/15. A workaround would be creating the default ServerOptions and providing them to `Server.remote`

Thank you very much for developing SuperCollider!

**Comment by jamshark70** [comment]
The `options` are not the problem here.

It is mandatory to supply a NetAddr to locate the remote server. Your example doesn't -- hence, error.

I think, not a bug.

**Comment by dreinsch** [comment]
The minimal example I provided didn't include the NetAddr. However in the original code of sc3nb we provided a NetAddr.
The workaround commit we currently use to successfully avoid the issue is the following: https://github.com/interactive-sonification/sc3nb/commit/43aa4945ee27289c5dd82e4f10488819969daec5

The code
```SuperCollider
~remote = Server.remote('remote', NetAddr("127.0.0.1", 57110))
```
also fails.

Only following snippets work:

```SuperCollider
~remote = Server.remote('remote', NetAddr("127.0.0.1", 57110), ServerOptions.new)
```
```SuperCollider
~remote = Server.remote('remote', options: ServerOptions.new)
```

And if you look at the `Server.remote` code 
https://github.com/supercollider/supercollider/blob/9885b7e4f78d8220a826964cc3ccf553abc61ee7/SCClassLibrary/Common/Control/Server.sc#L391-L400
You can see that the message `protocol` from the error trace is used on `options` (with `options = nil`) and thus the error `ERROR: Message 'protocol' not understood.
RECEIVER: nil`

Note that the commit https://github.com/supercollider/supercollider/commit/c1eb86075c77293c29b9cb6020f06d7e5132f9fb  introduced the issue just recently in version 3.12. 

While I agree that it might be unusual to create a "remote server" via `Server.remote` without providing a NetAddr it should be perfectly fine as the `Server.remote` code uses the `Server.new` class method where addr has the following documentation "_an optional instance of NetAddr, providing host and port. The default is the localhost address using port 57110; the same as the local server._". This would mean that the "remote server" would simply use the local default server address. This specification of the fallback address should be added to the `Server.remote` documentation.

**Comment by telephon** [comment]
The message `*new` does provide default options. The problem is that this:
```supercollider
if(options.protocol == \tcp) {
			addr.tryConnectTCP({ result.startAliveThread }, nil, 20)
		} {
			result.startAliveThread;
		};
```

should refer to the new instance:

```supercollider
if(result.options.protocol == \tcp) {
			addr.tryConnectTCP({ result.startAliveThread }, nil, 20)
		} {
			result.startAliveThread;
		};
```

The repeated reference to `result` seems to me like the whole part of code should be an instance method.

**Comment by jamshark70** [comment]
Ah, I see... so another thing to include in a fix is a unit test. If we advertise that ServerOptions are optional, then testing should include that scenario.
