### ISSUE TITLE
Building on Mac M1: Could not find a package configuration file provided by "Qt5WebEngine"

### ISSUE THREAD

**Issue by madskjeldgaard** [supercollider/supercollider#5584]
Hi 

This might be me being an absolute newbie at using MacOS, and if so I am very sorry. But I am trying to compile SC on my Mac Mini M1 on MacOS 11.6 and it is not going so well.

At first I spent a long time trying to understand why cmake couldnt find C and CXX compilers (which then turned out to be because I hadnt run `sudo xcode-select --reset` and `sudo xcodebuild -license` to agree to Mac@s terms...) but now my main issue is that qt5webengine doesnt seem to be able to be found. I installed qt5 via homebrew `brew install qt5` and I tried setting the paths as suggested in `brew info qt5` but still no luck. 

Did I miss something obvious here?

```
~/tmp/supercollider/build ☭ cmake -G Xcode -DCMAKE_PREFIX_PATH=`brew --prefix qt` -DSUPERNOVA=ON -DCMAKE_INSTALL_PREFIX=/Applications -DNATIVE=ON ..
-- SuperCollider Version: 3.12.1
-- Building from branch develop, commit hash is 3287b55ed
-- Please specify the build configuration in the next step
-- Compiling with Qt GUI
-- Using bundled boost
-- Using bundled yaml-cpp
-- HIDAPI components:
--     mac
--     hidapi_parser
-- Building with HID support
-- FFT library (scsynth): vDSP
-- Audio API (scsynth): coreaudio
-- Found fftw3f: /opt/homebrew/lib/libfftw3f.dylib
-- FFT library (supernova): FFTW
-- Audio API (supernova): portaudio
-- Found a homebrew install of readline /opt/homebrew/opt/readline
-- Found GNU Readline version 8.1: /opt/homebrew/opt/readline/lib/libreadline.dylib
CMake Error at /opt/homebrew/opt/qt@5/lib/cmake/Qt5/Qt5Config.cmake:28 (find_package):
  Could not find a package configuration file provided by "Qt5WebEngine" with
  any of the following names:

    Qt5WebEngineConfig.cmake
    qt5webengine-config.cmake

  Add the installation prefix of "Qt5WebEngine" to CMAKE_PREFIX_PATH or set
  "Qt5WebEngine_DIR" to a directory containing one of the above files.  If
  "Qt5WebEngine" provides a separate development package or SDK, be sure it
  has been installed.
Call Stack (most recent call first):
  QtCollider/CMakeLists.txt:30 (find_package)
  lang/CMakeLists.txt:184 (include)


-- Configuring incomplete, errors occurred!
See also "/Users/mads/tmp/supercollider/build/CMakeFiles/CMakeOutput.log".
```

**Comment by madskjeldgaard** [comment]
oh and it is MacOS Big Sur 11.6

**Comment by dyfer** [comment]
I can't remember what is the state of QtWebEngine in homebrew qt5 on M1 macs. You can try disabling QtWebEngine (and thus help browser...) in CMake and see if it configures properly.

We haven't ironed out all the issues building on M1. As you probably know, if you build natively on arm, external plugins compiled for intel won't work. Eventually we'll offer "universal" builds but this requires some work.

I have built SC on M1 mac some time ago (thus probably earlier Big Sur, though it likely doesn't matter). Even though I managed to compile it correctly (can't remember what I did exactly, sorry), I had to then manually re-sign all the binaries and the libraries, not sure why. YMMV.

**Comment by scztt** [comment]
When I do:
```
cd "$(brew --prefix qt@5)"
find . -iname "*Qt5WebEngineConfig.cmake*"
```
I see:
```
> ./lib/cmake/Qt5WebEngine/Qt5WebEngineConfig.cmake
```

Does this roughly match what you see (e.g. your prefix path is valid and has the config in the right location)?

**Comment by dyfer** [comment]
I can confirm that homebrew Qt5 on arm macOS does not appear to include QtWebEngine. `find . -iname "*Qt5WebEngineConfig.cmake*"` run in qt folder doesn't return anything. Currently, to build on m1 you need to build without the webengine (and thus without the help system): add `-DSC_USE_QTWEBENGINE=OFF` when running cmake.

However, the resulting build, as generated from the cmake build step, did not run for me originally. I had to re-sign all the binaries, I can't remember how exactly.

If I open the XCode project created by CMake (and allow it to create schemes automatically), I can build and run SuperCollider target in XCode.

**Comment by dyfer** [comment]
Here's the confirmation for the lack of qtwebengine on arm: https://github.com/Homebrew/homebrew-core/blob/master/Formula/qt@5.rb#L119

We'll be able to offer native arm build with the qtwebengine again once we upgrade (i.e. fix deprecations etc) to Qt 6.

**Comment by dyfer** [comment]
Just co clarify for others that might see this:
On M1 we currently need to build SC without the QtWebEngine. When configuring cmake specify ` -DSC_USE_QTWEBENGINE=OFF`, e.g.:
```
cmake -GXcode -DCMAKE_PREFIX_PATH=`brew --prefix qt` -DSC_USE_QTWEBENGINE=OFF
```

**Comment by StratosBichakis** [comment]
The workaround to build for M1 processors without the QtWebEngine doesn't seem to work any more.

**Comment by dyfer** [comment]
@StratosBichakis what do you mean? What is the error you are getting?

**Comment by StratosBichakis** [comment]
Probably, the wrong topic to post that issue. I get multiple Qt errors both in QtCollider and sc_ide. I can build successfully if I disable both from the CMake options. Could share my terminal output if it helps. 

I am using M1 max and Qt v5.15.3
Trying to build the latest develop branch.

**Comment by StratosBichakis** [comment]
This is my config output
```console
-- The C compiler identification is AppleClang 13.1.6.13160021
-- The CXX compiler identification is AppleClang 13.1.6.13160021
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- SuperCollider Version: 3.13.0-dev
-- Building from branch develop, commit hash is 2c104108d
-- Please specify the build configuration in the next step
-- Compiling with Qt GUI
-- Found Pthreads: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/usr/lib/libpthread.tbd  
-- Using bundled boost
-- Using bundled yaml-cpp
-- HIDAPI components:
--     mac
--     hidapi_parser
-- Building with HID support
-- Found homebrew install of libsndfile
-- FFT library (scsynth): vDSP
-- Audio API (scsynth): coreaudio
-- Found a homebrew install of readline /opt/homebrew/opt/readline
-- Found GNU Readline version 8.1: /opt/homebrew/opt/readline/lib/libreadline.dylib
-- Found Qt: /opt/homebrew/opt/qt@5/lib/QtCore.framework/QtCore
-- Compiling with Ableton Link support
-- Compiling with Readline support
-- Building the Qt IDE
-- Found Qt deploy utility: /opt/homebrew/opt/qt@5/bin/macdeployqt
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/stratosbichakis/workspaces/learn/supercollider/build
```

**Comment by dyfer** [comment]
@StratosBichakis please open a new issue for this.

**Comment by dyfer** [comment]
I think it's OK to close this for now.
Currently the solution is to build without QtWebEngine on M1: `-DSC_USE_QTWEBENGINE=OFF`.
Please let me know if you think this should stay open!
