### ISSUE TITLE
Attempting to 'Reboot the Interpreter' will crash the interpreter on Windows

### ISSUE THREAD

**Issue by bla3kw3b** [supercollider/supercollider#5586]
***OS: Windows 10 Pro 21H2***
***SC: 3.12***
***IDE: ScIDE***

Rebooting the interpreter from any context will the interpreter cause to crash *at least* nine times out of ten times.

The past two attempts, while testing another issue, resulted in the same exit code:

```
main: waiting for input thread to join...
main: quitting...
cleaning up OSC
Interpreter has crashed or stopped forcefully. [Exit code: -2147483645]
```

**Comment by jamshark70** [comment]
I'm gonna fold all of these into #5583. We really don't need a ton of issues that are all variants of "interpreter crashed."
