### ISSUE TITLE
Pdef errors inside stream need to .stop.clear to restart

### ISSUE THREAD

**Issue by elgiano** [supercollider/supercollider#5597]
## Environment

* SuperCollider version: 3.12.1
* Operating system: Linux

## Steps to reproduce

```supercollider
Pdef(\play, 'garbage').play;
// ERROR: Message 'playAndDelta' not understood. Then
Pdef(\play).isPlaying
// -> true
Pdef(\play, Pbind(\instrument, \default)).play
// nothing happens
Pdef(\play).stop.clear;
Pdef(\play, Pbind(\instrument, \default)).play;
// now it plays
```

## Expected vs. actual behavior
I would expect Pdefs to stop on errors, or at least to be available for a new definition to take effect immediately. Instead, after an error occurs, Pdefs are left in playing state while their player is no longer running, making new definitions uneffective. Calling `.stop.clear` on the Pdef resets it and makes it ready to work again, but this is a hacky trick considering that the Pdef gives no feedback about its unworkable state: it seems to accept a new definition, but it doesn't play, leaving users quite clueless until they figure out on their own that they have to reset it.

## Proposed fix
Catch errors inside EventStreamPlayer:prNext, and stop the player before throwing them
https://github.com/supercollider/supercollider/blob/0ff1fe45db3dbab937596f42d678112eff104399/SCClassLibrary/Common/Streams/Stream.sc#L486
```supercollider
try {
    nextTime = outEvent.playAndDelta(cleanup, muteCount > 0);
} { |error|
    this.removedFromScheduler;
    error.throw;
};
```

**Comment by telephon** [comment]
Good idea to fix this once and for all in EventStream. So far it is located in `Pprotect` used in `EventStreamPlayer` – I don't know what is wrong there (I am pretty sure it used to work, a long time ago, I should have added precise tests).

**Comment by jamshark70** [comment]
> So far it is located in Pprotect used in EventStreamPlayer...

Pprotect will catch errors thrown while evaluating the pattern's stream, e.g. 

```
Pdef(\x, Pbind(\a, Pfunc { 1 + nil })).play;
```

The problem in elgiano's reproducer is that the provided source is inappropriate (symbol rather than Event). The error occurs outside the control of Pprotect.

I suppose it would be useful if EventStreamPlayer had a way to run arbitrary cleanups upon any error.

Btw @elgiano `protect` would be preferred in the above case.

But... on top of that... the `isPlaying` logic appears to be faulty. After the above:

```
Pdef(\x).isPlaying
-> true

Pdef(\x).player.wasStopped
-> false
```

It looks like this interface might be too complicated and poorly defined. I guess `wasStopped` was added because, at some point, we needed to distinguish between a stream player that ended under its own power versus one that was stopped by user action:

```
t = Task { "done".postln }.play;
t.isPlaying
-> false

t.wasStopped
-> false
```

... but then it's been taken to mean, here, that it stopped for any reason.

Hm...

```
Pdef(\x).player.isPlaying
-> false  // a-HA. That's correct
```

So possibly the bug is in TaskProxy:isPlaying:

```
	isPlaying { ^player.notNil and: { player.wasStopped.not } }
```

This should probably be `^player.notNil and: { player.isPlaying }`.

I can't think of a reason why `wasStopped` was preferred here, when there is a method on the player that directly answers the question being asked.

**Comment by elgiano** [comment]
@telephon @jamshark70 Thanks for looking at this so quickly! And thanks for the explanations, it made me look deeper into the class hierarchy :)

@jamshark70 Here is another case where Pprotect doesn't catch it:
```supercollider
Pdef(\x, Pbind(\finish, { Error('onpurpose').throw })).play
Pdef(\x, Pbind(\instrument, \default)).play // nothing happens
```
Which I think is a decent use case, not like the demo one I made above :) Of course `\callback` would be also affected (like any key associated to a Function instead of a Pfunc).

And thanks, I forgot about `protect`! So maybe my fix would become something like this:
```supercollider
protect {
    nextTime = outEvent.playAndDelta(cleanup, muteCount > 0);
} { |err|
    if (err.notNil) { this.streamError };
};
```

> So possibly the bug is in TaskProxy:isPlaying:
I can see how calling `player.wasStopped.not` could make more sense in this case than `player.isPlaying`. In this example, the first definition fails, but the second starts playing immediately, without even calling `play` another time. After all, the user didn't express a desire to stop playing, it just stopped by mistake:
```supercollider
Pdef(\play, Pbind(\finish, {Error('onpurpose').throw})).play;
Pdef(\play).isPlaying; // -> true
Pdef(\play).player.isPlaying; // -> false
Pdef(\play, Pbind(\instrument, \default)); // plays immediately
```
What do you think?

@telephon 
By the way now that you mention tests, I think it would be a good idea to add a test for precisely this case: can TaskProxy and Pdefs resume playing after an error occurred and a new source was provided (both for in-stream error and others)? I could do this as well.

**Comment by elgiano** [comment]
Hello @telephon and @jamshark70 
I know this is not high priority and life is full of tasks, but I wouldn't like it to end up buried and forgotten, so I was thinking to make a PR with my small fix and a test for it, if you don't have anything against it, or haven't started or planned to work on it.

I would also put aside consideration about semantics of `.isPlaying` and `.wasStopped` for now.

**Comment by telephon** [comment]
Hi @elgiano –  it is an important issue, I really find it very annoying.

> So possibly the bug is in TaskProxy:isPlaying:
> `isPlaying { ^player.notNil and: { player.wasStopped.not } }`
>This should probably be ^player.notNil and: { player.isPlaying }.
>I can't think of a reason why wasStopped was preferred here, when there is a method on the player that directly answers >the question being asked. "I want to know 'are you playing' but I'll ask instead 'did somebody force you to stop'."

The intention of `wasStopped` is that it was stopped externally, not just that it has ended.


I have not much time, got down to the following. It is taken from the `playOnce` method (which is called in `play`).

```supercollider
(
var t = Routine { loop { "started".postln; 0.1.wait; SinOsc.wait; } };
r = PauseStream(
	Pprotect(t, { "pauseStream.streamError".postln; r.streamError }).asStream
);
r.play;
)
r.isPlaying // -> false, correct

(
var t = Tdef(\x, { loop { "started".postln; 0.1.wait; SinOsc.wait; } });
r = PauseStream(Pprotect(t.asStream, { "pauseStream.streamError".postln;  }).asStream);
r.play;
)

r.isPlaying // -> true, incorrect
```


There is also an `asProtected` method to be deprecated. This all looks as if we need to find some time to clean this up.
The best solution would be, in my opinion, if a `PauseStream` would correctly tell that it has stopped when it has thrown an error:

```supercollider
r = Task { loop { 0.1.wait; SinOsc.wait; } }.play;
r.isPlaying // => true
r.streamError
r.isPlaying // => false
```

Then it could all be cleaned up and simplified.

Right now I have not much time unfortunately.

**Comment by telephon** [comment]
OK, here is one more finding. Part of the issue is that `Pprotect` is broken in some cases.

```supercollider
(
var failPattern = Pseq([(play: { "... running".postln }, dur: 0.4), (play: { Error.new.throw })], inf);
Pprotect(failPattern, { "--report the failue --".postln }).play;
)


(
var failPattern = Pseq([(play: { "... running".postln }, dur: 0.4), (play: { SinOsc.foo })], inf);
Pprotect(failPattern, { "--report the failue --".postln }).play;
)

// also the example from the help file is broken
(
var x;
var func = { "an error happened".postln };
a = Pprotect(Pseq([1, 3, 3, Pfuncn({ Error.throw }), 2]), func);
x = Pbind(\degree, a, \dur, 0.5).play;
)
```

**Comment by jamshark70** [comment]
```
(
var x;
var func = { "an error happened".postln };
a = Pprotect(Pseq([1, 3, 3, Pfuncn({ Error.throw }), 2]), func);
x = Pbind(\degree, a, \dur, 0.5).play;
)
```

This is broken because it's throwing Error (the class), not an instance of Error.

`Error.throw` -- no
`Error("ad-hoc error").throw` -- yes

**Comment by elgiano** [comment]
Thanks @jamshark70 and @telephon 
After the discussion in #5620, it seems even more reasonable to fix this in `EventStreamPlayer`, rather than in `PauseStream`, so I pushed a PR.

**Comment by telephon** [comment]
- `throw` will call `thisThread.handleError`, 
- `PauseStream` sets the `Thread `'s instance variable `threadPlayer`
-  so normally, the threadPlayer should be sent the message `streamError` 

This used to work, also for nested threads, but maybe there are cases that were incomplete which bite us now.

**Comment by telephon** [comment]
Here is a suggestion for a fix that is more efficient. If this turns out to be a good solution, I'll see if I can simplify PatternProxy in a separate step.
