### ISSUE TITLE
Most examples in 'examples/GUI examples' do not work

### ISSUE THREAD

**Issue by scztt** [supercollider/supercollider#560]
Nearly none of the examples in 'examples/GUI examples' work out of the box. Some work with trivial modifications. Some invoke objects that are not implemented in GUI.qt

These should be removed, or fixed if they are going to be left in - they're the first thing a new user will try, they should work out of the box.

**Comment by vivid-synth** [comment]
(can we add the "comp: QT GUI" label to this?)

**Comment by snappizz** [comment]
What about #2329? I forgot exactly how it differs/overlaps with #2653
