### ISSUE TITLE
Run Python Script from Supercollider

### ISSUE THREAD

**Issue by PolykarposPolykarpidis** [supercollider/supercollider#5608]
I want to run a Python script from Supercollider.
Then, I want Supercollider received an answer from that script.
How can I do that?

In Google searches I always find the opposite (Python script run Supercollider)

Thank you in advance!

**Comment by markk** [comment]
Another option is for the python script to send data back to SuperCollider using OSC.

```
n = NetAddr("127.0.0.1", 57120);
OSCdef(\test, {|msg, time, addr, recvPort| msg.postln}, '/blah', n);
"python3 script.py".unixCmd;
```

See https://python-osc.readthedocs.io/en/latest/ for one Python OSC implementation. Note this can also be run as an OSC server, so the communication could use OSC in both directions.

**Comment by dyfer** [comment]
I think this issue can be closed now, but feel free to reopen if desired.

For the future -  scsynth.org is a more suitable place for user questions. Github issues are better for bug reports and feature requests.
