### ISSUE TITLE
Add info on bus allocation + LFO mapping in NRT guide

### ISSUE THREAD

**Issue by madskjeldgaard** [supercollider/supercollider#5609]
## Motivation

The Non-Realtime Synthesis guide (https://doc.sccode.org/Guides/Non-Realtime-Synthesis.html) currently doesn't contain much info or examples that make use of busses and synth mapping/lfo mapping. 

## Description of Proposed Feature

Add info ala the examples here:
https://scsynth.org/t/how-to-allocate-busses-in-nrt-mode/4826

**Comment by michelestew** [comment]
Hi can I work on this?

**Comment by madskjeldgaard** [comment]
oo ahad

**Comment by jamshark70** [comment]
The key point that kicked off the scsynth thread ("Bus doesn’t have an allocMsg or newMsg like Buffer for example") is that, even though we use the same word for allocating buses and buffers, there is a difference:

- A buffer doesn't exist in the server until you tell it how big it should be (`/b_alloc`), hence the `allocMsg`, `readMsg` etc. methods.
- All buses *do* exist from the moment the server boots. So there is no need for a bus-allocation message, which means also no need for Bus to have `allocMsg` or such. The bus allocator only gives you an available bus number, but that's the end of it, nothing to do after that.

So you would follow the same pattern as Buffer allocation -- create a temporary server object, and grab bus IDs as `Bus.audio(nrtServer, 2)` etc., and then simply use those IDs in the score.

I'm not sure it requires a very long example. It might even be enough to note that users should not go looking for bus allocation OSC messages.

**Comment by michelestew** [comment]
Ok! Thanks for the explanation. Getting started on it today.

**Comment by michelestew** [comment]
Hello, I am trying to understand this issue a bit more. Where would I be adding this example/extra information? What is the process for updating the documentation?
