### ISSUE TITLE
Cmd+Period doesn't work in Qt GUI windows

### ISSUE THREAD

**Issue by scztt** [supercollider/supercollider#561]
Steps:
1. Start a routine: ```r { inf.do({ ".".postln; 1.wait }) }.play;```
2. Generate an SC window:  ```Window.new.front;```
3. Cmd+period

Result:
Nothing (routine continues)

Expected:
Cmd+period should work the same in the IDE and in SC-generated windows.

**Comment by scztt** [comment]
This has worked fine for a while. Tested in 3.7 alpha and see no problems whatsoever. Close?

**Comment by adcxyz** [comment]
Tested again today, does here on 3.7alpha, 10.10.3. 
So I close this.

**Comment by muellmusik** [comment]
For the future, it would be IAC very helpful to have user configurable menus in sclang, for standalones as well as general use. This should contain CmdPeriod I think. Again if there's a concern about that, it could be removable.
