### ISSUE TITLE
embedInStream makes client unreachable using MIDI

### ISSUE THREAD

**Issue by bla3kw3b** [supercollider/supercollider#5615]
***SC:*** *3.12.1*
***OS:*** *Windows 10 Pro*

This issue is mostly grounded in MIDI & Windows.

The following code will ultimately cause the client to become silent & unresponsive, with only this message in the bottom border of the application window for scide:

*`Error when passing data to the interpreter!`*

```
i = (..127).iter.repeat

;

TempoClock.sched(0, r
	{
		~midi_out.noteOn(0, i.next, choose((5..7)))

		;

		0.01.yield

		;

		127.do{ |n| ~midi_out.noteOff(0, n) }  

		;

		0.01.yieldAndReset 
		
	}
)
```

**Comment by jamshark70** [comment]
I think it's simply that the MIDI operations are taking longer than 0.01 ms. TempoClock will try to keep up with the 10 ms timing but if the operations can't finish in time, then it will always be trying to catch up = lock up the interpreter.

I could reproduce the lockup with 0.01.yield but did not reproduce it with 0.1.yield.

**Comment by jamshark70** [comment]
Would it be ok to close this, with the explanation of overwhelming the scheduler?
