### ISSUE TITLE
RLPFD extension?

### ISSUE THREAD

**Issue by andybru** [supercollider/supercollider#5630]
I can not find the Class RLPFD.
But actually I do not know
what is the difference between a Quark(s) and an extension
and how to install it?

Thanks for help.

## Environment

* SuperCollider version: SuperCollider 3.12.1, Built from branch 'HEAD' [b678713]
* Operating system: Windows 10 -21H2, Buiild 19044.1348, Windows Feature Experience Pack 120.2212.3920.0
* Other details (Qt version, audio driver, etc.): Qt Version 5.15.2.

## Steps to reproduce
var sig = Ndef(\z).ar + WhiteNoise.ar(0.001!2);
RLPFD.ar(sig, ffreq: 440.0, res: 0.0, dist: 0.0, mul: 1.0, add: 0.0)

try to evaluate «Guitar feedback emulation» by nathanielvirgo "http://sccode.org/1-U"

## Expected vs. actual behavior
TB303 Filter Emulation
Source: bhobGens.sc

This filter can be a little quiet, so i often multiply it by 3 or so. Watch out for high frequencies + hi res + hi dist = feedback.

ERROR: Class not defined.
  in interpreted text
  line 2 char 5:

  RLPFD.ar(sig, ffreq: 440.0, res: 0.0, dist: 0.0, mul: 1.0, add: 0.0)

**Comment by geoffroymontel** [comment]
Did you install sc3-plugins ?
https://github.com/supercollider/sc3-plugins

**Comment by andybru** [comment]
Thank you very much for the fast response.
Sorry this was just a false flag of me.
Irritated by the unexpectedly rather complicated plugin installation process.
Somewere I read that Quarks are not Plugins .. but for Quarks exists a visual Installation GUI.
Not for Plugins and I have to manually copy the content directory of the Windows Binary release
[https://github.com/supercollider/sc3-plugins/releases/download/Version-3.11.1/sc3-plugins-3.11.1-Windows-64bit-VS.zip]

The Default installation as only mentioned there in the README.txt in to userExtensionsDir:
    C:\Users\<USERNAME>\AppData\Local\SuperCollider\Extensions

currently the version number 3.11.0 is a little bit irritating in conjunction with the SC version number.

**Comment by jamshark70** [comment]
For future reference: scsynth.org is usually a better place for usage questions. (The github issue tracker is meant primarily for bug reports and feature requests.)

Agreed that it would have been nicer for the online example to indicate where to get RLPFD -- however, that is a community-run site that is not under direct control of SC maintainers.

There have been discussions about how to include server plug-ins in quarks. It isn't obvious how to do that -- just noting that the topic hasn't been ignored.

> currently the version number 3.11.0 is a little bit irritating in conjunction with the SC version number.

Another way to look at it is: for example, Reaper DAW issues a new version 1-3 times every month. Would you expect to update your plug-ins for every DAW release? Most users would not be happy with that.

We need to issue a new release of sc3-plugins when the server's application binary interface changes, which is not often (and should not be often).
