### ISSUE TITLE
Missing documentation on SinOscFB's special frequency modulation behavior

### ISSUE THREAD

**Issue by wolfgangschaltung** [supercollider/supercollider#5641]
## Environment

* SuperCollider version: SuperCollider 3.12.1 (built from branch 'HEAD' [b678713])
* Operating system: macOS 10.14.6
* Other details (Qt version, audio driver, etc.): using built-in audio of MacBook Pro 15" (Intel Core i7 / 2,8 GHz / 16 GB)

## Steps to reproduce

```supercollider
{SinOsc.ar(440*SinOsc.ar(),0,0.1)}.play   // expected sound with SinOsc as carrier
{SinOscFB.ar(440*SinOsc.ar(),0,0.1)}.play // unexpected distorted sound with SinOscFB as carrier
{SinOsc.ar(440*SinOsc.kr(),0,0.1)}.play   // for comparison: same distorted sound with modulator running at .kr
```

## Expected vs. actual behavior
`SinOscFB` does not update incoming frequency modulation values as often as `SinOsc`, thus generating the unexpected distortion. It sounds as if `SinOscFB` updates incoming frequency modulation values only once every block of 64 samples, not for every sample as `SinOsc`, as the sonic result of
FM’ing `SinOscFB.ar` with `SinOsc.ar`
is practically idential to
FM’ing `SinOsc.ar` with `SinOsc.kr`.

The [documentation for `SinOscFB`](http://doc.sccode.org/Classes/SinOscFB.html) does not mention this behavioral deviation from `SinOsc`, which caused user confusion as can be seen in [this](https://scsynth.org/t/noob-how-to-do-classic-dx7-style-operator-feedback/4753/13?u=wolfgangschaltung) and the following post.

Perhaps adding the following sentence to the **Description** of `SinOscFB` would help:
"Please note: As SinOscFB does not update incoming frequency modulation values on every sample, but only once every block of 64 samples, you will notice distortion artefacts at higher frequency modulation frequencies."

**Comment by telephon** [comment]
Thank you. I think it would be good to note that `frequency can be modulated at control rate` (this is not unusual behaviour). Would you like to make a pull request?

**Comment by fmiramar** [comment]
Would it be possible to have `SinOscFB.ar` updating frequency in the same way as `SinOsc.ar` ?

**Comment by wolfgangschaltung** [comment]
Hi @telephon, I am really a newbie in SC in particular (and programming in general), so I don't know how to actually make a pull request. I will read up about it [here](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request) and [here](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests#about-pull-requests) and follow the advice there. Please let me know if there are other sources I should read first.

Please see below for a revised version of the text, which should be added to the **Description** section of `SinOscFB`:

"Please note: The frequency of `SinOscFB` can be modulated at control rate. When trying to modulate the frequency of `SinOscFB` at audio rate, you will notice audible artefacts at higher frequency modulation frequencies. This is due to `SinOscFB` updating incoming frequency modulation values only once every block of 64 samples, instead of updating on every sample (like e.g. `SinOsc`)."

**Comment by wolfgangschaltung** [comment]
@telephon, sorry that it took so long, but now I finally found the time to make my first steps in GitHub and create my first pull request, yeah (where is the excitement emoticon when I need it?):
https://github.com/supercollider/supercollider/pull/5654
Happy holiday season & a happy New Year! / Frohes Fest und guten Rutsch!
