### ISSUE TITLE
Question: Where can I find list of SC environment variables I can set in my configs?

### ISSUE THREAD

**Issue by molleweide** [supercollider/supercollider#5649]
Hi there,

What can I search for to find a list of environment variables that supercollider uses?

In my own personal use case I am using `scnvim` plugin with neovim and there seems to be somekind of env mismatch.
Can I set supercollider enviroment in my dotfiles?

**Comment by telephon** [comment]
This question is better asked in https://scsynth.org/

You can take a look into `Interpreter.sc`
