### ISSUE TITLE
SynthDef.build posthook

### ISSUE THREAD

**Issue by avdrd** [supercollider/supercollider#5656]
## Motivation

[Some quarks](https://refined-github-html-preview.kidonng.workers.dev/supercollider-quarks/autogui/raw/master/Help/SynthDefAutogui.html) are rolling their own `SynthDef.build` posthook by overriding that method because their devs hate depending on SynthDescLib, perhaps because one forgets to `add` their synthdefs manually. In practice, this is a bit problematic because it can result in such quarks [installing outdated versions of SynthDef.build](https://github.com/supercollider-quarks/autogui/issues/4).

I can say I commiserate with that, as I have occasionally forgotten to `add` a new version of SynthDef only to wonder why nothing appears to have changed when I start a Synth on that name.

But for such purposes as standard notification mechanism exists in SC, and it is actually used by SynthDescLib, but alas not by SynthDef, so that doesn't help if you expect fully automatic `add`s or some other kind of post-hook in `SynthDef.build`.

## Description of Proposed Feature

Basically, this is a one-line addition to make `SynthDef.build` call `changed` on its class at the end of a successful build, passing the newly built SynthDef instance as parameter to the notification:

```
+ SynthDef {

	build { arg ugenGraphFunc, rates, prependArgs;
		protect {
			this.initBuild;
			this.buildUgenGraph(ugenGraphFunc, rates, prependArgs);
			this.finishBuild;
			func = ugenGraphFunc;
			this.class.changed(\synthDefBuilt, this); // post-HOOK added
		} {
			UGen.buildSynthDef = nil;
		} ;	
	}
}
```

Interested objects can register themselves the usual way to receive that, e.g.

```
ForgetfulMe {

	classvar <>autoAdd = false;

	*initClass {
	
		Class.initClassTree(SynthDef);
		SynthDef.addDependant(this);
		
		// you probably don't want update to run during sclang boot
		// as that would double-add every std. synth, wasting a bit of time
		StartUp.add {
			{ autoAdd = true; }.defer(2) // too early otherwise
		}
	}
	
	*update { arg obvious, iKnow, synthDefInstance;

		if(this.autoAdd) {
			synthDefInstance.add;
			postln("Auto-added new SynthDef" + synthDefInstance.name)
		}
	}
	
}
```

As rather trivial application, the above will auto-register synthedefs with synthdesclib. I'm not saying this latter class should be added to SC. I'm just giving it as an example that I have used to test that this idea works in practice.

## Plan for Implementation

Pretty trivial. I'll make a PR for that one-liner.

**Comment by jamshark70** [comment]
> this.class.changed(\synthDefBuilt, this);

I agree with this -- it's how I'd have done it. The specific symbol, not sure, "built" doesn't quite roll off the tongue... maybe `\newSynthDef` or `\madeSynthDef`, but the general approach (let interested parties register) is correct.

`this.class` will differentiate, for instance, between SynthDef and ProxySynthDef -- this is probably appropriate, since users generally shouldn't be mucking around directly with NodeProxy internals, but worth noting.

**Comment by avdrd** [comment]
Actually, since sub-classes are different (meta) objects, one needs to register with them explicitly.

```
SynthDef.addDependant(callMe)
```
will not get any calls from `ProxySynthDef.build`!

You need explicitly register interest with the latter as well, i.e. 

```
ProxySynthDef.addDependant(callMe)
```

Whether this is a bug or a feature... it depends.

**Comment by telephon** [comment]
What about `finishedSynthDef` or `synthDefReady`?
