### ISSUE TITLE
String incosistent behaviour in response to .asArray and .as(Array)

### ISSUE THREAD

**Issue by fmiramar** [supercollider/supercollider#5658]
## Environment

* SuperCollider version: 3.12.1
* Operating system: Windows 11

## Steps to reproduce
`String` is not responding in the same way to `.asArray` and `.as(Array)`. 

``` supercollider
("some"++"string").asArray; // -> somestring
("some"++"string").asArray.class; // -> String
("some"++"string").as(Array); // -> [ s, o, m, e, s, t, r, i, n, g ]
("some"++"string").as(Array).class; // -> Array
```

## Expected vs. actual behavior
Although `String` does respond to `.asArray` it is only returning iteself, it should be returning an array of `char`.

**Comment by jamshark70** [comment]
I don't think this is a bug.

`as(Array)` means *always* explicitly build an instance of Array and add the contents into it, one by one.

`asArray` means to convert to an array *if necessary* -- if the receiver is already some type of array, then it will bypass conversion and just return the original form of array.

```
1.asArray
-> [ 1 ]

[1].asArray
-> [ 1 ]

FloatArray[1].asArray
-> FloatArray[ 1.0 ]
```

Note that the last one does not convert the type of array. (But, `List[1].asArray` does strip off the List wrapper and just return `[ 1 ]` as an Array instance... I suppose the explanation here is that List isn't formally an *array* exactly -- it's a wrapper for one -- so asArray may reasonably drop the wrapper.)

In any case, they are different use cases. `as(Array)` is when you have a collection and you want to be certain you will have exactly an Array afterward (also note that `as(Array)` is not guaranteed to behave as you expect if you give it a non-collection: `1.as(Array)` --> `[ 0 ]` *and* `2.as(Array)` --> `[ 0 ]` which I interpret to mean, `aNonCollection.as(Array)` is undefined behavior and should be avoided). `asArray` is when you have something that may or may not be an array *of some variety*, and at the end, you want some type of array without being concerned exactly which type.

String's response to asArray is consistent with that of FloatArray above.

**Comment by fmiramar** [comment]
Thanks, interesting point! 

Investigating further, `Object` help says:

> ## Conversion
> To convert an object of a certain class into a similar object of another class, Object provides a number of methods.
> 
> ### .as(aSimilarClass)
> Returns a similar new Object of a different class.
> ``` supercollider
> [1, 2, 3].as(Set);
> Pwhite(0.0, 1.0, 10).as(Set);
> ```
> ### .asArray
> Returns an Array with the receiver, unless it is an Array already.
> ``` supercollider
> [1, 2, 3].asArray;
> 5.asArray;
> ```

The abstract superclass `RawArray` shows that `FloatArray` and `String` are considered as *arrays*, thus `"string".asArray` is not returning an array because it is already an array (of `Char`s)... 

I do understand the logic of the implementation here, but from a practical and organizational point of view, does it make sense to have `.asArray` implemented at all if it has this behavior? Any relevant and crucial usage were this behavior makes sense? 

As a similar case, `.asInteger` responds in the same way to `Integer` and `Float` which all inherit from the superclass `SimpleNumber`:

``` supercollider
1.asInteger.class //returns Integer
1.0.asInteger.class //returns Integer

[1.0, 1.0].asInteger // returns an array of Integers 
-> [ 1, 1 ]
```

isn't a too messy behavior if we have `.asArray` responding in such a different way then `.asInteger` ?

would it be less confuse if the name of this method was `.asRawArray` instead ?

**Comment by avdrd** [comment]
I would have expeted that

```
("some"++"string").asArray
```

would do the same as

```
("some"++"string").bubble
```

Because

```
("some"++"string").asSymbol.asArray
```

actually does that. But I guess it'd debatable. I've been bitten a few times by stuff like that, i.e. string working differently than Symbol.  And I'm [not the only one](https://github.com/supercollider-quarks/autogui/pull/3).

**Comment by fmiramar** [comment]
also realized that 
``` supercollider 
1.0.as(Integer); // ERROR: Message 'newFrom' not understood.
1.as(Float); // ERROR: Message 'newFrom' not understood.
\a.as(Char); // ERROR: Message 'newFrom' not understood.
```
although `Object` provides this `.as(aSimilarClass)` method. 

Moreover, `.asInt` was deprecated in favor of `.asInteger` #4089  #4015 .

However:
``` supercollider 
[1.0, 2.0].asInteger // -> [ 1, 2 ]
$a.asInteger // -> 97
"a".asInteger // -> 0
[$a, $b].asInteger // ERROR: Message 'asInteger' not understood.
```

One possible solution can be implementing `.as(aSimilarClass)` as a general casting method as it seems to be proposed on `Object` class (although not fully implement) using the optimizations mentioned on #4089  #4015 . 

Another solution can be improving the documentation explaining how casting work in SC. 

Indeed, both seem to be hard work because they will demand a big overview of what is going on throughout the whole language. I guess that small regular upgrades on `.as(aSimilarClass)` seem to be doable.

I do agree that casting in sclang is not as important/crucial as in other languages, but a more homogeneous conversion method would be really helpful for the users and potentially reduce bugs.

**Comment by jamshark70** [comment]
> I do understand the logic of the implementation here, but from a practical and organizational point of view, does it make sense to have .asArray implemented at all if it has this behavior?

Yes.

It absolutely makes sense in a situation where you have some object being passed in, which may or may not be an Array, and you want to be certain to be operating on an Array.

```
(
f = { |something|
	something.asArray.do { |item, i|
		/* here's some stuff */
	}
}
)
```

This idiom appears in literally hundreds of places in the class library. If it were not useful, then developers wouldn't use it... but it's everywhere... it's so much everywhere that I have to conclude that it's commonly useful.

Changing the meaning of `asArray` in SC 3.x would be disastrous. `Class.findAllReferences(\asArray).size` is 446... 446! I thought a few dozen, but... 400+. Imagine going through over 400 places in the class library, to update things that are currently working but which would be broken after changing this method... how many developer hours would be spent on this? (Or, how many bugs would go unfixed by pulling dev attention over to this?)

I do wish to be sensitive to the fact that it is confusing, and to be open to solutions, but as a practical matter, asArray is not going to change in the SC 3.x line.

It might be feasible to discuss a more consistent type conversion semantic for SC 4.

**Comment by fmiramar** [comment]
I understand, it is indeed a quite complex change. I will make a post in SC4 forum discussion about this as a suggestion for the future.

**Comment by rd--** [comment]
Here for the same reason, i.e. "String".asArray.class != Array

I also wonder why Sc does it this way.

St-80 has asArray, and it always answers an Array.

In case there ever is an Sc4, it seems like a nice rule for such a message to follow!

**Comment by jamshark70** [comment]
> Here for the same reason, i.e. "String".asArray.class != Array> > I also wonder why Sc does it this way.I don't recall whether I already said this or not, but..."as array" meaning, take whatever you've got and make an instance of Array from its contents, and the class of the result should be specifically Array -- this is a valid and necessary operation."as array" meaning, if you've already got *some type* of sequenceable collection, then just use it, whatever its class is, but otherwise convert -- this is also a valid and useful operation.Currently the former is written `.as(Array)` and the latter is written `.asArray`.So with the above comment, there are two directions to go with it.If the latter meaning of "as array" is valid and useful, *and* if the method selector `asArray` should be changed to take the first meaning, then we would need a new method selector to handle the second meaning (current meaning of asArray).Otherwise we are talking about removing an operation from SC. This should not be taken lightly!So I'd ask those who are raising questions about this: Do you believe the current meaning of asArray should be deleted from SC? If not, what should its new name be?When put this way, then one might consider that the current situation is actually quite reasonable: there are two distinct operations, which are easily disambiguated with currently available syntax. "If it ain't broke, don't fix it" is a wholly reasonable conclusion in this case.-------- Original message --------From: rd-- ***@***.***>Date: Sun, 7 Aug 2022, 23:21To: supercollider/supercollider ***@***.***>Cc: "H. James Harkins" ***@***.***>, Comment ***@***.***>Subject: Re: [supercollider/supercollider] String incosistent behaviour in response to .asArray and .as(Array) (Issue #5658)
Here for the same reason, i.e. "String".asArray.class != Array
I also wonder why Sc does it this way.
St-80 has asArray, and it always answers an Array.
In case there ever is an Sc4, it seems like a nice rule for such a message to follow!

**Comment by jamshark70** [comment]
Apologies for the failed email formatting in my last reply -- I've edited to make it readable.

**Comment by JordanHendersonMusic** [comment]
Closing because this is a (completely understandable) misunderstanding between `a.as(X)` which converts to the _class_ `X`, and `a.asX` which converts to the _interface_ `X` . Perhaps a new issue or even pr could be opened that make the documentation clearer.
