### ISSUE TITLE
Calling CondVar.wait multiple times from the same routine results in the same routine being ran multiple times on CondVar.signalAll

### ISSUE THREAD

**Issue by avdrd** [supercollider/supercollider#5668]
This is a replication of #5667 using "workflow 1" of CondVar, meaning `while` loop in the caller.

## Environment

* SuperCollider version: 3.12.1
* Operating system: all

## Steps to reproduce

```
(
c = CondVar.new;
t = false; // CondVar only supports "external" tests
r = Routine {
	"Routine started.".postln;
	while {
		postln("t ==" + t);
		t == false // actual test of while
	} {
		"t is false. Routine waiting at CondVar.".postln;
		c.wait; // (t) for 2nd wf
		"Routine resumed from wait.".postln;
	};
	loop {
		"t is true. Routine can do its work.".postln.yield;
	};
})

r.next
// Routine started.
// t == false
// t is false. Routine waiting at CondVar.
// -> wait

r.next
// Routine resumed from wait.
// t == false
// t is false. Routine waiting at CondVar.
// -> wait

t = true;
c.signalAll; // you don't really expect more than one copy of yourself...
// -> a CondVar
// Routine resumed from wait.
// t == true
// t is true. Routine can do its work.
// t is true. Routine can do its work.
```

## Expected vs. actual behavior

So we got the exact same bad result as when using Condition, meaning our routine ran twice.

Someone might argue this can be "fixed" by calling just `signalOne` in this case, but that isn't a feasible approach for fixing something like FlowVar, since it makes no sense for the latter to signal just one of the threads that called `.value` on the FlowVar when latter is set with `.value_`, i.e. the semantics there mandate a signalAll (which is the semantics of `Condition.signal`, currently called by FlowVar, if that needs saying).

**Comment by jamshark70** [comment]
Shouldn't these all be one issue? (Diluting your content means that attention to it is diluted as well.)

The intended use of CondVar is: once you block a thread with it, then you aren't supposed to wake it up manually. To wake it up manually short-circuits the condition = wrong usage.

It's fair to make it safer for the user to make a mistake, but IMO the use case presented here is a mistake.

**Comment by avdrd** [comment]
Closing as a near-duplicate of 5669, which uses the "higher-level" API when it passes a predicate per  https://github.com/supercollider/supercollider/issues/5669#issuecomment-1002902852.
