### ISSUE TITLE
does not detect jack if provided by pipewire-jack-audio-connection-kit-devel

### ISSUE THREAD

**Issue by jwaldmann** [supercollider/supercollider#5678]
[EDIT] not sure about the "bug" label. Still posting the issue in the hope that someone knows a work-around.

## Environment

* SuperCollider version: 3.12.2-rc1
* Operating system: Fedora GNU/Linux
* Other details (Qt version, audio driver, etc.):

```
Package pipewire-jack-audio-connection-kit-devel-0.3.40-1.fc35.x86_64 is already installed.

$ pkgconf jack --cflags
-D_REENTRANT 
$ pkgconf jack --libs
-L/usr/lib64/pipewire-0.3/jack -ljack -ljacknet 
$ pkgconf jack --print-provides
jack = 1.9.17
```

related: https://bugzilla.redhat.com/show_bug.cgi?id=1966869

## Steps to reproduce

```
$ cmake -DSC_QT=OFF -DCMAKE_INSTALL_PREFIX=/opt/supercollider/3.12.2-rc1   ../source-sc-3.12.2-rc1
```

## Expected vs. actual behavior

expected: build from source succeeds

actual:
```
$ cmake -DSC_QT=OFF -DCMAKE_INSTALL_PREFIX=/opt/supercollider/3.12.2-rc1   ../source-sc-3.12.2-rc1
-- The C compiler identification is GNU 11.2.1
-- The CXX compiler identification is GNU 11.2.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- SuperCollider Version: 3.12.2-rc1
-- Building from branch HEAD, commit hash is 38b28f95e
-- Build type defaulting to "RelWithDebInfo"
-- Not compiling SC IDE, because it requires Qt but SC_QT is False
-- Found Pthreads: /usr/lib64/libpthread.a  
-- Using bundled boost
-- Using bundled yaml-cpp
-- HIDAPI components:
--     linux hidraw
-- libudev stable: 1
-- Found UDev: /usr/lib64/libudev.so
--    include: /usr/include
--     hidapi_parser
-- Building with HID support
-- Found Sndfile: /usr/lib64/libsndfile.so  
-- Found X11: /usr/include   
-- Looking for XOpenDisplay in /usr/lib64/libX11.so;/usr/lib64/libXext.so
-- Looking for XOpenDisplay in /usr/lib64/libX11.so;/usr/lib64/libXext.so - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Looking for IceConnectionNumber in ICE
-- Looking for IceConnectionNumber in ICE - found
-- Found fftw3f: /lib64/libfftw3f.so
-- FFT library (scsynth): FFTW
-- Found PkgConfig: /usr/bin/pkg-config (found version "1.8.0") 
-- Checking for module 'jack'
--   Found jack, version 1.9.17
CMake Error at server/scsynth/CMakeLists.txt:43 (message):
  Jack selected as audio API, but development files not found
```

**Comment by dvzrv** [comment]
This is more of a packaging problem on fedora's side in regards to the jack library files though.
`libjack.so` is expected to be located in the global lib namespace for FindJack.cmake to find it:

https://github.com/supercollider/supercollider/blob/cea67fcd49eb899366d6f7252c70157c5bc8b18f/cmake_modules/FindJack.cmake#L43-L56

**Comment by dvzrv** [comment]
That being said: You can modify the `find_library()` call to include your custom `libjack.so` location `/usr/lib64/pipewire-0.3/jack`.

**Comment by jwaldmann** [comment]
Thanks, will try this. - Is SC not using the output of `pkgconf jack --libs`?

**Comment by dvzrv** [comment]
> Is SC not using the output of `pkgconf jack --libs`?

No. [Pkgconfig integration](https://cmake.org/cmake/help/latest/module/FindPkgConfig.html) has historically been a bit weird with cmake (although it has improved over the past years), which is why the custom FindJack.cmake exists (but probably shouldn't anymore by now).

As a sidenote: There are also quite a few projects that do only rely on plain makefiles and attempt to link against libjack.so directly (using `-ljack`), which would also break in this context if not supplying an additional search dir for the linker (e.g. `-L/usr/lib64/pipewire-0.3/jack`).

As background information: Pipewire's jack implementation is supposed to be able to replace jack properly, therefore it should also provide the jack libraries at the appropriate location. On Arch Linux we are also not there yet (and therefore do not provide or support pipewire providing the development files for jack). As soon as https://github.com/jackaudio/jack-example-tools has gotten a release (most likely this month), I plan on changing that though unless upstream thinks this is a bad idea.

**Comment by dvzrv** [comment]
> which is why the custom FindJack.cmake exists (but probably shouldn't anymore by now).

I think I can provide a PR to remove the current implementation and replace it with the builtin FindPkgConfig based implementation (as supercollider only supports cmake >= 3.12.0 anyways).

**Comment by dvzrv** [comment]
@jwaldmann can you check whether https://github.com/supercollider/supercollider/pull/5680 improves this for you?

**Comment by jwaldmann** [comment]
Yes I am checking this now.

**Comment by dvzrv** [comment]
> compilation seems fine, linking gives an error

Ah, my bad. Should have used `JACK_LINK_LIBRARIES` instead of `JACK_LIBRARIES`.
Please try again with the current HEAD of that branch.

**Comment by jwaldmann** [comment]
Works!

**Comment by jwaldmann** [comment]
thank you for handling this quickly, and for explaining related issues.

**Comment by dvzrv** [comment]
> thank you for handling this quickly, and for explaining related issues.

You're welcome! Always happy to remove old code :laughing:

**Comment by patrickdupuis** [comment]
I've been having issues building SC against the Piprewire JACK headers on Fedora 35. I just tested #5680 and was able to run cmake and successfully build SC. 

Previously, I had used this workaround:
```$ cmake -DAUDIOAPI=jack -DJACK_LIBRARY=/usr/lib64/pipewire-0.3/jack/libjack.so ..```

**Comment by dyfer** [comment]
Hello @jwaldmann 
This is an issue, not a PR, so it does not make it into the main branch. The linked PR would (listed close to the top on the right) but I hasn't yet, waiting for a follow up from its author.

**Comment by dvzrv** [comment]
@jwaldmann yeah, I lost track of this. There was a small change still to be made (I think that is now done satisfactory) and should be good to go though!
