### ISSUE TITLE
NdefGui fail with buffer object argument

### ISSUE THREAD

**Issue by redFrik** [supercollider/supercollider#5691]
Calling .gui on a Ndef with a Buffer instance as an argument produces an error.
This affects NdefMixer as well if you happen to click the 'ed' button.

Buffer does not implement rate. Bus and other classes in question do.

## Environment

* SuperCollider version: 3.12.2
* Operating system: macOS

## Steps to reproduce

```supercollider
s.boot;
b= Buffer.read(s, Platform.resourceDir +/+ "sounds/a11wlk01.wav");
Ndef(\test, {|buf| PlayBuf.ar(1, buf, loop:1)*0.2!2}).set(\buf, b).play;
Ndef(\test).gui;  //ERROR: Message 'rate' not understood.
```

## Expected vs. actual behavior

It should not throw an error, but instead display the buffer's bufnum.

## Proposal for fixing

```supercollider
--- a/SCClassLibrary/JITLib/ProxySpace/NodeMap.sc
+++ b/SCClassLibrary/JITLib/ProxySpace/NodeMap.sc
@@ -132,7 +132,9 @@ ProxyNodeMap : NodeMap {
        controlNames {
                var res = Array.new;
                this.keysValuesDo { |key, value|
-                       var rate = if(value.rate == \audio) { \audio } { \control };
+                       var rate = if(value.respondsTo(\rate) and:{
+                               value.rate == \audio
+                       }) { \audio } { \control };
                        res = res.add(ControlName(key, nil, rate, value))
                };
                ^res
```

**Comment by telephon** [comment]
looks like a good solution.

**Comment by redFrik** [comment]
thanks.  made a pull request for it here: #5692 

just wondering if this is a hotspot and the extrra .repondsTo call will slow things down?  probably insignificant but please give it a think.

**Comment by telephon** [comment]
Yes, a little, this is true. But building control names happens within `SynthDef` building, which is relatively slow paced anyhow, no?

**Comment by redFrik** [comment]
yes, in the bigger scope this extra check is nothing.
just wanted us to consider it.

**Comment by discordantseeds** [comment]
any solution?
the error is still present.

**Comment by redFrik** [comment]
I believe it was fixed. Are you sure you are using the development branch?

As per the guidelines, this fix was committed to the development branch and will only be available in the next release of supercollider.

If you need the fix right now - in whatever version of sc you are running - you can create a local .sc file in your Extensions folder with the following override...
```supercollider
+NodeMap {
	controlNames {
		var res = Array.new;
		this.keysValuesDo { |key, value|
			var rate = if(value.respondsTo(\rate) and:{
				value.rate == \audio
			}) { \audio } { \control };
			res = res.add(ControlName(key, nil, rate, value))
		};
		^res
	}
}
```
