### ISSUE TITLE
GitHub has deprecated unauthenticated git:// access

### ISSUE THREAD

**Issue by josiah-wolf-oberholtzer** [supercollider/supercollider#5693]
GitHub has deprecated unauthenticated `git://` access.

This means, for example, that cloning SuperCollider with submodules (i.e. `--recursive` is currently broken in GitHub actions) because the current `.gitmodules` uses `git://` rather than `ssh://` / `https://` / `git@github.com`. 

See: https://github.blog/2021-09-01-improving-git-protocol-security-github/#git-protocol-troubleshooting

To fix, try swapping to `https://`. Users will have to `git submodule sync`. Possibly more, but I haven't tested extensively on my personal fork.

**Comment by dyfer** [comment]
Thanks! I'm about to submit a fix for this.

To clarify: IIUC, after the fix is pulled in, users should update their forks (pull the latest `develop`) and then run `git submodule sync`.

**Comment by josiah-wolf-oberholtzer** [comment]
Yes, I believe those steps are correct. `git submodule sync` worked for me on my local machine and just updating the `.gitmodules` allowed GHA using my SuperCollider fork to continue working.
