### ISSUE TITLE
sclang.exe "No networking: unable to bind udp socket"

### ISSUE THREAD

**Issue by shantih19** [supercollider/supercollider#5698]
## Environment

* SuperCollider version: 3.12.2
* Operating system: Windows 10 20H2 (Build 19042.1466) 64 Bit
* Other details (Qt version, audio driver, etc.): 

## Steps to reproduce

Running sclang.exe, either from the ide or commandline.
Port 52110 was not used by any other process, the error persisted even after system restarts.
sclang.exe was added as exception to Windows Firewall, no change.

## Expected vs. actual behavior

No networking: unable to bind udp socket
compiling class library...
	Found 853 primitives.
	Compiling directory 'C:\Program Files\SuperCollider-3.12.2\SCClassLibrary'
	Compiling directory 'C:\ProgramData\SuperCollider\Extensions'
	Compiling directory 'C:\Users\shant\AppData\Local\SuperCollider\Extensions'
	numentries = 1273592 / 19292208 = 0.066
	5752 method selectors, 3354 classes
	method table size 20674104 bytes, big table size 154337664
	Number of Symbols 14778
	Byte Code Size 434392
	compiled 553 files in 1.74 seconds

Info: 2 methods are currently overwritten by extensions. To see which, execute:
MethodOverride.printAll

compile done
localhost : setting clientID to 0.
internal : setting clientID to 0.
Class tree inited in 0.01 seconds
ERROR: Primitive '_GetLangPort' failed.
Failed.
RECEIVER:
class NetAddr (0000024E3D7A8AC0) {
  instance variables [19]
    name : Symbol 'NetAddr'
    nextclass : instance of Meta_Nil (0000024E32619580, size=19, set=5)
    superclass : Symbol 'Object'
    subclasses : instance of Array (0000024E3A8FD5C0, size=1, set=2)
    methods : instance of Array (0000024E3D7A8C40, size=30, set=5)
    instVarNames : instance of SymbolArray (0000024E3D7A8EC0, size=4, set=2)
    classVarNames : instance of SymbolArray (0000024E3D7A9040, size=1, set=2)
    iprototype : instance of Array (0000024E3D7A8F80, size=4, set=2)
    cprototype : instance of Array (0000024E3D7A9100, size=1, set=2)
    constNames : nil
    constValues : nil
    instanceFormat : Integer 0
    instanceFlags : Integer 0
    classIndex : Integer 195
    classFlags : Integer 0
    maxSubclassIndex : Integer 196
    filenameSymbol : Symbol 'C:\Program Files\SuperCollider-3.12.2\SCClassLibrary\Common\Control\NetAddr.sc'
    charPos : Integer 0
    classVarIndex : Integer 302
}
CALL STACK:
	MethodError:reportError
		arg this = <instance of PrimitiveFailedError>
	Nil:handleError
		arg this = nil
		arg error = <instance of PrimitiveFailedError>
	Thread:handleError
		arg this = <instance of Thread>
		arg error = <instance of PrimitiveFailedError>
	Object:throw
		arg this = <instance of PrimitiveFailedError>
	Object:primitiveFailed
		arg this = <instance of Meta_NetAddr>
	Main:startup
		arg this = <instance of Main>
		var didWarnOverwrite = false
^^ The preceding error dump is for ERROR: Primitive '_GetLangPort' failed.
Failed.
RECEIVER: NetAddr

**Comment by shantih19** [comment]
Error no longer appearing after update to windows version 21H2 (Build 19044.1466), don't know what caused it but it's very likely windows being windows

**Comment by totalgee** [comment]
My machine had done some updates before (yesterday), and today I manually checked and ran another update and rebooted several more times. Eventually, I was able to run SC again, without the socket binding error... Very strange (and worrying).

**Comment by iaremsen** [comment]
The exact same thing just happened to me, if an extra data point helps anyone.

**Comment by RA19** [comment]
I have the same error exactly. And nothing has helped.
Tried removing Hyper V
Stopping firewalls, antivirus, vpns
Connecting slang on different ports manually through windows shell (still fails)
reinstalling SC
downgrading SC

Could someone please help with this?

**Comment by capital-G** [comment]
Maybe some app on your system is already using port 57120, therefore sclang can not claim it and it fails.
Can you try to to start supercollider on a different port? 

You need to open `sclang` in a terminal via e.g. via

```
sclang.exe -a -u 57121
```

Try this out with the next 10 numbers of 57120 and if this always yields the same error it is most likely a security preference within windows.
If it works with 57121 you need to find the application which is using port `57120` (maybe you have already sclang running? look into your task manager)

**Comment by RA19** [comment]
> Try this out with the next 10 numbers of 57120 and if this always yields the same error it is most likely a security preference within windows.

So i tried it out and it gave the same error from 57120 and the next 10 numbers
" No networking: unable to bind udp socket ...""

As for>  python -m http.server 57120 
I get the following (for all the list of ports 57120, 57121 etc)
Serving HTTP on 0.0.0.0 port 57120 (http://0.0.0.0:57120/) ...

If I am understanding correctly, python has no problem allocating to the ports right? so I guess more digging ? :)

**Comment by RA19** [comment]
No one has any idea on this ?

**Comment by giohappy** [comment]
In my case the issue was WSL2 and in particular the reservations of ports for its NATting.

You can check if the SC ports are inside the exclusion range by issuing the following command in a terminal:

`netsh interface ipv4 show excludedportrange protocol=udp`

If the reported ranges include the SC ports, this is the case.

Removing the ports from the exclusion range is not advices, because it might break WSL2 networking.
In my case the solution (usually) is to shutdown WSL, and restart the `HNS` service:

```
wsl --shutdown
Stop-Service hns
Start-Service hns
```

This often lease a new range of exclusion ports. If you're lucky as me the SC port is not anymore in those ranges and `sclang` and `scsynth` can boot bind.

**Comment by giohappy** [comment]
I also found similar solutions in [this comment](https://github.com/supercollider/supercollider/issues/6667#issuecomment-3200162464) (and the following)
