### ISSUE TITLE
NDef fade out/in instead of crossfade

### ISSUE THREAD

**Issue by ondrejpar** [supercollider/supercollider#5703]
Hi, I would like to replace synth registered with Ndef, fading out the old synth and fading in the new one to prevent clicks. However, crossfading them using fadeTime means that both will run at the same time and consume twice as much CPU, is that right?
Is it possible to somehow (not necessarily using Ndef) replace synths with fade out/in instead crossfade? If not, would it please be possible to add such option to NDef? Thanks.

**Comment by alln4tural** [comment]
Hi Ondřej,the issue tracker here is for development of the SuperCollider software -- you usage question is a good fit for scsynth.org, you'll get good help there.Cheers,eddi

 
  
  
 
 On 20/01/2022, 00:19 "Ondřej Pár" ***@***.***> wrote:

   
  Hi, I would like to replace synth registered with Ndef, fading out the old synth and fading in the new one to prevent clicks. However, crossfading them using fadeTime means that both will run at the same time and consume twice as much CPU, is that right? Is it possible to somehow (not necessarily using Ndef) replace synths with fade out/in instead crossfade? If not, would it please be possible to add such option to NDef? Thanks.
