### ISSUE TITLE
ERROR: Superclass 'View' of class 'QuartzComposerView' is not defined in any file.

### ISSUE THREAD

**Issue by wtkns** [supercollider/supercollider#5731]
i'm building sc without x11 and getting an error when i use sclang from the command line:

!echo '"hello world".postln;'>test.scd
!sclang ./test.scd

ERROR: Superclass 'View' of class 'QuartzComposerView' is not defined in any file.
/usr/local/share/SuperCollider/SCClassLibrary/deprecated/3.13/QQuartzComposerView.sc
ERROR: There is a discrepancy.
numClassDeps 928   gNumClasses 1854
Library has not been compiled successfully.

but i dont see any errors in the cmake, make, or install output

commands run and full output is here: https://gist.github.com/wtkns/9d021c1e71ebe2a8f90bf24cec1b3675 

thanks for any help!!

## Environment

* SuperCollider version:
 sclang 3.13.0-dev (Built from branch 'develop' [25aa4fe71])

* Operating system:
Google Colab VM

* Other details (Qt version, audio driver, etc.):
SC_QT=OFF

## Steps to reproduce

BUILD PROCESS FOLLOWED:
git clone --recursive https://github.com/supercollider/supercollider.git
!sudo apt-get install build-essential cmake libjack-jackd2-dev libsndfile1-dev libfftw3-dev libxt-dev libavahi-client-dev
!sudo apt-get install git libasound2-dev libicu-dev libreadline6-dev libudev-dev pkg-config libncurses5-dev

import os
os.makedirs('supercollider/build')
os.chdir('supercollider/build')

!cmake -DSC_QT=OFF -DCMAKE_BUILD_TYPE=Release -DNATIVE=ON -DNO_X11=ON -DSC_EL=no ..
!make -j3
!sudo make install

TESTING:
!sclang -v
!echo '"hello world".postln;'>test.scd
!sclang ./test.scd

## Expected vs. actual behavior
EXPECTED OUTPUT: 
hello world

ACTUAL OUTPUT:
sclang 3.13.0-dev (Built from branch 'develop' [25aa4fe71])
compiling class library...
	Found 738 primitives.
	Compiling directory '/usr/local/share/SuperCollider/SCClassLibrary'
	Compiling directory '/usr/local/share/SuperCollider/Extensions'
ERROR: Superclass 'View' of class 'QuartzComposerView' is not defined in any file.
/usr/local/share/SuperCollider/SCClassLibrary/deprecated/3.13/QQuartzComposerView.sc
ERROR: There is a discrepancy.
numClassDeps 928   gNumClasses 1854
Library has not been compiled successfully.

https://gist.github.com/wtkns/9d021c1e71ebe2a8f90bf24cec1b3675

**Comment by wtkns** [comment]
when i retried this with sclang 3.12.2 (Built from branch 'HEAD' [7c4c983cb]) i got the expected output:

*** Welcome to SuperCollider 3.12.2. *** For help type ctrl-c ctrl-h (Emacs) or :SChelp (vim) or ctrl-U (sced/gedit).
Couldn't set realtime scheduling priority 1: Operation not permitted
hello world

**Comment by dyfer** [comment]
Thanks for reporting, this is a valid bug. We need to make sure that the deprecated class is not included in gui-less builds.
