### ISSUE TITLE
SuperCollider Docs

### ISSUE THREAD

**Issue by TgyRoussel** [supercollider/supercollider#5734]
Hi, 

I just would like to report that the SuperCollider Docs webpage is inaccessible. Is there a new adress or is it just a bug ?  

Here the link : http://doc.sccode.org/ 

Thank you all. 

Tanguy

**Comment by alln4tural** [comment]
Which one do you mean?(http://doc.sccode.org/ is up for.me, but that's a private site)Cheers,eddi--https://alln4tural.bandcamp.comOn 22/02/2022, 11:00 TgyRoussel ***@***.***> wrote:

   
  Hi, 
  I just would like to report that the SuperCollider Docs webpage is inaccessible. Is there a new adress or is it just a bug ? 
  Thank you all. 
  Tanguy

**Comment by TgyRoussel** [comment]
Hi Eddi, 

Sorry for my late answer. That's the website I'm talking about. 
I always had access to that site with all examples and posts from the other users until the date I posted my original demand, that's why I don't understand ... 

Cheers, 
Tanguy

**Comment by dyfer** [comment]
@TgyRoussel 
Sorry to hear you have problems accessing the doc.sccode.org website.
As @alln4tural pointed out, this is not an official SuperCollider-maintained website.
Moreover, it seems that the connection issue is somewhere between you and the website, as I also am able to access it without problems. I suggest trying: 
- using a different browser
- accessing the site in incognito/private mode (this helps if it's an issue with site cache or cookies)
- cleaning up cookies for that site

Not sure if we can help beyond that. Again, as this site is not maintained by core SC devs, I'll close this issue (though feel free to comment back on your progress).
