### ISSUE TITLE
[FR] Add post_install and post_uninstall hooks to quarks

### ISSUE THREAD

**Issue by madskjeldgaard** [supercollider/supercollider#5753]
Some quarks produce files/folders outside of it's own folder, some quarks need the system to run a certain command after installation/uninstallation or do other things to finish the setup, and while this can be done with a method in a class of the package or documentation, it would be really great to have this automated in the quark file itself.

What I propose is that the quark dictionary contains two extra fields that each take a function that is run as hooks (inspired by how some linux package managers do this). 

* *post_install* - A function that runs after the quark is cloned and downloaded. Could be used to install further dependencies or setup things on the system.
* *post_uninstall* - A function that runs after the quark is uninstalled. Could be used for cleaning up stuff.

Those two are the most important I can come up with now, but I have an additional hook in mind that is worth mentioning, but I'm currently not sure how to solve it. It would additionally be great to have a hook that is triggering a function after the first class library compilation after the quark is installed - maybe called *post_compilation*. This would allow to call methods and classes in the quark after it has been installed and the classes are now compiled by the system.

**Comment by madskjeldgaard** [comment]
As further inspiration, here are the hooks that are used in the Arch Linux package system:

* pre_install
* post_install
* pre_upgrade
* post_upgrade
* pre_remove
* post_remove

**Comment by dyfer** [comment]
I think this was added in #5907

**Comment by madskjeldgaard** [comment]
Ah that's amazing @dyfer !

**Comment by madskjeldgaard** [comment]
and thanks @telephon !

**Comment by dyfer** [comment]
and thanks to @capital-G

**Comment by madskjeldgaard** [comment]
Thanks @capital-G !
