### ISSUE TITLE
Can't type [ (open bracket) character with Spanish keyboard

### ISSUE THREAD

**Issue by totalgee** [supercollider/supercollider#577]
Hi all, for me this is a showstopper.  I just am trying out alpha3 on a MacBook Air (10.8.2). I have a Spanish keyboard (default 'Spanish - ISO' setting under Input Settings in System Prefs).  On such a keyboard layout, typing the open bracket (i.e. '[' ) requires "alt" and the key located immediately to the right of 'P' (aka ⌥`). (according to KeyDownAction --> Mods: 524288 Unicode: 91 KeyCode: 33)

However, when I use that key combination to create an array, it seems hard-coded to jump to the previous block.  I noticed that "Go to Previous Block" is defined as Command-[, But I'm not pressing the Command/Apple key, I'm pressing the modifier key (alt) required simply to type an open bracket!

I tried redefining the "Go to Previous Block" Shortcut as another key combination, but that has no effect, it still jumps back and does not insert the bracket symbol in the editor.  Note that close-bracket ], as well as open/close brace { } (which also require alt key combinations) work correctly in the editor.

**Comment by brianlheim** [comment]
I've been noticing that we get a lot of traffic on this page. For anyone who's happening to visit here, would you mind leaving a comment as to why you're here, and whether there's anything we could do to make your life easier? Thanks!

**Comment by telephon** [comment]
It might be that this is just because the problem has nothing to do with SuperCollider?

But yes, if it has, please do so (also in spanish!)

**Comment by totalgee** [comment]
Since I was the one that opened it, I can say the original description is no longer true (and hasn't been for a long time).  I can type `[` on my MacBook Air Spanish keyboard (same laptop as in the original bug from 5 years ago ;-) and it works fine (using the key combination required by a Spanish keyboard layout).  It does not "Go to Previous Block" -- that was happening in a very old (2012) version of SC.  Regular keyboard usage works fine even if I leave all the default shortcut definitions in place. (At the time of the original bug, I had to un-define those shortcuts in order for the basic bracket keys to work.)

However,  all is still not perfect...  I generally assume that if I'm using a Spanish keyboard "all bets are off" for some shortcuts.  That's fine; I simply don't use them.  But it's interesting to note that even if I switch my OS to a North American layout, when using this machine/keyboard some of the default shortcuts **still** don't work.  For example, on my machine, using a Canadian layout (which I think is the same as US-English...certainly for characters like `[]{}` it is), the "Go to Previous Block" and "Go to Previous Region" (`Cmd-[` and `Cmd-Alt-[`) shortcuts work fine.  However, neither "Go to Next Block" (nor "Next Region") works...instead, they both do "Enlarge Font", which is defined for `Cmd-+`.  Plus (+) happens to be the same key where the close bracket is located on a Spanish keyboard (though with the English layout, it doesn't represent `+` any more!).  If this sounds complicated, it is indeed a bit weird!

Anyhow, there's no showstopper for me right now with these things.  Some shortcut things don't work properly, but I tend to just ignore/avoid them.

But, in case anyone is interested to study deeper some day, I ran the following:

```supercollider
(
Window("Test", 640@480).front.view.keyDownAction_{ |view, ch, mods, uni, keycode, key|
	var charStr = if(ch == 0.asAscii) { "nul" }{ ch.cs };
	var modStr = (isShift: "shift", isCtrl: "ctrl", isAlt: "alt", isCmd: "cmd").collect{|v,k|
		if (k.applyTo(mods)) {v}
	}.values.join($+);
	
	"ch: % mod: % unicode: % keycode: % key: %".format(charStr,
		modStr, uni, keycode, key).postln
}
)
```

Then, with that window focused, I tried different modifier combinations of the keys that show `[` and `]` on my physical keyboard, when Spanish and Canadian keyboard layouts are selected.

### `backtick` key (also marked `[`), immediately to the right of `P`:

| layout | modifier | message |
| ------ | -------- | --------- | 
|Spa| none | `ch: nul mod:  unicode: 0 keycode: 33 key: 33554431`
|Can| none | `ch: $[ mod:  unicode: 91 keycode: 33 key: 91`
|Spa| Alt | 2 messages: 1) `ch: nul mod: alt unicode: 0 keycode: 0 key: 16777251` 2) `ch: $[ mod: alt unicode: 91 keycode: 33 key: 91`
|Can| Alt | 2 messages: 1) `ch: nul mod: alt unicode: 0 keycode: 0 key: 16777251` 2) `ch: nul mod: alt unicode: 8220 keycode: 33 key: 91`
|Spa| Cmd | 2 messages: 1) `ch: nul mod: cmd unicode: 0 keycode: 0 key: 16777249` 2) `ch: nul mod: cmd unicode: 0 keycode: 0 key: 16777249`
|Can| Cmd | 2 messages: 1) `ch: nul mod: cmd unicode: 0 keycode: 0 key: 16777249` 2) `ch: nul mod: cmd unicode: 0 keycode: 33 key: 91`
|Spa| Cmd+Alt | 2 messages (**none emitted** when I press the actual `[` key!): 1) `ch: nul mod: cmd unicode: 0 keycode: 0 key: 16777249` 2) `ch: nul mod: cmd+alt unicode: 0 keycode: 0 key: 16777251`
|Can| Cmd+Alt | 3 messages (one for each pressed key in order): 1) `ch: nul mod: cmd unicode: 0 keycode: 0 key: 16777249` 2) `ch: nul mod: cmd+alt unicode: 0 keycode: 0 key: 16777251` 3) `ch: nul mod: cmd+alt unicode: 0 keycode: 33 key: 91`

### `+` key (also marked `]`), two keys to the right of `P`:

| layout | modifier | message |
| ------ | -------- | --------- | 
|Spa| none | `ch: $+ mod:  unicode: 43 keycode: 30 key: 43`
|Can| none | `ch: $] mod:  unicode: 93 keycode: 30 key: 93`
|Spa| Alt | 2 messages: 1) `ch: nul mod: alt unicode: 0 keycode: 0 key: 16777251` 2) `ch: $] mod: alt unicode: 93 keycode: 30 key: 43`
|Can| Alt | 2 messages: 1) `ch: nul mod: alt unicode: 0 keycode: 0 key: 16777251` 2) `ch: nul mod: alt unicode: 8216 keycode: 30 key: 93`
|Spa| Cmd | 2 messages: 1) `ch: nul mod: cmd unicode: 0 keycode: 0 key: 16777249` 2) `ch: nul mod: cmd unicode: 0 keycode: 30 key: 43`
|Can| Cmd | 2 messages: 1) `ch: nul mod: cmd unicode: 0 keycode: 0 key: 16777249` 2) `ch: nul mod: cmd unicode: 0 keycode: 30 key: 93`
|Spa| Cmd+Alt | 3 messages (one for each pressed key in order): 1) `ch: nul mod: cmd unicode: 0 keycode: 0 key: 16777249` 2) `ch: nul mod: cmd+alt unicode: 0 keycode: 0 key: 16777251` 3) `ch: nul mod: cmd+alt unicode: 0 keycode: 30 key: 43`
|Can| Cmd+Alt | 3 messages (one for each pressed key in order): 1) `ch: nul mod: cmd unicode: 0 keycode: 0 key: 16777249` 2) `ch: nul mod: cmd+alt unicode: 0 keycode: 0 key: 16777251` 3) `ch: nul mod: cmd+alt unicode: 0 keycode: 30 key: 93`

**Comment by brianlheim** [comment]
Thank you @totalgee !

**Comment by wovendan** [comment]
Re traffic to this page. I have never heard of supercollider, I am arriving via the nightmare alluded to here of coding in English on a keyboard purchased in South America, where square brackets and many other things (like tilda) require some balancing act like Richard Prior in Superman (Both Keys... at the same time). It really is horrible and as @totalgee (at sign is AltGr + Q)  implies, the printed letters on the keyboard and the sheer number of chars that require special treatment mean its not remotely practical to just switch to US keyboard (then remember where the keys are) - one completely loses the thread of thought...Arghhh!

**Comment by dyfer** [comment]
Hi @wovendan 
I'm not sure we can help here :) I also wanted to note, that some of these issues might be also specific to Qt - the GUI framework that SuperCollider uses.

**Comment by wovendan** [comment]
No worries, I didnt expect help, just wanted to answer the question above about why this page is getting so much traffic (and share some general but related frustration!) ... I came here searching for something like 'square bracket on spanish keyboard'.
