### ISSUE TITLE
Windows: Multiple MIDI devices gets the same endpoint name

### ISSUE THREAD

**Issue by lijon** [supercollider/supercollider#5773]
I have a problem regarding multiple MIDI devices built with Teensy's. They all have different MIDI device names in their firmware (Island1, Island2), but SuperCollider sees them all with the same name on Windows (Island2, Island2). Works fine on Mac though.
The windows settings show the correct names, so I believe the OS itself gets the name right.

Also their index in the `MIDIClient.sources` list changes between each connect or sclang boot, so can't use that either.
This makes it impossible to pick the correct MIDI device.

## Environment

* SuperCollider version: SC 3.12.12
* Operating system: Windows 7

## Steps to reproduce

```supercollider
MIDIIn.connectAll;
```

## Expected vs. actual behavior

Expected to see two MIDI Endpoints: Island1 and Island2.
Actual behavior: Two endpoints with same name: Island2 and Island2.

**Comment by dyfer** [comment]
Hello,

Can you post the output of MIDI `.sources` and `.destinations` with both Teensy devices connected?

```supercollider
MIDIClient.init;
MIDIClient.sources.postln;
MIDIClient.destinations.postln;
```

**Comment by lijon** [comment]
This is the USB info on mac, btw:

```
  Product ID: 0x0485
  Vendor ID:  0x16c0
  Version:  2.73
  Serial Number:  7750070
  Manufacturer: Teensyduino
```

serial number and product name are different on all devices, vendor and product ID are the same.

**Comment by lijon** [comment]
I have now also tried changing both manufacturer string and midi port string, but SC still sees them as having the same name.

**Comment by lijon** [comment]
Here's someone having the same problem 6 years ago: https://stackoverflow.com/questions/63195134/usb-midi-device-name-problems-under-windows

**Comment by lijon** [comment]
It also shows up with the same name in Ableton for example, so maybe it's a bug in PortMIDI and Ableton is using that, or it's a bug in Windows.

**Comment by dyfer** [comment]
I found this on https://www.pjrc.com/teensy/td_midi.html:

> Windows: On version 10, Windows appears to [automatically recognize MIDI name changes](https://forum.pjrc.com/threads/32534-Adjusting-the-Teensy-MIDI-device-name?p=165942&viewfull=1#post165942). Older versions of Windows may require deleting the device from the Windows Device Manager, then unplug and reconnect the USB cable and allow the New Hardware Wizard to detect the change.

If this behavior also occurs in Ableton, I'm guessing this is more likely to be an issue between the Teensy firmware and Windows's handling (caching?) of device names.

If you haven't already, please follow the troubleshooting instructions on the linked page and report back.

**Comment by lijon** [comment]
In this case it's Windows 7. The devices does have different names in the Windows device manager. However, in all software we tried they are listed with the same name. I suspect that some Windows API ignores the names and just looks at the USB vendor/product ID.

**Comment by dyfer** [comment]
Have you dried removing/re-adding the device like the linked page suggests?
