### ISSUE TITLE
Close brace } put at the wrong indent level in new SC IDE editor

### ISSUE THREAD

**Issue by totalgee** [supercollider/supercollider#578]
When I type a new close-brace } it doesn't put it at the right indent level… I'd like it to move back one level (as it does in the SC IDE), but it puts it at the same level.  Note that it does do the "right thing" if I subsequently choose "Edit -> Autoindent Line or Region", or if I press tab after writing the character. But is it normal that I should have to do this?

    if(true) {
        "hello".postln;
        }; // yuck

This looks vaguely related to issue 409, but that's closed…

**Comment by scztt** [comment]
Fixed.
