### ISSUE TITLE
Quark update relies on master branch

### ISSUE THREAD

**Issue by capital-G** [supercollider/supercollider#5781]
## Environment

* SuperCollider version : 3.13-dev
* Operating system: Any
* Other details (Qt version, audio driver, etc.): -

## Steps to reproduce

Try to update a Quark which does not have a `master` branch as we will 

https://github.com/supercollider/supercollider/blob/b38fbc1bac91c698ddaf8c880f987b282a2112c9/SCClassLibrary/Common/Quarks/Quark.sc#L88-L95

https://github.com/supercollider/supercollider/blob/b38fbc1bac91c698ddaf8c880f987b282a2112c9/SCClassLibrary/Common/Quarks/Git.sc#L19-L21

see also

https://github.com/supercollider/supercollider/blob/b38fbc1bac91c698ddaf8c880f987b282a2112c9/SCClassLibrary/Common/Quarks/Git.sc#L91-L94

Interestingly enough it seems to not fail on Quarks which does not have a master branch, such as https://github.com/capital-G/OSCMapper

```supercollider
Quarks.install("OSCMapper");
```

```text
Installing OSCMapper
Adding path: /Users/xxx/Library/Application Support/SuperCollider/downloaded-quarks/OSCMapper
OSCMapper installed
-> Quark: OSCMapper[0.1.0]
```

recompile

```supercollider
Quarks.update("OSCMapper");
```

```text
Quark 'OSCMapper' updated to version: 0.1.0 tag: tags/v0.1.0 refspec: tags/v0.1.0
```

[i have not tested it with an actual diff in the repo!]

Does git internally re-route the master branch?

## Expected vs. actual behavior

SuperCollider should use the default branch (which can be master and is determined by the hoster/or git ?) and not the deprecated master branch as default branch.

Clone e.g. does not rely on a specified branch

https://github.com/supercollider/supercollider/blob/b38fbc1bac91c698ddaf8c880f987b282a2112c9/SCClassLibrary/Common/Quarks/Git.sc#L11-L18

and maybe we can resolve this by removing any explicitly specifications of a branch name? If you managed to switch to a different branch within a quark you are most likely an advanced user already anyhow and can revert to a desired branch manually?

**Comment by dyfer** [comment]
Hello @capital-G, I believe this is a duplicate of #5096. What do you think about moving the conversation there?

**Comment by capital-G** [comment]
Oh, sorry, I should have checked if there is already an issue concerning this topic. OC, lets close this issue then.
