### ISSUE TITLE
.pointsTo

### ISSUE THREAD

**Issue by melas0nos** [supercollider/supercollider#5784]
## Environment
Windows 10 21h1
* SuperCollider version:
* SuperCollider 3.12.2
Built from branch 'HEAD' [7c4c983]

## Steps to reproduce

I found it going through the main Object class help file:

```supercollider
a = 9;
b = [1, a, 6, 8];
c = [1, b, 5];
c.pointsto(b); // true
c.pointsto(a); // false
```

## Expected vs. actual behavior
Expected: Bool

^^ ERROR: Message 'pointsto' not understood.
Perhaps you misspelled 'pointsTo', or meant to call 'pointsto' on another receiver?
RECEIVER: [ 1, [ 1, 9, 6, 8 ], 5 ]

I'm not sure how big of a deal this is. I've never used this method. Just thought I'd relay.

**Comment by melas0nos** [comment]
I see now that the help file has typos. poinsto instead of pointsTo (capital T)

Not sure if I should just close since this is obviously not a big deal, or keep open so the typo gets fixed.

**Comment by dyfer** [comment]
Fixed, thanks for reporting @melas0nos
