### ISSUE TITLE
The server freezes the system 

### ISSUE THREAD

**Issue by Disc0erg0sum** [supercollider/supercollider#5795]
## Environment

* SuperCollider version: 3.12.2-1
* Operating system: Majaro, Linux 5.17.1.17.realtime2-3-rt x86_64
* Other details (Qt version, audio driver, etc.):qt5, jack2, i3 

## Steps to reproduce
Open SuperColiider IDE and start the server.

## Expected vs. actual behavior

After a short time, the entire system freezes.
The only thing you can do is to pull the plug.
There is nothing to be found in the journalctl.

I can start other audio applications with Jack, without problems.

**Comment by dyfer** [comment]
That's very strange. Is there anything playing on the server? Or is it just running idle?
