### ISSUE TITLE
 Indentation stopped working SCIDE windows v 3.12.2

### ISSUE THREAD

**Issue by Maxouwe** [supercollider/supercollider#5805]
Somehow the indentation functionality stopped working.  I tried setting it to different different keys, nothing happens when i press them. I even reinstalled the the IDE but it made no difference. Tab works fine and as intended in other IDE's.
Yesterday it was working fine, until it just stopped working.

**Comment by dyfer** [comment]
Does it happen it in multiple SC documents, or only a particular one?

**Comment by Maxouwe** [comment]
Hey i closed this issue, because there was no problem at all, embarrassingly enough. Sorry.
