### ISSUE TITLE
GrainBuf Ugen doesn't seem to support stereo buffers

### ISSUE THREAD

**Issue by petethomasmusique** [supercollider/supercollider#5809]
## Environment

* SuperCollider version: 3.12.1
* Operating system: Mac OS Monterey 12.3
* Other details (Qt version, audio driver, etc.):

## Steps to reproduce

```supercollider
b = Buffer.read(s, '/path/to/a/mono/file');
b = Buffer.read(s, '/path/to/a/stereo/file');

(
{
	var sig;
	sig = GrainBuf.ar(
		1, // Change this to match buffer channels
		Impulse.ar({ExpRand(130,130.5)}!12), 
		LFNoise1.kr(0.3!12).exprange(0.0002,0.1),
		b, 
		1, 
		MouseX.kr(0, 1, lag:0.5), 
		2, 
		0, 
		-1,
		512, 
	);
	sig = Splay.ar(sig);
}.play
)
```

## Expected vs. actual behavior
Stereo should work and the numChannels argument (1st) implies that it supports stereo. However, although no error is thrown, a stereo buffer does not work, whereas a mono one does.

Is this a bug? Or is my code wrong.

Very many thanks for you time.

**Comment by jparmentervf** [comment]
from the documentation:
sndbuf: the buffer holding a mono audio signal. If using multi-channel files, use Buffer.readChannel.
