### ISSUE TITLE
Add save-to-image method for plots or windows

### ISSUE THREAD

**Issue by capital-G** [supercollider/supercollider#5813]
## Motivation

As an extension to my project https://github.com/capital-G/sc_kernel I would like to add an easy possibility to save e.g. a plotted graph to a file so I can easily embed it into a document.
It would be nice if this could also work headless but I think we need Qt for this.

## Description of Proposed Feature

The idea is to have a programmatic way of creating a file of

```supercollider
{SinOsc.ar(2.0)}.savePlot(fileName: "my_plot.png", duration: 1.0);
```
![image](https://user-images.githubusercontent.com/8267062/179189203-a39126e6-54b6-49f3-8209-91c054ad6261.png)
`my_plot.png`

where the boundaries of the window should not be included.

## Plan for Implementation

There are functions in Qt which support this already, see

* ```cpp
   QPixmap QWidget::grab(const QRect &rectangle = QRect(QPoint(0, 0), QSize(-1, -1)))
   ```
   https://doc.qt.io/qt-5/qwidget.html#grab

and

* ```cpp
   bool QPixmap::save(const QString &fileName, const char *format = nullptr, int quality = -1) const
   ```
   https://doc.qt.io/qt-5/qpixmap.html#save

so maybe it is as easy as adding a method to [`QcWindow.cpp`](https://github.com/supercollider/supercollider/blob/develop/QtCollider/widgets/QcWindow.cpp) which then gets invoked from sclang.
Within sclang we could extend the `Window` class with a `saveToFile` method.

## Who will implement this? How long will it take?

I could take a look at this, hopefully it would not take long and would allow me to take a look at the mechanics of QtCollider.

**Comment by dyfer** [comment]
Have you seen the `Image` class? I believe this functionality already exists:
```supercollider

~plot = {SinOsc.ar(2.0)}.plot(duration: 1.0);

~image = Image.fromWindow(~plot.parent, Rect(0, 0, ~plot.parent.bounds.width, ~plot.parent.bounds.height)); // get image from the view

~image.plot; // draw the image itself to check;
~image.write("~/Desktop/my_plot.png.png".standardizePath); // save
```

And yes, SC needs to be built with Qt for this to work.

**Comment by dyfer** [comment]
@capital-G is it okay to close this issue?

**Comment by capital-G** [comment]
Oh, this is really nice, thanks for bringing this to my attention, I was not aware of this.
Yeah, I think this is already implemented in this case, I'll close the Issue.
