### ISSUE TITLE
Cannot build on openSUSE Tumbleweed (sndfile-related)

### ISSUE THREAD

**Issue by fpesari** [supercollider/supercollider#5818]
## Environment

* SuperCollider version: 3.12.2
* Operating system: openSUSE Tumbleweed
* Other details (Qt version, audio driver, etc.): libsndfile 1.1.0

Hello. When I try to build SuperCollider on openSUSE Tumbleweed via OBS, I get this error:

```
[   76s] In file included from /home/abuild/rpmbuild/BUILD/SuperCollider-3.12.2-Source/server/plugins/DiskIO_UGens.cpp:27:
[   76s] /usr/include/sndfile.h:356:33: error: conflicting declaration 'typedef struct sf_private_tag SNDFILE'
[   76s]   356 | typedef struct sf_private_tag   SNDFILE ;
[   76s]       |                                 ^~~~~~~
[   76s] In file included from /home/abuild/rpmbuild/BUILD/SuperCollider-3.12.2-Source/include/plugin_interface/SC_World.h:31,
[   76s]                  from /home/abuild/rpmbuild/BUILD/SuperCollider-3.12.2-Source/include/plugin_interface/SC_PlugIn.h:23,
[   76s]                  from /home/abuild/rpmbuild/BUILD/SuperCollider-3.12.2-Source/server/plugins/DiskIO_UGens.cpp:25:
[   76s] /home/abuild/rpmbuild/BUILD/SuperCollider-3.12.2-Source/include/plugin_interface/SC_SndBuf.h:25:28: note: previous declaration as 'typedef struct SNDFILE_tag SNDFILE'
[   76s]    25 | typedef struct SNDFILE_tag SNDFILE;
[   76s]       |                            ^~~~~~~
```

**Comment by dyfer** [comment]
Hello @fpesari 
This has been fixed in #5761 (the fix is not present in 3.12.2). Can you build from the `develop` branch instead?

**Comment by fpesari** [comment]
Hello @dyfer, building from `develop` indeed works, however packaging straight from git is generally discouraged. I could turn those two commits into a patch for 3.12.2 (and probably will do it) but it'd better if a new release came out, so I seriously hope that :smile_cat:

**Comment by dyfer** [comment]
The new release will come out! Eventually :)
