### ISSUE TITLE
Some args aren't editable in Ugen OteyPiano

### ISSUE THREAD

**Issue by hr30** [supercollider/supercollider#5860]
## Environment

* SuperCollider version: 3.11.2
* Operating system: Debian 11 (bullseye)
* Other details (Qt version, audio driver, etc.):
SC3 plug-ins 3.9.1
## Steps to reproduce

```supercollider
(
f = { | t_gate = 1, freq  = 440 , vel = 0.2, detune = 0.01 | 
	var sig = OteyPiano.ar(freq, vel, t_gate: t_gate, detune: detune);
	sig !2;
};
)
x = f.play;
x.set (\freq, 220, \vel, 0.2, \t_gate, 1, \detune, 0.1);
```

## Expected vs. actual behavior
Some arguments implemented in the Ugen OteyPiano like ```freq``` or ```detune``` can't be edited via ```set```. Not sure if this intended, but if so, it is inconsistent, because ```t_gate```and ```vel``` can be changed. I didn't test all arguments, but I think this UGen needs to be revised.

No errors generated

No crashes to report.

**Comment by dyfer** [comment]
Hello @hr30 
Thanks for the report.
OteyPiano is part of [sc3-plugins](https://github.com/supercollider/sc3-plugins), not the core SuperCollider library. These plugins sometimes are not as polished as the ones included in SC.
If you can, please re-file this in the sc3-plugins repository, as that's the place to submit sc3-plugins issues.

**Comment by jamshark70** [comment]
@hr30 If you do refile the issue under sc3-plugins, please also state exactly what you would like to happen when modulating frequency. 

This is a physical model. You might be assuming that you could start, for instance, with 50 Hz and instantly modulate to 5000 Hz... but, is this even possible in the real world? In a real piano, those strings would be different weights. I'd expect the best OteyPianoStrings could do would be highly glitchy in this case.

The stated request makes sense from the standpoint of a programming interface, but it might not make sense for the audio algorithm. So it would be helpful to be clear about the expectation.
