### ISSUE TITLE
No sound on windows 10 using ASIO4ALL driver

### ISSUE THREAD

**Issue by OJMusic** [supercollider/supercollider#5881]
Hi :)
I have a serious problem. It's not possible for me to get sound on my Windows 10 computer when I'm using SuperCollider. I have sound on my computer in all other programs than SuperCollider. It's a big problem for me as I studying sound production in my University, and right now we're being taught how to use SuperCollider by a real pro. But with no sound on my computer, when using Supercollider and Asio4All, it's not possible for me to learn this programming, which I really want to learn.

My computer is a HP Elitebook 8760w with intel i7, 8 Gb Ram and Windows 10 pro 64 bit.
My teacher can't solve the problem, even if he's really good at using SuperCollider. I can't solve it, and none of my fellow students has been able to solve the problem - so far. 

I have set the sound settings to 16 bit, 44100 hz. I've tried to allow programs to take exclusive control over the sound, and also dis-alliowed programs to do so. Same result - no sound.

In REAPER I have good sound using ASIO4ALL-driver on my computer, but not in SuperCollider using ASIO4ALL.

When SuperCollider is active - I can't play sound from Winamp either. When I click "play" in winamp it simply doesn't start to play. The second I close SuperCollider - the music starts to play in WinAmp.

I really hope you can help me to solve this problem

Best regards
Ole Jakob

Bug description:

Steps to reproduce:
1.
2.
3.

Actual result:

Expected result:

**Comment by dyfer** [comment]
Hello @OJMusic 

> In REAPER I have good sound using ASIO4ALL-driver on my computer, but not in SuperCollider using ASIO4ALL.

Can you confirm that Reaper actually uses the ASIO4ALL driver and that you get sound that way?

How are you setting SC to use ASIO4ALL driver? Please provide 1) your code that sets the device and 2) output of the post window when you boot the server.

> When SuperCollider is active - I can't play sound from Winamp either. When I click "play" in winamp it simply doesn't start to play. The second I close SuperCollider - the music starts to play in WinAmp.

This is an issue/feature of ASIO4ALL, AFAIU. In order to provide low-latency operation, ASIO4ALL "takes over" the audio device (it opens it in "exclusive mode"). If Reaper indeed uses ASIO4ALL, you should observe similar behavior with Reaper running.

**Comment by OJMusic** [comment]
Hi Marcin
Thank you for your answer. :-)

I would like Supercollider to use my default sound driver, but it doesn't work. The sound simply won't boot in Supercollider when using the default sound driver on my HP workstation. 

The numbers below the Post Window are white. When I boot the sound engine these numbers become yellow and then white again - and no sound. The sound server just won't boot.

But I can get sounds from all other programs except SuperCollider when using the default sound driver. The name of the default sound driver is: IDT High Definition Audio CODEC"

Then I downloaded the ASIO4All driver to my computer to see if this could solve the problem. And in the startup file in SC is typed:

Server.default.options.inDevice = "ASIO : ASIO4ALL v2";
Server.default.options.outDevice = "ASIO : ASIO4ALL v2";

to make SuperCollider use the ASIO4All sound driver.

When SC starts it types that it's using the ASIO4ALL driver
Now the sound engine in SC actually boots and I can se the numbers under the Postwindow turn from white over yellow to remain green. The sound server is now booted.

Then I write a simple code to generate sound, and all the various scopes in SC shows me a sound is actually being produced in SC. But no sound at all is coming from my speakers. It's indeed a mystery.

I can confirm that Reaper actually uses the ASIO4ALL driver and that I get sound that way.
Because Reaper tells me that it's using ASIO4ALL and also provides me with a little control window to ASIO4ALL. When doing so I get sound on my computer. 
I would expect the same to be the case in SuperCollider but as this isn't the case I suppose it's because of an unknown bug in SC that causes this problem.

I hope this bug can be found and fixed.

Thank you for trying to help me :-)

All the best
Ole Jakob

**Comment by dyfer** [comment]
> I would like Supercollider to use my default sound driver, but it doesn't work. The sound simply won't boot in Supercollider when using the default sound driver on my HP workstation.

Please provide full code and post window output when trying to use the default device and booting the server.

Also, could you provide an output of `ServerOptions.devices`? You can explicitly set input/output device that way, not necessarily using ASIO4All.

> I would expect the same to be the case in SuperCollider but as this isn't the case I suppose it's because of an unknown bug in SC that causes this problem.
> I hope this bug can be found and fixed.

I really doubt this is an SC bug. Is is most likely a configuration issue.

You still didn't provide the code that you're using to make sound, nor the output of the post window when you boot the server. Issues that are not reproducible and don't provide detailed information are impossible to address.

**Comment by dyfer** [comment]
Closing due to lack of response. Feel free to reopen if the problem still occurs.

**Comment by OJMusic** [comment]
Hi Marcin
Sorry for not answering - I've been very busy these days.
I've found a solution however.

I have bought an external USB soundcard - a Behringer UCA222. It also
uses the ASIO4ALL driver and works as plug and play. When I put it into
the USB port and started SuperCollider I was able to get sound in
SuperCollider through that USB soundcard.
I bought it at www.Thomann.de and the pricetag including delivery to
Denmark was around 21 Euros.

Maybe this can help other of your users if a similar problem should occur
to them.

First I was considering buying a Creative USB external Soundcard but my
teacher at the University suggested I bought the Behringer instead as it
uses the ASIO4ALL sounddriver I use in SuperCollider after he made me a
startup file til ensure the ASIO4ALL driver was used.

You can see the Behringer soundcard here:
https://www.thomann.de/dk/behringer_ucontrol_uca_222.htm

All the best!
Ole Jakob

On Mon, 24 Oct 2022 14:52:07 -0700, Marcin Pączkowski wrote:

> Closing due to lack of response. Feel free to reopen if the problem
still occurs.
