### ISSUE TITLE
Hide/Show all widgets

### ISSUE THREAD

**Issue by telephon** [supercollider/supercollider#589]
It would make sense if we could hide/show all visual elements / widgets from the View menu.
For example, the clock may be redundant when you have a clock elsewhere, the server display when no server is involved, and (link to #585) line numbers are not needed for everything.

**Comment by brianlheim** [comment]
Pinging. I'm not sure it's worth adding this capability; I like always having the Interpreter/Server status at the bottom, and the line numbers issue has been solved. How do others feel? @telephon ?

**Comment by telephon** [comment]
not important.
