### ISSUE TITLE
Reports of high CPU for 3.13 release candidates

### ISSUE THREAD

**Issue by yaxu** [supercollider/supercollider#5910]
Under both mac and linux, 3.13 causes high CPU on idle when using the SuperDirt framework. Re-installing 3.12 resolves the issue.

For more details please see the superdirt issue: https://github.com/musikinformatik/SuperDirt/issues/277

Reporting here in case people are seeing similar high CPU outside of superdirt.

**Comment by telephon** [comment]
Here is the reproducer.
It has to do with the initialisation of the first frame for a trigger input.

```supercollider
// this never stops
(
{
	Silent.ar.poll(label: "I am not paused, sorry.");
	PauseSelf.kr(Impulse.kr(0));
}.play
)
```


```supercollider
// this stops after 2 sec
(
{
	Silent.ar.poll(label: "I am not paused, sorry.");
	PauseSelf.kr(Impulse.kr(0.5));
}.play
)
```

**Comment by telephon** [comment]
This might be connected to the [Fix UGen Initialization](https://github.com/supercollider/rfcs/pull/19) project.

**Comment by telephon** [comment]
It would have to be here:

https://github.com/supercollider/supercollider/blob/71f161c5440b2e1e84d3664b61c4d8d97cc56b68/server/plugins/TriggerUGens.cpp#L2254-L2271

**Comment by mtmccrea** [comment]
Thanks @yaxu for reporting this and @telephon for tracking the problem down.
`PauseSelf` is not initialized properly, so the first trigger is missed as you pointed out.

I've submitted a fix: #5914.

@yaxu, if you're familiar with building SC, you could give it a try, or wait until the updated release candidate. Either way, please let us know if this solves your issue!

**Comment by dyfer** [comment]
@yaxu can you confirm that https://github.com/supercollider/supercollider/pull/5914 fixes the issue? You can grab the build from [here](https://github.com/supercollider/supercollider/actions/runs/3576446573) (note that the macOS builds are unsigned)

**Comment by yaxu** [comment]
@dyfer I've asked on the upstream ticket, I didn't try 3.13 at all myself yet - was just reporting on behalf of people who had.
If no-one else comes forward I can try it on my (linux) system tho

**Comment by dyfer** [comment]
The examples provided by @telephon seem to behave correctly after #5914 so I assume this issue is now fixed.

Feel free to reopen if that's not the case.
