### ISSUE TITLE
Ubuntu Studio 22.04 dependency hell vs udev

### ISSUE THREAD

**Issue by jamshark70** [supercollider/supercollider#5911]
This had been reported a year ago on scsynth, but never addressed.

https://scsynth.org/t/dependency-installation-issues-on-ubuntu/4106

```
$ sudo apt-get install libudev-dev

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 udev : Breaks: systemd (< 247.3-3ubuntu3.1)
        Breaks: systemd:i386 (< 247.3-3ubuntu3.1)
E: Error, pkgProblemResolver::Resolve generated breaks, this may be caused by held packages.
```

If this is unsatisfied, cmake complains:

```
CMake Error in external_libraries/hidapi/linux/CMakeLists.txt:
  Found relative path while evaluating include directories of "hidapi":

    "UDEV_INCLUDE_DIR-NOTFOUND"
```

The upshot is that SuperCollider cannot be built in current Ubuntu LTS, and the problem has been known (wrt Ubuntu 21.xx) for over a year now. That is not good.

Since this seems to be related to HID... can HID be disabled? README is not clear on this.

**Comment by dyfer** [comment]
FWIW in GitHub Actions we _do_ build SC with [Ubuntu 22.04](https://github.com/supercollider/supercollider/blob/develop/.github/workflows/actions.yml#L96). 
[Here's what we install](https://github.com/supercollider/supercollider/blob/develop/.github/workflows/actions.yml#L190) and [here's the cmake invocation](https://github.com/supercollider/supercollider/blob/develop/.github/workflows/actions.yml#L215). I can't look closely right now or test/check what can be wrong, but just wanted to point out that AFAICT SC can indeed be built with the latest LTS version of Ubuntu.

**Comment by jamshark70** [comment]
Ubuntu *Studio* preinstalls a lot of creative software. While this is not "vanilla" Ubuntu, it would be worth paying attention to this as it's reasonable to expect that SuperCollider users might favor a distribution tailored toward real-time creative work.

I'll go to askubuntu first, though. I see a couple of possible solutions for other desktop systems, but unfortunately not for the KDE Plasma desktop that Ubuntu Studio is using now.

**Comment by dyfer** [comment]
> Ubuntu _Studio_ preinstalls a lot of creative software. While this is not "vanilla" Ubuntu, it would be worth paying attention to this as it's reasonable to expect that SuperCollider users might favor a distribution tailored toward real-time creative work.

Thanks for clarifying, I updated the title. Of course making sure SC works on Ubuntu Studio makes sense.

Please report back after trying the linked solution. IMO this is ultimately Ubuntu's problem, but if it can't be fixed in the OS then we can try finding a workaround in SC.

**Comment by dyfer** [comment]
BTW one workaround would be to build without hidapi:
`cmake -D SC_HIDAPI=OFF ..`
This would of course disable support for Human Input Devices, so it might not be an option...

**Comment by jamshark70** [comment]
Seems to be resolved by the askubuntu thread.

For posterity: https://askubuntu.com/questions/1417403/can-not-install-libudev-dev-on-ubuntu-22-04/1417416#1417416 -- as it would be quite useful to have a record of this somewhere for SC users.
