### ISSUE TITLE
FileDialog fileMode 2 seems broken in KDE Plasma

### ISSUE THREAD

**Issue by jamshark70** [supercollider/supercollider#5918]
## Environment

* SuperCollider version: 3.11.2 (packages because I can't build yet)
* Operating system: Ubuntu Studio 22.04, KDE Plasma 5.24.4
* Other details (Qt version, audio driver, etc.):

## Steps to reproduce

```supercollider
FileDialog({ |path| path.debug("got path") }, fileMode: 2, acceptMode: 0);
```

## Expected vs. actual behavior

Expected: Posts `got path: ...`.

Actual: OK button is inactive. Click it repeatedly and nothing happens.

Maybe we need to pass a different flag? Or maybe KDE Plasma just doesn't support this.

Anyway it breaks an audio-file browser GUI of mine. Will have to work around by "Choose a file inside the folder" instead of "choose a folder."

**Comment by JordanHendersonMusic** [comment]
@jamshark70 would you mind just retesting this and closing the issue if its fixed as it works on my system KDE 5.27.11?

**Comment by jamshark70** [comment]
I switched to XFCE because Plasma was a [expletive deleted] disaster on this particular machine. So I guess just close it.

**Comment by JordanHendersonMusic** [comment]
Ah that's a shame, I've always had good results with KDE, but it has seen quite a lot of work recently!

Closing because cannot replicate.
