### ISSUE TITLE
Buffer.cueSoundFile does not expose path

### ISSUE THREAD

**Issue by salkin-mada** [supercollider/supercollider#5936]
`*cueSoundFile` does not "save" the path. But `cueSoundFile` (**instance** method) does. Possibly due to a miss in the class method.

## Environment

* SuperCollider version: 3.12.2
* Operating system: Linux, Arch btw

## Example: class method vs. instance method

```supercollider
// path is not visible
~b0 = Buffer.cueSoundFile(s, Platform.resourceDir +/+ "sounds/a11wlk01.wav", 0, 1);
~b0.path;
~b0.inspect

// path is visible
~b1 = Buffer(s, 32768);
~b1.cueSoundFile(Platform.resourceDir +/+ "sounds/a11wlk01.wav", 0);
~b1.path;
~b1.inspect;
```

**Comment by dyfer** [comment]
Thanks @salkin-mada for filing this! It is now fixed in the develop branch. I also plan to pull it into 3.13.0-rc2

BTW the second example is missing `.alloc` - pointing it out in case someone comes across this example in the future. It should be:

```supercollider
~b2 = Buffer.alloc(s, 32768, 1); // number of channels needs to be the same as the one in the soundfile; defaults to 1 effectively, so it happens to work for mono files without specifying number of channels
~b2.cueSoundFile(Platform.resourceDir +/+ "sounds/a11wlk01.wav", 0);
```
