### ISSUE TITLE
[feature request] - inverse square root fast fourier transform ugen in cuda

### ISSUE THREAD

**Issue by tiagomoraismorgado2022** [supercollider/supercollider#5947]
what if this could be the starting point for a new ugen in supercollider:
- https://gist.github.com/tiagomoraismorgado2022/ea81ca8277a3e04b3e37866f98f4b471
this could be interesting for instance for an intelligent counterpoint based harmonizer, or some cv crazy thing emulation

**Comment by Spacechild1** [comment]
See https://github.com/pure-data/pure-data/issues/1866#issuecomment-1379591276
