### ISSUE TITLE
Scheduling problems on Apple M1

### ISSUE THREAD

**Issue by Josemiguelfernandez** [supercollider/supercollider#5948]
## Environment

* SuperCollider version: 3.12.2, 3.13.0-rc-1 arm64 and x64
* Operating system: macOS Monterey 12.6.1 and Ventura

## Steps to reproduce

```supercollider
SynthDef(\imp, { OffsetOut.ar(0, Impulse.ar(0)); FreeSelf.kr(Impulse.kr(0)); }).add;

(
t = Task({
	10000.do({ arg i;
		Synth(\imp);
		0.05.wait;
		});
	});
)

t.start;
t.stop;
```

## Expected vs. actual behavior

I have done different tests sending messages from scland and from another OSC client (Antescofo) to scsynth and I find scheduling problems (rhythmic irregularity or interruptions). 
If I launch the Task process (example above Steps to reproduce) on a Mac M1 the rhythm generated by scland in scsynth has irregularities and is not completely stable. For example if MacOS starts to make an indexation (Spotligth), if I connect to the internet or switch from one application to another (command+tab), there are interruptions. It seems that every time the system does a background operation, there are interruptions sending or receiving OSC messages.
I have done several tests on 2 MacBook Pro M1 with Monterey (12.6.1) and a MacBook Air M1 with Ventura.
This problem does not happen on a MacBook Pro with Intel processor running SC 3.12.2.
I've tried with the x64 version on Rosetta and native ARM64 and the problem is the same...

Apparently there is a priority problem, but using the 'renice' command in the terminal and increasing the priority of scsynth and sclang process there seems to be a very small improvement, but it doesn't solve the problem.

Any idea how to solve this problem? To make it work like on an Intel processor without interruptions ?

Thanks,

José

**Comment by Josemiguelfernandez** [comment]
I just launched the test using supernova and it works as expected without interruptions! It seems to be a problem with scsynth...

**Comment by smrg-lm** [comment]
If you replace `Synth(\imp)` with `(instrument: \imp).play()` does it play fine in the server? It could be an OS performance difference but since `Synth(\imp)` doesn't guaranties timing, because no bundles are created, the code can sound very different depending on the load.

**Comment by Josemiguelfernandez** [comment]
Hola Lucas, 
Thanks for the suggestion! I have done different tests with sclang and antescofo sending messages in different ways in udp and tcp, the example I have sent is minimal and can be done in several ways. I have also tried with patterns:
```
Pbind(\instrument, \imp, \dur, 0.05).play;
```
And with your example and the problem is the same, interruptions due to macOS background tasks. 
A simple way to play it exaggeratedly is to go to Spotlight (system preferences) then confidentiality and add the system disk (Macintosh HD). Wait a few minutes, launch the pattern, go back to Spotlight and removes Macintosh HD from confidentiality, the system will start indexing the HD content which completely disturbs the rhythm of the pattern and makes it unusable for making music ! To make it work on an M1 I have to disable the maximum of background tasks like Spotlight, Wi-FI, etc. and it helps but doesn't solve the problem, a priority problem apparently coming from scsynth running on Monterey and Ventura on M1.

**Comment by smrg-lm** [comment]
> Pbind(\instrument, \imp, \dur, 0.05).play;

With that pattern running, does the post window show any kind of message when this happens, something link late bundle or so? I can't test in a mac, if there is a late message in the post window sc could be working fine and the problem is excessive system load. To check the issue more info would be needed, the post window and maybe system configuration (which I can't help with).

**Comment by Josemiguelfernandez** [comment]
Hello,

I have done new tests with direct OSC messages (ASAP) and OSC TimeTag messages with Pbin or `(instrument: \imp).play()`.
In my setup which comes from the Intel version, the `.latency` was set to 0.045 which on an Intel MacBook does not cause interruptions but on my MacBook Pro M1 it does. With OSC TimeTag I have the `late` message...
Which leads me to the conclusion that scsynth on a Macintel works differently than on an M1.

Talking to a software developer who works with real time applications, he told me that the M1 architecture is different from intel's, especially in what is called Quality of Service (QoS):
In Apple silicon, the QoS class of a task influences whether the system runs that task on a performance core (P-core) or an efficiency core (E-core). For example, the system is more likely to run background tasks on E cores to maximise battery life. If you do not assign QoS classes, the responsiveness and efficiency of your application may suffer. See the explanation here:

https://developer.apple.com/documentation/apple-silicon/tuning-your-code-s-performance-for-apple-silicon

This could explain that when the system does a hard disk indexing or other background task, scsynth becomes less accuracy, because maybe scsynth is running on a non priority thread?

I don't know if doing this SC optimisation for M1 is very complicated, I'm not a developer, but apparently it could be the key to make SC work at least as well as before on a MacIntel, or maybe better?

Thanks !

José

**Comment by Spacechild1** [comment]
Probably related: https://github.com/supercollider/supercollider/issues/5624

I finally have access to a modern MacBook, so I might give it a shot.

**Comment by dyfer** [comment]
> Maybe the CoreAudio backend needs to assign the audio thread to an audio workgroup?

That may well be the case, but I'm not sure whether it's related to the problem reported here.

My thinking is: if the irregularities in the server create timing issues and not audio dropouts, this pertains either to the non-audio thread that does OSC processing (OSC processing is done on a non-RT thread, right?), or to the timing of _sending_ of OSC messages. However, the latter is not likely the case if the problem goes away with supernova, as @Josemiguelfernandez reported.

**Comment by Spacechild1** [comment]
Ah, sorry, I misread the issue description. I thought it was about the audio thread...

I had a quick look at the networking code. Both scsynth and supernova use asynchronous networking with `boost::asio`. For this they have to start a network thread that runs the `io_service`.

Supernova:
https://github.com/supercollider/supercollider/blob/da073949ed5021a5d59490bb061fbfcee0b395e8/server/supernova/utilities/osc_server.hpp#L51-L60

Scsynth:
https://github.com/supercollider/supercollider/blob/da073949ed5021a5d59490bb061fbfcee0b395e8/server/scsynth/SC_ComPort.cpp#L445-L456

Both versions try to set a high priority that is a bit lower than that of the audio thread. Note that `NOVA_TT_PRIORITY_RT` may *not* be defined for macOS. In that case, the behavior differs between supernova and scsynth! Supernova would simply do nothing. Scsynth, on the other hand, would assign a non-realtime priority! In fact, `thread_priority_interval` always returns a pair of (0, 0)! See https://github.com/timblechmann/nova-tt/blob/55da93741e76632579b63004d3378139e32d634f/nova-tt/thread_priority_mach.hpp#L51

@Josemiguelfernandez Can you check whether `NOVA_TT_PRIORITY_RT` is defined in your case? Just add something like `#error foo` inside one of the `#ifdef NOVA_TT_PRIORITY_RT` clauses above and see if it compiles.

**Comment by Josemiguelfernandez** [comment]
Thanks @Spacechild1 !

I don't know if I understood correctly but:  
- adding `#error foo` after `#ifdef NOVA_TT_PRIORITY_RT` (after line 448) compiles fine, no problem. 
- adding `#error foo` after `#else` (after line 451) does not compile ** BUILD FAILED **
- adding `#error foo` after `#endif`  (after line 455) does not compile ** BUILD FAILED ** 

Otherwise someone else has told me this which may help:
" there are 2 priority management systems :

 - the standard POSIX system based on pthread_setschedparam()

 - the Apple qos system based on pthread_set_qos_class_self_np()

Both systems are exclusive. If you use the standard system, it disables the qos system (for the current thread). A priori, it is better to use the qos system which is aware of the distinction between efficient and energy-saving cores.

In qos mode, you have 5 QOS classes (and not only 3 as in standard mode):

       QOS_CLASS_USER_INITIATED : the most reactive
       QOS_CLASS_DEFAULT : default
       QOS_CLASS_UTILITY: low reactive "server" type calculation
       QOS_CLASS_BACKGROUND: background calculation task
       QOS_CLASS_UNSPECIFIED : managed in standard not in qos

And the priority goes from -15 to 0 (0 is the maximum priority).
We have to see if scsynth is also in the right class and in maximum priority. But it should be.
"

I hope this helps!

**Comment by Josemiguelfernandez** [comment]
I just put these lines in comments (from 449 to 451)
```
// #else
//    std::pair<int, int> priorities = nova::thread_priority_interval();
//    nova::thread_set_priority(priorities.second);
```
And it works much better !!
Thank you for pointing out the difference with supernova @Spacechild1 ! 
I have reactivated Spotlight and tried other background tasks (switching apps, etc) and there are no interruptions. 
It's still not like a macintel where I could send very fast rhythms without interruptions. If I send fast beats (0.01s) there are still very small interruptions, but it's a big step!
Thanks a lot for the help @Spacechild1, @dyfer and @smrg-lm  ! 
I hope this part of OSC reception in scsynth and supernova can be improved in a more elegant way with a macOS threads and priority implementation using the possibility of P cores to allow more accurate client-server synchronization and without latency.

Best,

José

**Comment by Spacechild1** [comment]
@Josemiguelfernandez Thanks for checking! So my suspicion was correct: on macOS, scsynth accidentally sets a *lower* thread priority than the default! As a first fix, the scsynth version could be changed to match the supernova version. But you're right that we should also consider using the more recent APIs. We could choose the apprioriate strategy at runtime, e.g. by trying to dlopen `pthread_set_qos_class_self_np`, so that we wouldn't need to build and ship different versions of SuperCollider.

> If I send fast beats (0.01s) there are still very small interruptions, but it's a big step!

Is there still a difference to Supernova?

As a side note, your example code in the issue description does not use OSC bundles with timetags. Generally, there will always be some sort of network jitter and - more importantly - language jitter, so you cannot really expect precise timing without OSC bundles anyway.

**Comment by Josemiguelfernandez** [comment]
Thanks @Spacechild1 !

> Is there still a difference to Supernova?

I think it is the same. 
You are right that sending an OSC bundle timetag completely solves the problem. With a server latency of 0.015s I manage to send messages every 1 ms (and even less) without any interruptions or `late` messages !

Otherwise, I have found also in the resyncThreadFunc() the same priority problem:


https://github.com/supercollider/supercollider/blob/da073949ed5021a5d59490bb061fbfcee0b395e8/server/scsynth/SC_CoreAudio.cpp#L109-L116

If I comment lines as in the example above there is a big improvement in e.g. loading buffers or treat buffers (Flucoma) into scsynth. In the unmodified version, loading several buffers at the same time takes a long time because it is done on a low priority thread. With the modified version reading lots of sounds to scsynth buffers is almost instantaneous ! 

It would be great if SC could use the ad-doc API for these important parts and use high priority threads for the Apple P-cores.

**Comment by Josemiguelfernandez** [comment]
I forgot this one too :

https://github.com/supercollider/supercollider/blob/da073949ed5021a5d59490bb061fbfcee0b395e8/server/scsynth/SC_CoreAudio.cpp#L347-L354

**Comment by Spacechild1** [comment]
Ok. As a tentative fix we should remove all occurances of
```
std::pair<int, int> priorities = nova::thread_priority_interval(); 
nova::thread_set_priority(priorities.second); 
```
as this accidentally *lowers* the thread priority instead of raising it. I can make a PR for that (unless you want to do it).

The next step would be to update `nova-tt` so that it would use the more recent Apple APIs (if available).

**Comment by Josemiguelfernandez** [comment]
>  I can make a PR for that (unless you want to do it).

Please, go ahead!
> The next step would be to update nova-tt so that it would use the more recent Apple APIs (if available).

Thanks @Spacechild1 !! If I can help in any way, let me know !

**Comment by samaaron** [comment]
Just a quick aside to say *amazing work everyone!*. 

Thanks so much for your attention to detail and persistence to continue getting this tricky stuff working well.

Huge love.

**Comment by Spacechild1** [comment]
Note to myself: make a PR!
