### ISSUE TITLE
Uploading artifacts to S3 storage is broken

### ISSUE THREAD

**Issue by dyfer** [supercollider/supercollider#5978]
## Environment

* SuperCollider version: all
* Operating system: all
* Other details (Qt version, audio driver, etc.): n/a

## Steps to reproduce

The upload of artifacts to the S3 storage seems to be broken: https://github.com/supercollider/supercollider/actions/runs/4158888148/jobs/7194764418#step:6:25

## Expected vs. actual behavior

If we want to keep uploading to S3, the person with appropriate knowledge needs to look into this. Otherwise we can remove upload to S3, but then we'd want to provide an alternative method of downloading latest develop builds. One candidate is https://nightly.link, but it's not as elegant as providing a direct fixed URL, the way we do now.

**Comment by dyfer** [comment]
@scztt do you have any insight into this?

**Comment by scztt** [comment]
This should be resolved now - let me know if there are further problems? Apologies for the delay here, it took a while to figure out what was failing on the Amazon side (and resolve it...)

**Comment by dyfer** [comment]
Yes, it [works](https://github.com/supercollider/supercollider/actions/runs/4401489752/jobs/7774057696)! Thank you @scztt !
