### ISSUE TITLE
Sc 13.3 legacy doesn't start on mac osx 10.13.6

### ISSUE THREAD

**Issue by GiuseppeGui** [supercollider/supercollider#5985]
Hi everyone, I have Mac OS 10.13.6 and installed sc 13.3 legacy. When I start I have this error :

compiling class library…
Found 855 primitives.
Compiling directory ‘/Applications/SuperCollider.app/Contents/Resources/SCClassLibrary’
Compiling directory ‘/Users/pepgui/Library/Application Support/SuperCollider/Extensions’
numentries = 839396 / 12644580 = 0.066
5590 method selectors, 2262 classes
method table size 13500544 bytes, big table size 101156640
Number of Symbols 12524
Byte Code Size 382249
compiled 329 files in 1.69 seconds
compile done
localhost : setting clientID to 0.
internal : setting clientID to 0.
Class tree inited in 0.03 seconds

*** Welcome to SuperCollider 3.13.0. *** For help press Cmd-D.
SCDoc: Indexing help-files…
SCDoc: Indexed 1367 documents in 2.64 seconds
Booting server ‘localhost’ on address 127.0.0.1:57110.
Server ‘localhost’ exited with exit code 0.

This is the crash report:

Process: scsynth [737]
Path: /Applications/SuperCollider.app/Contents/Resources/…/Resources/scsynth
Identifier: scsynth
Version: 0
Code Type: X86-64 (Native)
Parent Process: sclang [731]
Responsible: scsynth [737]
User ID: 501

Date/Time: 2023-02-23 13:51:40.080 +0100
OS Version: Mac OS X 10.13.6 (17G66)
Report Version: 12
Anonymous UUID: 9A92C8F0-C6F3-B6E3-63D0-41EDB344AB32

Time Awake Since Boot: 950 seconds

System Integrity Protection: enabled

Crashed Thread: 0 Dispatch queue: com.apple.main-thread

Exception Type: EXC_BAD_ACCESS (SIGBUS)
Exception Codes: KERN_PROTECTION_FAILURE at 0x000000010535c000
Exception Note: EXC_CORPSE_NOTIFY

Termination Signal: Bus error: 10
Termination Reason: Namespace SIGNAL, Code 0xa
Terminating Process: exc handler [0]

VM Regions Near 0x10535c000:
__LINKEDIT 000000010535a000-000000010535c000 [ 8K] rw-/rwx SM=NUL /Applications/SuperCollider.app/Contents/Resources/plugins/PV_ThirdParty.scx
→ __TEXT 000000010535c000-000000010536c000 [ 64K] r-x/rwx SM=COW /Applications/SuperCollider.app/Contents/Resources/plugins/OscUGens.scx
__DATA 000000010536c000-0000000105370000 [ 16K] rw-/rwx SM=COW /Applications/SuperCollider.app/Contents/Resources/plugins/OscUGens.scx

Application Specific Information:
dyld: in dlopen()

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0 OscUGens.scx 0x0000000105361c08 SinOsc_Ctor + 8
1 dyld 0x0000000107f18c5c ImageLoader::link(ImageLoader::LinkContext const&, bool, bool, bool, ImageLoader::RPathChain const&, char const*) + 260
2 dyld 0x0000000107f0cf6a dyld::link(ImageLoader*, bool, bool, ImageLoader::RPathChain const&, unsigned int) + 161
3 dyld 0x0000000107f16046 dlopen + 429
4 libdyld.dylib 0x00007fff640cbd86 dlopen + 86
5 scsynth 0x0000000102aa20a6 PlugIn_LoadDir(boost::filesystem::path const&, bool) + 422
6 scsynth 0x0000000102aa1a23 initialize_library(char const*) + 963
7 scsynth 0x0000000102ac0105 World_New + 597
8 scsynth 0x0000000102a74935 scsynth_main(int, char**) + 2037
9 libdyld.dylib 0x00007fff640ca015 start + 1

Thread 1:
0 libsystem_kernel.dylib 0x00007fff6421b28a __workq_kernreturn + 10
1 libsystem_pthread.dylib 0x00007fff643e2009 _pthread_wqthread + 1035
2 libsystem_pthread.dylib 0x00007fff643e1be9 start_wqthread + 13

Thread 2:
0 libsystem_kernel.dylib 0x00007fff6421b28a __workq_kernreturn + 10
1 libsystem_pthread.dylib 0x00007fff643e2009 _pthread_wqthread + 1035
2 libsystem_pthread.dylib 0x00007fff643e1be9 start_wqthread + 13

Thread 3:
0 libsystem_kernel.dylib 0x00007fff6421b28a __workq_kernreturn + 10
1 libsystem_pthread.dylib 0x00007fff643e220e _pthread_wqthread + 1552
2 libsystem_pthread.dylib 0x00007fff643e1be9 start_wqthread + 13

Thread 4:
0 libsystem_pthread.dylib 0x00007fff643e1bdc start_wqthread + 0

Thread 5:
0 libsystem_kernel.dylib 0x00007fff6421ad82 __semwait_signal + 10
1 libsystem_c.dylib 0x00007fff64195724 nanosleep + 199
2 libc++.1.dylib 0x00007fff62062934 std::__1::this_thread::sleep_for(std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> > const&) + 73
3 UIUGens.scx 0x00000001031a56d6 gstate_update_func() + 198
4 UIUGens.scx 0x00000001031a6248 void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_deletestd::__1::__thread_struct >, void ()()> >(void) + 40
5 libsystem_pthread.dylib 0x00007fff643e2661 _pthread_body + 340
6 libsystem_pthread.dylib 0x00007fff643e250d _pthread_start + 377
7 libsystem_pthread.dylib 0x00007fff643e1bf9 thread_start + 13

Thread 6:
0 libsystem_kernel.dylib 0x00007fff6421aa16 __psynch_cvwait + 10
1 libsystem_pthread.dylib 0x00007fff643e3589 _pthread_cond_wait + 732
2 libc++.1.dylib 0x00007fff62021cb0 std::__1::condition_variable::wait(std::__1::unique_lockstd::__1::mutex&) + 18
3 DiskIO_UGens.scx 0x00000001052c3834 void std::__1::condition_variable_any::wait<std::__1::unique_lockstd::__1::mutex >(std::__1::unique_lockstd::__1::mutex&) + 84
4 DiskIO_UGens.scx 0x00000001052c3539 (anonymous namespace)::DiskIOThread::ioThreadFunc() + 185
5 DiskIO_UGens.scx 0x00000001052c398e void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_deletestd::__1::__thread_struct >, std::__1::__bind<void ((anonymous namespace)::DiskIOThread::)(), (anonymous namespace)::DiskIOThread> > >(void*) + 62
6 libsystem_pthread.dylib 0x00007fff643e2661 _pthread_body + 340
7 libsystem_pthread.dylib 0x00007fff643e250d _pthread_start + 377
8 libsystem_pthread.dylib 0x00007fff643e1bf9 thread_start + 13

Thread 0 crashed with X86 Thread State (64-bit):
rax: 0x000000010535c000 rbx: 0x00007f9faed00030 rcx: 0x000000010535c420 rdx: 0x000000010535c468
rdi: 0x000000010535c000 rsi: 0x000000010535c000 rbp: 0x00007ffeed191340 rsp: 0x00007ffeed18f4f8
r8: 0x0000000000000074 r9: 0x00000000000004b0 r10: 0x0000000000031001 r11: 0x000000010305d908
r12: 0x00007f9faec5a350 r13: 0x0000000000000000 r14: 0x000000010535c000 r15: 0x0000000105361c08
rip: 0x0000000105361c08 rfl: 0x0000000000010293 cr2: 0x00007f9faf2950e8

Logical CPU: 0
Error Code: 0x02000131
Trap Number: 133

Binary Images:
0x102a6e000 - 0x102af1ff3 +scsynth (0) <12D9BBCC-B776-3166-8B9B-F6D1B7173C78> /Applications/SuperCollider.app/Contents/Resources/scsynth
0x102b73000 - 0x102dd2fff +libsndfile.1.dylib (0) <7F77FE4F-6CA2-35A0-A84D-082E03EF0EEE> /Applications/SuperCollider.app/Contents/Frameworks/libsndfile.1.dylib
0x1031a1000 - 0x1031a8ffb +UIUGens.scx (0) /Applications/SuperCollider.app/Contents/Resources/plugins/UIUGens.scx
0x1031b9000 - 0x1031ccfff +GrainUGens.scx (0) /Applications/SuperCollider.app/Contents/Resources/plugins/GrainUGens.scx
0x1031d9000 - 0x1031e4ff3 +PanUGens.scx (0) /Applications/SuperCollider.app/Contents/Resources/plugins/PanUGens.scx
0x105188000 - 0x10518bff7 +DynNoiseUGens.scx (0) /Applications/SuperCollider.app/Contents/Resources/plugins/DynNoiseUGens.scx
0x105198000 - 0x1051c3ff3 +DelayUGens.scx (0) <8CBEEADB-DDD8-388D-9FC0-310F3E8F015B> /Applications/SuperCollider.app/Contents/Resources/plugins/DelayUGens.scx
0x1051d4000 - 0x1051e3ff3 +MulAddUGens.scx (0) <5CE45CD8-38DA-35CE-9988-F187D270DAC0> /Applications/SuperCollider.app/Contents/Resources/plugins/MulAddUGens.scx
0x1051f0000 - 0x1051fbfff +DemandUGens.scx (0) <815CE013-FE9A-329B-9E8D-508C8495053D> /Applications/SuperCollider.app/Contents/Resources/plugins/DemandUGens.scx
0x105208000 - 0x10520bfff +PhysicalModelingUGens.scx (0) /Applications/SuperCollider.app/Contents/Resources/plugins/PhysicalModelingUGens.scx
0x105218000 - 0x105223ffb +FFT_UGens.scx (0) /Applications/SuperCollider.app/Contents/Resources/plugins/FFT_UGens.scx
0x105244000 - 0x10525fff3 +FilterUGens.scx (0) <337DA415-1B61-39BC-9E2E-F2A0A222C79A> /Applications/SuperCollider.app/Contents/Resources/plugins/FilterUGens.scx
0x10526c000 - 0x105277fff +ML_UGens.scx (0) /Applications/SuperCollider.app/Contents/Resources/plugins/ML_UGens.scx
0x1052a8000 - 0x1052afff7 +ChaosUGens.scx (0) <26F73098-4689-3827-A499-14123BB51682> /Applications/SuperCollider.app/Contents/Resources/plugins/ChaosUGens.scx
0x1052bc000 - 0x1052c3ffb +DiskIO_UGens.scx (0) <275B5FF7-820E-3C9D-ADB1-81C6DA167413> /Applications/SuperCollider.app/Contents/Resources/plugins/DiskIO_UGens.scx
0x1052d0000 - 0x1052d3ffb +TestUGens.scx (0) <1DF7A535-2CE7-3BE0-9490-8A2AC2335570> /Applications/SuperCollider.app/Contents/Resources/plugins/TestUGens.scx
0x1052e0000 - 0x1052f7fff +UnaryOpUGens.scx (0) <787C7C55-D896-3FD4-BF02-599D7A854E38> /Applications/SuperCollider.app/Contents/Resources/plugins/UnaryOpUGens.scx
0x105304000 - 0x105317ffb +LFUGens.scx (0) /Applications/SuperCollider.app/Contents/Resources/plugins/LFUGens.scx
0x105324000 - 0x105327ffb +UnpackFFTUGens.scx (0) <0EEF5A39-0D6B-3821-B903-4EBDF8C4A4A3> /Applications/SuperCollider.app/Contents/Resources/plugins/UnpackFFTUGens.scx
0x10533c000 - 0x105343ff3 +PV_ThirdParty.scx (0) /Applications/SuperCollider.app/Contents/Resources/plugins/PV_ThirdParty.scx
0x10535c000 - 0x10536bff7 +OscUGens.scx (0) /Applications/SuperCollider.app/Contents/Resources/plugins/OscUGens.scx
0x107f08000 - 0x107f52acf dyld (551.4) <8A72DE9C-A136-3506-AA02-4BA2B82DCAF3> /usr/lib/dyld
0x7fff38456000 - 0x7fff38456fff com.apple.Accelerate (1.11 - Accelerate 1.11) <2EF00EFE-06E8-3082-85C3-2988B422A19D> /System/Library/Frameworks/Accelerate.framework/Versions/A/Accelerate
0x7fff3846f000 - 0x7fff38bbdffb com.apple.vImage (8.1 - ???) <56C275C1-459F-37CD-BF29-2E6D81C29E53> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vImage.framework/Versions/A/vImage
0x7fff38bbe000 - 0x7fff38d5eff3 libBLAS.dylib (1211.50.2) <93259222-2D94-333D-A1EB-09C6FC4A64B4> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
0x7fff38d5f000 - 0x7fff38d99fef libBNNS.dylib (38.1) <0AAE0109-71D5-3B26-8401-3E62DDF97624> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBNNS.dylib
0x7fff38d9a000 - 0x7fff39173ff7 libLAPACK.dylib (1211.50.2) <70781D0B-AEAD-33EB-9900-10DC30F37D61> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libLAPACK.dylib
0x7fff39174000 - 0x7fff3918aff7 libLinearAlgebra.dylib (1211.50.2) /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libLinearAlgebra.dylib
0x7fff3918b000 - 0x7fff39190ff3 libQuadrature.dylib (3) <3D6BF66A-55B2-3692-BAC7-DEB0C676ED29> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libQuadrature.dylib
0x7fff39191000 - 0x7fff39211fff libSparse.dylib (79.50.2) <0DC25CDD-F8C1-3D6E-B472-8B060708424F> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libSparse.dylib
0x7fff39212000 - 0x7fff39224ff7 libSparseBLAS.dylib (1211.50.2) <994A7D7E-FA3B-3943-A59C-8150B9AF86BE> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libSparseBLAS.dylib
0x7fff39225000 - 0x7fff39398fe7 libvDSP.dylib (622.50.5) <4BF310F4-31A3-3DA5-80E4-7F8014AD380B> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libvDSP.dylib
0x7fff39399000 - 0x7fff3944ffef libvMisc.dylib (622.50.5) <88143A88-4FDE-35A1-85FE-54FF0C2A9E43> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libvMisc.dylib
0x7fff39450000 - 0x7fff39450fff com.apple.Accelerate.vecLib (3.11 - vecLib 3.11) <880DEF40-389A-3F56-ACA1-B62A5BC57E59> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/vecLib
0x7fff39744000 - 0x7fff3a5a2fff com.apple.AppKit (6.9 - 1561.60.100) <3C27CF6F-E640-3411-A87D-CCB2222CC754> /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
0x7fff3a5f4000 - 0x7fff3a5f4fff com.apple.ApplicationServices (48 - 50) /System/Library/Frameworks/ApplicationServices.framework/Versions/A/ApplicationServices
0x7fff3a5f5000 - 0x7fff3a65bfff com.apple.ApplicationServices.ATS (377 - 445.4) <85E779EE-0219-3181-B4C4-201E4CC82AB5> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/ATS.framework/Versions/A/ATS
0x7fff3a6f4000 - 0x7fff3a816fff libFontParser.dylib (222.1.6) <6CEBACDD-B848-302E-B4B2-630CB16E663E> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/ATS.framework/Versions/A/Resources/libFontParser.dylib
0x7fff3a817000 - 0x7fff3a861ff7 libFontRegistry.dylib (221.4) <5FDB4F1A-E15C-3ACB-A5C1-F15458C0C6DC> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/ATS.framework/Versions/A/Resources/libFontRegistry.dylib
0x7fff3a9a3000 - 0x7fff3a9a7ff3 com.apple.ColorSyncLegacy (4.13.0 - 1) /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/ColorSyncLegacy.framework/Versions/A/ColorSyncLegacy
0x7fff3aa47000 - 0x7fff3aa99ffb com.apple.HIServices (1.22 - 624.1) <66FD9ED2-9630-313C-86AE-4C2FBCB3F351> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/HIServices.framework/Versions/A/HIServices
0x7fff3aa9a000 - 0x7fff3aaa8fff com.apple.LangAnalysis (1.7.0 - 1.7.0) /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/LangAnalysis.framework/Versions/A/LangAnalysis
0x7fff3aaa9000 - 0x7fff3aaf5fff com.apple.print.framework.PrintCore (13.4 - 503.2) /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/PrintCore.framework/Versions/A/PrintCore
0x7fff3aaf6000 - 0x7fff3ab30fff com.apple.QD (3.12 - 404.2) <38B20AFF-9D54-3B52-A6DC-C0D71380AA5F> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/QD.framework/Versions/A/QD
0x7fff3ab31000 - 0x7fff3ab3dfff com.apple.speech.synthesis.framework (7.8.1 - 7.8.1) /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/SpeechSynthesis.framework/Versions/A/SpeechSynthesis
0x7fff3ab3e000 - 0x7fff3adccff7 com.apple.audio.toolbox.AudioToolbox (1.14 - 1.14) /System/Library/Frameworks/AudioToolbox.framework/Versions/A/AudioToolbox
0x7fff3adce000 - 0x7fff3adcefff com.apple.audio.units.AudioUnit (1.14 - 1.14) /System/Library/Frameworks/AudioUnit.framework/Versions/A/AudioUnit
0x7fff3b0f1000 - 0x7fff3b48bff7 com.apple.CFNetwork (902.1 - 902.1) <76EB8CB6-BF59-3BDA-BF2B-F21B161611B9> /System/Library/Frameworks/CFNetwork.framework/Versions/A/CFNetwork
0x7fff3b4a5000 - 0x7fff3b7aafff com.apple.HIToolbox (2.1.1 - 911.10) /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/HIToolbox.framework/Versions/A/HIToolbox
0x7fff3b7b5000 - 0x7fff3b84affb com.apple.ink.framework (10.9 - 221) <5206C8B0-22DA-36C9-998E-846EDB626D5B> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/Ink.framework/Versions/A/Ink
0x7fff3b88b000 - 0x7fff3b891fff com.apple.speech.recognition.framework (6.0.3 - 6.0.3) <2ED8643D-B0C3-3F17-82A2-BBF13E6CBABC> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/SpeechRecognition.framework/Versions/A/SpeechRecognition
0x7fff3b9c0000 - 0x7fff3ba79fff com.apple.ColorSync (4.13.0 - 3325) /System/Library/Frameworks/ColorSync.framework/Versions/A/ColorSync
0x7fff3bc06000 - 0x7fff3bc99ff7 com.apple.audio.CoreAudio (4.3.0 - 4.3.0) /System/Library/Frameworks/CoreAudio.framework/Versions/A/CoreAudio
0x7fff3bd00000 - 0x7fff3bd29ffb com.apple.CoreBluetooth (1.0 - 1) /System/Library/Frameworks/CoreBluetooth.framework/Versions/A/CoreBluetooth
0x7fff3bd2a000 - 0x7fff3c08eff3 com.apple.CoreData (120 - 851) <8D605466-8676-3D45-9A4B-8980971551C3> /System/Library/Frameworks/CoreData.framework/Versions/A/CoreData
0x7fff3c08f000 - 0x7fff3c172fff com.apple.CoreDisplay (99.14 - 99.14) /System/Library/Frameworks/CoreDisplay.framework/Versions/A/CoreDisplay
0x7fff3c173000 - 0x7fff3c60dff7 com.apple.CoreFoundation (6.9 - 1454.90) /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
0x7fff3c60f000 - 0x7fff3cc3dff7 com.apple.CoreGraphics (2.0 - 1161.21) /System/Library/Frameworks/CoreGraphics.framework/Versions/A/CoreGraphics
0x7fff3cc3f000 - 0x7fff3cf2efff com.apple.CoreImage (13.0.0 - 579.5) /System/Library/Frameworks/CoreImage.framework/Versions/A/CoreImage
0x7fff3d303000 - 0x7fff3d303fff com.apple.CoreServices (822.36 - 822.36) /System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices
0x7fff3d304000 - 0x7fff3d378ffb com.apple.AE (735.1 - 735.1) <08EBA184-20F7-3725-AEA6-C314448161C6> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/AE.framework/Versions/A/AE
0x7fff3d379000 - 0x7fff3d650fff com.apple.CoreServices.CarbonCore (1178.4 - 1178.4) <0D5E19BF-18CB-3FA4-8A5F-F6C787C5EE08> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/CarbonCore.framework/Versions/A/CarbonCore
0x7fff3d651000 - 0x7fff3d685fff com.apple.DictionaryServices (1.2 - 284.2) <6505B075-41C3-3C62-A4C3-85CE3F6825CD> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/DictionaryServices.framework/Versions/A/DictionaryServices
0x7fff3d686000 - 0x7fff3d68effb com.apple.CoreServices.FSEvents (1239.50.1 - 1239.50.1) <3637CEC7-DF0E-320E-9634-44A442925C65> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/FSEvents.framework/Versions/A/FSEvents
0x7fff3d68f000 - 0x7fff3d84cfff com.apple.LaunchServices (822.36 - 822.36) <6E68C090-B12D-3D3D-9617-E5D82C36B2D0> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/LaunchServices.framework/Versions/A/LaunchServices
0x7fff3d84d000 - 0x7fff3d8fdff7 com.apple.Metadata (10.7.0 - 1191.4.13) /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/Metadata.framework/Versions/A/Metadata
0x7fff3d8fe000 - 0x7fff3d95efff com.apple.CoreServices.OSServices (822.36 - 822.36) <3BB2E0CE-81AE-3D3D-9FCE-E1B7FC6D6A61> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/OSServices.framework/Versions/A/OSServices
0x7fff3d95f000 - 0x7fff3d9cdfff com.apple.SearchKit (1.4.0 - 1.4.0) <3662545A-B1CF-3079-BDCD-C83855CEFEEE> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/SearchKit.framework/Versions/A/SearchKit
0x7fff3d9ce000 - 0x7fff3d9f2ffb com.apple.coreservices.SharedFileList (71.21 - 71.21) <35582D88-5975-35E2-A29A-E3148C3EE727> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/SharedFileList.framework/Versions/A/SharedFileList
0x7fff3dc93000 - 0x7fff3dde3fff com.apple.CoreText (352.0 - 578.22) <6129F39D-284D-3BBF-8999-7854AB61C01C> /System/Library/Frameworks/CoreText.framework/Versions/A/CoreText
0x7fff3dde4000 - 0x7fff3de1efff com.apple.CoreVideo (1.8 - 0.0) <86CCC036-51BB-3DD1-9601-D93798BCCD0F> /System/Library/Frameworks/CoreVideo.framework/Versions/A/CoreVideo
0x7fff3de1f000 - 0x7fff3deaaff3 com.apple.framework.CoreWLAN (13.0 - 1350.1) /System/Library/Frameworks/CoreWLAN.framework/Versions/A/CoreWLAN
0x7fff3e125000 - 0x7fff3e12afff com.apple.DiskArbitration (2.7 - 2.7) /System/Library/Frameworks/DiskArbitration.framework/Versions/A/DiskArbitration
0x7fff3e2eb000 - 0x7fff3e6b1fff com.apple.Foundation (6.9 - 1454.90) <8EA924F3-ADAE-3F4B-8482-8B11C027D9A5> /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation
0x7fff3e722000 - 0x7fff3e752fff com.apple.GSS (4.0 - 2.0) /System/Library/Frameworks/GSS.framework/Versions/A/GSS
0x7fff3e864000 - 0x7fff3e968ffb com.apple.Bluetooth (6.0.7 - 6.0.7f10) <557F26F9-C7A0-34EA-A905-22E243BF6B48> /System/Library/Frameworks/IOBluetooth.framework/Versions/A/IOBluetooth
0x7fff3e9c8000 - 0x7fff3ea63fff com.apple.framework.IOKit (2.0.2 - 1445.71.1) <2EA4F383-CAA9-3AF0-99C5-90C22ADAA6B6> /System/Library/Frameworks/IOKit.framework/Versions/A/IOKit
0x7fff3ea65000 - 0x7fff3ea6cfff com.apple.IOSurface (211.15 - 211.15) <9FD406F1-6BF2-35B0-8339-DF83A1A661EB> /System/Library/Frameworks/IOSurface.framework/Versions/A/IOSurface
0x7fff3eac3000 - 0x7fff3ec40fff com.apple.ImageIO.framework (3.3.0 - 1739.3) <86D14377-8F57-387E-982E-2EF60EE41E2F> /System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO
0x7fff3ec41000 - 0x7fff3ec45ffb libGIF.dylib (1739.3) /System/Library/Frameworks/ImageIO.framework/Versions/A/Resources/libGIF.dylib
0x7fff3ec46000 - 0x7fff3ed2dfff libJP2.dylib (1739.3) <3C1150F8-4983-3380-9B8C-5021AD972FFE> /System/Library/Frameworks/ImageIO.framework/Versions/A/Resources/libJP2.dylib
0x7fff3ed2e000 - 0x7fff3ed51fff libJPEG.dylib (1739.3) /System/Library/Frameworks/ImageIO.framework/Versions/A/Resources/libJPEG.dylib
0x7fff3f02e000 - 0x7fff3f054ff3 libPng.dylib (1739.3) <97A8B816-7A79-3CB8-9D47-CCDC19B84E2F> /System/Library/Frameworks/ImageIO.framework/Versions/A/Resources/libPng.dylib
0x7fff3f055000 - 0x7fff3f057ff3 libRadiance.dylib (1739.3) <47A0D85B-8AE8-3FF2-9C13-279550850A24> /System/Library/Frameworks/ImageIO.framework/Versions/A/Resources/libRadiance.dylib
0x7fff3f058000 - 0x7fff3f0a5ff3 libTIFF.dylib (1739.3) <9833CCBB-48FB-3E7B-A11A-F2F331FD094D> /System/Library/Frameworks/ImageIO.framework/Versions/A/Resources/libTIFF.dylib
0x7fff3ff5f000 - 0x7fff3ff78ff7 com.apple.Kerberos (3.0 - 1) /System/Library/Frameworks/Kerberos.framework/Versions/A/Kerberos
0x7fff4095a000 - 0x7fff409dbfff com.apple.Metal (125.30 - 125.30) <975FD6B5-D695-346A-869F-0584A968D100> /System/Library/Frameworks/Metal.framework/Versions/A/Metal
0x7fff409f8000 - 0x7fff40a13fff com.apple.MetalPerformanceShaders.MPSCore (1.0 - 1) /System/Library/Frameworks/MetalPerformanceShaders.framework/Frameworks/MPSCore.framework/Versions/A/MPSCore
0x7fff40a14000 - 0x7fff40a83fef com.apple.MetalPerformanceShaders.MPSImage (1.0 - 1) <338B7779-E608-3D68-8A07-2ACC11299744> /System/Library/Frameworks/MetalPerformanceShaders.framework/Frameworks/MPSImage.framework/Versions/A/MPSImage
0x7fff40a84000 - 0x7fff40aa8fff com.apple.MetalPerformanceShaders.MPSMatrix (1.0 - 1) <9CE072D7-853B-3939-9645-7EB951376B87> /System/Library/Frameworks/MetalPerformanceShaders.framework/Frameworks/MPSMatrix.framework/Versions/A/MPSMatrix
0x7fff40aa9000 - 0x7fff40b90ff7 com.apple.MetalPerformanceShaders.MPSNeuralNetwork (1.0 - 1) <0DE891AD-27E5-38FF-AEC8-4A95356C4357> /System/Library/Frameworks/MetalPerformanceShaders.framework/Frameworks/MPSNeuralNetwork.framework/Versions/A/MPSNeuralNetwork
0x7fff40b91000 - 0x7fff40b91ff7 com.apple.MetalPerformanceShaders.MetalPerformanceShaders (1.0 - 1) <2D2D261C-50B0-32F9-BF9A-5C01382BB528> /System/Library/Frameworks/MetalPerformanceShaders.framework/Versions/A/MetalPerformanceShaders
0x7fff41b90000 - 0x7fff41b9cffb com.apple.NetFS (6.0 - 4.0) <471DD96F-FA2E-3FE9-9746-2519A6780D1A> /System/Library/Frameworks/NetFS.framework/Versions/A/NetFS
0x7fff4498e000 - 0x7fff449e8ff7 com.apple.opencl (2.8.24 - 2.8.24) <4D7401A7-6ADD-3632-85AE-7A5012DFFA04> /System/Library/Frameworks/OpenCL.framework/Versions/A/OpenCL
0x7fff449e9000 - 0x7fff44a05ffb com.apple.CFOpenDirectory (10.13 - 207.50.1) <29F55F7B-379F-3053-8FF3-5C6675A3DD4D> /System/Library/Frameworks/OpenDirectory.framework/Versions/A/Frameworks/CFOpenDirectory.framework/Versions/A/CFOpenDirectory
0x7fff44a06000 - 0x7fff44a11fff com.apple.OpenDirectory (10.13 - 207.50.1) /System/Library/Frameworks/OpenDirectory.framework/Versions/A/OpenDirectory
0x7fff45b90000 - 0x7fff45b92fff libCVMSPluginSupport.dylib (16.7.4) /System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libCVMSPluginSupport.dylib
0x7fff45b93000 - 0x7fff45b98ffb libCoreFSCache.dylib (162.9) <7AF87F3E-D5D0-3625-BE09-CA4223195466> /System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libCoreFSCache.dylib
0x7fff45b99000 - 0x7fff45b9dfff libCoreVMClient.dylib (162.9) <115FE643-6141-39B4-8193-77DFCBE7A4E0> /System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libCoreVMClient.dylib
0x7fff45b9e000 - 0x7fff45ba7ff3 libGFXShared.dylib (16.7.4) /System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libGFXShared.dylib

It seem there is a problem with oscugens.scx and other .scx files , searching on the web i have found this

[Servers built with XCode 11+ crash on macOS 10.13, 10.14 · Issue #5318 · supercollider/supercollider · GitHub](https://github.com/supercollider/supercollider/issues/5318)

Thankyou all for your help

**Comment by dyfer** [comment]
Thank you for the report!

We have JUST fixed the legacy build. Please re-download and try again.

**Comment by GiuseppeGui** [comment]
Hey it works. thankyou all guys!
