### ISSUE TITLE
building on macOS 12.6, PhaseScriptExecution CMake PostBuild Rules failed

### ISSUE THREAD

**Issue by telephon** [supercollider/supercollider#5996]
## Environment

* SuperCollider version: latest build
* Operating system: 
* Other details (Qt version, audio driver, etc.):

## Steps to reproduce

following the usual build steps on macOS, cmake works, but the build fails with:

```
The following build commands failed:
PhaseScriptExecution CMake\ PostBuild\ Rules
<…>
 FTUGens.build/RelWithDebInfo/Script-957DED8BEED535BDE11472B3.sh (in target 'UnpackFFTUGens' from project 'SuperCollider')
```

**Comment by dyfer** [comment]
Hello @telephon 
I just tried to build on macOS 12.6 with Xcode 14.0 and it seems to work for me.
Which Xcode and macOS versions are you running?
One thing I keep running into is that you may not have qt6 (aka "qt") installed _and linked_ in homebrew (`brew unlink qt` does the trick), but your error doesn't seem to be related to that.
A full output of the build step might be helpful (maybe wrapped in `<details> </details>` or as an attachment).

**Comment by dyfer** [comment]
No, we don't need qt6 - actually we don't support it (it doesn't work) yet. I'm just pointing it out since one might accidentally install it with `brew install qt`, which now points to qt6.
