### ISSUE TITLE
MIDIClient.init causes ERROR: Primitive '__none' failed.

### ISSUE THREAD

**Issue by nuss** [supercollider/supercollider#5997]
## Environment

* SuperCollider version: 3.13.0-rc3
* Operating system: Debian 11
* Other details (Qt version, audio driver, etc.): 

## Steps to reproduce

```supercollider
(
MIDIClient.init;
MIDIClient.list;
)
```

## Expected vs. actual behavior
`MIDIClient` should execute its `init` method and list initialized sources and destiantions. 

```
ERROR: A primitive was not bound. 0 854
Instance of Method {    (0x5571e3602e40, gc=01, fmt=00, flg=11, set=04)
  instance variables [15]
    raw1 : Float 0.000000   00000000 0060000C
    raw2 : Float 0.000000   00000100 01000001
    code : instance of Int8Array (0x5571e3602fc0, size=4, set=2)
    selectors : nil
    constants : nil
    prototypeFrame : instance of Array (0x5571d8c3bc00, size=1, set=2)
    context : nil
    argNames : instance of SymbolArray (0x5571d8c3bcc0, size=1, set=2)
    varNames : nil
    sourceCode : nil
    ownerClass : class Meta_MIDIClient (0x5571e35ff500)
    name : Symbol 'prInitClient'
    primitiveName : Symbol '_InitMIDIClient'
    filenameSymbol : Symbol '/usr/local/share/SuperCollider/SCClassLibrary/Common/Control/MIDIOut.sc'
    charPos : Integer 1973
}
ERROR: Primitive '__none' failed.
Failed.
RECEIVER:
   nil
PATH: /home/stefan/.local/share/SuperCollider/Extensions/CVCenterKeyboard/CVCenterKeyboard.sc
CALL STACK:
	MethodError:reportError
		arg this = <instance of PrimitiveFailedError>
	Nil:handleError
		arg this = nil
		arg error = <instance of PrimitiveFailedError>
	Thread:handleError
		arg this = <instance of Thread>
		arg error = <instance of PrimitiveFailedError>
	Object:throw
		arg this = <instance of PrimitiveFailedError>
	Object:primitiveFailed
		arg this = nil
	Meta_MIDIClient:init
		arg this = <instance of Meta_MIDIClient>
		arg inports = nil
		arg outports = nil
		arg verbose = true
	Interpreter:interpretPrintCmdLine
		arg this = <instance of Interpreter>
		var res = nil
		var func = <instance of Function>
		var code = "MIDIClient.init"
		var doc = nil
		var ideClass = <instance of Meta_ScIDE>
	Process:interpretPrintCmdLine
		arg this = <instance of Main>
^^ The preceding error dump is for ERROR: Primitive '__none' failed.
Failed.
RECEIVER: nil
```

**Comment by nuss** [comment]
As I just found out this issue affects SC 3.12 too which I didn't expect. I have just set up my machine from scratch. I have never experienced the above described on my 'old' machine (Ubuntu Studio 22.04, SC 3.12.2). I'm pretty clueless what happened...

**Comment by dyfer** [comment]
I've seen weird behavior with the midi backend on macOS, that sometimes occurred when devices were added/removed from the system, but I'm not sure how much of that code is shared between OSs.

In any case, it seems that `MIDIClient.list` is meant for refreshing device list, not for printing a list of devices (they are automatically printed when running `MIDIClient.init`). In other words, there's no point in running it right after `MIDIClient.init`, IIUC. 

Does your error also occur if you just run `MIDIClient.init`?

**Comment by nuss** [comment]
Ok, that is probably true but the error occurs if I only call `MIDIClient.init`.

**Comment by dyfer** [comment]
Are you building SC from source? If so, can you confirm that the ALSA MIDI is found during configuration? ([see example here](https://github.com/supercollider/supercollider/actions/runs/4484322309/jobs/7884712897#step:8:94))

**Comment by nuss** [comment]
Mille Grazie, @dyfer ... I just had to install `libasound2-dev`. Don't know, is it maybe worth noting somewhere that Debian users will have to install that? (Just had a look: README says 'On Debian-like systems, the following command installs the minimal recommended dependencies for compiling scsynth and supernova:' but the given string doesn't include `libasound2-dev`. Neither is it mentioned anywhere else in the text. Maybe Debian it came with Debian 10, in Debian 11, however, it's missing. 

I'm gonna do a pull request and close this issue as completed. Thanks again!

**Comment by dyfer** [comment]
Thanks for pointing it out.

I see what's hapnnining there: these are recommended packages for the servers only! `libasound2-dev` is listed below, under "dependencies for sclang".

I think it would be good to combine these into one code block to avoid such misunderstandings.

**Comment by nuss** [comment]
Sorry, sorry!! I just found out myself... I was just about to update my last comment....

**Comment by nuss** [comment]
I also think the `apt install` sequences could be combined in one. Anyway, rtfm... Thanks!

**Comment by pHJosef** [comment]
I'm running into a very similar issue after building 3.13.1 from source on Ubuntu 24.04.


`MIDIClient.init;` returns:

```sc

ERROR: A primitive was not bound. 0 854
Instance of Method {    (0x59a67a22d000, gc=01, fmt=00, flg=11, set=04)
  instance variables [15]
    raw1 : Float 0.000000   00000000 0060000C
    raw2 : Float 0.000000   00000100 01000001
    code : instance of Int8Array (0x59a67a22d180, size=4, set=2)
    selectors : nil
    constants : nil
    prototypeFrame : instance of Array (0x59a677419d40, size=1, set=2)
    context : nil
    argNames : instance of SymbolArray (0x59a677419e00, size=1, set=2)
    varNames : nil
    sourceCode : nil
    ownerClass : class Meta_MIDIClient (0x59a67a2296c0)
    name : Symbol 'prInitClient'
    primitiveName : Symbol '_InitMIDIClient'
    filenameSymbol : Symbol '/usr/local/share/SuperCollider/SCClassLibrary/Common/Control/MIDIOut.sc'
    charPos : Integer 1973
}
ERROR: Primitive '__none' failed.
Failed.
RECEIVER:
   nil
CALL STACK:
	MethodError:reportError
		arg this = <instance of PrimitiveFailedError>
	Nil:handleError
		arg this = nil
		arg error = <instance of PrimitiveFailedError>
	Thread:handleError
		arg this = <instance of Thread>
		arg error = <instance of PrimitiveFailedError>
	Object:throw
		arg this = <instance of PrimitiveFailedError>
	Object:primitiveFailed
		arg this = nil
	Meta_MIDIClient:init
		arg this = <instance of Meta_MIDIClient>
		arg inports = nil
		arg outports = nil
		arg verbose = true
	Interpreter:interpretPrintCmdLine
		arg this = <instance of Interpreter>
		var res = nil
		var func = <instance of Function>
		var code = "MIDIClient.init"
		var doc = nil
		var ideClass = <instance of Meta_ScIDE>
	Process:interpretPrintCmdLine
		arg this = <instance of Main>
^^ The preceding error dump is for ERROR: Primitive '__none' failed.
Failed.
RECEIVER: nil
```


I have all required and recommended dependencies installed, including libasound2-dev (1.2.11-1build2).  Everything was working fine before on the same system and with SuperCollider 3.13.0 (I was using the official Ubuntu packge).  

When I rerun:

`sudo apt-get install git libasound2-dev libicu-dev libreadline6-dev libudev-dev pkg-config libncurses5-dev`

I get a hint that libreadline-dev instead of libreadline6-dev and libncurses-dev instead of libncurses5-dev are used. Could that be related?

I've already reinstalled libreadline-dev, libncurses-dev and libasound2-dev but that didn't help.

**Comment by jamshark70** [comment]
@pHJosef 

If you go to your build directory and run:

```
$ cmake .. -L
```

... does the following line appear in the output?

```
-- Compiling with ALSA midi support
```

If it doesn't appear, then that's the cause.

If it does, then it's possible that libasound2-dev wasn't found in your initial build, but could be found during this `cmake .. -L` run, after reinstalling that package. To test that, try `make` and `sudo make install` again.

In any case, I did try building SC 3.13.1-rc (the only 3.13.1 tag in the repository) -- on my machine, the ALSA lib is definitely found -- and `MIDIClient.init` has no problem. So I don't see evidence of a regression from 3.13.0 to 3.13.1, at least not on my machine.

So, for your problem, I'd suggest to look at cmake output first, to make sure it's really building with MIDI support.

**Comment by dyfer** [comment]
Thanks @jamshark70 for checking this!

> the only 3.13.1 tag in the repository)

Have you fetched tags from the remote?
https://github.com/supercollider/supercollider/tree/Version-3.13.1

**Comment by jamshark70** [comment]
> Have you fetched tags from the remote?

Oh, not in that repository. I've got 2 clones, one for stable versions and one for dev.

**Comment by pHJosef** [comment]
@jamshark70 thank you for testing!

`-- Compiling with ALSA midi support` appeared after running `cmake .. -L`, so I was building again and now it works. As I rebuilt already yesterday, it seems that running `cmake .. -L` after reinstalling libasound2-dev was needed to find the package, thanks!
