### ISSUE TITLE
Dictionary trueAt returns entry value not boolean if it exists

### ISSUE THREAD

**Issue by rumblesan** [supercollider/supercollider#6000]
## Environment

* SuperCollider version: 3.13.0
* Operating system: MacOS (though presumable all affected)

## Steps to reproduce

```supercollider
c = Dictionary.newFrom([\foo, 3])

if (c.trueAt(\foo), {"true".postln})
```
## Expected vs. actual behavior

This throws an error.

```
ERROR: Non Boolean in test.
RECEIVER:
   Integer 3
```

Looking at the code for `trueAt` this makes sense, but it's explicitly not what the docs say.

https://github.com/rumblesan/supercollider/blob/develop/SCClassLibrary/Common/Collections/Dictionary.sc#L25-L27
https://doc.sccode.org/Classes/Dictionary.html#-trueAt

Hapy to raise a PR to change either the dictionary code or the docs, but just want to make sure which it should be.

**Comment by rumblesan** [comment]
was not expecting a fix this quick hah. nice one 👍

**Comment by telephon** [comment]
It's an anniversary issue …

**Comment by nhthn** [comment]
I'm not convinced of the usefulness of `.trueAt` overall. What's so bad about writing `foo[\bar] == true`?

**Comment by telephon** [comment]
well, seemed like a good idea at the time …
