### ISSUE TITLE
instantiating a BPF with arrayed controls as arguments bricks coreaudio

### ISSUE THREAD

**Issue by mxw** [supercollider/supercollider#6017]
hey folks—i asked this as a question on the scsynth forums just now, but after some further testing i've become more confident that it's a scsynth bug.

in short, **the BPF UGen seems to break coreaudio on macOS when used with arrayed controls** in the `freq` and `rq` arguments. if i run the following short test case, all audio from all sources terminates as soon as the Synth is instantiated. subsequently, even if i shut down the scsynth server, my computer won't produce audio until i restart coreaudio (via `kill -9`).

```
(
s.waitForBoot({

SynthDef(\testcase, { |
  out = 0,
  gate = 1,
  buf,
  pan = 0.0,
  amp = 0.5
|
  var fbfreqs = \fbfreqs.ir({ |i| i * 440 } ! 2); // line A
  var fbrqs = \fbrqs.ir(1.0 ! 2); // line B

  var trig = Impulse.kr(10);
  var srate = BufRateScale.ir(buf);
  var grains = TGrains.ar(1, trig, buf, srate, 0.5, 0.5, 0.0, 1.0, 4);

  var fx = BPF.ar(grains, \fbfreqs[0], \fbrqs[0], 0.5); // line C
  var env = Env.adsr.kr(2, gate);

  var spatial = Pan2.ar(fx * env * amp, pan);
  Out.ar(0, spatial);
}).add;

~path = "/Users/mxawng/path-to-audio.WAV";
~noise = Buffer.readChannel(s, ~path, channels: [0]);

s.sync;

Synth(\testcase, [buf: ~noise]);

});
)
```

as far as i can tell, the issue is specific to BPF and arrayed controls. in particular, all of the following variations of the above code are unproblematic:
- replacing BPF with RLPF in line C (i didn't test other filters)
- replacing `\fbfreqs[0]` and `\fbrqs[0]` in line C with arrays of numbers: `var fx = BPF.ar(grains, [440, 880], [1.0, 1.0], 0.5);`
- replacing the arrayed controls with float controls:
```
var fbfreq = \fbfreq.ir(440); // line A
var fbrq = \fbrq.ir(1.0); // line B
...
var fx = BPF.ar(grains, \fbfreq, \fbrq, 0.5); // line C
```

contrariwise, the problem still persists regardless of the rate of the arrayed controls—all of `ir`, `kr`, and `ar` cause the same coreaudio failure.

### environment

- 2019 macbook pro (intel), macOS 12.6
- SC 3.12.2 (7c4c983)

**Comment by mxw** [comment]
a commenter pointed out my off-by-one—indeed it's the 0 freq that's bricking coreaudio. it seems odd to me that this should interfere with coreaudio in a way that persists beyond the lifetime of scsynth, even though the documentation does indicate problematic behavior near zero.

**Comment by dyfer** [comment]
Just to clarify, for me this does not _crash_ coreaudio, but only stops all audio processing (because of introducing NaNs to the coreaudio mixer). When I stop the synth, the audio comes back. I'm on macOS 12.6, SC 3.13.

**Comment by mxw** [comment]
for me, coreaudio does not crash, but stopping the synth (and even killing the server) does not resume processing; coreaudio remains stuck.

i didn't realize there was a version update past 3.12.2; i'll download 3.13.0 and try again to repro.

**Comment by mxw** [comment]
tried on 3.13.0 and the issue still repros.

**Comment by dyfer** [comment]
Yes, this behavior has not changed in 3.13. However, the fact that in your case audio doesn’t resume after stopping the synth is puzzling.
