### ISSUE TITLE
Localhost error supercollider

### ISSUE THREAD

**Issue by pi-314159265** [supercollider/supercollider#6038]
Bug description:

Steps to reproduce:
1. Error:
SC_PortAudioDriver: PortAudio failed at Pa_OpenStream with error: 'Unanticipated host error'
could not initialize audio.
Server 'localhost' exited with exit code -1073740791

**Comment by JordanHendersonMusic** [comment]
Closing because there isn't enough information in the issue to reproduce, feel free to edit the issue with more information following the wiki's guidelines and reopen!
