### ISSUE TITLE
Broken schelp link: FunctionDef: -makeFuncArgModifierString

### ISSUE THREAD

**Issue by joslloand** [supercollider/supercollider#6058]
## Environment

* SuperCollider version: 3.13.0
* Operating system: macOS

## Steps to reproduce

```supercollider
// render documents & index
SCDoc.renderAll(includeExtensions: true)
SCDoc.indexAllDocuments(true)
```

## Expected vs. actual behavior

Expecting a clean render of all schelp files.

Returned message:
```supercollider
WARNING: SCDoc: In /Applications/SuperCollider 3.13.0/SuperCollider.app/Contents/Resources/HelpSource/Classes/FunctionDef.schelp
  Method -makeFuncArgModifierString not found.
```

**Comment by joslloand** [comment]
The warning appears to be the result of a simple mismatch between method names in `FunctionDef.schelp` and `Kernel.sc`...
- schelp: [makeFuncArgModifierString](https://github.com/supercollider/supercollider/blob/develop/HelpSource/Classes/FunctionDef.schelp#L115C1-L115C1)
- sc: [makeFuncModifierString](https://github.com/supercollider/supercollider/blob/develop/SCClassLibrary/Common/Core/Kernel.sc#L530)

... and appears to merely be a documentation error, resulting from this refactoring (@telephon):

- https://github.com/supercollider/supercollider/pull/5900/commits/0abc3b67ebe1752d12dd8fe5fbca964c36b2758f
- https://github.com/supercollider/supercollider/pull/5900/commits/7ba1e0f66d9b4dc665cb11645272f2655a3d4deb

I'd propose the fix to be updating schelp to reflect the name found in the class file.

---
This _doesn't_ appear to be a critical issue, as the related example code found in schelp uses `-makeFuncModifierString`.

**Comment by redFrik** [comment]
fixed in https://github.com/supercollider/supercollider/pull/6029

**Comment by joslloand** [comment]
Hurrah!

Apologies for the noise.
