### ISSUE TITLE
Regression with pipewire 0.3.78?

### ISSUE THREAD

**Issue by garpu** [supercollider/supercollider#6076]
## Environment

* SuperCollider version: 3.13.0
* Operating system: Slackware-current with multilib, patched to August 22.
* Other details: pipewire-0.3.78, qt5-5.15.10, boost-1.83.0, kernel 6.1.45, preempt=dynamic

## Steps to reproduce

Upgrade pipewire to 0.3.78 (built with jack enabled)
Start a server, and it fails to connect: 
[supercollider_jack.txt](https://github.com/supercollider/supercollider/files/12420858/supercollider_jack.txt)

If I roll back to pipewire 0.3.77, everything works normally. Is this a supercollider bug, or a pipewire bug?

**Comment by dyfer** [comment]
Thanks for the report.
Was SC rebuilt after upgrading pipewire?

**Comment by garpu** [comment]
Yes.  I tried rebuilding supercollider after I upgraded pipewire with the same result. (compiled against my system boost because I encountered this bug: https://github.com/supercollider/supercollider/issues/5865).  I can try building it against supercollider's boost.

**Comment by dyfer** [comment]
> Yes. I tried rebuilding supercollider after I upgraded pipewire with the same result.

Got it. Then I really have no idea what the issue is.
> Would it make a difference if I compiled it against supercollider's boost?

I don't think so... but maybe worth a try? Otherwise I really have no idea how to approach this, though I'd double check whether this could be something in the PW's JACK interface that might've changed...

**Comment by garpu** [comment]
> > Would it make a difference if I compiled it against supercollider's boost?
> 
> I don't think so... but maybe worth a try? Otherwise I really have no idea how to approach this, though I'd double check if it's not something in the PW's JACK interface that might've changed...

OK, I just rebuild supercollider against pipewire 0.3.78 with supercollider's boost, and it exhibited the same problem of not connecting when booting the server.  Rolling back to pipewire 0.3.77 fixed it. Wait until 0.3.79 and retest?

**Comment by garpu** [comment]
Awesome, thanks. I can add my data.

**Comment by garpu** [comment]
Fixed in pipewire.  I'll close this, since it's not a supercollider bug.

**Comment by dyfer** [comment]
Thanks for reporting back!
