### ISSUE TITLE
Update 'Issue' template to refer to the wiki instead of CONTRIBUTING.md

### ISSUE THREAD

**Issue by MikeTheGreat** [supercollider/supercollider#6080]
This is a bug/change request for the SuperCollider repo here in GitHub, and has nothing to do with the SuperCollider software itself.

When I create a new issue (whether it's a bug or feature request) the first line reads:

` <!-- Please see CONTRIBUTING.md for guidelines. -->`

I found CONTRIBUTING.md at the top level of the source code in the repo, and it says:

`The Contributing Guide has been moved to the SuperCollider wiki: https://github.com/supercollider/supercollider/wiki`

I would like to suggest that the template for new issues be updated so that the first line reads:

` <!-- Please see [the SuperCollider wiki](https://github.com/supercollider/supercollider/wiki#issues) for guidelines. -->`

Also, please keep the CONTRIBUTING.md file! :)

**Comment by cdbzb** [comment]
If anyone with write access who wants to fix this:

https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#creating-issue-templates

**Comment by mtmccrea** [comment]
Should this link to the wiki page [specifically about filing issues](https://github.com/supercollider/supercollider/wiki/Reporting-bugs%2C-issues%2C-feature-requests), or the [Contributing directory](https://github.com/supercollider/supercollider/wiki/Contributing-directory), which has a collection of useful/related links?

**Comment by cdbzb** [comment]
No harm in both perhaps, as long as it fits on the line and the issues page comes first. maybe something like: 

for guidelines please see [filing issues](https://github.com/supercollider/supercollider/wiki/Reporting-bugs%2C-issues%2C-feature-requests). For contributing generally please see [Contributing](https://github.com/supercollider/supercollider/wiki/Contributing-directory)

**Comment by telephon** [comment]
@mtmccrea would you like to do the change?

**Comment by mtmccrea** [comment]
I can't see a settings tab on the repo to access the template, I think [someone with owner status](https://github.com/orgs/supercollider/people) would need to do this. I'd be happy to do this if my access level were bumped up.

As a related aside: GitHub supports [issue forms](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#creating-issue-forms), which may give us the opportunity to improve formatting for triage.

**Comment by telephon** [comment]
I've looked at it, the guidelines are also here, so we don't need two links, jsut this one:

https://github.com/supercollider/supercollider/wiki/Contributing-directory
