### ISSUE TITLE
scsynth OSC packet size in NRT mode

### ISSUE THREAD

**Issue by jleben** [supercollider/supercollider#61]
[Issue migrated from SourceForge | ID: 1970340 | Submitted by 'sciss']
[http://sourceforge.net/support/tracker.php?aid=1970340]

scsynth's OSC packet size differs from realtime and NRT mode, in realtime i think it's 64K(?) and in NRT just 8K(?). that produces problems in porting realtime code to NRT equivalents, particularly with using /d_recv to transfer synthdefs. The packet size should be increased in NRT to match the realtime size.

**Comment by scztt** [comment]
Someone want to look and see if this is an easy issue (meaning - changing a constant somewhere :) ) to fix for 3.7?

**Comment by davidgranstrom** [comment]
Maybe this issue is obsolete now since #714 was merged?

**Comment by vivid-synth** [comment]
Yup, this looks like a duplicate of https://github.com/supercollider/supercollider/issues/714

**Comment by vivid-synth** [comment]
As this looks like a duplicate of https://github.com/supercollider/supercollider/issues/714 , can we close?
