### ISSUE TITLE
Missing command in the GitHub wiki : Setting up your development environment

### ISSUE THREAD

**Issue by SimonDeplat** [supercollider/supercollider#6100]
## Environment

* SuperCollider version: SC 3.14.0-dev
* Operating system: Ubuntu 22.04
* Other details (Qt version, audio driver, etc.): N/A

## Steps to reproduce

When executing the provided code in 'For schelp and SuperCollider contributions', the 'sclang_conf_development.yaml' file generated contains 'excludeDefaultPaths: false' by default.

This leads to the infamous duplicate Class definition error.

## Expected vs. actual behavior

I think this command is missing, regardless of the OS : 

`LanguageConfig.excludeDefaultPaths = true;`

This correctly sets 'excludeDefaultPaths: true' when generating the file, removing the error.

**Comment by dyfer** [comment]
Thanks! I updated the [wiki page](https://github.com/supercollider/supercollider/wiki/Setting-up-your-development-environment#for-schelp-and-supercollider-contributions).
