### ISSUE TITLE
Provide official documentation for the web

### ISSUE THREAD

**Issue by capital-G** [supercollider/supercollider#6108]
## Motivation

Currently there are 2 known websites to provide documentation for SuperCollider

* https://doc.sccode.org/
* https://depts.washington.edu/dxscdoc/Help/Help.html

but it is not transparent how these were build (e.g. which extensions) and they are often linked (e.g. in forum or tutorials), yet there is no way for the dev community to maintain these important documents - e.g. force an update or make sure it is online and does not go offline.

In order to gain control over the online documentation for the SC developers I coded a CI repository which builds the docs and deploys them via GitHub Pages

repo: https://github.com/capital-G/sc-docs
docs: https://capital-g.github.io/sc-docs

This has advantages such as

* transparent build procedures via CI/CD which allows for forks and PRs
* Link to source files (help and code) are working and are referring to the official source files on the GitHub repository (closes https://github.com/supercollider/supercollider/issues/5157 )
* stays automatically up to date (GH actions run weekly, dependabot runs monthly)
* The docs are not designed for 4k displays - applying a custom.css fixes some of these issues 

## Description of Proposed Feature

See above

## Plan for Implementation

The code is already implemented, but there are things to discuss

* [ ] Import this repo into the `supercollider` github organization?
* [ ] Obtain a non-github URL for official representation in order to be not-dependent upon GitHub - for example `super-collider.org` is still available, I would be willing to buy this domain for 10+ years

---

See also https://github.com/supercollider/supercollider/pull/5872 for prior discussion

**Comment by cdbzb** [comment]
I'm enthusiastic about the idea of having an official domain and I would also be willing to help with cost - I don't prefer `super-collider` though! I see that various `supercollider` (without the hyphen) domains are still cheap...  

The documentation link in the current website points to Sccode.org which is outdated (12.2) which makes your point. 

I notice though that file links in your script open in the develop branch rather than the appropriate release branch. The page also is narrower than my browser windows.  These quibbles aside I actually find opening the files in github to be quite useful.

Another issue is that Sccode and UW both do contain documentation for external Quarks - is it a problem to have multiple documentation websites with different scopes?

**Comment by capital-G** [comment]
> I notice though that file links in your script open in the develop branch rather than the appropriate release branch

Good idea, I now link to the used branch instead of the develop branch

>  The page also is narrower than my browser windows.

Well, that is actually more a feature/proposition than a bug, see

<img width="2372" alt="grafik" src="https://user-images.githubusercontent.com/8267062/190145333-2fba4666-7ee8-4fad-89ed-4920cb1c10a7.png">

vs

<img width="2367" alt="grafik" src="https://user-images.githubusercontent.com/8267062/190145285-0f5f514d-fd18-4eac-9a16-aa22344cbf84.png">

**Comment by mtmccrea** [comment]
Nice proposal!
I'm in favor of the constrained width.

pinging maintainers of the current docs 
@joslloand 
@vividsnow (I think?)

**Comment by dyfer** [comment]
We've discussed this at the last dev meeting.
While I _personally_ think that help which includes as many extensions as possible would be useful for the end user, I also think this would not be the proper way for the "official" docs, as it could imply that the included extensions are somehow supported by core SC team.
One area that was floated was to include a mechanism to easily generate HTML help for each quark on its github page. I think that would be a cleaner solution, though it becomes another project to tackle, and then deploy among the quarks.

The first thing to do would be to get some input from the maintainer of doc.sccode.org (I also thought it's @vividsnow, but I'm not sure). The last thing we want is to have _two_ common helpfile pages that differ slightly... The same is true for pages maintained by @joslloand.

**Comment by mtmccrea** [comment]
> While I personally think that help which includes as many extensions as possible would be useful for the end user,

What do you mean by extensions? Quarks? sc3-plugins?
IMO hosting sc3-plugins docs could be a good option, but if that's contentious or introduces other issues (like quality control), it shouldn't block getting main docs hosted.

> it could imply that the included extensions are somehow supported by core SC team.

I don't see this as a big concern, in part because the docs indicate an extension quite explicitly:
<img width="585" alt="Screenshot 2023-10-15 at 11 56 46" src="https://github.com/supercollider/supercollider/assets/923342/00fcbd75-d368-4abc-b6c1-a511a2896600">

> One area that was floated was to include a mechanism to easily generate HTML help for each quark on its github page. I think that would be a cleaner solution, though it becomes another project to tackle, and then deploy among the quarks.

Standalone quark doc pages wouldn't be searchable from within the doc system without new features added. Even if we could link to external quark docs, navigation would also be interrupted—the browser would handle going "back" to the main docs, but how to redirect links from within the Quark's docs to, e.g., other classes?
That said, in principle, I like this idea for the sake of having more info available on the quark GH pages.

In any case, I think that should be a separate effort and shouldn't block hosting main docs. 

Those are some initial impressions anyway ... It would be useful to know how different people use the doc system. 
For example, @joslloand - I know you use the UW-hosted version for teaching purposes, so you need plugin and quark docs available online (especially Quarks that are course material). So I'd imagine a centrally-maintained doc system wouldn't replace this use case and you'd need to continue hosting your own version, right? 
Would be interested to here how/if a central doc system impacts use cases like this.

**Comment by capital-G** [comment]
> One area that was floated was to include a mechanism to easily generate HTML help for each quark on its github page. I think that would be a cleaner solution, though it becomes another project to tackle, and then deploy among the quarks.

I currently think about extending https://capital-g.github.io/quarks-web/ to include features such as versioning, dependency scanning (by looking up used classes and methods within the source code) and documentation of the quarks, inspired by something similar to [docs.rs](https://docs.rs). Following a GH page for each quark has problems such as forcing people to use github and there are many repositories which are very interesting but haven't been updated in a decade.

Any internal classes could reference the official docs and the quarks-web site could provide a "lookup URL" for docs for classes and methods across core + quarks which would need to resolve any conflicts (e.g. class name duplicates), but that is more an idea than a WIP or something finished.

Nonetheless, I think while this is an important discussion which extensions to in- and exclude, it should be an issue on its own as there will be many valid opinions on this topic, but I would like to shift the attention towards "should be there any official vanilla-docs at all" in order to progress on this.

> The last thing we want is to have _two_ common helpfile pages that differ slightly.

Well, that is the status quo and none of these are administrated by the maintainers :) I think it is not a flaw to have multiple resources online, but adding an official one could provide some stability and reduce ambiguity which to refer to, especially for beginners.

**Comment by dyfer** [comment]
> What do you mean by extensions? Quarks? sc3-plugins?

Either/both.

> "should be there any official vanilla-docs at all" in order to progress on this.

IMO yes. BUT if it's official/vanilla, then it likely should not include extensions/quarks...

Getting in touch with @vividsnow (or whoever controls sccode.org) seems to be a logical next step...

**Comment by vividsnow** [comment]
Hi!

Yes, I maintain [doc.sccode.org](https://doc.sccode.org) and personally prefer to include [sc3-plugins](https://github.com/supercollider/sc3-plugins) documentation.
Thanks for the proposal! I'll include [build_docs.sh#L10-L13](https://github.com/capital-G/sc-docs/blob/11c7ff7b64e86d50b526204220cb2e64f52deada/build_docs.sh#L10-L13) and [custom.css](https://github.com/capital-G/sc-docs/blob/main/custom.css) to the [doc.sccode.org](https://doc.sccode.org) build process

**Comment by capital-G** [comment]
> Hi!
> 
> Yes, I maintain [doc.sccode.org](https://doc.sccode.org) and personally prefer to include [sc3-plugins](https://github.com/supercollider/sc3-plugins) documentation. Thanks for the proposal! I'll include [build_docs.sh#L10-L13](https://github.com/capital-G/sc-docs/blob/11c7ff7b64e86d50b526204220cb2e64f52deada/build_docs.sh#L10-L13) and [custom.css](https://github.com/capital-G/sc-docs/blob/main/custom.css) to the [doc.sccode.org](https://doc.sccode.org) build process

Hey, thanks for your response :) The motivation of the PR is less about improving existing online material but providing an official and transparent way of deploying docs which can be managed through code via a CI, but you are welcome to include any changes :)

Although `sccode.org` is now a familiar address, I was not aware of it for a long time and I think for newcomers it would still be good to have a somewhat official address which includes `supercollider` in some way and bundles all resources - sadly there are not many TLD left for this name and the current official URL is a github.io domain :l (but the current website is really nice!)

Maybe we can agree on a good name (or use an existing one?), register it, use it as official website domain and host the docs under `docs.new-supercollider-domain.org`? I would also be willing to register it and pay for it.

**Comment by joslloand** [comment]
Sure... I'm in favor of an "official" always up to date vanilla documentation site being available and accessible to users.

@vividsnow's https://doc.sccode.org/ is already linked from the SuperCollider [links page](https://supercollider.github.io/links), though it isn't exactly highlighted given the current bullet ordering.

A nice feature when generating the help pages could be to include a page listing any included extension, so a reader could easily review the extensions which have been included in installation the pages reflect.

As for https://depts.washington.edu/dxscdoc/Help/Help.html, the extensions I've included are largely required for support of the [SuperCollider distribution of the Ambisonic Toolkit](https://github.com/ambisonictoolkit/atk-sc3), as well as other teaching.

Is a new domain needed? Or can the pages be hosted at https://github.com/supercollider? https://github.com/supercollider/learn is there, so why not vanilla docs?

**Comment by vividsnow** [comment]
@capital-G I think [doc.scsynth.org](https://doc.scsynth.org) would be appropriate place, but I dont know who controls dns records of the scsynth.org zone.

..or, as @joslloand proposed, the official auto-generated docs can be placed at https://supercollider.github.io/doc

**Comment by capital-G** [comment]
> Is a new domain needed? Or can the pages be hosted at https://github.com/supercollider? https://github.com/supercollider/learn is there, so why not vanilla docs?

I think it would be good to not rely too much on GitHub, especially as domains are somehow cheap and it would allow SC more independence what happens behind a URL and provide consistency for years to come (see [supercollider.sourceforge.net](https://supercollider.sourceforge.net)) - I would vote to abandon [supercollider.github.io](https://supercollider.github.io) as an official URL as it ties SuperCollider to GitHub.

I have no problem on using GitHub as a hosting platform via `github.io` because they also allow custom domain names via CNAME entry and provide therefore a cheap CDN, but which could also easily be migrated to a static nginx/apache deployment (or whatever). But an URL without ownership can not be migrated at all :/

**Comment by vividsnow** [comment]
TMTOWTDI, apparently ) As far as I understand, there is no such entity like "SuperCollider Language Foundation" that would "officially" represent the SuperCollder project.

**Comment by joslloand** [comment]
@capital-G wrote:
> I think it would be good to not rely too much on GitHub

... this also applies to the current facilitation of the core SuperCollider code base. In its [initial](https://sourceforge.net/p/supercollider/supercollider/ci/start/tree/) (... correct me if I'm wrong) iteration as a public project, [SC was found on SourceForge](https://sourceforge.net/projects/supercollider/). SC has moved in the past.

My 2¢s, if it is to be "core" then host with the core of the project. That would meet...

> - [ ] Import this repo into the <supercollider> github organization?

... and would make sense to me.

The second proposal...

> - [ ]  Obtain a non-github URL for official representation in order to be not-dependent upon GitHub - for example <super-collider.org> is still available, I would be willing to buy this domain for 10+ years

... seems to me to be something that should be considered elsewhere, as a _separate issue_. If having a non-github URL is important, my feeling is it should concern the complete project, not just the documentation.

Relatedly, building a documentation release into the _SC4 ... N_ release cycle sounds like an excellent idea to me!

**Comment by capital-G** [comment]
In order to keep this issue focused on the "official docs" issue, I created a new issue which discusses the necessity of an official URL, see
* https://github.com/supercollider/supercollider/issues/6114

**Comment by capital-G** [comment]
Docs are now served under https://docs.supercollider.online/ see https://github.com/supercollider/supercollider/issues/6114#issuecomment-1807207283 - @dyfer should the corresponding repo https://github.com/capital-G/sc-docs be transferred to the supercollider organization?

For docs of quarks I created Baryon - checkout https://baryon.supercollider.online

**Comment by JordanHendersonMusic** [comment]
@capital-G  does [https://docs.supercollider.online/](https://docs.supercollider.online/) solve this issue and can it be closed?

**Comment by mtmccrea** [comment]
I think solving this issue will be when a decision is made on whether this is the "official" documentation, which we haven't yet seen consensus on. It would also involve updating links to this throughout the docs.

Would like to see more interest in this!

**Comment by capital-G** [comment]
@JordanHendersonMusic 
> @capital-G does https://docs.supercollider.online/ solve this issue and can it be closed?

I think it would be best if the repo which creates and serves the files(https://github.com/capital-G/sc-docs) would be transferred to the SuperCollider organization (so https://github.com/supercollider/sc-docs) in order that the people who maintain SC also have the ability to influence and maintain the docs - this was the intention so multiple people can be in charge of keeping the docs in a good state.

We could also add a link to these docs on the official website.

Regarding the extensions, I wrote https://baryon.supercollider.online/ which also serves the docs for all projects listed via https://github.com/supercollider-quarks/quarks/blob/master/directory.txt , see, e.g. https://baryon.supercollider.online/project/Fracture (click on docs) which leads to https://baryon.supercollider.online/media/sc_docs/Fracture/Classes/Fracture.html

**Comment by mtmccrea** [comment]
> I think it would be best if the repo which creates and serves the files(https://github.com/capital-G/sc-docs) would be transferred to the SuperCollider organization (so https://github.com/supercollider/sc-docs)

I think multiple people in this conversation have voiced agreement on this. Do we need more consensus? For example perhaps a ping on the discourse thread to say we're approaching this decision.

IIUC, this is the full scope of this PR, given discussion of both the domain and inclusion of extensions/quarks can be regarded as separate issues. IMO people will be more prepared for those discussions after this first step is made.

**Comment by capital-G** [comment]
As there has been no objections I decided to move the repository under the official supercollider organization, see https://github.com/supercollider/sc-docs 

The rendered docs are available @ https://docs.supercollider.online/

Currently the docs only cover a vanilla installation as we would otherwise would need to take care of building/installation plugins or quarks which I think would make a build rather complex and unstable.

**Comment by mtmccrea** [comment]
Thanks for your work on this @capital-G! It will be great to have up-to-date docs :) 

I've updated links to the docs on the Wiki, and I've added to the release checklist that the dockerfile needs to be updated with each new release.

Would you mind making an announcement on the scsynth forum when you have a chance? It's probably best that it has its own Topic if there is follow up discussion to be had WRT including extensions, or how this may relate to moving a new URL for the SC webpage.

Thanks again!

**Comment by cdbzb** [comment]
While we here we should update the documents link at https://supercollider.github.io/links ...
