### ISSUE TITLE
Method index generation takes too long

### ISSUE THREAD

**Issue by prko** [supercollider/supercollider#6120]
## Environment

* SuperCollider version: 3.14.0-dev
* Operating system: macOS 12.7.1

## Steps to reproduce

1. type the following code
```
.plot
```
2. press cmd + d

## Expected vs. actual behavior
- Expected behaviour:
  <img width="784" alt="Screenshot 2023-10-27 at 8 24 09" src="https://github.com/supercollider/supercollider/assets/416281/d657a08d-1b08-4056-88dc-299fce0f8acc">
- Actual behaviour: SuperCollider takes too long to create the index.
  <img width="1059" alt="Screenshot 2023-10-27 at 8 08 04" src="https://github.com/supercollider/supercollider/assets/416281/1ff4d31a-4e8d-46ab-92a5-726ee2458203">

**Comment by JordanHendersonMusic** [comment]
I cannot recreate this issue, it happens instantly here.
3.14.0-dev, linux.
