### ISSUE TITLE
Server error

### ISSUE THREAD

**Issue by Lispilo** [supercollider/supercollider#6134]
Bug description:
when i start my server and run my code(
        x = {SinOsc.ar(440, 0, 0.2)}.play;
)
i get an error that say that the server isent roning. 

Steps to reproduce:
1.  Start server
2. run code
3. sea error in the post window

Actual result:
Booting server 'localhost' on address 127.0.0.1:57110.

Device options:
  - MME : Microsoft Sound Mapper - Input   (device #0 with 2 ins 0 outs)
  - MME : Mikrofon (USB Audio CODEC )   (device #1 with 2 ins 0 outs)
  - MME : Mikrofon (Steam Streaming Micro   (device #2 with 8 ins 0 outs)
  - MME : Headset Microphone (Razer Krake   (device #3 with 2 ins 0 outs)
  - MME : Mikrofon (Logi C615 HD WebCam)   (device #4 with 1 ins 0 outs)
  - MME : Headset Microphone (Oculus Virt   (device #5 with 1 ins 0 outs)
  - MME : Microsoft Sound Mapper - Output   (device #6 with 0 ins 2 outs)
  - MME : Högtalare (Razer Kraken TE - Ga   (device #7 with 0 ins 2 outs)
  - MME : Högtalare (Steam Streaming Spea   (device #8 with 0 ins 8 outs)
  - MME : Headset Earphone (Razer Kraken    (device #9 with 0 ins 2 outs)
  - MME : Högtalare (Steam Streaming Micr   (device #10 with 0 ins 8 outs)
  - MME : Hörlurar (Oculus Virtual Audio    (device #11 with 0 ins 2 outs)
  - MME : C27F390 (NVIDIA High Definition   (device #12 with 0 ins 2 outs)
  - MME : Realtek Digital Output (Realtek   (device #13 with 0 ins 2 outs)
  - MME : C24F390 (NVIDIA High Definition   (device #14 with 0 ins 2 outs)
  - MME : Högtalare (USB Audio CODEC )   (device #15 with 0 ins 2 outs)
  - Windows DirectSound : Primär drivrutin för ljudinfångst   (device #16 with 2 ins 0 outs)
  - Windows DirectSound : Mikrofon (USB Audio CODEC )   (device #17 with 2 ins 0 outs)
  - Windows DirectSound : Mikrofon (Steam Streaming Microphone)   (device #18 with 8 ins 0 outs)
  - Windows DirectSound : Headset Microphone (Razer Kraken TE - Chat)   (device #19 with 2 ins 0 outs)
  - Windows DirectSound : Mikrofon (Logi C615 HD WebCam)   (device #20 with 1 ins 0 outs)
  - Windows DirectSound : Headset Microphone (Oculus Virtual Audio Device)   (device #21 with 1 ins 0 outs)
  - Windows DirectSound : Primär ljuddrivrutin   (device #22 with 0 ins 2 outs)
  - Windows DirectSound : Högtalare (Razer Kraken TE - Game)   (device #23 with 0 ins 2 outs)
  - Windows DirectSound : Högtalare (Steam Streaming Speakers)   (device #24 with 0 ins 8 outs)
  - Windows DirectSound : Headset Earphone (Razer Kraken TE - Chat)   (device #25 with 0 ins 2 outs)
  - Windows DirectSound : Högtalare (Steam Streaming Microphone)   (device #26 with 0 ins 8 outs)
  - Windows DirectSound : Hörlurar (Oculus Virtual Audio Device)   (device #27 with 0 ins 2 outs)
  - Windows DirectSound : C27F390 (NVIDIA High Definition Audio)   (device #28 with 0 ins 2 outs)
  - Windows DirectSound : Realtek Digital Output (Realtek High Definition Audio)   (device #29 with 0 ins 2 outs)
  - Windows DirectSound : C24F390 (NVIDIA High Definition Audio)   (device #30 with 0 ins 2 outs)
  - Windows DirectSound : Högtalare (USB Audio CODEC )   (device #31 with 0 ins 2 outs)
  - Windows WASAPI : Högtalare (Steam Streaming Speakers)   (device #32 with 0 ins 2 outs)
  - Windows WASAPI : Headset Earphone (Razer Kraken TE - Chat)   (device #33 with 0 ins 2 outs)
  - Windows WASAPI : Högtalare (Steam Streaming Microphone)   (device #34 with 0 ins 2 outs)
  - Windows WASAPI : Hörlurar (Oculus Virtual Audio Device)   (device #35 with 0 ins 2 outs)
  - Windows WASAPI : C27F390 (NVIDIA High Definition Audio)   (device #36 with 0 ins 2 outs)
  - Windows WASAPI : Högtalare (Razer Kraken TE - Game)   (device #37 with 0 ins 2 outs)
  - Windows WASAPI : Realtek Digital Output (Realtek High Definition Audio)   (device #38 with 0 ins 2 outs)
  - Windows WASAPI : C24F390 (NVIDIA High Definition Audio)   (device #39 with 0 ins 2 outs)
  - Windows WASAPI : Högtalare (USB Audio CODEC )   (device #40 with 0 ins 2 outs)
  - Windows WASAPI : Mikrofon (Steam Streaming Microphone)   (device #41 with 1 ins 0 outs)
  - Windows WASAPI : Headset Microphone (Razer Kraken TE - Chat)   (device #42 with 2 ins 0 outs)
  - Windows WASAPI : Mikrofon (Logi C615 HD WebCam)   (device #43 with 1 ins 0 outs)
  - Windows WASAPI : Headset Microphone (Oculus Virtual Audio Device)   (device #44 with 1 ins 0 outs)
  - Windows WASAPI : Mikrofon (USB Audio CODEC )   (device #45 with 1 ins 0 outs)
  - Windows WDM-KS : Output 1 (OCULUSVAD Wave Speaker Headphone)   (device #46 with 0 ins 2 outs)
  - Windows WDM-KS : Output 2 (OCULUSVAD Wave Speaker Headphone)   (device #47 with 0 ins 2 outs)
  - Windows WDM-KS : Input (OCULUSVAD Wave Speaker Headphone)   (device #48 with 2 ins 0 outs)
  - Windows WDM-KS : Headset Microphone (OCULUSVAD Wave Microphone Headphone)   (device #49 with 1 ins 0 outs)
  - Windows WDM-KS : Linjeingång (Realtek HD Audio Line input)   (device #50 with 2 ins 0 outs)
  - Windows WDM-KS : SPDIF Out (Realtek HDA SPDIF Out)   (device #51 with 0 ins 2 outs)
  - Windows WDM-KS : Speakers (Realtek HD Audio output)   (device #52 with 0 ins 8 outs)
  - Windows WDM-KS : Stereo mix (Realtek HD Audio Stereo input)   (device #53 with 2 ins 0 outs)
  - Windows WDM-KS : Mikrofon (Realtek HD Audio Mic input)   (device #54 with 2 ins 0 outs)
  - Windows WDM-KS : Mikrofon (Logi C615 HD WebCam)   (device #55 with 1 ins 0 outs)
  - Windows WDM-KS : Mikrofon på headset (Razer Kraken TE - Chat)   (device #56 with 2 ins 0 outs)
  - Windows WDM-KS : Hörlurar på headset (Razer Kraken TE - Chat)   (device #57 with 0 ins 2 outs)
  - Windows WDM-KS : Mikrofon (Steam Streaming Microphone Wave)   (device #58 with 8 ins 0 outs)
  - Windows WDM-KS : Speakers (Steam Streaming Microphone Wave)   (device #59 with 0 ins 8 outs)
  - Windows WDM-KS : Input ()   (device #60 with 2 ins 0 outs)
  - Windows WDM-KS : Output (NVIDIA High Definition Audio)   (device #61 with 0 ins 2 outs)
  - Windows WDM-KS : Output (NVIDIA High Definition Audio)   (device #62 with 0 ins 2 outs)
  - Windows WDM-KS : Output (@System32\drivers\bthhfenum.sys,#4;%1 Hands-Free HF Audio%0

;(Milos iphone))   (device #63 with 0 ins 1 outs)
  - Windows WDM-KS : Input (@System32\drivers\bthhfenum.sys,#4;%1 Hands-Free HF Audio%0

;(Milos iphone))   (device #64 with 1 ins 0 outs)
  - Windows WDM-KS : Input (Steam Streaming Speakers Wave)   (device #65 with 8 ins 0 outs)
  - Windows WDM-KS : Speakers (Steam Streaming Speakers Wave)   (device #66 with 0 ins 8 outs)
  - Windows WDM-KS : Högtalare (USB Audio CODEC)   (device #67 with 0 ins 2 outs)
  - Windows WDM-KS : Mikrofon (USB Audio CODEC)   (device #68 with 2 ins 0 outs)
  - Windows WDM-KS : Högtalare (Razer Kraken TE - Game)   (device #69 with 0 ins 2 outs)

Requested devices:
  In:
  - (default)
  Out:
  - (default)

Selecting default system input/output devices

Booting with:
  In: MME : Mikrofon (USB Audio CODEC )
  Out: MME : Högtalare (Razer Kraken TE - Ga
  Sample rate: 44100.000
  Latency (in/out): 0.013 / 0.091 sec
SC_AudioDriver: sample rate = 44100.000000, driver's block size = 64
SuperCollider 3 server ready.
WARNING: server 'localhost' not running.
-> nil

Expected result:
Booting server 'localhost' on address 127.0.0.1:57110.

Device options:
  - MME : Microsoft Sound Mapper - Input   (device #0 with 2 ins 0 outs)
  - MME : Mikrofon (USB Audio CODEC )   (device #1 with 2 ins 0 outs)
  - MME : Mikrofon (Steam Streaming Micro   (device #2 with 8 ins 0 outs)
  - MME : Headset Microphone (Razer Krake   (device #3 with 2 ins 0 outs)
  - MME : Mikrofon (Logi C615 HD WebCam)   (device #4 with 1 ins 0 outs)
  - MME : Headset Microphone (Oculus Virt   (device #5 with 1 ins 0 outs)
  - MME : Microsoft Sound Mapper - Output   (device #6 with 0 ins 2 outs)
  - MME : Högtalare (Razer Kraken TE - Ga   (device #7 with 0 ins 2 outs)
  - MME : Högtalare (Steam Streaming Spea   (device #8 with 0 ins 8 outs)
  - MME : Headset Earphone (Razer Kraken    (device #9 with 0 ins 2 outs)
  - MME : Högtalare (Steam Streaming Micr   (device #10 with 0 ins 8 outs)
  - MME : Hörlurar (Oculus Virtual Audio    (device #11 with 0 ins 2 outs)
  - MME : C27F390 (NVIDIA High Definition   (device #12 with 0 ins 2 outs)
  - MME : Realtek Digital Output (Realtek   (device #13 with 0 ins 2 outs)
  - MME : C24F390 (NVIDIA High Definition   (device #14 with 0 ins 2 outs)
  - MME : Högtalare (USB Audio CODEC )   (device #15 with 0 ins 2 outs)
  - Windows DirectSound : Primär drivrutin för ljudinfångst   (device #16 with 2 ins 0 outs)
  - Windows DirectSound : Mikrofon (USB Audio CODEC )   (device #17 with 2 ins 0 outs)
  - Windows DirectSound : Mikrofon (Steam Streaming Microphone)   (device #18 with 8 ins 0 outs)
  - Windows DirectSound : Headset Microphone (Razer Kraken TE - Chat)   (device #19 with 2 ins 0 outs)
  - Windows DirectSound : Mikrofon (Logi C615 HD WebCam)   (device #20 with 1 ins 0 outs)
  - Windows DirectSound : Headset Microphone (Oculus Virtual Audio Device)   (device #21 with 1 ins 0 outs)
  - Windows DirectSound : Primär ljuddrivrutin   (device #22 with 0 ins 2 outs)
  - Windows DirectSound : Högtalare (Razer Kraken TE - Game)   (device #23 with 0 ins 2 outs)
  - Windows DirectSound : Högtalare (Steam Streaming Speakers)   (device #24 with 0 ins 8 outs)
  - Windows DirectSound : Headset Earphone (Razer Kraken TE - Chat)   (device #25 with 0 ins 2 outs)
  - Windows DirectSound : Högtalare (Steam Streaming Microphone)   (device #26 with 0 ins 8 outs)
  - Windows DirectSound : Hörlurar (Oculus Virtual Audio Device)   (device #27 with 0 ins 2 outs)
  - Windows DirectSound : C27F390 (NVIDIA High Definition Audio)   (device #28 with 0 ins 2 outs)
  - Windows DirectSound : Realtek Digital Output (Realtek High Definition Audio)   (device #29 with 0 ins 2 outs)
  - Windows DirectSound : C24F390 (NVIDIA High Definition Audio)   (device #30 with 0 ins 2 outs)
  - Windows DirectSound : Högtalare (USB Audio CODEC )   (device #31 with 0 ins 2 outs)
  - Windows WASAPI : Högtalare (Steam Streaming Speakers)   (device #32 with 0 ins 2 outs)
  - Windows WASAPI : Headset Earphone (Razer Kraken TE - Chat)   (device #33 with 0 ins 2 outs)
  - Windows WASAPI : Högtalare (Steam Streaming Microphone)   (device #34 with 0 ins 2 outs)
  - Windows WASAPI : Hörlurar (Oculus Virtual Audio Device)   (device #35 with 0 ins 2 outs)
  - Windows WASAPI : C27F390 (NVIDIA High Definition Audio)   (device #36 with 0 ins 2 outs)
  - Windows WASAPI : Högtalare (Razer Kraken TE - Game)   (device #37 with 0 ins 2 outs)
  - Windows WASAPI : Realtek Digital Output (Realtek High Definition Audio)   (device #38 with 0 ins 2 outs)
  - Windows WASAPI : C24F390 (NVIDIA High Definition Audio)   (device #39 with 0 ins 2 outs)
  - Windows WASAPI : Högtalare (USB Audio CODEC )   (device #40 with 0 ins 2 outs)
  - Windows WASAPI : Mikrofon (Steam Streaming Microphone)   (device #41 with 1 ins 0 outs)
  - Windows WASAPI : Headset Microphone (Razer Kraken TE - Chat)   (device #42 with 2 ins 0 outs)
  - Windows WASAPI : Mikrofon (Logi C615 HD WebCam)   (device #43 with 1 ins 0 outs)
  - Windows WASAPI : Headset Microphone (Oculus Virtual Audio Device)   (device #44 with 1 ins 0 outs)
  - Windows WASAPI : Mikrofon (USB Audio CODEC )   (device #45 with 1 ins 0 outs)
  - Windows WDM-KS : Output 1 (OCULUSVAD Wave Speaker Headphone)   (device #46 with 0 ins 2 outs)
  - Windows WDM-KS : Output 2 (OCULUSVAD Wave Speaker Headphone)   (device #47 with 0 ins 2 outs)
  - Windows WDM-KS : Input (OCULUSVAD Wave Speaker Headphone)   (device #48 with 2 ins 0 outs)
  - Windows WDM-KS : Headset Microphone (OCULUSVAD Wave Microphone Headphone)   (device #49 with 1 ins 0 outs)
  - Windows WDM-KS : Linjeingång (Realtek HD Audio Line input)   (device #50 with 2 ins 0 outs)
  - Windows WDM-KS : SPDIF Out (Realtek HDA SPDIF Out)   (device #51 with 0 ins 2 outs)
  - Windows WDM-KS : Speakers (Realtek HD Audio output)   (device #52 with 0 ins 8 outs)
  - Windows WDM-KS : Stereo mix (Realtek HD Audio Stereo input)   (device #53 with 2 ins 0 outs)
  - Windows WDM-KS : Mikrofon (Realtek HD Audio Mic input)   (device #54 with 2 ins 0 outs)
  - Windows WDM-KS : Mikrofon (Logi C615 HD WebCam)   (device #55 with 1 ins 0 outs)
  - Windows WDM-KS : Mikrofon på headset (Razer Kraken TE - Chat)   (device #56 with 2 ins 0 outs)
  - Windows WDM-KS : Hörlurar på headset (Razer Kraken TE - Chat)   (device #57 with 0 ins 2 outs)
  - Windows WDM-KS : Mikrofon (Steam Streaming Microphone Wave)   (device #58 with 8 ins 0 outs)
  - Windows WDM-KS : Speakers (Steam Streaming Microphone Wave)   (device #59 with 0 ins 8 outs)
  - Windows WDM-KS : Input ()   (device #60 with 2 ins 0 outs)
  - Windows WDM-KS : Output (NVIDIA High Definition Audio)   (device #61 with 0 ins 2 outs)
  - Windows WDM-KS : Output (NVIDIA High Definition Audio)   (device #62 with 0 ins 2 outs)
  - Windows WDM-KS : Output (@System32\drivers\bthhfenum.sys,#4;%1 Hands-Free HF Audio%0

;(Milos iphone))   (device #63 with 0 ins 1 outs)
  - Windows WDM-KS : Input (@System32\drivers\bthhfenum.sys,#4;%1 Hands-Free HF Audio%0

;(Milos iphone))   (device #64 with 1 ins 0 outs)
  - Windows WDM-KS : Input (Steam Streaming Speakers Wave)   (device #65 with 8 ins 0 outs)
  - Windows WDM-KS : Speakers (Steam Streaming Speakers Wave)   (device #66 with 0 ins 8 outs)
  - Windows WDM-KS : Högtalare (USB Audio CODEC)   (device #67 with 0 ins 2 outs)
  - Windows WDM-KS : Mikrofon (USB Audio CODEC)   (device #68 with 2 ins 0 outs)
  - Windows WDM-KS : Högtalare (Razer Kraken TE - Game)   (device #69 with 0 ins 2 outs)

Requested devices:
  In:
  - (default)
  Out:
  - (default)

Selecting default system input/output devices

Booting with:
  In: MME : Mikrofon (USB Audio CODEC )
  Out: MME : Högtalare (Razer Kraken TE - Ga
  Sample rate: 44100.000
  Latency (in/out): 0.013 / 0.091 sec
SC_AudioDriver: sample rate = 44100.000000, driver's block size = 64
SuperCollider 3 server ready.

**Comment by dyfer** [comment]
Hello,

Can you post the output of running just `s.boot` right after starting SC? 
From the output you posted it isn't clear at what point the server starts or not - the last message (`SuperCollider 3 server ready.`) indicates that it should be running... BTW do you have anything in your `startup.scd` file?

Also, please put the output and code inside the code fence ` ``` ` (three backticks).

**Comment by Lispilo** [comment]
the server dident close when i chut down my computer
