### ISSUE TITLE
"/*" is parsed incorrectly when it is within /* */

### ISSUE THREAD

**Issue by prko** [supercollider/supercollider#6170]
## Environment

* SuperCollider version: 3.14.0_dev
* Operating system: macOS, Windows, Linux

## Steps to reproduce
https://github.com/supercollider/supercollider/pull/6164

## Expected vs. actual behavior
`"/*"` should not be regarded as the start of a comment, even within a `/*` `*/` pair.

**Comment by JordanHendersonMusic** [comment]
Closing as this is a duplicate of #5578
