### ISSUE TITLE
A gtk ide

### ISSUE THREAD

**Issue by exoess** [supercollider/supercollider#6179]
## Motivation
I feel that'd it'd be nice to have an alternative to the qt ide

## Description of Proposed Feature
A near duplicate of the qt ide, but in gtk

## Plan for Implementation
I've already started writing this, I'm writing it in vala, and it will be as close to the qt ide as i can make it

I will implement this, maybe with some help, but i assume I'm the only one interested in this venture. As for how long it will take, I'm unsure, if I'm the only one who ends up working on it, it may take awhile.

**Comment by mossheim** [comment]
This will not be happening, sorry. We do not have development resources for it.
