### ISSUE TITLE
SynthDef not making sound.

### ISSUE THREAD

**Issue by popculturenews** [supercollider/supercollider#6186]
Bug description:
Repeatedly this has transpired. I have to open precisely the same SynthDef in a new file. No errors are showing up on the post window, so it is bound to be something wrong with the application or audio settings.

Actual result:
No sound.
Expected result:
(
SynthDef(\synthOne, {
	arg ampHertz = 4, crucial = 40, two = 20, width = 0.5, dampRev = 0.5, mixRev = 0.7, conductDecipher = 30, speedDecipher = 20;
    var amp1, amp2, freq1, freq2, ex1, ex2;

//Introduces variable characteristics, assign control rate, exponential range, refer to arguments atop.
	freq1 = LFNoise0.kr(10).exprange(crucial, crucial * two).round(crucial);
    freq2 = LFNoise0.kr(8).exprange(crucial, crucial * two).round(crucial);

//Assign pulse, adding 1 to prior.
    freq1 = freq1 * LFPulse.kr(conductDecipher, add: 1);
    freq2 = freq2 * LFPulse.kr(speedDecipher, add: 1);

//Amplitude; volume manipulation.
    amp1 = LFPulse.kr(ampHertz, 0, 0.12) * 0.75;
    amp2 = LFPulse.kr(ampHertz, 0.5, 0.12) * 0.75;

//Combines elements to conduct tune.
    ex1 = Pulse.ar(freq1, width, amp1);
    ex2 = Pulse.ar(freq2, width, amp2);
}).add;
)
b = Synth.new(\synthOne);

**Comment by joshpar** [comment]
You need to write your sound out to an output with an Out.ar <http://out.ar/> ugen…

(
SynthDef(\synthOne, {
arg ampHertz = 4, crucial = 40, two = 20, width = 0.5, dampRev = 0.5, mixRev = 0.7, conductDecipher = 30, speedDecipher = 20;
var amp1, amp2, freq1, freq2, ex1, ex2;

//Introduces variable characteristics, assign control rate, exponential range, refer to arguments atop.
freq1 = LFNoise0.kr <http://lfnoise0.kr/>(10).exprange(crucial, crucial * two).round(crucial);
freq2 = LFNoise0.kr <http://lfnoise0.kr/>(8).exprange(crucial, crucial * two).round(crucial);

//Assign pulse, adding 1 to prior.
freq1 = freq1 * LFPulse.kr <http://lfpulse.kr/>(conductDecipher, add: 1);
freq2 = freq2 * LFPulse.kr <http://lfpulse.kr/>(speedDecipher, add: 1);

//Amplitude; volume manipulation.
amp1 = LFPulse.kr <http://lfpulse.kr/>(ampHertz, 0, 0.12) * 0.75;
amp2 = LFPulse.kr <http://lfpulse.kr/>(ampHertz, 0.5, 0.12) * 0.75;

//Combines elements to conduct tune.
ex1 = Pulse.ar <http://pulse.ar/>(freq1, width, amp1);
ex2 = Pulse.ar <http://pulse.ar/>(freq2, width, amp2);

Out.ar <http://out.ar/>(0, [ex1, ex2]);

}).add;
)
b = Synth.new(\synthOne);

Hope that helps
Josh

>

**Comment by popculturenews** [comment]
Thank you very much. That was a very absent-minded mistake!
