### ISSUE TITLE
Build failure with -DSYSTEM_BOOST=ON against >=boost-1.84: server/scsynth/SC_GraphDef.cpp:49:10: fatal error: boost/filesystem/string_file.hpp: No such file or directory

### ISSUE THREAD

**Issue by a17r** [supercollider/supercollider#6210]
In boost-1.79, the library was deprecated and in 1.84 finally removed (without replacement in boost, to my knowledge).

Downstream report with full build.log: https://bugs.gentoo.org/921595

I've got a workaround for it, but cannot consider it a proper fix.

**Comment by mossheim** [comment]
It would be easy to inline, the implementation was not very complex: https://www.boost.org/doc/libs/1_60_0/boost/filesystem/string_file.hpp

**Comment by a17r** [comment]
I did something to that effect in my workaround: https://github.com/supercollider/supercollider/compare/develop...a17r:supercollider:workaround-boost-1.84

**Comment by capital-G** [comment]
I think this should be fixed via https://github.com/supercollider/supercollider/pull/6331 - re-open if necessary.
