### ISSUE TITLE
`valueArray` does not handle variable arguments correctly.

### ISSUE THREAD

**Issue by JordanHendersonMusic** [supercollider/supercollider#6233]
## Steps to reproduce

For some testing function...
```supercollider
f = {|a, b, c, d ...e| 
   var i = 0;
   var j = 1;
	
   a.debug(\a);
   b.debug(\b);
   c.debug(\c);
   d.debug(\d);
   e.debug(\e);
};
```
This works as expected.

```supercollider
f.valueArray(\a, \b, \c, \d, [\e, \f, \g])

a: a
b: b
c: c
d: d
e: [e, f, g]
```

This does not.
```supercollider
a = [\a, \b, \c, \d, [\e, \f, \g]]
f.valueArray(a)

a: a
b: b
c: c
d: d
e: [[e, f, g]] <<<< double wrapped.
```

valueArray is supposed to work by taking the last item on the stack and expanding it, which it does!
However, when called with an actually array, the total number of items on the stack is not the array's SIZE, but its CAPACITY.
The solution in sclang is to alway call `valueArray` like this...

```supercollider
a = [\a, \b, \c, \d, [\e, \f, \g]]
f.valueArray(*a)  <<< teeny little star fixes problem

a: a
b: b
c: c
d: d
e: [e, f, g] <<<< correct
```
... making the method very brittle and easy to misuse.

This is quite a big change as many (but not all) use cases get this wrong.

I do not think this can be fixed in the primitive.

This will also be the case for `valueArrayEnvir`;

**Comment by telephon** [comment]
Hm, strange I would have expected this:

```
a = [\a, \b, \c, \d, [\e, \f, \g]]
f.valueArray(a)  

a: [\a, \b, \c, \d, [\e, \f, \g]]
b: nil
c: nil
d: nil
e: nil
```

Because this is what you get when you implement it "by hand":
```

~valueArray = { |func ... args| func.(*args) };
~valueArray = { |func ... args| func.valueArray(args) }; // either variant

~valueArray.(f, [\a, \b, \c, \d, [\e, \f, \g]])
```


But apart from this (which is a bit like a "feature"), the behaviour is correct I think.

**Comment by telephon** [comment]
The primitive is correct, yes. Is just read the comment in the source code:

```
// evaluate a function, if the last argument is an array it will be
// expanded into separate args.
```

But I we simply need a difference between the two arrays:
```
[\a, \b, \c, \d, [\e, \f, \g]] 
[\a, \b, \c, \d, \e, \f, \g]
```
If everything would magically auto-expand, then it would be impossible to make the difference, no?

**Comment by JordanHendersonMusic** [comment]
It is called valueArray implying it is meant to take an array as its argument, not a series of arguments. This matches how it is used throughout the code.

If you didn't want to pass an array, or were going to expand it with the *prefix, you'd just call value.
```
f.value(\a, \b, \c, \d, [\e, \f, \g]); //e: [[e, f, g]]
f.value(\a, \b, \c, \d, \e, \f, \g); // e: [e, f, g]

a = [\a, \b, \c, \d, [\e, \f, \g]];
f.value(*a); //e: [[e, f, g]]

a = [\a, \b, \c, \d, \e, \f, \g];
f.value(*a); //e: [e, f, g]
```

Double wrapping the varargs when valueArray is called with an array seems very odd, since this is its purpose.

**Comment by telephon** [comment]
> If you didn't want to pass an array, or were going to expand it with the *prefix, you'd just call value.

This is true.

But I think the original idea is that you pass all the arguments as an array, not nested.

It is the same as `performList`:

```supercollider

f.valueArray([\a, \b, \c, \d, \e, \f, \g]);
// the comment says "if the last argument is an array it will be
// expanded into separate args:
f.valueArray(\a, \b, [\c, \d, \e, \f, \g]);
f.valueArray(\a, \b, \c, [\d, \e, \f, \g]);


f.performList(\value, [\a, \b, \c, \d, \e, \f, \g]);
// the comment says "if the last argument is an array it will be
// expanded into separate args:
f.performList(\value, \a, \b, [\c, \d, \e, \f, \g]);
f.performList(\value, \a, \b, \c, [\d, \e, \f, \g]);
```

**Comment by telephon** [comment]
> It is called valueArray implying it is meant to take an array as its argument, not a series of arguments. This matches how it is used throughout the code.

Yes, in a sense. But then why does it have ellipsis (variable) args? 
```
{ |...args| args }.valueArray(2, 3, [4, 8])
```

It seems to be a hidden feature for the good and the bad ...

**Comment by JordanHendersonMusic** [comment]
I'm gonna close this because my understanding of the method was wrong... It's quite confusing how it interacts with variable arguments. I'm not entirely convinced that all places where this is used do the right thing.... but haven't been able to find any bugs. I think this might be related to this:
https://scsynth.org/t/object-prototyping-is-not-broken-for-higher-oder-functions-but-why/9171/4

Either way, I do think that how functions are called is way too complex and numerous. I'm gonna do some tests and try removing all value*, perform* and functionperform* methods, replacing them with value, valueWith, performWith, and functionPerformWith. Where the *With methods take an array of args, a key-value pair of keyword args, and a bool if args should be looked up on the current environment. 

That way, value is strictly used when the users calls a function, and the *Withs are used when programmatically building arguments and function calls.

**Comment by telephon** [comment]
As an experiment, it's worth it. But I wouldn't try to deprecate such central methods in the future. One could unify the use within the class library, if the performance is the same or better though.
