### ISSUE TITLE
Tuning .wrapAt method produces unexpected results

### ISSUE THREAD

**Issue by JaimeClover** [supercollider/supercollider#6243]
## Environment

* SuperCollider version: 3.12.2
* Operating system: macOS monterey 12.2.1

## Steps to reproduce

```supercollider
Scale.major.tuning.wrapAt(11.5)
```

## Expected vs. actual behavior

Expected result: 11.5
Actual result: 5.5

This behavior occurs with non-integer inputs between 11 and 12 in a 12-pitch Tuning because `Tuning.wrapAt` uses the `Object.blendAt` method, which blends 11 with 0 to get 5.5 in this case.

## Proposed fix

Add a new method, `Tuning.blendAt`, which addresses this corner case to produce the expected result above. This would also fix the same issue with the `Tuning.at` method, which likewise cannot produce tunings between 11 and 12.

**Comment by telephon** [comment]
This bug is "hidden" because there is a warning if tunings are shorter than the degrees.

I am a little unsure what the correct result should be if the tuning is shorter. It would have to work similar to `degreeToKey`, considering the tuning's octave ratio, perhaps?

**Comment by JaimeClover** [comment]
I was referring to cases where the Tuning is the correct size for the Scale, but the user wants to play microtones. Perhaps this is a better illustration of the bug:
```
Pbind(
    \note, Pseq([11, 11.5, 12]),
    \callback, {~midinote.value.postln}
).play;
```
produces these unexpected results:
```
71.0
65.5 // should be 71.5
72.0
```
I currently use an extension overwriting Tuning.at and Tuning.wrapAt to fix this bug:
```
+ Tuning {
    at { arg index;
        var extendedTuning;
        if (index.isInteger) {^tuning.at(index)};
        extendedTuning = tuning ++ [this.stepsPerOctave];
        ^extendedTuning.blendAt(index.clip(0, this.size - 1e-12));
    }

    wrapAt { arg index;
        var extendedTuning;
        if (index.isInteger) {^tuning.wrapAt(index)};
        extendedTuning = tuning ++ [this.stepsPerOctave];
        ^extendedTuning.blendAt(index % this.size);
    }
}
```
I have not tested it extensively, but it appears to work correctly so far.

**Comment by telephon** [comment]
Thank you for the example! There seems to be something missing though, I get a different result:

```supercollider
(
Pbind(
    \note, Pseq([11, 11.5, 12]),
    \callback, {~midinote.value.postln}
).play;
)
71.0
71.5
72.0

```

**Comment by JaimeClover** [comment]
Thanks for checking! The problem was with one of my own quarks.
