### ISSUE TITLE
Missing functionality in Qt: Retina display

### ISSUE THREAD

**Issue by smrg-lm** [supercollider/supercollider#625]
Retina/HiDPI support for QUserView (that is a real show-stopper for me right now).
(this may be out dated?)

**Comment by telephon** [comment]
Is still an issue. Retina seems to be supported only for the main window, not for widgets. I'm not sure if windows with ```UserView``` are widgets internally, but they all still show the same bug in ```QT5``` and ```OS 10.11```.

For those who do graphics with sclang, this is quite an issue.

I found this hint: http://stackoverflow.com/questions/23985143/how-do-i-enable-hidpi-retina-support-in-a-qt4-opengl-application

```QApplication::setGraphicsSystem("native");```

But where to put it? Any hint?

**Comment by telephon** [comment]
Here is an example:

<img width="402" alt="retina-rain" src="https://cloud.githubusercontent.com/assets/1810559/10869225/179deba8-80a9-11e5-96ad-419de2aff7f4.png">

**Comment by woutersnoei** [comment]
anyone still working on this? Issue #1810 is about the same problem..

**Comment by brianlheim** [comment]
once we are using a newer version of the Qt libs it will be worthwhile to revisit it.

**Comment by scztt** [comment]
I've got this mostly fixed in the WebEngine / QT update branch, with one or two more isolated fixes that I'll merge once the main enchilada is in place.

**Comment by telephon** [comment]
#3165
