### ISSUE TITLE
Sclang says "syntax error" but if I copy the file contents into sclang manually it works

### ISSUE THREAD

**Issue by zmrocze** [supercollider/supercollider#6314]
Hey!

## Environment

* SuperCollider version: 3.13
* Operating system: nixOs
* Other details (Qt version, audio driver, etc.): Qt = 5.15, pipewire

## Steps to reproduce

With a file [startup.scd](https://github.com/zmrocze/my-tidal-flake/blob/22b454db42f60222eef52397d5e855fb16d20338/startup.scd) like in the link I run:

```bash
sclang startup.scd
```

The link above directs to a nix flake, so if you are nix user you can reproduce it for example by running: `nix run github:zmrocze/my-tidal-flake#superdirt-start`. 

## Expected behaviour

I expect the command to work, because I can execute the `startup.scd` file "manually" pasting the commands into `sclang`. I'll describe this precisely:

The `startup` file is made of lines:

```supercollider
SuperDirt.start;
```

and a block of code surrounded in brackets:

```supercollider
(
var on, off, cc;
[...]
)
```

If I first input the `SuperDirt.start;` command and click enter, the command runs, prints output and stops printing after few seconds. The `sclang` prompt doesn't appear, but it appears if I click enter once again, so I do that.

Then I copy the whole code snippet inside brackets, brackets included, paste it into sclang and click enter. Now these commands execute printing some output and succeeding in the end. No errors neither syntax nor other appear.

## Actual behaviour

Because the script file can be executed in two steps I am surprised to find out that if I run `sclang startup.scd` directly with the whole script snippet, then I get a syntax error: 

```
compiling class library...
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
	Found 867 primitives.
	Compiling directory '/nix/store/2k7vd8jadyph59ma9wdsrz2w0alw03mk-supercollider-with-plugins-3.13.0/share/SuperCollider/SCClassLibrary'
	Compiling directory '/nix/store/2k7vd8jadyph59ma9wdsrz2w0alw03mk-supercollider-with-plugins-3.13.0/share/SuperCollider/Extensions'
	Compiling directory '/home/zmrocze/.local/share/SuperCollider/Extensions'
	Compiling directory '/nix/store/nn7g033l6aqvdhclh2pjw2p7q92fr192-SuperDirt/quark'
	numentries = 1300113 / 20328288 = 0.064
	5937 method selectors, 3424 classes
	method table size 21149408 bytes, big table size 162626304
	Number of Symbols 15410
	Byte Code Size 463821
	compiled 568 files in 0.28 seconds

Info: 4 methods are currently overwritten by extensions. To see which, execute:
MethodOverride.printAll

compile done
localhost : setting clientID to 0.
internal : setting clientID to 0.
Couldn't set realtime scheduling priority 1: Operation not permitted
Class tree inited in 0.01 seconds


*** Welcome to SuperCollider 3.13.0. *** For help type ctrl-c ctrl-h (Emacs) or :SChelp (vim) or ctrl-U (sced/gedit).
Couldn't set realtime scheduling priority 1: Operation not permitted
ERROR: syntax error, unexpected VAR, expecting ')'
  in interpreted text
  line 5 char 3:

  var on, off, cc;
  ^^^
  var osc;
-----------------------------------
ERROR: Command line parse failed
```

**Comment by cdbzb** [comment]
I can confirm this on Mac - any single line or code block followed by a second code block will error in this way - both using the CLI and using `.load`.  @zmrocze as a workaround please try putting all in a single code block and wrapping the second function with `s.waitForBoot` like so:
```
(
SuperDirt.start;
s.waitForBoot{
    var osc, ...
}
)
```
