### ISSUE TITLE
`.isKindOf("View")` and `.isKindOf("ScrollView")` return inconsistency value in macOS and Windows

### ISSUE THREAD

**Issue by prko** [supercollider/supercollider#6318]
## Environment

* SuperCollider version: 3.14.dev
* Operating system: Windows 11, macOS 14.4.1, Linux

## Steps to reproduce
Evaluate the following code line per line:
```
w
w = nil
w = Window()
w.isKindOf("View")
w.isKindOf("ScrollView")
w.isKindOf("View")
w.isKindOf("ScrollView")
w.isKindOf("View")
w.isKindOf("ScrollView")
w.isKindOf("View")
w.isKindOf("ScrollView")
```

## Expected vs. actual behavior
- Expected behaviour:
   - Each of `w.isKindOf("View")` should always return the same result.
   - Each of `w.isKindOf("ScrollView")` should always return the same result.
- actual behaviour
  inconsistency results. Watch the following video:
   https://www.dropbox.com/scl/fi/qddl4dojs5hweopun8j1q/Window.isKindOf.mov?rlkey=f82e1lll4edtxjbapahxcipz9&dl=0

In this video, the result on Linux seems to be consistent, but not.

Also evaluating the following code returns inconsistent values.
```
w.view.isKindOf("TopView")
w..view.isKindOf("ScrollView")
```

**Comment by telephon** [comment]
The first argument of the message `isKindOf` should be a class:
```
[].isKindOf("Array") // false
[].isKindOf(Array) // true
```

**Comment by prko** [comment]
Ah, thanks! Sorry for the wrong bug report!
