### ISSUE TITLE
Kill and yank lines in QtIDE

### ISSUE THREAD

**Issue by rukano** [supercollider/supercollider#633]
Some editors use crtl+k and ctrl+y for killing and yanking lines.
This is pretty useful for people who don't like to use the mouse to select a line, copy and paste it.
Is it possible to implement this behaviour in the the new IDE? Other usual commands are functioning already (ctrl+a, ctrl+e for moving to the start and end of a line). It would be very useful to keep this behavious which was present in the SCAPP and for people used to this commands on other different editors (emacs, text edit, etc...). It makes reorganizing code and duplicating lines for live coding much easier ;)

**Comment by brianlheim** [comment]
Closing—inconclusive discussion and inactivity. But, added [here](https://github.com/supercollider/supercollider/projects/3).
