### ISSUE TITLE
Failed build on Mac OS

### ISSUE THREAD

**Issue by nnbveh** [supercollider/supercollider#6389]
loning into '/Users/nnbveh/SuperColliderAU/supercollider/external_libraries/hidapi'...
fatal: unable to connect to github.com:
github.com[0: 20.205.243.166]: errno=Operation timed out

fatal: clone of 'git://github.com/supercollider/hidapi.git' into submodule path '/Users/nnbveh/SuperColliderAU/supercollider/external_libraries/hidapi' failed
Failed to clone 'external_libraries/hidapi'. Retry scheduled
Cloning into '/Users/nnbveh/SuperColliderAU/supercollider/external_libraries/link'...
remote: Enumerating objects: 2840, done.        
remote: Counting objects: 100% (1219/1219), done.        
remote: Compressing objects: 100% (516/516), done.        
remote: Total 2840 (delta 787), reused 859 (delta 695), pack-reused 1621        
Receiving objects: 100% (2840/2840), 2.23 MiB | 6.89 MiB/s, done.
Resolving deltas: 100% (1668/1668), done.
Cloning into '/Users/nnbveh/SuperColliderAU/supercollider/external_libraries/nova-simd'...
fatal: unable to connect to github.com:
github.com[0: 20.205.243.166]: errno=Operation timed out

fatal: clone of 'git://github.com/timblechmann/nova-simd.git' into submodule path '/Users/nnbveh/SuperColliderAU/supercollider/external_libraries/nova-simd' failed
Failed to clone 'external_libraries/nova-simd'. Retry scheduled
Cloning into '/Users/nnbveh/SuperColliderAU/supercollider/external_libraries/nova-tt'...
fatal: unable to connect to github.com:
github.com[0: 20.205.243.166]: errno=Operation timed out

fatal: clone of 'git://github.com/timblechmann/nova-tt.git' into submodule path '/Users/nnbveh/SuperColliderAU/supercollider/external_libraries/nova-tt' failed
Failed to clone 'external_libraries/nova-tt'. Retry scheduled
Cloning into '/Users/nnbveh/SuperColliderAU/supercollider/external_libraries/portaudio_sc_org'...
remote: Enumerating objects: 3981, done.        
remote: Total 3981 (delta 0), reused 0 (delta 0), pack-reused 3981        
Receiving objects: 100% (3981/3981), 2.38 MiB | 6.80 MiB/s, done.
Resolving deltas: 100% (2302/2302), done.
Cloning into '/Users/nnbveh/SuperColliderAU/supercollider/external_libraries/yaml-cpp'...
remote: Enumerating objects: 7047, done.        
remote: Total 7047 (delta 0), reused 0 (delta 0), pack-reused 7047        
Receiving objects: 100% (7047/7047), 3.10 MiB | 8.44 MiB/s, done.
Resolving deltas: 100% (4548/4548), done.
Cloning into '/Users/nnbveh/SuperColliderAU/supercollider/external_libraries/hidapi'...
fatal: unable to connect to github.com:
github.com[0: 20.205.243.166]: errno=Operation timed out

fatal: clone of 'git://github.com/supercollider/hidapi.git' into submodule path '/Users/nnbveh/SuperColliderAU/supercollider/external_libraries/hidapi' failed
Failed to clone 'external_libraries/hidapi' a second time, aborting
fatal: Failed to recurse into submodule path 'supercollider'

**Comment by capital-G** [comment]
It seems you want to build an older version of the SuperCollider source code which uses `git` submodules instead of `https` submodules.
Please take a look at https://github.com/supercollider/supercollider/issues/5695, use a more recent version of SuperCollider source code or download a tarball from https://github.com/supercollider/supercollider/releases

Please re-open if this does not fix your problem.
