### ISSUE TITLE
Unmatched Closing Parenthesis ')' in the Interpreted text

### ISSUE THREAD

**Issue by vLunarTides** [supercollider/supercollider#6391]
## Environment

* SuperCollider version:  ~13.3.0
* Operating system: Windows
* Other details (Qt version, audio driver, etc.): n/a

## Steps to reproduce

```supercollider

(
x = 4;
x = x*x;
x = x.neg;
x;
)

//same with

(
~val = 4;
~val = ~val.squared;
~val = ~val.neg;
~val;
)


```

## Expected vs. actual behavior

Each line works. My code starts on line 1. I'm expecting a value of -16. But when I run the last parenthesis (the entire code is highlighted) it results in the following error message...

Following along on a 

ERROR: Parse error
  in interpreted text
  line 1 char 1:

  ) 
  ^
-----------------------------------
unmatched ')'
  in interpreted text line 1 char 1
ERROR: syntax error, unexpected BADTOKEN, expecting end of file
  in interpreted text
  line 1 char 1:

  ) 
  ^
-----------------------------------
ERROR: Command line parse failed
-> nil

**Comment by vLunarTides** [comment]
Apologies, I am new to supercollider (and coding in general). TIL there is a difference between running the highlighted portion with 'shift' + 'enter' and 'ctrl' + 'enter'. You can also use Language > Evaluate Selection to evaluate either the region or single line. False alarm!

**Comment by JordanHendersonMusic** [comment]
No worries, if you haven't heard of it, there's also https://scsynth.org/ with lots of helpful people if you have more queries or just want to discuss other music/art/technology related things 😊
