### ISSUE TITLE
Nil.addAll should return a copy

### ISSUE THREAD

**Issue by JordanHendersonMusic** [supercollider/supercollider#6414]
## Environment

* SuperCollider version: 3.14
* Operating system:
* Other details (Qt version, audio driver, etc.):

## Steps to reproduce

```supercollider

a = [1, 2];
nil.addAll(a) === a;

```

## Expected vs. actual behavior

It should return a copy.

**Comment by telephon** [comment]
Yes, I agree this should be done.

**Comment by SimonDeplat** [comment]
Hello,
I can fix this and write the PR. I also propose to update the method to the piping syntax.

I tried: 
`addAll { |array| ^array.asArray.shallowCopy }`
which works.

However, I think this creates an unnecessary array every time the method is used on a non-collection object. This seems the right adjustment:
```
addAll { |array|
	if(array.isKindOf(Collection))
	{ ^array.asArray.shallowCopy }
	{ ^array.asArray };
}
```

Can anybody confirm ?

**Comment by JordanHendersonMusic** [comment]
Thanks for taking this up! 

I wouldn't try to avoid the copy. While you might be right about the class library classes, users can make their own collection class and overwrite `asArray` as they please - this means you have no guarantee that it is a newly created array. The safest thing is just to copy.
