### ISSUE TITLE
SCLang: Keyword arguments resolve collisions incorrectly.

### ISSUE THREAD

**Issue by JordanHendersonMusic** [supercollider/supercollider#6419]
## Environment

* SuperCollider version: dev
* Operating system:
* Other details (Qt version, audio driver, etc.):

## Steps to reproduce

```supercollider
f = { |a| a };

f.(1, a: 2);
// Ignoring duplicate keyword 'a' at position 0 found in function call
-> 1

f.(a: 1, a: 2);
-> 2
```

## Expected vs. actual behavior

As per docs, the last override should apply, meaning `f.(1, a: 2)` is incorrect.

 https://doc.sccode.org/Reference/Messages.html#Keyword%20Arguments

I will fix this (asI wrote this code) I am just a little busy right now.

**Comment by dyfer** [comment]
Closed in #6426 I believe
