### ISSUE TITLE
SCIDE: SCDoc Colours Reset to Defaults When 'Search' Button is Clicked

### ISSUE THREAD

**Issue by sidechained** [supercollider/supercollider#642]
Hey,

I have my colour scheme set to custom white on black in the IDE, which is replicated in SCDoc at first but resets to the default (black on white) when the search button is clicked. A fairly minor issue, but definitely an issue all the same...

Regards,
Graham

**Comment by brianlheim** [comment]
Pinging. @sidechained Can you answer jleben's questions, or can someone recreate?

**Comment by snappizz** [comment]
I think this is what happened -- they implemented a theme for the help browser using "custom.css" in order to match their editor theme, but the Search.html didn't respect custom styling. This was fixed in #1920.
