### ISSUE TITLE
Just a note, I've cosed the "discussion" tab for now.

### ISSUE THREAD

**Issue by telephon** [supercollider/supercollider#6425]
Just a note, I've cosed the "discussion" tab for now, it is useful but encourages people to ask questions here instaed of the forum. We can discuss it  under this bug report … hm, oh well.

**Comment by telephon** [comment]
Actually I realised that this removes access to the four past discussions, so I re-opened the tab for now. But let's close it after a while.

**Comment by capital-G** [comment]
Discussions tab is now closed, thanks @telephon
