### ISSUE TITLE
Using `-latest` Github Runner images in CI

### ISSUE THREAD

**Issue by dyfer** [supercollider/supercollider#6430]
## Motivation

@capital-G recently inquired about using the `ubuntu-latest-lts` runner image for sc3-plugins. 
I had considered this before and I wanted to share my thoughts here, with the idea that's applicable to both for SC and sc3-plugins.

## Description of Proposed Feature

I'd like to consider whether we want to switch some of our build jobs to use the `-latest` runner images, as opposed to fixed versions, which we use currently.

Pros of fixed version:
- build environment does not change out of our control (well, mostly, e.g. on macOS homebrew libraries still do get updated...)
- releases are built using consistent tools

Cons of fixed version:
- we need to periodically manually update the build matrix to check compatibility with newer systems
- if we wait too long and the runner image gets deprecated/removed, build jobs stop working (as was the case with sc3-plugins recently)

Pros of `-latest` version:
- **easier testing against new/current OSes and toolchains** - build environment automatically switches to the newest available OS (newest in the sense of their availability in GHA)
- theoretically there's no need to manually update the build environment once OS runner versions get updated
  - however, sometimes some build details still need to be adjusted for newer OS; i.e. build matrix might break when the new image is released
  - but that also forces us to update compatibility not only in our GHA setup, but also documentation and possibly other areas of the project(s)

Cons of `-latest` version:
- we might be forced to fix our builds when the runner images update (i.e. timing of that would be controlled by GHA updates, not developers availability)
- if used for release builds, it would possibly cause switching the build environment in the middle of the release process

Implied above, but to spell it out: I think there are two slightly different goals with the CI: 
1. testing build environment
2. creating release and testing binaries

I think it would be reasonable for `1.` to target the newest OSes and `2.` to use fixed image versions.

Finally, the changes in GHA have different timing for different OS environments: Windows seems to be updated every 3 years, Linux every 2 years (coinciding with Ubuntu LTS releases) and macOS every year (for every new major macOS version).

## Plan for Implementation

My proposition is to keep fixed OS versions for the main release builds for macOS and Windows, but to add `-latest` images for testing build envifornment.

I think the relevance of this change is different for each platform, due to different timing of their updates.

macOS seems the most affected, as it changes most frequently. I think we could switch the "use system libraries" build to run on the `latest` macOS in order to check compatibility with the newest provided toolchains (this also broke most recently). This can only happen after we upgrade boost (see #5865 and linked/related PRs)

I think on Linux we could add one more job using the `ubuntu-latest-lts` image, which would use the default gcc provided in that image. Otherwise we have a matrix set up to test for a range of compiler compatibility and I don't think we should switch all that up.

On Windows - the change is so infrequent that I'm not sure it's worth the extra GHA job. Also, the way our matrix is set up, some parameters would need to be updated every time the runner image is updated (like the version of MSVC to use). So maybe Windows can stay as is?

Any comments welcome!

**Comment by dyfer** [comment]
> Personally, I am not a fan of implicit updates (via `latest`), but I do support getting to the latest OS release as soon as possible.

Got it. So maybe we should just keep our matrix updated manually :) 

I think my points about using different versions for testing build vs making a release is still valid though.


> I think something like dependabot could be useful here

Maybe... but a manual update is marginally more work, so I don't think adding automation here adds any value.

> That said, is it that likely that we will break a build once it compiles on the platform? It is not like we have constant changes here. Changes that would break things once compiled are most likely the introduction of new compiler features or updates to dependencies, both of which happen infrequently here?

Idk. The original point of the CI, particularly of the extensive Linux matrix, was to keep track of when we break things. It's not often, but CI exists partially to make us aware of that.

It does not mean that we shouldn't keep the CI updated - we just haven't lately.

> 
> Maybe we can add a version table to the readme that matches which OS version is compatible/officially tested with each SC version, something along the lines of

Ah, that's a nice idea, though that would be another thing to keep updated manually. I guess our README only states what's supported in the _current_ version (which sometimes means the last minor version, sometimes the upcoming release...)

**Comment by capital-G** [comment]
> Ah, that's a nice idea, though that would be another thing to keep updated manually. I guess our README only states what's supported in the _current_ version (which sometimes means the last minor version, sometimes the upcoming release...)

We also have the website where most people will take a look at prior to downloading - maybe we can put it there? :) This would be indeed a great resource combined with all download links to old versions.

> Maybe... but a manual update is marginally more work, so I don't think adding automation here adds any value.

ofc, but someone needs to remember to bump the CI - but yeah, as it is currently not an available feature of dependabot, lets skip on this idea.

> Idk. The original point of the CI, particularly of the extensive Linux matrix, was to keep track of when we break things. It's not often, but CI exists partially to make us aware whenever we break something.

Maybe we should stick more closely to our support agreement, quoting from https://github.com/supercollider/supercollider/wiki/Platform-Support#platforms

---
The following platforms are supported:
- macOS: 2 years, 2 major releases (i.e. Mojave 10.14, Catalina 10.15)
- Windows: 4 years, 4 major updates
- Ubuntu: 4 years, 2 LTS releases
- Debian: 4 years, 2 major releases
- Fedora: latest release
- Arch Linux: latest release
- Raspberry Pi (Raspbian): latest release
- BeagleBone Black (Debian): latest release
---

**Comment by redFrik** [comment]
let's drop support for BeagleBone Black.  i had a hand in adding that, but my impression now is that no one is using it.

**Comment by dyfer** [comment]
> Maybe we should stick more closely to our support agreement

Yeah, we should :)
We could also update testing to reflect compilers compatibility outlined in this document.

**Comment by capital-G** [comment]
Maybe once the boost upgrade (see #6334 ) is done we can bump/re-adjust the CI matrix?

I'd propose to focus on the latest versions in order to be aware early on any potential failures and guarantee a long lasting lifetime of the binary upon download.

Here is a proposition, where we include the most recent version of a compiler and the default version from the package manager, and the prior version of an OS with defaults from the package manager. This already results in more than 14 builds!

<table><thead>
  <tr>
    <th>Operating system</th>
    <th>Version</th>
    <th>Compiler</th>
    <th>Platform</th>
    <th>Comment</th>
  </tr></thead>
<tbody>
  <tr>
    <td rowspan="5">Ubuntu</td>
    <td rowspan="3">24.04</td>
    <td>clang 18</td>
    <td>x64</td>
    <td>Currently dev &amp; stable version</td>
  </tr>
  <tr>
    <td>gcc 14</td>
    <td>x64</td>
    <td>dev version</td>
  </tr>
  <tr>
    <td>gcc 13</td>
    <td>x64</td>
    <td>stable version</td>
  </tr>
  <tr>
    <td rowspan="2">22.04</td>
    <td>clang 14</td>
    <td>x64</td>
    <td></td>
  </tr>
  <tr>
    <td>gcc 11</td>
    <td>x64</td>
    <td></td>
  </tr>
  <tr>
    <td rowspan="4">macOS</td>
    <td rowspan="3">14</td>
    <td rowspan="3">xcode 15</td>
    <td>x64</td>
    <td></td>
  </tr>
  <tr>
    <td>arm</td>
    <td></td>
  </tr>
  <tr>
    <td>universal</td>
    <td>also build with system-libraries<br></td>
  </tr>
  <tr>
    <td>13</td>
    <td>xcode 14</td>
    <td>universal</td>
    <td></td>
  </tr>
  <tr>
    <td rowspan="4">Windows</td>
    <td rowspan="3">2022</td>
    <td rowspan="2">msvc</td>
    <td>x64</td>
    <td></td>
  </tr>
  <tr>
    <td>x86</td>
    <td></td>
  </tr>
  <tr>
    <td>mingw</td>
    <td>x64</td>
    <td>without qt webengine<br></td>
  </tr>
  <tr>
    <td>2019</td>
    <td>msvc</td>
    <td>x64</td>
    <td></td>
  </tr>
</tbody></table>


Feel free to suggest edits to this, I created it with https://www.tablesgenerator.com/html_tables#, the CSV which can be imported is located @ https://gist.github.com/capital-G/98b3acdfa6f7abdaf22b652fd72bb731 (click display raw)

**Comment by dyfer** [comment]
> Maybe once the boost upgrade (see #6334 ) is done we can bump/re-adjust the CI matrix?

Yes! Actually, I was planning to do that as a part of the upcoming Qt deprecations PR, en route to Qt6 migration, see here: https://github.com/supercollider/supercollider/commit/71277ae23c404488da0383dcff16151c932380fe
> 
> I'd propose to focus on the latest versions in order to be aware early on any potential failures and guarantee a long lasting lifetime of the binary upon download.

I think that's generally a good idea.
We should definitely try to keep it close to the supported compilers matrix from the readme. In the branch above I didn't follow that as closely as I could, but I also remember that clang 16 wasn't available for some reason, so I kept clang 15 as the highest in the Linux matrix. I'll revise this before making the PR.
In the branch above I tried to keep "4 most recent + one oldes" from both GCC and Clang, so that we can catch issues on both ends of the supported (and unsupported, for the older ones) spectrum.

> Feel free to suggest edits to this, I created it with https://www.tablesgenerator.com/html_tables#, the CSV which can be imported is located @ https://gist.github.com/capital-G/98b3acdfa6f7abdaf22b652fd72bb731 (click display raw)

Nice, thanks for the reference!

> I think it still would be interesting to add binary builds for other platforms like RaspberryPi, Beaglebone etc - 

Oh yes, I would love that! But never had the time to investigate setting up cross-compilation CI.

> We should also add a matrix "operating version vs latest supported SuperCollider version"

Yes. Probably in the readme? Or on the website? I think it should be _one_ of those places, otherwise they will inevitably get out of sync.

**Comment by JordanHendersonMusic** [comment]
> We could also consider removing the Windows 32-bit build

One thing is that it is the only 32 bit system we check. In something like my nan-boxing pr, this is really important. Could it be replaced with a Linux one?

**Comment by dyfer** [comment]
In that case we can keep building it. 
We could also keep building it and remove it from the release process. The nice thing about that is that once release candidate is published, and people complain about it, we can easily bring it back.

**Comment by capital-G** [comment]
> Yes! Actually, I was planning to do that as a part of the upcoming Qt deprecations PR, en route to Qt6 migration, see here: [dyfer@71277ae](https://github.com/dyfer/supercollider/commit/71277ae23c404488da0383dcff16151c932380fe)

BTW, would you mind making this a WIP PR here? Makes it easier to track what the state is and refer to it if necessary.

**Comment by dyfer** [comment]
> BTW, would you mind making your Qt branch a WIP PR here?

I try to document my progress in https://github.com/supercollider/supercollider/issues/5169. There you can also find the reference to the (finally working) [qt6 branch](https://github.com/dyfer/supercollider/tree/topic/qt6-27).
