### ISSUE TITLE
"Source" link should go to online revisions of the source code

### ISSUE THREAD

**Issue by masaeedu** [supercollider/supercollider#6431]
## Motivation

Hello. I think it'd be useful if the "Source" link in online class docs pointed to a file in an online hosted copy of the source code for each release (e.g. but not necessarily here on GitHub).

Among other things this would be useful for users of FHS-divergent distros like NixOS, or for someone reading about a feature or class that has changed over time.

## Description of Proposed Feature

The "Source" link of the online documentation (hosted at https://doc.sccode.org/) would no longer contain a `file://` URL pointing at the user's filesystem. It would instead contain a durable, publicly accessible URL, referring to the source code intended by the documentation.

E.g. the [docs](https://doc.sccode.org/Classes/Environment.html) for the `Environment` class currently have a "Source" link like this:

> file:///usr/local/share/SuperCollider/SCClassLibrary/Common/Collections/Environment.sc

Depending on whether...

- you have SuperCollider installed at all
- you're on an FHS compliant system
- you have an appropriate file type handler set up

...that link may or may not go anywhere.

In the proposed implementation the link URL would instead be:

> https://github.com/supercollider/supercollider/blob/1ad87e4d76e85bea78eda0294c9f83f57229ab4c/SCClassLibrary/Common/Collections/Environment.sc

(or whatever tag/revision the docs were generated from). Now the link works for anyone...

---

...provided they can reach GitHub, and your source code is still hosted here. I assume this is probably a pretty safe bet, but just in case:

Another option is that the source code files are baked into the docs site, and then each "Source" can be a relative URL. This might be attractive because it makes a particular revision of source and docs a closed system with no external references, invulnerable to e.g. a change of primary source code host.

Maybe worth noting the SuperCollider derivation for NixOS seems to have already worked out how to do this. A "Source" link in the SuperCollider IDE on NixOS points to

```
file:///nix/store/gf2drba9mmr9y0r16armm89xpcffak2r-supercollider-with-plugins-3.13.0/share/SuperCollider/SCClassLibrary/Common/Audio/SynthDef.sc
```

(where `gf2drba9mmr9y0r16armm89xpcffak2r-supercollider-with-plugins-3.13.0/` realizes an internally consistent packaging of source code and docs for the version of the IDE you're running).

## Plan for Implementation

> Who will implement this? 

I'd be happy to try and implement this, once I know a direction to go and learn enough about the doc-building process.

> How long will it take?

I can't say exactly how long it will take, it would depend on which approach you folks find best, and how much meta information is already available to the process generating the documentation. The first approach (simple GitHub link) doesn't seem like it should be super hard to do though.

**Comment by capital-G** [comment]
Hello @masaeedu , thanks for your suggestion.

The actual "official" docs (or at least docs that are maintained by the devs), which are located at https://docs.supercollider.online/ for latest stable and https://dev.docs.supercollider.online/ for latest dev version, have this exact feature, see e.g. https://docs.supercollider.online/Classes/Gendy3.html 
The docs are built through the repo https://github.com/supercollider/sc-docs

It seems that docs.sccode.org is currently unmaintained (as it is using version 3.12), and it is also not clear who is responsible for this site (although see https://github.com/supercollider/supercollider/pull/5872#issuecomment-1312790656 ), but there is not really much that the GH-SC-community can do about this site.

Does this resolve the enhancement request?

**Comment by masaeedu** [comment]
@capital-G It does, thank you! Would it be better to use a separate issue to track doing a pass that replaces sccode.org with the "official" docs URL everywhere (e.g. in the README)?

**Comment by capital-G** [comment]
Yes, this would be a great thing! Can you make a PR for this? :)

**Comment by masaeedu** [comment]
Yup!
