### ISSUE TITLE
GHA: using version numbers for Linux OS identifiers?

### ISSUE THREAD

**Issue by dyfer** [supercollider/supercollider#6455]
## Motivation

We currently use the Ubuntu distribution names to indicate runner image OS version for our Linux builds:
```
...
- Linux focal gcc9
- Linux jammy gcc10
...
```
As I was updating the build matrix, I found myself looking up (again) the names of the distributions, corresponding to the version numbers (22.04, 24.04). The version numbers refer to the release year and month, which IMO makes it easier to identify the OS, as opposed to the name, which is more obscure for those not using Ubuntu on regular basis.

## Description of Proposed Feature

This is cosmetic, but I propose that we use **version numbers** to describe Linux builds. These numbers refer explicitly to _Ubuntu_ versions, so I wonder whether the jobs should be called `Linux` or `Ubuntu`. In either case, I'd find them easier to understand.

I suggest to go with either
```
- Linux 20.04 gcc9
- Linux 22.04 gcc10
```
or
```
- Ubuntu 20.04 gcc9
- Ubuntu 22.04 gcc10
```

What do you think?

## Plan for Implementation

I'd implement whatever we agree on.

**Comment by capital-G** [comment]
I'd vote for `Ubuntu 22.04 gcc10`, seems to be the most explicit and matching to me.
