### ISSUE TITLE
Document Buffer.freeAll because it doesn't free all the buffers.

### ISSUE THREAD

**Issue by JordanHendersonMusic** [supercollider/supercollider#6461]
## Motivation

I don't know what `Buffer.freeAll` and there is no documentation. It does not free all the buffers.

## Plan for Implementation

Does any one know what this does?
@telephon and @jamshark70 git blame says you were the last two people to touch this (a long time ago mind you!), do either of you happen to remember what this is supposed to do?

**Comment by jamshark70** [comment]
Do you have a concrete reproducer where Buffers are not freed?

The way the method is written now is: It iterates over all of the "used" buffer numbers that have been allocated in the bufferAllocator, and adds a "/b_free" message for each one to a bundle.

AFAICS there are two ways it could fail:

- If the user is manually specifying buffer numbers, then the buffer allocator wouldn't know about them. Probably nobody is doing this unless they know what they are doing (and if they know what they are doing, they would have less need of a convenience method like `freeAll`).
- Or, it could fail if the bundle gets too large. (This would be easily solved by clumping the bundle to some maximum size, and sending multiple bundles.)

(FWIW I think the intent of the method is very clear from the name.)

**Comment by jamshark70** [comment]
BTW I think we can pretty much rule out the "large bundle" issue, at least for local servers. Here's a test that creates 1024 buffers, and `freeAllBuffers` *does* remove them all. ("Hard coding wait times is bad" but s.sync seemed not to release the thread, a majority of the time, so I didn't have much of a choice.)

```
(
s.waitForBoot {
	var responses = IdentitySet.new;
	var resp;
	var num = s.options.numBuffers;
	
	s.dumpOSC(1);
	1.0.wait;
	
	"creating".postln;
	b = Array.fill(num, { Buffer.alloc(s, 1024, 1) });
	// s.sync;
	2.0.wait;
	
	"freeing".postln;
	s.freeAllBuffers;
	// s.sync;
	2.0.wait;
	
	"querying".postln;
	resp = OSCFunc({ |msg|
		if(msg[2] > 0) {
			responses.add(msg[1]);
		};
	}, '/b_info');
	
	num.do { |id|
		s.sendMsg(\b_query, id);
	};
	3.0.wait;
	resp.remove;
	"b_infos".postln;
	responses.postln;
	r = responses;
};
)
```

So I feel like the blanket statement that "it doesn't free them all" perhaps would benefit from some qualification. It sounds as though there is a specific failure case in mind, but it's difficult to evaluate that when the failure case is not specified.

**Comment by JordanHendersonMusic** [comment]
> Do you have a concrete reproducer where Buffers are not freed?

Ah... I've made a mistake! I was trying to speed up a unit test and I've misread buffer as bus!!! :facepalm: So of course, `busses.do { b.free }` isn't replaceable with `Buffer.freeAll`!

So I am going to close this. Thank you for having a look at this, sorry for the confusion, teach me not to work on stuff late at night!
