### ISSUE TITLE
Which OSes can we support in the Mac/Win binaries for the upcoming release?

### ISSUE THREAD

**Issue by dyfer** [supercollider/supercollider#6482]
## Motivation

I'd like to use this issue as a centralized place to discuss plans for revising the builds that we offer for macOS and Windows. This would also involve discussing potentially the tooling and library versions that we support. Here's a loose list of matters to consider:
- maintaining compatibility with QT 5.15 after moving to Qt 6
- sources for macOS libraries: `homebrew`, `vcpkg`, `macports`
- macOS: building one "universal" build vs separate x64_64 and arm64 builds
- macOS: building the "legacy" build
- Windows: building the 32-bit build
- Windows: introducing a "legacy" build for Windows 7, 8

In the past I have argued to keep the macOS and Windows binaries compatible as far back as we can, as those with older hardware might be locked into older operating systems. The counterargument were about managing the developer's time in context of supporting current OSes and toolchains, as well as security considerations for things like QtWebEngine. I still would like to maintain a good level of backward compatibility of our binary distributions, but I don't want to do this beyond some reasonable level - which I'd like us to agree on.

[Here are some download statistics for the releases.](https://tooomm.github.io/github-release-stats/?username=supercollider&repository=supercollider)

Backwards compatibility depends on various factors and differs a bit between macOS and Windows. In both cases backwards compatibility depends on the use of up-/outdated system APIs. AFAIR, we haven't had any of the native system calls updates recently (aside from `std::filesystem` but that's not strictly an OS API change), so I'd like to point out the other factors here.

### macOS target OSes

On macOS backwards compatibility is defined by **`deployment target`** set when building the app _and its dependent libraries_. In practice, the deployment target is limited by:
- deployment target set when building (we're in control of that)
- supported platforms of Qt
- deployment target set in the libraries we link to (like `libsndfile`)
- c++ features (see `std::filesystem` change)

First, Qt support (oldest OS listed):

| Qt | macOS |
| - | - |
| 5.15 | 10.13 |
| 6.2-6.4 | 10.14 |
| 6.6 | 11 |
| 6.8 beta | 12 |

The deployment target of the 3rd party libraries is tricky. By default we support homebrew for our libraries. Howebrew libraries are generally built for the version of the OS they are deployed for, i.e. homebrew packages on macOS 12 have the deployment target set to macOS 12. When we're building SC targeting a lower deployment target and link to such libraries, we get a warning, but depending on which APIs the library uses, it might still work in the older OS. _This is what's happening in the main build_ currently, since we use Qt and all the libraries from homebrew. Even though we targeted macOS 10.14 until recently, it turned out that the dev builds [were not compatible with that OS](https://github.com/supercollider/supercollider/issues/6125). 

That's why we started using vcpkg on macOS. In vcpkg we can also specify the deployment target the library is build for. We set it to the same target as the SC version that's being build. We use vcpkg for the legacy build.

If we consider using another source for libraries, like MacPorts, we need to consider what deployment target is used in their binaries. 

The recently incorporated `std::filesystem` change bumped up the oldest deployment target we can use to `10.15`. I believe this is a necessary step forward. However, after the release, if it turns out that there are many people who still use 10.13 or 10.14 requesting a build, we _could_ consider making a one-off more compatible legacy build. That would be on a separate branch, reverting the `std::filesystem` and boost updates, if there were no other changes that would need to be reverted. 

### Windows target OSes

IIUC, on Windows we don't have an equivalent of a deployment target when building. In this case our practical limit is only with the Qt version, aside from the system APIs used. Here's the Windows support in Qt (oldest only listed):

| Qt | Windows |
| - | - |
| 5.15 | 7 |
| 6.2-6.8 beta | 10 21H2 (1809?) |

That means that after updating to Qt 6, we'll loose support for Windows 7 and 8 in the main build.

### Qt 5.15 compatibility

One reason to remove compatibility with Qt 5.15 is to remove some old code and a number of switches in the sources. The [Qt6 PR](https://github.com/supercollider/supercollider/pull/6475) currently maintains 5.15 compatibility, with 30+ preprocessor statements throughout the cpp codebase, managing the differences between Qt 5.15 and 6.2+. We can consider removing Qt 5.15 compatibility for a cleaner code. I personally wouldn't do this until we encounter actual difficulties maintaining it.

### macOS builds and tools to consider

IMO for building SC, using homebrew is still the preferred environment, and we should keep supporting that. 
However, for the releases, we might want to move away from homebrew, in order to have a better control over the range of supported OSes.

Additionally we should decide whether we keep making the universal build, or separate builds for x86_64 and arm64. There is no clean way to create universal binaries currently - we are using a custom script to achieve that using homebrew packages (more info in https://github.com/supercollider/supercollider/issues/6480). Vcpkg does not provide universal binaries either - I was exploring that option, but I was eventually unsuccessful, with some dependencies not building properly as universal libs. Vcpkg still provides a good option for single-architecture libraries, where we're in control of the deployment target.

@capital-G suggested that MacPorts could provide an alternative, but I haven't looked into that. We'd need to know what is the deployment target of the libs distributed there?

### Windows builds to consider

A while back some devs suggested dropping the Windows 32-bit build, as it was speculated that people are downloading the 32-bit build by accident or without knowing they have a 64-bit OS. If we remove Qt 5.15 support, we won't be able to make 32-bit builds with Qt/IDE anymore (sclang/scsynth alone would probably still work?). I think @JordanHendersonMusic recently brought this up in the context of testing https://github.com/supercollider/supercollider/pull/6365, but I can't find this comment now. Instead of removing it, we can keep building 32-bit Windows, but not upload its artifact to the release page, essentially "hiding" it from the release. That way we can still check if it builds, or even run builds from the GHA page, but phase it out from use.

Aside from dropping the 32-bit Windows build, we may also encounter users on Windows 7 or 8 discovering they can't run upcoming SC 3.14 (or current develop) after the Qt6 migration. If that happens, we may consider making a "Windows 64-bit legacy" build, that uses Qt 5.15 (if we don't remove the support for it). That should be very straightforward to add.

## Description of Proposed Feature

I propose to revise the build configuration as follows, after the qt6 update. 
I'm open to suggestions!

- macOS
  - 3 builds creating binaries:
    - main x86_64: Qt 6.7.2 from the binary distribution; other 3rd-party libraries from vcpkg
    - main arm64: same configuration as main x86_64
    - legacy x86_64: Qt 5.15.2 from the binary distribution; other 3rd-party libraries from vcpkg 
  - pros:
    - main builds supporting wider range of OSes (macOS 11+)
  - cons
    - none of the builds creating binaries use homebrew (the "system libraries" build still would though)
      - it's harder to test that setup, which is still the "recommended" way to build SC
      - it looks like we won't be able to use verify_app with Qt6 from homebrew (https://github.com/supercollider/supercollider/issues/6481)
  - we could consider using MacPorts instead of vcpkg, which might allow us to make a universal build, but I'm not sure if that makes a difference since we'd still have the problem of the homebrew configuration not being "tested in the wild"
  - for the x86_64 and legacy builds, we could consider "splitting the difference" and using  Qt 6.4 from the binary distribution; other 3rd-party libraries from vcpkg; that way it would be compatible with macOS 10.15 and we wouldn't need to make a separate legacy build; however, it would not include QuartzComposerView (deprecated, but still present in macOS Qt5 builds, as of the current state of Qt6 migration)
- Windows
  - 2 builds creating binaries:
    - x64: Qt 6.7.2
    - x32: Qt 5.15.2
  - 32-bit build removed from the release uploads
  - if requested, consider adding "x64 legacy" build using Qt 5.15.2

## Plan for Implementation

I'm happy to implement these changes, once we agree on the path forward.

**Comment by capital-G** [comment]
Thanks for you excellent summary!

Just to get some reference from other projects at the beginning:

Software | min macOS | min Windows
--- | --- | ---
Ableton 12 | macOS 11 | Windows 10 22H2
Adobe Premiere 24.x | macOS 12 | Windows 10 22H2
Reaper 7 | OS X 10.5 | Windows XP
Cubase 13 | macOS 12 | Windows 10 22H2
ProTools 2024 | macOS 12 | Windows 10 22H2
Max 8 | OS X 10.15 | Windows 10
PureData | OS X 10.6 (?) | Windows XP
SuperCollider 3.13 | OS X 10.10 | Windows 7

---

I would be interested why people actually *need* the newest SuperCollider version on an older OS (e.g. macOS 10.13)?

While I have a heart for people with older hardware, we need to choose our fights and time here. 

I think the tendency towards legacy support in code and platforms is understandable,yet it slows us down considerably and makes new features hard to implement, which I think is **not healthy** for any project in the long run.
There seems to be always people, passing by, who question this necessity of legacy support, while there are some people in charge who (not) swiftly say "legacy is prio 1".
Concerning this *passing by*, I think this could be a chicken/egg problem, depending from which side you are looking at it. But this would be something for another Issue/discussion.

For myself, I think I am not alone by spending a considerable amount of dev time to maintain legacy support - to machines, OS and code.
E.g. the Boost upgrade (https://github.com/supercollider/supercollider/pull/6477, https://github.com/supercollider/supercollider/pull/6334, https://github.com/supercollider/supercollider/pull/5920), where the latest iteration was delayed by multiple months due to our (unofficial) mingw support.
As an alternative: this PR could have been merged within a few days and the mingw fix could have been a PR by a person who cares about mingw support.
And this itself was also only a platform support PR, to get proper compilation support on the most recent macOS version, which I think should be the prio of `dev`: Have SC compiling and working on the newest available platform, as this will be the future of SuperCollider. E.g. I currently don't upate my macOS b/c of this, but I don't see doing such a thing another time because it makes building other things difficult for me.

---

> maintains 5.15 compatibility, with 30+ preprocessor statements throughout the cpp codebase [...] I personally wouldn't do this until we encounter actual difficulties maintaining it.

This already sounds like technological debt which makes our codebase more complex and that will take some effort to get removed in the future, and considering our limited dev time, I'd say if we have Qt6 support, "go full Qt6". Otherwise this will bloat our code and CI pipeline and we will have discussions about when to deprecate Qt5, where *now* would be the moment to deprecate it in order to save our resources.

> none of the builds creating binaries use homebrew

The more I work with homebrew the more I dislike it due to its rolling nature. Additionally they don't provide fine-grained nuances like deployment target or architecture/cross compilation.
It seems homebrew is fine as a default local package manager, but if you need fine-grained builds this seems not like a reliable partner. I wonder how other projects do this? Do they use CI for "does it compile" and do local full "native compilation" for releases?

Concerning MacPorts, quoting from the [MacPorts mailing list](https://trac.macports.org/ticket/54332)

> You can set `macosx_deployment_target` and `macosx_sdk_version` in `macports.conf`. They're undocumented because not all ports honor these settings. 

Also, very interesting seems [this repo](https://github.com/macports/macports-legacy-support), *MacPorts support for missing functions in legacy macOS versions*.

---

Regarding Windows32 builds - let's drop it, it is 2024 and the last 32bit only CPU from Intel was sold in 2003. I don't see a use case why anyone would still be on a 32bit Windows - yet on Linux I could understand.
On the other hand, Windows on ARM becomes a thing, so maybe we should include/prepare such a build as this will be the future? I think more people will interested in a SuperCollider Windows ARM build than a  Windows x86 build, and x86 people can still use SuperCollider 3.13.

In the end, if someone steps up to take care of such a build I am fine, but *only* if this will not drag general development and obfuscate the code considerably.

---

I'd therefore propose (instead), in accordance to our [Platform support commitment](https://github.com/supercollider/supercollider/wiki/Platform-Support)

<table><thead>
  <tr>
    <th>Operating system</th>
    <th>Version</th>
    <th>Compiler</th>
    <th>Platform</th>
    <th>Comment</th>
  </tr></thead>
<tbody>
  <tr>
    <td rowspan="5">Ubuntu</td>
    <td rowspan="4">24.04</td>
    <td>clang 18</td>
    <td>x64</td>
    <td></td>
  </tr>
  <tr>
    <td rowspan="3">gcc 13</td>
    <td>x64</td>
    <td>flatpack version, reference, Linux testing</td>
  </tr>
  <tr>
    <td>arm</td>
    <td></td>
  </tr>
  <tr>
    <td>x86</td>
    <td></td>
  </tr>
  <tr>
    <td>22.04</td>
    <td>gcc 11</td>
    <td>x64</td>
    <td>legacy build</td>
  </tr>
  <tr>
    <td rowspan="3">macOS</td>
    <td rowspan="2">14</td>
    <td rowspan="2">xcode 15</td>
    <td>arm64<br></td>
    <td>reference, using brew, macOS testing</td>
  </tr>
  <tr>
    <td>x64</td>
    <td>"legacy", cross compile via MacPorts</td>
  </tr>
  <tr>
    <td>12</td>
    <td>xcode 13</td>
    <td>x64</td>
    <td>legacy_legacy, using brew as long as possible</td>
  </tr>
  <tr>
    <td rowspan="3">Windows</td>
    <td rowspan="2">2022</td>
    <td rowspan="2">msvc</td>
    <td>x64</td>
    <td>reference, Windows testing</td>
  </tr>
  <tr>
    <td>arm</td>
    <td></td>
  </tr>
  <tr>
    <td>2019</td>
    <td>msvc</td>
    <td>x64<br></td>
    <td>legacy</td>
  </tr>
</tbody></table>

Therefore, I'd drop the current "macOS use system libraries" version, which is, iiuc, "use boost from brew instead of our provided boost".

**Comment by dyfer** [comment]
Thank you for all your comments!

> Just to get some reference from other projects at the beginning:

Yes, I see Reaper as the "gold standard" here 😄

> I would be interested why people actually _need_ the newest SuperCollider version on an older OS (e.g. macOS 10.13)?

Good question. I think this would be mostly for the gradual improvements and fixes that are added to SC and the plugins. But I can also accept that we may say that only older version of SC runs on older systems. This may also come up if we break plugin interface compatibility (last time that happened I believe was 3.9 -> 3.10). 

I wanted to turn around this questions: why people keep using older OSes? The main case that I think is relevant for us are "stable configurations" for studio/live music work. macOS update cycle happens at a (relatively) breakneck pace - re-installing all the software, plugins, settings etc every year is rather cumbersome. Of course, one can just let the OS update itself, but I don't think that process is recommended when the machine is used in a relatively "critical" role of realtime audio processing. I'm only putting this out here so that we keep this in mind when we make changes to supported platforms.

> E.g. the Boost upgrade (#6477, #6334, #5920), where the latest iteration was delayed by multiple months due to our (unofficial) mingw support.

This was unfortunate, yes. But the other reason was that we (I?) was hoping that we can make the plugin interface changes first, so that the boost update doesn't affect flucoma. Time has passed and it hasn't happened unfortunately.

> I'd say if we have Qt6 support, "go full Qt6".
> Otherwise this will bloat our code and CI pipeline and we will have discussions about when to deprecate Qt5, where _now_ would be the moment to deprecate it in order to save our resources.

Did you mean deprecate or remove?

I am willing to add commit(s) removing Qt5 in the Qt6 PR, as long as the devs agree as a group that this is what we want to do.

> > You can set `macosx_deployment_target` and `macosx_sdk_version` in `macports.conf`. They're undocumented because not all ports honor these settings.

That's good information. Still, `not all ports honor these settings` means we'd need to test this on a case by case basis.

Currently we have the ability to build dependencies for macOS (except Qt) in any _single_ architecture with vcpkg. It already works. Is it worth spending time swapping this for macports? This is all in CI, not suggesting swapping the "official" homebrew approach (which _could_ be considered later).

> I'd therefore propose (instead), which also matches our [Platform support commitment](https://github.com/supercollider/supercollider/wiki/Platform-Support)

Thanks for this. I have a few questions/comments:
- Linux 
  - I'd treat binary releases as a separate issue, as we don't provide binary packages currently
    - issues to resolve include jack/pipewire communication and discussion on the standalone app 
    - #3604, #5938, #5898, #6393
  - Ubuntu 22.04 has Qt 6.2 - I don't think this needs to be a legacy version, unless you meant a binary that supports Ubuntu 22.04, which would indeed need to be different than the one for 24.04
  - I like the idea of adding cross-compiled configs for `arm64` and `x86`; that's some extra work though, but would be great, especially if that could mean streamlining support for e.g. Raspberry Pi
- macOS
  - I _strongly_ feel that the main arm64 build should run _at least_ on macOS 12 (none of the commercial software you listed requires a higher macOS version); if this works when building on macOS 14 with homebrew, we can do that; otherwise I'd consider making a _separate_ build that uses homebrew, and separate "main" build that uses other package manager for arm64
  - "legacy" x86_64 - again - why macports and not vcpkg?
  - "legacy legacy" - I think that the "legacy" build should support macOS 12 or 11 and there'd be no need for "legacy legacy"
- Windows
  - I like eventually adding the arm build
  - for the older MSVC - I don't think we'd need to make a binary of that, would we? I think the resulting supported OSes would be the same (mainly set by the Qt version); but I agree that it would be good to build with both older and newer MSVC

**Comment by capital-G** [comment]
> Yes, I see Reaper as the "gold standard" here 😄

Me too, Reaper is somehow a miracle on multiple levels - maybe we can get some devs from them to help us? :D They seem to tackle stability, performance, fast-paced features upon a wide variety of platforms.
Maybe it is actually not a bad idea to ask them for some advice concerning (OS) support, maybe just as an estimation of how much of their time gets spend on "legacy" support, and the do's and don'ts regarding such support? E.g. I think they also rely on Qt? I have the feeling they could be open to share some insights, maybe behind doors?

> I wanted to turn around this questions: why people keep using older OSes? The main case that I think is relevant for us are "stable configurations" for studio/live music work.

Indeed very valid and relatable, and I feel that our dependencies/surroundings are pushing us at a faster space than we are comfortable. Yet I think we should always have a priority on the most recent platforms on dev branch and we need to see how we invest our time.

> Did you mean deprecate or remove?

I'd personally say we should remove Qt5 support if it adds further complexity and support issues, but this is only my uneducated opinion. This needs to be evaluated thoroughly, it is maybe the biggest decision for the next release?

I think the people who commit(ed) to work on Qt related code should decide on this as they can give the best estimate about the impact - you are definitely such a person. If you think Qt5/6 support is feasible and you say you take care of it, I am fine with keeping Qt5 support.

Maybe we could keep Qt5 around, deprecate it for a 3.14 release and remove it in 3.15? This would help to give some more years of Qt5 while also not having to deal with some legacy Qt5/6 mixing until Qt7 is around.

Maybe this "issue" of Qt5 support needs to be resolved first?

> Currently we have the ability to build dependencies for macOS (except Qt) in any _single_ architecture with vcpkg. It already works. Is it worth spending time swapping this for macports? This is all in CI, not suggesting swapping the "official" homebrew approach (which _could_ be considered later).

Somehow I always forget vcpkg - if it works, let's keep it, never change a running system.

> Thanks for this. I have a few questions/comments:

In general, I somehow mixed this regarding our future CI pipeline. Although there is a strong overlap between CI and released binaries, you specifically asked for what binaries we should target as release, so sorry for my confusion here.

For me, the CI guarantees our platforms as "first class citizens", and any platforms beyond that are welcomed as a contribution to the release!

>  * Linux
>    * I'd treat binary releases as a separate issue, as we don't provide binary packages currently

Fair - in general I'd like to see a somehow *official* way of providing linux builds like we do with macOS and windows builds - flatpack seems to solve this for linux, so if we ever get this to working we should test it in our pipeline.

> * Ubuntu 22.04 has Qt 6.2 - I don't think this needs to be a legacy version, unless you meant a binary that supports Ubuntu 22.04, which would indeed need to be different than the one for 24.04

You are right, the binary should be equivalent, but we should test a build in our CI - here is a mixup between CI and release.

> * I like the idea of adding cross-compiled configs for `arm64` and `x86`; that's some extra work though, but would be great, especially if that could mean streamlining support for e.g. Raspberry Pi

I tried it out some months ago, and it is slow - maybe we should only build it upon request? See https://github.com/capital-G/supercollider/actions/runs/9269467852 and https://github.com/capital-G/supercollider/blob/cbc57cd34f2c5c501f37a15519e71ab06053595e/.github/workflows/actions.yml#L566

Maybe we should find a way for those "2nd class platforms" such as Raspberry Pi - maybe create a downstream repository which gets synced with upstream upon request and has a CI?

>  * macOS 
>     * I _strongly_ feel that the main arm64 build should run _at least_ on macOS 12 (none of the commercial software you listed requires a higher macOS version); if this works when building on macOS 14 with homebrew, we can do that; otherwise I'd consider making a _separate_ build that uses homebrew, and separate "main" build that uses other package manager for arm64

Here is a CI/release mixup again, so let me refine my proposition: lets assure we can build on the most recent macOS, currently 14, but, I also _strongly_ agree, target *at least* macOS 12 - or as low as we can get. I think macOS 11 could still be feasible r/n? I think it would depend on Qt in this case?

> * "legacy" x86_64 - again - why macports and not vcpkg?

Forgot about vcpkg, lets use vcpkgs.
This would be our most precious "legacy" build as it will be the CI to support a macOS Intel build as long as possible. I think we should put effort to keep this around as long as possible as this is really about hardware which would get obsolete in this case, with no way to upgrade it (beyond switching to linux).

> * "legacy legacy" - I think that the "legacy" build should support macOS 12 or 11 and there'd be no need for "legacy legacy"

Again a CI/release mixup.
But we should test in our CI if we can still build on a native on a intel mac.

>  * Windows
>    * I like eventually adding the arm build
Me too :)
>   * for the older MSVC - I don't think we'd need to make a binary of that, would we? I think the resulting supported OSes would be the same (mainly set by the Qt version); but I agree that it would be good to build with both older and newer MSVC

For the release indeed, but for CI it may be beneficial?

**Comment by dyfer** [comment]
> E.g. I think they also rely on Qt? I have the feeling they could be open to share some insights, maybe behind doors?

I'd love to get their thoughts :) I didn't think they used Qt, but I might be wrong.

> > Yet I think we should always have a priority on the most recent platforms on dev branch and we need to see how we invest our time.

Agreed that we should absolutely ensure SC _compiles_ in most recent OSes. We have a mixed record of that recently.


> Maybe this "issue" of Qt5 support needs to be resolved first?

What do you think about making _yet another issue_ to discuss Qt upgrade? Just so it has enough attention from everyone.


> 
> Somehow I always forget vcpkg - if it works, let's keep it, never change a running system.

Sounds good.

> 
> > Thanks for this. I have a few questions/comments:
> 
> In general, I somehow mixed this regarding our future CI pipeline. 

After I wrote my responses I wondered if that might've been the case.

> Maybe we should find a way for those "2nd class platforms" such as Raspberry Pi - maybe create a downstream repository which gets synced with upstream upon request and has a CI?

Yeah, I like the idea of having these build less often. Another way to do this would be to have an "on demand" CI pipeline for these that we'd run manually when needed/desired.

> 
> > * macOS
> 
> Again a CI/release mixup. But we should test in our CI if we can still build on a native on a intel mac.

I just tested this:

Built arm64 on macOS 14 runner with default config (homebrew) - _runs fine in macOS 12_
Built x86_64 on macOS 13 runner with default config (homebrew) - _runs fine in macOS 11_
https://github.com/dyfer/supercollider/actions/runs/10873789105

The issue is that unless someone tests this manually, we won't know for sure that it works. But for now it does seem to work, even without vcpkg.

> > * for the older MSVC - I don't think we'd need to make a binary of that, would we? 
> For the release indeed, but for CI it may be beneficial?

Yes, probably beneficial for CI, even if marginally.

**Comment by capital-G** [comment]
> What do you think about making _yet another issue_ to discuss Qt upgrade? Just so it has enough attention from everyone.

Regarding dual support of Qt5 and Qt6 or just Qt6. But after reviewing #6475 , it looks like dual support is worth it.

**Comment by dyfer** [comment]
I think that with recent build changes the this has been mostly discussed and implemented. 
Currently we build (not a complete list, but what's relevant to this issue):
- macOS arm64 using official Qt6 binaries (macOS 11+)
- macOS x64 using official Qt6 binaries (macOS 11+)
- macOS x64 legacy using official Qt5 binaries (macOS 10.15+, includes QuartzComposerView)
- macOS x64 "system libraries" using homebrew's Qt6 (no artifact upload)
- Windows x64 (MSVC 2022) using official Qt6 binaries
- Windows x64 (MSVC 2019) using official Qt6 binaries (no artifact upload)
- Windows x32 using official Qt5 binaries (no artifact upload)

We haven't implemented arm cross-compiling on Linux, TBA later.

----

I think this can be closed - _almost_. I want to discuss macos binaries.

For reference, we use Qt6 official binaries as opposed to homebrew binaries, since homebrew binaries are built against the latest OS and the last I checked the ones from macOS 13 only supported macOS 13... but I think we should still support macOS 11 or 12 at the very least.

The official Qt6 binaries are "universal" - they include both x64 and arm64 binaries. Unfortunately macdeployqt (the tool that assembles the application bundle) does _not_ remove the unused architecture from the bundled libraries. The WebEngine is probably the biggest "offender" here, but other Qt libraries are almost twice the size as well. The resulting package is rather large - 250MB. 

We could theoretically add a step removing the other architecture in the CMake, but that's adding a "workaround" code to the build process, will take extra time, and is generally cumbersome, as the [lipo tool](https://ss64.com/mac/lipo.html) which we'd presumably use, does not modify files in place, IIUC (i.e. we'd need to make a copy first, then write the modified file to the original location).

I think we have 3 solutions:
1. leave this as is - offer both x64 arm64 builds that are large
2. implement manual removal of the other architecture in CMake
3. consider moving back to offer a universal binary

I'm leaning towards 3.
Instead of re-introducing my hacky script we used before, I'd be open to using some macports packages for that...

Thoughts?

**Comment by capital-G** [comment]
How much work and maintenance-work would you estimate for point 2?

Another solution could be to use macports to obtain a "native" qt build, but I don't know their general compatibility regarding OS? I wonder how other projects do it, Qt seems not a too obscure?[^1]

On the other hand: We are talking about 100 MB of storage here - maybe there are more important issues lying around? :) I personally am fine with 1), but 2) and 3) are also fine. I think I prefer the one with the least maintenance/hacks.

[^1]: I just took a look at qgis, they do something really interesting by storing their dependencies on their own server https://github.com/qgis/QGIS/actions/runs/11451825301/workflow - but I don't know how they obtain them
