### ISSUE TITLE
GUI --> ERROR: Message '/' not understood. 

### ISSUE THREAD

**Issue by Evrikast** [supercollider/supercollider#6495]
I'm facing a problem with the GUI system, tryin to make a Synth with GrainBuf. The problem is that when i turn of the ON\OFF button it seems that it doesn't find the synth again so i have to restart it.

Does anyone know what is going on? 
Thank you in advance!

///////////////////////////////////////////// the code:
s.reboot;
(
Buffer.freeAll;
~buf1 = Buffer.read(s, "C:/Users/user/Desktop/September programming 2/Samples/GtrMono1.wav");

e = Env.new([0,0,1],[0.01,1],[0,-4]);
~grainEnv = Buffer.sendCollection(s,e.discretize(8192));
)
(
SynthDef(\GBSGUI ,
	{
		arg freqT = 20, phaseT = 0, 
		rateG = 60, posSp = 1, ampGBSGUI = 0, out = 0;
		var sig;

		sig =  GrainBuf.ar(
			numChannels: 2,
			trigger: Impulse.ar(
				freq: freqT,                       // Slide 1
				phase: phaseT),                    // Slide 2
			dur: {Rand(0.001,3)},
			sndbuf: ~buf1,
			rate: rateG, //{MouseX.kr(-5,20)},     // Slide 3
			pos: Phasor.ar(
				0,
/*speed*/		posSp * BufRateScale.ir(~buf1),    // Slide 4
				0, BufSamples.ir(~buf1) -1   )
			    + LFNoise1.ar(100).bipolar(1 * SampleRate.ir) / BufSamples.ir(~buf1),
			interp: 2,
			pan: LFNoise0.kr(20),
			envbufnum: -1,);

		sig = sig * ampGBSGUI;

		Out.ar(out,sig);

}).add;

)
(
Synth(\GBSGUI,[
	// \freqT, 100,
	// \phaseT, 1,
	// \rateG, 10,
	// \posSp, 1,
	\ampGBSGUI, 1
]);
	
)

////  GUi
(
Window.closeAll;
w = Window.new(\GrainBuf, Rect(700,600,700,220))
// w.bounds
.front
.alwaysOnTop_(true);
w.view.background = Color(0.2,0.2,0.2);
~synth2Button = Button.new(w, Rect(240,10,190,50));
~synth2Button.states_([
	["Synth2 off", Color.black,Color.red],
	["Synth2 on", Color.black,Color.green]
]);

~synth2Button.action_({
	arg obj;
	if(
		obj.value == 1,
		{
			o = Synth(\GBSGUI,[
				\ampGBSGUI, ~s5S2amp.value.linexp(0,1)
			]).register;
		},
		{o.free}
	);
});

~s1S2 = Slider.new(w,Rect(240,60,40,150));
~s1S2.action_({
	arg obj;
	var freq;
	freq = obj.value.linexp(0,1,1,500);
	if(
		p.isPlaying,
		{p.set(\freqT, freq)}
	);
});

~s2S2= Slider.new(w, Rect(290,60,40,150));
~s2S2.action_({
	arg obj;
	var phase;
	phase = obj.value.linexp(0,1,0,5);
	if(
		p.isPlaying,
		{p.set(\phaseT, phase)}
	);
});

~s3S2 = Slider.new(w, Rect(340,60,40,150));
~s3S2.action_({
	arg obj;
	var rate;
	rate = obj.value.linexp(0,1,1,40);
	if(
		p.isPlaying,
		{p.set(\rateG, rate)}
	);
});

~s4S2 = Slider.new(w,Rect(390,60,40,150));
~s4S2.action_({
	arg obj;
	var sp;
	sp = obj.value.linexp(0,1,-10,10);
	if(
		p.isPlaying,
		{p.set(\posSp, sp)}
	);
	
});

~s5S2amp = Slider.new(w,Rect(430,10,40,200));                   // volume
~s5S2amp.action_({
	arg obj;
	var vol;
	vol = obj.value.linexp(0,1,0.0001,1).postln;
	if(
		p.isPlaying,
		{p.set(\ampGBSGUI,vol)};
	);
});
/* se periptosh pou balw kati akoma
~k1S2posSp = Knob.new(w,Rect(250,17,40,40));
~k1S2posSp.action_({
	arg obj;
	var speed;
	speed = obj.value.linexp(0,1,-4,10);
	o.set(\posSp, speed);
});*/
)
////////////////////////

## Environment

* SuperCollider version:
* Operating system:
* Other details (Qt version, audio driver, etc.):

## Steps to reproduce

```supercollider

Using as little code as possible, please provide an example that can be run and reproduces the bug.
Paste code here between the tick marks. 

```

**Comment by telephon** [comment]
Maybe post this on https://scsynth.org/ ? That is the better place!

**Comment by Evrikast** [comment]
> Maybe post this on https://scsynth.org/ ? That is the better place!

Ok thanks!!
