### ISSUE TITLE
Ubuntu 22: SC builds against Qt5 when both Qt5 & Qt6 are available

### ISSUE THREAD

**Issue by SimonDeplat** [supercollider/supercollider#6509]
## Environment

* SuperCollider version: 3.14.0-dev
* Operating system: Ubuntu 22.04

## Steps to reproduce

Uninstall SC:
`sudo make uninstall`

Uninstall Qt5:
`sudo apt-get remove qtbase5-dev qt5-qmake qttools5-dev qttools5-dev-tools qtdeclarative5-dev libqt5svg5-dev libqt5websockets5-dev qtwebengine5-dev`

Uninstall Qt6:
`sudo apt-get remove qt6-base-dev qt6-base-dev-tools qt6-tools-dev qt6-tools-dev-tools qt6-declarative-dev libqt6gui6 libqt6printsupport6 libqt6svgwidgets6 libqt6websockets6-dev libqt6webenginecore6 qt6-webengine-dev qt6-webengine-dev-tools libqt6core5compat6-dev libqt6webchannel6-dev libqt6opengl6-dev libqt6svg6-dev linguist-qt6 qt6-l10n-tools  libglx-dev libgl1-mesa-dev libvulkan-dev libxkbcommon-dev libxcb-xkb-dev`

Clone SC, etc:
```
git clone https://github.com/supercollider/supercollider.git
cd supercollider/
git submodule update --init --recursive
mkdir build && cd build/
```

Install Qt5:
`sudo apt-get install qtbase5-dev qt5-qmake qttools5-dev qttools5-dev-tools qtdeclarative5-dev libqt5svg5-dev libqt5websockets5-dev qtwebengine5-dev`

Install Qt6:
`sudo apt-get install qt6-base-dev qt6-base-dev-tools qt6-tools-dev qt6-tools-dev-tools qt6-declarative-dev libqt6gui6 libqt6printsupport6 libqt6svgwidgets6 libqt6websockets6-dev libqt6webenginecore6 qt6-webengine-dev qt6-webengine-dev-tools libqt6core5compat6-dev libqt6webchannel6-dev libqt6opengl6-dev libqt6svg6-dev linguist-qt6 qt6-l10n-tools  libglx-dev libgl1-mesa-dev libvulkan-dev libxkbcommon-dev libxcb-xkb-dev`

CMake:
`cmake ..`
which yields
`-- Found Qt 5.15.3: /usr/lib/x86_64-linux-gnu/libQt5Core.so.5.15.3`

`make -j9 && sudo make install && scide`
Starts with Qt5 (obviously)

Removing Qt5:
`sudo apt-get remove qtbase5-dev qt5-qmake qttools5-dev qttools5-dev-tools qtdeclarative5-dev libqt5svg5-dev libqt5websockets5-dev qtwebengine5-dev`

CMake again:
`cmake ..`
which yields
`-- Found Qt 6.2.4: /usr/lib/x86_64-linux-gnu/libQt6Core.so.6.2.4`

`make -j9 && sudo make install`
All good

`scide`
Does not work:
```
Could not find QtWebEngineProcess
Abandon (core dumped)
```

`sudo apt install libqt6webenginecore6-bin`
`scide`

SC working, with Qt6.

## Expected vs. actual behavior
When both Qt5 & Qt6 are installed on the system, SC should build against Qt6.

And `libqt6webenginecore6-bin` should be included in the README_LINUX?

**Comment by xunil-cloud** [comment]
I test this using podman. Can you try to change `Qt6_FOUND` to `QT_FOUND` ? `Qt6_FOUND` is somehow not set even though Qt6 is actually found. 
 ```patch
diff --git a/QtCollider/CMakeLists.txt b/QtCollider/CMakeLists.txt
index 8ce0798bf9..df8b48a3e0 100644
--- a/QtCollider/CMakeLists.txt
+++ b/QtCollider/CMakeLists.txt
@@ -16,7 +16,7 @@ set(

 # find Qt6 or Qt5
 find_package(QT NAMES Qt6 ${REQUIRED_QT_VERSION} QUIET COMPONENTS Core)
-if (NOT Qt6_FOUND)
+if (NOT QT_FOUND)
     set(REQUIRED_QT_VERSION 5.15)
     find_package(QT NAMES Qt5 ${REQUIRED_QT_VERSION} QUIET COMPONENTS Core)
 endif()
``` 

I don't encounter this issue on Arch Linux (cmake 3.30.5 and Qt 6.8.0) but `QT_FOUND` also works for me.

**Comment by dyfer** [comment]
Thanks for reporting!
I think @xunil-cloud 's solution is worth testing. I also have other ideas - I think that maybe we need use versioned targets throughout CMake, and/or add minimum required versions in more places... I'll try to test this soon.

**Comment by dyfer** [comment]
Upon further investigation, @xunil-cloud's suggestion should be implemented anyway.
Since we run 
```
find_package(QT (...) )
```
then the resulting variable should indeed be `QT_FOUND`, since we set the package name to be `QT`. 
This is described in the [cmake help](https://cmake.org/cmake/help/latest/command/find_package.html#basic-signature):

> Regardless of the mode used, a \<PackageName\>_FOUND variable will be set to indicate whether the package was found.

I implemented the change here: https://github.com/supercollider/supercollider/tree/topic/qt6-found
@SimonDeplat could you please test it on your system?

**Comment by SimonDeplat** [comment]
It works!
I first tried to reinstall Qt5 packages after building with Qt6 to see if this would keep Qt6. It didn't.
But switching to topic/qt6-found now prioritize Qt6 correctly.
Thanks for your help.

**Comment by dyfer** [comment]
Thanks for testing!
