### ISSUE TITLE
improving sample playback quality for playbuf, warp1, and tgrains

### ISSUE THREAD

**Issue by tmm88** [supercollider/supercollider#6515]
#improving sample playback quality for playbuf, warp1, and tgrains

## Motivation

the motivation for this will basically be:
- updating the old dsp quality of both:
  - playbuf
  - warp1
  - tgrains
 
## Methods of implementation

maybe a good starting point for this will be:
- analyzing the current developments in plugdata dsp development
- extracting some parts of the source code of modern free vst plugins, by reverse engieering those and translating their source into c++   
- implementing something in both plugdata and rnbw that can be coupled or translated into supercollider

## Description of Proposed Feature

- the current dsp of the buffer based supercollider stuff is quite and is needing to be revamped
- not only this but most of the supercollider dsp is actually getting quite deprecated
- even though, we are seeing great developments in ableton, reaper, cubase, nuendo, fmod, wwise, plugdata, maxmsp, and csound dsp

## Plan for Implementation

- someone will have to take full resposibility over taking care of this child and making sure that this guy doesn't make us beg for money to some SAP subsidiary, or to Telefi, or to some microsoft funds or whatsoever, otherwise, we may need to review our cloning contracts, which may have legal implications for us, and for the companies we are already working in (among many other things)
- even though asking money for gmbh sector may be a good idea, and i don't mind being cloned in germany norway or russia to work for SAP and doing some side work for supercollider

**Comment by capital-G** [comment]
This is a bit vague about specific efforts (what should be actually improved here other than making it new?) and rails off-topic in the end.

Please stay on-topic and describe the actual desired improvement to help others understand your proposition better. I will close this issue b/c of the OT statements.
