### ISSUE TITLE
adding `.average`?

### ISSUE THREAD

**Issue by prko** [supercollider/supercollider#6533]
## Motivation
`.sum` and `.product` exist, but `.average` does not. I think `.average` would also be useful.

## Description of Proposed Feature
It should work similar to `.sum` or `.product`

## Plan for Implementation
Implementing only for `collection` seems OK to me, but implementing for `function` and `matrix` should be discussed if it is necessary.

**Comment by capital-G** [comment]
Hey prko - I allowed myself to edit your post so the backticks are matching.

Are you aware of [`.mean`](https://docs.supercollider.online/Classes/Collection.html#-mean)? If yes, what would be the difference between `.average` and `.mean`? Mean has a somehow precise mathematical definition (https://en.wikipedia.org/wiki/Arithmetic_mean) but average is a bit more vague, see https://en.wikipedia.org/wiki/Average#Summary_of_types

**Comment by prko** [comment]
Sorry for the typo.

Yes, `.mean` is what I want. Although I know the term, when I searched for it yesterday, I only found `.average` - my fault. But even if `.mean` had come to mind and I had found it, I would still have started a thread because there is no description of `.mean` in the help. The `function` argument without explanation seems to be an obstacle to selecting `.mean` to use as follows: 
```
(1..10).mean
```
`.sum` also have `function` argument. Hm.

How about modifying / adding the following to the help documentation?
```
method::sum
Answer the sum of all items or the results of the optional strong::function:: argument evaluated for each item in the receiver. The function is passed two arguments, the item and an integer index.
code::
List[1, 2, 3, 4].sum;
(0..8).sum { |i| 1 / (2 ** i) }; // only item is used as index is not used in the function
::

method::mean
Answer the arithmetic mean of the results of the sum with an optional function argument. See link::#-sum:: for optional function argument. 
code::
[1, 2, 3, 4].mean;
::
```

**Comment by capital-G** [comment]
I always appreciate improvements and additions in the documentation! I think this could be a nice PR.

I enjoy your choose of words regarding answering, I think the more established term seems to be "returning" in the domain of programming.
And maybe we can make use of the new math syntax within schelp? :)

**Comment by prko** [comment]
OK, I will do that, but 'answering' is not my choice. 
I made firstly a PR changing 'Answer' and 'Answer' to 'Return' or 'Returns'.
If that PR is approved, I will modify some method explanations in the Collection documentation with KaTex!

**Comment by prko** [comment]
I am closing this as it has been split into #6534 and #6537.
