### ISSUE TITLE
argument order of `(?<!\()\bEnv\.[^)]*\([^)]*\)\.(k|a)r`

### ISSUE THREAD

**Issue by prko** [supercollider/supercollider#6574]
## Motivation
In the SC help documentation and in the code editor popup, I could not find the argument order for the following code:
```
Env.adsr(0.01, 0.1, 0.7, 0.3).kr(Done.freeSelf, gate, ...);
```
## Description of Proposed Feature
This 'syntax sugar' (not sure if this is the right term in this case) should be documented in the SC help documentation,

## Plan for Implementation
I can do this if someone advises me where to put it.

**Comment by telephon** [comment]
What we need is the full text search for the help documents!
In this case, you simply ask yourself what the receiver of the message `ar` or `kr` is :-).
 An Env. It is documented in Env help ...

**Comment by prko** [comment]
Oh, I found it in the instance methods. Thank you very much!
