### ISSUE TITLE
Impossible to join discord or https://scsynth.org/

### ISSUE THREAD

**Issue by tobiasBora** [supercollider/supercollider#6578]
Sorry if this is not the right place to ask, but I am unable to contact any member of the community to ask question. Namely:
- the discord link on https://github.com/supercollider/supercollider/wiki/Community-channels is invalid
- my subsription to the forum https://scsynth.org/ has been waiting for approval by moderators for a day without much news 
- slack is kind of dead

Would it be possible to fix this, at least  the discord link?

**Comment by telephon** [comment]
Sorry about this! Discourse is better, I'll approve you.

**Comment by telephon** [comment]
I don't see you. Can you try again at scsynth, please?

**Comment by tobiasBora** [comment]
I found the link https://discord.gg/FPRmwfFS not sure how to edit wiki from phone. And I just tried again and I'm in thanks!

**Comment by capital-G** [comment]
Currently only people of the SC organization can edit the wiki. I updated the discord invite link in the wiki, so thanks for the new link.

While Discord seems like a convenient place, it is a closed platform and does not allow access w/o an account or searching of its content - therefore, in the spirit of FOSS, we always appreciate if people use scsynth.org which is a community-owned discourse instance which also has chat functionality enabled and can be viewed and searched w/o an account.

I will close this for now, please re-open if necessary.

**Comment by tobiasBora** [comment]
Thanks! I also enjoy open source stuff, but live chat is also nice sometimes. But a FOSS solution would be to have a matrix space.https://element.io/

**Comment by capital-G** [comment]
Well, discourse is also FOSS and has a chat :) See https://scsynth.org/chat/browse/all

It is not as crowded as discourse yet and I also thought about setting up a matrix space, but https://xkcd.com/927/

**Comment by telephon** [comment]
> I found the link https://discord.gg/FPRmwfFS not sure how to edit wiki from phone. And I just tried again and I'm in thanks!

Glad it worked, but e.g. I am not there, because we try to focus the efforts into https://scsynth.org/

**Comment by tobiasBora** [comment]
> Well, discourse is also FOSS and has a chat :) See https://scsynth.org/chat/browse/all

I read that before but whenever I click on the link I get redirected to https://scsynth.org/categories any idea what I did wrong? And is there an apps/ways to get a notification when I get an answer there?

> I also thought about setting up a matrix space, but https://xkcd.com/927/

Ahah yeah that's often a problem, and it also dillutes people, unless we configure bridges between solutions.

> we try to focus the efforts into https://scsynth.org/

I see, makes sense. I'll try to do my best to use it or at least document back there answers I get on discord. But would it make sense to remove the moderation when subscribing? Anyway I guess moderators rarely refuse a new subscription and it's the first discourse I see with that… and waiting a few hours/days to be accepted will mecanically redirect people to discord.

**Comment by capital-G** [comment]
> and waiting a few hours/days to be accepted will mecanically redirect people to discord.

This was introduced quite recently and was a counter-measure against a recent spam-attack, see https://scsynth.org/t/spambot-attack/10506/2 Maybe we find another way of dealing with such problems.

> I read that before but whenever I click on the link I get redirected to https://scsynth.org/categories any idea what I did wrong?

I think you currently have to be logged in in order to access the chat of scsynth. Are you logged in and approved? If you are still not approved yet, please post your username here and hopefully a scsynth mod can look into it.

IIRC, discourse allows/asks to use your browsers push notifications.

**Comment by telephon** [comment]
>I see, makes sense. I'll try to do my best to use it or at least document back there answers I get on discord. 

Ah that is good, thank you.

> But would it make sense to remove the moderation when subscribing? Anyway I guess moderators rarely refuse a new subscription and it's the first discourse I see with that… and waiting a few hours/days to be accepted will mecanically redirect people to discord.

True. Right now we are drowned in fake subscription attempts, that may be the reason why yours has been overlooked. I wonder how discord solves this problem …

**Comment by tobiasBora** [comment]
> Right now we are drowned in fake subscription attempts

Oh that's annoying, even when enabling basic questions to see if the subscription is done, like `supercollider is for: music/photo/…` or via captcha? Is it possible maybe to allow the subscription but then filter the first messages? Cause I guess a moderator can barely know if an account is a spam or not while only seing the email no?

**Comment by tobiasBora** [comment]
> I think you currently have to be logged in in order to access the chat of scsynth. Are you logged in and approved?

Sorry I missed your message but yes, I'm both logged in and approuved (I can create new messages…).

**Comment by telephon** [comment]
Thank you! I've tried to find those (basic questions) settings, but I couldn't …
