### ISSUE TITLE
SuperCollider 3.14.dev for Windows crahes

### ISSUE THREAD

**Issue by prko** [supercollider/supercollider#6580]
## Environment

* SuperCollider version: 3.14.dev
* Operating system: Windows 11

## Steps to reproduce

1. download SC3.14.dev
2. launch sc-ide.exe

## Expected vs. actual behavior

- Expected: Launch SC-IDE without errors:
- Actual:
![csrss_50Q6a3HUUp](https://github.com/user-attachments/assets/68c78344-4a9d-4c20-8e9e-91695f4ad5d8)
![csrss_EJ50nK1lBo](https://github.com/user-attachments/assets/89bdf3de-4728-4702-8a20-8ca8ce41a304)
![csrss_Ux7k46ov0G](https://github.com/user-attachments/assets/9e502886-c6c5-40f4-9426-3ad719317b25)
Interpreter has crashed or stopped forcefully. [Exit code: -1073741515]

**Comment by capital-G** [comment]
Seems the dependencies of scsynth are linked dynamically but not included in the build? I don't have a windows machine, but if you put the mentioned dll files into a directory (next to `scide.exe`?) they should be picked up by.
FFTW can be downloaded via
https://github.com/supercollider/supercollider/blob/f9a797ac0b50fa61145e1998758a60f07172fb7b/.github/workflows/build_windows.yml#L38

Nonetheless, it would be great if the nightly builds can be easily used by people :)

**Comment by prko** [comment]
Thanks!
I downloaded it today again and all three files are there!
