### ISSUE TITLE
OSCpathResponder is broken

### ISSUE THREAD

**Issue by jleben** [supercollider/supercollider#66]
[Issue migrated from SourceForge | ID: 2021481 | Submitted by 'sciss']
[http://sourceforge.net/support/tracker.php?aid=2021481]

OSCpathResponder is still broken and only works under certain circumstances. In the example below, responder y doesn't get notified:

x = OSCpathResponder( NetAddr.localAddr, [ '/timeline', 1004, \position ], { "x received!".postln }).add;
y = OSCpathResponder( NetAddr.localAddr, [ '/timeline', 1004 ], { "y received!".postln }).add;
z = OSCresponderNode( NetAddr.localAddr, '/timeline', { "z received!".postln }).add;

NetAddr.localAddr.sendMsg( '/timeline', 1004, \position, 1234 );

**Comment by Sciss** [comment]
apologies for polluting multiple issues with automatic mentions from unrelated commits; I accidentally pushed non-overlapping ScalaCollider branches to my fork of SuperCollider (a wrongly set-url remote). I deleted those branches again, but seems the mentions are still in the ticket system, now pointing to orphaned commits.
