### ISSUE TITLE
postcs of recursive data structure crashes sclang

### ISSUE THREAD

**Issue by timblechmann** [supercollider/supercollider#665]
running postcs on a recursive data structure causes an infinite loop:

```
a = (foo: 1);
a = a.add(\bar -> a);
a.postcs
```

not sure, what's the best way to deal with this, because recursive data structures cannot easily be serialized as compile string.

**Comment by telephon** [comment]
feel free to reopen

**Comment by brianlheim** [comment]
Recognizing/informing the user about infinite loops is very low priority and arguably just user error rather than language design failure IMO.
