### ISSUE TITLE
Key commands like STOP (cmd + . ) don't work in Help window when it's detached 

### ISSUE THREAD

**Issue by miczac** [supercollider/supercollider#668]
This is probably related to https://github.com/supercollider/supercollider/issues/480 :
STOPing a sound or Task etc.  by pressing CMD + . works within the Help window as long as this is attached (regardless if docked or undocked).
As soon as this is detached (and therefore undocked) the STOP-command apparently doesn't get passed through. I have to switch to the Editor window (where also the STOP command becomes available in the Language menu) to kill any action (like crazy sounds as Dan described it colourful).

edit:
It looks like as if this applies for other key commands as well, for instance for cmd + B for booting the server.

(found on Mac OS X 10.6.8)

**Comment by albreche** [comment]
Ctrl+. doesn't work in scide. 
Supercollider 3.7.1 built from HEAD d3a87c1, ubuntu 14.04.4 LTS
QT 5.2.1
