### ISSUE TITLE
Crash when using a class name in binop method call syntax

### ISSUE THREAD

**Issue by jamshark70** [supercollider/supercollider#669]
1 Class: 2

Expected behavior: Parse error

Actual behavior: Language crashes

True, it's wrong input, but we should catch wrong input and provide reasonable error output rather than crashing.

**Comment by scztt** [comment]
Hah!

**Comment by baconpaul** [comment]
Turns out this error occurs if you use the name of any object which is registered as an object. So 

1 Object: 2

crashes. But 

1 FooBaz: 2 

doesn't. I think I have a fix, though.
