### ISSUE TITLE
QDialog seems unable to be on top

### ISSUE THREAD

**Issue by spluta** [supercollider/supercollider#672]
CocoaDialog was always the top window when it was opened. QDialog seems incapable of being the top window. This is a problem as it may open up hidden behind a bunch of other windows.

BTW - I don't know if you guys want my personal problems submitted here, but having tried to move to 3.6 this weekend, I realized it will not be possible until some issues with the QT GUI stuff is fixed.

**Comment by vivid-synth** [comment]
Close?
