### ISSUE TITLE
Clear post window should also have a menu item

### ISSUE THREAD

**Issue by muellmusik** [supercollider/supercollider#675]
This would make it discoverable, (It doesn't seem to be documented anywhere) and would be in keeping with UI conventions (for OSX at least).

**Comment by LFSaw** [comment]
similar and related to #644

**Comment by dkmayer** [comment]
This just came up again

https://scsynth.org/t/ide-ui-improvements-branch/300/9

This would be really useful to have, I remember that students sometimes asked for it and I told them, but I wasn't aware that it's not in the menu.

**Comment by muellmusik** [comment]
@brianlheim I assigned you as there seems to be an old PR from you for this, but feel free to undo that if that's appropriate
