### ISSUE TITLE
The tutorial series "A practical guide..." should be findable by typing either "Practical" or "Guide" into the search box

### ISSUE THREAD

**Issue by danstowell** [supercollider/supercollider#694]
The tutorial series "A practical guide..." should be findable by typing either "Practical" or "Guide" into the search box - doesn't really work at the moment, I think because the documents mostly use the label "PG" rather than "Practical guide".

I think this just requires changing some of the metadata in the guide docs themselves (e.g. adding it to the description text?)

**Comment by vivid-synth** [comment]
This is not an issue with search -- it's actually that they're not really titled "A Practical Guide": if we want this to work we could add "practical" to their descriptions. Otherwise I'd be okay closing.

**Comment by brianlheim** [comment]
#3030 is a more general version of this
