### ISSUE TITLE
Dialog.openPanel hangs on Windows XP

### ISSUE THREAD

**Issue by geoffroymontel** [supercollider/supercollider#707]
Hello

With SC 3.6.2, on Windows XP, when I launch SC IDE, boot the server, show the serveur GUI with s.makeGUI and then just execute
```
Dialog.openPanel;
```
The panel does not open. The server GUI window is frozen and becomes blank.

I have to press ctrl + . to open it, and then it hangs when I enter a folder. If I press again ctrl + . then it's working.

Best regards

Geoffroy

**Comment by bagong** [comment]
I don't remember if this was just Windows XP related or a general Windows problem. The problem does not occur master/Qt5/Win 8.1 any more. Generally speaking I think Win XP support can be dropped for 3.7.

**Comment by jamshark70** [comment]
I agree -- close all XP-only issues. If Microsoft doesn't support it anymore, then we don't have to.

**Comment by bagong** [comment]
Closed because Windows XP support is dropped
