### ISSUE TITLE
Cursor forced to end of line

### ISSUE THREAD

**Issue by mtmccrea** [supercollider/supercollider#710]
Under _some_ circumstances, when a line in the editor wraps around to a new line (for example if making the editor window narrower, forcing a line to wrap), you can no longer click to place the cursor in the middle of a line.  Instead, the cursor is forced to the end of the line.

You can still navigate with arrow and option+arrow keys to move the cursor to the middle of the line, but cannot click to place the cursor there.  

Making the window wide again, allowing the line to unwrap and only occupy a single line, the problem goes away.

It's hard to intentionally recreate different cases, but the following line is one example. Paste it and resize the editor to force it to wrap to see the problem.

s.options.numInputBusChannels = 32; s.options.numInputBusChannels = 32; s.options.numInputBusChannels = 32; s.options.numInputBusChannels = 32; s.options.numInputBusChannels = 32;

Mac 10.6, SC 3.6 alpha2

Thanks!

**Comment by vivid-synth** [comment]
Is this something anyone can repro? Looks like it could be closed...

**Comment by brianlheim** [comment]
I can't reproduce this. We're several versions ahead on all of this, so I'll close.
