### ISSUE TITLE
SCRangeSlider bg draws wrong in relative origin parent

### ISSUE THREAD

**Issue by jleben** [supercollider/supercollider#72]
[Issue migrated from SourceForge | ID: 2474755 | Submitted by 'jmfuo']
[http://sourceforge.net/support/tracker.php?aid=2474755]

SCRangeSlider thumb draws incorrectly in relative origin parent

(
w = SCWindow.new.front;
v=SCCompositeView(w,Rect(50,50,300,300)).relativeOrigin_(true);
a = SCRangeSlider(v, Rect(20, 80, 120, 30))
.lo_(0.2)
.range_(0.4)

)

**Comment by Sciss** [comment]
apologies for polluting multiple issues with automatic mentions from unrelated commits; I accidentally pushed non-overlapping ScalaCollider branches to my fork of SuperCollider (a wrongly set-url remote). I deleted those branches again, but seems the mentions are still in the ticket system, now pointing to orphaned commits.
