### ISSUE TITLE
Autosave

### ISSUE THREAD

**Issue by jleben** [supercollider/supercollider#725]
An option to automatically save documents every now and then.

Tim has summed up examples from other code editors:

> emacs does an autosave after a few hundred key strokes, gedit can be configured to auto-save every few minutes. kate and emacs save a temp file with the current state of the file while editing, so in case of a crash, one can recover the current state of the file

**Comment by scztt** [comment]
This was implemented in add4e058d3d4e297ac90069c1137e25ffef66ff8 and related.
