### ISSUE TITLE
Psycollider 3.3a openTextFile crashable - not thread-safe?

### ISSUE THREAD

**Issue by jleben** [supercollider/supercollider#73]
[Issue migrated from SourceForge | ID: 2490331 | Submitted by 'danstowell']
[http://sourceforge.net/support/tracker.php?aid=2490331]

In Psycollider the following works fine:

  "startup.sc".openTextFile

but the following causes an ugly and unexplained Psycollider crash:

 Task{"startup.sc".openTextFile}.play(AppClock)

Same goes if you specify SystemClock.

Now, the PYSCLang code includes a little bit of code which is supposed
(according to the comments) to make it thread-safe, but it feels like
somehow this isn't working. Three questions:

(1) Does this happen on Psyco 3.2 (my test is on my recent build)?
(2) Has it been discovered/discussed before?
(3) Any suggestions for a fix/workaround?

Unfortunately the bad crash can be triggered during use of Help.gui so
it's particularly horrible!

http://www.listarc.bham.ac.uk/lists/sc-dev/msg05897.html

**Comment by Sciss** [comment]
apologies for polluting multiple issues with automatic mentions from unrelated commits; I accidentally pushed non-overlapping ScalaCollider branches to my fork of SuperCollider (a wrongly set-url remote). I deleted those branches again, but seems the mentions are still in the ticket system, now pointing to orphaned commits.
