### ISSUE TITLE
Collpsable code blocks

### ISSUE THREAD

**Issue by miguel-negrao** [supercollider/supercollider#731]
Sometime code gets unwieldy and one has to scroll up and down all the time. It would much simplify code navigation if it was possible to collapse code blocks such as function and method definition or code blocks within parenthesis:

![Captura de ecra 2013-02-19 a s 10 55 11](https://f.cloud.github.com/assets/382777/170941/ea3d9ae8-7a82-11e2-9f13-14a28dfc0615.png)

![Captura de ecra 2013-02-19 a s 10 56 35](https://f.cloud.github.com/assets/382777/170946/11419d4c-7a83-11e2-942f-9ab5d7b7cc39.png)

**Comment by snappizz** [comment]
closing per #2264 -- this is not an easy feature to implement and really unlikely to happen in the near future.
