### ISSUE TITLE
Implement macros (and/or TextMate-style snippets) in IDE

### ISSUE THREAD

**Issue by totalgee** [supercollider/supercollider#733]
Perhaps this will be solved in the future by Quarks, once the Document class is re-implemented under the SC IDE, but it would be great for live coding (and coding in general, in fact) if there were a way to support TextMate-style snippets -- or some other basic macros support -- in the Qt editor.

Related to this, it would also be great if there were an option to insert matching brackets, parentheses, etc, as you type them (as in Xcode and many other editors).

**Comment by vivid-synth** [comment]
@totalgee is this what you're looking for?: https://github.com/jamshark70/ddwSnippets

**Comment by totalgee** [comment]
Yes, it looks like it'll be, pretty much, once a few (OS X) glitches with
the Quark are ironed out.

**Comment by vivid-synth** [comment]
Great -- I'm going to close this then as it looks like the problem will be solved outside of SC core!

**Comment by jamshark70** [comment]
Well, we'll see... ddwSnippets is kind of a hack that's working reasonably well for me in Linux, working somewhat less well for Glen in Mac, and for which I have no user reports in Windows. I wouldn't mind if someone wanted to do it properly in the IDE itself, with more features... but I don't realistically expect that to happen.

A concrete issue with ddwSnippets is that the IDE swallows Cmd keys in Mac -- the global key down action is never called, so a whole class of hotkeys is unavailable.

Yes, close it, as this is the best we're going to have until somebody gets mad enough and digs into the IDE source ;)

**Comment by brianlheim** [comment]
For future ref, if anyone's interested, some relevant code is here: 

https://github.com/supercollider/supercollider/blob/772bdd6946a7253390ba0b1b23eb3adc0acb97ea/editors/sc-ide/widgets/code_editor/editor.cpp#L627-L676
