### ISSUE TITLE
PartConv - erros with +/-fftSize/2 frames of convolution kernel

### ISSUE THREAD

**Issue by joslloand** [supercollider/supercollider#734]
PartConv UGen appears to be dropping or zeroing the final fftSize/2 frames of its kernel for partitioned convolution.

The following code illustrates the failure:

> // -----------------------------------------------
> // Test: PartConv failure
> Server.default = s = Server.local.boot;
> 
> // number of frames for buffer (kernel)
> ~numFrames = 2**15; // 32768
> 
> // FFT size
> ~fftSize = 2**11; // 2048 - recommended
> 
> 
> // set up buffer (kernel)
> ~buffer = Buffer.alloc(s, ~numFrames);
> ~buffer.zero;
> 
> // add an impulse @ gain
> ~gain = -9.dbamp;
> 
> // NOTE: PartConv drops or otherwise zeros the last fftSize/2 frames
> // ~sampleIndex = 0; // works
> ~sampleIndex = ~numFrames - (~fftSize/2) - 1; // works
> ~sampleIndex = ~numFrames - (~fftSize/2); // fails
> //~sampleIndex = ~numFrames - 1; // fails
> 
> // create impulse at sampleIndex
> ~buffer.set(~sampleIndex, ~gain);
> 
> 
> // prepare spectra buffer
> ~specBufSize= PartConv.calcBufSize(~fftSize, ~buffer);
> 
> ~spectrum = Buffer.alloc(s, ~specBufSize);
> ~spectrum.preparePartConv(~buffer, ~fftSize);
> 
> ~buffer.free; // don't need time domain data anymore, just needed spectral version
> 
> (
> // test!
> ~synth = {
> 	PartConv.ar(
> 		Saw.ar(110.0, -18.dbamp),
> 		// PinkNoise.ar(-6.dbamp),
> 		~fftSize,
> 		~spectrum.bufnum
> 	)
> }.play;
> )
> ~synth.free;
> ~spectrum.free;
> s.quit;
>

**Comment by sonoro1234** [comment]
@joslloand could you try with the PR#2015 ?

**Comment by joslloand** [comment]
@sonoro1234 Have you had a chance to try my test cases above? I haven't had the opportunity to try out https://github.com/supercollider/supercollider/pull/2015 as of yet.

Something that may also be worth considering.... [Donald Craig](http://www.realizedsound.net/rhomboid/home.html) has done a completely new re-write of the PartConv implementation as he'd felt the current form to be rather "convoluted" and difficult to understand. I had planned to bring in his code as a solution after hammering it with a number of edge cases, but hadn't yet had the time to do so.

https://github.com/supercollider/supercollider/pull/2015 is quite minimal, so we could accept it now.

I'm just wondering if Don's "fresh code" would be more suitable in the long run, or not?

Any thoughts?

**Comment by sonoro1234** [comment]
The delayed signal is more delayed than convolved but thats ok because minimum delay is (~fftSize / s.sampleRate)/2 instead of (~fftSize / s.sampleRate).
So it is ok

**Comment by sonoro1234** [comment]
By the way, I also did a version that allows to change the kernel with a trigger. Buffer preparation is done internally which i find usefull. Another optimization would be to allow stereo or multichanel kernels for Atk.
it is at https://github.com/sonoro1234/DWGReverb/blob/master/PartitionedConvolutionTrig.cpp

As for Donald Craig re-write I dont know...
May be would be good to try it.

**Comment by bagong** [comment]
Looks like it's done...
