### ISSUE TITLE
allTuple returns out of bounds memory results sometimes

### ISSUE THREAD

**Issue by jleben** [supercollider/supercollider#74]
[Issue migrated from SourceForge | ID: 2497625 | Submitted by 'nobody']
[http://sourceforge.net/support/tracker.php?aid=2497625]

allTuple returns out of bounds memory results when the array contains strings:

["ptk", "ae"].allTuples;

returns e.g.:
[ [ 5.0718864331724e+233, 1.4907605608146e+161 ], [ 5.0718864331724e+233, a Frame ], [ a Frame, 1.4907605608146e+161 ], [ a Frame, a Frame ], [ 0, 1.4907605608146e+161 ], [ 0, a Frame ] ]

we need to check the prArrayAllTuples primitive.

**Comment by Sciss** [comment]
apologies for polluting multiple issues with automatic mentions from unrelated commits; I accidentally pushed non-overlapping ScalaCollider branches to my fork of SuperCollider (a wrongly set-url remote). I deleted those branches again, but seems the mentions are still in the ticket system, now pointing to orphaned commits.
