### ISSUE TITLE
sclang: interpreter bug when using method named 'switch' in custom class

### ISSUE THREAD

**Issue by redFrik** [supercollider/supercollider#754]
the follow code crashes sclang.  sc352, sc357, sc363 on osx 10.8.2.

//--test class code
STest {
    var <switch;
}
/*
a= STest.new;
a.switch    //boom!
*/

**Comment by brianlheim** [comment]
Tried the test above, I get this:

```
ERROR: Missing argument in switch statement  in file 'selected text'
  line 1 char 9:

  a.switch 
```

Can someone else test this, preferably on linux/win?

**Comment by snappizz** [comment]
@brianlheim Same error here on Linux, no crash.

**Comment by brianlheim** [comment]
Hmm. I can't name a method `switch` and have it work, though. So it is an issue with bytecodes. Perhaps `switch` (and similar) should have highlighting like `thisProcess` and be un-overrideable?

Also, this means Float:-switch is a no-op.

**Comment by jamshark70** [comment]
> I can't name a method switch and have it work, though. So it is an issue with bytecodes.

Correct, for reasons explained above -- invoking `switch` is not certain to compile to a normal method dispatch.

It might be worth making it illegal to declare `switch` anywhere except where it's already defined. Also check case, if, loop, while... I think those are the only ones but I might have forgotten some.

**Comment by brianlheim** [comment]
> It might be worth making it illegal to declare switch anywhere except where it's already defined. Also check case, if, loop, while... I think those are the only ones but I might have forgotten some.

Agreed. I'm going to open an issue for that now. Closing this.
