### ISSUE TITLE
OSC-dumping crashes sound

### ISSUE THREAD

**Issue by jleben** [supercollider/supercollider#76]
[Issue migrated from SourceForge | ID: 2512986 | Submitted by 'jmfuo']
[http://sourceforge.net/support/tracker.php?aid=2512986]

(
s.waitForBoot({

```
q={arg freq=440; SinOsc.ar(freq,0,0.4)}.play    ;

w = Window.new.front;
a = Slider(w, Rect(50, 20, 300, 40))
    .action_({
        q.set(\freq,a.value*2000);
    })
```

});

)

then turn on osc-dumping in the serverwindow (hit d).

move the slider.

the sound stops, and I get funny little beeps an chirps.

this happens both with the internal and local server.

**Comment by Sciss** [comment]
apologies for polluting multiple issues with automatic mentions from unrelated commits; I accidentally pushed non-overlapping ScalaCollider branches to my fork of SuperCollider (a wrongly set-url remote). I deleted those branches again, but seems the mentions are still in the ticket system, now pointing to orphaned commits.
