### ISSUE TITLE
s.options.sampleRate_ setter requires boot then reboot to take effect

### ISSUE THREAD

**Issue by mtmccrea** [supercollider/supercollider#768]
Changing the sample rate using s.options.sampleRate_(sr) doesn't change the sample rate upon reboot if you're booting to a new sample rate from what was formerly running.  The user must boot (server boots to the old SR), quit, then reboot for the new SR to take effect.
Observe...
(assuming you were previously booted to 44.1 or 48...)
s.quit;
s.options.sampleRate_(96000);
s.boot; // still boots to the old sample rate
s.quit;
s.boot; // server now boots to the specified SR

Thanks in advance!

**Comment by scztt** [comment]
@mtmccrea - Can you retest this? I can't reproduce this in current versions....

**Comment by mtmccrea** [comment]
The behavior persists on my current version of SC, 3.7alpha1 (built today), OS 10.9.5.

With the AudioMIDI Setup window open, Built-In Output/Microphone selected as default, I see that setting the ServerOptions sampleRate then booting changes the sample rate at the moment of booting to the rate specified in the server options. However SC boots (or at least reports to boot) to the previous sample rate, both in the post window dump on boot and when requesting `s.sampleRate`.

This means that the server is running at a sample rate *different* from the audio device it's connected to (yikes) and resampling (?) ... or Server is incorrectly reporting it's sample rate.

Hope this helps and thanks for following up!

**Comment by scztt** [comment]
Can repro after all... this is actually really bad. Observe:
```
v = TextView(bounds:800@300).front;

fork({
	Server.default.quit;
	[44100, 48000, 96000].do({
		|requestedRate, i|
		2.do ({
			|j|
			var report;
			Server.default.options.sampleRate = requestedRate;
			Server.default.bootSync();
			{ SinOsc.ar(400) }.play;
			4.wait;
			
			report = "reported: %\t actual: %\t requested: %";
			if ((Server.default.actualSampleRate - requestedRate).abs > 5) {
				report = report + "[!! INCORRECT !!]"
			};
			report = report.format(
				Server.default.sampleRate, 
				Server.default.actualSampleRate, 
				requestedRate
			);
			v.string = v.string + report + "\n";
			
			Server.default.quit();
			1.wait;
		});
	})
}, AppClock)
```

**Comment by mtmccrea** [comment]
Wow.. the incorrect sample rates appear to be totally bogus. Is there any logic to the .actualSampleRate results when it's incorrect?

**Comment by scztt** [comment]
Heh, actualSampleRate is a slow running average, so I think it starts at the wrong sample rate, and slowly approached the right sample rate over a long period of time. :) Which explains why it's somewhere in between in the bug cases...

**Comment by telephon** [comment]
It seems that the starting estimate should be the "desired" one given by ````sampleRate````?

**Comment by telephon** [comment]
this happens in the calculation of ````mSmoothSampleRate````
