### ISSUE TITLE
scsynth and sclang do not comply to the OSC specification in terms of nested bundles

### ISSUE THREAD

**Issue by ventosus** [supercollider/supercollider#776]
According to the OSC specification 1.0, bundles can be nested, e.g. an OSC bundle may contain not only OSC messages, but also OSC bundles (which may again contain bundles, ...).

supernova correctly handles nested bundles, however, both scsynth and sclang cannot handle them. I know that nested bundles are not that commonly used, but they do have their use cases.

example:
<code>
bundle { timestamp: 1ULL (IMMEDIATE)
....message {/n_set isi 13 'gate' 0}
....bundle { timestamp: now+2seconds
........message {/n_free i 13}
....}
}
</code>

I'd like to send the above two messages in a single UDP packet (for efficiency reasons, as I'm sending from a microcontroller), which is possible with a nested bundle.

**Comment by vivid-synth** [comment]
This would be very nice to have in scsynth for Vivid, also!

**Comment by ventosus** [comment]
All sclang, scsynth and supernova support parsing nested bundles in the meantime.

This issue can thus be closed.

**Comment by vivid-synth** [comment]
Awesome!
