### ISSUE TITLE
remove lag argument from KeyState ugen

### ISSUE THREAD

**Issue by jreus** [supercollider/supercollider#785]
I'd like to put in a request that the lag argument be removed from the KeyState ugen. The documentation really doesn't say what this argument does in praxis. If it is intended to give a similar effect to Lag.kr then I imagine it would make more sense to use that Ugen.
Lag.kr(KeyState.kr( ... etc ...

The lag argument in KeyState now is a bit confusing! Thanks.

**Comment by snappizz** [comment]
I think we should close this. Let's not break stuff.

**Comment by brianlheim** [comment]
Closing, but added [here](https://github.com/supercollider/supercollider/projects/5).
