### ISSUE TITLE
scdoc: treat new-line as space

### ISSUE THREAD

**Issue by timblechmann** [supercollider/supercollider#786]
the Dxrand help file shows a problem of the scdoc parser (or html renderer)

the help file contains:

```
Dxrand never plays the same value twice, whereas  link::Classes/Drand::
chooses any value in the list.
```

however when rendered it appears as:

```
Dxrand never plays the same value twice, whereas Drandchooses any value in the list.
```

note the missing space between 'Drand' and 'chooses'. in a way we want to have a space character instead of the newline

**Comment by brianlheim** [comment]
Fixed for me. If someone can recreate this issue please reopen.
