### ISSUE TITLE
sc-ide: show more context around a find match

### ISSUE THREAD

**Issue by elmex** [supercollider/supercollider#788]
When using "find" to search for a text it can happen that the match is aligned
with the last visible line. Would it be possible to show a little more context
around the match? Because usually the context determines if I actually found
what I was looking for.

Here a graphic description of what I mean:

![scide_find_match_ctx](https://f.cloud.github.com/assets/907841/302948/fe806a2a-9617-11e2-9cd0-c5851a58385e.png)

The number of shown lines should maybe be configurable, or maybe a ratio of the
overall height of the screen. An alternative could be to center the line with the match to
the middle, but I wonder whether that might become too "jumpy" when searching through
a file. So I think it's more wise to just make sure that above and below the found match
at least N lines are shown. Where N is somewhere around 2-3.

(See also the -C cmd line option of grep in linux)

**Comment by brianlheim** [comment]
Closing as stale/lack of interest.
