### ISSUE TITLE
Add optional port argument to /notify and async commands

### ISSUE THREAD

**Issue by jamshark70** [supercollider/supercollider#801]
Server node notifications are not useful for clients (such as pure data) where the sending port to scsynth is not known (which makes it impossible to configure the OSC receiver to listen on the sending port). For such clients, it would be useful to tell scsynth, "Ignore the port I'm sending from; I'm listening on this port so please send the reply here."

There is another request on file for sending arbitrary OSC to arbitrary addresses. IMO that request is too complex and the gain is too limited (and it may not solve this issue anyway). So I'm logging this as a separate issue.

E.g., `/notify 1 57021` or `/b_allocRead ... completion_message port`

I'm not convinced it would be necessary to add an IP argument. I tend to think, if you want to issue a buffer-read command on one client, but notify a different client on another machine that the buffer is ready, then it would make more sense to rethink the approach as that's a bit nonsensical.

**Comment by defaultxr** [comment]
Hi, I'd just like to say that adding an optional port to /notify would allow for things like non-realtime analysis. For example, running Amplitude.ar on a sound file or finding onsets with Coyote.kr. I'm working on functions to automatically split up sound files based on onsets and it would be really awesome to be able to do it faster than real time. This is currently not possible, as there is no way (as far as I'm aware) to direct SendReply or SendTrig's messages to sclang when they're running on a NRT server instance.

If I get a vote, it would be to add the optional port to /notify just so this is possible.
