### ISSUE TITLE
Drag-and-drop broken on windows with 'alwaysOnTop' enabled

### ISSUE THREAD

**Issue by txmod** [supercollider/supercollider#812]
I'm using SC 3.6.3 with Qt on OS X 10.7.4.
If a window is alwaysOnTop then dragging to a DragSink and DragBoth doesn't work.

Test code:
(
// Window 1 - window is alwaysOnTop
w = Window.new("AlwaysOnTop, dragging to DragBoth or DragSink is broken", Rect(10, 700, 500, 300)).front;
w.alwaysOnTop_(true);

t = StaticText(w, Rect(10, 10, 100, 20));
t.string = "DragBoth";
a = DragBoth(w, Rect(120, 10, 150, 20)).align_(\center).background_(Color.rand);
a.object = 999.rand;

t = StaticText(w, Rect(10, 40, 100, 20));
t.string = "DragSource";
b = DragSource(w, Rect(120, 40, 150, 20)).align_(\center).background_(Color.rand);
b.object=999.rand;

t = StaticText(w, Rect(10, 70, 100, 20));
t.string = "DragSink";
c = DragSink(w, Rect(120, 70, 150, 20)).align_(\center).background_(Color.rand);
c.object=999.rand;

// Window 2 - normal window
w = Window.new("Normal window, dragging works ok", Rect(610, 700, 500, 300)).front;

t = StaticText(w, Rect(10, 10, 100, 20));
t.string = "DragBoth";
a = DragBoth(w, Rect(120, 10, 150, 20)).align_(\center).background_(Color.rand);
a.object = 999.rand;

t = StaticText(w, Rect(10, 40, 100, 20));
t.string = "DragSource";
b = DragSource(w, Rect(120, 40, 150, 20)).align_(\center).background_(Color.rand);
b.object=999.rand;

t = StaticText(w, Rect(10, 70, 100, 20));
t.string = "DragSink";
c = DragSink(w, Rect(120, 70, 150, 20)).align_(\center).background_(Color.rand);
c.object=999.rand;
)

**Comment by adcxyz** [comment]
works here, current 3.7a debug, 10.10.1.

**Comment by scztt** [comment]
thx for testing @adcxyz - appears fixed for me too. closing.
