### ISSUE TITLE
Return key before closing bracket: empty line is not always appropriate

### ISSUE THREAD

**Issue by jamshark70** [supercollider/supercollider#814]
I understand the point of inserting an empty line if you hit return when the cursor is just before a closing bracket, e.g.

    Plazy {}

If the cursor is between the brackets when you hit return, it does make sense to have the empty space:

    Plazy {
    
    }

But, suppose I've written an argument list on one line, and for readability, I want to push them onto separate lines, for instance:

    Env(#[ ... blah blah blah blah ... ], #[ ... blah blah blah ... ])

-->

    Env(
    	#[ ... blah blah blah blah ... ],
    	#[ ... blah blah blah ... ]
    )

But instead, I get:

    Env(
    	#[ ... blah blah blah blah ... ],
    	#[ ... blah blah blah ... ]
    	
    )

The difference between these two cases is that, in the second, the cursor is between two closing brackets. Here, it's perhaps a matter of taste, but I think it may be reasonable for the editor not to assume that you want to open up space. I.e., cursor between `{}`, then sure, if you hit return there, almost certainly you want to put something inside. Cursor between `])`, it's not so certain. I find I do the latter a fair amount, and the empty line is an annoyance pretty much every time.

**Comment by scztt** [comment]
Still a bug, still annoying me on a daily basis. I can look at it.
