### ISSUE TITLE
doneAction in RecordBuf doesn't work

### ISSUE THREAD

**Issue by jleben** [supercollider/supercollider#82]
[Issue migrated from SourceForge | ID: 2629222 | Submitted by 'jrhb']
[http://sourceforge.net/support/tracker.php?aid=2629222]

// synth is never freed:
(
// allocate a Buffer
s = Server.local;
b = Buffer.alloc(s, 44100 * 4.0, 1); // a four second 1 channel Buffer
)

// record for four seconds
(
SynthDef("help-RecordBuf",{ arg out=0,bufnum=0;
var formant;
formant = Formant.ar(XLine.kr(400,1000, 4), 2000, 800, 0.125);
RecordBuf.ar(formant, bufnum, doneAction: 2);
}).play(s,[\out, 0, \bufnum, b]);
)

**Comment by scztt** [comment]
Closing, this seems fixed for all the cases I can think of.
