### ISSUE TITLE
Library directory name should not be hardcoded.

### ISSUE THREAD

**Issue by karllinden** [supercollider/supercollider#824]
Hi!

In Gentoo Linux there is a feature (called multilib-strict) that requires packages to install into the library directory for the ABI of the current library; "lib32" for 32 bit libraries and likewise for 64 bit ones.

In the build system the library directory names are hardcoded (set to "lib") which is not very optimal. I suggest implementing an option that can be passed to CMake setting the name of, or, the path to the library directory.

Thanks in advance,
Karl

**Comment by brianlheim** [comment]
Closing as stale, please submit a PR if you are still interested in having this fixed.
