### ISSUE TITLE
linux - open/save panel : use native panels

### ISSUE THREAD

**Issue by miguel-negrao** [supercollider/supercollider#826]
Would it be possible to the use the native panels in for the open /save dialog windows on linux ? The panel presented by the IDE is very basic and painful to navigate in ubuntu 13.04. It doesn't display the harddrives, the favorites, etc.

**Comment by brianlheim** [comment]
Pinging. @miguel-negrao is this still an issue?

**Comment by miguel-negrao** [comment]
I'm not sure in master as I don't build in a while, but on my last build from a couple of months ago which reports using Qt 5.6.1, it is still an issue in gnome 3.20.2.

**Comment by gusano** [comment]
@brianlheim This was reported as working on other linux wm than Gnome (KDE) in 2013, I just tested on LXDE and XFCE and it also works there so closing this as it's either a Gnome or a Qt issue.
cc @miguel-negrao
