### ISSUE TITLE
ide - OSC in out indicators

### ISSUE THREAD

**Issue by miguel-negrao** [supercollider/supercollider#828]
It would be quite nice to have indicators in the bottom bar, perhaps to the right or left of the server widgets that would light up whenever there is incoming or outgoing osc to sclang. I'm thnking of just two squares, perhaps one green one red.
   I would say by default server traffic would be ignored, but right clicking on the indicator could turn on checking server traffic. This would really help immensilly troubleshooting osc communication.  I routinelly have to connect a tablet with supercollider and there are many points of failure. With these indicators one could immediatelly see if supercollider is receiving/sending something or not on OSC.

**Comment by brianlheim** [comment]
Closing as stale/lack of interest.
