### ISSUE TITLE
QListView:items_ can crash sclang

### ISSUE THREAD

**Issue by jamshark70** [supercollider/supercollider#835]
While researching a strange crash in the class browser, I found that the crash can be reproduced without using the class browser at all.

This ECM mimics what happens when a method search for "depend" is executed in the class browser. At first, the methodView is populated with a list of Object's methods. The method search replaces those items with the search result (quoted as a compile string).

    x = Object.methods.collect { |m| m.name };
    
    y = ListView(nil, Rect(800, 100, 240, 260)); y.front;
    y.items = x;
    
    // crash here
    y.items = [ "addAsDependantOf (MixerChannel)", "addDependant (Nil)", "addDependant (Object)", "addDependantMC (MixerChannel)", "dependants (Nil)", "dependants (Object)", "dependantsDictionary (Meta_Object)", "dependencies (Quark)", "getDependencies (Quark)", "independent (Penvir)", "independent_ (Penvir)", "releaseDependants (Object)", "releaseFromDependencies (Object)", "removeAsDependantOf (MixerChannel)", "removeDependant (Nil)", "removeDependant (Object)", "removeDependantMC (MixerChannel)" ];

**Comment by telephon** [comment]
Works fine now. 
@jamshark70 can you still reproduce?
