### ISSUE TITLE
Several MIDI issues in Windows

### ISSUE THREAD

**Issue by jleben** [supercollider/supercollider#84]
[Issue migrated from SourceForge | ID: 2686455 | Submitted by 'jamshark70']
[http://sourceforge.net/support/tracker.php?aid=2686455]

1. The initMIDI function incorrectly increments the counter for input devices when it sees an output device.

    for( int i = 0; i < nbDev ; ++i ) {
      const PmDeviceInfo* devInfo = Pm_GetDeviceInfo(i);
      if( devInfo->input )
      {
        gNumMIDIInPorts++;
        gMidiInputIndexToPmDevIndex[inIndex++] = i;
        gMidiPmDevIndexToInputIndex[i] = inIndex;
      }
      if( devInfo->output )
      {

        gNumMIDIInPorts++;// ***** << oops

        gMidiOutputIndexToPmDevIndex[outIndex++] = i;
        gMidiPmDevIndexToOutputIndex[i] = outIndex;
      }
    }

The upshot of this bug is that the MIDI client destinations array never gets populated so MIDI output is totally impossible at present.

2. MIDI input appears not to connect properly.

MIDIClient.init(6, 6);
MIDIClient.sources.do({ |src, i| MIDIIn.connect(i, i) });

MIDIIn.noteOn = { |... args| args.postln };

Now play on a MIDI keyboard connected to the system. In my installation, nothing printed. (This could potentially be due to bios or chipset problems -- since it isn't my machine, I'm not at liberty to muck around with that.)

At least, before the 3.3 Windows release, it should be confirmed that this simple example works.

3. The prDisposeMIDIClient function for windows simply returns a "failed" error code. This produces a "primitive failed" error in the post window when recompiling the library. That will confuse new users.

Maybe the fix is to use try {  } in the UI.registerForShutdown function. Shutdown actions should not throw errors.

4. Some MIDI primitives are not implemented yet: sendsysex, prSendSysex, sendmidi, prSendMIDIOut.

**Comment by bagong** [comment]
Needs testing

**Comment by llloret** [comment]
As far as I can see, all MIDI known issues under Windows should be working with 3.7.2.

**Comment by bagong** [comment]
Thanks, Luis!

**Comment by ne1001en** [comment]
Luis - no this is not working on 3.7.2 - I installed latest version 3.7.2 and the midi bug is persistent. This makes the code not portable across windows-linux machines.

**Comment by llloret** [comment]
Hi, @ne1001en, thanks for the feedback. Can you specify exactly what problem are you having? What windows version? What device? Any information that you can provide will be useful.

**Comment by ne1001en** [comment]
Hi @llloret , yesterday I experienced issues adding +1 to uid solved it, but today I am unable to reproduce the issue, it seems that it really works. I use Windows 7 + Novation Launchpad. Maybe I did a mistake in my piece, I will let you know if it reoccurs. Thank you.

**Comment by llloret** [comment]
@ne1001en, great! Thanks for the update, and let me know if you experience
any issues. We want to really make sure that MIDI works 100% on Windows.
