### ISSUE TITLE
OSCresponderNode SCUserView refresh crashes

### ISSUE THREAD

**Issue by jleben** [supercollider/supercollider#85]
[Issue migrated from SourceForge | ID: 2728998 | Submitted by 'nobody']
[http://sourceforge.net/support/tracker.php?aid=2728998]

Closing the SCWindow while OSCresponderNode is continually calling refresh method on SCUserView intermittently causes SC to crash.
 
SC version: Version 2008-10-29 (Revision 7885)
OS X 10.5.6 PowerPC G4
crash report attached.
Sample code:
(
SynthDef("InTrig",{|inbus=0,outbus=0,gain = 1.0|
var amp,in;
in = SoundIn.ar(inbus)*gain;
amp = Amplitude.kr(in);
SendTrig.kr(Impulse.kr(10),76,amp);
Out.ar(outbus,in);
}).send(s);
)

(
var win,led;
var ampSynth,ampResponder;
var ledColor = Color.red;
win = SCWindow("audio input",Rect(100,100,300,200)).front;
win.onClose_({
ampResponder.remove;
ampSynth.free;
});
led = SCUserView(win,Rect(10,10,20,20));
led.drawFunc_({
Pen.fillColor = ledColor;
Pen.fillOval(Rect(10,10,10,10));
});
ampResponder = OSCresponderNode(s.addr,'/tr',{|t,r,msg|
{
ledColor = Color.green.alpha_(1-(msg[3].ampdb.abs * 0.01));
led.refresh;
}.defer;
}).add;

ampSynth = Synth("InTrig");

)

**Comment by scztt** [comment]
Limited to old version, closing.
