### ISSUE TITLE
sclang crashes on evaluation of private method (due to bug in keysValuesArrayDo)

### ISSUE THREAD

**Issue by miczac** [supercollider/supercollider#852]
tested on OS X 10.6.8 & SC v3.4.4 - v3.6.5:

evaluating
o = [Event.prNew]
kills sclang.
Same applies to some other objects, some like Array apparently don't crash.

see also:
http://new-supercollider-mailing-lists-forums-use-these.2681727.n2.nabble.com/sclang-perishes-tp7598889p7598908.html

**Comment by scztt** [comment]
This occurs with Dictionary.prNew and all subclasses, but not Set.prNew, nor any other's I could find.

**Comment by scztt** [comment]
This looks like it's actually a bug in the implementation of keysValuesArrayDo (PyrInterpreter3.cpp:1710). In the example case, the Event's array object is nil - that value normally gets initialized in initSet, which isn't getting called. keysValuesArrayDo naively tries to get this slot as an object, and barfs when it's nil. You can generate the same crash by doing:
`().keysValuesArrayDo();`
`e = (); e.array = nil; e.keysValuesDo({});`

@miczac's original calling of prNew is actually NOT a problem, and seems to do everything right from the perspective of the interpreter - it just doesn't hit the standard init method, which reveals this bug. So, uh, @miczac - you can workaround in your code by manually calling initSet after you do your prNew.

I suspect the correct fix here is to bail with an error - Number-forSeries does this in comparable cases. I can submit a pr.

**Comment by scztt** [comment]
There is also no protection against overriding keysValuesArrayDo in a subclass - similar problem to the switch bug. It will, at best, do nothing, and possibly blow up. We need to make overriding all of the "special bytecode" methods a compile error.

**Comment by miczac** [comment]
the point I was trying to make was that the interpreter shouldn't crash but throw an error.
I stumbled upon this when I was knowingly inappropriately playing with the code generated by .writeArchive (writeArchive should say 'no user serviceable parts in there ;) )

**Comment by vivid-synth** [comment]
I can still repro this (although it doesn't seem highest priority)

**Comment by brianlheim** [comment]
Sorry this took so long @miczac! :)
