### ISSUE TITLE
Windows: No 64-bit version

### ISSUE THREAD

**Issue by bagong** [supercollider/supercollider#853]
Since mingwbuilds brought out GCC4.8 & and Qt built with that compiler, it is not difficult anymore to assemble a build-environment, that allows building a 64 bit version. But SC still needs some adjustments.

**Comment by scztt** [comment]
Should be fixed by #1387. @maedoc - if you're still around, want to try building that branch, helping out with the remaining cleanup that's required?

**Comment by maedoc** [comment]
Sorry don't use Windows anymore, so I can't build this anytime soon.

**Comment by bagong** [comment]
SC/SC-IDE can now be build on VS 12/2013 in a 64-bit version (no sc3-plugins and supernova support yet, though). Build-instructions (and the required changes) are not in master yet but should make the move soon. For now look in the branch `winport` in htpps://github.com/bagong/supercollider.git
