### ISSUE TITLE
No documentation for thisMethod

### ISSUE THREAD

**Issue by blacksound** [supercollider/supercollider#871]
I think all the pseudo variables should, when searched for in help, open a "Pseudo variables" help document.

When hilighting any of these:
thisMethod
thisFunction

neither ctrl - D, nor ctrl - I shows anything.

thisProcess
thisThread
points to help files for Process and Thread.

**Comment by scztt** [comment]
thisProcess, thisThread, thisFunction all currently show proper help. thisMethod does not  - that should be fixed.

**Comment by snappizz** [comment]
Fixed in #2632.
