### ISSUE TITLE
MCLDFilter UGens fail unit tests

### ISSUE THREAD

**Issue by telephon** [supercollider/supercollider#886]
There were failures:
a TestFilterUGens:test_time_invariance - Friction.ar is time invariant when delayed by 1 sample(s).
4184 of 4410 items in array failed to match. Displaying arrays from index of first failure (226) onwards:
FloatArray[ nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, ...etc...
! = 
0

a TestFilterUGens:test_time_invariance - Friction.ar is time invariant when delayed by 64 sample(s).
4121 of 4410 items in array failed to match. Displaying arrays from index of first failure (289) onwards:
FloatArray[ nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, ...etc...
! = 
0

**Comment by scztt** [comment]
Been around for a while, we can skip for 3.7.

**Comment by snappizz** [comment]
Migrating to https://github.com/supercollider/sc3-plugins/issues/116
