### ISSUE TITLE
Some bhob ugens fail in unit test

### ISSUE THREAD

**Issue by telephon** [supercollider/supercollider#887]
a TestFilterUGens:test_time_invariance - NestedAllpassC.ar is time invariant when delayed by 1 sample(s).
16 of 4410 items in array failed to match. Displaying arrays from index of first failure (1587) onwards:
FloatArray[ -0.23038358986378, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0...etc...
! = 
0

a TestFilterUGens:test_time_invariance - NestedAllpassC.ar is time invariant when delayed by 64 sample(s).
16 of 4410 items in array failed to match. Displaying arrays from index of first failure (1650) onwards:
FloatArray[ -0.23038358986378, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0...etc...
! = 
0

a TestFilterUGens:test_time_invariance - DoubleNestedAllpassL.ar is time invariant when delayed by 64 sample(s).
175 of 4410 items in array failed to match. Displaying arrays from index of first failure (2006) onwards:
FloatArray[ -9.1525726020336e-07, -2.7474015951157e-06, 3.6619603633881e-06, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...etc...
! = 
0

a TestFilterUGens:test_time_invariance - DoubleNestedAllpassC.ar is time invariant when delayed by 1 sample(s).
907 of 4410 items in array failed to match. Displaying arrays from index of first failure (972) onwards:
FloatArray[ 0.050404109060764, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0...etc...
! = 
0

a TestFilterUGens:test_time_invariance - DoubleNestedAllpassC.ar is time invariant when delayed by 64 sample(s).
911 of 4410 items in array failed to match. Displaying arrays from index of first failure (1034) onwards:
FloatArray[ -0.0048005161806941, 0.050404109060764, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0...etc...
! = 
0

a TestFilterUGens:test_time_invariance - Streson.ar is time invariant when delayed by 1 sample(s).
514 of 4410 items in array failed to match. Displaying arrays from index of first failure (132) onwards:
FloatArray[ -5.3718686103821e-06, 6.556510925293e-07, -5.9604644775391e-08, 7.4505805969238e-09, -9.3132257461548e-10, 1.1641532182693e-10, -1.4551915228367e-11, 1.3642420526594e-12, -1.7053025658242e-13, 1.4210854715202e-14, -1.7763568394003e-15, 2.2204460492503e-16, -2.7755575615629e-17, 2.6020852139652e-18, -3.2526065174565e-19, 4.0657581468206e-20, -5.0821976835258e-21, 6.3527471044073e-22, -7.9409338805091e-23, 8.2718061255303e-24, -8.2718061255303e-25, 1.0339757656913e-25, -9.6935228033558e-27, 1.2116...etc...
! = 
0

**Comment by scztt** [comment]
Been around for a while, we can skip for 3.7.

**Comment by snappizz** [comment]
Migrating to https://github.com/supercollider/sc3-plugins/issues/117
