### ISSUE TITLE
QEnvelopeView.curves = { this.nonimpl( "curves" )}

### ISSUE THREAD

**Issue by rd--** [supercollider/supercollider#895]
This was mentioned here:

http://permalink.gmane.org/gmane.comp.audio.supercollider.devel/49269

I'd also use this if implemented.

Best,
R

PS. The -1 in that post seems wrong to me, rather:

~w_getEnv = {
    arg e;
    var t,l,c;
    #t,l = e.value;
    /\* c = e.curves; */
    c = \lin;
    Env(l,t.differentiate.drop(1),c);
};

**Comment by telephon** [comment]
Should we replace the current one with this?
