### ISSUE TITLE
Dialog -> select folder?

### ISSUE THREAD

**Issue by rd--** [supercollider/supercollider#906]
This was raised on sc-users (23 Feb 2012).

http://permalink.gmane.org/gmane.comp.audio.supercollider.user/83625

I'd also appreciate this (ie. a 'canChooseDirectories' argument).

I don't think it's implemented anywhere else (searching help for Directory didn't locate anything).

Thanks,
RD

**Comment by jamshark70** [comment]
Old issue, happened to find while looking for something else.

We should change this to a documentation issue. It has actually been supported to select folders directly from a file dialog, for a long time, but the help files currently make it next to impossible to find the answer unless you already know where to look.

```
FileDialog({ ... ok ... }, { ... cancel ... },
	fileMode: 2,  // directory
	acceptMode: 0  // open (1 = save)
)
```

The documentation problem is that users will go to `Dialog` help first. There is no link anywhere in this help file to `FileDialog`! There should at least be a sentence in Dialog help pointing the user to FileDialog for choosing directories.

**Comment by telephon** [comment]
Looking at the comments in the source
```
	/**
		fileMode:
			QFileDialog::AnyFile		0	The name of a file, whether it exists or not.
			QFileDialog::ExistingFile	1	The name of a single existing file.
			QFileDialog::Directory		2	The name of a directory. Both files and directories are displayed.
			QFileDialog::ExistingFiles	3	The names of zero or more existing files.
		acceptMode:
			QFileDialog::AcceptOpen		0
			QFileDialog::AcceptSave		1

		stripResult:
		   true: okFunc(path1, path2, path3)
		   false: okFunc(paths)
		**/
```

 I failed to understand how in the file mode 3, a default path can be specified.

**Comment by jamshark70** [comment]
This issue is not about specifying a default path -- that's #874. That seems to be a bigger problem.

This one is about choosing a folder rather than a file. There's no need to delay a fix for this issue while waiting for the other.

We could add a convenience method to Dialog as well as fixing the documentation.

**Comment by rd--** [comment]
> FileDialog({ ... ok ... }, { ... cancel ... },
>     fileMode: 2,  // directory
>     acceptMode: 0  // open (1 = save)
> )

cool - thanks kindly - i'd still not located it! - rd
