### ISSUE TITLE
 Qt menu's with > 10 items get a scrollbar, and at the same time the view doesn't get wider

### ISSUE THREAD

**Issue by miguel-negrao** [supercollider/supercollider#915]
Cocoa:
![](https://f.cloud.github.com/assets/472356/811191/9ee1fabc-eecc-11e2-8923-c911fe9a616f.png)
Qt:
![](https://f.cloud.github.com/assets/382777/806566/33fdaa14-ee3d-11e2-8559-ee074b3538b7.png)

**Comment by jamshark70** [comment]
In Linux, the upgrade to Qt5 has fixed this issue "for free."

Can other people test OSX and Windows?

```
w = Window("popup test", Rect(800, 200, 200, 120));
p = PopUpMenu(w, Rect(2, 2, 50, 20))
.items_(Array.fill(10, { |i| "Very long item name" + i }));
w.front;
```

On my system, the widget is 50 pixels wide and shows only "Very." Clicking on the widget brings up a box that's much wider, and displays the complete strings.

**Comment by telephon** [comment]
Works here on OS X 10.10. I suppose that counts?
