### ISSUE TITLE
acceptsMouseOver and toolTip

### ISSUE THREAD

**Issue by nuss** [supercollider/supercollider#924]
I have recognized that toolTips aren't displayed if the window isn't the front most one. So I tried setting acceptsMouseOver explicitely to true. But that doesn't seem to work either - neither setting acceptsMouseOver for the whole window nor setting it for the regarding element that contains the toolTip seems to work if the window isn't the front most one.
I have had a look at other programs and it seems to be common practise that tooltips are being displayed even if the window isn't the front most one. Could this be implemented that way in Qt gui as well resp. make toolTips work like that if acceptsMouseOver has been set to true?

**Comment by scztt** [comment]
This appears to be a qt5 limitation. But, it might be possible to work around, if inactive windows still receive mouseover events with tracking on.....

**Comment by nuss** [comment]
Unfortunately my knowledge about Qt is still very limited, as well as my time for learning more about it... (at least for now). However, it seems to be common in many desktop applications and I think it would be usefull. Thanks for your attention ;)

**Comment by brianlheim** [comment]
Closing as stale/lack of interest.
