### ISSUE TITLE
Programmatically opening help files bug on linux

### ISSUE THREAD

**Issue by gusano** [supercollider/supercollider#931]
#### Reproduction

`"SinOsc".help`

#### What happens

- if Help browser is not already opened, nothing happens
- if Help browser is opened, the correct help file is displayed but the Help browser does not get the focus

#### Expected behavior

Help browser should open (if not already) and get the focus.

**Comment by scztt** [comment]
This is working in current builds. Closing.

**Comment by gusano** [comment]
@scztt This is still not working on my linux machine so I'm reopening this.
Is it working on OSX and Windows?

My setup:
- 3.18.6-1-ARCH
- `db05db8` (March 30th)

**Comment by crucialfelix** [comment]
works on OSX for me

**Comment by gusano** [comment]
@crucialfelix Thanks.
It would be nice to know if that works on other linux ditros or if it's archlinux-only.

**Comment by scztt** [comment]
@gusano - I just realized that there may be some confusion amongst us about this bug.... When you say help isn't opening, do you mean the IDE help docklet, or the sclang Help browser window? If I'm running SC from the ide and I DON'T have the Help docklet open, `"SinOsc".help` does not expose the help browser, or shift focus to it if it's already visible. If I'm running standalone sclang, `"SinOsc".help` works as expected.

I just added a PR that deals with the IDE issue - want to test?

**Comment by gusano** [comment]
@scztt Yes, #1529 fixes the current issue :+1:
