### ISSUE TITLE
filter request

### ISSUE THREAD

**Issue by adam4** [supercollider/supercollider#944]
some 4 pole filters, and perhaps a multimode - i was thinking a wrapper round BPF RLPF & RHPF since they have the same args iirc

like MMF(freq,q,mul,add,filter type) have been trying to do it myself but no luck (or skill ;) so far

**Comment by snappizz** [comment]
Be sure to check out MoogFF, and in sc3-plugins there's also MoogVCF and DFM1.

I'm definitely open to cooler filters, which can certainly help with making SC appeal to electronic music producers. We'll probably go the route of introducing in sc3-plugins and then migrating to core. I have some expertise in virtual analog filter design, so I'll probably be able to contribute something in the future.

However, I'm going to have to close this in the absence of a more specific proposal.
