### ISSUE TITLE
Feature request: move method for Array

### ISSUE THREAD

**Issue by totalgee** [supercollider/supercollider#956]
After a discussion on sc-users ([started by Perdo](http://new-supercollider-mailing-lists-forums-use-these.2681727.n2.nabble.com/move-item-in-Array-td7602932.html)), it seems reasonable to request a move method for ArrayedCollection.

```
a = [0, 2, 4, 6, 8]

// Perdo wanted: a.move(4, 1) // move(<index>, <destination index>)

// Right now, you can do it this way:
a.insert(1, a.removeAt(4))
a // -> [0, 8, 2, 4, 6]
```

But it would be handy to have a native method to do the move directly (like swap).

**Comment by brianlheim** [comment]
Done: https://github.com/supercollider/supercollider/commit/22c9712d2cb21e9c0d3c55f5b39002a944d68231

**Comment by totalgee** [comment]
Great, thanks!  I see this was done three years ago...  (-;
