### ISSUE TITLE
SuperCollider won't build with Xcode 5

### ISSUE THREAD

**Issue by lloeki** [supercollider/supercollider#958]
Xcode 5 drops the 10.7 SDK, which makes building SuperCollider on 10.8 with Xcode 5 (and soon 10.9 altogether) impossible because the Wiimote bluetooth code uses an obsolete API.

## Stop-gap solution:

downgrade to Xcode 4.6 by removing Xcode 5 and downloading Xcode 4.6 from developer.apple.com/downloads, while taking great care not to upgrade it again by accident via the App Store.

## Long term possible solutions:

- upgrade the wiimote code to use a non-obsolete API.
- make the wiimote code optional with a cmake/build flag.

**Comment by telephon** [comment]
On OS 10.10, SC builds seamlessly with 6.1.1
