### ISSUE TITLE
README_OS_X.txt is overly complex

### ISSUE THREAD

**Issue by lloeki** [supercollider/supercollider#960]
To build on OSX, one merely needs to

- install Xcode up to 4.6 (not 5, because it drops the 10.7 SDK)
- install the CTL (command line tools, e.g via preferences)
- run `cmake` as follows:

```
mkdir build && cd build
cmake -DCMAKE_OSX_SYSROOT=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.7.sdk/ -DCMAKE_OSX_DEPLOYMENT_TARGET=10.7 -DCMAKE_BUILD_TYPE="Release" ..
make    # install if you wish
```

**Comment by scztt** [comment]
I just rewrote the OS X build instructions. They're about as simple as they can be, without taking shortcuts that will get people stuck..... Closing.
