### ISSUE TITLE
Rendering issue on edge of help browser

### ISSUE THREAD

**Issue by muellmusik** [supercollider/supercollider#966]
Happens after scrolling, disappears when focus is lost. OSX 10.8, but don't know if it's limited to that.

![help browser](https://f.cloud.github.com/assets/1315053/1275344/eee74f24-2df3-11e3-878b-9000e6259cbb.png)

**Comment by brianlheim** [comment]
Ping. Can anyone recreate this? I can't on macOS 10.11

**Comment by telephon** [comment]
I can't either.

**Comment by brianlheim** [comment]
This is from 3 years ago and we've gone through updates in Qt since then. With no other comments/details, I'm closing for now.
