### ISSUE TITLE
NamedControl.new() returns single-element array of Lags when it should return a Lag

### ISSUE THREAD

**Issue by totalgee** [supercollider/supercollider#973]
See [this thread](http://new-supercollider-mailing-lists-forums-use-these.2681727.n2.nabble.com/Bug-with-Control-lag-and-Pan2-td7603440.html) for more details.  Basically, when using NamedControls with a single lag value in a SynthDef, the Control unexpectedly returns an array.

e.g.

```sc
{NamedControl.new('freq', 440, \control).postln}.asSynthDef; ""
// --> an OutputProxy
{NamedControl.new('freq', 440, \control, 1).postln}.asSynthDef; ""
// --> [ a Lag ]  // (why return an Array?)
```

This causes confusion and "special case" handling when using NamedControls, for example in the following case with Pan2:

```sc
{ var sig = Pan2.ar(SinOsc.ar(440, 0, 0.1), \pan.kr(0, 0.1)); sig.poll(1) }.play
// --> UGen Array [0]: 0.00442991
// --> UGen Array [0]: 0.00442991
```
but we would expect a result like this (note we need to add `[0]` to the Control, to get it out of the unexpected array:

```sc
{ var sig = Pan2.ar(SinOsc.ar(440, 0, 0.1), \pan.kr(0, 0.1)[0]); sig.poll(1) }.play
// --> UGen Array [0]: 0.00442991
// --> UGen Array [1]: 0.00442991
```

**Comment by scztt** [comment]
pr was merged, so I think it's okay to close this.
