### ISSUE TITLE
Regexp replace doesn't support escaped sequences (but regexp find does)

### ISSUE THREAD

**Issue by jamshark70** [supercollider/supercollider#979]
Just tried to do a regexp find/replace like this:

Find: `\tb\.`
Replace: `\t~`

The search behaves as expected: it finds places where "b." immediately follows a tab character. But after replacing, the tab disappears and turns into `\t` (including the backslash). I would have expected that if I wanted that result, I would have to write the replace string as `\\t~`.

I could work around this limitation by:

Find: `(\t)b\.`
Replace: `\1~`

But I don't think I should have to do that. It's reasonable to expect a regexp replace string to insert a backslash into the document only if the backslash has been escaped -- `\\` rather than `\` -- since a single backslash should be an escape character.

Low priority since a workaround exists.

**Comment by brianlheim** [comment]
Closing as stale/lack of interest.
