### ISSUE TITLE
scrolling scide is extremely slow on osx

### ISSUE THREAD

**Issue by timblechmann** [supercollider/supercollider#984]
scrolling the code editor is extremely slow on osx. profiling indicates that most of the CPU time is spent in `QPlainTextEdit::paintEvent(event);` which is called from `GenericCodeEditor::paintEvent`.

since qt-4.8 is only a legacy project, it is unlikely that the sc devs can fix this without migrating to qt-5

**Comment by scztt** [comment]
Migrated to qt5, this is no longer an issue.
