### ISSUE TITLE
scrolling help file on OSX with a trackpad adds strange and irritating "physical" effect

### ISSUE THREAD

**Issue by LFSaw** [supercollider/supercollider#991]
If I scroll a helpfile in the helpfile browser with the MacBook trackpad (not with the mouse!), a strange and irritating physical effect (inertia, friction, speedup). As this is not the same behaviour as with e.g. the mouse or in native osx applications, and it sometimes takes about 3 seconds to settle after releasing, it is extremely irritating.
I guess that it is connected with this bug:

https://bugreports.qt-project.org/browse/QTBUG-16684

which I cannot figure out if it is fixed already (filed in 2011)

**Comment by scztt** [comment]
Retests after qt5 merge? This should be fixed. If you need a build:
http://supercollider.s3.amazonaws.com/builds/supercollider/supercollider/osx/master-latest.html

**Comment by brianlheim** [comment]
Closing; no longer an issue.
